### ISSUE TITLE
Restrict access to manifests for packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#100]
Some software vendors will want to manage releases for manifests of their software.

**Comment by denelon** [comment]
Some OSS producers also wish to manage releases for manifests and installers for their software.

**Comment by denelon** [comment]
https://gist.github.com/denelon/0285ade55410f118b92d03e883a24c5e

**Comment by ocdtrekkie** [comment]
Why was WinGet 1.0 released/announced without completing this incredibly security-critical goal?

**Comment by denelon** [comment]
The technical implementation for this feature is complete. We are now working on the business process for identifying verified developers. The implementation is similar to the waivers for validation stored in a .version file. The ownership metadata will be recorded in a .package file.

**Comment by slonopotamus** [comment]
> The technical implementation for this feature is complete.

After re-reading this whole issue six times, I still fail to understand how this feature was implemented and how to use it. Could you please give a link to some docs or whatever?

**Comment by denelon** [comment]
We are still working on the business process for this feature. Once that has been completed, the technical implementation here will be further documented.

The simple overview of the technical implementation is we will have a file in the directory (either publisher, or package) identifying the verified developers GitHub alias. When a PR is submitted by anyone other than the verified developer, they will be informed. If the verified developer submits a PR, the validation will continue down the normal process.

**Comment by ocdtrekkie** [comment]
I'm still *deeply* concerned this thing is actually on real Windows PCs that actual people use prior to this being implemented.

**Comment by russellbanks** [comment]
Just a thought, what about scenarios like LF/CRLF line ending enforcement? We would need to ensure that the pull request pipeline fails if line endings are incorrect first, as we wouldn't be able to normalise the manifest at a later stage if we are restricted in changing the manifest for the package.

**Comment by thomaseizinger** [comment]
> the technical implementation here will be further documented.

Has this been done somewhere?
