### ISSUE TITLE
[Package Request]: Microsoft.SQLServerManagementStudio - add automation for rolling update URL

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#100111]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:   https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms
Publisher:  Microsoft
Package Name:  SQLServerManagementStudio
Description: SQL Server Management Studio - EN-US rolling update. This URL will always point at the most recent SQL Management Studio instaler for EN-US language.
Package Version: (this URL is not for a fixed version, it is regularly updated to point to the most recent)
Installer URL:  https://aka.ms/ssmsfullsetup

**Please add a winget repository for automatic rolling update for Microsoft SQL Management Studio, EN-US edition, which is kept updated at the following short aka.ms URL:**

https://aka.ms/ssmsfullsetup

This URL is supposed to always point at the latest version of the installer and thus the Azure pipeline bots will detect automatically when the installer EXE file is changed/updated, and will automatically update the Winget manifests here.

So far i see that updates for SQL Management Studio are only published as manually-added pull requests, without update automation
https://github.com/microsoft/winget-pkgs/commits/master/manifests/m/Microsoft/SQLServerManagementStudio

I think that since this installer is for the English language, the installers for other languages will have to be defined separately, as they are currently.

**Comment by stephengillie** [comment]
The version of SSMS from WinGet's manifests appears to be the most recent version: 
```
Name                                   Id                                  Version Match         Source
-------------------------------------------------------------------------------------------------------
Microsoft SQL Server Management Studio Microsoft.SQLServerManagementStudio 19.0.2  Moniker: ssms winget
```
Internet search: 
![image](https://user-images.githubusercontent.com/114952565/226403333-7aedf019-90d8-4f9a-a772-f7fb2d09e371.png)

Does this InstallerUrl hold a newer version of SSMS?
> Installer URL: https://aka.ms/ssmsfullsetup

**Comment by R-Adrian** [comment]
> One issue with this is that using a vanity URL like the aka.ms link will cause previous versions to become unavailable when a new version is available as part of the automation

could wingetbot build that "previous versions list" by removing the HTTP redirect layers and keeping a record of the last URL in the redirect chain? (assuming that one will remain valid for the version, when anorher version is pushed to she short url?)

When it detects an updated file, can wingetbot push an additional "fixed" version of the package manifest?

currently the redirect chain goes like this:

```
---request begin---
GET /ssmsfullsetup HTTP/1.1
Host: aka.ms
User-Agent: Wget/1.21.2
Accept: */*
Accept-Encoding: identity
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Server: Kestrel
Location: https://go.microsoft.com/fwlink/?linkid=2226343
Request-Context: appId=cid-v1:9b037ab9-fa5a-4c09-81bd-41ffa859f01e
X-Response-Cache-Status: True
Expires: Mon, 20 Mar 2023 19:52:31 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 20 Mar 2023 19:52:31 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

---response end---
```

```
---request begin---
GET /fwlink/?linkid=2226343 HTTP/1.1
Host: go.microsoft.com
User-Agent: Wget/1.21.2
Accept: */*
Accept-Encoding: identity
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Server: Kestrel
Location: https://download.microsoft.com/download/9/f/8/9f8197f4-0f71-42a3-8717-b2817c77b820/SSMS-Setup-ENU.exe
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
X-Response-Cache-Status: True
Expires: Mon, 20 Mar 2023 19:52:31 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 20 Mar 2023 19:52:31 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

---response end---
```


```
---request begin---
GET /download/9/f/8/9f8197f4-0f71-42a3-8717-b2817c77b820/SSMS-Setup-ENU.exe HTTP/1.1
Host: download.microsoft.com
User-Agent: Wget/1.21.2
Accept: */*
Accept-Encoding: identity
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Accept-Ranges: bytes
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-blob-content-md5: tq7qy2qGXFooFmdTYOudog==
Last-Modified: Mon, 13 Mar 2023 18:04:01 GMT
ETag: "0x8DB23ED535AA330"
Content-Length: 659373600
Date: Mon, 20 Mar 2023 19:52:31 GMT
Connection: keep-alive

---response end---
```

**Comment by Matteo-T** [comment]
Hey guys, I'm on the SSMS Team.

I believe I know quite well when we publish it and when we want to make it available thru the many release channels. :)

I was only guilty of not doing this on a regular basis in the past (I may have done it a couple of times maybe).

Starting with SSMS 19.0.2, I've added the **automation** that generates the files and prepares the PR to the SSMS release process, so it's going to be a lot harder (read: impossible, unless there is a reason for us not to push it out to winget) to be out of date.

So, as long as I'm concerned:
- I'd like the SSMS Team to own the update of the winget files going forward
- There is no need for anybody to have winget to try and guess from the download page what to do
- Ultimately, close this issue

Let me know what you think.

**Comment by R-Adrian** [comment]
> Starting with SSMS 19.0.2, I've added the **automation** that generates the files and prepares the PR to the SSMS release process, so it's going to be a lot harder (read: impossible, unless there is a reason for us not to push it out to winget) to be out of date.
> 

thanks - i think that solves most of the automation side of things and i can close this issue.
