### ISSUE TITLE
[Update Request]: PointPlanck.FileBot 5.0.1

### ISSUE THREAD

**Issue by jeffwlawson** [microsoft/winget-pkgs#100394]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

PointPlanck.FileBot

### Package Version

5.0.1

### Please describe the changes you would like to see

There is a new release of PointPlanck.FileBot (5.0.1) available.

Download page url: https://www.filebot.net/#download
Installer url: https://get.filebot.net/filebot/FileBot_5.0.1/FileBot_5.0.1_x64.msi

**Comment by mdanish-kh** [comment]
Close with reason: Package merged in #100501;
