### ISSUE TITLE
[Update Request]: deprecate Microsoft.GitCredentialManagerCore

### ISSUE THREAD

**Issue by ldennington** [microsoft/winget-pkgs#100542]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

Microsoft.GitCredentialManagerCore

### Package Version

All (most recent is 2.0.785)

### Please describe the changes you would like to see

I'm not sure whether this capability exists, but if so I would like to request deprecation of the `Microsoft.GitCredentialManagerCore` package. The project is no longer publishing new releases to `winget`, but certain users are getting confused and downloading the outdated packages that are still available.

**Comment by mdanish-kh** [comment]
All versions have been removed so it's no longer possible to install GCM through WinGet.
