### ISSUE TITLE
Visual Studio Code alias "code"

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/winget-pkgs#10071]
On Linux, it's possible to install VS Code by typing `apt install code` which is the name of the package. Would it be possible to create an "alias" for VS Code to install it with a similar, short alias?

**Comment by denelon** [comment]
You might look at issue #3201 
@lszomoru has been driving the manifest for Visual Studio Code. He might want to let me know which issue is a duplicate.

**Comment by ItalyPaleAle** [comment]
Hi @denelon this seems to be a different issue. #3201 is about the user vs system installer of VS Code. I'm asking if it's possible to make an alias so installing VS Code with WinGet is not harder than it is on Linux, where one does only need to ask for the "code" package

**Comment by denelon** [comment]
@ItalyPaleAle yeah, I was just trying to find some of the related issues. I can't remember where the discussion is, but there has been some opinion about whether the moniker should be "code" or "vscode". That's why I tagged @lszomoru. 

We have some logic in "search" that is used to determine which package to install, or which packages to display.

**Comment by denelon** [comment]
I think this might be the one I was recalling: https://github.com/microsoft/winget-pkgs/discussions/277

**Comment by ItalyPaleAle** [comment]
I see, that's the one. I second the preference for "code" however so it's aligned with the experience on Linux (and it's simpler!)

**Comment by lszomoru** [comment]
@denelon, @ItalyPaleAle lost this issue in my notifications. I went over #277 and it looks like there is desire to have both `code` and `vscode` as monikers. It seems to be that the Moniker field does support a string array. @denelon, could you please confirm that? If so, I will update our publishing pipeline. Thanks!

**Comment by denelon** [comment]
@lszomoru correct, there can be only one "moniker", but there can be many tags.

If a moniker is unique to a single package (across configured sources), users can `winget install <moniker>` as the command to install or show the package.

If two packages have the same moniker, this behavior will not work, and the user will be forced to disambiguate. This is true across sources.
