### ISSUE TITLE
[Package Issue]: Posit.RStudio update not found with `winget upgrade`

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#100799]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

`winget upgrade` does not find an update of `Posit.RStudio` from [`PackageVersion: 2022.12.0+353`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Posit/RStudio/2022.12.0%2B353) to [`2023.03.0+386`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Posit/RStudio/2023.03.0+386). 

### Steps to reproduce

Install `Posit.RStudio 2022.12.0+353` e.g. with

```ps1
.\Tools\SandboxTest.ps1 .\manifests\p\Posit\RStudio\2022.12.0+353\ -prerelease
```

`winget upgrade` after install completes

### Actual behavior

`Posit.RStudio 2023.03.0+386` does not show up as an upgrade option (also not with the winget release version).

winget _does_ find and install the available upgrade, when the package is explicitly specified, i.e. with `winget upgrade Posit.RStudio`

### Expected behavior

`Posit.RStudio 2023.03.0+386` ought to show up as an upgrade option with `winget upgrade`

### Environment

```raw
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.2728
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0
```

### Screenshots and Logs

```ps1
--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 2022.12.0+353

Found RStudio Desktop [Posit.RStudio] Version 2022.12.0+353
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download1.rstudio.org/electron/windows/RStudio-2022.12.0-353.exe
  ██████████████████████████████   193 MB /  193 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName DisplayVersion Publisher      ProductCode
----------- -------------- ---------      -----------
RStudio     2022.12.0+353  Posit Software RStudio



PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
[... Terms of Transaction prompt ...]
Name           Id             Version     Available     Source
--------------------------------------------------------------
Microsoft Edge Microsoft.Edge 92.0.902.67 111.0.1661.54 winget
1 upgrades available.
```

The winget log shows (same with the winget release version):

```log
2023-03-27 17:39:01.661 [REPO]   Checking match with package id: Posit.RStudio
2023-03-27 17:39:01.661 [REPO]   Found multiple packages with strong match fields
2023-03-27 17:39:01.661 [REPO]   Appropriate available package could not be determined
```

**Comment by SpecterShell** [comment]
Actually, all versions of professional edition existing in winget-pkgs (`2022.12.0+353.pro20` and `2023.03.0+386.pro1` currently) and all versions of open source edition prior to `2022.12.0+353` can be updated directly.

For the latest two versions of open source edition `2022.12.0+353` and `2023.03.0+386`, running `winget upgrade` gave me these logs:
```
2023-03-29 09:22:55.726 [REPO] Found multiple matches for installed package [RStudio] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='rstudio'[Exact] Include:NormalizedNameAndPublisher='rstudio'+'positsoftware'[Exact]]
2023-03-29 09:22:55.728 [REPO]   Checking match with package id: Posit.RStudio.Pro
2023-03-29 09:22:55.729 [REPO]   Checking match with package id: Posit.RStudio
2023-03-29 09:22:55.729 [REPO]   Found multiple packages with strong match fields
2023-03-29 09:22:55.729 [REPO]   Appropriate available package could not be determined
```
I thought that WinGet could distinguish the two different editions with identical `PackageName` and `Publisher` according to the version, just like what it did for `OpenJS.NodeJS` and `OpenJS.NodeJS.LTS` as well as `Kingsoft.WPSOffice` and `Kingsoft.WPSOffice.CN`. But now it seems that WinGet is performing fuzzy search for the version entry, causing `2022.12.0+353` being matched with `2022.12.0+353.pro20`.

cc @denelon

**Comment by SpecterShell** [comment]
Weird. I tested it on another machine with WinGet of latest version and RStudio of version `2022.07.2+576` pre-installed and it gave me different result. I will remove the professional edition in case of further unexpected issues. 🤔

**Comment by dpprdan** [comment]
RStudio 2023.06.0+421 installed without issue for me about a month ago and the professional edition is not available anymore, so the issue is "fixed". I therefore close this.
