### ISSUE TITLE
[Update Request]: Tailscale 1.38.2

### ISSUE THREAD

**Issue by LeaderbotX400** [microsoft/winget-pkgs#100930]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Tailscale.tailscale

### Package Version

1.38.2

### Please describe the changes you would like to see

Azure pipeline for [existing PR](https://github.com/microsoft/winget-pkgs/pull/100336) is failing #100336

Version 1.38.2 is now available
Download Page URL: https://pkgs.tailscale.com/stable/tailscale-setup-1.38.2.exe

**Comment by brotich** [comment]
This has been done in https://github.com/microsoft/winget-pkgs/pull/100336

**Comment by ItzLevvie** [comment]
Close with reason: Resolved in PR 100336;
