### ISSUE TITLE
[Update Request]: Zoom.Zoom

### ISSUE THREAD

**Issue by Tratino** [microsoft/winget-pkgs#101028]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Zoom.Zoom

### Package Version

5.14.0 (13888)

### Please describe the changes you would like to see

Zoom Client contains multiple security vulnerabilities and should be updated to 5.14.0 (13888).
Current version in winget Repo is 5.13.4 (11835), which is from Jan. 9 2023 and is massively outdated.

**Comment by BrandonWanHuanSheng** [comment]
Reviewing the link. Setup pattern. "https://cdn.zoom.us/prod/5.13.4.11835/x64/ZoomInstallerFull.exe", "https://cdn.zoom.us/prod/5.14.0.13888/x64/ZoomInstallerFull.exe" Checking for website to see if there is newer version.  Setup pattern successful.

**Comment by BrandonWanHuanSheng** [comment]
This zoom version is randomly changed their version. Most of my client Zoom were outdated.

**Comment by BrandonWanHuanSheng** [comment]
Another Zoom will come in soon. Please see the release note. 
 https://support.zoom.us/hc/en-us/articles/201361953-Release-notes-for-Windows

**Comment by BrandonWanHuanSheng** [comment]
Waiting for moderator to be approved.

**Comment by BrandonWanHuanSheng** [comment]
Why this issue is not yet closed.
