### ISSUE TITLE
Automatically detect nullsoft/inno/wix/burn installers in the Yaml ps1 or GUI tool

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#1011]
# Description of the new feature/enhancement

Currently a user has to do research as to whether their exe installer is actually nullsoft, inno, or wix/burn. Many packages that are actually one of these are still marked as exe with manually set silent switches due to many users choosing to write their installers manually. There are tools that allow users to check the installer type, such as ["The Ultimate Silent Switch Finder"](https://deployhappiness.com/the-ultimate-exe-silent-switch-finder/) albeit not updated for recent versions of inno setup. Offloading this responsibility to the generators should help reduce the number of manifests that manually provide the switches instead of using the correct installertype.

# Proposed technical implementation details (optional)

**Comment by denelon** [comment]
We are building a wizard to help generate manifests for packages. It will detect installer types.

**Comment by superusercode** [comment]
still relevant

**Comment by superusercode** [comment]
still relevant

**Comment by denelon** [comment]
The new tool coming soon (think days, not weeks) https://github.com/microsoft/winget-cli/issues/157 detects the installer type :)

**Comment by denelon** [comment]
Here is the link to the new [wingetcreate](https://github.com/microsoft/winget-create) tool designed to help build manifests. The PR is in progress so soon you will be able to `winget install wingetcreate`.

**Comment by denelon** [comment]
@superusercode we implemented this in the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create). I'd like to close this issue as "Done"/"Released".
