### ISSUE TITLE
[Package Issue]: OO-Software.ShutUp10

### ISSUE THREAD

**Issue by DonEstefan** [microsoft/winget-pkgs#101150]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

wingetbot's "Automatic update of OO-Software.ShutUp10" seems to create portable packages with version mismatches. `PackageVersion` is raised correctly, but `DisplayVersion` always stays at "1.9.1431". 
See https://github.com/microsoft/winget-pkgs/commit/f6099af1e99aa403d4733b42f505c90b862398a3 
and https://github.com/microsoft/winget-pkgs/commit/86e41069a068e266639a45e52f19a03a99237556

This version mismatch causes "winget upgrade" to always mark the installed package as outdated - even when the latest version is installed.

### Steps to reproduce

install latest version and check for updates immediately afterwards

```
C:\> winget install OO-Software.ShutUp10
ShutUp10++ [OO-Software.ShutUp10] Version 1.9.1435.396

C:\> winget upgrade
Name                   ID                         Version        Verfügbar    Quelle
------------------------------------------------------------------------------------
O&O ShutUp10++         OO-Software.ShutUp10       1.9.1431       1.9.1435.396 winget
```

### Actual behavior

winget shows available updates, even with the latest version being installed

### Expected behavior

winget should not show available updates, when latest version is installed already

### Environment

```raw
C:\Windows\System32>winget --info
Windows-Paket-Manager v1.4.10173

Windows: Windows.Desktop v10.0.19045.2728
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by BrandonWanHuanSheng** [comment]
I am going to check what is happening.

**Comment by BrandonWanHuanSheng** [comment]
@https://github.com/apps/microsoft-github-policy-service add label:Installation-Issue

**Comment by BrandonWanHuanSheng** [comment]
This is normally caused by display version in registry key

**Comment by BrandonWanHuanSheng** [comment]
I failed to add the label. Who can add the label?

**Comment by BrandonWanHuanSheng** [comment]
I am going to the code to change their entries.

**Comment by BrandonWanHuanSheng** [comment]
Will be resolve in "https://github.com/microsoft/winget-pkgs/pull/101230/commits/a9cc12223b7bac146eb5e0c14827fdd349b45bdf"

**Comment by BrandonWanHuanSheng** [comment]
I don't know who is using winget. This is normally when someone use winget validate causing this issue to pop up a repository. I can see there file also having some issue. It suppose to be not me. I always edit very carefully with those file.

**Comment by BrandonWanHuanSheng** [comment]
Normally, I use find and replace tool to work on it.

**Comment by BrandonWanHuanSheng** [comment]
I was unable to uninstall "OO-Software.ShutUp10" It give me a reported that No installed package found matching input criteria.

**Comment by BrandonWanHuanSheng** [comment]
Uninstalled successfully OO-Software.ShutUp10

**Comment by BrandonWanHuanSheng** [comment]
It is resolved. The folder was changed to 1.9.1435

**Comment by mdanish-kh** [comment]
@DonEstefan Keep an eye on https://github.com/microsoft/winget-pkgs/issues/34421
