### ISSUE TITLE
[Update Request]: TheDocumentFoundation.LibreOffice.LTS - 7.4.6

### ISSUE THREAD

**Issue by kristapsesterlins** [microsoft/winget-pkgs#101494]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TheDocumentFoundation.LibreOffice.LTS

### Package Version

7.4.6

### Please describe the changes you would like to see

There is a new version available (7.4.6) - https://www.libreoffice.org/download/download-libreoffice/

**Comment by BrandonWanHuanSheng** [comment]
Checking for pull request to see.

**Comment by kristapsesterlins** [comment]
> There is a newer version! 7.5.2 was released.

The request ir for the LTS release, 7.5.2 is the current release but I am requesting the update for the LTS branch. 

> This version is slightly older and does not have the latest features, but it has been tested for longer.

**Comment by BrandonWanHuanSheng** [comment]
@kristapsesterlins Something failed on going. This package is going to delete "TheDocumentFoundation.LibreOffice.LTS" because duplicate link as "TheDocumentFoundation.LibreOffice"

**Comment by kristapsesterlins** [comment]
> @kristapsesterlins Something failed on going. This package is going to delete "TheDocumentFoundation.LibreOffice.LTS" because the duplicate URL link as "TheDocumentFoundation.LibreOffice"

The initial request for the version 7.4.6 and NOT 7.5.2

Download links:

https://www.libreoffice.org/donate/dl/win-x86_64/7.4.6/en-US/LibreOffice_7.4.6_Win_x64.msi
https://www.libreoffice.org/donate/dl/win-x86/7.4.6/en-US/LibreOffice_7.4.6_Win_x86.msi

Please update the manifest file. Thanks!

**Comment by BrandonWanHuanSheng** [comment]
Confirmed. Thus 2 URL have a same hashes. 
"https://download.documentfoundation.org/libreoffice/stable/7.5.2/win/x86_64/LibreOffice_7.5.2_Win_x86-64.msi"
"https://mirrors.bfsu.edu.cn/libreoffice/libreoffice/stable/7.5.2/win/x86_64/LibreOffice_7.5.2_Win_x86-64.msi" 
I will put the previous version back into "TheDocumentFoundation.LibreOffice"

**Comment by BrandonWanHuanSheng** [comment]
I will put temp file on "TheDocumentFoundation.LibreOffice.LTS" 7.4.6."  This is the last time that I release previous version. All the PR request might be in "TheDocumentFoundation.LibreOffice" to find their update.

**Comment by BrandonWanHuanSheng** [comment]
#101599
