### ISSUE TITLE
[Package Issue]: EpicGames.EpicGamesLauncher

### ISSUE THREAD

**Issue by CrushBug** [microsoft/winget-pkgs#101555]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Update checks show an update for the Epic Games client using version numbers (1.3.67.0) that don't match the actual client version (14.8.0). The package says there is an update when the latest client version is already installed. The Epic Games client updates itself.

### Steps to reproduce

1. Install the Epic Games client and let it keep itself updated. The latest version (as of April 4, 2023) is 14.8.0, displayed inside the client.

2. Go into the Settings of the Epic Games client and scroll down to the bottom where the client version is displayed.

3. Run winget upgrade and notice the version upgrade line:

> Epic Games Launcher   EpicGames.EpicGamesLauncher   1.3.23.0   1.3.67.0

4. Notice the difference between the package update offer version (1.3.67.0) and the actual up to date client version (14.8.0).

### Actual behavior

The package makes winget claim there is an update when there is not.

### Expected behavior

Winget package info would display the actual version of the Epic Games client and not offer updates with different, lower, version numbers.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2728
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

### Screenshots and Logs

Screenshot from the Epic Games client.

![EGSClientVersion-14 8 0](https://user-images.githubusercontent.com/32339000/229957458-d30c8e19-948f-40af-add1-211e2e542f3c.png)

No logs that mention the Epic Games client.

**Comment by Trenly** [comment]
This seems to be a difference in how EpicGames has the version in their launcher versus what they write to Control Panel. In control panel they write '1.3.67.0` but the launcher appears to be the `14.6.2` launcher, which immediately self-updates to `14.8.0`

**Comment by CrushBug** [comment]
The Epic Games Launcher keeps itself updated (there is a notification icon in the Launcher itself) and the actual Launcher version number is stored in the executable itself.

INSTALLPATH\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe

and INSTALLPATH is stored in the registry in the InstallLocation key, is it possible to read the version information directly from the installed executable?
![EpicGamesLauncher-Properties](https://user-images.githubusercontent.com/32339000/230228728-92b4d189-e1b9-4836-bcfd-43c3581beb6c.png)

**Comment by Trenly** [comment]
No, because the installed executable isn’t always in the same location. Many installers allow users to install to a directory of their choice.

Because the app keeps itself updated, this would be an issue with the auto-update function from Epic Games not updating the version in the control panel

**Comment by CrushBug** [comment]
`Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe` is absolutely guaranteed, because it is part of the installer extraction process. INSTALLPATH after user selection is stored in the registry. Here is my registry entry:

"InstallLocation"="C:\games\Epic Games\"

Putting the 2 together results in 

`c:\games\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe`

which when I check the properties of that executable, results in the screenshot above, with the proper version information.

Now, if winget packages cannot read version information from executables, then fine, there is no way to solve this. Maybe the Epic Games package should just be removed if it is always going to show the incorrect information?

Also, I don't believe there is any way you will convince Epic that not writing the client version to the registry is a problem on their end. I can't see them ever resolving it.
