### ISSUE TITLE
[Package Request]: TrafficMonitor

### ISSUE THREAD

**Issue by sayeed205** [microsoft/winget-pkgs#101500]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/zhongyang219/TrafficMonitor/releases/latest
Publisher: [zhongyang219](https://github.com/zhongyang219)
Package Name: traffic-monitor
Description: TrafficMonitor is a network monitoring software with floating window feature for Windows. It displays the current internet speed and CPU and RAM usage. There are also other capabilities like an embedded display in the taksbar, changeable display skins, and historical traffic statistics.
Package Version: 1.84.1
Installer URL: https://github.com/zhongyang219/TrafficMonitor/releases/download/V1.84.1/TrafficMonitor_V1.84.1_x64.zip

**Comment by BrandonWanHuanSheng** [comment]
It might have dependices.

**Comment by BrandonWanHuanSheng** [comment]
Most Commonly, it used to build app.
Java
VCRuntime
Net Framework
Net Framework SDK
Network: Most likely is Java8. Currently is unpredictable.

**Comment by sayeed205** [comment]
> Most Commonly, it used to build app. Java VCRuntime Net Framework Net Framework SDK Network: Most likely is Java8. Currently is unpredictable.

Oh

then is it not possible to add this ?

**Comment by stephengillie** [comment]
> > Most Commonly, it used to build app. Java VCRuntime Net Framework Net Framework SDK Network: Most likely is Java8. Currently is unpredictable.
> 
> Oh
> 
> then is it not possible to add this ?

I'm not sure that @BrandonWanHuanSheng's comment presents a blocker - it might refer to a context of which we are unaware.

**Comment by mdanish-kh** [comment]
[Policy] Dependencies

**Comment by mdanish-kh** [comment]
@Weirdo1312 This is blocked until support for dependencies is implemented in the WinGet Client

- https://github.com/microsoft/winget-cli/issues/163

**Comment by Trenly** [comment]
In addition to requiring VCRedist, there are dll's in the zip file :(

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`

**Comment by Cyberavater** [comment]
Will it be uploaded now?

**Comment by Dragon1573** [comment]
> Will it be uploaded now?

It's now suppoted! :tada:

If you wish, _Komac_ `v2.8.0` or newer, `Tools/YamlCreate.ps1` from the latest commit in `master` branch, and the latest version of `wingetcreate.exe` can generate `v1.9.0` manifests. :heart:
