### ISSUE TITLE
[Update Request]: Add a Python version 3.9.8

### ISSUE THREAD

**Issue by tunguskar** [microsoft/winget-pkgs#101665]
### What type of update are you requesting?

A additional version of an existing package

### Current Package Identifier

Python.Python.3.9

### Package Version

3.9.8

### Please describe the changes you would like to see

There is an "older" version I rely on at the moment. The mentioned 3.9.8. It would be nice if it could be added.

https://www.python.org/downloads/release/python-398/

**Comment by BrandonWanHuanSheng** [comment]
Unable to created because there is a greater version than that one.

**Comment by tunguskar** [comment]
> Unable to created because there is a greater version than that one.

So it is not possible to add a version in between?
