### ISSUE TITLE
Validation should check extension for portable packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#101699]
If a manifest is submitted for a "portable" installer type, the validation infrastructure should verify the extension type for the downloaded portable package.

              It's actually a `ps1` script, not an executable

> I installed it using the `InstallerType: portable` but it creates a file at `C:\Users\natob\AppData\Local\Microsoft\WinGet\Links\scoop.exe`. It's probably great for portable apps but this is a [PowerShell installer](https://github.com/ScoopInstaller/Install/blob/master/install.ps1) for a [full-blown PowerShell project](https://github.com/ScoopInstaller/Scoop/tree/master/lib). I guess a new installer type is still required?

I haven't followed the project recently, so I don't know if that new installer type made it in

_Originally posted by @NatoBoram in https://github.com/microsoft/winget-pkgs/issues/19425#issuecomment-1498453595_

**Comment by mdanish-kh** [comment]
[Policy] Area-Validation-Pipeline

**Comment by denelon** [comment]
Thanks for mentioning this one as well @NatoBoram. I don't know if it would be possible to do something similar to what chocolatey did with respect to building an installer or not, but that would certainly be an option for Scoop to get into the community repository.

**Comment by NatoBoram** [comment]
Maybe it would be possible to package [install.ps1](https://github.com/ScoopInstaller/Install/blob/master/install.ps1) with [PS2EXE](https://github.com/MScholtes/PS2EXE)?
