### ISSUE TITLE
[Package Request]: TextPad

### ISSUE THREAD

**Issue by stym-singh** [microsoft/winget-pkgs#101613]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.textpad.com/download
Publisher: Helios Software Solutions
Package Name: TextPad
Description: TextPad is a powerful, general-purpose editor for plain text files. Easy to use, with all the features a power user requires.
Package Version: 9.2.0
Installer URL: https://www.textpad.com/file?path=v9/setupv9.exe

**Comment by BrandonWanHuanSheng** [comment]
A bots detected on this link https://www.textpad.com/file?path=v9/setupv9.exe

**Comment by BrandonWanHuanSheng** [comment]
winget do not support authentication.

**Comment by mdanish-kh** [comment]
[Policy] Area-External

See https://github.com/microsoft/winget-pkgs/pull/101618
