### ISSUE TITLE
[Update Request]: Agent Ransack outdated since 16-11-2022

### ISSUE THREAD

**Issue by JustMyGithub** [microsoft/winget-pkgs#101624]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mythicsoft.AgentRansack

### Package Version

9.0.3341.1

### Please describe the changes you would like to see

https://www.mythicsoft.com/agentransack/information/#version-history
https://download.mythicsoft.com/flp/3367/filelocator_3367.exe

**Comment by BrandonWanHuanSheng** [comment]
URL is not match

**Comment by BrandonWanHuanSheng** [comment]
Most likely, I get metadata from .exe, version.txt, .xml.
