### ISSUE TITLE
[Package Request]: Steam Art Manager

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#101920]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v1.4.5
Publisher: Travis Lane
Package Name: Steam Art Manager
Description: A tool for setting the artwork of your Steam library.
Package Version: 1.4.5
Installer URL:https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v1.4.5/Steam.Art.Manager_1.4.5_x64_en-US.msi

**Comment by BrandonWanHuanSheng** [comment]
Configuring The Installation

**Comment by stephengillie** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/101955 is merged, I'm going to assume this is complete. If this is in error, feel free to @ me and I'll reopen.
