### ISSUE TITLE
[Update Request]: CodecGuide.K-LiteCodecPack.*

### ISSUE THREAD

**Issue by NLZ** [microsoft/winget-pkgs#102016]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

CodecGuide.K-LiteCodecPack.Full

### Package Version

17.5.2

### Please describe the changes you would like to see

Requesting all the CodecGuide.K-LiteCodecPack packages to be updated:
 Id | Url
---|---
CodecGuide.K-LiteCodecPack.Basic | https://files3.codecguide.com/K-Lite_Codec_Pack_1752_Basic.exe
CodecGuide.K-LiteCodecPack.Standard | https://files3.codecguide.com/K-Lite_Codec_Pack_1752_Standard.exe
CodecGuide.K-LiteCodecPack.Full | https://files3.codecguide.com/K-Lite_Codec_Pack_1752_Full.exe
CodecGuide.K-LiteCodecPack.Mega | https://files3.codecguide.com/K-Lite_Codec_Pack_1752_Mega.exe

This would close  #99153 as well

**Comment by mdanish-kh** [comment]
Close with reason: K-lite packages have been updated to 17.5.2;
