### ISSUE TITLE
[Package Issue]: BiniSoft.WindowsFirewallControl 6.9.0.0

### ISSUE THREAD

**Issue by sebaFlame** [microsoft/winget-pkgs#102101]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

While upgrading BiniSoft.WindowsFirewallControl from 6.8.2.0 to 6.9.0.0 there is an "Installer hash does not match." error.

### Steps to reproduce

Upgrade to BiniSoft.WindowsFirewallControl 6.9.0.0

### Actual behavior

Not upgrading

### Expected behavior

Should upgrade

### Environment

```raw
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2728
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by BrandonWanHuanSheng** [comment]
It look like I have validated the manifest but why it did not show up on Github
![Screenshot (186)](https://user-images.githubusercontent.com/118059864/231112440-55a63bd4-6121-4413-8f1b-7afaafa9cd90.png)

**Comment by sebaFlame** [comment]
@BrandonWanHuanSheng the update to 6.9.2.0 is from feb 15. If it didn't pick it up by now, it won't.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie Did you know what is happening to wingetbot PR? I already sent a validate request on 11 April 5:09.  It did not show up on GitHub either. Expected Behavior is to show up on Github

**Comment by BrandonWanHuanSheng** [comment]
Do you remember that is no author? Suppose another pull request is Automatic Update  BiniSoft.WindowsFirewallControl 6.9.0.0 to BiniSoft.WindowsFirewallControl 6.9.2.0 But the actual PR can't found in here.
![Screenshot (1148)](https://user-images.githubusercontent.com/118059864/231899770-becd3f5b-df09-4121-9ab8-fbeeabac65dc.png)

**Comment by sebaFlame** [comment]
Just did a winget upgrade and got the new 6.9.2.0 with correct hash! Thanks all, closing.
