### ISSUE TITLE
[Package Request]: OWASP ZAP

### ISSUE THREAD

**Issue by thesobercoder** [microsoft/winget-pkgs#102186]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.zaproxy.org/download/
Publisher: OWASP 
Package Name: ZAP
Description: Zed Attack Proxy (ZAP) is a free, open-source penetration testing tool being maintained under the umbrella of the Open Web Application Security Project (OWASP).
Package Version: 2.12.0
Installer URL: https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2_12_0_windows.exe

**Comment by BrandonWanHuanSheng** [comment]
It look like that dependency is not in winget yet.

**Comment by thesobercoder** [comment]
> Speaking of versions, is the `Oracle.JavaRuntimeEnvironment`'s version `8.0.3610.9` below this package's version `11` requirement?

@stephengillie That is correct. Also, Oracle changed a lot of licensing terms and conditions post version `8`.

**Comment by mdanish-kh** [comment]
[Policy] Dependencies

**Comment by thc202** [comment]
I think this can already be closed with the merge of #756.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #756;
