### ISSUE TITLE
[Package Request]: ryujinx-ava

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#102341]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Ryujinx/release-channel-master/releases
Publisher: Ryujinx
Package Name: ryujinx-ava
Description: Ryujinx build with Avalonia UI 
Package Version: 1.1.707
Installer URL: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.707/test-ava-ryujinx-1.1.707-win_x64.zip

**Comment by BrandonWanHuanSheng** [comment]
Failed to create symlink. It can't handled to winget.

**Comment by BrandonWanHuanSheng** [comment]
Does anyone know how to resolve this?

**Comment by BrandonWanHuanSheng** [comment]
This one is blocked by https://github.com/microsoft/winget-cli/issues/2711 because it has a symlink error while during creation.
