### ISSUE TITLE
[Update Request]: Zoom.Zoom

### ISSUE THREAD

**Issue by xtian08** [microsoft/winget-pkgs#102338]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Zoom.Zoom

### Package Version

5.14.2.14578

### Please describe the changes you would like to see

To reproduce is to install zoom via winget then run oobe sysprep, after boot the zoom app is gone.

Using the MSI installer works after sysprep instead of x64 EXE installer

**Comment by BrandonWanHuanSheng** [comment]
It look like the latest version was already added into the manifests.

**Comment by BrandonWanHuanSheng** [comment]
I found it, Winget install Zoom.Zoom --Scope Machine

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie It look like there is no update request on Zoom.Zoom We need to wait for the publisher website to push the update up. The update will be arrived on 17-April-2023.

**Comment by Footur** [comment]
I'm missing the current release of Zoom (v5.15.1 (17948)).

**Comment by Footur** [comment]
I have created a PR #110539.

**Comment by Footur** [comment]
@stephengillie I think this thread can be closed.

**Comment by BrandonWanHuanSheng** [comment]
It look like the author released the update from time to another time.
