### ISSUE TITLE
[Update Request]: Update Microsoft.PowerShell to 7.3.4

### ISSUE THREAD

**Issue by AtifChy** [microsoft/winget-pkgs#102530]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PowerShell

### Package Version

7.3.4.0

### Please describe the changes you would like to see

There is a new release (7.3.4.0) available. 
Download URL: https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/PowerShell-7.3.4-win-x64.msi

**Comment by mdanish-kh** [comment]
Close with reason: Package added in #102538;
