### ISSUE TITLE
Invalid YAML file format

### ISSUE THREAD

**Issue by ashu1710** [microsoft/winget-pkgs#102516]
Path: winget-pkgs/manifests/c/COAS/SemantaModeler/6.7.3.5307

FileName: COAS.SemantaModeler.locale.en-US.yaml

This file has invalid yaml format...Can you please correct it. 

Thank you

**Comment by BrandonWanHuanSheng** [comment]
I am updating the file. It just opened.

**Comment by Trenly** [comment]
Close with reason: Resolved by PR 102519;
