### ISSUE TITLE
[Package Request]: helix-editor

### ISSUE THREAD

**Issue by andyliuhaowen** [microsoft/winget-pkgs#102583]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/helix-editor/helix/releases/tag/23.03
Publisher: helix-editor 
Package Name: helix-editor 
Description:  A post-modern modal text editor.
Package Version: 23.03
Installer URL: https://github.com/helix-editor/helix/releases/download/23.03/helix-23.03-x86_64-windows.zip

**Comment by BrandonWanHuanSheng** [comment]
What is your winget info?

**Comment by lesleyrs** [comment]
https://github.com/microsoft/winget-pkgs/pull/101377 it's called Helix.Helix

**Comment by andyliuhaowen** [comment]
I didn't see that. Thank you!
