### ISSUE TITLE
[Update Request]: Guru3D.Afterburner 4.6.5

### ISSUE THREAD

**Issue by ianalexis** [microsoft/winget-pkgs#102811]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Guru3D.Afterburner

### Package Version

4.6.5

### Please describe the changes you would like to see

New 4.6.5 FINAL STABLE
https://www.guru3d.com/files-get/msi-afterburner-beta-download,37.html

**Comment by valery-kirichenko** [comment]
I already submitted https://github.com/microsoft/winget-pkgs/pull/102825

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #102825;
