### ISSUE TITLE
[Package Issue]: KDE.Kdenlive uses wrong download URLs

### ISSUE THREAD

**Issue by qsuscs** [microsoft/winget-pkgs#102898]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The KDE.Kdenlive package uses the the KDE CI automatic builds, which update often and do not produce stable results.  In particular, old build jobs get deleted and result in a HTTP 403 when attempting to fetch it.  These builds are linked from [the download page](https://kdenlive.org/en/download/), with an explicit note “[t]hey can be unstable and can corrupt existing projects, do not use in production”—so these appear inappropriate for the winget package.

The package should rather use stable release URLs, such as https://download.kde.org/stable/kdenlive/22.12/windows/kdenlive-22.12.3.exe.  Checksums for these files are provided [on the file details page](https://download.kde.org/stable/kdenlive/22.12/windows/kdenlive-22.12.3.exe.mirrorlist).  These download.kde.org URLs also automatically redirect to a mirror near the user.

This issue has appeared already in #96254 and #95801, but the fix for them was only the then-current daily build URL, not a stable one as I proposed.

Pinging @vedantmgoyal2009, as these URLs appear to come from his automation (cf. #102083).

### Steps to reproduce

`> winget install KDE.Kdenlive`

### Actual behavior

```
> winget install KDE.Kdenlive
Gefunden Kdenlive [KDE.Kdenlive] Version 22.12.3
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Wird heruntergeladen https://binary-factory.kde.org/view/Windows%20MingW/job/Kdenlive_Stable_mingw64/1058/artifact/kdenlive-22.12.3-1058-windows-gcc-x86_64.exe
Unerwarteter Fehler beim Ausführen des Befehls:
Download request status is not success.
0x80190193 : Nicht zulässig (403).
```
(Sorry for the German output, if someone tells me how to temporarily switch it to English, I can provide that as well.  The gist should be clear though.)

### Expected behavior

The package should install.

### Environment

```raw
> winget --info
Windows-Paket-Manager v1.4.10173
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.2846
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Benutzereinstellungen: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by BrandonWanHuanSheng** [comment]
Continue to another PR. Duplicate PR is found. Failed to merge #102975 due to #103012

**Comment by BrandonWanHuanSheng** [comment]
@Trenly Can you close this issue?

**Comment by ItzLevvie** [comment]
Close with reason: See above;
