### ISSUE TITLE
[Package Issue]: WinSCP.WinSCP winget finds an update but doesn't install it

### ISSUE THREAD

**Issue by lackovic** [microsoft/winget-pkgs#103085]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

When running `winget upgrade -h --all` winget reports there is a new version for WinSCP.WinSCP (5.21.7 -> 5.21.8) but does not install it.

### Steps to reproduce

```powershell
> winget upgrade -h --all --verbose-logs
Name          Id            Version Available Source
----------------------------------------------------
WinSCP 5.21.7 WinSCP.WinSCP 5.21.7  5.21.8    winget
1 upgrades available.
``` 

### Actual behavior

Nothing happens.

### Expected behavior

The newer version 5.21.8 is installed.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by lackovic** [comment]
```powershell
> winget list WinSCP
Name          Id            Version Available Source
----------------------------------------------------
WinSCP 5.21.7 WinSCP.WinSCP 5.21.7  5.21.8    winget
```

**Comment by lackovic** [comment]
```powershell
> winget upgrade -h --all --verbose-logs
Name          Id            Version Available Source
----------------------------------------------------
WinSCP 5.21.7 WinSCP.WinSCP 5.21.7  5.21.8    winget
1 upgrades available.
```

**Comment by lackovic** [comment]
[WinGet-2023-04-21-09-01-46.037.log](https://github.com/microsoft/winget-pkgs/files/11292711/WinGet-2023-04-21-09-01-46.037.log)

**Comment by mdanish-kh** [comment]
@lackovic Can you check again if the issue has been resolved for you?

Although I don't find this in the logs, but I have a strong feeling the issue was due to a scope-mismatch. You probably have a user-context installation of WinSCP and could not upgrade using WinGet because the latest manifest did not contain the `Scope: user` installer node. I've updated the manifest and hopefully the issue is resolved now.

**Comment by w3lld0ne** [comment]
> @lackovic Can you check again if the issue has been resolved for you?
> 
> Although I don't find this in the logs, but I have a strong feeling the issue was due to a scope-mismatch. You probably have a user-context installation of WinSCP and could not upgrade using WinGet because the latest manifest did not contain the `Scope: user` installer node. I've updated the manifest and hopefully the issue is resolved now.

had the same issue with this package, now it's solved for me.

**Comment by lackovic** [comment]
> Can you check again if the issue has been resolved for you?

I checked now and it works, thanks!
