### ISSUE TITLE
[Package Request]: Winpinator

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#103090]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/swiszczoo/winpinator/releases
Publisher: swiszczoo
Package Name: Winpinator
Description:
Winpinator is an unofficial Windows port of [Warpinator](https://github.com/linuxmint/warpinator), rewritten from scratch in C++. It supports the gRPC based protocol of its Linux equivalent, as well as zeroconf/mDNS based service discovery. Due to the fact that Windows has a completely different filesystem, some Warpinator features have to be emulated, e.g. sending filesystem permissions along with the files.
Package Version: 0.1.0, 0.1.1, 0.1.2 (Latest)
Installer URL:
Latest (0.1.2)
https://github.com/swiszczoo/winpinator/releases/download/v0.1.2/winpinator_setup_0.1.2_x64.exe
https://github.com/swiszczoo/winpinator/releases/download/v0.1.2/winpinator_setup_0.1.2_x86.exe

Second Release (0.1.1)
https://github.com/swiszczoo/winpinator/releases/download/v0.1.1/winpinator_setup_0.1.1_x64.exe
https://github.com/swiszczoo/winpinator/releases/download/v0.1.1/winpinator_setup_0.1.1_x86.exe

First Release (0.1.0)
https://github.com/swiszczoo/winpinator/releases/download/v0.1.0/winpinator_setup_0.1.0_x64.exe
https://github.com/swiszczoo/winpinator/releases/download/v0.1.0/winpinator_setup_0.1.0_x86.exe

**Comment by BrandonWanHuanSheng** [comment]
It look like wingetcreate failed! The manifests file is already exist. Can you try to check your winget again?
Wingetcreate failed with
We have detected that this package identifier already exists. If you intend to update an existing package, please use the update command.

**Comment by BrandonWanHuanSheng** [comment]
Sometimes, it might not appear because you are not using the latest version.

**Comment by BrandonWanHuanSheng** [comment]
Submitting only 0.1.0, 0.1.1. Due to 0.1.2 was exist.

**Comment by BrandonWanHuanSheng** [comment]
Checking to see if anything was behind.

**Comment by thedoggybrad** [comment]
Just did not notice that after searching using the winget --search. Anyways, just submit the version 0.1.0 and 0.1.1.

**Comment by thedoggybrad** [comment]
The 2 PRs have been accepted and now been applied to the manifests. Closing this Issue now.
