### ISSUE TITLE
[Package Request]:  Kingston SSD Manager

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#103091]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.kingston.com/en/support/technical/ssdmanager
Publisher: Kingston

Package Name: Kingston SSD Manager

Description:
Kingston® SSD Manager is an application that provides users with the ability to monitor and manage various aspects of their Kingston® Solid State Drive.

With Kingston® SSD Manager you will be able to:

Monitor drive health, status, and disk usage
View drive identification data including model name, serial number, firmware version, and other relevant information
View and export detailed drive health and status reports
Update drive firmware
Securely erase data
Manage TCG Opal and IEEE 1667
Overprovision with Host Protected Area (HPA)

Package Version: Too Many

Installer URL(s):
v.1.5.2.6: https://media.kingston.com/support/downloads/KSM_setup_1.5.2.6.exe

v.1.5.2.5: https://media.kingston.com/support/downloads/KSM_setup_1.5.2.5.exe

v.1.5.2.4:
https://media.kingston.com/support/downloads/KSM_setup_1.5.2.5.exe

v.1.5.2.0:
https://media.kingston.com/support/downloads/KSM_setup_1.5.2.0.exe

v.1.5.1.8:
https://media.kingston.com/support/downloads/KSM_setup_1.5.1.8.exe

v.1.5.1.6:
https://media.kingston.com/support/downloads/KSM_setup_1.5.1.6.exe

v.1.1.2.6
https://media.kingston.com/support/downloads/KSM_setup_1.1.2.6.exe

(+More, will be sended on a reply, its too many)

**Comment by thedoggybrad** [comment]
v.1.5.1.5
https://media.kingston.com/support/downloads/KSM_setup_1.5.1.5.exe

**Comment by thedoggybrad** [comment]
Note: The most important and up to date releases are version 1.5.2.6 which is the latest and only supports x64 while version 1.1.2.6 is the last version to support x86.

**Comment by thedoggybrad** [comment]
Meaning versions higher than 1.1.2.6 is only x64.

**Comment by kkbruce** [comment]
https://github.com/microsoft/winget-pkgs/pull/103154 
KSM 1.5.2.6 PR is here.

**Comment by thedoggybrad** [comment]
https://github.com/microsoft/winget-pkgs/pull/103160
version 1.1.2.6 PR is submitted

**Comment by thedoggybrad** [comment]
There are still releases that are not pushed on winget. But atleast those important ones are published to winget. 

I will let this thing open for now.

**Comment by Dragon1573** [comment]
I see @thedoggybrad and other contributors has submitted following versions to the repository.

For versions `>1.1.2.6,<1.5.1.6` and `>1.5.1.6,<1.5.3.2`, it's not recommended to add them to the repository. These stale releases may contain bugs and lead to serious security problems. As a package manager, we should always add the current latest version to the repository instead of the old one. For those stale versions already available in the repository, we can still keep them as they are still downloadable.

```text
20:51:36 D:\...\winget-pkgs master ≡ 1ms pwsh> winget search -s winget -e Kingston.SSDManager --versions
已找到 Kingston SSD Manager x64 [Kingston.SSDManager]
版本
-------
1.5.3.3
1.5.3.2
1.5.1.6
1.1.2.6
```

The latest version of `Kingston.SSDManager` is `v1.5.3.4`. I'll help submitting the manifest. 😄
