### ISSUE TITLE
[Package Request]: Slowscript's Warpinator for Windows

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#103088]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/slowscript/warpinator-windows/releases

Publisher: slowscript

Package Name: Warpinator

Description:
This is an unofficial reimplementation of Linux Mint's file sharing tool [Warpinator](https://github.com/linuxmint/warpinator) for Windows 7-10.
Transfer files between Linux, Windows and Android devices

Package Version: 0.1, 0.2, 0.3

Installer URL(s):
•Version 0.1: https://github.com/slowscript/warpinator-windows/releases/download/v0.1b/warpinator-setup.exe
•Version 0.2:
https://github.com/slowscript/warpinator-windows/releases/download/v0.2/warpinator-setup_0.2.exe
•Version 0.3 (Latest):
https://github.com/slowscript/warpinator-windows/releases/download/v0.3/warpinator-setup_0.3.exe

Note: Windows Defender Smart Screen is giving a warning (due to low popularity) to the installer only, not the app.  (NOW RESOLVED)

**Comment by thedoggybrad** [comment]
PS: As of now, I have submitted all of these installers to Microsoft under the submission portal for the software "Windows Defender Smart Screen". But definitely this app is safe, just with low popularity.

**Comment by thedoggybrad** [comment]
Update: Microsoft have analyzed the file. Acc to an email, I will view the status now.

**Comment by thedoggybrad** [comment]
The warning you experienced indicates that the application had not established reputation with the Microsoft Defender SmartScreen Application Reputation feature at that time. We can confirm that the application warpinator-setup.exe, (SHA256:700A6905973ED3E32068C6A59C60C69D9C6C76B153A29E8BF0EA1213025E65B4) has since established reputation and attempting to download or run the application should no longer show any warnings.

**Comment by thedoggybrad** [comment]
So, this app is good to go for the creation of its manifest. Unfortunately, I do not have the proper knowledge to do so, so anyone here may do it.

**Comment by BrandonWanHuanSheng** [comment]
It look like it requires dependcies.

**Comment by thedoggybrad** [comment]
@BrandonWanHuanSheng 

Requires .NET SDK 4.6.2
-Slowscript's Github Page

Yes it does require. Do it is compatible to winget if it does need dependencies?

**Comment by BrandonWanHuanSheng** [comment]
Most likely, it block Azure Pipelines to be passed

**Comment by thedoggybrad** [comment]
https://github.com/microsoft/winget-pkgs/pull/103163
https://github.com/microsoft/winget-pkgs/pull/103162
https://github.com/microsoft/winget-pkgs/pull/103161

I have attempted anyways, thanks to wingetcreate, a super easy tool to send a PR.

**Comment by thedoggybrad** [comment]
Will resubmit, I deleted my fork.

**Comment by thedoggybrad** [comment]
https://github.com/microsoft/winget-pkgs/pull/103174
https://github.com/microsoft/winget-pkgs/pull/103173
https://github.com/microsoft/winget-pkgs/pull/103172

Updated PRs.

**Comment by thedoggybrad** [comment]
PRs are commited. Now closing this PR.
