### ISSUE TITLE
[Update Request]: Standardize NordSecurity programs

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-pkgs#103170]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

NordPassTeam.NordPass, Nord.NordLocker, NordVPN.NordVPN

### Package Version

Not tied to a specific version

### Please describe the changes you would like to see

Should we standardize folder structure and package names of programs from Nord Security? Currently, it looks something like this:

![image](https://user-images.githubusercontent.com/81419612/233787337-d199a5ad-a080-4fda-98c6-c80a8f1c2bfd.png)

The programs are all from the same company, so I don't think it makes sense how we currently handle these packages.

**Comment by stephengillie** [comment]
NordVPN.com has: © 2023 Nord Security. All Rights Reserved
 [support@nordvpn.com](mailto:support@nordvpn.com)
NordPass's website has: © 2023 [Nord Security](https://nordsecurity.com/). All Rights Reserved · [support@nordpass.com](mailto:support@nordpass.com)

**Comment by stephengillie** [comment]
This will require 24 PRs: 
Nord/NordLocker: 5 
NordPassTeam/NordPass: 1 
NordVPN/NordVPN: 18

**Comment by CanePlayz** [comment]
Is there no way that someone of a "higher rank" can force all of these changes in one PR? Or is it mandatory to go through the pipeline and everything?

I will do it I guess, will we call them "NordSecurity" everywhere now?

**Comment by Trenly** [comment]
I have a script that will allow for automatically creating the PR's @stephengillie. I will take care of this one

**Comment by Trenly** [comment]
I believe it has to do with how the pre-indexed package is created. I recall @denelon mentioning that he broke it one time by deleting multiple packages in a single PR. Perhaps it has to do with the fact that PR's are merged in as squash commits?

**Comment by Trenly** [comment]
Close with reason: Packages moved;

**Comment by CanePlayz** [comment]
> Close with reason: Packages moved;

Thanks!

**Comment by CanePlayz** [comment]
> Close with reason: Packages moved;

One more thing: The folders of the old three publishers are still there. Can they be removed?
