### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-pkgs#103209]
Testing bot replies

**Comment by mdanish-kh** [comment]
[Policy] Dependencies

**Comment by mdanish-kh** [comment]
Hmmm.. @Trenly, the autoresponder doesn't want to work

**Comment by Trenly** [comment]
> Hmmm.. @Trenly, the autoresponder doesn't want to work. Can you try adding a comment?

Hmmm

[Policy] Interactive Only
