### ISSUE TITLE
[Update Request]: OliverBetz.ExifTool

### ISSUE THREAD

**Issue by musm** [microsoft/winget-pkgs#103227]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OliverBetz.ExifTool

### Package Version

12.60

### Please describe the changes you would like to see

Download Page URL:  https://oliverbetz.de/pages/Artikel/ExifTool-for-Windows

**Comment by BrandonWanHuanSheng** [comment]
The pull request was started.

**Comment by BrandonWanHuanSheng** [comment]
It is quite noisy when you comment on a pull request because the notification subscribed after you have been commented.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #103345;
