### ISSUE TITLE
[Package Issue]: mcmilk.7zip-zsdt

### ISSUE THREAD

**Issue by treysis** [microsoft/winget-pkgs#103363]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Wrong version string. Same problem as before in https://github.com/microsoft/winget-pkgs/issues/94590

### Steps to reproduce

https://github.com/microsoft/winget-pkgs/issues/94590

### Actual behavior

https://github.com/microsoft/winget-pkgs/issues/94590

### Expected behavior

https://github.com/microsoft/winget-pkgs/issues/94590

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2846
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by BrandonWanHuanSheng** [comment]
It look like that issue caused by winget-update-bot.

**Comment by BrandonWanHuanSheng** [comment]
That wrong version manifest string will be totally deleted.

**Comment by treysis** [comment]
So will this fix it in future commits from winget-update-bot as well?

**Comment by stephengillie** [comment]
This might fix the issue and allow future Wingetbot commits to work as expected. But non-semantic versions seem to be more likely to have issues in the first place, so this might recur.

**Comment by BrandonWanHuanSheng** [comment]
Do you think it was resolved?

**Comment by treysis** [comment]
Yes, it's fixed now!
