### ISSUE TITLE
[Update Request]: ETHZurich.SafeExamBrowser version 3.5.0.544

### ISSUE THREAD

**Issue by ianalexis** [microsoft/winget-pkgs#103458]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ETHZurich.SafeExamBrowser

### Package Version

3.5.0.544

### Please describe the changes you would like to see

There is a new release (3.5.0) available.
Download Page Url: https://sourceforge.net/projects/seb/files/seb/SEB_3.5.0/SEB_3.5.0.544_SetupBundle.exe/download

**Comment by BrandonWanHuanSheng** [comment]
It look like I might clog out the pull request.

**Comment by BrandonWanHuanSheng** [comment]
Going to expand some previous manifest.

**Comment by BrandonWanHuanSheng** [comment]
Newer Version is 3. But the some of previous version will be hide and the newest will appear.

**Comment by BrandonWanHuanSheng** [comment]
You also saw my pull request.

**Comment by Trenly** [comment]
Close with reason: Resolved by PR 103654;

* #103654
