### ISSUE TITLE
[Package Issue]: Gyan.FFmpeg.Shared

### ISSUE THREAD

**Issue by bitingsock** [microsoft/winget-pkgs#103471]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When installing the shared version the symlinks to the exes are correctly made but they can't see the shared resources in the source directory.

### Steps to reproduce

![Untitled](https://user-images.githubusercontent.com/6302101/234403534-a6947576-b21b-4393-a1b2-7860493d7eae.png)

### Actual behavior

The symlinks do not see the shared libraries.
CD to linked directory it runs fine.

### Expected behavior

Maybe the shared libs need to be linked too?

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by bitingsock** [comment]
@SpecterShell

**Comment by BrandonWanHuanSheng** [comment]
Blocked by https://github.com/microsoft/winget-cli/issues/2711

**Comment by bitingsock** [comment]
I see that it is a more general issue than I thought.
