### ISSUE TITLE
[Package Issue]: Microsoft.Sysinternals.TCPView

### ISSUE THREAD

**Issue by JeffMill** [microsoft/winget-pkgs#103660]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer hash mismatch.

### Steps to reproduce

winget install Microsoft.Sysinternals.TCPView

### Actual behavior

Installer hash does not match.

### Expected behavior

The command should successfully install

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

> winget install Microsoft.Sysinternals.TCPView
Found TCPView [Microsoft.Sysinternals.TCPView] Version 4.18
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://live.sysinternals.com/Tcpview.exe
  ██████████████████████████████   922 KB /  922 KB
Installer hash does not match.

**Comment by BrandonWanHuanSheng** [comment]
Warning! Evaluate the Pipelines. Causing lost 3 file

**Comment by BrandonWanHuanSheng** [comment]
Looking all the Sysinternals.
