### ISSUE TITLE
[Package Issue]: Syncplay.Syncplay.Beta

### ISSUE THREAD

**Issue by adripo** [microsoft/winget-pkgs#103684]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

With version 1.7.0, Syncplay is not anymore a beta version.
The package identifier should be changed by removing beta. Installed package on windows doesn't have beta anymore too.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Syncplay/Syncplay/Beta/1.7.0

### Steps to reproduce

-

### Actual behavior

PackageIdentifier: Syncplay.Syncplay.Beta

### Expected behavior

PackageIdentifier: Syncplay.Syncplay

### Environment

```raw
-
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/26493496/234723844-aa3617b6-888f-42b7-ac53-579161717385.png)

--> 

![image](https://user-images.githubusercontent.com/26493496/234723830-d8bdf721-e0b3-4250-a050-a6c86cfbba75.png)

**Comment by BrandonWanHuanSheng** [comment]
Watch out. I might remove out from the directory.

**Comment by BrandonWanHuanSheng** [comment]
Do you think the link might need to change?

**Comment by BrandonWanHuanSheng** [comment]
It look like it got Validation-Executable-Error

**Comment by adripo** [comment]
I think that the path must be changed as well as the packageId

**Comment by adripo** [comment]
I have just seen your PR #103708. Everything looks good.
Now the program is identified correctly by winget:
![image](https://user-images.githubusercontent.com/26493496/235007599-a58601d6-f646-4238-a7b4-99a903f6ccc7.png)

I think the Beta version should be removed

**Comment by BrandonWanHuanSheng** [comment]
It look like the beta1 link still available found on internet.

**Comment by BrandonWanHuanSheng** [comment]
I already request delete Syncplay.Syncplay.Beta

**Comment by Trenly** [comment]
Close with reason: Linked PR Merged;
