### ISSUE TITLE
[Package Request]: WikiSearch

### ISSUE THREAD

**Issue by MesterPerfect** [microsoft/winget-pkgs#103603]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/tecwindow/WikiSearch
Publisher: tecwindow
Package Name: WikiSearch
Description: This simple program enables you to search Wikipedia, the free encyclopedia, without having to open your browser.
Package Version: 1.4.0
Installer URL: https://github.com/tecwindow/WikiSearch/releases/download/V1.4.0/WikiSearchV1.4.0.exe

**Comment by BrandonWanHuanSheng** [comment]
It look like it was exist

**Comment by MesterPerfect** [comment]
> It look like it was exist
Yes, I added it two days ago.
