### ISSUE TITLE
[Update Request]: Tailscale new update

### ISSUE THREAD

**Issue by Xarishark** [microsoft/winget-pkgs#103726]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

tailscale.tailscale

### Package Version

1.40.0

### Please describe the changes you would like to see

https://pkgs.tailscale.com/stable/tailscale-setup-1.40.0-amd64.msi

**Comment by BrandonWanHuanSheng** [comment]
It look like there is Area-Bots.
