### ISSUE TITLE
[Package Request]: git-absorb

### ISSUE THREAD

**Issue by moswald** [microsoft/winget-pkgs#103855]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/tummychow/git-absorb/releases
Publisher: tummychow
Package Name: git-absorb
Description: [Absorb extension for git](https://andrewlock.net/super-charging-git-rebase-with-git-absorb/).
Package Version: 0.6.10
Installer URL: https://github.com/tummychow/git-absorb/releases/download/0.6.10/git-absorb-0.6.10-x86_64-pc-windows-msvc.zip

**Comment by BrandonWanHuanSheng** [comment]
It look like installable.

**Comment by BrandonWanHuanSheng** [comment]
Successfully added but need to call admin.
