### ISSUE TITLE
[Update Request]: Microsoft.OfficeDeploymentTool + old ones are dead

### ISSUE THREAD

**Issue by NLZ** [microsoft/winget-pkgs#103927]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.OfficeDeploymentTool

### Package Version

16.0.16227.20258

### Please describe the changes you would like to see

https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16227-20258.exe

Btw the install links of old versions of the package is dead.
Maybe the package could be reenginered as a portable installation, using
https://officecdn.microsoft.com/pr/wsus/setup.exe

**Comment by BrandonWanHuanSheng** [comment]
Checking for x86 if it is error.

**Comment by BrandonWanHuanSheng** [comment]
It look like that setup might restart the application.

**Comment by BrandonWanHuanSheng** [comment]
I got some new information with this file. It look like that PackageUrl is related to another URL.

**Comment by BrandonWanHuanSheng** [comment]
That setup is an portable program. How do we find the configuration file for https://officecdn.microsoft.com/pr/wsus/setup.exe

**Comment by BrandonWanHuanSheng** [comment]
https://github.com/microsoft/winget-pkgs/pull/105168#issuecomment-1533683007

**Comment by NLZ** [comment]
People make their configuration themselves:
https://learn.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options

Btw it seems the Microsoft.Office package also uses this, but immediately calls with a predefined config: 
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/Office/16.0.16227.20244/Microsoft.Office.installer.yaml
