### ISSUE TITLE
[Update Request]: cURL.cURL version 8.0.1

### ISSUE THREAD

**Issue by steff75** [microsoft/winget-pkgs#103917]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

cURL.cURL

### Package Version

8.0.1

### Please describe the changes you would like to see

There is a new release (8.0.1) available.

Download page: [https://curl.se/windows/](https://curl.se/windows/)

64-bit: [https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win64-mingw.zip](https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win64-mingw.zip)
32-bit: [https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win32-mingw.zip](https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win32-mingw.zip)
64-bit (ARM): [https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win64a-mingw.zip](https://curl.se/windows/dl-8.0.1_8/curl-8.0.1_8-win64a-mingw.zip)

**Comment by BrandonWanHuanSheng** [comment]
This one need another external tools to create

**Comment by steff75** [comment]
Added the url for the arm64-version.
