### ISSUE TITLE
Powershell and PowerShell-Preview have different cased names

### ISSUE THREAD

**Issue by yume-chan** [microsoft/winget-pkgs#1039]
# Description of the new feature/enhancement

Currently the Powershell package has a lower cased "s"

https://github.com/microsoft/winget-pkgs/blob/90c106976bcdcbb767ff4da935e281be43a35ec0/manifests/Microsoft/Powershell/7.0.1.yaml#L3

While the PowerShell-Preview package has a upper cased one

https://github.com/microsoft/winget-pkgs/blob/90c106976bcdcbb767ff4da935e281be43a35ec0/manifests/Microsoft/PowerShell-Preview/7.1.0-preview.3.yaml#L3

Since to install Powershell stable, we need to use the `--exact` option which is case-sensitive, this casing difference really confused me.

It's your own company's product, can you make is consistent?

# Proposed technical implementation details (optional)

**Comment by MarNicGit** [comment]
Solved by https://github.com/microsoft/winget-pkgs/pull/884

**Comment by yume-chan** [comment]
close as fixed
