### ISSUE TITLE
[Package Issue]: Meltytech.Shotcut does not get installed

### ISSUE THREAD

**Issue by lackovic** [microsoft/winget-pkgs#103967]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installation of `Meltytech.Shotcut` fails with error `Installer hash does not match.`

### Steps to reproduce

```
> winget install --id  Meltytech.Shotcut --verbose
```

### Actual behavior

```
Found Shotcut [Meltytech.Shotcut] Version 22.12.21
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/mltframework/shotcut/releases/download/v22.12.21/shotcut-win64-221221.exe
  ██████████████████████████████  99.2 MB / 99.2 MB
Installer hash does not match.
```

### Expected behavior

The application gets installed.

### Environment

```raw
> winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1635
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

[WinGet-2023-05-01-16-18-50.727.log](https://github.com/microsoft/winget-pkgs/files/11365525/WinGet-2023-05-01-16-18-50.727.log)

**Comment by BrandonWanHuanSheng** [comment]
Oh, I see. Which is hashes issues.

**Comment by lackovic** [comment]
Tried today and the installation went through:
```
> winget install --id  Meltytech.Shotcut --verbose
Found Shotcut [Meltytech.Shotcut] Version 22.12.21
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/mltframework/shotcut/releases/download/v22.12.21/shotcut-win64-221221.exe
  ██████████████████████████████  99.2 MB / 99.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
Thanks for fixing it!
