### ISSUE TITLE
[Package Issue]: LIGHTNINGUK.ImgBurn installs unwanted adware

### ISSUE THREAD

**Issue by ericswpark** [microsoft/winget-pkgs#104063]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The ImgBurn install routine installs Ask Toolbar, which is flagged by Microsoft Defender as a potentially unwanted program.

### Steps to reproduce

Install the `LIGHTNINGUK.ImgBurn` package

### Actual behavior

ImgBurn installs with Ask Toolbar

### Expected behavior

ImgBurn shouldn't install with Ask Toolbar (or any other adware/malware they bundle)

### Environment

```raw
Currently don't have access to my Windows machine but this part isn't relevant as it is a package installer bundling PUP issue.
```

**Comment by ericswpark** [comment]
According to some (admittedly old) forum posts over at ImgBurn:

- [Oh, hey! Ask Toolbar installed without asking.](https://forum.imgburn.com/topic/14830-oh-hey-ask-toolbar-installed-without-asking/)
- [Ask Toolbar](https://forum.imgburn.com/topic/14842-ask-toolbar/)
- [Launching the Ask Toolbar installer without user consent](https://forum.imgburn.com/topic/14944-launching-the-ask-toolbar-installer-without-user-consent/)
- [ImgBurn downloaded "Ask" toolbar, despite my unchecking that box.](https://forum.imgburn.com/topic/15027-imgburn-downloaded-ask-toolbar-despite-my-unchecking-that-box/)

Since I haven't found any recent forum posts about this issue, it might be that a flag needs to be specified during unattended installation.

**Comment by Trenly** [comment]
I booted a clean vm, installed chrome and firefox, then used winget to install imgburn and didn't see the Ask toolbar appear anywhere. Even going to the website and downloading the installer directly doesn't install the Ask toolbar for me.

I'm wondering if its locale specific? What language is your machine set to? Can you provide the URL that winget says it's downloading the package from?

**Comment by ericswpark** [comment]
@Trenly that is weird! I was running winget on Windows 10 with locale set to en.US, with the Korean language pack added. (The system language was in English).

It might be that ImgBurn wasn't actually the package that installed the Ask Toolbar. I was convinced that it was because it was the last package I installed with winget right before Windows Defender let me know Ask Toolbar was present on my system.

Actually, now that I think about it, it's possible that Windows Defender just flagged the installer executable in the temporary directory of winget, if the interactive installation includes a page where Ask Toolbar is offered. That would mean some part of Ask Toolbar is part of the executable.

Sorry about the false alarm! I will reopen this issue if I encounter it again and can verify that it's actually installed as opposed to just the installer executable getting flagged.
