### ISSUE TITLE
[Update Request]: Twilio.Authy

### ISSUE THREAD

**Issue by Lamera** [microsoft/winget-pkgs#104111]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Twilio.Authy

### Package Version

2.3.0

### Please describe the changes you would like to see

There is a new release: https://pkg.authy.com/authy/stable/2.3.0/win32/x64/Authy%20Desktop%20Setup%202.3.0.exe

**Comment by Lamera** [comment]
How often are packages checked for updates?

**Comment by mdanish-kh** [comment]
Close with reason: Resolved by #104054;

> How often are packages checked for updates?

At the moment, many packages included this one (that use a versioned URL) are manually updated by community contributors. If you find others, you are encouraged to create an issue or contribute it yourself if you wish by following the Contributor's Guide. Other packages that use a "vanity URL" (a URL that always points to the latest release) are automated by [winget-bot](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Awingetbot+Automatic+update) where the bot checks for hash mismatches daily and tries to update the package by retrieving the version from the downloaded installer.
