### ISSUE TITLE
[Package Request]: brow.sh

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/winget-pkgs#104234]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.brow.sh/downloads/
Publisher: [Thomas Buckley-Houston](https://tombh.co.uk/)
Package Name: ThomasBuckleyHouston.Browsh
Description: Browsh is a fully-modern text-based browser. It renders anything that a modern browser can; HTML5, CSS3, JS, video and even WebGL.
Package Version: 1.8.0
Installer URL: https://github.com/browsh-org/browsh/releases/download/v1.8.0/browsh_1.8.0_windows_amd64.exe

**Comment by rokejulianlockhart** [comment]
![image](https://user-images.githubusercontent.com/42837531/235769464-358be4f0-6421-4a66-860c-dd0335c6b813.png)

**Comment by mdanish-kh** [comment]
- Blocked by https://github.com/microsoft/winget-cli/issues/163

From the downloads page
> You need to have Firefox 57 or newer installed. For the TTY client you need to have a terminal with [true colour support](https://gist.github.com/XVilka/8346728).

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-pkgs/labels/Needs-Author-Feedback was mistakenly added and then removed by the bot.

> Consequently, can you add [microsoft/winget-cli#163 (comment)](https://github.com/microsoft/winget-cli/issues/163#issue-618664416) as a blocking issue here, or [#104234 (comment)](https://github.com/microsoft/winget-pkgs/issues/104234#issue-1692993890) as blocked by [microsoft/winget-cli#163 (comment)](https://github.com/microsoft/winget-cli/issues/163#issue-618664416), like https://github.com/bugzilla/bugzilla and https://github.com/phacility/phabricator can?

The issue is already labelled with https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue and https://github.com/microsoft/winget-pkgs/labels/Dependencies

**Comment by Dragon1573** [comment]
@RokeJulianLockhart - I'm working on this issue. 😄

During manually validation in Windows Sandbox, `browsh.exe` cannot launch `Mozilla.Firefox` (installed via `winget.exe`). I think this behaviour is not expected.

Shuld I add additional dependencies for this package? Or how should I validate this package manually?

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/e9ca9c06-48fc-423b-a079-adf5a612fb36)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> According to the _FAQs_ section on the download page, it seems there's some known issue with Windows releases.
>
> > ### It doesn’t work on Windows
> >
> > This is a known bug, it’s not been a top priority because of the main usecase described in the previous FAQ answer here. Please follow this [Github issue](https://github.com/browsh-org/browsh/issues/32) for updates.
>
> I'm facing the problem similar to https://github.com/browsh-org/browsh/issues/32#issuecomment-403816290, but I have no "panic". I can't solve this problem on my local Sandbox, so my PR (I don't submit them yet) will definitely fail in Azure Pipelines.
>
> We might not able to submit this package. 😞

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/104234#issuecomment-1862864419

@Dragon1573, we *could*, of course, submit an older (working) version of the package. However, I don't believe that that would be of much use, owing to the fact that we don't, to my knowledge, have a way of marking a package as obsolete in the CLI.

Consequently, considering that someone who has experienced the issue probably just needs to notify the developers (per https://github.com/browsh-org/browsh/issues/32#issuecomment-406499301) that the regression remains, can't we just leave this open until it's fixed, or close as unplanned and restart work on (and reopen) this when it has been fixed?

**Comment by Dragon1573** [comment]
@denelon,

According to above comments, this is still a https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue .

But https://github.com/microsoft/winget-pkgs/labels/Dependencies problem can be resolved as `Mozilla.Firefox` is currently available with `winget.exe`.

**Comment by tombh** [comment]
Thanks for pinging me. I'm afraid I'm not a Windows user and so these errors have always eluded me. If anybody wants to look into the problem will almost certainly be in this file: https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox_windows.go

**Comment by Dragon1573** [comment]
- [Line 36-43](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox_windows.go#L36-L43) and [line 62-65](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox_windows.go#L62-L65) contains a following snippet. What is it? Should it be added between line 24-25?
- At [line 25](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox_windows.go#L45C47-L45C47), `k.GetStringValue("")` gets an empty string as the key. It should be `"CurrentVersion"`.
- At [line 20](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox_windows.go#L20), the registry path should be
  ```go
  `Software\Mozilla\` + flavor + `\` + versionString + `\Main`
  ```

<details><summary>Changed code</summary>

```go
//go:build windows

package browsh

import (
	"fmt"
	"log/slog"
	"strings"

	"github.com/go-errors/errors"
	"golang.org/x/sys/windows/registry"
)

func getFirefoxPath() string {
	versionString := getWindowsFirefoxVersionString()
	flavor := getFirefoxFlavor()

	k, err := registry.OpenKey(
		registry.LOCAL_MACHINE,
		`Software\Mozilla\` + flavor + `\` + versionString + `\Main`,
		registry.QUERY_VALUE)
	if err != nil {
		Shutdown(fmt.Errorf("Error reading Windows registry: %w", err))
	}
        defer k.Close()

	path, _, err := k.GetStringValue("PathToExe")
	if err != nil {
		Shutdown(fmt.Errorf("Error reading Windows registry: %w", err))
	}

	return path
}

func getWindowsFirefoxVersionString() string {
	flavor := getFirefoxFlavor()

	k, err := registry.OpenKey(
		registry.LOCAL_MACHINE,
		`Software\Mozilla\` + flavor,
		registry.QUERY_VALUE)
	if err != nil {
		Shutdown(fmt.Errorf("Error reading Windows registry: %w", err))
	}
	defer k.Close()

	versionString, _, err := k.GetStringValue("CurrentVersion")
	if err != nil {
		Shutdown(fmt.Errorf("Error reading Windows registry: %w", err))
	}

	slog.Info("Windows registry Firefox", "version", versionString)

	return versionString
}

func getFirefoxFlavor() string {
	flavor := "null"
	k, err := registry.OpenKey(
		registry.LOCAL_MACHINE,
		`Software\Mozilla\Mozilla Firefox`,
		registry.QUERY_VALUE)

	if err == nil {
		flavor = "Mozilla Firefox"
	}
	defer k.Close()

	if flavor == "null" {
		k, err := registry.OpenKey(
			registry.LOCAL_MACHINE,
			`Software\Mozilla\Firefox Developer Edition`,
			registry.QUERY_VALUE)

		if err == nil {
			flavor = "Firefox Developer Edition"
		}
		defer k.Close()
	}

	if flavor == "null" {
		k, err := registry.OpenKey(
			registry.LOCAL_MACHINE,
			`Software\Mozilla\Nightly`,
			registry.QUERY_VALUE)

		if err == nil {
			flavor = "Nightly"
		}
		defer k.Close()
	}

	if flavor == "null" {
		Shutdown(errors.New("Could not find Firefox on your registry"))
	}
	return flavor
}

func ensureFirefoxVersion(path string) {
	versionString := getWindowsFirefoxVersionString()
	pieces := strings.Split(versionString, " ")
	version := pieces[0]
	if versionOrdinal(version) < versionOrdinal("57") {
		message := "Installed Firefox version " + version + " is too old. " +
			"Firefox 57 or newer is needed."
		Shutdown(errors.New(message))
	}
}
```

</details>

**Comment by Dragon1573** [comment]
I want to build this package with patches on my own using GitHub Workflows. Could @tombh please help me creating a workflow YAML file? I read [`SETUP_DEV_WIN.md`](https://github.com/browsh-org/browsh/blob/master/SETUP_DEV_WIN.md) but found there's no `build_browsh.sh` in the repository. 😞

- Build logs [here](https://github.com/Dragon1573/browsh/actions/runs/7272793122/job/19815529475#step:11:5)

**Comment by tombh** [comment]
Thanks for looking into this. I think these would be better discussed in the Browsh repo itself for others to benefit.

**Comment by Trenly** [comment]
[Policy] Blocking-Issue
[Policy] Area-External
