### ISSUE TITLE
Tailscale Manifest 

### ISSUE THREAD

**Issue by Teraskull** [microsoft/winget-pkgs#1050]
# Description of the new feature/enhancement

The Tailscale Manifest (manifests/Tailscale/Tailscale/0.98.0.0.yaml) has a problem with the name:

```Name: Tailscalehttps://pkgs.tailscale.com/stable/tailscale-ipn-setup-0.98-0.exe```

The download link is pasted next to the name.

**Comment by kn0rki** [comment]
@tiernano  Would you fix that?

**Comment by tiernano** [comment]
PR Created (https://github.com/microsoft/winget-pkgs/pull/1058)

**Comment by Teraskull** [comment]
Issue fixed (e2ca5bf)
