### ISSUE TITLE
[Update Request]: clawSoft.clawPDF

### ISSUE THREAD

**Issue by sreyruiz** [microsoft/winget-pkgs#105588]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

clawSoft.clawPDF

### Package Version

0.9.2

### Please describe the changes you would like to see

There is a new release (0.9.2) available.
Download page Url: https://github.com/clawsoftware/clawPDF/releases

**Comment by BrandonWanHuanSheng** [comment]
It might converted to draft because some of the dependcies failed to add in due to winget-cli

**Comment by Trenly** [comment]
[Policy] Dependencies

**Comment by BrandonWanHuanSheng** [comment]
We were still working on the pipelines. Two pipelines failed by what?
https://github.com/microsoft/winget-pkgs/issues/121946
