### ISSUE TITLE
[Package Request]: Sql server developer 2022 

### ISSUE THREAD

**Issue by DerekSMorin** [microsoft/winget-pkgs#106047]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://go.microsoft.com/fwlink/p/?linkid=2215158&clcid=0x1009&culture=en-ca&country=ca
Publisher: Microsoft
Package Name:
Description:
Package Version:
Installer URL:

**Comment by kkbruce** [comment]
Because the new MSSQL has no **full** `.exe` install type, only the initial install .exe type.
Do you just need the initial install .exe type? If yes, I can help make it.

**Comment by kkbruce** [comment]
Give me some time, and I'll make it.

**Comment by kkbruce** [comment]
Express: https://github.com/microsoft/winget-pkgs/pull/107220
Developer: https://github.com/microsoft/winget-pkgs/pull/107221

From the [previous discussion](https://github.com/microsoft/winget-pkgs/issues?q=is%3Aissue+SQLServer+is%3Aopen), it can be seen that none of them have been well resolved. After all, they are the official software of Microsoft, and those two PRs are what I can do to the maximum extent possible. I'm unsure if I can pass them, but I hope to have the opportunity to help.

**Comment by kkbruce** [comment]
@DerekSMorin good news

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/95aee89f-6591-477a-a7c8-657ec581c2bb)

**Comment by xtqqczze** [comment]
@kkbruce Can this issue be marked as completed?

**Comment by kkbruce** [comment]
Why not?

**Comment by xtqqczze** [comment]
@DerekSMorin @stephengillie Could you please close as completed?

@kkbruce For future reference, GitHub allows you [use a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link pull request to an issue, so that the issue will automatically close when the pull request is merged.

**Comment by DerekSMorin** [comment]
Marking this as completed.
