### ISSUE TITLE
[Update Request]: GnuWin32.GetText version 0.21.1

### ISSUE THREAD

**Issue by DefinitelyADev** [microsoft/winget-pkgs#106184]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GnuWin32.GetText

### Package Version

0.21.1

### Please describe the changes you would like to see

There are newer versions available that have multiple bugfixes.
Url: https://mlocati.github.io/articles/gettext-iconv-windows.html

**Comment by Trenly** [comment]
Is there a way to verify that the package at github - which appears to be from the publisher mlocati - is the same publisher as the sourceforge project - which appears to be gnuwin32?

**Comment by DefinitelyADev** [comment]
> Is there a way to verify that the package at github - which appears to be from the publisher mlocati - is the same publisher as the sourceforge project - which appears to be gnuwin32?

The above link it is directly referenced in the [gettext page](https://www.gnu.org/software/gettext/)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> For version `v0.21`, the package identifer has changed to `mlocati.GetText`. `GnuWin32.GetText` will NOT receive this version update. Please uninstall `GnuWin32.GetText` and reinstall `mlocati.GetText` after pull request is merged.
