### ISSUE TITLE
[Package Issue]: Piriform.CCleaner - Manifest version does not equal final package version

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-pkgs#106110]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After upgrading CCleaner, the version listed in the registry will be 6.11 as reported by winget, but winget upgrade will still see the manifest as a valid upgrade due to 6.11 being lower than 6.11.0.10455

### Steps to reproduce

Install CCleaner and then check for updates using winget upgrade

### Actual behavior

6.11 manifest is always seen as valid upgrade since version numbers do not match

### Expected behavior

Manifest and Package version agree

### Environment

```raw
Windows Package Manager (Preview) v1.5.1081-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1081.0

Winget Directories
-----------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bb…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bb…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/236638177-11b91d8f-b7c6-44ee-9efd-35c0f11bc1b8.png)

**Comment by BrandonWanHuanSheng** [comment]
That wingetbot caused it. Because Previous Pipeline is exactly wingetbot.

**Comment by Masamune3210** [comment]
I am aware, I made the issue because unless it is fixed, its just going to do the same thing the next time the bot makes the rounds.
