### ISSUE TITLE
[Package Request]: cf8-cli

### ISSUE THREAD

**Issue by codepwner** [microsoft/winget-pkgs#106116]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/cloudfoundry/cli/wiki/V8-CLI-Installation-Guide#installers-and-compressed-binaries
Publisher: https://www.cloudfoundry.org/
Package Name: cf8-cli
Description: The cf CLI is the official command line client for Cloud Foundry.
Package Version: 8.6.1 (currently)
Installer URL: 
    - 64-bit https://packages.cloudfoundry.org/stable?release=windows64&version=v8
    - 32-bit https://packages.cloudfoundry.org/stable?release=windows32&version=v8

There is also a related installer for version 7 of this application.  Ideally being able to run [winget install cf-cli] would match with both versions and prompt the user to pick from the two prominent versions.

**Comment by BrandonWanHuanSheng** [comment]
Please wait a moment. This will take a while because the setup have user and machine.

**Comment by codepwner** [comment]
Thank you!
