### ISSUE TITLE
[Package Request]: OneCommander

### ISSUE THREAD

**Issue by HernanH5582** [microsoft/winget-pkgs#106353]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://onecommander.com/
Publisher: One Commander
Package Name: OneCommander
Description: OneCommander is a modern file manager for Windows 10 and Windows 11. Features include tabs, dual-pane browsers, columns navigation, built-in preview, a theming system, color tags, and much more. It is free for home use and has no ads.
Package Version: 3.44.1.0
Installer URL: https://onecommander.com/OneCommanderSetup3.44.1.0.msi

**Comment by BrandonWanHuanSheng** [comment]
Creating with the scope and the type.

**Comment by BrandonWanHuanSheng** [comment]
It look like this installer support scope https://onecommander.com/OneCommanderSetup3.44.1.0.msi. What is the command?

**Comment by BrandonWanHuanSheng** [comment]
Failed to add Scope User.  😞 Because the pull request encountered Validation-Installation-Error while during adding on it.
