### ISSUE TITLE
[Update Request]: Upscayl.Upscayl

### ISSUE THREAD

**Issue by 14AUDDIN** [microsoft/winget-pkgs#106349]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Upscayl.Upscayl

### Package Version

2.5.1

### Please describe the changes you would like to see

There is a new release (2.5.1) available.
Download Page Url: https://github.com/upscayl/upscayl/releases
Exe downloader: https://github.com/upscayl/upscayl/releases/download/v2.5.1/upscayl-2.5.1-win.exe

**Comment by mdanish-kh** [comment]
Close with reason: Package added in #107175;
