### ISSUE TITLE
[Update Request]: dbeaver.dbeaver version 23.0.4

### ISSUE THREAD

**Issue by ianalexis** [microsoft/winget-pkgs#106386]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

dbeaver.dbeaver

### Package Version

23.0.4

### Please describe the changes you would like to see

https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe

**Comment by mrjcap** [comment]
Here you go: https://github.com/microsoft/winget-pkgs/pull/106426

Hopefully this will get merged into the master.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #106426;
