### ISSUE TITLE
[Package Request]: Pomatez

### ISSUE THREAD

**Issue by jnm2** [microsoft/winget-pkgs#106444]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://zidoro.github.io/pomatez/
Publisher: [Roldan Montilla Jr](https://github.com/roldanjr)
Package Name: Pomatez
Description: Stay Focused. Take a Break. 
Package Version: 1.2.3
Installer URL: https://github.com/zidoro/pomatez/releases/download/v1.2.3/Pomatez-v1.2.3-setup.exe

**Comment by mdanish-kh** [comment]
Close with reason: Stated above;
