### ISSUE TITLE
[Update Request]: Cosmos DB emulator

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/winget-pkgs#106439]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Azure.CosmosEmulator

### Package Version

2.14.9

### Please describe the changes you would like to see

There is a newer version available: `2.14.12-96d780da`
Download URL: https://cosmosdbportalstorage.azureedge.net/emulator/2023_03_19_2.14.12-96d780da/azure-cosmosdb-emulator-2.14.12-96d780da.msi

**Comment by BrandonWanHuanSheng** [comment]
I might guess could be wix or msi

**Comment by BrandonWanHuanSheng** [comment]
Checking for scope
