### ISSUE TITLE
[Package Request]: FFmpeg for Audacity

### ISSUE THREAD

**Issue by TheNavyBear** [microsoft/winget-pkgs#106460]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://lame.buanzo.org/ffmpeg.php
Publisher: Buanzo/Arturo Busleiman
Package Name: FFmpeg for Audacity
Description: FFmpeg Installer for Audacity 3.2 and later
Package Version: 5.0.0
Installer URL: https://lame.buanzo.org/FFmpeg_5.0.0_for_Audacity_on_Windows_x86_64.exe (64-bit)
https://lame.buanzo.org/FFmpeg_5.0.0_for_Audacity_on_Windows_x86.exe (32-bit)

**Comment by Dragon1573** [comment]
@TheNavyBear - See https://github.com/microsoft/winget-pkgs/pull/130784#issuecomment-1859150360, we are unable to submit this package to the repository. 😞
