### ISSUE TITLE
[Package Issue]: sharkdp.bat

### ISSUE THREAD

**Issue by fabiano** [microsoft/winget-pkgs#106463]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The environment variable added for the package is wrong. The installer adds to the PATH the folder `%LOCALAPPDATA%\Microsoft\WinGet\Packages\sharkdp.bat_Microsoft.Winget.Source_8wekyb3d8bbwe`, but the bat.exe is in `%LOCALAPPDATA%\Microsoft\WinGet\Packages\sharkdp.bat_Microsoft.Winget.Source_8wekyb3d8bbwe\bat-v0.23.0-x86_64-pc-windows-msvc`.

### Steps to reproduce

1. winget install sharkdp.bat
2. Restart the shell
3. Run `bat`

### Actual behavior

bat: The term 'bat' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Expected behavior

The .exe file to be in the user path.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment]
Does this occurr when using the latest preview release of winget (v1.5.1081-preview)?

There was a known CLI issue that should be patched in the preview -
* https://github.com/microsoft/winget-cli/issues/2909
* https://github.com/microsoft/winget-cli/pull/3002

**Comment by mrjcap** [comment]
I just tested it. No issue here.

Screenshot:
![image](https://github.com/microsoft/winget-pkgs/assets/3140504/186c3e5e-f8e6-4cab-84d9-8a79e16d7c69)

**Comment by helpimnotdrowning** [comment]
This issue occurs for a few more packages (for me at least): `Gyan.FFmpeg`, `Gyan.FFmpeg.Shared`, and `sharkdp.hyperfine`. The parent paths are added to the user PATH: 
`%localappdata%\Microsoft\WinGet\Packages\Gyan.FFmpeg.Shared_Microsoft.Winget.Source_8wekyb3d8bbwe`
`%localappdata%\Microsoft\WinGet\Packages\sharkdp.hyperfine_Microsoft.Winget.Source_8wekyb3d8bbwe`,
but the paths should be `Gyan.FFmpeg.Shared_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build-shared\bin` for ffmpeg and `harkdp.hyperfine_Microsoft.Winget.Source_8wekyb3d8bbwe\hyperfine-v1.16.1-x86_64-pc-windows-msvc` for hyperfine. Changing the paths in the PATH to the correct ones fixes the issue.

(I don't exactly know how the winget manifests work and all that, but the three packages *seem* to all specify the correct files in the `Installers.NestedInstallerFiles.RelativeFilePath` field(s) in their installer.yaml files)

**Comment by mdanish-kh** [comment]
@helpimnotdrowning

> Using:
>
>  Windows 11 22H2
>  Winget 1.4.10173

Please upgrade to [WinGet v1.5.1081-preview](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview) where this issue has been resolved

**Comment by Trenly** [comment]
@helpimnotdrowning - Do you see the same issue if you use version 1.5.1081-preview from the [releases page](/microsoft/winget-cli/releases)?

**Comment by helpimnotdrowning** [comment]
Gyan.FFmpeg installs and works perfectly fine now, but trying to install/uninstall/upgrade hyperfine make winget freeze when it writes "Starting package uninstall..." or "Starting package install...". 
![image](https://github.com/microsoft/winget-pkgs/assets/35247379/f93f306f-ea6d-4c5f-bda8-7174c1a66295)

**Comment by fabiano** [comment]
@Trenly I forgot to remove the package using v1.4.10173 and when I tried to do it using v1.5.1361-preview the command line frozen at this step:

![image](https://github.com/microsoft/winget-pkgs/assets/2686/f27eee17-7598-4104-b84b-cd568b6dab64)

**Comment by Trenly** [comment]
> I reinstalled v1.4.10173 and was able to remove the package. Then, I upgraded to v1.5.1361-preview and installed the package again. The bat.exe was added correctly to the path this time.

Great! Glad to hear this is resolved in the upcoming version of the client.
