### ISSUE TITLE
File path changed

### ISSUE THREAD

**Issue by qwordy** [microsoft/winget-pkgs#10657]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

Hi, I found all file path changed.
https://github.com/microsoft/winget-pkgs/tree/master/manifests
All my deployment scripts failed.
Anyway, I have fixed them.

# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by yigitemres** [comment]
File paths change because of https://github.com/microsoft/winget-cli/discussions/646.

**Comment by jedieaston** [comment]
More information is avaliable in #8900.

**Comment by denelon** [comment]
@qwordy we started the discussion @yigitemres mentioned in November and pinned https://github.com/microsoft/winget-pkgs/issues/8900 "PSA:  New Manifest Schema" in March for both the winget-cli and winget-pkgs repositories. I also tweeted Public Service Announcements about these changes. Do you have any other suggestions of where we could have put notice? Our intent was to keep the community informed.

What kind of deployment scripts were you referring to? The client also provided a notification when the schema changed. I'd like to understand your use case a bit better to see if there is something else we can do in the future to help with a smooth transition as the product evolves.

**Comment by qwordy** [comment]
Thank you all for so quick response. @denelon Thank you for tweeting the notice. I don't have better suggestions. . I was publishing Microsoft Azure CLI to winget. Old path is `manifests/Microsoft/AzureCLI`. New path is `manifests/m/Microsoft/AzureCLI`. Do I also need to change my `${CLI_VERSION}.yaml` file?

**Comment by jedieaston** [comment]
Yep. It needs to go under {cli_version}/Microsoft.AzureCLI.yaml now. 

Check out [Microsoft.WindowsTerminal](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsTerminal) for an example of how the file structure looks now.

**Comment by qwordy** [comment]
> 
> 
> Yep. It needs to go under ${CLI_VERSION}/Microsoft.AzureCLI.yaml now.
> 
> Check out [Microsoft.WindowsTerminal](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsTerminal) for an example of how the file structure looks now.

@jedieaston Thanks! We will read the new schema carefully and update the script. Windows Terminal is great!
