### ISSUE TITLE
[Package Issue]: ElectronicArts.EADesktop

### ISSUE THREAD

**Issue by xIUPITERx** [microsoft/winget-pkgs#107100]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

EA Desktop install fails because of wrong hash (+sketchy link?). 

### Steps to reproduce

try to install EA desktop via winget

### Actual behavior

Installer:
  Installer Type: burn
  Installer Url: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  Installer SHA256: c68acde54d602e9acf20b3e5148e6b0d933a2353201337a0b97828ab1b7de340

PS C:\Users\USER> winget install ElectronicArts.EADesktop
Found EA app [ElectronicArts.EADesktop] Version 12.184.0.5441
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  ██████████████████████████████  2.36 MB / 2.36 MB
Installer hash does not match.

### Expected behavior

EA APP should install without problems

### Environment

```raw
2023-05-17 19:09:56.184 [CORE] WinGet, version [1.4.10173], activity [{4D27157F-D251-4259-9CB4-8285ECD6BA9C}]
2023-05-17 19:09:56.184 [CORE] OS: Windows.Desktop v10.0.22621.1702
2023-05-17 19:09:56.184 [CORE] Command line Args: "C:\Users\USER\AppData\Local\Microsoft\WindowsApps\winget.exe" --info
2023-05-17 19:09:56.184 [CORE] Package: Microsoft.DesktopAppInstaller v1.19.10173.0
2023-05-17 19:09:56.184 [CORE] IsCOMCall:0; Caller: winget-cli
2023-05-17 19:09:56.188 [CLI ] WinGet invoked with arguments: '--info'
2023-05-17 19:09:56.188 [CLI ] Leaf command to execute: root
2023-05-17 19:09:56.189 [CLI ] Executing command: root
2023-05-17 19:09:56.199 [CORE] GetPathTo directory creation requested for [3], but path was not absolute: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
2023-05-17 19:09:56.211 [CLI ] Leaf command succeeded: root
```

**Comment by stephengillie** [comment]
[Akamai](https://www.akamai.com/) is a popular enterprise CDN.

**Comment by BrandonWanHuanSheng** [comment]
Configuring the new hashes, please wait a moments...

**Comment by FadeMind** [comment]
```
PowerShell 7.3.6
PS C:\Users\fademind> winget upgrade
Name       Id                       Version       Available     Source
----------------------------------------------------------------------
GOG GALAXY GOG.Galaxy               2.0.67.2      2.0.68.112    winget
EA app     ElectronicArts.EADesktop 12.251.0.5508 12.251.1.5504 winget
2 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS C:\Users\fademind> winget upgrade ElectronicArts.EADesktop
Found EA app [ElectronicArts.EADesktop] Version 12.251.1.5504
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  ██████████████████████████████  2.37 MB / 2.37 MB
Installer hash does not match; this cannot be overridden when running as admin
PS C:\Users\fademind>
```

**Comment by Chasapple4** [comment]
I can confirm that (tho EA had a newer version than the one WinGet found)

Found EA app [ElectronicArts.EADesktop] Version 13.67.0.5580
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  ██████████████████████████████  2.37 MB / 2.37 MB
Installer hash does not match.
PS C:\Users\usernamegoeshere> certUtil -hashfile C:\Users\usernamegoeshere\Downloads\EAappInstaller.exe SHA256
SHA256 hash of C:\Users\usernamegoeshere\Downloads\EAappInstaller.exe:
846260161a83526f13e02a4a5cfc821f46da73f51f6f4bca1f3adbb5d77acd7a
CertUtil: -hashfile command completed successfully.

That same file url gives me ElectronicArts.EADesktop Version 13.67.0.5582 vs 13.67.0.5580 that WinGet is listing so that might be why the Hash do not match as the file downloaded has a different hash

**Comment by Chasapple4** [comment]
Does EA have the SHA256 hash public that can be used to verify the hash of the file downloaded?

**Comment by wil2197** [comment]
This is still an issue. Any update on this. Amazing this has been left like this for so long.

Found an existing package already installed. Trying to upgrade the installed package...
Found EA app [ElectronicArts.EADesktop] Version 13.86.0.5599
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  ██████████████████████████████  2.37 MB / 2.37 MB
Installer hash does not match.

**Comment by Chasapple4** [comment]
> This is still an issue. Any update on this. Amazing this has been left like this for so long.
> 
> Found an existing package already installed. Trying to upgrade the installed package... Found EA app [ElectronicArts.EADesktop] Version 13.86.0.5599 This application is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe ██████████████████████████████ 2.37 MB / 2.37 MB Installer hash does not match.

The EA app might be a newer build with a different hash than what win get has for the current build they have listed
