### ISSUE TITLE
[New Feature]: Upgrade manual validation hardware

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#107639]
### Description of the new feature/enhancement

The absence of support for newer versions of opengl and lack of an audio driver on the manual validation VM causes launch errors that are specific to the pipeline and would not happen in the real world or even on a self set-up clean VM i.e. virtualbox (making this hard for new contributors to preemptively test for). This blocks PRs like https://github.com/microsoft/winget-pkgs/pull/107110 https://github.com/microsoft/winget-pkgs/pull/107333 https://github.com/microsoft/winget-pkgs/pull/107211 https://github.com/microsoft/winget-pkgs/pull/106964 https://github.com/microsoft/winget-pkgs/pull/107075 and would have blocked developer tools like https://github.com/microsoft/winget-pkgs/pull/107422 if not for the latter clearly stating it requires opengl 3.3+ - supported on GPUs in the last five years and near ubiquitous on windows 11. Open source programs and games lean on the newer side of opengl support since mesa is the default graphics package for most of their Linux users, so this may become a more common issue for some of the packages already in winget.

### Proposed technical implementation details (optional)

A better gpu driver and an audio device would resolve these issues.

**Comment by stephengillie** [comment]
Some research notes:
- Add-VMRemoteFx3dVideoAdapter -VMName
- https://social.technet.microsoft.com/wiki/contents/articles/31771.server-2016-experience-guide-enabling-opengl-support-for-vgpu.aspx
- https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploy-graphics-devices-using-remotefx-vgpu

**Comment by stephengillie** [comment]
The host may require some modification: 
```
WARNING: We no longer support the RemoteFX 3D video adapter. If you are still using this adapter, you may become vulnerable to security risks. Learn more (https://go.microsoft.com/fwlink/?linkid=2131976)
Add-VMRemoteFx3dVideoAdapter: Hyper-V cannot add a RemoteFX 3D video adapter to this virtual machine. To add this adapter, the host must have at least one graphics processing unit (GPU) that supports RemoteFX and that meets the minimum requirements for DirectX.
```

**Comment by stephengillie** [comment]
> Related: [Request](https://github.com/microsoft/winget-pkgs/pull/109817#issuecomment-1592301357) to revert Manual Validation pipeline to Windows 10, except for situations where `MinimumOSVersion` demands Windows 11.

Windows 10 pipeline VMs operational, completing this section.

**Comment by stephengillie** [comment]
In-PR: 
* https://github.com/microsoft/winget-pkgs/pull/110987

**Comment by stephengillie** [comment]
Need 32-bit OSes: 
* https://github.com/microsoft/winget-pkgs/pull/117891

**Comment by stephengillie** [comment]
For reference: Winget List installed packages:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/e26d3fea-1e75-4b52-9783-192201860b29)

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
