### ISSUE TITLE
[Package Issue]: dotPDNLLC.paintdotnet

### ISSUE THREAD

**Issue by juergenpf** [microsoft/winget-pkgs#107679]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The version 5.0.3 zip file that the installer tries to download doesn't exist. The URL reports "not found"
Installation faile

### Steps to reproduce

winget install --id dotPDNLLC.paintdotnet

### Actual behavior

Installation fails, reporting a not found error

### Expected behavior

Installation succeeds

### Environment

```raw
Windows-Paket-Manager v1.4.10173
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.1702
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Benutzereinstellungen: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by licon4812** [comment]
resolved by #107563

**Comment by Trenly** [comment]
We'll see if a different PR passes the dynamic scan

**Comment by Trenly** [comment]
Close with reason: Resolved by 107563;
