### ISSUE TITLE
[Package Issue]: Genymobile.scrcpy

### ISSUE THREAD

**Issue by headquarter8302** [microsoft/winget-pkgs#107858]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The symlink generated in `%LOCALAPPDATA%\Microsoft\WinGet\Links` is either faulty, or nonfunctional.

See Genymobile/scrcpy/issues/4027 for a more complete description

### Steps to reproduce

1. Install the package as usual. `winget install Genymobile.scrcpy`
2. Let Winget proceed with the installation

### Actual behavior

* The symlink `scrcpy` doesn't work. See aforementioned linked issue.

### Expected behavior

* The symlink to work as usual.

### Environment

```raw
└ ❯ winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-05-23-04-37-55.375.log](https://github.com/microsoft/winget-pkgs/files/11541501/WinGet-2023-05-23-04-37-55.375.log)

**Comment by mdanish-kh** [comment]
[Policy] zip-binary

This is because the portable package depends on `.dlls` that can't be referenced via a symlink.

One workaround is to upgrade to the latest preview version of WinGet and install the package in a non-administrative / user shell (with developer mode turned off in Windows). This would prevent symlink creation and would force WinGet to put the entire path of the portable package directly into the PATH variable.

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`
