### ISSUE TITLE
[Package Issue]: Parsec.Parsec

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#107862]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

```
PS C:\Users\ruruo> winget install -h Parsec.Parsec
Found Parsec [Parsec.Parsec] Version 150-86h
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://builds.parsecgaming.com/package/parsec-windows.exe
  ██████████████████████████████  2.74 MB / 2.74 MB
Installer hash does not match; this cannot be overridden when running as admin
```

### Steps to reproduce

`winget install -h Parsec.Parsec`

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Package installed.

### Environment

```raw
Windows Package Manager (Preview) v1.5.1081-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1081.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by adripo** [comment]
Thank you. I just tested and the version downloaded from the url `https://builds.parsecgaming.com/package/parsec-windows.exe` is `150-87c`, as per my logs:
```
[F 2023-05-25 21:35:06] ===== Parsec: Started =====
[D 2023-05-25 21:35:06] log: Parsec release (150-87c)
[D 2023-05-25 21:35:06] supdater_fetch: pservice.exe is up to date
[D 2023-05-25 21:35:06] supdater_fetch: parsecd.exe is up to date
```
I think we should revert the version to `150-87c` for now until the next version is out.

**Comment by adripo** [comment]
I found the source of this misunderstanding: https://parsec.app/changelog

The "App" has the old version number, while the "Teams" has the one with year and date:

![image](https://github.com/microsoft/winget-pkgs/assets/26493496/45cc8b6b-6ad0-4d3c-b96e-333532520519)
![image](https://github.com/microsoft/winget-pkgs/assets/26493496/dfca0b95-4283-4c4d-9afa-db271c425c3d)

**Comment by adripo** [comment]
You are right, it was me before updating from winget. Let me do some investigation

**Comment by adripo** [comment]
I closed the PR in the meantime.
It's a very strange behavior. I removed everything and done a clean setup and in the control panel I see `150-87d`, but after opening the app, in the settings I see version `150-87c`

![image](https://github.com/microsoft/winget-pkgs/assets/26493496/75daf789-ca5b-4365-aaf0-6cdafb656bc4)

**Comment by adripo** [comment]
After rebooting windows the version returned to `150-87c` also in control panel. I think we should keep it with c until the next release is out. Will reopen the PR.
