### ISSUE TITLE
[Package Issue]: Ngrok.Ngrok

### ISSUE THREAD

**Issue by licon4812** [microsoft/winget-pkgs#107857]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

winget bot isn't automatically creating an upgrade manifest even though the download URL isn't changing only the version and installer hash are.

I can manually add the updates but would prefer the bot to each time

### Steps to reproduce

winget install ngrok

check download page here

https://ngrok.com/download

### Actual behavior

installer mismatch due to winget bot not updating the package

### Expected behavior

for winget bot to automatically update the manifest

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
I believe this is because, as a zip file, there is no way for msftbot to get the version information. Without the version information, the bot doesn't know where to create the new manifest. 

@denelon - This is a great example of when msftbot should open a new issue if a hash mismatch is detected like it used to do

**Comment by BrandonWanHuanSheng** [comment]
What wingetbot use to get those information?

**Comment by BrandonWanHuanSheng** [comment]
Suspected could be v 3.3.0

**Comment by licon4812** [comment]
Maybe we can include the command to get the version in the manifest. Ngrok is a command line portable package that returns its version by going

ngrok.exe -v


Or ngrok -v if it was added to path.


Maybe we can add this feature for all portable packages that aren't installers?

**Comment by licon4812** [comment]
I am happy to manually keep adding the updates, but having the winget bot able to detect portable version would be wicked

**Comment by marty0678** [comment]
Has this regressed in 3.3.5?

```
PS C:\Users\marty> winget update --all
Name  Id          Version Available Source
------------------------------------------
Ngrok Ngrok.Ngrok 3.3.1   3.3.5     winget
1 upgrades available.

Installing dependencies:
(1/1) Found Ngrok [Ngrok.Ngrok] Version 3.3.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
  ██████████████████████████████  8.65 MB / 8.65 MB
Installer hash does not match.
```

**Comment by Zelgadis87** [comment]
Same issue with Ngrok 3.5.0

**Comment by oyjXkIfbSVdIJxCJDH8N** [comment]
Same issue with Ngrok 3.8.0

**Comment by tymokvo** [comment]
Also still seeing this with `Ngrok.Ngrok 3.5.0`.

**Comment by sql-sith** [comment]
_Still_ seeing this with Ngrok.Ngrok 3.5.0.
