### ISSUE TITLE
[Package Issue]: Dell.DisplayManager

### ISSUE THREAD

**Issue by TheAlienDrew** [microsoft/winget-pkgs#107808]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Trying to update Dell Display Manager from 2.0 to 2.1.x from winget causes issues, depending on where the installer is located.

In this case, since the installer is downloaded to `C:\Users\axla\AppData\Local\Temp\WinGet\Dell.DisplayManager.2.1.1.17\ddmsetup.exe`, ddmsetup.exe doesn't elevate correctly...

However, if trying to navigate to this directory and trying to elevate manually, it also errors out the same way. The only way to elevate the program properly is to move it to another folder outside of the AppData folders (e.g. to the user's downloads folder), and then open and elevate from there.

### Steps to reproduce

1. Make sure that Dell Display Manager 2.0 is installed
2. Run `winget upgrade --id Dell.DisplayManager` as an unelevated (non-admin) user.
3. Elevate with an admin user when the prompt shows for install.

### Actual behavior

Fails to install, thinks the user is aborting the install, when that's in fact not the case.

### Expected behavior

Should upgrade from 2.0 to the 2.1.x version of Dell Display Manager.

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-05-22-16-28-52.418.log](https://github.com/microsoft/winget-pkgs/files/11537744/WinGet-2023-05-22-16-28-52.418.log)

**Comment by mdanish-kh** [comment]
Can you please install the latest preview version of WinGet from [aka.ms/getwingetpreview](https://aka.ms/getwingetpreview) and see if the package upgrades correctly for you?

There was a known CLI bug related to permissions on the TEMP folder that was patched in the preview version. That may be the fix here?
- https://github.com/microsoft/winget-cli/issues/2740
- https://github.com/microsoft/winget-cli/pull/2945

**Comment by TheAlienDrew** [comment]
Tested this today, appears to be fixed now. Closing.
