### ISSUE TITLE
Viber.Viber is missing

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#107968]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I try to install Viber.Viber via command :

winget install Viber.Viber

Output is : 

PS C:\Users\> winget install Viber.Viber
No package found matching input criteria.
PS C:\Users\> winget search viber
Name  Id             Version Source
-------------------------------------
Viber XPFM5P5KDWF0JP Unknown msstore
PS C:\Users\>

### Steps to reproduce

 winget install Viber.Viber

### Actual behavior

No package found matching input criteria.

### Expected behavior

To be installed successfully.

### Environment

```raw
PS C:\Users\> winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\>
```

**Comment by BrandonWanHuanSheng** [comment]
> This seems to have occurred due to the `19.9.0.0` version being [automatically removed](https://github.com/microsoft/winget-pkgs/pull/105939) due to a hash mismatch, then both the [first attempt](https://github.com/microsoft/winget-pkgs/pull/105928) and the [second attempt](https://github.com/microsoft/winget-pkgs/pull/105935) to add version `19.9.0.6` failed because the `PublisherSupportUrl: https://help.viber.com/en` was unavailable.

I found. out the broken URL.
