### ISSUE TITLE
[Package Request]: AirID Installer for Windows

### ISSUE THREAD

**Issue by RufusJWB** [microsoft/winget-pkgs#108081]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://confluence.certgate.com/display/DEMTHSP/Download+Center#DownloadCenter-Win1
Publisher: https://airid.com/unternehmen/ueber-certgate/
Package Name: AirID Installer for Windows
Description: AirID Central and Driver installation for Windows, Winusbcompat
Package Version: 210906
Installer URL: https://confluence.certgate.com/download/attachments/102763475/AirID-Installer-210906.exe?version=1&modificationDate=1672913319615&api=v2

**Comment by Dragon1573** [comment]
@RufusJWB - Sorry, we're unable to submit this package to the repository. 😞

This package requires and authentication installing a driver for a kind of card reader. This authentication process cannot be unattended and will block the whole installation process.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a8b8efd0-b513-4a6c-8c6b-77946cfb875c)

**Comment by Dragon1573** [comment]
This issue can be closed as "Not planned".

**Comment by RufusJWB** [comment]
Thank you anyhow a lot for your support!

**Comment by Dragon1573** [comment]
Pull requests for submitting a package should pass ALL checks on Azure Pipelines. This pipeline executes everything automatically and unattendedly. However, this package will ask user inputs for explicitly accept and authenticate itself to install a driver (system level "core executable").

For the above reason, this package will DEFINITELY fail on the pipelines and have NO possibilities to pass the test. 😞
