### ISSUE TITLE
[Update Request]: Treat all Geekbench versions as different packages

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-pkgs#108043]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

PrimateLabs.Geekbench

### Package Version

all

### Please describe the changes you would like to see

Each Geekbench version has different benchmarking style, can be installed side by side with another, and are treated like seperate packages, and each has it's own results server. This is similar to Scratch. 

I request to move each Geekbench version's manifests to it's own package, maybe except Geekbench 6 which keeps it's original package area for the sake of it.

**Comment by upintheairsheep** [comment]
@stephengillie I've appreciated your work with moving folders, basically saving these pulls from stale closure

**Comment by stephengillie** [comment]
If I'm understanding correctly, the goal here is to modify all Geekbench manifests, to include their major version in their PackageIdentifier, so that major versions can be installed side-by-side.

**Comment by upintheairsheep** [comment]
> If I'm understanding correctly, the goal here is to modify all `PrimateLabs.Geekbench` manifests, to include their major version in their PackageIdentifier, so that major versions can be installed side-by-side.
> 
> Edit: This appears to already be the case, with [PrimateLabs.Geekbench.4](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PrimateLabs/Geekbench/4/4.3.3), [PrimateLabs.Geekbench.5](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PrimateLabs/Geekbench/5), and [PrimateLabs.Geekbench.6](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PrimateLabs/Geekbench/6).
> 
> Can I help with anything else?

OK. I misread them as versions. Please move my manifests accordingly.
