### ISSUE TITLE
7-Zip failing to install (0x8a15004a)

### ISSUE THREAD

**Issue by Pckgrapp** [microsoft/winget-pkgs#108155]
After the package was recently updated in the last two days 7-Zip fails to install in the SYSTEM context with the following error:

Found 7-Zip [7zip.7zip] Version 22.01
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
An unexpected error occurred while executing the command: 
0x8a15004a : Arguments for msiexec are invalid

This was working perfectly fine before the manifest was updated.

**Comment by BrandonWanHuanSheng** [comment]
Is that MSI application?

**Comment by Pckgrapp** [comment]
Yes, it's MSI:

Installer:
  Installer Type: wix
  Installer Locale: en-US
  Installer Url: https://7-zip.org/a/7z2201-x64.msi
  Installer SHA256: f4afba646166999d6090b5beddde546450262dc595dddeb62132da70f70d14ca
  Release Date: 2022-07-15

**Comment by Pckgrapp** [comment]
> Is that MSI application? Silent Switches are quite differently. Most MSI use /quiet.

I'm using the following command which has worked for over a year: & $wingetPaths install --id Zoom.Zoom --silent --accept-package-agreements --accept-source-agreements

**Comment by BrandonWanHuanSheng** [comment]
The manifest contains some NullSoft applications but it did not display out on 7zip.7zip instead of MSI 7zip.7zip

**Comment by Pckgrapp** [comment]
So I still get this: PS C:\Windows\system32> winget install --id 7zip.7zip --silent
Found 7-Zip [7zip.7zip] Version 22.01
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
An unexpected error occurred while executing the command:
0x8a15004a : Arguments for msiexec are invalid

Are you suggesting that --silent needs to be removed from the command? I'm confused why that is now breaking it.

**Comment by BrandonWanHuanSheng** [comment]
> So I still get this: PS C:\Windows\system32> winget install --id 7zip.7zip --silent Found 7-Zip [7zip.7zip] Version 22.01 This application is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Successfully verified installer hash Starting package install... An unexpected error occurred while executing the command: 0x8a15004a : Arguments for msiexec are invalid
> 
> Are you suggesting that --silent needs to be removed from the command? I'm confused why that is now breaking it.

No, I just delete Installer Silent Switches.

**Comment by Pckgrapp** [comment]
Must have been a delay for my device, it's working perfectly now. Thanks for your help and prompt response :)

**Comment by BrandonWanHuanSheng** [comment]
> Must have been a delay for my device, it's working perfectly now. Thanks for your help and prompt response :)

The delay is waiting for the pull-request to publish.

**Comment by BrandonWanHuanSheng** [comment]
When I add Installer Slient Switch: /S,  it look like MSI returns an error but only exe works. When I add Installer Silent Switch: /quiet. It look like exe does not work. Most likely, I can try to use custom commands. Also, Azure Pipelines did not report Validation-Installation-Unattended-Failure

**Comment by BrandonWanHuanSheng** [comment]
It look like Installer Silent Switches is unable to use in the root nodes. It failed on the Validation-Pull-Request

**Comment by BrandonWanHuanSheng** [comment]
See winget warning.

Manifest validation failed.
Manifest Error: Schema Error. [Schema validation failed.
Error context: <root>[Installers][0][InstallerSwitches] Description: Value type not permitted by 'type' constraint.
Error context: <root>[Installers][0] Description: Failed to validate against schema associated with property name 'InstallerSwitches'.
Error context: <root>[Installers] Description: Failed to validate item #0 in array.
Error context: <root>[Installers][1][InstallerSwitches] Description: Value type not permitted by 'type' constraint.
Error context: <root>[Installers][1] Description: Failed to validate against schema associated with property name 'InstallerSwitches'.
Error context: <root>[Installers] Description: Failed to validate item #1 in array.
Error context: <root>[Installers][2][InstallerSwitches] Description: Value type not permitted by 'type' constraint.
Error context: <root>[Installers][2] Description: Failed to validate against schema associated with property name 'InstallerSwitches'.
Error context: <root>[Installers] Description: Failed to validate item #2 in array.
Error context: <root>[Installers][3][InstallerSwitches] Description: Value type not permitted by 'type' constraint.
Error context: <root>[Installers][3] Description: Failed to validate against schema associated with property name 'InstallerSwitches'.
Error context: <root>[Installers] Description: Failed to validate item #3 in array.
Error context: <root>[Installers][4][InstallerSwitches] Description: Value type not permitted by 'type' constraint.
Error context: <root>[Installers][4] Description: Failed to validate against schema associated with property name 'InstallerSwitches'.
Error context: <root>[Installers] Description: Failed to validate item #4 in array.
Error context: <root> Description: Failed to validate against schema associated with property name 'Installers'.
] File: 7zip.7zip.installer.yaml
Manifest Warning: Unknown field. [Silent]
Manifest Warning: Unknown field. [Silent]
Manifest Warning: Unknown field. [Silent]
Manifest Warning: Unknown field. [Silent]
Manifest Warning: Unknown field. [Silent]
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
