### ISSUE TITLE
YamlCreate: Latest version is terribly slow with processing exe-installers 

### ISSUE THREAD

**Issue by borque** [microsoft/winget-pkgs#108264]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The latest version of YamlCreate.ps1 is terribly slow when processing exe-installers, while it is working normally on msi-installers:

I updated the Thunderbird manifests to version 102.11.1 yesterday with an older (don't know exactly which) versions of YamlCreate, using Quick-Update. Everthing worked as expected and processing all the various installers (languages as well as types) took about 10-15 seconds each.

After finishing I updated my local YamlCreate.ps1 with the current version available here. 

Unfortunately Mozilla released a hotfix bumping Thunderbird to version 102.11.2 last night and I wanted to provide this today.
While all the msi-installers process at normal speed with the new YamlCreate, processing the exe-installers takes 60-90 seconds each now.

No other changes were done on my system and there is no high CPU- or SSD-load and there are no other processes running explaining this. And, yes, it is "processing" that takes so long, downloadspeed is normal.

@Trenly : any ideas?

PS: I will be away from my desk the coming week, so my responses here might be rather slow.

### Steps to reproduce

see above

### Actual behavior

see above

### Expected behavior

see above

### Environment

```raw
Windows-Paket-Manager v1.4.10173
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.2965
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

None

**Comment by Trenly** [comment]
This is probably due to it now scanning to try and detect if an exe is a Burn installer. I might have to remove that feature if its being too slow
