### ISSUE TITLE
[Update Request]: Arm.GnuArmEmbeddedToolchain

### ISSUE THREAD

**Issue by seppeon** [microsoft/winget-pkgs#108352]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Arm.GnuArmEmbeddedToolchain

### Package Version

10 2021.10

### Please describe the changes you would like to see

There is a few new versions available:

12.2 is what I see here: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

The gnu-rm version that you have on winget was deprecated (see https://developer.arm.com/downloads/-/gnu-rm).

**Comment by seppeon** [comment]
Gday, just noting, the version currently on winget is officially deprecated.

**Comment by Trenly** [comment]
> Gday, just noting, the version currently on winget is officially deprecated.

Is the new software "Arm Gnu Toolchain" a direct replacement for "Arm Gnu Embedded Toolchain" or can they exist side by side on the same machine?

**Comment by seppeon** [comment]
You can have them both, in the same way you could have 10.3 + 9.3 etc...
Often times people will want multiple versions in order to re-compile something with the same tooling.

**Comment by seppeon** [comment]
I will try submit a PR :)

**Comment by seppeon** [comment]
https://github.com/microsoft/winget-pkgs/pull/110755
