### ISSUE TITLE
PowerBI installer hash does not match: Microsoft.PowerBI

### ISSUE THREAD

**Issue by GHArchitecht** [microsoft/winget-pkgs#108372]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

winget install Microsoft.PowerBI fails and prints output "Installer hash does not match".
Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.116.966.0

### Steps to reproduce

winget install Microsoft.PowerBi

### Actual behavior

[winget install Microsoft.PowerBi] fails  
prints output "installer hash does not match"

### Expected behavior

Microsoft.PowerBi "Successfully installed" output

### Environment

```raw
[winget --info]
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

From Logs
[CLI ] Package hash verification failed. SHA256 in manifest [0cd2df60651e65f369780bc808885a0b124a0062edec915220633bd93c188f04] does not match download [55832ac2280f1757a6abbc6ed9ee875504d4c886b664f0c56de65851cec17cb9]

**Comment by GHArchitecht** [comment]
`Winget search "PowerBi"` produces the following output
Name - Id - Version - Match - Source
---------------------------------------------------------------------------------
Microsoft PowerBI Desktop - Microsoft.PowerBI - **2.116.966.0** - Moniker: powerbi - winget

Downloaded and installed the PBIDesktopSetup_x64.exe file and typed the `Winget list`
Microsoft PowerBI Desktop (x64) - Microsoft.PowerBI - **2.117.984.0**  -  -  winget

`winget install Microsoft.PowerBI`                                                        
Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.116.966.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe

**Comment by BrandonWanHuanSheng** [comment]
This metadata keep changing. I might know the version after upgrading
