### ISSUE TITLE
[Update Request]: icsharpcode.ILSpy

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/winget-pkgs#108304]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

icsharpcode.ILSpy

### Package Version

8.0.0.7345

### Please describe the changes you would like to see

There is a new release available (8.0.0.7345). Also see https://github.com/icsharpcode/ILSpy/releases/tag/v8.0.
Installer url: https://github.com/icsharpcode/ILSpy/releases/download/v8.0/ILSpy_Installer_8.0.0.7345.msi

**Comment by Trenly** [comment]
Close with reason: Resolved by above linked PR;
