### ISSUE TITLE
[Update Request]: Windows Terminal Preview

### ISSUE THREAD

**Issue by brkerez** [microsoft/winget-pkgs#108420]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.WindowsTerminal.Preview

### Package Version

1.18.1462.0

### Please describe the changes you would like to see

There is a new release 1.18.1462.0 available.
https://github.com/microsoft/terminal/releases

**Comment by BrandonWanHuanSheng** [comment]
Oh, this pull request will converted to draft because it need to check the store commit for Microsoft.UI.Xaml_2.7.

**Comment by BrandonWanHuanSheng** [comment]
See #108349

**Comment by Trenly** [comment]
[Policy] Dependencies

**Comment by Dragon1573** [comment]
Seems this issue is already solved for a long time. It's time to close it as "completed". ❤️

**Comment by stephengillie** [comment]
This package appears to depend on `Microsoft.UI.Xaml.2.7`, which is available.
