### ISSUE TITLE
[Update Request]: calibre.calibre

### ISSUE THREAD

**Issue by byteborg** [microsoft/winget-pkgs#108519]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

calibre.calibre

### Package Version

6.19.1

### Please describe the changes you would like to see

https://github.com/kovidgoyal/calibre/releases/tag/v6.19.1

**Comment by pxwiz** [comment]
@byteborg,  new version is now available.  Cheers!

**Comment by stevenzhu25** [comment]
Fixed with #108781 by @pxwiz
