### ISSUE TITLE
[Package Issue] Hash mismatch error when attempting to install Microsoft.PowerBI from "winget" public repository

### ISSUE THREAD

**Issue by AnoopKumarEY** [microsoft/winget-pkgs#108649]
When attempting to install Microsoft.PowerBI from "winget" public repository using the command "winget install Microsoft.PowerBI" through PowerShell, the installer will download correctly but will fail on the hash verification stage, reporting the error "Installer hash does not match; this cannot be overridden when running as admin"

App details as below

Name                       	Id                  	Version     	Match            	Source
-------------------------------------------------------------------------------------------------------
Microsoft PowerBI Desktop 	Microsoft.PowerBI   	2.117.984.0 	Moniker: powerbi 	winget

**Comment by Trenly** [comment]
Close with reason: Version was updated to 2.118.621.0; 
This issue may pop up again the next time a new version of PowerBI is released

* #109686
