### ISSUE TITLE
[Update Request]: qBittorrent.qBittorrent version 4.5.3

### ISSUE THREAD

**Issue by ianalexis** [microsoft/winget-pkgs#108763]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

qBittorrent.qBittorrent

### Package Version

4.5.3

### Please describe the changes you would like to see

There is a new release (4.5.3) available.
Download Page Url:
https://www.fosshub.com/qBittorrent.html?dwl=qbittorrent_4.5.3_x64_setup.exe
https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.5.3/qbittorrent_4.5.3_x64_setup.exe/download
https://sitsa.dl.sourceforge.net/project/qbittorrent/qbittorrent-win32/qbittorrent-4.5.3/qbittorrent_4.5.3_x64_setup.exe

**Comment by stevenzhu25** [comment]
Fixed with #108811
