### ISSUE TITLE
[Package Request]: yt-dlp-nightly

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#108836]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/yt-dlp/yt-dlp-nightly-builds
Publisher: yt-dlp
Package Name: yt-dlp-nightly
Description:  yt-dlp nightly builds 
Package Version: 2023.06.03.063406
Installer URL: https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2023.06.03.063406/yt-dlp.exe

**Comment by BrandonWanHuanSheng** [comment]
It look like the pull request was merged and closed.

**Comment by soredake** [comment]
@BrandonWanHuanSheng thank you!
