### ISSUE TITLE
[Package Issue]: Anki.Anki

### ISSUE THREAD

**Issue by arnavbhate** [microsoft/winget-pkgs#109046]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Upgrading Anki to 2.1.64 fails because `UpgradeBehavior` is set to `install` and not `uninstallPrevious`. The installer now requires that any previous versions of Anki be uninstalled before installing a new version.

### Steps to reproduce

1. Install Anki version 2.1.63
```none
winget install Anki.Anki -v 2.1.63
```
2. Upgrade Anki
```none
winget upgrade Anki.Anki
```

### Actual behavior

The installer launches the uninstaller of the previous version of Anki and exits with a non-zero error code. The uninstaller runs but then the installer is not launched again.

### Expected behavior

The previous version of Anki is uninstalled either by WinGet or by the Anki installer before the new version is installed.

### Environment

```raw
Windows Package Manager (Preview) v1.5.1081-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1081.0
```

**Comment by mdanish-kh** [comment]
The installer itself requests for an uninstall once it detects a previous version in the system but the uninstall is not unattended/silent. Even if we include `UpgradeBehavior: uninstallPrevious` in the manifest, it does not resolve the issue. You can confirm this by using the `--uninstall-previous` experimental arg in the current preview version of WinGet, which has the same effect as `UpgradeBehavior: uninstallPrevious` in the manifest.

Are there are any command line switches that can bypass the interactive prompts during the uninstall? If so we can add them in the manifest and make the uninstall silent. But even if that's resolved, it seems the uninstaller returns a success code even though the package isn't uninstalled completely that signals WinGet to proceed with the **installation** process. I believe the issue should be raised up to the publisher for a fix.

![image](https://github.com/microsoft/winget-pkgs/assets/88161975/fe947b0e-e675-46c4-b90b-006da483316c)

**Comment by mdanish-kh** [comment]
[Policy] reset feedback
