### ISSUE TITLE
[Package Request]: TinyGo

### ISSUE THREAD

**Issue by andreabertanzon** [microsoft/winget-pkgs#109049]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://tinygo.org/getting-started/install/windows/
Publisher: The TinyGo Authors
Package Name: TinyGo
Description: TinyGo brings the [Go programming language](https://golang.org/) to embedded systems and to the modern web by creating a new compiler based on [LLVM](https://llvm.org/).
Package Version: 0.27.0
Installer URL: https://tinygo.org/getting-started/install/windows/

**Comment by BrandonWanHuanSheng** [comment]
Blocking issue with https://github.com/microsoft/winget-cli/issues/163

**Comment by BrandonWanHuanSheng** [comment]
So, the pull request has been converted to draft due to it requires GoLang.Go dependcies. Winget will support for package dependcies in the future.
