### ISSUE TITLE
[Package Issue]: Eugeny.Tabby --> CURRENTUSER switch on machine install

### ISSUE THREAD

**Issue by NJT145** [microsoft/winget-pkgs#109218]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

There is a custom switch on all installers of Eugeny.Tabby, and this make the machine install unavailable. Need to remove this switch and add CURRENTUSER and ALLUSERS switches to specific installers.

### Steps to reproduce

I tried `winget install -e -i --id=Eugeny.Tabby --source=winget --scope=machine` but it still install as CURRENTUSER.

### Actual behavior

When I use `--scope=machine`, it is installing as CURRENTUSER.

### Expected behavior

When I use `--scope=machine`, it must install as ALLUSERS.

### Environment

```raw
[winget --info]
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
Close with reason: Resolved with PR 109381;
