### ISSUE TITLE
[Package Issue]: Package.Revo

### ISSUE THREAD

**Issue by gothicx** [microsoft/winget-pkgs#109443]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

While trying to install Revo package, it revelaed a hash mismatch.

### Steps to reproduce

winget install revo

### Actual behavior

Installer hash mismatch

### Expected behavior

To install without issues.

### Environment

```raw
Gerenciador de Pacotes do Windows v1.4.11071
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22621.1778
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Configurações do Usuário: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
-------------------------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
Termos da Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

> winget install revo
Encontrado Revo Uninstaller [RevoUninstaller.RevoUninstaller] Versão 2.4.4
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Baixando https://download.revouninstaller.com/download/revosetup.exe
  ██████████████████████████████  6.64 MB / 6.64 MB
O hash do instalador não corresponde.

**Comment by quhxl** [comment]
Close with reason: #109806;

**Comment by quhxl** [comment]
#109806
