### ISSUE TITLE
[Update Request]: bottom 0.9.2

### ISSUE THREAD

**Issue by ClementTsang** [microsoft/winget-pkgs#109615]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Clement.bottom

### Package Version

0.9.2

### Please describe the changes you would like to see

New release available: https://github.com/ClementTsang/bottom/releases/download/0.9.2/bottom_x86_64_installer.msi

**Comment by quhxl** [comment]
Close with reason: already updated;

#109628

**Comment by quhxl** [comment]
You might want to try integrating winget into your github release workflow.
