### ISSUE TITLE
[Package Issue]: Mariocube.<all>

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#109796]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Request in https://github.com/microsoft/winget-pkgs/pull/103191 to review packages from publisher `Mariocube` for potential errors or mirror links.

### Steps to reproduce

winget install Mariocube.GUIFormatter

### Actual behavior

Download from mirror (pre-https://github.com/microsoft/winget-pkgs/pull/109789)

### Expected behavior

Download from Ridgecorp site. (This is specific to this manifest, but publisher's other manifests may have a similar situation.)

### Environment

```raw
Windows Package Manager (Preview) v1.5.1361-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1848
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1361.0
```

**Comment by Trenly** [comment]
@stephengillie - I think this can be closed? All mariocube packages have been removed for now, and the publisher has been added to GitOps to be flagged
