### ISSUE TITLE
[Update Request]: Google.Chrome hash mishmatch

### ISSUE THREAD

**Issue by ChrisWarrenCodux** [microsoft/winget-pkgs#109756]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Google.Chrome

### Package Version

114.0.5735.134

### Please describe the changes you would like to see

The manifest is hardcoded to always update to the latest version.
-  https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi

Since the update last week we have moved from version 114.0.5735.110 to 114.0.5735.114 and now have a hash mismatch, that can't be ignored while running as Admin or System.

It would be preferable if we can have a few manifest versions, with static deployment URL to avoid this in the future, if possable.

**Comment by soredake** [comment]
@ChrisWarrenCodux Hi! Please vote on this three issues if you can https://github.com/microsoft/winget-cli/discussions/3313#discussioncomment-6135375

**Comment by ashishpromobi** [comment]
I am also facing same issue.

![image](https://github.com/microsoft/winget-pkgs/assets/136595630/f4e95ae5-38ca-4fd7-b8af-4fc7615db905)
