### ISSUE TITLE
[Update Request]: OISF.Suricata (6.0.12)

### ISSUE THREAD

**Issue by 0xThiebaut** [microsoft/winget-pkgs#109899]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OISF.Suricata

### Package Version

6.0.12

### Please describe the changes you would like to see

There is a new release (6.0.12) available.
Download page: https://www.openinfosecfoundation.org/downloads/windows/Suricata-6.0.12-1-64bit.msi
Home page: https://suricata.io/download/

**Comment by 0xThiebaut** [comment]
Please validate which version their home page advertises. The binary suggests `6.0.12` while the homepage suggests `6.0.13`.

**Comment by Trenly** [comment]
> Please validate which version their home page advertises. The binary suggests `6.0.12` while the homepage suggests `6.0.13`.

6.0.13 isn't available for windows
