### ISSUE TITLE
[Package Request]: WinsiderSS.SystemInformer

### ISSUE THREAD

**Issue by 0xThiebaut** [microsoft/winget-pkgs#109907]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://systeminformer.sourceforge.io/nightly.php
Publisher: Winsider Seminars & Solutions, Inc.
Package Name: System Informer
Description: A free, powerful, multi-purpose tool that helps you monitor system resources, debug software and detect malware.
Package Version: 3.0.6772
Installer URL: https://github.com/winsiderss/si-builds/releases/download/3.0.6772/systeminformer-3.0.6772-setup.exe

**Comment by jxy-s** [comment]
👋 maintainer for System Informer here, I've updated System Informer to be compatible with winget and I've created two PRs, one for the release version and one for the "Canary" version of System Informer:
https://github.com/microsoft/winget-pkgs/pull/180087
https://github.com/microsoft/winget-pkgs/pull/180088

We look forward to being on the winget package repository 🎉
