### ISSUE TITLE
[Package Issue]: Git.Git - enable Terminal integration

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/winget-pkgs#109915]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Windows Terminal no longer autodetects Git Bash and now expects Git to register itself (which is safe to do even if Terminal is not installed): https://github.com/microsoft/terminal/issues/15559

Unfortunately the installer option is off by default and upstream will not change it: https://github.com/git-for-windows/git/issues/4468

Can you add `/enable-component windowsterminal` to install flags?
Not sure if that's the right syntax but that's how the option is named in https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L115

### Steps to reproduce

```
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Git.Git
wt
```

### Actual behavior

No git bash profile

### Expected behavior

Git Bash profile is on the list

### Environment

```raw
-
```

**Comment by BrandonWanHuanSheng** [comment]
It look like Windows 10 may be failed due to there is no Windows Terminal installed but Windows 11 have Windows Terminal might be success. Because that Windows 11 Setup have come with Windows Terminal.

**Comment by quhxl** [comment]
https://github.com/microsoft/winget-pkgs/pull/110011#issuecomment-1595704175
