### ISSUE TITLE
[Update Request]: JetBrains.DataGrip.EarlyAccess

### ISSUE THREAD

**Issue by wilmerferreira** [microsoft/winget-pkgs#110275]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JetBrains.DataGrip.EarlyAccess

### Package Version

232.7295.8

### Please describe the changes you would like to see

There is new release (232.7295.8) available
Download Page Url: https://www.jetbrains.com/datagrip/nextversion/

**Comment by Dragon1573** [comment]
This issue can be closed as "Completed". 😄

- https://github.com/microsoft/winget-pkgs/pull/120655
- https://github.com/microsoft/winget-pkgs/pull/120654
- https://github.com/microsoft/winget-pkgs/pull/120653
- https://github.com/microsoft/winget-pkgs/pull/120652
