### ISSUE TITLE
[Package Request]: NuGet Package Explorer

### ISSUE THREAD

**Issue by wilmerferreira** [microsoft/winget-pkgs#110277]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
Publisher: NuGetPackageExplorer
Package Name: NuGetPackageExplorer
Description: NuGet Package Explorer (NPE) is an application that makes it easy to create and explore NuGet packages. You can load a .nupkg or .snupkg file from disk or directly from a feed such as [nuget.org](https://www.nuget.org/).
Package Version: 6.0.64
Installer URL: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases/download/v6.0.64/PackageExplorer.6.0.64.zip

**Comment by wilmerferreira** [comment]
This package can be found in the [Windows Store](https://apps.microsoft.com/store/detail/nuget-package-explorer/9WZDNCRDMDM3?hl=en-gb&gl=gb&rtc=1) and in [Chocolatey](https://chocolatey.org/packages/NugetPackageExplorer)

**Comment by wilmerferreira** [comment]
The issues shouldn't be close since the package can have two sources (`winget` and `mstore`), e.g. Visual Studio code is available in the `mstore` source (`XP9KHM4BK9FZ7Q`) but also in the `winget` source (`Microsoft.VisualStudioCode`)

**Comment by ItzLevvie** [comment]
Reopen with reason: I thought you meant nightly releases as per the Download URL in your post since the NuGet team doesn't want nightly builds on WinGet. Only stable releases;

**Comment by Dragon1573** [comment]
[Policy] zip-binary

This package is released as a "loose executable" ZIP compressed archive, containing plenties of `*.dll` libraries. This kind of package is currently NOT supported by `winget.exe`. We are unable to submit this package to the repository. 😞

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/77a1a150-3f1f-42dd-90ab-e0fa11f7efbc)

This issue can be closed as "Not planned".

**Comment by ItzLevvie** [comment]
Close with reason: Not planned;
