### ISSUE TITLE
[Package Request]: czkawka

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#110314]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/qarmin/czkawka/releases/tag/6.0.0
Publisher: https://github.com/qarmin
Package Name: czkawka
Description:  Multi functional app to find duplicates, empty folders, similar images etc. 
Package Version: 6.0.0
Installer URL: https://github.com/qarmin/czkawka/releases/download/6.0.0/windows_czkawka_gui2.zip

**Comment by Dragon1573** [comment]
Hi @soredake, after inspecting those releases manually, we may only able to submit CLI-only version of this package.

Both [`windows_czkawka_gui.zip`](https://github.com/qarmin/czkawka/releases/download/6.1.0/windows_czkawka_gui.zip) and [`windows_czkawka_gui_console.zip`](https://github.com/qarmin/czkawka/releases/download/6.1.0/windows_czkawka_gui_console.zip) are "loose executable" ZIP compressed archive format, which is not supported by `winget.exe` at the moment. 😞

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/894530bd-22d6-46f9-820b-12dec6986281)
![image](https://github.com/microsoft/winget-pkgs/assets/49941141/63b68363-cc2a-4e17-a5b9-98d76bd81657)

While [`windows_czkawka_cli.exe`](https://github.com/qarmin/czkawka/releases/download/6.1.0/windows_czkawka_cli.exe) is a standalone portable executable file. I'll try if I can submit it for you. 😄

```text
D:\Workloads\winget-pkgs [master ≡]> D:\Dragon1573\Downloads\windows_czkawka_cli.exe
czkawka 6.1.0

USAGE:
    windows_czkawka_cli.exe <COMMAND> [SCFLAGS] [SCOPTIONS]

OPTIONS:
  -h, --help     Print help
  -V, --version  Print version                                                                                                                                             
SUBCOMMANDS:
  dup            Finds duplicate files
  empty-folders  Finds empty folders
  big            Finds big files
  empty-files    Finds empty files
  temp           Finds temporary files
  image          Finds similar images
  music          Finds same music by tags
  symlinks       Finds invalid symlinks
  broken         Finds broken files
  video          Finds similar video files
  ext            Finds files with invalid extensions
  tester         Small utility to test supported speed of
  help           Print this message or the help of the given subcommand(s)

    try "windows_czkawka_cli.exe <COMMAND> -h" to get more info about a specific tool

EXAMPLES:
    czkawka dup -d /home/rafal -e /home/rafal/Obrazy  -m 25 -x 7z rar IMAGE -s hash -f results.txt -D aeo
    czkawka empty-folders -d /home/rafal/rr /home/gateway -f results.txt
    czkawka big -d /home/rafal/ /home/piszczal -e /home/rafal/Roman -n 25 -x VIDEO -f results.txt
    czkawka empty-files -d /home/rafal /home/szczekacz -e /home/rafal/Pulpit -R -f results.txt
    czkawka temp -d /home/rafal/ -E */.git */tmp* *Pulpit -f results.txt -D
    czkawka image -d /home/rafal -e /home/rafal/Pulpit -f results.txt
    czkawka music -d /home/rafal -e /home/rafal/Pulpit -z "artist,year, ARTISTALBUM, ALBUM___tiTlE"  -f results.txt
    czkawka symlinks -d /home/kicikici/ /home/szczek -e /home/kicikici/jestempsem -x jpg -f results.txt
    czkawka broken -d /home/mikrut/ -e /home/mikrut/trakt -f results.txt
    czkawka extnp -d /home/mikrut/ -e /home/mikrut/trakt -f results.txt
```
