### ISSUE TITLE
[Package Issue]: SumatraPDF.SumatraPDF

### ISSUE THREAD

**Issue by szyb** [microsoft/winget-pkgs#110655]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Cannot update SumatraPDF.SumatraPDF
`Installer failed with exit code: 1`

### Steps to reproduce

* Installed SumatrPDF.SumatraPDF in version 3.3.3
* update the package : `winget update SumatraPDF.SumatraPDF`

### Actual behavior

Console:
```
Found SumatraPDF [SumatraPDF.SumatraPDF] Version 3.4.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```

### Expected behavior

It should be updated

### Environment

```raw
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3086
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

Logs (last entries before erorr):
```
2023-06-25 15:05:27.307 [CLI ] Installer args: -s -install -allusers -upgrade -allusers
2023-06-25 15:05:27.308 [CLI ] Starting: 'C:\Users\[username]\AppData\Local\Temp\WinGet\SumatraPDF.SumatraPDF.3.4.6\SumatraPDF-3.4.6-64-install.exe' with arguments '-s -install -allusers -upgrade -allusers'
2023-06-25 15:05:27.676 [CLI ] ShellExecute installer failed: 1
2023-06-25 15:05:27.677 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1cb
```

**Comment by stephengillie** [comment]
Does this occur with upgrades outside of WinGet? If version 3.3.3 were downloaded and installed manually, and then upgraded manually, does the error still occur? These will have to be tested, to find if it's an issue with the installer performing the upgrade.

**Comment by szyb** [comment]
Ok, so I updated manually to 3.4.6 and it worked fine. 
Then I uninstalled app and
1) Installed manually version 3.3.3. Then updated manually to 3.4.6 -> works fine
uninstalled manually and performed a test with winget, so:
2) `winget install SumatraPDF.SumatraPDF --version 3.3.3` -> installed
`winget update SumatraPDF.SumatraPDF` -> failed
uninstalled with `winget remove SumatraPDF.SumatraPDF` 
3) `winget install SumatraPDF.SumatraPDF` -> installed in version 3.4.6

Obviously there is something with winget when performing update from 3.3.3 to 3.4.6
