### ISSUE TITLE
[Update Request]: Cloudflare Tunnel client (cloudflared)

### ISSUE THREAD

**Issue by dingwen07** [microsoft/winget-pkgs#110631]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Cloudflare.cloudflared

### Package Version

2023.6.1

### Please describe the changes you would like to see

There is a new release (2023.6.1) available.
Download Page Url: https://github.com/cloudflare/cloudflared/releases

**Comment by szhu25** [comment]
Created PR 110636 to address this issue.
