### ISSUE TITLE
[Package Issue]: Mojang.MinecraftLauncher

### ISSUE THREAD

**Issue by just-ero** [microsoft/winget-pkgs#110658]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Cannot download `Mojang.MinecraftLauncher` 2.0.0.0.  
> Installer hash does not match.

### Steps to reproduce

`winget install Mojang.MinecraftLauncher`

### Actual behavior

```
Found Minecraft Launcher [Mojang.MinecraftLauncher] Version 2.0.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://launcher.mojang.com/download/MinecraftInstaller.msi
  ██████████████████████████████  2.16 MB / 2.16 MB
Installer hash does not match.
```

---

The package does not begin installing.

### Expected behavior

The package should begin installing.

### Environment

```raw
Windows: Windows.Desktop v10.0.22621.1848
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0
```

**Comment by Raallen89** [comment]
> ### Please confirm these before moving forward
> 
> - [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
> - [X] I have not been informed if the issue is resolved in a preview version of the winget client.
> 
> ### Category of the issue
> 
> Installer hash mismatch.
> 
> ### Brief description of your issue
> 
> Cannot download `Mojang.MinecraftLauncher` 2.0.0.0.  
> > Installer hash does not match.
> 
> ### Steps to reproduce
> 
> `winget install Mojang.MinecraftLauncher`
> 
> ### Actual behavior
> 
> ```
> Found Minecraft Launcher [Mojang.MinecraftLauncher] Version 2.0.0.0
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://launcher.mojang.com/download/MinecraftInstaller.msi
>   ██████████████████████████████  2.16 MB / 2.16 MB
> Installer hash does not match.
> ```
> 
> ---
> 
> The package does not begin installing.
> 
> ### Expected behavior
> 
> The package should begin installing.
> 
> ### Environment
> 
> ```raw
> Windows: Windows.Desktop v10.0.22621.1848
> System Architecture: X64
> Package: Microsoft.DesktopAppInstaller v1.19.11071.0
> ```
> 
> 
> ### Screenshots and Logs
> 
> _No response_
