### ISSUE TITLE
[Package Request]: AVRDUDE

### ISSUE THREAD

**Issue by hayschan** [microsoft/winget-pkgs#110758]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/avrdudes/avrdude/releases
Publisher: AVR Dudes
Package Name: avrdude
Description: AVRDUDE is a program for downloading and uploading the on-chip memories of Microchip’s AVR microcontrollers. It can program the Flash and EEPROM, and where supported by the programming protocol, it can program fuse and lock bits. AVRDUDE also supplies a direct instruction mode allowing one to issue any programming instruction to the AVR chip regardless of whether AVRDUDE implements that specific feature of a particular chip.
Package Version: 7.1
Installer URL: 
- x64: https://github.com/avrdudes/avrdude/releases/download/v7.1/avrdude-v7.1-windows-x64.zip
- arm64: https://github.com/avrdudes/avrdude/releases/download/v7.1/avrdude-v7.1-windows-arm64.zip
- x86: https://github.com/avrdudes/avrdude/releases/download/v7.1/avrdude-v7.1-windows-x86.zip

**Comment by AsciiWolf** [comment]
It looks like AVRDUDE is already available on WinGet.
