### ISSUE TITLE
[Update Request]: Darktable 4.2.1 -> 4.4.0

### ISSUE THREAD

**Issue by thegreenmilecornant** [microsoft/winget-pkgs#110770]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

darktable.darktable

### Package Version

4.4.0

### Please describe the changes you would like to see

There is an update to Darktable, namely from 4.2.1 to 4.4.0.

[Here](https://github.com/darktable-org/darktable/releases/tag/release-4.4.0) is the Github release. And [here](https://www.darktable.org/install/) is the download url.

**Comment by thegreenmilecornant** [comment]
I gave it a shot and submitted pull request #110771 via WingetCreate.

**Comment by luzpaz** [comment]
JFYI v4.4.1 has been released https://www.darktable.org/2023/07/darktable-4.4.1-released/

**Comment by thegreenmilecornant** [comment]
> JFYI v4.4.1 has been released https://www.darktable.org/2023/07/darktable-4.4.1-released/

Just submitted pull request #111147 to update to 4.4.1. I guess this issue can be closed since I updated DT to 4.4.0 in the first PR.
