### ISSUE TITLE
[Update Request]: Microsoft Sysinternals ProcessMonitor

### ISSUE THREAD

**Issue by egerlach** [microsoft/winget-pkgs#110788]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Sysinternals.ProcessMonitor

### Package Version

3.95

### Please describe the changes you would like to see

There is a new release of ProcessMonitor. 
Documentation: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

Hashes reported as not matching when trying to install.

**Comment by BrandonWanHuanSheng** [comment]
Updating the file is underway.
