### ISSUE TITLE
[Package Request]: Python.Python.Latest meta package

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#110884]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/microsoft/winget-pkgs/tree/3b74cb8554db7a74ae03816f5430cf40f7a14e30/manifests/p/Python/Python/3/11/3.11.4
Publisher: Python
Package Name: Python.Python.Latest
Description: metapackage that will pull latest version of python, like in chocolatey https://community.chocolatey.org/packages/python/
Package Version: 3.11.4
Installer URL: https://github.com/microsoft/winget-pkgs/tree/3b74cb8554db7a74ae03816f5430cf40f7a14e30/manifests/p/Python/Python/3/11/3.11.4

**Comment by Trenly** [comment]
If the msstore source is enabled, `winget install python` will install the latest. If only the winget source is enabled, `winget install python3` will install the latest

**Comment by soredake** [comment]
@Trenly where can i learn about this package aliases like python/python or [nodejs](https://github.com/microsoft/winget-pkgs/issues/110883#issuecomment-1618867096)?

**Comment by Trenly** [comment]
> @Trenly where can i learn about this package aliases like python/python or [nodejs](https://github.com/microsoft/winget-pkgs/issues/110883#issuecomment-1618867096)?

If you do `winget search <query>` there may be a column that specified what exactly was matched - in the case of python or nodejs you should see the first option shows that moniker was matched.

The other way is to look at the manifests themselves. If you look at Python.Python.3.11, the defaultLocale manifest contains the moniker. 

Unfortunately there isn’t really a good way to get a list of all the monikers directly

**Comment by soredake** [comment]
@Trenly, thank you!
