### ISSUE TITLE
[Update Request]: Cisco.WebexTeams

### ISSUE THREAD

**Issue by cyronis** [microsoft/winget-pkgs#110825]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Cisco.WebexTeams

### Package Version

43.6.0.26407

### Please describe the changes you would like to see

Updated Version and SHA256 String
PackageIdentifier: Cisco.WebexTeams
PackageVersion: 43.6.0.26407
InstallerType: msi
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex.msi
  InstallerSha256: BAFAFA8407A1BEAD6DEFA29068EAB53DB8111D2B4163FAC0F31E801F111CA3EA
  ProductCode: "{C6CD3D57-7AED-58D9-9184-0B3AF5F04F33}"
ManifestType: installer
ManifestVersion: 1.2.0

**Comment by Trenly** [comment]
* Resolved by #110840
