### ISSUE TITLE
[Update Request]: GarboMuffin.TurboWarp 1.8.1

### ISSUE THREAD

**Issue by headquarter8302** [microsoft/winget-pkgs#110837]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GarboMuffin.TurboWarp

### Package Version

1.81

### Please describe the changes you would like to see

v1.8.1 released
https://github.com/TurboWarp/desktop/releases/tag/v1.8.1

**Comment by BrandonWanHuanSheng** [comment]
Why github bot know that one is In-PR label.
