### ISSUE TITLE
[Package Issue]: Microsoft.SQLServer.2022.Developer

### ISSUE THREAD

**Issue by ravenbix** [microsoft/winget-pkgs#110832]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Value specified for --override is not being applied.

### Steps to reproduce

winget install --id=Microsoft.SQLServer.2022.Developer  -e --override "/IACCEPTSQLSERVERLICENSETERMS /ENU /ACTION=Install /quiet /FEATURES=SQLEngine,IS"

### Actual behavior

-Microsoft (R) SQL Server Installer
Copyright (c) 2022 Microsoft.  All rights reserved.

The setting 'features' specified is not recognized.

For more information use /? or /Help.
Installer failed with exit code: 4294967295

### Expected behavior

All features specified should be installed.

### Environment

```raw
Windows: Windows.Desktop v10.0.22621.1928
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0
```

**Comment by Trenly** [comment]
Are you sure that it's winget not passing the override and not the installer not honoring the arguments? I just tried the exact command you pasted in, and I see that winget called the installer with the exact argument that was specified for `--override`
> 2023-07-03 12:20:12.459 [CLI ] Starting: 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Microsoft.SQLServer.2022.Developer.16.0.1000.6\SQL2022-SSEI-Dev.exe' with arguments '/IACCEPTSQLSERVERLICENSETERMS /ENU /ACTION=Install /quiet /FEATURES=SQLEngine,IS'

Please provide your log file and screenshots of the winget output when running the command so the issue can be diagnosed further.

**Comment by CyberSinh** [comment]
The `FEATURE` parameter is used by the SQL Server installer, not by the installer downloader called by the winget package.

It is possible to specify a configuration file to the downloader, which will then be read by the installer.

Create an .ini configuration file :
```ini
; Microsoft SQL Server Configuration file
[OPTIONS]

; Specifies a Setup work flow, like INSTALL, UNINSTALL, or UPGRADE.
; This is a required parameter.
ACTION=Install

; Specifies features to install, uninstall, or upgrade.
FEATURES=SQLEngine

; https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-ver16
; https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16
```

Then:
`winget install --id "Microsoft.SQLServer.2022.Developer" --override "/IAcceptSqlServerLicenseTerms /Quiet /Action=Install /ConfigurationFile=C:\your_path\configuration.ini"`
