### ISSUE TITLE
[Update Request]: Zoom.Zoom

### ISSUE THREAD

**Issue by kake-r** [microsoft/winget-pkgs#110982]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Zoom.Zoom

### Package Version

5.15.2 (18096)

### Please describe the changes you would like to see

There is a new release 5.15.2.18096 available.
Release Notes Url: https://support.zoom.us/hc/en-us/articles/201361953-New-Updates-for-Windows

**Comment by BrandonWanHuanSheng** [comment]
It look like this path is hard to get the version because it is in https://zoom.us/client/latest/ZoomInstallerFull.exe?archType=x64

**Comment by BrandonWanHuanSheng** [comment]
The pull request is underway.
