### ISSUE TITLE
[Update Request]: labplot

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#111043]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

KDE.LabPlot

### Package Version

2.10.0

### Please describe the changes you would like to see

Latest stable 2.10.0  
Download Page URL: https://download.kde.org/stable/labplot/labplot-2.10.0.exe

**Comment by BrandonWanHuanSheng** [comment]
download.kde.org is an website directory.So, you might see all application around there.

**Comment by luzpaz** [comment]
@BrandonWanHuanSheng thanks for the previous update. Could you bump it again to 2.10.1 ? :pray: TIA
