### ISSUE TITLE
[Package Issue]: SamyGO.<all>

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#111198]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Package ISV name is mis-capitalized. The final `O` should be upper case. 

From: https://github.com/microsoft/winget-pkgs/pull/109541/files#r1230366169
1. The old manifests will need to be completely removed.
2. Wait for the publish pipeline to publish all changes removing the SamyGo manifests.
3. Individually readd each package with the new SamyGO name.
> Doing it any other way will result in directory conflicts

Example of directory conflict: https://github.com/microsoft/winget-pkgs/issues/109794

### Steps to reproduce

Search for any SamyGO package.

### Actual behavior

Find `SamyGo`

### Expected behavior

Find `SamyGO`

### Environment

```raw
Windows Package Manager (Preview) v1.5.1361-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1848
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1361.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag╬ô├ç┬¬
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett╬ô├ç┬¬
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
Should be resolved once all referenced issues above are merged
