### ISSUE TITLE
[Package Request]: N1MM Logger+

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111298]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://n1mmwp.hamdocs.com/downloads/n1mm-full-install/
Publisher: N1MM
Package Name: N1MM Logger+
Description: World’s most popular ham radio contest logging program.
Package Version: 1.0.9694
Installer URL: https://n1mmwp.hamdocs.com/mmfiles/n1mm-logger-full-installer-1-0-9694-june-20-2023/

**Comment by Dragon1573** [comment]
@AsciiWolf - Sorry, we might not able to submit this package to the repository. 😞

It seems this package is using a vanity download URL and requires HTTP POST request for authorization. This action is not supported by `winget.exe` at the moment.

![PixPin_2023-12-10_17-12-55](https://github.com/microsoft/winget-pkgs/assets/49941141/f6a6db23-d7a4-45a2-9165-ac6b5c91927c)

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie remove In-PR labels

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie add Area-External
