### ISSUE TITLE
[Package Request]: WSJT-X

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111296]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://wsjt.sourceforge.io/wsjtx.html
Publisher: K1JT
Package Name: WSJT-X
Description: Computer program used for weak-signal radio communication between amateur radio operators.
Package Version: 2.6.1
Installer URL: https://wsjt.sourceforge.io/downloads/wsjtx-2.6.1-win64.exe

**Comment by AsciiWolf** [comment]
@CoolPlayLin Any chance you could prepare a WinGet package for this software? From all the requests I [have sent](https://github.com/microsoft/winget-pkgs/issues/created_by/AsciiWolf), I consider this one being the most important.

**Comment by CoolPlayLin** [comment]
@AsciiWolf 
- It will publish in #113258

**Comment by AsciiWolf** [comment]
Thanks! You are amazing. :-)

**Comment by CoolPlayLin** [comment]
But the Validation Pipeline has been paused.

**Comment by CoolPlayLin** [comment]
@AsciiWolf
- This software has been published in #111637

And no new version is available.

**This issue should be marked as complete**
