### ISSUE TITLE
[Package Request]: ManaPlus

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111397]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://manaplus.org
Publisher: manaplus.org
Package Name: ManaPlus
Description: Free and Open Source 2D MMORPG client, supports hercules, tmwAthena, evol.
Package Version: 2.1.3.17
Installer URL: http://download.evolonline.org/manaplus/download/manaplus-win32.exe

**Comment by szhu25** [comment]
Fixed by #107842
