### ISSUE TITLE
[Package Request]: JAERO

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111381]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://jontio.zapto.org/hda1/jaero.html
Publisher: Jonti Olds
Package Name: JAERO
Description: A program to demodulate and decode Classic Aero SatCom ACARS signals.
Package Version: 1.0.4.11
Installer URL: https://github.com/jontio/JAERO/releases/download/v1.0.4.11/JAERO-x64-setup.exe

**Comment by Trenly** [comment]
[Policy] zip binary

**Comment by AsciiWolf** [comment]
@Trenly @stephengillie I have just noticed that there is also a setup exe for JAERO: https://github.com/jontio/JAERO/releases/download/v1.0.4.11/JAERO-x64-setup.exe

**Comment by AsciiWolf** [comment]
Please remove he "Blocking-Issue" label. Thanks!

**Comment by AsciiWolf** [comment]
@vikingnope Are you interested in creating a manifest for this application? :-)

**Comment by vikingnope** [comment]
Coming right up
