### ISSUE TITLE
[Package Request]: FreeDV

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111388]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/drowe67/freedv-gui/releases
Publisher: freedv.org
Package Name: FreeDV
Description: Open Source Amateur Digital Voice mode for HF radio.
Package Version: 1.8.4
Installer URL: https://github.com/drowe67/freedv-gui/releases/download/v1.8.4/FreeDV-1.8.4-win64.exe

**Comment by luzpaz** [comment]
Note: latest package version is [v1.8.12](https://github.com/drowe67/freedv-gui/releases/tag/v1.8.12)

**Comment by CoolPlayLin** [comment]
I still create with this version now, you could create an issue to require to update it later
