### ISSUE TITLE
[Package Request]: SteamCMD

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111308]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://developer.valvesoftware.com/wiki/SteamCMD#Windows
Publisher: Valve Corporation
Package Name: SteamCMD
Description: Command-line version of the Steam client. Its primary use is to install and update various dedicated servers available on Steam using a command-line interface.
Package Version: latest
Installer URL: https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip

**Comment by szhu25** [comment]
I thought SteamCMD is already included as part of the manifest: https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/Valve/SteamCMD/latest
SteamCMD pull request #109831 merged 3 weeks ago.

**Comment by AsciiWolf** [comment]
Oops, you're right! Thanks! :-)
