### ISSUE TITLE
[Package Request]: MMSSTV

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111302]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.qsl.net/kf6ypq/mmsstv.html
Publisher: JE3HHT - Makoto Mori
Package Name: MMSSTV
Description: Slow Scan TV with Windows and Soundcard.
Package Version: 1.13A
Installer URL: n/a (The app itself is freeware and can be redistributed, however the website owner does not want direct links to the download url and obfuscates it, probably for bandwidth reasons.)

**Comment by Trenly** [comment]
> website owner does not want direct links to the download url and obfuscates it

[Policy] Blocking Issue
[Policy] Area-External

**Comment by AsciiWolf** [comment]
Replaced by #111361.
