### ISSUE TITLE
[Package Request]: Flrig

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111301]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: http://www.w1hkj.com
Publisher: W1HKJ Software
Package Name: Flrig
Description: Transceiver control program designed to be used either stand alone or as an adjunct to Fldigi.
Package Version: 2.0.02
Installer URL: http://www.w1hkj.com/files/flrig/flrig-2.0.02_setup.exe

**Comment by CoolPlayLin** [comment]
@AsciiWolf
Please send the package you wanted to my email
```
coolplaylin@foxmail.com
```
I would handle it later

**Comment by CoolPlayLin** [comment]
I've also noticed that this software has published new version, you could add a issue to update it later.
