### ISSUE TITLE
[Package Request]: Fldigi

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111300]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: http://www.w1hkj.com
Publisher: W1HKJ Software
Package Name: Fldigi
Description: Modem program for most of the digital modes used by radio amateurs today.
Package Version: 4.1.27
Installer URL: http://www.w1hkj.com/files/fldigi/fldigi-4.1.27_setup.exe

**Comment by CoolPlayLin** [comment]
The page is 404

![image](https://github.com/microsoft/winget-pkgs/assets/96709586/7d90a8a9-4274-4171-a832-81eaf718b393)

**Comment by AsciiWolf** [comment]
@CoolPlayLin There was a new version released and the old one got deleted. I have updated the download link.
