### ISSUE TITLE
[Package Issue]: DeepL.DeepL

### ISSUE THREAD

**Issue by jfernandz** [microsoft/winget-pkgs#111446]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

DeepL doesn't report a proper version so it's updated every time I run `winget upgrade --all --include-unknown`

```
 winget upgrade --all --include-unknown
Nombre           Id                                    Versión Disponible Origen
--------------------------------------------------------------------------------
DeepL            DeepL.DeepL                           Unknown 4.7.0.9554 winget
1 actualización disponible.

(2/2) Encontrado DeepL [DeepL.DeepL] Versión 4.7.0.9554
El propietario de esta aplicación le concede una licencia.
Microsoft no es responsable, ni tampoco concede ninguna licencia de paquetes de terceros.
Descargando https://appdownload.deepl.com/windows/0install/DeepLSetup.exe
  ██████████████████████████████  4.26 MB / 4.26 MB
El hash del instalador se verificó correctamente
Iniciando instalación de paquete...
Instalado correctamente
```

### Steps to reproduce

Install `DeepL.DeepL` and verify version isn't properly reported with `winget upgrade --all --include-unknown`

### Actual behavior

`DeepL.DeepL` is upgraded every time you run `winget upgrade --all --include-unknown`

### Expected behavior

`DeepL.DeepL` is upgraded once, just when newer version is available.

### Environment

```raw
 winget --info
Administrador de paquetes de Windows v1.5.1572
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22621.1848
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.20.1572.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Vínculos
-----------------------------------------------------------------------------------
Declaración de privacidad   https://aka.ms/winget-privacy
Contrato de licencia        https://aka.ms/winget-license
Avisos de terceros          https://aka.ms/winget-3rdPartyNotice
Página principal            https://aka.ms/winget
Términos de Microsoft Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Configuración de administrador            Estado
-------------------------------------------------------
LocalManifestFiles                        Deshabilitado
BypassCertificatePinningForMicrosoftStore Deshabilitado
InstallerHashOverride                     Deshabilitado
LocalArchiveMalwareScanOverride           Deshabilitado
```
```


### Screenshots and Logs

_No response_

**Comment by krystofkrticka** [comment]
This is impossible to do because app installer isn't writing version number of package to registry. And because it uses some exotic installer it's going to be quite hard to detect version number of package from file properties once https://github.com/microsoft/winget-cli/issues/3134 is finished. Because winget would need to start the app to see where is the executable located to detect version number from executable metadata.

**Comment by jfernandz** [comment]
@krystofkrticka and couldn't we report this upstream as in https://github.com/microsoft/winget-pkgs/issues/88994?

**Comment by krystofkrticka** [comment]
Well the issue here is that this package does not have constant install path as is shown in example with WinDirStat. Because this installer is creating new directory every time it downloads and update and path to this apps executable looks like this: `C:\ProgramData\0install.net\implementations\sha256new_UWNGXVK6DRTTECOLMXJSJBKPLJSVPF4RLJDWUUYVXIU4S6CAUU7A` and since it uses sha256 in it's path it'll change every update.

**Comment by Trenly** [comment]
Either way, it's an issue with the way the installer was designed and, at this time, there isn’t anything Winget can do to correct it

[Policy] Installer issue
