### ISSUE TITLE
[Package Request]: Universal Radio Hacker

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111416]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/jopohl/urh/releases
Publisher: Dr. Johannes Pohl
Package Name: Universal Radio Hacker
Description: Investigate Wireless Protocols Like A Boss.
Package Version: 2.9.4
Installer URL: https://github.com/jopohl/urh/releases/download/v2.9.4/Universal.Radio.Hacker-2.9.4-x64.exe

**Comment by CoolPlayLin** [comment]
Hello @AsciiWolf 
I am creating this software's manifest, I'll open a PR soon

**Comment by Trenly** [comment]
Close with reason: Package already exists; at manifests\j\JohannesPohl\UniversalRadioHacker\2.9.4
