### ISSUE TITLE
[Package Issue]: Microsoft.Sysinternals.ProcessMonitor

### ISSUE THREAD

**Issue by jfernandz** [microsoft/winget-pkgs#111448]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Can't upgrade `Microsoft.Sysinternals.ProcessMonitor` URL is apparently broken.

```
 winget upgrade --all
Nombre          Id                                    Versión Disponible Origen
-------------------------------------------------------------------------------
Process Monitor Microsoft.Sysinternals.ProcessMonitor 3.93    3.95       winget
1 actualizaciones disponibles.
1 paquete(s) tienen números de versión que no se pueden determinar. Use --include-unknown para ver todos los resultados.

(1/1) Encontrado Process Monitor [Microsoft.Sysinternals.ProcessMonitor] Versión 3.95
El propietario de esta aplicación le concede una licencia.
Microsoft no es responsable, ni tampoco concede ninguna licencia de paquetes de terceros.
Descargando https://live.sysinternals.com/Procmon64.exe
Se ha producido un error inesperado al ejecutar el comando:
InternetOpenUrl() failed.
0x80072efd : unknown error

106 paquete(s) tienen números de versión que no se pueden determinar. Use --include-unknown para ver todos los resultados.
```

### Steps to reproduce

Just trying to install Install `Microsoft.Sysinternals.ProcessMonitor` is enough as I'm having a "closed connection" when I try to get the URL: https://live.sysinternals.com/Procmon64.exe

### Actual behavior

`Microsoft.Sysinternals.ProcessMonitor` is not being installed.

### Expected behavior

`Microsoft.Sysinternals.ProcessMonitor` is properly installed/upgraded.

### Environment

```raw
 winget --info
Administrador de paquetes de Windows v1.5.1572
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22621.1848
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.20.1572.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Vínculos
-----------------------------------------------------------------------------------
Declaración de privacidad   https://aka.ms/winget-privacy
Contrato de licencia        https://aka.ms/winget-license
Avisos de terceros          https://aka.ms/winget-3rdPartyNotice
Página principal            https://aka.ms/winget
Términos de Microsoft Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Configuración de administrador            Estado
-------------------------------------------------------
LocalManifestFiles                        Deshabilitado
BypassCertificatePinningForMicrosoftStore Deshabilitado
InstallerHashOverride                     Deshabilitado
LocalArchiveMalwareScanOverride           Deshabilitado
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/4059108/69429abf-62af-4619-9c4e-40bb17ee02ff)

**Comment by krystofkrticka** [comment]
You need to restart your shell to apply changes in environment variables as is said after installing the package: "Path environment variable modified; restart your shell to use the new value."

**Comment by jfernandz** [comment]
@krystofkrticka I'd say this has nothing to do with env vars ... I can't reach the URL https://live.sysinternals.com/Procmon64.exe even from the web browser (i.e. ... `Procmon64.exe` is not downloadable to me at all)

**Comment by krystofkrticka** [comment]
My bad this issue looked similar to your other issue.

**Comment by krystofkrticka** [comment]
@jfernandz This has to be some kind of issue with your DNS because just checked if I can download it and it downloads just fine.

**Comment by jfernandz** [comment]
> My bad this issue looked similar to your other issue.

I'ts not an issue of mine, but I think I know what issue you are meaning 😉 

> @jfernandz This has to be some kind of issue with your DNS because just checked if I can download it and it downloads just fine.

hmmm .... 🤔 I'ts so weird ... because I've tested with different wireless connections and I can't reach the resource ... I'll check this afternoon at my home, but with my work WiFi and my mobile data connection doesn't work (I have complete different DNSs with both) maybe it's because of the wireless adapter 😕

**Comment by krystofkrticka** [comment]
BTW I tested this on network resolving using CloudFlare DNS and Google DNS. I might also test this using my selfhosted DNS which I use for networkwide adblocking.

**Comment by stephengillie** [comment]
Confirming that the [URL](https://live.sysinternals.com/Procmon64.exe) works for me too.

**Comment by jfernandz** [comment]
hmmm, I can download the file from another computer in my home ... but cannot download it from y work computer, maybe it's because of some antivirus setting ... but it's apparently a thing of my company computer 😞. I think I'll have to figure it out at my side and this is not an issue of this package ...

Thank you anyway guys 😄 

Do you think could I provide manually the .exe to winget? 🤔

**Comment by BrandonWanHuanSheng** [comment]
> BTW I tested this on network resolving using CloudFlare DNS and Google DNS. I might also test this using my selfhosted DNS which I use for networkwide adblocking.

I think your VPN using on it. It might blocked some website from accessing.

**Comment by jfernandz** [comment]
Some clue on how might I provide manually the .exe file to winget? I've tried something like `winget upgrade Microsoft.Sysinternals.ProcessExplorer -s C:\Users\jfernandz\Downloads\procexp64.exe` but it doesn't work either :-(
