### ISSUE TITLE
[Package Request]: SDR-Radio

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#111414]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.sdr-radio.com/download
Publisher: Simon G4ELI
Package Name: SDR-Radio
Description: Windows solution for Software Defined Radio (SDR) receivers and transceivers.
Package Version: 3.2
Installer URL: https://irp.cdn-website.com/46d0be53/files/uploaded/SDR-Radio%20V3.2%2C%2064-bit%2C%202022-09-18_1224.zip

**Comment by upintheairsheep** [comment]
#112001

**Comment by szhu25** [comment]
> #112001

I noticed this recently: If you reference the this issue in your PR's description (first comment), then the bot can close this issue automatically when the PR got merged.

**Comment by AsciiWolf** [comment]
From the changelog of the latest 3.3 beta release (that is sadly only available from Dropbox or OneDrive unlike final releases) from the [download page](https://www.sdr-radio.com/download):

> Silent Installation
> Fixed installer issues when using the silent (/S) switch. Had never tried a silent installation before.

So, we need to wait for the final stable 3.3 version to be released which will hopefully happen this year.
