### ISSUE TITLE
[Package Issue]: Python 3.11 [9NRWMJP3717K]

### ISSUE THREAD

**Issue by lyj0309** [microsoft/winget-pkgs#111533]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

can't change pip source

### Steps to reproduce

pip config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple

### Actual behavior

success

### Expected behavior

Writing to C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\pip.ini
ERROR: Unable to save configuration. Please report this as a bug.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_internal\commands\configuration.py", line 267, in _save_configuration
    self.configuration.save()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_internal\configuration.py", line 213, in save
    with open(fname, "w") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\pip.ini'
ERROR: Internal Error.

### Environment

```raw
Windows: Windows.Desktop v10.0.22621.1928
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.21.1573.0
```

**Comment by Trenly** [comment]
I believe this is a cli issue, since the package identifier provided in the title is an msstore package, not the one from this repo

cc @denelon
