### ISSUE TITLE
[Package Issue]: OpenJS.NodeJS tries to update to nightly

### ISSUE THREAD

**Issue by lutzroeder** [microsoft/winget-pkgs#111537]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When running update, `20.4.0` is updated to `21.0.0-nightly20230706b5e16adb1d`.

@CoolPlayLin @stephengillie #111148

### Steps to reproduce

```
> winget install OpenJS.NodeJS
> winget upgrade
Name    Id            Version Available                        Source
---------------------------------------------------------------------
Node.js OpenJS.NodeJS 20.4.0  21.0.0-nightly20230706b5e16adb1d winget
```

### Actual behavior

The `21.0.0-nightly20230706b5e16adb1d` build is offered and installed.

### Expected behavior

No new build should be installed and `20.4.0` is the latest available.

### Environment

```raw
Windows Package Manager (Preview) v1.6.1573-preview
Windows: Windows.Desktop v10.0.22621.1928
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0
```

**Comment by CoolPlayLin** [comment]
It's not my problem, I checked it just now. The nightly version is in correct folder

**Comment by CoolPlayLin** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/38201c4a-9a1f-400b-a728-93c5801fc319)

**Comment by mdanish-kh** [comment]
> It's not my problem, I checked it just now. The nightly version is in correct folder

It's an issue with `winget upgrade` not `winget install`

**Comment by CoolPlayLin** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/fc3d4af4-affb-4a2a-bcf4-87e4f3ee9694)
It seems `OpenJS.NodeJS` as `OpenJS.NodeJS.Nightly`

**Comment by mdanish-kh** [comment]
WinGet can't differentiate nightly and stable releases as they use the same Apps&Features entries i.e. same DisplayName, Publisher, UpgradeCode values that causes conflicts in upgrade matching. The solution is likely to be addressed in
- https://github.com/microsoft/winget-cli/issues/147

For now, the quick fix would be to not support nightly releases in the WinGet repository as they cause conflicts with stable releases. It's hard anyway to keep up-to-date with nightly releases without automation / publisher taking control of the package releases

**Comment by CoolPlayLin** [comment]
Remove OpenJS.NodeJS.Nightly to OpenJS.NodeJSNightly ?

**Comment by mdanish-kh** [comment]
> @mdanish-kh Move OpenJS.NodeJS.Nightly to OpenJS.NodeJSNightly ?

That won't help, I'm talking about removing nightly releases altogether from the repo; Also seeing your screenshot I noticed that there is another problem with the nightly manifests concerning the DisplayVersion field not being present in all manifests. That is evident from the "<" symbol resulting in infinite upgrade scenario for the end-user.

**Comment by lutzroeder** [comment]
@mdanish-kh @stephengillie the issue still repros. Is there a local cache that needs to be updated or the removal needs to propagate?

**Comment by mdanish-kh** [comment]
@lutzroeder https://github.com/microsoft/winget-pkgs/pull/111562 hasn't passed the publish pipeline; Changes will appear once all the PRs have made their way through the publish pipeline

**Comment by mdanish-kh** [comment]
@lutzroeder All package removal PRs have now passed the publish pipeline; Can you confirm if the issue has been resolved now?

**Comment by lutzroeder** [comment]
Yes, `20.4.0` is now listed as latest available for `OpenJS.NodeJS`. Thank you, @mdanish-kh and @stephengillie.
