### ISSUE TITLE
[Update Request]: MTSD.AllDup 4.5.46 to 4.5.48 & auto-detection/ Auto-update

### ISSUE THREAD

**Issue by JustMyGithub** [microsoft/winget-pkgs#111511]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MTSD.AllDup

### Package Version

4.5.46

### Please describe the changes you would like to see

4.5.48 was released on 4th of June, more than one month ago. It would be really nice if this was detected (and updated) automatically, because this is not the first time for this Package. 
https://alldup.de/alldup_help/alldup_version.php

Thanks

**Comment by krystofkrticka** [comment]
It was auto updated, but for some reason winget bot and many other automated bots updating packages in winget stopped working around the end of May or start of June for some weird reason.
