### ISSUE TITLE
wingetbot automatic update PRs have stopped working

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-pkgs#111576]
The last ["Automatic update"](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Awingetbot+is%3Aclosed+Automatic+update) PR by wingetbot was https://github.com/microsoft/winget-pkgs/pull/109310 which is approximately a month old as of creating this issue. Since then, wingetbot hasn't been catching hash mismatches with vanity URLs in the repo

[Policy] Area-Bots

**Comment by mdanish-kh** [comment]
[Policy] Area-Bots

**Comment by borque** [comment]
Any news or ETA for a fix on this?

**Comment by auanasgheps** [comment]
Please, take a look at this issue.
There are apps that update very frequently and it's impossible to keep them updated manually.

**Comment by denelon** [comment]
This was just released into production:
* https://github.com/microsoft/winget-pkgs/pull/125612
