### ISSUE TITLE
[Update Request]: 

### ISSUE THREAD

**Issue by Pckgrapp** [microsoft/winget-pkgs#111640]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AnyDeskSoftwareGmbH.AnyDesk

### Package Version

7.1.13

### Please describe the changes you would like to see

There is a new release: 7.1.13

**Comment by BrandonWanHuanSheng** [comment]
The Azure Pipelines was unstable. Are you sure you want to continue?
