### ISSUE TITLE
The PR validation have some issue.

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#111634]
No commit pushedDate could be found for PR 111553 in repo microsoft/winget-pkgs

_Originally posted by [azure-pipelines[bot]](https://github.com/apps/azure-pipelines) in https://github.com/microsoft/winget-pkgs/issues/111553#issuecomment-1626321580_

Actual Behaviour

It look like almost everyone pipelines have this error also. Before, I did not see this issue on before winget pipelines update. ⚠️ Sometimes the pull request does not have label, please be aware because it throws this error out when wingetbot trying to run validation-pipelines. Also, sometimes could be this comment happening on moderator or admin in the repo try to run validation pipelines.

Expected Behaviour

This comments suppose to be gone. Suppose when the pull request add a label and wingetbot will automatically commented 1 time to run the pipelines. Close and Reopened pull request will work as expected.

**Comment by BrandonWanHuanSheng** [comment]
![Screenshot (255)](https://github.com/microsoft/winget-pkgs/assets/118059864/2489d10d-7d62-4624-b05f-9cb6cf72ec8a)

**Comment by BrandonWanHuanSheng** [comment]
@denelon

**Comment by krystofkrticka** [comment]
This issue also happens even without adding waiver, something is really messed up with the validation pipeline. As you can see in #111653

**Comment by BrandonWanHuanSheng** [comment]
Example: https://github.com/microsoft/winget-pkgs/pull/111666

**Comment by Trenly** [comment]
[Policy] Area-Validation-Pipeline

**Comment by BrandonWanHuanSheng** [comment]
Thank you, Trenly

**Comment by BrandonWanHuanSheng** [comment]
https://github.com/microsoft/winget-pkgs/pull/111708

**Comment by krystofkrticka** [comment]
#111756

**Comment by denelon** [comment]
We've been looking into this issue. Unfortunately, it seems to currently be in the state where we need to simply retry the pipeline. We will see if we can get into a root cause, but if this is a transient issue with the infrastructure, we may not find a root cause if it subsides.

**Comment by lewing** [comment]
> We've been looking into this issue. Unfortunately, it seems to currently be in the state where we need to simply retry the pipeline. We will see if we can get into a root cause, but if this is a transient issue with the infrastructure, we may not find a root cause if it subsides.

There was a breaking change from github [ttps://docs.github.com/en/graphql/overview/breaking-changes#changes-scheduled-for-2023-07-01](https://docs.github.com/en/graphql/overview/breaking-changes#changes-scheduled-for-2023-07-01) and it looks like something on the azdo side needs to be fixed.

**Comment by CoolPlayLin** [comment]
#112256

**Comment by CoolPlayLin** [comment]
- It's serious in #113054, wingetbot tried three times but it still appears this issue

**Comment by Alexey-Rivkin** [comment]
Unable to use comment triggers lately.
`/azp run perf` results in error:
"No commit pushedDate could be found for PR 9238 in repo openucx/ucx"
https://github.com/openucx/ucx/pull/9238#issuecomment-1650538426

**Comment by CoolPlayLin** [comment]
#113437

**Comment by stephengillie** [comment]
This package was handled in an especially bad way, removing `Validation-Complete` and `Moderator-Approved` labels after manual validation. https://github.com/microsoft/winget-pkgs/pull/113381

**Comment by stephengillie** [comment]
This PR was ping-pong'ing between adding and removing `Validation-Completed` and enabling and disabling automatic squash-and-merge. 
- https://github.com/microsoft/winget-pkgs/pull/114089

**Comment by stephengillie** [comment]
This PR won't even run: https://github.com/microsoft/winget-pkgs/pull/114818

**Comment by mdanish-kh** [comment]
> This PR won't even run: 
> * https://github.com/microsoft/winget-pkgs/pull/114818

PR has 0 files changed, probably that's why

**Comment by BrandonWanHuanSheng** [comment]
How long this issue will closed and resolved

**Comment by stephengillie** [comment]
This PR took 5 minutes to start running:
* https://github.com/microsoft/winget-pkgs/pull/115062

**Comment by BrandonWanHuanSheng** [comment]
> This PR took 5 minutes to start running:
> * https://github.com/microsoft/winget-pkgs/pull/115062

Sometimes the pipelines took long time to start up because pushedDate is synchronizing.

**Comment by BrandonWanHuanSheng** [comment]
Azure Pipelines with issues ended with 1/08/23 16:59.. There is no more about No commit about pushedDate could be found for PR #XXXXXX in repo: microsoft/winget-pkgs

**Comment by BrandonWanHuanSheng** [comment]
So, while I was watching the repository, because another is filtering my email.
