### ISSUE TITLE
[Package Request]: Natron

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#111784]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://natrongithub.github.io/#download
Publisher: https://natrongithub.github.io
Package Name: Natron
Description: Open-Source Compositing Software
Package Version: 2.5.0
Installer URL: https://github.com/NatronGitHub/Natron/releases/download/v2.5.0/Natron-2.5.0-Windows-x86_64.zip

**Comment by upintheairsheep** [comment]
#112002

**Comment by Dragon1573** [comment]
This issue is resoved and should be closed as "Completed".
