### ISSUE TITLE
[Package Request]: Visual Studio Code CLI

### ISSUE THREAD

**Issue by cglong** [microsoft/winget-pkgs#111729]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://code.visualstudio.com/Download
Publisher: Microsoft
Package Name: code-cli
Description: Visual Studio Code CLI Standalone
Package Version: 1.80.0
Installer URL: https://code.visualstudio.com/sha/download?build=stable&os=cli-win32-x64

**Comment by mdanish-kh** [comment]
[Policy] Area-External
[Policy] Blocking-Issue
