### ISSUE TITLE
[Update Request]: tastyworks/tastytrade

### ISSUE THREAD

**Issue by ProminentRetail** [microsoft/winget-pkgs#111718]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

tastyworks.tastyworks

### Package Version

2.3.1

### Please describe the changes you would like to see

I believe #95553 is relevant, but tastyworks has rebranded to tastytrade, and I am unsure as to how this should be handled.
The new version is: https://download.tastytrade.com/desktop-2.x.x/2.3.1/tastytrade-2.3.1.msi

**Comment by Trenly** [comment]
There is a workaround to "redirect" manifests which is documented in the [FAQ](https://github.com/microsoft/winget-pkgs/blob/master/FAQ.md#what-should-i-do-if-a-package-is-being-published-by-a-new-publisher).
