### ISSUE TITLE
[Update Request]: Mozilla.Thunderbird 115.0

### ISSUE THREAD

**Issue by ChungZH** [microsoft/winget-pkgs#111897]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mozilla.Thunderbird

### Package Version

115.0

### Please describe the changes you would like to see

https://www.thunderbird.net/

**Comment by BrandonWanHuanSheng** [comment]
https://download-origin.cdn.mozilla.net/pub/thunderbird/releases/115.0/SHA256SUMS which is all the sha256.

**Comment by BrandonWanHuanSheng** [comment]
#111940

**Comment by ChungZH** [comment]
done. thanks
