### ISSUE TITLE
[Package Request]: PinPoint

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#112090]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.pinpointaprs.com/download.html
Publisher: AB0WV
Package Name: PinPoint
Description: Free software that allows you to visually track and communicate with people using Amateur Radio equipment and APRS. During an emergency, it can be used as a location aware tactical communications tool. It is mostly used as a tool for tracking people and assets on a map, although it is capable of so much more.
Package Version: 2.0-230511
Installer URL: https://www.pinpointaprs.com/PinPoint_v2_build_230511.zip

**Comment by Trenly** [comment]
> System Requirements
• PinPoint has been shown to run on computers with very minimal memory and processor capabilities, but I’d like to recommend at least 4GB of memory for stability.
• Microsoft .NET framework 4.5 (can be downloaded from http://www.microsoft.com if needed).
• If you’re using a serial port TNC, you will need at least one COM port for your TNC and GPS, or two COM ports if connecting the GPS and the TNC directly to your machine. Most USB to COM converters will work just fine. A radio, GPS or TNC is not required for use.
• PinPoint has been tested on Windows 7 and Windows 10, but should run fine on Windows Vista and Windows 8 as well. PinPoint is not supported to run on Windows XP or earlier.
• While PinPoint does not require an Internet connection, you will need one to initially cache maps (automatic) or to use the APRS-IS servers. More information on that below.

Dependency on .NET
