### ISSUE TITLE
[Update Request]: Synology Drive Client to version 3.3.0-15082

### ISSUE THREAD

**Issue by phit42** [microsoft/winget-pkgs#112274]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Synology.DriveClient

### Package Version

7.2.1.13271

### Please describe the changes you would like to see

New version available at 
https://global.synologydownload.com/download/Utility/SynologyDriveClient/3.3.0-15082/Windows/Installer/Synology%20Drive%20Client-3.3.0-15082.msi
MD5 f1f7b14792cef82f0bf815ea8c052579
Release notes at https://www.synology.com/de-de/releaseNote/SynologyDriveClient

Thank you @max-schmidt for the last update. PS There was a bugfix release to 3.2.1.13272 between those.

**Comment by szhu25** [comment]
Uhhh is there a reason why the old releases have different version than on the website?
On Synology's release log, everything seems to be on version 3, but for some reason in this repo the major version number is 7?

**Comment by max-schmidt** [comment]
@szhu25 For the version number, see this old pull request #19672 
There was already a pr for the new version #112207. But I don't know why the pipeline has a problem to validate the installer.

**Comment by szhu25** [comment]
> @szhu25 For the version number, see this old pull request #19672 
> There was already a pr for the new version #112207. But I don't know why the pipeline has a problem to validate the installer.

Cool. I'll close my PR then. Thanks!

**Comment by max-schmidt** [comment]
Hi, my pr is merged. Can be closed.

**Comment by szhu25** [comment]
> Hi, my pr is merged. Can be closed.

Can you try to add `fix #112274` in the description of your PR and see if the bot would close this automatically? (Not sure if it'll work when the PR is already merged)

**Comment by stephengillie** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/112207 has merged, I'm going to assume this Issue is complete. If this is in error, please @ me and I'll reopen.
