### ISSUE TITLE
[Update Request]: Cloudflare.cloudflared

### ISSUE THREAD

**Issue by dingwen07** [microsoft/winget-pkgs#112282]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Cloudflare.cloudflared

### Package Version

2023.7.0

### Please describe the changes you would like to see

URL: https://github.com/cloudflare/cloudflared/releases/tag/2023.7.0

**Comment by CoolPlayLin** [comment]
@dingwen07 
I've opened a PR in #112435 to resolve your issue
