### ISSUE TITLE
[Package Issue]: Twilio.Authy

### ISSUE THREAD

**Issue by MiyeonLin** [microsoft/winget-pkgs#112647]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

The 2.4.0 update is not available

### Steps to reproduce

Try to update authy using winget.

### Actual behavior

Trying to update authy using winget results in 403 error.

### Expected behavior

Package should be downloaded and installed.

### Environment

```raw
N/A
```

**Comment by CoolPlayLin** [comment]
@MiyeonLin
It has published in
- https://github.com/microsoft/winget-pkgs/pull/112366

**Comment by MiyeonLin** [comment]
> @MiyeonLin It has published in
> 
> * [New version: Twilio.Authy version 2.4.0 #112366](https://github.com/microsoft/winget-pkgs/pull/112366)

Yes but the actual update exe is not available on twillio site itself so the published update does not work, is this just publishing in advance awaiting the actual update?
