### ISSUE TITLE
[Update Request]: Node.js LTS

### ISSUE THREAD

**Issue by Umoxfo** [microsoft/winget-pkgs#112618]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OpenJS.NodeJS.LTS

### Package Version

18.17.0

**Comment by CoolPlayLin** [comment]
I've published in
- https://github.com/microsoft/winget-pkgs/pull/112434

![image](https://github.com/microsoft/winget-pkgs/assets/96709586/9fa75c59-b503-490d-afef-b3fdac7fd300)

**Comment by CoolPlayLin** [comment]
The PR should mark as complete.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #112434;
