### ISSUE TITLE
[Package Issue]: Google.Drive

### ISSUE THREAD

**Issue by wxnode** [microsoft/winget-pkgs#112779]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

`Google.Drive` cannot be downloaded because of an installer hash mismatch.

### Steps to reproduce

winget install -i Google.Drive

### Actual behavior

已找到 Google Drive [Google.Drive] 版本 77.0.3.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
Downloading https://dl.google.com/drive-file-stream/GoogleDrive.exe
  ██████████████████████████████   317 MB /  317 MB
安装程序哈希不匹配；若要覆盖此检查，请使用 --force

### Expected behavior

Google.Drive installs correctly.

### Environment

```raw
Windows 程序包管理器 v1.2.10691
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.1992
程序包: Microsoft.DesktopAppInstaller v1.17.10691.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by CoolPlayLin** [comment]
@wxnode
>- 清单文件 manifest
>![image](https://github.com/microsoft/winget-pkgs/assets/96709586/e1a0e6fa-47e8-44b4-a656-4582c27b999b)
>- Komac
>![image](https://github.com/microsoft/winget-pkgs/assets/96709586/6a60c022-58f8-4603-8a14-97bdfaefdd85)
> - 7zip
>![image](https://github.com/microsoft/winget-pkgs/assets/96709586/4d57603f-0e88-49b3-a2d7-dfb2ffa3584d)

本地计算 Hash 值和清单文件的 Hash 值一样

>![image](https://github.com/microsoft/winget-pkgs/assets/96709586/c0506435-5f79-47d5-807b-fca6bf1997ef)

也没有出现这种情况

**Comment by CoolPlayLin** [comment]
可能就是你下载的文件出错

**Comment by CoolPlayLin** [comment]
This issue should mark as complete

**Comment by Trenly** [comment]
I'm not able to reproduce this issue. Is it still happening on your end if you retry?

[Policy] Needs Author Feedback
