### ISSUE TITLE
[Package Request]: Hydrogen

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#112758]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: http://hydrogen-music.org/downloads/
Publisher: http://hydrogen-music.org/
Package Name: Hydrogen
Description:  Drum Machine and Sequencer
Package Version: 1.2.1
Installer URL: https://github.com/hydrogen-music/hydrogen/releases/download/1.2.1/Hydrogen-1.2.1-win64.exe
Changelog: https://github.com/hydrogen-music/hydrogen/releases/tag/1.2.1

**Comment by BrandonWanHuanSheng** [comment]
It look like setup installer did not create a shortcut on the desktop.

**Comment by luzpaz** [comment]
How to proceed ?

**Comment by BrandonWanHuanSheng** [comment]
It look like it was exit in the winget repo.

**Comment by luzpaz** [comment]
Thank you!
