### ISSUE TITLE
[Package Issue]: Oracle.JDK.20

### ISSUE THREAD

**Issue by just-ero** [microsoft/winget-pkgs#112764]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

`Oracle.JDK.20` cannot be downloaded because of an installer hash mismatch.

### Steps to reproduce

`winget install Oracle.JDK.20`

### Actual behavior

```
Found Java SE Development Kit 20 [Oracle.JDK.20] Version 20.0.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.oracle.com/java/20/latest/jdk-20_windows-x64_bin.msi
  ██████████████████████████████   158 MB /  158 MB
Installer hash does not match.
```

### Expected behavior

`Oracle.JDK.20` installs correctly.

### Environment

```raw
Windows Package Manager v1.5.1881

Windows: Windows.Desktop v10.0.22621.1992
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0
```

**Comment by CoolPlayLin** [comment]
Hi @just-ero,
I've opened a PR in #112773 to resolve your issue
