### ISSUE TITLE
InstallShield silent install with response file

### ISSUE THREAD

**Issue by jeremytmsi** [microsoft/winget-pkgs#112817]
### Discussed in https://github.com/microsoft/winget-pkgs/discussions/112816

<div type='discussions-op-text'>

<sup>Originally posted by **jeremytmsi** July 22, 2023</sup>
Hello everyone,

I want to create a package in WinGet who uses InstallShield installer [#112792]. I created a response file who is needed for silent install but when I want to validate the manifest with Windows Sandbox, I get this error :

![image](https://github.com/microsoft/winget-pkgs/assets/36115128/3c4fd438-b9f3-4137-a1b2-19dfa6108767)

Can you help me ?

Thanks
</div>

**Comment by Trenly** [comment]
Currently additional files are not supported. This request is being tracked in
* https://github.com/microsoft/winget-pkgs/issues/246
