### ISSUE TITLE
[Package Issue]: Microsoft.Office

### ISSUE THREAD

**Issue by ricardodevries** [microsoft/winget-pkgs#112944]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Winget tries to install a version of Microsoft Office that does not match the hash online.

### Steps to reproduce

1. Go to powershell
2. Enter this into the terminal:
```
PS C:\Users\Ricardo> winget install -e --id Microsoft.Office
```
Then you should get this output:

Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.16501.20210
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe
  ██████████████████████████████  7.22 MB / 7.22 MB
Installer hash does not match.

### Actual behavior

Winget tries to install a version of Microsoft Office that does not match the hash online.

### Expected behavior

I expected Winget to properly install Microsoft Office as it has done before.

### Environment

```raw
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3208
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/78354174/6aae07ee-34a2-4d5c-a879-8c9bc2f663c4)

**Comment by CoolPlayLin** [comment]
Hi @ricardodevries 
Microsoft Office has been updated, so the hash has been changed.
I am going to remove old version soon.
