### ISSUE TITLE
[Package Request]: wfview

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113087]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://wfview.org/download/
Publisher: Elliott Liggett and Phil Taylor
Package Name: wfview
Description: Open Source interface for Icom transceivers. It provides the user with controls that may be comfortably operated from a keyboard, mouse, or touch screen interface.
Package Version: 1.64
Installer URL: https://wfview.org/download/windows-x64-release-v1-62-2/?wpdmdl=1168

**Comment by CoolPlayLin** [comment]
Holy shit................................
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/7425c59e-bc7a-4e61-a13d-78e1d3f78e5b)

**Comment by AsciiWolf** [comment]
:-) Try downloading the installer manually and running it for example in a Windows Sandbox. I am currently on a Linux machine and I don't remember what type this application's installer was.

**Comment by Dragon1573** [comment]
`wingetcreate.exe` also failed to inspect the installer type 😞

```text
D:\Workloads\winget-pkgs [issues/113183 ≡]> file.exe .\Packages\wfview-164-x86.exe
.\Packages\wfview-164-x86.exe: PE32 executable (console) Intel 80386, for MS Windows, 9 sections
```

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/0017959e-3061-4958-8ae8-41c47e7f171a)

**Comment by Dragon1573** [comment]
@AsciiWolf, @CoolPlayLin - The package is inspected as Qt Installer Framework manually.

```text
D:\Workloads\winget-pkgs [issues/113183 ≡]> .\Packages\wfview-164-x86.exe --help
Usage: D:\Workloads\winget-pkgs\Packages\wfview-164-x86.exe [options] command <args> <key=value>

Qt Installer Framework supports both GUI and headless mode. The installation operations can be invoked with the following commands and options. Note that the options marked with "CLI" are available in the headless mode only.

Commands:
  in, install - install default or selected packages - <pkg ...>
  ch, check-updates - show available updates information on maintenance tool
  up, update - update all or selected packages - <pkg ...>
  rm, remove - uninstall packages and their child components - <pkg ...>
  li, list - list currently installed packages - <regexp>
  se, search - search available packages - <regexp>
  co, create-offline - create offline installer from selected packages - <pkg ...>
  pr, purge - uninstall all packages and remove entire program directory

Options:
  -?, -h, --help                                 Displays this help.
  -v, --version                                  Displays version information.
  -d, --verbose                                  Verbose mode. Prints out more
                                                 information. Adding -d or
                                                 --verbose more than once
                                                 increases verbosity.
...
```

If `wingetcreate.exe`, `YamlCreate.ps1` and Komac support this installer type with `InstallerType: Qt`, it would be nice.

**Comment by BrandonWanHuanSheng** [comment]
Warning: https://github.com/microsoft/winget-cli/issues/3945
