### ISSUE TITLE
[Update Request]: Inkscape.Inkscape to version 1.3

### ISSUE THREAD

**Issue by k4waiiiii** [microsoft/winget-pkgs#113038]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Inkscape.Inkscape

### Package Version

1.3

### Please describe the changes you would like to see

There is new release Inkscape ver. 1.3
Download page/link: https://inkscape.org/release/inkscape-1.3/windows/64-bit/msi/dl/ OR https://media.inkscape.org/dl/resources/file/inkscape-1.3_2023-07-21_0e150ed6c4-x64_31XBEKV.msi

**Comment by CoolPlayLin** [comment]
Hi @k4waiiiii,
I've opened a PR in #113052 to resolve your issue

**Comment by k4waiiiii** [comment]
> Hi @k4waiiiii, I've opened a PR in #113052 to resolve your issue

Thank you!
