### ISSUE TITLE
[Package Request]: SyncTERM

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113048]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/syncterm/files/syncterm/
Publisher: Stephen James Hurd
Package Name: SyncTERM
Description: A cross-platform ANSI-BBS terminal designed to connect to remote BBSs via telnet, rlogin, or SSH. Supports ANSI music and the IBM charset when possible.
Package Version: 1.1
Installer URL: https://sourceforge.net/projects/syncterm/files/syncterm/syncterm-1.1/SyncTERM-1.1-setup.exe

**Comment by CoolPlayLin** [comment]
@AsciiWolf 
- It will publish in #113259
