### ISSUE TITLE
[Update Request]: SMPlayer without updates since a year

### ISSUE THREAD

**Issue by reaseno** [microsoft/winget-pkgs#113039]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

SMPlayer 22.7.0 but its current release is 23.6.0

### Steps to reproduce

Install SMPlayer

### Actual behavior

You only get an old version

### Expected behavior

current release version

### Environment

```raw
Windows-Paket-Manager v1.5.1881
Windows: Windows.Desktop v10.0.19045.3208
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.20.1881.0
```

**Comment by CoolPlayLin** [comment]
Hello @reaseno,
Could you provide us with download URLs so that we can help you out

**Comment by reaseno** [comment]
https://github.com/smplayer-dev/smplayer/releases

**Comment by CoolPlayLin** [comment]
And the package id?

**Comment by reaseno** [comment]
https://github.com/microsoft/winget-pkgs/tree/02378f85cd7358679786feed14439f5c339bb8f1/manifests/s/SMPlayer/SMPlayer

**Comment by CoolPlayLin** [comment]
Now, I am going to open a PR to resolve your issue soon

**Comment by reaseno** [comment]
I'm not really sure how it works, isn't it possible to automate it by just specifying the Github repository in the CI?

And thank you 👍

**Comment by CoolPlayLin** [comment]
Hello @reaseno,
You could see this https://github.com/vedantmgoyal2009/winget-releaser
I hope it will help you a lot

**Comment by Trenly** [comment]
> I'm not really sure how it works, isn't it possible to automate it by just specifying the Github repository in the CI?
> 
> And thank you 👍

Winget has very limited CI to detect new releases. The best way to ensure packages remain up to date is for publishers to add a winget publishing step into their own CI/CD. Other than that, it is mostly up to users of the software to contribute updates to winget (or post an issue when new updates are available). Some contributors have built tools that help automate this, but they are not perfect and are not officially supported (services could go down any time)

**Comment by reaseno** [comment]
Thank you, I will try that.
