### ISSUE TITLE
[Package Issue]: Most of Software from JetBrains Needs to be Updated

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#113126]
### Category of the issue

No applicable update found.

### Brief description of your issue

>I've noticed that most of Software from JetBrains are previous versions and I've opened PRs in
>- #113117 
>- #113120 
>- #113121 
>- #113122 
>- #113123
>- #113124 
>- #113125 
>
>**However, I am not sure if I update all of them**
>- https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains

### Update Progress
- [ ] Aqua
  - [ ] EAP
- [ ] PyCharm
  - [ ] Community 
  - [ ] Professional
- [ ] CLion
  - [ ] EAP
- [ ] DataGrip
- [ ] Gateway
- [ ] DataSpell
- [ ] GoLang
- [ ] Hub
- [ ] IntelliJIDEA
   - [ ] Community
   - [ ] Ultimate
- [ ] MPS
- [ ] PHPStorm
- [x] QonadaCLI #115344
- [ ] ReSharper
- [ ] Rider
- [ ] RubyMine
- [x] Space #121138
- [ ] TeamCity
- [x] Toolbox #120339
- [ ] WebStorm
- [ ] YouTrack
- [ ] dotUltimate

When you open a PR about these software, please mention this issue so that I could modify the progress at the first time.

**Comment by BrandonWanHuanSheng** [comment]
While I am trying to configure the update version. It give me some aqua major version.
Major Version is 231.9206
Minor Version is unsure

**Comment by CoolPlayLin** [comment]
Hello everyone,
I've edited this issue and added `Update Progress`

**Comment by CoolPlayLin** [comment]
> Summoning the master - @jedieason

Summoning the master - @jedieaston

**Comment by BrandonWanHuanSheng** [comment]
CoolPlayLin, Did you noticed that someone created an issue about Display Version? Some of the manifest file have App and Features Entries. This Display Version sometimes can be seen after install by running winget list

**Comment by BrandonWanHuanSheng** [comment]
I always check side to side to see if display version get a minor version.

**Comment by CoolPlayLin** [comment]
> CoolPlayLin, Did you noticed that someone created an issue about Display Version? Some of the manifest file have App and Features Entries. This Display Version sometimes can be seen after install by running winget list

I've noticed that the display version could case [Manifest-AppsAndFeaturesVersion-Error](https://github.com/microsoft/winget-pkgs/labels/Manifest-AppsAndFeaturesVersion-Error) like #113117

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng
May we need use Display Version with 2023.4.1 and Version with build version?

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng
May we need to use Display Version with main version and  Package Version with build version to resolve this issue?
If so, I think the work is really heavy because we need to almost refactor the whole JetBrains folder

**Comment by CoolPlayLin** [comment]
**New Update Progress**

Most of software in this issue has recently published new version. They are outdated now.

CC @BrandonWanHuanSheng @Trenly

**Comment by SpecterShell** [comment]
@vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
Will be done in few days
