### ISSUE TITLE
[Package Request]: ProgDVB

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113132]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.progdvb.com/download_progdvb.html
Publisher: Prog
Package Name: ProgDVB
Description: Universal and very powerful software for watching digital TV and listening to radio channels.
Package Version: 7.51.6
Installer URL: https://files.progdvb.com/progdvb/ProgDVB7.51.6Pro.exe

**Comment by CoolPlayLin** [comment]
@AsciiWolf
What's the type of this software?

**Comment by CoolPlayLin** [comment]
@AsciiWolf 
- It will publish in #113218
