### ISSUE TITLE
[Update Request]: Amazon.SessionManagerPlugin

### ISSUE THREAD

**Issue by GKastner87** [microsoft/winget-pkgs#113186]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Amazon.SessionManagerPlugin

### Package Version

1.2.463.0

### Please describe the changes you would like to see

Version: 1.2.398.0 is currently pushed out. Please update for latest release

**Comment by CoolPlayLin** [comment]
Hi @GKastner87 
- I've opened a PR in #113200 to resolve your issue
