### ISSUE TITLE
[Package Request]: Zandronum

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113180]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://zandronum.com/download
Publisher: Torr Samaho & Zandronum Team
Package Name: Zandronum
Description: Multiplayer oriented port, based off Skulltag, for Doom and Doom II by id Software.
Package Version: 3.1
Installer URL: https://zandronum.com/downloads/zandronum3.1-win32-installer.exe

**Comment by CoolPlayLin** [comment]
@AcsiiWolf
- It has been published in #110197 
But new version was available now, I am going to update it.

**This issue should be marked as `Update Request`**

**Comment by AsciiWolf** [comment]
Oops! I overlooked that PR. :-)
