### ISSUE TITLE
[Package Request]: Doomsday Engine

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113177]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://dengine.net/windows
Publisher: dengine.net
Package Name: Doomsday Engine
Description: Doomsday Engine is a Doom / Heretic / Hexen port with enhanced graphics.
Package Version: 2.3.1
Installer URL: https://files.dengine.net/archive/doomsday_2.3.1_x64.msi

**Comment by CoolPlayLin** [comment]
@AsciiWolf
It will publish in #113215

**Comment by CoolPlayLin** [comment]
@AsciiWolf

- It has been published in #109626

And no new version is available now.

**This issue should be marked as complete**

**Comment by AsciiWolf** [comment]
Oh my... Another PR that I overlooked. Thanks!
