### ISSUE TITLE
[Update Request]: pdfforge/ PDFCreator (+major version change)

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#113188]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

pdfforge.PDFCreator

### Package Version

~~5.1.1~~ 5.1.2

### Please describe the changes you would like to see

PDFCreator has changed the major version number in october 2022, but winget still reports v4.4.2 from march 2022 as "latest" version even if there also was a v4.4.3 released in the v4 series before they migrated to v5.

The current stable version is downloadable from the generic URL
**https://download.pdfforge.org/download/pdfcreator/PDFCreator-stable?download**

That looks to be redirected automatically to the latest stable version, ~~which is 5.1.1 currently~~
~~https://cdn.download.pdfforge.org/pdfcreator/5.1.1/PDFCreator-5_1_1-Setup.exe~~

Also, their list of past published versions is at:  https://download.pdfforge.org/download/pdfcreator/list
(even if the title of that web page is "Older releases" the most recent version on top there looks to be the current one)

**Comment by R-Adrian** [comment]
update:  i see that v5.1.2 has been released

and the generic URL
https://download.pdfforge.org/download/pdfcreator/PDFCreator-stable?download

has been changed, it now redirects to
https://cdn.download.pdfforge.org/pdfcreator/5.1.2/PDFCreator-5_1_2-Setup.exe

**Comment by Dragon1573** [comment]
@R-Adrian - This issue is resolved by https://github.com/microsoft/winget-pkgs/pull/123176 on October 24th and can be closed as completed.

```text
D:\Workloads\winget-pkgs [master ≡]> winget search -s winget -e pdfforge.PDFCreator
名称       ID                  版本
------------------------------------
PDFCreator pdfforge.PDFCreator 5.1.2
```
