### ISSUE TITLE
[Package Request]: praat

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#113183]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.fon.hum.uva.nl/praat/download_win.html
Publisher: https://www.fon.hum.uva.nl/praat/ (Phonetic Sciences, Faculty of Humanities, University of Amsterdam)
Package Name: praat
Description:  
> Praat is a speech analysis tool used for doing phonetics by computer. Praat can analyse, synthesize, and manipulate speech, and create high-quality pictures for your publications. Praat was created by Paul Boersma and David Weenink of the Institute of Phonetics Sciences of the University of Amsterdam.

Package Version: 6.3.12
Installer URL:  
https://www.fon.hum.uva.nl/praat/praat6312_win64.zip  
https://www.fon.hum.uva.nl/praat/praat6312_win32.zip

**Comment by Jvr2022** [comment]
hi i am creating the package

**Comment by Dragon1573** [comment]
I'm continue working on this issue 😄

- @Jvr2022's [pull request](https://github.com/microsoft/winget-pkgs/pull/113235) failed to pass the manifests validation and close because of stale.
