### ISSUE TITLE
[Package Request]: Qt-DAB

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113130]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/JvanKatwijk/qt-dab/releases
Publisher: JvanKatwijk
Package Name: Qt-DAB
Description: Software for listening to terrestrial Digital Audio Broadcasting (DAB and DAB+).
Package Version: 5.4
Installer URL: https://github.com/JvanKatwijk/qt-dab/releases/download/qt-dab-4.7%2F5.4/setup-qt-dab32-5.4.exe

**Comment by CoolPlayLin** [comment]
@AcsiiWolf
- It will publish in #113221
