### ISSUE TITLE
The bot sometimes tries to remove a manifest without asking for a replacement.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#11318]
Something I've noticed is that the bot will sometimes make a PR to remove a manifest without waiting for a replacement (either by opening an issue or by doing it itself). In the last 24 hours, ZeroTier and Google Chrome (#11266 and #11313) have been removed and since the PRs haven't cleared for their replacements, they are no longer in the repo at all, which means this happens:

```
PS C:\Users\Easton Pillay\projects\winget-pkgs> winget install Google.Chrome
No package found matching input criteria.
PS C:\Users\Easton Pillay\projects\winget-pkgs> # Oh no!
```

instead of the client just saying "hey! The hash hasn't been updated! use --force" which means the end-user can at least override instead of wondering why Chrome isn't offered by winget at all.

Ideally, whoever is checking PRs would catch it and merge the PR to add the new one to the repo first, but the bot shouldn't even try to open a PR to remove something at all unless it is sure that it should be removed (to the extent it can be).

**Comment by denelon** [comment]
@jedieaston thanks for informing us. You are correct, this shouldn't be the way these are handled. We should merge the add before the delete gets merged.

**Comment by denelon** [comment]
We have a workaround in place. We will provide a "permanent" fix for this in the future.

**Comment by denelon** [comment]
@jedieaston, we've implemented the changes so we don't delete the "last" manifest for a given package. Let us know if you see this behavior again.
