### ISSUE TITLE
[Package Request]: CW Skimmer

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113268]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.dxatlas.com/Download.asp
Publisher: Afreet Software
Package Name: CW Skimmer
Description: Multi-channel CW decoder and analyzer.
Package Version: 2.1
Installer URL: https://www.dxatlas.com/CwSkimmer/Files/CwSkimmer.zip

**Comment by Jvr2022** [comment]
i have done

#113292

**Comment by CoolPlayLin** [comment]
Hi @Jvr2022
> i have done
> 
> #113292
Add
```markdown
Resolve #113268
```
to link this issue with your PR

**Comment by Jvr2022** [comment]
> Hi @Jvr2022
> > i have done
> > 
> > #113292
> 
> Add
> ```markdown
> Resolve #113268
> ```
> into your PR's body so that you can link this issue with your PR
> 

Done
