### ISSUE TITLE
[Package Request]: DXLog.net

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113260]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: http://dxlog.net/sw/
Publisher: Krassy K1LZ
Package Name: DXLog.net
Description: Ham radio contest logging software by 9A5K.
Package Version: 2.5.47
Installer URL: http://dxlog.net/sw/files/DXLog.net-2.5.47.msi

**Comment by AsciiWolf** [comment]
@CoolPlayLin This is probably the second most important software from all the requests I have sent (along with [Ham Radio Deluxe](https://github.com/microsoft/winget-pkgs/issues/111363)). Feel free to make a package. :-)

**Comment by CoolPlayLin** [comment]
I am busy doing sth now, I will deal with your issue due in 11:40(UTC+8)

**Comment by CoolPlayLin** [comment]
@AsciiWolf 
- It will be published in #113269
