### ISSUE TITLE
[Update Request]: REALiX.HWiNFO 7.60

### ISSUE THREAD

**Issue by Velgus** [microsoft/winget-pkgs#113393]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

REALiX.HWiNFO

### Package Version

7.60

### Please describe the changes you would like to see

New Release: 7.60
Download Page: https://www.hwinfo.com/download/

**Comment by jessey-git** [comment]
The PR for this was closed due to some URL access shenanigans... anyone know what's up with that?  Is the host site blocking automated downloads or something?

**Comment by ianalexis** [comment]
> 

In my issue i put alternatives https://github.com/microsoft/winget-pkgs/issues/113568#issue-1827639572

New Stable release 7.60
https://www.hwinfo.com/files/hwi_760.exe
https://www.sac.sk/download/utildiag/hwi_760.exe
https://www.fosshub.com/HWiNFO.html?dwl=hwi_760.exe
