### ISSUE TITLE
[Update Request]: Anaconda3

### ISSUE THREAD

**Issue by thomass4t** [microsoft/winget-pkgs#113420]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Anaconda.Anaconda3

### Package Version

2023.07-1

### Please describe the changes you would like to see

Hello,
I already have the latest Anaconda3 package installed. However, winget reports an available update:
```
Name                                       ID                 Version   Verfügbar Quelle
----------------------------------------------------------------------------------------
Anaconda3 2023.07-1 (Python 3.11.3 64-bit) Anaconda.Anaconda3 2023.07-1 2023.07   winget
```

Maybe the "-1" in the current version is causing the issue.
2023.07-1 is newer than 2023.07.

**Comment by Dragon1573** [comment]
Should be closed as "not planned".

- Till now, nobody works on this issue.
- Newer versions (currently latest `v2023.09`) are submitted to the repository.
  - #119225
  - #121167

**Comment by stephengillie** [comment]
> Should be closed as "not planned".
> 
> * Till now, nobody works on this issue.
> * Newer versions (currently latest `v2023.09`) are submitted to the repository.
>   
>   * [New version: Anaconda.Anaconda3 version 2023.07-2 #119225](https://github.com/microsoft/winget-pkgs/pull/119225)
>   * [Add version: Anaconda.Anaconda3 version 2023.09 #121167](https://github.com/microsoft/winget-pkgs/pull/121167)
