### ISSUE TITLE
[Package Issue]: Microsoft.PowerBI Hash mismatch error when attempting to install Microsoft.PowerBI from "winget" public repository

### ISSUE THREAD

**Issue by squeekymouse89** [microsoft/winget-pkgs#113433]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match

### Steps to reproduce

winget install Microsoft.PowerBI
or winget upgrade Microsoft.PowerBI

### Actual behavior

Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.119.666.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe

    7.00 MB /  480 MB
   19.0 MB /  480 MB
   32.0 MB /  480 MB
   41.0 MB /  480 MB
   52.0 MB /  480 MB
   62.0 MB /  480 MB
   73.0 MB /  480 MB
   82.0 MB /  480 MB
   93.0 MB /  480 MB
    102 MB /  480 MB
    110 MB /  480 MB
    118 MB /  480 MB
    127 MB /  480 MB
    133 MB /  480 MB
    141 MB /  480 MB
    149 MB /  480 MB
    156 MB /  480 MB
    163 MB /  480 MB
    171 MB /  480 MB
    179 MB /  480 MB
    186 MB /  480 MB
    195 MB /  480 MB
    203 MB /  480 MB
    211 MB /  480 MB
    220 MB /  480 MB
    226 MB /  480 MB
    235 MB /  480 MB
    244 MB /  480 MB
    253 MB /  480 MB
    261 MB /  480 MB
    269 MB /  480 MB
    280 MB /  480 MB
    288 MB /  480 MB
    298 MB /  480 MB
    306 MB /  480 MB
    314 MB /  480 MB
    324 MB /  480 MB
    335 MB /  480 MB
    343 MB /  480 MB
    353 MB /  480 MB
    361 MB /  480 MB
    370 MB /  480 MB
    377 MB /  480 MB
    385 MB /  480 MB
    392 MB /  480 MB
    399 MB /  480 MB
    407 MB /  480 MB
    414 MB /  480 MB
    424 MB /  480 MB
    435 MB /  480 MB
    442 MB /  480 MB
    450 MB /  480 MB
    456 MB /  480 MB
    463 MB /  480 MB
    470 MB /  480 MB
     480 MB /  480 MB
Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Package installation without error (This seems to be happening frequently for this app) 

### Environment

```raw
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1992
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by CoolPlayLin** [comment]
Hi @squeekymouse89 
The URL always points to the latest version. Because this software has published new version, it case this issue.

I am going to open PR to resolve your issue
