### ISSUE TITLE
[Package Request]: OmniRig

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#113446]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

exe

### Please provide the following information

Download Page Url: https://www.hb9ryz.ch/omnirig/index.html
Install Options: 
Publisher: HB9RYZ
Publisher Page: https://www.hb9ryz.ch
Package Page: https://www.hb9ryz.ch/omnirig/index.html
Package Name: OmniRig
Description: Freeware CAT engine for Ham Radio Transceiver/Receiver control.
Package Version: 2.1
Installer URL: https://www.hb9ryz.ch/downloads/install_omnirigv21.zip
License: Freeware
License Page: 
Copyright: Copyright 2023 by HB9RYZ

**Comment by AsciiWolf** [comment]
@CoolPlayLin One more high priority app for me. :-)

**Comment by CoolPlayLin** [comment]
I am usually online on 16:00 ~ 22:00 UTC+8, This is the best time you call me up

**Comment by AsciiWolf** [comment]
There is a slightly older version 2.0 of OmniRig available from the original author (2.1 is from a new developer that took over this project):

https://www.dxatlas.com/omnirig/
https://www.dxatlas.com/OmniRig/Files/OmniRig.zip
(Zip containing EXE installer.)

Unlike the version 2.1, this version 2.0 has working silent installation.
