### ISSUE TITLE
[Update Request]: xanderfrangos.twinkletray 1.15.4

### ISSUE THREAD

**Issue by ianalexis** [microsoft/winget-pkgs#113570]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

xanderfrangos.twinkletray

### Package Version

1.15.4

### Please describe the changes you would like to see

There is a new release (1.15.4) available.
https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.15.4/Twinkle.Tray.v1.15.4.exe

**Comment by Dragon1573** [comment]
Issue can be closed as completed.

- Resolved by https://github.com/microsoft/winget-pkgs/pull/116835

**Comment by kudlav** [comment]
ping @stephengillie

**Comment by stephengillie** [comment]
> Issue can be closed as completed.
> 
> * Resolved by [New version: xanderfrangos.twinkletray version 1.15.4 #116835](https://github.com/microsoft/winget-pkgs/pull/116835)
