### ISSUE TITLE
PSA: Validation pipelines are unhealthy

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#11375]
All, we're seeing several failures with validation pipelines. I'll update this issue when they appear to have been resolved.

**Comment by denelon** [comment]
It looks like we may have resolved the issue. I'll update and close this bug a bit later if the services remain stable.

**Comment by denelon** [comment]
Our processing pool is having a certificate issue. Depending on where a PR is routed, it will experience an intermittent failure. We are actively working to resolve the issue.

**Comment by zachcarp** [comment]
We have identified the machine which was failing to properly install the certificate, and re-imaged it. All outstanding internal errors were re-processed without errors. I'll close this bug. If we detect this problem again we will re-open it at that time.
