### ISSUE TITLE
[Package Request]: Superhuman

### ISSUE THREAD

**Issue by michaelmhoffman** [microsoft/winget-pkgs#113725]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

exe

### Please provide the following information

Download Page Url: https://superhuman.com/download
Install Options: none
Publisher: Superhuman
Publisher Page: https://superhuman.com/
Package Page: https://superhuman.com/
Package Name: Superhuman
Description: Superhuman email client
Package Version: All
Installer URL: https://download.superhuman.com/Superhuman.exe
License: https://superhuman.com/terms
License Page: https://superhuman.com/terms
Copyright: Yes

**Comment by michaelmhoffman** [comment]
Pull request available at #118257.

**Comment by CuriousDog81** [comment]
> Pull request available at #118257.

so why don't you just close this issue?

**Comment by michaelmhoffman** [comment]
#118257 merged
