### ISSUE TITLE
[Package Request]: BellSoft LibericaJRE

### ISSUE THREAD

**Issue by CreeperKong** [microsoft/winget-pkgs#113719]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

msi

### Please provide the following information

Download Page Url: https://bell-sw.com/pages/downloads/
Install Options: MSI package
Publisher: BellSoft
Publisher Page: https://bell-sw.com/
Package Page: https://bell-sw.com/pages/downloads/
Package Name: BellSoft.LibericaJRE
Description: BellSoft LibericaJRE
Package Version: 8u382+6 11.0.20+8 17.0.8+7 etc...
Installer URL: https://download.bell-sw.com/java/8u382+6/bellsoft-jre8u382+6-windows-amd64-full.msi etc...
License: GPLv2
License Page: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
Copyright: BellSoft Corporation

**Comment by Dragon1573** [comment]
Hello, @PakhomGolynga.

I search all pull requests related to keyword "Liberica" and see most manifests of `BellSoft.LibericaJDK` are submitted by you. They are created perfectly and pass the Azure pipelines without any exceptions or errors.

I'm currently working on submitting all versions of `BellSoft.LibericaJRE` from version 8 to 21, including standard and full edition. All above pull requests passed the pipeline but labeled `Validation-Domain` error.

Could you please help review and request changes of the above pull requests? I can't figure out what is wrong and have no idea how to improve my manifests. Thank you!
