### ISSUE TITLE
[Package Request]: veeam.veeam-agent

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#114439]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

To get to the list/main page for the downloads you need to login [here](https://www.veeam.com/windows-backup-free-download.html?ad=in-text-link).
But luckily not for the release PDF and program itself!

The changelog for the latest version currently (5.0.2) is [here](https://www.veeam.com/veeam_agent_windows_5_0_2_release_notes_rn.pdf).

The program itself (zip) is [here](https://download5.veeam.com/VAW/v5/VeeamAgentWindows_5.0.2.4680.zip).

* _Reference: https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1195_
```[tasklist]
### Tasks
```

**Comment by stephengillie** [comment]
Is it possible to navigate to the InstallerUrl without logging in?

**Comment by vedantmgoyal2009** [comment]
And the install args:
/silent /accepteula /acceptthirdpartylicenses

source: https://helpcenter.veeam.com/docs/agentforwindows/userguide/installation_unattended.html?ver=60

**Comment by Macleykun** [comment]
[Veeam.VeeamAgent.installer.txt](https://github.com/microsoft/winget-pkgs/files/12432765/Veeam.VeeamAgent.installer.txt)
[Veeam.VeeamAgent.locale.en-US.txt](https://github.com/microsoft/winget-pkgs/files/12432766/Veeam.VeeamAgent.locale.en-US.txt)
[Veeam.VeeamAgent.txt](https://github.com/microsoft/winget-pkgs/files/12432767/Veeam.VeeamAgent.txt)

hope that these may somewhat help!

**Comment by UncleDan** [comment]
Just pulling [update to 6.1.2.134](https://github.com/microsoft/winget-pkgs/pull/162545).
