### ISSUE TITLE
[Package Issue]: Termius [Termius.Termius] installation fails with hash mismatch

### ISSUE THREAD

**Issue by wrathofniel** [microsoft/winget-pkgs#114544]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installation for Termius [Termius.Termius] Version 7.59.2 fails with a "Installer hash does not match" error.

### Steps to reproduce

Running `winget install Termius.Termius`

### Actual behavior

Installation fails with `Installer hash does not match; to override this check use --force`

### Expected behavior

Successfull instalation of Termius package, version 7.59.2.

### Environment

```raw
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1992
Package: Microsoft.DesktopAppInstaller v1.17.10691.0
```

**Comment by borque** [comment]
A vanity URL is used for the installer ( https://autoupdate.termius.com/windows/Install%20Termius.exe ) and it was updated to 8.0.2.0. This and issue #111576 result in the hash missmatch.
