### ISSUE TITLE
[Update Request]: FreeCAD.FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#114940]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

FreeCAD.FreeCAD

### Package Version

0.21.1

### Please describe the changes you would like to see

https://github.com/FreeCAD/FreeCAD/releases/tag/0.21.1

**Comment by luzpaz** [comment]
Updated ticket to reflect latest release https://github.com/FreeCAD/FreeCAD/releases/tag/0.21.1

**Comment by Dragon1573** [comment]
Issue can be closed.

- Resolved by https://github.com/microsoft/winget-pkgs/pull/118692
