### ISSUE TITLE
[Package Issue]: TeamViewer.TeamViewer installation fails with hash does not match

### ISSUE THREAD

**Issue by lackovic** [microsoft/winget-pkgs#115171]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When running `winget install --id TeamViewer.TeamViewer` the installation fails with the error `Installer hash does not match; this cannot be overridden when running as admin`.

### Steps to reproduce

```powershell
> winget install --id TeamViewer.TeamViewer
Found TeamViewer [TeamViewer.TeamViewer] Version 15.44.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
  ██████████████████████████████  54.9 MB / 54.9 MB
Installer hash does not match; this cannot be overridden when running as admin
```

### Actual behavior

The application is not installed and the error `Installer hash does not match; this cannot be overridden when running as admin` is produced. The same error appears regardless whether the installation command is executed with or without Administrator privileges. 

### Expected behavior

The application is installed.

### Environment

```raw
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2070
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

[WinGet-2023-08-03-20-13-24.692.log](https://github.com/microsoft/winget-pkgs/files/12254635/WinGet-2023-08-03-20-13-24.692.log)

**Comment by ImJoakim** [comment]
This should be resolved (#115061). Can you try again and report back?
