### ISSUE TITLE
[Update Request]: JetBrains.PyCharm.Community

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#115268]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JetBrains.PyCharm.Community

### Package Version

2023.2

### Please describe the changes you would like to see

New version is available now
Download Page: https://www.jetbrains.com/pycharm/download/?section=windows
**It's in the bottom of the page**
Related to #113126

**Comment by CoolPlayLin** [comment]
> `JetBrains.PyCharm.Professional` also needs updating to 2023.2. The Download Page actually leads to the Professional page :)

It appears Community Version hasn't had independent page :)

**Comment by CoolPlayLin** [comment]
- And I've opened an issue in https://github.com/microsoft/winget-pkgs/issues/116175

**Comment by dnl-blkv** [comment]
> > `JetBrains.PyCharm.Professional` also needs updating to 2023.2. The Download Page actually leads to the Professional page :)
> 
> It appears Community Version hasn't had independent page :)

Yeah, to be honest it is generally sad there is a need to update all of this stuff manually... Can't we just give the devs an opportunity to push new versions/version tags themselves like it is done in any modern feed flow such as NuGet or Docker Hub? (I apologize for being off-topic here)

**Comment by CoolPlayLin** [comment]
> > > `JetBrains.PyCharm.Professional` also needs updating to 2023.2. The Download Page actually leads to the Professional page :)
> > 
> > 
> > It appears Community Version hasn't had independent page :)
> 
> Yeah, to be honest it is generally sad there is a need to update all of this stuff manually... Can't we just give the devs an opportunity to push new versions/version tags themselves like it is done in any modern feed flow such as NuGet or Docker Hub? (I apologize for being off-topic here)

Tell you the truth, most of software is being updated by users. A lot of developers and publishers even haven't known this platform. So, most of PR is opened by users who like software 🤔

**Comment by CoolPlayLin** [comment]
These issues have opened for lots of days. I'm going to deal with them by my own

**Comment by vedantmgoyal2009** [comment]
@coolplaylin can you please remain it as it is for some more time? I need some more time to fix the automation so that all JetBrains packages are updated at once. Also, once I fix the bugs which are preventing package updates for JetBrains & some other packages, they will be regularly updated within the day of the official release or so.

**Comment by CoolPlayLin** [comment]
> @CoolPlayLin can you please remain it as it is for some more time? I need some more time to fix the automation so that all JetBrains packages are updated at once. Also, once I fix the bugs which are preventing package updates for JetBrains & some other packages, they will be regularly updated within the day of the official release or so.

No problem. I will haven't modified it in this week

**Comment by CoolPlayLin** [comment]
@dnl-blkv 
And there are also users such as @vedantmgoyal2009 spend their precious time in writing automations to update software fast or deal with issues that other users submitted😊

**Comment by treysis** [comment]
Any update on this? JetBrains has always been annoying with updating their version number FOR A GOOD TEN YEARS!!!

**Comment by Dragon1573** [comment]
I can help submitting the latest version (`2023.2.3`) of this package. At the moment, version `2023.2.1` is available.

- https://github.com/microsoft/winget-pkgs/pull/117956
