### ISSUE TITLE
[Update Request]: Microsoft.PowerToys

### ISSUE THREAD

**Issue by Pckgrapp** [microsoft/winget-pkgs#115204]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PowerToys

### Package Version

0.72.0

### Please describe the changes you would like to see

New version is available 0.72.0

**Comment by CoolPlayLin** [comment]
@Pckgrapp
This software has already opened PR in
- https://github.com/microsoft/winget-pkgs/pull/114199

**Comment by CoolPlayLin** [comment]
This PR has published in
- https://github.com/microsoft/winget-pkgs/pull/114199

**This issue should be marked as complete**

**Comment by mdanish-kh** [comment]
Close with reason: Stated above;
