### ISSUE TITLE
LibreOffice - Reboot after installation

### ISSUE THREAD

**Issue by noxifoxi** [microsoft/winget-pkgs#1154]
# Description of the problem

I installed an update to LibreOffice via winget and my PC just rebooted without a warning after the installation finished. Luckily I didn't had any important work opened.

# Proposed technical implementation details

Don't force reboots, but if a reboot is necessary, there should be a warning, so you have time to react.

**Comment by Kissaki** [comment]
I just had this happen to me. So it is still or again an issue.

**Comment by noxifoxi** [comment]
It's again an issue. Just happened to me again too, yesterday.
