### ISSUE TITLE
[Update Request]: JesseDuffield.lazygit 0.40.0

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#115437]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JesseDuffield.lazygit

### Package Version

0.40.0

### Please describe the changes you would like to see

New release 0.40.0 is available.  
Changelog: https://github.com/jesseduffield/lazygit/releases/tag/v0.40.0

**Comment by vedantmgoyal2009** [comment]
* https://github.com/microsoft/winget-pkgs/pull/115759
