### ISSUE TITLE
[Package Issue]: Docker.DockerDesktop ha the wrong installer link

### ISSUE THREAD

**Issue by EsZHONG** [microsoft/winget-pkgs#115544]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installer link for Docker.DockerDesktop v4.21.1 is pointing to latest and leading to hash mismatch. Correct link is: https://desktop.docker.com/win/main/amd64/114176/Docker%20Desktop%20Installer.exe

### Steps to reproduce

winger --id docker.dockerdesktop

### Actual behavior

installer hash does not match

### Expected behavior

docker desktop installed

### Environment

```raw
--
```

**Comment by felipepessoto** [comment]
The issue is back with 4.26.0
