### ISSUE TITLE
[Update Request]: dotPDNLLC.paintdotnet 5.0.8 -> 5.0.9

### ISSUE THREAD

**Issue by j-dc** [microsoft/winget-pkgs#115852]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

dotPDNLLC.paintdotnet

### Package Version

5.0.9

### Please describe the changes you would like to see

Also:  older versions are removed  and can't be downloaded anymore

  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.install.x64.zip
  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.install.arm64.zip
  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.winmsi.x64.zip
  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.winmsi.arm64.zip
  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.portable.x64.zip
  InstallerUrl: https://github.com/paintdotnet/release/releases/download/v5.0.9/paint.net.5.0.9.portable.arm64.zip

**Comment by stephengillie** [comment]
If older versions are still provided by the publisher, they should be available as a historical reference - in case someone wants to install and troubleshoot an issue with another program, recreate a beneficial bug, or to see what an older version of software was like. Is there a specific reason to remove the older versions of these packages?

**Comment by Pckgrapp** [comment]
#116078

**Comment by j-dc** [comment]
> Personally, I feel that if older versions are still provided by the publisher, they should be available as a historical reference - in case someone wants to install and troubleshoot an issue with another program, recreate a beneficial bug, or to see what an older version of software was like. Is there a specific reason to remove the older versions of these packages?

They can't be downloaded anymore.   Installing 5.0.8 (the latest at the time of writing)  of this package gave me 404 error.   Hence I opened this issue: https://github.com/paintdotnet/release/releases/download/v5.0.8/paint.net.5.0.8.install.x64.zip => 404

**Comment by blackzafiqz** [comment]
this issue can be closed now

**Comment by SpecterShell** [comment]
> Personally, I feel that if older versions are still provided by the publisher, they should be available as a historical reference - in case someone wants to install and troubleshoot an issue with another program, recreate a beneficial bug, or to see what an older version of software was like. Is there a specific reason to remove the older versions of these packages?

The author of this package will remove old version immediately when a new version is released.

**Comment by Trenly** [comment]
Close with reason: Newer version available in repo;
