### ISSUE TITLE
P.S.A. openjdk moniker

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#115985]
Hey everyone, we've been discussing the "openjdk" moniker. The Microsoft Java team has been working on supporting an open JDK for some time and the current package ojdkbuild.ojdkbuild does not appear to be actively supported.

Due to this we would like to remove the moniker from that package and add it to the latest Microsoft.OpenJDK.17 package.

This is not an intent to force the community to use the Microsoft Open JDK or JRE, but to ensure the moniker is being used by an actively maintained implementation.

We are also getting close to support for dependencies in WinGet 1.6. We will have additional work to reason about dependencies where there are options for packages that have support. 

We had talked about the work to create a "meta package" for something like Java Development Kits or Java Runtimes where a single dependency could be checked before installing the package, and offering options for which one to install, but this type of prompt would be breaking for automated scenarios. 

Discussion is welcome.

**Comment by denelon** [comment]
One of the options we're considering is an enhancement to dependencies with a type of "one of" check to see if a JDK is installed using the meta package. If the dependency is not satisfied then there would be an entry for the "default dependency package" to install that the manifest author could select if we decide to go with the meta package approach.

* microsoft/winget-cli/issues/1789
* microsoft/winget-cli/issues/2969

All features with the dependency label in one [query](https://github.com/microsoft/winget-cli/issues?q=is%3Aissue+is%3Aopen+label%3Adependencies+label%3Aissue-feature) at winget-cli.

**Comment by denelon** [comment]
There have been concerns with licensing and the Microsoft team publishes the manifest updates themselves and have committed to continue to support and maintain the implementation. I don't believe Oracle has expressed interest in official support via WinGet.

**Comment by SpecterShell** [comment]
Is there a way to select a lower version of OpenJDK as dependency as some Java programs do not support the latest JRE?
