### ISSUE TITLE
[Update Request]: Update WinMerge.WinMerge to 2.16.32

### ISSUE THREAD

**Issue by wmentha** [microsoft/winget-pkgs#116084]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

WinMerge.WinMerge

### Package Version

2.16.32

### Please describe the changes you would like to see

> This is a WinMerge 2.16.32 stable release.
> This release replaces earlier WinMerge stable releases as a recommended release.

https://github.com/WinMerge/winmerge/releases/tag/v2.16.32

**Download:**
32Bit: https://github.com/WinMerge/winmerge/releases/download/v2.16.32/WinMerge-2.16.32-Setup.exe
64Bit: https://github.com/WinMerge/winmerge/releases/download/v2.16.32/WinMerge-2.16.32-x64-Setup.exe
64Bit per User setup: https://github.com/WinMerge/winmerge/releases/download/v2.16.32/WinMerge-2.16.32-x64-PerUser-Setup.exe
ARM64: https://github.com/WinMerge/winmerge/releases/download/v2.16.32/WinMerge-2.16.32-ARM64-Setup.exe

**Comment by Pckgrapp** [comment]
#116152
