### ISSUE TITLE
[Package Issue]: All of Automatic Waiver Addition PRs Needs to be Merged Manually

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#116081]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

In recently Automatic Waiver Addition PR by @wingetbot, I've noticed that @wingetbot has stopped adding label [Validation-Metadata](https://github.com/microsoft/winget-pkgs/labels/Validation-Metadata) such as
- https://github.com/microsoft/winget-pkgs/pull/116079
- https://github.com/microsoft/winget-pkgs/pull/116056
- https://github.com/microsoft/winget-pkgs/pull/115779

### Steps to reproduce

Automatic Waiver Addition PR that opened by @wingetbot 

### Actual behavior

@wingetbot hasn't added [Validation-Metadata](https://github.com/microsoft/winget-pkgs/labels/Validation-Metadata) so that all of such PRs need merging manually

### Expected behavior

@wingetbot would add [Validation-Metadata](https://github.com/microsoft/winget-pkgs/labels/Validation-Metadata) so that it would automatically be merged by [microsoft-github-policy-service[bot]](https://github.com/apps/microsoft-github-policy-service)

### Environment

```raw
None
```

CC @denelon

**Comment by stephengillie** [comment]
This seems to be handled in
* #116423

**Comment by Trenly** [comment]
> This seems to be handled in
> 
> * [Add GitOps trigger for automatic waivers #116423](https://github.com/microsoft/winget-pkgs/pull/116423)

Just need to wait for a wavier to be generated to test

**Comment by stephengillie** [comment]
Using for test:
* https://github.com/microsoft/winget-pkgs/pull/115842

**Comment by CoolPlayLin** [comment]
@Trenly
But there is still [microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) automatically comment like
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/d4efe20a-4fa2-4f71-a493-73491b34e472)

It doesn't look very good

CC @stephengillie

**Comment by BrandonWanHuanSheng** [comment]
It look like this one is having some issue if we can exclude wingetbot 
https://github.com/microsoft/winget-pkgs/blob/master/.github/policies/labelAdded.validationCompleted.yml

**Comment by Trenly** [comment]
> > @Trenly But there is still [microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) automatically comment like ![image](https://user-images.githubusercontent.com/96709586/260171288-d4efe20a-4fa2-4f71-a493-73491b34e472.png)
> > It doesn't look very good
> 
> It look like this one is having some issue if we can exclude author: wingetbot https://github.com/microsoft/winget-pkgs/blob/master/.github/policies/labelAdded.validationCompleted.yml

I know exactly what the issue is and how to fix it; I simply don’t have my computer with me at the moment - I'll take care of it when I'm back at home on Monday
