### ISSUE TITLE
Allow InstallShield pass validation

### ISSUE THREAD

**Issue by Reset12138** [microsoft/winget-pkgs#1161]
#661 For example, the Adobe Acrobat Reader DC's installer type should be InstallShield.
![image](https://user-images.githubusercontent.com/40438607/82923174-2ceb5400-9fad-11ea-8d26-d7d247bb6088.png)
Although if i changed the type to inno in the yaml and the validation run successfully, winget failed the validation of type if the installertype is InstallShield.
![image](https://user-images.githubusercontent.com/40438607/82923292-51dfc700-9fad-11ea-82b3-e0e551173393.png)
![image](https://user-images.githubusercontent.com/40438607/82923512-abe08c80-9fad-11ea-9052-15a50be385af.png)
![image](https://user-images.githubusercontent.com/40438607/82923539-b569f480-9fad-11ea-8592-f7f75b167f08.png)

**Comment by oxygen-dioxide** [comment]
"InstallShild" should be "InstallShield". However, "InstallShield" failed validation, too.

**Comment by Reset12138** [comment]
@oxygen-dioxide oh thank you for catching this, I will correct the mistake right now

**Comment by denelon** [comment]
Is this issue resolved?

**Comment by oxygen-dioxide** [comment]
> Is this issue resolved?

No. Installshield needs config file #246

**Comment by Trenly** [comment]
@denelon - Since this is duplicated over at CLI, can probably be closed here?
