### ISSUE TITLE
[Update Request]: JetBrains.PyCharm.Professional

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#116175]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JetBrains.PyCharm.Professional

### Package Version

2023.2

### Please describe the changes you would like to see

New version is available now.
Download Page: https://www.jetbrains.com/pycharm/download/?section=windows

Related to https://github.com/microsoft/winget-pkgs/issues/113126

**Comment by LogicalError007** [comment]
I personally use JetBrains Toolbox for their IDEs and Android Studio. Easier to manage.
