### ISSUE TITLE
[Package Request]: VPN by Google One

### ISSUE THREAD

**Issue by mezbauddin** [microsoft/winget-pkgs#116413]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://dl.google.com/google-one/VpnByGoogleOneSetup.exe
Publisher: Google
Package Name:  Google One VPN
Description: Google VPN
Package Version: 1.3.36.292
Installer URL: https://dl.google.com/google-one/VpnByGoogleOneSetup.exe

**Comment by mezbauddin** [comment]
Hi @AsciiWolf  i am not sure where to get the missing information can you please advice?

**Comment by AsciiWolf** [comment]
Well, Package Name should probably be `Google VPN`, Description should be a short text describing what this application does, Package Version can be `latest` if there is not an easy way to find out the actual app version and Installer URL should be the actual (exe/msi(x)/zip) installer URL.

**Comment by mezbauddin** [comment]
@AsciiWolf I have just updated the details please let me know if there is anything else i need to do?

**Comment by AsciiWolf** [comment]
Looks good. If possible, please also change the Download Page Url to one that does not require login.

**Comment by AsciiWolf** [comment]
This is the correct way, however it still does not look right:

![incorrect_details](https://github.com/microsoft/winget-pkgs/assets/2339930/c07d9d24-5bca-48a2-857d-2d2a5dc2be71)

By the way, you have selected to prepare the WinGet manifest yourself. [Here](https://github.com/microsoft/winget-pkgs#submitting-a-package) is a guide how to do it. If you do not want to make the manifest yourself, edit your [first message](https://github.com/microsoft/winget-pkgs/issues/116413#issue-1846711374) in this issue to reflect that.

**Comment by AsciiWolf** [comment]
I have just found out that there is a [duplicate ticket](https://github.com/microsoft/winget-pkgs/issues/113834) about this application.

**Comment by AsciiWolf** [comment]
It should be Download **Page** Url, not **Installer** URL.

You can probably ignore the other ticket since your ticket contains more information.

**Comment by AsciiWolf** [comment]
By the way, please rename this ticket to "[Package Request]: VPN by Google One".

**Comment by mezbauddin** [comment]
HI i am so confused not sure which link you mean, also tried to use winget create and that create dpull request https://github.com/microsoft/winget-pkgs/pull/116723/files
