### ISSUE TITLE
Wingetbot does not working after someone created the pull request.

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#116516]
@wingetbot  always comments after someone created a request but do not why the wingetbot did not comments after someone created the pull request.
https://github.com/microsoft/winget-pkgs/pull/116512#issuecomment-1675811318
https://github.com/microsoft/winget-pkgs/pull/116513#issuecomment-1675808478
https://github.com/microsoft/winget-pkgs/pull/116514
https://github.com/microsoft/winget-pkgs/pull/116515

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng It appears wingetbot would run the validation pipeline after you have been open PR for 20~40 mins. It's probable to resolve #111634 because it hasn't ever appeared such error after that.

**Comment by BrandonWanHuanSheng** [comment]
OK.
