### ISSUE TITLE
[Update Request]: Graphviz.Graphviz

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#116895]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Graphviz.Graphviz

### Package Version

8.1.0

### Please describe the changes you would like to see

Release: https://gitlab.com/graphviz/graphviz/-/releases/8.1.0  
Changelog: https://gitlab.com/graphviz/graphviz/raw/main/CHANGELOG.md

**Comment by 9R2by** [comment]
I created a PR #116905

**Comment by Trenly** [comment]
Close with reason: Resolved by above PR;
