### ISSUE TITLE
[Package Issue]: GeoGebra.Classic

### ISSUE THREAD

**Issue by Orava2** [microsoft/winget-pkgs#116962]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match

### Steps to reproduce

C:\Temp>winget install GeoGebra.Classic
Found GeoGebra Classic [GeoGebra.Classic] Version 6.0.793
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.geogebra.org/package/win-autoupdate
  ██████████████████████████████  94.5 MB / 94.5 MB
Installer hash does not match; this cannot be overridden when running as admin

C:\Temp>winget install GeoGebra.Classic --scope machine
Found GeoGebra Classic [GeoGebra.Classic] Version 6.0.793
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.geogebra.org/package/win-msi6
  ██████████████████████████████  79.4 MB / 79.4 MB
Installer hash does not match; this cannot be overridden when running as admin

### Actual behavior

-

### Expected behavior

-

### Environment

```raw
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3324
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Orava2** [comment]
Insead of download URL https://download.geogebra.org/package/win-msi6 which points to the latest version, version specific URL should be used. In this case these are  https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-793-0.msi and https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-793-0.exe

**Comment by Orava2** [comment]
Command `winget install GeoGebra.Classic --scope machine` works now ok. It installs successfully the MSI version.

At the moment the newest versions are GeoGebra-Windows-Installer-6-0-794-0.msi and GeoGebra-Windows-Installer-6-0-794-0.exe but the 6-0-793 is ok for me.

**Comment by Orava2** [comment]
> If you would like to use previous version of the GeoGebra.Classic app, Run this command winget install GeoGebra.Classic -v 6.0.793 --Scope machine. If there is no version specified, they will actually use latest version on the manifest.

Sorry, I meant that the latest version on the manifest is 6.0.793 but Geogebra has released now a new version 6.0.794.
https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-794-0.msi
https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-794-0.exe

**Comment by BrandonWanHuanSheng** [comment]
Already added into the manifest.

**Comment by BrandonWanHuanSheng** [comment]
I think my publish pipelines was succeed.

**Comment by Orava2** [comment]
This doesn't work https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/GeoGebra/Classic/6.0.794/GeoGebra.Classic.installer.yaml .

1. Scope tags are missing.
```
winget upgrade GeoGebra.Classic --scope machine
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
```

2. This will be broken as soon as Geogebra releases a new version. The installer hash won't match to the new installer.
```
  InstallerUrl: https://download.geogebra.org/package/win-autoupdate
  InstallerSha256: FDFF1C47175A30A44FDB62FC04CF14900CFE76E33C1BD0286CE5C1CF525B8F60

  InstallerUrl: https://download.geogebra.org/package/win-msi6
  InstallerSha256: 85E8E5B456A8325DE9D9CED8374B6D074D2D0B225BB691E4AE05CDCB4960E24C

```
This will always work.
```
  InstallerUrl: https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-794-0.exe
  InstallerSha256: FDFF1C47175A30A44FDB62FC04CF14900CFE76E33C1BD0286CE5C1CF525B8F60

  InstallerUrl: https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-794-0.msi
  InstallerSha256: 85E8E5B456A8325DE9D9CED8374B6D074D2D0B225BB691E4AE05CDCB4960E24C

```

**Comment by Trenly** [comment]
> If you would like to use previous version of the GeoGebra.Classic app, Run this command winget install GeoGebra.Classic -v 6.0.793 --Scope machine. If there is no version specified, they will actually use latest version on the manifest.

This will not aways work for GeoGebra, as they remove old versions from the site when new versions are released, keeping only a few versions back. Notice how 6.0.785 is no longer available on their website

**Comment by mdanish-kh** [comment]
So looks like the versioned URLs are similar to the vanity URLs but worse in sense that we have to look for a new URL for every new release. I'm all for the change.

**Comment by Tataz2** [comment]
If only vanity URLs are used, old version should be removed. Eg this doesn't work  https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/GeoGebra/Classic/6.0.791/GeoGebra.Classic.installer.yaml

**Comment by mdanish-kh** [comment]
Yes, they would be removed once wingetbot starts working again

**Comment by OfficialEsco** [comment]
Well, i remember GeoGebra having a lot of issues with both url types, there were for example https://github.com/microsoft/winget-pkgs/issues/62404 where all of them were outdated.

So there is 2 ways, someone really need to maintain GeoGebra so its never outdated.
Or the people need to wait for Wingetbot to catch the outdated hash which from my memory did not always work. Maybe its gotten better since this is the only issue in a year 🤷‍♂️

**Comment by BrandonWanHuanSheng** [comment]
Do you want me to expand all out previous version?

**Comment by Orava2** [comment]
```
C:\windows\system32>winget install GeoGebra.Classic
Found GeoGebra Classic [GeoGebra.Classic] Version 6.0.794
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.geogebra.org/package/win-autoupdate
  ██████████████████████████████   106 MB /  106 MB
Installer hash does not match; this cannot be overridden when running as admin
```

This just won't work. We start using our own source for GeoGebra.

**Comment by Orava2** [comment]
winget install GeoGebra.Classic --scope machine
Found GeoGebra Classic [GeoGebra.Classic] Version 6.0.801
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.geogebra.org/package/win-msi6
  ██████████████████████████████  87.9 MB / 87.9 MB
Installer hash does not match; this cannot be overridden when running as admin
