### ISSUE TITLE
[Update Request]: Schniz.fnm 1.35.1

### ISSUE THREAD

**Issue by YuzhiZhang** [microsoft/winget-pkgs#117122]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Schniz.fnm

### Package Version

1.35.1

### Please describe the changes you would like to see

There is a new release([1.35.1](https://github.com/Schniz/fnm/releases/tag/v1.35.1)) available

**Comment by YuzhiZhang** [comment]
[117458](https://github.com/microsoft/winget-pkgs/pull/117458)

**Comment by Trenly** [comment]
Close with reason: Resolved by above PR;
