### ISSUE TITLE
Add ILspy package

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/winget-pkgs#1172]
# Description of the new feature/enhancement

I use ILspy on Windows to decompile .NET assemblies for inspection of their public and private APIs. This package is currently provided by Scoop package manager, but it would be great if it were ported over to WinGet as well.

Add a new package to WinGet package manager for .NET ILspy utility.

https://github.com/icsharpcode/ILSpy

Here is an example manifest from the Scoop package manager:

https://github.com/lukesampson/scoop-extras/blob/master/bucket/ilspy.json

# Proposed technical implementation details (optional)

**Comment by Teraskull** [comment]
Not possible yet due to issue #174

**Comment by Marv51** [comment]
Not sure if it works with 0.2 but once Store download works, this should be easy, since ILSpy is available here: https://www.microsoft.com/store/productId/9MXFBKFVSQ13

**Comment by Trenly** [comment]
This is now available through the store; 
@ItzLevvie - Do you think we should keep this open until we can add the .zip to the community repo?
