### ISSUE TITLE
Add package manifest for iperf3

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/winget-pkgs#1173]
# Description of the new feature/enhancement
I use `iperf3` to perform network bandwidth tests on both Windows and Linux systems. Right now, I use the Scoop package manager, which includes the `iperf3` package. It would be great if this could get migrated over to WinGet as well.

Application Website: https://iperf.fr/
Scoop manifest: https://github.com/se35710/scoop-main/blob/master/bucket/iperf3.json

# Proposed technical implementation details (optional)

**Comment by Teraskull** [comment]
Not possible yet due to issue #174

**Comment by dolsem** [comment]
Any updates on this?

**Comment by MagicAndre1981** [comment]
now WinGet 1.4 support .zip can we get it added? Latest version 3.13 for Windows can be found here:

https://files.budman.pw/iperf3.13_64.zip

**Comment by Trenly** [comment]
Unfortunately this is a Zipped binary file and not just a portable EXE. Because of the way symlinks work, this is now blocked by https://github.com/microsoft/winget-cli/issues/2711

cc @denelon for labeling with Zipped Binary

**Comment by Blacklands** [comment]
Since microsoft/winget-cli/issues/#2711 is now merged, this issue is now no longer blocked, right?

**Comment by Trenly** [comment]
No; This is still blocked by -
* #186398

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`

**Comment by MagicAndre1981** [comment]
>  Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`

nice improvement. Can you please create a PR that shows this new feature?
