### ISSUE TITLE
Add draw.io (diagrams.net) desktop application manifest

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/winget-pkgs#1174]
# Description of the new feature/enhancement

I use the draw.io (now known as diagrams.net) desktop application on Windows 10 to create diagrams and drawings. This package is installable via the Scoop package manager, but it would be great if it were ported over to the WinGet package manager.

Desktop Application: https://github.com/jgraph/drawio-desktop/releases/tag/v13.0.3
Scoop manifest example: https://github.com/lukesampson/scoop-extras/blob/master/bucket/draw.io.json

# Proposed technical implementation details (optional)

**Comment by ath0mas** [comment]
draw.io is already available : `winget install JGraph.Draw`

https://github.com/microsoft/winget-pkgs/tree/master/manifests/JGraph/Draw
version 13.0.3

**Comment by pcgeek86** [comment]
Gotcha. I missed that due to the weird name!
