### ISSUE TITLE
[Package Request]: MaxLauncher

### ISSUE THREAD

**Issue by AwesomeDog** [microsoft/winget-pkgs#117453]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://maxlauncher.sourceforge.io/downloads.html
Publisher:MaxLauncher
Package Name:MaxLauncher.MaxLauncher
Description:MaxLauncher is an open source tabbed launcher. Its primary goal is to reduce the amount of time to run a program/file. 
Package Version:1.31.0.0
Installer URL:https://sourceforge.net/projects/maxlauncher/files/MaxLauncher/1.31.0.0/maxlauncher_1.31.0.0_setup.exe/download  not sure if its right

**Comment by Dragon1573** [comment]
@AwesomeDog Azure Pipeline seems blocked by SourceForge. Maybe downloading and installing applications via `winget.exe` violate ToS of SourceForge?

https://github.com/microsoft/winget-pkgs/pull/122410#issuecomment-1758616142

**Comment by AwesomeDog** [comment]
> @AwesomeDog Azure Pipeline seems blocked by SourceForge. Maybe downloading and installing applications via `winget.exe` violate ToS of SourceForge?
> 
> [#122410 (comment)](https://github.com/microsoft/winget-pkgs/pull/122410#issuecomment-1758616142)

https://sourceforge.net/p/forge/documentation/Release%20Files%20for%20Download/
