### ISSUE TITLE
[Package Issue]: Remove All Beta/Eap Version from JetBrains.Kotlin.Compiler

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#117473]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Remove all unstable version from JetBrains.Kotlin.Compiler 

### Steps to reproduce

N/A

### Actual behavior

N/A

### Expected behavior

N/A

### Environment

```raw
N/A
```

**Comment by vedantmgoyal2009** [comment]
@Trenly @mdanish-kh @stephengillie close with reason: resolved in mentioned PRs

**Comment by Trenly** [comment]
K.
