### ISSUE TITLE
Add nmap package manifest to WinGet

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/winget-pkgs#1175]
# Description of the new feature/enhancement
I use the nmap utility to perform network security monitoring and penetration testing. Today, I install this package via the Scoop package manager, but it would be great to have this ported over to the WinGet package manager for Windows 10.

Scoop manifest example: https://github.com/ScoopInstaller/Main/blob/master/bucket/nmap.json
App website: https://nmap.org/download.html

# Proposed technical implementation details (optional)

**Comment by DocBox12** [comment]
Issue to close.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/Insecure/Nmap/7.80.yaml
