### ISSUE TITLE
[Package Request]: ParaView 5.11.1

### ISSUE THREAD

**Issue by hedegaardDK** [microsoft/winget-pkgs#117586]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.11&type=binary&os=Windows&downloadFile=ParaView-5.11.1-Windows-Python3.9-msvc2017-AMD64.msi
Publisher: kitware Inc.
Package Name: ParaView-5.11.1-Windows-Python3.9-msvc2017-AMD64
Description: ParaView is the world’s leading open source post-processing visualization engine. It integrates with your existing tools and workflows, allowing you to build visualizations to analyze data quickly. With its open, flexible, and intuitive user interface, you can analyze extremely large datasets interactively in 3D or programmatically using ParaView’s batch processing.
Package Version: 5.11.1
Installer URL: ?

**Comment by Dragon1573** [comment]
@hedegaardDK The requested version (`v5.11.1`) of ParaView is already available as `KitWare.ParaView`. Above attached PR is a newer version of ParaView.
