### ISSUE TITLE
[Package Issue]: Unity.UnityHub

### ISSUE THREAD

**Issue by just-ero** [microsoft/winget-pkgs#117669]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

`Unity.UnityHub` cannot be downloaded because of an installer hash mismatch.

### Steps to reproduce

`winget install Unity.UnityHub`

### Actual behavior

```
Found Unity Hub [Unity.UnityHub] Version 3.5.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe
  ██████████████████████████████   116 MB /  116 MB
Installer hash does not match.
```

### Expected behavior

`Unity.UnityHub` installs correctly.

### Environment

```raw
Windows Package Manager v1.5.2201

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #117640;
