### ISSUE TITLE
Handbrake has duplicate manifests

### ISSUE THREAD

**Issue by sanyer** [microsoft/winget-pkgs#11766]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Handbrake has duplicate manifests:

```none
[ winget search handbrake]
Name      Id                         Version Source
----------------------------------------------------
HandBrake thehandbraketeam.handbrake 1.3.3   winget
HandBrake HandBrake.HandBrake        1.3.3   winget
```

https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HandBrake/HandBrake/1.3.3
and
https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/thehandbraketeam/handbrake/1.3.3

# Steps to reproduce

# Expected behavior
Only one manifest should point to handbrake installer.

# Actual behavior
Two manifests pointing to the same installer.

# Environment

```none
[winget --info]
Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.928
Package: Microsoft.DesktopAppInstaller v1.11.11102.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by denelon** [comment]
@sanyer I'm not sure which "publisher" is the best choice for Handbrake. Do you know what the entry in "Add / Remove Programs" looks like? The list feature attempts to match packages based on meta-data. When the publisher and the package name match, the experience tends to be better for users when they use `winget upgrade`. I'd suggest keeping the correct one and removing the other.

**Comment by OfficialEsco** [comment]
@jedieaston

@denelon 
![image](https://user-images.githubusercontent.com/15158490/116689106-f33e7c80-a9b7-11eb-838d-207510566480.png)

Since Publisher and PackageIdentifier can be different i don't think its too big of a deal, we have a few packages where Publisher have been updated to what Programs and Features say and don't match the PackageIdentifier at all anymore.

**Comment by jedieaston** [comment]
Up to you, but I think Handbreak.Handbreak is more discoverable. We can set the publisher attribute to "The HandBreak Team".

**Comment by jedieaston** [comment]
Okay, I moved everything to Handbrake.Handbrake, and set the Publisher to "The Handbrake Team". I suppose this can be closed now.

**Comment by denelon** [comment]
Thanks @jedieaston!
