### ISSUE TITLE
Add AutoHotkey package manifest to WinGet

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/winget-pkgs#1176]
# Description of the new feature/enhancement

I use the open source AutoHotkey package to perform automation tasks on Windows 10. Today, I install this using the Scoop package manager, but it would be great if it were ported over to the WinGet package manager, so I can migrate to this instead.

App website: https://www.autohotkey.com/
Scoop manifest example: https://github.com/lukesampson/scoop-extras/blob/master/bucket/autohotkey.json

# Proposed technical implementation details (optional)

**Comment by Teraskull** [comment]
PR #882
