### ISSUE TITLE
[Package Issue]: Docker.DockerDesktop

### ISSUE THREAD

**Issue by rkolka** [microsoft/winget-pkgs#118191]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Docker.DockerDesktop Installer hash does not match.

### Steps to reproduce

winget upgrade Docker.DockerDesktop

### Actual behavior

Found Docker Desktop [Docker.DockerDesktop] Version 4.22.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe
  ██████████████████████████████   579 MB /  579 MB
Installer hash does not match.

### Expected behavior

Successfully installed

### Environment

```raw
Windows Package Manager v1.5.2201
Windows: Windows.Desktop v10.0.19045.3324
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by CuriousDog81** [comment]
After the update (yes, now the version if higher), it's working.
