### ISSUE TITLE
[Package Issue]: Sky.SkyGo

### ISSUE THREAD

**Issue by schlamar** [microsoft/winget-pkgs#118174]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Apparently there are multiple versions of Sky Go for different locations. Installing Sky Go from German page (https://www.sky.de/produkte/sky-go) shows as login:

<img width="295" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/238652/3dd42a59-fbc1-4371-bbc4-a1b99535f533">

Installing the Sky Go from winget shows a totally different login (I assume UK version):

<img width="259" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/238652/7e1e129f-7036-47bd-bf5f-0e12313dfd5a">

I had the German version installed and a winget upgrade transformed my German installation to this other version. I cannot login with my German user so the upgrade completely broke the application for me.

Both version numbers are the same! 

<img width="186" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/238652/292aa965-a666-408a-b52e-dea661913258">

I have no idea how to distinguish them. If that is generally not possible I think Sky Go shouldn't be included as package at all because of the breaking behavior after upgrade.

### Steps to reproduce

see above

### Actual behavior

see above

### Expected behavior

see above

### Environment

```raw
> winget --info
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by uzzle1987** [comment]
@schlamar Can you try it again. My Pull-Request was accepted. A "de-DE" system should now download the /DE/ installer and all other systems the /GB/ installer. When I tested the manifest on my system the /DE/ installer was used

**Comment by Trenly** [comment]
Close with reason: Resolved by linked PR;

**Comment by mike2212** [comment]
Issue appears to be re-occurring.  In my case, de-DE version was installed when it should have been en-GB.

**Comment by SpecterShell** [comment]
> Issue appears to be re-occurring. In my case, de-DE version was installed when it should have been en-GB.
> 
> using `--Locale en-GB` resolves issue

The en-GB one has felled behind for a while. All other regions (de-DE, de-AT, it-IT) have the latest version `24.1.3.0` while the en-GB one is still staying at `23.5.1`.
