### ISSUE TITLE
Winget install Google.ChromeDev fails with hash check

### ISSUE THREAD

**Issue by leotsarev** [microsoft/winget-pkgs#11818]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

# Steps to reproduce

`winget install Google.ChromeDev`

# Expected behavior

Install succesfull.

# Actual behavior

```none
Found Google Chrome Dev [Google.ChromeDev]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  ██████████████████████████████  75.9 MB / 75.9 MB
Installer hash does not match; to override this check use --force
```

# Environment

```none
Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.964
Package: Microsoft.DesktopAppInstaller v1.11.11102.0
```

**Comment by jedieaston** [comment]
Sorry about that, looks like the bot has been on vacation. Once #11823 closes you should be good to go!

(p.s. @denelon does the bot have support for multiarch manifests? It sometimes does them but a lot of the time it doesn't. I've been doing Chrome Stable manually (when I see it, about once a week) since the bot doesn't do it anymore.)

**Comment by denelon** [comment]
@jedieaston we're still working through multi-architecture changes across the validation pipelines. There are a fairly large number of changes in flight working their way through the environments. This morning was a big push. I'll try to keep an eye on this.
