### ISSUE TITLE
[Package Request]: coreutils

### ISSUE THREAD

**Issue by pedrohgmacedo** [microsoft/winget-pkgs#118259]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/ScoopInstaller/Main/blob/master/bucket/coreutils.json
Publisher: scoop / fsf
Package Name: coreutils
Description: The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system. These are the core utilities which are expected to exist on every operating system.
Package Version: see download page url
Installer URL: https://github.com/ScoopInstaller/Main/blob/master/bucket/coreutils.json

**Comment by Dragon1573** [comment]
@pedrohgmacedo Sorry, we can't achieve this.

Package is release in multiple `*.tar.lzma` compressed archived files. WinGet does not support this kind of compressed files.

WinGet is not intended for installing porable, uncompress-as-install applications. In this case, Scoop is good enough.
