### ISSUE TITLE
[Package Request]: Tencent.QQ (NT Framework)

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#118245]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

## Important Note

This package aims for zh-CN users. Following properties should be set for `zh-CN` locale.

This package is NOT an upate of package `Tencent.QQ`. They are created by different "framework" ("NT" this package while "Native" the previously exists one) and should be labeled with different identity.

Related PR: #118186 #113453 #111273

*****

## Download URL

Homepage: `https://im.qq.com/pcqq/index.shtml`

- x64
  - Link: `https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe`
  - SHA-256: `0B91FB920B205F41AADAFA16621B0072A4A8F7EECC53FB82F46C5EE902176E6D`
- x86:
  - Link: `https://dldir1.qq.com/qqfile/qq/QQNT/63f8bbfe/QQ9.9.2.16183_x86.exe`
  - SHA-256: `15DF6BFDD1C643DDF1DAB6BC7AAF3183D761D6D5C99C1A03157275227F56DBFF`

## Publisher

腾讯科技（深圳）有限公司

## Package Name

腾讯QQ

## Description

腾讯 QQ，8 亿人在用的即时通讯软件。你不仅可以在各类通讯终端上通过 QQ 聊天交友，还能进行免费的视频、语音通话，或者随时随地收发重要文件。

## Package Version

`v9.9.2.16183`

## Installer URL

- x64
  - Link: `https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe`
  - SHA-256: `0B91FB920B205F41AADAFA16621B0072A4A8F7EECC53FB82F46C5EE902176E6D`
- x86:
  - Link: `https://dldir1.qq.com/qqfile/qq/QQNT/63f8bbfe/QQ9.9.2.16183_x86.exe`
  - SHA-256: `15DF6BFDD1C643DDF1DAB6BC7AAF3183D761D6D5C99C1A03157275227F56DBFF`

**Comment by SpecterShell** [comment]
It is impossible to add this package to winget-pkgs because the installer doesn't support silent installation even if it is based on the same installer technology used in the old edition (`Tencent.QQ`). Its self-update function also executes the installer directly without any parameters.

**Comment by Dragon1573** [comment]
> It is impossible to add this package to winget-pkgs ...

Okay ... This issue and related PRs can be closed. Hope that further version support silent installation.

Willing to contribute then.
