### ISSUE TITLE
[Package Issue]: Microsoft.PowerBI 2.120.731

### ISSUE THREAD

**Issue by JvDrunen** [microsoft/winget-pkgs#118343]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The version in the manifest is not the same as the one in the registry after installation.
early version of powerBI have a .0 at the end. (in the version and manifest) which indicates an actual version instead of a semver.

the latest version misses this .0 which is not consistent with the installation package as the result in the registry has a .0 at the end.

We use the manifest to get the installer information and using this version we get installation errors because the version is not matching the installed (display)version

### Steps to reproduce

![Screenshot 2023-08-29 120744](https://github.com/microsoft/winget-pkgs/assets/30151600/27e85953-78b7-44c3-985a-7f8c7e83539f)

### Actual behavior

after installation
![Screenshot 2023-08-29 120839](https://github.com/microsoft/winget-pkgs/assets/30151600/099408ed-5a65-4a93-862a-24c19738e801)

### Expected behavior

Expected to have a .0 added to the manifest version in the package repo

### Environment

```raw
All windows
```

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #118352;

Thanks @PckgrBot
