### ISSUE TITLE
[Update Request]: Python 3.11.5

### ISSUE THREAD

**Issue by MajorTanya** [microsoft/winget-pkgs#118360]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Python.Python.3.11

### Package Version

3.11.5

### Please describe the changes you would like to see

Python 3.11.5 was released on 2023-08-24.
Download Page: https://www.python.org/downloads/release/python-3115/
Installer URL: https://www.python.org/ftp/python/3.11.5/python-3.11.5-amd64.exe
Package Version: 3.11.5150

**Comment by Trenly** [comment]
Close with reason: Resolved by linked PR;
