### ISSUE TITLE
GitHub Release Automation

### ISSUE THREAD

**Issue by RichiCoder1** [microsoft/winget-pkgs#1184]
# Description of the new feature/enhancement

Somewhat spitball of an idea, but it'd be nice to automate going from a GitHub Release -> Winget-pkgs Pull Request. A *lot* of OSS distributes binaries via GitHub Releases now, so it'd be one less step for them to be able to map releases.

# Proposed technical implementation details

I'm not sure TBH. The ability to configure a GitHub Project + an asset -> manifest mapping, and then a Msft service that polled those endpoints respectfully and created PRs on new releases?

**Comment by dfreilich** [comment]
Great idea! It seems like there's more traction on dealing with this in #500

**Comment by denelon** [comment]
We have a new tool coming very soon (think days, not weeks) that will help with this issue. https://github.com/microsoft/winget-cli/issues/157 we will include a standalone .exe you can include in CI pipelines to create/submit manifests and new package versions.

**Comment by denelon** [comment]
Here is the link to the new [wingetcreate](https://github.com/microsoft/winget-create) tool designed to help build manifests. The PR is in progress so soon you will be able to `winget install wingetcreate`.

**Comment by SonOfDiablo** [comment]
I'm not sure if this applies 100% to this issue.

But other package managers has great ways of handling manifest updates, such as [Scoop's Autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate).

Could be worth looking into for inspiration.

**Comment by denelon** [comment]
@SonOfDiablo we would prefer Independent Software Vendors (ISVs) and publishers to produce their own manifests. The wingetcreate utility can run as an .exe in a GitHub action to generate and submit manifests. The secondary option would be to "self-serve" GitHub releases. We've added a ".package" file for #100 and I think we could extend that functionality for this scenario.

**Comment by vedantmgoyal2009** [comment]
Unless the winget team makes something their own, I have created https://github.com/vedantmgoyal2009/winget-pkgs-automation for this.

As a side-note, I have excluded packages for e.g. Oh-My-Posh and Rainmeter which developers have automated or like to publish themselves.

**Comment by denelon** [comment]
@vedantmgoyal2009 as we get closer to having the ability to add a .packages file to support "pull" style automation vs. "push" from a publisher, we might be able to leverage some of the the work you've done. Thanks for building it open source under MIT license. That makes it much easier for us to look at how we might integrate this work into the Windows Package Manager app repository.

**Comment by vedantmgoyal2009** [comment]
Thanks, @denelon, it was the comment I posted yesterday, but anyways thanks for replying here too.

**Comment by denelon** [comment]
I think this issue could have been closed a while back. There are a few different automated options available.

Here are a couple of examples using [wingetcreate](https://github.com/microsoft/winget-create):
* [PowerToys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml)
* [Oh-My-Posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml)
