### ISSUE TITLE
[Package Issue]: KeePassXCTeam.KeePassXC

### ISSUE THREAD

**Issue by Elijahh177** [microsoft/winget-pkgs#118590]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

WinGet points to the wrong (legacy) installer. The new installer should be used instead.

### Steps to reproduce

`winget show KeePassXCTeam.KeePassXC`

### Actual behavior

Installer-URL: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-Win64-LegacyWindows.msi

### Expected behavior

Installer-URL: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-Win64.msi

### Environment

```raw
Windows: Windows.Desktop v10.0.22621.2134
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by Elijahh177** [comment]
Related KeepassXC issue: https://github.com/keepassxreboot/keepassxc/issues/9800

**Comment by CuriousDog81** [comment]
Updated locally, pushing to GitHub later

**Comment by Trenly** [comment]
Close with reason: Resolved by linked PR;

**Comment by Zocker1999NET** [comment]
installed KeePassXC today with freshly installed Windows 11, it still used the legacy installer. Shouldn't this fixed?
