### ISSUE TITLE
Power BI Desktop [Package Issue]: Package.Identifer

### ISSUE THREAD

**Issue by herveyy** [microsoft/winget-pkgs#118583]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Seems to be a mismatch again on the Power BI Desktop Installer Hash.

winget installer HASH - 248376787a322ef9f70b2588ecc70fdee8d0d71a509fb31ce343b965d9dfdbe4
winget Installer URL - https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe

when you download manually and check the HASH from within winget the HASH of the file is actually.

Sha256: 89d1eee9552af3c33d9af0941da642fb9c53ab9a53d20dd11bf363e9c547bb2a

### Steps to reproduce

winget install Microsoft.PowerBI

### Actual behavior

fails on hash check

### Expected behavior

installation

### Environment

```raw
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
Package: Microsoft.DesktopAppInstaller v1.17.10691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #118524;
