### ISSUE TITLE
[Package Issue]: qBittorrent.qBittorrent

### ISSUE THREAD

**Issue by hueldoeu** [microsoft/winget-pkgs#118557]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget upgrade qBittorrent.qBittorrent only works, if qbittorrent had been closed and removed from the RAM. otherwise winget says "installation successfull" although qbittorrent had not been upgraded.

first of all for enthusiastic reasons i have not installed the old qbittorrent with qt5-api and libtorrent 1.2 but the qbittorrent_4.5.5_lt20_qt6_x64_setup.exe with qt6 and lt2.0. i have also installed it manually from the official site.
i wish, there would be an msi-file too, but so far there is only qbittorrent_4.5.5_lt20_qt6_x64_setup.exe made with NSIS.

when there is an update, like 4.5.4 to 4.5.5, first qbittorrent tells me about it, then it's visible in winget upgrade. when i winget upgrade qbittorrent, the upgrade process is going on and ends successfully, but no files had been exchanged and no new files and no new folders had been created. 4.5.4 sitll running in RAM, useable. i know this problem when i had upgraded qbittorrent manually. the setup-exe-files says, i have to exit and remove qbittorrent from the RAM first. in winget, this error will be ignored, it will be not visible. when i winget upgrade again, qbittorrent 4.5.5, the update, is not visible. when i deinstall qbittorrent from my storage, the exe-file (main file) is still running. it seems that qbittorrent is just a big exe-file with a database file and lots of langauge-files. when i close qbittorrent and remove it from the RAM, i can delete the last file.

for safety reasons, i installed qbittorrent_4.5.4_lt20_qt6_x64_setup.exe the older version again manually, closed it, removed it from RAM and upgraded with winget upgrade qbittorrent. now everything is perfect.

there is also a personal problem. i write winget ugprade instead of winget upgrade. i wish that the command "winget upgrade" will be shorter like "winget ug".

### Steps to reproduce

wait for an update for qbittorrent, then winget upgrade qbittorrent, while qbittorrent is still running. qbittorrent will not be upgraded, but still running fine, while even after closing, winget upgrade won't work since it told itself "winget upgrade qbittorrent had been successfull".

### Actual behavior

qbittorrent is not upgrading

### Expected behavior

qbittorrent is upgrading or at least showing an error, where you can see that you have to close qbittorrent first.

### Environment

```raw
C:\Users\Nutzer>winget --info
Windows-Paket-Manager v1.5.2201
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.3324
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by hueldoeu** [comment]
i also write wignet instead of winget a lot.

**Comment by xavier2k6** [comment]
Please see: https://github.com/qbittorrent/qBittorrent/issues/18115

**Comment by denelon** [comment]
I commented at the linked issue regarding the way WinGet uses expected return codes to inform users when an application is running, or a file is in use.
