### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2015+.x64

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-pkgs#118664]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When you run

```
winget upgrade --all
```

Microsoft.VCRedist.2015+.x64 is not updated.

### Steps to reproduce

Run following 2 times:

```
winget upgrade --all
```

### Actual behavior

2nd time you see it is not updated

### Expected behavior

Should update

### Environment

```raw
winget --info
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2215
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
```
```


### Screenshots and Logs

_No response_

**Comment by Trenly** [comment]
This is a known issue with packages that install Side-By-Side. If you run `winget list 'Visual C++'` you will almost certainly see two versions installed. 

Because both an older version is installed, the package shows up as needing an upgrade, but because the latest version is also installed, is skipped when performing the upgrades.

* https://github.com/microsoft/winget-cli/issues/2129

Close with reason: Known issue logged at winget-cli; Please refer to Area-Matching and Side-By-Side tags for related issues
