### ISSUE TITLE
[Package Issue]: Daum.PotPlayer

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-pkgs#118682]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Upgrade all installed PotPlayer x86 on a x64 system with PotPlayer x64 installed.

### Steps to reproduce

Install PotPlayer using download from website
Run upgrade all

Maybe add `--force`

### Actual behavior

Wrong architecture version being installed in update.

### Expected behavior

Install the matching architecture

### Environment

```raw
winget --info
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2215
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
```
```


### Screenshots and Logs

_No response_

**Comment by unwillinglyawesome** [comment]
#118934

**Comment by vedantmgoyal2009** [comment]
@Trenly @stephengillie @mdanish-kh close with reason: resolved in #118934

**Comment by Trenly** [comment]
@vedantmgoyal2009  - Testing with that change gives Installer Hash mismatch. Probably needs another update before this can be resolved

**Comment by unwillinglyawesome** [comment]
118570 -- broken commit
118934 -- I fix it
119243 -- some bot breaks it again and it gets approved once again

@stephengillie

**Comment by unwillinglyawesome** [comment]
#118570 -- broken commit
#118934 -- I fix it
#119243 -- some bot breaks it again and it gets approved once again

@stephengillie

**Comment by unwillinglyawesome** [comment]
#119852
