### ISSUE TITLE
[Package Request]: PolyMC

### ISSUE THREAD

**Issue by rokejulianlockhart** [microsoft/winget-pkgs#118715]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://polymc.org/download/
Publisher: PolyMC
Package Name: PolyMC.PolyMC
Description: An Open Source Minecraft launcher with the ability to manage multiple instances, accounts, and mods. Focused on user freedom and free redistributability.
Package Version: 5.1
Installer URL: https://github.com/PolyMC/PolyMC/releases/download/5.1/PolyMC-Windows-Setup-5.1.exe

**Comment by mdanish-kh** [comment]
There was a concern about PolyMC not being safe anymore

- https://github.com/microsoft/winget-pkgs/issues/84685

**Comment by rokejulianlockhart** [comment]
https://prismlauncher.org/wiki/overview/faq/#what-happened

**Comment by KaspianDev** [comment]
> There was a concern about PolyMC not being safe anymore
> 
>     * [[Package Issue]: PolyMC.PolyMC #84685](https://github.com/microsoft/winget-pkgs/issues/84685)

fyi its not, in fact never was

**Comment by binex-dsk** [comment]
> There was a concern about PolyMC not being safe anymore
> 
> - https://github.com/microsoft/winget-pkgs/issues/84685
> 
> 

That was over a year ago, the maintainer didn't go rogue. There is no malware or anything else in PolyMC, you can look at the code for yourself

**Comment by RuiNtD** [comment]
I can't say anything regarding if PolyMC has malware or not. The application is horribly outdated and succeeded by Prism Launcher. Not to mention that its transphobic lead developer did a hostile takeover of the project over my own personal beliefs. Nobody in the Minecraft community trusts PolyMC anymore, or its developer.

**Comment by KaspianDev** [comment]
> I can't say anything regarding if PolyMC has malware or not. The application is horribly outdated at this point and succeeded by Prism Launcher. Not to mention that its transphobic lead developer did a hostile takeover of the project over my own personal beliefs. Nobody in the Minecraft community trusts PolyMC anymore, or its developer.

why do views of other people bother you so much if they don't push them into their software, unlike the one you mentioned.
