### ISSUE TITLE
Cannot install PowerShell 7

### ISSUE THREAD

**Issue by HurricanKai** [microsoft/winget-pkgs#1187]
PowerShell 7 and PowerShell Core have the same ID, not sure how that's even possible, but it's now impossible to install PowerShell via winget.

**Comment by Teraskull** [comment]
```winget install -e Microsoft.PowerShell``` installs PowerShell 7, but I agree, they shouldn't share the same ID.

**Comment by OfficialEsco** [comment]
Since Powershell 7.0.1 is just called Powershell now it becomes a issue, i made a request to change the name to Powershell, or if people want 7.0.0 to be Core the ID should be Microsoft.PowershellCore

#1189

**Comment by denelon** [comment]
@TravisEz13 it looks like there is some discussion here about product naming.

**Comment by TravisEz13** [comment]
I'm confused as to what else would it install?

**Comment by OfficialEsco** [comment]
Right now it says "Multiple apps found matching input criteria. Please refine the input.", i bet the workaround is typing the version number, but thats abit clumsy aint it?

You get this message you try to install Powershell or Microsoft.Powershell

**Comment by TravisEz13** [comment]
I think the initial description is confusing then, the issue is that there are two versions published.  Both, are PowerShell 7, one was mislabeled PowerShell core.

**Comment by TravisEz13** [comment]
I found a workaround for now.

```
winget install --id Microsoft.PowerShell -e
```

I'm putting in a PR to fix the name and ID of the 7.0.0 so there are less variants

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT

**Comment by TravisEz13** [comment]
This is related to https://github.com/microsoft/winget-cli/issues/339

**Comment by Teraskull** [comment]
> I found a workaround for now.
> 
> ```
> winget install --id Microsoft.PowerShell -e
> ```
> 
> I'm putting in a PR to fix the name and ID of the 7.0.0 so there are less variants

I literally gave you the same solution [here](https://github.com/microsoft/winget-pkgs/issues/1187#issuecomment-634250666)

**Comment by TravisEz13** [comment]
The remaining issue is https://github.com/microsoft/winget-cli/issues/282

**Comment by sdaaish** [comment]
> 
> 
> > I found a workaround for now.
> > ```
> > winget install --id Microsoft.PowerShell -e
> > ```
> > 
> > 
> > I'm putting in a PR to fix the name and ID of the 7.0.0 so there are less variants
> 
> I literally gave you the same solution [here](https://github.com/microsoft/winget-pkgs/issues/1187#issuecomment-634250666)

It didn't work for me until I copy/pasted it. Because "-e" is case sensitive. Go figure.
Just for the record, is a separate issue for this, #1039.
