### ISSUE TITLE
[Package Issue]: TheDocumentFoundation.LibreOffice

### ISSUE THREAD

**Issue by hueldoeu** [microsoft/winget-pkgs#118938]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

There is one NASTY problem with winget install TheDocumentFoundation.LibreOffice or winget upgrade TheDocumentFoundation.LibreOffice ...

![image](https://github.com/microsoft/winget-pkgs/assets/11273667/72e54e6d-1fe8-4894-a2a1-dc07ef2a2844)

the templates from the windows explorer context menu (right mouse click) are unuseable. i had a discussion about it here:

https://www.libreoffice-forum.de/viewtopic.php?f=2&t=38690

there is a folder called shellnew made by the libreoffice-installer. i modified the folder a lot but made it just worse.

but maybe it's because of my badly developed laptop. i think on other PCs its working great.

### Steps to reproduce

install libreoffice and create a new file with right mouseclick => context menu => New => open document XXX on the desktop and the new created file is absolute useless. even more than just useless, like an ODP-file or ODS-file is opening in libreoffice writer, because the files are totally emtpy, no structure, no content. ODF-files have a minimum of files in it like zip-files.

### Actual behavior

newly created files on the desktop are absolute useless. even more than just useless, like an ODP-file or ODS-file is opening in libreoffice writer, because the files are totally emtpy, no structure, no content. ODF-files have a minimum of files in it like zip-files.

### Expected behavior

the newly created files are opening correctly and they are ready to be filles with text, images and tables.

### Environment

```raw
Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Nutzer>winget --info
Windows-Paket-Manager v1.5.2201
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.3324
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by Trenly** [comment]
When installing or upgrading, winget simply downloads and runs the installer from the publisher's website. If there is an issue with the behavior of the installed application, it is most likely due to the LibreOffice installer. Based on your description, it seems like this is the case.

**Comment by hueldoeu** [comment]
> When installing or upgrading, winget simply downloads and runs the installer from the publisher's website. If there is an issue with the behavior of the installed application, it is most likely due to the LibreOffice installer. Based on your description, it seems like this is the case.

yes. this is what i also have discussed with several libreoffice users. it must be the libreoffice installer.

maybe it's my faulty windows 10 installation. gotta format it again.

it's just ... i wanted to publish a very nasty problem with winget install libreoffice and i hope, nobody mind, until the problem got solved. a problem i caused on my own and i am sure that winget is not the problem.
