### ISSUE TITLE
[Package Issue]: GoLang.Go

### ISSUE THREAD

**Issue by kobykahane** [microsoft/winget-pkgs#119099]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The 1.21.x versions of the GoLang.Go package are missing the ARM64 installer and only have the x64 installer. This is a regression compared to the 1.20.x versions of the package.

The ARM64 versions are available upstream for 1.21.x, see e.g., https://go.dev/dl/go1.21.1.windows-arm64.msi.

### Steps to reproduce

Install with `winget install GoLang.Go` on a Windows ARM64 device and observe that the x64 version is installed.

### Actual behavior

Only the x64 version appears in the manifest and the x64 version is installed.

### Expected behavior

The ARM64 version should also appear in the manifest and be installed on ARM64 devices.

### Environment

```raw
C:\>winget --info
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
* Related to https://github.com/microsoft/winget-pkgs/issues/92688
