### ISSUE TITLE
[Update Request]: GitHub.GitHubDesktop and GitHub.GitHubDesktop.Beta

### ISSUE THREAD

**Issue by radoslew** [microsoft/winget-pkgs#119131]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GitHub.GitHubDesktop

### Package Version

3.3.1

### Please describe the changes you would like to see

There is a new release of GitHub.GitHubDesktop (3.3.1) and GitHub.GitHubDesktop.Beta (3.3.2-beta1).
https://desktop.github.com/

**Comment by Trenly** [comment]
Looks like the PR was linked above
