### ISSUE TITLE
Can not install ...

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#1191]
# Description of the problem:

Cannot Install `<package>`

Unfortunately, there are a few different reasons a program might not install correctly. 

# Common reasons:

There are several different reasons a package might not install on your system.

Requires elevation (are you running in "admin" mode?)

Requires another program (some IDEs require the language to be installed)

# Reporting:

The issue is likely to be related either to the winget.exe client, or the installer provided. If you would like to submit a bug, please put it in the client repository https://github.com/microsoft/winget-cli/issues

**Comment by thutrang162** [comment]
Unable to install KeePass, error is "incorrect parameters".
![image](https://user-images.githubusercontent.com/37037333/92479968-8a19b700-f1e4-11ea-96cb-b4b8d2454094.png)

**Comment by denelon** [comment]
The User vs System https://github.com/microsoft/winget-cli/issues/149 and Dependencies https://github.com/microsoft/winget-cli/issues/163 features are on the client backlog. This is a duplicate of those issues.
