### ISSUE TITLE
Support the installation of Microsoft office 32-Bit

### ISSUE THREAD

**Issue by 215carlos** [microsoft/winget-pkgs#11918]
# Description of the new feature/enhancement
Support the installations of Microsoft office 32-bit

# Proposed technical implementation details (optional)

**Comment by OfficialEsco** [comment]
Hey! Try now :)

**Comment by 215carlos** [comment]
will it be listed as Microsoft.Office32bit? 
If I do a "winget search Microsoft. " I only see the original microsoft.office package.
I assume that the 32-bit installer will be listed as microsoft.office32bit or something along those lines....

**Comment by OfficialEsco** [comment]
No, WinGet will Install the architecture for your system, when it's x64 you cannot install the package on a x32 system, if it's x86 it will work for both, if it's neutral the installer contains both the x32 and x64 version and will install the suitable architecture for your PC.

**Comment by 215carlos** [comment]
The installer should allow the end-user to specify which version (32 or 64 bit) should be installed. 

Or in this case, Im proposing for there to be a separate 32 bit installer, I do understand the architecture limitations and all, but there are specific scenarios where the 32 bit installer is necessary (mainly compatibility with other programs)

**Comment by OfficialEsco** [comment]
Ok, @denelon i agree with the architecture switch suggestion. 

However in this case we cannot force a installer to install a different architecture if the installer don't have the switches for it. If there was a different installer there would be a x64 and x86 InstallerURL in the manifest.

**Comment by OfficialEsco** [comment]
Denelon already made a Feature Request about this that the search function didn't lead me to.. https://github.com/microsoft/winget-cli/issues/906

**Comment by denelon** [comment]
I've reached out internally to see if there is a plan for a 32-bit installer that would work with the Windows Package Manager. I'm not sure if that's on the roadmap or not. The one currently in the repository is the result of a fix-hack-learn project. Hopefully, there will be more goodness to come :smile:

**Comment by 215carlos** [comment]
Great! Thank you for the info @denelon

**Comment by lychichem** [comment]
So, if I change the `InstallerSwitches` and point the configure file to a custom configure file, I can select the components to install and install Microsoft Office 365 Home using this winget package?

**Comment by OfficialEsco** [comment]
> So, if I change the `InstallerSwitches` and point the configure file to a custom configure file, I can select the components to install and install Microsoft Office 365 Home using this winget package?

You should be able to do `winget intall Microsoft.Office --override "https://LinkToFileSharingDomain.com/officehome.xml"`
After checking out https://config.office.com/deploymentsettings it seems like we should be able to make a x64 and x86 `InstallerSwitch` AND tons of locales, but we would need a official Microsoft website to store all these xml's.

@denelon do you know if there is any more cloudconfigs available?

**Comment by lychichem** [comment]
> > So, if I change the `InstallerSwitches` and point the configure file to a custom configure file, I can select the components to install and install Microsoft Office 365 Home using this winget package?
> 
> You should be able to do `winget intall Microsoft.Office --override "https://LinkToFileSharingDomain.com/officehome.xml"`
> After checking out https://config.office.com/deploymentsettings it seems like we should be able to make a x64 and x86 `InstallerSwitch` AND tons of locales, but we would need a official Microsoft website to store all these xml's.
> 
> @denelon do you know if there is any more cloudconfigs available?

We can just use config.office.com to create those configure files. The problem is we need to find a place to store them.

**Comment by jedieaston** [comment]
Once the spec is out for custom repos, this wouldn't be a hard feature to add as an additional endpoint.

**Comment by denelon** [comment]
> @denelon Demitrius Nelon FTE do you know if there is any more cloudconfigs available?

@OfficialEsco I'll ask about other cloudconfigs.

**Comment by lychichem** [comment]
> Once the spec is out for custom repos, this wouldn't be a hard feature to add as an additional endpoint.
> 
> In the meantime, you could store it as a GitHub Gist if there isn't secrets in your config (like company name or product keys or whatever).

Actually I have generated [one](https://gist.github.com/lychichem/15cff0e449c46262fb74218834324234), because I need to use and only use Word, PowerPoint and Excel from Office 365 home, so I just want to install these three components, however the installer from MS don't let me select.

**Comment by denelon** [comment]
> So, if I change the `InstallerSwitches` and point the configure file to a custom configure file, I can select the components to install and install Microsoft Office 365 Home using this winget package?

It’s possible to build your own cloudconfig. You could then override the switches with `winget install Microsoft.Office --override “/configure <path to your cloudconfig>”`. I haven’t tested this so your mileage may vary.

**Comment by MattBDev** [comment]
It would be even cooler is Office could be deployed using MSIX. Obviously, that's outside of the scope of this issue and the winget team but I only hope that someone will see this and pass the message along.

**Comment by denelon** [comment]
I've shared the feedback and a link to this Issue with them.

**Comment by MatthiasDE** [comment]
Hi there, but the given version is anyhow just for enterprises, isn't it? What is with microsoft single / family?

Search just shows a deployment or enterprise version

`C:\Users\xxxxx>winget search "microsoft.office"`
`Name                              ID                             Version          Quelle`
`Microsoft 365 Apps for enterprise Microsoft.Office               16.0.14527.20276 winget`
`Office Deployment Tool            Microsoft.OfficeDeploymentTool 16.0.14527.20178 winget`

**Comment by lychichem** [comment]
> Hi there, but the given version is anyhow just for enterprises, isn't it? What is with microsoft single / family?
> 
> Search just shows a deployment or enterprise version.
> 
> `C:\Users\xxxxx>winget search "microsoft.office"` `Name ID Version Quelle` `Microsoft 365 Apps for enterprise Microsoft.Office 16.0.14527.20276 winget` `Office Deployment Tool Microsoft.OfficeDeploymentTool 16.0.14527.20178 winget`
> 
> Or is the comment from lychichem with the home-version .xml also valid for this? If so, yes then please also pass over that all versions are included and the enterprise is taken away - that confuses maximum ;)..

Yes, my config file is for Office 365 home 64-bit zh-CN version. Feel free to use it. The key is you need to set `Product ID="O365HomePremRetail"`. You can change `Language ID` to other value to install office in other languages.

**Comment by jedieaston** [comment]
You *should* be able to sign in to that version of Office anyway and it'll adjust your license. You'll have apps you can't use maybe (Publisher/Access) but it'll work I think.

**Comment by denelon** [comment]
Both architectures are present in the manifest.

You can use the "--architecture" argument to specify x86 or x64
