### ISSUE TITLE
[Package Issue]: HiBitSoftware.HiBitUninstaller

### ISSUE THREAD

**Issue by ViperCanel** [microsoft/winget-pkgs#119244]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

While trying to install I get hash mismatch problem. Also the listed version is very old at 3.1.25, while the newest is 3.1.50.

### Steps to reproduce

Run command: winget install HiBitSoftware.HiBitUninstaller

### Actual behavior

Command returns: Installer hash does not match.

### Expected behavior

Winget should install HiBitSoftware.HiBitUninstaller version 3.1.50.

### Environment

```raw
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by ViperCanel** [comment]
Correction: I misread the automatic package deletion. It seems to be for 3.1.20; an even older version. 3.1.25 package is still present in manifests.

**Comment by TaliaFlor** [comment]
The same thing is happening when I try to install Geek Uninstaller, but the version is correct in my case.

![image](https://github.com/microsoft/winget-pkgs/assets/47438099/c47103a0-ad39-4001-a60f-0b8a8e83ba2d)

**Comment by TaliaFlor** [comment]
Also, I had to specify the source even though I was using the ID and winget was the only source. This has never happened before.

**Comment by ViperCanel** [comment]
The software manifest has been updated. The issue has been fixed.
