### ISSUE TITLE
[Package Update Request]: Rename `FreedomScientific.JawsForWindows`

### ISSUE THREAD

**Issue by gradyat** [microsoft/winget-pkgs#119235]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

FreedomScientific.JawsForWindows

### Package Version

2023.2307.37.400

### Please describe the changes you would like to see

I’m interested in adding the latest version of JAWS 2023 (2023.2307.37.400). However when looking at doing that, I noticed JAWS in this repo already has a package identifier of `FreedomScientific.JawsForWindows`. JAWS releases a new version every year, and multiple versions can be installed at a time (it is not simply an update). In addition, the application does not have “for Windows” in its name. Thus I think the package identifier would be better as `FreedomScientific.JAWS.2023` or `FreedomScientific.JAWS2023`. This way when JAWS 2024 is released, it can be added and named accordingly.

**Comment by gradyat** [comment]
I’m interested in submitting a PR for this, but first I would appreciate some guidance on if and how this is possible. Thanks.

**Comment by vedantmgoyal2009** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/FreedomScientific/JawsForWindows/2023.2212.23.400

You will have to the 3 files (manifests) from path `manifests/f/FreedomScientific/JawsForWindows/2023.2212.23.400` to `manifests/f/FreedomScientific/JAWS/2023/2023.2212.23.400`.

Additionally, you will have to update `PackageIdentifier` to `FreedomScientific.JAWS.2023` in each manifest, and also rename the files accordingly:
- `FreedomScientific.JawsForWindows.installer.yaml` -> `FreedomScientific.JAWS.2023.installer.yaml`
- `FreedomScientific.JawsForWindows.locale.en-US.yaml` -> `FreedomScientific.JAWS.2023.locale.en-US.yaml`
- `FreedomScientific.JawsForWindows.yaml` -> `FreedomScientific.JAWS.2023.yaml`

Please delete and add files in separate PRs. If you move, and update things in a single PR, the automated pipelines will fail. They are designed to process only one change per PR.

**Comment by vedantmgoyal2009** [comment]
* https://github.com/microsoft/winget-pkgs/pull/119284
* https://github.com/microsoft/winget-pkgs/pull/119285

**Comment by vedantmgoyal2009** [comment]
This can be closed now.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #119284 and #119285;
