### ISSUE TITLE
[Update Request]: 

### ISSUE THREAD

**Issue by divieira** [microsoft/winget-pkgs#119369]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Docker.DockerDesktop

### Package Version

4.23.0

### Please describe the changes you would like to see

Currently running `winget install docker.dockerdesktop` fails with:

`Found Docker Desktop [Docker.DockerDesktop] Version 4.22.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe
  ██████████████████████████████   572 MB /  572 MB
Installer hash does not match.`

**Comment by rodrigoborgesdeoliveira** [comment]
Fixed by
- #119337

**Comment by mdanish-kh** [comment]
Close with reason: See above;
