### ISSUE TITLE
[Update Request]: XnSoft.XnViewMP

### ISSUE THREAD

**Issue by horganPPL** [microsoft/winget-pkgs#119563]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

XnSoft.XnViewMP

### Package Version

1.5.5

### Please describe the changes you would like to see

XnViewMP 1.5.5 is now available.

Download link: https://download.xnview.com/XnViewMP-win-x64.exe

**Comment by Trenly** [comment]
* Resolved by #119562
