### ISSUE TITLE
[Package Request]: Ipe extensible drawing editor

### ISSUE THREAD

**Issue by r0uv3n** [microsoft/winget-pkgs#119554]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://ipe.otfried.org/ (alternatively: https://github.com/otfried/ipe/releases)
Publisher: Otfried Cheong
Package Name :IPE extensible drawing editor
Description: A drawing editor for creating figures in PDF format.
Package Version: v7.2.28
Installer URL: https://github.com/otfried/ipe/releases/download/v7.2.28/ipe-7.2.28-win64.zip

**Comment by r0uv3n** [comment]
I vaguely remember seeing that Winget supports installing portable applications like this (though I might have misremembered), but when I tried to create a manifest for Ipe using WingetCreate, I could not find a way to avoid having to select an installer.

**Comment by stephengillie** [comment]
Please use `InstallerType: portable` for portable packages.
