### ISSUE TITLE
[Package Request]: Intel® Arc™ & Iris® Xe Graphics Drivers

### ISSUE THREAD

**Issue by jinyuzu99** [microsoft/winget-pkgs#119812]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
Publisher: Intel
Package Name: Intel® Arc™ & Iris® Xe Graphics Drivers
Description: This download installs Intel® Graphics Driver 31.0.101.4824 (WHQL Certified) for Intel® Arc™ A-Series Graphics and Intel® Iris® Xe Graphics.
Package Version: 31.0.101.4824
Installer URL: https://downloadmirror.intel.com/788440/gfx_win_101.4824.exe

**Comment by drshtmstry** [comment]
https://github.com/microsoft/winget-pkgs/pull/123322
Already created PR but installer doesn't support silent mode. or maybe I don't have enough knowledge.
