### ISSUE TITLE
[Package Issue]: TeraTermProject.teraterm

### ISSUE THREAD

**Issue by gjabouley-invn** [microsoft/winget-pkgs#120092]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Download from OSDN is either super slow or not working, using url  https://osdn.net/frs/redir.php?m=auto&f=ttssh2%2F74780%2Fteraterm-4.106.exe

Team already put new releases in GitHub: https://github.com/TeraTermProject/osdn-download/releases/tag/teraterm-4_106

Maybe package could be update to use GitHub url instead of OSDN

### Steps to reproduce

winget install --id TeraTermProject.teraterm

### Actual behavior

Slow, and regurlarly fails / timeouts

### Expected behavior

Download success

### Environment

```raw
Windows Package Manager v1.5.2201
Windows: Windows.Desktop v10.0.19043.2364
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by ItzLevvie** [comment]
Close with reason: A newer version exists in the repository which uses GitHub URLs;
