### ISSUE TITLE
[Package Issue]: Google.Chrome, cannot install the latest 117.0.5938.63 version

### ISSUE THREAD

**Issue by ali50m** [microsoft/winget-pkgs#120072]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

I cannot install the latest Google.Chrome(117.0.5938.63) through winget, it always report "安装程序哈希不匹配" or something like "Installer hash mismatch".

![image](https://github.com/microsoft/winget-pkgs/assets/9393831/fa77b0b2-92b4-497d-97f0-63fcdf2007a6)

### Steps to reproduce

```pwsh
winget install Google.Chrome
```

### Actual behavior

after downloading the installer, it reported "安装程序哈希不匹配。"

### Expected behavior

can install the Chrome  successfully.

### Environment

```raw
winget v1.5.2201
Windows 10 22H2 19045.3448
```

**Comment by ImJoakim** [comment]
Close with reason: Resolved by #119978;
