### ISSUE TITLE
Add Squirrel installertype

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#1201]
# Description of the new feature/enhancement

This installertype is popular with many electron apps, including discord and authy.

# Proposed technical implementation details (optional)

**Comment by SoftCreatR** [comment]
Doesn't this belong to [winget-cli](https://github.com/microsoft/winget-cli)?

**Comment by superusercode** [comment]
https://github.com/microsoft/winget-cli/issues/372
