### ISSUE TITLE
[Package Request]: bandwhich

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#120225]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/imsnif/bandwhich/releases/tag/v0.21.0
Publisher: imsnif
Package Name: bandwhich
Description: This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
Package Version: 0.21.0
Installer URL: https://github.com/imsnif/bandwhich/releases/download/v0.21.0/bandwhich-v0.21.0-x86_64-pc-windows-msvc.zip

**Comment by Dragon1573** [comment]
@stephengillie - Could you please help close this issue as "Not planned"? Thank you ❤️

- Related https://github.com/imsnif/bandwhich/issues/287#issuecomment-1886745239
- Related https://github.com/imsnif/bandwhich/issues/287#issuecomment-1889831852

**Comment by stephengillie** [comment]
> @stephengillie - Could you please help close this issue as "Not planned"? Thank you ❤️
