### ISSUE TITLE
[Package Removed]: Postman.Postman version 10.18.2 is 404

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#120398]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The `10.18.2` version of `Postman.Postman` appears to have been removed by the ISV, and its manifest should be removed from WinGet's public manifests. 

### Steps to reproduce

winget install Postman.Postman --version 10.18.2

### Actual behavior

PS C:\Users\User\Desktop> winget install Postman.Postman --version 10.18.2
Found Postman [Postman.Postman] Version 10.18.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.pstmn.io/download/version/10.18.2/win64
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Expected behavior

PS C:\Users\User\Desktop> winget install Postman.Postman --version 10.18.2
(Package not found)

### Environment

```raw
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag╬ô├ç┬¬
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett╬ô├ç┬¬
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

Included as Actual Behavior above.

**Comment by BrandonWanHuanSheng** [comment]
It was invalid direct link.

**Comment by BrandonWanHuanSheng** [comment]
Pipelines is applying on the background.

**Comment by BrandonWanHuanSheng** [comment]
Pipelines applied succeed.

**Comment by BrandonWanHuanSheng** [comment]
The file was not existed on that URL.
![Screenshot_2023-10-24-16-52-04-864_com.microsoft.emmx.jpg](https://github.com/microsoft/winget-pkgs/assets/118059864/6403926f-0e3a-4e26-a81d-d11141a2dfd0)
Also, the manifest file in winget-pkgs 10.18.2 was removed.

**Comment by BrandonWanHuanSheng** [comment]
It looks like 10.18.4 was removed by ISV.
Most of this file was removed.

**Comment by mdanish-kh** [comment]
Close with reason: 10.18.2 version is no longer available in the repo;
