### ISSUE TITLE
[Package Request]: Rem0o/FanControl

### ISSUE THREAD

**Issue by cbr-github** [microsoft/winget-pkgs#120619]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Rem0o/FanControl.Releases/releases
Publisher: https://github.com/Rem0o
Package Name: FanControl
Description: Fan Control, a highly customizable fan controlling software for Windows.
Package Version: V170
Installer URL: https://github.com/Rem0o/FanControl.Releases/releases/download/V170/FanControl_net_7_0.zip

**Comment by Trenly** [comment]
Duplicate of #97145
