### ISSUE TITLE
[Package Request]: GitQL

### ISSUE THREAD

**Issue by AmrDeveloper** [microsoft/winget-pkgs#120711]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/AmrDeveloper/GQL/releases
Publisher: https://github.com/AmrDeveloper
Package Name: gitql
Description: A SQL like language to perform queries on .git files
Package Version: 0.7.0
Installer URL: https://github.com/AmrDeveloper/GQL/releases/download/0.7.0/gql-x86-windows.exe

**Comment by Dragon1573** [comment]
@stephengillie Could this issue close as "Completed"?

**Comment by mdanish-kh** [comment]
Close with reason: PR merged in #121198;
