### ISSUE TITLE
[Update Request]: RealVNC.VNCViewer 7.6.1  (also "current" version 7.6.0 from winget fails to install)

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#120739]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

RealVNC.VNCViewer

### Package Version

7.6.1

### Please describe the changes you would like to see

MSI Installers:  https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.6.1-Windows-msi.zip

EXE installer: https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.6.1-Windows.exe

the "current" version known by winget, 7.6.0, is failing to install, but manually downloading the 7.6.1 zip, extracting it and then installing the x64 msi works ok for me.

```
PS C:\WINDOWS\system32> winget upgrade RealVNC.VNCViewer
Found VNC Viewer [RealVNC.VNCViewer] Version 7.6.0.50657
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.6.0-Windows-msi.zip
  ██████████████████████████████  7.37 MB / 7.37 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Installer failed with exit code: 1603
```

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/0f9ab8fe-e526-480d-99db-852c6de50301)

**Comment by R-Adrian** [comment]
note: i opened that log file... the error is because winget is trying to install a 32-bit MSI on a system where the previous installed version is 64-bit... and it tries to upgrade a 64-bit program to a 32-bit one

```
=== Logging started: 25.09.2023  09:14:54 ===
Action start 09:14:54: INSTALL.
Action start 09:14:54: FindRelatedProducts.
Action ended 09:14:54: FindRelatedProducts. Return value 1.
Action start 09:14:54: SaveInstallDirCmdLineValue.
Action ended 09:14:54: SaveInstallDirCmdLineValue. Return value 1.
Action start 09:14:54: AppSearch.
Action ended 09:14:55: AppSearch. Return value 1.
Action start 09:14:55: LaunchConditions.
MSI (s) (94:D8) [09:14:55:001]: Product: RealVNC Viewer 7.6.0 -- Setup has detected that you are running a 64-bit version of Windows. Please download and install a 64-bit version of the software.

Setup has detected that you are running a 64-bit version of Windows. Please download and install a 64-bit version of the software.
Action ended 09:14:55: LaunchConditions. Return value 3.
Action ended 09:14:55: INSTALL. Return value 3.
```

**Comment by Trenly** [comment]
* Related to https://github.com/microsoft/winget-cli/issues/3653
