### ISSUE TITLE
[Package Issue]: WHONET.WHONET.2023 installer hash problem

### ISSUE THREAD

**Issue by drshtmstry** [microsoft/winget-pkgs#120783]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

I have submitted a package but the problem is that the url of installer is constant and it always points to latest release available.
Version numbered installer links are not available.
How do I change my installer yaml file so that the sha256 hash automatically update to latest release.
Without update to hash, it leads to installer hash mismatch, because it downloads new installer from link, but uses old hash from installer yaml file.

Download links:
1) https://whonet.org/WHONET2023-Setup-x64.exe
2) https://whonet.org/WHONET2023-Setup-x86.exe

![Web capture_25-9-2023_203815_whonet org](https://github.com/microsoft/winget-pkgs/assets/145197941/575ba006-a661-421a-b615-8de837e22c52)
![Web capture_25-9-2023_203854_whonet org](https://github.com/microsoft/winget-pkgs/assets/145197941/22fe8240-9bca-4432-b531-f2830dd8ab32)

### Steps to reproduce

When `winget install WHONET.WHONET.2023` or `winget upgrade WHONET.WHONET.2023` is used, it downloads installer from link which always provides latest installer, but the hash is used from yaml which takes a few days to update after package upgrade is submitted.

### Actual behavior

It leads to installer hash mismatch.

### Expected behavior

It should user signature or update hash in yaml if download link is same for each version.

### Environment

```raw
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![Web capture_25-9-2023_203815_whonet org](https://github.com/microsoft/winget-pkgs/assets/145197941/daab70aa-6c74-40f8-8c7c-7834721ffe9d)
![Web capture_25-9-2023_203854_whonet org](https://github.com/microsoft/winget-pkgs/assets/145197941/30b02292-269b-4a87-bff7-5225256d1cb0)

**Comment by Trenly** [comment]
> How do I change my installer yaml file so that the sha256 hash automatically update to latest release.

This isn't possible. The SHA256 is a security measure that ensures the file content itself hasn't changed. We've seen cases where the signing certificates have fallen into the wrong hands or where bad actors at the company have intentionally pushed malware as patch updates to existing versions. Validating the actual content of the file with the SHA256 hash is a security measure.

In order for there to be any form of automatic update, the publisher would need to add a step to their release process to automatically submit a pull request that updates the hash. There is a bot that would go through and perform automatic updates, but it is currently down for maintenance - even so, it would still take a little while for the hash to be updated. The best way is to use a versioned URL instead of a vanity URL - that way the link always points to the same file.

**Comment by drshtmstry** [comment]
> > How do I change my installer yaml file so that the sha256 hash automatically update to latest release.
> 
> This isn't possible. The SHA256 is a security measure that ensures the file content itself hasn't changed. We've seen cases where the signing certificates have fallen into the wrong hands or where bad actors at the company have intentionally pushed malware as patch updates to existing versions. Validating the actual content of the file with the SHA256 hash is a security measure.
> 
> In order for there to be any form of automatic update, the publisher would need to add a step to their release process to automatically submit a pull request that updates the hash. There is a bot that would go through and perform automatic updates, but it is currently down for maintenance - even so, it would still take a little while for the hash to be updated. The best way is to use a versioned URL instead of a vanity URL - that way the link always points to the same file.

The publisher (whonet.org) only provides vanity url.
