### ISSUE TITLE
Build Pipeline broken

### ISSUE THREAD

**Issue by SoftCreatR** [microsoft/winget-pkgs#1209]
It seems, that the build pipeline is somewhat broken. On my latest PR, it says:

> Comment was made before the most recent commit for PR 1208 in repo microsoft/winget-pkgs

and that's it.

However, according to [https://github.com/microsoft/winget-pkgs/pulls?q=is%3Aopen+is%3Apr+no%3Alabel](this) list, checks are sometimes not triggered at all. This leads to some dead PRs, because they won't be assigned for review or anything.

**Comment by SoftCreatR** [comment]
I was able to trigger the build process by doing a force push without changes.

**Comment by denelon** [comment]
This is resolved.
