### ISSUE TITLE
UPDATE FAILED for Zoom.Rooms 5.15.7

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#120972]
I also can't find the switch command. Dont know where the Zoom Room installer switch get it from?
It look like the interface was changed and don't know the slient switches. 

_Originally posted by @BrandonWanHuanSheng in https://github.com/microsoft/winget-pkgs/pull/116892#issuecomment-1680238227_

**Comment by stephengillie** [comment]
Hi @BrandonWanHuanSheng,

This isn't a good location to look for a package's install switches.

**Comment by BrandonWanHuanSheng** [comment]
Ok
