### ISSUE TITLE
[Package Issue]: Cryptomator.Cryptomator

### ISSUE THREAD

**Issue by JaniruTEC** [microsoft/winget-pkgs#121241]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

winget keeps showing version `1.10.1.4844` of the package `Cryptomator.Cryptomator` as available; updating doesn't change this.

---

Currently there are two conflicting manifests for the same version of the package in the repository.
This was caused by two PRs for this version being accepted in close succession, namely #120260 by @infeo (from the Cryptomator Dev Team) and #120273 by @vedantmgoyal2009.
Both were approved by @stephengillie, so I would be particularly thankful for their help.

As I am not familiar with the inner workings of winget, I assume this is what causes users to repeatedly encounter the package when running `winget upgrade`. Upgrading the package doesn't resolve this issue; it is shown again on the next invocation.

The `System Settings > Apps & features` UI reports the installed version as `1.10.1.4844`

If possible, please:
(1) confirm whether this is caused by the duplicate manifests
(2) and if so, please either delete one of them OR provide me with information on how to request deletion.

With kind regards,
JanriuTEC // Cryptomator Dev Team

### Steps to reproduce

1. If not already installed: Install `Cryptomator.Cryptomator`
2. Run `winget upgrade` or `winget upgrade --all` or `winget upgrade Cryptomator`

### Actual behavior

(1) winget reports the version as `1.10.1` and (2) the package keeps appearing in the list of upgradeable packages. Upgrading doesn't change this any of this.

### Expected behavior

winget reports the correct version and doesn't keep asking for updates.

### Environment

```raw
PS C:\Users\Tea> winget --info
Windows Package Manager v1.6.2701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3448
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2701.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

```
$ winget upgrade
Name                                                               Id                             Version       Available     Source
------------------------------------------------------------------------------------------------------------------------------------
[...]
Cryptomator                                                        Cryptomator.Cryptomator        1.10.1        1.10.1.4844   winget
10 upgrades available.
```

```
$ winget upgrade Cryptomator
Found Cryptomator [Cryptomator.Cryptomator] Version 1.10.1.4844
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/cryptomator/cryptomator/releases/download/1.10.1/Cryptomator-1.10.1-x64.msi
  ██████████████████████████████  48.4 MB / 48.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Notes: On Windows, Cryptomator works best with WinFsp. For installation and setup, see https://docs.cryptomator.org/en/1.7/desktop/volume-type/#winfsp-winfsp-local-drive
```

Related bug report on the forum: [Link](https://community.cryptomator.org/t/windows-winget-incorrectly-reports-upgrade-available/12941)
Related issue on the Cryptomator issue tracker: cryptomator/cryptomator#3132
Possivly related issue: microsoft/winget-cli/issues/2313

**Comment by Trenly** [comment]
I'm guessing this is because the Winget manifest contains the patch version and the data Cryptomator writes to the registry does not.

Can you share the output of `winget list cryptomator`

**Comment by JaniruTEC** [comment]
I also had that idea, but wouldn't that cause `Apps & features` to display the version without patch as well?
We only recently switched to including the patch in the manifest, but for `1.10.0` it didn't give us any problems as far as I know.

```
$ winget list cryptomator
Name        Id                      Version Available   Source
--------------------------------------------------------------
Cryptomator Cryptomator.Cryptomator 1.10.1  1.10.1.4844 winget
```

**Comment by Trenly** [comment]
> I also had that idea, but wouldn't that cause `Apps & features` to display the version without patch as well? We only recently switched to including the patch in the manifest, but for `1.10.0` it didn't give us any problems as far as I know.
> 
> ```
> $ winget list cryptomator
> Name        Id                      Version Available   Source
> --------------------------------------------------------------
> Cryptomator Cryptomator.Cryptomator 1.10.1  1.10.1.4844 winget
> ```



> I also had that idea, but wouldn't that cause `Apps & features` to display the version without patch as well?

No, it wouldn’t. Because Crypromator is an msi installer Winget has no control over what is written to Apps & Features. Based on the output of `winget list` that you shared, it confirms that Cryptomator doesn’t write the patch version to registry (and what is written to the registry is also what shows in Apps & Features).

The temporary fix is to nove the manifest for 1.10.1.4844 to be manifest version 1.10.1 instead, removing the older manifests. This is the only way winget will be able to know not to perform an upgrade.

The permanent fix is for Cryptomator to write the patch version as part of their install

**Comment by JaniruTEC** [comment]
> Based on the output of winget list that you shared, it confirms that Cryptomator doesn’t write the patch version to registry (and what is written to the registry is also what shows in Apps & Features).

I apologize, but I fear I don't fully understand. If I get you correctly, you say that Cryptomator doesn't write the patch version to the registry because:
(1) `winget list` reads from the registry
(2) A&F reads from the registry

But `winget list` reports `1.10.1` and A&F reports `1.10.1.4844` - isn't that a contradiction?

**Comment by Trenly** [comment]
> I apologize, but I fear I don't fully understand. If I get you correctly, you say that Cryptomator doesn't write the patch version to the registry because: (1) `winget list` reads from the registry (2) A&F reads from the registry
> 
> But `winget list` reports `1.10.1` and A&F reports `1.10.1.4844` - isn't that a contradiction?
> 

I'll have to look and see. I haven’t had a chance to actually install using the manifest

**Comment by Trenly** [comment]
Ah, I see the issue now. You are right, Cryptomator does write the patch version to the registry, I was incorrect.

When @vedantmgoyal2009 added version 1.10.1 they used the `AppsAndFeaturesEntries` to specify the version to match since the GitHub tag is 1.10.1, and the pipelines didn't catch it as a duplicate because the PR for 1.10.1.4844 hadn't been merged yet.

**Comment by JaniruTEC** [comment]
Thank you very much the quick resolution!

**Comment by eldair** [comment]
Hello, same thing is happening again with 1.11.1 version :/
