### ISSUE TITLE
[Package Issue]: task.task new version not found by winget

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#121205]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

`winget` doesn't find updates to task.task beyond version 3.28 even though newer manifests are available, see https://github.com/go-task/task/issues/1355

I suspect that this is because the newer manifests have `PackageVersion: v3.xx.x` instead of e.g. `3.28.0`, i.e. that this is a manifest error. I just want to double check with someone from the winget team. Should this have been caught during manifest validation?

https://github.com/microsoft/winget-pkgs/blob/ca73312d2792cd7f93e738915bd509c4518602b3/manifests/t/Task/Task/v3.30.1/Task.Task.installer.yaml#L4

NB task has a `NestedInstallerType: portable`.

### Steps to reproduce

After installing task 3.28.0 to the Sandbox:
```
--> Comparing ARP Entries

DisplayName DisplayVersion Publisher ProductCode              Scope
----------- -------------- --------- -----------              -----
Task        3.28.0         Task      Task.Task__DefaultSource User

PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade task.task
No available upgrade found.
No newer package versions are available from the configured sources.
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget show task.task
Found Task [Task.Task]
Version: 3.28.0
Publisher: Task
[...]
```

### Actual behavior

If I install one of the newer versions in the Sandbox, and run `winget upgrade` afterwards, winget offers `3.28.0` as an update for `v3.30.0`, which is obviously not correct.

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade

Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 100.0.1185.36 117.0.2045.43 winget
Task           Task.Task      v3.30.0       3.28.0        winget
```

### Expected behavior

winget ought to find versions >3.28.0

### Environment

```raw
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager v1.6.2701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2701.0
```
```


### Screenshots and Logs

_No response_

**Comment by Trenly** [comment]
This does seem like an error with the manifests, although it is also related to 
* https://github.com/microsoft/winget-cli/issues/2394

**Comment by dpprdan** [comment]
Now that #121213 has been merged I see

```
PS C:\> winget search task.task
Name Id        Version Source
------------------------------
Task Task.Task 3.30.1  winget
```

So this can be closed AFAICT
