### ISSUE TITLE
[Package Issue]: The defaultLocale of Microsoft.PCManager.CN should be zh-CN

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#121601]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The `Microsoft.PCManager.CN` is provided for users in China mainland by Microsoft(China). Because its main area is China mainland, the value of `defaultLocale` should be `zh-CN` instead of `en-US`

CC @denelon @stephengillie @Trenly

**Comment by SpecterShell** [comment]
I set the `defaultlocale` to `en-US` so that users speaking languages other than Chinese and English (e.g. Spanish) will finally see the package information in English, regardless of the actual operating region of the package.
