### ISSUE TITLE
[Update Request]: Devolutions.RemoteDesktopManagerFree

### ISSUE THREAD

**Issue by ThinkPadNL** [microsoft/winget-pkgs#121676]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Devolutions.RemoteDesktopManagerFree

### Package Version

2023.2.32.0

### Please describe the changes you would like to see

Version in winget is quite old (2022.2.20.0), a new version is available (2023.2.32.0)
https://devolutions.net/remote-desktop-manager/home/downloadfree/

Please update :)

**Comment by krystofkrticka** [comment]
No need to update this package, I'm also thinking about submitting PR for it's removal because both RDM Free and RDM Enterprise know come in same installer which is `Devolutions.RemoteDesktopManager`.

**Comment by ThinkPadNL** [comment]
Sounds good to me, to combine them!
