### ISSUE TITLE
The bot doesn't know that ProductCode changes in a new MSI.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#12167]
It appears that the bot doesn't change the ProductCode when it automatically updates a MSI manifest. I've fixed two of these (#12159, #12164), but it'd be a real pain to do for every single one. Is there any way the bot can start to do it itself? The product code is available in the MSI's database (which I assume is where it grabs the new version number anyway).

**Comment by denelon** [comment]
This has been resolved.
