### ISSUE TITLE
[Package Issue]: upgrade dotPDNLLC.paintdotnet -v 5.0.10

### ISSUE THREAD

**Issue by cbr-github** [microsoft/winget-pkgs#121705]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Paintdotnet updgrade to 5.0.10 does not work.
Probably related to commit: https://github.com/microsoft/winget-pkgs/commit/85edaea76aef0982ee80c1d18fe8bffe99c309af.
@vedantmgoyal2009 Can you help?

### Steps to reproduce

Ensure paint.net 5.0.9 is installed.
I was only able to reproduce this in Windows Sandbox by downloading it here: https://www.softportal.com/en/paint-net/windows/download . In the github repo v5.0.9 is not available anymore (which also results in `winget install dotPDNLLC.paintdotnet-v 5.0.9` not being able to install it...).

Then:
`winget upgrade dotPDNLLC.paintdotnet`

### Actual behavior

Nested installer file does not exist. Ensure the specified relative path of the nested installer matches:
C:\Users\<user>\AppData\Local\Temp\WinGet\dotPDNLLC.paintdotnet.5.0.10\extracted\paint.net.5.0.10.winmsi.x64.**msi**

### Expected behavior

Should probably be
C:\Users\<user>\AppData\Local\Temp\WinGet\dotPDNLLC.paintdotnet.5.0.10\extracted\paint.net.5.0.10.winmsi.x64.**exe**

### Environment

```raw
Windows-Paket-Manager v1.6.2721
Windows: Windows.Desktop v10.0.22621.2361
Paket: Microsoft.DesktopAppInstaller v1.21.2721.0
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/66955841/a78f3af2-cafb-4911-a664-59d7ae00fd04)

**Comment by cbr-github** [comment]
Probably the issue is that the wrong URL is used for `InstallerUrl: ` for arm64 and x64.
I commented on the commit: https://github.com/microsoft/winget-pkgs/commit/85edaea76aef0982ee80c1d18fe8bffe99c309af

fyi: @vedantmgoyal2009

**Comment by cbr-github** [comment]
opened a PR https://github.com/microsoft/winget-pkgs/pull/121707

**Comment by Trenly** [comment]
Above PR has been merged

**Comment by Romanitho** [comment]
same here:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/d/dotPDNLLC/paintdotnet/5.0.11/dotPDNLLC.paintdotnet.installer.yaml
still broken with latest.
