### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2019.arm64

### ISSUE THREAD

**Issue by numerunix** [microsoft/winget-pkgs#122148]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Hello, i've downloaded the latest vc++ runtime for arm64 from visual studio site, and i installed it in safe mode.
When i try to to make update with winget on my pro x (arm64) computer, i obtain that there is a newer package, but if i try to install it, it does not install giving me the error that an updated package is already installed.

Please investigate, thanks.

### Steps to reproduce

Search the latest vc++ runtime for arm64 online (https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md) download ad install it in safe mode, and then trying to do winget upgrade.

### Actual behavior

It gives the error that a newer package is already installed

### Expected behavior

The package should be upgraded

### Environment

```raw
Gestione pacchetti Windows v1.6.2771
Copyright (c) Microsoft Corporation. Tutti i diritti sono riservati.

Windows: Windows.Desktop v10.0.22621.2361
Architettura di sistema: Arm64
Pacchetto: Microsoft.DesktopAppInstaller v1.21.2771.0
```

### Screenshots and Logs

![Screenshot 2023-10-08 090550](https://github.com/microsoft/winget-pkgs/assets/49764967/42a0ae91-a81a-4d1e-9e0e-a412ccdc4bd7)

**Comment by Trenly** [comment]
Several other issues are tracking issues related to VC Runtimes and side-by-side. I'm closing this issue in favor of the work over at the CLI.

###### Close with reason: Tracked at CLI;
