### ISSUE TITLE
[Package Request]: Detect it easy

### ISSUE THREAD

**Issue by HeavySnowJakarta** [microsoft/winget-pkgs#122464]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/horsicq/Detect-It-Easy
Publisher: horsicq
Package Name: Detect It Easy
Description: Program for determining types of files for Windows, Linux and MacOS.
Package Version: 3.08
Installer URL: ~~https://github.com/horsicq/Detect-It-Easy/releases~~  ~~I am not sure~~ https://github.com/horsicq/DIE-engine/releases

**Comment by stephengillie** [comment]
Portable packages are accepted, usually with the `portable` installer type. WinGet will place the package under AppData and create a symlink.
