### ISSUE TITLE
[Package Request]: 腾讯桌面整理

### ISSUE THREAD

**Issue by HeavySnowJakarta** [microsoft/winget-pkgs#122465]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://guanjia.qq.com/product/zmzl/
Publisher: Tencent
Package Name: 腾讯桌面整理
Description: 桌面文件分类整理，从此告别凌乱桌面
Package Version: 3.3.1485.127
Installer URL: ~~https://dlied6.qq.com/invc/xfspeed/qqpcmgr/download/QQPCDownload1601.exe~~ https://webcdn.m.qq.com/spcmgr/download/DeskGo_3_3_1485_127_full.exe

Description in English: An app like Fences to organize user's desktop

**Comment by Dragon1573** [comment]
@HeavySnowJakarta 

1. The provided `InstallerUrl` property is a full version of **腾讯电脑管家** . According to the title of this issue, we are asking for a [standalone version](https://webcdn.m.qq.com/spcmgr/download/DeskGo_3_3_1485_127_full.exe).
2. `wingetcreate.exe` cannot inspect the standalone package. Only UAC dialog is poped up during manual installation, something wierd of this performance.
   ```text
   正在下载和分析: https://webcdn.m.qq.com/spcmgr/download/DeskGo_3_3_1485_127_full.exe...
   无法从 [https://webcdn.m.qq.com/spcmgr/download/DeskGo_3_3_1485_127_full.exe] 中分析数据包
   ```

**Comment by Dragon1573** [comment]
Asked official team in [the Support System](https://support.qq.com/products/415334/post/169829825297364167). Waiting for response ...
