### ISSUE TITLE
[Update Request]: Microsoft PowerBI Desktop

### ISSUE THREAD

**Issue by GypsIT** [microsoft/winget-pkgs#122657]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PowerBI

### Package Version

2.122.746.0

### Please describe the changes you would like to see

There is a new release available with version: 2.122.746.0
Download Link: https://www.microsoft.com/en-us/download/details.aspx?id=58494

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #122598;
