### ISSUE TITLE
[Package Issue]: Google.Chrome.Beta 120.0.6099.5 identified as >118...

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#122774]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

my currently installed Google.Chrome.Beta is 119.0.6045.21 (Official Build) beta (64-bit)
but Winget identifies it as > 118.0.5993.18

```
> winget upgrade
Name               Id                 Version         Available    Source
-------------------------------------------------------------------------
Google Chrome Beta Google.Chrome.Beta > 118.0.5993.18 119.0.6045.9 winget
1 upgrades available.
```

### Steps to reproduce

- install Google.Chrome.Beta
- open the program, navigate to Help -> About  ( chrome://settings/help )
- restart browser if it just did a self-update
- check Help -> About again
- check the output of `winget upgrade`

### Actual behavior

Winget tries to downgrade Google.Chrome.Beta from v119.0.6045.21 to  v119.0.6045.9

edit: but when actually trying to install, it fails because of installer hash not matching.

```
PS C:\WINDOWS\system32> winget upgrade Google.Chrome.Beta
Found Google Chrome Beta [Google.Chrome.Beta] Version 119.0.6045.9
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  ██████████████████████████████   110 MB /  110 MB
Installer hash does not match; this cannot be overridden when running as admin
PS C:\WINDOWS\system32>
```
/edit

### Expected behavior

do not nuke newer versions

### Environment

```raw
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3570
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/d5fafbbe-c47d-492c-9f0b-99a8ed52ec0c)

**Comment by R-Adrian** [comment]
side note: Google.Chrome.Beta might be another package that could use the `UpgradeBehavior: deny`  mechanism introduced with the new version 1.6.0 client, but for which we don't have a schema manifest yet  https://github.com/microsoft/winget-pkgs/issues/121127

this is because Beta upgrades for Chrome have a way faster release cadence than winget can keep up with...

**Comment by R-Adrian** [comment]
in PR https://github.com/microsoft/winget-pkgs/pull/122849 the manifest for Chrome Beta was changed to 119.0.6045.21

but... the existing Chrome Beta version is still mis-identified as 118-something and when trying to apply the update shows
`A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.`

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/564a5492-465d-404f-adfd-10ef3aeeb7b6)

**Comment by R-Adrian** [comment]
another note:
my Chrome Beta was originally installed with the EXE installer from https://www.google.com/chrome/beta/
but winget is trying to upgrade it using the MSI for Enterprise installer....  so i uninstalled that one and re-installed the MSI one from winget ...

... and the problem still remains, Chrome Beta 119.0.6045.21 that was just installed moments ago... is detected as being 118-something... and winget wants to upgrade it again, using the same MSI installer:

(btw, the package that cannot be determined below is an older version of Mikrotik.TheDude)

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/97ccdd5e-5db9-4ac5-838d-056b404de7c4)

**Comment by R-Adrian** [comment]
side note: Google.Chrome.Beta updated itself to version 119.0.6045.33.. and the 118 version identification by winget is still happening... and winget is yet again trying to downgrade it to 119.0.6045.21 because it has no manifests for newer versions.

for future versions where it happens i will just change the issue title without adding additional comments.

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/e1b8e1ea-19d9-4738-b8a5-83e40eccf517)

**Comment by BrandonWanHuanSheng** [comment]
It seem like does it side to side install.

**Comment by R-Adrian** [comment]
Chrome Beta on my systems it is not a side-by-side installation, it is installed system-wide (scope: machine)
(yes, plural - the problem with winget happens the same on multiple machines) 

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/fb956771-da55-4435-86b6-29ae59fe2ad8)

**Comment by R-Adrian** [comment]
also, the stable version of Chrome is 119.0.6045.106 (currently), so i don't know where winget is pulling the 118 version number from...
![image](https://github.com/microsoft/winget-pkgs/assets/16319504/f53aab88-c22f-423a-b0b6-f661e5f97f14)

**Comment by R-Adrian** [comment]
i found a version 118 of a Chromium-derived browser ... but is Microsoft Edge, not Google Chrome... could winget mis-identify MS Edge as Google Chrome?

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/ce52317c-1224-40f3-b555-894e48b3e4c6)

**Comment by BrandonWanHuanSheng** [comment]
I think could be displayed version key was not deleted.

**Comment by BrandonWanHuanSheng** [comment]
I am going to do with a quick check to see if binary is correct.

**Comment by BrandonWanHuanSheng** [comment]
It look like I was trying to download but an interrupted action which is vanity url

**Comment by BrandonWanHuanSheng** [comment]
Resolving where is the hashes failed.

**Comment by BrandonWanHuanSheng** [comment]
@denelon. Sometimes, it was misidentified or winget confused.

**Comment by BrandonWanHuanSheng** [comment]
The pipelines was merged #124544. Is the issue still persists.

**Comment by R-Adrian** [comment]
Chrome Beta is still identified as version 118-something.... `¯\_(ツ)_/¯ `

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/76215849-db2f-44a4-a139-652a26362531)

**Comment by BrandonWanHuanSheng** [comment]
I am going to del superseded manifests. This one might help

**Comment by BrandonWanHuanSheng** [comment]
Waiting to see if #124601 get merged.

**Comment by BrandonWanHuanSheng** [comment]
@R-Adrian, Can you see if that one was resolved?.

**Comment by BrandonWanHuanSheng** [comment]
It seem like need to cleanup all the folder.

**Comment by BrandonWanHuanSheng** [comment]
Someone set display version and upgrade code which caused it

**Comment by BrandonWanHuanSheng** [comment]
I am going to del all other version left the newest version.

**Comment by R-Adrian** [comment]
> Can you see if that one was resolved?.

the problem still happens



> Someone set display version and upgrade code which caused it. 

i looked back through the commit history, it looks like this started to happen when @vedantmgoyal2009 migrated the winget package manifest version from 1.2.0 to 1.5.0 ,,, but i cannot figure out where did they get that DisplayVersion number from...

https://github.com/microsoft/winget-pkgs/pull/117105/commits/3dc8c61a62f54b994bce28ab60ba2877d02ca680

**Comment by BrandonWanHuanSheng** [comment]
Can you double check to see if the hashes was mismatched on current version.

**Comment by R-Adrian** [comment]
```
 Installer Url: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
 Installer SHA256: 88e53d6fb3d9cc1a67273e6a911a82806587c72d55e6c6c59a13ca772b19749f
```
those lines from the 120.0.6099.5 manifest are still correct, that SHA256 hash matches the file that i just downloaded manually from Google.

I forced a re-install of the MSI on top of the existing Chrome Beta and the version 118 detection still happens... (i think because the other pull requests to delete old version of manifests have not been commited yet)

```
> winget upgrade
Name               Id                 Version         Available    Source
-------------------------------------------------------------------------
Google Chrome Beta Google.Chrome.Beta > 118.0.5993.11 120.0.6099.5 winget
1 upgrades available.
```

**Comment by BrandonWanHuanSheng** [comment]
Yes, that is true

**Comment by R-Adrian** [comment]
The manifest cleanup of old versions has finally been approved and commited, the wrong version detection is no longer happening.

Thank you!

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/c3a24d27-76f0-40a7-9143-9362e6bd443d)

(that pin for Discord in the screenshot is an unrelated issue - the Discord app is doing self-updates but is not updating the version number in registry when it updates itself))
