### ISSUE TITLE
Azure Pipelines not started

### ISSUE THREAD

**Issue by DocBox12** [microsoft/winget-pkgs#1227]
I have several pull requests and Azure Pipelines has been automatically launched everywhere, only in two cases.

https://github.com/microsoft/winget-pkgs/pull/934
https://github.com/microsoft/winget-pkgs/pull/933

Even after making corrections, the bot does not start. I checked the yaml files on the local computer and winget reports that they are properly created and the applications are installing on the computer.

**Comment by denelon** [comment]
This is resolved.
