### ISSUE TITLE
[Update Request]: Tutanota

### ISSUE THREAD

**Issue by PottedRosePetal** [microsoft/winget-pkgs#122757]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Tutanota.Tutanota

### Package Version

3.114.1

### Please describe the changes you would like to see

there is a new version (3.118.13) available, old version does not work anymore. 

https://tutanota.com/#download

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #122845;
