### ISSUE TITLE
[New Feature]: Adding contributors section to the readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [microsoft/winget-pkgs#122859]
### Description of the new feature/enhancement

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!

### Proposed technical implementation details (optional)

![contributors](https://github.com/microsoft/winget-pkgs/assets/147402107/c8a084bb-a4ae-4fd5-a985-c059d4ca18d5)

**Comment by Kalyanimhala** [comment]
@mtodd kindly assign me this #122859 issue I want to work on it.

**Comment by Trenly** [comment]
@Kalyanimhala - This repo has over 2400 contributors. I'm not sure that it's reasonable to add a contributors section to the readme recognizing them all. Winget-Pkgs isn't quite like other open-source repositories
![image](https://github.com/microsoft/winget-pkgs/assets/12611259/fe5a1c27-8347-4839-90bb-60d391d8bcdb)

**Comment by Kalyanimhala** [comment]
@Trenly  Ok thanks, no issues.

**Comment by denelon** [comment]
OK, I'll go ahead and close this issue as not planned.
