### ISSUE TITLE
[Update Request]: dotPDNLLC.paintdotnet to v5.0.11

### ISSUE THREAD

**Issue by FBoucher** [microsoft/winget-pkgs#122854]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

dotPDNLLC.paintdotnet

### Package Version

5.0.10

### Please describe the changes you would like to see

There a new version 5.0.11 available on [https://github.com/paintdotnet/release/releases](https://github.com/paintdotnet/release/releases)

The mix of bot version make the install failed via Winget

**Comment by mdanish-kh** [comment]
This should be resolved with
- https://github.com/microsoft/winget-pkgs/pull/122671 (changes take some time to get published)
