### ISSUE TITLE
[Update Request]: Mullvad Browser to 13.0

### ISSUE THREAD

**Issue by tabtomi8** [microsoft/winget-pkgs#123047]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mullvad.Browser

### Package Version

13.0

### Please describe the changes you would like to see

https://github.com/mullvad/mullvad-browser/releases/tag/13.0

**Comment by Dragon1573** [comment]
@tabtomi8 The new version was introduced about 20 hours ago. This issue can be closed as completed.

- Related https://github.com/microsoft/winget-pkgs/pull/123058
