### ISSUE TITLE
[Package Request]: Password Safe

### ISSUE THREAD

**Issue by southisup** [microsoft/winget-pkgs#123025]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/passwordsafe/files/latest/download – BUT serves 32-bit by default
Publisher: https://pwsafe.org/
Package Name: Password Safe / pwsafe
Description: password manager
Package Version: current V3.64
Installer URL: https://sourceforge.net/projects/passwordsafe/files/Windows/3.64.0/pwsafe64-3.64.0.msi/download

There is a GitHub but it's non-Windows versions only:  https://github.com/pwsafe/pwsafe/releases/latest

Note was in list at https://github.com/microsoft/winget-pkgs/issues/906

**Comment by Dragon1573** [comment]
This package identifier is already present as `RonyShapiro.PasswordSafe`, stored in `manifests/r/RonyShapiro/PasswordSafe`. Current latest version of this package in `winget` is `v3.62.0`. I can make help updating the package.

```text
PS> winget search RonyShapiro.PasswordSafe
名称          ID                       版本   源
-----------------------------------------------------
Password Safe RonyShapiro.PasswordSafe 3.62.0 winget
```
