### ISSUE TITLE
[Package Request]: dropbox-dash

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#123740]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.dropbox.com/dash
Publisher: dropbox
Package Name: dropbox-dash
Description: Search all your apps. All your tabs. All in one place. Don’t just save time—spend it well with Dropbox Dash, your AI-powered universal search tool. Keep your key information just a few clicks away, so you can focus less on busywork and more on big ideas.
Package Version: 2.92.0
Installer URL: https://dash-releases.s3.amazonaws.com/Dropbox%20Dash%20Setup%202.92.0.exe

**Comment by BrandonWanHuanSheng** [comment]
INSTALL_UNATTENDED_FAILURE_x86: Could be a dialog pop-up say it was just install x64 bits only?
INSTALL_UNATTENDED_SUCEESS_x64: Setup was completely silent.

**Comment by BrandonWanHuanSheng** [comment]
It look like pull request was published-pipelines-succeeded
