### ISSUE TITLE
[Package Request]: Microsoft.Sysinternals.Sysmon

### ISSUE THREAD

**Issue by janegilring** [microsoft/winget-pkgs#123715]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
Publisher: Microsoft
Package Name: Microsoft Sysinternals Sysmon
Description: System Monitor (Sysmon) is a Windows system service and device driver that, once installed on a system, remains resident across system reboots to monitor and log system activity to the Windows event log.
Package Version: 15.0
Installer URL: https://download.sysinternals.com/files/Sysmon.zip

**Comment by BrandonWanHuanSheng** [comment]
This pull request can safely closed.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #123717;
