### ISSUE TITLE
[Package Request]: PageEdit

### ISSUE THREAD

**Issue by palopezv** [microsoft/winget-pkgs#123996]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Sigil-Ebook/PageEdit/releases
Publisher: Sigil-Ebook
Package Name: PageEdit
Description: WYSIG XHTML editor focused on ebook publishing, complementary to Sigil Ebook Editor.
Package Version: 2.0.2
Installer URL: https://github.com/Sigil-Ebook/PageEdit/releases/download/2.0.2/PageEdit-2.0.2-Windows-x64-Setup.exe

**Comment by Eddga** [comment]
#124177
