### ISSUE TITLE
[Package Request]: WatchGuard SSL VPN

### ISSUE THREAD

**Issue by ramclain** [microsoft/winget-pkgs#123941]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: 
Publisher: WatchGuard
Package Name: Mobile VPN with SSL v12.10 for Windows
Description: WatchGuard Mobile VPN client with SSL v12.10 for Windows
Package Version: 12.10
Installer URL: https://cdn.watchguard.com/SoftwareCenter/Files/MUVPN_SSL/12_10/WG-MVPN-SSL_12_10.exe

**Comment by BrandonWanHuanSheng** [comment]
It look like unavailable to run unattended

**Comment by fancybody** [comment]
![fs102923](https://github.com/microsoft/winget-pkgs/assets/87397831/332a5044-724f-4e0d-ac45-c4a4875a48c9)
 `/SILENT` and `/VERYSILENT` works on my end.
