### ISSUE TITLE
[Update Request]: ViGEm.HidHide

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#124286]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ViGEm.HidHide

### Package Version

1.3.173

### Please describe the changes you would like to see

https://github.com/nefarius/HidHide/releases/tag/v1.4.181.0

**Comment by BrandonWanHuanSheng** [comment]
That one is a beta releases. But winget can confused with that edition above.

**Comment by Dragon1573** [comment]
> It look like the domain URL does not match []() that you provided.

**Comment by soredake** [comment]
https://github.com/nefarius/HidHide/releases/tag/v1.4.181.0 is out

**Comment by BrandonWanHuanSheng** [comment]
It might cause a binary-validation-error if it is not right domain.

**Comment by reloxx13** [comment]
Hey, @Dragon1573 please update to latest version and remove this version, it got nuked.
Thank you!
