### ISSUE TITLE
[Package Request]: neovim

### ISSUE THREAD

**Issue by Redhawk18** [microsoft/winget-pkgs#124326]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/neovim/neovim/wiki/Installing-Neovim
Publisher: neovim
Package Name: nvim
Description: neovim
Package Version: 0.9
Installer URL: https://github.com/neovim/neovim/releases/latest/download/nvim-win64.msi

While Neovim-qt is in winget, I want to open nvim within Windows Terminal.

**Comment by Yousha** [comment]
Resolved by #133235 ?

**Comment by mdanish-kh** [comment]
Close with reason: Resolved by #133235;
