### ISSUE TITLE
[New Feature]: Inform PR authors when they are using a deprecated schema version

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#124470]
### Description of the new feature/enhancement

When a PR is made for a package, the schema version should be the latest version supported by validation.

A label "Manifest-Version-Deprecated" should be added to the PR informing authors when they are using a deprecated version.

PR authors should be informed which version of the schema is the latest supported by validation, and when a PR is created with an older version, a label should be added to inform them.

**Comment by Trenly** [comment]
* Related to #80572
* Related to #124472
