### ISSUE TITLE
[New Feature]: Inform PR authors when they are using an invalid schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#124471]
### Description of the new feature/enhancement

When a PR is made for a package, the schema version should be a valid version.

A label "Manifest-Version-Error" should be added to the PR informing authors when they are using an invalid version.

PR authors should be informed which version of the schema is the latest supported by validation, and when a PR is created with an invalid version, a label should be added to inform them.

**Comment by Trenly** [comment]
* Related to #80572
* Related to #83014
