### ISSUE TITLE
[New Feature]: Missing Fields Notification

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#124465]
### Description of the new feature/enhancement

Sometimes a new version of a package is submitted, and the manifest isn't as rich or complete as the "latest" version of that package. I'd like to have a label added to those PRs like "Manifest-Metadata-Consistency".

In addition, I would like an informational message indicating which fields are present in the latest version of the manifest and not in the current PR.

This is not a blocking behavior, but an informational one. This would make it easier for moderators to validate the quality of the current PR. Sometimes the new PR is exactly what is needed, and other times, the missing fields add value.

**Comment by mdanish-kh** [comment]
- Related to https://github.com/microsoft/winget-pkgs/issues/92688

[Policy] Area-Validation-Pipeline

**Comment by stephengillie** [comment]
I've just built the means to check for missing fields into my PR Watcher. Currently it only checks for AppsAndFeaturesEntries, but other fields could be added. 
- It gathers the version number from WinGet, then uses this to build the installer yaml URL. 
- It downloads this then checks it for the field.
- Then it checks the current manifest for the field.
- If the two answers don't match, it alerts. 

Should this be increased to check all manifest fields, or only specific ones? 
Also, should we move this from the approval step of the process and into the validation step?
