### ISSUE TITLE
[Update Request]: ViGEm.ViGEmBus

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#124548]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ViGEm.ViGEmBus

### Package Version

1.22.0

### Please describe the changes you would like to see

https://github.com/nefarius/ViGEmBus/releases/tag/v1.22.0

**Comment by Dragon1573** [comment]
- Resolved by https://github.com/microsoft/winget-pkgs/pull/124609
