### ISSUE TITLE
[Update Request]: ViGEm.HidHide

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#124549]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ViGEm.HidHide

### Package Version

1.4.186.0

### Please describe the changes you would like to see

https://github.com/nefarius/HidHide/releases/tag/v1.4.186.0

**Comment by Dragon1573** [comment]
The above pull request is merged. This issue can be closed.
