### ISSUE TITLE
[Package Request]: Windows 10 SDK version 2104 (10.0.20348.0)

### ISSUE THREAD

**Issue by ArchGuyWu** [microsoft/winget-pkgs#124608]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
Publisher: Microsoft Corporation
Package Name: Microsoft.WindowsSDK.10.0.20348
Description: Windows Software Development Kit - Windows 10.0.20348.1
Package Version: 10.1.20348.1
Installer URL: https://go.microsoft.com/fwlink/?linkid=2164145

**Comment by BrandonWanHuanSheng** [comment]
This one seem need to write the installer data.

**Comment by BrandonWanHuanSheng** [comment]
Copying some related file which is related to the pull.

**Comment by ArchGuyWu** [comment]
> This one seem need to write the installer data.

I added some information for [this](https://github.com/ArchGuyWu/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsSDK/10/0/20348/10.1.20348.1), but don't know how to get the ProductCode.

**Comment by BrandonWanHuanSheng** [comment]
I still working on the pull request. It might take a while.

**Comment by BrandonWanHuanSheng** [comment]
The pipelines is taking longer than expected usual.  #124858

**Comment by ArchGuyWu** [comment]
> The pipelines is taking longer than expected usual. #124858

The default installation parameter will install all components.

**Comment by BrandonWanHuanSheng** [comment]
#124886

**Comment by BrandonWanHuanSheng** [comment]
Already added in

**Comment by ArchGuyWu** [comment]
> Already added in

Thanks,
