### ISSUE TITLE
[Package Issue]: Remove The Whole Folder of Fndroid.ClashForWindows

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-pkgs#124660]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

It appears package Fndroid.ClashForWindows's whole project has been deleted by @Fndroid (Author & Developer). All of its version is unavailable now. Please remove all version for it.

Related to #124619 https://github.com/microsoft/winget-pkgs/issues/124619#issuecomment-1792483273

**Comment by BrandonWanHuanSheng** [comment]
Please wait a while. I need spot which one is a vanity URL.

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng It is no need to verify. The whole project including releases has already deleted.

**Comment by BrandonWanHuanSheng** [comment]
I will not verify but I need to verify that other app which is also being superseded by same url. Like Google.Chrome.Beta

**Comment by BrandonWanHuanSheng** [comment]
It might take a while for the operation to complete.

**Comment by BrandonWanHuanSheng** [comment]
I might be back for a while.

**Comment by BrandonWanHuanSheng** [comment]
All the manifest queued to the pipelines

**Comment by CoolPlayLin** [comment]
Once they are merged, please pin me to mark this issue as complete

**Comment by BrandonWanHuanSheng** [comment]
All the pipelines is in required moderator to approvef

**Comment by BrandonWanHuanSheng** [comment]
The pull request is being finalizing...

**Comment by BrandonWanHuanSheng** [comment]
@CoolPlayLin, Did you noticed that pipelines have been merged. @LiCaoZ The whole directory of Fndroid.ClashforWindows was permanently deleted.

**Comment by BrandonWanHuanSheng** [comment]
@CoolPlayLin, can you marked this issue as completed.

**Comment by BrandonWanHuanSheng** [comment]
@CoolPlayLin Please marked it as resolved. All the files has been deleted in winget-pkgs.

**Comment by mdanish-kh** [comment]
Close with reason: Package removed from the repo;
