### ISSUE TITLE
Can't install Microsoft.Azd latest version 1.4.3

### ISSUE THREAD

**Issue by vhvb1989** [microsoft/winget-pkgs#124600]
despite the 1.4.400 manifest version being [merged last week](https://github.com/microsoft/winget-pkgs/pull/123748), 1.4.300 is still what is found. Also, winget even says a newer version is available, but it doesn't show up when running winget upgrade

![image](https://github.com/microsoft/winget-pkgs/assets/24213737/b55b5e7e-5ef2-477c-88e0-b2a911406de4)

**Comment by heaths** [comment]
A user removed it in https://github.com/microsoft/winget-pkgs/pull/123748. Would be great if we could lock down certain package prefixes like with NuGet packages. I'm restoring it now.
