### ISSUE TITLE
where is Clash-for-Windows package

### ISSUE THREAD

**Issue by wangcomeoffit** [microsoft/winget-pkgs#124619]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Side-By-Side installation.

### Brief description of your issue

where is Clash-for-Windows package

### Steps to reproduce

where is Clash-for-Windows package

### Actual behavior

where is Clash-for-Windows package

### Expected behavior

where is Clash-for-Windows package

### Environment

```raw
where is Clash-for-Windows package
```

### Screenshots and Logs

where is Clash-for-Windows package

**Comment by ArchGuyWu** [comment]
https://github.com/Fndroid/clash_for_windows_pkg 404

**Comment by CoolPlayLin** [comment]
@Fndroid Could you please tell us why you delete the whole project?

**Comment by CoolPlayLin** [comment]
> @Fndroid Could you please tell us why you delete the whole project?

According the information from internet, the project was forced to be deleted due to that @Fndroid has received a threat from Chinese government. Because the behavior of developing app, which can help people in China mainland bypass the GFW(China's National Great Firewall), is illegal.

**Related Laws**
>*Interim Provisions of the People's Republic of China on the Administration of International Networking of Computer Information Networks*

> Article 6 For direct international networking of computer information networks, it is necessary to use the international entrance and exit channels provided by the national public telecommunications network of the Ministry of Posts and Telecommunications.
> No unit or individual may establish or use other channels for international networking on their own.

**Comment by myhonggithub** [comment]
So if it is **possible** For us to find any packages of Clash For Windows?

**Comment by CoolPlayLin** [comment]
@myhonggithub You could find it via other ways if there is someone archived it. Anyway, Clash For Windows current no longer owned official releases channel

**Comment by tiankaima** [comment]
> @myhonggithub You could find it via other ways if there is someone archived it. Anyway, Clash For Windows current no longer owned official releases channel

I opened #124535 to delete the whole package, apparently this isn't the supposed way to do so.

Since now all
```yaml
InstallerUrl:
  https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.xx.x/Clash.for.Windows.Setup.0.xx.x.exe
```
aren't available anymore, is the team removing the files or updating these urls to an archive location?

**Comment by BrandonWanHuanSheng** [comment]
All the pipelines is being required moderator to be approved.

**Comment by BrandonWanHuanSheng** [comment]
The pipelines is being finalize

**Comment by BrandonWanHuanSheng** [comment]
All the pipelines is merged

**Comment by BrandonWanHuanSheng** [comment]
> > @myhonggithub You could find it via other ways if there is someone archived it. Anyway, Clash For Windows current no longer owned official releases channel
> 
> I opened #124535 to delete the whole package, apparently this isn't the supposed way to do so.
> 
> Since now all
> ```yaml
> InstallerUrl:
>   https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.xx.x/Clash.for.Windows.Setup.0.xx.x.exe
> ```
> aren't available anymore, is the team removing the files or updating these urls to an archive location?

The file was removed by that branch. See https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aclosed+ClashforWindows
