### ISSUE TITLE
[Update Request]: Firefox ESR 115.4.0 update

### ISSUE THREAD

**Issue by alpha194** [microsoft/winget-pkgs#124882]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Firefox.ESR

### Package Version

115.4.0

### Please describe the changes you would like to see

There is a new release 115.4.0 for ESR that contains security fixes.

Download page:
https://www.mozilla.org/en-US/firefox/enterprise/#download

**Comment by lunacd** [comment]
#125503

**Comment by lunacd** [comment]
The requested version is merged. Please close as completed.

**Comment by Exorcism0666** [comment]
@stephengillie ^

**Comment by mdanish-kh** [comment]
Close with reason: Package merged in repo in #125503;
