### ISSUE TITLE
[Package Request]: pipe-rename

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#124933]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/marcusbuffett/pipe-rename/releases
Publisher: marcusbuffett
Package Name: pipe-rename
Description: pipe-rename takes a list of files as input, opens your editor of choice, then renames those files accordingly.
Package Version: 1.6.5
Installer URL: https://github.com/marcusbuffett/pipe-rename/releases/download/1.6.5/renamer-1.6.5-x86_64-pc-windows-msvc.exe

**Comment by ShatilKhan** [comment]
I'm taking this one

**Comment by Dragon1573** [comment]
Could you please link your pull request with this issue by adding following markdown content to the first comment of your PR? I can't find you PR 😕

```markdown
- Resolve https://github.com/microsoft/winget-pkgs/issues/124933
```
