### ISSUE TITLE
[Update Request]: KDE.Krita 5.2.1

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#124968]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

KDE.Krita

### Package Version

5.2.1

### Please describe the changes you would like to see

https://krita.org/en/item/krita-5-2-1-released/

**Comment by BrandonWanHuanSheng** [comment]
This can be normally found by download.kde.org

**Comment by BrandonWanHuanSheng** [comment]
#124974
