### ISSUE TITLE
Cannot install the following packages 

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#124954]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I try to install the following list of packages 

Bandizip [Bandisoft.Bandizip]
GOM Player [GOMLab.GOMPlayer]
IObit Uninstaller [IObit.Uninstaller]
MEGAsync [Mega.MEGASync]
MiniTool Partition Wizard Free [MiniTool.PartitionWizard.Free]
Webex [Cisco.WebexTeams]
 EA app [ElectronicArts.EADesktop]

I am facing the messages bellow :

Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

winget install --id=Bandisoft.Bandizip -e; winget install --id=GOMLab.GOMPlayer -e; winget install --id=IObit.Uninstaller -e; winget install --id=Mega.MEGASync-e; winget install --id=MiniTool.PartitionWizard.Free -e; winget install --id=Cisco.WebexTeams -e; winget install --id=ElectronicArts.EADesktop -e

### Actual behavior

I am facing the messages bellow :

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Installed succesfully 

### Environment

```raw
PS C:\Users\> winget --info
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2506
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Dragon1573** [comment]
Reproduced by downloading the installer with Aria2. `Bandisoft.Bandizip` does have this `Hash-Mismatch` problem.

I can make help.

**Comment by BrandonWanHuanSheng** [comment]
Does Powershell allow me to use URL instead of File to get SHA256? But a critical problem, Powershell can't extract the file. Because some of burn file contains 0 file. Also, some of the exe is in bin of the setup.

**Comment by Dragon1573** [comment]
> Does Powershell allow me to use URL instead of File to get SHA256?

NO, IT DOESN'T. Not only Powershell, all hash algorithm should calculate hashes on a file. URL here is only a "link" to the file content, not the file content "itself". Try to hash on a URL will only get the hash value of the URL string.

There's no online platform providing such kind of service. If you'd like to, you can try to implement it on your own. Send a URL to the service, the backend server download the file content and calculate hashes for you remotely and response it to you.

**Comment by Dragon1573** [comment]
> Reproduced by downloading the installer with Aria2. `Bandisoft.Bandizip` does have this `Hash-Mismatch` problem.

`Bandisoft.Bandizip` using a "static" installer URL which allways point to the latest version. The installer URL is version-unrelated.

**Comment by Dragon1573** [comment]
```[tasklist]
## Pull requests related `ElectronicArts.EADesktop`
- [x] https://github.com/microsoft/winget-pkgs/pull/126158
- [x] https://github.com/microsoft/winget-pkgs/pull/125848
- [x] https://github.com/microsoft/winget-pkgs/pull/125856
- [x] https://github.com/microsoft/winget-pkgs/pull/125872
- [x] https://github.com/microsoft/winget-pkgs/pull/125883
- [x] https://github.com/microsoft/winget-pkgs/pull/125890
- [x] https://github.com/microsoft/winget-pkgs/pull/125895
- [x] https://github.com/microsoft/winget-pkgs/pull/125898
- [x] https://github.com/microsoft/winget-pkgs/pull/125901
- [x] https://github.com/microsoft/winget-pkgs/pull/126165
```

**Comment by Dragon1573** [comment]
## Pull requests related `IObit.Uninstaller`

- https://github.com/microsoft/winget-pkgs/pull/126088

**Comment by Dragon1573** [comment]
### Pull requests related `Cisco.WebexTeams`

- https://github.com/microsoft/winget-pkgs/pull/125313
- https://github.com/microsoft/winget-pkgs/pull/126095
- https://github.com/microsoft/winget-pkgs/pull/126090
- https://github.com/microsoft/winget-pkgs/pull/126083

**Comment by BrandonWanHuanSheng** [comment]
OOPS! https://www.virustotal.com/gui/file/46d5482980d028aa875115471bf01e5c9480283df74de6f242d67638c855ffff/details Is this false positive?

**Comment by stephengillie** [comment]
Hi @ivonenchev,

Are you still seeing a hash mismatch for any of these applications?
