### ISSUE TITLE
[Pull Request Issue]: I cannot accept CLA via comment

### ISSUE THREAD

**Issue by MokaSoda** [microsoft/winget-pkgs#124962]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I cannot accept CLA by commenting "@microsoft-github-policy-service agree"

### Steps to reproduce

While azure-pipelines and wingetbot are running, I comment "@microsoft-github-policy-service agree" to agree CLA.

### Actual behavior

https://github.com/microsoft/winget-pkgs/pull/124959/checks?check_run_id=18395841937

Title show
"Contributor License Agreement is not agreed yet."

### Expected behavior

The license/cla result should be

"All CLA requirements met."

### Environment

```raw
Not applicable. This is PR system problem not winget client problem.
```

**Comment by BrandonWanHuanSheng** [comment]
This seem like a labels issue because @microsoft-github-policy-service did not add other labels when @wingetbot  add those labels. But the team is already in aware due to one of my pull request keep re-run  /Azure-Pipelines run. Are you available to try again when moderator is around?

**Comment by denelon** [comment]
There was an issue this morning with the CLA bot. We believe it has been resolved and re-running the pipelines should pass now.
