### ISSUE TITLE
[Package Request]: Spacedrive.Spacedrive

### ISSUE THREAD

**Issue by HeavySnowJakarta** [microsoft/winget-pkgs#125024]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.spacedrive.com
Publisher: Spacedrive
Package Name: Spacedrive
Description: Spacedrive is an open source cross-platform file manager, powered by a virtual distributed filesystem VDFS written in Rust.
Package Version: 0.1.2
Installer URL: https://www.spacedrive.com/api/releases/desktop/stable/windows/x86_64

**Comment by Foadsf** [comment]
Now when I try installing, I get

```
Installer hash does not match.
```
