### ISSUE TITLE
[Update Request]: Elgato.CameraHub package does not appear to contain all needed version info

### ISSUE THREAD

**Issue by trajanmcgill** [microsoft/winget-pkgs#125262]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Elgato.CameraHub

### Package Version

1.8.0.852

### Please describe the changes you would like to see

The `Elgato.CameraHub` package correctly installs the latest version (1.8.0.852 as of the present moment), but following the installation `winget` is unable to fully determine the currently installed version, and it therefore continually reports that the package needs update to the latest version. I am not well-versed in the package contents for winget, but I do notice that a particular value called "DisplayVersion" disappeared from the installation YAML file a few versions ago, and perhaps this is the culprit.

**Comment by BrandonWanHuanSheng** [comment]
It seem like I can’t see AppsandFeaturesVersionEntries.
I might use sigcheck program to determine AppsandFeaturesEntries. It seem like it could be mostly in Alternative Data Stream

**Comment by BrandonWanHuanSheng** [comment]
The characteristics of AppsandFeaturesEntries
-  0 file appears in burn file
-  Exe file contain bin in the setup
-  might be able to use sigcheck to determine AppsandFeaturesEntries.

**Comment by BrandonWanHuanSheng** [comment]
It seem I almost found Publisher.

**Comment by BrandonWanHuanSheng** [comment]
Oops. One of the folder contains AppsandFeaturesEntries
