### ISSUE TITLE
[Package Issue]: clsid2.mpc-hc 404 Not Found error

### ISSUE THREAD

**Issue by tabtomi8** [microsoft/winget-pkgs#125453]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

0x80190194 : Not Found (404).

### Steps to reproduce

- Try to install MPC-HC
- 404 not found error

### Actual behavior

0x80190194 : Not Found (404).

### Expected behavior

Successfully installing the package.

### Environment

```raw
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2506
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![Képernyőkép 2023-11-09 163034](https://github.com/microsoft/winget-pkgs/assets/59199402/0571a321-3e55-466c-86e9-afb5cd6996a9)
[WinGet-2023-11-09-16-28-09.154.log](https://github.com/microsoft/winget-pkgs/files/13309865/WinGet-2023-11-09-16-28-09.154.log)
[WinGetCOM-2023-11-09-16-28-11.102.log](https://github.com/microsoft/winget-pkgs/files/13309866/WinGetCOM-2023-11-09-16-28-11.102.log)

**Comment by MagicAndre1981** [comment]
2.1.1 was rejected and 2.1.2 was released

![image](https://github.com/microsoft/winget-pkgs/assets/8274816/fb2a1fb5-8cfd-4aa5-b092-641335520c81)

So, the 2.1.1 should be removed and 2.1.2 added
