### ISSUE TITLE
Upload installer to Microsoft CDN?

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-pkgs#12553]
I want to add support for Fortinet.FortiClientVPN, but sadly on their website they only distribute the Online installer version

Page: https://www.fortinet.com/support/product-downloads#vpn7
Online installer (will redirect): https://links.fortinet.com/forticlient/win/vpnagent
Online installer (redirected): https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.0.0029.exe

This online installer sadly does not support any switches, but it does download the offline and then the offline supports everything needed:

![image](https://user-images.githubusercontent.com/29582865/118011138-10633b80-b326-11eb-9350-a1ba045ef105.png)

They advise in their own KB to use the online installer to download the offline installer, and find it in `%TEMP%\FortiClientVPN.exe`:

https://kb.fortinet.com/kb/documentLink.do?externalID=FD48418

But of course, Winget can't do this all automatically, so I wonder: is there a Microsoft CDN where we can upload installers to be used by Winget later, or something like that?

**Comment by denelon** [comment]
No. Several ISVs and publishers prohibit others from distributing their software. There is also true cost associated with hosting and distributing binaries.

**Comment by felipecrs** [comment]
> Several ISVs and publishers prohibit others from distributing their software.

Yes, I meant the ones who allow, of course. I'm not actually sure about Fortinet, though.

> There is also true cost associated with hosting and distributing binaries.

Definitely, but perhaps it would be of Microsoft interest doing so.

Thank you for the answer, I'll be closing the issue as I just wanted to raise this doubt.
