### ISSUE TITLE
Validation Error: The source request body exceeds the maximum permissible limit (100MB)

### ISSUE THREAD

**Issue by xiaoyang-liu-cs** [microsoft/winget-pkgs#1260]
Pull request: #1256 Add Bilibili Livehime 3.15.0.1649
Installer URL: `https://dl-hdslb-com.oss-cn-shanghai.aliyuncs.com/bili/bililive/win/Livehime-Win-beta-3.15.0.1649.exe` (Size: 129MB)
I could download the installer file on my personal computer, but the pull request cannot pass the validation test.
The [validation test](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=83641&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d) failed with the message `The source request body for copy source is too large and exceeds the maximum permissible limit (100MB).`

**Comment by denelon** [comment]
The size limit has been removed.
