### ISSUE TITLE
Remove beta versions of Thunderbird and Firefox

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#126346]
@stephengillie Please don't approve @vedantmgoyal2009's PRs for `Mozilla.Thunderbird.Beta` anymore, as these cause problems with the current version of winget.

_Originally posted by @treysis in https://github.com/microsoft/winget-pkgs/issues/125399#issuecomment-1804295063_

**Comment by denelon** [comment]
These cause problems for customers during the upgrade flow.

It's like we will not be able to safely bring these packages back into the community repository until either the installers have a way for WinGet to determine what versions are stable vs. beta or WinGet has support for channels:

* https://github.com/microsoft/winget-cli/issues/147

**Comment by denelon** [comment]
Mentioning @Trenly as well based on comments in the PR.

**Comment by vedantmgoyal2009** [comment]
The issue can be closed, once the following PRs have been merged.

- https://github.com/microsoft/winget-pkgs/pull/126771
- https://github.com/microsoft/winget-pkgs/pull/126772
- https://github.com/microsoft/winget-pkgs/pull/126773
- https://github.com/microsoft/winget-pkgs/pull/126774
- https://github.com/microsoft/winget-pkgs/pull/126775

**Comment by mdanish-kh** [comment]
Close with reason: Beta versions of firefox and thunderbird have been removed;
