### ISSUE TITLE
Cannot install packages 

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#126589]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Cannot instal the following packages : 

viber.viber is missing 

IObit.Uninstaller
Mega.MEGASync
Daum.PotPlayer

### Steps to reproduce

winget install --id=viber.viber -e; winget install --id=IObit.Uninstaller -e; winget install --id=Mega.MEGASync -e; winget install --id=Daum.PotPlayer -e;

### Actual behavior

For viber.viber, the packages is missing 

for
IObit.Uninstaller
Mega.MEGASync
Daum.PotPlayer

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

To be installed sucessfully. 

### Environment

```raw
PS C:\Users\> winget --info
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2506
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
* https://github.com/microsoft/winget-pkgs/pull/126088
* https://github.com/microsoft/winget-pkgs/pull/125894
* https://github.com/microsoft/winget-pkgs/pull/126591
* https://github.com/microsoft/winget-pkgs/pull/126593

**Comment by BrandonWanHuanSheng** [comment]
There is a critical problem which is security check failed due to the following. See the details
        Verified:       Signed
        Signing date:   5:58 PM 19/9/2023
        Publisher:      IObit CO., LTD
        Company:        IObit
        Description:    Setup File
        Product:        IObit Uninstaller 13
        Prod version:   13.1.0.3
        File version:   13.1.0.3
        MachineType:    32-bit
        MD5:    65DFDEB20BF56CD5C10EF649D0E0DE2A
        SHA1:   942F06453CA23538ACD790F483FC2CB4367ABB4D
        PESHA1: F862303548E4855D0E19676155AB6D5EC2E02A91
        PE256:  1D0500521558E4EB71FF7164192F7FFD6664708525D7A7B4F90C670FC10B54FE
        SHA256: 46D5482980D028AA875115471BF01E5C9480283DF74DE6F242D67638C855FFFF
        IMP:    20DD26497880C05CAED9305B3C8B9109
        VT detection:   4/76
        VT link:        https://www.virustotal.com/gui/file/46d5482980d028aa875115471bf01e5c9480283df74de6f242d67638c855ffff

**Comment by BrandonWanHuanSheng** [comment]
https://forums.iobit.com/topic/27518-installer-identified-as-risk-blocked/#comment-131403

**Comment by stephengillie** [comment]
Hi @ivonenchev,

Are you still seeing a hash mismatch for any of these applications?
