### ISSUE TITLE
DockerDesktop hash verification failed

### ISSUE THREAD

**Issue by ycrack** [microsoft/winget-pkgs#1265]
I've encountered the error `hash verification failed` during installing the `Docker.DockerDesktop`.

This had prophesied in https://github.com/microsoft/winget-pkgs/pull/190#issuecomment-630985224 .

**Comment by StefanScherer** [comment]
Winget packages need auto updates like the Chocolatey community does in https://github.com/riezebosch/BoxstarterPackages/blob/master/docker-desktop/Update.ps1

Update to version 2.3.0.3 eg. was done in https://github.com/riezebosch/BoxstarterPackages/commit/f74e04b591fce69062c1db75eb9f279b55bb5b5b

As you can see, it's better to use the version specific links.

For version 2.3.0.2 to fix the current package the correct download link can be found here https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2302

**Comment by SoftCreatR** [comment]
@StefanScherer I've also just created a PR (see https://github.com/microsoft/winget-pkgs/pull/1274) for Docker and Docker Edge. I would prefer the full version string. Furthermore, your PR (and even the original PR) is missing the silent switch. This might result in an unwanted behavior, at least in a later version of winget-cli (a simple check via `winget validate manifests/Docker/DockerDesktop/2.3.0.3.yaml` should spit out a warning).

**Comment by StefanScherer** [comment]
Thanks @SoftCreatR, I just started with a small PR to fix the URL. I'll look into the silent options which make sense.

**Comment by SoftCreatR** [comment]
Alternatively, check out my PR and if you think it's fine, just close yours.
