### ISSUE TITLE
[Update Request]: aria2.aria2

### ISSUE THREAD

**Issue by grandpa1946** [microsoft/winget-pkgs#126785]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

aria2.aria2

### Package Version

1.37.0 from 1.36

### Please describe the changes you would like to see

There is a new release (1.37.0) available.
[Download Page Url: https://github.com/microsoft/winget-create/releases
](https://github.com/aria2/aria2/releases/tag/release-1.37.0)

**Comment by BrandonWanHuanSheng** [comment]
Oops, you provide wrong URL. 
Seem like the PackageIdentifier give me clues to the link.

**Comment by BrandonWanHuanSheng** [comment]
Seem like the manifest is using up to date version. aria2/aria2/releases/tag/release-1.37.0

**Comment by BrandonWanHuanSheng** [comment]
@Trenly It seem the manifest was added by someone in the PR.

**Comment by Dragon1573** [comment]
- Resolved by https://github.com/microsoft/winget-pkgs/pull/126900

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #126900;
