### ISSUE TITLE
[Package Request]: github.com/uutils/coreutils

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/winget-pkgs#126833]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

*Type*                | *Data*
----------------------|---------------------------------------------------------------------------------------------------------
**Download Page URI** | https://github.com/uutils/coreutils/releases
**Publisher**         | UUtils Developers
**Package Name**      | `UUtilsDevelopers.Coreutils`
**Description**       | > uutils coreutils is a cross-platform reimplementation of the GNU coreutils in Rust.
**Package Version**   | [0.0.23](https://github.com/uutils/coreutils/releases/tag/0.0.23)
**Installer URI**     | https://github.com/uutils/coreutils/releases/download/0.0.23/coreutils-0.0.23-x86_64-pc-windows-msvc.zip

**Comment by RokeJulianLockhart** [comment]
I chose the MSVC version because it merely *seemed* most appropriate for WinGet. I've no idea whether the GNU or MSVC version is preferable.

**Comment by tertsdiepraam** [comment]
Thanks for making this! Since you asked for feedback, I only have one small suggestion: uutils is usually not capitalized. What else do you need feedback on?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/uutils/coreutils/issues/4291#issuecomment-1813211832

@tertsdiepraam and @sylvestre, WinGet doesn't use that naming scheme. It uses CamelCase reverse DNS with a mandatory publisher as its parent.

**Comment by YDX-2147483647** [comment]
> It uses CamelCase reverse DNS with a mandatory publisher as its parent.

Is it due to winget's doc/spec?

When I was drafting `uutils.coreutils{,.installer,.locale.en-US}.yaml` in https://github.com/uutils/coreutils/issues/4291#issuecomment-1812534020, I chose `uutils.coreutils` because I noticed https://github.com/microsoft/winget-pkgs/tree/master/manifests/u/uxmal/reko, whose ID is **fully lower case**, can be installed by `winget install -e --id uxmal.reko` as decribed in https://winget.run/pkg/uxmal/reko.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/126833#issuecomment-1813751506

I can't say, @YDX-2147483647. I'd never seen an exception after a good few years of using it and helping to publish manifests, so although I might once have been told so or read it, it was probably more likely an assertion at best. We can always change the manifest later, although that *might* cause issues for users.

Have you been able to find anything relevant? https://learn.microsoft.com/en-us/windows/package-manager/configuration/create#example-winget-configuration-file:~:text=in%20this%20section.-,resource,-%3A%20Both%20the%20%22Assertions doesn't appear to be of much use.

**Comment by YDX-2147483647** [comment]
The only thing I find is https://github.com/microsoft/winget-pkgs/blob/f508b5d5e52df0b055e95e8ddc4fa1c01135b7fa/doc/manifest/schema/1.5.0/installer.md?plain=1#L152C25-L152C36

> This key is the unique identifier for a given package. This value is generally in the form of `Publisher.Package`. It is case sensitive, and this value must match the folder structure under the partition directory in GitHub.

I have not inspect any winget manifest before, so let's take your choice.

**Comment by adityamwagh** [comment]
Can you update this to v0.0.26?

**Comment by sylvestre** [comment]
@Dragon1573 is that something you could help with? thanks

**Comment by qualk** [comment]
Can this be updated to `v0.0.29`?

**Comment by YDX-2147483647** [comment]
I have created https://github.com/uutils/coreutils/issues/7295. Let's fix it there. (This issue was closed in 2023.)
