### ISSUE TITLE
[Update Request]:  Microsoft.VisualStudioCode version 1.84.2

### ISSUE THREAD

**Issue by jahvari** [microsoft/winget-pkgs#126841]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.VisualStudioCode

### Package Version

1.84.2

### Please describe the changes you would like to see

There is a new update to 1.84.2
https://update.code.visualstudio.com/1.84.2/win32-x64-user/stable

**Comment by Dragon1573** [comment]
Issue can be closed as completed.

- Resolved by https://github.com/microsoft/winget-pkgs/pull/127062

**Comment by mdanish-kh** [comment]
Close with reason: See above;
