### ISSUE TITLE
[Package Issue]: ImageMagick.ImageMagick

### ISSUE THREAD

**Issue by mstevens83** [microsoft/winget-pkgs#126969]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I install the ImageMagick.ImageMagick package it adds the installation folder to the system path of my machine. I think this should not be the default behaviour. Instead adding to the user path seems more appropriate.
Note that I was not running install with administrator privileges.

### Steps to reproduce

Run `winget install ImageMagick.ImageMagick`

### Actual behavior

Package gets installed and installation path is added to system path.

### Expected behavior

Package gets installed and installation path is added to user path.

### Environment

```raw
Windows Package Manager v1.6.3133
Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

ImageMagick 7.1.1-21 Q16-HDRI (64-bit) (2023-10-21)
```

**Comment by Trenly** [comment]
Looking at the [manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/i/ImageMagick/ImageMagick/7.1.1.21/ImageMagick.ImageMagick.installer.yaml), ImageMagick uses an inno installer. This means that winget does not control any of the data which is written to the registry or the path variable, and winget cannot do anything to fix it. This is an issue with the ImageMagick installer itself and only the publisher of ImageMagick will be able to fix it. I would suggest reaching out to their support team.

[Policy] Installer-Issue

**Comment by BrandonWanHuanSheng** [comment]
It always available in github.com.
You can try https://github.com/ImageMagick/repositories.

**Comment by BrandonWanHuanSheng** [comment]
I think that inno have /CURRENTUSER switches. But the switches was not activate on the manifest.
