### ISSUE TITLE
[Update Request]: Unity.Unity.2022 release 2022.3.13f1

### ISSUE THREAD

**Issue by lofidevops** [microsoft/winget-pkgs#127093]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Unity.Unity.2022

### Package Version

2022.3.13f1

### Please describe the changes you would like to see

There is a new release 2022.3.13f1 available from https://unity.com/releases/editor/qa/lts-releases

The direct URL is https://download.unity3d.com/download_unity/5f90a5ebde0f/Windows64EditorInstaller/UnitySetup64-2022.3.13f1.exe

**Comment by lofidevops** [comment]
It's not clear to me if I can actually contribute here. @vedantmgoyal2009 it looks like your bot handles it? :D

**Comment by Dragon1573** [comment]
> It's not clear to me if I can actually contribute here.

Yes, you can! Try to use `wingetcreate.exe` or `Tools/YamlCreate.ps1` for creating manifests. They are interactive tools for doing this work. Follow the instructions, fill in the blanks, and don't forget to test the manifest locallyor in Windows Sandbox.

> @vedantmgoyal2009 it looks like your bot handles it? :D

Not yet. I search all pull requests related to this package identifier and there's no PR for release `2022.3.13f1`. Feel free to submit the manifests and solve your issue on your own!
