### ISSUE TITLE
[Package Request]: Cinebench R24

### ISSUE THREAD

**Issue by tabtomi8** [microsoft/winget-pkgs#127112]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.maxon.net/en/downloads/cinebench-2024-downloads
Publisher: Maxon
Package Name: Cinebench R24
Description:  Cinebench is a tool to compare CPU and graphics performance across various systems and platforms 
Package Version: 2024.1.0
Installer URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip

**Comment by Dragon1573** [comment]
Inspected by Thunder Download, the installer file has a huge size up to 1.31 Gigabytes. Is it acceptable? I see there's a `1GB+` label for classifing these packages.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/750e806a-909f-4528-9bff-54ec520f28c5)

**Comment by Dragon1573** [comment]
@tabtomi8 - Does the _Terms of Service_ of Cinebench 2024 allow packages to be delivered by third-party?

I'm trying to create manifests for it on GitHub Codespace via Komac, since I don't have enough bandwidth to download such huge files locally. Komac cannot download the installer file for me and report "HTTP 403 Forbidden".

```text
@Dragon1573 ➜ /workspaces/winget-pkgs (master) $ java -jar ../Komac-1.11.0-all.jar new
Please enter your GitHub personal access token:

[Required] Enter the package identifier
Example: Microsoft.Excel
Package Identifier: Maxon.Cinebench

[Required] Enter the package version
Example: 7.46.3
Package Version: 2024.1.0

[Required] Enter the Download URL to the installer
Installer URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip
Unsuccessful Response Code - The server responded with 403 Forbidden
Installer URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_arm64.zip
Unsuccessful Response Code - The server responded with 403 Forbidden
Installer URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip
Unsuccessful Response Code - The server responded with 403 Forbidden
Installer URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_arm64.zip
Unsuccessful Response Code - The server responded with 403 Forbidden
```

**Comment by Dragon1573** [comment]
The download URL requires cookies and `Referer` property for authentication. Unable to submit this package to the repository.

_Originally posted by @Dragon1573 in https://github.com/microsoft/winget-pkgs/issues/127316#issuecomment-1817843764_

-----

Can be closed as not planned, as we are unable to submit it to the repository.
