### ISSUE TITLE
[Update Request]: Microsoft.PowerShell 7.4.0.0

### ISSUE THREAD

**Issue by jrdodds** [microsoft/winget-pkgs#127108]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PowerShell

### Package Version

7.4.0.0

### Please describe the changes you would like to see

There is a new release available - [v7.4.0 Release of PowerShell](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0)

**Comment by mdanish-kh** [comment]
Will be resolved by
- #127003
