### ISSUE TITLE
[Package Issue]: XPDC2RH70K22MN (Discord)

### ISSUE THREAD

**Issue by jrdodds** [microsoft/winget-pkgs#127113]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I have the Windows Discord app installed from [https://discord.com/](https://discord.com/). The Discord app self-updates on launch. The app displays its current version as:

Stable 245648 (758ffd2) 
Host **1.0.9024** x86 (39566) 
Windows 10 64-Bit (10.0.22631)

But `winget upgrade` reports

```
Name                   Id                 Version  Available Source
-------------------------------------------------------------------
Discord                XPDC2RH70K22MN     1.0.9018 1.0.9024  winget
```

and `winget list discord` reports

```
Name    Id             Version  Available Source
------------------------------------------------
Discord XPDC2RH70K22MN 1.0.9018 1.0.9024  winget
```

Winget is incorrectly showing an update from 1.0.9018 to 1.0.9024 when the installed version is already 1.0.9024.

`winget upgrade --id XPDC2RH70K22MN` reports

```
No available upgrade found.
No newer package versions are available from the configured sources.
```

If I re-download and run `DiscordSetup.exe`, the Discord app will no longer be shown as needing an update and `winget list discord` reports

```
Name    Id             Version  Source
---------------------------------------
Discord XPDC2RH70K22MN 1.0.9024 winget
```

It seems that Discord and WinGet don't play well together.

### Steps to reproduce

1. Install Discord with `DiscordSetup.exe` from [https://discord.com/](https://discord.com/).
2. Verify that the app is detected by WinGet.
3. Note the version of Discord.
4. Wait for an update to Discord.
5. Verify the version of Discord has changed.
6. Run `winget upgrade` to see if WinGet sees the updated version but thinks the older version is installed.

### Actual behavior

WinGet incorrectly shows that Discord needs an update, incorrectly shows that Winget is the Source. and can't update Discord.

### Expected behavior

Discord is self-updating and probably shouldn't be shown as updateable by WinGet.

### Environment

```raw
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by BrandonWanHuanSheng** [comment]
This is discord self update issues because it does not modify display version.

**Comment by jrdodds** [comment]
Is there a change that can be made so that WinGet doesn't track Discord or doesn't report Discord in the `upgrade` command?

**Comment by BrandonWanHuanSheng** [comment]
Run winget pin

**Comment by jrdodds** [comment]
`pin` doesn't solve the issue. It's just a work-around.

**Comment by Trenly** [comment]
`winget pin add XPDC2RH70K22MN --blocking` will hide it from `winget upgrade` exactly as you requested.

There is a feature request for fully excluding packages over at winget-cli -
* https://github.com/microsoft/winget-cli/issues/2339

In the meantime, this is an installer issue since Discord's auto-updater doesn't write the new version to registry when updating. The only way to prevent winget from attempting to upgrade the package is with the `pin` command.

**Comment by jrdodds** [comment]
How or why does WinGet decide it is the source?

**Comment by Trenly** [comment]
> How or why does WinGet decide it is the source?

Winget manages all applications which have registered themselves to the computer, regardless of whether they were manually installed or installed using winget. The data the application provides to Windows such as the DisplayName, PackageVersion, ProductCode, Publisher, etc. is used to correlate installed applications to available applications from either the msstore, this repository, or any custom sources you have added.

**Comment by jrdodds** [comment]
WinGet says `winget` is the source for Discord which seems to be incorrect since it can't properly track Discord's version.

WinGet doesn't show `winget` to be the source for `dotPeek Portable`, `Joplin 2.12.19`, `Microsoft SQL Server 2019 (64-bit)`, and `My Dell`. These examples are also not from the Microsoft Store.

How or why does WinGet decide it is the source for Discord and not these other examples?

**Comment by stephengillie** [comment]
This is an unusual situation, as we have `Discord.Discord` in our manifests also, and at the `1.0.9024` version:
```PowerShell
PS C:\ManVal> Find-WinGetPackage discord

Name                    Id                                      Version
----                    --                                      -------
Discord                 Discord.Discord                         1.0.9024
```

The ID `XPDC2RH70K22MN ` doesn't show up in the above search for me, but does if I search for it:
```PowerShell
PS C:\ManVal> Find-WinGetPackage XPDC2RH70K22MN

Name    Id             Version Source
----    --             ------- ------
Discord XPDC2RH70K22MN Unknown msstore
```
And with the `MSStore` source.

**Comment by jrdodds** [comment]
hmm. I had installed Discord with an installer downloaded from the discord website and not from the store.

I uninstalled Discord and then re-installed with `winget install --id discord.discord`. I'll see what happens when Discord next updates.

**Comment by Trenly** [comment]
It also gets even more confusing because (iirc) msstore uses winget to distribute some win32 apps

**Comment by BrandonWanHuanSheng** [comment]
I also reported to discord.
https://support.discord.com/hc/en-us/requests/41185419.
Only me just available to see the request only.
