### ISSUE TITLE
[Package Request]: Microsoft Teams (work or school)

### ISSUE THREAD

**Issue by hamnarauf** [microsoft/winget-pkgs#127275]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:
Publisher:
Package Name:
Description:
Package Version:
Installer URL:

**Comment by Trenly** [comment]
@hamnarauf - Teams already exists in the winget source as `winget install Microsoft.Teams` and in the msstore source

If you need a different installer, please include the URL with your request
