### ISSUE TITLE
[Package Issue]: SumatraPDF.SumatraPDF

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-pkgs#127265]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

executable not added to PATH

### Steps to reproduce

Install SumatraPDF by:

```
winget install SumatraPDF.SumatraPDF
```

restart terminal, run `sumatrapdf` or `sumatrapdf.exe`

### Actual behavior

Terminal reports command cannot be find.

### Expected behavior

The program should be able to start from terminal (needed for LaTeX compilation)

### Environment

```raw
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

**Comment by mdanish-kh** [comment]
WinGet simply downloads the installer and executes it with some [args specified in the manifest](https://github.com/microsoft/winget-pkgs/blob/e6dd04194fe9f73b7ca2d516f1e4c8feea62db16/manifests/s/SumatraPDF/SumatraPDF/3.5/SumatraPDF.SumatraPDF.installer.yaml#L9-L13) to ensure an unattended install. Unless the package is a portable/loose binary, it is up to the installer to write itself to the PATH variable. Is there a switch that can be passed to the installer to enable it to write itself to the PATH? If yes, then we can include that in its manifest.

- Related to https://github.com/microsoft/winget-cli/issues/549

**Comment by xarthurx** [comment]
Thanks for the quick reply.
So whether the program is installed under `~\AppData\Local` or `~\AppData\Local\Program` is also determined by the program installer, not winget?

I find it a bit confusing that some of the program are installed into the latter, and it seems (might be wrong) I can access their executives through `cmd`.

**Comment by mdanish-kh** [comment]
> Thanks for the quick reply. So whether the program is installed under `~\AppData\Local` or `~\AppData\Local\Program` is also determined by the program installer, not winget?

Yes. 

However some installers (like SumatraPDF) support passing install locations from the command line. We specify that metadata in the manifest that allows WinGet to take advantage of that and allow users to pass in a custom location using the `--location` switch. i.e., `winget install SumatraPDF --location <InstallLocation>`.
