### ISSUE TITLE
[Package Issue]: Amazon.SAM-CLI

### ISSUE THREAD

**Issue by sehra** [microsoft/winget-pkgs#127319]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Always downloads and attempts to install latest version. Likely that the v at start of v1.98.0 is breaking.

### Steps to reproduce

1. winget install Amazon.SAM-CLI
2. winget upgrade

### Actual behavior

Installed version always reported as "> v1.98.0", attempting to upgrade to same version.

### Expected behavior

Installed version should be recognized.

### Environment

```raw
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3693
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by stephengillie** [comment]
* https://github.com/microsoft/winget-cli/issues/2394

**Comment by snebjorn** [comment]
The `Amazon.SAM-CLI` package is broken and have been for a while now.

```
$ winget upgrade
Name                                             Id                            Version          Available        Source
-----------------------------------------------------------------------------------------------------------------------
AWS SAM Command Line Interface                   Amazon.SAM-CLI                > v1.98.0        1.105.0          winget

$ sam --version
SAM CLI, version 1.108.0
```

As of writing the actual available version is 1.109.0. Not sure if the package authors abandoned it.

Using a version range (> v1.98.0) as the installed version is rather pointless information. It conveys little more information than a "Is it installed: yes / no" flag.

Bottom line:
`Amazon.SAM-CLI` is unusable at the moment. Please send help 🛩️

**Comment by mdanish-kh** [comment]
@snebjorn @sehra This should be resolved now through the above linked PRs? Could you kindly confirm?

**Comment by snebjorn** [comment]
@mdanish-kh it appears to work now. Thank you! ❤️ 

I updated manually to 1.109.0 so can't tell if 100% works. But `winget upgrade` doesn't list Amazon.SAM-CLI so I think it works.

**Comment by sehra** [comment]
> @snebjorn @sehra This should be resolved now through the above linked PRs? Could you kindly confirm?

Working as expected now.
