### ISSUE TITLE
[Update Request]: MapTiler.MapTilerDesktop

### ISSUE THREAD

**Issue by kudlav** [microsoft/winget-pkgs#127874]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MapTiler.MapTilerDesktop

### Package Version

13.0

### Please describe the changes you would like to see

PackageName: MapTiler Engine
Download Page Url: https://maptiler.download/engine/maptiler-engine-13.0-app-win-x64-setup.exe

**Comment by Dragon1573** [comment]
I'm taking this issue 😄
