### ISSUE TITLE
[Update Request]: Internet Download Manager 6.42.1

### ISSUE THREAD

**Issue by FadeMind** [microsoft/winget-pkgs#127921]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Tonec.InternetDownloadManager

### Package Version

6.42.1

### Please describe the changes you would like to see

Valid version `6.42.1`   
Winget report version: `6. 42. 1. 1`
![20231124-1700800769](https://github.com/microsoft/winget-pkgs/assets/9846948/b71e0e4b-13ea-47c5-918a-8317d0e3fc27)

**Comment by Dragon1573** [comment]
Pull request leading to this issue https://github.com/microsoft/winget-pkgs/pull/127821 .

**Comment by 3xploiton3** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/19517680/7b4298ca-8c57-4ede-87e1-bf4c04bb932d)

**Comment by hexerus** [comment]
![Screenshot 2023-11-28 095900](https://github.com/microsoft/winget-pkgs/assets/47005060/dbe9f921-d78a-42df-8ea6-250ae2dfad97)
Have the same issue.

**Comment by FadeMind** [comment]
Still exists 
![20231128-1701156383](https://github.com/microsoft/winget-pkgs/assets/9846948/0a377417-75b8-4e3b-b396-726d09fbff71)

**Comment by Dragon1573** [comment]
I'm working on it @hexerus @FadeMind .

- https://github.com/microsoft/winget-pkgs/issues/128340
