### ISSUE TITLE
The bot is attempting to autoupdate a manifest (x64+x86) but only for one installer

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#12800]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
The bot attempted to replace the PowerBI manifest https://github.com/microsoft/winget-pkgs/pull/12647 earlier, but only included the x86 version despite it also including a x64 version which was updated to the new version (at the source) simultaneously.

# Steps to reproduce

1. Submit manifest with with x64 and x86 arch installers with links that allow it to be updated
2. Bot attempts to autoupdate it
3. Bot picks only one type to update and deletes the other

# Expected behavior

Both architecture urls are checked and info is updated for both

# Actual behavior
 Only one architecture is selected for autoupdate, and the other is deleted.

**Comment by denelon** [comment]
@superusercode we've made several improvements since this issue was reported. Can you confirm if this is still happening?
