### ISSUE TITLE
What is that- [ ] [New package: windows.PCSX2 version 1.6.0 | winget-pkgs#127891](https://github.com/microsoft/winget-pkgs/pull/127891) - [ ] [[Package Request]: Anytype | winget-pkgs#127358](https://github.com/microsoft/winget-pkgs/issues/127358)

### ISSUE THREAD

**Issue by fwadnjar** [microsoft/winget-pkgs#128062]
What is that

_Originally posted by @BrandonWanHuanSheng in https://github.com/microsoft/winget-pkgs/issues/128061#issuecomment-1826364523_

**Comment by BrandonWanHuanSheng** [comment]
I am not a robots, sometimes the connection slow down which is my home network. When I change to another web page during high usage, No Description Provided after that the task need to wait for a long time to load.
@fwadnjar Can you closed this as not planned?

**Comment by Trenly** [comment]
Close with reason: No information provided in issue;
