### ISSUE TITLE
[Package Issue]: Ubisoft.Connect installation fails with "Installer hash does not match"

### ISSUE THREAD

**Issue by lackovic** [microsoft/winget-pkgs#128282]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installation of Ubisoft.Connect fails with `Installer hash does not match.` error.

### Steps to reproduce

Run `winget install --id Ubisoft.Connect` in an elavated shell.

### Actual behavior

The installation fails with:
```powershell
Found Ubisoft Connect [Ubisoft.Connect] Version 147.0.10965
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://static3.cdn.ubi.com/orbit/launcher_installer/UbisoftConnectInstaller.exe
  ██████████████████████████████   224 MB /  224 MB
Installer hash does not match; this cannot be overridden when running as admin
```

### Expected behavior

The installation succeeds.

### Environment

```raw
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

### Screenshots and Logs

[WinGet-2023-11-27-22-21-11.727.log](https://github.com/microsoft/winget-pkgs/files/13479883/WinGet-2023-11-27-22-21-11.727.log)

**Comment by calvinwonghk** [comment]
same issues is happening again.   PS C:\Users\xxxxxx> winget install -e --id Ubisoft.Connect
Found Ubisoft Connect [Ubisoft.Connect] Version 163.1.0.12222
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://static3.cdn.ubi.com/orbit/launcher_installer/UbisoftConnectInstaller.exe
  ██████████████████████████████   228 MB /  228 MB
Installer hash does not match.

**Comment by Dragon1573** [comment]
> Same issues is happening again.

> [!IMPORTANT]
> 
> This package is using a "vanity URL", which always points to the current latest version. It will keep facing <https://github.com/microsoft/winget-pkgs/labels/Error-Hash-Mismatch> forever, once a new version is released.
> 
> Feel free to create another issue asking for package updates. ❤
