### ISSUE TITLE
[Package Issue]: Microsoft.UI.Xaml.2.8

### ISSUE THREAD

**Issue by otto-liljalaakso-nt** [microsoft/winget-pkgs#128252]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget considers `Microsoft.UI.Xaml.2.8` not installed, then fails to install it due to "A higher version of this application is already installed."

### Steps to reproduce

```
> winget list Microsoft.UI.Xaml.2.8
> winget install Microsoft.UI.Xaml.2.8
```

### Actual behavior

Not installed according to `list`:
```
> winget list Microsoft.UI.Xaml.2.8
No installed package found matching input criteria.
```

But `install` fails due to higher version being installed:
```
> winget install Microsoft.UI.Xaml.2.8
Found Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ████████████████████████████▌   95%
Installer failed with exit code: 0x80073d06 : Pakettia ei voitu asentaa, koska t�m�n paketin uudempi versio on jo asennettuna.
A higher version of this application is already installed.
```

### Expected behavior

Finds the version that has already been installed using some other method than WinGet, does not attempt to update.

### Environment

```raw
Windows Package Manager v1.6.3133
Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

**Comment by Trenly** [comment]
@denelon - Seems like this is a CLI issue, especially since `winget list` isn't finding that it is installed

**Comment by DHowett** [comment]
I am just making stuff up, but... could this be because the installer YAML doesn't have the `PackageFamilyName` at the top level?

https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/UI/Xaml/2/8/8.2306.22001.0/Microsoft.UI.Xaml.2.8.installer.yaml

WindowsTerminal _does_ have the `PackageFamilyName` at the top level.

**Comment by Trenly** [comment]
> I am just making stuff up, but... could this be because the installer YAML doesn't have the `PackageFamilyName` at the top level? Could this interfere with package identity correlation?
> 
> https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/UI/Xaml/2/8/8.2306.22001.0/Microsoft.UI.Xaml.2.8.installer.yaml
> 
> WindowsTerminal _does_ have the `PackageFamilyName` at the top level.

I doubt it; The installer level will override anything at the top level

**Comment by yao-msft** [comment]
It is most likely the package is recognized as system app and get ignored [here](https://github.com/microsoft/winget-cli/blob/113debcc0f3fe968c58b60162f6b957b832c7498/src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp#L94)

I checked the package is signed with WP Store-1st party app (1.3.6.1.4.1.311.76.5.100)

**Comment by Trenly** [comment]
> It is most likely the package is recognized as system app and get ignored [here](https://github.com/microsoft/winget-cli/blob/113debcc0f3fe968c58b60162f6b957b832c7498/src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp#L94)
> 
> I checked the package is signed with WP Store-1st party app (1.3.6.1.4.1.311.76.5.100)

So the flow may need to be udated to not ignore system apps during install / list, but should ignore them for uninstall?

**Comment by yao-msft** [comment]
Correction: @JohnMcPMS just corrected me that the actual [code](https://github.com/microsoft/winget-cli/blob/113debcc0f3fe968c58b60162f6b957b832c7498/src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp#L77) filtering out framework packages is the cause. We may need to revisit this to include more package types.
