### ISSUE TITLE
[Package Issue]: TechPowerUp.GPU-Z

### ISSUE THREAD

**Issue by axieum** [microsoft/winget-pkgs#128537]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The `TechPowerUp.GPU-Z` package installer download URL is no longer valid.

### Steps to reproduce

```sh
$ winget install --id TechPowerUp.GPU-Z
Found TechPowerUp GPU-Z [TechPowerUp.GPU-Z] Version 2.55.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://us2-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : unknown error
```

### Actual behavior

```sh
$ winget install --id TechPowerUp.GPU-Z
Found TechPowerUp GPU-Z [TechPowerUp.GPU-Z] Version 2.55.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://us2-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : unknown error
```

### Expected behavior

To download correctly from the actual download URL.

`https://us1-dl.techpowerup.com/files/3UAXiZS...jCma6R9zA/170...67/GPU-Z.2.55.0.exe`

Note, the URL parts (containing `...`) appear to be unique to the download. So I wonder if it is even possible to get a predictable download URL now?

### Environment

```raw
$ winget --info
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1992
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
```


### Screenshots and Logs

_No response_

**Comment by Dragon1573** [comment]
Download URL presented in manifest files responses `HTTP 404 Not Found`.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/b10b6f0d-63e0-48d1-9af4-5198fa90518d)

The generated URL is got from a redirection by making a POST request of [Server List](https://www.techpowerup.com/download/techpowerup-gpu-z/). As `winget.exe` can only make GET request to download server and follow redirections, we might not able to fix this problem.

<details><summary>Screenshots</summary>

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/e1427156-8052-4408-a827-3da4f3c53caa)

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a6142261-3052-4775-ae93-37c4c052d761)

</details>

**Comment by MagicAndre1981** [comment]
because 2.56 was released:

> **v2.56.0 (November 29th, 2023)**
> Added support to list and detect versions of NVIDIA Frame Generation and Ray Reconstruction DLLs in Advanced -> NVIDIA DLSS
> Added "Open Folder" context-menu option in DLSS version scanner
> Added sensor for NVIDIA Crossbar clock (default off)
> Fixed Intel Arc BIOS version reporting
> Fixed release date for Intel Arc A580
> Added support for NVIDIA RTX 5000 Ada, RTX 4500 Ada, RTX 4000 Ada, new RTX 2050 Mobile variant, L40S, H800 PCIe
> Added support for AMD Radeon RX 7900GRE, RX 6750 GRE, Pro W7700, Pro V620 MxGPU
> Added support for Intel Arc A570M, A530M, GPU Flex 170

**Comment by Dragon1573** [comment]
> Because v2.56.0 was released.

NO, this is NOT the reason.

Including latest v2.56.0, all releases are using dynamic, encrypted, auto-generated download URL. This is not a static vanity URL which always point to the latest version.

**Comment by R-Adrian** [comment]
it looks like TechPowerUP wants to prevent third-party download tools / package manager apps from linking to official GPU-Z download sources.

i think that means WinGet should permanenly remove GPU-Z from the package manifests, like it did with FileZilla Client

**Comment by mdanish-kh** [comment]
As for the author facing this issue through installing with WinGet, it may be possible that the URL is blocked in your region / the mirror us2 is not working for you.

Can you check whether another mirror works for you? I'll add the steps below to check this

1. Clone the winget-pkgs repository (`git clone https://github.com/microsoft/winget-pkgs`)
2. Navigate to TechPowerUp.GPU-Z version 2.55.0 directory (`cd manifests/t/TechPowerUp/GPU-Z/2.55.0`)
3. Inside the installer file (TechPowerUp.GPU-Z.installer.yaml), change InstallerUrl from the us2 mirror to `https://us1-dl.techpowerup.com/files/GPU-Z.2.55.0.exe`
4. Install the manifest locally with `winget install --manifest <path_to_manifest_folder>` i.e., `winget install --manifest manifests/t/TechPowerUp/GPU-Z/2.55.0` (you will need to enable installing local manifest files setting if not enabled, winget will prompt and show you the command for if it's disabled)

See if this URL works and installs the package for you

**Comment by Dragon1573** [comment]
Manual validated first 6 server of GPU-Z. All of them are valid and no errors during downloading.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a1d21f58-93b2-4636-98c9-38cf6f6f5cb5)

<details><summary>Console logs</summary>

```text
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://sg1-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> sed.exe -i 's/sg1/us3/' .\manifests\t\TechPowerUp\GPU-Z\2.55.0\TechPowerUp.GPU-Z.installer.yaml
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://us3-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> sed.exe -i 's/us3/de1/' .\manifests\t\TechPowerUp\GPU-Z\2.55.0\TechPowerUp.GPU-Z.installer.yaml
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://de1-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> sed.exe -i 's/de1/nl2/' .\manifests\t\TechPowerUp\GPU-Z\2.55.0\TechPowerUp.GPU-Z.installer.yaml
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://nl2-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> sed.exe -i 's/nl2/uk1/' .\manifests\t\TechPowerUp\GPU-Z\2.55.0\TechPowerUp.GPU-Z.installer.yaml
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://uk1-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> sed.exe -i 's/uk1/us7/' .\manifests\t\TechPowerUp\GPU-Z\2.55.0\TechPowerUp.GPU-Z.installer.yaml
D:\Workloads\winget-pkgs [master ≡ +0 ~1 -0 !]> winget download -m .\manifests\t\TechPowerUp\GPU-Z\2.55.0\
已找到 TechPowerUp GPU-Z [TechPowerUp.GPU-Z] 版本 2.55.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://us7-dl.techpowerup.com/files/GPU-Z.2.55.0.exe
  ██████████████████████████████  9.06 MB / 9.06 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TechPowerUp.GPU-Z_2.55.0\TechPowerUp GPU-Z_2.55.0_Machine_X86_exe_en-US.exe
```

</details>

**Comment by axieum** [comment]
It appears that `us2-dl.techpowerup.com` is back up and working for me again now.

**Comment by BrandonWanHuanSheng** [comment]
I already know all the server seem online. It seem i don't know which id belong to those mirror.
[19.log](https://github.com/microsoft/winget-pkgs/files/13523055/19.log)
[12.log](https://github.com/microsoft/winget-pkgs/files/13523056/12.log)
[8.log](https://github.com/microsoft/winget-pkgs/files/13523057/8.log)
[4.log](https://github.com/microsoft/winget-pkgs/files/13523058/4.log)
[11.log](https://github.com/microsoft/winget-pkgs/files/13523059/11.log)
[5.log](https://github.com/microsoft/winget-pkgs/files/13523060/5.log)
[16.log](https://github.com/microsoft/winget-pkgs/files/13523061/16.log)
[20.log](https://github.com/microsoft/winget-pkgs/files/13523062/20.log)
[14.log](https://github.com/microsoft/winget-pkgs/files/13523063/14.log)
[15.log](https://github.com/microsoft/winget-pkgs/files/13523064/15.log)

**Comment by mdanish-kh** [comment]
Close with reason: Issue now resolved, seemed to be a temporary server issue;

**Comment by W1zzardTPU** [comment]
Not sure if this is the right place, but we now support http://closest-dl.techpowerup.com, which will 302 to the closest mirror, using the exact URL provided. This endpoint is also infrastructure changes aware, so it won't redirect to a down or removed mirror.

For winget all that's needed is to change the download URLs from a specific host to closest-dl

```
curl http://closest-dl.techpowerup.com/files/GPU-Z.2.69.0.exe -I
HTTP/1.1 302 Found
server: nginx
date: Thu, 28 May 2026 07:26:48 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'self'
location: http://de1-dl.techpowerup.com/files/GPU-Z.2.69.0.exe

curl http://closest-dl.techpowerup.com/foo-bar-baz -I
HTTP/1.1 302 Found
server: nginx
date: Thu, 28 May 2026 07:26:57 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'self'
location: http://de1-dl.techpowerup.com/foo-bar-baz
```

**Comment by mdanish-kh** [comment]
@W1zzardTPU Thank you. I just made a PR for the latest version to use `closest-dl`. The intent is that any community member updating the package in the future would hopefully refer to the latest manifest, and use the same subdomain. If you're interested in automating the publishing yourself, you may want a look at [winget-create](https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline)

**Comment by W1zzardTPU** [comment]
Thanks! I think we also have a bunch of other packages that should be updated. NVCleanstall? Throttlestop?

**Comment by mdanish-kh** [comment]
@W1zzardTPU Opened PRs for the latest manifests of all packages under [TechPowerUp/](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TechPowerUp)

- https://github.com/microsoft/winget-pkgs/pull/380712
- https://github.com/microsoft/winget-pkgs/pull/380726
- https://github.com/microsoft/winget-pkgs/pull/380728
