### ISSUE TITLE
[Update Request]: How to run wingetbot for Automatic submission of update for Vanity URL

### ISSUE THREAD

**Issue by drshtmstry** [microsoft/winget-pkgs#128759]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

WHONET.2023

### Package Version

23.11.30

### Please describe the changes you would like to see

I don't want to manually submit pull request. Package has vanity URL and new version is available which leads to hash mismatch.
How to configure wingetbot for automatic submitting pull request when this happens?

**Comment by Dragon1573** [comment]
@drshtmstry - @wingetbot IS working on this issue. Please be patient as moderators (sorry, I'm not) should manually validate and then approve the pull request.

- Resolving by https://github.com/microsoft/winget-pkgs/pull/128724

**Comment by drshtmstry** [comment]
> @drshtmstry - @wingetbot IS working on this issue. Please be patient as moderators (sorry, I'm not) should manually validate and then approve the pull request.
> 
> * Resolving by [Automatic update of WHONET.2023 from 23.11.27 to 23.11.30 #128724](https://github.com/microsoft/winget-pkgs/pull/128724)

Sorry about that.
I didn't see that PR was created.
I thought I need to configure wingetbot manually for updating package.
