### ISSUE TITLE
[Update Request]: FreeCAD.FreeCAD 0.21.2

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#128859]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

FreeCAD.FreeCAD

### Package Version

0.21.2

### Please describe the changes you would like to see

https://github.com/FreeCAD/FreeCAD/releases/tag/untagged-0f0a725fb4db2dfdd95e

**Comment by Dragon1573** [comment]
@luzpaz - Could you please verify if it's a valid release? I find HTTP 404 on [your provided URL](https://github.com/FreeCAD/FreeCAD/releases/tag/untagged-0f0a725fb4db2dfdd95e).

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/058b6b91-3cff-48db-a0db-838c698557f4)

**Comment by Dragon1573** [comment]
Tag [`v0.21.2`](https://github.com/FreeCAD/FreeCAD/releases/tag/0.21.2) does exists, but it does not associate with any release and no assets are attached to it.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/7081b1e2-6f16-4325-8070-e7f243635d81)

In the [releases](https://github.com/FreeCAD/FreeCAD/releases) page, the latest release is [`v0.21.1`](https://github.com/FreeCAD/FreeCAD/releases/tag/0.21.1)

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/594f9024-bd2e-4b22-ab95-34ad03b536b8)

**Comment by luzpaz** [comment]
Team hasn't officially released it due to macOS signing issue. But other non macOS package repos have picked it up.

**Comment by luzpaz** [comment]
[![Packaging status](https://repology.org/badge/vertical-allrepos/freecad.svg?columns=3)](https://repology.org/project/freecad/versions)

**Comment by luzpaz** [comment]
Closing until upstream fixes the issue.
