### ISSUE TITLE
[Package Request]: micromamba

### ISSUE THREAD

**Issue by lucasfcnunes** [microsoft/winget-pkgs#129022]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/mamba-org/micromamba-releases or https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html
Publisher: mamba-org
Package Name: micromamba
Description: micromamba is a tiny version of the mamba package manager. It is a statically linked C++ executable with a separate command line interface. It does not need a base environment and does not come with a default version of Python.
Package Version: 1.5.3
Installer URL: https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64

**Comment by Dragon1573** [comment]
It seems Windows cannot run an executable without file extension. `winget.exe` have to add `.exe` suffix for the downloaded file.

According to [official installation guide](https://github.com/mamba-org/micromamba-releases/tree/main?tab=readme-ov-file#windows), we should run an "installer script" which is not supported by `winget.exe`.

**Comment by Dragon1573** [comment]
There's a functional `Library/bin/micromamba.exe` in [`micromamba-win-64.tar.bz2`](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64.tar.bz2), which is not supported by `winget.exe` either.

**Comment by BrandonWanHuanSheng** [comment]
I think that winget can use this link to download. https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64
If the help appear after adding exe by winget. 
So the command line supposed to micromamba-win-64.exe /?
micromamba-win-64.exe /help

**Comment by Dragon1573** [comment]
@BrandonWanHuanSheng - NO. The download URL you provided is a standalone portable executable file.

```text
09:58:25 ~ $ file ~/storage/downloads/micromamba-win-64.zip
/data/data/com.termux/files/home/storage/downloads/micromamba-win-64.zip: PE32+ executable (console) x86-64, for MS Windows, 6 sections
```

`winget.exe` can't rename them file and add `.exe` suffix for it. :disappointed:

**Comment by BrandonWanHuanSheng** [comment]
The type could be portable. Because it say PE32 executable console.

**Comment by Dragon1573** [comment]
Okay ...

It seems the manifest is valid on my Windows Sandbox. I'll submit it 😄

**Comment by lucasfcnunes** [comment]
@BrandonWanHuanSheng @Dragon1573 

About the missing `.exe`: mamba-org/micromamba-releases#24.
I knew that it could be a problem but @Dragon1573 made it work anyways 🤣. Thanks!
In future releases the direct link may have the `.exe` explicitly.

**Comment by Dragon1573** [comment]
> I knew that it could be a problem but @Dragon1573 made it work anyways 🤣. Thanks!

For portable executables, `winget.exe` will simply extract the compressed archive to some folder and create a symlink to the target executable in another folder. The symlink always contains an `*.exe` extension.

**Comment by BrandonWanHuanSheng** [comment]
Windows always give a some hint by using command prompt if the file does not have extension but can’t use explorer because they have no default association. If you open the file by using explorer, you might see what do you want to do with this file? The explorer just only work when the extension was set.

**Comment by BrandonWanHuanSheng** [comment]
> There's a functional `Library/bin/micromamba.exe` in [`micromamba-win-64.tar.bz2`](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64.tar.bz2), which is not supported by `winget.exe` either.


That one could be docker. Because docker sometimes use tar or bz2

**Comment by BrandonWanHuanSheng** [comment]
It seem there is 2 more release

**Comment by BrandonWanHuanSheng** [comment]
It seem there is 2 more release.

### Tasklist

**Comment by BrandonWanHuanSheng** [comment]
```[tasklist]
### Tasks
```

**Comment by BrandonWanHuanSheng** [comment]
@Dragon1573 it seem there are processing the same change but different version because the author rolled out the update on 14 December 2023. So, it will not interface my pull request.

**Comment by BrandonWanHuanSheng** [comment]
Actually, my pull request fall into validation-completed but don't know why Dragon1573 pull request contains validation executable-error.

**Comment by Dragon1573** [comment]
> It seem there are processing the same change but different version because the author rolled out the update on 14 December 2023. So, it will not interface my pull request and your pull request.

Okay, I'll close my pull request without beging merged. 😃

-----

### Out of topic things

@BrandonWanHuanSheng - Could you please explain how you can add labels in your comments and make them looks like a label? What is the markdown syntax of it?

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/8839ad5c-2b89-4985-aa3e-71db79ee3310)

**Comment by rakleed** [comment]
> ### Out of topic things
> @BrandonWanHuanSheng - Could you please explain how you can add labels in your comments and make them looks like a label? What is the markdown syntax of it?
> 
> ![image](https://private-user-images.githubusercontent.com/49941141/290977833-8839ad5c-2b89-4985-aa3e-71db79ee3310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTM5NjEsIm5iZiI6MTcwMjcxMzY2MSwicGF0aCI6Ii80OTk0MTE0MS8yOTA5Nzc4MzMtODgzOWFkNWMtMmI4OS00OTg1LWFhM2UtNzFkYjc5ZWUzMzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA4MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZmNjNjQ5ZTBiMzkwY2YxMjEzOTc2OTM1ZTZlZDcwYTk1NTE0ZGUyNGRkMTU5MmUxZWM5ZDZlYzRlMzkwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PrF8lrvAjLorUQIu_IHjXXpKX23ycOXf2S9I2PrOYiw)

@Dragon1573 https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#labels

**Comment by BrandonWanHuanSheng** [comment]
Oops! I forgot to link that issue on my pr.

**Comment by lucasfcnunes** [comment]
Solved by https://github.com/microsoft/winget-pkgs/pull/130585
