### ISSUE TITLE
[Package Issue]:  Jackaudio.JACK2 has superflous 'v' prepending version number and should be renamed

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#129013]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Per [repology jack2](https://repology.org/project/jack-audio-connection-kit/versions) is showing a superfluous 'v' before the version name
![Screenshot_20231203_062820](https://github.com/microsoft/winget-pkgs/assets/4140247/c47a9919-0507-4d65-93cc-f3fcf24f14e0)

This is how the package is listed in winget-pkgs
![Screenshot_20231203_062155](https://github.com/microsoft/winget-pkgs/assets/4140247/f3c19db8-6791-468e-a2a4-7b97a2ee22bc)

**Note:** this seems like an anomaly in winget-pkgs. Usually version numbers don't have a 'v' prepended.

This has been reported to repology

![Screenshot_20231203_062552](https://github.com/microsoft/winget-pkgs/assets/4140247/ff022729-d960-4b90-86bb-7cd27c72f1d5)

Per repology's answer, this needs to be corrected in this repo 

 
### Steps to reproduce

See above

### Actual behavior

See above

### Expected behavior

See above

### Environment

```raw
n/a
```

### Screenshots and Logs

See above

**Comment by stephengillie** [comment]
* https://github.com/microsoft/winget-cli/issues/2394

**Comment by luzpaz** [comment]
@stephengillie @Trenly  looks the preamble issues has been resolved.  Can you take a stab at this issue now?

**Comment by luzpaz** [comment]
soft bump

**Comment by Trenly** [comment]
It has been resolved in 1.9, but there could still be a significant portion of users who have not updated to the latest version of WinGet. The renames should wait until after the 1.9 manifest support is released into the pipelines, as that only happens after a majority of users have moved to the newer versions of WinGet

**Comment by luzpaz** [comment]
> The renames should wait until after the 1.9 manifest support is released into the pipelines, as that only happens after a majority of users have moved to the newer versions of WinGet

Is there a way to determine when this moment arrives ?

**Comment by Trenly** [comment]
> Is there a way to determine when this moment arrives ?

Yes, this issue will close when 1.9 manifests are supported in the pipelines -
* #186398
