### ISSUE TITLE
[Package Request]: Scilab-2024.0.0

### ISSUE THREAD

**Issue by rdaval** [microsoft/winget-pkgs#129130]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.scilab.org/download/scilab-2024.0.0
Publisher: Scilab Entreprises
Package Name: Scilab-2024.0.0
Description: Scilab is free and open source software for numerical computation providing a powerful computing environment for engineering and scientific applications.
Package Version: 2024.0.0
Installer URL: https://www.scilab.org/download/2024.0.0/scilab-2024.0.0.bin.x64.exe

**Comment by Dragon1573** [comment]
@rdaval - I'm working on this issue 😄

This is not a new package identifier but a new version. Previous versions of this package is already presented as identifier `Scilab.Scilab`. Please check them out ~ ❤️

**Comment by rdaval** [comment]
Merci pour votre réponse, mais dans ce cas comment fait on pour avoir la mise à jour du package

**Comment by Dragon1573** [comment]
Most of the moderators are volunteers, they need times to manually validate the manifest. Please be patient waiting their approval. After the pull request is merged and Publish Pipelines successfully executed, then you can upgrade the package with `winget upgrade`.

If you can't wait for the new version, you can simply download (or copy contents of) 3 YAML files from my pull request and `winget upgrade --manifest <path>` to upgrade the package with local manifest.

> Note: English is recommended in this repository. You can translate your comments with online translators (such as Google Translate) BEFORE posting them. It's a pleasure for other contributors.
