### ISSUE TITLE
[Package Issue]: Docker.DockerDesktop

### ISSUE THREAD

**Issue by f-cramer** [microsoft/winget-pkgs#129245]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The version was updated to 4.26.0.130397 by wingetbot, but when installed Docker Desktop itself announces its version as 4.26.0 (missing the 130394 suffix). Because of this, winget lists an available update for Docker Desktop when in reality there is none.

### Steps to reproduce

Update Docker Desktop to version 4.26.0
Run `winget update`

### Actual behavior

Winget lists an update for Docker.DockerDesktop from current version 4.26.0 to version 4.26.130397
Running `winget update Docker.DockerDesktop` fails with an error ("Eine andere Version dieser Anwendung ist bereits installiert." in german, roughly "another version is already installed" in english)

### Expected behavior

There should be not update available for Docker.DockerDesktop

### Environment

```raw
Windows-Paket-Manager v1.6.3133
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.2715
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3133.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               D:\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Aktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by Trenly** [comment]
@stephengillie - #129216 seems like your manual validation pipeline may have missed the version discrepancy

**Comment by stephengillie** [comment]
> @ stephengillie - #129216 seems like your manual validation pipeline may have missed the version discrepancy

@Trenly "missed" due to "don't have a good way to detect" the discrepancy. 
- Extra spaces in the semantic version parameters, such as `4.5 .5 .349`, are easy to detect.
- But it's less easy to tell when a developer has intentionally added a revision version to their semantic version, without installing and verifying. 
  - It feels like 90% of the time, this situation is like this, where erroneous data is added.
  - And the other 10% of the time, necessary data has been omitted. 
- I'll add a check that fires if the new semantic version has more parameters than the previous. 
  - Feel free to suggest better ways to check this, and/or other checks to perform.
