### ISSUE TITLE
Spotify installer fail with error: "Installer failed with exit code: 3221226505"

### ISSUE THREAD

**Issue by TheRndCoder** [microsoft/winget-pkgs#1293]
# Brief description of your issue
When running 'winget install spotify', winget is unable to verify the hash, even if I let winget to continue and try to install it, I'll get the following error: 'Installer failed with exit code: 3221226505'

# Steps to reproduce

Open Windows Terminal, then run 'winget install spotify', the app will download, fail to verify hash and the installation will fail

# Expected behavior

winget would be able to verify the hash of the app for Spotify and then properly install it with or without verifying it

# Actual behavior

![image](https://user-images.githubusercontent.com/25141697/82554756-c76a1400-9b23-11ea-814c-d95359ad7ed0.png)

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
Not applicable
```

**Comment by SoftCreatR** [comment]
@denelon This also happens when using the direct installer:

```
Id: Spotify.Spotify
Version: 1.1.34.694
Name: Spotify
Publisher: Spotify
License: Copyright © 2012 Spotify AB. All rights reserved.
LicenseUrl: https://www.spotify.com/us/legal/end-user-agreement/
AppMoniker: spotify
Description: Spotify music player
Homepage: https://www.spotify.com/
Installers:
  - Arch: x86
    Url: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.34.694.gac68a2b3-15.exe
    Sha256: 35CE7176234B5A050472F00E102FC50AB64AD8E96D53EFF66F30F2217938723D
    InstallerType: exe
    Switches:
        Silent: /Silent
        SilentWithProgress: /Silent
```

**Comment by icenine457** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Is-there-a-version-specific-URL-that-can-be-used-for-Spotify/m-p/4969814#M347

**Comment by bondarenkod** [comment]
the same with PowerToys
```
PS C:\Users\bonda> WinGet install powertoys
Found PowerToys [Microsoft.PowerToys]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/microsoft/PowerToys/releases/download/v0.20.0/PowerToysSetup-0.20.0-x64.exe
  ██████████████████████████████  20.4 MB / 20.4 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 3221226505
```
win 19041.388

**Comment by ehmiiz** [comment]
I get the same with PowerToys as above ^

**Comment by fredinfu** [comment]
> I get the same with PowerToys as above ^
> 
> Edit: Worked fine today!

So you did nothing and just worked that day? I'm having the same problem with PowerToys

`PS C:\Users\user> winget install powertoys
Found PowerToys [Microsoft.PowerToys]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/microsoft/PowerToys/releases/download/v0.21.1/PowerToysSetup-0.21.1-x64.exe
  ██████████████████████████████  20.5 MB / 20.5 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1`

**Comment by denelon** [comment]
I was able to install Spotify, cpu-z, and PowerToys. Have these issue all been resolved?

**Comment by crimsonclyde** [comment]
Still the same for days:

```
winget install spotify
Found Spotify [Spotify.Spotify]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://download.scdn.co/SpotifySetup.exe
  ██████████████████████████████   871 KB /  871 KB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Installer failed with exit code: 3221226505
````

Winget Info
```
winget --info
Windows Package Manager v0.2.2941 Vorschau
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19041.610
Paket: Microsoft.DesktopAppInstaller v1.11.2941.0
```

**Comment by ItzLevvie** [comment]
@crimsonclyde No issues here:
![image](https://user-images.githubusercontent.com/11600822/98450386-54397600-2134-11eb-9487-c5b55eeb81da.png)

**Comment by denelon** [comment]
We now have automation to update installers that point to a vanity URL. I'll leave this issue open for a few more days before closing as resolved.

**Comment by TheRndCoder** [comment]
Hello, I'm still running into the same error code: 

![image](https://user-images.githubusercontent.com/25141697/104595303-08291700-5638-11eb-9db5-7fefcdaaae84.png)

This is the version of Winget I have installed on my machine, I checked the Microsoft Store for updates and there's no updates for the AppInstaller package for me:

```
Windows Package Manager v0.2.3162 Preview
Package: Microsoft.DesktopAppInstaller v1.11.3162.0
```

**Comment by TheRndCoder** [comment]
Update:

I did some troubleshooting, I had to reset the configuration for the AppInstaller app on Settings -> Apps -> AppInstaller -> Advanced Options and finally clicked on Reset, after doing that I tried to install Spotify and it went smooth as butter.

Since it is working fine now I'll close this issue.

**Comment by crimsonclyde** [comment]
@TheRndCoder 
I can confirm!

Did the same but ended up with "Installer Hash mismatch".
But there's a simple fix, just add the "--force" to the end of:

`winget install spotify --force`

and voilà - done. Thx for this hint!
