### ISSUE TITLE
[Package Issue]: Microsoft.AzureCLI 2.55 (32-bit) but installs x64 and give hint, but was already before x64

### ISSUE THREAD

**Issue by pocki** [microsoft/winget-pkgs#129427]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Had Azure CLI x64 version 2.54 installed.
Upgrade the package with `winget upgrade --all`
Winget Package name "Microsoft Azure CLI (32-bit)" is confusing as it upgrades to x64 - which is correct.
Also hint after upgrade to migrate to x64 is confusing as it was and is already x64

### Steps to reproduce

Azure CLI x64 version 2.54 installed
`winget upgrade --all`

### Actual behavior

Wrong Package name, confusing hint about migrate to x64

### Expected behavior

Correct package name and hint only if installed and/or upgraded version is 32-bit on x64 system

### Environment

```raw
Windows-Paket-Manager v1.6.3133
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.3693
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3133.0
```

### Screenshots and Logs

winget upgrade --all --include-unknown
Name                         ID                 Version Verfügbar Quelle
------------------------------------------------------------------------
Microsoft Azure CLI (32-bit) Microsoft.AzureCLI 2.54.0  2.55.0    winget
1 Aktualisierungen verfügbar.

Abhängigkeiten werden installiert:
(1/1) Gefunden Microsoft Azure CLI [Microsoft.AzureCLI] Version 2.55.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://azcliprod.azureedge.net/msi/azure-cli-2.55.0-x64.msi
  ██████████████████████████████  66.8 MB / 66.8 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
Hinweise: Winget installs the 64-bit CLI on 64-bit OS by default now. If you have used the 32-bit CLI before, please follow this guide to migrate to 64-bit version: https://learn.microsoft.com/cli/azure/install-azure-cli-windows#migrate-to-64-bit-azure-cli

**Comment by Exorcism0666** [comment]
@Trenly idk if it's fixed now ?

**Comment by pocki** [comment]
It seems to be fixed.
