### ISSUE TITLE
[Package Request]: Scratch 1.4 Editor

### ISSUE THREAD

**Issue by manOnWebs** [microsoft/winget-pkgs#129950]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [ ] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://scratch.mit.edu/scratch_1.4
Publisher: MIT
Package Name: Scratch 1.4
Description: Scratch 1.4 Offline Editor
Package Version: 1.4.0.0
Installer URL: https://download.scratch.mit.edu/ScratchInstaller1.4.exe

**Comment by Dragon1573** [comment]
Hi @manOnWebs, maybe package `MIT.Scratch1` is what you need. It's already presented in the repository. 😄

```text
PS> winget show -e MIT.Scratch1
已找到 Scratch [MIT.Scratch1]
版本: 1.4.0
发布者: Lifelong Kindergarten Group @ MIT Media Lab
描述: Scratch 1.4
许可证: MIT Licence
安装：
  安装程序类型： msi (zip)
  安装程序区域设置： en-US
  安装程序 URL： https://download.scratch.mit.edu/Scratch1.4.msi.installer.zip
  安装程序 SHA256： be7202251aae062d6e1e096fbe387346bd46992a9190438f62d5e7ae85e12e31
```

**Comment by manOnWebs** [comment]
> Hi @manOnWebs, maybe package `MIT.Scratch1` is what you need. It's already presented in the repository. 😄
> 
> ```
> PS> winget show -e MIT.Scratch1
> 已找到 Scratch [MIT.Scratch1]
> 版本: 1.4.0
> 发布者: Lifelong Kindergarten Group @ MIT Media Lab
> 描述: Scratch 1.4
> 许可证: MIT Licence
> 安装：
>   安装程序类型： msi (zip)
>   安装程序区域设置： en-US
>   安装程序 URL： https://download.scratch.mit.edu/Scratch1.4.msi.installer.zip
>   安装程序 SHA256： be7202251aae062d6e1e096fbe387346bd46992a9190438f62d5e7ae85e12e31
> ```

Oh okay, thanks :)
