### ISSUE TITLE
Add wildcards for commands

### ISSUE THREAD

**Issue by Rorymon** [microsoft/winget-pkgs#1299]
It would be great if we could use wildcards in commands similar to how we can do this in PowerShell with App-V e.g. Unpublish-AppVClientPackage *Visual*

If you could run a winget install **, it could help people to install based on app without necessarily requiring to run a show first to look up the name.

**Comment by MarNicGit** [comment]
@Rorymon doesn't this issue belong to [winget-cli](https://github.com/microsoft/winget-cli) instead?

**Comment by denelon** [comment]
@Rorymon users may `winget install vscode` without having to perform a show. The `show` command just provides some of the metadata from the most recent packages manifest.

**Comment by denelon** [comment]
Users may execute `winget search` to determine which applications match by substring.

**Comment by bvowell1975** [comment]
> Users may execute `winget search` to determine which applications match by substring.

`winget search` is useless 90% of the time and doesn't return any results.  We need wildcard support like pretty much all other CLI commands provide.
