### ISSUE TITLE
It seem like publish pipelines failed.

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#130014]
There is a problem with the publish pipelines. 
![Screenshot_2023-12-11-16-46-37-494_com github android](https://github.com/microsoft/winget-pkgs/assets/118059864/c9e23d9e-1596-4c05-a07a-8c0efbc7cc9e)

**Comment by stephengillie** [comment]
I believe we have identified the issue, and that the resolution is underway.

**Comment by stephengillie** [comment]
Publish pipeline has been successfully publishing for about 90 minutes.
