### ISSUE TITLE
Pull requests won't complete if the source branch has been deleted

### ISSUE THREAD

**Issue by lutzroeder** [microsoft/winget-pkgs#1300]
Deploy scripts using fork, push, pull request, delete fork approach will create a pull request with the original fork being deleted. This is desirable as it causes less friction next time the script.

**Actual:**
These PRs remain open as the branch is deleted with a message `No commit pushedDate could be found for PR 841 in repo microsoft/winget-pkgs`.

For example: https://github.com/microsoft/winget-pkgs/pull/841

**Expected:**
PR gets merged.

**Comment by denelon** [comment]
@lutzroeder this may be a duplicate ask, but I'll hold off marking this Issue as such until I find the earliest report.
