### ISSUE TITLE
[Update Request]: Rime.Weasel

### ISSUE THREAD

**Issue by sotcit** [microsoft/winget-pkgs#130125]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Rime.Weasel

### Package Version

0.15.0

### Please describe the changes you would like to see

There is a new release (0.15.0) available.
Download Page Url: https://github.com/rime/weasel/releases

**Comment by SpecterShell** [comment]
https://github.com/rime/weasel/issues/949

**Comment by Amoenus** [comment]
PR https://github.com/microsoft/winget-pkgs/pull/116453

**Comment by Trenly** [comment]
[Policy] Reset Labels

**Comment by Trenly** [comment]
[Policy] Package Update
[Policy] Help Wanted
