### ISSUE TITLE
Any comment on the AppGet situation?

### ISSUE THREAD

**Issue by Bartmax** [microsoft/winget-pkgs#1303]
For context: https://keivan.io/the-day-appget-died/

I think the community will likely want to know whatever you have to say about it.

Thanks.

**Comment by SoftCreatR** [comment]
I don't think, that this is the right place.

**Comment by Eugeny** [comment]
This place is as good as any other, at least MS won't be able to just ignore it.

**Comment by TheRndCoder** [comment]
There's already a discussion over here: https://github.com/microsoft/winget-cli/issues/353

You can see that the author for appget has already given his points on the thread as well and on The Verge article for this matter Microsoft gave a statement that they're already executing an internal investigation to find out what happened during the interview process.

**Comment by Bartmax** [comment]
I'll close this since there's a proper issue as @TheRndCoder mentioned.
