### ISSUE TITLE
[Package Request]: DS4Windows

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#130665]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Ryochan7/DS4Windows/releases
Publisher: Ryochan7
Package Name: DS4Windows
Description: DS4Windows is a utility designed to bring the Sony DualShock 4 game controllers into popular PC games that don't specifically support it
Package Version: 3.2.21
Installer URL: https://github.com/Ryochan7/DS4Windows/releases/download/v3.2.21/DS4Windows_installer_x64_v3.2.21.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This package is already presented in the repository as `Ryochan7.DS4Windows`. This issue should be https://github.com/microsoft/winget-pkgs/labels/Package-Update instead of https://github.com/microsoft/winget-pkgs/labels/Package-Request .

```text
D:\Workloads\winget-pkgs [master ≡]> winget search -e Ryochan7.DS4Windows
名称       ID                  版本   源
---------------------------------------------
DS4Windows Ryochan7.DS4Windows 3.2.19 winget
D:\Workloads\winget-pkgs [master ≡]> winget show -e Ryochan7.DS4Windows --versions
已找到 DS4Windows [Ryochan7.DS4Windows]
版本
------
3.2.19
```

**Comment by github-account1111** [comment]
Are you sure? I don't have it.

```
> winget search ds4windows
No package found matching input criteria.
```

**Comment by Dragon1573** [comment]
> Are you sure? I don't have it.
> 
> ```
> > winget search ds4windows
> No package found matching input criteria.
> ```

Try search with keyword `DS4Windows` or enter "exact searching mode" with `-e Ryochan7.DS4Windows`. Maybe `winget.exe` is performing case sensitive search.
