### ISSUE TITLE
[Package Issue]: Nvidia.CUDA may reboot Windows

### ISSUE THREAD

**Issue by HenkPoley** [microsoft/winget-pkgs#131152]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Unless you supply the `-n` option, the CUDA installer may automatically reboot Windows. E.g. to update a driver.

That's maybe useful, but also a bit unexpected.

Documentation: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#download-the-nvidia-cuda-toolkit

Just above 'Extracting and Inspecting the Files Manually':

> Use the `-n` option if you do not want to reboot automatically after install or uninstall, even if reboot is required.

Winget Package: [manifests/n/Nvidia/CUDA/12.3.1/Nvidia.CUDA.installer.yaml](https://github.com/microsoft/winget-pkgs/blob/a2d83e335fac4a52f3a409ec518263c61456d5e1/manifests/n/Nvidia/CUDA/12.3.1/Nvidia.CUDA.installer.yaml)

### Steps to reproduce

```
winget install Nvidia.CUDA
```

### Actual behavior

Windows reboots

### Expected behavior

Use the -n option to suppress reboots.

Maybe check if the RunOnce is populated (I suspect the installer sets that) and print a message that the user needs to reboot the system themselves.

### Environment

```raw
winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment]
It appears that the `-n` flag does not work with silent installation.

I tried to manually check the following sets of commands for the latest installer and none of them succeeded:

```
.\cuda_12.3.1_546.12_windows.exe -s -n
.\cuda_12.3.1_546.12_windows.exe /s -n
.\cuda_12.3.1_546.12_windows.exe /n /s
.\cuda_12.3.1_546.12_windows.exe -n /s
.\cuda_12.3.1_546.12_windows.exe -s
```

Only the following works:

```
.\cuda_12.3.1_546.12_windows.exe /s
```

**Comment by BrandonWanHuanSheng** [comment]
That installer seem like greater than 1GB

**Comment by HenkPoley** [comment]
@mdanish-kh You think this is basically an Nvidia installer bug?

**Comment by mdanish-kh** [comment]
> @mdanish-kh You think this is basically an Nvidia installer bug?

Yes I believe so. Forgot to label this issue properly

[Policy] Installer-Issue

**Comment by HenkPoley** [comment]
Just saying, that the latest CUDA 12.6.1 update I saw, did _not_ reboot the system automatically.

Which is good.

_Somewhere, somewhen_ this bug got fixed. 👍

```
PS C:\> winget upgrade --all
Name                     Id              Version Available Source
-----------------------------------------------------------------
NVIDIA CUDA Toolkit 12.6 Nvidia.CUDA     12.6    12.6.1    winget
1 upgrade available.

(1/1) Found NVIDIA CUDA Toolkit [Nvidia.CUDA] Version 12.6.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://developer.download.nvidia.com/compute/cuda/12.6.1/local_installers/cuda_12.6.1_560.94_windows.exe
  ██████████████████████████████  3.00 GB / 3.00 GB
Successfully verified installer hash
Starting package install...
Successfully installed
```
