### ISSUE TITLE
How to manage installers dedicated for each language?

### ISSUE THREAD

**Issue by auanasgheps** [microsoft/winget-pkgs#13114]
# Description of the new feature/enhancement

How should we manage those apps that have a **dedicated** installer for each language? 
Popular packages are Firefox and WinRAR.

I tried using "Add Locale" within `YAMLCreate.ps1`, but only allows the app info to be localized, not an installer.

I tried adding manually another installer to the `Mozilla.Firefox.installer.yaml`, but the validator marked the additional package as duplicated.

# Proposed technical implementation details (optional)

When using `Add Locale` feature, add the option for a dedicated installer.
The main `PackageName.installer.yaml` will still have a default English package installed by default, but if the user locale or setting is set to a specific language, install the package from the corresponding language YAML.

I hope it makes sense.

**Comment by OfficialEsco** [comment]
As the one who reworked the YAMLCreate and created the "Add Locale" function i can say i did not think about this, the "Add Locale" function is basically only to write the information in another language..

[Firefox 82.0.1](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Mozilla/Firefox/82.0.1) is little example of how to do en-US and es-MX and [here is a installer manifest with multiple languages](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/79.0/Mozilla.Firefox.installer.yaml) but no locale manifest.
The problem with Firefox is that they use a different locale code than Windows so its a bit hard to know which url goes to which locale... (The manifest with multiple manifest is correct, but i removed quite a few)

If someone knows Powershell they can easily modify the Reworked YamlCreate, however the WinGet team is working on `winget create` which hopefully includes what my script does, just better and more functions 😄 

Feel free to ask any questions around manifest creation :)

**Comment by denelon** [comment]
This is a particularly challenging area. We do support multiple installer nodes in a way you can specify the locale for the installer with BCP47 format. You would specify the "InstallerLocale" in the "Installer" node. Note: this does require the multi-file manifest structure.
