### ISSUE TITLE
[Package Issue]: joncampbell123.DOSBox-X

### ISSUE THREAD

**Issue by br2soft** [microsoft/winget-pkgs#131327]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After deinstall and reinstalling the newest version of that package, the package wants still to be updated. I had installed version 2023.09.01 and I installed the new version 2023.10.06.

### Steps to reproduce

Install the current version of joncampbell123.DOSBox-X and run winget update.

### Actual behavior

winget wants to update a package that is already installed in the latest availabe version.

### Expected behavior

No message that there is an update.

### Environment

```raw
Windows-Paket-Manager v1.6.3421
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.3803
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3421.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by Trenly** [comment]
Can you share the output of `winget list Dosbox` ?

**Comment by br2soft** [comment]
<code>C:\WINDOWS\system32>winget list Dosbox
    Name     ID                      Version      Verfügbar  Quelle
    ---------------------------------------------------------------
    DOSBox-X joncampbell123.DOSBox-X > 2023.09.01 2023.10.06 winget
</code>

**Comment by Trenly** [comment]
@stephengillie - Seems this is another case where older versions contain AppsAndFeaturesEntries and the newest does not - and they are required to map the correct version

**Comment by Trenly** [comment]
* Caused by https://github.com/microsoft/winget-pkgs/pull/125180

**Comment by stephengillie** [comment]
@Trenly Oh - thanks but I've solved that problem by having the PR Watcher retrieve the previous manifest version and compare. So I don't need to gather a list as it's automatic.
