### ISSUE TITLE
P.S.A. Packages with explicit agreements in manifests removed

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#131328]
Several packages were passing explicit arguments representing agreements to the installers to achieve a silent install. These packages are being evaluated to see if they will succeed with a non-interactive configuration with those explicit arguments removed. If they will not succeed, they will be removed.

We are working on a short-term solution to allow agreements in packages for the community repository. We will require agreement Title(s) and URL(s) when these switches are required. The agreement text will still be gated by the verified developer feature.

**Comment by Trenly** [comment]
<details>
<summary>Affected Packages</summary>

- [ ] NI.ni-packagemanager
- [ ] NhekoReborn.Nheko
- [ ] KhronosGroup.VulkanSDK
- [ ] ESET.Nod32
- [ ] ESET.Security
- [ ] Segger.EmbeddedStudioARM
- [ ] Rowley.CrossWorks
- [ ] nomic.gpt4all
- [ ] Microsoft.ServiceFabricRuntime
- [ ] veeam.veeam-agent
- [ ] XmacsLabs.Mogan
- [ ] Zoom.ZoomRooms
- [ ] Kingsoft.WPSOffice.CN
- [ ] Kingsoft.KingsoftPDF - 1 Version
- [ ] Splunk.UniversalForwarder
- [ ] VMWare.WorkstationPlayer
- [ ] VMWare.WorkstationPro
- [ ] Tableau.PrepBuilder
- [ ] Tableau.Desktop
- [ ] Tableau.Reader
- [ ] Tableau.Public
- [ ] IDRIX.VeraCrypt
- [ ] Bitvise.SSH.Server
- [ ] Bitvise.SSH.Client
- [ ] Microsoft.PowerBIReportBuilder
- [ ] Microsoft.PowerBIDesktopReportServer
- [ ] Microsoft.PowerAutomateDesktop
- [ ] Microsoft.PowerBI
- [ ] Microsoft.SQLServer2012NativeClient
- [ ] WHTA.Tamara
- [ ] Atlassian.Sourcetree (Wix Installers only)

</details>

**Comment by Smith8154** [comment]
Removing these packages caused some issues for our organization, as we were relying on some of the packages for automated deployments that started failing while I was on holiday at the end of the year. I think it would have been best to wait until after the holidays to make this change to give everyone some time to make adjustments without running into change freezes or having people out on holiday.

**Comment by khaffner** [comment]
@denelon Are the relevant teams at Microsoft informed about fixing their respective installers?

**Comment by JvDrunen** [comment]
Any update?

**Comment by vvirtues** [comment]
When is the fix (short or long term) coming in? I see the `--accept-source-agreements` and `--accept-package-agreements` flag, but how do I implement it in a manifest? (also which is used for which situations).

EDIT: I realize that there is the `Agreements` parameter, but it is not documented in schema or otherwise. I am trying to implement it in a PR (https://github.com/microsoft/winget-pkgs/pull/136114) but I will just have to use the info from https://github.com/microsoft/winget-cli/issues/200 and https://github.com/microsoft/winget-cli/pull/1347/files#diff-851d289ea5f2ac425d19f54c568328e3557b0928478bed123b4232dd4189c8db to implement it.

**Comment by Trenly** [comment]
> When is the fix (short or long term) coming in? I see the `--accept-source-agreements` and `--accept-package-agreements` flag, but how do I implement it in a manifest? (also which is used for which situations).
> 
> EDIT: I realize that there is the `Agreements` parameter, but it is not documented in schema or otherwise. I am trying to implement it in a PR (#136114) but I will just have to use the info from [microsoft/winget-cli#200](https://github.com/microsoft/winget-cli/issues/200) and [microsoft/winget-cli#1347 (files)](https://github.com/microsoft/winget-cli/pull/1347/files#diff-851d289ea5f2ac425d19f54c568328e3557b0928478bed123b4232dd4189c8db) to implement it.

The `Agreements` section of the manifest is what needs to be added to resolve this issue. However, submitting a manifest with `Agreements` currently will be blocked as that field requires verified publishers currently. I believe that @denelon is working on a solution to allow the agreements without being a verified publisher, which will allow many of these packages to be re-added

**Comment by vvirtues** [comment]
> > When is the fix (short or long term) coming in? I see the `--accept-source-agreements` and `--accept-package-agreements` flag, but how do I implement it in a manifest? (also which is used for which situations).
> > EDIT: I realize that there is the `Agreements` parameter, but it is not documented in schema or otherwise. I am trying to implement it in a PR (#136114) but I will just have to use the info from [microsoft/winget-cli#200](https://github.com/microsoft/winget-cli/issues/200) and [microsoft/winget-cli#1347 (files)](https://github.com/microsoft/winget-cli/pull/1347/files#diff-851d289ea5f2ac425d19f54c568328e3557b0928478bed123b4232dd4189c8db) to implement it.
> 
> The `Agreements` section of the manifest is what needs to be added to resolve this issue. However, submitting a manifest with `Agreements` currently will be blocked as that field requires verified publishers currently. I believe that @denelon is working on a solution to allow the agreements without being a verified publisher, which will allow many of these packages to be re-added

Oh ok, should I keep my PR as a draft or should I close and re-open once the solution's out?

**Comment by olegpro81** [comment]
Guys, any update on this issue?

**Comment by denelon** [comment]
Hey everyone, we have the updated policy implemented for the community repository. We're now allowing packages to be added back with agreements with explicit switches being passed to installers.

**Comment by denelon** [comment]
I'm going to go ahead and close this issue since we have the ability to accept these packages back into the community repository, but I will keep this message pinned until the packages have been added back.

**Comment by denelon** [comment]
All removed packages have been restored. I'm unpinning this issue now.
