### ISSUE TITLE
[Package Request]: StandardML.SMLNJ

### ISSUE THREAD

**Issue by chen-qingyu** [microsoft/winget-pkgs#131581]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.smlnj.org/index.html
Publisher: [The SML/NJ Team](https://www.smlnj.org/people.html)
Package Name: StandardML.SMLNJ
Description: Standard ML of New Jersey (abbreviated SML/NJ) is a compiler for the [Standard ML '97](https://www.smlnj.org/sml97.html) programming language with associated libraries, tools, and documentation.
Package Version: 110.99.4
Installer URL: http://smlnj.cs.uchicago.edu/dist/working/110.99.4/smlnj-110.99.4.msi

**Comment by Dragon1573** [comment]
@chen-qingyu,

The current latest version is [`v2023.1`](https://www.smlnj.org/dist/working/2023.1/index.html), released on Dec 10, 2023. The exect version you are requesting for is [`v110.99.4`](https://www.smlnj.org/dist/working/110.99.4/index.html), released on Aug 1, 2023.

According to the [download page](https://www.smlnj.org/index.html), it seems this package is released with a mixture of version `x.y` and version `x.y.z`. This will confuse the version management of `winget.exe`. `winget.exe` will regard `v110.99.4` newer than `v2023.1`.

Can we format them to a "standard" version number? Or is there any difference between them so we can seperate them with different package identifier?

**Comment by stephengillie** [comment]
We have other packages where we've had to remove old versions when they change versioning schema, to prevent an old version being recommended as an upgrade to the newest version. This might be similar.

**Comment by chen-qingyu** [comment]
According to their source code repository readme documentation:

> There are two main repositories:
> 
> The ["legacy"](https://github.com/smlnj/legacy) repository (smlnj/legacy) contains the source for the 110.99 patch releases. This version is being maintained as a stable version while we make more radical changes in the development version. It supports older architectures (e.g., the PowerPC and Sparc) and 32-bit executables.
> To report bugs in the legacy versions, use the [legacy issue tracker](https://github.com/smlnj/legacy/issues).
> 
> The ["development"](https://github.com/smlnj/smlnj) repository (smlnj/smlnj) is the latest version of the system. We are making substantial changes to the runtime system and compiler backend in this repository, so it is not recommended for production work.
> To report bugs in the development version, use the [development issue tracker](https://github.com/smlnj/smlnj/issues).

It looks like this is two repositories, making two packages is possible but complex, the development version should be the main support in the future, so I changed to the development version (v2023.1).
