### ISSUE TITLE
Product Masquerading as Microsoft Corporation as Publisher

### ISSUE THREAD

**Issue by imposhster** [microsoft/winget-pkgs#131654]
https://github.com/microsoft/winget-pkgs/blob/4e76aed0d59412f0be0ecfefabfa14b5df05bec4/manifests/z/zokugun/MrCode/1.82.0.23253/zokugun.MrCode.locale.en-US.yaml#L7C1-L7C33

MrCode has the publisher as "Microsoft Corporation" when there is no reference to being supported by or distributed by Microsoft.

**Comment by stephengillie** [comment]
I'll add a check to the PR Watcher to try to catch this in the future.
