### ISSUE TITLE
[Package Issue]: SoftwareFreedomConservancy.QEMU

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/winget-pkgs#131959]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget installs version 8.2.0-rc4 from https://qemu.weilnetz.de/w64/2023/qemu-w64-setup-20231214.exe  that reports itself as 8.1.94
Version 8.2.0 is already released and located at https://qemu.weilnetz.de/w64/2023/qemu-w64-setup-20231224.exe 
When i installed 8.2.0 winget asks me to "upgrade" 8.2.0 to 8.2.0-rc4

### Steps to reproduce

Install qemu 8.2.0
winget thinks that 8.2.0-rc4 us newer.

### Actual behavior

 Winget  tries to downgrade release version to release candidate.

### Expected behavior

  Winget doesn't try to downgrade release version to release candidate.

### Environment

```raw
Диспетчер пакетов Windows версии 1.6.3482
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.22631.2861
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.21.3482.0

Каталоги WinGet
-----------------------------------------------------------------------------------------------------------------------
Журналы                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Параметры пользователя                    %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Каталог переносимых ссылок (пользователь) %LOCALAPPDATA%\Microsoft\WinGet\Links
Каталог переносимых ссылок (компьютер)    C:\Program Files\WinGet\Links
Корень переносимого пакета (пользователь) %LOCALAPPDATA%\Microsoft\WinGet\Packages
Корень переносимого пакета                C:\Program Files\WinGet\Packages
Корень переносимого пакета (x86)          C:\Program Files (x86)\WinGet\Packages
Скачивания установщика                    %USERPROFILE%\Downloads

Ссылки
--------------------------------------------------------------------------------------
Заявление о конфиденциальности https://aka.ms/winget-privacy
Лицензионное соглашение        https://aka.ms/winget-license
Уведомления третьих сторон     https://aka.ms/winget-3rdPartyNotice
Домашняя страница              https://aka.ms/winget
Условия Windows Store          https://www.microsoft.com/en-us/storedocs/terms-of-sale

Параметр администратора                   Состояние
---------------------------------------------------
LocalManifestFiles                        Отключено
BypassCertificatePinningForMicrosoftStore Отключено
InstallerHashOverride                     Отключено
LocalArchiveMalwareScanOverride           Отключено

Wingetui 2.1.2 is used.
```

**Comment by Pandoriaantje** [comment]
wouldn't this be a bug in winget? as it does not appear to correctly interpret release candidate tags, or is there a uniform naming scheme for this?

**Comment by stephengillie** [comment]
Related: 

- https://github.com/microsoft/winget-cli/issues/2394
