### ISSUE TITLE
[Package Issue]: KDE.Okular

### ISSUE THREAD

**Issue by BOY0038v2** [microsoft/winget-pkgs#131937]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

installation fails with error "0x80190193 : Forbidden (403)."

### Steps to reproduce

`winget install KDE.Okular`

### Actual behavior

```
winget install KDE.Okular
Found Okular [KDE.Okular] Version 23.08.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/1611/artifact/okular-23.08.4-1611-windows-cl-msvc2019-x86_64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).
```

### Expected behavior

a succesfull installation

### Environment

```raw
winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.3803
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by fancybody** [comment]
`KDE.Okular` installer urls are dynamically generated [here](https://binary-factory.kde.org/view/Windows%2064-bit/) (Okular_Release_win64 in the list).

The static url list for windows builds [here](https://download.kde.org/stable/release-service/) have not been updated for `23.08.3` and `23.08.4`.

The easiest way is to install via MSstore.
```
winget search okular
winget install --id=9N41MSQ1WNM8 -e
```

**Comment by Dragon1573** [comment]
```text
D:\Workloads> winget download -e KDE.Okular
已找到 Okular [KDE.Okular] 版本 23.08.4
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/1622/artifact/okular-23.08.4-1622-windows-cl-msvc2019-x86_64.exe
  ██▋                             11.0 MB /  121 MB
已取消
```

Seems the issue is successfully resolved. Shall we close this issue as completed?

**Comment by BOY0038v2** [comment]
Now it's working perfectly fine. I will close the issue. Thanks to everyone, have a good day!

**Comment by pedrohgmacedo** [comment]
I'm still having this problem. The same as the #122215 issue.
