### ISSUE TITLE
[Update Request]:  ManuelLaggner.tinyMediaManager - update installer hash

### ISSUE THREAD

**Issue by kcris** [microsoft/winget-pkgs#132337]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

ManuelLaggner.tinyMediaManager

### Package Version

v4

### Please describe the changes you would like to see

```
Downloading https://release.tinymediamanager.org/v4/dist/tinyMediaManagerSetup.exe
...
Installer hash does not match.
```

**Comment by Exorcism0666** [comment]
@BiosPlus There is already a pull request.
![image](https://github.com/microsoft/winget-pkgs/assets/46537034/d794524a-f62c-47d8-94e5-8e9064e2e5b9)
