### ISSUE TITLE
[Package Request]: Windscribe

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#132741]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Windscribe/Desktop-App/releases
Publisher: Windscribe
Package Name: Windscribe
Description: Windscribe 2.0 desktop client for Windows, Mac and Linux
Package Version: 2.8.6
Installer URL: https://github.com/Windscribe/Desktop-App/releases/download/v2.8.6/Windscribe_2.8.6.exe

**Comment by Exorcism0666** [comment]
let me just update my bot, and normally it will work. :)
