### ISSUE TITLE
[Package Issue]: Windscribe.Windscribe will uninstall instead of updating

### ISSUE THREAD

**Issue by Eddga** [microsoft/winget-pkgs#132894]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Updating an existing version of Windscribe via winget will instantly fail with `Uninstall failed with exit code: 20016`, leave you with uninstallation prompt open and not continue to reinstall afterwards.

### Steps to reproduce

1. Install an older version of Windscribe (e.g. https://github.com/Windscribe/Desktop-App/releases/tag/v2.8.4 )
2. `winget update Windscribe.Windscribe`

### Actual behavior

- `Uninstall failed with exit code: 20016`
- Uninstall prompt is opened (no silent uninstallation)
- Install/update won't continue after uninstallation

### Expected behavior

Update Windscribe to the latest version

### Environment

```raw
Windows Package Manager v1.6.3482
Windows: Windows.Desktop v10.0.22631.2861
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Eddga** [comment]
I didn't find any properties in the manifests that would allow for silent uninstall switches.
But you can update by just installing. Therefore changing the UpgradeBehavior to _install_ should fix the issue.

**Comment by OfficialEsco** [comment]
This is probably the reason for uninstallprevious
![image](https://github.com/microsoft/winget-pkgs/assets/15158490/8b8ec5b8-3440-403b-a60a-1d8e6ffdba33)

Pre 2.4.11 appears to be 32bit only, 2.5.18 overwrites 2.8.6 because they are both 64bit
