### ISSUE TITLE
[Package Request]: Crucial Storage Executive

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/winget-pkgs#132973]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.crucial.de/support/storage-executive
Publisher: Crucial
Package Name: Crucial Storage Executive
Description: Crucial Storage Executive SSD / NVMe Management and Firmware
Package Version: ? 
Installer URL: https://www.crucial.de/content/dam/crucial/support/storage-executive-win-64.zip

**Comment by Exorcism0666** [comment]
Version: 9.09.092023.03

I will open a pull request in the next few minutes.

**Comment by Karl-WE** [comment]
Thank you very much for working on this and others @Exorcism0666

**Comment by Exorcism0666** [comment]
No problem! :-)
