### ISSUE TITLE
[Package Issue]: calibre.calibre broken download links

### ISSUE THREAD

**Issue by wickles** [microsoft/winget-pkgs#133004]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Manifests for some recent versions of Calibre are using github links for `InstallerUrl` but these become stale after a new release, since they delete old release artifacts from github for some reason. (@kovidgoyal why?)

This makes it impossible to install or upgrade when a new version is released but not yet included in winget.

Instead of

```
https://github.com/kovidgoyal/calibre/releases/download/v${version}/calibre-64bit-${version}.msi
```

the stable link should be

```
https://download.calibre-ebook.com/${version}/calibre-64bit-${version}.msi
```

Please do not submit or accept updates for calibre with github download links in the future unless this issue is resolved upstream and the download links become stable again. (@vedantmgoyal2009)

### Steps to reproduce

Try to install or upgrade `calibre.calibre` to a bad version.

```
winget install calibre.calibre --version 7.2.0
```

### Actual behavior

```
> winget install calibre.calibre --version 7.2.0
Found an existing package already installed. Trying to upgrade the installed package...
Found calibre [calibre.calibre] Version 7.2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/kovidgoyal/calibre/releases/download/v7.2.0/calibre-64bit-7.2.0.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

### Expected behavior

Old versions should remain accessible.

### Environment

```raw
Windows Package Manager (Preview) v1.7.3481-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.3481.0
```

**Comment by wickles** [comment]
@kovidgoyal could you please comment on why the old artifacts get deleted from the github repo? As far as I know it should not cost anything to persist all build artifacts on a public repo.

**Comment by kovidgoyal** [comment]
Because calibre releases are huge and frequent and I am not comfortable
using up so much storage/bandwidth from a free service. All calibre
releases are available in perpetuity from
https://download.calibre-ebook.com/ regardless of changes to other
hosting services.

**Comment by wickles** [comment]
I see, thank you for the feedback.

Closing since all versions have been fixed now.

**Comment by wickles** [comment]
Unstable link was added again in #145749. Requesting @vedantmgoyal9 to update the link and stop submitting github download links for calibre in the future.

**Comment by alorle** [comment]
The same thing happens with the versions 7.8.0 (#147834), 7.9.0 (#150076), 7.10.0 (#152040), 7.11.0 (#154954) and 7.12.0 (#155837).

**Comment by wickles** [comment]
@SpecterShell #155866 does not resolve the issue. The other versions mentioned in the previous comment are still broken. As an example/demonstration:
```
winget install calibre --version 7.10.0
```
fails with error 404.

**Comment by SpecterShell** [comment]
Done

**Comment by yifeizhu0001-png** [comment]
not working for 9.14

**Comment by SpecterShell** [comment]
> not working for 9.14

Works normally on my device.

```
❯ winget download calibre.calibre
Found calibre [calibre.calibre] Version 9.14.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.calibre-ebook.com/9.14.0/calibre-64bit-9.14.0.msi
  ██████████████████████████████   213 MB /  213 MB
Successfully verified installer hash
Installer downloaded: C:\Users\SpecterShell\Downloads\calibre.calibre_9.14.0\calibre_9.14.0_Machine_X64_wix_en-US.msi
```
