### ISSUE TITLE
Spell Checking workflow runs fail for no apparent reason

### ISSUE THREAD

**Issue by marco-eckstein** [microsoft/winget-pkgs#133051]
### Discussed in https://github.com/microsoft/winget-pkgs/discussions/87054

<div type='discussions-op-text'>

<sup>Originally posted by **clovett** November  1, 2022</sup>
I'm submitting this PR: https://github.com/microsoft/winget-pkgs/pull/87051/checks

But I get runs like this reporting spellcheck failures to me:
https://github.com/clovett/winget-pkgs/actions/runs/3366593799 

It's reporting spelling errors in packages that have nothing to do with me or my PR? 

![image](https://user-images.githubusercontent.com/3336415/199153857-e9fd3b1f-15f9-4d6f-b2e3-1bad94cb697d.png)
</div>

I have the same issue. Every time I push master or another branch, I get the notification _Spell Checking workflow run failed for..._. Until a few days ago, I did not have this issue even with an up-to-date fork. Only after I synced my fork again, it appeared.

Pull requests for the failing branches have been accepted anyway, so apparently the issue can be ignored. But Microsoft, please fix it!

**Comment by Trenly** [comment]
@jsoref - can you help us out here?

**Comment by twpayne** [comment]
I've hit this problem too, which is preventing me from updating my software in winget-pkgs: https://github.com/twpayne/winget-pkgs/pull/434#issuecomment-1884659138

The spell check seems to apply to the whole repo, which includes files outside the PR, i.e. any spelling error breaks winget-pkgs for everyone.

I would suggest disabling the check-spelling workflow immediately until this is fixed.

**Comment by Trenly** [comment]
> I would suggest disabling the check-spelling workflow immediately until this is fixed.

You will need to disable the workflow on your fork, since each fork of the repo runs the workflows independently

**Comment by twpayne** [comment]
I've disabled GitHub Actions on my fork now.

**Comment by jsoref** [comment]
I can't see this file in https://github.com/microsoft/winget-pkgs/tree/master/.github nor in https://github.com/clovett/winget-pkgs/tree/master/.github

If someone can point me to it live somewhere, I can provide better advice in a bit (I'm hopping offline shortly, I should be back and it should be simple if I can see the file; normally I'd use a computer and hunt for the file myself, but I only have a phone atm and really need to hop off).

**Comment by twpayne** [comment]
They're in:

https://github.com/microsoft/winget-pkgs/blob/5c894ce8522d5caa65060d2970b06a628d7bd2d1/.github/workflows/spellCheck.yaml

https://github.com/microsoft/winget-pkgs/tree/5c894ce8522d5caa65060d2970b06a628d7bd2d1/.github/actions/spelling

**Comment by Trenly** [comment]
> I can't see this file in [`master`/.github](https://github.com/microsoft/winget-pkgs/tree/master/.github) nor in [clovett/winget-pkgs@`master`/.github](https://github.com/clovett/winget-pkgs/tree/master/.github)
> 
> If someone can point me to it live somewhere, I can provide better advice in a bit (I'm hopping offline shortly, I should be back and it should be simple if I can see the file; normally I'd use a computer and hunt for the file myself, but I only have a phone atm and really need to hop off).

I believe that specific file has been removed from `master` for a while, so perhaps that fork is just out of date.

**Comment by jsoref** [comment]
That seems like the most likely explanation.

**Comment by Trenly** [comment]
Close with reason: Fixed spelling and PR has been merged to master;
