### ISSUE TITLE
[Package Issue]: Microsoft.PowerAutomateDesktop

### ISSUE THREAD

**Issue by JvDrunen** [microsoft/winget-pkgs#133240]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Using the installation parameters the installation wont coninue. it is expecting the -accepteula. (this is commented out in the manifest)

### Steps to reproduce

 winget install Microsoft.PowerAutomateDesktop

### Actual behavior

response:
 winget install Microsoft.PowerAutomateDesktop
Found Power Automate for desktop [Microsoft.PowerAutomateDesktop] Version 2.39.306.23341
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
Downloading https://download.microsoft.com/download/b/d/8/bd8409df-7b80-4ef7-89c5-5a7a941a5093/Setup.Microsoft.PowerAutomate.exe
  ██████████████████████████████   274 MB /  274 MB
Successfully verified installer hash
Starting package install...
   / To install silently, you'll need to accept the terms of use and privacy statement with -accepteula. Rerun without -s to view these terms.
Installer failed with exit code: 4294967295

### Expected behavior

installation of power automate

### Environment

```raw
winget --info
Windows Package Manager v1.6.3421
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3421.0
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/30151600/03b6623c-69b4-4742-8b98-f40621cb05b1)

**Comment by JvDrunen** [comment]
Just remove the # in manifests/m/Microsoft/PowerAutomateDesktop/2.39.306.23341/Microsoft.PowerAutomateDesktop.installer.yaml

**Comment by denelon** [comment]
We're blocking packages that explicitly pass a EULA argument a user might not see right now. We're doing some changes in the client so we can validate those and have the "agreements" logic trigger for those packages.

**Comment by JvDrunen** [comment]
ok, so when is the client ready for this? the package is not working at this moment.

**Comment by olegpro81** [comment]
Guys, any ETA on this one?

**Comment by olegpro81** [comment]
I'm running this command, still not working: .\winget.exe install -e --id Microsoft.PowerAutomateDesktop --force --silent --accept-package-agreements --accept-source-agreements

**Comment by olegpro81** [comment]
Sorry guys, just want to know if someone is working on it or I should start packaging it on ConfigManager side :(.

**Comment by Trenly** [comment]
> Sorry guys, just want to know if someone is working on it or I should start packaging it on ConfigManager side :(.

Someone is working on this, it's just a matter of time

**Comment by olegpro81** [comment]
Guys, any progress?

**Comment by mdanish-kh** [comment]
@olegpro81 This will be resolved by PR:

- #139648

**Comment by mdanish-kh** [comment]
Close with reason: Package re-added in PR #139648 with agreements;
