### ISSUE TITLE
[Package Request]: ComPortInfo

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#133301]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.uwe-sieber.de/ComPortInfo_e.html#download
Publisher: Uwe Sieber
Package Name: ComPortInfo
Description: Information about COM ports.
Package Version: 1.1.9
Installer URL: https://www.uwe-sieber.de/files/ComPortInfo.zip

**Comment by UweSieber** [comment]
Just made the latest release available for download as
https://www.uwe-sieber.de/files/ComPortInfo121_x64.zip

I'm new to winget. I there a notification mechanism for new releases?

Uwe Sieber

**Comment by AsciiWolf** [comment]
There are some bots that can parse pages for new releases, but it varies from app to app.

However, you can create a new package update request [here](https://github.com/microsoft/winget-pkgs/issues).
