### ISSUE TITLE
Fix two manifests for same publisher/app

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-pkgs#13374]
[manifests/4/4KDownload](https://github.com/microsoft/winget-pkgs/tree/master/manifests/4/4KDownload) and [manifests/o/OpenMedia](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia) are for same publisher/app so one of them needs to be removed.

**Comment by jedieaston** [comment]
I think I've cleaned this up. Once those PRs clear, you should be good to go!

**Comment by jedieaston** [comment]
Looks like it's all cleaned up!

**Comment by KaranKad** [comment]
Thanks, I'll close this issue then.
