### ISSUE TITLE
Support default install root

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#13382]
# Description of the new feature/enhancement

https://github.com/microsoft/winget-cli/issues/970 Some packages are installed based on the location of the installer on the drive. This can be an undesired behavior, and may be further complicated by packages with long paths like Python as discovered in microsoft/winget-pkgs#13076.

# Proposed technical implementation details (optional)

* https://github.com/microsoft/winget-cli/issues/970
* https://github.com/microsoft/winget-cli-restsource/issues/32
* https://github.com/microsoft/winget-pkgs/issues/13382

**Comment by vedantmgoyal2009** [comment]
@denelon this has been implemented...
