### ISSUE TITLE
[Update Request]: Discord 64-bit version

### ISSUE THREAD

**Issue by xAphex** [microsoft/winget-pkgs#133982]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Discord.Discord

### Package Version

1.0.9028

### Please describe the changes you would like to see

The current Discord that is provided is 32bit only, can you include the 64bit version that is available at:
https://dl.discordapp.net/distro/app/stable/win/x64/1.0.9028/DiscordSetup.exe

Thank you

**Comment by Dragon1573** [comment]
@xAphex - There's no `v1.0.9028` present in the repository. Do you mean `v1.0.9030`?

```text
D:\Workloads\winget-pkgs [master ≡]> winget search -e Discord.Discord --versions
已找到 Discord [Discord.Discord]
版本
--------
1.0.9030
1.0.9025
1.0.9024
1.0.9023
1.0.9018
1.0.9017
1.0.9016
1.0.9015
1.0.9013
1.0.9012
1.0.9011
1.0.9010
1.0.9008
1.0.9007
1.0.9006
1.0.9005
1.0.9004
D:\Workloads\winget-pkgs [master ≡]> winget show -e Discord.Discord
已找到 Discord [Discord.Discord]
版本: 1.0.9030
发布者: Discord Inc.
发布服务器 URL: https://discord.com
发布服务器支持 URL: https://support.discord.com
作者: Discord Inc.
描述: Discord 是最简单易用的通讯工具,兼具语音、视频以及文字信息功能。您可以聊聊天,拉拉家常,一起玩耍,与好友和社区保持紧密联系。
主页: https://discord.com
许可证: 专有软件
许可证 URL: https://discord.com/terms
隐私 URL: https://discord.com/privacy
版权所有: Copyright (c) 2023 Discord Inc. All rights reserved.
发行说明 URL: https://discord.com/blog/discord-update-june-22-2023-changelog
购买 URL： https://discord.com/nitro
标记：
  开黑
  游戏
  聊天
  语音
  语音聊天
安装：
  安装程序类型： exe
  安装程序区域设置： en-US
  安装程序 URL： https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86
  安装程序 SHA256： d85eb0787c08183f26c90213958966b1f7a3c11871060f338007a2bef15b3be7
  发布日期: 2023-12-13
```

**Comment by stephengillie** [comment]
The [direct link](https://support.discord.com/hc/en-us/articles/17997797368471--Known-Issue-Support-for-32-bit-Windows-Operating-Systems) doesn't work for me (even tried it on my personal laptop with my Discord creds), but [this news article](https://www.neowin.net/news/the-discord-app-is-ending-support-for-32-bit-windows-operating-systems-on-december-1/#:~:text=The%20support%20for%20using%20a,systems%20on%20December%201%2C%202023.) says:

> The support for using a PC with a Windows 32-bit operating system is getting smaller and smaller. This week, the gaming-themed online messaging service Discord announced it would end its support for running its Windows app client on Windows 32-bit operating systems on December 1, 2023.

Based on this, should the `x86` version be omitted in future manifests? 

- This is part of a small trend of applications halting 32-bit development in recent months. Including Git.

**Comment by xAphex** [comment]
Winget is showing x86 upgrade for x64 discord package

```
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name         Id                           Version           Available           Source
------------------------------------------------------------------------
Discord       Discord.Discord      1.0.9028        1.0.9030            winget
```

Latest version for **x86** is **1.0.9030**
Latest version for **x64** is **1.0.9028**
