### ISSUE TITLE
[New Feature]: make Python.Launcher branched

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#135072]
### Description of the new feature/enhancement

Right now Python.Launcher package does not have branches, which results in this situation where winget wants to update python.launcher to latest version (3.12) even when you installed python ≤3.11, this should not happen:
![image](https://github.com/microsoft/winget-pkgs/assets/5204968/c6d01614-6790-4d13-ae34-01919380c129)

To reproduce:
```
winget install -h --id=Python.Python.3.11  -e
winget upgrade
```

**Comment by stephengillie** [comment]
Is `Python.Launcher` meant to have different versions installed side-by-side? For instance, with 3.12 installed, should installing 3.11 result in both 3.11 and 3.12 installed and independently usable?

**Comment by soredake** [comment]
> Is `Python.Launcher` meant to have different versions installed side-by-side?

My bad, it is not, and turns out python.launcher is backwards compatible, closing.
