### ISSUE TITLE
P.S.A Pipelines Paused

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#135118]
We've paused the pipelines. We're doing some migration work for internal governance requirements. We will start the pipelines back up as soon as possible.

**Comment by khaffner** [comment]
Any estimate on when the pipelines are back?

**Comment by stephengillie** [comment]
I believe these might be operational again.

**Comment by denelon** [comment]
We just re enabled the webhook, so the PR cleaner should start triggering validations again.
