### ISSUE TITLE
[Update Request]: Java SE Development Kit 21 - 21.0.2

### ISSUE THREAD

**Issue by Umoxfo** [microsoft/winget-pkgs#135445]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Oracle.JDK.21

### Package Version

21.0.2

### Please describe the changes you would like to see

There is a new release (21.0.2) available.
Download Package Url: https://www.oracle.com/jp/java/technologies/downloads/#jdk21-windows

**Comment by Dragon1573** [comment]
@Umoxfo - There's a pull request currently work in progress. Please be patient as moderators have to manually validate it.

@PckgrBot - Could you please `Resolve #135445` in https://github.com/microsoft/winget-pkgs/pull/135253#issue-2087185012 ? It can link the PR to this issue, make this issue into https://github.com/microsoft/winget-pkgs/labels/In-PR and automatically close this issue after PR is merged.

**Comment by Exorcism0666** [comment]
@stephengillie Can you close this issue ?

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #135253;
