### ISSUE TITLE
cannot install packages 

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#135683]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I have try to install the following packages : 

GOMLab.GOMPlayer, Mega.MEGASync, Intel.IntelDriverAndSupportAssistant, ElectronicArts.EADesktop, 

I am facing the following error message : 
Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

winget install --id=GOMLab.GOMPlayer -e; winget install --id=Mega.MEGASync -e; winget install --id=ElectronicArts.EADesktop -e; 

### Actual behavior

I am facing the following error message : 
Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

To install the following packages : 

GOMLab.GOMPlayer, Mega.MEGASync, Intel.IntelDriverAndSupportAssistant, ElectronicArts.EADesktop, 

successfully 

### Environment

```raw
PS C:\Users> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3007
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
PS C:\Users>
```

**Comment by drshtmstry** [comment]
https://github.com/microsoft/winget-pkgs/pull/135699
