### ISSUE TITLE
Add a pipeline status badge

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#13612]
# Description of the new feature/enhancement

As a manifest submitter, I would like to see a pipeline status badge so I am informed about the status of the validation and publishing pipelines

# Proposed technical implementation details (optional)

Add a status badge for the validation and publishing pipelines to the README.md and the PR template so users can be informed.

**Comment by vedantmgoyal2009** [comment]
> [...]
> Add a status badge for the validation and publishing pipelines to the README.md and the PR template so users can be informed.

@denelon As you mentioned "the PR template", can't we directly integrate into PULL_REQUEST_TEMPLATE.md and remove the additional comment posted by @wingetbot?

**Comment by denelon** [comment]
@vedantmgoyal2009 due to the way some of the pipelines work, we needed to do it in a comment after the PR is initiated so we get the right pipeline execution instance.

**Comment by vedantmgoyal2009** [comment]
@denelon Okay 👍
