### ISSUE TITLE
[Update Request]: ctrl-f.userdiag 24.1.17

### ISSUE THREAD

**Issue by SkyEmie** [microsoft/winget-pkgs#136463]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ctrl-f.userdiag

### Package Version

24.1.18

### Please describe the changes you would like to see

New version: 24.1.18
Installer URL: https://userdiag.com/download?winget

**Comment by Trenly** [comment]
@skyemie - Is there some form of UserAgent or Client check which could be preventing WinGet from being able to access the URL?

```
Found UserDiag [ctrl-f.userdiag] Version 24.1.17
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://userdiag.com/download?WinGet
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).
```

**Comment by stephengillie** [comment]
Yes, WinGet uses its own User-Agent string, which some hosts have started blocking. This allows them to prevent automated downloads but still allow user downloads through the browser. 

The InstallerUrl here appears to use a JavaScript function to gather details about the browser, to prevent automated downloads. WinGet probably doesn't invoke a full browser for downloads, and instead probably performs a simple GET. This is a different method from above, and is just as effective.

Packages on this host might not be a good fit for inclusion into the WinGet public manifests.

**Comment by SkyEmie** [comment]
I've updated the link (?winget instead of ?WinGet)
It doesn't seem to be a problem now

```bash
emie@desktop-8sonn9n:~$ curl -I https://userdiag.com/download?winget
HTTP/1.1 200 OK
Date: Sat, 27 Jan 2024 00:40:24 GMT
Content-Type: application/octet-stream
Content-Length: 939952
Connection: keep-alive
content-description: File Transfer
content-disposition: attachment; filename=ud_winget.exe
content-transfer-encoding: binary
expires: 0
Cache-Control: no-store
strict-transport-security: max-age=0
referrer-policy: strict-origin-when-cross-origin
x-xss-protection: 1; mode=block
x-frame-options: sameorigin
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
CF-Cache-Status: DYNAMIC
```

**Comment by Trenly** [comment]
> I've updated the link (?winget instead of ?WinGet) It doesn't seem to be a problem now
> 
> ```shell
> emie@desktop-8sonn9n:~$ curl -I https://userdiag.com/download?winget
> HTTP/1.1 200 OK
> Date: Sat, 27 Jan 2024 00:40:24 GMT
> Content-Type: application/octet-stream
> Content-Length: 939952
> Connection: keep-alive
> content-description: File Transfer
> content-disposition: attachment; filename=ud_winget.exe
> content-transfer-encoding: binary
> expires: 0
> Cache-Control: no-store
> strict-transport-security: max-age=0
> referrer-policy: strict-origin-when-cross-origin
> x-xss-protection: 1; mode=block
> x-frame-options: sameorigin
> x-content-type-options: nosniff
> x-permitted-cross-domain-policies: none
> CF-Cache-Status: DYNAMIC
> ```

Looks like they might be blocking additional user agents now - https://github.com/microsoft/winget-pkgs/pull/136739#issuecomment-1917543551
