### ISSUE TITLE
[Update Request]: Podman Desktop

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#136426]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

RedHat.Podman-Desktop

### Package Version

1.7.0

### Please describe the changes you would like to see

There is a new release (1.7.0) available. Download Page Url: https://podman-desktop.io/downloads

**Comment by Trenly** [comment]
* Resolved by #136388
