### ISSUE TITLE
When the bot creates new manifests it should add the schema comment

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#13651]
# Description of the new feature/enhancement

In PR #13650 the bot is deleting the:
```YAML
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
```
When not only should that be preserved, the proper schema should added to any changes made by the bot.

# Proposed technical implementation details (optional)

**Comment by OfficialEsco** [comment]
Before this gets to the releases stage i want it to be normalized like this
```
# Automatically updated by the winget bot at 2021/Jul/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Ubisoft.Connect
```
instead of this
```
# Automatically updated by the winget bot at 2021/Jul/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Ubisoft.Connect
```
https://github.com/microsoft/winget-pkgs/pull/21922/files#

**Comment by denelon** [comment]
I forgot to close this one.
