### ISSUE TITLE
[Update Request]: Malwarebytes.Malwarebytes showing the wrong version

### ISSUE THREAD

**Issue by jmaraujouy** [microsoft/winget-pkgs#136644]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Malwarebytes.Malwarebytes

### Package Version

4.6.8.311

### Please describe the changes you would like to see

Latest version is *4.6.8.311*, but Winget shows version 4.6.8.370 as the latest available version.

Malwarebytes for Windows Release History:
(https://support.malwarebytes.com/hc/en-us/sections/360005863113)

**Comment by Chasapple4** [comment]
Not fixed https://github.com/microsoft/winget-pkgs/issues/138846 got info from Malwarebytes
