### ISSUE TITLE
Incorrect information in WinGet description for mRemoteNG

### ISSUE THREAD

**Issue by gnarlygeek** [microsoft/winget-pkgs#1366]
There doesn't appear to be a good place to provide feedback for inaccurate information in the WinGet results.  **That may actually be the primary issue/idea - provide a way to provide feedback regarding inaccurate information in the winget db.** Specifically, WinGet description for mRemoteNG is "The Official home of the DB Browser for SQLite" which isn't even close to the function of the app.  mRemoteNG is an RDP client also interfaces with putty to provide SSH/telnet sessions.

**Comment by denelon** [comment]
As we move towards better quality, a PR with some reference links goes a long way towards helping improve the quality of a manifest.  Creating an issue is a great way to open up the dialog. Generally, we're going to defer to the publisher for what they want to see in the descriptive meta-data in a manifest.
