### ISSUE TITLE
[Update Request]: Update TechPowerUp.GPU-Z to Version 2.57.0

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/winget-pkgs#136690]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TechPowerUp.GPU-Z

### Package Version

2.57.0

### Please describe the changes you would like to see

> * Added support for AMD Radeon RX 7600 XT, 760M (8640H), Steam Deck OLED GPU
>  * Added support for NVIDIA GeForce RTX 4070 Super, RTX 4070 Ti Super, RTX 4080 Super, RTX 4090D, Tesla T4G, A100 40 GB
>  * Fixed BIOS saving on some newer NVIDIA cards
>  * Added detection for AV1 Profile 2 in Advanced -> DXVA

**Download:**
https://www.techpowerup.com/download/techpowerup-gpu-z/

**Comment by MagicAndre1981** [comment]
@Exorcism0666 looks like the url is only valid for a short time:

```
C:\WINDOWS\system32>winget upgrade TechPowerUp.GPU-Z
Gefunden TechPowerUp GPU-Z [TechPowerUp.GPU-Z] Version 2.57.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://us1-dl.techpowerup.com/files/et38Px2tsc4RUklNJJUOwA/1706338334/GPU-Z.2.57.0.exe
Unerwarteter Fehler beim Ausführen des Befehls:
Download request status is not success.
0x8019019a : Nicht vorhanden (410).
```

**Comment by Exorcism0666** [comment]
@MagicAndre1981 If you have the permanent link for the download, i can fix that :)

**Comment by MagicAndre1981** [comment]
not really. all servers generate an url which are likely 24h valid

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 If you have the permanent link for the download, i can fix that :)

I found [mirror links](https://www.download3k.com/Install-GPU-Z.html), I'm not sure if the mods approve this unknown URL:

https://mirrors.download3k.com/Download-GPU-Z/GPU-Z.2.57.0.exe (US)
https://mirrorseu.download3k.com/Download-GPU-Z/GPU-Z.2.57.0.exe (EU)

**Comment by mdanish-kh** [comment]
@Exorcism0666 @MagicAndre1981 

The static URL is in the form `https://us2-dl.techpowerup.com/files/GPU-Z.<version>.exe`. This URL will fail for you in the browser but work for package managers such as WinGet, choco etc. See https://github.com/microsoft/winget-pkgs/issues/70469#issuecomment-1218684399 for explanation.

I've created a PR to fix this issue

**Comment by MagicAndre1981** [comment]
> @Exorcism0666 @MagicAndre1981
> 
> The static URL is in the form `https://us2-dl.techpowerup.com/files/GPU-Z.<version>.exe`. This URL will fail for you in the browser but work for package managers such as WinGet, choco etc. See [#70469 (comment)](https://github.com/microsoft/winget-pkgs/issues/70469#issuecomment-1218684399) for explanation.

I always use wget (`JernejSimoncic.Wget`) to download files on Windows and here the static url was broken with 2.57 yesterday, maybe they fixed it now.

**Comment by W1zzardTPU** [comment]
> > @Exorcism0666 @MagicAndre1981
> > The static URL is in the form `https://us2-dl.techpowerup.com/files/GPU-Z.<version>.exe`. This URL will fail for you in the browser but work for package managers such as WinGet, choco etc. See [#70469 (comment)](https://github.com/microsoft/winget-pkgs/issues/70469#issuecomment-1218684399) for explanation.
> 
> I always use wget (`JernejSimoncic.Wget`) to download files on Windows and here the static url was broken with 2.57 yesterday, maybe they fixed it now.

Did you use the correct user agent? See #70469

**Comment by MagicAndre1981** [comment]
> Software author here. Did you use the correct user agent? See #70469
> 
> If you use the default user agent it will get rejected, but when winget's user agent is detected you can download just fine from the "base" URL

I checked my command history and I used wget.exe and not my custom `wget.cmd` where I added -U command with custom user agent. With user agent download works.

**Comment by W1zzardTPU** [comment]
Awesome, thanks for confirming
