### ISSUE TITLE
support versioning: major.minor.patch.int-somestring

### ISSUE THREAD

**Issue by soloturn** [microsoft/winget-pkgs#13670]
# Description of the new feature/enhancement

currently windows packages know major.minor.patch as version and major.minor.patch.someInteger is allwoed. which is a perfect fit for a central source code repository. nowadays git is used and there is no straight versioning any more. so it would be convenient to somehow include the git-hash in the versioning scheme. well known is to add the distance since the last branch (e.g. 10 commits) and the hash. which may make something like 1.20.3-10-adsfa. or 1.20.3.10-asdfa .

please support such versions.

# Proposed technical implementation details (optional)

to not confuse too much and be compatible with what was before, allow adding a "-" and some arbitrary string, so the format is:
int.int.int.int-arbitraryString

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/981
