### ISSUE TITLE
[New Feature]: Microsoft To-do app open feature in the toolbox > windows tools section ,

### ISSUE THREAD

**Issue by suray-marag-pandit** [microsoft/winget-pkgs#137077]
### Description of the new feature/enhancement

A feature to open Microsoft To-do app from the toolbox section.

**Comment by denelon** [comment]
@suray-marag-pandit this is the WinGet community repository for manifests. I'm not sure where this request belongs. We don't have any App specific behaviors associated with WinGet. I'm also not sure which toolbox section you are referring to, but that is likely a different product team.
