### ISSUE TITLE
[Package Request]: Geeks3D.FurMark

### ISSUE THREAD

**Issue by nett00n** [microsoft/winget-pkgs#137134]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://geeks3d.com/furmark/downloads/
Publisher: Geeks3D
Package Name: FurMark
Description: FurMark is a lightweight but very intensive graphics card / GPU stress test on Windows platform. It's a quick [OpenGL benchmark](https://geeks3d.com/20120413/furmark-opengl-benchmark-scores-comparative-charts/) as well ([online scores](https://gpuscore.top/furmark/)).
FurMark is simple to use and is free.
Package Version: 1.37.2.0
Installer URL: https://geeks3d.com/downloads/2023p/FurMark_1.37.2.0_Setup.exe

**Comment by CoolPlayLin** [comment]
Hi @nett00n
It appears your package cannot download without browser
We have to click the button to download
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/bca78099-ec43-479a-a02b-93dc8afe94dd)

![image](https://github.com/microsoft/winget-pkgs/assets/96709586/6f38d6f2-8ff7-4704-9b48-64cf0ddd8ff1)

**Comment by nett00n** [comment]
Also the package is distributed on this forum https://www.majorgeeks.com/files/details/furmark.html
with link like https://files1.majorgeeks.com/10afebdbffcd4742c81a3cb0f6ce4092156b4375/benchmark/FurMark_1.37.2.0_Setup.exe

**Comment by Dragon1573** [comment]
The [installer URL](https://files1.majorgeeks.com/10afebdbffcd4742c81a3cb0f6ce4092156b4375/benchmark/FurMark_1.37.2.0_Setup.exe) from [the forum](https://www.majorgeeks.com/files/details/furmark.html) is manually checked to be valid, because the file can be downloaded with _Motrix_ without configuring any properties (except proxy server for some special reason).
