### ISSUE TITLE
[Package Request]: `GorillaDevs.Ferium`

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/winget-pkgs#137328]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

**          | **
------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Download Page Url | https://github.com/gorilla-devs/ferium/releases/tag/v4.5.0
Publisher         | https://github.com/gorilla-devs
Package Name      | `GorillaDevs.Ferium`
Description       | <blockQuote cite="https://github.com/gorilla-devs/ferium/blob/52cd45558e13dc26fc5d3dc9047c3f54a51ea00a/README.md#ferium:~:text=ferium%20is%20a%20fast%20and%20feature%20rich%20cli%20program%20for%20downloading%20and%20updating%20minecraft%20mods%20from%20modrinth%2C%20curseforge%2C%20and%20github%20releases%2C%20and%20modpacks%20from%20modrinth%20and%20curseforge.">Ferium is a fast and feature rich CLI program for downloading and updating Minecraft mods from Modrinth, CurseForge, and GitHub Releases, and modpacks from Modrinth and CurseForge.</blockQuote>
Package Version   | 4.5.0
Installer URL     | https://github.com/gorilla-devs/ferium/releases/download/v4.5.0/ferium-windows-msvc.zip

https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+ferium&type=commits returned 0 results at +2024-01-31T14:31:24+00:00.

**Comment by ST-DDT** [comment]
I'll have a look at this.

**Comment by ST-DDT** [comment]
There might be a typo here: 

````diff
-GorrilaDevs.Ferium
+GorillaDevs.Ferium
````

**Comment by ST-DDT** [comment]
One 1 `r`

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/137328#issuecomment-1925291790

Sorry, @ST-DDT. Little tired today.

**Comment by ST-DDT** [comment]
No problem. Thanks for fixing this anyway.
