### ISSUE TITLE
[Update Request]: MultiPSK

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#137439]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

F6CTE.MultiPSK

### Package Version

4.48.4.1

### Please describe the changes you would like to see

New version of [MULTIPSK](http://f6cte.free.fr/index_anglais.htm) was released. The download url did not change, just the SHA256 checksum.

**Comment by Exorcism0666** [comment]
@stephengillie Can you close this issue ?

**Comment by CoolPlayLin** [comment]
@AsciiWolf The issue should be marked as resolved

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #136067;
