### ISSUE TITLE
[Package Request]: Geeks3d.FurMark

### ISSUE THREAD

**Issue by D3strukt0r** [microsoft/winget-pkgs#137775]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.geeks3d.com/furmark/downloads/
Publisher: Geeks3D
Package Name: Geeks3d.FurMark
Description: FurMark is a lightweight but very intensive graphics card / GPU stress test on Windows platform.
Package Version: 1.37.2.0
Installer URL: https://geeks3d.com/downloads/2023p/FurMark_1.37.2.0_Setup.exe

**Comment by CoolPlayLin** [comment]
duplicate of 137134

**Comment by stephengillie** [comment]
> duplicate of #137134
