### ISSUE TITLE
[Package Request]: cppcryptfs 

### ISSUE THREAD

**Issue by eai04191** [microsoft/winget-pkgs#137818]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://github.com/bailey27/cppcryptfs/releases
Publisher:bailey27
Package Name: cppcryptfs
Description: cppcryptfs is an implementation of the gocryptfs encrypted overlay filesystem in C++ for Windows.
Package Version: 1.4.4.2
Installer URL: https://github.com/bailey27/cppcryptfs/releases/download/1.4.4.2/cppcryptfs.exe

**Comment by stephengillie** [comment]
- Depends on https://github.com/microsoft/winget-cli/issues/3017
