### ISSUE TITLE
[Package Request]: Google.Brotli

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#137904]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

- Download Page Url: https://github.com/google/brotli/releases/tag/v1.1.0
- Publisher: Google
- Package Name: Brotli
- Description:
  - Short: Brotli compression format.
  - Full:
    > Brotli is a generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling, with a compression ratio comparable to the best currently available general-purpose compression methods. It is similar in speed with deflate but offers more dense compression.
- Package Version: v1.1.0
- Installer URL:
  - `x64`: https://github.com/google/brotli/releases/download/v1.1.0/brotli-x64-windows-static.zip
  - `x86`: https://github.com/google/brotli/releases/download/v1.1.0/brotli-x86-windows-static.zip
```[tasklist]
### Tasks
- [ ] #137907
```

**Comment by Exorcism0666** [comment]
@Dragon1573 Is it a portable application or not?
