### ISSUE TITLE
[Package Issue]: SimonG4ELI.SDR-Radio

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#138357]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

SDR-Radio (latest 3.3 stable) installed using Winget does not get detected as a Winget package.

Maybe the package namespace is incorrect? The `wingetcreate` tool suggests `SDR-Radio.comLtd.SDR-Radio.comV3(64-bit)created2024-02-05_0741` as a PackageIdentifier. So maybe something like `SDR-Radio.comLtd.SDR-Radio.comV3` could work better? Also, the PackageName itself should probably be changed to `SDR-Radio.com (V3)`.

### Steps to reproduce

1. Run: `winget install SimonG4ELI.SDR-Radio`
2. Reboot the computer.
3. Run: `winget list|Select-String sdr-radio`
4. Run: `winget uninstall SimonG4ELI.SDR-Radio`

### Actual behavior

```
> winget list|Select-String sdr-radio

SDR-Radio.com (V3)                            SDR-Radio.com (V3)                             Unknown
```

```
> winget uninstall SimonG4ELI.SDR-Radio
No installed package found matching input criteria.
```

### Expected behavior

```
> winget list|Select-String sdr-radio

SDR-Radio.com (V3)                            SimonG4ELI.SDR-Radio                             3.3
```

### Environment

```raw
winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3930
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
```

**Comment by AsciiWolf** [comment]
SDR-Radio is now correctly detected as installed by Winget, however its version is still shown as Unknown and update is offered every time:

```
Name                                                       Id                                                  Version            Available      Source
SDR-Radio.com (V3)                                         SimonG4ELI.SDR-Radio                                Unknown            3.3            winget
```

This is probably because the installer does not seem to report installed version:

![screenshot](https://github.com/microsoft/winget-pkgs/assets/2339930/a17353b3-fe6a-4e01-905c-8bcf4e06e06d)

@Trenly Is there any way to workaround this? Thanks!

**Comment by Trenly** [comment]
> SDR-Radio is now correctly detected as installed by Winget, however its version is still shown as Unknown and update is offered every time:
> 
> ```
> Name                                                       Id                                                  Version            Available      Source
> SDR-Radio.com (V3)                                         SimonG4ELI.SDR-Radio                                Unknown            3.3            winget
> ```
> 
> This is probably because the installer does not seem to report installed version:
> 
> ![screenshot](https://private-user-images.githubusercontent.com/2339930/303505277-a17353b3-fe6a-4e01-905c-8bcf4e06e06d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzY5MjUsIm5iZiI6MTcwNzQzNjYyNSwicGF0aCI6Ii8yMzM5OTMwLzMwMzUwNTI3Ny1hMTczNTNiMy1mZTZhLTRlMDEtOTA1Yy04YmNmNGUwNmUwNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMjM1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxNWEwOGJlZmYyZWFjNTZjNDBiNzU5NzgzNjU1OWIwOGE1MGQ4OWM3NDdiYjMwYmE1MTBiZjZmNmY4NTc1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6i730yOmkynYG9Wnyyj1tXQsDlG52Lc4rHKNUPCw8Do)
> 
> @Trenly Is there any way to workaround this? Thanks!
> 
> By the way, SDR-Radio is not the only app that has this problem. For example, DG0JBJ.HDSDR is another.

Apps with version `Unknown` always show for upgrade because their version cannot be determined. However, they are skipped when using `winget upgrade --all`

**Comment by AsciiWolf** [comment]
That's what I thought. Thanks! I've created a ticket on the SDR-Radio.com support forum for the missing version info, so hopefully it will be added in a future release. :-)

Closing this issue since the other problem has been resolved.
