### ISSUE TITLE
[Package Issue]: Logitech.GHUB upgrading package causing uninstallation

### ISSUE THREAD

**Issue by ShockwaveNN** [microsoft/winget-pkgs#138663]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

After upgrade of package - the package is removed:

This is a log of upgrade:
```
(2/2) Found Logitech G HUB [Logitech.GHUB] Version 2024.1.5200
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  ██████████████████████████████  39.8 MB / 39.8 MB
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Successfully installed
```

During the update Logitech G Hub window opened and it asks 'Keep the settings' so it seems like calling uninstallation
After upgrade is done - package is removed (not found) - after that I need to install version again by 

```
 winget install Logitech.GHUB
Found Logitech G HUB [Logitech.GHUB] Version 2024.1.5200
```

### Steps to reproduce

Not sure how to easilty reproduce - need to install some old version, I just called an upgrade

### Actual behavior

Package is removed

### Expected behavior

Package is upgraded

### Environment

```raw
winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3085
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by ShockwaveNN** [comment]
@github-actions, nope mister bot - all those issues have problems (errors) during installation - on my system there is zero errors, but the package is gone

**Comment by BiosPlus** [comment]
This'll be why: https://github.com/microsoft/winget-pkgs/blob/efbd01069957fa9575f09e07df0efc205052e417/manifests/l/Logitech/GHUB/2024.1.5200/Logitech.GHUB.installer.yaml#L16

I'll do a PR to get that changed and see if it goes through.

**Comment by ShockwaveNN** [comment]
Thanks @BiosPlus
