### ISSUE TITLE
Validation should check for duplicate packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#13861]
# Description of the new feature/enhancement

Sometimes manifest authors aren't sure about the correct "Publisher" or "PackageName". This results in duplicate entries in the repository.

# Proposed technical implementation details (optional)

The validation pipelines should check to see if a duplicate package has been added. One possible way to do this is by checking the SHA256 to see if it already exists in the repository.  The validation pipeline could also check for a duplicate URL to an installer.

Sometimes the manifest author is correcting or improving the manifest, so this shouldn't automatically result in closing the PR. The validation pipeline could add a label like "Possible-Duplicate". Manual validation would likely be required to ensure the correct changes are made.

**Comment by jedieaston** [comment]
The only problem with using the SHA256 only is that in certain cases, we list multiple installers in a single manifest with different properties (for example, if a single installer file can be used for both user and machine level installs). Manual review to confirm it is a duplicate would be appreciated.
