### ISSUE TITLE
[Package Request]: Simon's World Map

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#138630]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.sdr-radio.com/world-map#Downloads
Publisher: Simon G4ELI
Package Name: Simon's World Map
Description: A free map of the world for radio aficionados.
Package Version: 1.4.0
Installer URL: https://www.dropbox.com/scl/fi/k8nzcys5n8pe1sc7zu7tm/Simon-s-World-Map-2024-02-04-19h24m.exe?rlkey=abskz0i1tyjgsbwlcw5pufxti&dl=1

**Comment by Dragon1573** [comment]
It seems this package only releases via [OneDrive](https://public.db.files.1drv.com/y4m1xoWOMTiL7WzJKMp3tdxmvaV9QnlC3BWetYtyUGTcUryiLojMhE-24hb986vx_vuNrYLuHuv5UNpOnASRVxXBIV2KITehwAwzd73oTDy6DTSORu9mal6HY_zeq2VPc07EiVqZkQqcRfts93o-irHe3ja7camh-LXUNyJaD7BAw71CgfFmpUHMSiFkxbUflH5dYi7s8B6QxYLmZe6k--HU_fxAtTPQ_RWy_MNXtzlhl) and [Dropbox](https://uc434ac2efdc35d4717b6531878d.dl.dropboxusercontent.com/cd/0/get/CNDhZKk7nmgkewxrnJ1li6AJexMlKtgdu5K-QlkhR7hwW18QqgcQqikauJ712z-3idYinCeRr12ZnjzSwOjiYFlwRItv1HOWWEWhxgS6BXWK1KDmcn1VOHCCilql70nGZ6UBrdZIPHwWg_qWfgxc-9mKh-pK8tV8LSFfoUNMh-I_WA/file?_download_id=9479127065560489527904434065733537783778701684594921017268962551&_notify_domain=www.dropbox.com&dl=1). Both of them are not supported by `winget.exe`.

Is there any direct link for downloading installer? Does _Dropbox_ or _OneDrive_ provides RESTful API for downloading the file by a static URL without authentication?

<details><summary>Screenshots</summary>

![PixPin_2024-02-10_23-12-01](https://github.com/microsoft/winget-pkgs/assets/49941141/47e646fd-b9cf-45bb-bcb8-1aef192d2c8a)
![PixPin_2024-02-10_23-12-22](https://github.com/microsoft/winget-pkgs/assets/49941141/c9afabc8-d683-4159-8f30-59d3107ec621)
![PixPin_2024-02-10_23-14-21](https://github.com/microsoft/winget-pkgs/assets/49941141/be52d4b4-43ce-4672-8477-609ce6586a3c)

</details>
