### ISSUE TITLE
[Package Issue]: Mozilla.Firefox 122.0.1 - packages installing wrong locales

### ISSUE THREAD

**Issue by DragRedSim** [microsoft/winget-pkgs#138703]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The latest update for the Firefox package has been created incorrectly, with all locales pointing to the CS locale for x64 installs, and for EL for both x86 and ARM; the ARM package is also pointing to the x86 version.

### Steps to reproduce

Attempt to install Firefox using WinGet.

### Actual behavior

CS locale is installed.

### Expected behavior

System locale (for me, EN-GB as the best derivative of EN-AU) is installed

### Environment

```raw
[winget --info]
Windows Package Manager (Preview) v1.7.3481-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3085
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.3481.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\David\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/122.0.1/Mozilla.Firefox.installer.yaml

Compare to https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/122.0/Mozilla.Firefox.installer.yaml

**Comment by mdanish-kh** [comment]
_Should_ be resolved now through PR https://github.com/microsoft/winget-pkgs/pull/138666. Are you able to confirm this?

**Comment by adatum** [comment]
> Should be resolved now through PR https://github.com/microsoft/winget-pkgs/pull/138666. Are you able to confirm this?

Can confirm fixed, as mentioned here: https://github.com/microsoft/winget-cli/issues/4082#issuecomment-1945270656

**Comment by DragRedSim** [comment]
Also confirming that the new manifest is working.
