### ISSUE TITLE
[Update Request]: Malwarebytes current version info is wrong

### ISSUE THREAD

**Issue by Chasapple4** [microsoft/winget-pkgs#138846]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Malwarebytes 

### Package Version

4.6.8.311

### Please describe the changes you would like to see

Verified with Malwarebytes https://twitter.com/Malwarebytes/status/1756004662245761142 that 4.6.8.311 is the current stable not 4.6.8.370 as of this issue created

**Comment by Trenly** [comment]
Raised a PR to fix
