### ISSUE TITLE
`Manifest-Metadata-Consistency` not using latest version

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#139016]
* https://github.com/microsoft/winget-pkgs/pull/138982

In the above PR, the label was applied for -
> === manifests\j\JetBrains\IntelliJIDEA\Community\2023.3.4 ===
> Missing Properties value based on version 2023.2.5:
> Scope
> ElevationRequirement

However, according to the [directory tree](https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/IntelliJIDEA/Community), version `2023.3.3` was added 3 weeks ago. The latest version should be used for ensuring manifest metadata consistency

**Comment by Trenly** [comment]
[Policy] Area validation pipelines
[Policy] Area bots

**Comment by hackean-msft** [comment]
@denelon Issue should be fixed when the existing pull requests get retriggered and for subsequent pull requests.

**Comment by denelon** [comment]
@Trenly I'll let you close this once you can confirm.

**Comment by Trenly** [comment]
Seems to be fixed
