### ISSUE TITLE
[Package Issue]: Fail run YamlCreate.ps1

### ISSUE THREAD

**Issue by kkbruce** [microsoft/winget-pkgs#139213]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Fail run YamlCreate.ps1

### Steps to reproduce

.\YamlCreate.ps1

### Actual behavior

.\YamlCreate.ps1
OperationStopped: C:\Github\winget-pkgs\Tools\YamlCreate.ps1:238
Line |
 238 |    throw [System.Net.WebException]::new('Manifest schemas could not be …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Manifest schemas could not be downloaded. Try running the script again

### Expected behavior

Gen package files.

### Environment

```raw
winget --info
Windows 封裝管理員 v1.6.3482
Copyright (c) Microsoft Corporation. 著作權所有，並保留一切權利。

Windows: Windows.Desktop v10.0.22631.3085
系統架構: X64
包裹: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget 目錄
---------------------------------------------------------------------------------------------------------------------
記錄檔                    %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputD…
使用者設定                %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.js…
可攜式連結目錄 (使用者)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可攜式連結目錄 (電腦)     C:\Program Files\WinGet\Links
可攜式封裝根目錄 (使用者) %LOCALAPPDATA%\Microsoft\WinGet\Packages
可攜式封裝根目錄          C:\Program Files\WinGet\Packages
可攜式封裝根目錄 (x86)    C:\Program Files (x86)\WinGet\Packages
安裝程式下載              %USERPROFILE%\Downloads

連結
------------------------------------------------------------------------
隱私權聲明       https://aka.ms/winget-privacy
授權合約         https://aka.ms/winget-license
第三方聲明       https://aka.ms/winget-3rdPartyNotice
首頁             https://aka.ms/winget
Windows 市集條款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理員設定                                州
----------------------------------------------
LocalManifestFiles                        停用
BypassCertificatePinningForMicrosoftStore 停用
InstallerHashOverride                     停用
LocalArchiveMalwareScanOverride           停用
```

**Comment by Trenly** [comment]
Try pulling the latest changes down into your master branch. There was a bug which was fixed that caused this error due to incorrect URL parsing

**Comment by kkbruce** [comment]
@Trenly 

I got same error.

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/75790626-e9cf-425b-abf2-e0dcd9f1bfa7)

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/f5eb27b7-5273-4029-ae48-d027b2ea9f18)

**Comment by Trenly** [comment]
Have you pulled the latest changes down to your local? Even though your branch is updated in GitHub, it may be possible that your local copy also needs to be synced

**Comment by kkbruce** [comment]
local is up to date:

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/07d156da-b57a-4443-936c-585dc57f12b8)

check `ScriptHeader`:

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/753d5362-8ff1-4ea8-a3cd-a4d54d85f2c1)

**Comment by ImJoakim** [comment]
The result appears to be different when using PowerShell 7 compared to PowerShell 5.

PowerShell 5:
 
![image](https://github.com/microsoft/winget-pkgs/assets/52826317/2ad63620-de0e-4daa-9712-f9789c439d75)

![image](https://github.com/microsoft/winget-pkgs/assets/52826317/935c6573-6888-400e-9755-5d3a6be7276b)

PowerShell 7:

![image](https://github.com/microsoft/winget-pkgs/assets/52826317/cbabdb4a-e0f4-44f5-814c-f30f15bdf62e)

![image](https://github.com/microsoft/winget-pkgs/assets/52826317/8cfc5404-2c21-4f2a-8e9d-81c731563c9e)

**Comment by Trenly** [comment]
Oh how fun. PS7 changed how they handle the return object for WebRequest. 

I should be able to find a fix for it
