### ISSUE TITLE
[Package Issue]: OPenRCT2.OpenRCT2 upgrade loop with 0.4.6

### ISSUE THREAD

**Issue by markusdd** [microsoft/winget-pkgs#139970]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

identical to issue #94743 , 0.4.6 PR is [#118921](https://github.com/microsoft/winget-pkgs/pull/118921)

There is an update loop from 0.4.5 to 0.4.6

### Steps to reproduce

try upgrade 0.4.5 to 0.4.6

### Actual behavior

upgarde runs, but package again gets offered as updateable

### Expected behavior

upgrade, and do not offer for upgrade again

### Environment

```raw
winget --info
Windows-Paket-Manager v1.6.3482
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.3155
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3482.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               F:\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by markusdd** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> ### Closed similar issues:
> 
>     * [[Package Issue]: OpenRCT2.OpenRCT2 wrong version advertisement leads to update loop (#94743)](https://github.com/microsoft/winget-pkgs/issues/94743),  similarity score: 0.81
> 
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

useless, I even quoted this issue but this is obv not for the same version...

**Comment by mdanish-kh** [comment]
Can you share the output of `winget list openrct2`?

**Comment by markusdd** [comment]
> Can you share the output of `winget list openrct2`?

sure, here you go:

```
PS C:\> winget list openrct2
Name                         ID                Version Verfügbar Quelle
-----------------------------------------------------------------------
OpenRCT2 0.4.5master-76ca840 OpenRCT2.OpenRCT2 0.4.5   0.4.6     winget
```

I think this is very much related to what we saw last time, the ID string is not just the version but some previous version with a branch and hash name.

Very much looks like the issue we had back then in the issue linked above.

**Comment by markusdd** [comment]
Just cross-checked the releases-section, the winget repo is indeed behind a lot: https://github.com/OpenRCT2/OpenRCT2/releases

**Comment by markusdd** [comment]
ok so I just think the hash is wrong in the latest 0.4.6 commit here.
![grafik](https://github.com/microsoft/winget-pkgs/assets/25175069/e15ce3b4-9b57-4116-9cde-077d74857d98)

it's supposed to be `b40b5da`, but the PR mentioned above has this:
![grafik](https://github.com/microsoft/winget-pkgs/assets/25175069/c4f7a2ad-8334-40c1-810f-91422922f61b)

And all later versions  have not been added. any automation that broke?

**Comment by mdanish-kh** [comment]
That's not the issue I believe; It appears to be an installer issue. If you install the package manually from https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.6/OpenRCT2-0.4.6-windows-installer-x64.exe in a clean VM or sandbox, it'll actually write an older version `0.4.5master-76ca840` to the Registry / Control Panel / Apps&Features. This should be reported to the publisher to update the DisplayVersion string written to registry.

[Policy] Installer-Issue
[Policy] Area-External

**Comment by mdanish-kh** [comment]
Looks like `0.4.8` is writing the correct version to the Control Panel. I'll make a PR for that and remove `0.4.6`

**Comment by markusdd** [comment]
0.4.7 works as well.

any idea why they have not been added for so long? Isn't this automatic?

**Comment by mdanish-kh** [comment]
> 0.4.7 works as well.
> 
> any idea why they have not been added for so long? Isn't this automatic?

Most packages are updated by the community. If you find a package outdated, you can create an issue for it to let contributors know that it's outdated or even better if you wish, you can submit a PR yourself. If you know the publisher, you can reach out to them to use manifest creator tools like [wingetcreate](https://github.com/microsoft/winget-create/blob/main/README.md#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline) / [Komac](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-) and set-up CI that can automate the releases to the community repository.

**Comment by markusdd** [comment]
did you use Komac just now to create the PR so quickly?

I have no issue to submit myself if I know how to do it.

**Comment by mdanish-kh** [comment]
It was this one-liner 😄 

```
wingetcreate update OpenRCT2.OpenRCT2 --version 0.4.8 --urls "https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.8/OpenRCT2-0.4.8-windows-installer-win32.exe" "https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.8/OpenRCT2-0.4.8-windows-installer-x64.exe" "https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.8/OpenRCT2-0.4.8-windows-installer-arm64.exe" --submit --replace
```

Made a search with `wingetcreate show OpenRCT2.OpenRCT2 -i` first to get the old URLs and replace `0.4.6` with `0.4.8`

**Comment by markusdd** [comment]
I see. very helpful!

Will suggest this over at OpenRCT2

**Comment by mdanish-kh** [comment]
> I have no issue to submit myself if I know how to do it.

You can learn how to contribute by going through the contributing docs in this repo, or if you prefer video format, you can check out these Open at microsoft episodes
- [Contributing to Windows Package Manager](https://learn.microsoft.com/en-us/shows/open-at-microsoft/contributing-to-windows-package-manager)
- [WingetCreate: Keeping WinGet packages up-to-date](https://learn.microsoft.com/en-us/shows/open-at-microsoft/wingetcreate-keeping-winget-packages-up-to-date)

**Comment by markusdd** [comment]
I just tried and yes, it updated from 0.4.7 to 0.4.8 and does not get re-offered.

I opened the suggestion ticket over at OpenRCT2 to provide the manifests.

Thank you!

**Comment by markusdd** [comment]
closing as resolved as far as winget goes.
