### ISSUE TITLE
[Package Issue]: Microsoft.DotNet.SDK.8 version 8.0.201 does not replace/uninstall previous version 8.0.101

### ISSUE THREAD

**Issue by slowthgt** [microsoft/winget-pkgs#139949]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

When upgrading the `Microsoft.DotNet.SDK.8` to `8.0.201` from `8.0.101` using `winget install -i -e --id Microsoft.DotNet.SDK.8` the previous version is not uninstalled/replaced and the command `winget list --upgrade-available` will still list the package to be updated.

### Steps to reproduce

- `winget install -i -e --id Microsoft.DotNet.SDK.8 -v 8.0.101`
- `winget install -i -e --id Microsoft.DotNet.SDK.8`
- `winget list --upgrade-available` where you can observe the old entry still showing and asking for upgrade.
- Check Apps and Features and observe both packages installed.

### Actual behavior

winget/SDK installer fails to remove/replace the previous SDK version.

### Expected behavior

Only the most recent SDK installation remain on the computer.

### Environment

```raw
Windows Package Manager v1.6.3482
Windows: Windows.Desktop v10.0.19045.4046
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Trenly** [comment]
This is how the .NET SDK installer is designed. Winget only downloads and runs the installer. This would be an issue for the .NET team to address

**Comment by slowthgt** [comment]
> This is how the .NET SDK installer is designed. Winget only downloads and runs the installer. This would be an issue for the .NET team to address

Couldn't we technically just switch to Uninstall to Install instead of replacement? (Not sure if I'm making myself clear, but can't remember the names from yamlcreate)

**Comment by MagicAndre1981** [comment]
the first number shows the feature level (100 shows first release, 200 the second with new features) and later patches for that level increases last part (8.0.201 is patch to 200 feature level) and here the older SDK for that feature level get removed)
