### ISSUE TITLE
[Update Request]: Parsec.parsec 

### ISSUE THREAD

**Issue by Trouffman** [microsoft/winget-pkgs#140065]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Parsec.Parsec

### Package Version

150.92.1.0

### Please describe the changes you would like to see

Winget infos (at ticket creation date)
Version 150-90d
Hash : 

New version :
Source : https://builds.parsec.app/package/parsec-windows.exe (same as now.)
PackageVersion: 150.92.1.0

**Comment by stephengillie** [comment]
Wingetbot has been suggesting this version for some time, but the version schema change hadn't been verified before now.
