### ISSUE TITLE
[Update Request]: Termius 8.8.3 -> 8.9.7

### ISSUE THREAD

**Issue by Trouffman** [microsoft/winget-pkgs#140062]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Termius.Termius

### Package Version

8.9.7

### Please describe the changes you would like to see

It's been couple weeks that the winget installation of Termius is not succeeding to "hash mismatch" This is because there is a new version.

As of 5 min ago 8.9.7
Source : https://autoupdate.termius.com/windows/Install%20Termius.exe
(Same source used in Winget)

PackageVersion: 8.9.7
InstallerSha256: B159761B935B8900DA7DD255B75788C23F435E9F484E4FC38856EDD4BAB3FAEA

**Comment by mherrmann** [comment]
Hello, if this is a frequent pain point for you, then we now have a service that fixes the "hash mismatch" problem once and for all: https://winget.pro/pkgs-winget-installer-hash-does-not-match/

**Comment by BiosPlus** [comment]
For future ref since this uses a vanity URL, it's going to run into issues quite often where the hash of the installer wont match. This can be solved for by installing via the ms store version: `winget install 9nk1gdvpx09v`

**Comment by SpecterShell** [comment]
https://autoupdate.termius.com/windows/latest.yml
