### ISSUE TITLE
[Package Issue] Typo: Kubernates.kwok

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#140049]
## Description

This is an issue about typo (word spelling). This should not affect users (I think).

> Hi, the Kubernates is a typo.
>
> _Originally posted by @wzshiming in https://github.com/microsoft/winget-pkgs/issues/130691#issuecomment-1951645517_
            
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/140050
```

**Comment by wzshiming** [comment]
[Kubernates.kwokctl](https://github.com/microsoft/winget-pkgs/pull/130692) is also a typo.

**Comment by Dragon1573** [comment]
> [Kubernates.kwokctl](https://github.com/microsoft/winget-pkgs/pull/130692) is also a typo.

It was fixed directly in the pull request by commit https://github.com/microsoft/winget-pkgs/commit/8ebd2157bc193d6de6fdc09cd0876a1b8bf0ba15
