### ISSUE TITLE
[Package Issue]: Rufus.Rufus odd package behavior?

### ISSUE THREAD

**Issue by Spunkie** [microsoft/winget-pkgs#140674]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I ran `winget install Rufus.Rufus` and the version that it installed didn't show up when I searched rufus in windows search. If I then try to run `rufus` in terminal it opens up a version of rufus but the program also tries to run a 2nd cmd itself. 

It runs `rufus.com` which is obviously not a valid cmd but also it's not even a valid website for the rufus project. Searching "rufus.com" in windows search reveals a malformed shortcut/link to app called rufus.com.

### Steps to reproduce

1. Uninstall the mstore Rufus
2. Open terminal
3. Run `winget install Rufus.Rufus`

### Actual behavior

Missing app links in search, unexpected behavior, and links to illegitimate websites.

### Expected behavior

No unexpected behavior, any links would go to the official site([rufus.ie](https://rufus.ie)), start menu links exist.

### Environment

```raw
PS C:\Users\micha> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs
![image](https://github.com/microsoft/winget-pkgs/assets/1653976/164a561e-2f18-4019-b48d-a3cbc439b184)

**Comment by Trenly** [comment]
This is a behavior of the executable itself, and not of WinGet. If you download the binary directly from https://github.com/pbatard/rufus/releases/download/v4.4/rufus-4.4.exe and then run it from the command line, the same thing happens

![image](https://github.com/microsoft/winget-pkgs/assets/12611259/3f7309d8-a5c0-4834-8a29-7b18f1e12b5c)
