### ISSUE TITLE
[Package Request]: NVIDIA.app

### ISSUE THREAD

**Issue by 250h** [microsoft/winget-pkgs#140696]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.nvidia.com/en-us/software/nvidia-app/
Publisher: NVIDIA Corporation
Package Name: NVIDIA app
Description: The NVIDIA app is the essential companion for PC gamers and creators. Keep your PC up to date with the latest NVIDIA drivers and technology.
Package Version: 10.0.0.499
Installer URL: https://us.download.nvidia.com/nvapp/client/10.0.0.499/NVIDIA_app_beta_v10.0.0.499.exe

**Comment by regunakyle** [comment]
This should not be blocked by "hardware requirement": GeForce Experience is already in the official repo, so the Nvidia App should get the same treatment.

GeForce Experience is nowdeprecated in favor of Nvidia App, so far none of the major package managers in Windows provide this app, it would be great if Winget support it first (and also remove Geforce Experience from the repo, or redirect `Nvidia.GeForceExperience` to Nvidia App, I guess).

**Comment by emilwojcik93** [comment]
I have developed a temporary solution for the missing Nvidia App package in the winget repository. This solution is available in the following GitHub Gist: [Install-NvidiaApp.ps1](https://gist.github.com/emilwojcik93/788eca2e456488c360fabc15d274031d#file-install-nvidiaapp-ps1).

The script scrapes the official Nvidia App page for the latest version and automatically installs the Nvidia App silently. It includes a PowerShell Synopsis Help Note for ease of use.

You can execute the script directly from the internet using the command described in my comment [here](https://gist.github.com/emilwojcik93/788eca2e456488c360fabc15d274031d?permalink_comment_id=5294025#gistcomment-5294025).

Best regards,
emilwojcik93

**Comment by regunakyle** [comment]
> I have developed a temporary solution for the missing Nvidia App package in the winget repository. This solution is available in the following GitHub Gist: [Install-NvidiaApp.ps1](https://gist.github.com/emilwojcik93/788eca2e456488c360fabc15d274031d#file-install-nvidiaapp-ps1).
> 
> The script scrapes the official Nvidia App page for the latest version and automatically installs the Nvidia App silently. It includes a PowerShell Synopsis Help Note for ease of use.
> 
> You can execute the script directly from the internet using the command described in my comment [here](https://gist.github.com/emilwojcik93/788eca2e456488c360fabc15d274031d?permalink_comment_id=5294025#gistcomment-5294025).
> 
> Best regards,
> emilwojcik93

On a related note: Nvidia does not provide a static URL that points to the latest version of Nvidia App. 
I have asked them about this but they didn't do anything 🤷‍♂️

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Comment by jo-chemla** [comment]
@denelon If I submit a manifest file PR for Nvidia.App package, would the PR get merged if it passes checks?

**Comment by KamiCrit** [comment]
Would be great to see this added to winget.

**Comment by ZCban** [comment]
Install whit winget cudatoolkit and auto install nvidia app

**Comment by eksime** [comment]
@regunakyle

> On a related note: Nvidia does not provide a static URL that points to the latest version of Nvidia App.

Looking at requests from the updater, it seems like you can get the latest installer url from:

https://ota.nvidia.com/NvApp/v1.0/self-update/?%7B%22version%22%3A%2210.0.0.000%22%2C%22channel%22%3A%22Official%22%2C%22osVersion%22%3A%2211.0%22%7D

(url param is `{"version":"10.0.0.000","channel":"Official","osVersion":"11.0"}` url-encoded)

**Comment by DandelionSprout** [comment]
I've been able to add it to the 3rd-party Winget source [winget-extras](https://github.com/pl4nty/winget-extras) by [pl4nty](https://github.com/pl4nty) now, at least:

`winget source add --name winget-extras --type Microsoft.PreIndexed.Package --arg https://winget.tplant.com.au/cache; winget install Nvidia.NVIDIAApp`
