### ISSUE TITLE
[Package Issue]: Obsidian.Obsidian - winget uses 'wrong' version for tracking

### ISSUE THREAD

**Issue by jrdodds** [microsoft/winget-pkgs#140743]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

`winget list --id Obsidian.Obsidian` reports

```
Name     Id                Version Available Source
---------------------------------------------------
Obsidian Obsidian.Obsidian 1.5.3   1.5.8     winget
```

The [Obsidian](https://obsidian.md/) application itself reports that it is version 1.5.8 and is up to date. However, the application also reports that its installer version is 1.5.3.

![Screenshot 2024-02-23 083605](https://github.com/microsoft/winget-pkgs/assets/1728516/3a19180d-f1e2-4d2e-a034-d5c006e0e803)

It would appear that winget is using the 'wrong' version.

### Steps to reproduce

1. Download an older release from [obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases).
2. Launch Obsidian. Open Settings -> General. Note that the 'current version' and 'installer version' match.
3. Click the "Check the updates" button and update to the current release.
4. Run `winget upgrade`. Note that Obsidian is reported as having an upgrade.

### Actual behavior

It appears that [Obsidian](https://obsidian.md/) versions the application and the application installer and that winget is incorrectly using the application installer version and then incorrectly reporting an upgrade.

### Expected behavior

winget should track the application version, not the installer version.

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by jrdodds** [comment]
`winget list Obsidian`

```
Name     Id                Version Available Source
---------------------------------------------------
Obsidian Obsidian.Obsidian 1.5.3   1.5.8     winget
```

**Comment by Trenly** [comment]
Interesting. Sometimes the list by ID and list by name have different results, so them being the same rules out a couple of potential issues.
