### ISSUE TITLE
[Package Issue]: Sogou.SogouInput version 14.2.0.8968

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#140704]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

`winget.exe` is blocked by the installer URL and get `HTTP 403 Forbidden`.

### Steps to reproduce

> [!TIP]
>
> See **Actual behavior** section for more details.

### Actual behavior

```text
# Proxy enabled
pwsh> winget download -e Sogou.SogouInput
已找到 搜狗输入法 [Sogou.SogouInput] 版本 14.2.0.8968
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://ime.sogoucdn.com/sogou_pinyin_14.2.0.8968.exe
执行此命令时发生意外错误：
InternetOpenUrl() failed.
0x80072efd : unknown error

# Proxy disabled
pwsh> winget download -e Sogou.SogouInput
已找到 搜狗输入法 [Sogou.SogouInput] 版本 14.2.0.8968
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://ime.sogoucdn.com/sogou_pinyin_14.2.0.8968.exe
执行此命令时发生意外错误：
Download request status is not success.
0x80190193 : �ѽ�ֹ(403)��
```

### Expected behavior

Package successfully downloaded.

### Environment

```raw
D:\Workloads> winget --info
Windows 程序包管理器 v1.7.10514
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22631.3085
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.22.10514.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   D:\Applications\WinGet\Packages\Users\
可移植包根目录         D:\Applications\WinGet\Packages\Machine\
可移植包根目录 (x86)   D:\Applications\WinGet\Packages\Machine\
安装程序下载           D:\Dragon1573\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已启用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已启用
```

### Screenshots and Logs

- [WinGet-2024-02-23-14-40-13.893.log](https://github.com/microsoft/winget-pkgs/files/14382312/WinGet-2024-02-23-14-40-13.893.log)
- [WinGet-2024-02-23-14-40-46.418.log](https://github.com/microsoft/winget-pkgs/files/14382319/WinGet-2024-02-23-14-40-46.418.log)
- [WinGet-2024-02-23-14-42-52.260.log](https://github.com/microsoft/winget-pkgs/files/14382338/WinGet-2024-02-23-14-42-52.260.log)

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a0dc7db4-ad18-496e-9cd2-63fe0764c628)

**Comment by Dragon1573** [comment]
Seems _Sogou_ move their domain from public `ime.sogoucdn.com` to encrypted `ime-sec.gtimg.com`. The installer URL various each time.

```text
https://ime-sec.gtimg.com/202402231511/6ed060e3907bb1ea691e63e458b1c5af/pc/dl/gzindex/1708350902/sogou_pinyin_14.2a.exe
                          ^            ^
                          |            Randomly generated token?
                          Timestamp in minutes
```

Shall we remove this package manifest and instruct other users to download the package from [Microsoft Store](https://apps.microsoft.com/store/detail/XP8LJRRT557RDL)?

**Comment by SpecterShell** [comment]
The publisher uses vanity links for all their products on the homepages regardless of the domain. Currently I am using the static URLs I found on another domain for these packages.

The URLs for the last two versions of the installers appear to have been removed but the remaining ones still work though.

**Comment by Dragon1573** [comment]
Both version `14.1.0.8858` and `14.2.0.8968` response _HTTP 403 Forbidden_. The latest valid version is `13.13.0.8820`. Shall we remove them?

**Comment by Dragon1573** [comment]
Seems this problem can't be easily resolved by us, this issue will be closed as not planned.
