### ISSUE TITLE
How did my project get here? (General Licensing Question)

### ISSUE THREAD

**Issue by Pololot64** [microsoft/winget-pkgs#14083]
I was reading the terms outlined [here](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) and was confused.

In number three it says:
```Originality of Work. You represent that each of Your Submissions is entirely Your original work. Should You wish to Submit materials that are not Your original work, You may Submit them separately to the Project if You (a) retain all copyright and license information that was in the materials as You received them, (b) in the description accompanying Your Submission, include the phrase “Submission containing materials of a third party:” followed by the names of the third party and any licenses or other restrictions of which You are aware, and (c) follow any other instructions in the Project’s written guidelines concerning Submissions.```

Suppose someone uploaded a link to someone else's code here without consent. How does that work? Even if the code is open source, it seems a little unclear.

**Comment by denelon** [comment]
The content you are quoting comes from the CLA. 

With respect to a "manifest" in this repository, This applies to the file you are creating and/or submitting.

You are not submitting the "installer" to this repository, just the URL that is publicly available.
