### ISSUE TITLE
Error 0x80d03002

### ISSUE THREAD

**Issue by eglyn** [microsoft/winget-pkgs#14080]
Hello all, 
I just proceed to the update with last version, and I have this error when I want to install a software: 

```
PS C:\windows\system32> winget install firefox
Trouvé Mozilla Firefox [Mozilla.Firefox]
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/88.0.1/win64/en-US/Firefox%20Setup%2088.0.1.msi
Une erreur inattendue s'est produite lors de l'exécution de la commande :
0x80d03002 : unknown error
```

I did not find anything about the error 0x80d03002 on Google, any idea ? 

thx !

**Comment by OfficialEsco** [comment]
```
PS C:\Users\Esco> winget install firefox
Found Mozilla Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/88.0.1/win64/en-US/Firefox%20Setup%2088.0.1.msi
  ██████████████████████████████  53.9 MB / 53.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
I think i've maaaybe seen this error code before, can you try again?

**Comment by denelon** [comment]
@eglyn is this an enterprise managed machine?

**Comment by eglyn** [comment]
> 
> 
> @eglyn is this an enterprise managed machine?

Yes, but it's a VM test wich has local admin right, but still connected to a domain.

**Comment by mchubby** [comment]
```posh
start ($env:LOCALAPPDATA + 'Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir')
```

The logs said:
```
2021-05-29 15:25:01.699 [CORE] DeliveryOptimization downloading from url: https://github.com/mcmilk/7-Zip-zstd/releases/download/19.00-v1.4.5-R2/7z19.00-zstd-x64.exe
2021-05-29 15:25:01.706 [FAIL] C:\BA\311\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(24)\AppInstallerCLI.exe!00007FF60A1BE5C3: (caller: 00007FF60A17BD68) Exception(1) tid(4b2c) 80D03002 
```

So in my case it has to do with the delivery optimization service.
`Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config' -Name DODownloadMode` returns 0.

`Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings'
 -Name DownloadMode` is 0 too.

I will try and logoff/reboot after renaming those registry values and see if it unblocks the Settings app.

**Comment by eglyn** [comment]
@mchubby I will test this on next monday :)

**Comment by eglyn** [comment]
I do not have this 2 keys: 
- HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config
- HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Settings

![image](https://user-images.githubusercontent.com/24936778/120151686-da123100-c1ec-11eb-9e95-2f3f971cadf5.png)

and in the setting windows: 
![image](https://user-images.githubusercontent.com/24936778/120151725-e7c7b680-c1ec-11eb-9479-796c38305ece.png)

**Comment by mchubby** [comment]
Alright, rename or delete that setting and see if it the Settings page is no longer grayed out. I also had this setting set to 0x64

**Comment by denelon** [comment]
There is another option here. It seems we've run into this on a few machines. You can configure the "network" provider in your `winget settings`.

```JSON
    "network": {"downloader": "wininet"},
```

The three settings are listed in the JSON schema. This essentially tells the Windows Package Manager to use the WININET API to download packages rather than Delivery Optimization (the default).

**Comment by eglyn** [comment]
> 
> 
> There is another option here. It seems we've run into this on a few machines. You can configure the "network" provider in your `winget settings`.
> 
> ```json
>     "network": {"downloader": "wininet"},
> ```
> 
> The three settings are listed in the JSON schema. This essentially tells the Windows Package Manager to use the WININET API to download packages rather than Delivery Optimization (the default).

that works ! thank you :) :)
