### ISSUE TITLE
[Package Request]: VLC media player nightly-win64-arm

### ISSUE THREAD

**Issue by ArmandDelessert** [microsoft/winget-pkgs#140895]
# VLC 4.0 for Windows (ARM64), built with LLVM

- [VLC media player nightly builds](https://nightlies.videolan.org/)
- [Repository for Windows (ARM64) nightly builds](https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/)

### How can we help?

None. I would do it myself.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/
Publisher: VideoLAN
Package Name: VLC media player
Description: VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files, and various streaming protocols.
Package Version: 20240225-0427
Installer URL:
- https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/20240225-0427/vlc-4.0.0-dev-win64-d58a95d8.msi
- https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/20240225-0427/vlc-4.0.0-dev-win64-d58a95d8.exe

**Comment by R-Adrian** [comment]
i'm opposed to this, can we please stop adding nightly or fast-evolving beta versions of random softwares already?

at the snail pace that winget is moving with most approvals, by the time a particular nightly build is approved it is already obsolete as there are multiple newer builds available.
case in point: the same VLC nightly builds: https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/
thus the pull request for 20240225-0427 is already obsolete.
Q.E.D.
