### ISSUE TITLE
[Package Issue]: SDCC.SDCC REMOVES PATH ENV when installed

### ISSUE THREAD

**Issue by zerodegress** [microsoft/winget-pkgs#140990]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installing SDCC.SDCC REMOVES PATH ENV in user(not the system).

### Steps to reproduce

Note: Please be careful to reproduce it.
Just install SDCC.SDCC.

### Actual behavior

The PATH in user env gone.

### Expected behavior

Just append the SDCC to PATH(system) safely.

### Environment

```raw
Windows Package Manager: v1.6.3482
Windows: Windows.Desktop v10.0.22631.3155
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Trenly** [comment]
[Policy] Installer issue

This is caused by the SDCC installer itself. Since it is an exe, winget just downloads and runs the installer. A bug should be filed with the creators of SDCC
