### ISSUE TITLE
[Package Issue]: KDE.Kdenlive 23.08.4 -> 23.08.5

### ISSUE THREAD

**Issue by rumplin** [microsoft/winget-pkgs#141108]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I have Kdenlive installed 23.08.5, winget shows it's 23.08.4 and offers me an update.

### Steps to reproduce

I have Kdenlive installed 23.08.4
Do winget upgrade KDE.Kdenlive
Installation finishes
winget still shows that I have 23.08.4 installed and there is a new version ready.
I check version in Kdenlive in the About window, it shows 23.08.5 version.

I uninstalled Kdenlive and reinstalled with winget, still having the same issue.

### Actual behavior

winget keeps offering me the 23.08.5 update

### Expected behavior

winget doesn't offer me an update, because I already have 23.08.5 installed.

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled

Other software:
WingetUI
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/35449956/861f0383-96db-43fc-894d-754ed7c3d6ca)
![image](https://github.com/microsoft/winget-pkgs/assets/35449956/6e55650a-45d1-4ecd-abbf-a43eff6fbb6f)

**Comment by ericswpark** [comment]
@stephengillie this is still an issue, the upgrade entry still shows up for me. Is the fix not deployed yet?

**Comment by stephengillie** [comment]
Hi @ericswpark,

What version does it show as installed and what version is offered as an upgrade? Could you paste the output? 

The installer with `23.08.5` in the name installed `23.08.4` in a Windows 10 VM for me.

**Comment by ericswpark** [comment]
@stephengillie sure, here's the output:

```powershell
PS C:\Users\erics> winget upgrade
Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 122.0.2365.66 122.0.2365.80 winget
kdenlive       KDE.Kdenlive   23.08.4       23.08.05      winget
2 upgrades available.
```
This is after I tried uninstalling and re-installing Kdenlive. When I launch it it says the version is .5.
