### ISSUE TITLE
Unable to create PR due to "Validation failed: must be a collaborator"

### ISSUE THREAD

**Issue by mausam-patel** [microsoft/winget-pkgs#141391]
### Discussed in https://github.com/microsoft/winget-pkgs/discussions/141390

<div type='discussions-op-text'>

<sup>Originally posted by **mausam-patel** February 28, 2024</sup>
I am trying to open a PR to merge a branch from a forked repo into this repo. An example PR of this previously with the same source/target branches is 
https://github.com/microsoft/winget-pkgs/pull/86812. However, I am receiving the following error: 

`Pull request creation failed. Validation failed: must be a collaborator`

Have there been any changes to the contributions policy or permissions? Any insight/assistance would be helpful! </div>

**Comment by Trenly** [comment]
There have been no changes as far as I know. Perhaps your collaborator access on splunk/winget-pkgs has changed. I have been able to raise PRs from my own forks without issue

**Comment by mausam-patel** [comment]
Yup, seems that my collaborator access on splunk/winget-pkgs changed. Thanks
