### ISSUE TITLE
[Update Request]: GIMP.GIMP version 2.10.36 installer revision 1

### ISSUE THREAD

**Issue by drshtmstry** [microsoft/winget-pkgs#141573]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GIMP.GIMP

### Package Version

2.10.36 installer revision 1

### Please describe the changes you would like to see

Updated on 2024-02-29: GIMP 2.10.36 installer revision 1
Add missing OpenEXR libraries

URL: https://download.gimp.org/gimp/v2.10/windows/gimp-2.10.36-setup-1.exe

**Comment by Exorcism0666** [comment]
@stephengillie @drshtmstry 

Resolve: https://github.com/microsoft/winget-pkgs/pull/141575
