### ISSUE TITLE
[Package Request]: ATOK for Windows

### ISSUE THREAD

**Issue by AioiLight** [microsoft/winget-pkgs#141585]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://mypassport.atok.com/install/install_win.html
Publisher: JustSystems Corporation
Package Name: JustSystems.ATOK
Description: A Japanese input method system
Package Version: 34.2
Installer URL: https://gate.justsystems.com/download/atok/ut/win/at34_2.exe

**Comment by Exorcism0666** [comment]
I think it will be almost impossible to put it on for winget, unfortunately.
