### ISSUE TITLE
Hasleo EasyUEFI Request

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#14168]
PackageIdentifier: Hasleo EasyUEFI
PackageVersion: 4.6
PackageLocale: en-US
Publisher: Hasleo
PackageName: Hasleo
License: Proprietary
ShortDescription: this app is for managing UEFI and partition for Windows
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://www.easyuefi.com/downloads/EasyUEFI_Trial.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by OfficialEsco** [comment]
Hmm this might have a problem with the validation
![image](https://user-images.githubusercontent.com/15158490/120167049-91af3f00-c1fd-11eb-9840-0e95bf3139c6.png)

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
