### ISSUE TITLE
Feem Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#14163]
PackageIdentifier:   Feem
PackageVersion:      4.3.0 beta
PackageLocale:       en-US
Publisher:           Feeperfect AG
PackageName:         Feem
License:             Proprietary
ShortDescription:    Feem is the app for sync between phone and PCs
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://f000.backblazeb2.com/file/feemdownloads/Feem_v4.3.0_beta_Windows_Installer.exe.zip
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by OfficialEsco** [comment]
Blocked by microsoft/winget-cli#859
