### ISSUE TITLE
[Package Request]: FTP Manager Lite

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#141603]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.deskshare.com/ftp-manager-free.aspx
Publisher: DeskShare Incorporated
Package Name: FTP Manager Lite
Description: Free FTP Client for Windows.
Package Version: 2.54
Installer URL: https://www.deskshare.com/download/fml/FTPManagerLite.exe

**Comment by Exorcism0666** [comment]
sorry I published it in the wrong repo, plus YamlCreate is complicated to manage 😭 .
