### ISSUE TITLE
Qoppa PDF Studio Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#14169]
PackageIdentifier:   Qoppa PDF Studio
PackageVersion:      6.0
PackageLocale:       en-US
Publisher:           Qoppa
PackageName:         Qoppa PDF Studio
License:             Proprietary
ShortDescription:    this app is for editing and reading pdf
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://download.qoppa.com/pdfstudio/PDFStudio_win64.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by denelon** [comment]
@dtantono I see you've submitted several requests to add packages with the URL. Have you tried the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create)?

**Comment by dtantono** [comment]
I am happy to contribute. But, winget still has a serious drawback like installation within zip file is not possible at this moment. is thatso?

**Comment by denelon** [comment]
We have not implemented support for .zip, standalone .exe, or an installer inside of a .zip.

Be sure to add your 👍 to those issues to help raise priority.

**Comment by KaranKad** [comment]
Done #14363

**Comment by Trenly** [comment]
@denelon Per the above comment, I believe this issue can be closed
