### ISSUE TITLE
PCloud Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#14162]
PackageIdentifier:   PCloud
PackageVersion:      3.10.4
PackageLocale:       en-US
Publisher:           PCloud AG
PackageName:         Pcloud
License:             Proprietary
ShortDescription:    Pcloud brings the team together, wherever you are.
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://p-def7.pcloud.com/cBZxU1NhDZo9pE8TZQwBrZXZl7rpv7ZAkZZ6RFZkZFATNkZuzZKFZ8JZFFZvJZHzZSVZ4pZiFZ2zZ0zZopZipZvHZ5wSDXZDcP44s4FiqH3kn0AVhV8QuDHtLO7/pCloud_Windows_3.10.4_x64.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by iDolmatov** [comment]
InstallerUrl - incorrect, the site generate temp links.
Can't create repository for PCloud.

**Comment by dtantono** [comment]
I suppose this one (https://www.pcloud.com/how-to-install-pcloud-drive-windows.html?download=windows-10-64bit) is better

**Comment by iDolmatov** [comment]
This is the page that generates links. You will not be able to download the application file via winget, aria, etc. using this link.
Try contacting support PCloud for a permanent direct download link. It could be a link that redirects to a different temporary link, but without using the web design (backend only).

**Comment by dtantono** [comment]
I asked them today and they said that they don't have it

**Comment by GeorgeCY2** [comment]
https://p-lux4.pcloud.com/cBZxU1NhDZo9pE8TZZZiXDzv7ZAkZZH4XZkZFATNkZuzZKFZ8JZFFZvJZHzZSVZ4pZiFZ2zZ0zZopZipZvHZ5wSDXZS93Og51p55SNgxjR8GFxo0GJ6W27/pCloud_Windows_3.10.4_x64.exe is the direct link to the installer of pCLOUD, so it is possible to submit.

**Comment by ppvnf** [comment]
Would it be possible to use the links below?
https://www.pcloud.com/release-notes/windows.html
https://u.pcloud.link/publink/show?code=XZq7mjVZjFMLGUg7tVQnVenp02bHQjBy7ugX

**Comment by ppvnf** [comment]
https://partner.pcloud.com/dl/win64
https://partner.pcloud.com/dl/win
