### ISSUE TITLE
[Package Request]: IP Camera Viewer

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#141602]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.deskshare.com/ip-camera-viewer.aspx
Publisher: DeskShare Incorporated
Package Name: IP Camera Viewer
Description: Video Monitoring Software for IP Camera.
Package Version: 4.12
Installer URL: https://www.deskshare.com/download/ipcv/IPCameraViewer.exe

**Comment by Exorcism0666** [comment]
welp 😭 
![image](https://github.com/microsoft/winget-pkgs/assets/46537034/1e024357-7b6b-4943-8c0b-cab7a184c6d8)
