### ISSUE TITLE
[Package Issue]: Package.Identifer Winget installed 32-bit zuluJava17 on my 64 bit computer

### ISSUE THREAD

**Issue by postyizhan** [microsoft/winget-pkgs#141709]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

64 bit w11 operating system using ` winget install Azul Zulu. 17. JRE ` installed 32-bit software instead of 64 bit software

Zulu.17 has 64 bits（ https://www.azul.com/downloads/?version=java -17 lts&package=jdk # zulu)

### Steps to reproduce

1. Update the application installation program from the Microsoft store
https://www.microsoft.com/store/productId/9NBLGGH4NNS1?ocid=pdpshare
2. Execute `winget install Azul Zulu.17.JRE`

### Actual behavior

It installs 32-bit zuluJava17

### Expected behavior

Installing 64 bit zuluJava17

### Environment

```raw
PS C:\Users\-XYZ-> winget --info
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment]
The [current latest manifest for `Azul.Zulu.17.JRE`](https://github.com/microsoft/winget-pkgs/blob/41e2e79c922a8dd58be527f04dd5d3d3691ce805/manifests/a/Azul/Zulu/17/JRE/17.36.15/Azul.Zulu.17.JRE.installer.yaml#L20-L26) did not contain an x64 installer. This should be resolved by PR https://github.com/microsoft/winget-pkgs/pull/141727
