### ISSUE TITLE
Thunderbird Beta Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#14176]
PackageIdentifier: Thunderbird
PackageVersion: 88b2
PackageLocale: en-GB
Publisher: Mozilla
PackageName: Thunderbird Beta
License: Open Source
ShortDescription: this app is for managing emails
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://download.mozilla.org/?product=thunderbird-88.0b2-msi-SSL&os=win64&lang=en-GB
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by KaranKad** [comment]
[ThunderbirdBeta](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Mozilla/ThunderbirdBeta) is available.

**Comment by OfficialEsco** [comment]
There ya go, added en-GB for you.
However Winget will not know there is a newer version because it does not have a ProductCode and the PackageName is not Thunderbird Beta
