### ISSUE TITLE
Hi I'm an AI powered bot that finds similar issues based off the issue title.

### ISSUE THREAD

**Issue by Mohamwd420** [microsoft/winget-pkgs#142011]
Hi I'm an AI powered bot that finds similar issues based off the issue title.

Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!

### Closed similar issues:
- [[New Feature]:  (#61714)](https://github.com/microsoft/winget-pkgs/issues/61714),  similarity score: 1.00

> Note: You can give me feedback by thumbs upping or thumbs downing this comment.

_Originally posted by @github-actions[bot] in https://github.com/microsoft/winget-pkgs/issues/142010#issuecomment-1976108873_

**Comment by Trenly** [comment]
Close with reason: No information in issue;
