### ISSUE TITLE
[Package Issue]: YuzuEmu.Yuzu.Mainline

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/winget-pkgs#142116]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The Yuzu Emulator and a bunch of related tools are being taken down due to [settling the court case with Nintendo](https://www.theverge.com/2024/3/4/24090357/nintendo-yuzu-emulator-lawsuit-settlement).

The main yuzu GitHub repo is already privated/gone: https://github.com/yuzu-emu/yuzu, and I expect the other tools to follow shortly.  
Packages affected seem likely to be:

 - YuzuEmu.Yuzu.Mainline
 - CitraEmu.Citra
 - eliboa.TegraRcmGUI

### Steps to reproduce

`winget install YuzuEmu.Yuzu.Mainline`, etc.

### Actual behavior

Fails/will fail to install 

### Expected behavior

Fails/will fail to install

### Environment

```raw
N/A
```

**Comment by dtantono** [comment]
Better to redirect it here https://github.com/pineappleEA/pineapple-src/releases

**Comment by Clockwork-Muse** [comment]
Apparently Citra is also disappearing (at least for now?), added to the comment

**Comment by dtantono** [comment]
yeah I open this issue (https://github.com/microsoft/winget-pkgs/issues/142153) to redirect the repo to https://github.com/PabloMK7/citra/releases/tag/v2.1

**Comment by Exorcism0666** [comment]
TegraRcmGUI is still available: https://github.com/eliboa/TegraRcmGUI

**Comment by Clockwork-Muse** [comment]
@Exorcism0666 - some of the news items I saw were indicating that that tool (and a number not in pkgs) was possibly also part of the settlement.

**Comment by Exorcism0666** [comment]
Yuzu has since been removed from winget, so I think we can close this issue @stephengillie.
