### ISSUE TITLE
[Package Request]: Nuzu

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#142143]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:
Publisher: Nicola
Package Name: Nuzu
Description: Nuzu is an open-source Nintendo Switch emulator
Package Version: EA-4176
Installer URL: https://github.com/Nikilites/nuzu/releases/download/Nuzu/Windows-Nuzu.YUZU.-EA-4176.zip

**Comment by stephengillie** [comment]
Hi @dtantono,

Unfortunately, the InstallerUrl is no longer available. Is there another?

**Comment by dtantono** [comment]
Ah yes, the project is dead yesterday and I will close this
