### ISSUE TITLE
Hash error and Installer error when trying to install CPU-Z and GPU-Z

### ISSUE THREAD

**Issue by Daerdor** [microsoft/winget-pkgs#14224]
# Brief description of your issue
I tried installing CPU-Z (CPUID.CPU-Z) and GPU-Z (TechPowerUp.GPU-Z) packages but both return errors.

# Steps to reproduce

Run the following commands:
winget install CPUID.CPU-Z
winget install TechPowerUp.GPU-Z

# Expected behavior

Both packages CPU-Z and GPU-Z are successfully installed.

# Actual behavior

CPU-Z returns an error that the Installer hash does not match:

![image](https://user-images.githubusercontent.com/40768445/120015351-8b457b00-bfe3-11eb-94d0-01e96794be14.png)

GPU-Z shows a messagebox that the installer couldn't be unpacked:

![image](https://user-images.githubusercontent.com/40768445/120016685-2be86a80-bfe5-11eb-9773-61218ea16a38.png)

Logs are provided in attachment.
# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
PowerShell 7.1.3
```
[DiagOutputDir.zip](https://github.com/microsoft/winget-cli/files/6562270/DiagOutputDir.zip)

**Comment by denelon** [comment]
@Daerdor you could try to update the manifest with the hash mismatch using the [Windows Package Manager Manifest Creator](https://github.com/microsoft/wingetcreate)

Something like `wingetcreate update --id CPUID.CPU-Z` would generate the manifest.

Something like `wingetcreate update --id CPUID.CPU-Z --submit` would generate the manifest and submit the PR.

**Comment by Daerdor** [comment]
@denelon thanks for the feedback.
I followed your instructions and created the PR: https://github.com/microsoft/winget-pkgs/pull/14227

Validation succeeded, installation now passes the hash validation but the installer does return an error:

![image](https://user-images.githubusercontent.com/40768445/120023622-5854b480-bfee-11eb-8166-c280fdc8b78e.png)

**Comment by denelon** [comment]
I wonder if exit code "1" for that particular installer is a success or error code. 

If it is a success code, you can add that to the manifest. I don't think the wingetcreate tool has the ability to add that as an optional field yet, so you would need a "traditional" PR to add it.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-create/issues/37 wingetcreate should prompt for optional fields.

**Comment by Trenly** [comment]
I believe these issues have been resolved with the latest versions
```raw
Found CPUID CPU-Z [CPUID.CPU-Z] Version 1.98
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.cpuid.com/cpu-z/cpu-z_1.98-en.exe
  ██████████████████████████████  2.01 MB / 2.01 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install gpu-z
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires current machine's geographic region to be sent to function properly.

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Found TechPowerUp GPU-Z [TechPowerUp.GPU-Z] Version 2.43.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://us2-dl.techpowerup.com/files/GPU-Z.2.43.0.exe
  ██████████████████████████████  7.10 MB / 7.10 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```
-----
cc @ItzLevvie
