### ISSUE TITLE
[Package Issue]: MediaArea.MediaInfo.GUI version 24.01.1

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#143390]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

related pull request:  https://github.com/microsoft/winget-pkgs/pull/141628

MediaArea.MediaInfo.GUI 24.01.1 keeps being updated in an infinite loop by winget because the app itself sets the displayed version number "24.01" in the registry, not "24.01.1"

### Steps to reproduce

winget install MediaArea.MediaInfo.GUI
winget upgrade MediaArea.MediaInfo.GUI
winget upgrade MediaArea.MediaInfo.GUI
winget upgrade MediaArea.MediaInfo.GUI
winget upgrade MediaArea.MediaInfo.GUI
winget upgrade MediaArea.MediaInfo.GUI
(and so on...)

### Actual behavior

infinite loops that are actually reinstalls (when issuing winget upgrade commands)

### Expected behavior

not re-installing

### Environment

```raw
environment not relevant - this is a manifest issue + installer design problem
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/ff53b06c-8902-40fb-88d0-f45caae45875)

**Comment by stephengillie** [comment]
I approved the previous PR because it has a screenshot of the matching version number from the product's About window. I'll verify the Apps and features Settings page entry in the future.
