### ISSUE TITLE
Zeit is now Vercel

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/winget-pkgs#1436]
# Description
There is a manifest (specifically speaking the [Zeit/Hyper](https://github.com/microsoft/winget-pkgs/blob/master/manifests/Zeit/Hyper/3.0.2.1510.yaml) manifest), but recently Zeit has announced their change in name to [Vercel](https://vercel.com/blog/zeit-is-now-vercel), so it should be renamed according to this change.

**Comment by MarNicGit** [comment]
Welp, rename is currently blocked by #1448

**Comment by denelon** [comment]
This scenario should be supported now. If you are renaming a manifest, it gets registered as a single file delete and a single file add.
