### ISSUE TITLE
[Package Issue]: Microsoft.WindowsAppRuntime.1.4

### ISSUE THREAD

**Issue by ewan-paterson** [microsoft/winget-pkgs#144292]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Today, after updating winget, the Microsoft.WindowsAppRuntime.1.4 is being detected as Microsoft Windows Desktop Runtime - 6.0.28 (x64) (or vice versa). Before upgrading winget it was showing as having a package pin, but the pin list did not show anything.

### Steps to reproduce

Have both Microsoft.WindowsAppRuntime.1.4 and Microsoft Windows Desktop Runtime - 6.0.28 (x64) installed.

### Actual behavior

Package mismatch.

### Expected behavior

No updates available as both are at latest versions.

### Environment

```raw
Windows Package Manager v1.7.10661
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10661.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

Winget v1.7.10582:
![image](https://github.com/microsoft/winget-pkgs/assets/87709415/b10f69d5-c640-4883-832e-9293d649d4b9)

Winget v1.7.10661:
![image](https://github.com/microsoft/winget-pkgs/assets/87709415/1cc062ac-b336-4c58-b5a3-081f907cb5d6)

**Comment by mdanish-kh** [comment]
@ewan-paterson Can you tell exactlly what version or versions of WinApp 1.4 you have installed?

You can check them out by running the following command in PowerShell:
```
Get-AppxPackage *WindowsAppRuntime.1.4* | Select Version
```

**Comment by ewan-paterson** [comment]
Thanks for the reply @mdanish-kh, I have `4000.1136.2333.0` installed. I don't know why it lists two, maybe x86 & x64?

![image](https://github.com/microsoft/winget-pkgs/assets/87709415/777aca0b-83b7-444d-9bd9-a088e1284fa4)

**Comment by mdanish-kh** [comment]
@ewan-paterson A couple PRs were merged that may have improved the package correlation. Can you check again to see if you found an improvement?

If not, this appears to be related to a class of issues that are being tracked with [Area-Matching](https://github.com/microsoft/winget-cli/issues?q=is%3Aopen+is%3Aissue+label%3AArea-Matching) label over at winget-cli repo. 

If you want a temporary workaround, you can remove the package from `winget upgrade --all` by adding a pin for this package as `winget pin add --id Microsoft.WindowsAppRuntime.1.4`

[Policy] Area-Matching

**Comment by mdanish-kh** [comment]
Also out of curiosity, since this appears to be conflicting with a package that's supposed to have the ID `Microsoft.DotNet.DesktopRuntime.6`, what do you get when you do `winget list "Desktop runtime" --open-logs --verbose-logs`? The output of that may help someone who's investigating these issues later on. Can you also share the logs related to this command? (I've appended --open-logs in the command so that the logs directory is automatically opened when the command finishes, the log will be the latest one if you sort by date)

**Comment by ewan-paterson** [comment]
Hey @mdanish-kh, I noticed your PRs go in, but unfortunately made no difference. Here's all the logs for the various commands, I hope this helps!
![image](https://github.com/microsoft/winget-pkgs/assets/87709415/301d7ca7-36b9-4f64-8015-b7215da8fb7b)
[WinGet-2024-03-18-09-48-12.811.log](https://github.com/microsoft/winget-pkgs/files/14634156/WinGet-2024-03-18-09-48-12.811.log)
[WinGet-2024-03-18-09-53-20.448.log](https://github.com/microsoft/winget-pkgs/files/14634157/WinGet-2024-03-18-09-53-20.448.log)
[WinGet-2024-03-18-09-48-41.062.log](https://github.com/microsoft/winget-pkgs/files/14634159/WinGet-2024-03-18-09-48-41.062.log)

**Comment by ewan-paterson** [comment]
@mdanish-kh I installed a Visual Studio update a few days ago, which reinstalled `Microsoft Windows Desktop Runtime - 6.0.28` and seems to have resolved the problem. Both `Microsoft.DotNet.DesktopRuntime.6` and `Microsoft.WindowsAppRuntime.1.4_8wekyb3d8bbwe` are now listed correctly in `winget list`. Must have been a local issue. I'll close the issue, but thanks for your help!
