### ISSUE TITLE
[Package Issue]: RedHat.Podman

### ISSUE THREAD

**Issue by krachynski** [microsoft/winget-pkgs#144380]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

In trying to install the latest Podman, I am being presented with the dependency on the feature WSL. This dependency requires an elevated prompt to process.

Podman doesn't require WSL in order to run. Podman-Desktop does, though.

### Steps to reproduce

1. Launch a terminal with a non-elevated shell (PowerShell 7.4, say)
2. `winget install RedHat.Podman`

### Actual behavior

Found Podman [RedHat.Podman] Version 4.9.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Windows Features
      Microsoft-Windows-Subsystem-Linux
This command requires administrator privileges to execute.

### Expected behavior

I expected Podman to install like 4.9.2 did without requiring an elevated prompt

### Environment

```raw
Windows Package Manager v1.7.10661
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10661.0
```

**Comment by SpecterShell** [comment]
I added the dependency as there was an option to install WSL in the installer and it was checked by default. Will be fixed after the 4 PRs get merged.

![image](https://github.com/microsoft/winget-pkgs/assets/56779163/f5867655-c10d-4958-8958-0586e06595c0)
