### ISSUE TITLE
astral-sh.ruff: An extremely fast Python linter and code formatter, written in Rust.

### ISSUE THREAD

**Issue by frazar** [microsoft/winget-pkgs#144360]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Here is my attempt, based on on older submission: https://github.com/microsoft/winget-pkgs/pull/143774/checks?check_run_id=22514233933

Download Page Url: https://github.com/astral-sh/ruff/releases/tag/v0.3.2
Publisher: Astral
Package Name: Ruff
Description: An extremely fast Python linter and code formatter, written in Rust.
Package Version: 0.3.2
Installer URL: https://github.com/astral-sh/ruff/releases/download/v0.3.2/ruff-0.3.2-x86_64-pc-windows-msvc.zip

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #143774;
