### ISSUE TITLE
[Package Request]: Add MSI Gaming Intelligence Software

### ISSUE THREAD

**Issue by vikingnope** [microsoft/winget-pkgs#144938]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.msi.com/support/technical_details/MNT_SW_MSI_Preloaded_Software#txt01
Publisher: MSI
Package Name: MSI Gaming Intelligence
Description: Used to control MSI Gaming Monitors
Package Version: 0.0.2.77
Installer URL: https://download.msi.com/uti_exe/monitor/Gaming-Intelligence-x64.zip

**Comment by vikingnope** [comment]
@stephengillie, I am trying to install it through winget, but it says that the hash does not match, could it be the issue of the hash not being consistent?

**Comment by stephengillie** [comment]
What's unexpected here is that it worked on the 2nd try. This looks like a vanity URL, which always serves the latest version, and these frequently have a hash mismatch on new releases - after a new version is releassed, but before the new version has a manifest submitted to this repo. At first, your scenario resembled this. But then it worked, so maybe an error page got downloaded the first time?
