### ISSUE TITLE
=== manifests\r\Ryujinx\Ryujinx\1.1.1239 ===

### ISSUE THREAD

**Issue by Exorcism0666** [microsoft/winget-pkgs#144932]
=== manifests\r\Ryujinx\Ryujinx\1.1.1239 ===
Missing Properties value based on version 1.1.1231: 
NestedInstallerType
NestedInstallerFiles

_Originally posted by @wingetbot in https://github.com/microsoft/winget-pkgs/pull/144925#issuecomment-2002293313_

However NestedInstallerFiles and NestedInstallerType are present.

**Comment by mdanish-kh** [comment]
Duplicate of #139015
