### ISSUE TITLE
[Package Request]: Peace Equalizer

### ISSUE THREAD

**Issue by vikingnope** [microsoft/winget-pkgs#145076]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/peace-equalizer-apo-extension/
Publisher: [peverbeek](https://sourceforge.net/u/peverbeek/profile/)
Package Name: Peace Equalizer
Description: Better GUI for Equalizer APO (Requires Equalizer APO to be installed beforehand)
Package Version: 1.6.6.0
Installer URL: https://sourceforge.net/projects/peace-equalizer-apo-extension/files/latest/download

**Comment by Dragon1573** [comment]
Both _Peace Equalizer_ and _Equalizer APO_ are not presented in the repository.

Is _Equalizer APO_ have special physical hardware dependencies? When testing the manifest with local-server-provided `InstallerUrl` in Windows Sandbox, the package cannot be silently installed, get stuck and unable to "OK" for further installation steps.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/42bd27b7-0dec-4ad3-9be9-9581fbe78ee9)

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
