### ISSUE TITLE
[Package Request]: MSI Afterburner Beta

### ISSUE THREAD

**Issue by vikingnope** [microsoft/winget-pkgs#145078]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.guru3d.com/download/msi-afterburner-beta-download/
Publisher: Guru3D
Package Name: MSI Afterburner
Description: Used to see GPU and CPU usage
Package Version: 4.6.6
Installer URL: https://www.guru3d.com/download/msi-afterburner-beta-download/

**Comment by vikingnope** [comment]
#145129

**Comment by elisimpson** [comment]
Package version needs to be updated to reflect the full version number (4.6.6 Beta 3). Currently the package wants to upgrade constantly because it sees 4.6.6 as "greater" than 4.6.6 Beta 3.
