### ISSUE TITLE
[Package Issue]: Typst.Typst

### ISSUE THREAD

**Issue by Enivex** [microsoft/winget-pkgs#145055]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget believes 0.11.0-rc1 is newer than 0.11.0. Therefore the only way to install 0.11.0 is to manually specify that version.

### Steps to reproduce

```
winget show typst --versions
Found Typst [Typst.Typst]
Version
----------
0.11.0-rc1
0.11.0
0.10.0
0.9.0
0.8.0
0.7.0
0.6.0
0.5.0
0.4.0
0.3.0
0.2.0
```

### Actual behavior

0.11.0 should be on top

### Expected behavior

0.11.0-rc1 is on top

### Environment

```raw
Windows Package Manager v1.7.10661
Windows: Windows.Desktop v10.0.22635.3350
Package: Microsoft.DesktopAppInstaller v1.22.10661.0
```

**Comment by mdanish-kh** [comment]
With how WinGet performs version sorting, `0.11.0-rc1` will be considered higher than `0.11.0`. WinGet does not have proper channels support (beta, stable etc) yet. If we want to make pre-release versions available, they should be added under a separate PackageId like `Typst.Typst.Preview` / `Typst.Typst.Prerelease`.

To unblock this issue, I'll remove the release candidate version from `Typst.Typst` PackageId.

**Comment by stephengillie** [comment]
Should the release candidate be readded under another PacakgeIdentifier? Possibly `Typst.Typst.RC`?
