### ISSUE TITLE
[Update Request]: Samsung.SamsungMagician

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#145127]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Samsung.SamsungMagician

### Package Version

8.0.1

### Please describe the changes you would like to see

https://download.semiconductor.samsung.com/resources/software-resources/Samsung_Magician_Installer_Official_8.0.1.1000.exe

**Comment by phuzion** [comment]
Version 8.0.1 of Samsung Magician cannot be silently installed, per [#134001.](https://github.com/microsoft/winget-pkgs/pull/134001#issuecomment-1892803273)

**Comment by mews-se** [comment]
Version 8.1.0.800 is now the latest: 

https://download.semiconductor.samsung.com/resources/software-resources/Samsung_Magician_Installer_Official_8.1.0.800.exe

**Comment by cvrebert** [comment]
Duplicate of #121594
