### ISSUE TITLE
[Update Request]: Governikus.AusweisApp version 2.1.0

### ISSUE THREAD

**Issue by cn-ml** [microsoft/winget-pkgs#145211]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Governikus.AusweisApp

### Package Version

2.1.0

### Please describe the changes you would like to see

Release [2.1.0](https://github.com/Governikus/AusweisApp/releases/tag/2.1.0) was published 3 weeks ago.

**Comment by og-mrk** [comment]
should be closed, as #145212 PR resolves this issue.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #145212;
