### ISSUE TITLE
[Update Request]: Plex.Plexamp version 4.10.0

### ISSUE THREAD

**Issue by Mjsciarabba** [microsoft/winget-pkgs#145900]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Plex.Plexamp

### Package Version

4.10.0

### Please describe the changes you would like to see

There is a new release available (4.10.0). Download url: https://plexamp.plex.tv/plexamp.plex.tv/desktop/Plexamp%20Setup%204.10.0.exe

**Comment by vikingnope** [comment]
Latest update seems to be 4.10.1 so that will be installed
