### ISSUE TITLE
[Package Issue]: FACEITLTD.FACEITClient package not updating correctly

### ISSUE THREAD

**Issue by vikingnope** [microsoft/winget-pkgs#146226]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I get an update for this package, and I update it using winget, it should update normally, but iin fact in never actually updates and stays saying that it needs to be updated.

### Steps to reproduce

Install a version which is not the latest of FaceIT Client, and try to update it

### Actual behavior

Says it updated successfully, but it did not actually update

### Expected behavior

Should update successfully.

### Environment

```raw
Windows Package Manager v1.7.10661
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10661.0

Winget Directories
--------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopApp…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopApp…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
This is most likely an issue with the FaceIT Client itself, as WinGet simply downloads and runs the installer. If the installer cannot be used for upgrade, or the upgrade fails, the installer is responsible for providing a non-zero exit code indicating the software could not be upgraded. Or, in the case that the software is actually being upgraded, it's possible that the registry entries aren't being updated on an install. In either case, the fix for this resides with the FaceIT publishers, as there really isn't anything that WinGet can do about it
