### ISSUE TITLE
[Update Request]: Rime.Weasel

### ISSUE THREAD

**Issue by jizusun** [microsoft/winget-pkgs#146489]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Rime.Weasel

### Package Version

0.15.0

### Please describe the changes you would like to see

Download URL https://github.com/rime/weasel/releases/
New version releaese: [tag/0.15.0](https://github.com/rime/weasel/releases/tag/0.15.0)

**Comment by SpecterShell** [comment]
https://github.com/rime/weasel/issues/949

**Comment by Trenly** [comment]
[Policy] Interactive Only - until a new version is released by the publisher with the fix for
