### ISSUE TITLE
Package still not available in winget despite being merged

### ISSUE THREAD

**Issue by AndroidWG** [microsoft/winget-pkgs#14666]
I submitted a package (#14540) I created using `wingetcreate`. I validated and tested on my machine, and it worked fine. The pull request also passed all tests with no issues and got merged around 7 hours ago, however using `winget install corkscrew` or `winget search corkscrew` returns no results. I ran `winget source update` but this also didn't help.

I searched around this repo's README and the other winget repos ([wingetcreate](https://github.com/microsoft/winget-create) and [winget-cli](https://github.com/microsoft/winget-cli)) to see if the long wait is expected or if I need to do anything else, but it seems like the package should go live when it's merged to master.

**Comment by ItzLevvie** [comment]
cc @denelon @ashpatil-msft seems like the pipelines are stuck on https://github.com/microsoft/winget-pkgs/runs/2702875105

**Comment by DasCanard** [comment]
resolved
