### ISSUE TITLE
LibreOffice not up to date

### ISSUE THREAD

**Issue by nolme** [microsoft/winget-pkgs#146676]
Hello,
I ran a list and update command on a computer which see no update available but I'm pretty sure many applications are not up to date.
I look deeper for LibreOffice as sample. As you can see it's a 7.6.4.1 version but update is not found.
I installed manually the 24.2.1.2, it's now listed.
Is there a problem with the component or winget update list is not working ?

![Winget - LibreOffice](https://github.com/microsoft/winget-pkgs/assets/4461224/1c47e290-794b-47dd-bbeb-f1771f88853c)

Winget --version retrieve : 1.7.10661

**Comment by MerrickZ** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/1021332/3e4f5848-5e1d-40ba-9624-64625dce806c)

As you can see from LibreOffice's [Official Site](https://www.libreoffice.org/download/download-libreoffice/)
There're LibreOffice for technology enthusiast, which version is 24.2.1, and LibreOffice for business deployments with version 7.6.5.
They're different packages.

**Comment by nolme** [comment]
maybe you're right. But the system should at least detect that latest version is 7.6.5 instead of 7.6.4 ?

**Comment by stephengillie** [comment]
It appears that `LibreOffice for business` was already installed, and `LibreOffice for technology enthusiast` overwrote this. 

Is this the case?

**Comment by kotenok2000** [comment]
Now it wants to upgrade from 24.2.1.2 to 24.2.2.2 but can't

**Comment by MagicAndre1981** [comment]
>  to 24.2.2.2 but can't

yeah, local is [misconfigured as en-us](https://github.com/microsoft/winget-pkgs/pull/146821#issuecomment-2026125216) which prevents update.

**Comment by krystofkrticka** [comment]
Looks like a bug in Komac from russellbanks because it added back the installerlocale.

**Comment by krystofkrticka** [comment]
I just created PR where I removed it manually. I never noticed this even though I did updates on multiple computers today which have their locale set to cs-CZ and it installed just fine.

**Comment by hueldoeu** [comment]
> > to 24.2.2.2 but can't
> 
> yeah, local is [misconfigured as en-us](https://github.com/microsoft/winget-pkgs/pull/146821#issuecomment-2026125216) which prevents update.

why again?
