### ISSUE TITLE
[Package Request]: Java SE Development Kit 22

### ISSUE THREAD

**Issue by happylynx** [microsoft/winget-pkgs#146722]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.oracle.com/java/technologies/downloads
Publisher: Oracle Corporation
Package Name: Java SE Development Kit 22
Description: The JDK is a development environment for building applications and components using the Java programming language.
Package Version: 22
Installer URL:  https://download.oracle.com/java/22/latest/jdk-22_windows-x64_bin.msi

**Comment by Dragon1573** [comment]
Oracle JDK are identified by a special "series" in the repository, in this issue should be `Oracle.JDK.22`. You can try `winget show -e Oracle.JDK.21` for the previous version of Oracle Java SE Development Kit.

You can create the manifest on your own by using `wingetcreate.exe`, `YamlCreate.ps1` or _Komac_. Most of the values can be copy-pasted from the previous version.

Feel free to create pull requests ❤️
