### ISSUE TITLE
[Update Request]: Microsoft.PIX is out of date and should ask for EULA agreement

### ISSUE THREAD

**Issue by sfreed141** [microsoft/winget-pkgs#146860]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PIX

### Package Version

2403.08

### Please describe the changes you would like to see

The current version of PIX on Windows is about a year out of date (new releases can be found at https://devblogs.microsoft.com/pix/download/). The newest release is version 2403.08.

I would've tried to do this myself but I don't see how to require accepting a EULA in the [manifest](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md). The current package does not prompt for any confirmation (!), but when you run the installer manually you're presented with this
![image](https://github.com/microsoft/winget-pkgs/assets/6880264/697a32ed-cad5-4e03-9867-95f6e44824c5)
(you have to check the circled checkbox in order to install)

Here's the existing manifest: https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PIX/23.3.30.1/Microsoft.PIX.installer.yaml

**Comment by Dragon1573** [comment]
You can get the _Setup Help_ by adding `-h` switch to the installer file. It seems there're `/passive` switch for `silentWithProgress` mode and `/quiet` for `silent` mode.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/faafc593-3114-45b5-b8af-9f150909289a)

**Comment by sfreed141** [comment]
Thanks everyone for the quick help! I just tried it out and it works great!
