### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2015+.x64

### ISSUE THREAD

**Issue by EscapeAltDelete** [microsoft/winget-pkgs#146805]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Package is marked for update while being on latest version already.

### Steps to reproduce

winget update --all --include-unknown

### Actual behavior

When i update all my package's Microsoft.VCRedist.2015+.x64 is always marked, but seems to be on the latest version already.

### Expected behavior

Package is only marked for an update when it needs one.

### Environment

```raw
Windows Package Manager v1.7.10661
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1288
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10661.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

[Video](https://i.supa.codes/7gwVr)
[WinGet-2024-03-28-14-45-17.299.log](https://github.com/microsoft/winget-pkgs/files/14790477/WinGet-2024-03-28-14-45-17.299.log)

**Comment by Trenly** [comment]
Can you share the output of `winget list "Visual C++ Redistributable"`? There are known issues when upgrading VCRedist where sometimes it installs side-by-side

**Comment by EscapeAltDelete** [comment]
It spit out: No installed package found matching input criteria.

**Comment by EscapeAltDelete** [comment]
I reinstalled both package's and now it seems to work as normal, sorry for wasting your time :).
