### ISSUE TITLE
[Package Issue]: WiresharkFoundation.Wireshark

### ISSUE THREAD

**Issue by ewanm89** [microsoft/winget-pkgs#146941]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

#146861 merge was flagged by bot as the URLs and hashes are those of version 4.2.3 not 4.2.4 and so already matched an existing manifest, this was then manually approved anyway even know the URLs have 4.2.3 in the actual URLs in the manifest.

As a such winget trys to install the wrong version.

### Steps to reproduce

Install/update wireshark via winget, observe it downloads and installs the old version.

### Actual behavior

Install/update wireshark, observe it downloads and installs the old version.

### Expected behavior

Correct manifest URLs and hashes, also manual reviewer should check this when the bot flags that it already found the hashes. The only time the hash should match between manifest versions is if the installer is a downloader/updater/launcher that will grab the latest version anyway.

### Environment

```raw
Windows Package Manager v1.7.10861
Windows: Windows.Desktop v10.0.19045.4170
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

### Screenshots and Logs

```
ewanm89@Defiant-B ❯  wg upgrade WiresharkFoundation.Wireshark
Found Wireshark [WiresharkFoundation.Wireshark] Version 4.2.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://2.na.dl.wireshark.org/win64/Wireshark-4.2.3-x64.exe
```

**Comment by Trenly** [comment]
[Policy] Package Update
[Policy] Help Wanted
