### ISSUE TITLE
[Package Request]: Zoom VDI Universal Plugin

### ISSUE THREAD

**Issue by kd2flz** [microsoft/winget-pkgs#147062]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063810
Publisher: Zoom
Package Name: Zoom VDI Universal Plugin
Description: Compatible plugins for the Zoom VDI Client to be installed on the endpoint.
Package Version:  5.17.10.24730 (64-bit)
Installer URL: https://zoom.us/download/vdi/5.17.10.24730/ZoomVDIUniversalPluginx64.msi?archType=x64

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/issues/147061#issuecomment-2029866910
