### ISSUE TITLE
[Package Issue]: CoreyButler.NVMforWindows – No applicable upgrade found

### ISSUE THREAD

**Issue by glen-84** [microsoft/winget-pkgs#147043]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

```
$ winget upgrade
Name                                                               Id                             Version       Available     Source
------------------------------------------------------------------------------------------------------------------------------------
NVM for Windows 1.1.11                                             CoreyButler.NVMforWindows      1.1.11        1.1.12        winget
```

`winget upgrade CoreyButler.NVMforWindows`

> No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.

### Steps to reproduce

I think that the current version was installed without using WinGet – should that matter?

### Actual behavior

> No applicable upgrade found.

... when there is one.

### Expected behavior

For the upgrade to succeed.

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3374
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by mdanish-kh** [comment]
> I think that the current version was installed without using WinGet – should that matter?

That shouldn't necessarily have an effect

Can you share the logs from running the command

```
winget upgrade CoreyButler.NVMforWindows --verbose-logs --open-logs
```

This'll open the logs directory for you (it should be the latest log if sorted by date)

**Comment by Dragon1573** [comment]
@mdanish-kh - Successfully reproduce this issue in Windows Sandbox.

<details><summary>Console Logs</summary>

```text
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -e CoreyButler.NVMforWindows --version 1.1.11
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y
Found NVM for Windows [CoreyButler.NVMforWindows] Version 1.1.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe
  ██████████████████████████████  5.46 MB / 5.46 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade CoreyButler.NVMforWindows --verbose-logs --open-logs
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
```

</details>
<details><summary>Environments</summary>

```text
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> systeminfo.exe

Host Name:                 7A5458BB-FBE9-4
OS Name:                   Microsoft Windows 11 企业版
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00328-90000-00000-AAOEM
Original Install Date:     1/1/1970, 8:00:00 AM
System Boot Time:          3/30/2024, 8:28:41 PM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2803 Mhz
BIOS Version:              Microsoft Corporation Hyper-V UEFI Release v4.1, 4/6/2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             zh-cn;Chinese (China)
Input Locale:              en-us;English (United States)
Time Zone:                 N/A
Total Physical Memory:     4,095 MB
Available Physical Memory: 2,491 MB
Virtual Memory: Max Size:  5,823 MB
Virtual Memory: Available: 4,033 MB
Virtual Memory: In Use:    1,790 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\7A5458BB-FBE9-4
Hotfix(s):                 N/A
Network Card(s):           1 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                                 Connection Name: 以太网
                                 DHCP Enabled:    Yes
                                 DHCP Server:     172.26.32.1
                                 IP address(es)
                                 [01]: 172.26.40.40
                                 [02]: fe80::9319:ae01:65b5:8ac0
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3420
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

</details>
<details><summary>Log files</summary>

- [WinGet-2024-03-30-20-30-23.517.log](https://github.com/microsoft/winget-pkgs/files/14811991/WinGet-2024-03-30-20-30-23.517.log)
- [WinGet-CoreyButler.NVMforWindows.1.1.11-2024-03-30-20-30-39.409.log](https://github.com/microsoft/winget-pkgs/files/14811994/WinGet-CoreyButler.NVMforWindows.1.1.11-2024-03-30-20-30-39.409.log)
- [WinGet-2024-03-30-20-31-09.365.log](https://github.com/microsoft/winget-pkgs/files/14811995/WinGet-2024-03-30-20-31-09.365.log)

</details>

**Comment by glen-84** [comment]
@mdanish-kh

That highlighted the issue, thanks.

> 2024-03-30 14:25:32.745 [CLI ] Installer [X86,inno,User,en-US] not applicable: Installer scope does not match currently installed scope: User != Machine

The scope of the package is `user`:

https://github.com/microsoft/winget-pkgs/blob/26f4cc828f87f363e3eb611cf5819880f15b9364/manifests/c/CoreyButler/NVMforWindows/1.1.12/CoreyButler.NVMforWindows.installer.yaml#L8

Should this explicit scope be removed?

**Comment by Dragon1573** [comment]
In the current latest commit of version 1.1.11, it also contains this explicit `Scope` configuration. I think it should not be removed.

https://github.com/microsoft/winget-pkgs/blob/26f4cc828f87f363e3eb611cf5819880f15b9364/manifests/c/CoreyButler/NVMforWindows/1.1.11/CoreyButler.NVMforWindows.installer.yaml#L8

`winget.exe` behaves unexpectedly and install version 1.1.11 to machine scope instead of user scope. 😕

**Comment by mdanish-kh** [comment]
> A new install should default to the `user` scope.

That's what WinGet would already do with this package


> An existing `machine` install should be upgraded with `machine` scope.

WinGet would do that as well if we had another installer node defined in the manifest for `machine` scope. Currently WinGet is only offering the user scope installation. I dug up a previous issue and saw that the machine scope installation is currently not possible through WinGet because it requires setting an environment variable, something WinGet is currently incapable of doing.

See https://github.com/microsoft/winget-pkgs/issues/92737 and related upstream issue https://github.com/coreybutler/nvm-windows/issues/915

**Comment by glen-84** [comment]
> That's what WinGet would already do with this package

Dragon1573 mentioned that it doesn't when the scope is removed.

> See #92737 and related upstream issue coreybutler/nvm-windows#915

I'm not sure how I missed that, thanks.

---

I guess I'll just switch to a user-scoped installation for now.

Thanks both.
