### ISSUE TITLE
[Update Request]: Cloudflare.Warp

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#147039]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Cloudflare.Warp

### Package Version

24.3.409.0

### Please describe the changes you would like to see

There is a new release.
I was unable to find again the package in the repository.

**Comment by Dragon1573** [comment]
@Edoardo66 - Seems `Cloudflare.Warp` meets some special case and should be entirely removed from the repository. I can help submitting the manifest, but I think the same problem may occur and block the PR.

> [!NOTE]
>
> Manifest is valid and able to install in Windows Sandbox if modify `InstallerUrl` to a pre-downloaded local server URL.

## Related issues or pull requests

- #145124
- #144984
- #141535

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Pull request #147041 failed to resolve this issue. And this issue seems blocked by external reason. https://github.com/microsoft/winget-pkgs/labels/In-PR should be removed from this issue.
