### ISSUE TITLE
[Package Request]: Zoom VDI Client

### ISSUE THREAD

**Issue by kd2flz** [microsoft/winget-pkgs#147061]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063810
Publisher: Zoom
Package Name: VDI client version 5.17.10 (64-bit)
Description: Zoom client for Virtual Desktop Infrastructure
Package Version: 5.17.10
Installer URL: https://zoom.us/download/vdi/5.17.10.24730/ZoomInstallerVDI.msi?archType=x64

**Comment by stephengillie** [comment]
Does this package require VDI software to be installed before it will install? Will it work with any VDI, or does it require a specific brand? Only asking because other VDI clients seem to have a dependency on having one of several VDI agents already installed on the PC.

**Comment by kd2flz** [comment]
The client is only useful in a VDA environment, but I don't know that it checks whether it is installed on a virtual desktop. I don't even know if it would be possible to check for that, since virtual desktops don't necessarily know if or how you're connecting to them via a virtualization provider. 
I've made a package request for the universal plugin r on #147062. If you attempt to run the Zoom VDA client on the virtual desktop without the plugin running on your endpoint, the result is the client just appears as a blank window. 
For reference, what's happening is that Zoom is rendering the video and audio for the call locally on the endpoint, but allowing you to run the call within the virtual desktop with screen sharing etc.
The plugin/ client combination supports the following virtualization providers:

Citrix
VMWare
Azure Virtual Desktop
Amazon Workspaces
HP Anywhere

Hopefully this helps!
