### ISSUE TITLE
Unity package is extremely problematic

### ISSUE THREAD

**Issue by foxscore** [microsoft/winget-pkgs#14700]
# Describe issue
The Unity package `UnityTechnologies.Unity` is not suitable for a package manager, as it will always try to install the latest version.
This leads to the newest version (which won't even be used) to be installed and just waste (at minimum) 10GB.

Managing Unity installations is UnityHub's job, since the Unity version you are using differs from project to project.

# Solution
Remove the Unity package and don't allow for it to be commited again.

**Comment by jedieaston** [comment]
Once there is a way of freezing version numbers this won’t be a problem anymore. Unity Hub is in the repo, if you want to use it you can.

**Comment by foxscore** [comment]
> Once there is a way of freezing version numbers this won’t be a problem anymore. Unity Hub is in the repo, if you want to use it you can.

I am aware of Unity hub being in the repo, but freezing version numbers doesn't help.
The only solutions would be to either add "Channels" (like snap), or to add every mayor Unity version seperatly

**Comment by denelon** [comment]
@foxscore it sounds like you're describing the way Java JDKs and a few other tools are added. The "major" versions are treated like separate packages. The pin feature https://github.com/microsoft/winget-cli/issues/476 would just prevent the Windows Package Manager from updating a package with `winget upgrade --all`.

**Comment by jedieaston** [comment]
I understand now. I can work on moving these at some point (if someone gets to it before me, by all means....)

**Comment by denelon** [comment]
We're working on:
* microsoft/winget-cli/issues/476
