### ISSUE TITLE
[Package Request]: ccache

### ISSUE THREAD

**Issue by DeveloperPaul123** [microsoft/winget-pkgs#147166]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://ccache.dev/download.html
Publisher: [Joel Rosdahl](https://github.com/jrosdahl/).
Package Name: Ccache.Ccache
Description: Compiler cache that speeds up re-compilation.
Package Version: `4.9.1`
Installer URL: https://github.com/ccache/ccache/releases/download/v4.9.1/ccache-4.9.1-windows-x86_64.zip

**Comment by Trenly** [comment]
[Policy] In PR

**Comment by DeveloperPaul123** [comment]
Thank you @og-mrk!
