### ISSUE TITLE
[Package Request]: Add Back CloudFlare WARP

### ISSUE THREAD

**Issue by hanlim83** [microsoft/winget-pkgs#147129]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://one.one.one.one/
Publisher: Cloudflare Inc
Package Name: Cloudflare.Warp
Description: 1.1.1.1 with WARP replaces the connection between your device and the Internet with a modern, optimized, protocol.
Package Version: 2024.3.409.0
Installer URL: https://1111-releases.cloudflareclient.com/windows/Cloudflare_WARP_Release-x64.msi

**Comment by BiosPlus** [comment]
Warp uses a vanity URL, and the client updates so frequently that the sha256 hash that winget uses to validate the file is pretty much always invalid.

This has also been referenced here:
https://github.com/microsoft/winget-pkgs/issues/147039
https://github.com/microsoft/winget-pkgs/pull/145124
https://github.com/microsoft/winget-pkgs/pull/144984
https://github.com/microsoft/winget-pkgs/pull/141535 <- example of it changing before a moderator can even approve a new version.

It would be in Cloudflares interest to have non-vanity links should it be more widely adopted via winget.
