### ISSUE TITLE
[Update Request]: VeraCrypt 1.26.7

### ISSUE THREAD

**Issue by jorgwolski** [microsoft/winget-pkgs#147384]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IDRIX/VeraCrypt

### Package Version

1.26.7

### Please describe the changes you would like to see

Newer version (1.26.7) is available.
New launchpad link to the msi-file: https://launchpad.net/veracrypt/trunk/1.26.7/+download/VeraCrypt_Setup_x64_1.26.7.msi

**Comment by BiosPlus** [comment]
While launchpad is good, using the GH repo as a package source allows many tools to auto add the changelog to the winget manifest ;)

https://github.com/veracrypt/VeraCrypt
