### ISSUE TITLE
[Update Request]: ACLAP.DownloadHelperCoApp 2.0.19

### ISSUE THREAD

**Issue by ACasset** [microsoft/winget-pkgs#147477]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ACLAP.DownloadHelperCoApp

### Package Version

2.0.19

### Please describe the changes you would like to see

New 2.0.19 release at https://github.com/aclap-dev/vdhcoapp/releases/tag/v2.0.19

**Comment by Exorcism0666** [comment]
@stephengillie @ACasset can you close this issue ?
