### ISSUE TITLE
[Package Issue]: EpicGames.EpicGamesLauncher

### ISSUE THREAD

**Issue by Andrew-J-Larson** [microsoft/winget-pkgs#147542]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Updating the Epic Games launcher fails when older version is still running.

### Steps to reproduce

1. Install the Epic Games launcher (an older version) if it's not already installed, or downgrade to an older version.
2. Attempt to update it with winget

### Actual behavior

Throws an error about Epic Games launcher still running, but it doesn't give an option to force close the processes.

### Expected behavior

Winget should process terminating the Epic Games launcher processes before proceeding with the update.

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
The error that the process is still running is actually coming from the installer itself and not WinGet. Fundamentally, all WinGet does is download the new installer and run it. WinGet has no knowledge of what process needs to be closed and has no way to determine beforehand if the installer will or will not be successful. 

You could try running an interactive upgrade using `winget upgrade <query> -i` to see if the installer behaves any differently.

Ultimately, Epic Games is the only one who can truly fix the issue by either providing a switch that forces the application to close or making the installer work while the application is running

<!--
[Policy] Area-External
