### ISSUE TITLE
[Package Issue]: GitHub.GitHubDesktop V3.3.12 Installer hash does not match

### ISSUE THREAD

**Issue by fossbrandon** [microsoft/winget-pkgs#147524]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

I get an installer hash mismatch when trying to update GitHub Desktop from version `3.3.11` to `3.3.12`. Here is my update output:

```
PS C:\source\repos> winget upgrade --all
Name           Id                   Version Available Source
------------------------------------------------------------
GitHub Desktop GitHub.GitHubDesktop 3.3.11  3.3.12    winget
1 upgrades available.

(1/1) Found GitHub Desktop [GitHub.GitHubDesktop] Version 3.3.12
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://central.github.com/deployments/desktop/desktop/latest/win32
  ██████████████████████████████   146 MB /  146 MB
Installer hash does not match.
```

### Steps to reproduce

Install a previous version of GitHub Desktop and attempt to upgrade to `3.3.12`

### Actual behavior

The installation fails with a mismatched hash error.

### Expected behavior

The upgrade should succeed with no errors.

### Environment

```raw
Windows Package Manager v1.7.10861
Windows: Windows.Desktop v10.0.22621.3296
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by exchange12rocks** [comment]
Should be fixed by #147522

**Comment by fossbrandon** [comment]
Awesome, I'll give the upgrade another try once that gets merged. Thank you

**Comment by fossbrandon** [comment]
I'm able to install `3.3.13` now, thank you.
