### ISSUE TITLE
[Package Request]: FreeFileSync

### ISSUE THREAD

**Issue by alxhu-dev** [microsoft/winget-pkgs#147611]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://freefilesync.org/download.php
Publisher: Zenju
Package Name: zenju.freefilesync
Description: Open source folder comparison and synchronization software 
Package Version: 13.5
Installer URL: https://freefilesync.org/download/FreeFileSync_13.5_Windows_Setup.exe

**Comment by Trenly** [comment]
* Duplicate of #57900
