### ISSUE TITLE
Google chrome installed via winget shows error while checking for updates, package identifier `Google.Chrome`

### ISSUE THREAD

**Issue by Ankitr19** [microsoft/winget-pkgs#147702]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I have tried installing Google chrome via winget on 2 devices and on both of them I am seeing the same issue that after installation when I open Chrome and go to `Settings > About Chrome` , it shows the following error

<img width="773" alt="AboutChromError" src="https://github.com/microsoft/winget-pkgs/assets/24638137/cd10fd38-98d1-447d-b212-f7c7c8b4c2df">

If I download Chrome manually from web then this issue doesn't show up

### Steps to reproduce

I have tried the following command

`winget install --Id Google.Chrome --version 122.0.6261.112 --silent --scope machine --accept-package-agreements --accept-source-agreements`

and other variation of it with a different version and also a user level scope

### Actual behavior

Chrome's version checker is not working

### Expected behavior

Chrome's version checker should work

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
All WinGet does is download and run the installer, so this must be something with the way Google is hanlding command line installs

**Comment by Ankitr19** [comment]
@SpecterShell I saw that you have recent commits for the Chrome manifest, do you have any idea as why this would be happening?

**Comment by SpecterShell** [comment]
> @SpecterShell I saw that you have recent commits for the Chrome manifest, do you have any idea as why this would be happening?

If Chrome was installed in user scope (did not use `--scope machine` in WinGet when installing Chrome), you can try `winget install Google.GoogleUpdate` to install the missing update component.

If Chrome was installed in machine scope (used `--scope machine` in WinGet when installing Chrome), you can try `winget install Google.Chrome --force` to install the MSI version of Chrome and override the existing one.

**Comment by Trenly** [comment]
@spectershell - should we add Google.GoogleUpdate as a dependency just for the user scoped installers of Google.Chrome ?

**Comment by SpecterShell** [comment]
> @SpecterShell - should we add Google.GoogleUpdate as a dependency just for the user scoped installers of Google.Chrome ?

Probably not. `Google.GoogleUpdate` does not write ARP entries to registry, so adding it as a dependency could cause WinGet to install it every time it upgrades `Google.Chrome` as WinGet can not find that ARP entry.

**Comment by Trenly** [comment]
> > @SpecterShell - should we add Google.GoogleUpdate as a dependency just for the user scoped installers of Google.Chrome ?
> 
> Probably not. `Google.GoogleUpdate` does not write ARP entries to registry, so adding it as a dependency could cause WinGet to install it every time it upgrades `Google.Chrome` as WinGet can not find that ARP entry.

Does it always install the files to the same location?

**Comment by SpecterShell** [comment]
> > > @SpecterShell - should we add Google.GoogleUpdate as a dependency just for the user scoped installers of Google.Chrome ?
> > 
> > 
> > Probably not. `Google.GoogleUpdate` does not write ARP entries to registry, so adding it as a dependency could cause WinGet to install it every time it upgrades `Google.Chrome` as WinGet can not find that ARP entry.
> 
> Does it always install the files to the same location?

In user scope it is installed in `%localappdata%\Google\Update`. In machine scope (although this package can not be installed in machine scope directly) it is stored in `C:\Program Files (x86)\Google\Update`.
