### ISSUE TITLE
[Package Request]: OCBase OCCT

### ISSUE THREAD

**Issue by JamiePaton** [microsoft/winget-pkgs#147718]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.ocbase.com/download
Publisher: OCBase
Package Name: OCCT
Description: OCCT has a test for every major component in your system. We sometimes even have several just to get you covered. If there's something wrong, we'll report it, and OCCT's reputation at finding flaws will help you get the faulty part RMA'ed.
Package Version: 12.1.18
Installer URL: https://www.ocbase.com/download/edition:Personal

**Comment by Dragon1573** [comment]
Excuse me @JamiePaton, could you please provide following informations? I need them for creating manifest 🙏🏼

1. Is this package a "standalone portable executable"?
2. The test environment of mine is under control of my company. It's currently in a domain. When launching `OCCT.exe`, it will prompt a GUI dialog requesting **Pro or Enterprise License**. This may block Azure Pipelines and causing failure of the automation test. Is there any commandline switches for suppressing the dialog?
   ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/836fc063-024b-4d26-af1e-8e44b605867a)
