### ISSUE TITLE
Validation checks failing when they shouldn't

### ISSUE THREAD

**Issue by Phyyl** [microsoft/winget-pkgs#1477]
Not sure if my issue is related to other validation check errors, but I'm also getting validation checks in [my PR](https://github.com/microsoft/winget-pkgs/pull/1474) that should pass but aren't passing.

`Manifest: The Id property of a manifest must include the publisher name and application name separated by a period. actual: 'Devolutions.RemoteDesktopManagerFree', expected 'Devolutions'`

I submitted other manifests with the same format and they all passed.

**Comment by MarNicGit** [comment]
Validation is not failing, see comment: https://github.com/microsoft/winget-pkgs/pull/1474#issuecomment-637600526

**Comment by Phyyl** [comment]
Of course. Sorry about that! 👍
