### ISSUE TITLE
[Package Issue]: HuaWei.QuickAppIde

### ISSUE THREAD

**Issue by msingle** [microsoft/winget-pkgs#147892]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I had previously downloaded VSCodium.
Today when updating packages, that package seemed to match Huawei.QuickAppIde ?
`
nu                      Nushell.Nushell                                0.91.0             0.92.1    winget
VSCodium          Huawei.QuickAppIde                             1.70.2.22230       14.0.1    winget
SharpKeys          RandyRants.SharpKeys                           3.9.0000           3.9.4000  winget
`

### Steps to reproduce

run update

### Actual behavior

Installed a new app?

### Expected behavior

Update existing VSCodium (or do nothing)

### Environment

```raw
Windows Package Manager (Preview) v1.8.924-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.25941.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.924.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

2024-04-05 07:01:05.254 [REPO] Found multiple matches for installed package [{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}_is1] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{d77b7e06-80ba-4137-bcf4-654b95ccebc5}_is1'[Exact] Include:NormalizedNameAndPublisher='vscodium'+'microsoft'[Exact]]
2024-04-05 07:01:05.254 [REPO]   Checking match with package id: Huawei.QuickAppIde
2024-04-05 07:01:05.255 [REPO]   Checking match with package id: VSCodium.VSCodium
2024-04-05 07:01:05.334 [REPO] Found multiple matches for installed package [{a10fbb63-03ff-4b8c-a176-f5fd355f715b}] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{a10fbb63-03ff-4b8c-a176-f5fd355f715b}'[Exact] Include:NormalizedNameAndPublisher='python'+'pythonsoftwarefoundation'[Exact] Include:NormalizedNameAndPublisher='python(x64)'+'pythonsoftwarefoundation'[Exact]]

**Comment by stephengillie** [comment]
Hi @msingle,

Thanks for reporting this.

> 2024-04-05 07:01:05.254 [REPO] Found multiple matches for installed package [{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}_is1] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{d77b7e06-80ba-4137-bcf4-654b95ccebc5}_is1'[Exact] Include:NormalizedNameAndPublisher='vscodium'+'microsoft'[Exact]]
2024-04-05 07:01:05.254 [REPO] Checking match with package id: Huawei.QuickAppIde
2024-04-05 07:01:05.255 [REPO] Checking match with package id: VSCodium.VSCodium

The first `ProductCode` is used in the `Huawei.QuickAppIde` [manifest](https://github.com/microsoft/winget-pkgs/pull/146914/files). It might be used by the `VSCodium.VSCodium` installer but it's not in the manifest to confirm. 

> 2024-04-05 07:01:05.334 [REPO] Found multiple matches for installed package [{a10fbb63-03ff-4b8c-a176-f5fd355f715b}] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{a10fbb63-03ff-4b8c-a176-f5fd355f715b}'[Exact] Include:NormalizedNameAndPublisher='python'+'pythonsoftwarefoundation'[Exact] Include:NormalizedNameAndPublisher='python(x64)'+'pythonsoftwarefoundation'[Exact]]

The second `ProductCode` is in what appears to be the latest `Python.Python.3.10` [manifest](https://github.com/microsoft/winget-pkgs/blob/8cd77b6035e2689580fa2784c017dcab53b080b4/manifests/p/Python/Python/3/10/3.10.11/Python.Python.3.10.installer.yaml#L55) for both scopes of `x64`. 

Some background detalis: 
> The Publish pipeline takes our repo's /manifests contents, and rewrites this into an XML file, which is compressed into source.msix, and put onto a host for our CDN to distribute. Then, running 'winget list" has the client download this MSIX and decompress it, to use as a data source. This data is compared to data under certain Registry paths within HKLM and HKCU, and matching results returned.
https://github.com/microsoft/winget-cli/issues/3921#issuecomment-2037901572

What seems to be occurring is that both `Huawei.QuickAppIde` and `VSCodium.VSCodium` write the same `ProductCode` GUID to the Registry in the first case, and apparently 2 versions of Python in the second case. And so when the package manager reads this data from the Registry, it can't tell the 2 installations apart. 

These appear to be GUID collisions. This implies that additional data might help differentiate these packages.

**Comment by Trenly** [comment]
@denelon - Should this be moved to CLI?

**Comment by SpecterShell** [comment]
The manifests for VSCodium version 1.70.2.22230 have no ProductCode information. Probably the package with ProductCode information will have higher priority when compared with others?
