### ISSUE TITLE
[Update Request]: PageEdit v2.1.0

### ISSUE THREAD

**Issue by palopezv** [microsoft/winget-pkgs#147894]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Sigil-Ebook.PageEdit

### Package Version

2.1.0

### Please describe the changes you would like to see

There is a [new version 2.1.0 available upstream](https://github.com/Sigil-Ebook/PageEdit/releases/tag/2.1.0).

**Comment by Trenly** [comment]
[Policy] In-PR

**Comment by dougmassay** [comment]
Look at the changes made to Sigil's installer yaml for 2.1.0 for advice.
