### ISSUE TITLE
[Package Issue]: VideoLAN.VLC

### ISSUE THREAD

**Issue by segln** [microsoft/winget-pkgs#148017]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

VLC installer on WinGet has no 'Context menus' option.

### [From official website](https://www.videolan.org/vlc/index.html)
![image](https://github.com/microsoft/winget-pkgs/assets/18192378/691511ce-13af-463f-b02b-ed601aaca94b)

### From winget
![image](https://github.com/microsoft/winget-pkgs/assets/18192378/cf876315-adf2-4624-b30c-36185193852e)

### Steps to reproduce

`winget install vlc`

### Actual behavior

The installer has no context menu option.

### Expected behavior

The installer has context menu option.

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3374
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Dragon1573** [comment]
Issue reproduced!

According to the manifest, `winget.exe` is using `x64` **MSI** installer. Do you accidentally using `x64` **EXE** installer file from official website? They're packaged with different installation technology, so available options are also different.

**Comment by segln** [comment]
You are absolutely right. I used EXE installer from official website and used default MSI installer on WinGet.

Issue solved with `--installer-type nullsoft`.
