### ISSUE TITLE
[Package Request]: New package: Microsoft.Promptflow version 1.7.0

### ISSUE THREAD

**Issue by YingChen1996** [microsoft/winget-pkgs#148166]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

pr: https://github.com/microsoft/winget-pkgs/pull/148162/files

Download Page Url: https://promptflowartifact.blob.core.windows.net/msi-installer/promptflow-1.7.0.msi
Publisher: Microsoft Corporation
Package Name: Microsoft Promptflow
Description: Prompt flow is a suite of development tools designed to streamline the end-to-end development cycle of LLM-based AI applications, from ideation, prototyping, testing, evaluation to production deployment and monitoring. It makes prompt engineering much easier and enables you to build LLM apps with production quality.

Package Version: 1.7.0
Installer URL:  https://promptflowartifact.blob.core.windows.net/msi-installer/promptflow-1.7.0.msi

**Comment by Trenly** [comment]
Close with reason: Resolved by PR;
* #148162
