### ISSUE TITLE
[Package Issue]: Microsoft.PowerToys

### ISSUE THREAD

**Issue by og-mrk** [microsoft/winget-pkgs#148119]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

WinGet-CLI Insists on Upgrading Microsoft's Powertoys from version `0.79.0` to `0.80.0`, even though the version that's installed and running is `0.80.0`

> [!NOTE]
> I'm unsure if this's a problem to be reported in this repo, or winget-cli repo, any guidance will help, thanks in advance 😄

### Steps to reproduce

1. Have Microsoft's Powertoys installed on your system, with version `0.79.0` (This is the version I'm having problem with, maybe older version have the same problem when trying to upgrade to version `0.80.0`)
2. Run CMD.exe or PowerShell Terminal as Admin
3. run `winget upgrade Microsoft.PowerToys`
4. Notice that the Program upgraded successfully, but now there's two packages with Identifier `Microsoft.PowerToys` listed when running `winget list`, but with different versions.

### Actual behavior

Upgraded `Microsoft.PowerToys` but there's two Packages of it, with different versions.
Plus, when trying to upgrade using `winget upgrade Microsoft.PowerToys` or `winget upgrade --all`, it'll try and upgrade to version `0.80.0`, even though it's already upgraded.

### Expected behavior

Microsoft's Powertoys upgrades without problems

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/70659536/b6dd60cb-5c7f-4cdc-a257-cb93323bf03e)

**Comment by stephengillie** [comment]
Hi @og-mrk,

Thanks for adding a screenshot. This happens sometimes when a package that's not designed for side-by-side install becomes installed twice, through a bug or other unexpected situation. Could that have happened here?

**Comment by og-mrk** [comment]
> Hi @og-mrk,
> 
> Thanks for adding a screenshot. This happens sometimes when a package that's not designed for side-by-side install becomes installed twice, through a bug or other unexpected situation. Could that have happened here?

Hello @stephengillie,

No problem with the screenshots, happy it was useful 😄
And this problem might be related to winget-cli it self, not really to the PowerToys package, as I don't really see why it would fail (Nothing out of the ordinary when comparing the Installer manifest files).

I'll keep this issue open, as I'm unsure the root case of it, further investigation will be required to know why it happens.

**Comment by stephengillie** [comment]
It's not impossible that an internal error might cause incorrect output, but usually a duplicate package entry is caused by a duplicate Registry entry. Does the Apps and features Settings page (or the Control Panel's Add and Remove Programs page) have 2 entries for this also, or just one? 

Generally, the package manager downloads a file with all of the manifest data, then compares this with the data in the Registry, returning matching results. These pages read the same Registry entries, so they can give another perspective of the data stored there.

**Comment by og-mrk** [comment]
> It's not impossible that an internal error might cause incorrect output, but usually a duplicate package entry is caused by a duplicate Registry entry. Does the Apps and features Settings page (or the Control Panel's Add and Remove Programs page) have 2 entries for this also, or just one?

Yes there's 2 entries in Apps and Features Settings page, **_see screenshot below_**.

![image](https://github.com/microsoft/winget-pkgs/assets/70659536/e659939b-0c5f-41da-8943-8af87916179b)

**Comment by stephengillie** [comment]
If you click on the 3 dots to the right, is it possible to uninstall the older version? (If trying this won't work out, it's okay.)

**Comment by og-mrk** [comment]
> If you click on the 3 dots to the right, is it possible to uninstall the older version? (If trying this won't work out, it's okay.)

Shows that a specific registry key isn't available, **_screenshot below_**.

![image](https://github.com/microsoft/winget-pkgs/assets/70659536/731d64e7-ac2a-4e37-ad99-9b02030455a8)

Trying to uninstall PowerToys in general isn't possible using WinGet, getting `Ox800401f5 : unknown error`, **_screenshot below_**.

![image](https://github.com/microsoft/winget-pkgs/assets/70659536/913e5917-7eeb-4385-93fc-616b817fb372)

**Comment by stephengillie** [comment]
Thanks for these. Could it be that the Registry entry *is* available, but the files it points to aren't? 

It seems like a 2nd Registry entry got created somehow. The fix would be removing that entry. Some common ways are:
- Uninstall the program through other means, such as the Apps and features Settings page, from the installer, or maybe with uninstaller software. 
  - Then run this again, to remove the other Registry entry. 
  - Then reinstall with the package manager. 
- Edit the Registry, with the Registry Editor or another tool. (Caution: not recommended, as it's easy to accidentally change the wrong setting, and there might not be an undo or backup.) 

Fixing this might be outside of the package manager's current abilities.

**Comment by og-mrk** [comment]
> Thanks for these. Could it be that the Registry entry _is_ available, but the files it points to aren't?

This is true, there's a Registry Key for `0.79.0` version of Microsoft's PowerToys, but the Files for it isn't available, because while upgrading PowerToys using winget-cli, the newer version (`0.80.0`) of the package has deleted the older one (`0.79.0`).


> It seems like a 2nd Registry entry got created somehow. The fix would be removing that entry. Some common ways are:
> 
> * Uninstall the program through other means, such as the Apps and features Settings page, from the installer, or maybe with uninstaller software.
>   
>   * Then run this again, to remove the other Registry entry.
>   * Then reinstall with the package manager.
> * Edit the Registry, with the Registry Editor or another tool. (Caution: not recommended, as it's easy to accidentally change the wrong setting, and there might not be an undo or backup.)

I've fixed the Registry issue by using a Free and Open Source program called **BCUninstaller**, used it to get and delete the Registry Key for PowerToys version `0.79.0`, [link to their GitHub Repo](https://github.com/Klocman/Bulk-Crap-Uninstaller).

> Fixing this might be outside of the package manager's current abilities.

I do agree on this, while the root of this problem might be related to PowerToys Package it selfg (Very Unlikely, the package manifest is quite normal IMHO), or WinGet it self, _it would make sense that WinGet makes a Registry Backup of the old version, then purges said version, then installs the new version... but I don't have a say on this, due to my own lack of expertise in this field._

------

Will close this issue, as this problem has been fixed for me using the above solution, thanks for the help/feedback @stephengillie 😄
