### ISSUE TITLE
[Package Issue]: Microsoft.RemoteDesktopClient no start menu shortcut in machine scope

### ISSUE THREAD

**Issue by ChrisWarrenCodux** [microsoft/winget-pkgs#148161]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

As of version 1.2.5112.0, the yaml file was revised and the below was removed from the machine scope installs.  Without this installer switch, no start menu shortcut is deployed for users. 
```
  InstallerSwitches:
    Custom: ALLUSERS=1
```

### Steps to reproduce

This will fail
```
winget install --id Microsoft.RemoteDesktopClient --version 1.2.5326.0 --scope machine --silent
```
This will work as expected
```
winget install --id Microsoft.RemoteDesktopClient --version 1.2.5326.0 --scope machine --silent  --custom ALLUSERS=1
```

### Actual behavior

No Start Menu shortcut is added when installed with the --scope machine switch.

### Expected behavior

When the app is installed, with the machine scope, all users get the desktop shortcut.

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by stephengillie** [comment]
I believe the package manager doesn't create shortcut `.lnk` files, so this request might need to be made to the team supporting Remote Desktop Client, to modify their installer application.

**Comment by ChrisWarrenCodux** [comment]
Yep, its not the package managers responsibility to create .lnk files.   In an ideal world the installer would create this shortcut when installed in the machine scope, however, the --custom ALLUSERS=1 switch seems to be responsible for this action.
