### ISSUE TITLE
[Package Issue]:  TheDocumentFoundation.LibreOffice.HelpPack

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#148657]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Side-By-Side installation.

### Brief description of your issue

In the repository is present only the fresh branch. It is necessary to add a LTS one, that is the natural companion of the package TheDocumentFoundation.LibreOffice.LTS .

### Steps to reproduce

winget search  TheDocumentFoundation.LibreOffice.HelpPack

### Actual behavior

There is only a package listed that is that of the fresh branch.

### Expected behavior

One more package is yo be added of the form:  TheDocumentFoundation.LibreOffice.HelpPack.LTS for the LTS branch.

### Environment

```raw
Directory WinGet
-----------------------------------------------------------------------------------------------------------------------
Log                                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Impostazioni utente                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Directory collegamenti portabili (utente)   %LOCALAPPDATA%\Microsoft\WinGet\Links
Directory collegamenti portabili (computer) C:\Program Files\WinGet\Links
Radice pacchetto portabile (utente)         %LOCALAPPDATA%\Microsoft\WinGet\Packages
Radice pacchetto portabile                  C:\Program Files\WinGet\Packages
Radice pacchetto portabile (x86)            C:\Program Files (x86)\WinGet\Packages
Download del programma di installazione     %USERPROFILE%\Downloads

Collegamenti
------------------------------------------------------------------------------------
Informativa sulla privacy    https://aka.ms/winget-privacy
Contratto di licenza         https://aka.ms/winget-license
Comunicazioni di terze parti https://aka.ms/winget-3rdPartyNotice
Home page                    https://aka.ms/winget
Condizioni di Windows Store  https://www.microsoft.com/en-us/storedocs/terms-of-sale

Impostazione amministrazione              Stato
------------------------------------------------------
LocalManifestFiles                        Disabilitate
BypassCertificatePinningForMicrosoftStore Disabilitate
InstallerHashOverride                     Disabilitate
LocalArchiveMalwareScanOverride           Disabilitate
```

**Comment by Edoardo66** [comment]
Last version of the still branch (LTS) download url: [https://download.documentfoundation.org/libreoffice/stable/7.6.6/win/x86_64/LibreOffice_7.6.6_Win_x86-64_helppack_it.msi](url)

**Comment by exoosh** [comment]
> Last version of the still branch (LTS) download url: [https://download.documentfoundation.org/libreoffice/stable/7.6.6/win/x86_64/LibreOffice_7.6.6_Win_x86-64_helppack_it.msi](url)

That's the localized version for Italian, though.

**Comment by Edoardo66** [comment]
> > Last version of the still branch (LTS) download url: [https://download.documentfoundation.org/libreoffice/stable/7.6.6/win/x86_64/LibreOffice_7.6.6_Win_x86-64_helppack_it.msi](url)
> 
> That's the localized version for Italian, though.

This is only for example. All of them can be downloaded from parent directory ( [https://download.documentfoundation.org/libreoffice/stable/7.6.6/win/x86_64/](url) )

**Comment by Edoardo66** [comment]
Package was added
