### ISSUE TITLE
[Package Request]: Adobe InDesign

### ISSUE THREAD

**Issue by tarunsinghhf** [microsoft/winget-pkgs#148919]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.adobe.com/ca/products/indesign/free-trial-download.html
Publisher: Adobe 
Package Name: Adobe Indesign
Description: Indesign
Package Version: N/A
Installer URL: https://www.adobe.com/ca/products/indesign/free-trial-download.html

**Comment by Dragon1573** [comment]
Excuse me @tarunsinghhf, The [download page url](https://www.adobe.com/ca/products/indesign/free-trial-download.html) and [installer url](https://www.adobe.com/ca/products/indesign/free-trial-download.html) does not provide direct link to the installer file.

Users seem have to login and pick a subscription for downloading the trail version of _Adobe Indesign_. If there's any other pages that can provide direct link (vanity or version-related are both acceptable) to the installer file, could you please provide it here?

**Comment by tarunsinghhf** [comment]
Hi @Dragon1573 , Sorry for that as Adobe has stopped providing direct download links for softwares since 2020. If uploading this package is not possible lets leave that.

Can you help me upload the following softwares to winget though?

**Console Plus** 

Download Page Url: https://www.cryopakdigital.com/software/
Publisher: Cryopak
Package Name: Consoleplussetup.zip
Description: Cryopak Digital temperature monitoring solution
Package Version: N/A
Installer URL: https://miradorexpress.com/upgrade/ConsolePlusSetup.zip

**Filezilla Server**
Download Page Url: https://filezilla-project.org/download.php?platform=win64&type=server
Publisher: Filezilla
Package Name: FileZilla_Server_1.8.1_win64-setup.exe
Description: FileZilla Server
Package Version: 1.8.1
Installer URL: https://dl3.cdn.filezilla-project.org/server/FileZilla_Server_1.8.1_win64-setup.exe?h=IYBUhb9Ct5mvJOPFFMddWA&x=1713190526

**Filezilla Client**
Download Page Url: https://filezilla-project.org/download.php?platform=win64
Publisher: Filezilla
Package Name: FileZilla_3.66.5_win64_sponsored2-setup.exe
Description: FileZilla Client for Windows
Package Version: 3.66.5
Installer URL: https://download.filezilla-project.org/client/FileZilla_3.66.5_win64_sponsored2-setup.exe

**Genesys Cloud**
Download Page Url: https://apps.mypurecloud.com/directory-windows/
Publisher: Genesys Cloud
Package Name: genesys-cloud-windows-2.34.771.exe
Description: Genesys Cloud
Package Version: 2.34.771
Installer URL: https://app.mypurecloud.com/directory-windows/build-assets/2.34.771-90/genesys-cloud-windows-2.34.771.exe

**Zebra Printer Utilities**
Download Page Url: https://www.zebra.com/us/en/support-downloads/printer-software/printer-setup-utilities.html
Publisher: Zebra
Package Name: zsu-1191325.exe
Description: Zebra Printer Utilities
Package Version: 1191325
Installer URL: https://www.zebra.com/us/en/support-downloads/eula/unrestricted-eula.7b8a235653193b4c72c440110c25661656f56f5180957c98e7c0bc2144149cd156a1bc6e684725abae8eaa3b64ee1090eb44d0c7df0abb7f8ed97b5b3f7c9a5376e9eb05b8b828d41d895371710557b9df8c658334af4c49d754cef7dadf3fd445653285136f43b7.html#

Please let me know if you require any additional information.
Regards,
Tarun.

**Comment by Dragon1573** [comment]
> Hi @Dragon1573 , Sorry for that as Adobe has stopped providing direct download links for softwares since 2020. If uploading this package is not possible lets leave that.

Okay, could you please manually close this issue as "not planned"?

> Can you help me upload the following softwares to winget though?

I'm glad to help, but I have to split them into seperate issues. ❤️

**Comment by Dragon1573** [comment]
### Filezilla Server

After inspecting the "download page url", I can't find a static vanity or version-related link to the installer file. :disappointed:

The URL you provided [above](https://dl4.cdn.filezilla-project.org/server/FileZilla_Server_1.8.1_win64-setup.exe?h=ObelqqRzdy4ZlRsvad8QpQ&x=1713199838) contains 2 parameters `?h=&x=`, and both of them are dynamically generated each time you visit the download page. `winget.exe` does not support this kind of package at the moment.

### Filezilla Client

Seems automated downloading is not welcome on *FileZilla*'s site. Validation pipelines and `winget.exe` on user's device will be blocked by the server.

```text
00:06:28 (base) D:\...\winget-pkgs master ≡ 40.275s 0x0001 pwsh> komac new --output .
> Package identifier: FileZilla.FileZilla.Client
> Package version: 3.66.5
> 1st Installer URL https://download.filezilla-project.org/client/FileZilla_3.66.5_win64_sponsored2-setup.exe
? 2nd Installer URL <canceled>
Error:
   0: https://download.filezilla-project.org/client/FileZilla_3.66.5_win64_sponsored2-setup.exe returned 403 Forbidden
```
