### ISSUE TITLE
[Update Request]: Powershell 7.4.2

### ISSUE THREAD

**Issue by vulpicastor** [microsoft/winget-pkgs#148928]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Powershell

### Package Version

7.4.2

### Please describe the changes you would like to see

A new release is available: https://github.com/PowerShell/PowerShell/releases/tag/v7.4.2

**Comment by Exorcism0666** [comment]
Close with reason: Resolved by https://github.com/microsoft/winget-pkgs/pull/148951;

**Comment by mdanish-kh** [comment]
Close with reason: Stated above;
