### ISSUE TITLE
[Update Request]: Subtitle Edit 4.0.5

### ISSUE THREAD

**Issue by niksedk** [microsoft/winget-pkgs#149002]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Nikse.SubtitleEdit

### Package Version

4.0.5

### Please describe the changes you would like to see

There is a new release available
PR: https://github.com/microsoft/winget-pkgs/pull/149000

https://github.com/SubtitleEdit/subtitleedit/releases/tag/4.0.5

**Comment by KaranKad** [comment]
Close with reason: Resolved in https://github.com/microsoft/winget-pkgs/pull/149000;
