### ISSUE TITLE
Where can I find licenses?

### ISSUE THREAD

**Issue by Meteor24** [microsoft/winget-pkgs#14914]
Hi. I would like to contribute to the directory but don't know any good sources to find licenses for programs I want to add. Any help would be greatly appreciated.

**Comment by iDolmatov** [comment]
The licenses are provided by the owners of a programs. If the site does not have a license or you cannot find a direct link, then leave this field blank.

**Comment by jedieaston** [comment]
But type “name of software” + EULA into Google and you’ll usually find something.

**Comment by Meteor24** [comment]
Thank you
