### ISSUE TITLE
[Package Request]: Console Plus

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#149309]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

- Download Page Url: https://www.cryopakdigital.com/software/
- Publisher: Cryopak
- Package Name: Console Plus
- Description: Cryopak Digital temperature monitoring solution
- Package Version: N/A
- Installer URL: https://miradorexpress.com/upgrade/ConsolePlusSetup.zip

_Originally posted by @tarunsinghhf in https://github.com/microsoft/winget-pkgs/issues/148919#issuecomment-2056847664_

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/149317
```

**Comment by vikingnope** [comment]
This should be closed as there is already the following package for it which is a newer version: https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.5611

**Comment by og-mrk** [comment]
Hello @Dragon1573
Thanks for opening this request, now I've tested the `.exe` installer that's inside the downloaded `.zip` file, and sadly I can't seem to find a way to install it in Silent Mode, which's a requirement for any program to be accepted into the winget packages repo.
If you, _and anyone who've the time to test this program_, know a way to do the above Install it silently, then please go ahead and share it here, or open a PR for this program.

**Comment by Dragon1573** [comment]
@og-mrk @vikingnope Thanks for your help ❤️

Successfully inspected by _Komac v2.2.0_. The nested installer wizard is packaged by _InnoSetup_.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Because of the following reason, this issue is not able to be solved. Close as "not planned".
>
> - https://github.com/microsoft/winget-pkgs/pull/149317#issuecomment-2057145661
>
> The installer wizard requires a graphical approval for installing "driver application". `winget.exe` does not support installing this kind of package.

@stephengillie - Could you please add https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/DriverInstall (or other related labels) to this issue? Thank you ❤️

CC @tarunsinghhf
