### ISSUE TITLE
[Update Request]: TortoiseSVN

### ISSUE THREAD

**Issue by Regtur1983** [microsoft/winget-pkgs#149613]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TortoiseSVN.TortoiseSVN

### Package Version

1.14.7

### Please describe the changes you would like to see

There is a new version available: 1.14.7
Downloadlink: https://sourceforge.net/projects/tortoisesvn/files/1.14.7/Application/TortoiseSVN-1.14.7.29687-x64-svn-1.14.3.msi/download

**Comment by Regtur1983** [comment]
This issue is regarding version 1.14.7.

**Comment by vikingnope** [comment]
@Regtur apologies but I wrote the version number wrong, will fix it sorry
