### ISSUE TITLE
[Update Request]:  Logi Options+

### ISSUE THREAD

**Issue by felixsanz** [microsoft/winget-pkgs#149649]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Logitech.OptionsPlus

### Package Version

1.68.542186

### Please describe the changes you would like to see

They change the installer "logioptionsplus_installer.exe" all the time, so the hash changes.

```
❯ winget install -e --id Logitech.OptionsPlus
Found an existing package already installed. Trying to upgrade the installed package...
Found Logi Options+ [Logitech.OptionsPlus] Version 1.68.542186
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.exe
  ██████████████████████████████  29.3 MB / 29.3 MB
Installer hash does not match.
```

But they don't version the package so... Can someone update the hash please?

**Comment by felixsanz** [comment]
I don't want to break it, so if anyone wants to take care of the change here is a previous upgrade example:

https://github.com/microsoft/winget-pkgs/pull/111465/files

**Comment by vikingnope** [comment]
This is probably caused by a new version, will release an update for it
