### ISSUE TITLE
[Update Request]: PuTTy

### ISSUE THREAD

**Issue by Regtur1983** [microsoft/winget-pkgs#149610]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

PuTTY.PuTTY

### Package Version

0.81

### Please describe the changes you would like to see

There is a new release available: 0.81
Download link: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.81-installer.msi

**Comment by vikingnope** [comment]
This update is already in the manifest as can be seen here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PuTTY/PuTTY/0.81.0.0

**Comment by Regtur1983** [comment]
My apologies. Closing it now.
