### ISSUE TITLE
[Update Request]:  Godot 4.2.2

### ISSUE THREAD

**Issue by cjmaxik** [microsoft/winget-pkgs#149765]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GodotEngine.GodotEngine

### Package Version

4.2.2

### Please describe the changes you would like to see

GitHub release: https://github.com/godotengine/godot/releases/tag/4.2.2-stable
Direct link: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_win64.exe.zip

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/149751

**Comment by BiosPlus** [comment]
@Exorcism0666 You've got a code suggestion holding up the approval ;)

**Comment by og-mrk** [comment]
Made a new PR to add Godot version 4.2.2, [link to it](https://github.com/microsoft/winget-pkgs/pull/150735)
