### ISSUE TITLE
[Update Request]: CCleaner

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#149818]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Piriform.CCleaner

### Package Version

6.23.11010

### Please describe the changes you would like to see

There is a new update available

**Comment by vikingnope** [comment]
Related PR: https://github.com/microsoft/winget-pkgs/pull/149757

**Comment by stephengillie** [comment]
> Related PR: #149757

It's merged.
