### ISSUE TITLE
[Update Request]: New version: Microsoft.Promptflow version 1.9.0

### ISSUE THREAD

**Issue by 0mza987** [microsoft/winget-pkgs#149811]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Promptflow

### Package Version

1.9.0

**Comment by 0mza987** [comment]
Related PR is https://github.com/microsoft/winget-pkgs/pull/149780

**Comment by aisgbnok** [comment]
Since #149780 was merged, this can be closed?

**Comment by Trenly** [comment]
Close with reason: Resolved by above linked PR;
