### ISSUE TITLE
[Package Issue]: FireDaemon.OpenSSL

### ISSUE THREAD

**Issue by pjhavariotis** [microsoft/winget-pkgs#150085]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Different install technology.

### Brief description of your issue

I'm trying to upgrade from 3.2.1 -> 3.3.0 and I'm getting the following error:
`A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.`

### Steps to reproduce

`winget upgrade --id FireDaemon.OpenSSL`

### Actual behavior

```
PS C:\Users\p.chavariotis> winget upgrade --id FireDaemon.OpenSSL
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
```

### Expected behavior

Download and upgrade the package

### Environment

```raw
Windows: Windows.Desktop v10.0.19045.4291
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by vikingnope** [comment]
Have you tried uninstalling 3.2.1 and installing version 3.3.0?

**Comment by pjhavariotis** [comment]
> Have you tried uninstalling 3.2.1 and installing version 3.3.0?

No

**Comment by vikingnope** [comment]
Try that and see how it goes if possible

**Comment by pjhavariotis** [comment]
The following 2 commands finished Successfully !
```
winget remove --id FireDaemon.OpenSSL
winget install --id FireDaemon.OpenSSL
```

**Comment by pjhavariotis** [comment]
However, the `upgrade `function should work!

**Comment by vikingnope** [comment]
It was probably some conflicting files from previous versions which caused the issue.

**Comment by stephengillie** [comment]
> However, the `upgrade `function should work!

I believe that automating this currently manual process (finding and running the previous version uninstaller before running the current version installer) is planned, but might be lower priority than other work. This error isn't usually encountered when both the previous and current versions have manifests in the repo - the usual case is when performing `upgrade` for the first time. But here, it seems that the installer technology changed between versions.

**Comment by pjhavariotis** [comment]
This issue remains (from 3.3.0 -> 3.3.1)!
`A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.`

**Comment by mdanish-kh** [comment]
This is because the package is an `MSI` bundled inside of a `EXE` installer. If you run `winget upgrade FireDaemon.OpenSSL --verbose-logs --open-logs` and see the latest generated log file, you would be able to see the line at the end

```
2024-07-10 11:24:38.198 [CLI ] Installer [X64,exe,Machine,] not applicable: Installed package type 'msi' is not compatible with installer type exe
```	

I think this'll get fixed if we add `AppsAndFeatures > InstallerType: msi` in its manifest to let WinGet know it's a nested MSI

---

In the meantime you can use `winget upgrade FireDaemon.OpenSSL --force` to ignore the installer type warning and continue with the upgrade

**Comment by pjhavariotis** [comment]
Unfortunately, I'm getting the same error: 
`2024-07-11 13:53:34.040 [CLI ] Installer [X64,exe,Machine,] not applicable: Installed package type 'msi' is not compatible with installer type exe`

**Comment by mdanish-kh** [comment]
PR https://github.com/microsoft/winget-pkgs/pull/162349 _should hopefully_ fix the issue. You'll have to try again once that's merged and published. Did `--force` work for you though?

**Comment by pjhavariotis** [comment]
No. The error I shared before is with the `--force` option.

**Comment by mdanish-kh** [comment]
@pjhavariotis PR https://github.com/microsoft/winget-pkgs/pull/162349 is now merged. Can you try again now?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by pjhavariotis** [comment]
Issue resolved!

**Comment by mdanish-kh** [comment]
Close with reason: Issue resolved;
