### ISSUE TITLE
[Package Issue]: SublimeHQ.SublimeText.4 version cannot be determined

### ISSUE THREAD

**Issue by johnburnett** [microsoft/winget-pkgs#150026]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The version of the installed package cannot be determined, which blocks upgrades.

### Steps to reproduce

Initial install succeeds fine:
```
PS> winget install SublimeHQ.SublimeText.4
Found Sublime Text 4 [SublimeHQ.SublimeText.4] Version 4.0.0.416900
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.sublimetext.com/sublime_text_build_4169_x64_setup.exe
  ██████████████████████████████  15.7 MB / 15.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

### Actual behavior

Immediate re-run fails with version number not being determined:
```
PS> winget install SublimeHQ.SublimeText.4
Found an existing package already installed. Trying to upgrade the installed package...
This package's version number cannot be determined. To upgrade it anyway, add the argument --include-unknown to your previous command.
```

### Expected behavior

The same results as packages that seem to work fine.  e.g. `Python.Python.3.11` gives this:
```
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
```

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
```


### Screenshots and Logs

_No response_

**Comment by vikingnope** [comment]
This is probably due to Sublime Text storing the version in the Registry Editor, run this command instead, it should still work normally:

winget install --id SublimeHQ.SublimeText.4 --include-unknown

**Comment by johnburnett** [comment]
I’m aware of the —include-unknown switch as a workaround, but I’m more curious if there’s a way to update the package manifest to allow winget to determine the package version.

**Comment by stephengillie** [comment]
I believe this might be solvable through `AppsAndFeaturesEntries`. The problem here appears to be a matching error - there aren't enough bits in the Registry for the package manager to match against the repo data in source.msix and return only 1 manifest. Instead, I'm guessing that 2 or more manifests are returned. 

Maybe an `UpgradeCode` could be used here? It's a GUID that is written to the Registry, and sometimes added to manifests to help with matching and correlation.

**Comment by vikingnope** [comment]
This is the only thing I found in my RegEdit for Sublime Text

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text_is1`

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/c4f65603-2bd1-4553-996e-a10d3be7a344)

There does not seem to be a ProductCode for it

**Comment by stephengillie** [comment]
Maybe we could use the `InstallDate`? Otherwise, I agree that differentiating bits are sparse here. 

@mdanish-kh and @Trenly, is there another option that we're not seeing here?

**Comment by Trenly** [comment]
Because the UpgradeCode is generally the same across versions, there really isn’t anything we can do to force a version detection. Even a product code would likely only correlate it to the PackageIdentifier.  

Unless the publisher of Sublime updates their installer to add the DisplayVersion registry key, WinGet won’t be able to determine the version.

**Comment by johnburnett** [comment]
I'm very unfamiliar with the workings of winget, so apologies for the basic question but is it possible to look at installed files on disk?  The installed sublime_text.exe has [resource fields](https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa) for both product version and file version.

**Comment by Trenly** [comment]
> I'm very unfamiliar with the workings of winget, so apologies for the basic question but is it possible to look at installed files on disk? The installed sublime_text.exe has [resource fields](https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa) for both product version and file version.

No, only the data in registry is queried

**Comment by johnburnett** [comment]
Gotcha - I’ll poke the Sublime devs then and see if there’s interest on their side in changing the installer.  For clarity, what exactly does winget need to see in the above registry section to get a version number? (e.g. what key name/type/value format)?

**Comment by Trenly** [comment]
> Gotcha - I’ll poke the Sublime devs then and see if there’s interest on their side in changing the installer. For clarity, what exactly does winget need to see in the above registry section to get a version number? (e.g. what key name/type/value format)?

DisplayVersion - I believe it is a REG_SZ

**Comment by johnburnett** [comment]
Just saw this [this known issue](https://github.com/sublimehq/sublime_text/issues/1114) and [this support forum post](https://forum.sublimetext.com/t/winget-not-fully-compatibility-yet/72009/3).  Looks like it's been a known issue for years, with no indication it'll be resolved.  Ah well, I'll close this ticket.
