### ISSUE TITLE
[Package Issue]: Zoom.Zoom

### ISSUE THREAD

**Issue by cprivitere** [microsoft/winget-pkgs#150120]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Zoom has changed its versioning to use parentheses instead of dots for the build number and it is confusing winget about whether the latest version is installed. Thus, winget will always try to update zoom even if the latest version is installed.

Actual version Zoom uses now: `6.0.0 (37205)`
Version winget expects to see: `6.0.0.37205`

### Steps to reproduce

`winget upgrade --all` with Zoom installed.

### Actual behavior

winget reinstalls Zoom even though the latest version is installed.

### Expected behavior

winget should recognize the latest version is installed and not try to update it.

### Environment

```raw
❯ winget --info
Windows Package Manager (Preview) v1.8.924-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.924.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

```
❯ winget upgrade --all
Name           Id             Version       Available   Source
--------------------------------------------------------------
Zoom Workplace XP99J3KP4XZ4VV 6.0.0 (37205) 6.0.0.37205 winget
2 upgrades available.

(1/1) Found Zoom [Zoom.Zoom] Version 6.0.0.37205
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.exe?archType=x64
  ██████████████████████████████  97.9 MB / 97.9 MB
```

**Comment by SpecterShell** [comment]
It is due to the difference in how Zoom official versions the two types of installers, where the machine-wide MSI installer uses `6.0.0 (37205)` while the user-wide EXE installer uses `6.0.0 (37205)`.

Anyway, the EXE one has been moved to a separate package `Zoom.Zoom.EXE` and the versions of `Zoom.Zoom` have been changed to align with the MSI installers.

**Comment by vikingnope** [comment]
So there is a new thing now, instead of using the package called `Zoom.Zoom`, you should install `Zoom.Zoom.Exe`

**Comment by cprivitere** [comment]
Looks like the Zoom.Zoom manifests are properly aligned now. So we can close this. Thanks @SpecterShell.
