### ISSUE TITLE
[Update Request]: DOSBoxStaging

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#150323]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DOSBoxStaging.DOSBoxStaging

### Package Version

0.81.0

### Please describe the changes you would like to see

There is a new release (0.81.0) available. Download Page Url: https://dosbox-staging.github.io/releases/windows/ (https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.0/dosbox-staging-windows-v0.81.0-setup.exe)

**Comment by CoolPlayLin** [comment]
I plan to include this package into my automations
- CoolPlayLin/AutoPublish#27

**Comment by CoolPlayLin** [comment]
@AsciiWolf BTW, if you want to keep software the newest and I don't have automation currently. You could reach https://github.com/CoolPlayLin/AutoPublish/issues/new to request a package automation
