### ISSUE TITLE
[Update Request]: Tencent.TencentDocs

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#150368]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Tencent.TencentDocs

### Package Version

3.5.0.53

### Please describe the changes you would like to see

There's a new version available at [official page](https://docs.qq.com/home/download) as `v3.5.0`.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/09af9367-0cb3-4951-bf1b-f9eb42409d07)

The downloaded package reports itself as _version 3.5.0.53 (stable version) (x64) (30001)_.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a4fdcffb-d116-4896-b2ea-90406b9fea6c)

It seems the download url redirected from official site contains encrypted parameters as follows.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/aa445514-4220-4355-a8e1-533b49331929)
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/150369
- [ ] https://github.com/microsoft/winget-pkgs/pull/150388
```

**Comment by SpecterShell** [comment]
They appear to have moved to a new API lately. 🤔

**Comment by Dragon1573** [comment]
Both 2 pull requests get https://github.com/microsoft/winget-pkgs/labels/Azure-Pipeline-Passed. Does it means the `InstallerUrl` is valid and available to `winget.exe` on all users' devices?

What is the https://github.com/microsoft/winget-pkgs/labels/Validation-Domain here?

> [!NOTE]
>
> The file URL shown in _Motrix_ above can be downloaded directly without attaching those parameters, cookies, user agent and more.
>
> ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/aa1a093f-bd84-4122-a680-c25e658d8a70)
> ![recording](https://github.com/microsoft/winget-pkgs/assets/49941141/89f5311a-4b67-46ec-9f64-98b8e51b4b21)

**Comment by stephengillie** [comment]
> What is the [Validation-Domain](https://github.com/microsoft/winget-pkgs/labels/Validation-Domain) here?

Often, this is because our automated processes couldn't navigate from the `PackageUrl` to the `InstallerUrl`. It's more common with QQ domains than others.
