### ISSUE TITLE
[Package Issue]: RealVNC.VNCViewer, RealVNC.VNCServer

### ISSUE THREAD

**Issue by bjaraujo** [microsoft/winget-pkgs#150613]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The package name of VNC server is not correct (should be like the viewer):

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc |winget
**VNC Server** *   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc |winget

* should be "RealVNC Server"

### Steps to reproduce

No steps necessary

### Actual behavior

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc| winget
VNC Server   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc| winget|

### Expected behavior

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc| winget
RealVNC Server   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc| winget

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4291
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by Trenly** [comment]
Hi @bjaraujo, can you please share a screenshot from `Add & Remove Programs` of the installer entry from RealVNC Server and RealVNC Viewer?

**Comment by bjaraujo** [comment]
That is fine. 
![image](https://github.com/microsoft/winget-pkgs/assets/5067963/2a73a539-e37b-41fa-83a7-73da23d4a393)
The issue is just when doing: winget search vnc.
https://github.com/microsoft/winget-pkgs/blob/238b457d88eac93328a7ee531f810a4bf899d7e7/manifests/r/RealVNC/VNCServer/7.8.0/RealVNC.VNCServer.locale.en-US.yaml#L11

**Comment by Dragon1573** [comment]
@bjaraujo - Unable to solve the issue 😞

_RealVNC_ blocks `winget.exe` from downloading the installer file. Users will get `HTTP 405 Method Not Allowed` error from the server. User agent and cookies are required for the download request. The pull request failed to pass tests on Azure Pipelines and rejected to be merged into the `master` branch.

All manifests related to `RealVNC.VNCServer` and `RealVNC.VNCViewer` are failed. They might need to be totally removed from the repository.

**Comment by bjaraujo** [comment]
> @bjaraujo - Unable to solve the issue 😞
> 
> _RealVNC_ blocks `winget.exe` from downloading the installer file. Users will get `HTTP 405 Method Not Allowed` error from the server. User agent and cookies are required for the download request. The pull request failed to pass tests on Azure Pipelines and rejected to be merged into the `master` branch.
> 
> All manifests related to `RealVNC.VNCServer` and `RealVNC.VNCViewer` are failed. They might need to be totally removed from the repository.

Can you retry now?

**Comment by vikingnope** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/81376423/679ac7e0-140b-4058-a225-c491e95ca132)

**Comment by Dragon1573** [comment]
> Can you retry now? (I believe the captcha has been removed)

Branch resotred and pull request repoened. See https://github.com/microsoft/winget-pkgs/pull/150625#issuecomment-2077182821

**Comment by vikingnope** [comment]
@bjaraujo, can the title of this issue be changed to the following please: 

[Package Issue]: RealVNC.VNCViewer, RealVNC.VNCServer
