### ISSUE TITLE
[Update Request]: IDMComputerSolutions,Inc.UltraEdit

### ISSUE THREAD

**Issue by pitichou** [microsoft/winget-pkgs#150803]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IDMComputerSolutions,Inc.UltraEdit

### Package Version

31.0.0.28

### Please describe the changes you would like to see

Everytime there is a new release for UltraEdit, the version number is wrong.
31.0.28 but it should be 31.0.0.28.

Already reported here: https://github.com/microsoft/winget-pkgs/issues/133241

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/150183
