### ISSUE TITLE
[Update Request]: reMarkable.reMarkableCompanionApp update to 3.10.0.845

### ISSUE THREAD

**Issue by kris6673** [microsoft/winget-pkgs#150809]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

reMarkable.reMarkableCompanionApp

### Package Version

3.10.0.845

### Please describe the changes you would like to see

New release available from this download URL: https://downloads.remarkable.com/latest/windows
Current package cannot install since hashes do not match

**Comment by BiosPlus** [comment]
I borked the original PR for this by misconfiging the nestedinstallertype flag.

Fix for it is in #150934.

Thanks @kris6673 for pointing out it was failing.

**Comment by BiosPlus** [comment]
You can solve for the additional remarkable download by deleting the reMarkable directory in `%LOCALAPPDATA%\Microsoft\WinGet\Packages\` since it's just sitting in there taking up space.

![image](https://github.com/microsoft/winget-pkgs/assets/9003059/8c792b13-4c71-44ab-8623-fb2171d37926)
