### ISSUE TITLE
[Update Request]: IrfanSkiljan.IrfanView v4.67

### ISSUE THREAD

**Issue by Kaligula0** [microsoft/winget-pkgs#150840]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IrfanSkiljan.IrfanView

### Package Version

4.67

### Please describe the changes you would like to see

There is a new version available (4.67). Download page: https://www.irfanview.com/

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/150884

**Comment by Kaligula0** [comment]
Thank you!

**Comment by stephengillie** [comment]
> Completed already: #150884
