### ISSUE TITLE
[Package Issue]: WinAuth.WinAuth

### ISSUE THREAD

**Issue by xCephandrius** [microsoft/winget-pkgs#151056]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The cmd 'winget install WinAuth.WinAuth' completes, but the application doesn't seem to install to system.  Its not registered as an app, nor can I find it as a standalone/portable file.

### Steps to reproduce

winget install WinAuth.WinAuth

### Actual behavior

Nothing seems to happen

### Expected behavior

Should have the app installed after cmd successfully runs

### Environment

```raw
C:\Users\Nate>winget --info
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
It seems to install and run fine on my VM. Can you provide the following information?

* Logs from the install
* Logs from `winget install winauth --verbose` (after uninstalling)
* Have you closed and re-opened your terminal session before trying to run the `winauth` command?
* Is developer mode enabled on your machine?
* Did you install using an administrator terminal or a user-scoped terminal?
