### ISSUE TITLE
[Update Request]: Lime3DS 2110

### ISSUE THREAD

**Issue by ItachiSan** [microsoft/winget-pkgs#151164]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Lime3DS.Lime3DS

### Package Version

2110

### Please describe the changes you would like to see

The package has a new release: 2110
Download URL:
https://github.com/Lime3DS/Lime3DS/releases/download/2110/lime3ds-2110-windows-msvc.zip

**Comment by ItachiSan** [comment]
@BiosPlus is it possible also to add a link to the QT frontend?
It is the `lime-qt` app in the ZIP.

**Comment by BiosPlus** [comment]
@itachisan
Answered here: https://github.com/microsoft/winget-pkgs/pull/151168#issuecomment-2080368567

tl;dr: Is not possible at this point.
