### ISSUE TITLE
[Update Request]: EaseUS Partition Master version 18.5

### ISSUE THREAD

**Issue by ArmandDelessert** [microsoft/winget-pkgs#151336]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

EaseUS.PartitionMaster

### Package Version

18.5

### Please describe the changes you would like to see

A newer version of EaseUS Partition Master is available:
[EaseUS® Partition Master Editions History](https://www.easeus.com/partition-manager/history.html)

**Comment by vikingnope** [comment]
Do you have a static download link for the file?

**Comment by ArmandDelessert** [comment]
No, I'm sorry. I couldn't find a link to download the offline installer.

**Comment by vikingnope** [comment]
Then I think we will have to skip this, as I am unable to find a static URL

**Comment by stephengillie** [comment]
We accept dynamic URLs also. There's currently no requirement for static URLs.

**Comment by Dragon1573** [comment]
Inspect from [this page](https://www.easeus.com/partition-manager/history.html), [the installer file URL](https://download2.easeus.com/epm.php?product=epm_trial&tid=A&id=17145555275072b2495&dateline=1714555528) (has expired) points to a `*.php` page, with parameters `product`, `tid`, `id` and `dateline`. The publisher does not provide a vanity URL. 😞

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/f33e1e66-c46f-45ca-ad62-31be52e7c98b)
![image](https://github.com/microsoft/winget-pkgs/assets/49941141/b633f4cb-1cea-413b-ba0e-fada5be109e9)

**Comment by zarabaig0** [comment]
# [💹🔽⏬ Download Here EaseUS Partition Master Version 💹🔽⏬](https://corlubar.com/dl/)

**Comment by zacharymiller66** [comment]
# [EaseUS Partition Master Version Download](https://wp.me/sgJOlZ-ddl)

**Comment by binteu4** [comment]
# [[Update Request]: EaseUS Partition Master Version Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)

**Comment by gafoorr0** [comment]
# [[Package Request]: EaseUS Partition Master Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)
