### ISSUE TITLE
[Package Request]: iPerf3

### ISSUE THREAD

**Issue by sidy3d** [microsoft/winget-pkgs#151395]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://iperf.fr/iperf-download.php
Publisher: ESnet
Package Name: iPerf3
Description: iPerf3 is a tool for active measurements of the maximum achievable bandwidth on IP networks.
Package Version: 3.16
Installer URL: https://iperf.fr/iperf-download.php

**Comment by Trenly** [comment]
Duplicate of #1173
