### ISSUE TITLE
[Package Request]: oxipng

### ISSUE THREAD

**Issue by sidy3d** [microsoft/winget-pkgs#151396]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/shssoichiro/oxipng
Publisher: shssoichiro
Package Name: oxipng
Description: Oxipng is a multithreaded lossless PNG/APNG compression optimizer.
Package Version: 9.1.1
Installer URL: https://github.com/shssoichiro/oxipng/releases/tag/v9.1.1

**Comment by Trenly** [comment]
[Policy] In PR
