### ISSUE TITLE
[Update Request]: MongoDB server version 7.0.9

### ISSUE THREAD

**Issue by alimohsin05** [microsoft/winget-pkgs#151597]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MongoDB.Server

### Package Version

7.0.9

### Please describe the changes you would like to see

There is a new release (7.0.9.0) available. Download page URL: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-7.0.9-signed.msi
The current version offered by winget is v6.0.6.
<img width="638" alt="mongo server" src="https://github.com/microsoft/winget-pkgs/assets/166210728/bed16e04-49d7-484c-9d2e-46c993520858">
MongoDB has added the version 6.0.6 into archived released due to critical issues.
<img width="559" alt="MongoDB Server issue" src="https://github.com/microsoft/winget-pkgs/assets/166210728/e9399c36-04aa-4c88-9f4a-10f1eaea1a13">

**Comment by Trenly** [comment]
[Policy] In PR
