### ISSUE TITLE
[Update Request]: Git.Git to version 2.45.0

### ISSUE THREAD

**Issue by michha** [microsoft/winget-pkgs#151605]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Git.Git

### Package Version

2.45.0

### Please describe the changes you would like to see

New Release 2.45.0 available, see https://git-scm.com/download/win

**Comment by Utesgui** [comment]
#151542

**Comment by Trenly** [comment]
[Policy] In PR

**Comment by PckgrTom** [comment]
Hi,

This PR has been merged.

**Comment by CoolPlayLin** [comment]
This issue should be marked as complete

**Comment by mdanish-kh** [comment]
Close with reason: 2.45.0 is merged into the repo;
