### ISSUE TITLE
Failed Checks

### ISSUE THREAD

**Issue by Meteor24** [microsoft/winget-pkgs#15179]
I tried to add a program to the winget directory but it says I failed two of the checks and asked if I forgot to add a "Silent" or "SilentWithProgress" switch. I don't know how to add those and would like some help in rectifying the situation.
Heres the link to the pull request in case it helps:  https://github.com/microsoft/winget-pkgs/pull/14919

**Comment by iDolmatov** [comment]
You write `InstallerType: nullsoft`
https://www.silentinstall.org/nsis
https://documentation.help/NSIS/Section4.12.html

Need write **/S** as switches. You write without /S.

**Comment by iDolmatov** [comment]
>  Have you validated your manifest locally with winget validate --manifest <path>?
> Have you tested your manifest locally with winget install --manifest <path>?
True? Local test is worked as hidden installer?

**Comment by Meteor24** [comment]
I will go through the process again as I don't remember the exact results

**Comment by Meteor24** [comment]
Also which document do I put the installertype: Nullsoft and switches in and what line

**Comment by OyePradumya** [comment]
#15198 #15200 these two submissions reported failed but on my system it installed just fine without silent switching or anything, I tested on my local machine with winget install -m "path/to/manifest" 
Please help. I would request you to please test it yourself.

**Comment by OfficialEsco** [comment]
When the `InstallerType` is `msi, msix, inno, nullsoft, appx, wix or burn` WinGet already know the silent switches so there is no need to add them 99% of the time, only for exe you would require to add `InstallerSwitches`.
If the InstallerType is one of those there is probably a problem somewhere else.

**Comment by OyePradumya** [comment]
> When the `InstallerType` is `msi, msix, inno, nullsoft, appx, wix or burn` WinGet already know the silent switches so there is no need to add them 99% of the time, only for exe you would require to add `InstallerSwitches`.
> If the InstallerType is one of those there is probably a problem somewhere else.

Please can you test those manifests on your machine?

**Comment by Meteor24** [comment]
Now I'm more confused

**Comment by Meteor24** [comment]
When I tested the manifest for a silent install the only thing I got was a UAC prompt and a progress bar in the terminal

**Comment by iDolmatov** [comment]
> When the `InstallerType` is `msi, msix, inno, nullsoft, appx, wix or burn` WinGet already know the silent switches so there is no need to add them 99% of the time, only for exe you would require to add `InstallerSwitches`.
> If the InstallerType is one of those there is probably a problem somewhere else.

My mistake. Didn't study the documentation and source code enough. Now I looked at the details and do not see the reason for the refusal. So I will not answer instead of a competent specialist.

**Comment by denelon** [comment]
@Meteor24 you can try the new [wingetcreate](https;//github.com/microsoft/winget-create) tool. It has the ability to detect most "known" supported installer types.

**Comment by iDolmatov** [comment]
> @Meteor24 you can try the new [wingetcreate](https;//github.com/microsoft/winget-create) tool. It has the ability to detect most "known" supported installer types.
URL typo. Correct: https://github.com/microsoft/winget-create
I have not been able to unequivocally determine the convenience versus the script.
https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1

When using these methods, I could not specify several bit versions of the distribution kit of one program.

**Comment by denelon** [comment]
@iDolmatov the new tool currently does support only some of the simpler use cases. Once the manifest has been merged, you can experiment by adding some of the additional capabilities.
