### ISSUE TITLE
[Package Issue]: MoonchildProductions.PaleMoon

### ISSUE THREAD

**Issue by fraxgut** [microsoft/winget-pkgs#151755]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Download request status is not success.
0x80190194 : unknown error

### Steps to reproduce

Try installing Pale Moon through WinGet.

### Actual behavior

Downloading is failing (probably 404 error).

### Expected behavior

Download functions correctly, and installation too.

### Environment

```raw
Windows: Windows.Desktop v10.0.19044.4291
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.22.11132.0
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/88363070/cfe75d56-c1e4-48a9-a06a-91d684d2612f)

**Comment by Trenly** [comment]
[Policy] In PR
