### ISSUE TITLE
[Update Request]: DeepL 24.4.3.12310

### ISSUE THREAD

**Issue by Naxterra** [microsoft/winget-pkgs#151956]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DeepL.DeepL

### Package Version

24.4.3.12310

### Please describe the changes you would like to see

There is a new package available for DeepL 24.4.3.12310. Download link https://appdownload.deepl.com/windows/0install/DeepLSetup.exe

At the moment winget is not recognizing currently installed version.
DeepL           DeepL.DeepL           Unknown     24.4.3.12310 winget

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/151441

**Comment by stephengillie** [comment]
> #151441
