### ISSUE TITLE
[New Feature]: Update PlayNite WinGet package to 10.33

### ISSUE THREAD

**Issue by IliasWhoElse** [microsoft/winget-pkgs#151960]
### Description of the new feature/enhancement

WinGet still shows 10.32 as latest install.

**Comment by Trenly** [comment]
Please provide additional details around which package you're specifically encountering issues with

**Comment by IliasWhoElse** [comment]
I'm not encountering issue's with a package. It just seems winget doesn't have the latest playnite version listed. See screenshot below.

![image](https://github.com/microsoft/winget-pkgs/assets/24387083/1af45a92-581f-4343-b675-949d39af0145)

**Comment by Trenly** [comment]
> I'm not encountering issue's with a package. It just seems winget doesn't have the latest playnite version listed. See screenshot below.
> 
> ![image](https://private-user-images.githubusercontent.com/24387083/327558637-1af45a92-581f-4343-b675-949d39af0145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Nzg5ODcsIm5iZiI6MTcxNDY3ODY4NywicGF0aCI6Ii8yNDM4NzA4My8zMjc1NTg2MzctMWFmNDVhOTItNTgxZi00MzQzLWI2NzUtOTQ5ZDM5YWYwMTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE5MzgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwY2VkNTVhNTBhMTBlMzUwYzlmODE0OTM3ZWZiNjJlYTE4MTk5NTQ1NTFmNDNhNWQ0NTNiMTdkOTFmNWUyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1B4NL9IoESOmt4LcJL3kyvn8I7nxhTKIyvQa2rqG348)

Ah, I see. I just didn’t see Playnite referenced at all in your post

**Comment by IliasWhoElse** [comment]
> > I'm not encountering issue's with a package. It just seems winget doesn't have the latest playnite version listed. See screenshot below.
> > ![image](https://private-user-images.githubusercontent.com/24387083/327558637-1af45a92-581f-4343-b675-949d39af0145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Nzg5ODcsIm5iZiI6MTcxNDY3ODY4NywicGF0aCI6Ii8yNDM4NzA4My8zMjc1NTg2MzctMWFmNDVhOTItNTgxZi00MzQzLWI2NzUtOTQ5ZDM5YWYwMTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE5MzgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwY2VkNTVhNTBhMTBlMzUwYzlmODE0OTM3ZWZiNjJlYTE4MTk5NTQ1NTFmNDNhNWQ0NTNiMTdkOTFmNWUyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1B4NL9IoESOmt4LcJL3kyvn8I7nxhTKIyvQa2rqG348)
> 
> Ah, I see. I just didn’t see Playnite referenced at all in your post

Apologies. That's completely my mistake.

**Comment by Trenly** [comment]
* https://github.com/microsoft/winget-pkgs/pull/151153
