### ISSUE TITLE
[Package Request]: Processing v4.3

### ISSUE THREAD

**Issue by 2gn** [microsoft/winget-pkgs#152037]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://processing.org/download
Publisher: Processing
Package Name: Processing
Description: A flexible software sketchbook and a language for learning how to code
Package Version: 4.3
Installer URL: https://github.com/processing/processing4/releases/download/processing-1293-4.3/processing-4.3-windows-x64.zip

**Comment by Dragon1573** [comment]
I'm currently trying on this issue ❤️

**Comment by 2gn** [comment]
Ok, thanks! I'll close this issue for now.
