### ISSUE TITLE
[Update Request]: Windows App SDK version 1.5.3

### ISSUE THREAD

**Issue by Zaibatsu89** [microsoft/winget-pkgs#152091]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.WindowsAppRuntime.1.5

### Package Version

1.5.3

### Please describe the changes you would like to see

There is a new release `v1.5.3` available, which is released at May 1, 2024. Current version in winget is `v1.5.2`.
| Properties | Link |
|--------|--------|
| Download page | [https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads) |
| Installer (x64) | [https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-x64.exe](https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-x64.exe) |
| Installer (x86) | [https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-x86.exe](https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-x86.exe) |
| Installer (arm64) | [https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-arm64.exe](https://aka.ms/windowsappsdk/1.5/1.5.240428000/windowsappruntimeinstall-arm64.exe) |
| Redistributable | [https://aka.ms/windowsappsdk/1.5/1.5.240428000/Microsoft.WindowsAppRuntime.Redist.1.5.zip](https://aka.ms/windowsappsdk/1.5/1.5.240428000/Microsoft.WindowsAppRuntime.Redist.1.5.zip) |
| Release notes | [https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-153-15240428000](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-153-15240428000) |

**Comment by BiosPlus** [comment]
Well formatted table, thanks for making it easy :)
