### ISSUE TITLE
[Package Issue]:  Mozilla.Thunderbird version 115.10.2 is not meant for upgrades (breaking change in the upgrade path to version 125.0)

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#152043]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

related pull request:  https://github.com/microsoft/winget-pkgs/pull/151869

version 115.10.2 is not meant to be used for upgrades over anything else in the previous 115 version series because it only introduces a breaking change in the upgrade path:
the automatic upgrade channel for Thunderbird is changed to ESR with this version. Thunderbird 125.0 is almost ready for release.

See  https://www.thunderbird.net/en-US/thunderbird/115.10.2/releasenotes/

and also https://ftp.mozilla.org/pub/thunderbird/releases/125.0/

### Steps to reproduce

- Install Thunderbird 115.10.1
- in the app go to Help -> About to check for self-updates
- read Release Notes for the version 115.10.2 (next version shown by `winget upgrade` )

### Actual behavior

winget changes upgrade channel of Thunderbird from RELEASE to ESR

### Expected behavior

winget should not change the channel.

### Environment

```raw
env not relevant
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/24ed10a9-ad50-46b2-97a4-e131967b3c20)

https://wiki.mozilla.org/Thunderbird/tb-planning
(screenshot from the Topicbox Thunderbird planning site:)

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/22e58c60-8996-45bf-b4b9-608f7ca1cd7c)

**Comment by stephengillie** [comment]
Should this be added as a separate `PackageIdentifier`, possibly `Mozilla.Thunderbird.115`? 
- This way, users could upgrade past it without knowing - and if a user really wanted to install it, they would still have an easy way. 
- One caveat is that both versions should be able to be installed side-by-side. If they can't be side-by-side then this suggestion probably won't work.

**Comment by R-Adrian** [comment]
> Should this be added as a separate `PackageIdentifier`, possibly `Mozilla.Thunderbird.115`?
> 

I think the identifier should be `Mozilla.Thunderbird.ESR`
the same way that Firefox ESR has the identifier `Mozilla.Firefox.ESR`
https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Mozilla/Firefox/ESR

This way when future versions go into extended maintenance we do not have to change the ESR tag.

**Comment by SpecterShell** [comment]
The installer on the homepage is 115.10.2 though.

**Comment by R-Adrian** [comment]
> It is weird that the official homepage still provides 115.10.2 even if it is in ESR, and there is no specific page for downloading ESR editions.

I expect that when version 125 is finally qualified for a full release they will start showing two update buttons in the "About" window of Thunderbird - one to stay on the 115 ESR release track and one to upgrade to version 125.

Not sure how this will work for people who have already switched to the ESR channel... probably those two buttons will still be shown for them too.

Anyway... the current problem is that we cannot differentiate between Thunderbird (normal release) and Thunderbird ESR just by looking at the registry...
...so i have filed a bug in Bugzilla for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1895080

Firefox ESR had practically the same problem in 2014 - https://bugzilla.mozilla.org/show_bug.cgi?id=726781
and they solved if by adding the "ESR" string to the product name in registry.

**Comment by R-Adrian** [comment]
update: apparently all these years Thunderbird was actually considered to be on the ESR track all along. just not explicitly named as such. i think that also closes this WinGet issue ticket as resolved (for now) too.

quote from Bugzilla:
> 115.10.1 SHOULD be upgraded to 115.10.2, so there's no bug there.
>
> What's going on here is that Thunderbird hasn't had a "standard release" in many years, we've had ESR rebranded as a "standard release". But we are adding a REAL standard release that updates monthly as it should, so all current users of "release" are really ESR users and are being intentionally relabeled as such.
>
>I believe we are planning to add ESR to the name with version 128.0, which is the first (new) version with actual overlap between the ESR version number and the new "standard release" channel.

/quote
