### ISSUE TITLE
[Package Request]: Mapillary Uploader

### ISSUE THREAD

**Issue by Timonade** [microsoft/winget-pkgs#152226]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.mapillary.com/desktop-uploader
Publisher: Meta
Package Name: Mapillary Uploader
Description: The Mapillary Desktop Uploader is a desktop application that enables uploading Mapillary imagery in bulk.
Package Version: 4.3.0
Installer URL: https://tools.mapillary.com/uploader/download/win

**Comment by BiosPlus** [comment]
Damn, that's a pretty cool project.

I'll do the desktop uploaded as `Mapillary.MapillaryUploader` and the [CLI](https://github.com/mapillary/mapillary_tools) version I found as `Mapillary.MapillaryTools` if that works.
