### ISSUE TITLE
Auto upload file for Validation-SmartScreen

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/winget-pkgs#1523]
# Description of the new feature/enhancement

When there is Validation-SmartScreen error, auto upload file via robot to https://www.microsoft.com/en-us/wdsi/filesubmission to scan the file, as the download URL already in the yaml config file, should not need human to do it

**Comment by superusercode** [comment]
Definitely a key part of #500

**Comment by KevinLaMS** [comment]
We agree.  We are investigating improving this process.  I am working with the smartscreen team and have quit assigning the packages back to the submitter.

**Comment by KevinLaMS** [comment]
Greetings, the process has changed, this should no longer be an issue.
