### ISSUE TITLE
[Package Request]: Plex.PlexMediaServer

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#152491]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.plex.tv/media-server-downloads/?cat=computer&plat=windows
Publisher: Plex
Package Name: Plex.PlexMediaServer
Description: Plex Media Server is a software application that allows users to organize, stream, and share their media files, including movies, TV shows, music, and photos, across various devices. It centralizes media collections and provides a user-friendly interface for accessing content from anywhere with an internet connection. Users can access Plex through dedicated apps on smart TVs, streaming devices, computers, and mobile devices, making it a versatile solution for managing and enjoying digital media libraries.
Package Version: 1.40.2.8395
Installer URL: https://downloads.plex.tv/plex-media-server-new/1.40.2.8395-c67dce28e/windows/PlexMediaServer-1.40.2.8395-c67dce28e-x86_64.exe

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/150094

**Comment by vikingnope** [comment]
This should have been an upgrade request as the package already exists. Kindly close as this has already been completed.
