### ISSUE TITLE
[Update Request]: Amazon Games fails due to mismatch hash

### ISSUE THREAD

**Issue by dlaventu** [microsoft/winget-pkgs#152476]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Amazon.Games

### Package Version

2.3.8982.5

### Please describe the changes you would like to see

https://download.amazongames.com/AmazonGamesSetup.exe
File SHA256: c8fd66a011cb214cae4e8394ae49ec264cb094879dc4bb02b5d49713f7a68d43

Winget SHA256: 51cfee1c225d11c92bf4997e1a76be3655fd88fec0f45654df114437a0eedf4b

**Comment by dlaventu** [comment]
New Release Available 2.0.9143.0

**Comment by Dragon1573** [comment]
The provided `InstallerUrl` with `InstallerSha256: c8fd66a011cb214cae4e8394ae49ec264cb094879dc4bb02b5d49713f7a68d43` points to `PackageVersion: 3.0.9124.0`.

`winget.exe` will regard `2.3.8982.5` newer than `2.0.9143.0`, which is obviously incorrect.
