### ISSUE TITLE
[Package Issue]: VidCoder.Beta

### ISSUE THREAD

**Issue by 3xploiton3** [microsoft/winget-pkgs#152508]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

how to install vidcoder via winget?

### Steps to reproduce

`winget install VidCoder.Beta`

### Actual behavior

cannot install
`winget install VidCoder.Beta`

### Expected behavior

No package found matching input criteria.

### Environment

```raw
Windows Package Manager v1.7.11132
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3527
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11132.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/19517680/299e55fc-a12c-4405-9150-9e47e63ab821)

**Comment by vikingnope** [comment]
What is the install error?

**Comment by R-Adrian** [comment]
the `list` command for winget is used to list already-installed software - even if it was not installed by winget.

On packages that are recognized as being manageable with winget you will have "winget" mentioned in the Source column of the `list` command output.

example:
![image](https://github.com/microsoft/winget-pkgs/assets/16319504/030894d7-0ce5-4ac2-902c-62274bf48560)


If that software appeared after using winget to install something else maybe it is a component needed by that something else software and that one installed it during its own installation?


Also, there is no such company and/or source named `VidCoder` or `VidCoder.Beta` defined in the winget manifests
https://github.com/microsoft/winget-pkgs/tree/master/manifests/v

There is a package named `RandomEngy.VidCoder.Beta` but that one is nowhere near the version number 10 so i do not know if that is related to version 10+ that you have installed.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RandomEngy/VidCoder/Beta

![image](https://github.com/microsoft/winget-pkgs/assets/16319504/1157b3c7-1104-4501-b68d-62e68795d3ce)
