### ISSUE TITLE
 `Moniker` erroneously included in `locale` Manifest Schema Documentation

### ISSUE THREAD

**Issue by aisgbnok** [microsoft/winget-pkgs#152635]
The `Moniker` field is included in the [locale manifest documentation](https://github.com/microsoft/winget-pkgs/blob/b2b55cd0c3db7ea176ce911814cdc403dccf449e/doc/manifest/schema/1.6.0/locale.md), while it is not present in the locale manifest [JSON schema](https://github.com/microsoft/winget-cli/blob/4073c4304e6a87db3cbf0826bb694d9296072cd3/schemas/JSON/manifests/v1.6.0/manifest.locale.1.6.0.json) or [REST documentation](https://github.com/microsoft/winget-cli-restsource/blob/main/documentation/WinGet-1.6.0.yaml).

https://github.com/microsoft/winget-pkgs/blob/b2b55cd0c3db7ea176ce911814cdc403dccf449e/doc/manifest/schema/1.6.0/locale.md?plain=1#L34

---
Related:

- https://github.com/microsoft/winget-cli/issues/1595

**Comment by Trenly** [comment]
[Policy] In PR
