### ISSUE TITLE
[Package Issue]: Bluebeam.Revu.21

### ISSUE THREAD

**Issue by stop-error** [microsoft/winget-pkgs#152700]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

All versions of package Bluebeam.Revu.21 after version 21.0.40 fail to install with the following error:

**An unexpected error occurred while executing the command:
[YAML:Policy] unsupported control character [line 3; col 12]
0x8a150004 : Opening manifest failed**

Versions 21.0.40 and 21.0.20 install successfully. 

### Steps to reproduce

Run the following:

**winget install --id Bluebeam.Revu.21**

### Actual behavior

Installation fails with the following error:

**An unexpected error occurred while executing the command:
[YAML:Policy] unsupported control character [line 3; col 12]
0x8a150004 : Opening manifest failed**

### Expected behavior

Package should install successfully. 

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
----------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutpu…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/129561633/57c6b1c7-563c-448d-9812-b21bc4983a53)

**Comment by markvanreerobertsco** [comment]
Please fix asap. We're currently updating our users from v20 to v21 via winget.
