### ISSUE TITLE
[Package Issue]: Tenable.NessusAgent

### ISSUE THREAD

**Issue by markpconroyscp** [microsoft/winget-pkgs#152831]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Pull request https://github.com/microsoft/winget-pkgs/pull/151990 appears to have removed all references to the x64 package. The 32-bit package will not install on a 64-bit operating system.

### Steps to reproduce

- Install the Tenable.NessusAgent package via winget (winget install Tenable.NessusAgent)
- The package fails to install

### Actual behavior

The package fails to install on x64 devices

### Expected behavior

Winget should select the correct package version for the architecture but the manifest no longer contains the x64 package

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4291
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by vikingnope** [comment]
@markpconroyscp Can you show me a screenshot of the error please?

**Comment by markpconroyscp** [comment]
@vikingnope PSB
![image](https://github.com/microsoft/winget-pkgs/assets/69902295/9a6478d9-9aa4-4a3f-b7c5-79a20ee759b1)

**Comment by vikingnope** [comment]
I think I have found a fix, please give me a few minutes to create a PR

**Comment by vikingnope** [comment]
@markpconroyscp Can you try again now and let me know please?

**Comment by markpconroyscp** [comment]
@vikingnope All working! Thank you for your prompt assistance :)
