### ISSUE TITLE
[Update Request]: Oracle.MySQLShell 8.4.0

### ISSUE THREAD

**Issue by fabiang** [microsoft/winget-pkgs#152996]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Oracle.MySQLShell

### Package Version

8.4.0

### Please describe the changes you would like to see

8.4.0 is available from here https://dev.mysql.com/downloads/shell/. PR following.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This pull request should be closed as "completed", as it's already solved by #152997.

**Comment by fabiang** [comment]
Thanks for the merge.

**Comment by fabiang** [comment]
closed
