### ISSUE TITLE
[Update Request]: remove ProtonTechnologies.ProtonVPN in favor of Proton.ProtonVPN

### ISSUE THREAD

**Issue by Silther** [microsoft/winget-pkgs#153000]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

ProtonTechnologies.ProtonVPN

### Package Version

3.2.11

### Please describe the changes you would like to see

Please remove the ProtonTechnologies.ProtonVPN package as it is an duplicate of Proton.ProtonVPN and uses a different (older) naming scheme as the rest of the proton packages (all else are also using Proton.APPLICATION).

**Comment by vikingnope** [comment]
will get to removing it

**Comment by BiosPlus** [comment]
Heads up @vikingnope, you forgot to throw `Resolves: ` in front of the issue reference in your PR.

**Comment by vikingnope** [comment]
@BiosPlus, thanks, thought I had done it lol

**Comment by vikingnope** [comment]
@Silther, is this okay now?
