### ISSUE TITLE
[Package Issue]: VMware.WorkstationPro

### ISSUE THREAD

**Issue by p-fruck** [microsoft/winget-pkgs#153068]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installation of the package with version 17.5.0 results in error. Not sure if this is a duplicate of #152915, but the error message seems different

### Steps to reproduce

Run `winget install VMware.WorkstationPro --version 17.5.0`

### Actual behavior

```
Download request status is not success.
0x8019020a : unknown error
```

### Expected behavior

Should install

### Environment

```raw
Windows-Paket-Manager v1.7.11261
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.4291
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.22.11261.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by Utesgui** [comment]
The installer (https://download3.vmware.com/software/WKST-1750-WIN/VMware-workstation-full-17.5.0-22583795.exe) is currently just not available
![image](https://github.com/microsoft/winget-pkgs/assets/76051010/225c9498-7898-4fdf-9f25-851d1cdcb975)

**Comment by p-fruck** [comment]
my bad :smile: Closing for now as I expect winget to work once the installer becomes available, thanks for pointing that out ^^

**Comment by pricemc1** [comment]
This may not self-resolve because VMware URLs no longer exist for the most part. Someone will have to identify if there is similar URL available from Broadcom at this point since all VMware content has been transitioned over to the Broadcom site. Good luck with that...

**Comment by Utesgui** [comment]
@pricemc1 you are right.

According to my research, the downloadlinks are only available after logging in to the broadcom portal.
https://community.broadcom.com/communities/community-home/digestviewer/viewthread?GroupId=2023&MessageKey=8656f477-8100-425d-b948-018f4f379941
https://community.broadcom.com/communities/community-home/digestviewer/viewthread?GroupId=2023&MessageKey=39ce514e-acd8-4864-b7c8-018f8319ede4

I have found the following Direcotry containing all Verions, but only as .exe.tar which is currently not supported by winget:
https://softwareupdate.vmware.com/cds/vmw-desktop/ws/

I'll try to find other (public available) links.
If anyone alese finds something feel free to let me know.
