### ISSUE TITLE
[Update Request]: Oracle VM VirtualBox

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#153152]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Oracle.VirtualBox

### Package Version

7.0.18

### Please describe the changes you would like to see

There is a new release (7.0.18) available

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/152163

**Comment by stephengillie** [comment]
> #152163
