### ISSUE TITLE
[Update Request]: Dell Command Update Universal > 5.3.34.0 (April 2024)

### ISSUE THREAD

**Issue by FluXs** [microsoft/winget-pkgs#153253]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DellInc.DellCommandUpdate_htrsf667h5kn2

### Package Version

5.3.34.0

### Please describe the changes you would like to see

Release: 5.3.34.0
Download URL: https://dl.dell.com/FOLDER11563484M/1/Dell-Command-Update-Windows-Universal-Application_P83K5_WIN_5.3.0_A00.EXE

Note on the package id: When this is installed manually I do not see the current **Dell.CommandUpdate.Universal** mentioned in the previous releases yaml file, perhaps this has changed over time.

**Comment by a-mnich** [comment]
I can't seem to find version 5.3.34.0.  In the [changelog](https://www.dell.com/support/kbdoc/en-us/000177325/dell-command-update) your download link is referred to as 5.3.0 which is currently in PR with [#15321](https://github.com/microsoft/winget-pkgs/pull/153212)

**Comment by FluXs** [comment]
Ah yes this looks like a dupe
