### ISSUE TITLE
[Update Request]: ShareX

### ISSUE THREAD

**Issue by 3xploiton3** [microsoft/winget-pkgs#153315]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ShareX.ShareX

### Package Version

ShareX 16.1.0

### Please describe the changes you would like to see

https://github.com/ShareX/ShareX/releases

![image](https://github.com/microsoft/winget-pkgs/assets/19517680/dd60b4a6-a51d-47b7-afa9-66d8c1897208)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This will be resolved by #153267.
