### ISSUE TITLE
Add youtube-dl Package

### ISSUE THREAD

**Issue by xmha97** [microsoft/winget-pkgs#1534]
Hello,
I can't find the youtube-dl package on winget
Please add it.
https://github.com/ytdl-org/youtube-dl

**Comment by xmha97** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25517

**Comment by SoftCreatR** [comment]
Youtube-DL doesn't have an installer, therefore it's currently incompatible with winget.

**Comment by Restia666Ashdoll** [comment]
They have to first solve this(its in their milestone)
https://github.com/microsoft/winget-cli/issues/361
Till then use [Scoop](https://github.com/ScoopInstaller/Main/blob/master/bucket/youtube-dl.json), [Scoop-Python](https://github.com/TheRandomLabs/Scoop-Python/blob/master/bucket/youtube-dl-py.json) or [pip](https://pypi.org/project/youtube_dl/)
https://www.reddit.com/r/youtubedl/comments/dzj0mr/youtubedl_the_complete_installation_guide_for/

**Comment by xmha97** [comment]
> They have to first solve this(its in their milestone) first
> [microsoft/winget-cli#361](https://github.com/microsoft/winget-cli/issues/361)
> Till then use [Scoop](https://github.com/ScoopInstaller/Main/blob/master/bucket/youtube-dl.json), [Scoop-Python](https://github.com/TheRandomLabs/Scoop-Python/blob/master/bucket/youtube-dl-py.json) or [pip](https://pypi.org/project/youtube_dl/)
> https://www.reddit.com/r/youtubedl/comments/dzj0mr/youtubedl_the_complete_installation_guide_for/

OK, Thanks.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by Trenly** [comment]
@denelon - https://github.com/microsoft/winget-pkgs/pull/68800
