### ISSUE TITLE
[Package Issue]: mitmproxy.mitmproxy

### ISSUE THREAD

**Issue by av-gal** [microsoft/winget-pkgs#153582]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

`winget install mitmproxy.mitmproxy` downloads the mitmproxy installer without running it.

### Steps to reproduce

Run `winget install mitmproxy.mitmproxy`.

### Actual behavior

The mitmproxy installer is downloaded and "mitmproxy-10.3.0-windows-x86_64-installer" is added as a command-line alias for it.

### Expected behavior

The mitmproxy installer is downloaded and run, and "mitmproxy" is added as a command-line alias for the installed executable.

### Environment

```raw
winget --info 
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3296
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
--------------------------------------------------------------------------------------------------------------------------- 
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutp… 
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings… 
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/32237198/24fe84e9-bcda-4d5e-95dd-5cc00efa37fd)
![image](https://github.com/microsoft/winget-pkgs/assets/32237198/f14abd90-4f04-4f7a-9134-6e1796fc8ea2)

**Comment by vikingnope** [comment]
I have a fix coming for this in the next few minutes
