### ISSUE TITLE
[Package Request]: LAME

### ISSUE THREAD

**Issue by fgimian** [microsoft/winget-pkgs#153522]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.rarewares.org/mp3-lame-bundle.php
Publisher: RareWares
Package Name: LAME
Description: High quality MPEG Audio Layer III (MP3) encoder.
Package Version: 3.100.1
Installer URL:
- https://www.rarewares.org/files/mp3/lame3.100.1-x64.zip
- https://www.rarewares.org/files/mp3/lame3.100.1-win32.zip

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/153518

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This issue should be closed as "completed", as pull request #153518 has successfully merged.

**Comment by fgimian** [comment]
> > [!NOTE]
> 
> >
> 
> > This issue should be closed as "completed", as pull request #153518 has successfully merged.

Agreed, thanks for the merge 😊
