### ISSUE TITLE
7zip Validation Unattended

### ISSUE THREAD

**Issue by Aditya-0704** [microsoft/winget-pkgs#15355]
7zip Validation Unattended

**Comment by OfficialEsco** [comment]
Most of the time it means do your research before submiting.

**Comment by Aditya-0704** [comment]
I did the research

**Comment by GeorgeCY2** [comment]
> I did the research

you sure? even if you have ticked everything, you must ensure you have validated and tested the manifest before submitting. also maybe sing the CLA if you havent

**Comment by lychichem** [comment]
> 7zip Validation Unattended

Please, clearly explain the issue you ran into, using what we ordinary people can understand to describe what happened. If English is not your mother language, you can just use your mother language. And the community has a good issue template, try to use it. As far as I know, the installer of 7-zip has no issue, and if you mean installers distribuated via .7z, currently it's not supported due to some blocking issue.

**Comment by Aditya-0704** [comment]
The problem is that when test the manifest  it shows the UAC Prompt which is fine but after that it shows a 7zip installer window which asks for the installation directory. 

Please Help

**Comment by KaranKad** [comment]
Thing about 7zip is that its already available at https://github.com/microsoft/winget-pkgs/tree/master/manifests/7/7zip/7zip. So you don't need to worry about adding it.

**Comment by OfficialEsco** [comment]
> The problem is that when install the manifest it shows the UAC Prompt which is fine but after that it shows a 7zip installer window which asks for the installation directory.
> 
> Please Help

Steps to reproduce? Just tested the EXE in the existing manifest and it installed silently...

**Comment by Aditya-0704** [comment]
Actually I find out that 7sip is already in winget. Thank you all who helped me

**Comment by OfficialEsco** [comment]
> I did the research

So.. you didn't do your research?

**Comment by Aditya-0704** [comment]
@KaranKad said
Thing about 7zip is that its already available at https://github.com/microsoft/winget-pkgs/tree/master/manifests/7/7zip/7zip. So you don't need to worry about adding it.
