### ISSUE TITLE
Add more information regarding validation pipeline failures.

### ISSUE THREAD

**Issue by jksolbakken** [microsoft/winget-pkgs#15382]
Hi! How can I find out why https://github.com/microsoft/winget-pkgs/pull/15362/checks?check_run_id=2716408213 failed? The detail view just says `0 warnings/0 errors`, and no additional info in the Azure DevOps log.

**Comment by GeorgeCY2** [comment]
have you tested the installer yourself or sandboxed (using the tools?), usually there are factors that will fail such as needing user input.

**Comment by jedieaston** [comment]
@denelon Is there anyway the installer verification run can attach the WinGet logs when it completes the test, so it is easier to debug what happened?

**Comment by x10an14** [comment]
> @GeorgeCY2: have you tested the installer yourself or sandboxed (using the tools)? Usually there are factors that will fail such as needing user input.
Well, yes. We know that if you ain't admin on the windows machine it's run on, it'll pop-up UAC and warnings/errors/retry-dialogs ref. "You no haz access".

Primarily for the low-level vpn networking stuff and background service(s) being installed.

**Comment by GeorgeCY2** [comment]
> Well, yes. We know that if you ain't admin on the windows machine it's run on, it'll pop-up UAC and warnings/errors/retry-dialogs ref. "You no haz access".
> 
> Primarily for the low-level vpn networking stuff and background service(s) being installed.

yes UAC is excluded, some installers will ask Administrator Priviliges in order to install and that's excluded. I'm talking about issues like rainmeter where it doesnt support "silent install" and needs user input.

**Comment by x10an14** [comment]
> @GeorgeCY2: I'm talking about issues like rainmeter where it doesnt support "silent install" and needs user input.

@jksolbakken or I will confirm tomorrow during CE(S)T working hours once we get that Win10 VM up and running again. But no, it should not (we offer no configuration options ourselves in the MSI).

But let us double-check what happens if we start the terminal (from which we call `winget`) as Admin tomorrow.

**Comment by denelon** [comment]
@jedieaston we're discussing a couple of options to expose more of the data from the validation.

**Comment by vedantmgoyal2009** [comment]
Since we have logs now, from the pipelines, this may be already resolved?

**Comment by denelon** [comment]
Thanks @vedantmgoyal2009 😊
