### ISSUE TITLE
[Package Issue]: Python.Python override causes installer to ignore scope

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#153928]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Using overrides makes it impossible to install Python system-wide.

### Steps to reproduce

```
winget install --id Python.Python.3.11 --scope machine --override '/quiet'
```

### Actual behavior

Python is installed in *%LOCALAPPDATA%\Programs*.

### Expected behavior

Python is installed in *%PROGRAMFILES%* .

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4412
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by SpecterShell** [comment]
The scope is controlled by the `InstallAllUsers` switch from the installer, which would be overrode by your own installer switches by using the `--override` switch from WinGet.
https://github.com/SpecterShell/winget-pkgs/blob/713c2747ac9bde2ef1bb0dec0f30aad06be6ac30/manifests/p/Python/Python/3/11/3.11.9/Python.Python.3.11.installer.yaml#L42

It is recommended to use the `--silent` switch from WinGet for silent (without progress) installation.

**Comment by github-account1111** [comment]
`\quiet` was just for a minimum reproducible example. The full command is as follows:

```
/quiet AssociateFiles=0 CompileAll=0 PrependPath=1 Shortcuts=1 Include_doc=0 Include_debug=0 Include_dev=0 Include_exe=0 Include_launcher=0 Include_lib=1 Include_pip=1 Include_symbols=0 Include_tcltk=0 Include_test=0 Include_tools=0'
```

`--silent` alone simply isn't enough. What is the reason it is recommended?

**Comment by github-account1111** [comment]
No I should be sorry, I wasn't clear in explaining my intent in the initial example.

Thanks very much for the explanation, this makes much more sense now. Is there a technical reason winget discards `Custom` switches when `--overrides` is used? Can't they be appended? At the very least, a warning before proceeding with the install that the `--scope machine` of my install command will be ignored would be helpful.

**Comment by SpecterShell** [comment]
> No I should be sorry, I wasn't clear in explaining my intent in the initial example.
> 
> Thanks very much for the explanation, this makes much more sense now. Is there a technical reason winget discards `Custom` switches when `--overrides` is used? Can't they be appended? At the very least, a dialog before proceeding with the install informing the user that the `--scope machine` part of the install command will be discarded would be helpful.

It not only discards the `Custom` switch, but also all other switches, including the `InstallLocation` switch above, the pre-defined `Silent` switch (`/quiet /norestart` in this case), the pre-defined `SilentWithProgress` switch (`/passive /norestart`) and the pre-defined `Log` switch (`/log "<LOGPATH>"`). All of them will be overrode by `--override`.

The `--custom` WinGet switch will only override the custom switch. Since this switch has already been used for forcing the scope for the installer and will be overrode by `--custom`, you need to manually include `InstallAllUsers=1` in your switches.

So the final command line would be like
```
winget install --id Python.Python.3.11 --scope machine --silent --custom 'InstallAllUsers=1 AssociateFiles=0 CompileAll=0 PrependPath=1 Shortcuts=1 Include_doc=0 Include_debug=0 Include_dev=0 Include_exe=0 Include_launcher=0 Include_lib=1 Include_pip=1 Include_symbols=0 Include_tcltk=0 Include_test=0 Include_tools=0' 
```

**Comment by Trenly** [comment]
> The --custom WinGet switch will only override the custom switch.

Actually, it doesn't! `--custom` will only append the value

```
2024-05-17 10:07:01.168 [CLI ] WinGet invoked with arguments: 'install' '-m' 'C:\Users\WDAGUtilityAccount\Desktop\SandboxTest\3.12.3' '--verbose-logs' '--ignore-local-archive-malware-scan' '--dependency-source' 'winget' '--custom' '/quiet'
|
| Truncated for readability
|
2024-05-17 10:07:04.732 [CLI ] Starting: 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Python.Python.3.12.3.12.3\python-3.12.3-amd64.exe' with arguments '/passive /norestart /log "C:\Users\WDAGUtilityAccount\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Python.Python.3.12.3.12.3-2024-05-17-10-07-04.731.log" InstallAllUsers=0 PrependPath=1 /quiet'

**Comment by Trenly** [comment]
@github-account1111 - try using `--custom` instead of `--override` to add parameters to the install without erasing any of the ones defined in the manifest

**Comment by olegpro81** [comment]
Hi guys,

Sorry, maybe this is not related directly, but hope someone can advise. I'm trying to add a number of Python versions under winget remediation. All tests are under system user. Started to test the install first. When I run: **.\winget.exe install -e --id Python.Python.3.11 --scope machine** it does install ok and regular user can open it. But when I try to check it with **.\winget.exe list -e --id Python.Python.3.11 --scope machine** it's not found. List works when I remove -**-scope machine**. When I try to uninstall it without --scope it does fail with An unexpected error 0x800401f5: App not found. Can someone please advise what I'm doing wrong? How can I upgrade those 10-12 versions we have in our environment?
