### ISSUE TITLE
[Package Issue]: Nvidia.CUDA

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-pkgs#154059]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

I've installed Nvidia.CUDA 12.4.1. However, the registry entry for that is just "12.4":

![image](https://github.com/microsoft/winget-pkgs/assets/81419612/852647f1-77cd-4aad-80f0-9602eb6d45eb)

That shouldn't be an issue since the `DisplayVersion` in the manifest is set to 12.4 too, but `winget upgrade` still shows an update available combined with a weird version number:

```terminal
winget upgrade
Name                                            ID                                Version        Available      Source
----------------------------------------------------------------------------------------------------------------------
NVIDIA CUDA Toolkit 12.4                        Nvidia.CUDA                       > 12.3.2       12.4.1         winget
```

### Steps to reproduce

Install the newest version of Nvidia.CUDA.

### Actual behavior

Shows a weird version number and an available update.

### Expected behavior

Show the right version number in the output (12.4) and don't show an available update as the reported version number corresponds to the `DisplayVersion` of the latest manifest.

### Environment

```raw
Windows: Windows.Desktop v10.0.26212.5000
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.23.1133.0
```

**Comment by Trenly** [comment]
Can you share the output of `winget list cuda` ?

**Comment by Trenly** [comment]
@stephengillie - Seems like you approved the below PR specifying the installer type as `portable` when it should be `exe`. Perhaps your PR checker needs a check for if installer type changes? It's pretty rare for publishers to change installer types

* https://github.com/microsoft/winget-pkgs/pull/148528
