### ISSUE TITLE
[Update Request]: JesseDuffield.lazygit version 0.42.0

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#154313]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JesseDuffield.lazygit

### Package Version

0.42.0

### Please describe the changes you would like to see

There's a new release `v0.42.0` available.

- Download page url: `https://github.com/jesseduffield/lazygit/releases/tag/v0.42.0`
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/154239
```

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/154239
