### ISSUE TITLE
Package Not Found

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#154857]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I have tried to install the following packages : 
Mega.MEGASync
CodecGuide.K-LiteCodecPack
IrfanSkiljan.IrfanView 
Viber.Viber
Cisco.WebexTeams
Google.Drive

### Steps to reproduce

winget install Mega.MEGASync CodecGuide.K-LiteCodecPack IrfanSkiljan.IrfanView  Viber.Viber Cisco.WebexTeams Google.Drive

### Actual behavior

Package not found: Mega.MEGASync
Package not found: CodecGuide.K-LiteCodecPack
Package not found: IrfanSkiljan.IrfanView 
Package not found: Viber.Viber
Package not found: Cisco.WebexTeams
Package not found: Google.Drive

### Expected behavior

To be able to install the following packages 

Mega.MEGASync
CodecGuide.K-LiteCodecPack
IrfanSkiljan.IrfanView 
Viber.Viber
Cisco.WebexTeams
Google.Drive

### Environment

```raw
PS C:\Users> winget --info
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3593
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
PS C:\Users>
```

**Comment by vikingnope** [comment]
Known issue, will get to fixing these, kindly allow a few minutes for me to create my PRs

**Comment by vikingnope** [comment]
For the `CodecGuide.K-LiteCodecPack`, this is actually split into 4, there is standard, basic, full, mega
i.e.:
`CodecGuide.K-LiteCodecPack.Standard`
`CodecGuide.K-LiteCodecPack.Full`
`CodecGuide.K-LiteCodecPack.Basic`
`CodecGuide.K-LiteCodecPack.Mega`

**Comment by vikingnope** [comment]
`IrfanSkiljan.IrfanView`, this works fine for me so test it again
