### ISSUE TITLE
Sublime Text 3 fails upgrade with "Installer failed with exit code: 1"

### ISSUE THREAD

**Issue by pjaj** [microsoft/winget-pkgs#15495]
I tried to update Sublime Text and got the following
```
C:\Users\peter>winget upgrade "Sublime Text 3"
Found Sublime Text 3 [SublimeHQ.SublimeText.3]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download.sublimetext.com/Sublime%20Text%20Build%203211%20x64%20Setup.exe
  ██████████████████████████████  10.4 MB / 10.4 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```
Bug or user error?

Using the update popup inside Sublime Text updated the program without any problem.

**Comment by denelon** [comment]
@pjaj I suspect this has to do with the Sublime installer. It is possible that exit code: 1 is actually a success condition. Someone with familiarity of Sublime might be able to verify. If it is a success code, the manifest can be updated accordingly.

**Comment by pjaj** [comment]
I don't think it was successful as later I was offered a newer version, when I manually updated it,  and now I'm told no newer versions are available.
Unless the winget repository has a down level version intermediate between my original one and the latest.

**Comment by denelon** [comment]
I see "Sublime Text 3" and "Sublime Text 4" are two separate packages in the repository. Is this issue still a problem?
