### ISSUE TITLE
[Package Issue]:  Google.PlayGames.Beta

### ISSUE THREAD

**Issue by Edoardo66** [microsoft/winget-pkgs#155036]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

If I execute the command "winget ls --upgrade-available" I obtain the following lines:

Nome                    Id                    Versione         Disponibile      Origine
---------------------------------------------------------------------------------------
Google Play Giochi beta Google.PlayGames.Beta 24.4.932.3       127.0.6490.0     winget

When I launch upgrade command, the updating seems to end succefully but the package's version remains unchanged.

### Steps to reproduce

winget upgrade Google.PlayGames.Beta

### Actual behavior

After updating, the package remains unchanged.

### Expected behavior

Package's version should be updated.

### Environment

```raw
Gestione pacchetti Windows v1.7.11261
Copyright (c) Microsoft Corporation. Tutti i diritti sono riservati.

Windows: Windows.Desktop v10.0.22631.3593
Architettura di sistema: X64
Pacchetto: Microsoft.DesktopAppInstaller v1.22.11261.0

Directory WinGet
-----------------------------------------------------------------------------------------------------------------------
Log                                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Impostazioni utente                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Directory collegamenti portabili (utente)   %LOCALAPPDATA%\Microsoft\WinGet\Links
Directory collegamenti portabili (computer) C:\Program Files\WinGet\Links
Radice pacchetto portabile (utente)         %LOCALAPPDATA%\Microsoft\WinGet\Packages
Radice pacchetto portabile                  C:\Program Files\WinGet\Packages
Radice pacchetto portabile (x86)            C:\Program Files (x86)\WinGet\Packages
Download del programma di installazione     %USERPROFILE%\Downloads

Collegamenti
------------------------------------------------------------------------------------
Informativa sulla privacy    https://aka.ms/winget-privacy
Contratto di licenza         https://aka.ms/winget-license
Comunicazioni di terze parti https://aka.ms/winget-3rdPartyNotice
Home page                    https://aka.ms/winget
Condizioni di Windows Store  https://www.microsoft.com/en-us/storedocs/terms-of-sale

Impostazione amministrazione              Stato
------------------------------------------------------
LocalManifestFiles                        Disabilitate
BypassCertificatePinningForMicrosoftStore Disabilitate
InstallerHashOverride                     Disabilitate
LocalArchiveMalwareScanOverride           Disabilitate
```

**Comment by stephengillie** [comment]
We were working last week to fix this. Wingetbot is picking up the wrong version. I've added the `PackageIdentifier` to my Review file, but for some reason it's not reminding me before approving. 

- https://github.com/microsoft/winget-pkgs/pull/154622
