### ISSUE TITLE
[Package Request]: FLAC (RareWares Builds)

### ISSUE THREAD

**Issue by fgimian** [microsoft/winget-pkgs#155263]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.rarewares.org/lossless.php
Publisher: RareWares
Package Name: FLAC
Description: Free Lossless Audio Codec (FLAC) command-line encoder and decoder.
Package Version: 1.4.3
Installer URL:
- https://www.rarewares.org/files/lossless/flac-1.4.3-x64-20240525.zip
- https://www.rarewares.org/files/lossless/flac-1.4.3-x86-nonXP-20240525.zip

I have already raised a PR for this package at https://github.com/microsoft/winget-pkgs/pull/155261

This issue is related to https://github.com/microsoft/winget-pkgs/issues/151382 although this issue tracks the statically linked builds provided by RareWares which can work with winget today. Meanwhile, the official builds require a DLL at runtime and are blocked by https://github.com/microsoft/winget-cli/issues/2711.

I think it's best to keep the original issue open so we can build a package of the official Xhip binaries when the required feature is implemented.

These RareWare builds have recently been improved after some discussions I had with John Edwards who runs the site. The prior builds on the site were compiled with the Intel 19 compiler and the non-AVX2 build was quite a lot slower than the official build. The new builds (used in this package manifest) are compiled with GCC and have identical if not better performance than the official Xhip builds.

I have specifically selected the following builds:
- **x86**: The non-XP build is compiled with GCC and is faster than the build that provides Windows XP compatibility. Since winget is only supported on Windows 10 onward, I didn't think Windows XP compatibility was a concern. 😄 
- **x64**: I chose the regular build which doesn't require an AVX2-compatible CPU. The reason is that in benchmarks performed by both John and I, the performance of both builds is comparable and thus I chose the more compatible build. The official Xhip builds also do not have a hard requirement on an AVX2-compatible processor either so this made the most sense.

**Comment by Dragon1573** [comment]
> I have already raised a PR for this package at #155261

Hello, @fgimian. Could you please add "close keywords" to the first comment of pull request #155261 ? This can link that PR to issue (such as this) and automatically close the issue while PR is successfully merged.

```markdown
Resolve #155263
```

**Comment by fgimian** [comment]
> > I have already raised a PR for this package at #155261
> 
> Hello, @fgimian. Could you please add "close keywords" to the first comment of pull request #155261 ? This can link that PR to issue (such as this) and automatically close the issue while PR is successfully merged.
> 
> ```
> Resolve #155263
> ```

Absolutely, all done. Sorry about that 😄 

Please let me know if it all looks OK now
Fotis
