### ISSUE TITLE
[Update Request] Change identifier: MystiPanda.ClashVerge

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#155227]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

MystiPanda.ClashVerge

### Package Version

1.6.2

### Please describe the changes you would like to see

> [!NOTE]
>
> This is related to #153116

According to the `InstallerUrl` of the package, should we change the package identifier to `clash-verge-rev.clash-verge-rev`? It seems the manifest does not meet the value in Owner's repository.

- Package homepage: https://github.com/clash-verge-rev/clash-verge-rev

**Comment by stephengillie** [comment]
Thsi appears to have been completed.
