### ISSUE TITLE
[Package Issue]: JRSoftware.InnoSetup

### ISSUE THREAD

**Issue by fgimian** [microsoft/winget-pkgs#155264]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The Inno Setup application contains a CLI tool called `ISCC.exe` which is not made available via a link or in `$PATH` after installation.

### Steps to reproduce

1. `winget install JRSoftware.InnoSetup`
2. Open a new PowerShell window
3. Type `ISCC`

### Actual behavior

```
iscc: The term 'iscc' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

The command should be avaliable in `$PATH` to run from any terminal. I can confirm the executable is correctly installed at the following paths (depending on scope)

**user**: `%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe`
**machine**: `C:\Program Files (x86)\Inno Setup 6\ISCC.exe`

I can also confirm that using a symlink does work correctly (i.e. there appear to be no DLL dependencies for the executable to run).

### Environment

```raw
Windows Package Manager v1.7.11261
Windows: Windows.Desktop v10.0.22631.3593
Package: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by Trenly** [comment]
WinGet doesn’t have the ability to add programs to PATH unless they have the installer type portable - which are loose binaries that don’t have an installer. In all other cases, it is up to the application's installer to update PATH.

###### [Policy] Installer Issue

**Comment by fgimian** [comment]
> WinGet doesn’t have the ability to add programs to PATH unless they have the installer type portable - which are loose binaries that don’t have an installer. In all other cases, it is up to the application's installer to update PATH.
> 
> ###### [Policy] Installer Issue

Ah, I had a feeling that may be the case. Thanks for the clarification. I'm happy to raise this directly with the vendor if that's the case and close this issue if you like.

Cheers
Fotis
