### ISSUE TITLE
[Package Request]: UrbanVPN

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#155325]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

_Download Page Url: https://www.urban-vpn.com/free-products/free-windows-vpn/
Publisher: UrbanVPN team
Package Name: UrbanVPN
Description: Free VPN For Windows
Package Version: 2.3.0.2

![2302](https://github.com/microsoft/winget-pkgs/assets/22171451/17e9015a-8cbe-493b-9c20-b63aacb92e8a)

Installer URL:_ https://install.urban-vpn.com/UrbanVPN.exe

**Comment by vikingnope** [comment]
Unable to complete due to a Network blocker. Kindly close this issue as not planned
