### ISSUE TITLE
[Package Request]: Add BORICA B-TRUST egov sign application

### ISSUE THREAD

**Issue by smsimeonov** [microsoft/winget-pkgs#155379]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.b-trust.bg/services/software
Publisher: BORICA AD
Package Name: BISS
Description: Borica software application to assist with signing and managing egov/trusted platforms access.
Package Version: 3.34
Installer URL: https://www.b-trust.bg/attachments/BtrustPrivateFile/64/docs/BISS.msi

**Comment by smsimeonov** [comment]
@vikingnope Just to mention, as I thought I would just get a template to fill instead of someone else doing it (I don't mind), Oracle's Java 8 is a prerequisite for the software to function properly. (The main package that the installer results in is actually a .jar file)

**Comment by vikingnope** [comment]
I just tested it locally and it worked fine without the dependency.

**Comment by smsimeonov** [comment]
If the application worked, it probably means you had Java installed. But Java is not preinstalled on Windows, so it would be good to add it as a dependency.

**Comment by vikingnope** [comment]
It was in a Sandbox, I think the msi installs it automatically

**Comment by smsimeonov** [comment]
They have added a Java Runtime to the package, I just checked. Ignore my comments, my bad.
