### ISSUE TITLE
[Update Request]: Process Explorer v17.06

### ISSUE THREAD

**Issue by Noxillio** [microsoft/winget-pkgs#155525]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Sysinternals.ProcessExplorer

### Package Version

17.06

### Please describe the changes you would like to see

There is a new release (17.06) available. Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer#download

**Comment by Jvr2022** [comment]
I am gonna do it
