### ISSUE TITLE
URL arguments

### ISSUE THREAD

**Issue by mddtest** [microsoft/winget-pkgs#15551]
# Description of the new feature/enhancement

Have the option to view a list of all winget entries url source destination.

# Proposed technical implementation details (optional)

add a -u,  --URL  argument so you can see an output off the source of where files will be downloaded from.

**Comment by KaranKad** [comment]
Use `winget show <appname>` command

**Comment by mddtest** [comment]
This is what I have more in mind.  when you `winget list --URL`

![image](https://user-images.githubusercontent.com/72764339/120364955-dad5c080-c2db-11eb-92a4-1d03c1ca6470.png)

**Comment by abdonmorales** [comment]
Almost like DNF Package Manager from Red Hat

**Comment by iDolmatov** [comment]
For the interface (CLI), you need to write here:
https://github.com/microsoft/winget-cli

See this section on package distribution.
Additionally, you can discuss in the [discussions](https://github.com/microsoft/winget-pkgs/discussions) section.

**Comment by mddtest** [comment]
posted on correct one closing this one
