### ISSUE TITLE
[Package Request]: Tesseract

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#155768]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: [STABLE](http://tesseract.gg/) and [NIGHTLY](https://mappinghell.net/tesseract/)
Publisher: `Tesseract team`
Package Name: `Tesseract`
Description: `Tesseract is a first-person shooter game focused on instagib deathmatch and capture-the-flag gameplay as well as cooperative in-game map editing.`
Package Version: _**Multiple**_ _`(see below)`_
Installer URL:  _`(see below)`_
Notes: [Official webpage](http://tesseract.gg/) **AND**  [Nightly-builds page](https://mappinghell.net/tesseract/)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> The _Nightly_ build is released as a compressed archive of loose executables. `winget.exe` does not support such kind of packages.
>
> ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/8830df77-ce7d-44eb-9a58-aa3b6a295240)
