### ISSUE TITLE
[Update Request]: Typora (ARM64)

### ISSUE THREAD

**Issue by PeronGH** [microsoft/winget-pkgs#155855]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

appmakes.Typora

### Package Version

1.8.5

### Please describe the changes you would like to see

Please add ARM64 version of Typora. The ARM64 version is a little bit lagging behind (1.8.5 for ARM64 vs. 1.8.10 for x86). It can be downloaded at https://download.typora.io/windows/typora-setup-arm64-1.8.5.exe

**Comment by Dragon1573** [comment]
Sorry, they are already there ❤️

- [`v1.8.5` International](https://github.com/Dragon1573/winget-pkgs/blob/master/manifests/a/appmakes/Typora/1.8.5/appmakes.Typora.installer.yaml#L53-L66)
- [`v1.8.5` Simplified Chinese](https://github.com/Dragon1573/winget-pkgs/blob/master/manifests/a/appmakes/Typora/1.8.5/appmakes.Typora.installer.yaml#L99-L114)

**Comment by SpecterShell** [comment]
The publisher sometimes does not release new installers for all the platforms or the architectures.
