### ISSUE TITLE
[Package Request]: Fufu Tools v1.3.1-1

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#156080]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:`https://github.com/DuckDuckStudio/Fufu_Tools/releases/`
Publisher:`鸭鸭「カモ」` (or `Duck Studio`)
Package Name:`芙芙工具箱` (or `Fufu Tools`)
Description:`一个开源的实用工具箱`
Package Version:`v1.3.1-1`
Installer URL:`https://github.com/DuckDuckStudio/Fufu_Tools/releases/download/v1.3.1-1/Fufu_Tools_Setup.v1.3.1-1.exe`

**Comment by Dragon1573** [comment]
> [!IMPORTANT]
>
> @DuckDuckStudio, since you are the publisher & author of this package. Please give me "approval" or "request changes" on the above pull request, to make sure it match your satisfaction.
>
> Thank you! ❤️

**Comment by DuckDuckStudio** [comment]
@Dragon1573 
In fact, there was a PR of the same version (old installation package download link) before, and it was not pass all checked.
But I confirm that the installation package can be installed properly.
其实之前有个相同版本（旧安装包下载链接）的PR，也没过检查。
但我确认安装包可以正常安装。
> 之前Issue的由 @Luna-Grace 提交
之前的PR:[#156017](https://github.com/microsoft/winget-pkgs/pull/156017)
之前的Issue:[#155966](https://github.com/microsoft/winget-pkgs/issues/155966)

**Comment by Dragon1573** [comment]
Both I and @CoolPlayLin mark this installer file with `Architecture: x86`, and _Azure Pipelines_ by Microsoft will run all tests on a 32-bit virtual machine.

Is this package "64-bit only"? I have seen several packages provides `x86` installer wizard but only installable on `x64` device.

-----

我和 CoolPlayLin 都把这个安装程序标记成了 `x86` 架构，所以微软配置的 Azure 流水线会使用32位虚拟机运行所有测试。

这个应用是「仅64位」的吗？我之前遇到过几个应用提供了 `x86` 架构的安装包（指安装包文件本身），但只能在 `x64` 架构的设备上完成安装（指安装后的主程序是仅支持 `x64` 的）

**Comment by DuckDuckStudio** [comment]
I only test this installer file with Architecture: **x64**...
<hr />
我只在 **x64** 架构的设备上测试过...

**Comment by DuckDuckStudio** [comment]
New PR #157822
