### ISSUE TITLE
[Update Request]: Subtitle Edit 4.0.6

### ISSUE THREAD

**Issue by niksedk** [microsoft/winget-pkgs#156068]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Nikse.SubtitleEdit

### Package Version

4.0.6

### Please describe the changes you would like to see

New release

Highlights:
    Audio to text (in the video menu)
    Generate video with burned-in subs "Batch mode" 
    A few fixes for Auto translate.

https://github.com/SubtitleEdit/subtitleedit/releases/tag/4.0.6

**Comment by niksedk** [comment]
PR: https://github.com/microsoft/winget-pkgs/pull/156067

**Comment by stephengillie** [comment]
> PR: #156067
