### ISSUE TITLE
[Package Request]: Lobster

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#156085]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/aardappel/lobster
Publisher: https://github.com/aardappel
Package Name: Lobster
Description: The Lobster Programming Language
Package Version: v2024.0
Installer URL: https://github.com/aardappel/lobster/releases/download/v2024.0/lobster_windows_release.zip
Official webpage: https://www.strlen.com/lobster/
Official repository: https://github.com/aardappel/lobster

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This package is an unzip-to-install, loose executable compressed archive. `winget.exe` does not support such kind of packages at the moment.

**Comment by stephengillie** [comment]
Since #163997 has merged, I'll assume this Issue is complete. If this is in error, please @ me and I'll reopen the Issue.

**Comment by anderlli0053** [comment]
Why yes, thank you all!
