### ISSUE TITLE
[Package Request]: Z-Sharp

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#156094]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/sam-astro/Z-Sharp/releases
Publisher: https://github.com/sam-astro
Package Name: `ZSharp`
Description: `Custom programming interpreter for ZSharp (Z#)`
Package Version: `v2.1.3-alpha`
Installer URL: https://github.com/sam-astro/Z-Sharp/releases/download/v2.1.3/ZSharp-Win-Installer.zip **OR**  https://github.com/sam-astro/Z-Sharp/releases/download/v2.1.3/ZS_Win_Base_Raw.zip

**Comment by stephengillie** [comment]
Since #163996 has merged, I'll assume this Issue is complete. If this is in error, please @ me and I'll reopen the Issue.

**Comment by anderlli0053** [comment]
Why yes, thank you all!
