### ISSUE TITLE
[Update Request]: WhatsApp.WhatsApp

### ISSUE THREAD

**Issue by loadstring1** [microsoft/winget-pkgs#156231]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

WhatsApp.WhatsApp

### Package Version

22405.508.1.0

### Please describe the changes you would like to see

There is a new release (22405.508.1.0) availbale.

Download page url: https://www.whatsapp.com/?lang=en

**Comment by Dragon1573** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/49941141/547d7efa-5461-4a2f-8524-7b0446601d6f)

Official team of _WhatsApp_ seems prefer distribute their application via _Microsoft Store_ than by installer file. I think it'd better instruct users to install _WhatsApp_ via `msstore` source or _Microsoft Store_ directly.

**Comment by loadstring1** [comment]
> ![image](https://private-user-images.githubusercontent.com/49941141/336012893-547d7efa-5461-4a2f-8524-7b0446601d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTc4ODYsIm5iZiI6MTcxNzQxNzU4NiwicGF0aCI6Ii80OTk0MTE0MS8zMzYwMTI4OTMtNTQ3ZDdlZmEtNTQ2MS00YTJmLTg1MjQtN2IwNDQ2NjAxZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEyMjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NWRlMjhlOGE4YzdkOGI4OTNlMTZiMGZjMWNjY2Q0NTA0ZDcwYWY2OTMzYzgzMjJmZjcwZGNjNDNjOTYwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e62tydgx7fAU7w3D8MfMFrhiLqYcjOPqELhc493bbu4)
> 
> Official team of _WhatsApp_ seems prefer distribute their application via _Microsoft Store_ than by installer file. I think it'd better instruct users to install _WhatsApp_ via `msstore` source or _Microsoft Store_ directly.

thats the reason why i made this issue because when you try to winget install WhatsApp.WhatsApp it will error with hash doesn't match so they either update package with the one from msstore or they redirect everyone who does winget install WhatsApp.WhatsApp to msstore source and not winget source

**Comment by Dragon1573** [comment]
I'd prefer remove this package from `winget` source, since there's only 1 version available in `winget`.

```text
22:48:44 D:\Repository 4ms pwsh> komac list-versions --identifier WhatsApp.WhatsApp
2.2326.10

22:48:49 D:\Repository 2.964s pwsh> winget show -e WhatsApp.WhatsApp --versions
已找到 WhatsApp [WhatsApp.WhatsApp]
版本
---------
2.2326.10
```

**Comment by Trenly** [comment]
@dragon1573 - You may want to also remove `WhatsApp.WhatsApp.Beta`
