### ISSUE TITLE
[Package Request]: Connect Fonts

### ISSUE THREAD

**Issue by Airey7** [microsoft/winget-pkgs#156228]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.extensis.com/support/connect-fonts
Publisher: Extensis
Package Name: Connect Fonts
Description: Software used for installing fonts
Package Version: 25.1.1
Installer URL: https://links.extensis.com/connect_fonts/cf_latest?language=en&platform=win

**Comment by Dragon1573** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/49941141/ef1d8e31-5b78-454a-80c7-a821612262a2)

This package has the ability to install `Microsoft.VCRedist.2015+.x64` and `Microsoft.VCRedist.2015+.x86` by itself, but user authentication is required for this process.

Also the package seems requires `x64` and `x86` version at the same time, but we can't add them into a single manifest.

**Comment by stephengillie** [comment]
Support for multiple dependencies has been added.
