### ISSUE TITLE
[Update Request]: CodecGuide.K-LiteCodecPack.* 18.3.5

### ISSUE THREAD

**Issue by MageLuingil** [microsoft/winget-pkgs#156242]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

CodecGuide.K-LiteCodecPack.Full

### Package Version

18.3.5

### Please describe the changes you would like to see

Requesting all K-Lite codec packs be updated:

| ID | URL |
| - | - |
| CodecGuide.K-LiteCodecPack.Basic | https://files3.codecguide.com/K-Lite_Codec_Pack_1835_Basic.exe |
| CodecGuide.K-LiteCodecPack.Standard | https://files3.codecguide.com/K-Lite_Codec_Pack_1835_Standard.exe |
| CodecGuide.K-LiteCodecPack.Full | https://files3.codecguide.com/K-Lite_Codec_Pack_1835_Full.exe |
| CodecGuide.K-LiteCodecPack.Mega | https://files3.codecguide.com/K-Lite_Codec_Pack_1835_Mega.exe |

**Comment by Exorcism0666** [comment]
- #156138
