### ISSUE TITLE
FoxIt Reader 2024.2.2.25170 install failed

### ISSUE THREAD

**Issue by nolme** [microsoft/winget-pkgs#156396]
Hello,

FoxIt update is not working anymore : 
C:\Windows\System32>winget upgrade --all
Nom                                           ID                                  Version        Disponible     Source
----------------------------------------------------------------------------------------------------------------------
Discord                                       Discord.Discord                     1.0.9013       1.0.9144       winget
Driver Easy 6.0.0                             Easeware.DriverEasy                 6.0.0          6.0.0.25691    winget
Foxit PDF Reader                              Foxit.FoxitReader                   2024.1.0.23997 2024.2.2.25170 winget
Microsoft SQL Server Management Studio - 19.2 Microsoft.SQLServerManagementStudio 19.2           20.1           winget
Teams Machine-Wide Installer                  Microsoft.Teams.Classic             1.6.0.4472     1.7.00.13456   winget
Microsoft .NET Runtime - 6.0.30 (x64)         Microsoft.DotNet.Runtime.6          6.0.30         6.0.31         winget
6 mises à niveau disponibles.

[WinGet-Foxit.FoxitReader.2024.2.2.25170-2024-06-03-14-10-02.876.log](https://github.com/user-attachments/files/15533673/WinGet-Foxit.FoxitReader.2024.2.2.25170-2024-06-03-14-10-02.876.log)

**Comment by stephengillie** [comment]
Despite the error, did FoxIt become installed? The error code `1603` sometimes means "Install successful but reboot required" - is that the case here?

**Comment by nolme** [comment]
> Despite the error, did FoxIt become installed? The error code `1603` sometimes means "Install successful but reboot required" - is that the case here?

Computer reboot, same problem. When I run the program it prompt for the same update.

**Comment by SpecterShell** [comment]
Could you try `winget upgrade Foxit.FoxitReader.Inno`?

**Comment by nolme** [comment]
> Should have been fixed. Could you try again?

All seems ok. thanks :)

**Comment by Dragon1573** [comment]
> All seems ok. thanks :)

It seems this issue is successfully resolved. Could you please manually close this issue as "completed"? 🙏🏼
