### ISSUE TITLE
[Update Request]: python

### ISSUE THREAD

**Issue by 3xploiton3** [microsoft/winget-pkgs#156377]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

python

### Package Version

3.12.3

### Please describe the changes you would like to see

![image](https://github.com/microsoft/winget-pkgs/assets/19517680/ba257bc7-3957-42bd-88c4-b64b527d568d)

**Comment by Trenly** [comment]
@3xploiton3 - It looks like you have the `msstore` source enabled, which is not controlled by this repository. I checked all the packages under `Python.Python.*` in the `winget` source, and they are all up to date. Using `winget install python3 -s winget` will install Python 3.12.3

**Comment by 3xploiton3** [comment]
> @3xploiton3 - It looks like you have the `msstore` source enabled, which is not controlled by this repository. The `msstore` source requires publishers of applications to upload their new version in the Microsoft Store. I checked all the packages under `Python.Python.*` in the `winget` source, and they are all up to date. Using `winget install python3 -s winget` will install Python 3.12.3

thanks for the explanation, 

![image](https://github.com/microsoft/winget-pkgs/assets/19517680/6ba51dd2-156f-49f0-a259-eb37054a9573)
