### ISSUE TITLE
Repology unlisted WinGet; no longer providing package statuses

### ISSUE THREAD

**Issue by aisgbnok** [microsoft/winget-pkgs#156468]
The Repology section in the README.md does not work as WinGet has been *temporarily* delisted from Repology. https://github.com/repology/repology-updater/commit/e676156f23fe6e28d8d3098695edfd1c57cba082 

https://github.com/microsoft/winget-pkgs/issues/156468#issuecomment-2146635690 

---

https://github.com/microsoft/winget-pkgs/blob/20070f1f67a38f10522bb1c4bf86fd28b206381a/README.md?plain=1#L24-L27

Going to https://repology.org/repository/winget, you get: 
![image](https://github.com/microsoft/winget-pkgs/assets/10838153/68507b3b-c7a6-4894-85dc-02b8d954d6d7)

> Sorry, but Repology no longer tracks repository **winget**.
>
> Last time Repology has processed this repository was 2024-05-31 12:20 (3 days ago).
> 
> Some of the reasons which may have caused this:
> 
> - The repository has reached it's end of life, is no longer updated or supported, should no longer be used, and has probably disappeared from the mirrors. There may be a newer version of this repository available though, check [the list](https://repology.org/repositories/statistics).
> - Repository has stopped publishing information about it's packages in format usable to Repology, so it's can't be processed any more. You may try contacting repository owners and ask them to fix this.

**Comment by SpecterShell** [comment]
https://github.com/repology/repology-updater/commit/e676156f23fe6e28d8d3098695edfd1c57cba082

**Comment by ztest973004** [comment]
Still not fixed after 1 month.

**Comment by aisgbnok** [comment]
> Still not fixed after 1 month.

Work is being done to address this. Ex:

- https://github.com/microsoft/winget-cli/issues/1725
- https://github.com/microsoft/winget-cli/pull/4588
