### ISSUE TITLE
I cant install TeamViewer with Winget

### ISSUE THREAD

**Issue by unknown850** [microsoft/winget-pkgs#15651]
0x80072f7c : unknown error

That is the error code. I uninstalled TeamViewer and ran powershell with Adminitrative Permission.

**Comment by Trenly** [comment]
@unknown850 @itayzimet @lucki1000 - Are any of you still experiencing this issue? I just tested the latest version of TeamViewer with the latest version of winget (`winget install TeamViewer.TeamViewer --source winget`) and it installed perfectly fine for me

**Comment by unknown850** [comment]
Well, it been long time since I started this page and I already decided to switch to Chocolatey instead but thank everyone who trying to help me all these time.
Chears

**Comment by lucki1000** [comment]
@Trenly, now it seems like it is working.

**Comment by ghadzhigeorgiev** [comment]
Cannot upgrade to latest TeamViewer:

winget upgrade TeamViewer.TeamViewer --source winget

Found TeamViewer [TeamViewer.TeamViewer] Version 15.40.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
**Installer failed with exit code: 2**
