### ISSUE TITLE
[Update Request]: OpensJS.NodeJS

### ISSUE THREAD

**Issue by akitson-degreed** [microsoft/winget-pkgs#156541]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OpenJS.NodeJS

### Package Version

18.19.0

### Please describe the changes you would like to see

I would like to use winget to install version 18.19.0 of node, but it is not in the list of versions available at https://winget.run/pkg/OpenJS/NodeJS or at https://winget.run/pkg/OpenJS/NodeJS.LTS

**Comment by aisgbnok** [comment]
That's part of NodeJS.LTS:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenJS/NodeJS/LTS/18.19.0

Installing using the command below should work:
```
`winget install OpenJS.NodeJS.LTS -v 18.19.0`
```

**Comment by Trenly** [comment]
If you look at the actual manifests, it is present in `OpenJS.NodeJs.LTS` - https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenJS/NodeJS/LTS/18.19.0

Use `winget install OpenJS.NodeJS.LTS --version 18.9.0`.

Please note that winget.run is not an official site, and you can always check which versions of a package are available with `winget show <ID> --versions`

**Comment by akitson-degreed** [comment]
ah thank you!
