### ISSUE TITLE
Upgrade does not work properly on auto-updating apps

### ISSUE THREAD

**Issue by derkrasseleo** [microsoft/winget-pkgs#15661]
# Brief description of your issue

Discord updated itself to version 1.0.9002 but winget doen't realise and thinks there is an update. When I do `winget upgrade` I get an Update for Discord but when I try to upgrade discord it says nothing to update.  That could be confusing and could cause issues with self-updating apps.

# Steps to reproduce

1. `winget upgrade`
2. `winget upgrade discord` or `winget upgrade discord.discord`

# Expected behavior

Updating discord to the newest version or ignoring the upgrade when a newer version is already installed.

# Actual behavior

Discord doen't get updated / doesn't check wich version is installed?

# Environment

```none
[winget --info]
v1.0.11451

Windows: Edition	Windows 10 Pro
Version	21H1
Build	19043.1023
Windows Feature Experience Pack 120.2212.3740.0

Package: Discord Discord.Discord 1.0.9001 1.0.9002  winget

**Comment by denelon** [comment]
This appears to be related to the metadata in the manifest or the package itself. This depends on what version is stated in the latest manifest as well as the version the package reports in Add / Remove Programs.

**Comment by denelon** [comment]
Is this still an issue? Hopefully Discord is reporting the version and the manifest is correctly determining when an update is available.

**Comment by denelon** [comment]
If packages are updating themselves, they can be excluded from `winget upgrade --all` by default if the "requireExplicitUpgrade" is specified in the manifest.

**Comment by NeighbourDYY** [comment]
So this is up to the package authors?

> If packages are updating themselves, they can be excluded from `winget upgrade --all` by default if the "requireExplicitUpgrade" is specified in the manifest.

**Comment by rollingmoai** [comment]
- https://github.com/Squirrel/Squirrel.Windows/issues/1676

**Comment by Trenly** [comment]
I'm going to close this issue as a stale issue since it is up to the applications themselves to write the proper version information into the registry. WinGet has several features to help when this case is present such as `requireExplicitUpgrade`, the `winget pin` command, and now a new `UpgradeBehavior: deny` that can be specified in manifests
