### ISSUE TITLE
[Package Request]: Synergy

### ISSUE THREAD

**Issue by voidblack** [microsoft/winget-pkgs#156602]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://symless.com/synergy/download
Publisher: Symless
Package Name: Synergy keyboard and mouse
Description: Use a single keyboard and mouse between multiple computers
Package Version: 3.0.79.1-rc3
Installer URL: https://symless.com/synergy/synergy/api/download/synergy-win_x64-v3.0.79.1-rc3.msi

**Comment by stephengillie** [comment]
The package version has an `rc` - is it a Release Candidate? We've been working to separate pre-release and mainline software versions, as there is a definite demand for both. Should this specific version be added to a `PackageIdentifier` such as `Symless.Synergy.RC`, and the most recent non-`rc` version be `Symless.Synergy`?

**Comment by voidblack** [comment]
Well, the version has in fact an `rc` but it is the mainline version. There is no other offical download with a another version string / name. So from my view the version can be simply named `Symless.Synergy`
