### ISSUE TITLE
[Update Request]: Update TheDocumentFoundation.LibreOffice

### ISSUE THREAD

**Issue by yuguuk** [microsoft/winget-pkgs#156958]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TheDocumentFoundation.LibreOffice

### Package Version

24.2.4

### Please describe the changes you would like to see

There is a new release (24.2.4) available. 
Download link: https://download.documentfoundation.org/libreoffice/stable/24.2.4/win/x86_64/LibreOffice_24.2.4_Win_x86-64.msi

**Comment by Dragon1573** [comment]
This is already in progress. 

- See #156768

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This issue should be closed as "completed", since the related pull request is merged.

**Comment by Exorcism0666** [comment]
@stephengillie

**Comment by stephengillie** [comment]
> Note
> 
> This issue should be closed as "completed", since the related pull request is merged.
