### ISSUE TITLE
Blitz.Blitz requests upgrades indefinitely

### ISSUE THREAD

**Issue by MCOfficer** [microsoft/winget-pkgs#15710]
# Brief description of your issue
Blitz has an available update (always the same) whenever you run `winget upgrade blitz`.

# Steps to reproduce

- Install Blitz
- Run `winget upgrade blitz`, get the upgrade
- Repeat ^

# Expected behavior

No new update should be installed until blitz actually releases one.

# Actual behavior

The same update is reinstalled whenever i run `winget upgrade blitz`

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19041.928
Paket: Microsoft.DesktopAppInstaller v1.11.11451.0
```
---

I reckon this is due to the full version number being filed in this repo, while winget only sees the 3-digit version number locally:

```
PS > winget upgrade
Name                 ID                   Version  Verfügbar   Quelle
---------------------------------------------------------------------
Blitz                Blitz.Blitz          1.14.17  1.14.17.511 winget  
```
*German: Verfügbar = Available; Quelle = Source*

**Comment by OfficialEsco** [comment]
This comes from the dynamic link and wingetbot automaticly updating it and taking the File Version from the installer.
![image](https://user-images.githubusercontent.com/15158490/120469026-2652a200-c3a2-11eb-9c9b-7fadcab4029a.png)

We can fix it with a Static URL https://blitz-stable.blitz.gg/Blitz-1.14.17.exe

**Comment by denelon** [comment]
@OfficialEsco do we have a bug or feature on the winget-pkgs backlog to fix this, or is this the best the bot can do given the installer and the metadata?

**Comment by OfficialEsco** [comment]
I don’t actually know what the bot does or how it gets the Version, because it SHOULD have the same metadata, so this is probably a feature bug which looks at File Version instead of Product Version

**Comment by denelon** [comment]
It's been a while since we had the discussion, but I believe we look for Product Version, and if we don't find that we look at File Version. I could be wrong though. I'll double check with the team.

**Comment by denelon** [comment]
@OfficialEsco We check both but if we find both and major and minor are the same we return the file version.
