### ISSUE TITLE
[Package Issue]: Google.Drive

### ISSUE THREAD

**Issue by Surfict** [microsoft/winget-pkgs#157228]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Hello,

Currently installing google drive v71.0.3.0 (currrent displayed last version) does not work. 

### Steps to reproduce

Run in powershell
```
winget install -e --id Google.Drive
```

### Actual behavior

I have the message "No package found matching input criteria." . The package is not installed

### Expected behavior

Google drive package to be installed.

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3672
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by Surfict** [comment]
It works with
```
winget install -e -h --id Google.GoogleDrive
```

I guess it needs to be changed [here](https://winget.run/pkg/Google/Drive)

**Comment by stephengillie** [comment]
Hi @Surfict,

To my knowledge, the linked site is an independent operation built around the package manager. This issue might need to be reposted to the site owner.

**Comment by Surfict** [comment]
I added an issue in their [tracker ](https://issuetracker.google.com/issues/346350838)(not totally sure this is the good place, but didn't find anything else). Hopefully it ends to the right people.

**Comment by aisgbnok** [comment]
@surfict, this is not an issue with the Google Drive installer, but that the package Id is wrong. `Google.Drive` is not the package Id, it is `Google.GoogleDrive`.

```PowerShell
winget install -e Google.GoogleDrive
```

As @stephengillie states, [winget.run](https://winget.run/) is a third-party website independent of Microsoft's Windows Package Manger. Therefore, it may not show up-to-date commands.

In the future WinGet search may help:

```PowerShell
PS E:\> winget search "Google Drive"
Name         Id                 Version  Source
------------------------------------------------
Google Drive Google.GoogleDrive 92.0.0.0 winget
PS E:\>
```

**Comment by Surfict** [comment]
Oh ok ! Misunderstood @stephengillie. Thanks. I guess the issue can be closed.
