### ISSUE TITLE
[Package Issue]: IDMComputerSolutions,Inc.UltraEdit

### ISSUE THREAD

**Issue by GijsCalis** [microsoft/winget-pkgs#157277]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Version is incorrect. The manifest in the repository states 31.0.35 as the current version. This should be 31.0.0.35.

### Steps to reproduce

1. Install latest version of UltraEdit (31.0.0.35 at time of writing) 
2. run `winget upgrade`
3. Notice that 'newer' version 31.0.35 is available according to this repo.

### Actual behavior

Incorrect new version is found:
```
Name                                             Id                                 Version   Available Source
--------------------------------------------------------------------------------------------------------------
UltraEdit                                        IDMComputerSolutions,Inc.UltraEdit 31.0.0.35 31.0.35   winget
```

### Expected behavior

No new version should be found as 31.0.0.35 is the current release.

### Environment

```raw
Windows Package Manager v1.7.11261
Windows: Windows.Desktop v10.0.22621.3593
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0
```

### Screenshots and Logs
![image](https://github.com/microsoft/winget-pkgs/assets/51088038/a573e208-4b51-4976-98b0-b21a8c0c5c9d)

**Comment by GijsCalis** [comment]
The version for IDMComputerSolutions,Inc.UEStudio is also wrong: it should be `24.0.0.35` instead of `24.0.35`.
Is this an error in an automatic detection mechanism?

I can provide pull requests to fix the versions of these packages. But if these versions are detected incorrectly it would of course be better to fix this issue at the source.

**Comment by GijsCalis** [comment]
I think this is an issue with the 'Publisher' information in the MSI files from IDM.
The MSI file has an incorrect version included in the 'Publisher' field. Could this be the cause?

I'll report this to IDM and post any update here, if you are interested.
```
PS C:\Downloads> Get-AppLockerFileInformation -Path ue_english_64.msi

RunspaceId : b6b0431b-4b1a-49d8-8604-ff50b9a61661
Path       : %OSDRIVE%\DOWNLOADS\UE_ENGLISH_64.MSI
Publisher  : O=ULTRAEDIT, INC., L=AUSTIN, S=TEXAS, C=US\ULTRAEDIT\{32AE92AA-6BFE-1014-A875-D17E057FC493},31.0.35.0
Hash       : SHA256 0x7E077C563FA4C0509096595A3E4B3E494534FBB6588CAF5BCBDDFBBEDA3E94E6
AppX       : False
```

**Comment by Trenly** [comment]
@GijsCalis - I think you're right that this is an issue specifically because the MSI files and the EXE files have different versions, since installing with the MSI installer does write `31.0.35` as the version

![image](https://github.com/microsoft/winget-pkgs/assets/12611259/7e7fd72a-e678-4a36-b6d4-5e540f6a8995)

**Comment by GijsCalis** [comment]
You're right, the exe installer file reports the same version number as the application executable:
```
PS C:\Downloads> get-applockerfileinformation -path .\ue_english_64.exe
Publisher  : O=ULTRAEDIT, INC., L=AUSTIN, S=TEXAS, C=US\ULTRAEDIT\SUF_LAUNCH.EXE,31.0.0.35
```
I've reported the issue to IDM.

**Comment by Trenly** [comment]
@gijscalis - I've made some updates to the manifest that may also help with this issue. Can you let me know if you're still seeing the problem?

**Comment by GijsCalis** [comment]
Winget is no longer reporting an newer version available for my UltraEdit (exe) installation version 31.0.0.35. So you're updates are working for me. Thanks!

**Comment by mdanish-kh** [comment]
Close with reason: Trenly's PRs fixed the issue;
