### ISSUE TITLE
[Package Issue]: Guru3D.Afterburner.Beta

### ISSUE THREAD

**Issue by elisimpson** [microsoft/winget-pkgs#157227]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Package version is listed as 4.6.6, whereas the program itself is 4.6.6 Beta 3. This results in the package constantly thinking it is outdated and installs over and over again. The version in the manifest needs to be updated to include the "Beta 3" part of the full version string

### Steps to reproduce

1. install package
2. `winget upgrade`
3. package shows as needing to upgrade to 4.6.6

### Actual behavior

package shows as needing to update when it doesn't

### Expected behavior

Version string should be updated to include the beta number so it doesn't think it needs to upgrade when it doesn't and will show upgrade when 4.6.6 Beta 4 is eventually released.

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3672
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by vikingnope** [comment]
This contains an apps and features entry, so it should not be the case:

```
AppsAndFeaturesEntries:
  - DisplayName: MSI Afterburner 4.6.6 Beta 3
    DisplayVersion: 4.6.6 Beta 3
```

**Comment by elisimpson** [comment]
Interesting. Something's not right though as when I do `winget list` I get this:

```
Name                                      Id                                         Version           Available Source
MSI Afterburner 4.6.6 Beta 3              Guru3D.Afterburner.Beta                    4.6.6 Beta 3      4.6.6     winget
```

**Comment by vikingnope** [comment]
@stephengillie, what would you recommend?

**Comment by stephengillie** [comment]
Verify:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/f1d9bbf9-ccab-4cb9-8a51-3b5593ac9f81)
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/b0050be3-7021-40d1-b719-2a0f11cb8ee5)

Repro:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/44ef5493-442e-469e-9a3d-92d4441dbfe0)

- Ideally, the `PackageVersion` should be updated to match the application: `v4.6.6.16381 Beta 3`
- But this doesn't cover the "upgrade always available" situation. It seems like the package manager is comparing the Registry data with the `PackageVersion`, and ignoring the `DisplayVersion`. 
- Why it's doing this and how to fix, I'm not sure. I'm guessing that maybe the `DisplayVersion` isn't parsing the spaces in the version number correctly - maybe adding quotes around it will help parsing? 

@mdanish-kh and @Trenly, is there anything I missed here?

**Comment by mdanish-kh** [comment]
@elisimpson PR containing the mentioned changes was merged into the repo. Could you please check if you are still encountering the issue?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by elisimpson** [comment]
Issue is resolved on my end. Thanks to all!

**Comment by mdanish-kh** [comment]
Close with reason: Issue resolved by removing DisplayVersion;
