### ISSUE TITLE
[Update Request]: IDMComputerSolutions,Inc.UltraEdit

### ISSUE THREAD

**Issue by pitichou** [microsoft/winget-pkgs#157345]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

IDMComputerSolutions,Inc.UltraEdit

### Package Version

31.0.0.35

### Please describe the changes you would like to see

Everytime there is a new release for UltraEdit, the version number is wrong.
31.0.35 but it should be 31.0.0.35.

Previously reported here https://github.com/microsoft/winget-pkgs/issues/150803 and here https://github.com/microsoft/winget-pkgs/issues/133241

**Comment by Trenly** [comment]
Duplicate of #157277
