### ISSUE TITLE
[New Feature]: install Viber via winget

### ISSUE THREAD

**Issue by ilijamilcinoski** [microsoft/winget-pkgs#157344]
### Description of the new feature/enhancement

There should be added winget https://winstall.app/ a way to install Viber

### Proposed technical implementation details (optional)

winget install Viber

**Comment by ilijamilcinoski** [comment]
https://github.com/microsoft/winget-pkgs/issues/45361 here i found the code  winget install Viber it works

**Comment by Trenly** [comment]
> #45361 here i found the code winget install Viber it works

It \*used to* work, it no longer is possible due to limitations Viber has put in place
