### ISSUE TITLE
How do you update a package when it has a new version?

### ISSUE THREAD

**Issue by DestroyerXyz** [microsoft/winget-pkgs#15732]

**Comment by iDolmatov** [comment]
Upload new manifests (3 files) with the version number. Recommend use wingetcreate.

**Comment by DestroyerXyz** [comment]
So the same way you upload new packages?

**Comment by iDolmatov** [comment]
Yes. `wingetcreate submit`.
Example, https://github.com/microsoft/winget-pkgs/pull/15730
