### ISSUE TITLE
[Package Issue]: JonasJohn.RemoveEmptyDirectories

### ISSUE THREAD

**Issue by JustMyGithub** [microsoft/winget-pkgs#157422]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

1) 2.3 is beta but winget does not have a beta tag on it and stable (2.2) is not available either - https://github.com/hxseven/Remove-Empty-Directories/releases
2) the short name RED should be included in the name

### Steps to reproduce

n/a

### Actual behavior

n/a

### Expected behavior

n/a

### Environment

```raw
Windows: Windows.Desktop v10.0.19044.4412
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by JustMyGithub** [comment]
> Other than the version number, is there any indication that 2.3 is a beta?
Its tagged Pre-Release on Github. The website ( https://www.jonasjohn.de/red.htm ) also says its beta.

**Comment by Dragon1573** [comment]
Related #27049.

For version `v2.2`, the package requires **.NET Framework 3.5** Windows Feature to be enabled. Currently `Dependencies.[*].WindowsFeatures` hasn't been implemented.

Also, **.NET Framework 3.5** didn't available in `winget` source. Maybe we can try adding it to the repository as `PackageDependency`.

**Comment by stephengillie** [comment]
> Related #27049.
> 
> For version `v2.2`, the package requires **.NET Framework 3.5** Windows Feature to be enabled. Currently `Dependencies.[*].WindowsFeatures` hasn't been implemented.
> 
> Caution
> 
> Microsoft provides an [`*.exe` installer](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net35-sp1) for **.NET Framework 3.5** Windows Feature. But the installer wizard doesn't support silent install.
> 
> We have to wait for `Dependencies.[*].WindowsFeatures` to be available.

To my knowledge, this feature *is* available. A list of available feature names can be found with `Get-WindowsOptionalFeature -Online`. 

```suggestion
Dependencies:
  WindowsFeatures:
    - netfx3 
Installers:
```

**Comment by JustMyGithub** [comment]
I see it was renamed to JonasJohn.RED.Beta - but stable ist not available, is it? So I would not agree that this is "completed"
