### ISSUE TITLE
[Update Request]: WinSSHTerm metadata is incomplete and does not allow for machine wide installations

### ISSUE THREAD

**Issue by dnnnp** [microsoft/winget-pkgs#158024]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

P-StSoftware.WinSSHTerm

### Package Version

2.35.2

### Please describe the changes you would like to see

The metadata for WinSSHTerm is incomplete and does not allow for machine wide installations.

Issuing the command ` winget install P-StSoftware.WinSSHTerm --scope machine` yields the following error:
```
No applicable installer found; see logs for more details.
```

The error log contains the following hint:
```
2024-06-16 04:53:31.803 [CLI ] Installer [X64,wix,Unknown,en-US] not applicable: Installer scope does not match required scope: Unknown != Machine
```

**Comment by dnnnp** [comment]
Hello, unfortunately I have no idea on how to proceed from here. Every attempt in validating the manifest files via `winget validate` fails. Implementing the changes within https://github.com/dnnnp/winget-pkgs/commit/3739c58a5c8a25114b5e068f6d9ff86fba5db1c5 directly into the merged manifest works flawlessly for me.

Can anyone point me into the right direction?

**Comment by Dragon1573** [comment]
I'm working on it with version `v2.35.2`.

For validating manifests in the case of this issue, you should run `winget validate manifests/p/P-STSoftware/WinSSHTerm/2.35.2/`. "Manifest" here is the entire directory of that exact version.

For local validation, you can also run `Tools/SandboxTest.ps1 manifests/p/P-STSoftware/WinSSHTerm/2.35.2/` for both validating the manifests and try to install the package in _Windows Sandbox_.
