### ISSUE TITLE
[Update Request]: VLC new version

### ISSUE THREAD

**Issue by alpha194** [microsoft/winget-pkgs#158549]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

VideoLAN.VLC

### Package Version

3.0.21

### Please describe the changes you would like to see

There is a new release of VLC:

Win64: https://get.videolan.org/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
Win32: https://get.videolan.org/vlc/3.0.21/win32/vlc-3.0.21-win32.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This issue should be closed as "not planned", since it's a duplicate of #157606.
>
> `winget.exe` currently using `*.msi` as installer file, but this version provides none of them.

- https://github.com/microsoft/winget-pkgs/issues/157606#issuecomment-2176657880
- [videolan/vlc#28677 (comment)](https://code.videolan.org/videolan/vlc/-/issues/28677#note_441953)

**Comment by alpha194** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/issues/157606
