### ISSUE TITLE
MP3 tag installation failure

### ISSUE THREAD

**Issue by musm** [microsoft/winget-pkgs#15863]
# Brief description of your issue

# Steps to reproduce
```
winget install Mp3tag
```

# Expected behavior

It should install without any issues

# Actual behavior

![image](https://user-images.githubusercontent.com/4319522/120517079-0de08880-c39e-11eb-8198-156ea7b9773e.png)

# Environment

```none> 
winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
~
>
```

**Comment by ItzLevvie** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/11600822/125864060-5e0adb91-776b-4c5a-bbe6-52edb5381919.png)

**Comment by Trenly** [comment]
@musm Are you still experiencing this issue?

**Comment by OfficialEsco** [comment]
![VirtualBoxVM_qB9QvtD1RT](https://user-images.githubusercontent.com/15158490/150436260-c67dafe7-3d2d-4be5-b048-af5a77c1c957.png)
