### ISSUE TITLE
[Package Issue]: NagleCode.PacketSender 

### ISSUE THREAD

**Issue by pjhavariotis** [microsoft/winget-pkgs#158740]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The `upgrade` command generate the following error:
`1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.`
As you can see from the following output this package is the `NagleCode.PacketSender` :
```
winget upgrade --include-unknown
Name                                      Id                            Version          Available        Source
----------------------------------------------------------------------------------------------------------------
Packet Sender                             NagleCode.PacketSender        Unknown          8.7.1            winget
1 upgrades available.
```

### Steps to reproduce

First, install the aforementioned package with the command:
`winget install packetsender`
Secondly, try to upgrade with the command:
`winget upgrade`

### Actual behavior

The version of the package cannot be determined (Version: Unknown)!

### Expected behavior

The version of the package should be 8.7.1 !

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4412
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
The issue here is the installer doesn’t write a version to the registry. Because the installer doesn’t write a version, there is no way for WinGet to be able to determine the currently installed version. The only way to get this fixed would be for the creator of the software to update their installer so that it writes the version

**Comment by pjhavariotis** [comment]
Thanks. I'll make sure to inform the creator accordingly.
