### ISSUE TITLE
[Package Request]: UniFi Network Server

### ISSUE THREAD

**Issue by ageekhere** [microsoft/winget-pkgs#158707]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://ui.com/download/releases/network-server
Publisher: Ubiquiti
Package Name: UniFi Network Server
Description: The UniFi Network Application, developed by Ubiquiti Inc., is a centralized network management software designed to configure, manage, and monitor UniFi devices and networks. It provides a comprehensive suite of tools for network administrators to handle their network infrastructure efficiently
Package Version: 8.2.93
Installer URL: https://dl.ui.com/unifi/8.2.93/UniFi-installer.exe

They update the UniFi Network Server quite often so would be nice to have it added to winget

**Comment by Dragon1573** [comment]
> They update the UniFi Network Server quite often so would be nice to have it added to winget.

Glad to help. But it would be better if authorizing manifests by their own. I can help creating the "very first" manifest of the package, then they can automate the update process either with GitHub Actions (_Winget Releaser v2_) or by a bot account.

Manifests submissions are doing by volunteers or moderators (automatically or manually). Maybe the community can't catch up with official team.
