### ISSUE TITLE
WinGetSvc-Validation (Manifest Content Validation) fails

### ISSUE THREAD

**Issue by auanasgheps** [microsoft/winget-pkgs#1588]
Hi, 

#1445 fails reaching the timeout (1500m) at Manifest Content Validation / Installers Scan.

I can't understand why, I can't find anything wrong in my manifest.
I am not a super expert but I have already submitted two other programs which have been accepted.

**Comment by SoftCreatR** [comment]
You may try a force push in order to trigger the build process again. To do so, switch to your branch and run

```
git commit --amend
```

save unchanged and then, run

```
git push --force
```

**Comment by auanasgheps** [comment]
Thanks, but before I could do anything a Microsoft employee has forced the bot for me.
