### ISSUE TITLE
[Package Issue]: PortSwigger.BurpSuite.Community

### ISSUE THREAD

**Issue by BraveThrasher** [microsoft/winget-pkgs#159215]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Unable to update PortSwigger.BurpSuite.Community from version 2024.2.1.3 to the latest version.

### Steps to reproduce

With PortSwigger.BurpSuite.Community version 2024.2.1.3 installed do the following:

- execute `winget update`
- verify the available update
- execute `winget update PortSwigger.BurpSuite.Community`

### Actual behavior

The message below is shown:
```
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
```

### Expected behavior

A successful update of PortSwigger.BurpSuite.Community to the latest version.

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3737
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![Screenshot 2024-06-21 154125](https://github.com/microsoft/winget-pkgs/assets/3652075/6b7b008f-5443-416d-973f-b83df6f5ea93)
![Screenshot 2024-06-21 155450](https://github.com/microsoft/winget-pkgs/assets/3652075/670aa520-4b2b-4e29-a528-e29d3d121ceb)
[WinGet-2024-06-21-15-18-35.463.log](https://github.com/user-attachments/files/15928672/WinGet-2024-06-21-15-18-35.463.log)

**Comment by Dragon1573** [comment]
It seems the issue is caused by following property:

https://github.com/microsoft/winget-pkgs/blob/7aa3a8856073e16372c96c19f1d4696eba7fbd58/manifests/p/PortSwigger/BurpSuite/Community/2024.5.3/PortSwigger.BurpSuite.Community.installer.yaml#L7

It locks the manifest that "the package can only be installed in user scope", while you install the package (maybe in another way) in machine scope. `winget.exe` can't find a machine scope installer for you.

Is there any command line switch(es) for configuring the package installation scope? We can duplicate the installer entrance and distinguish them with different `InstallerSwitches` (something like follows).

```yaml
Installers:
- # Other parameters ignored
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER
- # Other parameters ignored
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
```
