### ISSUE TITLE
[Package Issue]: Package.Identifier GitHub Desktop

### ISSUE THREAD

**Issue by Robertblazor** [microsoft/winget-pkgs#159348]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

GitHub Desktop doesn't keep it up to date on the winget platform

### Steps to reproduce

winget search --name "GitHub"

### Actual behavior

<img width="638" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/96743273/6467da35-658c-41f7-b4ca-5bb0db8be138">

### Expected behavior

<img width="790" alt="image" src="https://github.com/microsoft/winget-pkgs/assets/96743273/8b79bfbd-e80f-4f25-bab8-191dfadc432e">

### Environment

```raw
[winget - Normal]
[Powershell 7.5.0 - preview.3]
[Windows 11 24H2 Dev channel June 2024]
```

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> You are in a wrong channel!
>
> Currently `GitHub.GitHubDesktop` is the stable version, which `PackageUrl` is `https://desktop.github.com/`. But what you want is something like `GitHub.GitHubDesktop.Beta`, which `PackageUrl` should be `https://desktop.github.com/beta`.
>
> They are not the same package.
