### ISSUE TITLE
[Package Request]: Stencyl

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#159487]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.stencyl.com/download/
Publisher: Stencyl, LLC
Package Name: stencyl
Description: `Stencyl isn't your average game creation software; it's a gorgeous, intuitive toolset that accelerates your workflow and then gets out of the way. We take care of the essentials, so you can focus on what's important - making your game yours.`
Package Version: 4.1.3 (Build 12232)
Installer URL: https://static.stencyl.com/downloads/stencyl/release/4.1.3/Stencyl-4.1.3.zip

**Comment by Dragon1573** [comment]
Sorry, this package seems to be a compressed archive of loose executables. `winget.exe` does not support such kind of packages at the moment.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/26600014-05d3-4e5f-9cec-31366a9d55d1)

The issue should be closed as "not planned" and attach https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/zip-binary.

**Comment by anderlli0053** [comment]
I cannot attach labels, but i can close as per https://github.com/microsoft/winget-pkgs/issues/159487#issuecomment-2185102047

**Comment by Dragon1573** [comment]
I previously use _Scoop_ as a package manager on _Windows_. It supports pre- and post-install scripts for installer files. In this case, _Scoop_ may be better than _WinGet_. ❤️
