### ISSUE TITLE
AnyDesk installer is broken

### ISSUE THREAD

**Issue by DRSchlaubi** [microsoft/winget-pkgs#15947]
# Brief description of your issue
The Anydesk installer always fails:
`Installer failed with exit code: 11341828`
# Steps to reproduce

- `winget install AnyDeskSoftwareGmbH.AnyDesk`

# Expected behavior

No error

# Actual behavior

Installer failed with exit code: 11341828

# Environment

```none
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19042.985
Paket: Microsoft.DesktopAppInstaller v1.11.11451.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
----------------------------------------------------------------
Datenschutzerklärung        https://aka.ms/winget-privacy
Lizenzvereinbarung          https://aka.ms/winget-license
Hinweise von Drittanbietern https://aka.ms/winget-3rdPartyNotice
Startseite                  https://aka.ms/winget
```

The Problem here is that https://download.anydesk.com/AnyDesk.exe isn't actually an installer. It's a thin client with an installation button (not sure if there is an install flag or something)
The `AnyDeskSoftwareGmbH.AnyDeskMSI` seems to work fine though

**Comment by GeorgeCY2** [comment]
I'll be trying to reproduce this today and I'll +1 this post if I can confirm, I can maybe try resubmitting the manifest package or remove it altogether until AnyDesk developers patch it

**Comment by GeorgeCY2** [comment]
Upon testing the MSI Version `Anydesk MSI` works better than the .exe installer, I'll try locally making another manifest and see if that works otherwise I'll pull request for removal of the Exe version until further notice of the team and Contributors of the repository.
Rather than commenting second time and filling out the issue I'll edit once I grab my results.

**Comment by OfficialEsco** [comment]
The 11341828 error code means its already installed, i had the same issue with the MSI when doing `winget update anydeskmsi` until i swapped the `UpgradeBehavior` from `Install` to `uninstallPrevious`, i also solved this issue for the exe by adding the `--remove-first` parameter

**Comment by OfficialEsco** [comment]
Aight, lemme know if there are more issues with AnyDesk

**Comment by i-zanis** [comment]
I would like to report the same issue with **winget install** on Windows11 (exit code: 11341828).

**Comment by OfficialEsco** [comment]
Is it already installed?

> The 11341828 error code means its already installed,

Which AnyDesk are you installing?  Since there have been some rework
