### ISSUE TITLE
Winget export says intalled package is not available while the package does exist.

### ISSUE THREAD

**Issue by BitSec01** [microsoft/winget-pkgs#15949]
Hello, When I ran `winget export -o programs.txt` I got a list of packages that were installed but not available from any source.
When I wanted to add the specific software to the repository I found that it actually does already exist.

winget export says:
`Installed package is not available from any source: Python 3.9.5 (64-bit)`

But when I took a look at the winget-pkgs I found:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Python/Python/3.9.5

# How to reproduce
1. Install Python 3.9.5 (64-bit)
2. Run `winget export -o programs.txt`

**Comment by denelon** [comment]
https://learn.microsoft.com/windows/package-manager/winget/export was updated to reflect this specific scenario where packages aren't being reported in a reliable way with Windows Apps & Features such that a match can be made with a manifest.
