### ISSUE TITLE
[Package Issue]: AppFlowy.AppFlowy

### ISSUE THREAD

**Issue by orkeilius** [microsoft/winget-pkgs#159413]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Wrong download link for 0.6.1
(there is a "v" in the version that shouldn't be here)
https://github.com/AppFlowy-IO/AppFlowy/releases/download/v0.6.1/AppFlowy-0.6.1-windows-x86_64.exe

### Steps to reproduce

install/update the package

### Actual behavior

the link is wrong

### Expected behavior

the link should be 

https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.1/AppFlowy-0.6.1-windows-x86_64.exe

### Environment

```raw
Windows: Windows.Desktop v10.0.26100.994
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.23.1522.0
```

**Comment by orkeilius** [comment]
Issue in the appFlowy repo : https://github.com/AppFlowy-IO/AppFlowy/issues/5604

**Comment by Dragon1573** [comment]
- Related #159135
- Related #158970
