### ISSUE TITLE
[Update Request]:  JetBrains.Toolbox

### ISSUE THREAD

**Issue by devdecrux** [microsoft/winget-pkgs#159480]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

JetBrains.Toolbox

### Package Version

2.2.3.20090

### Please describe the changes you would like to see

A newer version has been released for this package - Version: 2.3.2, Released: June 3, 2024
For more information: https://www.jetbrains.com/toolbox-app/

**Comment by Dragon1573** [comment]
Sorry @devdecrux, this issue should be closed as not planned.

- See https://github.com/microsoft/winget-pkgs/pull/159492#issuecomment-2185809071

**Comment by aisgbnok** [comment]
Can this be closed now that `2.4.0.32175` is published?
- https://github.com/microsoft/winget-pkgs/pull/161181

**Comment by mdanish-kh** [comment]
Close with reason: Package is updated to 2.4 release that's the current latest as of writing this message;

If you want a specific version added, feel free to open up a new issue for it
