### ISSUE TITLE
[Update Request]: HandBrake.handBrake

### ISSUE THREAD

**Issue by cyberpunk2350** [microsoft/winget-pkgs#159697]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

HandBrake.handBrake

### Package Version

1.8.1

### Please describe the changes you would like to see

New release available (1.8.1)
Download page: https://github.com/HandBrake/HandBrake/releases/download/1.8.1/HandBrake-1.8.1-x86_64-Win_GUI.exe
Signature:  https://github.com/HandBrake/HandBrake/releases/download/1.8.1/HandBrake-1.8.1-x86_64-Win_GUI.exe.sig

**Comment by Dragon1573** [comment]
> [!TIP]
>
> The issue will be resolved by #159397.
