### ISSUE TITLE
[Update Request]: TechSmith.Camtasia

### ISSUE THREAD

**Issue by Cam-GT** [microsoft/winget-pkgs#159607]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TechSmith.Camtasia

### Package Version

24.0.0

### Please describe the changes you would like to see

There is a new version of Camtasia available 24.0.0
https://download.techsmith.com/camtasiastudio/releases/2400/camtasia.exe

**Comment by vikingnope** [comment]
Unable to create a new Manifest due to a Network Blocker
