### ISSUE TITLE
[Package Issue]: Package.Identifier

### ISSUE THREAD

**Issue by DavArrow** [microsoft/winget-pkgs#159615]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Unable to install Floorp Browser (https://github.com/Floorp-Projects/Floorp)

### Steps to reproduce

winget install Ablaze.Floorp

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Install Completed

### Environment

```raw
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3737
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by vikingnope** [comment]
Kindly change title to [Package Issue]: Ablaze.Floorp, mismatch hash
