### ISSUE TITLE
Continue upgrade even if a single app fails to upgrade

### ISSUE THREAD

**Issue by UsefulVid** [microsoft/winget-pkgs#15987]
# Description of the new feature/enhancement
As soon as a single app fails to upgrade with
winget upgrade --all 
the whole upgrade process is canceled.
Example:
https://github.com/microsoft/winget-pkgs/issues/15651

# Proposed technical implementation details (optional)

It would be great to have an option like --ignorefailed for the upgrade switch to make sure all other apps get the updates
Another wanted feature would be to exclude certain apps from the upgrade. This would allow me to skip apps which are causing problems.

**Comment by iDolmatov** [comment]
I recommend closing the request, as there is a duplicate and the topic is in the wrong location.
https://github.com/microsoft/winget-cli/issues/1080

> Another wanted feature would be to exclude certain apps from the upgrade. 

https://github.com/microsoft/winget-pkgs/discussions/15243#discussioncomment-818792 and above.

**Comment by IGR2014** [comment]
Well, it is CERTAINLY NOT fixed. On of updates does not work (AIMP download server seems to be unavailable in Ukraine because of war). And this stops whole process of upgrade!

**Comment by BaronAdam** [comment]
Can confirm, crashes when I get response status code 403.
