### ISSUE TITLE
[Package Issue]: karakun.OpenWebStart

### ISSUE THREAD

**Issue by TheStingPilot** [microsoft/winget-pkgs#159914]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Different install technology.

### Brief description of your issue

karakun.OpenWebStart (1.10.1) not visible in Start Menu after installation. 

### Steps to reproduce

Install via `winget.exe install --exact --id karakun.OpenWebStart --silent --accept-package-agreements --accept-source-agreements --scope machine --source winget`
The application is not visible in the Start Menu,

If you install the previous version with `winget.exe install --exact --id karakun.OpenWebStart --version "1.9.1" --silent --accept-package-agreements --accept-source-agreements --scope machine --source winget` then the application is visible in the Start Menu.

### Actual behavior

The application is not visible in the Start Menu.

### Expected behavior

The application should be visible in the Start Menu.

### Environment

```raw
WinGet version: v1.7.11261
```

### Screenshots and Logs

I checked the installation yaml file. The only difference I see is:

Version 1.9.1 and earlier:
`InstallerType: exe`

Version 1.10.1:
`InstallerType: portable`

Hope this helps...

**Comment by stephengillie** [comment]
> I checked the installation yaml file. The only difference I see is:
> 
> Version 1.9.1 and earlier: `InstallerType: exe`
> 
> Version 1.10.1: `InstallerType: portable`
> 
> Hope this helps...

Hi @TheStingPilot,

Unfortunately, the package manager [doesn't currently supply Start menu shortcuts](https://github.com/microsoft/winget-cli/issues/2299), only symlinks as command line alaises. Any Start menu shortcuts would be supplied by the installer. It sounds like the `exe` installer in `1.9.1` might have added these - but the `portable` type of `1.10.1` wouldn't have this functionality, and niether does the package manager currently.

**Comment by Dragon1573** [comment]
> Edit: Does the `1.10.1` version have an `exe` installer? If so, the `1.10.1` manifest could be updated with it, which should resolve the issue.

I'm currently working on this issue ❤️ Both _Komac_ version `2.2.1` and `2.3.0` all detects the installer file as `InstallerType: portable` instead of `InstallerType: exe`. We should manually edit manifests (since _Komac_ `v2.3.0`, or use external editor after saving manifests locally) and correct this mistake.

Something wired here ...
