### ISSUE TITLE
Does YamlCreate.ps1 store installers somewhere?

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-pkgs#16041]
I would like to know if `YamlCreate.ps1` keeps installer somewhere after generating manifest for an application. This would be helpful for me as I would be able to install the application afterwards to get additional metadata about the application like `ProductCode`, accurate `Publisher`, `PackageName` and `PackageVersion`

**Comment by OfficialEsco** [comment]
This is the code part:

```
    while ([string]::IsNullOrWhiteSpace($InstallerUrl)) {
        Write-Host
        Write-Host -ForegroundColor 'Green' -Object '[Required] Enter the download url to the installer.'
        $InstallerUrl = Read-Host -Prompt 'Url' | TrimString
    }
    Write-Host $NewLine
    Write-Host 'Downloading URL. This will take awhile...' -ForegroundColor Blue
    $WebClient = New-Object System.Net.WebClient

    try {
        $Stream = $WebClient.OpenRead($InstallerUrl)
        $InstallerSha256 = (Get-FileHash -InputStream $Stream -Algorithm SHA256).Hash
    }
    catch {
        Write-Host 'Error downloading file. Please run the script again.' -ForegroundColor Red
        exit 1
    }
    finally {
        $Stream.Close()
    }
```

I don't actually know, but i don't think it saves it somewhere since it will be gone once you do `$Stream.Close`

**Comment by KaranKad** [comment]
Is it possible to add it as a opt in feature, I really don't know much about PowerShell scripting.

**Comment by OfficialEsco** [comment]
> Is it possible to add it as a opt in feature, I really don't know much about PowerShell scripting.

I would gladly add tons of stuff to YamlCreate, however it seems like the WinGet Team is keen on creating `wingetcreate` instead which slows down the merge process and i won't get any suggestions/help with parts of code...

Kinda disappointed `wingetcreate` didn't have the features of YamlCreate + more on release..

But yeah it would be possible to save the file to temp with a few lines

**Comment by denelon** [comment]
@OfficialEsco, I've been talking with the wingetcreate team about extending behavior to include things that speed up the merge process. They are heads down fixing bugs and LOVING your suggestions. I don't know if you are following discussions or not, but https://github.com/microsoft/winget-pkgs/discussions/15951 is an ask to help identify things that you, @jedieaston, and @ItzLevvie would like us to focus on to help with "Catalog-Health".

**Comment by OfficialEsco** [comment]
Well @denelon i don't think you understood the comment, if i would update YamlCreate it would most likely take days for it to be merged, and at the same time the one who is creating `wingetcreate` have to approve my changes.

I would like `wingetcreate` to be developed faster so it actually contains what YamlCreate does and fixes the major issues it is currently making.

And i don't speak C# so i have no idea what i'm looking at..
