### ISSUE TITLE
[Package Request]: `ASRock.AppShop`

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/winget-pkgs#160709]
### **How can we help?**

I would like someone else to build the manifest.

### **Please read and ensure the following**

- [X] The installer meets the above requirements

### **Package Requested**

- [X] I would like someone else to build the manifest.
- [ ] I would like help, so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available, and I have provided the URL.

### **Please provide the following information**

<table><tr>
	<th>Download Page URI</th>
	<td><a href="https://www.asrock.com/feature/appshop/#:~:text=Size%20%09Description-,Download,-4.26MB%20%09APP%20Shop">https://www.asrock.com/feature/appshop/#:~:text=Size%20%09Description-,Download,-4.26MB%20%09APP%20Shop</a></td>
</tr><tr>
	<th>Publisher</th>
	<td>ASRock</td>
</tr><tr>
	<th>Package Name</th>
	<td><code>ASRock.AppShop</code></td>
</tr><tr>
	<th>Description</th>
	<td> <blockQuote cite="https://www.asrock.com/feature/appshop/#:~:text=ASRock%20APP%20Shop%20is%20an%20all%2Din%2Done%20utility%20designed%20for%20system%20update%20and%20software%20downloading."> ASRock APP Shop is an all-in-one utility designed for system update and software downloading. </blockQuote> </td>
</tr><tr>
	<th>Package Version</th>
	<td>2.0.0.4</td>
</tr><tr>
	<th>Installer URI</th>
	<td><a href="https://download.asrock.com/Utility/Others/APPShop%28v2.0.0.4%29.zip">https://download.asrock.com/Utility/Others/APPShop%28v2.0.0.4%29.zip</a> from <a href="https://www.asrock.com/feature/appshop/dl.asp">https://www.asrock.com/feature/appshop/dl.asp</a></td>
</tr></table>

**Comment by Dragon1573** [comment]
Really weird ...

```text
10:42:18 D:\...\winget-pkgs  [issues/160709 +1 ~0 -0 !] 48.044s pwsh> sudo winget install -m .\manifests\a\ASRock\AppShop\2.0.0.4\
已找到 APP Shop [ASRock.AppShop] 版本 2.0.0.4
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://download.asrock.com/Utility/Others/APPShop(v2.0.0.4).zip
  ██████████████████████████████  4.26 MB / 4.26 MB
已成功验证安装程序哈希
正在提取存档...
已成功提取存档
正在启动程序包安装...
已成功安装
```

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/a88f8cc1-6c7f-4d48-b0a4-4af2ef6af2f5) ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/3bd0b6a9-d685-44d0-8dd2-82e52e25f31a)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/160709#issuecomment-2198413118

@Dragon1573, are you using an ASRock motherboard? I've not had that error, but I am using one.

**Comment by Dragon1573** [comment]
> @Dragon1573, are you using an ASRock motherboard?

Nope ... None of my device use this motherboard.

Is **ASRock motherboard** required? If it is, the issue should be closed as not planned because it will never pass the validation pipelines hosted on Microsoft Azure.

Issue should be marked with `Blocking-Issue` and `Hardware`.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/160709#issuecomment-2198500963

@Dragon1573, I don't know whether it does. However, this is a quite important vendor firmware updater, so it should probably be considered based upon the fact that the motherboard itself prompts the user to install it the moment that Windows is first configured - it solely being available from their website is going to cause people to accidentally install malware from similar websites higher in Google's search rankings.

**Comment by Dragon1573** [comment]
Do you have any other devices with non-ASRock baseboard? Could you please check if this baseboard is required for running `ASRock.AppShop`?

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/ff6dbe0c-1189-46a3-b970-4bedcdd5a87b)

> [!NOTE]
>
> My device is a laptop bought from [_HUAWEI_](https://www.vmall.com/index.html). Some packages (such as `Huawei.AppGallery` and `Huawei.HuaweiMobileCloud`) are integrated to the initial OS image and support features only available for _HUAWEI_ hardware.
>
> In your situation, it would be better integrate to the OS image than asking users to install themselves. Or, provide the official link directly to users instead of asking users to search themselves.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/160709#issuecomment-2198558234

@Dragon1573, I think you quite severely underestimate what would be bureaucratically necessary to integrate this into Windows, and why that would be wholly undesirable. Irrespective, that shan't occur.

I do have another device with the exact same baseboard, and it indeed installs, but why do you ask - what does that prove?

**Comment by Dragon1573** [comment]
Could you launch _App Shop_ on that non-ASRock baseboard?

I do able to submit a manifest for this package, but I think it will mostly fail during validation.

-----

@stephengillie , this package seems hard depends on a specific hardware (baseboard), how can we dig deeper? :pray:

I created a manifest and validated with `Tools/SandboxTest.ps1`, it can be successfully installed but unable to launch. Should we reject this package?

**Comment by Dragon1573** [comment]
Currently, the PR mentioned above pass the automatic validation. Moderators of this repository will perform manual validation with this package on Azure VMs.

Currently no responses from them. Patience are needed.

**Comment by stephengillie** [comment]
Unfortunately, we're not able to satisfy the hardware requirement.

**Comment by Dragon1573** [comment]
@RokeJulianLockhart, the hardware requirements is proved. I think we can closed this issue as "not planned".

- https://github.com/microsoft/winget-pkgs/issues/160709#issuecomment-2200500590
- https://github.com/microsoft/winget-pkgs/pull/160878#issuecomment-2200499702
