### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#160790]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When I try to install the following packages : 

 WhatsApp.WhatsApp
 Viber.Viber

I am facing issue with the following description : 

Package not found:

### Steps to reproduce

winget install   WhatsApp.WhatsApp Viber.Viber

### Actual behavior

Package not found: WhatsApp.WhatsApp
Package not found: Viber.Viber

### Expected behavior

Installation successfully 

### Environment

```raw
PS C:\Users> winget --info
Windows Package Manager v1.8.1791
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3810
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1791.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
PS C:\Users>
```

**Comment by Trenly** [comment]
Viber is no longer available in winget due to a network blocker which prevents the application from being validated.

* https://github.com/microsoft/winget-pkgs/issues/157344

WhatsApp has also been removed as the publisher now distributes through the Microsoft store (msstore) source.

* https://github.com/microsoft/winget-pkgs/issues/156231


###### Close with reason: Packages were removed intentionally;
