### ISSUE TITLE
[Update Request]: Paperlib

### ISSUE THREAD

**Issue by GeoffreyChen777** [microsoft/winget-pkgs#160768]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

FutureScholars.Paperlib

### Package Version

3.1.5

### Please describe the changes you would like to see

Hi, I'm the developer of this app: `Paperlib`.

I noticed that someone consistently maintains the metadata in winget-pkgs for our updates, thanks for that.

But I noticed that the URL is like:

https://github.com/microsoft/winget-pkgs/blob/c780b5aab58fdc205850a357452026f6d17e69ad/manifests/f/FutureScholars/Paperlib/3.1.5/FutureScholars.Paperlib.installer.yaml#L14

We are going to deprecate this url, and use the new one to replace it `https://distribution.paperlib.app/electron-win/Paperlib_3.1.5.exe`

The new one will be used for future versions.

Could you please update it?

Best wishes.

**Comment by stephengillie** [comment]
Closing as all 3 linked issues are closed. If this is in error, please @ me and I'll reopen.
