### ISSUE TITLE
EpicGames.EpicGamesLauncher error 1602

### ISSUE THREAD

**Issue by danielhits** [microsoft/winget-pkgs#16089]
when upgrading epic games launcher gives this text Installer failed with exit code: 1602

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by Selanda** [comment]
Exit codes 1602 and 1603 are both an MSI installer error. Specifically, 1602 means "the user cancelled the installation" and 1603 indicates a fatal error has occured with the MSI installer package. Getting a 1603 error typically means you've encountered a permissions issue becuase you're attempting to deploy an application that isn't designed to be deployable.
