### ISSUE TITLE
[Update Request]: wrong file link

### ISSUE THREAD

**Issue by exclued** [microsoft/winget-pkgs#161087]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

clsid2.mpc-hc

### Package Version

2.3.2

### Please describe the changes you would like to see

There is a wrong X64 file link in package manifest. Instead of
**https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.x64.exe**
there must be
**https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.1.x64.exe**

**Comment by aisgbnok** [comment]
This can be closed

- Fixed by: https://github.com/microsoft/winget-pkgs/pull/161077

**Comment by mdanish-kh** [comment]
Close with reason: See above;
