### ISSUE TITLE
[Package Issue]: OPAutoClicker.OPAutoClicker confusing "download" command alias

### ISSUE THREAD

**Issue by owowed** [microsoft/winget-pkgs#161295]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Upon installing, winget assigns "download" command line alias for OPAutoClicker, which doesn't make sense for an auto clicker, and can be misinterpreted for something like a download manager program.

### Steps to reproduce

1. Open Windows Terminal.
2. Run `winget install OPAutoClicker.OPAutoClicker`.
3. Run `download`, then OPAutoClicker should open up.

### Actual behavior

OPAutoClicker is assigned with "download" command line alias.

### Expected behavior

I'd suggest removing it, or use something like "opautoclicker".

### Environment

```raw
Windows Package Manager v1.8.1791
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3810
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1791.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![WindowsTerminal_rWxc2gNBhS](https://github.com/microsoft/winget-pkgs/assets/131748527/93e26677-4131-4087-857f-6922522ecdb3)
[WinGet-2024-07-03-17-19-53.490.log](https://github.com/user-attachments/files/16082374/WinGet-2024-07-03-17-19-53.490.log)

**Comment by Dragon1573** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/49941141/21c6b0b0-0f37-48d0-81fa-95920f8b7131)

We can add `Installers.[*].Commands` for this package. If we leave this property unset, `winget.exe` will parse it's name from `InstallerUrl`, and get `download` as it's command name.
