### ISSUE TITLE
[Update Request]: Clash Verge

### ISSUE THREAD

**Issue by Hechao404** [microsoft/winget-pkgs#161385]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MystiPanda.ClashVerge

### Package Version

1.7.2

### Please describe the changes you would like to see

There is a new release (1.7.2) available.Download Page Url:https://github.com/clash-verge-rev/clash-verge-rev/releases

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> According to [the publisher](https://github.com/MystiPanda) of this package, `PackageIdentifier` of this package should be changed to `ClashVergeRev.ClashVergeRev`.
>
> This also affect 3 outdated versions, so moderators may take longer time to review these changes.
>
> See https://github.com/clash-verge-rev/clash-verge-rev/pull/1326#discussion_r1665558798 for more details.
