### ISSUE TITLE
[Package Request]: tsukinaha

### ISSUE THREAD

**Issue by Hechao404** [microsoft/winget-pkgs#161389]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://github.com/tsukinaha/tsukimi/releases
Publisher:tsukinaha
Package Name:TsukimiSetup.exe
Description:一个简单的第三方 Emby 客户端。使用 GTK4-RS 编写的第三方 Emby 客户端
Package Version:v0.6.6
Installer URL:https://github.com/tsukinaha/tsukimi/releases/download/v0.6.6/TsukimiSetup.exe

**Comment by DuckDuckStudio** [comment]
此包似乎无法静默安装，该如何进行静默安装？（这是必须的）

**Comment by DuckDuckStudio** [comment]
#161423

**Comment by Trenly** [comment]
Close with reason: Resolved by PR 161423;

* #161423
