### ISSUE TITLE
[Update Request]: Joplin

### ISSUE THREAD

**Issue by shyun3** [microsoft/winget-pkgs#161427]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Joplin.Joplin

### Package Version

3.0.12

### Please describe the changes you would like to see

There is a new release (3.0.12) available. Download Page Url: https://github.com/laurent22/joplin/releases

**Comment by aisgbnok** [comment]
Resolved by:
- https://github.com/microsoft/winget-pkgs/pull/161178

**Comment by DuckDuckStudio** [comment]
#163332
