### ISSUE TITLE
Camtasia Outdated

### ISSUE THREAD

**Issue by UsefulVid** [microsoft/winget-pkgs#16146]
Camtasia version outdated
C:\Users\Admin>winget search camtasia
Name     ID                 Version
Camtasia TechSmith.Camtasia 2020.0.8

Camtasias newest version is **2021**.0.3
https://support.techsmith.com/hc/en-us/articles/115006443267-Camtasia-Windows-Version-History

**Comment by tiziodcaio** [comment]
Now I will upgrade

**Comment by tiziodcaio** [comment]
see #16154

**Comment by UsefulVid** [comment]
Is this the right way to report outdated versions?

**Comment by tiziodcaio** [comment]
No, but I think that the mods will be able to change the tags
Anyway, when the pull will be merged, can you close the issue please?

**Comment by UsefulVid** [comment]
Yes of course :) Can you tell me how to report outdated versions?

**Comment by tiziodcaio** [comment]
Try using Microsoft/winget-create

**Comment by KaranKad** [comment]
You can report outdated versions here, by creating an issue and https://github.com/microsoft/winget-create is a tool which you can use to submit new application or update  existing the application yourself.
