### ISSUE TITLE
[Update Request]: MPC-HC v2.3.2

### ISSUE THREAD

**Issue by crisp5** [microsoft/winget-pkgs#161546]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

clsid2.mpc-hc

### Package Version

2.3.2

### Please describe the changes you would like to see

MPC-HC x64 64-bit installer for version 2.3.2 should point to:
https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.1.x64.exe

It currently points to:
https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.x64.exe

x86 URL should remain the same.

**Comment by elisimpson** [comment]
Dup of:
https://github.com/microsoft/winget-pkgs/issues/161087
https://github.com/microsoft/winget-pkgs/pull/161111

**Comment by ItzLevvie** [comment]
Close with reason: Duplicate;
