### ISSUE TITLE
Microsoft Teams won't update

### ISSUE THREAD

**Issue by arteeh** [microsoft/winget-pkgs#16155]
# Brief description of your issue
When I ran `winget upgrade --all` with Microsoft Teams installed, it failed to update. It looks like the Teams installer doesn't work as an updater when Teams is already installed.

# Steps to reproduce

- Have a non-latest version of Microsoft Teams installed. As of writing, for me that's 1.4.00.11161.
- Run `winget upgrade Microsoft.Teams` or `winget upgrade --all`

# Expected behavior

Teams runs its installer of the latest version without errors, after which the latest version is installed and working.

# Actual behavior

The installer downloads, starts, then exits with the following output: `Installer failed with exit code: 1638`.

The following installer log is written:

```none
MSI (s) (90:E0) [09:38:04:808]: Product: Teams Machine-Wide Installer -- Configuration failed.

MSI (s) (90:E0) [09:38:04:808]: Windows Installer reconfigured the product. Product Name: Teams Machine-Wide Installer. Product Version: 1.4.0.11161. Product Language: 1033. Manufacturer: Microsoft Corporation. Reconfiguration success or error status: 1638.

Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.
{731F6BAA-A986-45A4-8936-7C3AAAAA760B}
```

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Microsoft Teams Version 1.4.00.11161
```

**Comment by paulius-valiunas** [comment]
this was NOT fixed in that PR. I still have a bunch of duplicate packages that fail to update
