### ISSUE TITLE
[Package Issue]: notepad2 is not actually notepad2

### ISSUE THREAD

**Issue by Wallby** [microsoft/winget-pkgs#161688]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The package with name "Notepad2" seems to actually be a program called Notepad4.

Notepad2.. https://www.flos-freeware.ch/notepad2.html
Notepad4.. https://github.com/zufuliu/notepad4

The provided URL in notepad4 is..
```
Publisher Url: https://github.com/zufuliu/notepad2
Publisher Support Url: https://github.com/zufuliu/notepad2
```
.. which redirects to https://github.com/zufuliu/notepad4

### Steps to reproduce

\-

### Actual behavior

\-

### Expected behavior

Rename the name of this package to Notepad4 to be accurate.

### Environment

```raw
Not related to winget as this is in this repository.. https://github.com/microsoft/winget-pkgs/tree/master/manifests/z/zufuliu/notepad2
```

**Comment by Dragon1573** [comment]
Do you mean `zufuliu.notepad2`? Should it be renamed to `zufuliu.notepad4`?

**Comment by Wallby** [comment]
Right now if you type `winget install --Name Notepad2` it installs Notepad4, which is wrong.

**Comment by Wallby** [comment]
I saw that notepad2 was also added, which wasn't part of my suggested solution.
As a heads up, I believe the notepad2 installer asks to replace notepad with it. I am not sure if silent install would automatically thus replace notepad with notepad2 without alerting the user.
