### ISSUE TITLE
[Update Request]: gaubert/gmvault improperly detects v1.9.1 as v1.5-beta

### ISSUE THREAD

**Issue by ntman1** [microsoft/winget-pkgs#161768]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

gaubert/gmvault

### Package Version

1.9.1

### Please describe the changes you would like to see

The version of gaubert/gmvault located at https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/gaubert/gmvault fails to detect either manual or WinGet versions of gmvault v1.9.1 as being gmvault v1.9.1, and misidentifies the gmvault v1.9.1 installation as gmvault v1.5-beta (aka Installed Version:  1.5-beta - Update to 1.9.1 available) I am assuming based upon the manifest that it is installing the current package from https://bitbucket.org/gaubert/gmvault-official-download/downloads/gmvault_installer_v1.9.1.exe

**Comment by Dragon1573** [comment]
Successfully reproduced in `x64` _Windows Sandbox_ instance.

<details><summary>Console Logs</summary>

```text
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -e gaubert.gmvault --version 1.9.1
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y
Found Gmvault [gaubert.gmvault] Version 1.9.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://bitbucket.org/gaubert/gmvault-official-download/downloads/gmvault_installer_v1.9.1.exe
  ██████████████████████████████  4.47 MB / 4.47 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
Name           Id              Version       Available     Source
-----------------------------------------------------------------
Microsoft Edge Microsoft.Edge  100.0.1185.36 126.0.2592.87 winget
Gmvault        gaubert.gmvault 1.5-beta      1.9.1         winget
2 upgrades available.
```

</details>

I think it's not `winget.exe`'s fault, since the package installer writes `1.5-beta` to _Windows Registry_. It can be found in Settings Panel.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/664b2d52-dc22-4c61-ba35-6d1ebeee7413)

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> This package is currently "stale as archived". The latest commit related to this package is at branch [`dev-throttle`](https://github.com/gaubert/gmvault/tree/dev-throttle) 10 month ago.
>
> ![image](https://github.com/microsoft/winget-pkgs/assets/49941141/b1e91edc-5d5f-4c40-8cc4-c33afc2b5468)

> [!NOTE]
>
> The issue you report here is a known issue for them, created almost 7.5 years ago.
>
> - See gaubert/gmvault#307

**Comment by Dragon1573** [comment]
@stephengillie - Should this issue be labeled with https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Upgrade-Issue and close as "not planned"?

**Comment by stephengillie** [comment]
This bug doesn't seem to be a high priority for this developer.
