### ISSUE TITLE
[Update Request]: Python 3.10.11 to 3.10.14

### ISSUE THREAD

**Issue by MagicCarpetRider** [microsoft/winget-pkgs#161886]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Python.Python.3.10

### Package Version

3.10.14

### Please describe the changes you would like to see

There is a new release (3.10.14) available. Download Page Url: https://www.python.org/downloads/release/python-31014/

**Comment by aisgbnok** [comment]
> #### No installers
> According to the release calendar specified in <a href="https://www.python.org/dev/peps/pep-0619/">PEP 619</a>, Python 3.10 is now in the "security fixes only" stage of its life cycle: 3.10 branch only accepts security fixes and releases of those are made irregularly in source-only form until October 2026. Python 3.10 isn't receiving regular bug fixes anymore, and binary installers are no longer provided for it. <strong>Python 3.10.11</strong> was the last full <em>bugfix release</em> of Python 3.10 with binary installers.

https://www.python.org/downloads/release/python-31014/

It seems binary installers are no longer provided for that version of Python. Therefore, I don't believe it's practical to add that version to Winget. Sorry.

**Comment by MagicCarpetRider** [comment]
Thank you, I appreciate your time reviewing.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This issue should be closed as "not planned".
>
> **Policy**: https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Installer-Issue

**Comment by mdanish-kh** [comment]
Close with reason: Installers are not available for the requested version, issue is external to winget;
