### ISSUE TITLE
[Package Request]:  Add muandane/goji to winget

### ISSUE THREAD

**Issue by muandane** [microsoft/winget-pkgs#161966]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/muandane/goji/releases/tag/v0.1.1
Publisher: muandane
Package Name: goji
Description: "Commitizen-like Emoji Commit Tool written in Go"
Package Version: v0.1.1
Installer URL: https://github.com/muandane/goji/releases/download/v0.1.1/goji_v0.1.1_Windows_x86_64.zip

**Comment by Utesgui** [comment]
@muandane Issue can be closed i guess :)
