### ISSUE TITLE
[Package Request]: Add LiveKit CLI to winget

### ISSUE THREAD

**Issue by rektdeckard** [microsoft/winget-pkgs#162010]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/livekit/livekit-cli/releases
Publisher: LiveKit
Package Name: LiveKitCLI
Description: Command line interface to LiveKit
Package Version: 2.0.3
Installer URL: https://github.com/livekit/livekit-cli/releases/download/v2.0.3/lk_2.0.3_windows_amd64.zip

**Comment by Utesgui** [comment]
@rektdeckard issue solved :)
