### ISSUE TITLE
Upgrade showing in upgrade list but actually no upgrade found

### ISSUE THREAD

**Issue by albertopasqualetto** [microsoft/winget-pkgs#16213]
# Brief description of your issue

Upgrade showing in upgrade list but actually no upgrade found
# Steps to reproduce

```
winget upgrade
```
It shows a list
then try to upgrade one of them and no upgrade is found for some of them

![image](https://user-images.githubusercontent.com/39854348/120823283-935b6880-c557-11eb-9d22-5f3db6ecd64b.png)

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by denelon** [comment]
@albertopasqualetto the *experimental* store source does not provide the version for an available package. There is currently no way for the Windows Package Manager to know whether the package in the store is an upgrade or not.

**Comment by albertopasqualetto** [comment]
Ok, thanks, but it behaves the same with all the apps in that list, for example Discord.

**Comment by denelon** [comment]
Yes, there are some improvements we need to make in the schema so we can have a better experience with upgrade. There are plenty of gaps between what Apps report in Add / Remove Programs and what we currently have in package manifests. I think if you search for "Discord" in the repository, you will see several users with similar problems and some work in progress to try and provide a work around until the schema changes are in place.

**Comment by albertopasqualetto** [comment]
Ok, i got it, thanks for your support.

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your issue still persists. 

Additional Notes:  The `msstore` source still does not provide the version for an available package. This is a known issue and potential solutions are still being evaluated.

###### Close with reason: Stale;
