### ISSUE TITLE
[Update Request]: TrustedQSL

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#162370]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TrustedQSL.TrustedQSL

### Package Version

2.7.3

### Please describe the changes you would like to see

There is a new release (2.7.3) available. Download Page Url: https://www.arrl.org/tqsl-download (https://www.arrl.org/files/file/LoTW%20Instructions/tqsl-2.7.3.msi)

**Comment by stephengillie** [comment]
This might already exist, as `AmericanRadioRelayLeague.TrustedQSL`.

https://github.com/microsoft/winget-pkgs/pull/162503#issuecomment-2223377607

**Comment by Trenly** [comment]
Close with reason: Package already exists;
