### ISSUE TITLE
[Update Request]: PulseView (Nightly)

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#162354]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Sigrok.PulseView

### Package Version

nightly

### Please describe the changes you would like to see

The old installer got removed. Here is the new one: https://sigrok.org/download/binary/pulseview/pulseview-NIGHTLY-x86_64-release-installer.exe

**Comment by vikingnope** [comment]
Fixing this
