### ISSUE TITLE
[Update Request]: radioconda

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#162364]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ryanvolz.radioconda

### Package Version

2024.05.29

### Please describe the changes you would like to see

There is a new release (2024.05.29) available. Download Page Url: https://github.com/ryanvolz/radioconda/releases/tag/2024.05.29 (https://github.com/ryanvolz/radioconda/releases/download/2024.05.29/radioconda-2024.05.29-Windows-x86_64.exe)

**Comment by Utesgui** [comment]
https://github.com/microsoft/winget-pkgs/pull/159064

**Comment by stephengillie** [comment]
> #159064

This package exceeds the maximum RAM that I can give a VM for manual validation. During the scan phase, when all new EXEs are run at the same time, and a Defender scan performed. So unfortunately I cannot manually complete this PR.

**Comment by Trenly** [comment]
Close with reason: Resolved by PR 159064;

* #159064
