### ISSUE TITLE
[Update Request]: Microsoft.AzureCLI 2.62.0

### ISSUE THREAD

**Issue by dbaileyut** [microsoft/winget-pkgs#162416]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.AzureCLI

### Package Version

2.62.0

### Please describe the changes you would like to see

There's a new version available (2.62.0). See https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

**Comment by Utesgui** [comment]
https://github.com/microsoft/winget-pkgs/pull/162494

**Comment by stephengillie** [comment]
> #162494
