### ISSUE TITLE
[Package Request]: BC3Technologies FileSorter

### ISSUE THREAD

**Issue by bc3tech** [microsoft/winget-pkgs#162878]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/bc3tech/FileSorter/releases/download/0.2.70/Filesorter_0.2.70.zip
Publisher: BC3Technologies
Package Name: FileSorter
Description: Sorts files into datetime subfolders, optionally parsing EXIF data of photos to get accurate date/time information.
Package Version: 0.2.70
Installer URL: https://github.com/bc3tech/FileSorter/releases/download/0.2.70/Filesorter_0.2.70.zip

**Comment by Trenly** [comment]
[Policy] Zip Binary
