### ISSUE TITLE
League of Legends fails to detect version (installed with winget or not)

### ISSUE THREAD

**Issue by andyliuhaowen** [microsoft/winget-pkgs#16287]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

# Steps to reproduce
```
winget install RiotGames.LeagueOfLegends
winget list
```

# Expected behavior

`winget list` will print

```
League of Legends               RiotGames.LeagueOfLegends                     30.0.1.3715678
```

# Actual behavior

`winget list` prints

```
League of Legends               RiotGames.LeagueOfLegends                                Unknown             30.0.1.371… winget
```

This also causes `winget upgrade --all` to try to upgrade League every time.

# Environment

```none
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

```

**Comment by iDolmatov** [comment]
Winget get version number from Windows Control Panel (Settings - installed app list). 
Game developer should be add info.

This is known issue. Try find similar issue, include https://github.com/microsoft/winget-cli

**Comment by andyliuhaowen** [comment]
I see. I'll report this to Riot Games. But in the mean time, is there a way blacklist apps for `winget upgrade --all`?

**Comment by andyliuhaowen** [comment]
Got it. Thank you so much!
