### ISSUE TITLE
[Package Issue]: SlackTechnologies.Slack

### ISSUE THREAD

**Issue by jay-babu** [microsoft/winget-pkgs#162931]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Slack has an arm version https://slack.com/downloads/instructions/windows?ddl=1&build=arm64 but the winget package only specifies an x86 version. https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/SlackTechnologies/Slack/4.39.90/SlackTechnologies.Slack.installer.yaml

I am happy to contribute if I could get pointed in the right direction.

### Steps to reproduce

N/A

### Actual behavior

Installing x86

### Expected behavior

Arm version installed

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.863
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by mdanish-kh** [comment]
> I am happy to contribute if I could get pointed in the right direction.

Feel free to submit a pull request to update the [latest Slack's manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/SlackTechnologies/Slack/4.39.90/SlackTechnologies.Slack.installer.yaml). You can add an `arm64` installer under the `Installers:` node. The installer seems to be `msix` so you'll need to specify `InstallerType: msix`

You may want to familiarize yourself with the [Contribution process](https://github.com/microsoft/winget-pkgs?tab=readme-ov-file#documentation). There's also an Open at Microsoft episode covering

**Comment by arafelp** [comment]
Hello there is any way to add slack machine wide to winget? slack has this version https://slack.com/help/articles/212475728-Deploy-Slack-via-Microsoft-Installer#msi-for-machine-wide-installation

**Comment by mdanish-kh** [comment]
@arafelp Machine-wide installer is available in the [latest manifest](https://github.com/microsoft/winget-pkgs/blob/75c7bafe11ec1dba84e4413e7b9909d2a78bc6de/manifests/s/SlackTechnologies/Slack/4.39.95/SlackTechnologies.Slack.installer.yaml#L20-L29). You can install it using `winget install SlackTechnologies.Slack --scope machine` (winget defaults to user scope install if --scope parameter is not specified)

**Comment by arafelp** [comment]
Thank you!!!
