### ISSUE TITLE
[Update Request]: ShiningLight.OpenSSL

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#163088]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ShiningLight.OpenSSL

### Package Version

3.2.1+

### Please describe the changes you would like to see

- To replace https://github.com/microsoft/winget-pkgs/pull/162989
If the developer has stopped hosting this application, please state this in the comments.

**Comment by Dragon1573** [comment]
![image](https://github.com/user-attachments/assets/2359d297-da88-4cb4-8167-2af651058ef0)

It seems version 3.2.1 is not available any more. The current latest version of `v3.2.x` series is `v3.2.2`, and the latest version over all is `v3.3.1`.
