### ISSUE TITLE
[Update Request]: SaltStack.SaltMinion

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#163087]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SaltStack.SaltMinion

### Package Version

30.07.0+

### Please describe the changes you would like to see

- To replace https://github.com/microsoft/winget-pkgs/pull/163002

If the developer has stopped hosting this application, please state this in the comments.

**Comment by Trenly** [comment]
Close with reason: Resolved;
