### ISSUE TITLE
[Update Request]: Oracle JDK 22.0.2

### ISSUE THREAD

**Issue by Umoxfo** [microsoft/winget-pkgs#163477]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Oracle.JDK.22

### Package Version

22.0.2.0

### Please describe the changes you would like to see

There is a new release (22.0.2) available.
Download Page: https://www.oracle.com/java/technologies/downloads/#jdk22-windows

**Comment by Utesgui** [comment]
https://github.com/microsoft/winget-pkgs/pull/163301

**Comment by DuckDuckStudio** [comment]
- #163332

**Comment by Trenly** [comment]
* Close with reason: Resolved; by #163301
