### ISSUE TITLE
[Package Issue]: Some versions of the 115.115 url return 404.

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#163641]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Some download link returned 404 in [my automation](https://github.com/DuckDuckStudio/winget-tools) and was not directly accessible.

### Steps to reproduce

Use winget to install these versions.

### Actual behavior

Return 404

### Expected behavior

Normal program installation

### Environment

```raw
Windows 程序包管理器 v1.8.1911
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22631.3880
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Packages
可移植包根目录         C:\Program Files\WinGet\Packages
可移植包根目录 (x86)   C:\Program Files (x86)\WinGet\Packages
安装程序下载           %USERPROFILE%\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已启用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已禁用
ProxyCommandLineOptions                   已禁用
DefaultProxy                              已禁用
```

### Screenshots and Logs

My automation output:
[output.log](https://github.com/user-attachments/files/16286277/output.log)

**Comment by DuckDuckStudio** [comment]
- [x] It has been confirmed that all relevant pull requests have been mentioned.

**Comment by SpecterShell** [comment]
The desktop client (`115.115`) has been deprecated by the publisher in favor of the browser one (`115.115Chrome`) recently, and all the installers on the server appear to have been removed.

**Comment by DuckDuckStudio** [comment]
All related pull requests have been merged.
