### ISSUE TITLE
[Package Request]: difftastic

### ISSUE THREAD

**Issue by lloydjatkinson** [microsoft/winget-pkgs#163714]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Wilfred/difftastic/releases
Publisher: 
Package Name: difftastic
Description: A structural diff that understands syntax
Package Version: 0.58.0
Installer URL: https://github.com/Wilfred/difftastic/releases

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This package is already available in `winget` source.
>
> ```text
> 14:14:46 D:\...\winget-pkgs  [issues/163714] 192ms pwsh> komac new --output .
> > Package identifier: Wilfred.difftastic
> Latest version of Wilfred.difftastic: 0.57.0
> ```
