### ISSUE TITLE
[Update Request]: Samsung Magician

### ISSUE THREAD

**Issue by kenohassler** [microsoft/winget-pkgs#163966]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Samsung.SamsungMagician

### Package Version

8.1.0

### Please describe the changes you would like to see

The current version of the tool is ages old and doesn't actually work properly anymore. Update to the current release 8.1.0 found on https://semiconductor.samsung.com/consumer-storage/support/tools/.

Deeplink: https://download.semiconductor.samsung.com/resources/software-resources/Samsung_Magician_Installer_Official_8.1.0.800.exe
SHA256: 5F3F8D53B3DD8FA7655366A7C2B4427B8799FA52BC242176C1F67ACFCDB7B2C5

**Comment by Dragon1573** [comment]
### ⚠️ Policy

https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer

- Related #148013

**Comment by kenohassler** [comment]
Thanks for the hint. In this case, I would advise to remove the App altogether, because in the current state, it is completely useless. Not even the self-updater in the old version works 🤷
