### ISSUE TITLE
Nutstore install is not detected

### ISSUE THREAD

**Issue by liuhaowen478** [microsoft/winget-pkgs#16405]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Installed Nutstore is not detected.

# Steps to reproduce

```
winget install Nutstore.Nutstore
winget list
```

# Expected behavior

```
Nutstore                                          Nutstore.Nutstore            5.2.4
```

# Actual behavior

```
Nutstore                                          {DD8D8D7A-337E-4577-8B20-46AAB38CAED4}            5.2.4
```

# Environment

```none
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by OfficialEsco** [comment]
#16410 Should fix this, do you speak Chinese? Would you mind creating a Chinese Locale for it?
```
Chinese - Taiwan / zh-TW
Chinese - People's Republic of China / zh-CN
Chinese - Hong Kong SAR / zh-HK
Chinese - Singapore / zh-SG
Chinese - Macao SAR / zh-MO
```

Nutstore.Nutstore.locale.zh-CN.yaml
```
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json
PackageIdentifier: Nutstore.Nutstore
PackageVersion: 5.2.4
PackageLocale: zh-CN
Publisher: Shanghai YiCun Network Tech Co., Ltd.
PublisherUrl: https://www.jianguoyun.com
PublisherSupportUrl: http://help.jianguoyun.com
PrivacyUrl: http://help.jianguoyun.com/?page_id=3961
Author: Shanghai YiCun Network Tech Co., Ltd.
PackageName: Nutstore
PackageUrl: https://www.jianguoyun.com
License: Proprietary
LicenseUrl: https://help.jianguoyun.com/?page_id=490
Copyright: © 2020 Shanghai YiCun Network Tech Co., Ltd.
CopyrightUrl: https://help.jianguoyun.com/?page_id=490
ShortDescription: Share your files anytime, anywhere, with any device
#Description: 
Tags:
  - cloud
  - storage
  - cloudstorage
  - jianguoyun
  - jgy
ManifestType: locale
ManifestVersion: 1.0.0
```

These most stay the same
```
PackageIdentifier
PackageVersion
Publisher
PackageName
```

**Comment by liuhaowen478** [comment]
Yes I'm glad to help. But I'm not sure what I need to change. Could you point me somewhere, like documentation on this?

Do I just update update the name to Chinese and the link to point to a Chinese download?

**Comment by liuhaowen478** [comment]
How does this look?

```
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json
PackageIdentifier: Nutstore.Nutstore
PackageVersion: 5.2.4
PackageLocale: zh-CN
Publisher: 上海亦存网络科技有限公司
PublisherUrl: https://www.jianguoyun.com
PublisherSupportUrl: http://help.jianguoyun.com
PrivacyUrl: http://help.jianguoyun.com/?page_id=3961
Author: 上海亦存网络科技有限公司
PackageName: 坚果云
PackageUrl: https://www.jianguoyun.com
License: Proprietary
LicenseUrl: https://help.jianguoyun.com/?page_id=490
Copyright: © 2020 上海亦存网络科技有限公司
CopyrightUrl: https://help.jianguoyun.com/?page_id=490
ShortDescription: Share your files anytime, anywhere, with any device
#Description: 
Tags:
  - cloud
  - storage
  - cloudstorage
  - jianguoyun
  - jgy
ManifestType: locale
ManifestVersion: 1.0.0
```

**Comment by OfficialEsco** [comment]
> Yes I'm glad to help. But I'm not sure what I need to change. Could you point me somewhere, like documentation on this?
> 
> Do I just update update the name to Chinese and the link to point to a Chinese download?

Hmm, as far as i know there is no straight documentation on locales, https://aka.ms/winget-manifest.locale.1.0.0.schema.json this is the schema link to the metadata that can be in the language locale.

If there is a specific link to the Chinese Installer it can be added in the installer manifest like this:

```
Installers:
  - InstallerLocale: zh-CN
    Architecture: x64
    InstallerType: exe
    InstallerUrl: https://www.jianguoyun.com/static/exe/installer/NutstoreWindowsWPFInstaller.exe
    InstallerSha256: 1D47A0F46A9B48E5CE595C392DAD2DAA0D41FF195F07E1EC5A14C8D55CA3F46A
    InstallerSwitches:
      Custom: /exenoui
      Silent: " "
      SilentWithProgress: " "
    ProductCode: "{DD8D8D7A-337E-4577-8B20-46AAB38CAED4}"
    Scope: machine
    UpgradeBehavior: install
```

The Nutstore.Nutstore.locale.zh-CN.yaml metadata will be used in WinGet if the user have selected zh-CN as their preferred locale.

So if the Chinese Installer have a different Publisher in Windows that will help to match the program to WinGet, or if the site have a version of the website that is only in Chinese then the `PublisherUrl`, `PublisherSupportUrl`, `PrivacyUrl`, `PackageUrl`, `LicenseUrl` and `CopyrightUrl` should point to the Chinese version of the Website.

The `Author`, `License`, `ShortDescription` and `Description` can be written in Chinese so only Chinese speaking people can search and understand what it means/does.

Tags can be in Chinese so its easier to find for Chinese people or if they have other words for it.
