### ISSUE TITLE
Duplicate Nutstore and Jianguoyun

### ISSUE THREAD

**Issue by liuhaowen478** [microsoft/winget-pkgs#16404]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Jianguoyun.Jianguoyun and Nutstore.Nutstore is the same application.

According to [official website](https://www.jianguoyun.com/s/downloads), Jianguoyun.Jianguoyun is the Win7 version of the software (4.3.7) and Nutstore.Nutstore has the correct and up to date Win10 version.

![image](https://user-images.githubusercontent.com/54611228/120932243-daf20980-c6a9-11eb-955b-01fbdaa6b27a.png)

Given that Win7 is irrelavent to winget anyway, I argue we should remove Jianguoyun.Jianguoyun.

**Comment by tiziodcaio** [comment]
Fixed
