### ISSUE TITLE
[Update Request]: Spacemesh.Spacemesh

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#164151]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Spacemesh.Spacemesh

### Package Version

0.2.6+

### Please describe the changes you would like to see

- Reference: https://github.com/microsoft/winget-pkgs/pull/164053

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue should be closed as "completed", since #164212 resolve this.

**Comment by DuckDuckStudio** [comment]
#163332

**Comment by Trenly** [comment]
* Close with reason: Resolved; by #164212
