### ISSUE TITLE
[Update Request]: gnuplot.gnuplot v6.0.1

### ISSUE THREAD

**Issue by JakeOShannessy** [microsoft/winget-pkgs#164131]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

gnuplot.gnuplot

### Package Version

6.0.1

### Please describe the changes you would like to see

There is a new release for gnuplot available at https://sourceforge.net/projects/gnuplot/files/gnuplot/6.0.1/gp601-win64-mingw.exe/download. This is the from the same origin as the current installer (v5.4.8).

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue should be closed as "completed", since it is resolved by #164141

**Comment by DuckDuckStudio** [comment]
#163332
