### ISSUE TITLE
[Package Request]: DGP-Studio.Snap.Hutao

### ISSUE THREAD

**Issue by Luna-Grace** [microsoft/winget-pkgs#164178]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/DGP-Studio/Snap.Hutao/releases
Publisher: DGP-Studio
Package Name: Snap.Hutao (胡桃工具箱)
Description: 实用的开源多功能原神工具箱 🧰 / Multifunctional Open-source Genshin Impact Toolkit 🧰
Package Version: 1.10.7
Installer URL: https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.10.7/Snap.Hutao.1.10.7.msix

**Comment by Dragon1573** [comment]
[Policy] Blocking-Issue, Area-External
