### ISSUE TITLE
Error: Unable to write to C:/... IT policies may be restricting access to this folder

### ISSUE THREAD

**Issue by Juknum** [microsoft/winget-pkgs#16415]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Each time I make `winget upgrade --all`, when the download ends, I get a window error saying: **Installation has failed: Unable to write to C:\ProgramData\julie IT policies may be restricting access to this folder**
![image](https://user-images.githubusercontent.com/49886317/120936613-fd673f80-c708-11eb-8aa4-491ad616a043.png)

The worse there is that winget is telling me that the upgrade succeed but in facts, it doesn't:
![image](https://user-images.githubusercontent.com/49886317/120936561-be38ee80-c708-11eb-937d-c133f858cacb.png)
Winget is writting that the software has been "correctly installed" (Installé Correctement in the screenshot) but they still show up when doing `winget upgrade`:
![image](https://user-images.githubusercontent.com/49886317/120936678-5afb8c00-c709-11eb-80d4-1a90beacaae9.png)

# Steps to reproduce

1. Open a command prompt as Administrator (the default one from Windows 10)
2. Type `winget upgrade --all`
3. See the errors window everywhere
4. Make `winget upgrade` and see that nothing has been updated

# Expected behavior

A working command or a way to disabled IT policies?

# Actual behavior

Already explained in the description

# Environment

```none
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```
Can I ask what do you expect by _any other software?_ ? Like anything related to winget? Then no.

**Comment by jedieaston** [comment]
Can you open this issue in microsoft/winget-cli? This repo is for the packages in the repo, not the client itself.

**Comment by Juknum** [comment]
oops my bad, you can close this issue
