### ISSUE TITLE
[Update Request]: Packege updated request

### ISSUE THREAD

**Issue by Thulasi225** [microsoft/winget-pkgs#164213]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

Microsoft widget

### Package Version

1.2.5.0

### Please describe the changes you would like to see

New Version (1.2.5.0)

**Comment by stephengillie** [comment]
Hi @Thulasi225,

Is this a request to have the package manager be able to enable Microsoft Widgets? This request might be a better fit for DSC, as it's apparently enabling a Windows feature, not installing a software package.
