### ISSUE TITLE
[Update Request]: DuckStudio.ChineseGit version 2.9 not a Pre-release version

### ISSUE THREAD

**Issue by Luna-Grace** [microsoft/winget-pkgs#164966]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

DuckStudio.ChineseGit

### Package Version

2.9

### Please describe the changes you would like to see

Remove tag `- pre-release`

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/pull/164755

**Comment by stephengillie** [comment]
> * [Update manifest: DuckStudio.ChineseGit version 2.9 #164755](https://github.com/microsoft/winget-pkgs/pull/164755)
