### ISSUE TITLE
WeChat install not detected

### ISSUE THREAD

**Issue by liuhaowen478** [microsoft/winget-pkgs#16490]
# Brief description of your issue

WeChat install not detected

# Steps to reproduce

```
winget install Tencent.WeChat
winget list
```

# Expected behavior

```
WeChat                                   Tencent.WeChat                                    3.2.1.154
```

# Actual behavior

```
WeChat                                   WeChat                                    3.2.1.154
```

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by lychichem** [comment]
This is another situation of #16011

**Comment by OfficialEsco** [comment]
@lychichem Its fine, most of these Issues comes from the Publisher not being correct, in this case it had to be Chinese characters o_O
We can also close these Issues by commiting a PR so there is no spam. And if there is one that cannot be fixed there is a PR for that specific case :)
