### ISSUE TITLE
[Package Issue]: `SlackTechnologies.Slack`

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/winget-pkgs#164940]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Updating Slack with Winget always reenables the auto-start feature, despite it being disabled in its preferences.

### Steps to reproduce

Disable auto-start of Slack in Task Manager, then update `SlackTechnologies.Slack`.

### Actual behavior

Described above.

### Expected behavior

According to [Slack's documentation](https://slack.com/help/articles/212475728-Deploy-Slack-via-Microsoft-Installer), auto-start requires explicit enabling on the command line. As such, this should not occur.

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.1150
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by stephengillie** [comment]
Unless the explicit enabling switches were added to the manifest, this seems like it might be an issue with the package's installer, which would be the developer's responsibility to fix. 
- Does this happen when installing through other means, such as downloading the MSI and running it directly?

**Comment by colejohnson66** [comment]
Running the x64 MSI listed in the manifest directly does not enable auto-start.

**Comment by colejohnson66** [comment]
I commented that the MSI does not enable auto-start, but no one responded.

**Comment by s0racat** [comment]
Why was this issue closed?

**Comment by s0racat** [comment]
It would be good to add RequireExplicitUpgrade: true to the manifest.
