### ISSUE TITLE
[Remove Package]: 0x192.UniversalAndroidDebloaterGUI 

### ISSUE THREAD

**Issue by Magniquick** [microsoft/winget-pkgs#165043]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

``0x192.UniversalAndroidDebloaterGUI`` matches ``Command: adb``.
However, running adb fork-bombs the system with adb instances on the latest windows 11 and makes the system unusable.
also the (repo)[https://github.com/0x192/universal-android-debloater] hasn't been updated for about a year

### Steps to reproduce

winget install "Universal Android Debloater GUI"
adb.exe

### Actual behavior

System crashes due to OOM

### Expected behavior

System to not crash.

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3880
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Enabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

running adb --verbose produces no output.

**Comment by Magniquick** [comment]
> Does your system have Android Platform Tools installed? 

I do not - it (seems to) come bundled with the package - henceforth why it lists ``Command: adb`` in the matches section, I assumed.
Do correct me if I am wrong though.
> Google.PlatformTools

Unrelated, but that is broken too due to #151482 

> [UAD-ng](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation)

My purpose was to somehow get adb working via winget, so I don't really have an opinion on that.

**Comment by drshtmstry** [comment]
> My purpose was to somehow get adb working via winget, so I don't really have an opinion on that.

Use `winget install Google.PlatformTools`.
