### ISSUE TITLE
@ChristianGalla the PR created by the action already does that.

### ISSUE THREAD

**Issue by ClintonOffor** [microsoft/winget-pkgs#165011]
@ChristianGalla the PR created by the action already does that.

PR created from the last workflow run on your project's repo: https://github.com/microsoft/winget-pkgs/pull/110332/files already has an ARP containing `DisplayVersion`. 

_Originally posted by @vedantmgoyal9 in https://github.com/vedantmgoyal9/winget-releaser/issues/174#issuecomment-1657079724_
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/165012
```

**Comment by Trenly** [comment]
I'm not sure what this issue is asking. Please use the issue tenplates when creating a new issue, or ensure your problem is clearly stated
