### ISSUE TITLE
[New Feature]: Scripted Package Installs

### ISSUE THREAD

**Issue by amber-m-mvd** [microsoft/winget-pkgs#165037]
### Description of the new feature/enhancement

Scripted package installs would solve a lot of issues with the current state of the winget package manager. It would allow more than just running EXEs and MSI files and then leaving it. It would allow a more configurable installation of certain apps. An issue that would benefit from this feature would be #163711. It currently cannot be pulled into the repository due to the fact that the MSI file inside the EXE installer cannot be extracted. With the introduction of this feature, it would allow a dependency like the command line version of 7-Zip (7z.exe) to be used to extract the MSI file and install the app.

### Proposed technical implementation details (optional)

I am suggesting a GitHub Actions approach to the scripted installation. For more features and security, I suggest using PowerShell only and not adding Batch/CMD to the supported environments.

**Comment by Trenly** [comment]
[Policy] Scripted Application

**Comment by Trenly** [comment]
Scripted applications are against the security policies of WinGet (and Microsoft in general)

This is explicitly stated in the [original devblog](There are a number of qualities in AppGet that really helped us get to a better product direction for WinGet:

No scripts during install – something that we completely agreed with and don’t allow with MSIX) -
> No scripts during install – something that we completely agreed with and don’t allow with MSIX

More information can be found in the [Policies](https://github.com/microsoft/winget-pkgs/blob/master/doc/Policies.md#installer-types). Additional reference issues -
* https://github.com/microsoft/winget-pkgs/pull/131091
* https://github.com/microsoft/winget-cli/discussions/2940
