### ISSUE TITLE
[Package Request]: AlgoKit

### ISSUE THREAD

**Issue by neilcampbell** [microsoft/winget-pkgs#165104]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/algorandfoundation/algokit-cli/releases
Publisher: Algorand Foundation
Package Name: AlgoKit
Description: The Algorand AlgoKit CLI is the one-stop shop tool for developers building on the Algorand network.
Package Version: 2.2.2
Installer URL: https://github.com/algorandfoundation/algokit-cli/releases/download/v2.2.2/algokit-2.2.2-windows_x64-winget.msix

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Should be closed as "completed", since #165113 is merged.

**Comment by neilcampbell** [comment]
Sure is.
