### ISSUE TITLE
Microsoft.PIX installer locations are moving, need to update WinGet accordingly

### ISSUE THREAD

**Issue by austinkinross** [microsoft/winget-pkgs#165137]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I'm the PIX dev lead. We need to move the installer locations, and update WinGet accordingly

### Steps to reproduce

N/A

### Actual behavior

N/A

### Expected behavior

N/A

### Environment

```raw
N/A
```

### Screenshots and Logs

N/A

**Comment by Trenly** [comment]
[Policy] Reset Labels

**Comment by Luna-Grace** [comment]
- https://github.com/microsoft/winget-pkgs/issues/163332

**Comment by Trenly** [comment]
Close with reason: linked prs merged;
