### ISSUE TITLE
[Update Request]: Amazon.AWSVPNClient 3.12.1 hashes do not match

### ISSUE THREAD

**Issue by shimosyan** [microsoft/winget-pkgs#165204]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Amazon.AWSVPNClient

### Package Version

3.12.1

### Please describe the changes you would like to see

I get the following error when installing this package.
```
Installer hash does not match; this cannot be overridden when running as admin
```

The reason is probably that 'latest' is specified in the installer URL in the manifest and the version is different.
https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/Amazon/AWSVPNClient/3.12.1/Amazon.AWSVPNClient.installer.yaml#L11

**Comment by Dragon1573** [comment]
The `installerUrl` of this package is a **vanity URL**. This version of manifest should be removed.
