### ISSUE TITLE
[Update Request]: AntibodySoftware.WizTree

### ISSUE THREAD

**Issue by BraveThrasher** [microsoft/winget-pkgs#165211]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AntibodySoftware.WizTree

### Package Version

4.20

### Please describe the changes you would like to see

There is a new release (4.20) available, download link https://www.diskanalyzer.com/files/wiztree_4_20_setup.exe

Keep in mind that there is also an open issue with the previous version (4.19) see https://github.com/microsoft/winget-pkgs/issues/165210

**Comment by Dragon1573** [comment]
Currently in progress.

- See #165057

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue should be closed as "completed", since #165057 is successfully merged.

CC @BraveThrasher @stephengillie

**Comment by stephengillie** [comment]
> Note
> 
> Issue should be closed as "completed", since #165057 is successfully merged.
> 
> CC @ BraveThrasher @ stephengillie
