### ISSUE TITLE
[Package Request]: Good Commit CLI

### ISSUE THREAD

**Issue by Gukkey** [microsoft/winget-pkgs#165377]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Gukkey/good-commit-cli/releases
Publisher: Guhan
Package Name: Good Commit
Description: A CLI alternative to Commitzen
Package Version: 1.0.1
Installer URL: https://github.com/Gukkey/good-commit-cli/releases/download/v.1.0.1/good-commit-cli.exe

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Should be closed as "completed", since #165379 is successfully merged.
