### ISSUE TITLE
[Package Issue]: OpenStreetMap.Josm should have dependency on "one of" JDK > 17 not only the Oracle one

### ISSUE THREAD

**Issue by Binnette** [microsoft/winget-pkgs#165368]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

According to winget, Josm required "Oracle.JDK.17 >= 17.0.1.0". But instead it should required one of:

- Oracle.JDK.17
- Amazon.Corretto.17.JDK
- Azul.Zulu.17.JDK
- EclipseAdoptium.Temurin.17.JDK
- IBM.Semeru.17.JDK
- AdoptOpenJDK.OpenJDK.17 
- Microsoft.OpenJDK.17

Instead of forcing the installation of "Oracle.JDK.17", we should set the requirement of one of theses JDK. That way the user can install for example EclipseAdoptium.Temurin.17.JDK and then install OpenStreetMap.Josm

And Josm will work because, Josm can work on any JDK >= 17.0.1.0

### Steps to reproduce

1. winget install EclipseAdoptium.Temurin.17.JDK
2. winget install OpenStreetMap.Josm

Here winget want to install Oracle.JDK.17, but I already installed another JDK 17

### Actual behavior

winget force install Oracle.JDK.17

### Expected behavior

winget should check for any JDK 17 and do not force to install Oracle.JDK.17

### Environment

```raw
Gestionnaire de package Windows v1.8.1911
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.19045.4651
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.23.1911.0

Répertoires Winget
-----------------------------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  %USERPROFILE%\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Désactivé
LocalArchiveMalwareScanOverride           Désactivé
ProxyCommandLineOptions                   Désactivé
DefaultProxy                              Désactivé
```

**Comment by Trenly** [comment]
Unfortunately "one-of" dependencies are not currently supported. 

* https://github.com/microsoft/winget-cli/issues/1789
* https://github.com/microsoft/winget-cli/issues/2969

**Comment by Dragon1573** [comment]
![image](https://github.com/user-attachments/assets/2d6a3ab9-4e48-449d-b851-2fecf0482bcf)

There's no pre-installed JDK or JRE in a brand new _Windows Sandbox_ instance. Seems `OpenStreetMap.Josm` can handle JDK/JRE on its own?

Only modified: 

![image](https://github.com/user-attachments/assets/71728486-6448-4e14-a805-0b9a38644232)

**Comment by stephengillie** [comment]
> Unfortunately "one-of" dependencies are not currently supported.
> 
> * [Support for "or" dependencies. winget-cli#1789](https://github.com/microsoft/winget-cli/issues/1789)
> * [Dependency Providers winget-cli#2969](https://github.com/microsoft/winget-cli/issues/2969)

Generally for these cases, we omit the dependency. The same should probably be done for this package.

**Comment by Binnette** [comment]
Also, when I install Josm with winget, I saw that it install with its own embed JRE. So this dependency is useless and can be removed.
