### ISSUE TITLE
[Update Request]: Arc Browser 1.13.0 (40526)

### ISSUE THREAD

**Issue by iPixelGalaxy** [microsoft/winget-pkgs#165653]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TheBrowserCompany.Arc

### Package Version

1.13.0.40526

### Please describe the changes you would like to see

New Update for Arc (which also supports Windows 10 out of the box): https://releases.arc.net/windows/prod/1.13.0.40526/Arc.x64.msix

Dependencies should be the same as before.

**Comment by YusufKhalifadev** [comment]
Close this issue there's already a PR about this update #165636

**Comment by iPixelGalaxy** [comment]
> Close this issue there's already a PR about this update #165636

Damn, no one pulled an update for this since 1.5.0, really didn't think anyone cared, but I guess I wasn't the only one lmao
