### ISSUE TITLE
Uninstall using id invalid package detection

### ISSUE THREAD

**Issue by agowa** [microsoft/winget-pkgs#16565]
# Brief description of your issue

Error detecting correct package by id.

# Steps to reproduce

1. `winget install PythonSoftwareFoundation.Python.3.8`
2. `winget uninstall PythonSoftwareFoundation.Python.3.8`

# Expected behavior

Winget should use the exact match if one is available (Also I don't even know why the 2nd one matches at all).

# Actual behavior

```
PS C:\> winget uninstall PythonSoftwareFoundation.Python.3.8
Multiple installed packages found matching input criteria. Please refine the input.
Name                  Id
------------------------------------------------------------
Python 3.8            PythonSoftwareFoundation.Python.3.8
Python 3.7.8 (64-bit) {886f7e19-ca0e-4f00-9cb5-14f6506fea86}
```

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.21390.1
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by vedantmgoyal2009** [comment]
@agowa338 Now you can use `winget install Python.Python.3`. Also, if you want to install any specific version, you can use `winget show Python.Python.3 --versions` to list all versions and install it using `winget install Python.Python.3 --version <version>`

**Comment by DuNuNuBatman** [comment]
Just piggybacking on this same issue.
![image](https://user-images.githubusercontent.com/4228513/135660720-f8ccaf66-7141-4739-a04a-2f37759738f1.png)
Running winget show gives me the same versions... I have no idea where to go from here.
![image](https://user-images.githubusercontent.com/4228513/135660794-cd13a6b6-1a4b-4a28-93c7-3a0a8071f0aa.png)

**Comment by denelon** [comment]
@DuNuNuBatman We are still making improvements in this area. We do cover some of the options at https://docs.microsoft.com/en-us/windows/package-manager/winget/install#multiple-selections

Try: `winget show github.cli --versions -s winget`.

**Comment by DuNuNuBatman** [comment]
ah, my mistake. I thought the behavior had changed and the id was the default. Thanks!

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your issue still persists. 

###### Close with reason: Stale;
