### ISSUE TITLE
Gramps.Gramps does not allow uninstall

### ISSUE THREAD

**Issue by rbarbrow** [microsoft/winget-pkgs#16573]
after running winget install -e --id Gramps.Gramps

when running 

> winget uninstall -e --id Gramps.Gramps 

> winget uninstall Gramps  

will return 

- No installed package found matching input criteria.

however the items is still found in control pannel uninstall apps

**Comment by rbarbrow** [comment]
winget list gramps
Name        Id                Version
-------------------------------------
GrampsAIO64 GrampsAIO64 5.1.3 5.1.3

**Comment by rbarbrow** [comment]
**winget uninstall grampsAIO64**   Does work
**winget uninstall gramps**  does not work

**Comment by rbarbrow** [comment]
winget search gramps
Name   Id            Version
----------------------------
Gramps Gramps.Gramps 5.1.3

**Comment by ItzLevvie2** [comment]
This issue should be solved now:
```
Name                                      Id                                        Version
-----------------------------------------------------------------------------------------------------
GrampsAIO                                 Gramps.Gramps                             5.1.3
```
