### ISSUE TITLE
[Package Issue]: Docker.DockerDesktop

### ISSUE THREAD

**Issue by ThatStevenGuy** [microsoft/winget-pkgs#165813]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

On ARM devices, the x64 version of Docker Desktop is installed even though an ARM version is available. This x64 version won't function correctly on ARM due to a known [WSL issue](https://github.com/microsoft/WSL/issues/9611).

Versions 4.32.0, 4.33.0 and 4.33.1 (most recent as of writing) are affected. Their manifests refer to the AMD64 (x64) version of Docker Desktop for both the x64 and ARM architectures. The last version that does correctly install the ARM version of Docker Desktop is 4.31.1

Tested on a Microsoft Surface 7 laptop with a Snapdragon X Elite.

### Steps to reproduce

1. On an ARM device, run `winget install --id Docker.DockerDesktop`.
2. Observe the download URL and its inclusion of AMD64 rather than **ARM64**.

### Actual behavior

The x64 version of Docker Desktop is installed.

### Expected behavior

The ARM64 version of Docker Desktop should be installed.

### Environment

```raw
Windows: Windows.Desktop v10.0.26100.1150
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by mdanish-kh** [comment]
> Versions 4.32.0, 4.33.0 and 4.33.1 (most recent as of writing) are affected. Their manifests refer to the AMD64 (x64) version of Docker Desktop for both the x64 and ARM architectures.

Opened PRs to fix the URLs in `4.33.0` and `4.33.1`. The manifest for 4.32.0 [appears to reference the correct URL](https://github.com/microsoft/winget-pkgs/blob/098bf54e47c248f9bfdcc3d84e93bb1fb035fe6c/manifests/d/Docker/DockerDesktop/4.32.0/Docker.DockerDesktop.installer.yaml#L22-L24), can you double-check if you're facing the issue with 4.32.0?

**Comment by ThatStevenGuy** [comment]
Oh yes you're right, 4.32.0 is actually set up just fine. Must've looked a bit too quickly when checking the other affected versions.
Thanks for opening the PRs.

**Comment by mdanish-kh** [comment]
@ThatStevenGuy - The PRs got merged, can you check to see if you're still encountering the issue?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by ThatStevenGuy** [comment]
The correct ARM binaries are now downloaded for versions `4.33.0` and `4.33.1`. Thanks for the quick response & fixing the issue.
