### ISSUE TITLE
[Update Request]: Voidtool's Everything Lite

### ISSUE THREAD

**Issue by mikeyphan** [microsoft/winget-pkgs#166039]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

voidtools.Everything.Lite

### Package Version

1.4.1.1026

### Please describe the changes you would like to see

The wrong installer is linked to Everything Lite. The correct installer should have "Lite" in the file name. 

Link: https://www.voidtools.com/Everything-1.4.1.1026.x64.Lite-Setup.exe
SHA256: 2f3e5c06bf84845ad1e9b2626fbe1217dc08301f2c853c9485d09f20272e0e84

**Comment by mdanish-kh** [comment]
Close with reason: Resolved by #166062;
