### ISSUE TITLE
[Update Request]: Fortinet.FortiClientVPN

### ISSUE THREAD

**Issue by manugp** [microsoft/winget-pkgs#166049]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Fortinet.FortiClientVPN

### Package Version

7.4.0.1658

### Please describe the changes you would like to see

There is a new version available(7.4.0.1658). The package could be found at the Fortinet page(https://www.fortinet.com/support/product-downloads).
https://www.fortinet.com/support/product-downloads/forticlient. I was not able to connect to my company VPN due to me running an older version. I didn't even think about package version since I use winget to update everything. Only when a co-worker pointed it out did I double check and realize that winget had version 7.0.1, whereas the new version was 7.4.0.1658.

**Comment by Dragon1573** [comment]
Hello @manugp, what is the edition of this package at [download page](https://www.fortinet.com/support/product-downloads)? Is it [FortiClient VPN only](https://www.fortinet.com/support/product-downloads#vpn)?

![image](https://github.com/user-attachments/assets/82fb348f-b52c-4f64-97a9-002822ac7c09)

**Comment by manugp** [comment]
The link I gave points to the Fortinet Client VPN installer. Not the actual install package. The installer downloads the latest version from the Fortinet website and then installs it into the machine. Let me see if I can find the link of the actual package.

**Comment by Dragon1573** [comment]
Thanks @manugp ❤️

> [!NOTE]
>
> `InstallerUrl` in above pull request seems a web installer helper. The actual installer wizard is downloaded and automatically launched interactively by the helper. Seems the helper does not support unattended install.

**Comment by manugp** [comment]
Tough luck. I looked through online to find links to the installer and couldn't find any. Talked to a Fortinet support person online and they said that the offline installer package is only available to people with support contracts with Fortinet.

Based on one of the below articles I was able to find that the online installer downloads the offline installer into the temp folder, can winget handle such a scenario. The only other options I could think of was to monitor the FortinetOnline Installer to see where it is getting the package from. And the second option was to bruteforce link combinations to see where the package would be located in the domain(filestore.fortinet.com/forticlient/downloads/)

I tried a few softwares to see if the first option works and I couldn't find anything helpful, due to my lack of experience. The second one wasn't of much help too. Do let me know if you have any suggestions.

https://community.fortinet.com/t5/FortiClient/Technical-Tip-How-to-download-FortiClient-offline-installer/ta-p/197679

https://community.fortinet.com/t5/Support-Forum/FortiClient-offline-installer/td-p/88976

![image](https://github.com/user-attachments/assets/c9b8881f-5f65-4932-9d7a-42bd5f4431f6)

**Comment by Dragon1573** [comment]
@manugp - Could you please try contacting to Fortinet again? Is there any available switches of online installer file.

**Comment by amber-m-mvd** [comment]
> @manugp - Could you please try contacting to Fortinet again? Is there any available switches of online installer file.

I also looked for that too. The only ones I was able to find were --msi and --msiparams. They seem to be non-functional.

**Comment by amber-m-mvd** [comment]
An alternative I have found for sorting out the lack of scripting support is using Chocolatey or Scoop instead.

**Comment by Dragon1573** [comment]
I used to use _Scoop_ asy package manager. The `main` bucket seems only accept "portable" packages. Maybe adding it to `extras` bucket is better.

**Comment by y2k04** [comment]
Since it uses PowerShell scripting, couldn't we just wait for FortiClientVPN.exe to have a handle and immediately kill it and then after that start the MSI installer quietly from the Temp folder?

**Comment by y2k04** [comment]
I have created an issue in the Extras bucket for us to continue discussing this, as it is currently become off-topic from winget: [#13762](https://github.com/ScoopInstaller/Extras/issues/13762)

I hope we can persue this option further cause this is currently causing problems for a lot of people around the world, all cause of a firmware update with the FortiGate.

**Comment by manugp** [comment]
Is there not a way for us to see how the Fortinet VPN installer is downloading the package and saving it to the temp folder. If the installer is get the install from a web link, we could just use that. Or if is making an API call to get the package - why not we emulate this. Do excuse my lack of understanding. I am currently incapable of doing this and also not sure if this is even possible.

**Comment by manugp** [comment]
Also the below website mentions Fortinet Developer Network Accounts having access to the installer, not sure if that is also the online installer.
https://docs.fortinet.com/document/forticlient/7.4.0/administration-guide/269779/standalone-vpn-client
![image](https://github.com/user-attachments/assets/e8385649-5dba-4505-8572-5b09f8a0016a)

**Comment by amber-m-mvd** [comment]
> Is there not a way for us to see how the Fortinet VPN installer is downloading the package and saving it to the temp folder. If the installer is get the install from a web link, we could just use that. Or if is making an API call to get the package - why not we emulate this. Do excuse my lack of understanding. I am currently incapable of doing this and also not sure if this is even possible.

Cause that would require scripting which winget will never support.



> Also the below website mentions Fortinet Developer Network Accounts having access to the installer, not sure if that is also the online installer. https://docs.fortinet.com/document/forticlient/7.4.0/administration-guide/269779/standalone-vpn-client ![image](https://private-user-images.githubusercontent.com/10363506/356377979-e8385649-5dba-4505-8572-5b09f8a0016a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTg0OTgsIm5iZiI6MTcyMzE1ODE5OCwicGF0aCI6Ii8xMDM2MzUwNi8zNTYzNzc5NzktZTgzODU2NDktNWRiYS00NTA1LTg1NzItNWIwOWY4YTAwMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIzMDMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OGFmNzBjYWZlNzk0YWY2OGU4ZjkzYTVjZDgzNGE2YTg1Yzg4MjAxYjNkMmI5MTk2MTI1MTZkNGQ0MjVkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFGwHMCgNBw5FWMN5x__2rjS__B4uzwE35mc_QchS7A)

That is not.

**Comment by manugp** [comment]
It is so weird that they have a package for linux available, but not for Windows.

https://aur.archlinux.org/packages/forticlient

https://repo.fortinet.com/repo/forticlient/7.4/ubuntu22/pool/non-free/f/forticlient/forticlient_7.4.0.1636_amd64.deb

https://docs.fortinet.com/document/forticlient/7.4.0/administration-guide/213138/installing-forticlient-linux-from-repo-fortinet-com

**Comment by bkaug** [comment]
If you download and start the online installer it will download the full installer .exe in this folder: %localappdata%\Temp\

Copy the .exe to your desktop and close the online installer.

Now if you run this .exe installer with the /quiet parameter (I used a shortcut) it installs the forticlient quietly.

Does this help getting this installer into Winget?

**Comment by rvtdadmin** [comment]
Fortinet must have changed the way they package the installer now as I'm able to use the MSI to update Forticlient as a Win32 app.
![Image](https://github.com/user-attachments/assets/f2514618-aa13-44e0-b22a-3a72d264c1d1)

Removed the ForticlientInstaller.exe and packaged everything else.
msiexec /i "FortiClientVPN.msi" /qn /norestart

It is silent expect it does prompt the user to restart/Donotrestart. It does need to restart to start the Forticlient

Not sure if this helps getting it packages for Winget.
Thanks
