### ISSUE TITLE
[Package Request]: Jagex Launcher

### ISSUE THREAD

**Issue by KristofferDale** [microsoft/winget-pkgs#166111]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.jagex.com/no-NO/launcher
Publisher: Jagex Ltd
Package Name: Jagex Launcher
Description: The Jagex Launcher offers a new and improved experience for RuneScape and beyond. It allows you to access Jagex games seamlessly and securely, all in one place and with the safety and convenience of a single login.

The Jagex Launcher launches with the ability to remember your account details for quick, secure access to your RuneScape account and has lots of new [features](https://www.jagex.com/en-GB/launcher) on the way.
Package Version: 1.0.0.0
Installer URL: https://cdn.jagex.com/Jagex%20Launcher%20Installer.exe

**Comment by Dragon1573** [comment]
Seems this package does not support unattended installation. Is there any guide for silently install this package on a device?

**Comment by KristofferDale** [comment]
Not that im aware of.. I've been reasearching it for a bit, but I don't seem to find any way to install it silently sadly
