### ISSUE TITLE
VirtualBox install failed

### ISSUE THREAD

**Issue by andyliuhaowen** [microsoft/winget-pkgs#16612]
# Brief description of your issue

VirtualBox install failed

# Steps to reproduce

```
winget install VirtualBox
```

# Expected behavior

Install succeeds.

# Actual behavior

```
Found Oracle VM VirtualBox [Oracle.VirtualBox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.virtualbox.org/virtualbox/6.1.22/VirtualBox-6.1.22-144080-Win.exe
  ██████████████████████████████   103 MB /  103 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```

# Environment

```none
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by KaranKad** [comment]
Not able to replicate
```
winget install virtualbox
Found Oracle VM VirtualBox [Oracle.VirtualBox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.virtualbox.org/virtualbox/6.1.22/VirtualBox-6.1.22-144080-Win.exe
  ██████████████████████████████   103 MB /  103 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
Did you run command as admin?

**Comment by jedieaston** [comment]
Can you post any logs you have from the install attempt? `winget --info` will give you your log location.

**Comment by andyliuhaowen** [comment]
@KaranKad  No I did not run the command as admin. Do I need to?
@jedieaston  Here is the log: https://pastebin.com/JGeP4KwR

**Comment by andyliuhaowen** [comment]
Ok the issue is resolved when I run it as admin. Should I always run winget as admin? Is there a reason why most packages are fine even when I ran them as a regular user?

**Comment by KaranKad** [comment]
Some applications install fine without running admin but some don't, and in this case I think VirtualBox needs admin access for installation.

**Comment by andyliuhaowen** [comment]
I see. In that case, could we add an entry to the manifest saying whether or not a package requires admin access to install? That way winget can prompt for admin permission rather than just failing?

**Comment by denelon** [comment]
We're still working on the functionality here.  There may be a better way to improve the experience. Making changes to the schema is not trivial. It requires changes across multiple projects. This includes the client, validation pipelines, publishing pipelines, manifest creator, and the REST API.

**Comment by jedieaston** [comment]
In this case we should set the scope explicitly so people know though.

**Comment by andyliuhaowen** [comment]
We could also simply add something like "Have you tried running under admin?" when a package install fails in non-admin mode.

Anyway, this is not really the right place to discuss this. And thank you for pointing me to the solution!
