### ISSUE TITLE
[Package Request]: Crystal Launcher

### ISSUE THREAD

**Issue by opuadm** [microsoft/winget-pkgs#166236]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://crystal-launcher.net/releases/redirector.php?fid=1
Publisher: Crystal Launcher
Package Name: Crystal Launcher
Description: Another launcher for minecraft
Package Version: 2.0
Installer URL: https://download944.mediafire.com/el1pt56zzhygxy79De7V6q3zmHYvO5CJii-kVJqdytazXkTSf7eSWvNEtYtCufkYk831GGGQFPJmkSy-yYEEMQqZBgxaV4P7COO4ljG6KbnoekmWzggl_31wcyyLlQuZSgaHE_H51VIjBasJcC5NnU95gaN6BlvLztPfXzukkpJg/hjwqp00a1nie99w/CrystalLauncherN+%281%29.exe

**Comment by stephengillie** [comment]
Hi @opuadm,

The proposed `InstallerUrl` is from a file sharing site, which we generally don't allow - packages have to come from the developer's own hosting. The download page leads to a different `InstallerUrl` - should this be used instead?

https://launcher.crystal-launcher.net/releases/win/CrystalLauncherN.exe

- There is the case where a developer might use a file sharing site as their official hosting, and the way we check for this is to visit the download page and navigate to the Windows installer, download it, and check the URL of the download.

**Comment by Dragon1573** [comment]
1. Goto [homepage](https://crystal-launcher.net/)
2. Click <kbd>Download latest version</kbd>
3. Automatically navigate to `https://clicks2apk.com/35hw5r/`
4. Click [Download Now](https://clicks2apk.com/35hw5r/fdm_x64_setup.exe)

-----

1. Goto [homepage](https://crystal-launcher.net/)
2. Navigate to [Download](https://crystal-launcher.net/p/downloads) page
3. Click [Download (exe)](https://crystal-launcher.net/releases/redirector.php?fid=1)
4. Click [click here](https://crystal-launcher.net/releases/redirector.php?fid=1#)
5. Redirect about 3 times and a download dialog pops up with [actual resource URL](https://launcher.crystal-launcher.net/releases/win/CrystalLauncherN.exe)

**Comment by Dragon1573** [comment]
_Komac_ can't inspect available command line switches of [the installer](https://launcher.crystal-launcher.net/releases/win/CrystalLauncherN.exe).

```text
11:22:18 D:\...\winget-pkgs  [master ≡] 0ms pwsh> komac new --output .
> Package identifier: CrystalLauncher.CrystalLauncher
> Package version: 2.0
> 1st Installer URL https://launcher.crystal-launcher.net/releases/win/CrystalLauncherN.exe
? 2nd Installer URL <canceled>
? Is CrystalLauncherN.exe a portable exe?  
Error: 
   0: Operation was interrupted by the user
```

@opuadm, does it support unattended installation?

**Comment by opuadm** [comment]
Crystal Launcher most likely doesn't support unattended installation.

**Comment by Dragon1573** [comment]
> Crystal Launcher most likely doesn't support unattended installation.

@stephengillie, should https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer be added to this issue?
