### ISSUE TITLE
[Package Request]: `FilesCommunity.Files.Preview`

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/winget-pkgs#166364]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

<table><tr>
	<th>Download Page URI</th>
	<td><a href="https://files.community/download">https://files.community/download</a></td>
</tr><tr>
	<th>Publisher</th>
	<td><a href="https://github.com/files-community">https://github.com/files-community</a></td>
</tr><tr>
	<th>Package Name</th>
	<td>
		<table><tr>
			<th>Static</th>
			<td><code>FilesCommunity.Files.Preview</code></td>
		</tr><tr>
			<th>Vanity</th>
			<td><i>Files - Preview</i> per <a href="https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2081062536:~:text=The%20name%20should%20show%20as%20Files%20%2D%20Preview.">https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2081062536:~:text=The%20name%20should%20show%20as%20Files%20%2D%20Preview.</a></td>
		</tr></table>
	</td>
</tr><tr>
	<th>Description</th>
	<td> <blockQuote cite="https://apps.microsoft.com/detail/9nghp3dx8hdx?hl=en-gb&gl=GB#:~:text=Introducing%20Files%2C%20the%20ultimate%20file,compression%20and%20decompression%20a%20breeze.">Introducing Files, the ultimate file manager for Windows. With its sleek and intuitive design, navigating through your files and documents has never been easier.</blockQuote> </td>
</tr><tr>
	<th>Package Version</th>
	<td><code>3.6.0.0</code>, from <a href="https://github.com/files-community/Files/releases/tag/v3.6">https://github.com/files-community/Files/releases/tag/v3.6</a> (per <a href="https://github.com/files-community/Files/releases/latest">https://github.com/files-community/Files/releases/latest</a>).</td>
</tr><tr>
	<th>Installer URI</th>
	<td><a href="https://cdn.files.community/files/preview/Files.Package_3.6.0.0_Preview_Test/Files.Package_3.6.0.0_x64_arm64_Preview.msixbundle">https://cdn.files.community/files/preview/Files.Package_3.6.0.0_Preview_Test/Files.Package_3.6.0.0_x64_arm64_Preview.msixbundle</a></td>
</tr></table>

1.	Relates to https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2068290158.
1.	Remediates https://github.com/files-community/Files/issues/11380#issue-1591954869.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer

`*.appinstaller` of this package is currently not supported by `winget.exe`, since it can't be installed unattendedly. Also the "classic installer" is only provided for stable version.

This issue should be closed as "not planned".

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273528233

@Dragon1573, does an issue for supporting `.AppInstaller` packages exist? I did ask https://superuser.com/revisions/1851464/2 prior to filing this, but I didn't receive any responses, so I wasn't aware. I'll try to request a standard MSIX package too.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273610132

I've filed https://github.com/files-community/Files/issues/15973#issue-2453655841 to hopefully bypass WinGet's lack of support for `.AppInstaller` files.

**Comment by Josh65-2201** [comment]
I have already given a link for preview builds https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2081062536

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273610132

@Dragon1573, I've filed https://github.com/microsoft/winget-cli/issues/4711#issue-2453673163 for support for the `.AppInstaller` format, because none existed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273649589

Thanks, @Josh65-2201. I'll update it with that.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273651129

@Josh65-2201, I'm going to revert the request to include the `.AppInstaller` package per https://github.com/files-community/Files/issues/15973#issuecomment-2273648537:

> We don’t offer standalone MSIX packages because they require specific dependencies to be installed beforehand, and we can’t provide the support needed for any confusion this might cause.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273528233

@Dragon1573, https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273660318 has been reverted per https://github.com/files-community/Files/issues/15973#issuecomment-2273719750, so the installer URI is now an `.MSIXBundle` package.

**Comment by Dragon1573** [comment]
It seems the `*.msixbundle` requires extra configurations.

- See https://github.com/microsoft/winget-pkgs/pull/166641#issuecomment-2273843075

**Comment by Josh65-2201** [comment]
Based on the PR your missing the dependencies and the arm64 version that Files supports. You can see the one for stable https://github.com/microsoft/winget-pkgs/pull/150504

**Comment by Dragon1573** [comment]
Dependencies and `arm64` entries are included in the manifest.

- See https://github.com/microsoft/winget-pkgs/pull/166641#issuecomment-2273954551

**Comment by florelis** [comment]
> 2. I did ask [_How do APPX, MSIX/MSIXBundle, and AppInstaller packages differ?_ at SE SU](https://superuser.com/revisions/1851464/2#:~:text=How%20do%20APPX%2C%20MSIX/MSIXBundle%2C%20and,about%20the%20.appinstaller%20format%2C%20though) prior to filing this, but I didn't receive any responses, so I wasn't aware.

@RokeJulianLockhart,

.appx and .msix are basically the same. You can change the extension from one to the other and things will generally work. Difference is that .appx is older. Older versions of the OS don't know MSIX (I think those are already out of support), and there are probably features that are only supported in MSIX and not APPX, but the package format is the same.

A bundle (either MSIX or APPX) contains a collection of individual packages. Those can be variations of the same package, just for different architectures. Or they can be resource packages with the strings/assets for different locales.

A .appinstaller file is an XML file that helps the OS manage auto-updates and dependencies for an MSIX package/bundle. It lists a URI for a main package and its dependencies, so that the OS can install the dependencies before the main package. It also lists a URI where a new version of the .appinstaller file can be found, and the OS can use that to check for updates.

Without changes to winget, you can already add a package for which you have a .appinstaller by just opening it in a text editor and extracting the package URI to use in winget.

> *.appinstaller of this package is currently not supported by winget.exe, since it can't be installed unattendedly

@Dragon1573, That isn't true. You can do `Add-AppPackage -AppInstallerFile <path>` in PowerShell, or use the API `PackageManager.AddPackageByUriAsync()`

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#issuecomment-2273966067

@florelis, that's brilliantly comprehensive. Thank you. If you'd rather not submit one yourself, I'll add that as an answer to the cited SU question.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/166364#event-14420832866

https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2377710960

**Comment by Josh65-2201** [comment]
> This issue has been identified as requiring a fix from a third party

I don't believe so see https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2273691802
