### ISSUE TITLE
[Package Request]: TeconmoonWiiVCInjector

### ISSUE THREAD

**Issue by ForeverFloating** [microsoft/winget-pkgs#166459]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/piratesephiroth/TeconmoonWiiVCInjector/releases
Publisher: piratesephiroth
Package Name: TeconmoonWiiVCInjector
Description: Fork of the popular Wii Virtual Console Injector for Wii U by Teconmoon
Package Version: 3.0.17
Installer URL: https://github.com/piratesephiroth/TeconmoonWiiVCInjector/releases/download/v3.0.17/TeconMoon.s.WiiVC.Injector.zip

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue should be closed as "completed" since #166456 is successfully merged.

**Comment by stephengillie** [comment]
> Note
> 
> Issue should be closed as "completed" since #166456 is successfully merged.
> 
> CC @ stephengillie, @ ForeverFloating
