### ISSUE TITLE
[Update Request]: Intel.IntelDriverAndSupportAssistant

### ISSUE THREAD

**Issue by yanurag994** [microsoft/winget-pkgs#166576]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Intel.IntelDriverAndSupportAssistant

### Package Version

24.4.32.8

### Please describe the changes you would like to see

Thers is a new version available 24.4.32.8. Intel directly updates url and hash does not match now. Intel no longer provides older version. Older vresion must be removed from WinGet Manifests.

**Comment by yanurag994** [comment]
#166417 Closes this issue

**Comment by stephengillie** [comment]
> #166417 Closes this issue
