### ISSUE TITLE
[Package Request]: Nvidia.GRID version 538.46

### ISSUE THREAD

**Issue by jbne** [microsoft/winget-pkgs#166666]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup
Publisher: NVIDIA Corporation
Package Name: NVIDIA GRID Display Driver
Description: NVIDIA GRID driver installers for NV, NVv3 and NVads A10 v5-series VMs used as virtual workstations or for virtual applications. Also for NCas_T4_V3 VM series where the GRID drivers enable the graphics functionalities similar to NV-series.
Package Version: 16.5 (538.46)
Installer URL: https://go.microsoft.com/fwlink/?linkid=874181

**Comment by jbne** [comment]
link to the PR: #166661

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
