### ISSUE TITLE
[Update Request]: OpenStreetMap.Josm new version 1.5.19160

### ISSUE THREAD

**Issue by tradmangh** [microsoft/winget-pkgs#166629]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.WingetCreate

### Package Version

1.5.19160

### Please describe the changes you would like to see

New release available 1.5.19160
Download at https://josm.openstreetmap.de/wiki/Download#Moredownloadoptions

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/166231

**Comment by stephengillie** [comment]
> #166231
