### ISSUE TITLE
[Update Request]: Jabra.Direct

### ISSUE THREAD

**Issue by egerlach** [microsoft/winget-pkgs#166890]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Jabra.Direct

### Package Version

 6.17.21301

### Please describe the changes you would like to see

There is a new release available.

Release Notes: https://www.jabra.com/support/release-notes/release-note-jabra-direct
Download Page: https://www.jabra.com/software-and-services/jabra-direct
Direct Download Link: https://jabraxpressonlineprdstor.blob.core.windows.net/jdo/JabraDirectSetup.exe

**Comment by Dragon1573** [comment]
@egerlach, this issue is already solved and should be closed as "completed". CC @stephengillie

- Resolved by @spectopo in #166822

**Comment by stephengillie** [comment]
> @egerlach, this issue is already solved and should be closed as "completed". CC @stephengillie
> 
> * Resolved by @spectopo in [New version: Jabra.Direct version 6.17.21301 (6.17.21301) #166822](https://github.com/microsoft/winget-pkgs/pull/166822)
