### ISSUE TITLE
[Update Request]: Siarhei Kuchuk: BUtil 2024.08.08

### ISSUE THREAD

**Issue by drweb86** [microsoft/winget-pkgs#166881]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SiarheiKuchuk.BUtil

### Package Version

2024.08.08

**Comment by Dragon1573** [comment]
Should be closed as "completed", since #166882 is successfully merged.

**Comment by stephengillie** [comment]
> Should be closed as "completed", since #166882 is successfully merged.
