### ISSUE TITLE
[Update Request]: Update scrcpy package to the latest version

### ISSUE THREAD

**Issue by Mujtaba0150** [microsoft/winget-pkgs#166969]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Genymobile.scrcpy

### Package Version

2.7

### Please describe the changes you would like to see

There's a newer version of scrcpy(2.7) available to download at [releases](https://github.com/Genymobile/scrcpy/releases)

**Comment by Dragon1573** [comment]
@Mujtaba0150,

it's currently in progress by @coolplaylinbot in #165921.

**Comment by stephengillie** [comment]
This package installs and launches normally. But the package manager creates a symlink instead of an LNK file, and launching by symlink prevents the application from reaching DLLs or other files it needs.

**Comment by Mujtaba0150** [comment]
> Is this topic still active?

Not sure what you mean by "active", well, seeing as the problem isn't resolved, yes it is still active, but with regards to whether there will be any further discussions here, I doubt that because the issue is something to do with the way winget handles DLLs and this issue is dependent on that.

**Comment by welpdx** [comment]
@stephengillie do you happen to know if this issue will be fixed https://github.com/microsoft/winget-cli/issues/2711? 
By the looks of it, it will be fixed in 1.9 client release?

**Comment by welpdx** [comment]
https://github.com/microsoft/winget-cli/issues/2711#issuecomment-2403370806
@stephengillie sorry to tag you again. But it sounds like a new patch/manifest should work for scrcpy now. Looking forward to movement for scrcpy. Thanks!
