### ISSUE TITLE
I made Happy Birthday program

### ISSUE THREAD

**Issue by AbubakarAtiq** [microsoft/winget-pkgs#16701]
# Description of the new feature/enhancement
How i can upload this exe file to winget?
`#include<iostream>
#include<string>
#include<iomanip>
#include <system_error>
//use instead of #include<windows.h>
using namespace std;
int main()
{
    for(;;)
    {
        
        system("color 02");
        cout<<"\t\tHappy Birthday:Hasan Bhai"<<endl;
        system("color 03");
        system("color 04");
        system("color 05");
        system("color 06");
        system("color 07");
        system("color 08");
        system("color 09");
        system("color 10");
        system("color 11");
        system("color 12");
        system("color 13");
        system("color 14");
        system("color 15");
        system("color 16");
        system("color 17");
        system("color 18");
        system("color 19");
        system("color 20");
        system("color 21");
        system("color 22");
        system("color 23");
        system("color 24");
        system("color 25");
        system("color 26");
        system("color 27");
        system("color 28");
        system("color 29");
    }
    return 0;
}`
I made exe file of it, then? What should i do?

# Proposed technical implementation details (optional)

**Comment by lychichem** [comment]
This seems a winget-cli issue? If it is not what you want winget.exe to do, you can simply build it, publish it on some site, and add the download link to the winget-pkgs repo. Anyway, I don't think adding this feature to winget-cli make any sense.
