### ISSUE TITLE
[Package Issue]: giuliosorrentino.numeronesfortuneinvalonia

### ISSUE THREAD

**Issue by GiulianoSpaghetti** [microsoft/winget-pkgs#167077]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Update is not listed. Latest update should be 2.0.3-1, instead is still present the 2.0.3 in the list.
2.0.3 is made with avalonia 11.0, and the 2.0.1 is made with avalonia 11.1.1

### Steps to reproduce

winget search giulio.sorrentino

### Actual behavior

The version 2.0.3 is listed

### Expected behavior

THe version 2.,0.3-1 should be listed

### Environment

```raw
Gestione pacchetti Windows v1.8.1911
Copyright (c) Microsoft Corporation. Tutti i diritti sono riservati.

Windows: Windows.Desktop v10.0.22631.3958
Architettura di sistema: X64
Pacchetto: Microsoft.DesktopAppInstaller v1.23.1911.0

Directory WinGet
-----------------------------------------------------------------------------------------------------------------------
Log                                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Impostazioni utente                         %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Directory collegamenti portabili (utente)   %LOCALAPPDATA%\Microsoft\WinGet\Links
Directory collegamenti portabili (computer) C:\Program Files\WinGet\Links
Radice pacchetto portabile (utente)         %LOCALAPPDATA%\Microsoft\WinGet\Packages
Radice pacchetto portabile                  C:\Program Files\WinGet\Packages
Radice pacchetto portabile (x86)            C:\Program Files (x86)\WinGet\Packages
Download del programma di installazione     %USERPROFILE%\Downloads

Collegamenti
------------------------------------------------------------------------------------
Informativa sulla privacy    https://aka.ms/winget-privacy
Contratto di licenza         https://aka.ms/winget-license
Comunicazioni di terze parti https://aka.ms/winget-3rdPartyNotice
Home page                    https://aka.ms/winget
Condizioni di Windows Store  https://www.microsoft.com/en-us/storedocs/terms-of-sale

Impostazione amministrazione              Stato
------------------------------------------------------
LocalManifestFiles                        Disabilitate
BypassCertificatePinningForMicrosoftStore Disabilitate
InstallerHashOverride                     Disabilitate
LocalArchiveMalwareScanOverride           Disabilitate
ProxyCommandLineOptions                   Disabilitate
DefaultProxy                              Disabilitate
PS C:\Users\numer>
```

### Screenshots and Logs

![2024-08-10](https://github.com/user-attachments/assets/f486c377-8071-4b24-957e-73537fd8b11c)

**Comment by Trenly** [comment]
This is not a bug. As I stated in your [discussion thread](https://github.com/microsoft/winget-pkgs/discussions/166106) for a similar issue:

> With the way WinGet sorts versions, `4.6.1-1` is considered a lower version than `4.6.1`
> 
> Take a look at [the documentation](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#version-sorting-in-winget) for an explanation.
> 
> If you want `4.6.1-1` to be listed as newer then you would need to change it to use the semantic version of `4.6.1.1` in both WinGet and the installer (or change it in WinGet and add AppsAndFeaturesEntries)

It is the same thing here. `2.0.3-1` is a lower version semantically than `2.0.3`. If you want the versions to be sorted propperly then you need to change the way you release so that the version is `2.0.3.1`, or you need to change the manifests to have AppsAndFeaturesEntries

**Comment by GiulianoSpaghetti** [comment]
And so why for some apps appear the -1 as latrest version and for others no?

**Comment by Trenly** [comment]
> And so why for some apps appear the -1 as latest version and for others no?

Do you have an example?
