### ISSUE TITLE
[Update Request]: Mikrotik.Winbox

### ISSUE THREAD

**Issue by stamepicmorg** [microsoft/winget-pkgs#167141]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mikrotik.Winbox

### Package Version

3.41

### Please describe the changes you would like to see

1. pr here https://github.com/microsoft/winget-pkgs/pull/167143

2. i added new version

3. updated manifest to 1.6.0

4. added some translations, why not

**Comment by Dragon1573** [comment]
Will be resolved by #167143.
