### ISSUE TITLE
Qnap Repository

### ISSUE THREAD

**Issue by mddtest** [microsoft/winget-pkgs#16765]
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Appears Qnap has many different programs to add to the repository I have created one so far to get this started  https://github.com/microsoft/winget-pkgs/pull/16764
https://www.qnap.com/en/download

**Comment by mddtest** [comment]
We may want to create the manifest Qnap/<model#>/program ?

**Comment by mddtest** [comment]
@ItzLevvie  So what are your thoughts on the naming conventions for this?

**Comment by max-stockhausen** [comment]
Have you looked into [https://github.com/microsoft/winget-create](url)? Because that does it for you

**Comment by mddtest** [comment]
Yes I have created may entries already.  I was wanting to see how we should handle QNAP as they have different hardware models with different software models.

**Comment by denelon** [comment]
Looping in other moderators who might have suggestions as well.

@OfficialEsco
@jedieaston

**Comment by OfficialEsco** [comment]
I checked it out when i saw the Issue, but i can't seem to find any actual programs?..

**Comment by mddtest** [comment]
So turns out its not as big of a deal here. found a page with all exe software.

**Comment by mddtest** [comment]
See https://www.qnap.com/en-us/utilities/

Added
Finder (merged)
Qsync (awaiting merge)


Items to add
 -NetBak Replicator 
 -QNAP JBOD Manager 
 -QNAP External RAID Manager 
 -QENC Decrypter 
 -QuDedup Extract Tool 
 -QVR Pro Client 
 -QVPN Device Client

**Comment by mddtest** [comment]
added them all.
close issue

**Comment by OfficialEsco** [comment]
> added them all.

I really hope you check for correct Publisher and PackageName 👀
