### ISSUE TITLE
Microsoft.DotNet downloads are slow and don't match official links

### ISSUE THREAD

**Issue by stevenlele** [microsoft/winget-pkgs#167642]
The installer links in the manifests submitted by @dotnet-winget-bot (https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+DotNet+in%3Atitle) don't match the official links, and the download speed is very slow in some regions (e.g. China) compared to the official ones.

For example, the x64 link in #167532 is https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/8.0.8/windowsdesktop-runtime-8.0.8-win-x64.exe, whereas the official link listed in the [release notes](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.8/8.0.8.md) and [official download page](https://dotnet.microsoft.com/download/dotnet/8.0) is https://download.visualstudio.microsoft.com/download/pr/907765b0-2bf8-494e-93aa-5ef9553c5d68/a9308dc010617e6716c0e6abd53b05ce/windowsdesktop-runtime-8.0.8-win-x64.exe, which downloads a lot faster than the former one in China (<100 KB/s vs ~5 MB/s).

@mthalman Please consider fixing your download network or switching to the official links instead.

Edit: DNS resolution FYI:
```powershell
> nslookup dotnetcli.azureedge.net
Server:  pdns.dnspod.cn
Address:  119.29.29.29

Non-authoritative answer:
Name:    cs9.wpc.v0cdn.net
Addresses:  2606:2800:147:120f:30c:1ba0:fc6:265a
          117.18.232.200 # Verizon Business, Australia
Aliases:  dotnetcli.azureedge.net
          dotnetcli.ec.azureedge.net

> nslookup download.visualstudio.microsoft.com
Server:  pdns.dnspod.cn
Address:  119.29.29.29

Non-authoritative answer:
Name:    download.visualstudio.microsoft.com.mwcname.com
Address:  117.24.10.17 # China Telecom, Quanzhou
Aliases:  download.visualstudio.microsoft.com
          visualstudio.download.prss.trafficmanager.net
```

**Comment by mthalman** [comment]
@rbhanda - Can we make any CDN configuration changes to improve this?

**Comment by mthalman** [comment]
`download.visualstudio.microsoft.com` isn't anymore official than `builds.dotnet.microsoft.com`. In fact, the goal is that `builds.dotnet.microsoft.com` will be the sole location for .NET bits: https://github.com/dotnet/core/issues/9675.

If you're experiencing issues with the `builds.dotnet.microsoft.com` CDN, please log an issue at https://github.com/dotnet/core.
