### ISSUE TITLE
[Package Issue]: Maltego.Maltego Don't read the right installed version.

### ISSUE THREAD

**Issue by makamo** [microsoft/winget-pkgs#167705]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget finds that the installed version of Maltego is 4, but in fact version 4.7.0 is already installed.

### Steps to reproduce

winget update Maltego.Maltego

### Actual behavior

winget try to install but its dosent work 

### Expected behavior

Don't ask to update.

### Environment

```raw
Gestionnaire de package Windows v1.8.1911
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.19045.4717
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.23.1911.0

Répertoires Winget
-----------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  %USERPROFILE%\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Activé
LocalArchiveMalwareScanOverride           Désactivé
ProxyCommandLineOptions                   Désactivé
DefaultProxy                              Désactivé
```

### Screenshots and Logs

![image](https://github.com/user-attachments/assets/7ce5d884-a253-4e00-a2ca-90efc8eb8a1e)

―― 11:00:47 - winget ――――――――――――――――――――――――
Nom               ID                               Version     Disponible     Source
――――――――――――――――――――――――――――――――――
Maltego          Maltego.Maltego       4               4.7.0               winget

**Comment by stephengillie** [comment]
I'm guessing that a `DisplayVersion` might be needed.

**Comment by Dragon1573** [comment]
https://github.com/microsoft/winget-pkgs/blob/b059bbbbc62900b789f501278981c80b0c2bd467/manifests/m/Maltego/Maltego/4.7.0/Maltego.Maltego.installer.yaml#L9

Maybe it should be changed to ... ?

```yaml
- DisplayVersion: '4'
```
