### ISSUE TITLE
[Update Request]: Nlitesoft.NTLite Installer hash does not match v2024.8.10013.0

### ISSUE THREAD

**Issue by hms54** [microsoft/winget-pkgs#167898]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Nlitesoft.NTLite

### Package Version

2024.8.10013.0

### Please describe the changes you would like to see

Update Installer Hash for NTLite v2024.8.10013.0 to resolve installation error message: 
Installer hash does not match; this cannot be overridden when running as admin

**Comment by aisgbnok** [comment]
This has been resolved by:

- https://github.com/microsoft/winget-pkgs/pull/167904
- https://github.com/microsoft/winget-pkgs/pull/167953
