### ISSUE TITLE
[Feature Request]: Support PAT to avoid "API rate limit exceeded"

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#167997]
### Description of the new feature/enhancement

I'm currently using `Tools/SandboxTest.ps1` for testing manifests locally. Sometimes I will trigger an error as follows.

> [!NOTE]
>
> Real IP address is masked for privacy. Just use `127.0.0.1` as a placeholder.

```text
Invoke-RestMethod: C:\Repository\winget-pkgs\Tools\SandboxTest.ps1:86:26
Line |
  86 |  … IResponse = Invoke-RestMethod 'https://api.github.com/repos/microsoft …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  {   "message": "API rate limit exceeded for 127.0.0.1. (But here\u0027s the good news: Authenticated requests get a higher rate limit. Check out the documentation
     | for more details.)",   "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting" }
```

### Proposed technical implementation details (optional)

Upgrade `Tools/SandboxTest.ps1` and other Powershell scripts, so they can support loading PAT from environment variables or _Windows Credential Manager_. PAT authentication can get grant higher rate limitations for developers and avoid seeing this "limit exceeded" error.

```[tasklist]
### Tasks
- [ ] #168000
- [ ] https://github.com/microsoft/winget-pkgs/pull/168384
```

**Comment by stephengillie** [comment]
This is one of the many reasons that I use Hyper-V VMs instead of the sandbox. Another is that I can run multiple VMs side-by-side, but can only run 1 sandbox at a time. The sandbox seems like it should be useful, but is missing key pieces (including the PAT credential loading suggested by this issue) needed to be compelling solution.
