### ISSUE TITLE
[Package Request]: Google Pinyin

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#168081]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://dl.google.com/pinyin/v2/GooglePinyinInstaller.exe
Publisher: Google China
Package Name: GooglePinyinInstaller.exe
Description: Google Pinyin IME ([simplified Chinese](https://en.wikipedia.org/wiki/Simplified_Chinese_characters): 谷歌拼音输入法; [traditional Chinese](https://en.wikipedia.org/wiki/Traditional_Chinese_characters): 谷歌拼音輸入法; [pinyin](https://en.wikipedia.org/wiki/Pinyin): Gǔgē Pīnyīn Shūrùfǎ) is a discontinued input method developed by [Google China](https://en.wikipedia.org/wiki/Google_China) Labs. The tool was made publicly available on April 4, 2007. Aside from Pinyin input, it also includes [stroke count method](https://en.wikipedia.org/wiki/Stroke_count_method) input. As of March 2019, Google Pinyin has been discontinued and the download page [tools.google.com/pinyin/](http://tools.google.com/pinyin/) has been deleted. However, Google Pinyin IME can still be obtained from https://dl.google.com/pinyin/v2/GooglePinyinInstaller.exe (as of August 17, 2024).
Package Version: 2.7.25.128 
Installer URL: https://dl.google.com/pinyin/v2/GooglePinyinInstaller.exe

**Comment by Dragon1573** [comment]
_Komac_ can't detect its install technology. Does it support unattended installation?

**Comment by khewweifeng** [comment]
Never tried but should be able to ... Source from https://argentolee.wordpress.com/2015/07/08/silent-installation-of-google-pinyin-chinese-input/ 


Sent from Workspace ONE Boxer 


On 18 Aug 2024 12:03 am, ❤是纱雾酱哟～ ***@***.***> wrote:

Komac can't detect its install technology. Does it support unattended installation?
