### ISSUE TITLE
[Package Issue]: `Google.PlayGames.Beta` version 129.0.6651.0 should be 24.7.1042.5; wingetbot uses `Google.GoogleUpdater` version

### ISSUE THREAD

**Issue by aisgbnok** [microsoft/winget-pkgs#168014]
### Category of the issue

Installation issue.

### Brief description of your issue

The `PackageVersion`/`DisplayVersion` does not match the `DisplayVersion` that is actually installed.

### Detailed Information

I just wanted to move this explanation from #168013 into an issue to provide a better place for referencing instead of a PR.

`Google.PlayGames.Beta` uses a vanity URL. It downloads the latest version of [`Google.GoogleUpdater`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Google/GoogleUpdater) ([currently version `129.0.6651.0`](https://github.com/microsoft/winget-pkgs/tree/369561b6a94bb258fbb3ba88f964affdc3e1a95c/manifests/g/Google/GoogleUpdater/129.0.6651.0)). However, it has a metainstaller tag (`appguid={47B07D71-505D-4665-AFD4-4972A30C6530}&appname=Google%20Play%20Games&lang=en-US&needsadmin=true&ap=beta`) embedded in the Updater (hence different hash than [`Google.GoogleUpdater`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Google/GoogleUpdater) package).

Because of this every time Google releases a new version of GoogleUpdater, this vanity URL will point to a new installer of GoogleUpdater. So wingetbot is using the GoogleUpdater installer version because it is the installer at the end of the URL. However, due to the metainstaller tag GoogleUpdater will download and install the latest version of `Google.PlayGames.Beta` after it installs itself.

So you have to go through full installation of `Google.PlayGames.Beta` to get the actual installer `DisplayVersion` for proper ARP matching.

There are other `Google.PlayGames.Beta` installers that you can query through Google's update API using appid such as`{47B07D71-505D-4665-AFD4-4972A30C6530}`, but none of them that I found seem to be compatible with Winget. They either don't offer unattended silent switches yet or they require unzipping/unpackaging that the GoogleUpdater handles.

### Steps to reproduce

1. Install `Google.PlayGames.Beta` using Winget.

```PowerShell
Found Google Play Games beta [Google.PlayGames.Beta] Version 129.0.6651.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/tag/s/appguid%3D%7B47B07D71-505D-4665-AFD4-4972A30C6530%7D%26appname%3DGoogle%2520Play%2520Games%26lang%3Den-US%26needsadmin%3Dtrue%26ap%3Dbeta/play/games/Install-GooglePlayGames-Beta.exe
  ██████████████████████████████  8.53 MB / 8.53 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

```PowerShell
DisplayName    : Google Play Games beta
DisplayVersion : 24.7.1042.5
Publisher      : Google LLC
ProductCode    : GooglePlayGames
Scope          : Machine
```

### Actual behavior

Wingetbot keeps updating `Google.PlayGames.Beta` to the `Google.GoogleUpdater` version because it relies on file version from the downloaded installer.

### Expected behavior

`Google.PlayGames.Beta` version should match the ARP `DisplayVersion` in Windows after the application installs. Currently version `24.7.1042.5`.

### Environment

```raw
Windows Package Manager (Preview) v1.9.2151-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26120.1350
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.2151.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![image](https://github.com/user-attachments/assets/c138d696-ecc0-4307-9daa-7c2d571393da)

**Comment by sebbu2** [comment]
It happens again with Google.PlayGames.Beta version 24.10.1176.6

**Comment by aisgbnok** [comment]
> It happens again with Google.PlayGames.Beta version 24.10.1176.6

Thanks for flagging. I'll fix the version again.
 
- #195537.

**Comment by joelspadin** [comment]
This is happening again. The current version is 25.1.52.0, but winget wants to update to 134.0.6947.0.

**Comment by aisgbnok** [comment]
> This is happening again. The current version is 25.1.52.0, but winget wants to update to 134.0.6947.0.

Thanks for flagging.
