### ISSUE TITLE
[Package Request]: DocFetcher

### ISSUE THREAD

**Issue by manugp** [microsoft/winget-pkgs#168159]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/docfetcher/files/docfetcher/1.1.25/docfetcher_1.1.25_win32_setup.exe
Publisher: Sourceforge/qfore
Package Name: DocFetcher
Description: Desktop Search Application

Package Version: 1.1.25
Installer URL: https://sourceforge.net/projects/docfetcher/files/docfetcher/1.1.25/docfetcher_1.1.25_win32_setup.exe

I have attached the file I made using WIngetCreate. Could someone review this and give me their comments. I added a .txt extension at the end of all the yaml files so that I could bring this into Github. Thank you.

[qforce.DocFetcher.installer.yaml.txt](https://github.com/user-attachments/files/16651411/qforce.DocFetcher.installer.yaml.txt)
[qforce.DocFetcher.locale.en-US.yaml.txt](https://github.com/user-attachments/files/16651412/qforce.DocFetcher.locale.en-US.yaml.txt)
[qforce.DocFetcher.yaml.txt](https://github.com/user-attachments/files/16651413/qforce.DocFetcher.yaml.txt)

**Comment by Dragon1573** [comment]
You can simply generate and create pull requests by `wingetcreate.exe` directly. ❤️

Just create a pull requests, moderators will review them and interact with you if there are any changes required.
