### ISSUE TITLE
[Update Request]: MSI.Kombustor.4

### ISSUE THREAD

**Issue by Deathskull01** [microsoft/winget-pkgs#168167]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MSI.Kombustor.4

### Package Version

4.1.29.0

### Please describe the changes you would like to see

Download Page: https://www.geeks3d.com/furmark/kombustor/downloads/
Download URL: https://geeks3d.com/dl/get/744

**Comment by znarfm** [comment]
taking this.

Using https://gpuscore.top/msi/MSI_Kombustor4_Setup_v4.1.29.0_x64.exe as download URL.
