### ISSUE TITLE
[Update Request]: Taiizor.SucroseWallpaperEngine

### ISSUE THREAD

**Issue by Taiizor** [microsoft/winget-pkgs#168263]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Taiizor.SucroseWallpaperEngine

### Package Version

24.8.8.0

### Please describe the changes you would like to see

There is a new release (24.8.8.0). Download Page Url: https://github.com/Taiizor/Sucrose/releases/tag/v24.8.8.0

x64 Architecture: https://github.com/Taiizor/Sucrose/releases/download/v24.8.8.0/Sucrose_Bundle_.NET_Framework_4.8_x64_24.8.8.0.exe
x86 Architecture: https://github.com/Taiizor/Sucrose/releases/download/v24.8.8.0/Sucrose_Bundle_.NET_Framework_4.8_x86_24.8.8.0.exe
ARM64 Architecture: https://github.com/Taiizor/Sucrose/releases/download/v24.8.8.0/Sucrose_Bundle_.NET_Framework_4.8_ARM64_24.8.8.0.exe

**Comment by Dragon1573** [comment]
Should be closed as completed, since #168268 is successfully merged.

**Comment by stephengillie** [comment]
> Should be closed as completed, since #168268 is successfully merged.
