### ISSUE TITLE
[Update Request]: Search My Files

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#168410]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

NirSoft.SearchMyFiles

### Package Version

3.30

### Please describe the changes you would like to see

Download urls are the same as with the older version (that should be deleted because it no longer installs), only the sha256 checksums have changed.

**Comment by stephengillie** [comment]
> Download urls are the same as with the older version (that should be deleted because it no longer installs), only the sha256 checksums have changed.

This frequently gets called a "vanity URL". We have a system that checks some of these on a daily basis, and creates PRs to add the new version, and then remove the old. Unfortunately, it doesn't cover all packages currently.
