### ISSUE TITLE
[Update Request]: Plover 4.0.0rc2

### ISSUE THREAD

**Issue by RAOEUS** [microsoft/winget-pkgs#168556]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OpenStenoProject.Plover

### Package Version

4.0.0rc2

### Please describe the changes you would like to see

There is a new release available (4.0.0rc2)
Download: https://github.com/openstenoproject/plover/releases/download/v4.0.0rc2/plover-4.0.0rc2-win64.setup.exe

**Comment by Dragon1573** [comment]
Resolved by #168557. Should be closed as "completed".

**Comment by stephengillie** [comment]
> Resolved by #168557. Should be closed as "completed".
