### ISSUE TITLE
[Package Request]: regedix

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#169197]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://regedix.webrox.fr/
Publisher: Stéphane Graziano
Package Name: regedix
Description: Windows Registry editor. Breadcrumb navigation, favorites, dark theme...
Package Version: 2.0.0.0
Installer URL: https://regedix.webrox.fr/download.php?v=2.0.0.0&file=2.0.0.0/Regedix_installer-2.0.0.exe

**Comment by Dragon1573** [comment]
I'm currently working on this issue.

The `InstallerUrl` you provided here seems to be an interactive only installer. I'll try if portable version is supported by `winget.exe`.

**Comment by soredake** [comment]
@Dragon1573 there is a portable version https://regedix.webrox.fr/download.php?v=2.0.0.0&file=2.0.0.0/Regedix-2.0.0-x64.exe

**Comment by Dragon1573** [comment]
The portable `x64` edition can't launch in my _Windows 11 `amd64` Sandbox_ instance, but it works normally as expected in my _Windows 11 `amd64` Host_ instance.
