### ISSUE TITLE
[Update Request]: Stripe.StripeCli 1.21.2

### ISSUE THREAD

**Issue by Persistent13** [microsoft/winget-pkgs#169169]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Stripe.StripeCli

### Package Version

1.21.2

### Please describe the changes you would like to see

There is a new release (1.21.2) available. Download Page Url: https://github.com/stripe/stripe-cli/releases/tag/v1.21.2

I'd submit a PR but I'm not able to find out what the expected process for that is. Is this documented somewhere in this repo that I'm just missing? The contributing.md file seems to just be for adding new packages rather than how to update existing ones like this.

**Comment by znarfm** [comment]
> I'd submit a PR but I'm not able to find out what the expected process for that is. Is this documented somewhere in this repo that I'm just missing? The contributing.md file seems to just be for adding new packages rather than how to update existing ones like this.

Hello, @Persistent13 ! Before, I just use the `YamlCreate.ps1` in the tools folder in this repo. However, just discovered [komac](https://github.com/russellbanks/Komac) and it made things easier and quicker when updating manifests.

**Comment by Dragon1573** [comment]
`Tools/YamlCreate.ps1` requires previous versions to be checkout in your workspace, but `komac.exe` and `wingetcreate.exe` does not need them.

If you know exactly what install technology the package is, and also they provide SHA-256 on their site, maybe using `YamlCreate.ps1` is a nice choice (no need to download and inspect the file).
