### ISSUE TITLE
[Package Issue]: DiskInternals.LinuxReader  Installer hash does not match; v4.19.2

### ISSUE THREAD

**Issue by carlosal1015** [microsoft/winget-pkgs#169288]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer hash do not match. Similar [issue](https://github.com/microsoft/winget-pkgs/issues/124542) but with a new version.

### Steps to reproduce

 winget install -e --id DiskInternals.LinuxReader

### Actual behavior

winget do no install the software.

### Expected behavior

winget install the software.

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4037
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0
```

### Screenshots and Logs

![image](https://github.com/user-attachments/assets/a8f8ec0d-e942-4d7e-b111-6ddc2bc84fdd)

**Comment by Dragon1573** [comment]
According to your screenshot, this package uses a vanity URL which always pointing to the latest version. Is this package updated?

**Comment by carlosal1015** [comment]
Thanks.
