### ISSUE TITLE
[Package Request]: BotProductions.PSPThumbnailHandler

### ISSUE THREAD

**Issue by KarbitsCode** [microsoft/winget-pkgs#170049]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.botproductions.com/pspthumb/index.html
Publisher: Bot Productions
Package Name: PSP Thumbnail Handler
Description: PSP Thumbnail Handler is a free utility that allows you to view thumbnails of Paint Shop Pro images.
Package Version: 2.10.49
Installer URL: https://www.botproductions.com/pspthumb/v2/pthsetup.exe; https://www.botproductions.com/pspthumb/v2/x64/pthsetup.exe

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> Although this package supports unattended install with `/quiet` and `/passive` switches, it have no ability to automatically exit the wizard after installation. This will still block `winget.exe`.
>
> See [Advanced Setup Options](https://www.botproductions.com/pspthumb/setup.html)

**Comment by Dragon1573** [comment]
https://github.com/user-attachments/assets/2600f291-c591-4d86-aa0a-7867dac68d4d

**Comment by KarbitsCode** [comment]
Ah, I see, but does it also happen with IconViewer one? ([BotProductions.IconViewer](https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/BotProductions/IconViewer/3.2.147))

**Comment by Dragon1573** [comment]
> Does it also happen with `BotProductions.IconViewer`?

No. Validated in _Windows 11 `amd64` Sandbox_ instance. _IconViewer_ install successfully without user interaction.

**Comment by KarbitsCode** [comment]
Did I see a deleted message?
