### ISSUE TITLE
[Update Request]: TeamViewer.TeamViewer 

### ISSUE THREAD

**Issue by kris6673** [microsoft/winget-pkgs#170160]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TeamViewer.TeamViewer 

### Package Version

15.57.3.0

### Please describe the changes you would like to see

Installer hash does not match cause the version was updated

**Comment by a-mnich** [comment]
should be resolved with #169553

**Comment by stephengillie** [comment]
> should be resolved with #169553
