### ISSUE TITLE
Theres no need to add another Persepolis to the manifests repository

### ISSUE THREAD

**Issue by Naomi010Sentzke** [microsoft/winget-pkgs#1704]
# Description of the new feature/enhancement
Original Persepolis manifest
https://github.com/microsoft/winget-pkgs/blob/master/manifests/persepolisdm/persepolis/3.2.0.0.yaml
Another manifest added later
https://github.com/microsoft/winget-pkgs/blob/master/manifests/Persepolis/DownloadManager/3.2.0.0.Yaml

# Proposed technical implementation details (optional)
I prefer the first manifest
1. The app in the second manifest is just called "DownloadManager" (`winget install DownloadManager`?), while the first manifest simply calls it "Persepolis" (`winget install persepolis`) like [other package managers](https://github.com/lukesampson/scoop-extras/blob/master/bucket/persepolis.json).
2. As per their [website](https://persepolisdm.github.io/), the publisher should be "Persepolis Download Manager" like the first manifest, not "Persepolis Team" like the second one.
![image](https://user-images.githubusercontent.com/53768184/84106502-ea0f8e80-aa38-11ea-86db-a8553198c8e9.png)
3. The description in the first manifest "Persepolis is a Download Manager & a GUI For aria2." is the official description of the app compared to the second manifests "Persepolis Download Manager Setup".
4. First manifest links to the [actual website](https://persepolisdm.github.io/) in homepage, while second manifest links to the github page.
5. No tags or appmoniker in the second manifest.

Update: Created PR based on thread suggestions
https://github.com/microsoft/winget-pkgs/pull/1732

**Comment by Naomi010Sentzke** [comment]
I also have to add, Microsoft should have a way to prevent multiple manifests of the same app from being generated.

**Comment by Naomi010Sentzke** [comment]
I do think the folders in the repository can be changed to `PersepolisDownloadManager/Persepolis/`.

**Comment by SoftCreatR** [comment]
Just go ahead. However, you'll have to create multiple PRs, i guess.

**Comment by Naomi010Sentzke** [comment]
@SoftCreatR I can do that in one PR
https://github.com/microsoft/winget-pkgs/pull/1732

**Comment by SoftCreatR** [comment]
You can't, because you can only submit one file/change per PR.

**Comment by Naomi010Sentzke** [comment]
@SoftCreatR I literally did. Check the PR. Files Changed (2).

**Comment by SoftCreatR** [comment]
And failed ;)

You have to delete the file in a separate PR.

**Comment by Naomi010Sentzke** [comment]
@SoftCreatR It will fail validation if you rename a file.
https://github.com/microsoft/winget-pkgs/issues/1448
I just hope an actual human looks into the issue.

**Comment by SoftCreatR** [comment]
> It will fail validation if you rename a file.

Not directly (see #1730 for example). It fails, because you modified two files in one PR, as i wrote already.

**Comment by denelon** [comment]
Is this issue resolved?

**Comment by Naomi010Sentzke** [comment]
@denelon yup it is.
