### ISSUE TITLE
[Package Issue]: JRSoftware.InnoSetup

### ISSUE THREAD

**Issue by bdovaz** [microsoft/winget-pkgs#170762]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

#119886 added the missing user scope but also changed the default behavior and is that the installation if you do not pass the `--scope machine` parameter explicitly, it does it with `user` and this behavior was not so until it was changed in this PR.

### Steps to reproduce

`winget install JRSoftware.InnoSetup`.

It installs with `user` scope when before the mentioned PR it did it with `machine`.

### Actual behavior

Do not change the default scope that has been changed.

### Expected behavior

Keep the default scope as `machine`.

### Environment

```raw
Windows: Windows.Desktop v10.0.22631.4112
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Update contents of https://github.com/microsoft/winget-pkgs/pull/170764#issue-2497106263 with "closing keyword" `Resolve #170762` will help linking the pull request with this issue. When pull request is successfully merged, this issue will also be closed as completed automatically.

**Comment by bdovaz** [comment]
@Trenly are you aware that in #214891 you reverted my PR #170764?

https://github.com/microsoft/winget-pkgs/pull/214891/files#diff-ee1829d61b7db5f164787544e9bac09310ba67dbd64e6f4e3d729171d4455361L7

Read this issue to see the motivation for why I added the default scope `machine`.

**Comment by Trenly** [comment]
@bdovaz - I was not aware, but after looking through the code at CLI, I don’t see how it makes a difference?

Adding an item at the root of the manifest does not make it the default **selection** for the CLI to use. Instead - it makes it the default **value** that is applied to all of the installer nodes. This value is then overridden by the values at the installer nodes. The value at the root node does not have any effect if the same parameter is specified within the installer nodes.
