### ISSUE TITLE
[Package Request]: youtube-dl nightly

### ISSUE THREAD

**Issue by rougeaden** [microsoft/winget-pkgs#171049]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/ytdl-org/ytdl-nightly
Publisher: ytdl-nightly 
Package Name: youtube-dl
Description: Nightly builds for youtube-dl. 
Package Version: 2024.08.07
Installer URL: https://github.com/ytdl-org/ytdl-nightly/releases/download/2024.08.07/youtube-dl.exe

**Comment by stephengillie** [comment]
- Caveat: https://github.com/microsoft/winget-pkgs/issues/163098
