### ISSUE TITLE
[Package Request]: TechPowerUp.ThrottleStop version 9.6

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#171060]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

 | Key               | Value                                                                                                                                                           |
 | :----             | :------                                                                                                                                                         |
 | Download Page URL | <https://www.techpowerup.com/download/techpowerup-throttlestop/>                                                                                                |
 | Publisher         | TechPowerUp                                                                                                                                                     |
 | Package Name      | ThrottleStop                                                                                                                                                    |
 | Description       | ThrottleStop is a small application designed to monitor for and correct the three main types of CPU throttling that are being used on many laptop computers. |
 | Package Version   | 9.6                                                                                                                                                             |
 | Installer URL     | <https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip>                                                                   |

```[tasklist]
### Tasks
- [x] #171061 
```

**Comment by sarahsevee** [comment]
Hey @Dragon1573,

if you have a look at other TechPowerUp packages, you will notice, if you use a direct url like: https://sg1-dl.techpowerup.com/files/ThrottleStop_9.6.zip for winget packages is fine.

TechPowerUp has a specific allowance for winget useragent, but will show error 404 in the browser.

See discussion in pr: https://github.com/microsoft/winget-pkgs/pull/150500

Hope this helps :smile:

**Comment by Dragon1573** [comment]
> If you have a look at other TechPowerUp packages, you will notice, if you use a direct url like: https://sg1-dl.techpowerup.com/files/ThrottleStop_9.6.zip for winget packages is fine.
> 
> TechPowerUp has a specific allowance for winget useragent, but will show error 404 in the browser.
> 
> See discussion in pr: https://github.com/microsoft/winget-pkgs/pull/150500

Thanks a lot. :heart:

CC @stephengillie should I re-create the PR?

**Comment by stephengillie** [comment]
> CC @stephengillie should I re-create the PR?

Yes, please do.

**Comment by Dragon1573** [comment]
Branches of pull request #171061 is successfully restored. PR is re-opened.
