### ISSUE TITLE
[Update Request]: 3CX.Softphone

### ISSUE THREAD

**Issue by Tehpaartos** [microsoft/winget-pkgs#171107]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

3CX.Softphone

### Package Version

18.13.959

### Please describe the changes you would like to see

Support for Machine scope

This installer itself supports deploying the 3CX Softphone in the machine scope, however, the 3CX.Softphone.installer.yaml is limited to user scope.  

Can this package be extended to the also include the machine scope to better suite SOE deployments?

**Comment by Dragon1573** [comment]
Could you please explain how `*.msi` is provided on their servers? I can only navigate to _Microsoft Store_ from `PackageUrl`.
