### ISSUE TITLE
[Update Request]: Move MapTiler.MapTilerDesktop to MapTiler.MapTilerEngine

### ISSUE THREAD

**Issue by kudlav** [microsoft/winget-pkgs#171381]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

MapTiler.MapTilerDesktop

### Package Version

all

### Please describe the changes you would like to see

Created PRs moving to new identifier:

 - https://github.com/microsoft/winget-pkgs/pull/171364
 - https://github.com/microsoft/winget-pkgs/pull/171365
 - https://github.com/microsoft/winget-pkgs/pull/171366
 - https://github.com/microsoft/winget-pkgs/pull/171367
 - https://github.com/microsoft/winget-pkgs/pull/171368
 - https://github.com/microsoft/winget-pkgs/pull/171369
 - https://github.com/microsoft/winget-pkgs/pull/171370
 - https://github.com/microsoft/winget-pkgs/pull/171371
 - https://github.com/microsoft/winget-pkgs/pull/171372
 - https://github.com/microsoft/winget-pkgs/pull/171373
 - https://github.com/microsoft/winget-pkgs/pull/171374
 - https://github.com/microsoft/winget-pkgs/pull/171375
 - https://github.com/microsoft/winget-pkgs/pull/171376
 - https://github.com/microsoft/winget-pkgs/pull/171377
 - https://github.com/microsoft/winget-pkgs/pull/171378
 - https://github.com/microsoft/winget-pkgs/pull/171379

Created using [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md) Move mode (6).

**Comment by stephengillie** [comment]
All of the PRs are completed, so I'll assume this PR is too. If this is in error, please @ me and I'll reopen.
