### ISSUE TITLE
[Update Request]:  IDRIX.VeraCrypt 1.26.15

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#171450]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IDRIX.VeraCrypt

### Package Version

1.26.15

### Please describe the changes you would like to see

```
1.26.15 (September 2nd, 2024):

    Windows:
        Fix MSI install/uninstall issues:
            Fixed error 1603 returned by MSI silent install when REBOOT=ReallySuppress is specified and a reboot is required.
            Fixed missing documentation and language files from the MSI package.
            Fixed MSI not installing new documentation and language files when upgrading from an EXE-based installation.
            Fixed installation folder not being removed after MSI uninstall in some cases.
        Fix regression during UEFI system decryption that caused the bootloader to persist.

```

**Comment by R-Adrian** [comment]
edit: scratch that.... 1.26.15 is released as a "nightly" not stable... but is mentioned in the release notes.
https://veracrypt.fr/en/Release%20Notes.html

**Comment by JustMyGithub** [comment]
@R-Adrian I do not see "nightly" on that page, even 4 days ago https://web.archive.org/web/20240903152957/https://veracrypt.fr/en/Release%20Notes.html

**Comment by R-Adrian** [comment]
when i saw the files trhey were placed in their "nightly" folder on Sourceforge
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/Windows/

but since then they seem to have graduated it to a stable
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%201.26.15/Windows/

**Comment by R-Adrian** [comment]
(since it is now "stable" i guess i should re-open this?)
