### ISSUE TITLE
[Update Request]: scrcpy

### ISSUE THREAD

**Issue by 7wells** [microsoft/winget-pkgs#171430]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

scrcpy

### Package Version

2.6.1

### Please describe the changes you would like to see

There is a new version available. Download releases: https://github.com/Genymobile/scrcpy/releases/

**Comment by Dragon1573** [comment]
- Duplicated #166969 
- Will be resolved by #165921

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #166969;
