### ISSUE TITLE
[Package Request]: Foxit PDF Editor with MSI Installer

### ISSUE THREAD

**Issue by ChristianOe** [microsoft/winget-pkgs#171403]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.foxit.com/downloads
Publisher: Foxit Software Inc.
Package Name: Foxit.Phantom.PDF.Subscription
Description: Powerful desktop PDF solution to create and edit PDF documents and integrate with Foxit eSign.
Package Version: 2024.2.3.25184
Installer URL: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2024.2.3/FoxitPDFEditor202423_L10N_Setup.msi

**Comment by Utesgui** [comment]
Package Version already in Winget:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/Foxit/PhantomPDF/Subscription/2024.2.3.25184
https://github.com/microsoft/winget-pkgs/pull/166082

**Comment by ChristianOe** [comment]
@Utesgui You are right. But I like to extend this version with the msi installer from the url I provided. Can you improve it?

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/171408

**Comment by a-mnich** [comment]
@ChristianOe out of pure curiosity: What is your scenario where the MSI installer is preferred or respectively what is the advantage of the MSI installer in this case?

**Comment by ChristianOe** [comment]
@a-mnich you can customize the installation with an .mst file or with more msi switches. This is why I prefere always the .msi file. In addition a detection of the installation is much easier and have good standards.

**Comment by SpecterShell** [comment]
@ChristianOe Which MSI switches are you going to use?

The manifests I just submit use a different installer, which contains the original MSI installer you have mentioned and all the MST files, so it will choose the locale and apply the MST file automatically. It has the same ARP entries as the MSI installer, but the switches might be different (The EXE bootstrapper does not pass all the switches to the inner MSI installer).

**Comment by ChristianOe** [comment]
@SpecterShell 
The best way for me is the installer from foxit with the url https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2024.2.3/FoxitPDFEditor202423_L10N_Setup.msi

Foxit use the same URL like the exe Installer. Only at the end they changed it to .msi

**Comment by SpecterShell** [comment]
> @SpecterShell The best way for me is the installer from foxit with the url [cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2024.2.3/FoxitPDFEditor202423_L10N_Setup.msi](https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2024.2.3/FoxitPDFEditor202423_L10N_Setup.msi)
> 
> Foxit use the same URL like the exe Installer. Only at the end they changed it to .msi

Added in https://github.com/microsoft/winget-pkgs/pull/171516

The package will use the MSI installer under English locale and the EXE one under other locales. To force to use the MSI one, append `--installer-type wix` to the WinGet command line.
