### ISSUE TITLE
[Update Request]: 1Password CLI

### ISSUE THREAD

**Issue by jrdodds** [microsoft/winget-pkgs#171668]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AgileBits.1Password.CLI

### Package Version

2.30.0

### Please describe the changes you would like to see

As of July 29, 2024, there is a new release available: 2.30.0. (Winget has only 2.29.0)

Release Notes:
https://app-updates.agilebits.com/product_history/CLI2

**Comment by Dragon1573** [comment]
- Related #165372
