### ISSUE TITLE
[Package Request]: Microsoft Authentication CLI

### ISSUE THREAD

**Issue by keyuxuan** [microsoft/winget-pkgs#171982]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/AzureAD/microsoft-authentication-cli/releases/tag/0.8.6
Publisher: https://github.com/AzureAD/microsoft-authentication-cli
Package Name: Microsoft Authentication CLI
Description: AzureAuth is a CLI wrapper for performing AAD Authentication. It makes use of [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) for authentication and caching. The CLI is designed for authenticating and returning an access token for public client AAD applications. This acts like a credential provider for Azure Devops and any other [public client app](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications).

Package Version: 0.8.6
Installer URL: https://github.com/AzureAD/microsoft-authentication-cli/releases/download/0.8.6/azureauth-0.8.6-win10-x64.zip

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/zip-binary
>
> There're external DLLs required for the executable, they are not supported by symlinks.
>
> ```text
> --> Installing WinGet
> --> Disabling safety warning when running installer
> Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.
> 
> --> Configuring Winget
> Enabled admin setting 'LocalManifestFiles'.
> Enabled admin setting 'LocalArchiveMalwareScanOverride'.
> 
> --> Installing the Manifest 0.8.6
> 
> Found Microsoft Authentication CLI [Microsoft.Authentication.CLI] Version 0.8.6
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://github.com/AzureAD/microsoft-authentication-cli/releases/download/0.8.6/azureauth-0.8.6-win10-x64.zip
>   ██████████████████████████████  35.6 MB / 35.6 MB
> Successfully verified installer hash
> Extracting archive...
> Successfully extracted archive
> Starting package install...
> Command line alias added: "azureauth"
> Path environment variable modified; restart your shell to use the new value.
> Successfully installed
> 
> --> Refreshing environment variables
> 
> --> Comparing ARP Entries
> 
> DisplayName                  DisplayVersion Publisher             ProductCode                                 Scope
> -----------                  -------------- ---------             -----------                                 -----
> Microsoft Authentication CLI 0.8.6          Microsoft Corporation Microsoft.Authentication.CLI__DefaultSource User
> 
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> azureauth.exe --version
> The application to execute does not exist: 'C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links\azureauth.dll'.
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Authentication.CLI__DefaultSource\azureauth.exe --version
> 0.8.6.0
> ```
