### ISSUE TITLE
[Package Issue]: Daum.PotPlayer

### ISSUE THREAD

**Issue by drshtmstry** [microsoft/winget-pkgs#172064]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

This package uses vanity url and has version information in "File version" property of installer exe.
@wingetbot currently not submitting automated update PRs for this package.

### Steps to reproduce

`winget install daum.potplayer`

### Actual behavior

Installer hash mismatch

### Expected behavior

@wingetbot should submit automated PRs when hash changes.

### Environment

```raw
PS C:\Users\drsht> winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4112
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![Screenshot 2024-09-06 205708](https://github.com/user-attachments/assets/ad619814-d9df-4f86-8240-3efc08a517fa)
![Screenshot 2024-09-06 210149](https://github.com/user-attachments/assets/c061324f-8c36-4374-b0b5-6ce4025dc3b9)

**Comment by drshtmstry** [comment]
https://github.com/microsoft/winget-pkgs/pull/172065

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue already resolved. Should be closed as completed.

**Comment by drshtmstry** [comment]
> Note
> 
> Issue already resolved. Should be closed as completed.

Not resolved because issue is about @wingetbot not submitting automated PR for updates.

**Comment by Dragon1573** [comment]
Maybe it's related to bot accounts ...

Suggested policy: https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Area-Bots

**Comment by slrgt** [comment]
im still getting this error `Installer hash does not match.`

**Comment by drshtmstry** [comment]
> im still getting this error `Installer hash does not match.`

- #172745
