### ISSUE TITLE
[Update Request]: Nikse.SubtitleEdit version 4.0.8.0

### ISSUE THREAD

**Issue by niksedk** [microsoft/winget-pkgs#172042]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Nikse.SubtitleEdit

### Package Version

4.0.8.0

### Please describe the changes you would like to see

There is a new release available: Nikse.SubtitleEdit version 4.0.8.0

Release page:
https://github.com/SubtitleEdit/subtitleedit/releases/tag/4.0.8

PR:
https://github.com/microsoft/winget-pkgs/pull/172041

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Add `Resolve #172042` to https://github.com/microsoft/winget-pkgs/pull/172041#issue-2509858112 can help linking that pull request to this issue. When pull request is successfully merged, this issue will also be closed automatically.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This issue is already resolved by pull request #172038. This pull request should be closed as completed.
>
> - #172038
