### ISSUE TITLE
[Package Issue]: JetBrains.Rider

### ISSUE THREAD

**Issue by PingvinB** [microsoft/winget-pkgs#172049]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installing JetBrains.Rider package with `--silent` option uses "Program Files (x86)" as installation destination. 

Appending `--architecture x64` does not do anything since the installer does not provide architecture information as far as I understand.

If the installer is run with `--interactive` instead, it chooses "Program Files" (see screenshot) as the default installation destination. 

```pwsh
> winget show JetBrains.Rider
Found JetBrains Rider [JetBrains.Rider]
Version: 2024.2.2
Publisher: JetBrains s.r.o.
...
Installer:
  Installer Type: nullsoft
  Installer Url: https://download.jetbrains.com/rider/JetBrains.Rider-2024.2.2.exe
  Installer SHA256: 575792e9b670cbfca5b75164e68579776b469bda4e2d76f7b3c2bc2c6a83624b
  Release Date: 2024-08-26
  Offline Distribution Supported: true
```

### Steps to reproduce

Run `winget install JetBrains.Rider --silent`

### Actual behavior

JetBrains.Rider gets installed in "C:\Program Files (x86)\JetBrains\Rider"

### Expected behavior

JetBrains.Rider gets installed in "C:\Program Files\JetBrains\Rider"

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4780
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![rider-installer](https://github.com/user-attachments/assets/abea6861-f663-427d-bc7d-3ee3d91dde6d)
[WinGet-JetBrains.Rider.2024.2.2-2024-09-03-16-30-43.310.log](https://github.com/user-attachments/files/16906577/WinGet-JetBrains.Rider.2024.2.2-2024-09-03-16-30-43.310.log)

**Comment by Trenly** [comment]
This seems to be the default behavior of the installer. When WinGet installs with the `/silent` switch, it is the same as if you downloaded the exe yourself and ran it from the command line with `/verysilent`. In this case, it doesn't seem like WinGet is specifying the default location.

[Policy] Installer Issue
