### ISSUE TITLE
[Update Request]: Microsoft.TeamMate 0.1.11

### ISSUE THREAD

**Issue by supermem613** [microsoft/winget-pkgs#172083]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.TeamMate

### Package Version

0.1.11

### Please describe the changes you would like to see

There is a new release (0.1.11) available at https://github.com/microsoft/TeamMate/releases/download/0.1.11-ci.2%2BBranch.main.Sha.6afd16e57956851810e31ec29df9fb85cce6ee31/Microsoft.Tools.TeamMate.msi

**Comment by supermem613** [comment]
#172082 Linking pR

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Issue is already resolved. Should be closed as completed.
>
> - #172082

**Comment by stephengillie** [comment]
> Note
> 
> Issue is already resolved. Should be closed as completed.
> 
> * [Microsoft.TeamMate version 0.1.11 #172082](https://github.com/microsoft/winget-pkgs/pull/172082)
