### ISSUE TITLE
[Update Request]: simplewall

### ISSUE THREAD

**Issue by 3xploiton3** [microsoft/winget-pkgs#172124]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

simplewall

### Package Version

3.8.3

### Please describe the changes you would like to see

https://github.com/henrypp/simplewall/releases

**Comment by Dragon1573** [comment]
There used to be in progress, but the installer file had been flagged by _Microsoft Defender SmartScreen_. I'll try if this false-positive is already resolved.

- https://github.com/microsoft/winget-pkgs/pull/166831#issuecomment-2277794921
- https://github.com/microsoft/winget-pkgs/pull/166831#issuecomment-2278605545

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_. A new pull request will be submitted.

![image](https://github.com/user-attachments/assets/7aaf35f3-1613-432c-9b2b-8926910eab74)

**Comment by Dragon1573** [comment]
There's still false-positive. 😞 Issue should be closed as not planned.

Suggested policy: https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Validation-SmartScreen-Error
