### ISSUE TITLE
[Package Request]: WavePad

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#172347]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.nch.com.au/wavepad/index.html
Publisher: NCHSoftware
Package Name: WavePad
Description: Fully featured professional audio and music editor.
Package Version: 19.50
Installer URL: https://www.nch.com.au/components/wpsetup.exe

**Comment by Dragon1573** [comment]
Unable to inspect the technology of the installer file. Seems it does not support unattended installation.

**Comment by AsciiWolf** [comment]
@Dragon1573 I guess it will be similar to the [already existing](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NCHSoftware) ones.
