### ISSUE TITLE
Make the bot tell us what the problem was

### ISSUE THREAD

**Issue by jazzdelightsme** [microsoft/winget-pkgs#1727]
# Description of the new feature/enhancement
The bot could be a lot more helpful.

As it is today, if it finds a problem, it leaves a comment saying so. But then it wants me to do some mind reading to figure out what problem the bot found.

How about if the bot just tells us what the actual problem was.

An example of the current bot output, which gives some hints, but won't just tell me the problem:

>Here are some common causes for this failure you should consider:

> The Sha256 HASH in the manifest does not match the HASH of the installer. Run winget hash to generate the hash.
> The URL is not valid. Make sure the URL to the installer is publicly available and valid.
> The installer has been identified as malware. If the installer is detected as malware, you can submit the installer to the defender team for analysis as a potential false positive.

**Comment by SoftCreatR** [comment]
Just open one of the failed checks.

For example: https://github.com/microsoft/winget-pkgs/pull/256 => https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=86314&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d

> Error occurred during installer copy from https://files.kde.org/kdenlive/release/kdenlive-20.04.1.exe.
> A redirected response (HTTP status code 302) from the copy source is not supported.

Solution: Use this proxy URL instead

`https://www.winget.it/dl/481377d68167726f5e90425b885e5a544d9589281407713d2a68ef87c104c8ca/https%3A%2F%2Ffiles.kde.org%2Fkdenlive%2Frelease%2Fkdenlive-20.04.1.exe`

**Comment by jazzdelightsme** [comment]
I understand that the information exists somewhere else. This Issue is to say the bot could tell us the information.

Perhaps it would be helpful to add the information you gave--that more details can be found in the checks at the bottom of the page. For example, "the package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue. **For more information, click on the "details" links for the failed checks at the bottom of the page.**"

**Comment by denelon** [comment]
We are working on exposing all of the low level issues at the PR level.

**Comment by denelon** [comment]
A couple of new labels were added and the build pipeline will now add those to PRs that fail. The two new areas are a timeout (>25 hours from static analysis start) and Installer-Unavailable for HTTP errors (404, redirects, range requests not supported).

**Comment by denelon** [comment]
This should be resolved now.
