### ISSUE TITLE
[Package Request]: Bforartists

### ISSUE THREAD

**Issue by anderlli0053** [microsoft/winget-pkgs#172862]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.bforartists.de/download/#bfa2dev
Publisher: **Bforartists team**
Package Name: Bforartists
Description: `All in one, Free and Open Source 3D creation`
`Bforartists is a complete, free and opensource 3D suite to create CG content. It offers you the full 3D art pipeline to create game graphics, pre-rendered movies and stills. From modeling, sculpting, texturing, rigging, animation, rendering, up to post processing. `
```
Bforartists stands for “Be For Artists”. A reminder to develop for the user, not the programmer!
Bforartists is a fork of the popular open source 3D software Blender. Developed by some 3D enthusiasts to make Blender even better.
```
Package Version: **4.2.2**
Installer URL: https://www.bforartists.de/download/#bfa2dev

**Comment by Dragon1573** [comment]
Manually validated in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/cf0940cd-e653-42ce-81de-b55a24a9be1c)
