### ISSUE TITLE
[Package Request]: Add Debug Diagnostic Tool v2 Update 3

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/winget-pkgs#172870]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.microsoft.com/en-us/download/details.aspx?id=58210
Publisher: Microsoft
Package Name: Microsoft.DebugDiag
Description: "The Debug Diagnostic Tool (DebugDiag) is designed to assist in troubleshooting issues such as hangs, slow performance, memory leaks or memory fragmentation, and crashes in any user-mode process."
Package Version: 2.3
Installer URL: https://download.microsoft.com/download/5/2/8/52862D92-0128-4957-AB9F-2FFED4E036E9/DebugDiagx64.msi

**Comment by Dragon1573** [comment]
Validated in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/92cf0f86-51db-41c2-9af0-0dd95b83fa2b)

**Comment by MagicAndre1981** [comment]
thanks. Where is the PR? The version number is 1 time .37 and 1 time .38
