### ISSUE TITLE
[Update Request]: TheDocumentFoundation.LibreOffice version 24.2.6

### ISSUE THREAD

**Issue by GMarcoSettantadue** [microsoft/winget-pkgs#173228]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TheDocumentFoundation.LibreOffice

### Package Version

24.2.6

### Please describe the changes you would like to see

The previous stable branch of LibreOffice, which we are still maintaining until November 2024.

**Comment by Dragon1573** [comment]
Manually validated in _Windows Sandbox_. A local file server (provided by _Alist_) is used for acceleration.

![image](https://github.com/user-attachments/assets/ee3588e9-3530-4f8c-997c-b0f7407fdb13)
