### ISSUE TITLE
[Update Request]: Fixing incorrect hash for QuadSpinner.Gaea v2.0.4.0

### ISSUE THREAD

**Issue by daxpandhi** [microsoft/winget-pkgs#173368]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

QuadSpinner.Gaea

### Package Version

2.0.4.0

### Please describe the changes you would like to see

The hash for the installer was incorrect as the installer was changed after the dumpling bot (not sure what that is?!) generated this manifest for our application. (I'm the owner of the QuadSpinner.Gaea application). We reissued the installer on our server but this manifest was generated before we could manually submit our own. This is to fix the bad hash. All else is fine.

Related Pull Request: #173367

**Comment by Dragon1573** [comment]
@daxpandhi - Is it already fixed by #173367 by yourself? Should this issue be closed as "completed"?

**Comment by daxpandhi** [comment]
Yes! Sorry forgot to close the issue. Oops.
