### ISSUE TITLE
[Update Request]: SomePythonThings.WingetUIStore

### ISSUE THREAD

**Issue by Strong-pwned** [microsoft/winget-pkgs#173379]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

SomePythonThings.WingetUIStore

### Package Version

All

### Please describe the changes you would like to see

**Suggested new package identifier:**
`MartiCliment.UniGetUI`

**Motivation:**
- The official publisher and author of the app is Martí Climent, not "SomePythonThings".
- The official name of the app is UniGetUI, not WingetUI.

**Compatibility:**
Anyone searching for the old name (`winget search wingetui`) will find the new name, since the package name and tags already have the old name:
https://github.com/microsoft/winget-pkgs/blob/f490e2c726a9aec4497822708c181673f2c0f6e8/manifests/s/SomePythonThings/WingetUIStore/3.1.1/SomePythonThings.WingetUIStore.locale.en-US.yaml#L11
https://github.com/microsoft/winget-pkgs/blob/f490e2c726a9aec4497822708c181673f2c0f6e8/manifests/s/SomePythonThings/WingetUIStore/3.1.1/SomePythonThings.WingetUIStore.locale.en-US.yaml#L30-L31

**Additional information:**
Official repository (the app is written in C#, not Python):
https://github.com/marticliment/UniGetUI/
Official website (mentioned in the repository):
https://www.marticliment.com/unigetui/

This is referenced in the manifest file itself:
https://github.com/microsoft/winget-pkgs/blob/f490e2c726a9aec4497822708c181673f2c0f6e8/manifests/s/SomePythonThings/WingetUIStore/3.1.1/SomePythonThings.WingetUIStore.locale.en-US.yaml#L7-L16

**Comment by vikingnope** [comment]
@marticliment would you agree with this change, or would you suggest leaving it as is?

**Comment by marticliment** [comment]
Yes, it definitely makes sense to make the change

**Comment by vikingnope** [comment]
@marticliment do you think we should remove previous WingetUI in total and just start the packages from the beginning not including any previous version of WingetUI (i.e. only including UniGetUI), or should we keep WingetUI here, and just create a new one for UniGetUI?

**Comment by marticliment** [comment]
Ideally it would be better to follow option 1, to prevent confusion, but I don't know if it is _feasible_ and _acceptable_ to delete an entire package and then publish it again with different names. Having that said, either if it ends up being option 1 or 2 it will be ok for me.

**Comment by vikingnope** [comment]
@stephengillie, would you suggest option 1 or 2 based on Marti's feedback?

**Comment by stephengillie** [comment]
I agree with @ marticliment that the first option is better. While it would be possible for us to continue offering `WinGetUI` as a historical record, I'm not sure how much demand there is for it. 

A third possible option could be leaving the manifests before the name change as-is, and only moving the post-rename manifests. This could reduce workload while also preserving the older manifest versions.

> [!note]
>
> Moving packages from one `PackageIdentifier` to another can be a lot of work. Foreach manifest version, 2 PRs are needed - one to add new and one to remove old. This process always winds up having some level of coordination between the submitter and a moderator to approve, and with the appropriate preparation can go very smoothly.

**Comment by vikingnope** [comment]
> I agree with @ marticliment that the first option is better. While it would be possible for us to continue offering `WinGetUI` as a historical record, I'm not sure how much demand there is for it.
> 
> A third possible option could be leaving the manifests before the name change as-is, and only moving the post-rename manifests. This could reduce workload while also preserving the older manifest versions.
> 
> Note
> 
> Moving packages from one `PackageIdentifier` to another can be a lot of work. Foreach manifest version, 2 PRs are needed - one to add new and one to remove old. This process always winds up having some level of coordination between the submitter and a moderator to approve, and with the appropriate preparation can go very smoothly.


So what I will do is follow what you suggested which is to create the new manifest then remove the old one. 😊

**Comment by vikingnope** [comment]
I will continue the rest when these commit just to make sure everything is correct

**Comment by marticliment** [comment]
Assuming we chose to delete the old manifests and just start from scratch (Option 1), would it be possible to delete all the manifests in one single PR? Or we'd still need to do one manifest at a time?

> I don't think `WingetUI` is still in demand since most people always want the latest version, which in this case is `UniGetUI`

I agree,  and all the installers for older versions are still (and will be) available on GitHub, so installing older versions shouldn't be an issue.

**Comment by vikingnope** [comment]
> Assuming we chose to delete the old manifests and just start from scratch (Option 1), would it be possible to delete all the manifests in one single PR? Or we'd still need to do one manifest at a time?

They will have to be removed in separate PRs one-by-one but that is easy with Komac, the hardest part is transferring all of them because they have to be done manually

**Comment by vikingnope** [comment]
When these are committed I will start removing all the packages from `SomePythonThings.WingetUI`

**Comment by vikingnope** [comment]
Multiple PRs have been scheduled so that this can be completed

**Comment by vikingnope** [comment]
Not entirely finished, still a bit more to go

**Comment by vikingnope** [comment]
This has officially been completed, I thank you all for your patience. :)
