### ISSUE TITLE
[Package Request]: Filezilla

### ISSUE THREAD

**Issue by 44rk33** [microsoft/winget-pkgs#173955]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://dl2.cdn.filezilla-project.org/client/FileZilla_3.67.1_win64-setup.exe?h=UA3Fz5Ep5PnA1-wxowvnvw&x=1726599548
Publisher:Filezilla
Package Name:FileZilla Client
Description:ftp client
Package Version:3.67.1
Installer URL:https://dl2.cdn.filezilla-project.org/client/FileZilla_3.67.1_win64-setup.exe?h=UA3Fz5Ep5PnA1-wxowvnvw&x=1726599548

**Comment by R-Adrian** [comment]
please search the history of Filezilla in the issues here before...

The author of Filezilla and its distribution license epressly DENIES the use of WinGet to leech bandwidth from their site.
Also the app itself is handling updates automatically on its own.

see https://github.com/microsoft/winget-pkgs/issues/78578
and https://github.com/ScoopInstaller/Extras/issues/9179

**Comment by Trenly** [comment]
Close with reason: Denied by license;

**Comment by binarygeek119** [comment]
https://github.com/microsoft/winget-pkgs/issues/154585#issuecomment-2484210085
