### ISSUE TITLE
[Package Issue]: Tableau Public [Tableau.Public] Version 24.2.931

### ISSUE THREAD

**Issue by voyager2saturn** [microsoft/winget-pkgs#174133]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

This package was working previously but unable to install now.
Package id = Tableau.Public
Other packages are working (eg. Chrome)

### Steps to reproduce

winget install Tableau.Public

### Actual behavior

Downloading https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2024-2-2.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).

### Expected behavior

Download the latest package and install

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4169
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![image](https://github.com/user-attachments/assets/8fca5df1-d881-49c7-bd29-8471182dc5d8)

**Comment by stephengillie** [comment]
Unfortunately I wasn't able to reproduce this error. The download worked normally in my browser, and installing the manifest in #168507 resulted in: 
![image](https://github.com/user-attachments/assets/de076760-7285-488d-bc32-60fbbcaaf0ba)

**Comment by Dragon1573** [comment]
Successfully reproduced in _PowerShell Core 7_ and _Motrix_.

```text
**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.10.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
12:12:02 D:\Workloads 1.886s pwsh> (iwr -Uri 'https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2024-2-2.exe' `
> -UserAgent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0' `
> -Method Head).StatusCode
Invoke-WebRequest: Response status code does not indicate success: 403 (Forbidden).
```

![image](https://github.com/user-attachments/assets/68ad3e08-578d-4470-b5bf-23d1f3bf3cae)

But it's available by _Microsoft Edge_ itself.

![image](https://github.com/user-attachments/assets/cda6df2e-bff4-4873-88ee-8a03a9e01b10)

Seems the download server blocks third-party downloader (for preventing automatic downloading action by bots or high-speed downloading action by third-party downloader).

**Comment by SpecterShell** [comment]
This might get fixed by using a preview version of WinGet client. Tableau servers have a weird blocking strategy.

**Comment by voyager2saturn** [comment]
It is working now
