### ISSUE TITLE
[Package Request]: ComicRack-CE Nightly

### ISSUE THREAD

**Issue by killo3967** [microsoft/winget-pkgs#174149]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/maforget/ComicRackCE
Publisher: maforget
Package Name: ComicRack Community Edition
Description: Comic Management Software
Package Version: Nightly
Installer URL: https://github.com/maforget/ComicRackCE/releases/download/nightly/ComicRackCESetup_nightly.exe

**Comment by killo3967** [comment]
Sorry but you make an error, it isn't "maforhet" it's "maforget".

Publisher: maforget

**Comment by maforget** [comment]
Developer here, also the version number and the folder you created `nightly-9745855` is the commit sha from Github, does it mean that someone will need to update it for every release or will the bot take care of it?

**Comment by vikingnope** [comment]
> Sorry but you make an error, it isn't "maforhet" it's "maforget".
> 
> Publisher: maforget

This fixes it: https://github.com/microsoft/winget-pkgs/pull/174724, https://github.com/microsoft/winget-pkgs/pull/174723

**Comment by vikingnope** [comment]
> Developer here, also the version number and the folder you created `nightly-9745855` is the commit sha from Github, does it mean that someone will need to update it for every release or will the bot take care of it?
> 
> The version and SHA256 will change on every push I do. Do I need to add something in my build workflow to update it?

Yes that will have to be done as that is what was recommended by the developer, but we can add it to one of your workflows, let me check it out
