### ISSUE TITLE
[Update Request]: Git.MinGit v2.46.1

### ISSUE THREAD

**Issue by ardislu** [microsoft/winget-pkgs#174209]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Git.MinGit

### Package Version

2.46.1

### Please describe the changes you would like to see

There have been the following releases since the last update request (#152319):
May 14, 2024 - 2.45.1 - https://github.com/git-for-windows/git/releases/tag/v2.45.1.windows.1
June 3, 2024 - 2.45.2 - https://github.com/git-for-windows/git/releases/tag/v2.45.2.windows.1
July 29, 2024 - 2.46.0 - https://github.com/git-for-windows/git/releases/tag/v2.46.0.windows.1
September 18, 2024 - 2.46.1 - https://github.com/git-for-windows/git/releases/tag/v2.46.1.windows.1

Also: I see `Git.Git` is updated relatively promptly. `Git.MinGit` is released from the same repo as `Git.Git`. Is there a way to combine updates so anytime `Git.Git` is updated, `Git.MinGit` is updated too?

**Comment by vedantmgoyal9** [comment]
Will do.

**Comment by symbiogenesis** [comment]
@vedantmgoyal9 Git.MinGit is not updated to 4.27 so something with the automation might need fixing.
