### ISSUE TITLE
[Package Request]: Mythicsoft AgentRansack

### ISSUE THREAD

**Issue by mattl135** [microsoft/winget-pkgs#174330]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.mythicsoft.com/agentransack/download/
Publisher: Mythicsoft Ltd
Package Name: Agent Ransack
Description: Free File Searching Utility
Package Version: 9.2.3435.1
Installer URL: https://download.mythicsoft.com/flp/3435/agentransack_3435.exe

**Comment by mattl135** [comment]
Application removed from Winget manifest a couple days ago when installer URL started returning 400 error codes. Application needs to be added back into the repository with the latest version.

[https://github.com/microsoft/winget-pkgs/pull/173713](https://github.com/microsoft/winget-pkgs/pull/173713)

**Comment by vikingnope** [comment]
Change title of this issue to `[Package Request]: Mythicsoft.AgentRansack`

**Comment by JustMyGithub** [comment]
It seems that this manifest changed the "install technology", so all users that had this installed via winget before (like me) now have to manually update it again - just WHY? The whole point of existance of winget is to NOT have to do EXACTLY THIS?!
