### ISSUE TITLE
[Update Request]: MicroSIP.MicroSIP

### ISSUE THREAD

**Issue by pjjonas** [microsoft/winget-pkgs#174579]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MicroSIP.MicroSIP

### Package Version

3.21.4

### Please describe the changes you would like to see

There is a new release available 3.21.4

Download URL: https://www.microsip.org/download/MicroSIP-3.21.4.exe

**Comment by Dragon1573** [comment]
Verified.

![image](https://github.com/user-attachments/assets/aea73fdd-d992-44b6-8bb3-3d7ae1e16b81)
