### ISSUE TITLE
Anti virus pull requests

### ISSUE THREAD

**Issue by andrewstech** [microsoft/winget-pkgs#17471]
Hi I made a pull request to add AVG antivirus to the Repo. However it was given the label Validation-Defender-Error. This has also happened to 2 other pull requests from 13 days ago. I was wondering if there is a way around this as antivirus such as AVG automatically disable windows defender. 

Pull requests referenced
#17206 
#15803 
#15349

**Comment by mddtest** [comment]
It is already being investigated by @ChuckFerring
