### ISSUE TITLE
[Package Request]: Epos Connect

### ISSUE THREAD

**Issue by jaimetuitorres** [microsoft/winget-pkgs#174729]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.eposaudio.com/contentassets/b79403493cb840ea89ca342e45139a27/eposconnect_7.9.0.47628.exe
Publisher: EPOS
Package Name: EPOS Connect for Windows
Description:  EPOS Connect for Windows gives the end user access to the latest firmware updates and personalized audio device settings. Stay in control with a tool that keeps EPOS headsets and speakerphones work seamlessly with all leading softphones.
Package Version: 7.9.0.47628
Installer URL:

**Comment by a-mnich** [comment]
Hi @jaimetuitorres, the requested package is already available under identifier `EPOS.EposConnect` in version `7.9.0`.
see #174323

**Comment by stephengillie** [comment]
> Hi @jaimetuitorres, the requested package is already available under identifier `EPOS.EposConnect` in version `7.9.0`. see #174323

The `DisplayVersion` matches: `7.9.0.47628`.
