### ISSUE TITLE
[Package Issue]: Sparrow wallet 2.0

### ISSUE THREAD

**Issue by jpph** [microsoft/winget-pkgs#174781]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Issue with the last update package https://github.com/microsoft/winget-pkgs/pull/174663

### Steps to reproduce

update existing 1.9.1 with : winget update sparrow

### Actual behavior

output:
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.

### Expected behavior

should update to 2.0.0

### Environment

```raw
C:\Windows\System32>winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4169
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by Trenly** [comment]
WinGet is performing as expected here. The installer for version 1.9.1 is a `burn` installer, which is a type of `.exe`. The installer for version `2.0.0` is a `wix` installer which is a type of `.msi`. WinGet will not upgrade in this case as the two installer types are incompatible, and the results cannot be guaranteed - user settings could be erased, duplicate versions could be installed, or the entire application could become unusable. To prevent this, WinGet detects that the installer types are different and then asks for you to uninstall the previous version before installing the new one.

You can override this check with `winget install sparrowwallet.sparrow --force`

**Comment by jpph** [comment]
Thank you for the explanation. but I think the error message could be more explanatory, specificaly the "it does not apply to your system or requirements." which is missleading.
So if next release will continue to be msi there will be no more issues.
Thank you for the explanation!
