### ISSUE TITLE
Version number and installer type issuefor 7zip.7zipalpha

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#17484]
https://github.com/microsoft/winget-pkgs/blob/230bbef605f2153c83fbea26cec5702b0f0af036/manifests/7/7zip/7zipAlpha/21.02.00.0/7zip.7zipAlpha.installer.yaml#L56

@ItzLevvie2 If you want to use .msi installers, then .exe type will be useless, as we cannot select installer type now. And if you want to use .exe, you need to remove .msi installer. And,the two type installers seems give different version numbers in ARP. At least .exe installer will show 21.02 alpha, but not 21.02.0.0.
![image](https://user-images.githubusercontent.com/9316590/121840737-6b19f980-cd0f-11eb-9631-b041460fc83d.png)

**Comment by OfficialEsco** [comment]
Tag @ItzLevvie 😁
Ok so i did notice this, we might have to split them into `7zip.7zip.Alpha.msi/exe` if its in a upgrade loop (That should work)
The reason the MSI is at the top is because people over at `winget-cli` would prefer only MSI's, however msi and exe can be in the same manifest for `winget upgrade` purposes

**Comment by ItzLevvie2** [comment]
I made PRs for it: https://github.com/microsoft/winget-pkgs/pull/17503 and https://github.com/microsoft/winget-pkgs/pull/17502.

**Comment by OfficialEsco** [comment]
Hmm
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget list
```
Name                    Id                                           Version           Available   Source
---------------------------------------------------------------------------------------------------------
7-Zip 21.02 alpha (x64) 7-Zip                                        21.02 alpha
7-Zip Alpha             7zip.7zip.Alpha.msi
```
![image](https://user-images.githubusercontent.com/15158490/121881872-1b87fd80-cd10-11eb-9bc7-49225ecabbe5.png)

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/1166

**Comment by lychichem** [comment]
Seems fixed. Thank you @ItzLevvie2

**Comment by OfficialEsco** [comment]
Just did a few tests, now `stable` `7-Zip` `19.00` installed via normal exe shows up as `7-Zip Alpha (exe)` and a update to `7-Zip Alpha` `21.02 alpha`

```
Name                  Id                                           Version          Available   Source
------------------------------------------------------------------------------------------------------
7-Zip Alpha (exe)     7zip.7zip.Alpha.exe                          19.00            21.02 alpha winget
7-Zip                 7zip.7zip                                    19.00.00.0
```

We miiiight have to wait for Channel support?
