### ISSUE TITLE
Some packages should only have the latest version in the manifest

### ISSUE THREAD

**Issue by Witchilich** [microsoft/winget-pkgs#1749]
# Description of the new feature/enhancement
This is in reference to [PDfill](https://github.com/microsoft/winget-pkgs/blob/master/manifests/PlotSoft/PDFill/14.0%20Build%202.yaml). The URL is 
http://www.plotsoft.com/download/PDFill_X64.msi
It always points to the latest version of the app. Once 15.0 Build 1 arrives, you wont be able to use 14.0 Build 2.

# Proposed technical implementation details (optional)
Apps like PDFill should only have the latest version available for download in the manifest.

**Comment by SoftCreatR** [comment]
As of now, that's up to people like you and me ;) Simply create a PR to remove outdated manifests (one by one).

I have to admit, that i forgot about this problem (which exists in multiple applications), but I'll take care of it in my future releases.

**Comment by Restia666Ashdoll** [comment]
There are also many apps that delete older versions beyond a certain point. There can be a flag to define how many older versions can exist, 0 means only latest version, -1 means there is no limit.

**Comment by OfficialEsco** [comment]
PDFill shows all their files in http://www.plotsoft.com/download
According to my testing http://www.plotsoft.com/download/PDFill_4_0.msi is the same version as http://www.plotsoft.com/download/PDFill_X64.msi, the program even runs in 32bit..

I think atleast some programs should keep their major older installers, incase the newer ones starts adding bloatware

Every small patch of HeidiSQL Nightly is definitively not needed tho =D

**Comment by Restia666Ashdoll** [comment]
@OfficialEsco Ok this is weird. The latest version is 14.0, not 4.0. That page only used to have 1.0 - 4.0, while later versions on the general link. All links were replaced on 2020-04-25. Do a hash check and 1.0 - 4.0 are the same as 14.0.
http://www.plotsoft.com/download/PDFill_1_0.msi
http://www.plotsoft.com/download/PDFill_2_0.msi
http://www.plotsoft.com/download/PDFill_3_0.msi
http://www.plotsoft.com/download/PDFill_4_0.msi
These are all same. Even the 32-bit
http://www.plotsoft.com/download/PDFill_X32.msi
Its the same file
I think when 15.0 arrives I will replace them with
http://www.plotsoft.com/download/PDFill_FREE_PDF_Editor_Basic.msi
This contains both 32-bit and 64-bit.
```
Id: PlotSoft.PDFill
Version: 15.0 Build 1
Name: PDFill
Publisher: PlotSoft
License: Freeware
AppMoniker: pdfill
Tags: PDF Tools
Description: Free PDF Tools.
Homepage: https://www.pdfill.com/
Installers:
  - Arch: Neutral
    Url: http://www.plotsoft.com/download/PDFill_FREE_PDF_Editor_Basic.msi
    InstallerType: msi
    Sha256: <unknown>
```

**Comment by denelon** [comment]
We've implemented some automation to generate a valid manifest and submit the PR when installers change under the same URL.
