### ISSUE TITLE
[Update Request]: Microsoft.Bicep new release v0.30.23

### ISSUE THREAD

**Issue by jrdodds** [microsoft/winget-pkgs#175098]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Bicep

### Package Version

0.30.23

### Please describe the changes you would like to see

There is a new release available - [v0.30.23](https://github.com/Azure/bicep/releases/tag/v0.30.23).

The prior release is [v0.30.3](https://github.com/Azure/bicep/releases/tag/v0.30.3).

**Comment by MarcoJanse** [comment]
Hi there.

I am currently working on submitting the new package. I will let you know the PR-number once it's submitted.

**Comment by MarcoJanse** [comment]
@jrdodds As you can see, the PR has been created: #175101. Once this has been successfully validated by the build pipeline, it will  need to be reviewed and approved by a community member. This is usually done within the day, but there are no guarantees on that timeframe...

**Comment by stephengillie** [comment]
I've just merged https://github.com/microsoft/winget-pkgs/pull/175101, so I'll close this as complete. If this is incorrect, please @ me and I'll reopen.
