### ISSUE TITLE
[Package Request]: Amazon Corretto 22

### ISSUE THREAD

**Issue by installation-scripts** [microsoft/winget-pkgs#175239]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://docs.aws.amazon.com/corretto/latest/corretto-22-ug/downloads-list.html
Publisher: Amazon
Package Name: Amazon Corretto 22
Description: Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the Open Java Development Kit (OpenJDK). Corretto comes with long-term support that includes performance enhancements and security fixes. 
Package Version: 22
Installer URL: https://corretto.aws/downloads/latest/amazon-corretto-22-x64-windows-jdk.msi

**Comment by Dragon1573** [comment]
@installation-scripts, it seems currently available in the repository. Could you please check with package identifier `Amazon.Corretto.22.JDK`?

```text
00:25:58 C:\...\winget-pkgs  [master ≡] 2.241s 0x0001 pwsh> winget search 'Amazon Corretto'
名称                  ID                     版本      源
--------------------------------------------------------------
Amazon Corretto 11    Amazon.Corretto.11.JDK 11.0.24.8 winget
Amazon Corretto 17    Amazon.Corretto.17.JDK 17.0.12.7 winget
Amazon Corretto 18    Amazon.Corretto.18.JDK 18.0.2.9  winget
Amazon Corretto 19    Amazon.Corretto.19.JDK 19.0.2.7  winget
Amazon Corretto 20    Amazon.Corretto.20.JDK 20.0.2.10 winget
Amazon Corretto 21    Amazon.Corretto.21.JDK 21.0.4.7  winget
Amazon Corretto 22    Amazon.Corretto.22.JDK 22.0.2.9  winget
Amazon Corretto 8     Amazon.Corretto.8.JDK  1.8.0.422 winget
Amazon Corretto JRE 8 Amazon.Corretto.8.JRE  1.8.0.422 winget

00:29:46 C:\...\winget-pkgs  [master ≡] 3ms pwsh> winget show -e Amazon.Corretto.22.JDK
已找到 Amazon Corretto 22 [Amazon.Corretto.22.JDK]
版本: 22.0.2.9
发布者: Amazon
发布服务器 URL: https://aws.amazon.com/
发布服务器支持 URL: https://github.com/corretto/corretto-22/issues
作者: Amazon
描述: Amazon Corretto 是 OpenJDK 的零成本、多平台、生产就绪的发行版。Corretto 提供长期支持,包括性能增强和安全修复。Corretto 在亚马逊内部数千个生产服务上运行,并已通过认证,与 Java SE 标准兼容。使用 Corretto,您可以在 Linux、Windows 和 macOS 等流行的操作系统上开发和运行 Java 应用程序。
主页: https://docs.aws.amazon.com/corretto/
许可证: GPL-2.0 with Classpath Exception
许可证 URL: https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source
隐私 URL: https://aws.amazon.com/privacy/
版权所有: Copyright © 2224
版权 URL: https://github.com/corretto/corretto-22/blob/develop/TRADEMARKS.md
发行说明 URL: https://github.com/corretto/corretto-22/blob/develop/CHANGELOG.md
标记：
  java
  jdk
  jre
  jvm
安装：
  安装程序类型： wix
  安装程序 URL： https://corretto.aws/downloads/resources/22.0.2.9.1/amazon-corretto-22.0.2.9.1-windows-x64.msi
  安装程序 SHA256： 9a1823908954fb562f739cdf1450dcc5bd1d42218ea1eee076dc34a79b17eada
  发布日期: 2024-07-16
  支持脱机分发: true
```

**Comment by Dragon1573** [comment]
Manually checked.

1. URL you provided above is a "vanity URL", which we discouraged.
2. At the time I checked and commented, the vanity URL points to `v22.0.2.9.1` ["version-related static URL"](https://corretto.aws/downloads/resources/22.0.2.9.1/amazon-corretto-22.0.2.9.1-windows-x64.msi), which is exactly the same as `Amazon.Corretto.22.JDK`.

**Comment by stephengillie** [comment]
This package is apparently already in the repo.
