### ISSUE TITLE
Unable to find `Microsoft.NuGet` package

### ISSUE THREAD

**Issue by Sunbreak** [microsoft/winget-pkgs#17533]
# Brief description of your issue

Unable to find `Microsoft.NuGet` package neither install it

# Steps to reproduce

```sh
C:\>winget search nuget
Name                 Id                                        Version
-----------------------------------------------------------------------
NuGetPackageExplorer NuGetPackageExplorer.NuGetPackageExplorer 5.8.34.0

C:\>winget install -e --id Microsoft.NuGet
No package found matching input criteria.
```

# Expected behavior

Able to install `nuget.exe` or remove package https://winget.run/pkg/Microsoft/NuGet

# Actual behavior

`No package found matching input criteria.`

# Environment

```sh
C:\>winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1052
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by Sunbreak** [comment]
Thanks for your clarifying.

Is it possible to install `nuget.exe` at `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`?

**Comment by ItzLevvie** [comment]
I don't think so since that's a protected folder. I haven't used NuGet but it seems like you may need to download the nuget.exe and set up an environment variable to use it globally.

There are instructions on how to do it here: https://stackoverflow.com/questions/45610728/nuget-is-not-a-recognized-as-an-internal-or-external-command/45613370

**Comment by Sunbreak** [comment]
https://github.com/woodemi/quick_notify/issues/5#issuecomment-888743117

**Comment by denelon** [comment]
@Sunbreak we have an issue for portable .exe packages at https://github.com/microsoft/winget-cli/issues/182

**Comment by Trenly** [comment]
Close with reason: Microsoft.NuGet has been re-added since portable apps are now supported;
