### ISSUE TITLE
[Update Request]: Update Microsoft.WinDbg to version 1.2409.17001.0

### ISSUE THREAD

**Issue by crivera25** [microsoft/winget-pkgs#175493]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.WinDbg

### Package Version

1.2409.17001.0

### Please describe the changes you would like to see

There is a new release available, version 1.2409.17001.0. Download link: [aka.ms/windbg/download](url)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Should be closed as completed: Resolved by #175492

**Comment by stephengillie** [comment]
> Note
> 
> Should be closed as completed: Resolved by #175492
