### ISSUE TITLE
Microsoft.Office fails to install unless launched with the interactive switch, -i

### ISSUE THREAD

**Issue by kriswilk** [microsoft/winget-pkgs#17560]
# Brief description of your issue

`Microsoft.Office` fails to install unless launched with the interactive switch, `-i`

# Steps to reproduce

`winget install -e Microsoft.Office`

# Expected behavior

Silent installation of Office 365.

# Actual behavior

A console window opens to run the downloaded installer. Moments later, an office installation error window appears stating "Couldn't install", as pictured below. However, if the install is launched interactively using

`winget install -e Microsoft.Office -i`

it proceeds normally and succeeds.

![image](https://user-images.githubusercontent.com/382436/121987656-e955ba80-cd66-11eb-8c21-3fbca34d9dee.png)

# Environment

```none
Windows 10 21H1 (build 19043.1052)

Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1052
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

All previous versions of office removed using official MS Office removal tool.
```

**Comment by lychichem** [comment]
Have you ever checked your network connection? The install requires connection to both the configure file and the office cdn. Any network error will make the installation fail.

**Comment by jedieaston** [comment]
I can replicate a similar error, it looks like the InstallerSwitches were adding two different config files and confusing the installer. 

I've fixed it (I think) in #17573, once that merges can you try to install it silently again?

**Comment by kriswilk** [comment]
> I can replicate a similar error, it looks like the InstallerSwitches were adding two different config files and confusing the installer.
> 
> I've fixed it (I think) in #17573, once that merges can you try to install it silently again?

Ah. I had a quick look at the manifest but didn't notice that. I'll test once merged and come back here to close the issue if it's fixed.

**Comment by kriswilk** [comment]
I see the fix is merged. I tried to test it but it seems the installer has changed versions (strangely, back to 16.0.13929.20238) and so I got a hash mismatch error. I went ahead and used `--force` to give it a try and it seems to work fine.

Will the msftbot pick up the new (old?) version automatically? Once it does I can do a final test.

**Comment by jedieaston** [comment]
I think that was my fault. It'll update automatically.

**Comment by quhxl** [comment]
It still has not updated. Can you look at it again?

**Comment by jedieaston** [comment]
It has been updated. Can you test it again?

**Comment by kriswilk** [comment]
Just tested. Looks like all is well now. Installs silently and hashes are fixed. Thanks!
