### ISSUE TITLE
[Update Request]: Update SiarheiKuchuk.BUtil to version 2024.09.29

### ISSUE THREAD

**Issue by drweb86** [microsoft/winget-pkgs#175725]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SiarheiKuchuk.BUtil

### Package Version

2024.09.29

## New Features

- Bengali, Urdu, Indonesian, Japanese, Nigerian Pidgin, Marathi, Telugu languages.
- It is possible to copy text from message.
- On task deletion log files are deleted as well.

## Changes

- 7-zip update to 24.08
- 7-zip is not used anymore to compress/encrypt files because of 7% average space profit (each file is compressed individually) with drawbacks of not supporting Android devices
- Update libraries
- Unit-tests are part of build.ps1 script execution
- Storage format upgrade. Previous versions of applications won't be able to open it. Backward compatibility for restoration etc will be preserved for some time.
- Checking for updates was switched back to github since upload was fixed, personal site at NAS will be shutdown after some time.
- Messages for questions was improved.

## Bug Fixes

- Message buttons locations was invalid
- Message text locations was invalid
! Incremental backup creates version when duplicate files exists
- Task status was missing on rename
- Import multimedia with skip already imported flag was not working correctly during rename of task

**Comment by Dragon1573** [comment]
Should be closed as completed manually.

- See #175726

**Comment by stephengillie** [comment]
> Should be closed as completed manually.
> 
> * See [[Update Request]: Update SiarheiKuchuk.BUtil to version 2024.09.29 #175726](https://github.com/microsoft/winget-pkgs/pull/175726)

**Comment by drweb86** [comment]
Thanks!
