### ISSUE TITLE
[Update Request]: DindeGDPS

### ISSUE THREAD

**Issue by masckmaster2007** [microsoft/winget-pkgs#175729]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DimisAIO.DindeGDPS

### Package Version

2024.09.25

### Please describe the changes you would like to see

Version bump to 2024.09.25
URL stays https://cdn-dinde.141412.xyz/DindeGDPS.exe

**Comment by a-mnich** [comment]
> [!NOTE] 
> Package update and modification was already requested through #175179 
>This issue is a duplicate and can be closed.

> [!TIP]  
> The highest available version of a package can be checked with `winget search --id DimisAIO.DindeGDPS`

**Comment by masckmaster2007** [comment]
Oh right! I didn't see that. Thanks! :)
