### ISSUE TITLE
[Update Request]: Malwarebytes offline installer

### ISSUE THREAD

**Issue by BKWQ** [microsoft/winget-pkgs#175951]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Malwarebytes.Malwarebytes

### Package Version

5.1.4.89

### Please describe the changes you would like to see

The offline installer should be used, located here:
https://data-cdn.mbamupdates.com/web/mb5-setup-consumer/offline/MBSetup.exe

**Comment by chuckopp** [comment]
The offline installer is not for automated installations as it's a specialized package and can be quite large.

The online installer is preferred.
