### ISSUE TITLE
[Update Request]: Update Microsoft.TimeTravelDebugging to 1.11.429

### ISSUE THREAD

**Issue by KenSykes** [microsoft/winget-pkgs#176108]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.TimeTravelDebugging

### Package Version

1.11.429

### Please describe the changes you would like to see

There is a new release (1.11.429) available. Url: https://aka.ms/ttd/download

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Should be closed as completed.
>
> - See #176096
