### ISSUE TITLE
[Update Request]: Ipe

### ISSUE THREAD

**Issue by puenka** [microsoft/winget-pkgs#176757]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OtfriedCheong.Ipe

### Package Version

7.2.29

### Please describe the changes you would like to see

There is a new version available fromMay 25, 2024.
https://github.com/otfried/ipe/releases

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`
