### ISSUE TITLE
[Package Request]: RiseupVPN

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [microsoft/winget-pkgs#176960]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://riseup.net/en/windows
Publisher: Riseup Collective
Package Name: RiseupVPN-installer-0.24.8.exe
Description: VPN Client
Package Version: 0.24.8
Installer URL: https://downloads.leap.se/RiseupVPN/windows/RiseupVPN-installer-0.24.8.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This is an installer wizard created with _Qt Installer Framework_.
