### ISSUE TITLE
[Update Request]: Apache Netbeans package version needs to be updated to v23

### ISSUE THREAD

**Issue by SpeakingFish** [microsoft/winget-pkgs#177065]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Apache.NetBeans

### Package Version

23

### Please describe the changes you would like to see

Currently when I tried to install netbeans I have an error:

	C:\WINDOWS\system32>winget install netbeans
	Found Apache NetBeans IDE [Apache.NetBeans] Version 22
	This application is licensed to you by its owner.
	Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
	This package requires the following dependencies:
	- Packages
		BellSoft.LibericaJDK.22
	Downloading https://dlcdn.apache.org/netbeans/netbeans-installers/22/Apache-NetBeans-22-bin-windows-x64.exe
	An unexpected error occurred while executing the command:
	Download request status is not success.
	0x80190194 : Not found (404).

At Apache distro server there is only v23 exists: https://dlcdn.apache.org/netbeans/netbeans-installers/

Please update package version to the latest actual one

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This is already resolved by #176957. Should be closed as completed.

CC @stephengillie

**Comment by stephengillie** [comment]
> Note
> 
> This is already resolved by #176957. Should be closed as completed.
> 
> CC @stephengillie
