### ISSUE TITLE
[Package Request]: qBittorrent Qt 6 version

### ISSUE THREAD

**Issue by FalxDraco** [microsoft/winget-pkgs#177048]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.qbittorrent.org/download
Publisher: The qBittorrent project
Package Name: qBittorrent.Qt6
Description: qBittorrent is a bittorrent client programmed in C++ / Qt that uses libtorrent (sometimes called libtorrent-rasterbar) by Arvid Norberg. It aims to be a good alternative to all other bittorrent clients out there. qBittorrent is fast, stable and provides unicode support as well as many features.
Package Version: 5.0.0
Installer URL: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-5.0.0/qbittorrent_5.0.0_lt20_qt6_x64_setup.exe/download

**Comment by SpecterShell** [comment]
"Qt 6 version" no longer makes sense as qBittorrent has dropped support for Qt5 since version 5.0, and all the two installers available are based on Qt6. The only difference is the version of the libtorrent library used (1.0/2.0).
