### ISSUE TITLE
[Update Request]: GnuWin32.Make

### ISSUE THREAD

**Issue by gedw99** [microsoft/winget-pkgs#177602]
### What type of update are you requesting?

Something else not listed.

It used to be there, but is gone now...

### Current Package Identifier

GnuWin32.Make

### Package Version

Dont know, since its gone.

### Please describe the changes you would like to see

It used to be there.
Please add it back.
Or let me know if there is a reason it is gone; would be useful to know.

```sh

PS C:\Users\admin> winget search --id GnuWin32 --source winget
Name                Id                 Version
-----------------------------------------------
GnuWin32: Bison     GnuWin32.Bison     2.4.1.0
GnuWin32: Cpio      GnuWin32.Cpio      2.6-2
GnuWin32: DiffUtils GnuWin32.DiffUtils 2.8.7-1
GnuWin32: FindUtils GnuWin32.FindUtils 4.2.20-2
GnuWin32: GetText   GnuWin32.GetText   0.14.4
GnuWin32: Gperf     GnuWin32.Gperf     3.0.1
GnuWin32: Grep      GnuWin32.Grep      2.5.4
GnuWin32: Gzip      GnuWin32.Gzip      1.3.12-1
GnuWin32: M4        GnuWin32.M4        1.4.13.0
Tar                 GnuWin32.Tar       1.13-1
GnuWin32: Tree      GnuWin32.Tree      1.5.2.2
GnuWin32: UnZip     GnuWin32.UnZip     5.51-1
Which for Windows   GnuWin32.Which     2.2
GnuWin32: Zip       GnuWin32.Zip       3

```

**Comment by Dragon1573** [comment]
Update request of package identifier `GnuWin32.Make` is already created by #122853, and it's already removed by #140010. New package identifier is `ezwinports.make`, created by #140009.

@gedw99 Is it your expected?
