### ISSUE TITLE
[Package Request]: The Bat!

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#177788]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.ritlabs.com/en/products/thebat/download.php
Publisher: Ritlabs SRL
Package Name: The Bat!
Description: The Bat! is a secure desktop email client for Windows, built to protect your correspondence against third-parties.
Package Version: 11.2.2
Installer URL: https://www.ritlabs.com/download/the_bat/thebat_64_11-2-2.msi

The package was already published, but then [removed](https://github.com/microsoft/winget-pkgs/pull/105363) without adding a new version.

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/c4cab6c0-33bb-410d-9e0e-7e276e834d08)
