### ISSUE TITLE
[Update Request]: FFmpeg Batch AV Converter (v3.0.9, from 3.0.8)

### ISSUE THREAD

**Issue by DragRedSim** [microsoft/winget-pkgs#177756]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

eibol.FFmpegBatchAVConverter

### Package Version

3.0.9, from 3.0.8

### Please describe the changes you would like to see

New versions of this package are available. The software is published both on GitHub at https://github.com/eibol/ffmpeg_batch, and on SourceForge at https://sourceforge.net/projects/ffmpeg-batch. (Yes, I know I submitted the 3.0.8 update only a couple of days ago; looks like 3.0.9 came out the day after the 3.0.8 update was added to the repository.)

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/bad03a83-a70b-4032-8013-f6f3f14c882c)
