### ISSUE TITLE
[Package Request]: optipng

### ISSUE THREAD

**Issue by AlexMax** [microsoft/winget-pkgs#177933]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://optipng.sourceforge.net/
Publisher: https://optipng.sourceforge.net/authors.txt
Package Name: optipng
Description:  optiPNG is a PNG optimizer that recompresses image files to a smaller size, without losing any information. This program also converts external formats (BMP, GIF, PNM and TIFF) to optimized PNG, and performs PNG integrity checks and corrections. 
Package Version: 0.7.8
Installer Url: http://prdownloads.sourceforge.net/optipng/optipng-0.7.8-win64.zip?download

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/95fe4f29-7f79-41f3-9bd1-c49a96b62cd7)
