### ISSUE TITLE
[Package Issue]: Tencent.WeChat still notify update even I have installed the latest version

### ISSUE THREAD

**Issue by ali50m** [microsoft/winget-pkgs#178063]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Install Tencent.WeChat with winget, then run `winget update`, it will notify there is update for `Tencent.WeChat`. If I run `winget update Tencent.WeChat`, winget will download and install it successfully. But when I run `winget update` again, it still prompt there is an update for `Tencent.WeChat`.

### Steps to reproduce

1. winget install Tencent.WeChat
2. winget update
3. winget update Tencent.WeChat
4. winget update

![图片](https://github.com/user-attachments/assets/777355f8-60ae-4747-bd88-51810ef93434)
![图片](https://github.com/user-attachments/assets/6c44b06f-fbb6-4336-904c-b7b86a393d79)

### Actual behavior

Always prompt there is an update for `Tencent.WeChat` .

### Expected behavior

install the latest `Tencent.WeChat` through winget successfully.

### Environment

```raw
Winget v1.8.1911
Windows: Windows.Desktop v10.0.19044.4894
Tencent.WeChat 3.9.12.16 -> 3.9.12.1000
WT: 1.21.2701.0
PowerShell 7.4.5
```

**Comment by Dragon1573** [comment]
Manually verified. It seems the `*.msi` installer will write `File version` instead of `Product version` to the ARP entries.

![image](https://github.com/user-attachments/assets/5cb88f91-d4db-4173-bf06-9fb02645b998)

**Comment by Dragon1573** [comment]
Start from version `3.9.12.16`, a vanity URL is used as `InstallerUrl`. In order to avoid "infinite upgrade loop", manifest version of `3.9.12.16` and `3.9.12.17` should be removed.

```text
11:13:46 D:\...\winget-pkgs  [master ≡] 1.387s pwsh> komac show --installer-manifest -v 3.9.12.17 Tencent.WeChat
PackageIdentifier: Tencent.WeChat
PackageVersion: 3.9.12.17
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- weixin
Installers:
- Architecture: x64
  InstallerUrl: https://dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe
  InstallerSha256: 4985F96235154FC4176E3972F14709F5F10FC0606E5589075A6DA9B6DC7FCCD3
  ProductCode: WeChat
ManifestType: installer
ManifestVersion: 1.6.0

11:14:14 D:\...\winget-pkgs  [master ≡] 1.895s pwsh> komac show --installer-manifest -v 3.9.12.16 Tencent.WeChat
PackageIdentifier: Tencent.WeChat
PackageVersion: 3.9.12.16
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- weixin
Installers:
- Architecture: x86
  InstallerUrl: https://dldir1v6.qq.com/weixin/Windows/WeChatSetup_x86.exe
  InstallerSha256: A084A7B6416F4AF4A7108A46CE0A4F288562475592B6053BE04EE9B8D91D8D96
  ProductCode: WeChat
ManifestType: installer
ManifestVersion: 1.6.0

11:14:34 D:\...\winget-pkgs  [master ≡] 2.049s pwsh> komac show --installer-manifest -v 3.9.10.19 Tencent.WeChat
PackageIdentifier: Tencent.WeChat
PackageVersion: 3.9.10.19
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- weixin
Installers:
- Architecture: x64
  InstallerUrl: https://dldir1v6.qq.com/weixin/Windows/WeChat3.9.10.19.exe
  InstallerSha256: 9602ACB85408EE48EE689468F63565496DFB12F1FE21AD674AA423029E38856C
  ProductCode: WeChat
ManifestType: installer
ManifestVersion: 1.6.0
```
