### ISSUE TITLE
[Package Request]: Freedom.Freedom

### ISSUE THREAD

**Issue by michaelmhoffman** [microsoft/winget-pkgs#178130]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://freedom.to/downloads
Publisher: Freedom
Package Name: Freedom
Description: Freedom blocks distracting websites and apps
Package Version: 2.29
Installer Url: https://cdn.freedom.to/installers/FreedomSetup.exe

**Comment by Dragon1573** [comment]
Failed to install silently. 😞

`<msiOptions>` seems not supported by this installer wizard. The inner wizard stored in EXE file is NOT an MSI.

![image](https://github.com/user-attachments/assets/4f214e20-d94e-44ca-95ba-3f3ffa4de55f)

**Comment by KarbitsCode** [comment]
> Failed to install silently. 😞
> 
> `<msiOptions>` seems not supported by this installer wizard. The inner wizard stored in EXE file is NOT an MSI.
> 

@Dragon1573 It seems this installer is similar to DirectFolders before (https://github.com/microsoft/winget-pkgs/issues/156118#issuecomment-2171770634), maybe you can reference the installer options from my PR.
