### ISSUE TITLE
[Update Request]: MinIO Clinet

### ISSUE THREAD

**Issue by uoya** [microsoft/winget-pkgs#178578]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MinIO.Client

### Package Version

2024.10.02

### Please describe the changes you would like to see

There is a new release (RELEASE.2024-10-02T08-27-28Z) available.
Download Page Url: https://dl.min.io/client/mc/release/windows-amd64/archive/mc.RELEASE.2024-10-02T08-27-28Z

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Modify your [very first comment](https://github.com/microsoft/winget-pkgs/pull/178579#issue-2568670381) of the pull request will help associating that pull request to this issue.
>
> Only `#number` is accepted for linking pull request with the issue. Other formats are not supported.
>
> ```diff
>   Checklist for Pull Requests
> 
>   * [x]  Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
> - * [x]  Resolve [[Update Request]: MinIO Clinet #178578](https://github.com/microsoft/winget-pkgs/issues/178578)
> + * [x]  Resolve #178578
> ```

**Comment by uoya** [comment]
@Dragon1573 
Thank you so much for sharing this helpful tip! I really appreciate your input and will definitely be applying it moving forward.
