### ISSUE TITLE
[Update Request]: HulubuluSoftware.AdvancedRenamer

### ISSUE THREAD

**Issue by Droidem** [microsoft/winget-pkgs#178769]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

HulubuluSoftware.AdvancedRenamer

### Package Version

4.03

### Please describe the changes you would like to see

There is a new version available (4.03) https://www.advancedrenamer.com/down/win/advanced_renamer_setup_4_03.exe

https://www.advancedrenamer.com/download

**Comment by Droidem** [comment]
The pull request above updates it to 3.94, whereas my pull request updates it to 4.03

**Comment by vikingnope** [comment]
Kindly change the title of the issue to the following:

`[Update Request]: HulubuluSoftware.AdvancedRenamer`
