### ISSUE TITLE
[Package Request]: Unity Version Control Enterprise Edition

### ISSUE THREAD

**Issue by pg-kawashima** [microsoft/winget-pkgs#178788]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.plasticscm.com/download/11.0.16.8906/plasticscm/windows/full
Publisher: Unity Technologies
Package Name: Unity Version Control (PlasticSCM) Enterprise Edition
Description: Unity Version Control (PlasticSCM) Enterprise Edition
Package Version: 11.0.16.8906
Installer Url: https://www.plasticscm.com/download/11.0.16.8906/plasticscm/windows/full

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![image](https://github.com/user-attachments/assets/d7c7cbe7-366b-4dcd-8f18-d468194d2b8b)
![image](https://github.com/user-attachments/assets/9fe3a1de-e25d-4872-b9d2-dc4a7b8f9da9)
![image](https://github.com/user-attachments/assets/71d91e96-920f-443b-a3a9-44bfacd32449)
