### ISSUE TITLE
[Package Request]: Nvidia App

### ISSUE THREAD

**Issue by thisischrys** [microsoft/winget-pkgs#179043]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.nvidia.com/en-us/software/nvidia-app/
Publisher: NVIDIA 
Package Name: NVIDIA App
Description: Keep your PC up to date with the latest NVIDIA drivers and technology. Optimize games and applications with a new unified GPU control center, capture your favorite moments with powerful recording tools through the in-game overlay, and discover the latest NVIDIA tools and software.
Package Version: 10.0.3.152
Installer Url: https://us.download.nvidia.com/nvapp/client/10.0.3.152/NVIDIA_app_beta_v10.0.3.152.exe

**Comment by Dragon1573** [comment]
Manually checked. Duplicate of #140696, this should be converted to a "package update" request.

**Comment by stephengillie** [comment]
> Manually checked. Duplicate of #140696, this should be converted to a "package update" request.

**Comment by DandelionSprout** [comment]
I've been able to add it to the 3rd-party Winget source [winget-extras](https://github.com/pl4nty/winget-extras) by [pl4nty](https://github.com/pl4nty) now, at least:

`winget source add --name winget-extras --type Microsoft.PreIndexed.Package --arg https://winget.tplant.com.au/cache; winget install Nvidia.NVIDIAApp`
