### ISSUE TITLE
[Policy Service]: `In-PR` label should be removed if a PR is closed before being merged

### ISSUE THREAD

**Issue by a-mnich** [microsoft/winget-pkgs#179050]
If a PR that links to an issue is closed before being merged, the Policy Service should remove the `In-PR` label and revert back to the state before the label was added.  
With this, the maintainers wouldn't need to change the labels back manually.
  
Issue Examples:
- https://github.com/microsoft/winget-pkgs/issues/178311
- https://github.com/microsoft/winget-pkgs/issues/174661
- https://github.com/microsoft/winget-pkgs/issues/171308

Issue filter: [unmerged PRs linked to an issue](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aclosed+is%3Aunmerged+linked%3Aissue)

**Comment by Trenly** [comment]
This may be tricky to implement since the policy service doesn't provide this functionality natively. There may be a way to do it, but I'll have to do some deeper investigation

**Comment by stephengillie** [comment]
I've been doing this manually because I wasn't aware that automation could do this.
