### ISSUE TITLE
Problems installing Paint.Net from Winget on Intune managed devices

### ISSUE THREAD

**Issue by nro494** [microsoft/winget-pkgs#179041]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Hi, I´m having trouble installing [Paint.Net](http://paint.net/) via Winget on Clients which are managed by Microsoft Intune.

I receive the following error:
Installer failed with exit code: 3762504530

I can´t find anything about this code online.
I previously raised this issue in the Paint.Net Forum and was directed here.
Is there any documentation on what this code could mean?

Since Admin rights are required for the installation, the setup is running in system context, not user context (our end users don´t have admin rights).

Manually running the installation on one of the devices (with admin rights) works but deploying it via Intune doesn´t.

We install other software from winget in the same way and haven´t had any issues with that yet.

This is the output I receive after running the winget install command:

Found [paint.net](http://paint.net/) [dotPDN.PaintDotNet] Version 5.0.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Installer failed with exit code: 3762504530

### Steps to reproduce

I´ll append the PowerShell Script I use to the end of this field.

We package said script into an Intunewin file and deploy it to intune as a Win32 App.
This App is installed in System Context.
User Context is not an Option since the install requires admin permissions which our end users don´t have.

When the user tries to install the app, the install fails because of the error stated in the description

Param
 (
   [parameter(Mandatory=$false)]
   [String[]]
   $param
 )
$ProgramName = "dotPDN.PaintDotNet"

$Path_local = "C:\Program Files\WingetInstallLogs"

if (Test-Path $Path_local) {
   #Folder existsiert
}
else {
   #Folder existiert nicht
   New-Item -Path ($Path_local+"\Log\uninstall") -ItemType Directory
}

Start-Transcript -Path "$Path_local\Log\$ProgramName-install.log" -Force -Append

# resolve winget_exe
$winget_exe = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe"
if ($winget_exe.count -gt 1){
       $winget_exe = $winget_exe[-1].Path
}

if (!$winget_exe){Write-Error "Winget not installed"}

& $winget_exe install --exact --id $ProgramName --silent --accept-package-agreements --accept-source-agreements --source winget --override "ALLUSERS=1 AI_INSTALLPERUSER=3 /passive /norestart"

Stop-Transcript

### Actual behavior

Winget setup fails when trying to install [Pain.Net](http://pain.net/)

### Expected behavior

Winget is supposed to run the installer and install the app on the PC

### Environment

```raw
Windows-Paket-Manager v1.8.1911
Windows.Desktop v10.0.22631.4037
Microsoft.DesktopAppInstaller v1.23.1911.0

Ohter installed Software:
Microsoft 365 Apps
MS Teams
Notepad++
HeidiSQL
Teamviewer
Rufus
```

### Screenshots and Logs

I can´t find any logs for the installation in the log directory.
I guess that´s because it runs in system context and I don´t know which directory that logs to.
It´s kind of strange since I can see logs for the detection script (winget list) that runs after the installation (also in system context).
I can only provide the output that my own install script logs to a custom directory:

Found [paint.net](http://paint.net/) [dotPDN.PaintDotNet] Version 5.0.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Installer failed with exit code: 3762504530

**Comment by SpecterShell** [comment]
The EXE installer stores the log files in `%temp%`. You can find the error information there.

**Comment by SpecterShell** [comment]
Or you can try the MSI installer, by running `winget install dotPDN.PaintDotNet --installer-type wix` for this package.

**Comment by nro494** [comment]
> Or you can try the MSI installer, by running `winget install dotPDN.PaintDotNet --installer-type wix` for this package.

Thank you very much, that did the trick.
