### ISSUE TITLE
[Package Issue]: Ryujinx.Ryujinx.Ava - Ryujinx organization no longer exists

### ISSUE THREAD

**Issue by Clockwork-Muse** [microsoft/winget-pkgs#179207]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

As with Switch emulator Yuzu, the Switch emulator Ryujinx and its org [has also been taken offline](https://www.polygon.com/gaming/458905/nintendo-switch-emulator-ryujinx-offline).

The relevant GitHub org/project pages already 404, so packages will no longer install.

### Steps to reproduce

Attempt to install the package

### Actual behavior

Fails, because the project no longer exists.

### Expected behavior

N/A

### Environment

```raw
N/A
```

**Comment by stephengillie** [comment]
Since all mentioned PRs are closed, I'll close this Issue. If this is in error, please @ me and I'll reopen.
