### ISSUE TITLE
clsid2.mpc-hc reports it as MPC-HC.MPC-HC

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#17972]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
`clsid2.mpc-hc` reports it as `MPC-HC.MPC-HC` in `winget list`, and it is the same as what reported by `MPC-HC.MPC-HC`
# Steps to reproduce
1. Install `clsid2.mpc-hc` using `winget install clsid2.mpc-hc`,
2. type `winget list` and search for mpc-hc.

# Expected behavior
clsid2.mpc-hc should report it as clsid2.mpc-hc, or any other name not used by other packages.

# Actual behavior
`clsid2.mpc-hc` reports it as `MPC-HC.MPC-HC`, which was used by `MPC-HC.MPC-HC`.

# Environment

```none
[winget --info]
Windows Package Manager version: v1.0.11451
Windows: Windows.Desktop version: v10.0.19043.1052
Package: Microsoft.DesktopAppInstaller version: v1.11.11451.0

Any other software?
```

Addition info: As MPC-HC team declared that they will not maintaince MPC-HC anymore, it stopped updating from 2017. However, clsid2.mpc-hc keeps maintaince and adding new features now. Should we remove MPC-HC.MPC-HC and treat clsid2.mpc-hc as the new offical source of MPC-HC?

**Comment by OfficialEsco** [comment]
Uhhm, so the `clsid2.mpc-hc` Manifest actually got the wrong `Publisher`, it might match the `PackageID` as `clsid2.mpc-hc` if we change the `Publisher` to `MPC-HC Team`
But as you can see from `winget list` and my comment this is actually clsid2's fault for not changing the `Publisher` in the installer
![image](https://user-images.githubusercontent.com/15158490/122555139-32915d00-d03a-11eb-86a1-43a2310504f4.png)

I don't think we should force the MPC-HC users to install clsid2's MPC-HC fork, however we are accidentally doing that right now 😬

**Comment by lychichem** [comment]
> Uhhm, so the `clsid2.mpc-hc` Manifest actually got the wrong `Publisher`, it might match the `PackageID` as `clsid2.mpc-hc` if we change the `Publisher` to `MPC-HC Team`
> But as you can see from `winget list` and my comment this is actually clsid2's fault for not changing the `Publisher` in the installer
> ![image](https://user-images.githubusercontent.com/15158490/122555139-32915d00-d03a-11eb-86a1-43a2310504f4.png)
> 
> I don't think we should force the MPC-HC users to install clsid2's MPC-HC fork, however we are accidentally doing that right now 😬

Yes, I don't want to force users too, however, the original MPC-HC team suggests users using something else on their homepage:
![image](https://user-images.githubusercontent.com/9316590/122565975-9edf8100-d079-11eb-86e1-cf6abccaf10c.png)

And wiki says:
![image](https://user-images.githubusercontent.com/9316590/122566291-f5e55600-d079-11eb-9d70-9cc533b30761.png)

![image](https://user-images.githubusercontent.com/9316590/122566235-e9f99400-d079-11eb-970c-d8ccf4e54ed3.png)

So I think replacing MPC-HC.MPC-HC with clsid2.mpc-hc makes sense.

**Comment by Trenly** [comment]
https://github.com/clsid2/mpc-hc/pull/1408

**Comment by clsid2** [comment]
The real fix is not to treat it as two different packages. The "original" is obsolete and deprecated.
