### ISSUE TITLE
[Update Request]: Element.Element 1.11.80

### ISSUE THREAD

**Issue by FalxDraco** [microsoft/winget-pkgs#179965]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Element.Element

### Package Version

1.11.80

### Please describe the changes you would like to see

A new version of Element (`v1.11.80`) is available at https://github.com/element-hq/element-desktop/releases/tag/v1.11.80

**Comment by a-mnich** [comment]
currently in PR with 
- https://github.com/microsoft/winget-pkgs/pull/179831

**Comment by stephengillie** [comment]
> currently in PR with
> 
> * [New version: Element.Element version 1.11.80 #179831](https://github.com/microsoft/winget-pkgs/pull/179831)

This has been approved.
