### ISSUE TITLE
[Package Issue]: Microsoft.NuGet

### ISSUE THREAD

**Issue by aetos382** [microsoft/winget-pkgs#180085]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The `DisplayVersion` in the manifest of the [Microsoft.NuGet package version 6.11.1](https://github.com/microsoft/winget-pkgs/blob/8733e365b3c2690fd770da950cf857c885f7b067/manifests/m/Microsoft/NuGet/6.11.1/Microsoft.NuGet.installer.yaml) is incorrect.
So, even though the latest version is installed, this package will be displayed as having update repeatedly. This is a false positive.

### Steps to reproduce

1. Run the `winget install Microsoft.NuGet --version 6.11.1` command.
2. Run the `nuget` command. Check that version `6.11.1.2` is running.
3. Run the `winget upgrade` command.

### Actual behavior

The version `6.11.0.119` is currently installed, and it is displayed that the `6.11.1` update is available.

### Expected behavior

[Unless a newer version is released](https://www.nuget.org/downloads), the `winget upgrade` command will not report that there is an update.

### Environment

```raw
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.1742
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by mphelt** [comment]
this issue still occurs.
it wasn't fixed for nuget 6.11.1, and is not fixed for 6.11.1.2
