### ISSUE TITLE
[Update Request]: MattermostDesktop version 5.9.0 to 5.9.0.0

### ISSUE THREAD

**Issue by sassdawe** [microsoft/winget-pkgs#180248]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

 Mattermost.MattermostDesktop

### Package Version

5.9.0

### Please describe the changes you would like to see

While the installed version is truly `5.9.0` the actually installed version has `5.9.0.0` as version number.

![Image](https://github.com/user-attachments/assets/ca544270-a1bf-4021-a063-fbc53c42b312)

This makes it hard to check with Automation whether there is new version installed or I already have the latest version installed.

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![Image](https://github.com/user-attachments/assets/97cadfac-9100-485d-8fb5-21eaf5b6fa02)

**Comment by Trenly** [comment]
@sassdawe - Won't `winget list --query mattermost --upgrade-available` work to automatically check if an upgrade is available?
