### ISSUE TITLE
[Package Issue]: Microsoft.Office    (16.0.17830.20162)

### ISSUE THREAD

**Issue by TheStingPilot** [microsoft/winget-pkgs#180211]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.17830.20162
  ++++++++++++++++++++++++++++++  7.17 MB / 7.17 MB
Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

Install via Winget

### Actual behavior

Application is not installed.

### Expected behavior

Installed application.

### Environment

```raw
WinGet version: v1.8.1911
```

**Comment by a-mnich** [comment]
A fix was published with #180015  
The hash mismatch will be resolved once the publish pipeline has published the new manifest.

**Comment by stephengillie** [comment]
> A fix was published with [#180015](https://github.com/microsoft/winget-pkgs/pull/180015) The hash mismatch will be resolved once the publish pipeline has published the new manifest.

Since the PR is merged, I'll mark this Issue as complete. If this is in error, please @ me and I'll reopen.

**Comment by maumeerally** [comment]
What a mess this is, Microsoft tool unable to deploy a Microsoft app
