### ISSUE TITLE
[Package Issue]: Merge Microsoft.VCRedist.2019.arm64 and Microsoft.VCRedist.2022.arm64

### ISSUE THREAD

**Issue by SpecterShell** [microsoft/winget-pkgs#180373]
Both `Microsoft.VCRedist.2019.arm64` and `Microsoft.VCRedist.2022.arm64` packages have the same UpgradeCode `{F608407A-6091-42E0-A1BA-B8FFFC21199B}`, and thus should be merged into one.

**Comment by Dragon1573** [comment]
## Suggestion

Similar to package identifier `Microsoft.VCRedist.2015+.x64` and `Microsoft.VCRedist.2015+.x86`, merge `Microsoft.VCRedist.2019.arm64` and `Microsoft.VCRedist.2022.arm64` into a new identifier `Microsoft.VCRedist.2019+.arm64`, with a new package name `Microsoft Visual C++ 2019-2022 Redistributable (Arm64)`.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/pull/180390
