### ISSUE TITLE
Repology no longer tracks repository winget

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/winget-pkgs#180435]
https://repology.org/repository/winget -> 404

> Sorry, but Repology no longer tracks repository winget.
> 
> Last time Repology has processed this repository was 2024-05-31 17:20 (4 months ago).
> 
> Some of the reasons which may have caused this:
> * The repository has reached its end of life, is no longer updated or supported, should no longer be used, and has probably disappeared from the mirrors. There may be a newer version of this repository available though, check [the list](https://repology.org/repositories/statistics).
> * Repository has stopped publishing information about its packages in format usable to Repology, so it's can't be processed any more. You may try contacting repository owners and ask them to fix this.
>

**Comment by xtqqczze** [comment]
https://github.com/repology/repology-updater/issues/1392#issuecomment-2144956402

**Comment by aisgbnok** [comment]
Related to https://github.com/microsoft/winget-pkgs/issues/156468

**Comment by xtqqczze** [comment]
When this is fixed https://github.com/microsoft/winget-pkgs/commit/59836656277d6844b6300f9273a61d3076a6f117 can be reverted.

**Comment by dreua** [comment]
It's fixed, you can do the revert and close this issue. (https://github.com/repology/repology-updater/issues/1392)
