### ISSUE TITLE
[Update Request]: Tauon Music Box

### ISSUE THREAD

**Issue by breadland** [microsoft/winget-pkgs#180528]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Taiko2k.TauonMusicBox

### Package Version

7.8.0

### Please describe the changes you would like to see

There have been a bunch of releases for Tauon in the last 9 months. The latest is v7.8.3 released back in September. 
Although the latest release with a .exe available for download is v7.8.0
https://github.com/Taiko2k/Tauon/releases/tag/v7.8.0

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/pull/180552
