### ISSUE TITLE
Package request: VeraCrypt

### ISSUE THREAD

**Issue by HtHNightwolf** [microsoft/winget-pkgs#18101]
Please add VeraCrypt to the repository

**Comment by mddtest** [comment]
It has issues for it to be added, so at this time looks as a nogo

https://github.com/microsoft/winget-pkgs/pull/3978
https://github.com/veracrypt/VeraCrypt/issues/447

**Comment by OfficialEsco** [comment]
Resolved in https://github.com/microsoft/winget-pkgs/pull/39880

**Comment by hueldoeu** [comment]
when will it be updated? there is v1.26.7 already
