### ISSUE TITLE
[Package Issue]: Microsoft.PowerAutomateDesktop

### ISSUE THREAD

**Issue by TylerRoberts** [microsoft/winget-pkgs#181137]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Hash verification fails.  Running as admin.

[CLI ] Package hash verification failed. SHA256 in manifest [d5efbcb34f1dee32e6912251678e0177415181bc7c4707b76d466c232b01fabd] does not match download [75a7ac72bbf192a70606ce92f3a2fc3f61f52b1e7ca572e76b3199da20fe41e7]

### Steps to reproduce

winget install --id Microsoft.PowerAutomateDesktop --silent --exact --accept-source-agreements --accept-package-agreements

### Actual behavior

The file downloads but fails hash verification.  This was working yesterday and fails today, though the package is still the same version as yesterday.

### Expected behavior

Ideally it would pass the hash verification :)

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4169
System Architecture: X64

Winget Directories                 
------------------------------------------------------------------------------------------------------
Logs                               %TEMP%\WinGet\defaultState
User Settings                      %LOCALAPPDATA%\Microsoft\WinGet\Settings\defaultState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by aisgbnok** [comment]
- Fixed by #180840.

The winget publishing pipeline has been having issues the past few days. See #180404. It should be working again soon.

**Comment by aisgbnok** [comment]
Verified this is working again:

```
Downloading https://download.microsoft.com/download/3/e/4/3e401e87-e96f-4527-bfdf-bf25e370f15a/Setup.Microsoft.PowerAutomate.exe
  ██████████████████████████████   313 MB /  313 MB
Successfully verified installer hash
Installer downloaded: C:\Users\...\Downloads\Microsoft.PowerAutomateDesktop_2.49.176.24278\Power Automate for desktop_2.49.176.24278_Machine_X86_burn_en-US.exe
```

**Comment by stephengillie** [comment]
> * Fixed by [Automatic update of Microsoft.PowerAutomateDesktop from 2.48.153.24261 to 2.49.176.24278 #180840](https://github.com/microsoft/winget-pkgs/pull/180840).
> 
> The winget publishing pipeline has been having issues the past few days. See [#180404](https://github.com/microsoft/winget-pkgs/issues/180404). It should be working again soon.

Since this version appears to have become published, I'll assume this Issue is complete. If this is in error, please @ me and I"ll reopen. 

```PowerShell
PS C:\ManVal> find-WinGetPackage Microsoft.PowerAutomateDesktop

Name                       Id                             Version        Source
----                       --                             -------        ------
Power Automate for desktop Microsoft.PowerAutomateDesktop 2.49.176.24278 winget
```
