### ISSUE TITLE
[Update Request]: FujitsuClientComputingLimited.DeskUpdate

### ISSUE THREAD

**Issue by applicma** [microsoft/winget-pkgs#181369]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

FujitsuClientComputingLimited.DeskUpdate

### Package Version

5.2.64

### Please describe the changes you would like to see

Hi !

Publisher: Fujitsu Client Computing Limited
Publisher Url: fujitsu.com
Package Name: DeskUpdate
Description: Fujitsu driver manager
Old Package Version: 5.2.56

There is a new release since 26/02/2024.
In the winget repository, there is 5.2.40 and 5.2.56 versions, but no 5.2.64.
Like the issue #99418 (https://github.com/microsoft/winget-pkgs/issues/99418), possible to add this new version ?

URL for this new version : https://webdownloads4.ts.fujitsu.com/download/FileDownload/fileDownload.aspx?SoftwareGUID=A63621A0-4BE1-476E-9B86-309ADB82E0A8&FileFolder=Downloadfiles&FileTypeExtension=EXE&FileNameClient=FTS_DeskUpdateSetup_5020064_1295759.EXE&Token=NTUxNTQxNjQ2ODE8MTc0Kio=

Many thx

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: Resolved
>
> This issue didn't close automatically by linked pull request. Should be manually closed as completed.

**Comment by stephengillie** [comment]
> [!Note]
> 
> Close with reason: Resolved
> 
> This issue didn't close automatically by linked pull request. Should be manually closed as completed.

**Comment by applicma** [comment]
many thanks !
