### ISSUE TITLE
[Package Issue]: Google.Chrome – Installer Hash Mismatch

### ISSUE THREAD

**Issue by florian-de** [microsoft/winget-pkgs#181365]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

The installation of Google.Chrome fails due to an installer hash mismatch. This error occurs while running the installation via WinGet.

### Steps to reproduce

winget install --id "Google.Chrome" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs

### Actual behavior

 C:\Windows\System32>"C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe" install --id "Google.Chrome" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs --scope machine      -                                                                                                                              ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 2.90 MB   ████████████████████▒▒▒▒▒▒▒▒▒▒  2.00 MB / 2.90 MB   ██████████████████████████████  2.90 MB / 2.90 MB                                                                                                                              -                                                                                                                           Found Google Chrome [Google.Chrome] Version 129.0.6668.90 This application is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Downloading https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi     -     \     |     /     -     \                                                                                                                              █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  37.0 MB /  118 MB   ████████████████████▒▒▒▒▒▒▒▒▒▒  81.5 MB /  118 MB   ██████████████████████████████   118 MB /  118 MB Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

The package should install without any hash mismatch issues.

### Environment

2024-10-10 18:46:31.506 [CORE] WinGet, version [1.8.1911], activity [{268E35D8-2EC7-4185-9F0B-48BA38528B50}]
2024-10-10 18:46:31.507 [CORE] OS: Windows.Desktop v10.0.22631.4317
2024-10-10 18:46:31.507 [CORE] Command line Args: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe"

**Comment by maumeerally** [comment]
Same issue, also Microsoft.Office is having a hash mismatch as well

**Comment by florian-de** [comment]
Error seems to be fixed. Installation successful now :)
