### ISSUE TITLE
[Package Issue]: TrackerSoftware.PDF-XChangeEditor – Installer Hash Mismatch

### ISSUE THREAD

**Issue by florian-de** [microsoft/winget-pkgs#181364]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

The installation of TrackerSoftware.PDF-XChangeEditor fails due to an installer hash mismatch. This error occurs while running the installation via WinGet.

### Steps to reproduce

winget install --id "TrackerSoftware.PDF-XChangeEditor" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs

### Actual behavior

The package downloads successfully, but the installation fails with an error stating that the installer hash does not match.

### Expected behavior

The package should install without any hash mismatch issues.

### Environment

2024-10-10 18:46:31.506 [CORE] WinGet, version [1.8.1911], activity [{268E35D8-2EC7-4185-9F0B-48BA38528B50}]
2024-10-10 18:46:31.507 [CORE] OS: Windows.Desktop v10.0.22631.4317
2024-10-10 18:46:31.507 [CORE] Command line Args: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe"

**Comment by Dragon1573** [comment]
@florian-de - Modifications are successfully published. Could you please have a try?

- See https://github.com/microsoft/winget-pkgs/pull/180449#issuecomment-2408244968

```text
16:01:14 D:\...\winget-pkgs  [master ≡] 47ms pwsh> winget download -e --id "TrackerSoftware.PDF-XChangeEditor" --source "winget"
已找到 PDF-XChange Editor [TrackerSoftware.PDF-XChangeEditor] 版本 10.4.2.390
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://downloads.pdf-xchange.com/EditorV10.x64.msi
  ██████████████████████████████   342 MB /  342 MB
已成功验证安装程序哈希
已下载安装程序: D:\Dragon1573\Downloads\TrackerSoftware.PDF-XChangeEditor_10.4.2.390\PDF-XChange Editor_10.4.2.390_X64_wix_en-US.msi
```

-----

Close with reason: Resolved

**Comment by florian-de** [comment]
Works now :) @Dragon1573

**Comment by stephengillie** [comment]
> Works now :) [@Dragon1573](https://github.com/Dragon1573)
