### ISSUE TITLE
[Package Issue]: Gimp.Gimp 2.10.38 not updated to Revision 1

### ISSUE THREAD

**Issue by a-mnich** [microsoft/winget-pkgs#181435]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Gimp received a new version 2.10.38 revision 1 and the user will be notified about the new update upon Startup of Gimp.
In winget the manifest was upgraded in place by https://github.com/microsoft/winget-pkgs/pull/178113 instead of creating a new separate version.

**Proposal:** 
- create separate package version for revision 1  `2.10.38.1`  to be detected as upgradable by winget.
- revert PR https://github.com/microsoft/winget-pkgs/pull/178113 and fix wrong DisplayName in `AppsAndFeaturesEntries`

### Steps to reproduce

- install Gimp.Gimp 2.10.38 (still available through direct link: `https://download.gimp.org/gimp/v2.10/windows/gimp-2.10.38-setup.exe`
- attempt an upgrade to 2.10.38 revision 1 through  `winget upgrade --id Gimp.Gimp`

### Actual behavior

 winget upgrade --id Gimp.Gimp
No applicable update found.

### Expected behavior

Gimp.Gimp will be upgraded to version 2.10.38 revision 1 by ` winget upgrade --id Gimp.Gimp`

### Environment

Windows-Paket-Manager (Vorschau) v1.9.2411-preview
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.4317
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.24.2411.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Aktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
ProxyCommandLineOptions                   Deaktiviert
DefaultProxy                              Deaktiviert

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/1e2de1da-61c1-4389-96b0-ab4db72e8003)

**Comment by drshtmstry** [comment]
> ### Please confirm these before moving forward
> * [x]  I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.[x]  I have not been informed if the issue is resolved in a preview version of the winget client.
> 
> ### Category of the issue
> No applicable update found.
> 
> ### Brief description of your issue
> Gimp received a new version 2.10.38 revision 1 and the user will be notified about the new update upon Startup of Gimp. In winget the manifest was upgraded in place by [#178113](https://github.com/microsoft/winget-pkgs/pull/178113) instead of creating a new separate version.
> 
> **Proposal:**
> 
> * create separate package version for revision 1  `2.10.38.1`  to be detected as upgradable by winget.
> * revert PR [Update version: GIMP.GIMP 2.10.38 installer revision 1 #178113](https://github.com/microsoft/winget-pkgs/pull/178113) and fix wrong DisplayName in `AppsAndFeaturesEntries`
> 
> ### Steps to reproduce
> * install Gimp.Gimp 2.10.38 (still available through direct link: `https://download.gimp.org/gimp/v2.10/windows/gimp-2.10.38-setup.exe`
> * attempt an upgrade to 2.10.38 revision 1 through  `winget upgrade --id Gimp.Gimp`
> 
> ### Actual behavior
> winget upgrade --id Gimp.Gimp No applicable update found.
> 
> ### Expected behavior
> Gimp.Gimp will be upgraded to version 2.10.38 revision 1 by ` winget upgrade --id Gimp.Gimp`
> 
> ### Environment
> Windows-Paket-Manager (Vorschau) v1.9.2411-preview Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> Windows: Windows.Desktop v10.0.22631.4317 Systemarchitektur: X64 Paket: Microsoft.DesktopAppInstaller v1.24.2411.0
> 
> ## WinGet-Verzeichnisse
> Protokolle %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir Benutzereinstellungen %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links Portables Linkverzeichnis (Computer) C:\Program Files\WinGet\Links Portierbarer Paketstamm (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Packages Portierbarer Paketstamm C:\Program Files\WinGet\Packages Portierbares Paketstamm (x86) C:\Program Files (x86)\WinGet\Packages Installationsprogrammdownloads %USERPROFILE%\Downloads
> 
> ## Links
> Datenschutzerklärung https://aka.ms/winget-privacy Lizenzvereinbarung https://aka.ms/winget-license Hinweise von Drittanbietern https://aka.ms/winget-3rdPartyNotice Startseite https://aka.ms/winget Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
> 
> ## Administratoreinstellung Status
> LocalManifestFiles Aktiviert BypassCertificatePinningForMicrosoftStore Deaktiviert InstallerHashOverride Deaktiviert LocalArchiveMalwareScanOverride Deaktiviert ProxyCommandLineOptions Deaktiviert DefaultProxy Deaktiviert
> 
> ### Screenshots and Logs
> ![Image](https://github.com/user-attachments/assets/1e2de1da-61c1-4389-96b0-ab4db72e8003)

Verify:
![Image](https://github.com/user-attachments/assets/a3baa73d-fe88-44df-b67a-fe2da13b3045)

DisplayName: GIMP 2.10.38-1
Version: 2.10.38

The package does not change version. It is just a installer revision for same version.
Use ` winget install --id Gimp.Gimp --force` to upgrade package.

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-pkgs/pull/182107#discussion_r1797640801

Publisher uses the same DisplayVersion for revision releases. In the repo, we can only retain one such version. Each manifest should correspond to a unique DisplayVersion in the registry for client matching logic to work properly. This should be brought up to the publisher to address i.e., use different DisplayVersion strings for revision releases


[Policy] Area-External
