### ISSUE TITLE
[Package Issue]: Package.Identifier

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#181423]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer hash does not match; this cannot be overridden when running as admin

No package found matching input criteria.

### Steps to reproduce

 winget install IObit.DriverBooster Viber.Viber Whatsapp.Whatsapp

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

No package found matching input criteria.

### Expected behavior

to be installed

### Environment

PS C:\Users> winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1910.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
PS C:\Users>

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> `WhatsApp.WhatsApp` and `Viber.Viber` will no longer added to the repository.
>
> - See https://github.com/microsoft/winget-pkgs/issues/160790#issuecomment-2198753288

**Comment by Dragon1573** [comment]
Manually verified. This issue is caused by `IObit.DriverBooster`.

```text
00:10:32 C:\...\winget-pkgs  [master ≡] 2ms pwsh> winget download IObit.DriverBooster
已找到 Driver Booster [IObit.DriverBooster] 版本 12.0.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://cdn.iobit.com/dl/driver_booster_setup.exe
  ██████████████████████████████  29.2 MB / 29.2 MB
安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash
```

![Image](https://github.com/user-attachments/assets/c903d6c6-ef3f-45fa-961c-22e2b1e2b730)
