### ISSUE TITLE
[Update Request]: Update Perfview to 3.1.16

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/winget-pkgs#181555]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Perfview

### Package Version

3.1.16

### Please describe the changes you would like to see

3.1.16 is released:

> **Roll-up through 2024/10/11.**
> 
> Performance improvements to DynamicParser.
> Fixed GetFileNameWithoutExtensionNoIllegalChars to only trim known file extensions.
> Fixed a memory leak when processing EventPipe traces.
> Added support for private/in-process loggers.

https://github.com/microsoft/perfview/releases/tag/v3.1.16

**Download:**
https://github.com/microsoft/perfview/releases/download/v3.1.16/PerfView.exe

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/181571

**Comment by vikingnope** [comment]
Kindly close as this is done
