### ISSUE TITLE
[Package Request]: WD Dashboard

### ISSUE THREAD

**Issue by theM0rzan** [microsoft/winget-pkgs#182128]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://support-en.wd.com/app/answers/detailweb/a_id/31759/~/download%2C-install%2C-test-drive-and-update-firmware-using-western-digital
Publisher: Western Digital
Package Name: WD.Dashboard
Description: The software helps check on Western Digital drives in Windows. Tools for checking health, firmware versions and updates are included.
Package Version: 4.2.2.5
Installer Url: https://wddashboarddownloads.wdc.com/wdDashboard/DashboardSetupSA.exe

**Comment by drshtmstry** [comment]
Installer does not support unattended installation.
