### ISSUE TITLE
[Package Request]: RoughGrep

### ISSUE THREAD

**Issue by vivainio** [microsoft/winget-pkgs#182569]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/vivainio/RoughGrep/releases/tag/v3.14.3
Publisher: Ville Vainio
Package Name: vivainio.RoughGrep
Description: User interface for RipGrep
Package Version: 3.14.3
Installer Url: https://github.com/vivainio/RoughGrep/releases/download/v3.14.3/RoughGrep-3.14.3.zip

**Comment by vivainio** [comment]
I am the maintainer of this application, and I am willing to publish it in WinGet in linked PR. It's a portable zip file

**Comment by Trenly** [comment]
Although it is a portable application, it depends on DLLs 

[Policy] Zip Binary

**Comment by Dragon1573** [comment]
Since _RoughGrep_ is a `*.sln` _Visual Studio Solution_ with `*.csproj` _C# Visual Studio Project_, I think it would be great introducing _WiX_ to the solution and package the project to an MSI install wizard.

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`
