### ISSUE TITLE
[Package Request]: Wesang.Yogiyo

### ISSUE THREAD

**Issue by alexkoala** [microsoft/winget-pkgs#182550]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

```
PackageIdentifier: Wesang.Yogiyo
PackageVersion: 4.0.6
PackageLocale: en-US
Publisher: Wesang Co.,Ltd.
PublisherUrl: https://www.wesang.com/
PublisherSupportUrl: https://partner.yogiyo.co.kr/faq
PrivacyUrl: https://owner.yogiyo.co.kr/owner/privacy/
PackageName: Yogiyo Order
PackageUrl: https://partner.yogiyo.co.kr/guide/order
License: Proprietary
Copyright: Copyright (c) YOGIYO. All Rights Reserved.
ShortDescription: Relay for Yogiyo Online Order System
Moniker: yogiyo-order
```
Installer Url: https://apps.rpsyogiyo.io/win/go/4.0.6/GoYogiyo_Installer_Supervisor_Net40_4.0.6.exe

`GoYogiyo_Installer_Supervisor_Net40_4.0.6.exe`(doesn't support silent install) extracts `GoYogiyo_Light_Installer_4.0.6.exe`. (supports silent install, `-q`)

**Comment by Dragon1573** [comment]
Manually checked in _Windows Sandbox_ instance.

1. `GoYogiyo_Installer_Supervisor_Net40_4.0.6.exe` seems a silent file downloader. When running it, it will download `GoYogiyo_Light_Installer_4.0.6.exe` to current working directory and automatically launch it.
2. `GoYogiyo_Light_Installer_4.0.6.exe` will first launch in background without any command line switches.
3. There seems another copy of `GoYogiyo_Light_Installer_4.0.6.exe` stored in `C:\Windows\Temp` folder be launched with several switches. Then a graphical installation wizard is shown.

> [!WARNING]
>
> Configuring the manifest with `InstallerType: zip` will automatically rename it to `*.zip` after downloading and  then perform an extraction. `GoYogiyo_Installer_Supervisor_Net40_4.0.6.exe` can be extracted as a ZIP archive.
> 
> Also, the installer failed to pass _Windows Defender SmartScreen_.
> 
> ```text
> --> Installing WinGet
> --> Disabling safety warning when running installer
> Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.
> 
> --> Configuring Winget
> Enabled admin setting 'LocalManifestFiles'.
> Enabled admin setting 'LocalArchiveMalwareScanOverride'.
> 
> --> Installing the Manifest 4.0.6
> 
> Found Go.Installer.Supervisor.Net40 [Wesang.Yogiyo] Version 4.0.6
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://apps.rpsyogiyo.io/win/go/4.0.6/GoYogiyo_Installer_Supervisor_Net40_4.0.6.exe
>   ██████████████████████████████  1.53 MB / 1.53 MB
> Successfully verified installer hash
> Archive scan detected malware. Proceeding due to --ignore-local-archive-malware-scan
> Extracting archive...
> Failed to extract the contents of the archive
> 
> --> Refreshing environment variables
> 
> --> Comparing ARP Entries
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
> ```

![Image](https://github.com/user-attachments/assets/1e6b907c-8f03-491a-8635-65879cd1acb9)
![Image](https://github.com/user-attachments/assets/97496713-2f8d-4e6a-bb26-649721812e4c)

**Comment by Dragon1573** [comment]
🎉 Direct link to offline installer is successfully found!

- Installer URL: <https://apps.rpsyogiyo.io/win/go/4.0.6/GoYogiyo_Light_Installer_4.0.6.exe>
