### ISSUE TITLE
[Package Issue]: Package.Identifier

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#182559]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

 winget install --id=EaseUS.PartitionMaster -e;

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

to be installed

### Environment

PS C:\Users> winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
PS C:\Users>

**Comment by Dragon1573** [comment]
Manually validated.

```text
22:26:51 C:\...\winget-pkgs  [master ≡] 1ms pwsh> winget download -e --id EaseUS.PartitionMaster
已找到 EaseUS Partition Master [EaseUS.PartitionMaster] 版本 19.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://d1.easeus.com/epm/free/epm1905_free_ob_B.exe
  ██████████████████████████████   116 MB /  116 MB
安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash

22:27:25 C:\...\winget-pkgs  [master ≡] 16.04s 0x8A150011 pwsh> winget download -e --id EaseUS.PartitionMaster --ignore-security-hash
已找到 EaseUS Partition Master [EaseUS.PartitionMaster] 版本 19.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://d1.easeus.com/epm/free/epm1905_free_ob_B.exe
  ██████████████████████████████   116 MB /  116 MB
安装程序哈希不匹配；由于 --ignore-security-hash 而继续进行
已下载安装程序: D:\Download\EaseUS.PartitionMaster_19.0\EaseUS Partition Master_19.0_Machine_X64_inno_zh-CN.exe

22:28:19 C:\...\winget-pkgs  [master ≡] 671ms 0x0002 pwsh> komac analyse 'D:\Download\EaseUS.PartitionMaster_19.0\EaseUS Partition Master_19.0_Machine_X64_inno_zh-CN.exe'
InstallerLocale: en-US
Architecture: x64
InstallerType: inno
InstallerUrl: https://www.example.com/
InstallerSha256: 3DB4A64796068CC26278BC70723750FF206CB7145328A2DB06B940FCAF024223
ProductCode: EaseUS Partition Master_is1
AppsAndFeaturesEntries:
- Publisher: EaseUS
  DisplayVersion: '19.0'
  ProductCode: EaseUS Partition Master_is1
ElevationRequirement: elevatesSelf

22:29:26 C:\...\winget-pkgs  [master ≡] 2ms pwsh> komac show --installer-manifest EaseUS.PartitionMaster
PackageIdentifier: EaseUS.PartitionMaster
PackageVersion: '19.0'
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://d1.easeus.com/epm/free/epm1905_free_ob_B.exe
  InstallerSha256: BD5748CE26AAC8BB578A5175B3294057920A7022AD8CAA72E1EAF88205467405
  ProductCode: EaseUS Partition Master_is1
ManifestType: installer
ManifestVersion: 1.6.0
```
