### ISSUE TITLE
[Package Issue]: PCSX2Team.PCSX2 - Version is incorrectly specified in the manifest

### ISSUE THREAD

**Issue by sharunkumar** [microsoft/winget-pkgs#182631]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

PCSX2 Installation reports the version to the system with the 'v' prefix:

![Image](https://github.com/user-attachments/assets/b1dd772d-37df-42fb-b296-acca11b47e7c)

however, in the winget manifest, the 'v' does not exist, and as a result, each time I run winget upgrade, PCSX2 always shows up even though it is in the latest version:

![Image](https://github.com/user-attachments/assets/a930eefe-b891-4343-ba46-8af937cede5d)

### Steps to reproduce

- winget install PCSX2Team.PCSX2
- winget upgrade PCSX2Team.PCSX2

### Actual behavior

- PCSX2Team.PCSX2 updates because version is different 

### Expected behavior

- PCSX2Team.PCSX2 should not update

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4317
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\Sharun\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by Trenly** [comment]
@sharunkumar  - Out of curiosity, does this behavior also happen with the latest pre-release of WinGet (https://aka.ms/GetWinGetPreview)?

**Comment by stephengillie** [comment]
Possibly related: 
- https://github.com/microsoft/winget-cli/issues/2394
- https://github.com/microsoft/winget-cli/pull/4558
