### ISSUE TITLE
[Package Issue]: Mikrotik.TheDude

### ISSUE THREAD

**Issue by VMelnalksnis** [microsoft/winget-pkgs#182741]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After installation the current version is `Unknown`.

### Steps to reproduce

1. Install the package `winget install Mikrotik.TheDude`
2. See that the version shows up as unknown
```
Name                                      Id               Version          Available        Source
---------------------------------------------------------------------------------------------------
The Dude                                  Mikrotik.TheDude Unknown          7.16             winget
```

### Actual behavior

The installed versions always is Unknown.

### Expected behavior

Installed version is correctly understood and winget does not always prompt for updates.

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.5011
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\_sort\_downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

### Screenshots and Logs

```
Found The Dude [Mikrotik.TheDude] Version 7.16
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.mikrotik.com/routeros/7.16/dude-install-7.16.exe
  ██████████████████████████████  2.22 MB / 2.22 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by Dragon1573** [comment]
🎉 Issue reproduced and identified!

The package does not write any version information to _Windows Registry_, so `winget.exe` can't get any version information from ARP Entries. `winget.exe` will mark this package as version `Unknown` and fall into an "infinite upgrade loop" ...

![Image](https://github.com/user-attachments/assets/aa02dfc6-6a95-4f3c-9e74-fce31045ed96)

Since this is a Nullsoft install wizard, `winget.exe` will not write any ARP entries for the package. All these stuff are done by the installer itself. So this might be a <https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue> with <https://github.com/microsoft/winget-pkgs/labels/Area-External>.

```text
16:54:59 D:\...\winget-pkgs  [master ≡] 5ms pwsh> komac show --installer-manifest Mikrotik.TheDude
PackageIdentifier: Mikrotik.TheDude
PackageVersion: '7.16'
InstallerType: nullsoft
ReleaseDate: 2024-09-24
Installers:
- Architecture: x64
  InstallerUrl: https://download.mikrotik.com/routeros/7.16/dude-install-7.16.exe
  InstallerSha256: D3382A4F472FF84F4174BE3A108AF77E06108C2CE7D9355248AC6D543BE8CF07
ManifestType: installer
ManifestVersion: 1.6.0
```

**Comment by stephengillie** [comment]
This is something of a known issue with packages whose installers do not write version data to the Registry.

**Comment by Trenly** [comment]
[Policy] Installer Issue
