### ISSUE TITLE
[Package Request]: VUSC 4 WIN

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#182773]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.ok2kkw.com/vusc4win_eng.htm
Publisher: OK1DIX
Package Name: VUSC 4 WIN
Description: Free VHF/UHF/SHF Contest Log Software
Package Version: 7.06
Installer Url: https://www.ok2kkw.com/vusc/vusc4win/vusc_setup_706.exe

**Comment by SpecterShell** [comment]
Unfortunately, the installer writes nothing to the ARP registry as [the author thinks the uninstaller is unnecessary for this program](https://www.ok2kkw.com/vusc/vusc4win/documentation/vusc_en.htm), which means it would not be detected by WinGet. I'll try to match using the installed files though.

**Comment by AsciiWolf** [comment]
Oops, I did not know that. Thanks!
