### ISSUE TITLE
[Package Request]: HomeBank

### ISSUE THREAD

**Issue by EduSe7en42** [microsoft/winget-pkgs#183008]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.gethomebank.org/en/downloads.php#mswindows
Publisher: Maxime DOYEN
Package Name: HomeBank-5.8.5-setup.exe
Description: HomeBank is a free software for managing personal finances, with features to track expenses and income, and generate reports and graphs.
Package Version: 5.8.5
Installer Url: https://www.gethomebank.org/public/binaries/HomeBank-5.8.5-setup.exe

**Comment by stephengillie** [comment]
Since #183061 is merged, I'll assume this PR is complete. If this is in error, please @ me and I'll reopen.
