### ISSUE TITLE
[Package Issue]: Microsoft.Office not found anymore

### ISSUE THREAD

**Issue by tb-mtg** [microsoft/winget-pkgs#183277]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

As mentioned in issue #181598, I have been using **`Winget upgrade --id Microsoft.Office`** with no problems until yesterday.

Now I get the following message: **`No installed package found matching input criteria. `**

Has this package been removed, or is there an alternative id or method to install/upgrade Microsoft 365 in Winget?

### Steps to reproduce

Winget upgrade --id Microsoft.Office

### Actual behavior

No installed package found matching input criteria.

### Expected behavior

Package is found and can be installed/upgraded.

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

**Comment by stephengillie** [comment]
Does the package show up in searches? 

```PowerShell
PS C:\ManVal> Find-WinGetPackage Microsoft.Office

Name                              Id                             Version          Source
----                              --                             -------          ------
Microsoft 365 Apps for enterprise Microsoft.Office               16.0.18129.20030 winget
Office Deployment Tool            Microsoft.OfficeDeploymentTool 16.0.17830.20162 winget
```

**Comment by tb-mtg** [comment]
No, only below appears:

```
PS C:\> winget search Microsoft.Office
Name                   Id                             Version          Source
------------------------------------------------------------------------------
Office Deployment Tool Microsoft.OfficeDeploymentTool 16.0.17830.20162 winget

```

**Comment by Dragon1573** [comment]
Package index works as expected.

Could you please try reset your source index URL settings and refresh the index?

```text
11:22:42 D:\...\winget-pkgs  [master ≡] 1ms pwsh> winget search Microsoft.Office
名称                              ID                             版本             源
-----------------------------------------------------------------------------------------
Microsoft 365 Apps for enterprise Microsoft.Office               16.0.18025.20140 winget
Office Deployment Tool            Microsoft.OfficeDeploymentTool 16.0.17830.20162 winget

11:22:47 D:\...\winget-pkgs  [master ≡] 2.039s pwsh> winget source list
名称    参数                                          显式
-----------------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0 false
winget  https://cdn.winget.microsoft.com/cache        false
11:22:51 D:\...\winget-pkgs  [master ≡] 121ms pwsh> 
```

**Comment by tb-mtg** [comment]
Yes it appears now, I didn't even have to do the reset the source or refresh the index, but it appears now:
```

Name                              Id                             Version          Source
-----------------------------------------------------------------------------------------
Microsoft 365 Apps for enterprise Microsoft.Office               16.0.18025.20140 winget
Office Deployment Tool            Microsoft.OfficeDeploymentTool 16.0.17830.20162 winget
```
```

Name    Argument                                      Explicit
--------------------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0 false
winget  https://cdn.winget.microsoft.com/cache        false
```

Not sure what happened.
Thank
