### ISSUE TITLE
[Update Request]: WinDirStat 2.0.1

### ISSUE THREAD

**Issue by jnm2** [microsoft/winget-pkgs#183304]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

WinDirStat.WinDirStat

### Package Version

2.0.1

### Please describe the changes you would like to see

There is a new release, no longer preview:
https://github.com/windirstat/windirstat/releases/tag/release/v2.0.1

See also <https://windirstat.net/download.html> for links to the same GitHub assets.

**Comment by stephengillie** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/183283 is merged, I'll assume that this Issue is complete. If this is in error, please @ me and I'll reopen.
