### ISSUE TITLE
wingetbot should not run full tests when only version, defaultlocale or locale manifest is updated.

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#18354]
# Description of the new feature/enhancement
The wingetbot should not run a full installer test when the metadata in version, defaultlocale or locale is updated, it can test if the links are valid but not run the installer.
This would be useful for when someone adds a locale or is correcting some metadata.

Example: #18352

# Proposed technical implementation details (optional)

**Comment by ItzLevvie** [comment]
There's a "Manifest-Only-Metadata" label - https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+label%3AManifest-Only-Metadata+is%3Aclosed - but that doesn't seem to get applied to PRs anymore when the manifest schema went from version `0.1.0` to `1.0.0`.

**Comment by OfficialEsco** [comment]
I think the `Azure-Pipeline-Passed` process works differently now compared to when Kevin got assigned before, since #4198 got `Azure-Pipeline-Passed` 5 min after submitting and then Kevin would add for example `Validation-Unattended-Failed` if it didn't silent install...

All PR's under /manifests/ might be hardcoded to run a full install

**Comment by jedieaston** [comment]
> All PR's under /manifests/ might be hardcoded to run a full install

But before they were under /manifests too, and I think the CI process applied Manifest-Only-Metadata, not @KevinLaMS (based on it appearing shortly after a PR opened in my experience). 

I wonder if the field names changing in schema 1.0 broke this check.

**Comment by denelon** [comment]
We have been discussing the right way to look at metadata only changes. We just hadn't created an issue yet.

**Comment by denelon** [comment]
I've been discussing this with the team. We're looking at the scope of work so it's a bit more "future proof". I've got an estimate so now I'm looking at sequencing.

**Comment by mdanish-kh** [comment]
@denelon - This one doesn't seem to be resolved. I tried testing this in 

-  #141727
