### ISSUE TITLE
Mozilla.Firefox  not upgrading even though listed in winget upgrade

### ISSUE THREAD

**Issue by rbarbrow** [microsoft/winget-pkgs#18416]
Firefox is giving unexpected results 

PS C:\Users\r> **winget upgrade Mozilla.Firefox**
No applicable update found.

however 

PS C:\Users\rbarbrow> **winget upgrade**
Name                 Id                    Version         Available    Source
-------------------------------------------------------------------------------
Mozilla Firefox      Mozilla.Firefox       78.0.2          89.0.1       winget

also **winget upgrade --all** 

upgrades all other packages but "skips" mozilla.firefox with out a mention

**Comment by KaranKad** [comment]
Might be related to this https://github.com/microsoft/winget-cli/issues/1191#issuecomment-865210093

**Comment by OfficialEsco** [comment]
Hey can you try now? Hopefully #18751 solved this..

**Comment by OfficialEsco** [comment]
Duplicate of #18751
