### ISSUE TITLE
[Package Request]: idigdoug.TextTools

### ISSUE THREAD

**Issue by richardsondev** [microsoft/winget-pkgs#184377]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/idigdoug/TextTools/releases/
Publisher: idigdoug
Package Name: TextTools
Description: xargs for Windows (wargs), iconv for Windows (wconv), Text conversion library
Package Version: 1.1.0
Installer Url: https://github.com/idigdoug/TextTools/releases/download/v1.1.0/TextUtils-X86-64.zip

**Comment by richardsondev** [comment]
#184376

**Comment by richardsondev** [comment]
https://github.com/microsoft/winget-pkgs/pull/184376#issuecomment-2445729993

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Already resolved by #184376

CC @stephengillie

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Resolved**.
> 
> * Already resolved by [New package: idigdoug.TextTools version 1.1.0 #184376](https://github.com/microsoft/winget-pkgs/pull/184376)
> 
> CC [@stephengillie](https://github.com/stephengillie)
