### ISSUE TITLE
Apple.iTunes client doesn't install Apple Mobile Device Support

### ISSUE THREAD

**Issue by andrewbaker-uk** [microsoft/winget-pkgs#18433]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

# Steps to reproduce

Install iTunes via WinGet

winget install iTunes

# Expected behavior

The ability to use the device within iTunes for syncing, updating or restoring firmware

# Actual behavior

The error "This device cannot be used because the required software is not installed. Run the iTunes installer to remove iTunes, then install iTunes again."

# Environment

```none
[winget --info]
Windows Package Manager version: 1.0.11451
Windows: Windows.Desktop v10.0.21390.2025
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

**Comment by denelon** [comment]
@andrewbaker-uk did you already have iTunes installed on your machine?

**Comment by andrewbaker-uk** [comment]
Hi @denelon,

This was a clean install of 21390 on the dev channel but I have also experienced this on production build 19043

Thanks,

Andrew

**Comment by denelon** [comment]
@andrewbaker-uk thanks, I'm not sure what is causing that error. Wild guesses at this point.

**Comment by KaranKad** [comment]
Did you restart your computer after installing this application?
looking at the switches here [Apple.iTunes.installer.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/Apple/iTunes/12.11.3.17/Apple.iTunes.installer.yaml) it looks like this application requires a restart after installation.

winget-cli needs a feature to tell you that restart is needed after installing a specific application.

**Comment by andrewbaker-uk** [comment]
Hi @KaranKad nope the iTunes installer doesn't require a reboot after installation if done outside of winget. Or at least I have never been asked to reboot after installing

**Comment by jedieaston** [comment]
I can confirm this behavior with the current manifest. Looks like Chocolatey gets around it by unzipping the exe file and installing the AppleMobileDeviceSupport64.msi file via msiexec. A brief Google search shows this is the typical fix for deploying it via SCCM too.

Unless someone has a contact at Apple that they can ask to fix this (because this *is* a bug in Apple's installer), I think the easiest workaround at the moment would be to add iTunes to the Microsoft Store source so people can choose to install that version.

**Comment by andrewbaker-uk** [comment]
Adding iTunes from the store does sound like a quicker option.

Only other way is to use power shell to extract the downloaded MSI file and then install the extracted MSI files from script
[however this would rely on adding ps1 support to the winget-cli](https://github.com/microsoft/winget-cli/issues/298)

**Comment by Trenly** [comment]
> Unless someone has a contact at Apple that they can ask to fix this (because this is a bug in Apple's installer), 

[Policy] Area-External
