### ISSUE TITLE
[Package Request]: Microsoft.msodbcsql.11

### ISSUE THREAD

**Issue by BurnsSilver** [microsoft/winget-pkgs#184471]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.microsoft.com/en-ca/download/details.aspx?id=36434
Publisher: Microsoft
Package Name: Microsoft.msodbcsql.11
Description: The Microsoft ODBC Drivers for SQL Server are stand-alone ODBC drivers which provide an application programming interface (API) implementing the standard ODBC interfaces to Microsoft SQL Server.
Package Version: 12.0.5543.11
Installer Url: https://download.microsoft.com/download/5/7/2/57249A3A-19D6-4901-ACCE-80924ABEB267/ENU/x64/msodbcsql.msi

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Similar requests of #133793.
