### ISSUE TITLE
manifests/i/ImageMagick/ImageMagick is problamatic

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-pkgs#18448]
[ImageMagick/ImageMagick](https://github.com/microsoft/winget-pkgs/tree/master/manifests/i/ImageMagick/ImageMagick)
This applications installer does not specify it's version properly. Latest version of this application is `7.1.0-1` but after installing it says `7.1.0`. Previous version of this application was `7.1.0-0` but it also reported as `7.1.0` in control panel. Now I have submitted its latest version #18447 according to control panel information to avoid `winget upgrade` issue but people on previous version won't know if there is a update because `PackageVersion` is same as the previous version.

**Comment by vedantmgoyal2009** [comment]
Can be fixed by 1.1 manifest schemas.

**Comment by quhxl** [comment]
That was solved by ImageMagick/ImageMagick#4133 (as seen in #27222)
