### ISSUE TITLE
[Update Request]: Microsoft.BingWallpaper 2.0.1.1

### ISSUE THREAD

**Issue by KarbitsCode** [microsoft/winget-pkgs#184512]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.BingWallpaper

### Package Version

2.0.1.1

### Please describe the changes you would like to see

There is a new release (2.0.1.1) available.
Download Page Url: https://bingwallpaper.microsoft.com/
Direct Download Url: https://download.microsoft.com/download/a/b/9/ab92b51f-92ea-4d46-9d21-9446bd20eed8/Installer/2.0.1.1/Bing/W017/BingWallpaper.exe

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> - Duplicate of #174661 
> - There're already 3 attempts for submitting previous version of this package
>   - See #174665
>   - See #166300 
>   - See #160817

**Comment by KarbitsCode** [comment]
> Warning
> 
> * Duplicate of [[Update Request]: Microsoft.BingWallpaper 2.0.0.9 #174661](https://github.com/microsoft/winget-pkgs/issues/174661)
> * There're already 3 attempts for submitting previous version of this package
>   
>   * See [New version: Microsoft.BingWallpaper version 2.0.0.9 #174665](https://github.com/microsoft/winget-pkgs/pull/174665)
>   * See [Microsoft.BingWallpaper version 2.0.0.8 #166300](https://github.com/microsoft/winget-pkgs/pull/166300)
>   * See [Microsoft.BingWallpaper version 2.0.0.6 #160817](https://github.com/microsoft/winget-pkgs/pull/160817)

I know, maybe this is the last try to push update for this package (if its still doesn't work)
