### ISSUE TITLE
[Update Request]: typst version 0.12.0

### ISSUE THREAD

**Issue by m-haug** [microsoft/winget-pkgs#184753]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Typst.Typst

### Package Version

0.12.0

### Please describe the changes you would like to see

There is a new release available at https://github.com/typst/typst/releases/download/v0.12.0/typst-x86_64-pc-windows-msvc.zip.

**Comment by a-mnich** [comment]
resolved by #184345

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Resolved by #184345 

CC @stephengillie 🙏🏼

**Comment by stephengillie** [comment]
> resolved by [#184345](https://github.com/microsoft/winget-pkgs/pull/184345)

> Note
> 
> Close with reason: **Resolved**.
> 
> * Resolved by [New version: Typst.Typst version 0.12.0 #184345](https://github.com/microsoft/winget-pkgs/pull/184345)
> 
> CC @ stephengillie 🙏🏼

Thank you both.
