### ISSUE TITLE
[Upstream maintainer's request]: Typography of PDF Arranger

### ISSUE THREAD

**Issue by dreua** [microsoft/winget-pkgs#184815]
Hi, I'm co maintainer of the PDF Arranger project (upstream) and I noticed that the project name is spelled as `pdfarranger` in the list where all the other apps are spelled with capitalization and spaces. This looks odd and ignores the preferred spelling which is `PDF Arranger`. (For executables and in contexts where spaces or capitalization are uncommon or not possible, `pdfarranger` would be correct but that does not seem to be the case here.)

![Image](https://github.com/user-attachments/assets/68ffa11f-2445-4fba-a282-1f855e655f21)

I have no knowledge of winget but my guess would be that this setting here is wrong:

https://github.com/microsoft/winget-pkgs/blob/ad4d662a6dedd317f223bc060c4afa877691b6e1/manifests/p/PDFArranger/PDFArranger/1.11.1/PDFArranger.PDFArranger.locale.en-US.yaml#L12

Can this just be changed to PDF Arranger in the next version or are there any side effects?

Thanks for maintainting the winget libraray by the way 👍

**Comment by SpecterShell** [comment]
WinGet uses the ARP (Add/Remove Programs) entries the installers wrote to the registry to match the packages. These entries can be found in the "Programs and Features" in the Control Panel or the "Installed Apps" in the Settings.

For this package, the ARP entry is like this:

![Image](https://github.com/user-attachments/assets/b380c83f-a17a-4d7b-a073-138f0e17456b)

You might need to update the name here: https://github.com/pdfarranger/pdfarranger/blob/d7d0c52be6076fe3e5964f8b6e4877103d665eec/setup.py#L106

**Comment by dreua** [comment]
Many thanks for your very quick and helpful reply and the PRs! It looks to me like you changed the Publisher and PackageName for 1.11.1 already while we haven't changed it in the already released installer, that will only make it in the next release. I'm just worried that this may lead to problems when people want to install/uninstall/update the old versions, but maybe the name doesn't really matter?
