### ISSUE TITLE
[Package Issue]: Ghisler.TotalCommander - Removed old Versions

### ISSUE THREAD

**Issue by thmeyer-msft** [microsoft/winget-pkgs#184972]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

All older Total Commander Versions were removed. The reason for that is, that the URLs return 404, but they used the wrong scheme. 

Please see #158276 ; and history https://github.com/microsoft/winget-pkgs/commits/master/manifests/g/Ghisler/TotalCommander 

Wrong Scheme: https://totalcommander.ch/**win**/tcmd1102x64.exe

Corrcect Scheme: 
https://totalcommander.ch/1103/tcmd1103x64.exe

https://totalcommander.ch/1102/tcmd1102x64.exe

https://totalcommander.ch/1052/tcmd1052x64.exe

Do we plan to add the older versions back again? 

@stephengillie - What would be the plans for this? 

### Steps to reproduce

Try to install TotalCommander Version 10.52

### Actual behavior

You can't install older versions since 11.03

### Expected behavior

You're able to install versions like 11.02 or 10.52 

### Environment

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by stephengillie** [comment]
HI @thmeyer-msft,

> @ stephengillie - What would be the plans for this?

The package should be readded. New PRs will be needed to make this happen. I've put labels onto this PR, to indicate to community members that their help here is welcome in creating these PRs.

**Comment by thmeyer-msft** [comment]
Added older Version again.. 

11.02, 11.01, 11.00, 10.52

#185314 ; #185313 ; #185312 ; #185311

**Comment by stephengillie** [comment]
> Added older Version again..
> 
> 11.02, 11.01, 11.00, 10.52
> 
> [#185314](https://github.com/microsoft/winget-pkgs/pull/185314) ; [#185313](https://github.com/microsoft/winget-pkgs/pull/185313) ; [#185312](https://github.com/microsoft/winget-pkgs/pull/185312) ; [#185311](https://github.com/microsoft/winget-pkgs/pull/185311)

Since these PRs are merged, I'll assume that this Issue is complete. If this is incorrect, please @ me and I'll reopen.
