### ISSUE TITLE
[Update Request]: SoftwareOK.Q-Dir

### ISSUE THREAD

**Issue by bitspyer** [microsoft/winget-pkgs#184934]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SoftwareOK.Q-Dir

### Package Version

11.84

### Please describe the changes you would like to see

New Release on WebPage (11.84) available. 

Website: https://www.softwareok.com/?Download=Q-Dir

**Comment by thmeyer-msft** [comment]
See pull request #184966

**Comment by stephengillie** [comment]
> See pull request [#184966](https://github.com/microsoft/winget-pkgs/pull/184966)
