### ISSUE TITLE
[Package Issue]: Package.Identifier Winget auto update is removing Adobe Acrobat Reader registry entries.

### ISSUE THREAD

**Issue by g2hp** [microsoft/winget-pkgs#185713]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget Auto Update is removing registry keys after upgrading adobe reader 32 bit to the version i.e. 24.003.20112. I am also not sure that the same issue will exist with the next update or not.

### Steps to reproduce

1. Install Adobe Acrobat reader 32 bit package older than 24.003.20112 by creating the two registries at below location -
HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown with "bAcroSuppressUpsell" -Value 1 and "bUpdater" -Value 0 

1. Now update the product with winget to upgrade to 24.003.20112, it will remove the above two registry keys.

### Actual behavior

When we update Adobe Acrobat reader 32 bit product using using SCUP, we do not have this issue.

### Expected behavior

After upgrading to Adobe acrobat reader 32 bit to  24.003.20112 version or higher , it should not remove the registries.

### Environment

C:\Users\924173>winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4317
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

### Screenshots and Logs

[Winget is removing adobe reader registries.docx](https://github.com/user-attachments/files/17523075/Winget.is.removing.adobe.reader.registries.docx)

**Comment by Trenly** [comment]
[Policy] Installer Issue
