### ISSUE TITLE
[Update Request]:

### ISSUE THREAD

**Issue by drweb86** [microsoft/winget-pkgs#185744]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SiarheiKuchuk.BUtil

### Package Version

2024.10.25

## Changes

- Old task format tasks are automigrated during load to the latest format.
After half a year old format version support will be dropped. Automigrate of old all tasks happens on load of UI apploication and on executing any task.
- Old storage format will be upgraded to the latest. Format upgrade is repacking of 7-zip files in the storage.
During upgrade Storage Quota setting will be disregarded.
Upgrade is done by chunks by 50 files. It might take some time.
During uppgrade you can stop it at any moment but except during state upload (which might damage the backup index).
Upgrade is started on any task execution.
Old storage format will be dropped after half a year. You will need to use previous app version to open it.
If you have huge backup on slow remote NAS, consider recreating backup from scratch.
- AvaloniaUI was updated to 11.1.4

## Removed Features

- Synchroniпzation mode subdirectory parameter is removed.
It is removed because in secure scenarios you need to create a separate account and separate storage for such tasks.
If you were using this parameter - edit and save sync task given that this param will be empty.

## New Features

- Possibility to specify minimum last write time for import of pictures.
Supported case: user moved to new PC and needs to import files he created after some point in the time.

## Bug Fixes

- SHA 512 hashes were not calculated.
! Hashes cache was inproperly calculated on adding new files.
- If hashes cache had incorrect JSON, application failed to start task.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Resolved by #185745

CC @drweb86 @stephengillie
