### ISSUE TITLE
[Update Request]: hledger 1.40

### ISSUE THREAD

**Issue by Clindbergh** [microsoft/winget-pkgs#186058]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

simonmichael.hledger

### Package Version

1.40

### Please describe the changes you would like to see

Update hledger to version 1.40.

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Should be manually closed as completed, since this issue was already resolved.
>
> - Already resolved by #186059

CC @stephengillie

**Comment by stephengillie** [comment]
> Tip
> 
> Should be manually closed as completed, since this issue was already resolved.
> 
> * Already resolved by [Hledger 1.40 #186059](https://github.com/microsoft/winget-pkgs/pull/186059)
> 
> CC [@stephengillie](https://github.com/stephengillie)
