### ISSUE TITLE
[Update Request]: New Version for qBittorrent

### ISSUE THREAD

**Issue by H-Jonathan** [microsoft/winget-pkgs#186764]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

qBittorrent.qBittorrent

### Package Version

5.0.1

### Please describe the changes you would like to see

What type of update are you requesting?

A new version of an existing package
Current Package Identifier
qBittorrent.qBittorrent

Package Version
5.0.1

Please describe the changes you would like to see

There is a [new release](https://sourceforge.net/p/qbittorrent/activity/?page=0&limit=100#6720074917ea732304b1ca01) available.

**Comment by drshtmstry** [comment]
- #186410

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Resolved by #186410 

CC @stephengillie @H-Jonathan

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Resolved**.
> 
> * Resolved by [New version: qBittorrent.qBittorrent version 5.0.1 #186410](https://github.com/microsoft/winget-pkgs/pull/186410)
> 
> CC [@stephengillie](https://github.com/stephengillie) [@H-Jonathan](https://github.com/H-Jonathan)
