### ISSUE TITLE
add Scratch

### ISSUE THREAD

**Issue by waterblock79** [microsoft/winget-pkgs#1868]
add scratch in winget please.

link: 

[https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.11.1.exe](https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.11.1.exe)

Info:

[https://scratch.mit.edu/download](https://scratch.mit.edu/download)

**Comment by VincentDrevet** [comment]
Hello,

I added scratch (PL #1998 ).

Best regards,

**Comment by VincentDrevet** [comment]
Hello,

PL was accepted, I think this issue can be closed now.

Best regards,

**Comment by waterblock79** [comment]
> Hello,
> 
> PL was accepted, I think this issue can be closed now.
> 
> Best regards,

thanksXD
