### ISSUE TITLE
[Notice] Package ID change: Microsoft.GDK.* to Microsoft.Gaming.GDK

### ISSUE THREAD

**Issue by RuthUlloa** [microsoft/winget-pkgs#186890]
Dear Community, 

We are excited to announce some important upcoming changes to our GDX WinGet packages. 

We are remapping the existing Microsoft.GDK.* (e.g. Microsoft.GDK.2303) packages to the new Microsoft.Gaming.GDK format using [Semantic Versioning,](https://semver.org/) following the YYMM.Q.<buildnumber> structure. 

This change enhances side-by-side scenarios and maintains a unified package structure. 

List of packages to be renamed: 

Microsoft.GDK.2303, Microsoft.GDK.2306, Microsoft.GDK.2310, Microsoft.GDK.2403, Microsoft.GDK.2406 

They would be renamed to the single ID Microsoft.Gaming.GDK, and they will be differentiated by the package version in the semantic versioning format previously mentioned.

**Comment by stephengillie** [comment]
Hi @RuthUlloa and @MattHyman,

This `PackageIdentifier` move appears to have been successful. Since all of the linked PRs are merged or closed, I'll assume this Issue is complete. If this is in error, please @ me and I'll reopen.

**Comment by RuthUlloa** [comment]
Yes. Migration is completed. So this issue can be closed.
