### ISSUE TITLE
[Update Request]: 3TSofwareLabs.Studio3T 2024.4.0

### ISSUE THREAD

**Issue by nascosto** [microsoft/winget-pkgs#187101]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

3TSoftwareLabs.Studio3T

### Package Version

2024.4.0

### Please describe the changes you would like to see

There is a new release available: 2024.4.0.
Download link: https://download.studio3t.com/studio-3t/windows/2024.4.0/studio-3t-x64.zip

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**
>
> - Resolved by #187100 

CC @nascosto @stephengillie

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Resolved**
> 
> * Resolved by [New version: 3TSoftwareLabs.Studio3T version 2024.4.0 #187100](https://github.com/microsoft/winget-pkgs/pull/187100)
> 
> CC [@nascosto](https://github.com/nascosto) [@stephengillie](https://github.com/stephengillie)
