### ISSUE TITLE
https://github.com/Autodesk-AutoCAD-Crack-Keygen/

### ISSUE THREAD

**Issue by salman8385khan28** [microsoft/winget-pkgs#187256]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

https://github.com/Autodesk-AutoCAD-Crack-Keygen/
https://github.com/Autodesk-AutoCAD-Crack-Keygen/

**Comment by ItzLevvie** [comment]
Close with reason: Spam;
