### ISSUE TITLE
https://github.com/IObit-Uninstaller-Pro-Key/

### ISSUE THREAD

**Issue by salman8385khan28** [microsoft/winget-pkgs#187253]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

https://github.com/IObit-Uninstaller-Pro-Key/
https://github.com/IObit-Uninstaller-Pro-Key/

**Comment by ItzLevvie** [comment]
Close with reason: Spam;
