### ISSUE TITLE
[Package Issue]: BleachBit.BleachBit - Interactive Install Choice not possible

### ISSUE THREAD

**Issue by Anutrix** [microsoft/winget-pkgs#187864]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

No Install choice option for Bleachbit via winget.
Elevated and non-elevated window, `install` without only `-i`(i.e, without explicit scope):
![Image](https://github.com/user-attachments/assets/a2534d35-acdd-4cf2-8161-e42044fbd547)

If we run --scope machine while elevated, it works but has user-level option disabled:
![Image](https://github.com/user-attachments/assets/a7c7c216-5be8-405c-a666-bdec88364b68)

If we run --scope machine while non-elevated, it gives following error but it doesn't seem to be a problem:
```
PS C:\Users\Anutrix> winget install -i BleachBit.BleachBit --scope machine
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070005 : unknown error
```

### Steps to reproduce

1. Just run `winget install -i BleachBit.BleachBit` in Windows Terminal.
2. Try in elevated and non-elevated. The install option is always pre-determined and never a choice.

### Actual behavior

![Image](https://github.com/user-attachments/assets/a2534d35-acdd-4cf2-8161-e42044fbd547)

### Expected behavior

This is how it looks when installer is directly run as admin:
![Image](https://github.com/user-attachments/assets/5e281744-0d9c-42c5-b7fc-14cca756f5a6)
It should be possible to do choose via winget.

### Environment

Windows Package Manager v1.9.25180
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2161
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25180.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by SpecterShell** [comment]
> Elevated and non-elevated window, `install` without only `-i`(i.e, without explicit scope):

> If we run --scope machine while elevated, it works but has user-level option disabled:

WinGet prefers user scope over machine scope, and by default chooses the user scope when it is available. For this package, WinGet passed the `/currentuser` switch (or `allusers` in the machine scope) to the installer, and the installer itself disabled another option. This is somehow expected.

> If we run --scope machine while non-elevated, it gives following error but it doesn't seem to be a problem:

This is a client bug. See #3898.

**Comment by Anutrix** [comment]
> > If we run --scope machine while non-elevated, it gives following error but it doesn't seem to be a problem:
> 
> This is a client bug. See [#3898](https://github.com/microsoft/winget-pkgs/pull/3898).

Is this link correct?

**Comment by SpecterShell** [comment]
> > > If we run --scope machine while non-elevated, it gives following error but it doesn't seem to be a problem:
> > 
> > 
> > This is a client bug. See [#3898](https://github.com/microsoft/winget-pkgs/pull/3898).
> 
> Is this link correct?

Sorry. This one: https://github.com/microsoft/winget-cli/issues/3011
