### ISSUE TITLE
[New Feature]:

### ISSUE THREAD

**Issue by helloworld1010101** [microsoft/winget-pkgs#188164]
### Description of the new feature/enhancement

I would like a file un-zipper built in for downloads packaged in .zip, .7z, and .rar etc.

### Proposed technical implementation details (optional)

by re-writing the code of WinGet and writing a piece of code that detects the file format and has the file unzipping function in programs such as Windows Explorer a.k.a explorer.exe,Or could have a Windows Explorer window where the users can unzip the files themselves.

**Comment by Trenly** [comment]
Zip files are already a supported type - https://github.com/microsoft/winget-cli/blob/03587c2162d609f4948bbdea20e18769bfd58b29/schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json#L62


* Duplicate of https://github.com/microsoft/winget-cli/issues/2899

**Comment by helloworld1010101** [comment]
> Zip files are already a supported type - https://github.com/microsoft/winget-cli/blob/03587c2162d609f4948bbdea20e18769bfd58b29/schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json#L62
> 
>     * Duplicate of [Support installing other archive formats winget-cli#2899](https://github.com/microsoft/winget-cli/issues/2899)

Yeah but 7zip files arent supported so programs packaged in .7z like DolphinEmulator.DolphinEmulator for their new versions above 5.0
