### ISSUE TITLE
[Package Request]: Sly

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#188149]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/kra-mo/sly/releases
Publisher: kramo
Package Name: Sly
Description: A Friendly Image Editor
Package Version: 0.4.0
Installer Url: https://github.com/kra-mo/sly/releases/download/v0.4.0/Sly-0.4.0-Windows.msix

**Comment by Dragon1573** [comment]
Emm... What's wrong with the installer file? 😕

```text
12:52:51 D:\...\winget-pkgs  [master ≡ +1 ~0 -0 !] 11.3s pwsh> winget install -m .\manifests\k\Kramo\Sly\0.4.0\
已找到 Sly [Kramo.Sly] 版本 0.4.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
已成功验证安装程序哈希
正在启动程序包安装...
  ▌                               2%
安装程序失败，退出代码为: 0x800b0109 : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
```

**Comment by SpecterShell** [comment]
The MSIX installer is unsigned.

https://github.com/microsoft/winget-cli/issues/424
