### ISSUE TITLE
[Package Issue]: `yt-dlp.yt-dlp-gui` should be `dsymbol.yt-dlp-gui`; wrong publisher, not an official `yt-dlp` package

### ISSUE THREAD

**Issue by aisgbnok** [microsoft/winget-pkgs#188395]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The package [`yt-dlp.yt-dlp-gui`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/y/yt-dlp/yt-dlp-gui/) does not follow the [winget `Publisher.Package` `PackageIdentifier` standard.](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#what-is-a-package) Using `yt-dlp.yt-dlp-gui` as the `PackageIdentifier` implies that `yt-dlp` is the publisher of `yt-dlp-gui` which is not the case. This is misleading and can cause confusion.

The publisher is actually [`dsymbol`](https://github.com/dsymbol/yt-dlp-gui) and does not appear to be affiliated with the `yt-dlp` publisher/organization.

Related:
- #180229

### Steps to reproduce

N/A

### Actual behavior

N/A

### Expected behavior

`PackageIdentifier` should should align with the actual publisher and package name: `dsymbol.yt-dlp-gui`.

### Environment

N/A

**Comment by aisgbnok** [comment]
I don't have any experience with moving `PackageIdentifier`s, anyone is free to solve this. Thanks.

**Comment by Trenly** [comment]
@aisgbnok - If you have ever used [YamlCreate](https://github.com/microsoft/winget-pkgs/tree/master/doc/tools/YamlCreate.md), you can just go to the main folder and run `./Tools/YamlCreate.ps1`, select option `6` and it should walk you though it. There will be a warning to not use the mode unless you know what you're doing, but that's mostly to discourage moving packages at random. I'd recommend having both Git (`winget install git.git`) and the GitHub CLI (`winget install GitHub.cli`) configured, as then it can automatically create the PRs for you. 

If you'd like me to move the package, I'm happy to do that, but thought you might want to try it yourself. Just let me know if you'd still like me or someone else to move it

**Comment by aisgbnok** [comment]
I see. Well that was pretty simple, thank you for the help.

- #188425
- #188426
