### ISSUE TITLE
ES.EXE "Error 8: Everything IPC window not found. Please make sure Everything is running" if voidtools.Everything 1.4.1.1009 installed using winget

### ISSUE THREAD

**Issue by craiglandis** [microsoft/winget-pkgs#18857]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When I have **voidtools.Everything 1.4.1.1009** installed via winget, **ES.EXE** (the voidtools Everything CLI) fails with error:

```
Error 8: Everything IPC window not found. Please make sure Everything is running
```
The Everything GUI search works fine.
And ES.EXE works fine if I install it using **Everything-1.4.1.1009.x64-Setup.exe** instead of from winget - 

https://www.voidtools.com/Everything-1.4.1.1009.x64-Setup.exe

This error happens despite the fact that the Everything service is definitely running, which I confirmed:

```
C:\> get-service everything

Status   Name               DisplayName
------   ----               -----------
Running  Everything         everything
```

-->
# Steps to reproduce

If it matters, all of this was done from elevated PS:

Use winget to install **voidtools.Everything**
```
winget install voidtools.Everything --exact --silent
```
Download and extract the Everything CLI tool ES.EXE - https://www.voidtools.com/ES-1.1.0.18.zip
Confirm Everything service is running
```
C:\> get-service everything

Status   Name               DisplayName
------   ----               -----------
Running  Everything         everything
```
Try a search using ES.EXE - 
```
C:\> es notepad.exe
Error 8: Everything IPC window not found. Please make sure Everything is running
```
# Expected behavior

ES.EXE should return search results instead of failing with "IPC window not found", regardless if Everything was installed via winget or the normal installer, assuming the Everything service is confirmed to be running

# Actual behavior

ES.EXE fails

```Error 8: Everything IPC window not found. Please make sure Everything is running```

# Environment

```
C:\> winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1052
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by denelon** [comment]
@craiglandis I don't know this tool so here is a question and a comment: 

Did you restart the shell/terminal after the install?

I'm wondering if this is just a path issue that isn't getting registered until the next shell/terminal restart.

**Comment by craiglandis** [comment]
> @craiglandis I don't know this tool so here is a question and a comment:
> 
> Did you restart the shell/terminal after the install?
> 
> I'm wondering if this is just a path issue that isn't getting registered until the next shell/terminal restart.

I even went so far as to restart Windows entirely, still same problem after restarting Windows.

**Comment by quhxl** [comment]
If I uncheck the “Start Every

**Comment by quhxl** [comment]
If I uncheck "Start Everything" at the end of the manual installer, then I can reproduce the error without winget. The problem is not with winget, in my opinion.

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your issue still persists. 

If as @quhxl mentioned, the error can be reproduced outside of WinGet, opening an issue with Voidtools would be the best next step

###### Close with reason: Stale;
