### ISSUE TITLE
NAPS2 install not detected

### ISSUE THREAD

**Issue by MattDahEpic** [microsoft/winget-pkgs#18855]
# Brief description of your issue
NAPS2 install not detected
# Steps to reproduce

```
> winget install NAPS2
```

# Expected behavior

```
> winget list NAPS2
Name  Id             Version
----------------------------
NAPS2 Cyanfish.NAPS2 6.1.2
```

# Actual behavior

```
> winget list NAPS2
Name  Id                                     Version
----------------------------------------------------
NAPS2 {302A19D3-0688-4D7E-9B42-040BB34C665F} 6.1.2
```

# Environment

```none
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19042.1052
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```
![image](https://user-images.githubusercontent.com/7366951/123459321-5f49f500-d5a3-11eb-93ce-155b44a958d2.png)
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{302A19D3-0688-4D7E-9B42-040BB34C665F}`:
![image](https://user-images.githubusercontent.com/7366951/123460139-6ae9eb80-d5a4-11eb-86d7-f661dd782c75.png)

**Comment by ItzLevvie** [comment]
![image](https://user-images.githubusercontent.com/11600822/123513684-45cda980-d686-11eb-8d32-0da0d3299b0e.png)
