### ISSUE TITLE
[Update Request]: Agilent.LabAdvisor 2.21.583

### ISSUE THREAD

**Issue by Spacefish** [microsoft/winget-pkgs#188769]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Agilent.LabAdvisor

### Package Version

2.21.583

### Please describe the changes you would like to see

New Version of the software released. PR is here: https://github.com/microsoft/winget-pkgs/pull/188686

**Comment by Spacefish** [comment]
#188686

**Comment by stephengillie** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/188686 is merged, I'll assume that this Issue is complete. If this is in error, please @ me and I'll reopen.
