### ISSUE TITLE
[Package Issue]: Minitool.PartitionWizard.Free is installing pro version instead of the free one.

### ISSUE THREAD

**Issue by yokowasis** [microsoft/winget-pkgs#188882]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

As the name of the package implies, it should install the free version instead of the paid / demo / pro one.

### Steps to reproduce

winget uninstall Minitool.PartitionWizard.Free

### Actual behavior

Installing Pro version of Minitool partition wizard that requires license

### Expected behavior

Installing free version that dont require license.

### Environment

Windows Package Manager v1.9.25180                                                                                      Copyright (c) Microsoft Corporation. All rights reserved.                                                                                                                                                                                       Windows: Windows.Desktop v10.0.26100.2033                                                                               System Architecture: X64                                                                                                Package: Microsoft.DesktopAppInstaller v1.24.25180.0

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_.

![Image](https://github.com/user-attachments/assets/36c50f73-31d1-47fd-be34-260a8b6ec003)
![Image](https://github.com/user-attachments/assets/f5ad338d-d546-4768-b338-510aae2cb042)
![Image](https://github.com/user-attachments/assets/53f41bd7-cd10-4a17-bb05-f79f287ff6ef)
