### ISSUE TITLE
[Update Request]: Wings3d to 2.3

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#189442]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Wings3D.Wings3D

### Package Version

2.3

### Please describe the changes you would like to see

https://sourceforge.net/projects/wings/files/wings/2.3/

Changelog: https://sourceforge.net/projects/wings/files/wings/2.3/README-22.txt/download

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Seems this package is interactive-only. There's a step asking users accept installing `Microsoft.VCRedist.2015+.*` version `14.29.30139.0`. This behavior can't be suppressed by adding it as a `PackageDependency` and install ahead externally.

**Comment by luzpaz** [comment]
Hi @dgud 👋   
Perhaps there can be a modification made upstream Wings3D to accommodate this ?

**Comment by dgud** [comment]
What do I need do?

**Comment by Dragon1573** [comment]
> What do I need do?

This package will ask users manually accept installing Visual C++ Runtime, and this step can't be suppressed.

Can this step be suppressed in newer versions? Can it detect if a valid Visual C++ Runtime newer than `14.29.30139.0` is already installed? Then we can manually ad Visual C++ Runtime as a dependency in manifest and silently install it ahead. Then _Wings3D_ can install soon after it without users' interactions.

**Comment by dgud** [comment]
Yeah I noticed that after asking the question, I don't know why it behaves like that I need to take a look, was many years
since I poked around in the installer.

I'll get back to you.
