### ISSUE TITLE
installer information doesn't change after PR

### ISSUE THREAD

**Issue by MerrickZ** [microsoft/winget-pkgs#189544]
Hi,
I've modified a manifest file with same version via [PR 189333](https://github.com/microsoft/winget-pkgs/pull/189333) , the manifest file in winget-pkgs [was changed](https://github.com/microsoft/winget-pkgs/blob/master/manifests/z/zufuliu/notepad4/4.24.05r5242/zufuliu.notepad4.installer.yaml) , but when I try ```winget show notepad4``` or ```wingetcreate show zufuliu.notepad4```, it is still the old version.

Console output:
[wc-202411080826.txt](https://github.com/user-attachments/files/17670994/wc-202411080826.txt)

Winget logs:
[WinGet-2024-11-08-10-12-35.609.log](https://github.com/user-attachments/files/17671720/WinGet-2024-11-08-10-12-35.609.log)

What could I do? Thanks.

**Comment by Trenly** [comment]
@MerrickZ - this is because 24.09r5472 is considered a higher version than 4.24.05r5242.  If you want to show a specific version, use the `--version` option with `winget show`. Otherwise, the manifests for the incorrect versions will need to be updated or removed

**Comment by MerrickZ** [comment]
Understood! Thanks!
