### ISSUE TITLE
[Update Request]: LINE Update (v9.4.0.3476)

### ISSUE THREAD

**Issue by yippo-dev** [microsoft/winget-pkgs#189854]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

LINE.LINE

### Package Version

9.4.0.3476

### Please describe the changes you would like to see

There's a new update available for Line. This update brings the app to version 9.4.0.3476.

You can download the update directly from the same URL: https://desktop.line-scdn.net/win/new/LineInst.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> It seems newer version (`v9.4.0.3476` here) becomes online web installer "wrapper". The "wrapper" does not support silent install.
