### ISSUE TITLE
[Package Request]: UEC- Unreal Engine CLI helper tool

### ISSUE THREAD

**Issue by Leinnan** [microsoft/winget-pkgs#190139]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Leinnan/uec
Publisher: MevLyshin
Package Name: uec
Description: Unreal Engine CLI helper tool
Package Version: 0.2.0
Installer Url: https://github.com/Leinnan/uec/releases/download/0.2.0/uec-0.2.0-x86_64.msi

**Comment by Dragon1573** [comment]
Hi @Leinnan 👋🏼 ,

> [!TIP]
>
> Modify your [very first comment](https://github.com/microsoft/winget-pkgs/pull/190138#issue-2646213891) of the related pull request as follows. It can help linking that pull reuqest to this issue. While the pull request is successfully merged, this issue will also be closed automatically.

```diff
  ## Checklist for Pull Requests
  
  - [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- - [x] Is there a linked Issue?
+ - [x] Resolve #190319
```

**Comment by Leinnan** [comment]
@Dragon1573 Thx! Updated!
