### ISSUE TITLE
[Update Request]: REAPER Arm64EC builds

### ISSUE THREAD

**Issue by snickler** [microsoft/winget-pkgs#190304]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Cockos.REAPER

### Package Version

7.27

### Please describe the changes you would like to see

An Arm64EC version of REAPER exists, and should be offered to those who are running Windows on Arm.

https://www.reaper.fm/files/7.x/reaper727_win11_arm64ec_beta-install.exe

**Comment by Dragon1573** [comment]
Hi @snickler 👋🏼 ,

> [!TIP]
>
> Modify the [very first comment](https://github.com/microsoft/winget-pkgs/pull/190305) of the pull request as follows. This can associate the pull request to this issue. When the pull request is successfully merged, this issue can also be closed automatically.

```diff
  Checklist for Pull Requests

  * [x]  Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- * [x]  Is there a linked Issue? [[Update Request]: REAPER Arm64EC builds #190304](https://github.com/microsoft/winget-pkgs/issues/190304)
+ * [x]  Is there a linked Issue? Resolve #190304
```
