### ISSUE TITLE
[Package Issue]: Logitech.OptionsPlus

### ISSUE THREAD

**Issue by elibrody** [microsoft/winget-pkgs#190579]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Install/Update command is not wrapped in quotes and errors out if the username has a space in it

### Steps to reproduce

winget update Logitech.OptionsPlus

### Actual behavior

"C:\Users\Eli" is not a valid value for the "/log" argument. Type /help to see the possible values for the arguments.

### Expected behavior

Proceed to update

### Environment

```raw
Windows Package Manager v1.9.25180
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25180.0

Winget Directories
------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagO…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\setti…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/8a1a99a8-69f3-4dd2-bbbb-901a463122ca)
![Image](https://github.com/user-attachments/assets/a1214f2f-6650-4581-b64b-81ba6f9d5fb0)

**Comment by a-mnich** [comment]
As `"C:\Users\Eli"` is a valid path, the installer should theoretically still accept it.   (At least accordingly to the help description of the installer which still documents the log argument)   
Not sure why it fails in this case.
![Image](https://github.com/user-attachments/assets/ff1a2059-39f0-4860-8a3a-38896ff7eadf)

**Comment by elibrody** [comment]
"C:\Users\Eli" is a partial path the full path is "C:\Users\Eli Brody\"
