### ISSUE TITLE
[Update Request]: Microsoft.PowerBI Hash Mismatch

### ISSUE THREAD

**Issue by durrante** [microsoft/winget-pkgs#190744]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Microsoft.PowerBI

### Package Version

2.137.1102

### Please describe the changes you would like to see

The PowerBI desktop installation is failing due to an Error-hash-Mismatch. Error:

![Image](https://github.com/user-attachments/assets/bafa029f-be51-4a28-8fa5-ae2f2615440c)

**Comment by stephengillie** [comment]
The PR for this version was opened a couple of weeks ago, but became closed due to merge conflicts in the headers. 
- https://github.com/microsoft/winget-pkgs/pull/187230/

**Comment by stephengillie** [comment]
I worked with @lukargit to get this updated. 
- https://github.com/microsoft/winget-pkgs/pull/190760

If there's any issue, please @ me and I'll reopen.
