### ISSUE TITLE
[Package Issue]: Electrum.Electrum update to 4.5.8

### ISSUE THREAD

**Issue by UsefulVid** [microsoft/winget-pkgs#190968]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

winget upgrade Electrum --source=winget
```
Es wurde kein anwendbares Upgrade gefunden.
In einer konfigurierten Quelle ist eine neuere Paketversion verfügbar, die jedoch nicht auf Ihr System oder Ihre Anforderungen zutrifft.
```

Copilot says this is the original English message
```
No applicable upgrade found.
A newer version of a package is available from a configured source, but it does not match your system or requirements.
```

Issue appears after:
https://github.com/microsoft/winget-pkgs/pull/190737

### Steps to reproduce

winget upgrade Electrum --source=winget
my source version is 4.5.5

### Actual behavior

Error message and no update

### Expected behavior

Update successful

### Environment

```raw
Windows-Paket-Manager v1.9.25180
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.4317
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.24.25180.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
ProxyCommandLineOptions                   Deaktiviert
DefaultProxy                              Deaktiviert
```

### Screenshots and Logs

No applicable upgrade found.
A newer version of a package is available from a configured source, but it does not match your system or requirements.

**Comment by UsefulVid** [comment]
@damn-good-b0t not sure how I did it last time

**Comment by mdanish-kh** [comment]
[Policy] Installer-Issue
[Policy] Area-External

Electrum installs machine-wide (installs in `Program Files (x86)`), but writes its registry entries to HKEY_CURRENT_USER, making WinGet think that it's a user-scoped install when it's actually not. I don't think WinGet can do much here to reason about this scenario. One thing may be possible to just remove `Scope:` from the manifest entirely and make WinGet treat it as `Scope: Any`. This would break anyone using `--scope machine` or `--scope user` with `winget install Electrum.Electrum`, but I think this should unblock the upgrade scenario. The root problem, however, should be brought up with the publisher to fix

Related to:

- https://github.com/microsoft/winget-pkgs/issues/94840#issuecomment-1465274798
- https://github.com/spesmilo/electrum/issues/8345

**Comment by mdanish-kh** [comment]
As an immediate workaround, try using `winget upgrade Electrum.Electrum --force`

**Comment by mdanish-kh** [comment]
@UsefulVid - PR [#192076](https://github.com/microsoft/winget-pkgs/pull/192076) was merged and published. Let me know if that solved the upgrade issue. I cannot repro anymore at my end

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by UsefulVid** [comment]
Update worked now! Thanks for the fast resolution
