### ISSUE TITLE
[Update Request]: New Version of TeamViewer available.

### ISSUE THREAD

**Issue by hms54** [microsoft/winget-pkgs#191287]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TeamViewer.TeamViewer

### Package Version

v15.59.5

### Please describe the changes you would like to see

At the time of this writing: 
The current version of TeamViewer.TeamViewer available for download is v15.59.5.   

Current package being offered via WinGet is v15.59.4 and it fails due to installer hash mismatch.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> It's currently in progress ❤
>
> - Will be resolved by #191445 
> - Will be resolved by #191296

**Comment by Trenly** [comment]
Close with reason: Above linked PR has merged;
