### ISSUE TITLE
[Update Request]: Nlitesoft.NTLite newer version.  Installer hash does not match.

### ISSUE THREAD

**Issue by hms54** [microsoft/winget-pkgs#191283]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Nlitesoft.NTLite

### Package Version

v2024.11.10166

### Please describe the changes you would like to see

The current NTLite installation package was built for v2024.11.10163.0 and includes the hash for that version.

However, NTlite has been updated on the download site to v2024.11.10166.0, which has a different hash.

Installation or updates fail with error message: Installer hash does not match

Please update package to current hash found at: https://www.ntlite.com/download/

**Comment by DuckDuckStudio** [comment]
This issue appears to have resolved in pull request #191323 .

**Comment by stephengillie** [comment]
> * This issue appears to have resolved in pull request [Automatic update of Nlitesoft.NTLite from 2024.11.10163.0 to 2024.11.10166.0 #191323](https://github.com/microsoft/winget-pkgs/pull/191323) .

If this is incorrect, please @ me and I'll reopen.
