### ISSUE TITLE
pgAdmin install not detected

### ISSUE THREAD

**Issue by MattDahEpic** [microsoft/winget-pkgs#19138]
# Brief description of your issue
pgAdmin install not detected

# Steps to reproduce
```
> winget install pgAdmin
```

# Expected behavior
```
> winget list pgAdmin
Name                  Id                 Version
------------------------------------------------
pgAdmin 4 version 5.3 PostgreSQL.pgAdmin 5.3
```

# Actual behavior
```
> winget list pgAdmin
Name                  Id              Version
---------------------------------------------
pgAdmin 4 version 5.3 pgAdmin 4v5_is1 5.3
```

# Environment

```none
Windows Package Manager v1.0.11692

Windows: Windows.Desktop v10.0.19043.928
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```
![image](https://user-images.githubusercontent.com/7366951/123553185-f5625480-d736-11eb-876d-059aa60d468a.png)
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\pgAdmin 4v5_is1`:
![image](https://user-images.githubusercontent.com/7366951/123553317-aec12a00-d737-11eb-9ab2-8539efe5eca6.png)

**Comment by quhxl** [comment]
Does it work now?

**Comment by MattDahEpic** [comment]
Yep, does now!
