### ISSUE TITLE
Broken anchor link in `doc/README.md`

### ISSUE THREAD

**Issue by Jayman2000** [microsoft/winget-pkgs#191542]
[`doc/README.md` says:](https://github.com/microsoft/winget-pkgs/blob/b7cb2f48ac3309b1ea16897bdbe4f1630412bacf/doc/README.md#submitting-a-manifest)

> 1. Follow the [Contributing](https://github.com/microsoft/winget-pkgs/blob/b7cb2f48ac3309b1ea16897bdbe4f1630412bacf/doc/README.md#contributing) guidelines below.

The “Contributing” link is broken because there’s no `contributing` anchor on the page.

**Comment by DuckDuckStudio** [comment]
This file?

https://github.com/microsoft/winget-pkgs/blob/master/CONTRIBUTING.md
