### ISSUE TITLE
[New Feature]: WinGet 1.9 Schema Documentation

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#191567]
### Description of the new feature/enhancement

Add the new schema elements for 1.9 and add to: https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema

**Comment by Trenly** [comment]
I'm already working on this in a local branch :D

**Comment by denelon** [comment]
I think @ryfu-msft may also be looking at this. Let's see if we can coordinate before one of you is finished :D
