### ISSUE TITLE
OpenMediaLLC's 4kYouTubeToMP3 is missing from the manifest repository.

### ISSUE THREAD

**Issue by vyujitanaka** [microsoft/winget-pkgs#1916]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by ErisuKuraku** [comment]
Hi, @vyujitanaka  I have added a 4KYoutubetoMP3 manifest to the repo and i'm currently waiting for it to be approved by microsoft :)

https://github.com/microsoft/winget-pkgs/pull/2813

**Comment by denelon** [comment]
`winget install OpenMedia.4KYoutubetoMP3`
