### ISSUE TITLE
[Package Request]: GPU Temp

### ISSUE THREAD

**Issue by binarygeek119** [microsoft/winget-pkgs#191699]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.gputemp.com/
Publisher: softsea
Package Name: GPU Temp
Description: GPU Temp is a free GPU temperature monitor that can display GPU core temperature and load, the temperature data will display in the system tray, and will be real-time updated. In addition, you can choose the color for temperature display, also supports start with the Windows system.
Package Version:  1.0
Installer Url:  https://file1.softsea.com/download/bd5cefd4/9be173058eaa384fad93a22d9f07fff9/Diagnostic_Software/gputemp_setup.exe

**Comment by stephengillie** [comment]
> Installer Url: https://file1.softsea.com/download/bd5cefd4/9be173058eaa384fad93a22d9f07fff9/Diagnostic_Software/gputemp_setup.exe

Hi @binarygeek119,

This URL gives me:
![Image](https://github.com/user-attachments/assets/7b15ad71-dee0-4119-bd09-eaab9de3b93a)

Is it available from another location?

**Comment by Trenly** [comment]
I will also note that softsea is an archive site, and not the original publisher, and thus would be blocked by domain validation @stephengillie

**Comment by Trenly** [comment]
Also, SoftSea only provides dynamic URLS which are only valid for a short time, as denoted by the long hex strings in the URL

**Comment by binarygeek119** [comment]
the auther website is no longer around. but this can be closed as LibreHardwareMonitor does what i was traying to do with core temp and gpu temp but in one app and so much better. thanks anyway.
