### ISSUE TITLE
BlueStacksAppPlayer is missing from the manifest repository

### ISSUE THREAD

**Issue by mryujitanaka** [microsoft/winget-pkgs#1919]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by perplexityjeff** [comment]
BlueStacks has an offline download option however both architectures have different versions?

![image](https://user-images.githubusercontent.com/19505844/89153740-c7e04b80-d565-11ea-979b-62740ecbc548.png)

**Comment by denelon** [comment]
I'm not sure if anything is blocking this package. We do need to have support for multiple installers for the same manifest in the event both architectures are available for the same version, but both versions of the package could be added.

**Comment by Trance-Paradox** [comment]
Bluestacks not getting installed after installing

![image](https://user-images.githubusercontent.com/54877610/123205500-a9fe3b00-d4d7-11eb-8f1f-1a43e3b45474.png)

**Comment by Trance-Paradox** [comment]
Anyone else getting this issue?

**Comment by ItzLevvie** [comment]
I seem to be unable to reproduce:
![image](https://user-images.githubusercontent.com/11600822/123473482-87ac1080-d5f0-11eb-9be7-79cdabd1b3e3.png)
![image](https://user-images.githubusercontent.com/11600822/123473521-98f51d00-d5f0-11eb-9cdc-76de87e578f0.png)

**Comment by Trance-Paradox** [comment]
Strange on my pc it download and unpacks everything.
Do u have previously installed bluestacks or this was a fresh installation?

**Comment by ItzLevvie** [comment]
> Strange on my pc it download and unpacks everything.

Which is what happened to me too.

> Do u have previously installed bluestacks or this was a fresh installation?

It's a fresh install of Windows on VMware Workstation; with everything uninstalled such as Microsoft OneDrive, Visual C++ redistributables, etc.

**Comment by naufalfachrian** [comment]
> Bluestacks not getting installed after installing

I got the issue but I've found the workaround. It seems you need to disable HyperV before installing BlueStacks 5. Running the installer will also revert the installation if they found HyperV enabled.

https://support.bluestacks.com/hc/en-us/articles/360055244412-How-to-disable-Hyper-V-on-Windows-for-BlueStacks-5

![image](https://user-images.githubusercontent.com/20085705/124435683-6d67f480-dd9f-11eb-95dd-40c1f0799383.png)

**Comment by Trance-Paradox** [comment]
Stilll not any progress

![image](https://user-images.githubusercontent.com/54877610/124616586-d6c92f80-de93-11eb-88ab-595ac71ca444.png)

**Comment by ItzLevvie** [comment]
> ![image](https://user-images.githubusercontent.com/54877610/124616586-d6c92f80-de93-11eb-88ab-595ac71ca444.png)

I see a spelling error there: bluetacks

**Comment by Trance-Paradox** [comment]
I don't think it was the problem
And yes it is not installed in my system at all i.e i have no way to run bluestacks
![image](https://user-images.githubusercontent.com/54877610/124630816-670d7180-dea0-11eb-80bd-dfeabe820eb0.png)

**Comment by ItzLevvie** [comment]
What happens when you download it from the URL on a browser and run it? There might be something blocking the installation on your end which I'm not seeing on a VM.

**Comment by Trance-Paradox** [comment]
> What happens when you download it from the URL on a browser and run it locally? There might be something blocking the installation on your end which I'm not seeing on a VM.

Well everything works as expected in that case. At last it asks me to enable hyper-v and restart my pc. After restart I can launch bluestacks no problem

**Comment by soredake** [comment]
@FedeIlLeone @ItzLevvie2 @vedantmgoyal2009 @RunTheBot can someone please update installer to new hybrid bluestacks installer?

**Comment by denelon** [comment]
```
PS C:\Users\denelon> winget search bluestacks
Name       Id                   Version      Source
----------------------------------------------------
BlueStacks BlueStack.BlueStacks 5.5.101.1001 winget
```
