### ISSUE TITLE
Cannot install RealVNC.VNCViewer

### ISSUE THREAD

**Issue by NN---** [microsoft/winget-pkgs#19208]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

# Steps to reproduce

```
>winget install  realvnc.vncviewer
Found VNCViewer [RealVNC.VNCViewer]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.21.406-Windows.exe
  ██████████████████████████████  10.0 MB / 10.0 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```

# Expected behavior

VNCViewer is installed

# Actual behavior

Installation failed.

# Environment

```none
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1055
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by OfficialEsco** [comment]
> Installer failed with exit code: 1

Try running Powershell as Administrator

**Comment by NN---** [comment]
Other installations doesn’t require it.

**Comment by OfficialEsco** [comment]
> Other installations doesn’t require it.

Because this is a issue with the Installer, i'm not sure if the installer does not prompt to run as Administrator or some installers require the command line to run as Administrator.
