### ISSUE TITLE
Kaspersky Security Cloud Free is missing from the manifest repository

### ISSUE THREAD

**Issue by vyujitanaka** [microsoft/winget-pkgs#1920]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by perplexityjeff** [comment]
I am not technical enough to make a manifest (yet) but the license file and download are here

https://products.s.kaspersky-labs.com/homeuser/kscloud4.0/21.0.44.1537/english-GB-0.103.0/3239373033367c44454c7c4e554c4c/eula_gdpr_en-gb.txt

https://pdc6.pa2.pdc.kaspersky.com/DownloadManagers/38/ee/38ee34ed-8c71-4d2c-8eda-c1646569e2e3/ks4.021.0.44.1537en_25092.exe

**Comment by perplexityjeff** [comment]
After some research Kaspersky does not provide a direct download link they are always dynamic.

**Comment by denelon** [comment]
Does the URL change every time? Is there another technical limitation here?
