### ISSUE TITLE
[Package Request]: autohotkey v1.1 (deprecated)

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#192054]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.autohotkey.com/download/ahk-install.exe
Publisher: https://www.autohotkey.com/
Package Name: AutoHotkey_1.1.37.02_setup.exe
Description: Powerful. Easy to learn.  The ultimate automation scripting language for Windows.
Package Version: AutoHotkey 1.1.37.02
Installer Url: https://www.autohotkey.com/download/ahk-install.exe

ahk v1 deprecated but I still wish to have it in winget, thank you.

**Comment by SpecterShell** [comment]
```PowerShell
winget install AutoHotkey.AutoHotkey --version 1.1.37.02
```

Append `--force` if v2 has already been installed.

**Comment by Dragon1573** [comment]
Previous versions (`v1.x`) of package identifier `AutoHotkey.AutoHotkey` is already available in the repository. Just use `-v` or `--version` to specify it.

```text
pwsh> Join-String -Separator ', ' -InputObject (komac list-versions AutoHotkey.AutoHotkey).Split("\n")
1.1.32.00, 1.1.33.02, 1.1.33.04, 1.1.33.06, 1.1.33.07,
1.1.33.08, 1.1.33.09, 1.1.33.11, 1.1.34.00, 1.1.34.01,
1.1.34.02, 1.1.34.03, 1.1.34.04, 1.1.35.00, 1.1.36.00,
1.1.36.01, 1.1.36.02, 1.1.37.00, 1.1.37.01, 1.1.37.02,
2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11,
2.0.12, 2.0.15, 2.0.16, 2.0.17, 2.0.18
```

**Comment by khewweifeng** [comment]
I see, thanks @SpecterShell  @Dragon1573
