### ISSUE TITLE
PhraseExpress is missing from the manifest repository

### ISSUE THREAD

**Issue by vyujitanaka** [microsoft/winget-pkgs#1922]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by mehtanisarg369** [comment]
@vyujitanaka I've added the manifest file for PhraseExpress v14.0.186. PhraseExpress should be available via winget after the moderators/administrators successfully merge my PR.

**Comment by denelon** [comment]
`winget install PhraseExpress'
