### ISSUE TITLE
[Package Request]: Meta.FacebookMessenger

### ISSUE THREAD

**Issue by iamsirbrave** [microsoft/winget-pkgs#192393]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.facebook.com/help/messenger-app/852837148154446
Publisher: Meta
Package Name: Facebook Messenger (desktop)
Description: Non-PWA version of Facebook Messenger app on Microsoft Store
Package Version: 215.6.0.24.211
Installer Url: https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.messenger.com%2Fdesktop%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3cChltXeH_vN2jB5Z0DO41rsLDzxOFPuV6TSMUJXgd2lwfWv496PhLhb0_aem_oeaP9Xl2_QBOu2qTygV7cg%23startDownload&h=AT1r4RpsjkJwaWAs26Io1_fJpeJPq5rpOeGv7blh-W3cuwyYsNzl1c7gTrjMle3qN6RtrGQtb4Jzi7XpyL1u1as_SRZhWyclkHjIwpow3XTeLEcy5kGioovypkgdEfilZei6iQ

**Comment by SpecterShell** [comment]
Unfortunately Meta/Facebook does not provide a static link for the installer, even in the [update source](https://www.facebook.com/messenger/desktop/zeratul/update.xml?target=zeratul&platform=win).
