### ISSUE TITLE
[Package Request]: HoYoverse.HoYoPlay

### ISSUE THREAD

**Issue by iamsirbrave** [microsoft/winget-pkgs#192594]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://hoyoplay.hoyoverse.com/
Publisher: HoYoverse
Package Name: HoYoPlay
Description: Access all of HoYoverse's PC-playable games in one place. Say goodbye to tiresome operations - install it once and you're off.
Package Version: v1.2.2.159
Installer Url: https://sg-public-api.hoyoverse.com/event/download_porter/trace/hyp_global/hyphoyoverse/default?url=https%3A%2F%2Fhoyoplay.hoyoverse.com%2F

**Comment by SpecterShell** [comment]
There is no silent installation switches in all miHoYo/HoYoverse products including the launcher AFAIK.
