### ISSUE TITLE
[Package Issue]: odin-lang.odin run fails with missing LLVM-C.DLL dependency

### ISSUE THREAD

**Issue by ccll** [microsoft/winget-pkgs#193086]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

This package can be installed successfully, but when I run odin.exe from the command prompt a message box pops up about missing LLVM-C.dll.

![Image](https://github.com/user-attachments/assets/9600a316-b1a4-4785-9e43-252c02432a79)

![Image](https://github.com/user-attachments/assets/bbb22991-a221-49a6-b455-5867684f4187)

Manually add the Odin installation directory to PATH solves this problem.

![Image](https://github.com/user-attachments/assets/bd0756bd-47c2-44d5-94c2-e9e9d8a6237c)

I fear this might be a more common problem for all packages with DLL dependencies, since winget just creates a symlink under %USERPROFILE%\AppData\Local\Microsoft\WinGet\Links for the main executable in the package, but seems not properly handle DLLs.

### Steps to reproduce

1. `winget install odin-lang.odin` to install the package
2. Open a new command prompt
3. Run the command `odin`

### Actual behavior

A message box popped up complaining about missing `LLVM-C.DLL`.

### Expected behavior

The command should run successfully, output a help message.

### Environment

```raw
(Sorry I failed to make my winget output English).


D:\>winget --info
Windows 程序包管理器 v1.9.25200
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22631.4460
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Packages
可移植包根目录         C:\Program Files\WinGet\Packages
可移植包根目录 (x86)   C:\Program Files (x86)\WinGet\Packages
安装程序下载           %USERPROFILE%\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已禁用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已禁用
ProxyCommandLineOptions                   已禁用
DefaultProxy                              已禁用
```

**Comment by Trenly** [comment]
The manifest will need to be updated to 1.9 once the pipelines support it

**Comment by Trenly** [comment]
[Policy] Unblocked; Will require `ManifestVersion: 1.9.0` with `ArchiveBinariesDependOnPath: true`
