### ISSUE TITLE
[Update Request]: Don't force update stardock fences 4 to fences 5

### ISSUE THREAD

**Issue by SckyzO** [microsoft/winget-pkgs#193117]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Stardock.Fences

### Package Version

5.8.4.7

### Please describe the changes you would like to see

Hello,

An issue has been opened to add Fences 5 to the winget package. It's not a problem (see here: https://github.com/microsoft/winget-pkgs/issues/191698).

However, Fences 4 and Fences 5 do not share the same license, and you need to purchase a new license key to use Fences 5. 👎

Is it possible to lock Fences 4 to prevent it from being updated to Fences 5? Fences 4 is still eligible for updates.

(Of course, I downgraded my Fences version and pinned it, but this is just a workaround.)

Regards,

**Comment by Dragon1573** [comment]
The issue #191698 is resolved by me via pull request #191710 ❤

I don't use this package, so I think v5 would be the successor of v4 and everyone is recommended to upgrade to v5 series.

If they should be regarded as 2 different packages (such as Python, each minor version of v3 series should be distinguished with different package identifier), I can help move them into `Stardock.Fences.4` and `Stardock.Fences.5`.
