### ISSUE TITLE
[Package Issue]: WiresharkFoundation.Wireshark 4.4.2 wrong arch (arm64) for x64

### ISSUE THREAD

**Issue by reini-1** [microsoft/winget-pkgs#193146]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installer yaml contains the wrong installation url for  x64. The arm64 url is configured and not the x64 url, see manifests/w/WiresharkFoundation/Wireshark/4.4.2/WiresharkFoundation.Wireshark.installer.yaml

Package details on a Win 11 x64 machine:

Paket-ID:  WiresharkFoundation.Wireshark

Manifest:  https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WiresharkFoundation/Wireshark

Version 4.4.2

Installations-Typ:  nullsoft

Installations-URL:  https://2.na.dl.wireshark.org/win64/Wireshark-4.4.2-arm64.exe

Installations-SHA256:  51965e0739799fe927a56befdbad5700e290130a2cb21afb87a9796a6b5c5c64

Installationsdatei herunterladen  (65,55104064941406 MB)

### Steps to reproduce

```shell
$ winget install --id "WiresharkFoundation.Wireshark" --exact --source winget --accept-source-agreements --accept-package-agreements
Gefunden Wireshark [WiresharkFoundation.Wireshark] Version 4.4.2
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://2.na.dl.wireshark.org/win64/Wireshark-4.4.2-arm64.exe
  ██████████████████████████████  65.5 MB / 65.5 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Installation fehlgeschlagen mit Exitcode: 2
```

### Actual behavior

Downloads wrong file and fails to install.

### Expected behavior

Download proper x64 file (https://2.na.dl.wireshark.org/win64/Wireshark-4.4.2-x64.exe) and installs it.

### Environment

```raw
$ winget --info
Windows-Paket-Manager v1.9.25200
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.4460
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.24.25200.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
ProxyCommandLineOptions                   Deaktiviert
DefaultProxy                              Deaktiviert
```

### Screenshots and Logs

see reproduce

**Comment by timbretimber** [comment]
These lines seems relevant from my logs
```
[CLI ] Starting installer selection.
[CLI ] Installer [X64,nullsoft,Machine,] is current best choice
[CLI ] Installer [Arm64,nullsoft,Machine,] not applicable: Machine is not compatible with Arm64
[CLI ] Installer [X64,wix,Machine,en-US] not applicable: Installed package type 'exe' is not compatible with installer type wix, or with accepted type(s) unknown
[CLI ] Completed installer selection.
[CLI ] Selected installer Architecture: 2
[CLI ] Selected installer URL: https://2.na.dl.wireshark.org/win64/Wireshark-4.4.2-arm64.exe
```
It seems since the current install is 'exe' it won't allow the msi install to proceed, which seems reasonable though maybe it should prompt to uninstall the existing install and replace it. Selecting an incompatible architecture as a result however is quite strange. On another note the .msi installer doesn't include npcap or usbpcap and requires their separate installation. 

![Image](https://github.com/user-attachments/assets/d9af614a-b5a6-44d2-9d52-d18fc4a7bcc6)

While usbpcap is up to date, npcap on winget is very old
```
winget.exe show npcap
Found Npcap [Insecure.Npcap]
Version: 0.86
Publisher: Insecure
Publisher Url: https://insecure.org/fyodor/
Description: Nmap Project's Windows packet capture and transmission library
Homepage: https://nmap.org/npcap/
License: Proprietary
Privacy Url: https://insecure.org/privacy.html
Copyright: Copyright 2016 Insecure.Com LLC ("The Nmap Project")
Installer:
  Installer Type: nullsoft
  Installer Url: https://nmap.org/npcap/dist/npcap-0.86.exe
  Installer SHA256: ab677b9037dc377303e6d68a9b8a8195c8e976efd550a6bb6ce91eed551c5cbe
  Offline Distribution Supported: true
```
and it seems the authors don't want it on winget
https://github.com/nmap/npcap/issues/588
https://github.com/nmap/npcap/issues/732

I think in light of this the installer should probably be kept as the .exe installer. Otherwise, one needs to install npcap manually if they want an up to date version of it which doesn't seem in line with what you'd expect from an automated package installer.
