### ISSUE TITLE
Installation validation failed - possible pipeline issue

### ISSUE THREAD

**Issue by marcauberer** [microsoft/winget-pkgs#19328]
Hi,
since a few weeks, the installation validation fails for `ChilliBits.CCom` despite nothing changed for building the msi installer.

Following installation validations succeeded:
- #14645 
- #17839

For following prs the validations failed:
- #19312 
- #19315 
- #19317 

I noticed, that other submissions are also affected by this. So it might be a problem with the validation pipeline?!

Thanks in advance,
Marc

**Comment by denelon** [comment]
@marcauberer it looks like all 5 PRs have been merged. Someone from the team looked at them and approved them. It's likely we're aware of the issue(s) for validation. I'll double check with the team.

**Comment by marcauberer** [comment]
@denelon any updates regarding this?

**Comment by denelon** [comment]
@marcauberer it's been quite a while since I updated this bug. I believe we've identified the known issues for why pipelines fail during dynamic validation. Do you have any other recent examples?

**Comment by marcauberer** [comment]
@denelon seems like the bug is fixed now. Have just created two prs, which are both passing:

#30104
#30072
