### ISSUE TITLE
[Package Issue]: ppy.osu

### ISSUE THREAD

**Issue by MoiraPrime** [microsoft/winget-pkgs#193291]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

ppy.osu version 2024.1115.3 is misconfigured. Instead of downloading and running the installer it installs the installer to path as the command "install"

### Steps to reproduce

1. type winget install ppy.osu
2. Let it run
3. ppy.osu's installer is installed to path at the end of setup. restarting your shell and typing "install" then runs the installer actualy

### Actual behavior

installer executable is installed to path

### Expected behavior

installer executable is downloaded and executed.

### Environment

```raw
PS C:\Users\MoiraPrime> winget --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2314
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\Libraries\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/48fd0586-8703-44ac-8e35-6966111d8675)

**Comment by Dragon1573** [comment]
Currently, there're 9 available versions of package identifier `ppy.osu`.

```text
23:18:04 D:\...\winget-pkgs  [master ≡] 0ms pwsh> komac list-versions ppy.osu
2024.412.1
2024.521.2
2024.625.0
2024.625.2
2024.906.2
2024.1009.1
2024.1115.1
2024.1115.2
2024.1115.3
```

Except version `2024.412.1`, all newer versions are configured `InstallerType: portable` instead of `InstallerType: exe`.

-----

It might be caused by above mis-configuration.
