### ISSUE TITLE
MPC-HC version is very old, there is a new one

### ISSUE THREAD

**Issue by aslze** [microsoft/winget-pkgs#1936]
# Description of the new feature/enhancement

MPC-HC (Media Player Classic-Home Cinema) was recently added (@aliheikal) using its *last* version from its "official" source, **1.7.13**. That version dates from 2017 and the project was abandoned.

However, some developers retook the project and continued maintaining it, fixing bugs and adding some features. And they did it greatly, keeping the spirit and quality of the original.

The current version is **1.9.4** here, which I consider the new home of MPC-HC

https://github.com/clsid2/mpc-hc

It can now play AOMedia AV1 videos and YouTube videos. It has better seeking, better video decoding, better UI, and lots of fixes and improvements.

# Proposed technical implementation details (optional)

I would link to the installer in the Releases page:

https://github.com/clsid2/mpc-hc/releases/tag/1.9.4

**Comment by aliheikal** [comment]
The one you are linking to seems to point to a fork/unofficial release. I believe winget is up-to-date with the latest version posted on the official site/repo.

I don't know if creating a PR under MPC-HC's name pointing to a fork/unofficial release would be the right thing, given that the publisher is no longer MPC-HC. I think if we do that we would be miscrediting the current maintainer of the fork/unofficial release as well as MPC-HC.

**Comment by aslze** [comment]
The "official" was abandoned years ago and the website even warns about that and says "please use something else".

The fork I mention took the original's last version (1.7.13) and continued with 1.7.14, 1.7.15, ..., 1.8.1, ..., up to yesterday's 1.9.5. It's keeps the essence of the old version but improves it with better performance, features and bug fixes, keeping the project alive. To me this is the real MPC-HC.

Well, ideally, I would like the original and fork authors to agree to merge both developments, or just pass the lead to the new repo. I don't know how to put them in touch :-)

**Comment by MarNicGit** [comment]
I guess you can add the fork as `Clsid2/MPC-HC`?
