### ISSUE TITLE
Some packages from China can't pass azure piplines validation

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#1937]
#1869
On my computer, this package can be installed successfully (from an elevated cmd)
```
C:\Users\lin\Desktop>winget install -m 1.yaml
Found deepvocal Huanxiaoyi [Boxstar.deepvocal-Huanxiaoyi]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading http://sharpkey-files.oss-cn-beijing.aliyuncs.com/sharpkey_voice/Setup_HuanXiaoYi_v1.2.exe
  ██████████████████████████████  1.50 GB / 1.50 GB
Successfully verified installer hash
Installing ...
Successfully installed!
```
However, it [failed azure piplines validation](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=87891&view=logs&jobId=c8020aa5-4aab-5881-691f-21986e02afd0&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d)
```
6/15/2020 4:05:09 AM
Status: Completed
Result: Failed
Error occurred during installer copy from http://sharpkey-files.oss-cn-beijing.aliyuncs.com/sharpkey_voice/Setup_HuanXiaoYi_v1.2.exe.
```
#1264 (Tencent QQ) #1256 (Bilibili livehime) #916 (Xmind) failed validation, too.
It seems that packages from aliyuncs.com never pass validation

winget v0.1.41331
windows 10 professional Build 19645.mn_release.200605-1502

**Comment by qiancy98** [comment]
It seems a copy of issue #91

**Comment by megamorf** [comment]
This is not a problem with the installer itself but rather the "Great Firewall of China". From my professional work I know how bad out-/inbound China traffic is affected by throttling and package loss. You can see in the Azure pipeline that the installer could not be downloaded in time causing a timeout error which lead to a failed job.

There's nothing the winget team can do about this at this time. The common solution to this problem is to host a mirror in China which offers acceptable up- and download speeds. In this case the opposite setup would be required where the Chinese packages are hosted on a mirror outside of China or you'd need a dedicated Azure pipeline running in Microsoft Azure China.

**Comment by qiancy98** [comment]
Meet the same on #1933.

**Comment by megamorf** [comment]
@qiancy98 I don't see how this issue relates to the problems with your PR. Your issue clearly is with a Range GET request and therefore related to #91:

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=89454&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41

```
6/20/2020 11:43:15 PM
Status: Completed
Result: Failed
Error occurred during installer copy from https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/tikzedt/TikzEdtBeta0_2_3.msi.
 Range GET requests are not supported by the copy source.
``` 

In comparison this is the error message related to this issue:

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=87891&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41

```
6/15/2020 4:05:09 AM
Status: Completed
Result: Failed
Error occurred during installer copy from http://sharpkey-files.oss-cn-beijing.aliyuncs.com/sharpkey_voice/Setup_HuanXiaoYi_v1.2.exe.
 Operation could not be completed within the specified time.
```

**Comment by qiancy98** [comment]
Sorry.

**Comment by denelon** [comment]
We've changed how we're pulling packages into CI for validation. This has fixed the issues with "Range GET requests" and some other interesting redirect scenarios. I've triggered builds again to see if they are all resolved.

**Comment by denelon** [comment]
They have passed automated validation.
