### ISSUE TITLE
[Package Issue]: UweSieber.UsbTreeView wrong InstallerUrl

### ISSUE THREAD

**Issue by eseub** [microsoft/winget-pkgs#193749]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The InstallerUrl for the UweSieber.UsbTreeView package always points to the latest release. However, this behavior is not desired because if the version in the winget repository has not been updated, attempting to install it will result in the error message: "Installer hash does not match."

Currently, the latest version of the package in the winget repository is 4.4.2, while the actual latest release is 4.4.3.

To resolve this issue, you can download the specific version of the package directly from the following URL format:
https://www.uwe-sieber.de/files/UsbTreeViewNNN_ARCH.zip

For example, to download version 4.4.2 for the x64 platform, use the following URL instead of the current one:
https://www.uwe-sieber.de/files/UsbTreeView442_x64.zip

Something like this:
```patch
--- UweSieber.UsbTreeView.installer.yaml	2024-11-25 21:24:23.381081238 +0100
+++ UweSieber.UsbTreeView.installer.yaml	2024-11-25 21:24:13.191084794 +0100
@@ -10,7 +10,7 @@
 UpgradeBehavior: install
 Installers:
 - Architecture: x64
-  InstallerUrl: https://www.uwe-sieber.de/files/UsbTreeView_x64.zip
+  InstallerUrl: https://www.uwe-sieber.de/files/UsbTreeView442_x64.zip
   InstallerSha256: 092EA02051DCE0274EEBCA943E630EEF6E0B79C3C1087621580315DA4227175C
 ManifestType: installer
 ManifestVersion: 1.6.0
```

### Steps to reproduce

Trying to install the current version:
```bat
winget install --source winget --id UweSieber.UsbTreeView
> Installer hash does not match.
```

Trying to install the latest version of the package, not yet in the winget repository
```bat
winget install --source winget --version 4.4.3 --id UweSieber.UsbTreeView
> No version found matching: 4.4.3
```

Trying to manually install the latest version available in the winget repository
```bat
winget install --source winget --version 4.4.2 --id UweSieber.UsbTreeView
> Installer hash does not match.
```

### Actual behavior

Unable to install the UweSieber.UsbTreeView package because the current InstallerUrl always points to the latest release, which does not match the version available in the winget repository.

### Expected behavior

Ensure the ability to install the UweSieber.UsbTreeView package using Winget by downloading the installer that matches the repository version.

### Environment

```raw
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2314
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0
```

**Comment by UweSieber** [comment]
Under the UsbTreeViewXXX_x64.zip name I keep previous version for download only.

Would it help to have the latest release available with its version in the file name too?

**Comment by UweSieber** [comment]
Done:
https://www.uwe-sieber.de/files/UsbTreeView443_x64.zip

And I'll do it for further releases.


Just in case: Some other popular tools

https://www.uwe-sieber.de/files/UsbDriveInfo563_x64.zip
https://www.uwe-sieber.de/files/ComPortInfo121_x64.zip
https://www.uwe-sieber.de/files/DeviceCleanup131_x64.zip

All x64 only.

**Comment by eseub** [comment]
> Done: https://www.uwe-sieber.de/files/UsbTreeView443_x64.zip
> 
> And I'll do it for further releases.
> 
> Just in case: Some other popular tools
> 
> https://www.uwe-sieber.de/files/UsbDriveInfo563_x64.zip https://www.uwe-sieber.de/files/ComPortInfo121_x64.zip https://www.uwe-sieber.de/files/DeviceCleanup131_x64.zip
> 
> All x64 only.

Thanks 😃
