### ISSUE TITLE
[Package Request]: TheBrowserCompany.Arc

### ISSUE THREAD

**Issue by just-ero** [microsoft/winget-pkgs#193877]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://arc.net
Publisher: The Browser Company
Package Name: TheBrowserCompany.Arc
Description: Arc is a Chromium-based web browser that allows users to cosmetically customize their browsing experience.
Package Version: 1.29.0
Installer Url: https://releases.arc.net/windows/ArcInstaller.exe

**Comment by SpecterShell** [comment]
The package is already there, with the same identifier `TheBrowserCompany.Arc`.

**Comment by SpecterShell** [comment]
Zen Browser was designed to be an Arc alternative AFAIK.

Anyway that tag has been there since the first PR of this package: #168940
