### ISSUE TITLE
[Package Request]: I want to help add the new nvidia app

### ISSUE THREAD

**Issue by laurNzini** [microsoft/winget-pkgs#193889]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.nvidia.com/en-us/software/nvidia-app/
Publisher: NVIDIA
Package Name: NVIDIA app
Description: GPU Companion
Package Version: 11.0.1.163
Installer Url: https://us.download.nvidia.com/nvapp/client/11.0.1.163/NVIDIA_app_v11.0.1.163.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> - Duplicate of #140696

> [!CAUTION]
>
> This is a <https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue>, because of <https://github.com/microsoft/winget-pkgs/labels/Hardware>
>
> - Will be resolved by #190775

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #140696;

**Comment by Trenly** [comment]
Duplicate of #140696

**Comment by DandelionSprout** [comment]
I've been able to add it to the 3rd-party Winget source [winget-extras](https://github.com/pl4nty/winget-extras) by [pl4nty](https://github.com/pl4nty) now, at least:

`winget source add --name winget-extras --type Microsoft.PreIndexed.Package --arg https://winget.tplant.com.au/cache; winget install Nvidia.NVIDIAApp`
