### ISSUE TITLE
Pls, add support of drivers

### ISSUE THREAD

**Issue by SlimRG** [microsoft/winget-pkgs#19401]
Pls, add Nvidia, AMD and Intel driver installation support throug your app.
It's true, that you have GeForce Experience in your repoositories, but without drivers it doesn't work.
It will be great, if I can choose version of driver to install or have autoupdate for drivers.
Thanks!

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. To keep things tidy, this issue is being tracked over on the CLI repository
* https://github.com/microsoft/winget-cli/issues/684

###### Close with reason: Stale;
