### ISSUE TITLE
Can you rename Microsoft 365 Apps for enterpri... to Microsoft Office 365?

### ISSUE THREAD

**Issue by SlimRG** [microsoft/winget-pkgs#19404]
When I use 
`winget search`
I found 
`Microsoft 365 Apps for enterpri Microsoft.Office                   16.0.14026.20308                 winget`
But it gives no information - what is it.
Can you rename to smth like Microsoft Office 365, please.
Thanks!

**Comment by denelon** [comment]
The `PackageName` is "Microsoft 365 Apps for enterprise".
The `PackageIdentifier` is "Microsoft.Office".
If you run `winget show Microsoft.Office`, the "ShortDescription" is "Microsoft 365 Apps for enterprise is the most productive and most secure Office experience for enterprises, allowing your teams to work together seamlessly from anywhere, anytime."

**Comment by denelon** [comment]
"Microsoft 365 Apps for enterprise" is the official product name provided by the publisher.
