### ISSUE TITLE
Brave browser not updating

### ISSUE THREAD

**Issue by KanishTech** [microsoft/winget-pkgs#19402]
Brave browser is not updating and return a message ,Installer failed with exit code: 2147748098 
![Screenshot 2021-06-30 210319](https://user-images.githubusercontent.com/74523078/123989559-a4788780-d9e6-11eb-9f6c-c3dbf0a0f66b.png)

**Comment by ImJoakim** [comment]
Hey there @KanishTech, a new version of Brave Browser was added yesterday (#19432). Can you give it a go now?

**Comment by cr13-cr** [comment]
**_Onnum panna mudiyadhu......._**

**Comment by vedantmgoyal2009** [comment]
@KanishTech Is the issue fixed now?

**Comment by asheroto** [comment]
Having this issue now as well, April 2, 2022

**Comment by asheroto** [comment]
The issue, for me, was because I had "keep Brave running in the background even when closed".

`taskkill /f /im brave*`

Then running setup again worked.

**Comment by cjwijtmans** [comment]
same issue as of now.
