### ISSUE TITLE
[Package Issue]: RealVNC.VNCViewer

### ISSUE THREAD

**Issue by jason-nyc** [microsoft/winget-pkgs#194244]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget list shows that the product is installed.  But there's no icon, program files, or other evidence that it's installed.
By manually downloading at installing from the wix (zip) source, it works fine and appears in C:\Program Files\RealVNC\VNC Viewer

### Steps to reproduce

Winget install --id RealVNC.VNCViewer --exact --scope machine

Winget list | findstr VNC
RealVNC Viewer                         RealVNC.VNCViewer                       7.12.0.14                         winget

### Actual behavior

Install happens as per winget.  But there's no icon, program files, or other evidence that it's installed.

### Expected behavior

A start menu icon or program files folder should be created.

### Environment

```raw
inget --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.3260
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by mdanish-kh** [comment]
Did this happen on an upgrade or a fresh install? I just made a fresh install on Sandbox using WinGet and could see the folder in Program Files and in Start menu

![Image](https://github.com/user-attachments/assets/a22450ee-0694-46bd-b105-8a51d98f4b80)

**Comment by jason-nyc** [comment]
I'm sure I'm doing something dumb but I can't figure it out - this is on another machine.

Open command prompt as admin and do this:

```
Winget install --id RealVNC.VNCViewer --exact --scope machine
dir "%ProgramFiles%\R*"
dir "%ProgramFiles(x86)%\R*"
```

![Image](https://github.com/user-attachments/assets/09a308df-5768-41a9-a2eb-4cd4a87fb3a9)
