### ISSUE TITLE
Is it safe?

### ISSUE THREAD

**Issue by FiftyFour7250** [microsoft/winget-pkgs#19442]
Hey, I'm new to package managers (first day) and it's not quite clear to me, is it safe? I mean, is there any guarantee that some bad person will not upload a new version of the software but with a built-in virus that even virustotal does not recognize.

What is the difference with Chocolatey in terms of security?

**Comment by OfficialEsco** [comment]
Its as safe as downloading the program from the website it self, aka not 100%.
Not sure what Chocolatey does for new releases but i doubt they do much more then running VirusTotal, i know they mark them as Unsafe at times (Bloatware etc), but you can still download that version IIRC.

**Comment by ImJoakim** [comment]
> I mean, is there any guarantee that some bad person will not upload a new version of the software but with a built-in virus that even virustotal does not recognize.

Also, if you're talking about adding a new version of an already trusted software (ex. Google Chrome) - all PRs are overseen and approved by Administrators or Community Moderators. More info on moderation can be found via #15674.
