### ISSUE TITLE
[Package Request]: vivetool

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#194782]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/thebookisclosed/ViVe/releases
Publisher: thebookisclosed
Package Name: vivetool
Description:  C# library and console app for using new feature control APIs available in Windows 10 version 2004 and newer 
Package Version: 0.3.3
Installer Url: https://github.com/thebookisclosed/ViVe/releases/download/v0.3.3/ViVeTool-v0.3.3.zip

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/92418

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> Close with reason: <https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue>
>
> - Any manifests of the package is prohibited to be submitted to the repository, due to https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1406903479
> - The package is currently not supported by `winget.exe`, due to https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1407203493

**Comment by sitiom** [comment]
> * Any manifests of the package is prohibited to be submitted to the repository, due to [[Zip][Portable] New package: thebookisclosed.ViVeTool version 0.3.2 #92418 (comment)](https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1406903479)

The author has also expressed publishing to Winget at a later point: https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1407100088.

> * The package is currently not supported by `winget.exe`, due to [[Zip][Portable] New package: thebookisclosed.ViVeTool version 0.3.2 #92418 (comment)](https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1407203493)

Now that has been resolved, I have created a new PR (with the [heads up from the author](https://github.com/thebookisclosed/ViVe/issues/43#issuecomment-2517901975)):

- https://github.com/microsoft/winget-pkgs/pull/196214

**Comment by sitiom** [comment]
The later PR got merged first 🫤 (anyway thanks @soredake 🙂)
