### ISSUE TITLE
Searches don't seem to get all results

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-pkgs#19470]
# Brief description of your issue
I search for java using this and it showed adopt open versions of java but not 8. I can manual look through the repository and see its there. when searching using the package identifier it shows up.

# Steps to reproduce
1) type winget search java
2) type winget search "AdoptOpenJDK.OpenJDK.8"

# Expected behaviour
All versions should show up

# Actual behaviour
versions are missing until using the direct identifier

# Screenshot
![image](https://user-images.githubusercontent.com/26977075/124064867-913cda80-da2d-11eb-9725-e1e0addddde7.png)

**Comment by denelon** [comment]
```
PS C:\Users\denelon> winget search AdoptOpenJDK --tag java
Name                             Id                      Version   Source
--------------------------------------------------------------------------
AdoptOpenJDK JDK with Hotspot 16 AdoptOpenJDK.OpenJDK.16 16.0.1.9  winget
AdoptOpenJDK JDK with Hotspot 15 AdoptOpenJDK.OpenJDK.15 15.0.2.7  winget
AdoptOpenJDK JDK with Hotspot 14 AdoptOpenJDK.OpenJDK.14 14.0.2.12 winget
```
