### ISSUE TITLE
[Update Request]: for Blink Eye v2.3.0

### ISSUE THREAD

**Issue by nomandhoni-cs** [microsoft/winget-pkgs#195349]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

NomanDhoni.BlinkEye

### Package Version

2.3.0

### Please describe the changes you would like to see

There is a new release of v2.3.0 of exe and msi both
https://github.com/nomandhoni-cs/blink-eye/releases

This is the EXE URL: https://github.com/nomandhoni-cs/blink-eye/releases/download/v2.3.0/Blink.Eye_2.3.0_x64-setup.exe
And This is the Signature: https://github.com/nomandhoni-cs/blink-eye/releases/download/v2.3.0/Blink.Eye_2.3.0_x64-setup.exe.sig

**Comment by nomandhoni-cs** [comment]
@fluentmoheshwar Can you please have a look at this issue, And thanks a lot for adding the app to winget

**Comment by fluentmoheshwar** [comment]
> @fluentmoheshwar Can you please have a look at this issue, And thanks a lot for adding the app to winget 

I currently don't have a computer to work with the issue. I think other maintainer will be able to solve the problem if not I will take a look at this
