### ISSUE TITLE
[Package Request]: Visual Studio Code Insiders system-wide installer

### ISSUE THREAD

**Issue by Mujtaba0150** [microsoft/winget-pkgs#195494]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url:  https://code.visualstudio.com/insiders/
Publisher: Microsoft
Package Name: Visual Studio Code Insiders
Description: Only the user installer of Visual Studio Code Insiders is available to install via winget, not the system-wide installer.
Package Version: 1.96.0
Installer Url: https://vscode.download.prss.microsoft.com/dbazure/download/insider/275faf6f08b7aa50843f3c18406b4d5969784e52/VSCodeSetup-x64-1.96.0-insider.exe

**Comment by SpecterShell** [comment]
```PowerShell
winget install Microsoft.VisualStudioCode.Insiders --scope machine
```

**Comment by Trenly** [comment]
Close with reason: Already available;
