### ISSUE TITLE
[Update Request]: Hydrus Network

### ISSUE THREAD

**Issue by clin1234** [microsoft/winget-pkgs#195408]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

HydrusNetwork.HydrusNetwork

### Package Version

600a

### Please describe the changes you would like to see

600a was released to fix a download typo
https://github.com/hydrusnetwork/hydrus/releases/tag/v600a

**Comment by DuckDuckStudio** [comment]
This package appears to already exist.
- https://github.com/microsoft/winget-pkgs/pull/194967

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - See #194967 
>
> ![Image](https://github.com/user-attachments/assets/b2df1c52-eabd-472e-8d5e-5edb2836ccc9)

**Comment by Trenly** [comment]
@dragon1573 - Even though the version exists, it probably needs to be moved to be `v600.a` since with the way version comparisons work `v600` is newer than `v600a`

**Comment by Dragon1573** [comment]
> It probably needs to be moved to be `v600.a` since with the way version comparisons work `v600` is newer than `v600a`.

Okay, I'll perform this migration. ❤

**Comment by DuckDuckStudio** [comment]
I've just realized something: the version v600 of this package became unavailable after the release of v600a...

- https://github.com/DuckDuckStudio/winget-tools/actions/runs/12974192612/job/36183770761#step:6:197
