### ISSUE TITLE
[Package Request]: Visual Studio Code system-wide installer

### ISSUE THREAD

**Issue by Mujtaba0150** [microsoft/winget-pkgs#195496]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url:  https://code.visualstudio.com/Download
Publisher: Microsoft
Package Name: Visual Studio Code
Description: The system-wide installer for Visual Studio Code isn't available to install via winget.
Package Version: 1.95.3
Installer Url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/VSCodeSetup-x64-1.95.3.exe

**Comment by SpecterShell** [comment]
The system-wide installer is available and can be installed with:

```PowerShell
winget install Microsoft.VisualStudioCode --scope machine
```

**Comment by Trenly** [comment]
Close with reason: already available;
