### ISSUE TITLE
[Update Request]: Q-Dir 11.91

### ISSUE THREAD

**Issue by bitspyer** [microsoft/winget-pkgs#195525]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SoftwareOK.Q-Dir

### Package Version

11.91

### Please describe the changes you would like to see

New Release on WebPage (11.91) available.

Website: https://www.softwareok.com/?Download=Q-Dir

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/195499

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - See #195499

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Resolved**.
> 
> * See [New version: SoftwareOK.Q-Dir version 11.91 #195499](https://github.com/microsoft/winget-pkgs/pull/195499)
