### ISSUE TITLE
[Package Request]: GWSMO

### ISSUE THREAD

**Issue by mfaisal81** [microsoft/winget-pkgs#195625]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://tools.google.com/dlpage/gssmo/#
Publisher:Google
Package Name:Google Workspace Sync for Microsoft Outlook
Description:Google Workspace Sync for Microsoft Outlook
Package Version:132.0.6833.0
Installer Url:https://dl.google.com/dl/google-apps-sync/x64/enterprise_gsync.msi

**Comment by Dragon1573** [comment]
Install failed in _Windows Sandbox_ instance.

![Image](https://github.com/user-attachments/assets/49f937c5-f800-4541-b306-66b321963773)

Also failed to install its dependencies (here choose `Microsoft.Office`).

![Image](https://github.com/user-attachments/assets/e639d838-2cfc-4ded-944e-47e12d9a5d22)

**Comment by mfaisal81** [comment]
You can try to use the below installer

https://tools.google.com/dlpage/gssmo/#

**Comment by Dragon1573** [comment]
> You can try to use the below installer
> 
> https://tools.google.com/dlpage/gssmo/#

`winget.exe` can only perform `GET` request to the server, just like `curl.exe` or `wget.exe`. It seems the download process is realized by using `POST` or other verbs.

The URL you provided seems navigate me to a special [thank you](https://tools.google.com/dlpage/gssmo/thankyou.html) page. And my multi-thread downloader automatically pops up asking for file download approval. Should I use it instead?

**Comment by mfaisal81** [comment]
Oh, I didn't know that. I'm all new to this but lets try it and see if it works.

**Comment by Dragon1573** [comment]
Both `*.msi` and `*.exe` of `Google.GWSMO` requires **Microsoft Outlook (classic)** desktop application pre-installed. But I can't install it inside _Windows Sandbox_ instance.

- See https://github.com/microsoft/winget-pkgs/issues/195625#issuecomment-2511442901

**Comment by mfaisal81** [comment]
Thats correct, office is pre requisite for the gwsmo app. Isn't there a workaround ? this is a genuine app from google and it would be great if we can get it on winget. Thanks.

**Comment by Dragon1573** [comment]
Manually verified again and failed.

![Image](https://github.com/user-attachments/assets/00a900a9-38e3-4210-a988-f27d1eebb175)

**Comment by Dragon1573** [comment]
> Isn't there a workaround ?

I think there's no walkaround.

In order to pass the validation pipeline, the package should be installed successfully without user interaction.

It's acceptable that a package requires external dependencies to launch and there're plenty of available dependencies (see package `FabricMC.FabricInstaller` #194923 as an example). Install of the package does not require them pre-installed. It just unable to launch **AFTER installation**.

**Comment by Dragon1573** [comment]
> I'm all new to this but lets try it and see if it works.

Emm ... The URL seems invalid if `winget.exe` try to download the installer file through it.

![Image](https://github.com/user-attachments/assets/6f52a2c5-e7fa-4004-beca-40366e1639f8)

Maybe it's only valid by visiting though a modern browser directly?

![Image](https://github.com/user-attachments/assets/0c9b6d89-c665-4bb7-b157-be07e010ef97)

**Comment by mfaisal81** [comment]
Thanks for trying, then we can ignore it in this case. Appreciate it
