### ISSUE TITLE
[Package Issue]: parallel Parallels PackageIdentifiers

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-pkgs#195776]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

These packages need to be merged:
- `Parallels.Parallels` was added in a PR that I can't locate, and updated in https://github.com/microsoft/winget-pkgs/pull/21009
- `ParallelsInternationalGmbH.ParallelsClient` was added in https://github.com/microsoft/winget-pkgs/pull/18009

### Steps to reproduce

https://github.com/microsoft/winget-pkgs/pull/195566#issuecomment-2510464137

### Actual behavior

> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: b9cf278f66954e869f0323cd027171ed9557db0aa1c86f3f4118e86a21bd281b`
>   
>   * manifests\p\ParallelsInternationalGmbH\ParallelsClient\20.0.25389
> * `InstallerSha256: a69951770daaae4460ce93ac2a5c6974af9dc1a1e5e261a5887500bd0defc16b`
>   
>   * manifests\p\ParallelsInternationalGmbH\ParallelsClient\20.0.25389

### Expected behavior

(no response)

### Environment

```raw
https://github.com/microsoft/winget-pkgs/pull/195566
```

**Comment by Dragon1573** [comment]
Manually verified ❤ 

```text
20:01:07 D:\...\winget-pkgs  [master ≡] 2ms pwsh> winget search -s winget -e Parallels.Parallels
名称             ID                  版本
-----------------------------------------------
Parallels Client Parallels.Parallels 19.4.25171
20:01:10 D:\...\winget-pkgs  [master ≡] 208ms pwsh> winget search -s winget -e ParallelsInternationalGmbH.ParallelsClient
名称             ID                                         版本
----------------------------------------------------------------------
Parallels Client ParallelsInternationalGmbH.ParallelsClient 20.0.25389
20:01:13 D:\...\winget-pkgs  [master ≡] 203ms pwsh> komac list-versions Parallels.Parallels | Join-String -Separator "`t"     
18.3.22916      19.4.25062      19.4.25171
20:02:26 D:\...\winget-pkgs  [master ≡] 1.9s pwsh> komac list-versions ParallelsInternationalGmbH.ParallelsClient | Join-String -Separator "`t"
19.4.25221      20.0.25389
```
