### ISSUE TITLE
[Update Request]: Rufus.Rufus

### ISSUE THREAD

**Issue by bomkz** [microsoft/winget-pkgs#195771]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Rufus.Rufus

### Package Version

4.6

### Please describe the changes you would like to see

https://github.com/pbatard/rufus/releases/tag/v4.6

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Already resolved**.
>
> - Resolved by #191556

CC @bomkz @stephengillie 🙏🏼

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Already resolved**.
> 
> * Resolved by [New version: Rufus.Rufus version 4.6 #191556](https://github.com/microsoft/winget-pkgs/pull/191556)
> 
> CC [@bomkz](https://github.com/bomkz) [@stephengillie](https://github.com/stephengillie) 🙏🏼
