### ISSUE TITLE
[Update Request]:  OpenRA list beta a stable

### ISSUE THREAD

**Issue by Chasapple4** [microsoft/winget-pkgs#195983]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

 OpenRA.OpenRA 

### Package Version

playtest-20241116 

### Please describe the changes you would like to see

playtest-20241116  is a beta version for testing fix since the last stable  release-20231010 

"OpenRA is available for many modern operating systems. The latest stable release is release-20231010 and the latest playtest is playtest-20241116."
https://www.openra.net/download/

![Image](https://github.com/user-attachments/assets/348d99c2-4f94-4cad-af40-652afc340420)

The current stable needs to be corrected back to release-20231010

**Comment by Dragon1573** [comment]
Is it better splitting them into 2 packages? Such as `OpenRA.OpenRA.Stable` and `OpenRA.OpenRA.Playtest`?
