### ISSUE TITLE
[Update Request]: appmakes.Typora version 1.3.6-8 & 1.2.3

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#196087]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

appmakes.Typora

### Package Version

1.3.6-8 & 1.2.3

### Please describe the changes you would like to see

The existing installer url for this version returns a 404 to the [GitHub Action](https://github.com/DuckDuckStudio/winget-tools/actions/runs/12150169890/job/33882365231#step:6:297), and I'm not sure if it's still available.

```[tasklist]
### Pull requests regarding this issue.
- [ ] #199959
- [ ] #199958
- [ ] #199957
- [ ] #199956
- [ ] #196726
- [ ] #199807
```

**Comment by Dragon1573** [comment]
```text
00:59:41 D:\...\winget-pkgs  [master ≡] 0ms pwsh> winget download --exact appmakes.Typora --version 1.3.7 --source winget
已找到 Typora [appmakes.Typora] 版本 1.3.7
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://typora-download.oss-cn-shanghai.aliyuncs.com/windows/typora-setup-x64-1.3.7.exe
执行此命令时发生意外错误：
Download request status is not success.
0x80190194 : Not found (404).
```

Unavailable for me either. 😞

**Comment by SpecterShell** [comment]
The Chinese server host was changed to `download2.typoraio.cn` two years ago. You can fix them by replacing the URL host manually.
