### ISSUE TITLE
[Package Request]: Speakeasy CLI

### ISSUE THREAD

**Issue by TristanSpeakEasy** [microsoft/winget-pkgs#196381]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/speakeasy-api/speakeasy/releases/tag/v1.451.5
Publisher: Speakeasy Inc
Package Name: speakeasy.cli
Description: This CLI is a tool for interacting with the Speakeasy platform - the CLI brings the functionality of Speakeasy into your development workflow. It can be run locally or in your CI/CD pipeline to validate your API specs, generate SDKs and more.

      Current functions of the CLI include:

      Generating idiomatic client SDKs from OpenAPI3.X specs:
      Live: Go, Python3, Typescript(Node), Java, PHP, Ruby, Terraform
      Validating the correctness of OpenAPI3 specs. The CLI has a built in command to validate your spec and post helpful error messages.
      Authenticating with the platform and managing API keys.
Package Version: 1.451.5
Installer Url: https://github.com/speakeasy-api/speakeasy/releases/download/v1.451.5/speakeasy_windows_amd64.zip

**Comment by TristanSpeakEasy** [comment]
Updated PR https://github.com/microsoft/winget-pkgs/pull/196383

**Comment by Dragon1573** [comment]
> Updated PR [#196383](https://github.com/microsoft/winget-pkgs/pull/196383)

Hello @TristanSpeakEasy 👋🏼, glad to see you resolve this issue on your own ❤.

> [!TIP]
>
> Modify your [very first comment](https://github.com/microsoft/winget-pkgs/pull/196383#issue-2719081184) as follows. This can link the pull request to this issue. When PR is merged, this issue can be closed as completed automatically. It can also prevent other contributors from confusing the issue state.

```diff
  Checklist for Pull Requests
 
  * [x]  Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- * [x]  Is there a linked Issue?
+ * [x]  Resolve #196381
```

**Comment by TristanSpeakEasy** [comment]
Great thank you done
