### ISSUE TITLE
[Update Request]: Autodesk.AutodeskAccess

### ISSUE THREAD

**Issue by pilcherd** [microsoft/winget-pkgs#196574]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Autodesk.AutodeskAccess

### Package Version

2.10.0.25

### Please describe the changes you would like to see

Almost every time I ever try and update this package (different versions), it is broken and refuses to update. The package hash never matches.
I assume that Autodesk is replacing their installer after the update is added, thereby breaking winget checks. That is a terrible practice - a single file with the same name should existing with a single hash. The only other option I see is the person maintaining this update is not updating the hash when a version is updated. All other packages in winget update fine.

Either way:

Found Autodesk Access [Autodesk.AutodeskAccess] Version 2.10.0.25
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://emsfs.autodesk.com/utility/access/1/installer/latest/AdAccess-installer.exe
  ██████████████████████████████   514 MB /  514 MB
**Installer hash does not match; this cannot be overridden when running as admin**

**Comment by pilcherd** [comment]
I guess, looking at the URL, since there is no version number in the URL, the more likely option is they've simply updated the installer again.

Would be good for AutoDesk to version installer upload filenames.

**Comment by pilcherd** [comment]
The installer was automatically updated to 2.10.0.25 by the auto bot on 10/22/24. The hash was set then.
However, the current EXE download has a different hash, digitally signed on ‎Sunday, ‎November ‎3, ‎2024 10:11:39 PM.
Looks like AD are releasing the _same_ version multiple times!. Should have had a version bump.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> - Will be resolved by #193429

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/163098

**Comment by stephengillie** [comment]
> Note
> 
> * Will be resolved by [Automatic update of Autodesk.AutodeskAccess 2.10.0.25 #193429](https://github.com/microsoft/winget-pkgs/pull/193429)

**Comment by pilcherd** [comment]
Thank you.
