### ISSUE TITLE
[Update Request]: MullvadVPN 2024.8

### ISSUE THREAD

**Issue by Tecnio** [microsoft/winget-pkgs#196668]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MullvadVPN.MullvadVPN 

### Package Version

2024.8

### Please describe the changes you would like to see

https://mullvad.net/en/download/vpn/windows

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Already resolved by #196648

CC @Tecnio @stephengillie 🙏🏼

**Comment by Dragon1573** [comment]
@Tecnio Could you please manually close the pull request as completed? 🙏🏼
