### ISSUE TITLE
[Package Issue]: Google.Chrome

### ISSUE THREAD

**Issue by SaidElKhoury** [microsoft/winget-pkgs#196617]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

I'm trying to install Google Chrome to using Winget. After Winget downloads the package it fails installing with the following error: _"Installer hash does not match".![Image](https://github.com/user-attachments/assets/c1bde28e-b82c-48d5-bf16-e995d124a176)

### Steps to reproduce

winget install google.chrome

### Actual behavior

Installer hash does not match.

### Expected behavior

Install Google Chrome using Winget

### Environment

```raw
C:\Users\selkho1>Winget --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4460
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/0711e048-9bda-45cf-9ff6-2c742f87f61b)

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/196086

**Comment by Dragon1573** [comment]
Manually verified. Issue still exists.

```text
01:12:03 ~\...\winget-pkgs  [master ≡] 2ms pwsh> winget download -e Google.Chrome -v 131.0.6778.86
已找到 Google Chrome [Google.Chrome] 版本 131.0.6778.86
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  ██████████████████████████████   121 MB /  121 MB
安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash
```

**Comment by SpecterShell** [comment]
> Manually verified. Issue still exists.
> 
> ```
> 01:12:03 ~\...\winget-pkgs  [master ≡] 2ms pwsh> winget download -e Google.Chrome -v 131.0.6778.86
> 已找到 Google Chrome [Google.Chrome] 版本 131.0.6778.86
> 此应用程序由其所有者授权给你。
> Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
> 正在下载 https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
>   ██████████████████████████████   121 MB /  121 MB
> 安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash
> ```

This version is outdated and should have been replaced 131.0.6778.109.
