### ISSUE TITLE
[Package Issue]: Mythicsoft.AgentRansack update failed several times

### ISSUE THREAD

**Issue by JustMyGithub** [microsoft/winget-pkgs#196682]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

9.2.3435.1 was installed. UniGetUI reported update 9.3.3499.1. I installed it and a few hours late the same update was reported again. This happened at least 3 times. during teh 2nd and 3rd time I noticed, that it was very quick and UAC was not shown, so I guess setup it not even run at all, but winget reported to UniGetUi that everything is fine.
After a manual install and restart of UniGetUI everything seems alright now.

### Steps to reproduce

As in "Brief description"

### Actual behavior

If update fails, it reported success

### Expected behavior

If update fails, report error

### Environment

```raw
Windows-Paket-Manager v1.9.25200
Windows: Windows.Desktop v10.0.19044.5131
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.24.25200.0
```

**Comment by Trenly** [comment]
@stephengillie - this is not a case of `Upgrade-Always-Available`, it is a case of `Upgrade didn't actually apply`.

What is happening here @JustMyGithub is WinGet tries to upgrade the app as instructed by UniGetUI, but returns this response -
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade Mythicsoft.AgentRansack
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
```

If using `winget upgrade --all` then the `$LASTEXITCODE` is `0` and this message isn't displayed, which is probably why UniGetUI isn't showing any errors. If attempting to upgrade the package directly, you get that error message and `$LASTEXITCODE` is `-1978335189`. 

-----

The installer type hasn't actually changed, which means that even though it is a nullsoft installer, the nullsoft is just a wrapper around another type of installer. This should be able to be corrected by adding `AppsAndFeaturesEntries` specifying what the underlying installer type is (msi), as well as the product code of the application.
