### ISSUE TITLE
[Package Request]: LiteratureandLatte.Scapple

### ISSUE THREAD

**Issue by AustinZhang1024** [microsoft/winget-pkgs#196760]
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.literatureandlatte.com/scapple/overview
Publisher: LiteratureandLatte
Package Name: LiteratureandLatte.Scapple
Description: Get your thoughts, musings and 3am brainwaves onto the page. Then join them up in any way you like.
Package Version: 1.4.2
Installer Url: https://www.literatureandlatte.com/download_action.php?url=https://scrivener.s3.amazonaws.com/Scapple-installer.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This package only provides "free trail" version, or users have to pay for it.
>
> Is these kinds of packages acceptable?

**Comment by AustinZhang1024** [comment]
> Note
> 
> This package only provides "free trail" version, or users have to pay for it.
> 
> Is these kinds of packages acceptable?

Scrivener 3 of LiteratureandLatte have been added. So I think it's acceptable.
