### ISSUE TITLE
[Update Request]: Genymobile.scrcpy 3.0.2

### ISSUE THREAD

**Issue by jotebe** [microsoft/winget-pkgs#196727]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Genymobile.scrcpy

### Package Version

3.0.2

### Please describe the changes you would like to see

There's a new version.

https://github.com/Genymobile/scrcpy/releases/tag/v3.0.2

**Comment by jotebe** [comment]
> We've found some similar issues:
> 
>     * [[Update Request]: Genymobile.scrcpy v3.0 #194619](https://github.com/microsoft/winget-pkgs/issues/194619) , similarity score: 97%
> 
>     * [[Update Request]: scrcpy #171430](https://github.com/microsoft/winget-pkgs/issues/171430) , similarity score: 87%
> 
>     * [[Update Request]: Update scrcpy package to the latest version #166969](https://github.com/microsoft/winget-pkgs/issues/166969) , similarity score: 86%
> 
>     * [[Update Request]: Genymobile.scrcpy #192018](https://github.com/microsoft/winget-pkgs/issues/192018) , similarity score: 81%
> 
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> > Note: You can give me feedback by 👍 or 👎 this comment.

All similar requests are for older versions than this request.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> It's currently in progress.
>
> - Related #196442 

> [!TIP]
>
> Manually subscribe to the related PR. Don't forget to close this issue as completed when the PR is merged ❤
