### ISSUE TITLE
[Update Request]: VCVRack.VCVRack 2.6.0

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#196744]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

VCVRack.VCVRack

### Package Version

2.6.0

### Please describe the changes you would like to see

https://github.com/VCVRack/Rack/blob/v2/CHANGELOG.md

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> [`InstallerUrl`](https://vcvrack.com/downloads/RackFree-2.5.2-win-x64.exe) of version `2.5.2` is extracted from [`PackageUrl`](https://vcvrack.com/Rack). The `PackageUrl` does not provide installer file of version `2.6.0`.
>
> ![Image](https://github.com/user-attachments/assets/a801ba30-9de1-46c9-890f-7826df52d01c)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> By guessing the pattern of `InstallerUrl`, it seems version `2.6.0` is available via [version-related static direct link](https://vcvrack.com/downloads/RackFree-2.6.0-win-x64.exe).
>
> Have no idea why they don't upgrade contents of their `PackageUrl` 😕.
