### ISSUE TITLE
[Update Request]: Zalo

### ISSUE THREAD

**Issue by iamsirbrave** [microsoft/winget-pkgs#196996]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

VNGCorp.Zalo

### Package Version

24.12.1

### Please describe the changes you would like to see

New version 24.12.1 of VNGCorp.Zalo
Download link: https://res-download-pc-te-vnso-zn-31.zadn.vn/win/ZaloSetup-24.12.1.exe

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> New `InsatllerUrl` extracted from `PackageUrl` should be <https://res-zaloapp-aka.zdn.vn/win/ZaloSetup-24.12.1.exe>, to keep consistency (URL pattern here) of the previous version `23.12.1`.

**Comment by iamsirbrave** [comment]
> Note
> 
> New `InsatllerUrl` extracted from `PackageUrl` should be https://res-zaloapp-aka.zdn.vn/win/ZaloSetup-24.12.1.exe, to keep consistency (URL pattern here) of the previous version `23.12.1`.

Oh, sorry. I took my link from the Zalo download page, it seems there are 2 URLs for the installer.
