### ISSUE TITLE
[Package Issue]:OBSProject.OBSStudio

### ISSUE THREAD

**Issue by 3xploiton3** [microsoft/winget-pkgs#197030]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Different install technology.

### Brief description of your issue

Files modified by the installer are currently in use by a different application. Exit the applications then try again.
Installer failed with exit code: 6

### Steps to reproduce

winget upgrade --all

### Actual behavior

Files modified by the installer are currently in use by a different application. Exit the applications then try again.
Installer failed with exit code: 6

### Expected behavior

success

### Environment

```raw
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.4317
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/dd4a5249-0866-4e67-bced-34ad6835f507)

**Comment by Trenly** [comment]
This is expected behavior. The installer can’t upgrade the application when it is in use, and WinGet won't close applications so that user data isnt lost. Make sure any applications that might be using OBS such as Zoom, Microsoft Team, and OBS itself are all closed before upgrading OBS

###### Close with reason: Expected Behavior;

**Comment by elreymon** [comment]
In my case was **Google Chrome**.
To guess which program is, just locate de installer (.exe) file downloaded by winget (you can see the log) and exceute it manually. Then in the install GUI the OBS installer will complain about a program opened and there you will see wich one is.

**Comment by jamesaepp** [comment]
I just want to comment for anyone else that I also experience this issue regularly. For me the last two times the culprit has been Edge.
