### ISSUE TITLE
[Update Request]: HWiNFO 8.16

### ISSUE THREAD

**Issue by asdf12303116** [microsoft/winget-pkgs#197018]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

REALiX.HWiNFO

### Package Version

8.16

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> It's currently in progress.
>
> - Will be resolved by #196079
> - Will be resolved by #194875

**Comment by Frenky9871** [comment]
Y

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - Already resolved by #194875 

CC @asdf12303116 @stephengillie 🙏🏼

**Comment by stephengillie** [comment]
> Note
> 
> Close with reason: **Resolved**.
> 
> * Already resolved by [New version: REALiX.HWiNFO version 8.16 #194875](https://github.com/microsoft/winget-pkgs/pull/194875)
> 
> CC [@asdf12303116](https://github.com/asdf12303116) [@stephengillie](https://github.com/stephengillie) 🙏🏼
