### ISSUE TITLE
Google.DriveFileStream version is outdated

### ISSUE THREAD

**Issue by DRSchlaubi** [microsoft/winget-pkgs#19732]
https://github.com/microsoft/winget-pkgs/blob/5cf0162934e7d69a6c29481da54a0e91bf686efc/manifests/g/Google/DriveFileStream/48.0.13.0/Google.DriveFileStream.yaml#L3

Currently, FileStream is listed as `48.0.13.0`

however if you run `winget install Google.DriveFileStream` version `49.0.8.0` get's installed instead
![](https://rice.by.devs-from.asia/TEzu3/kuwUdeYE64.png)

**Comment by ImJoakim** [comment]
Hey there, I get the correct version (according to the manifest) when I install it:

![image](https://user-images.githubusercontent.com/52826317/124373081-bdf02c80-dc8f-11eb-8245-b687c1b527fa.png)

I did some research, and it looks like the new version (`49.0.8.0`) is not out for everyone at this time.
I found this article from 9to5google talking about the latest version which includes this following sentence:

> Version 49.0.8.0 of this new Google Drive for desktop app is not yet widely rolled out.

Article: https://9to5google.com/2021/07/02/new-google-drive-desktop/

**Comment by ImJoakim** [comment]
@DRSchlaubi Seems version `49.0.8.0` has now been rolled out. A PR has been opened #20164.

**Comment by DRSchlaubi** [comment]
I guess this can be closed now because of #20164.
