### ISSUE TITLE
[Update Request]: NATS.Authors.CLI 0.1.5

### ISSUE THREAD

**Issue by gr7ffo** [microsoft/winget-pkgs#197487]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

NATS.Authors.CLI

### Package Version

0.1.5

### Please describe the changes you would like to see

There is a new release (0.1.5) available.
Download Page Url: https://github.com/nats-io/natscli/releases/tag/v0.1.5.

**Comment by Dragon1573** [comment]
Hi @gr7ffo 👋🏼,

```text
17:33:04 D:\...\winget-pkgs  [master ≡] 91ms 0x0002 pwsh> komac show --installer-manifest NATS.Authors.CLI
Error: 
   0: NATS.Authors.CLI does not exist in microsoft/winget-pkgs

17:33:25 D:\...\winget-pkgs  [master ≡] 1.984s 0x0001 pwsh> winget search -s winget NATS.Authors.CLI
找不到与输入条件匹配的程序包。
```

I can't find the exact package identifier. Did you mis-spell it?
