### ISSUE TITLE
[Update Request]: Picocrypt

### ISSUE THREAD

**Issue by EriusCalrissian** [microsoft/winget-pkgs#197486]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

EvanSu.Picocrypt

### Package Version

1.4.5

### Please describe the changes you would like to see

Repository moved to new directory, from https://github.com/HACKERALERT/Picocrypt to https://github.com/Picocrypt/Picocrypt. WinGet still old one.
Releases: https://github.com/Picocrypt/Picocrypt/releases
Direct Download Current Version: https://github.com/Picocrypt/Picocrypt/releases/download/1.45/Picocrypt.exe

**Comment by Dragon1573** [comment]
> ### Please describe the changes you would like to see
>
> Repository moved to new directory, from [HACKERALERT/Picocrypt](https://github.com/HACKERALERT/Picocrypt) to [Picocrypt/Picocrypt](https://github.com/Picocrypt/Picocrypt). WinGet still old one.

Hi @EriusCalrissian 👋🏼,

```text
17:30:20 D:\...\winget-pkgs  [master ≡] 0ms pwsh> winget show -s winget -e EvanSu.Picocrypt --versions
已找到 Picocrypt [EvanSu.Picocrypt]
版本
----
1.33
1.32
```

Should this package also move to a new identifier `Picocrypt.Picocrypt`?

**Comment by EriusCalrissian** [comment]
> Should this package also move to a new identifier `Picocrypt.Picocrypt`?

Hello @Dragon1573,

this might make sense but I don't know how WinGet usually handles such things.

**Comment by EriusCalrissian** [comment]
Hello @Dragon1573,

Picocrypt.Picocrypt new version 1.45 is still missing.

https://github.com/Picocrypt/Picocrypt/releases/download/1.45/Picocrypt.exe
