### ISSUE TITLE
[Update Request]: RevoUninstaller.RevoUninstaller

### ISSUE THREAD

**Issue by URD0TH** [microsoft/winget-pkgs#197583]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

RevoUninstaller.RevoUninstaller

### Package Version

2.5.6.0

### Please describe the changes you would like to see

# Please confirm these before moving forward

- [x]  I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

# Category of the issue

Installer hash does not match with the hash that's defined in the package manifest

Installer hash mismatch.

# Brief description of your issue

[RevoUninstaller manifest issue](https://github.com/microsoft/winget-pkgs/blob/master/manifests/r/RevoUninstaller/RevoUninstaller/2.5.6.0/RevoUninstaller.RevoUninstaller.installer.yaml)

https://github.com/microsoft/winget-pkgs/blob/939a544297687a3993f6b9a098ad2b80c33787a0/manifests/r/RevoUninstaller/RevoUninstaller/2.5.6.0/RevoUninstaller.RevoUninstaller.installer.yaml#L18

Installer hash does not match with the hash that's defined in the package manifest  
PackageVersion: 2.5.6.0  
InstallerSha256:  
`E9085FBB110DC2AFED76DB7AF8F3CE3DCB65D4278E7D2DEE9444D6D9F8EB1824`

# Steps to reproduce

Install the latest version of RevoUninstaller with the command:

```powershell
winget install RevoUninstaller.RevoUninstaller --accept-package-agreements --accept-source-agreements
```

# Actual behavior

Installation fails with the error "Installer hash does not match.".

# Expected behavior

Successful installation.

# Environment

```powershell
winget --info
Administrador de paquetes de Windows v1.9.25200
Copyright (c) Microsoft Corporation. Todos los derechos reservados.
```

# Screenshots and Logs

```powershell
Windows: Windows.Desktop v10.0.22621.4317
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.24.25200.0

winget install RevoUninstaller.RevoUninstaller --accept-package-agreements --accept-source-agreements
Found Revo Uninstaller [RevoUninstaller.RevoUninstaller] Version 2.5.6.0
The owner of this application grants you a license.
Microsoft is not responsible, nor does it grant any license for third-party packages.
Downloading https://download.revouninstaller.com/download/revosetup.exe
  ██████████████████████████████  10.8 MB / 10.8 MB
The installer hash does not match; this cannot be overwritten when running as administrator.

```

**Comment by Dragon1573** [comment]
Manually verified

```text
09:37:41 D:\...\winget-pkgs  [master ≡] 1ms pwsh> winget download -s winget RevoUninstaller.RevoUninstaller -v 2.5.6.0
已找到 Revo Uninstaller [RevoUninstaller.RevoUninstaller] 版本 2.5.6.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://download.revouninstaller.com/download/revosetup.exe
  ██████████████████████████████  10.8 MB / 10.8 MB
安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash
```

**Comment by URD0TH** [comment]
Good catch! @Dragon1573  I didn't realize the issue was caused by the software upgrade. Now it will be on my checklist to verify if the software has been upgraded , Thx!


![Image](https://github.com/user-attachments/assets/97207deb-79b1-4b8b-8c4d-ebccebf18d23)




> Manually verified
> 
> ```
> 09:37:41 D:\...\winget-pkgs  [master ≡] 1ms pwsh> winget download -s winget RevoUninstaller.RevoUninstaller -v 2.5.6.0
> 已找到 Revo Uninstaller [RevoUninstaller.RevoUninstaller] 版本 2.5.6.0
> 此应用程序由其所有者授权给你。
> Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
> 正在下载 https://download.revouninstaller.com/download/revosetup.exe
>   ██████████████████████████████  10.8 MB / 10.8 MB
> 安装程序哈希不匹配；若要重写此检查，请使用 --ignore-security-hash
> ```

Now I'll wait for the PR https://github.com/microsoft/winget-pkgs/pull/197639 to close.

**Comment by Dragon1573** [comment]
@wingetbot is currently doing the same thing.

- See #197624
