### ISSUE TITLE
Unetbootin Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#19768]
PackageIdentifier:Unetbootin
PackageVersion: 702
PackageLocale: en-US
Publisher: Geza Kovacs
PackageName: unetbootin
License: open source
ShortDescription: app for create bootable USB
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/unetbootin/unetbootin/releases/download/702/unetbootin-windows-702.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by quhxl** [comment]
We cannot add this because it is not an installer. Or do you have an installer URL?

**Comment by dtantono** [comment]
Hi,
I only have this github page (https://github.com/unetbootin/unetbootin). What do you think?

**Comment by quhxl** [comment]
I think there is no installer. We will probably have to wait until portable/standalone apps are possible. https://github.com/microsoft/winget-cli/issues/182

**Comment by vedantmgoyal2009** [comment]
@quhxl @dtantono we can use this: https://github.com/unetbootin/unetbootin/releases/download/702/unetbootin-windows-702.exe

**Comment by quhxl** [comment]
We can't because it's an portable application and not an installer...

**Comment by vedantmgoyal2009** [comment]
oh, yes! i forgot winget still lacks support for portable apps. 😞

**Comment by Trenly** [comment]
Close with reason: Resolved by #68804;
