### ISSUE TITLE
Citra Request

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#19771]
PackageIdentifier: Citra
PackageVersion: 1.0
PackageLocale: en-US
Publisher: Citra Team
PackageName: Citra
License: open source
ShortDescription: Nintendo 3ds emulator
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-windows.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by OfficialEsco** [comment]
Can't seem to find the installer switches for the installer?
```
PS C:\Users\Esco\Downloads> .\citra-setup-windows.exe /S
PS C:\Users\Esco\Downloads> .\citra-setup-windows.exe --silent
PS C:\Users\Esco\Downloads> .\citra-setup-windows.exe /qb
PS C:\Users\Esco\Downloads> .\citra-setup-windows.exe -s
PS C:\Users\Esco\Downloads> .\citra-setup-windows.exe /silent
```

**Comment by quhxl** [comment]
I don't think there are any. I have also been looking for some time.

**Comment by quhxl** [comment]
https://github.com/citra-emu/citra/issues/5790
An issue has already been created. I guess that's all we can do unless we find a switch.

**Comment by agowa** [comment]
It looks like this one has been resolved already. The only issue remaining, the installer fails when the application is already installed AND it sets the wrong version number information causing package managers like winget trying to update it every time `winget upgrade --all` is ran.

Also it looks like the update code is not present within the installer, which is kinda annoying for usage within package managers like winget.

https://github.com/microsoft/winget-pkgs/blob/cca2f0e6ccf6a7882ee18ade0e61ee72ba620fdb/manifests/c/CitraEmu/Citra/2.0/CitraEmu.Citra.installer.yaml

**Comment by Trenly** [comment]
Close with reason: Package added as per above comment; Please also note that Citra has been officially discontinued by the authors - https://citra-emu.org/
