### ISSUE TITLE
Pcsx2 Request

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#19770]
PackageIdentifier: Pcsx2
PackageVersion: 1.6.0
PackageLocale: en-US
Publisher: lightningterror
PackageName: Pcsx2
License: open source
ShortDescription: Playstation 2 emulator
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/PCSX2/pcsx2/releases/download/v1.6.0/pcsx2-1.6.0-setup.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by OfficialEsco** [comment]
This can be added when a newer version than 1.6.0 is released https://github.com/PCSX2/pcsx2/pull/3435

**Comment by Trenly** [comment]
[Policy] Package Request
