### ISSUE TITLE
yumi-uefi request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#19780]
PackageIdentifier: yumi-uefi
PackageVersion: 0.0.3.9
PackageLocale: en-US
Publisher: pendrive
PackageName: yumi-uefi
License: proprietary
ShortDescription: multiboot USB creator
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://www.pendrivelinux.com/downloads/YUMI/YUMI-UEFI-0.0.3.9.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by vedantmgoyal2009** [comment]
It is a portable app and winget still doesn't support portable apps.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/issues/182

**Comment by Trenly** [comment]
[Policy] Package Request
