### ISSUE TITLE
yumi-bios request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#19781]
PackageIdentifier: yumi-bios
PackageVersion: 2.0.8.8
PackageLocale: en-US
Publisher: pendrive
PackageName: yumi-bios
License: proprietary
ShortDescription: multiboot USB creator for old PC
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://www.pendrivelinux.com/downloads/YUMI/YUMI-2.0.8.8.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/issues/182

**Comment by Trenly** [comment]
[Policy] Package Request
