### ISSUE TITLE
[Update Request]: Update NomanDhoni.BlinkEye to v2.4.0

### ISSUE THREAD

**Issue by nomandhoni-cs** [microsoft/winget-pkgs#198144]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

NomanDhoni.BlinkEye

### Package Version

2.4.0

### Please describe the changes you would like to see

There is a new Release available 
https://github.com/nomandhoni-cs/blink-eye/releases/tag/v2.4.0

**Comment by nomandhoni-cs** [comment]
> We've found some similar issues:
> 
> * [[Update Request]: for Blink Eye v2.3.0 #195349](https://github.com/microsoft/winget-pkgs/issues/195349) , similarity score: 87%
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> > Note: You can give me feedback by 👍 or 👎 this comment.

Nope, that was 2.3.0, Now It's available in 2.4.0

**Comment by Dragon1573** [comment]
Hi @nomandhoni-cs 👋🏼, this issue is currently in progress now ❤.

- Will be resolved by #198148

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: **Resolved**.
>
> - See #198148 

CC @nomandhoni-cs @stephengillie 🙏🏼

**Comment by nomandhoni-cs** [comment]
@Dragon1573, @stephengillie  Just a question, If I release a new version of BlinkEye? Do I have create a issue for this you have a workflow setup that will update the version automatically?

**Comment by Dragon1573** [comment]
> Just a question, If I release a new version of _BlinkEye_? Do I have create a issue for this you have a workflow setup that will update the version automatically?

For most projects directly released via **GitHub Releases**, @wingetbot **MIGHT BE** able to detect a newer version of it.

For package publishers (those who officially own the project and publish releases) on GitHub, this can be done by integrate [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser) to GitHub Workflows.

Other contributors might use their own bot accounts with automatic tools, such as [🥟Dumplings](https://github.com/SpecterShell/Dumplings) by @SpecterShell.

For me, I'd prefer manually subscribe to those repositories and keep watching their releases action. While a new version is released, I'll manually create an issue for update request and create a pull request for solving it on my own. For those packages release elsewhere, I may be notified by the bundled "updater" inside the package and then do same things above.

**Comment by Dragon1573** [comment]
> Do I have create a issue for this you have a workflow setup that will update the version automatically?

At this comment publish, the repository contains 866 open and 4461 closed issues only, but 461 open and **192,013** closed pull requests. Most of the contributors and volunteers don't create a related issue for asking version upgrade. They just solve it with pull request only.

I think creating issue for asking version upgrade is not required. Just try using [`Tools/YamlCreate.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1), [`wingetcreate.exe`](https://github.com/microsoft/winget-create) or [`komac.exe`](https://github.com/RussellBanks/Komac) and upgrade the manifest on your own ❤.

**Comment by nomandhoni-cs** [comment]
I am the repository owner I think I will try to setup a workflow. Do I have to get `WINGET_TOKEN ` this token from any where or just I can just randomly make a token

**Comment by Dragon1573** [comment]
> Do I have to get `WINGET_TOKEN` this token from any where or just I can just randomly make a token.

`secrets.WINGET_TOKEN` is just a GitHub **Classic** Personal Access Token. Grant required rights to the token as instructed ❤.
