### ISSUE TITLE
Requirements for being a reviewer with write access

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#19827]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

-----------------------------------------------------------------------------------------------------
Can anyone tell me what requirements do I need to meet to be a reviewer with write access?

**Comment by OfficialEsco** [comment]
To keep it simple: By contributing more than 2 packages that required correction.

**Comment by vedantmgoyal2009** [comment]
Oh, thanks

**Comment by vedantmgoyal2009** [comment]
> To keep it simple: By contributing more than 2 packages that required correction.

Please name some packages so that I can make manifest files for them 🙏🏻

**Comment by denelon** [comment]
@vedantmgoyal2009 the moderators have each submitted more than 800 manifests personally and contributed over a period of many consecutive months. This includes helping others submit good quality manifests and working through challenges related to the upgrade scenario and other shortcomings of the client. You can take a look at the "Help Wanted" issues as a starting point to learn what is and isn't supported by the product, and look at the discussions across many of the "Moderator-Approved" PRs to get a sense for common issues and challenges. I'd suggest reading and learning about the product and watching the process. Try crafting a few more manifests based on the Help Wanted issues. Once you get a solid handle on how to build good manifests, and your submissions merely require a moderator to approve, then you can start helping others by making constructive suggestions on their PRs. You could also help by looking at new issues as they come in. We often have duplicates, and it helps to have someone who is familiar with the backlog deduplicate. Remember the Code of Conduct when interacting with others. There are many different ways to contribute, and we welcome your help.

**Comment by vedantmgoyal2009** [comment]
@denelon Please also tell what is ARP and where I can find it?

**Comment by OfficialEsco** [comment]
> @denelon Please also tell what is ARP and where I can find it?

https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/defaultLocale.md#publisher

**Comment by vedantmgoyal2009** [comment]
Where do I get this? This screenshot.
![](https://user-images.githubusercontent.com/52826317/124722823-b7b9b480-df0a-11eb-93d9-71e3b22b9087.png)

**Comment by ImJoakim** [comment]
> Where do I get this? This screenshot.
> ![](https://user-images.githubusercontent.com/52826317/124722823-b7b9b480-df0a-11eb-93d9-71e3b22b9087.png)
> This type of screenshot, I have seen many times. I googled about ARP but I only get info about Address Resolution Protocol.

This specific screenshot is from a program called Revo Uninstaller. You don't need to use this program, you can find this information in the control panel where you uninstall programs.

**Comment by vedantmgoyal2009** [comment]
Okay thanks for telling.

**Comment by vedantmgoyal2009** [comment]
What is the full form of ARP here, on Google, it shows Address Resolution Protocol but that doesn't fit here

**Comment by ItzLevvie** [comment]
Add or Remove Programs.

**Comment by ImJoakim** [comment]
> What is the full form of ARP here, on Google, it shows Address Resolution Protocol but that doesn't fit here

https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/defaultLocale.md#publisher

![image](https://user-images.githubusercontent.com/52826317/124733814-d8870780-df14-11eb-9ceb-14feec3ceba1.png)

**Comment by vedantmgoyal2009** [comment]
Thanks a lot.
