### ISSUE TITLE
Removal of old versions of softwares which have daily nightly builds

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#19840]
## Description of the new feature/enhancement
I think old versions of the software which have daily nightly builds should be removed and only the last 50-60 versions should be only kept. Keeping every version of the daily build is not a very good choice. For example, VLC Player and OpenJS/NodeJS.

## Proposed technical implementation details (optional)
Deleting manifests of very old versions of nightly builds of the software.

###### I have edited my old issue because I did not want to spam the repository.

**Comment by Marsfan** [comment]
I am just another user of winget. so my explanations might not be why others gave you a thumbs down. These are just my thoughts, however I suspect that others that disagree with you have the same (or similar reasons).

There are two areas that I can see that are reasons to not implement this. The first is that I don't see how the issues that you presented are solved by removing old manifest files, the second is that there are times when a user will actually want or need an older version. I organized this into two sections to make this clearer. 

## Issues are not fixed/not actually a problem. 

> no one would like to use the old version when new versions are available.

When a user installs a package with winget, it already selects the newest version available. The old manifest files are only used if the user explicitly selects to install an older version (I will cover this more in the next section). Thus, these files are completely harmless for a casual user of winget who just wants to install the newest version of a program. 

> It would make it easy to manage the repository.
How? Adding a new manifest file does not require opening all of the previous manifest files. They are harmless and completely independent. You don't need to do anything to the old files. Having to go in an delete old packages would add more work for managing the repository, as now someone has to find all manifest files that might be old versions, verify that they really are for an outdated version, and then delete them.

## Reasons why a user might want to install an older version. 

There are a number of uses for having access to older versions of packages available. This is a quick list off of the top of my head of a few reasons that a user might want to install an older version. 
1. Performance: A user might have an older computer that cannot run a newer version of a program, and thus would want to install an older version. 
2. Regressions: Often a new version of a program may introduce a bug or security vulnerability, and a user may wish to stick with an older version until a patch can be released. 
3. Necessity of specific versions. This has two sub parts. 
    1. It is fairly common for software that connects to other software or hardware to drop support for a system in newer updates. A user might have a product that would not be supported in the newer version and will want to download the old version. 
    2.  It is extremely common in some industries (engineering, software development, and government contracts to name a few) that a specific version of a program or library **_must_** be used. This can be for a number of different reasons (security, stability, government requirement, hardware support, IT rules, etc).  Removing old versions of programs will hurt lots of software developers. Switching to a newer version of a program can add lots of additional work in a development cycle, and can add lots of new bug and security issues. This is not to mention that a customer or sub-contractor might be on a different version (for whatever reason), and they might not be able to open a file created in the newer version of a program.

**Comment by vedantmgoyal2009** [comment]
> 1. Performance: A user might have an older computer that cannot run a newer version of a program, and thus would want to install an older version.
> 2. Regressions: Often a new version of a program may introduce a bug or security vulnerability, and a user may wish to stick with an older version until a patch can be released.

For these reasons, recent builds are kept, I am **not** saying to remove all daily builds and only the most recent version should be kept.
> 3. Necessity of specific versions. This has two sub parts.
>    
>    i. It is fairly common for software that connects to other software or hardware to drop support for a system in newer updates. A user might have a product that would not be supported in the newer version and will want to download the old version.
>    ii. It is extremely common in some industries (engineering, software development, and government contracts to name a few) that a specific version of a program or library **_must_** be used. This can be for a number of different reasons (security, stability, government requirement, hardware support, IT rules, etc).  Removing old versions of programs will hurt lots of software developers. Switching to a newer version of a program can add lots of additional work in a development cycle, and can add lots of new bug and security issues. This is not to mention that a customer or sub-contractor might be on a different version (for whatever reason), and they might not be able to open a file created in the newer version of a program.

Nightly builds are not used in such cases :)

**Comment by Marsfan** [comment]
@vedantmgoyal2009 I agree with you regarding nightly builds. That makes much more sense. 
However, I think you may be mistaken in being concered about "spamming" the repository. The changes are significant enough that I would recommend opening it as a new issue, and leaving this one closed and with the previous discussion you brought up. There is no shame in having issues that are disagreed with, its all part of the discussion and planning process. By editing this issue, you reduce the likelyhood that your new idea is seen, and the edits can potentially leave other users confused when trying to understand why replies to your original post no longer seem to address that post.
