### ISSUE TITLE
Hh

### ISSUE THREAD

**Issue by Frenky9871** [microsoft/winget-pkgs#198597]
> We've found some similar issues:
> 
> 
> - #188214 , similarity score: 83%
>   
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> Note: You can give me feedback by 👍 or 👎 this comment. 

 _Originally posted by @similar-issues-ai in [#197018](https://github.com/microsoft/winget-pkgs/issues/197018#issuecomment-2525561539)_

**Comment by Trenly** [comment]
Close with reason: Not enough info in Issue; Please open a new issue using the issue templates

**Comment by Frenky9871** [comment]
H
