### ISSUE TITLE
[Package Request]: DNS Jumper

### ISSUE THREAD

**Issue by celestialcato** [microsoft/winget-pkgs#198778]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://dnsjumper.net/
Publisher: DNS Jumper
Package Name: DnsJumper.DnsJumper
Description: DNS Jumper is a software tool designed to help users easily change their Domain Name System (DNS) settings.
Package Version: 2.3
Installer Url: https://customresolutionutility.b-cdn.net/DnsJumper.zip

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> It seems _DNS Jumper_ IS NOT the actual developer of this package. See [Disclaimer - DNS Jumper](https://dnsjumper.net/disclaimer/) for more.

**Comment by celestialcato** [comment]
@Dragon1573 
Thanks for the heads up. It seems that the developer of DNS Jumper is https://www.sordum.org/
Link to the software page : https://www.sordum.org/7952/dns-jumper-v2-3/
Link to the latest version : https://www.sordum.org/files/download/dns-jumper/DnsJumper.zip

**Comment by Dragon1573** [comment]
> Link to the latest version: <https://www.sordum.org/files/download/dns-jumper/DnsJumper.zip>

This URL seems a vanity URL, which always points to the latest version. This may cause <https://github.com/microsoft/winget-pkgs/labels/Error-Hash-Mismatch> frequently while a new version is released.

Do they actively maintaining the package? Do they provide version-related static links? I can't find any entrance like "version archives".

**Comment by Dragon1573** [comment]
It's okay to submit a package using vanity URL. But version-related static URL is always the better choice. ❤

Don't hesitate to create issues for asking package updates! 😄
