### ISSUE TITLE
Package Request: MSI Afterburner

### ISSUE THREAD

**Issue by Neikon** [microsoft/winget-pkgs#1990]
#Package Requested
MSI Afterburner a tool for OC and monitoring PC stats

Link: https://es.msi.com/page/afterburner

**Comment by jedieaston** [comment]
This is waiting on https://github.com/microsoft/winget-cli/issues/140, I think. Since Afterburner is distributed as a exe in a zip file, winget can't install it yet.

**Comment by Macleykun** [comment]
Small problem, even if .zip support would be added. The link has some hot-linking protection:
https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=1645450949~acl=/*~hmac=6085551a15037028645e6481cecadf35351bf7d52fc05be9290f0ffd6c1bb64f

This is one i currently got. But i'm sure it'll expire in a few hours/days. The only way to actually add support is to use a 3rd party and check the hashes from both installers.
I've made a PR https://github.com/microsoft/winget-pkgs/pull/47081 and i've checked that the latest 4.6.4 is indeed the exact same from both sources.

**Comment by soredake** [comment]
@Macleykun how choco package deals with this url https://github.com/HunterZ/choco/blob/master/msiafterburner/tools/chocolateyInstall.ps1#L2

**Comment by Macleykun** [comment]
> @Macleykun how choco package deals with this url https://github.com/HunterZ/choco/blob/master/msiafterburner/tools/chocolateyInstall.ps1#L2

Heya! Thanks for taking the time to look into this :) <3
I'm not entirely sure if winget allows using powershell commands to formulate the download url. I see that the token is merely the current day which is great news! But i have to ask one of the mods here if it's possible. If so i would love to give this another try!

If ya have any questions ya can always reach me on Discord Macley#6969

**Comment by soredake** [comment]
Example download url from chocolatey install `https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=1658905109~acl=/*~hmac=c9252b6f24d8a58f87fe3f4561bc2c94627e00efda3b89892bb301b99ff176d0`

**Comment by Macleykun** [comment]
> Example download url from chocolatey install `https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=1658905109~acl=/*~hmac=c9252b6f24d8a58f87fe3f4561bc2c94627e00efda3b89892bb301b99ff176d0`

If you visit this link it won't download from msi. There's a better way but i need confirmation from mods and zip support.

guru3d shows here: https://www.guru3d.com/files-details/msi-afterburner-beta-download.html
That we can download it, however the download starts after 5 seconds and i doubt winget would work with that.
Downloading it and looking at the downloaded url shows this:

https://ftp.nluug.nl/pub/games/PC/guru3d/afterburner/[Guru3D.com]-MSIAfterburner.zip

This is what guru3d refers to when downloading so in my eyes it's valid but not static (so you have to change the version and hash each time an upgrade happens).

That's the only way unless you manage to get msi to offer the download in a normal way.

**Comment by Macleykun** [comment]
> @Macleykun how choco package deals with this url https://github.com/HunterZ/choco/blob/master/msiafterburner/tools/chocolateyInstall.ps1#L2

also the way this works is probably not gonna be implemented in winget.

The way they get the token of today is by asking the api (funny this is set public) what the token is if you give the current date.
That token then grants you withoud manual intervention the download link.

Unless winget adds some sort of pre-scripting, we can't use msi directly for this.

Both solutions again would always send latest and need to automatically be updated, otherwise we get an incorrect version + hash.

**Comment by OfficialEsco** [comment]
Ahh i didn't realize you wanted a reply since you've described the requirements.
If we're going to use the chocolatey method we will have to wait for ps1/script InstallerType support (if it gets added)

>>  +1 for adding the ability to execute a `.ps1` or `.bat` script after extracting a ZIP file. Ideally, this should be a file that may not be included in the original package. This should allow us to work with most types of packages distributed as ZIP files.
>
> -1 for running semi-arbitrary scripts during a privileged install. Security? What was that?
>
> _Originally posted by **IanDarwin** in https://github.com/microsoft/winget-cli/issues/140#issuecomment-1194535799_

then proper zip support as you said.

@WinGetBot would update this regularly so @WinGetBot would need update ARP Entries support, in theory this should only trigger a hash missmatch once per version

So, this is a looooooooong way from being added.

The best way would be for Guru3D to release the installer without zipping it.
Or MSI or Guru3D to maintain it them self in the Microsoft Store repo.

**Comment by Macleykun** [comment]
> Ahh i didn't realize you wanted a reply since you've described the requirements. If we're going to use the chocolatey method we will have to wait for ps1/script InstallerType support (if it gets added)
> 
> > > +1 for adding the ability to execute a `.ps1` or `.bat` script after extracting a ZIP file. Ideally, this should be a file that may not be included in the original package. This should allow us to work with most types of packages distributed as ZIP files.
> > 
> > 
> > -1 for running semi-arbitrary scripts during a privileged install. Security? What was that?
> > _Originally posted by **IanDarwin** in [microsoft/winget-cli#140 (comment)](https://github.com/microsoft/winget-cli/issues/140#issuecomment-1194535799)_
> 
> then proper zip support as you said.
> 
> @wingetbot would update this regularly so @wingetbot would need update ARP Entries support, in theory this should only trigger a hash missmatch once per version
> 
> So, this is a looooooooong way from being added.
> 
> The best way would be for Guru3D to release the installer without zipping it. Or MSI or Guru3D to maintain it them self in the Microsoft Store repo.

Ya wanna ask :p ?

**Comment by mdanish-kh** [comment]
Close with reason: Package added in #97402;
