### ISSUE TITLE
[Update Request]: TechPowerUp.GPU-Z

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-pkgs#199152]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TechPowerUp.GPU-Z

### Package Version

2.61.0

### Please describe the changes you would like to see

There is a new release, version 2.61.0 for TechPowerUp.GPU-Z. I don't know how to get the URL though.

**Comment by cvrebert** [comment]
E.g. https://us2-dl.techpowerup.com/files/_JjH-TNo3N7BZFJNHPI6kQ/1734428336/GPU-Z.2.61.0.exe

**Comment by Dragon1573** [comment]
> E.g. https://us2-dl.techpowerup.com/files/_JjH-TNo3N7BZFJNHPI6kQ/1734428336/GPU-Z.2.61.0.exe

> [!NOTE]
>
> URL provided here contains encrypted messages. `winget.exe` does not support such kind of URLs.
>
> In previous versions, it seems the static direct link is only available for `winget.exe`. While visiting with browser, you'll be blocked by the server.
