### ISSUE TITLE
unicorn

### ISSUE THREAD

**Issue by Frenky9871** [microsoft/winget-pkgs#199191]
At Bitget, the safety of your assets is our priority.
https://www.bgportable.com/protection-fund?appVersion=2.47.4&time=1734340390875&androidSdk=34&language=en_US&appTheme=standard&clacCode=4XYB642Q![1734340413118.png](https://github.com/user-attachments/assets/172d9e9b-900c-450b-8a05-c3d4194f77b0)

**Comment by mdanish-kh** [comment]
Close with reason: Unrelated;
