### ISSUE TITLE
[Update Request]: Multiple NirSoft Packages

### ISSUE THREAD

**Issue by KarbitsCode** [microsoft/winget-pkgs#199574]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

NirSoft.*

### Package Version

Multiple

### Please describe the changes you would like to see

Some of the nirsoft packages are seem to be outdated, here is the report of each packages I have checked:

| Package name | Version from this repository | Version from nirsoft website |
|-----------------|--------------------------------|--------------------------------|
AppReadWriteCounter|[1.41](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/AppReadWriteCounter)|[1.42](https://www.nirsoft.net/utils/app_read_write_counter.html)
ChromeCacheView|[2.45](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/ChromeCacheView)|[2.51](https://www.nirsoft.net/utils/chrome_cache_view.html)
DNSLookupView|[1.12](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/DNSLookupView)|[1.15](https://www.nirsoft.net/utils/dns_lookup_view.html)
HashMyFiles|[2.44](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/HashMyFiles)|[2.50](https://www.nirsoft.net/utils/hash_my_files.html)
InsideClipboard|[1.25](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/InsideClipboard)|[1.27](https://www.nirsoft.net/utils/inside_clipboard.html)
InstalledDriversList|[1.05](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/InstalledDriversList)|[1.06](https://www.nirsoft.net/utils/installed_drivers_list.html)
InsttaledPackagesView|[1.05](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/InstalledPackagesView)|[1.10](https://www.nirsoft.net/utils/installed_packages_view.html)
NK2Edit|[3.45](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/NK2Edit)|[3.46](https://www.nirsoft.net/utils/outlook_nk2_edit.html)
NetworkOpenedFiles|[1.62](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/NetworkOpenedFiles)|[1.63](https://www.nirsoft.net/utils/network_opened_files.html)
NetworkUsageView|[1.31](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/NetworkUsageView)|[1.32](https://www.nirsoft.net/utils/network_usage_view.html)
SearchMyFiles|[3.30](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/SearchMyFiles)|[3.31](https://www.nirsoft.net/utils/search_my_files.html)
VideoCacheView|[3.09](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/VideoCacheView)|[3.10](https://www.nirsoft.net/utils/video_cache_view.html)
Volumouse|[2.10](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/Volumouse)|[2.15](https://www.nirsoft.net/utils/volumouse.html)
WifiInfoView|[2.93; 2.94](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/WifiInfoView)|[2.95](https://www.nirsoft.net/utils/wifi_information_view.html)
WirelessNetworkWatcher|[2.31](https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NirSoft/WirelessNetworkWatcher)|[2.41](https://www.nirsoft.net/utils/wireless_network_watcher.html)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Every pull request can only modify one version of manifest. It would be better splitting them into multiple issues.

**Comment by KarbitsCode** [comment]
> Every pull request can only modify one version of manifest. It would be better splitting them into multiple issues.

You can make multiple pull requests and link it to this one issue if you want 👍
