### ISSUE TITLE
[Update Request]: Microsoft.PowerToys bump to v0.87.0

### ISSUE THREAD

**Issue by rogeriopradoj** [microsoft/winget-pkgs#199578]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.PowerToys

### Package Version

v0.87.0

### Please describe the changes you would like to see

There is a new release (v0.87.0) available.
Download Page Url: https://github.com/microsoft/PowerToys/releases/tag/v0.87.0

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> It's currently in progress.
>
> - See #199172

**Comment by stephengillie** [comment]
> Note
> 
> It's currently in progress.
> 
> * See [New version: Microsoft.PowerToys version 0.87.0 #199172](https://github.com/microsoft/winget-pkgs/pull/199172)
