### ISSUE TITLE
Support hardware requirements.

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#199504]
# Custom Hardware Dependencies

> [!NOTE]
> The WinGet Community repository imposes requirements in the form of policies for automated validation. In the event we're unable to install the software, we're not able to validate the installers meet our requirements. Those requirements include the ability to have an unattended installation and that there are no other detections preventing us from approving the package for the community repository.

Some packages require custom hardware.

* https://github.com/microsoft/winget-pkgs/pull/19373
* https://github.com/microsoft/winget-pkgs/pull/25913

# Proposed technical implementation details (optional)

Extend schema and perform validations for hardware requirements.

> [!IMPORTANT]
> WinGet is capable of installing packages with hardware requirements from either a local manifest or a private repository given the required hardware is present. If there are additional requirements identified by ISVs with specific needs in WinGet, we will consider those requests.

**Comment by denelon** [comment]
At this time, we are not likely to look at purchasing custom hardware for the validation infrastructure. I'm closing this issue as "Not Planned", and as the Hardware label is added to PRs, they should still link to this issue.

**Comment by stek29** [comment]
@denelon so would such PRs be merged now, or would winget-pkgs not accept anything depending on specific hardware for now?
