### ISSUE TITLE
[Package Issue]: Update of Martchus.syncthingtray winget package fail (Uninstallation program failed with exit code: 0x8a150003)

### ISSUE THREAD

**Issue by LbqpdL** [microsoft/winget-pkgs#199789]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Hello,
I installed syncthingtray from winget repository, through the uniget-UI interface:
![Image](https://github.com/user-attachments/assets/df65b941-6c02-4701-8a09-b3a754ac3f04)

The update failed with the following error:

    Starting package update operation for package id=Martchus.syncthingtray with Manager name=Winget
    Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
    Process Executable : C:\Users\username\AppData\Local\Microsoft\WindowsApps\winget.exe
    Process Call Arguments : update --id "Martchus.syncthingtray" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
    Working Directory : C:\Users\username
    Process Start Time : 12/12/2024 17:53:13

    Trouvé Syncthing Tray [Martchus.syncthingtray] Version 1.6.4
    La licence d’utilisation de cette application vous est octroyée par son propriétaire.
    Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
    Le code de hachage de l’installation a été vérifié avec succès
    Extraction des archives...
    Extraction de l’archive réussie
    Début de la désinstallation du paquet...
    Une erreur inattendue s'est produite lors de l'exécution de la commande :
    remove: Acc�s refus�.: "C:\Users\username\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.3-x86_64-w64-mingw32.exe"
    Échec du programme de désinstallation avec le code de sortie : 0x8a150003 : Échec de l’exécution de la commande
    Process Exit Code : -1978335145

Note : I was not asked for admin privileges

OS: Windows 11 Pro
![Image](https://github.com/user-attachments/assets/b1ecf174-4b9e-470d-a9d4-b7c4b0511c8e)

Syncthing installed alongside with syncthingtray
![Image](https://github.com/user-attachments/assets/ac7b0048-6b43-4acc-ac38-6900fed5759e)

Log from upgrade attempted in command-line

`PS C:\Users\UserName> winget upgrade syncthingtray Trouvé Syncthing Tray [Martchus.syncthingtray] Version 1.6.4 La licence d’utilisation de cette application vous est octroyée par son propriétaire. Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci. Le code de hachage de l’installation a été vérifié avec succès Extraction des archives... Extraction de l’archive réussie Début de la désinstallation du paquet... Une erreur inattendue s'est produite lors de l'exécution de la commande : remove: Acc�s refus�.: "C:\Users\UserName\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.3-x86_64-w64-mingw32.exe" Échec du programme de désinstallation avec le code de sortie : 0x8a150003 : Échec de l’exécution de la commande`

Translated to english:

> PS C:\Users\UserName> winget upgrade syncthingtray
> Found Syncthing Tray [Martchus.syncthingtray] Version 1.6.4
> You are granted the license to use this application by its owner.
> Microsoft is not responsible for third-party packages and does not grant licenses for them.
> The installation hash has been successfully verified
> Extracting archive...
> Archive extraction successful
> Starting package uninstallation...
> An unexpected error occurred while executing the command:
> remove: Access denied: "C:\Users\UserName\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.3-x86_64-w64-mingw32.exe"
> Uninstallation program failed with exit code: 0x8a150003: Command execution failed

**Work-around:**
Quitting the running process before the install solves the issue

**Other tickets created in relation to this bug (all closed as deemed not related to the bug / not opened within the correct bug-tracker repo):**
https://github.com/Martchus/syncthingtray/issues/303
https://github.com/marticliment/UniGetUI/issues/3069

**Note from the developper on a possible update of the winget package:**
Note that Syncthing Tray can be started with --replace which might be something the winget packager could utilize. So you could ask for that on the issue tracker of that package. (This would be a feature request about the concrete winget package and not about Syncthing Tray and UniGetUI.)

### Steps to reproduce

Install package
Launch application
Attempt update of package while the application is running

### Actual behavior

Update fails
Update with admin rights fails (provided as an option in Uniget-UI interface)
Option to "deinstall and update" (provided in Uniget-UI interface) also fails

### Expected behavior

Expected behaviour would be the update to work without error

### Environment

```raw
PS C:\Users\Username> winget --info
Gestionnaire de package Windows v1.9.25200
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.26100.2605
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.24.25200.0

Répertoires Winget
-----------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  %USERPROFILE%\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Désactivé
LocalArchiveMalwareScanOverride           Désactivé
ProxyCommandLineOptions                   Désactivé
DefaultProxy                              Désactivé
```

**Comment by Dragon1573** [comment]
While you upgrading the package, are you still running the application?

This package seems contains `UpgradeBehavior: uninstallPrevious`. You should quit the application completely, then perform an upgrade.

-----

I'm currently using `AList.AList` as a local server, also I use `nssm` to register _Alist_ as a Windows Service. While upgrading, I HAVE TO stop the service before invoking an `winget upgrade`.
