### ISSUE TITLE
[Package Request]: Cisco Webex App and desktop meetings bundle

### ISSUE THREAD

**Issue by ChristianOe** [microsoft/winget-pkgs#199788]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://help.webex.com/en-us/article/nw5p67g/Webex-App-%7C-Installation-and-automatic-upgrade
Publisher: Cisco Systems, Inc
Package Name: Cisco.Webex.Bundle
Description: Cisco Webex is an app for continuous teamwork. Move work forward in secure work spaces where everyone can contribute anytime with messaging, file sharing, white boarding, video meetings, calling, and more. It works on virtually any device, with these top benefits for mobile app users:
  - Streamline Teamwork: One place for all the tools that help you do your job better and faster. Create spaces for you and another person or for a group working on a project.
  - Make Better Decisions: Start and join meetings instantly. See everyone with an amazing HD video experience. Share your screen. Keep teamwork going in the connected work space.
  - Stay Informed About All Your Work: Select from our growing catalog of integrations and bots to keep up to date with what's happening in other apps such as Box and Salesforce
  - Find Anything Fast: Search for people, messages, and files across all your spaces - no need to switch accounts or views
  - Bring The Experience Into Meeting Rooms: Pair your app to a Webex device, such as the Webex Board, to do things like wirelessly control meetings and save whiteboard drawings
  - Work Securely: Built for business collaboration with end-to-end encryption
Package Version: 44.12.0.31404
Installer Url: https://binaries.webex.com/Webex-Desktop-Windows-x64-Combined-Gold/WebexBundle.msi

**Comment by ChristianOe** [comment]
This is the bundle package. It is needed for isolated environements. Review the info from Cisco:

Bundle package: This package installs both Webex App and the desktop meetings app. Only use the bundle package in the following situations:

You’re installing in a secure environment that blocks the users' computers from downloading software. If Webex App can't download meetings components, people may have usability problems joining meetings with the app.
You haven’t yet fully migrated to Webex App and your users still need the separate desktopMeetings app.

**Comment by spectopo** [comment]
Does the bundle contain both `Cisco.CiscoWebexMeetings` and `Cisco.Webex`?

If so, you can install them separately:)

**Comment by SpecterShell** [comment]
Does the bundle contain both `Cisco.CiscoWebexMeetings` and `Cisco.Webex`?

If so, you can install them separately:)

**Comment by Dragon1573** [comment]
> Does the bundle contain both `Cisco.CiscoWebexMeetings` and `Cisco.Webex`?
> 
> If so, you can install them separately:)

> Bundle package: This package installs both Webex App and the desktop meetings app. Only use the bundle package in the following situations:
> 
> You’re installing in a secure environment that blocks the users' computers from downloading software. If Webex App can't download meetings components, people may have usability problems joining meetings with the app. You haven’t yet fully migrated to Webex App and your users still need the separate desktopMeetings app.

@ChristianOe, I think what **SpecterShell** means is, you can successfully download and install `Cisco.Webex.Bundle`, then you definitely can download `Cisco.Webex` and `Cisco.CiscoWebexMeetings` seperately. There should be no blocking internet connection on your device.

As it's instructed, `Cisco.Webex.Bundle` can be installed in an isolated environment, so there's no internet connection on that device, so it can't be downloaded via `winget.exe`, so submitting this package to the repository is useless.

-----

@SpecterShell Is that correct? 🙏🏼

**Comment by ChristianOe** [comment]
@SpecterShell, @Dragon1573: I don't think the issue is as simple as you might think. The bundle package also supports older Webex installations. So if you were to install the Webex and Webex Meetings packages separately, you would only have support for the latest server versions. If Webex detects an older version, it would download the required components. The bundle package has already integrated these components to provide optimal support. Thats why I like to have this version to support self hostet non last updated meetings. Otherwise Cisco would not offer this version separately.

**Comment by ChristianOe** [comment]
Isolated means that the MSI installer via winget is allowed, but not the reloading of components. I would like to have control over this.
