### ISSUE TITLE
[Update Request]: Splunk Universalforwarder

### ISSUE THREAD

**Issue by ChristianOe** [microsoft/winget-pkgs#199749]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Splunk.UniversalForwarder

### Package Version

9.4.0

### Please describe the changes you would like to see

Download URL: https://download.splunk.com/products/universalforwarder/releases/9.4.0/windows/splunkforwarder-9.4.0-6b4ebe426ca6-windows-x64.msi
SHA512: https://download.splunk.com/products/universalforwarder/releases/9.4.0/windows/splunkforwarder-9.4.0-6b4ebe426ca6-windows-x64.msi.sha512

**Comment by DuckDuckStudio** [comment]
Is there an installer for x86 architecture for this version?

**Comment by ChristianOe** [comment]
Yes.
https://download.splunk.com/products/universalforwarder/releases/9.4.0/windows/splunkforwarder-9.4.0-251651b291fe-windows-x86.msi

SHA512: https://download.splunk.com/products/universalforwarder/releases/9.4.0/windows/splunkforwarder-9.4.0-251651b291fe-windows-x86.msi.sha512
