### ISSUE TITLE
[Update Request]: f3d-app.f3d 2.5.1

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#199889]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

f3d-app.f3d

### Package Version

2.5.1

### Please describe the changes you would like to see

https://github.com/f3d-app/f3d/releases/tag/v2.5.1

**Comment by DuckDuckStudio** [comment]
The author does not provide an installer for this version.
<img src="https://github.com/user-attachments/assets/98b72341-e577-4a06-aef6-ee2a2e1f6cfb">
<img src="https://github.com/user-attachments/assets/f273d7a7-9369-4332-bed5-08d62246f23e">

<details>
<summary>原文</summary>
  作者没有为此版本提供安装程序。
  <img src="https://github.com/user-attachments/assets/98b72341-e577-4a06-aef6-ee2a2e1f6cfb">
  <img src="https://github.com/user-attachments/assets/f273d7a7-9369-4332-bed5-08d62246f23e">
</details>

**Comment by luzpaz** [comment]
Sorry, I missed that caveat.
