### ISSUE TITLE
[Package Request]: GDAL

### ISSUE THREAD

**Issue by Nnnes** [microsoft/winget-pkgs#199877]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.gisinternals.com/release.php (current version, all compilers/architectures) / https://www.gisinternals.com/query2.html?content=filelist&file=release-1930-x64-gdal-3-10-0-mapserver-8-2-2.zip (all installers for current GDAL core and plugins, built by most recent compiler for 64-bit architecture - despite the `.zip` this is a webpage)
Publisher: GISInternals
Package Name: GISInternals.GDAL
Description *(via https://gdal.org)*: GDAL is a translator library for raster and vector geospatial data formats that is released under an MIT style Open Source License by the Open Source Geospatial Foundation.
Package Version: 3.10.0
Installer Url: https://build2.gisinternals.com/sdk/downloads/release-1930-x64-gdal-3-10-0-mapserver-8-2-2/gdal-3.10.0-1930-x64-core.msi

Notes:
* Some more information about the builds can be found here: https://www.gisinternals.com/packageinfo.php?file=release-1930-x64-gdal-3-10-0-mapserver-8-2-2.zip
* GDAL (https://gdal.org, https://github.com/OSGeo/gdal) is not developed by GISInternals; rather, GISInternals is a project run by Tamas Szekeres (who also contributes to GDAL development) that provides nightly and release Windows builds of GDAL, similar to what Shining Light Productions does for OpenSSL. GISInternals is linked to by the official GDAL documentation [here](https://gdal.org/en/stable/download.html#windows).
* The installed programs do not work properly unless the `PATH` environment variable includes `C:\Program Files\GDAL` and the value of the `GDAL_DRIVER_PATH` environment variable is set to `C:\Program Files\GDAL\gdalplugins`. As far as I know, the installer does not provide a way set either of these automatically. Can WinGet do this or warn users that they should do this?
* The GISInternals.GDAL package should only include the core installer, `gdal-...-core.msi`. I would also be happy to see separate WinGet packages for each of the plugin installers `gdal-...-ecw-55.msi`, `gdal-...-filegdb.msi`, `gdal-...-mrsid.msi`, and `gdal-...-oracle.msi`; however, these are separate installers because of proprietary licensing. As stated [here](https://www.gisinternals.com/release.php):
  > Some external libraries which can be optionally used by GDAL and MapServer (provided as plugins) are under radically different licenses, you MUST obtain valid licenses for each of these dependent libraries.

  These licenses are not necessarily hard to find, but they are distinct from the GDAL and GISInternal licenses. I can create separate issues for each plugin and try to track down their respective licenses if that would help.
* The MapServer files are not required by GDAL and should be ignored for the purposes of this package. The Python bindings can also be ignored; I do not know much about them, but it seems to me that Python users on Windows would be more likely to install and use GDAL via OSGeo4W or Conda, not GISInternals.

**Comment by stephengillie** [comment]
> Can WinGet [add these paths to the PATH variable] this or warn users that they should do this?

Unfortunately, the package manager doesn't currently have this capability, to my knowledge.

**Comment by Nnnes** [comment]
Pull requests:
GISInternals.GDAL.ECW #204314
GISInternals.GDAL.FileGDB #204315
GISInternals.GDAL.MrSID #204316
GISInternals.GDAL.Oracle #204317
