### ISSUE TITLE
[Update Request]: Add paint.NET version 5.1.2

### ISSUE THREAD

**Issue by RubberDuckShobe** [microsoft/winget-pkgs#199938]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

dotPDN.PaintDotNet

### Package Version

5.1.2

### Please describe the changes you would like to see

The new version is available on GitHub at: https://github.com/paintdotnet/release/releases/tag/v5.1.2

**Comment by DuckDuckStudio** [comment]
- #199909
But I'm not sure if this pull request is correct...
