### ISSUE TITLE
[Update Request]: Update dependencies for DuongDieuPhap.ImageGlass

### ISSUE THREAD

**Issue by slowthgt** [microsoft/winget-pkgs#199949]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

DuongDieuPhap.ImageGlass

### Package Version

9.2.0.1208

### Please describe the changes you would like to see

As per the release notes for 9.2.0.1208 (https://github.com/d2phap/ImageGlass/releases/tag/9.2.0.1208), WebView2 Runtime is now optional, but the manifest still enforces it.

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/pull/199952#discussion_r1894123729
