### ISSUE TITLE
[Update Request]: mmozeiko.wcap

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#200009]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

mmozeiko.wcap

### Package Version

/

### Please describe the changes you would like to see

Repo: https://github.com/mmozeiko/wcap/
The existing installer link returns 404 and needs to be updated.
I'm not sure what the exact version number is.

**Comment by Dragon1573** [comment]
According to [GitHub Copilot](https://github.com/copilot), it seems the application version number is extracted by date (current latest `2024.10.18`), as shown in [`CHANGELOG.md`](https://github.com/mmozeiko/wcap/blob/main/CHANGELOG.md#20241018).

Thank you copilot ❤
