### ISSUE TITLE
Darktable package reports a 404, and is not latest stable

### ISSUE THREAD

**Issue by adamskt** [microsoft/winget-pkgs#20033]
# Brief description of your issue
Darktable package gets a 404 error when downloading the installer.

# Steps to reproduce
`PS> winget install darktable`

# Expected behavior
Package launches installer and installs

# Actual behavior
```
PS> winget install darktable
Found darktable [darktable.darktable]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0-win64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

# Environment

```none
[winget --info]
Windows Package Manager version
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: 10.0.19043.0
Package: darktable.darktable v3.6.0
```

The latest stable release on https://www.darktable.org/install/#windows points to an installer package at https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0.1-win64.exe so maybe they un-tagged the 3.6.0 release?

**Comment by ImJoakim** [comment]
#20035 removed the incorrect download url. I'll make a new PR to add version 3.6.0 with the new download url.
