### ISSUE TITLE
Package Request: Ninja build

### ISSUE THREAD

**Issue by gocarlos** [microsoft/winget-pkgs#2004]
# Package Requested
Manifest: Ninja is a small build system with a focus on speed.

Link: https://ninja-build.org/

**Comment by izep** [comment]
#174

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by kusma** [comment]
I second this request. For [Mesa3D](https://mesa3d.org), we're currently using [Chocolatey](https://chocolatey.org/) on [CI](https://gitlab.freedesktop.org/mesa/mesa/-/blob/c05e48308b432f93785520f48fbddc813040b11d/.gitlab-ci/windows/mesa_deps.ps1#L24) to bootstrap a build-environment. And Chocolatey packages [ninja](https://community.chocolatey.org/packages/ninja). In the long run, it would be nice if we could move to WinGet, so we don't have to download and install Chocolatey as well.

**Comment by IGR2014** [comment]
Ninja build is definitely a great build system which provides great multithreaded build and visually satisfying output. So we need this package for windows - that's :100: useful.

+1  for adding this package

**Comment by seppeon** [comment]
Also echoing the request for ninja build. Its an excellent build-system, lets get it in winget!

**Comment by denelon** [comment]
We're currently working on support for portable / standalone .exe programs with:
* microsoft/winget-cli/issues/182

Next, we will work on support for .zip files:

* microsoft/winget-cli/issues/140

**Comment by IGR2014** [comment]
Any updates on this issue?

**Comment by denelon** [comment]
* microsoft/winget-cli/issues/140

is in progress. Check [releases notes](https://github.com/microsoft/winget-cli/releases/tag/v1.4.2161-preview) for status.

**Comment by mastercoms** [comment]
Seems like it was solved, can Ninja now be added?

**Comment by mdanish-kh** [comment]
> Seems like it was solved, can Ninja now be added?

https://github.com/microsoft/winget-pkgs/issues/80892#issuecomment-1260057099

**Comment by IGR2014** [comment]
Seems like they are waiting for this: https://github.com/microsoft/winget-cli-restsource/issues/116
