### ISSUE TITLE
[Update Request]: vatis-project.vAtis version 4.1.0-beta.1

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#200510]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

vatis-project.vAtis

### Package Version

4.1.0-beta.1

### Please describe the changes you would like to see

~~昨天还好好的怎么今天连仓库都没了...~~  
I found a new version of this package at https://vatis.app/ This package should be updated from version 4.0.0 to 4.1.0.

```[tasklist]
### Pull request for removal of version 4.0.0 of this package
- [ ] #200517
- [ ] #200026
- [ ] #200518
- [ ] #200520 
- [ ] #200521 
- [ ] #200522 
- [ ] #200524 
- [ ] #200525 
- [ ] #200526 
- [ ] #200527 
- [ ] #200528 
- [ ] #200530 
- [ ] #200531 
- [ ] #200532 
```

**Comment by Dragon1573** [comment]
- Installer file URL: <https://hub.vatis.app/download/windows>

> [!WARNING]
>
> This is a **vanity URL** which always points to the latest version. Might facing problem in the future while a newer version is released.
