### ISSUE TITLE
[Update Request]: CiderCollective.Cider version 2.6.0

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#201289]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

CiderCollective.Cider

### Package Version

2.6.0

### Please describe the changes you would like to see

Version 1.x of this package has been deprecated and will need to be updated to version 2.x.
Version 2.x: https://cider.sh/downloads/client
Version 1.x: https://github.com/ciderapp/Cider?tab=readme-ov-file#cider-1

> [!WARNING]
> This appears to be a package that requires a paid download.

**Comment by Dragon1573** [comment]
Latest version of this package is available at [**Microsoft Store**](https://apps.microsoft.com/detail/9PL8WPH0QK9M?hl=neutral) with identifier `9PL8WPH0QK9M`. But it's a paid-required package and might not be able to search by `winget.exe`

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> The package is ONLY available to those who sponsored over **$3.49 USD**. This request might be closed as "not planned". 😞
>
> ![Image](https://github.com/user-attachments/assets/ba8a87c0-9621-4f97-9463-dcccb8d17d37)
