### ISSUE TITLE
[Update Request]: LDraw.AIOI.2023 version 2024-01 v1

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#201287]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

LDraw.AIOI.2023/24

### Package Version

2024-01 v1

### Please describe the changes you would like to see

The existing installer link returns 404 and needs to be updated.
Maybe you can find installer at https://www.ldraw.org/article/104.html

I can't test the current version, it took more than 1 hour to install on my VM.
![Image](https://github.com/user-attachments/assets/efc2fc0a-7ac6-4a22-b175-2ad7349c2e33)

```[tasklist]
### Tasks
- [ ] #201319 
- [ ] #201285 
```

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> _Komac_ can't find package identifier `LDraw.AIOI.2023` in the repository, but [it DOES](https://github.com/microsoft/winget-pkgs/tree/master/manifests/l/LDraw/AIOI/2023) in there.
>
> ```text
> 18:18:40 ~\...\winget-pkgs  [master ≡] 1.508s 0x0001 pwsh> komac update -o ./ -v '2024.01.1' LDraw.AIOI.2023 `
> > -u http://cache.alist.local/d/LDraw_All-In-One-Installer_2024-01_setup_64Bit_v1.exe
> Error: 
>    0: LDraw.AIOI.2023 does not exist in microsoft/winget-pkgs
> ```

**Comment by DuckDuckStudio** [comment]
- Version numbers with spaces appear(出现、来) from here: https://github.com/microsoft/winget-pkgs/pull/109369#pullrequestreview-1473458827
