### ISSUE TITLE
[Update Request]: DBVis.DBVisualizer version 24.3.2

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#201697]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DBVis.DBVisualizer

### Package Version

24.3.2

### Please describe the changes you would like to see

All current versions of this package return 404 and need to be updated.
A new version of this package should be available here: https://www.dbvis.com/
Unfortunately, this domain Time Out to me(我这里访问超时了).

```[tasklist]
### Tasks
- [ ] #201695 
- [ ] #201722 
```

**Comment by Dragon1573** [comment]
Manually verified (with proxy enabled)👍🏼

```text
15:46:39 D:\...\winget-pkgs  [master ≡] 0ms pwsh> winget download -s winget --skip-dependencies -e DBVis.DBVisualizer
已找到 DbVisualizer [DBVis.DBVisualizer] 版本 24.2.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
已跳过依赖项。
正在下载 https://www.dbvis.com/product_download/dbvis-24.2/media/dbvis_windows-x64_24_2_jre.exe
执行此命令时发生意外错误： 
Download request status is not success.
0x80190194 : 未找到(404)。
```
