### ISSUE TITLE
[Update Request]: VirtualDJ

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#201757]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AtomixProductions.VirtualDJ

### Package Version

8.5.8472.0

### Please describe the changes you would like to see

https://www.virtualdj.com/download/
https://download.virtualdj.com/b8472/397CC2A2/install_virtualdj_2025_b8472_pc.msi

Previous version (got removed because of no longer valid download link):
https://github.com/microsoft/winget-pkgs/pull/160169/files

**Comment by Dragon1573** [comment]
> [!IMPORTANT]
> 
> The package identifier is entirely removed.
>
> - See #160169

**Comment by Dragon1573** [comment]
<details><summary>Installation logs</summary>

```text
--> Installing WinGet
--> Disabling safety warning when running installers
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
已启用管理员设置 'LocalManifestFiles'。
已启用管理员设置 'LocalArchiveMalwareScanOverride'。

--> Installing the Manifest 2025.8472

已找到 VirtualDJ [AtomixProductions.VirtualDJ] 版本 2025.8472
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 http://alist.dragon1573.local/d/install_virtualdj_2025_b8472_pc.msi
  ██████████████████████████████   462 MB /  462 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName    DisplayVersion Publisher          ProductCode                            Scope
-----------    -------------- ---------          -----------                            -----
VirtualDJ 2025 8.5.8472.0     Atomix Productions {931405C1-56B6-4EFE-9201-66CC766EC45D} Machine
```

</details>
<details><summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/7b7d0e11-1320-444f-b153-896d341e532f)
![Image](https://github.com/user-attachments/assets/5da570b0-1e7b-4cab-823a-72f38ea4958a)
![Image](https://github.com/user-attachments/assets/97dd166d-873e-4ccf-ac42-86b890c4cd44)

</details>
