### ISSUE TITLE
Package Tencent.QQ: uninstall the package doesn't delete all installed files.

### ISSUE THREAD

**Issue by cdytoby** [microsoft/winget-pkgs#20199]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Uninstall the package Tencent.QQ doesn't delete all installed files. 
Under "C:\Program Files (x86)\Tencent" this folder there are still many binaries and dlls inside.
Also "C:\Program Files (x86)\QQMailPlugin" this folder also exists.

# Steps to reproduce

(I'm using Windows Sandbox to test this, so the OS has almost nothing installed)
- install the package by executing "winget install Tencent.QQ"
- Launch the software by double clicking the icon on the desktop.
- Do not login, just close the software.
- Wait for the software to be properly closed, and uninstall it by using "winget uninstall Tencent.QQ"

# Expected behavior

All files installed should be removed, including everything inside "C:\Program Files (x86)\Tencent"
Because QQ is the only software gets installed in this process, I believe nothing should be inside that folder after deinstalling it.

# Actual behavior

The following folders are still there, inside there are many dlls and binaries.
- C:\Program Files (x86)\Tencent\QQ
- C:\Program Files (x86)\Tencent\Qzone
- C:\Program Files (x86)\Tencent\QzoneMusic
- C:\Program Files (x86)\QQMailPlugin

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1083
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software?
Tencent.QQ current version is 9.4.2.27655
```

**Comment by OfficialEsco** [comment]
Isn't this a issue with QQ's uninstaller?..
AFAIK `winget uninstall` just executes the uninstall command for the program.

Anyways
> Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

https://github.com/microsoft/winget-cli/issues

**Comment by cdytoby** [comment]
I see. So if you think this should not be taking care of here, you can close this issue.

Then I want to borrow this thread and ask: is there any method to prevent potential harmful software from submitting to winget? 

I'm aware that these packages submitted here will be available through the brand new Microsoft Store. And one thing I really like about the current Microsoft Store is: it only allows dev to submit app in specific format, and that includes win32 app wrapped into some kind of special format. While it may complicate things on devs side, it effectively prevented some of the harmful behaviours, like download unwanted additional adware or even malware. 

Now it seems pure exe or msi are allowed to be installed directly through winget, or in the future MS Store, which is not very different from downloading directly from official website. And I test QQ specifically, because while this software is widely used and is sometime useful, it's famous for adding adware/malware into user's computer without notifying user. There are even accusation that it's scanning people's harddrive and leak personal information (I can't confirm it). So I was really hoping that there are some kind of measurement, to remove or reset the software completely, or even better, install it in some kind of container and isolated from the rest of the system. Just like what iOS does.

Maybe I'm asking too much here? 

(I did find an alternative which really do this kind of job: Sandboxie)

**Comment by OfficialEsco** [comment]
> Then I want to borrow this thread and ask: is there any method to prevent potential harmful software from submitting to winget?

No, but it does run VirusTotal so it will block some.

> I'm aware that these packages submitted here will be available through the brand new Microsoft Store. And one thing I really like about the current Microsoft Store is: it only allows dev to submit app in specific format, and that includes win32 app wrapped into some kind of special format. While it may complicate things on devs side, it effectively prevented some of the harmful behaviours, like installing unwanted additional adware or even malware.

No, this is a different Platform, Microsoft is validation each and every Microsoft Store submission, the difference with Microsoft Store is the forced Appx installer which is a "newer" MSI/MSIX Installer which pretty much clears up all the junk when uninstalled.

> Now it seems pure exe or msi are allowed to be installed directly through winget, or in the future MS Store

The winget-cli team kinda wanted MSI/MSIx/Appx ONLY because its a Microsoft Installer which is a lot safer than executing executables, but there would be A LOT less packages so they allowed EXE's.

> which is not very different from downloading directly from official website.

That is one part of what a Package Manager does, its a direct download link to the official download url so you don't have to browse the internet for a safe website and potentially click a bad link. 

> And I test QQ specifically, because while this software is widely used and is sometime useful, it's famous for adding adware/malware into user's computer without notifying user. There are even accusation that it's scanning people's harddrive and leak personal information (I can't confirm it). So I was really hoping that there are some kind of measurement, to remove or reset the software completely

Well... That's your fault for using a Software from a untrustworthy developer, and its a Chinese(?) company so no wonder they add spyware/bloatware. 

> or even better, install it in some kind of container and isolated from the rest of the system. Just like what iOS does.

That is not the purpose of a Package Manager, iOS apps do basically the same the same as Microsoft Store apps, just on a way stricter scale.

> I see. So if you think this should not be taking care of here, you can close this issue.

I'm not a Maintainer so i can't, for any future related questions you should post it to https://github.com/microsoft/winget-cli/issues because they know a lot more about the backend.

**Comment by lychichem** [comment]
As a Chinese user, I can tell you that tencent's software rules the way we communicate with each other, so a software store will soon be deprecated by Chinese users if it does not have a set  of usable and updated tencent software, like qq and wechat. Just like what whatsapp to you. 
Ok, tencent did and may still scanning users even if developers from our country posts analysis of tencent software at many forums . And I also hate tencent but I have to use it.
So, I'm sad to say, at least in China or for Chinese users, we have to accept what tencent does, and let it shows in winget source. Maybe we can add a custom uninstall script, which will delete the remaining files after the Uninstaller runs. Or, we have to add modified version of tencent software, which certainly breaks the EULA of tencent. You know they are called "Guranteed winner at  Nanshan court"...

**Comment by oxygen-dioxide** [comment]
Maybe we can have a "sandboxed mode" in winget using sandboxie. In sandboxed mode, each package is installed in a separate sandboxie sandbox. All the file and registry entries produced by the package and its installer are limited inside the sandbox. When uninstalling a package, just delete its sandbox.

**Comment by oxygen-dioxide** [comment]
Maybe we can have a "sandboxed mode" in winget using sandboxie. In sandboxed mode, each package is installed in a separate sandboxie sandbox. All the file and registry entries produced by the package and its installer are limited inside the sandbox. When uninstalling a package, just delete its sandbox.

**Comment by oxygen-dioxide** [comment]
Besides, [electron-qq](https://github.com/Clansty/electron-qq) is a good replacement to the official client, if you think that your privacy is important.

**Comment by lychichem** [comment]
> Besides, [electron-qq](https://github.com/Clansty/electron-qq) is a good replacement to the official client, if you think that your privacy is important.

Remember, any other softwares that using tencent's API will eventually be blocked when it has enough users and get into tencent's eye. So I don't think it's a good idea. At least, Microsoft cannot reject tencent's request for removing electron-qq from winget official source.

**Comment by linghengqian** [comment]
I'm adamantly against hanging winget applications in a sandbox-like container.  This will expand the limitations of tools such as vscode, powertoys, etc. It is meaningless to expand the limitations for the special needs of a small number of applications.
