### ISSUE TITLE
RStudio Package Correction

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#20218]
# Description of the new feature/enhancement

RStudio should be renamed RStudio Desktop because they have two versions, RStudio Desktop and RStudio Server.
Even in RStudio Desktop, they have two editions, RStudio Desktop Open-Source and RStudio Desktop Pro.

# Proposed technical implementation details (optional)

Hence, to give a user more detailed information about the package, here is what I think should be correct :
- RStudio.RStudioDesktop.OpenSource
- RStudio.RStudioDesktop.Pro
- RStudio.RStudioServer.OpenSource
- RStudio.RStudioServer.Workbench
Fixes #20226

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Please tell.

**Comment by KaranKad** [comment]
Looks like RStudio Server is only available for linux so we only need to make different package for RStudio Desktop Pro version.

**Comment by vedantmgoyal2009** [comment]
Oh, yes! So it should be:
- RStudio.RStudioDesktop.OpenSource
- RStudio.RStudioDesktop.Pro

**Comment by vedantmgoyal2009** [comment]
@ImJoakim How do I do this? Pull Request Error occurs every time.

**Comment by KevinLaMS** [comment]
@vedantmgoyal2009 Removing issue-feature.  I think we can close this issue as I see you are working through the submission and app name change.

**Comment by vedantmgoyal2009** [comment]
Okay

**Comment by denelon** [comment]
@vedantmgoyal2009 once you are done with the changes, you can close the issue. It's also possible to mention this Issue in the original PR comments so you can see the linked PRs and their status here.

**Comment by vedantmgoyal2009** [comment]
I am done with changes but because I renamed all the versions of RStudio in one PR, it encountered `Pull-Request-Error`

**Comment by denelon** [comment]
@vedantmgoyal2009 we only support one manifest / rename per PR currently. You will need to submit them one change at a time. Git reports a rename as a delete and an add. We're working on how we can support multiples, but it becomes much more complex when we're dealing with a mass change.
