### ISSUE TITLE
Vim Package - Not added to path

### ISSUE THREAD

**Issue by jazzdelightsme** [microsoft/winget-pkgs#20227]
# Brief description of your issue

This is a dupe of #656, but that was closed and not re-opened despite subsequent "still a problem" feedback.

# Steps to reproduce

`winget install --id vim.vim --silent`

# Expected behavior

After installing, I expect to be able to type "gvim" then <kbd>Enter</kbd> in a command prompt, and then gvim launches.

# Actual behavior

"gvim" is not recognized as a command. This is because the installer did not update the `%PATH%` environment variable.

Closing the shell and starting a new shell does not help.

# Environment

```none
PS C:\Windows\system32> winget --info
Windows Package Manager v1.0.11591
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22406.1001
Package: Microsoft.DesktopAppInstaller v1.11.11591.0
```

**Comment by KevinLaMS** [comment]
Sorry about the inconvenience.  This is the following feature that is on the winget backlog.
https://github.com/microsoft/winget-cli/issues/549
Would you mind upvoting that feature and closing this one?

**Comment by jazzdelightsme** [comment]
Thanks Kevin.
