### ISSUE TITLE
Record previous validation build in PRs

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#20232]
# Description of the new feature/enhancement

I'd like to have a link to any previous builds for PRs. It can be hard to diagnose/troubleshoot when a change is pushed and a new build is triggered, or a PR is closed.

# Proposed technical implementation details (optional)

Add a comment with link to a build when one is triggered by a PR changing the submitted manifest or "/azp run" command.

**Comment by Trenly** [comment]
I think this already happens for new commits; I don't think it happens for re-runs though
![image](https://user-images.githubusercontent.com/12611259/142703080-b28aff88-3aee-4d20-8ff2-03982c041b97.png)

**Comment by denelon** [comment]
That's what this issue is for. I want to be able to link to the earlier run(s) so we can see what happened when something fails the first time and succeeds later.

**Comment by Trenly** [comment]
> That's what this issue is for. I want to be able to link to the earlier run(s) so we can see what happened when something fails the first time and succeeds later.

Right, but in the issue it says
> when a change is pushed

Do you mean a change being pushed to the pipelines, or to the PR? If its a change pushed to the PR, the latest build for each commit is recorded.

Maybe I’m just misunderstanding exactly what additional runs would be missing that aren’t already recorded

**Comment by denelon** [comment]
I updated the description to be a bit more clear.

When a subsequent push happens, the initial build is "lost" and a new build is triggered.

**Comment by Trenly** [comment]
> I updated the description to be a bit more clear.
> 
> When a subsequent push happens, the initial build is "lost" and a new build is triggered.

I disagree.

If you go to the checks tab and select a different commit, the checks from that build appear and the links to that build are included there

**Comment by denelon** [comment]
Wow! TIL about that feature.

Does it persist if we do `/azp run` when we initially get a failure on the same commit?

**Comment by Trenly** [comment]
That I don’t know; I’ll do some more digging

**Comment by Trenly** [comment]
You can see all builds for a PR in the pipeline search. 

See this example - 

https://dev.azure.com/ms/winget-pkgs/_build?definitionId=337&_a=summary&branchFilter=81171%2C81171

**Comment by Trenly** [comment]
@denelon Did the links above show what you were thinking of for this feature?

**Comment by denelon** [comment]
Yes, that's fantastic. I'll go ahead and close this issue. Thank you so much for following up here!
