### ISSUE TITLE
Logitech Gaming Software detection/versions

### ISSUE THREAD

**Issue by auanasgheps** [microsoft/winget-pkgs#20230]
# Brief description of your issue

Logitech Gaming Software has changed multiple times over time, becoming a different product.

I have installed **the latest** version supported by the hardware I use, which is 5.10.127. It's old, but the latest supported.

Winget detects there's an update to version 9.02.65. Albeit having the same name, it's an entirely piece of software.

Also I did not install this software via winget, but winget thinks it happened.

Running a `winget upgrade -all` would break compatibility with the hardware I use.

I have noticed this version is not in the repo, but I don't think it would make a difference.

# Steps to reproduce

- Manually install Logitech Gaming Software 5.10.127. Can be found `https://support.logi.com/hc/en-us/articles/360024703714--Downloads-Wireless-Gamepad-F710`.
- The app is detected as winget installed and proposes the update to 9.02.65.

# Expected behavior

Do not prompt the update, 

# Actual behavior

Winget picks up the app and wants to update it

# Environment

```none
[winget --info]
Windows Package Manager  v1.0.11692
Windows: Windows.Desktop  v10.0.19041.1052
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software?
```

**Comment by OfficialEsco** [comment]
As somewho who dislike Logitech i'm not up to date with the LGS software versions, what are the different major versions of LGS?

I see we only have LGS 9 in the repo with the PackageName `Logitech Gaming Software` which would match against any LGS version...

This is most likely Logitech's fault for updating a software and dropping support for older devices, we can probably work around this by doing `Logitech Gaming Software 5` and `Logitech Gaming Software 9` however as of now it will break the matching because we don't have wildcard support... (it only works for `Logitech Gaming Software 9 *` not `Logitech Gaming Software 9*`)

**Comment by KevinLaMS** [comment]
@auanasgheps I think your issue would be solved with a future planned feature.  Feature pinning.  
https://github.com/microsoft/winget-cli/issues/476

Can you take a look and close this and UPVote the feature?  thanks

**Comment by auanasgheps** [comment]
> As somewho who dislike Logitech i'm not up to date with the LGS software versions, what are the different major versions of LGS?

Simply put: the current/latest version 9 **does not support** some legacy hardware. That's expected, my joypad is 10 years old. This is not a rant against Logitech, but they have built a new software using the same name, which is causing this error.




> @auanasgheps I think your issue would be solved with a future planned feature. Feature pinning.
> [microsoft/winget-cli#476](https://github.com/microsoft/winget-cli/issues/476)
> 
> Can you take a look and close this and UPVote the feature? thanks

Yes, the PR you have linked satisfies my scenario and I upvoted it. 
Please let me know if I should keep this case open. Thanks

**Comment by denelon** [comment]
I'll close this one for you @auanasgheps. Thanks for reporting and upvoting!
