### ISSUE TITLE
Need Download Size in yaml

### ISSUE THREAD

**Issue by VivekRaja2000** [microsoft/winget-pkgs#2030]
Can you add download size attribute in YAML as this makes GUI applications to be work as store and some extra time of loading GUI can be reduced in slow bandwidth networks

**Comment by Atemu** [comment]
Perhaps this information could be scraped from the installer URLs at runtime using their content-length field.

**Comment by VivekRaja2000** [comment]
Before runtime if we know about the download size we can download if we have enough data. In India  some of us will have limited data per day like 1GB or 2GB. For them this feature will be useful and they can be sure when to download the software

**Comment by Atemu** [comment]
A request and response to get the content-length of a URL is a few kilobytes at most.
