### ISSUE TITLE
Add `New Package` and `New Version` label to PRs

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#20303]
# Description of the new feature/enhancement
Add `New Package` and `New Version` label to PRs depending if the Package already exist, also fix the `Metadata` label.
And maybe a `Documentation` label to PRs which is not inside the Manifest folder.

This is useful for when you go trough Manifests, if a PR is marked as `New Package` and you know its already added you can tag it as Duplicate, if its `New Version` you can quickly look trough the PR and see that its correct. (Many PR's also haven't been updated in a while so if you "correct" the PackageIdentifier it will fail)

This is useful for both Moderators and active Package Maintainers which is up to date and also help with PR validation.

# Proposed technical implementation details (optional)
if (PR creates folder) {
  Add label New Package
}
elseif (previous version exist) {
  [bam!](https://user-images.githubusercontent.com/15158490/125081274-1d9e6b80-e0c6-11eb-849f-4351bc467833.png) New Version label added
}
elseif (no hash change) {
  Metadata Label
}

👌

**Comment by denelon** [comment]
@OfficialEsco we will see if the bot will cooperate 😊. I think this is a great feature to add.
