### ISSUE TITLE
search & install for .NET Core is showing and installing preview instead of stable

### ISSUE THREAD

**Issue by hangrymuppet** [microsoft/winget-pkgs#2053]
# Brief description

I am trying to install or search for .NET Core Stable using the following commands,

- `winget install --id=Microsoft.dotnet --exact`
- `winget search Microsoft.dotnet`

# Expected behavior

Display or install dotnet core that corresponds to the latest version in this path,
https://github.com/microsoft/winget-pkgs/tree/master/manifests/Microsoft/dotnet

# Actual behavior

Shows or installs a preview version from the below path,
https://github.com/microsoft/winget-pkgs/tree/master/manifests/Microsoft/dotnetPreview

Multiple search examples shown below,

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget search .net
Name              Id                         Version                    Matched
---------------------------------------------------------------------------------
LINQPad           LINQPad.LINQPad            6.8                        Tag: .net
Netron            LutzRoeder.Netron          4.3.3
mpv.net           stax76.mpv.net             5.4.8.0
.NET Core         Microsoft.dotnet           5.0.100-preview.4
.Net Framework    Microsoft.dotNetFramework  4.8
.NET Core Preview Microsoft.dotnetPreview    5.0.100-preview.5.20279.10
Stride            Stride.Stride              4.0.1.0                    Tag: .NET
Unity Hub         UnityTechnologies.UnityHub 2.3.2.0                    Tag: .NET
```

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget search dotnet
Name              Id                         Version                    Matched
---------------------------------------------------------------------------------------
.NET Core         Microsoft.dotnet           5.0.100-preview.4          Moniker: dotnet
.NET Core Preview Microsoft.dotnetPreview    5.0.100-preview.5.20279.10 Command: dotnet
.Net Framework    Microsoft.dotNetFramework  4.8                        Tag: dotnet
reko              uxmal.reko                 0.9.1.0                    Tag: dotnet
Stride            Stride.Stride              4.0.1.0                    Tag: dotnet
Unity Hub         UnityTechnologies.UnityHub 2.3.2.0                    Tag: dotnet
```

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget search Microsoft.dotnet
Name              Id                        Version
----------------------------------------------------------------------
.NET Core         Microsoft.dotnet          5.0.100-preview.4
.Net Framework    Microsoft.dotNetFramework 4.8
.NET Core Preview Microsoft.dotnetPreview   5.0.100-preview.5.20279.10
```

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget search --id=Microsoft.dotnet
Name              Id                        Version
----------------------------------------------------------------------
.NET Core         Microsoft.dotnet          5.0.100-preview.4
.Net Framework    Microsoft.dotNetFramework 4.8
.NET Core Preview Microsoft.dotnetPreview   5.0.100-preview.5.20279.10
```

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget search --id=Microsoft.dotnet --exact
Name      Id               Version
--------------------------------------------
.NET Core Microsoft.dotnet 5.0.100-preview.4
```

# Environment

```none
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\win-boo> winget --info
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.20150.1000
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by denelon** [comment]
The manifests were removed from the repository, but they didn't correctly get removed from the source.

**Comment by peter-dolkens** [comment]
@denelon - this is a good edge-case to consider while you're working on the overall manifest approvals process.

This should behave similar to nuget, where we can have a manifest removed from search/defaults, but if we explicitly request a version, it should remain available for anyone who developed a prior dependency on that version.

Perhaps we can add a flag to the manifest to indicate it should be hidden from the source, instead of removing them from the source via PRs entirely.

**Comment by denelon** [comment]
@peter-dolkens We have been looking at the options for retaining manifests. One of the challenges we've been facing is whether or not the original binary is available. In some cases, the distribution of packages is restricted (at least for some commercial packages). One of the thoughts is putting additional meta-data in a manifest to indicate that the binary has been removed, or possibly a reason it's no longer supported.

**Comment by denelon** [comment]
This appears to be resolved now.
```
PS C:\Users\denelon> winget search Microsoft.dotnet
Name              Id                        Version
----------------------------------------------------------------------
.NET Core         Microsoft.dotnet          3.1.301
.NET Core Preview Microsoft.dotnetPreview   5.0.100-preview.5.20279.10
.Net Framework    Microsoft.dotNetFramework 4.8
```

We had an issue where the CDN wasn't getting purged under a rebuild scenario. Issue #2274 seems to capture that one.

**Comment by peter-dolkens** [comment]
> @peter-dolkens We have been looking at the options for retaining manifests. One of the challenges we've been facing is whether or not the original binary is available. In some cases, the distribution of packages is restricted (at least for some commercial packages). One of the thoughts is putting additional meta-data in a manifest to indicate that the binary has been removed, or possibly a reason it's no longer supported.

Another issue is binaries that change over time.

Instead of metadata - perhaps an indexing service which removes manifests with expired links would be in order. Once a month, it could validate the hash of the listed download as part of a scheduled build.
