### ISSUE TITLE
Azure Pipelines are failing

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#20717]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

## Brief description of your issue
#20708 #20709 #20710 #20711 #20712 #20715 #20703 #20705 #20701 #20719
These PRs are successfully validated and installed on a local computer but failing on Azure Pipelines.

## Steps to reproduce
Not Applicable.

## Expected behavior
Pipelines should run successfully.

## Actual behavior
Pipelines are failing without giving any errors or warnings.

## Environment
Azure 

## Reason to create this issue
I have many commits to push but because all will get flagged by ```Internal-Error```, I am not pushing them.

**Comment by denelon** [comment]
@vedantmgoyal2009 this appears to have been a transient issue related to some of the infrastructure we depend on. Our retry logic did re-trigger builds, and many of the PRs succeeded. It looks like one of them failed with "Validation-Executable-Error" and was assigned to someone for investigation.

**Comment by vedantmgoyal2009** [comment]
Thanks. Now, I am closing this issue as it has been resolved.
