### ISSUE TITLE
Telegram Desktop alternate location issues

### ISSUE THREAD

**Issue by MuffinSmith** [microsoft/winget-pkgs#20798]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
I'm a sysadmin attempting to install telegram desktop through winget for my users.

Attempting to set an alternate location via --location does not work and setting --override "/VERYSILENT /NORESTART /DIR='C:\Program Files\Telegram Desktop'" returns with an error message saying "Folder names cannot include any of the following characters: / : * ? " < > |"

# Steps to reproduce

Winget install --id Telegram.TelegramDesktop --override "/VERYSILENT /NORESTART /DIR='C:\Program Files\Telegram Desktop'"

# Expected behavior

Telegram is installed to the system program files folder and updated by winget

# Actual behavior

Windows popup error message saying it cannot make a folder with special characters

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11692
Windows: Windows.Desktop version v10.0.19041.1083
Package: Microsoft.DesktopAppInstaller version v1.12.11692.0


```

**Comment by Trenly** [comment]
This seemed to work for me:
`Winget install --id Telegram.TelegramDesktop --override "/VERYSILENT /NORESTART /DIR=\"C:\Program Files\Telegram Desktop\""`

**Comment by MuffinSmith** [comment]
strange, I must have been doing something wrong the first time because you're right `--location` does work with `"${env:ProgramFiles}\Telegram Desktop"`
Thanks for lookin, and for the other escape char
