### ISSUE TITLE
Unsupported Package Name Format for multiple versions

### ISSUE THREAD

**Issue by mubaidr** [microsoft/winget-pkgs#2079]
# Description of the new feature/enhancement

As of now there are two packes publlished for PowerShell, as following: 

```bash
PowerShell         Microsoft.PowerShell         7.0.2
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
```

But trying to install Powershell using: `winget install Powershell` results in: 
```bash
Multiple apps found matching input criteria. Please refine the input.
Name                     Id                               Version         Matched
-----------------------------------------------------------------------------------------
PowerShell               Microsoft.PowerShell             7.0.2
Windows Terminal Preview Microsoft.WindowsTerminalPreview 1.1.1671.0      Tag: PowerShell
PowerShell-Preview       Microsoft.PowerShell-Preview     7.1.0-preview.3
Windows Terminal         Microsoft.WindowsTerminal        1.0.1401.0      Tag: powershell
```

and when trying to install using `winget install Microsoft.PowerShell`: 

```bash
Multiple apps found matching input criteria. Please refine the input.
Name               Id                           Version
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.0.2
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
```

So its impossible for now to install PowerShell suing `winget`. 

# Proposed technical implementation details (optional)

- Packages should be published by proper naming scheme (as `windows terminal` vs `WindowsTerminalPreview`) 
Or
- There should be a flag to force exact name match. 

Version information: 
- Windows 10 19640 build
- Windows Package Manager v0.1.41331 Preview

**Comment by OfficialEsco** [comment]
Can you install Windows Terminal? If so we need to hunt down - characters
You can install Powershell by typing winget install Microsoft.Powershell -e

**Comment by mubaidr** [comment]
Yes, I can.

I will test -e flag. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
