### ISSUE TITLE
URL in Troubleshoot.md results in a 404 Page

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#20948]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Clicking on the manifest documentation link in [Troubleshoot.md](/microsoft/winget-pkgs/blob/master/Troubleshoot.md) results in a page which is not found
# Steps to reproduce
Click on the aforementioned link

# Expected behavior
The link will take you to a valid manifest specification

# Actual behavior
The link results in a 404 page

# Environment
N/A

-----
I will submit a PR to resolve this issue

**Comment by denelon** [comment]
@Trenly thanks so much for filing issues on documentation, and even more thanks for submitting a PR 😊.
