### ISSUE TITLE
Changes to validation merge

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#21008]
# Description of the new feature/enhancement

Moderators will not need to wait for "Validation-Completed" to approve a PR and have the manifest merged by the bot. 

# Proposed technical implementation details (optional)

Moderators may approve a PR before validation has completed. If validation passes, the manifest will be merged.

I'm mentioning the moderators below so they are aware of the upcoming change.

@ItzLevvie
@jedieaston
@OfficialEsco

**Comment by jedieaston** [comment]
I think this should be reopened, it isn't happening as explained. I approved #22061 before it completed validation, then @wingetbot completed the validation but msftbot didn't add the Moderator-Approved tag.

**Comment by denelon** [comment]
@jedieaston, thanks for letting us know. I've reopened this Issue so we can dig a bit deeper into what happened. The bot has been having some performance issues recently, so I would also like to make sure we rule that out.

**Comment by vedantmgoyal2009** [comment]
What I think is that only these few changes are only needed.
- Modify _msftbot_ such that it adds "Moderator-Approved" immediately once the moderators approve the changes.
- _wingetbot_ should do nothing but add "Azure-Pipeline-Passed" and "Validation-Completed" labels together.
- _msftbot_ should attempt to merge the PR once all 3 labels are present on a PR.

Well, these are just my thoughts. I being a kid do not know how things work at the backend. If I am wrong, please forgive me.

**Comment by vedantmgoyal2009** [comment]
@denelon @jedieastion I guess it has been resolved now.

**Comment by jedieaston** [comment]
Yep. This can be closed!
