### ISSUE TITLE
YAMLCreate.ps1 Enhancement

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#21051]
## Description of the new feature/enhancement
- Add an option to directly enter SHA-256 checksum
- Set Default locale to en-US 

## Proposed technical implementation details (optional)
I would like others to implement the features.

**Comment by OfficialEsco** [comment]
What
> Added an option to directly enter SHA-256 checksum

Why? It fetches the SHA256 from the url you input.
The SHA256 is useless without the other info.

> Default locale to en-US

The default locale is en-US, when it prompts for locale its asking for installer locale, which for example Chinese software often are not.

**Comment by vedantmgoyal2009** [comment]
> **Add** an option to directly enter SHA-256 checksum 

Sorry for the mistake.

Because some websites (e.g. JetBrains) already provide SHA-256 checksum to verify the download. So, it is better to give an option to input file checksum manually as it will save the network of the person who is submitting the manifest. He would simply copy-paste the hash from the website instead of downloading the file and then calculating the hash. 

And, in locale, the default value should be made en-US, thereby still giving to enter it manually, as in the case of `Scope`.
![image](https://user-images.githubusercontent.com/83997633/125885171-8c4bc92f-9f1b-4f20-bff2-babf3a1f6aa7.png)
Like this: 
![image](https://user-images.githubusercontent.com/83997633/125885649-c54e6c05-2030-419e-bbda-6e4039543d0d.png)

**Comment by Trenly** [comment]
> [ . . . ]
> And, in locale, the default value should be made en-US, thereby still giving to enter it manually [ . . . ]
> Like this:
> ![image](https://user-images.githubusercontent.com/83997633/125885649-c54e6c05-2030-419e-bbda-6e4039543d0d.png)

I could see this as being useful. It also seems relatively easy to implement. I'm curious to know what @OfficialEsco thinks. I could probably have a PR for this ready in a matter of minutes

**Comment by OfficialEsco** [comment]
> I could see this as being useful. It also seems relatively easy to implement. I'm curious to know what @OfficialEsco thinks. I could probably have a PR for this ready in a matter of minutes

Go ahead as i have no idea how to do that

**Comment by vedantmgoyal2009** [comment]
Make sure to link this issue with the PR so that when it gets merged, the issue closes automatically.

**Comment by Trenly** [comment]
> Make sure to link this issue with the PR so that when it gets merged, the issue closes automatically.

To be clear, I think that defaulting to `en-US` is a good idea. I wasn't planning to address the SHA256 item, which is why I had removed that portion of it in my reply

**Comment by vedantmgoyal2009** [comment]
Made some basic changes and added the default locale option. The other change, if anyone can contribute, would be very helpful.
