### ISSUE TITLE
add package "Azkar app"

### ISSUE THREAD

**Issue by ahmed-tasaly** [microsoft/winget-pkgs#21079]
# Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: AbdelrahmanBayoumi 

**Publisher Url**: https://github.com/AbdelrahmanBayoumi

**Package Name**: Azkar-App

**Package Url**: 
https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/download/0.9.4/Azkar_windows-x64.exe
https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/download/0.9.4/Azkar_windows-x32.exe

**Description**: 
Desktop Application 💻 for:

    Calculating Muslim prayer times 🕌
    Morning and Nights Azkar with reminder 🤲
    With notification for random Azkar that pops-up in specific time 💬.

**Package Version**: **0.9.4**

**Installer URL**: 
_**64 bit :**_ https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/download/0.9.4/Azkar_windows-x64.exe
**_32 bit :_** https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/download/0.9.4/Azkar_windows-x32.exe

## For new versions:

**Current Package Identifier**:

**Comment by OfficialEsco** [comment]
What language code is the correct one?..
https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
