### ISSUE TITLE
YamlCreate.ps1 -> Prompt to test on creation / update

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#21148]
# Description of the new feature/enhancement
Upon creation of a new manifest or update of an existing manifest, YamlCreate should ask the user if they would like to test their manifest. This would avoid users having to copy the file path

# Proposed technical implementation details (optional)

- Users should not have to copy the file path
- The user should be informed that the sandbox testing script is required
- If the user responds yes, the manifest path should be passed to the sandbox test tool and run
- If the path to the sanbox script cannot be determined, this option should not be shown to the user

# Additional information
I am willing to work on this feature, but may need some guidance and assistance

**Comment by OfficialEsco** [comment]
I actually had a Draft with decent progress for this feature, but i scrapped it since i mainly use my VM and couldn't test it..
I'll look into it as i use Sandbox at Work

**Comment by OfficialEsco** [comment]
Mby i just looked into it last time, this is the Sandbox part
https://github.com/OfficialEsco/winget-pkgs/commit/af4251e1b9445b5cdf0dd4cfa51999f69c0c6674

Looking into PR Automation with git/gh which is why i haven't created the PR yet
