### ISSUE TITLE
Improve YAML parsing in YamlCreate.ps1

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#21205]
# Description of the new feature/enhancement

By using [powershell-yaml](/cloudbase/powershell-yaml) instead of (or in addtion to) raw parsing, it will make it easier for users to understand and contribute to the YamlCreate script

# Proposed technical implementation details (optional)
- This may need to be fully Spec'd out
- Using a dedicated YAML tool should not significantly change the resulting output

#References
- [Original Discussion](https://github.com/microsoft/winget-pkgs/discussions/21005#discussioncomment-1010444)
- Thanks to @OfficialEsco for identifying this need
-  #21204

**Comment by Trenly** [comment]
@denelon Would you be able to link the draft PR and add the "Help-Wanted" tag?

**Comment by Trenly** [comment]
@OfficialEsco  The more that I've been working on this, I'd like to know your opinion. If I can get everything working using `powerhell-yaml`, would we still want to keep the raw text processing? 

It would certainly make the script easier to read/digest if we didn't keep it, and `powershell-yaml` should be available to everyone, so I don't think there would be a huge risk of dependency issues. What are your thoughts?

**Comment by OfficialEsco** [comment]
> @OfficialEsco The more that I've been working on this, I'd like to know your opinion. If I can get everything working using `powerhell-yaml`, would we still want to keep the raw text processing?
> 
> It would certainly make the script easier to read/digest if we didn't keep it, and `powershell-yaml` should be available to everyone, so I don't think there would be a huge risk of dependency issues. What are your thoughts?

Thats the point, it would basically replace every part of the metadata processing and make it a lot easier to work with, however when i tested it out i didn't understand anything and since wingetcreate was going to do sorta the same thing i didn't put time into it...

The part where Powershell-yaml would really help out is for catching dependency metadata and most likely all other metadata we don't have hardcoded into the script..

**Comment by Trenly** [comment]
> > @OfficialEsco The more that I've been working on this, I'd like to know your opinion. If I can get everything working using `powerhell-yaml`, would we still want to keep the raw text processing?
> > It would certainly make the script easier to read/digest if we didn't keep it, and `powershell-yaml` should be available to everyone, so I don't think there would be a huge risk of dependency issues. What are your thoughts?
> 
> Thats the point, it would basically replace every part of the metadata processing and make it a lot easier to work with, however when i tested it out i didn't understand anything and since wingetcreate was going to do sorta the same thing i didn't put time into it...
> 
> The part where Powershell-yaml would really help out is for catching dependency metadata and most likely all other metadata we don't have hardcoded into the script..
I fully agree. I'm not 100% sure how it can best be leveraged for some of that metadata, but I think the biggest part will be getting everything reading and writing properly. 

I'll take some time next week to start ripping out the raw processing for the parts that I have completed. That should make it easier to focus on the remaining items
