### ISSUE TITLE
Problem of encoding

### ISSUE THREAD

**Issue by qiancy98** [microsoft/winget-pkgs#2120]
I am using the following program written by myself to check the encoding of files.

Now I find that there are 62 files coding in UTF8-With-BOM or UTF-16. Should we transform them into UTF-8?

```Python
import os
import re
import chardet

convert = False # Whether we transform the style

os.chdir('.')
print("Working Dictionary: ",os.getcwd())
for root, dirs, files in os.walk("."):
    # print(files)
    for name in files:
        full_name = os.path.join(root, name)
        if re.fullmatch(r".*\.yaml",name):
            with open(full_name,'rb') as fin:
                input = fin.read()
            Result = chardet.detect(input)
            if (Result['encoding'] in {'UTF-16','UTF-8-SIG'} and Result['confidence']>0.98):
                Code_Mapping = {'UTF-16':'UTF-16','UTF-8-SIG':'UTF-8-SIG'}
                string = input.decode(Code_Mapping.get(Result['encoding']))
                if convert:
                    print(full_name)
                    with open(full_name,'w',newline='',encoding='utf-8') as fout:
                        fout.write(string)
                else:
                    print(full_name)
            elif Result['encoding'] in {'utf-8','ascii','ISO-8859-1','Windows-1252'}:
                pass
            else:
                print(full_name,Result)
```

List of files:
> .\winget-pkgs\manifests\Bonnefon\Glogg\1.1.4.yaml
> .\winget-pkgs\manifests\canonical\MicroK8s\2.0.0.yaml
> .\winget-pkgs\manifests\canonical\Multipass\1.2.1.yaml
> .\winget-pkgs\manifests\CodeLite\CodeLite\14.0.0.yaml
> .\winget-pkgs\manifests\DasKeyboard\DasKeyboard\3.2.6.yaml
> .\winget-pkgs\manifests\Files-UWP\FilesUWP\0.8.2.0.yaml
> .\winget-pkgs\manifests\Files-UWP\FilesUWP\0.9.0.yaml
> .\winget-pkgs\manifests\Files-UWP\FilesUWP\0.9.1.yaml
> .\winget-pkgs\manifests\Gauge\Gauge\1.0.6.yaml
> .\winget-pkgs\manifests\GeoGebra\GeoGebraClassic\6.0.583.0.yaml
> .\winget-pkgs\manifests\GeoGebra\GeoGebraClassic6\6.0.583.0.yaml
> .\winget-pkgs\manifests\GeoGebra\Geometry\6.0.583.0.yaml
> .\winget-pkgs\manifests\GeoGebra\GraphingCalculator\6.0.583.0.yaml
> .\winget-pkgs\manifests\gnupg\GnuPG\2.2.20.yaml
> .\winget-pkgs\manifests\Insomnia\InsomniaDesigner\2020.2.0.yaml
> .\winget-pkgs\manifests\isaaclevin\presencelight\1.0.171.yaml
> .\winget-pkgs\manifests\isaaclevin\presencelight\2.0.49.yaml
> .\winget-pkgs\manifests\IsWiX\IsWiX\4.14.5.yaml
> .\winget-pkgs\manifests\Joplin\Joplin\1.0.216.yaml
> .\winget-pkgs\manifests\KKBOX\KKBOX\7.2.30.yaml
> .\winget-pkgs\manifests\Krisp\Krisp\1.14.3.yaml
> .\winget-pkgs\manifests\LyX\LyX\2.3.4.4.yaml
> .\winget-pkgs\manifests\MarkText\MarkText\0.16.1.yaml
> .\winget-pkgs\manifests\Microsoft\AccessibilityInsightsWindows\1.1.1248.1.yaml
> .\winget-pkgs\manifests\Microsoft\MouseAndKeyboardCenter\12.181.137.0.yaml
> .\winget-pkgs\manifests\MongoDB\Compass\Community\1.21.2.yaml
> .\winget-pkgs\manifests\MongoDB\Compass\Full\1.21.2.yaml
> .\winget-pkgs\manifests\MongoDB\Compass\Isolated\1.21.2.yaml
> .\winget-pkgs\manifests\MongoDB\Compass\Readonly\1.21.2.yaml
> .\winget-pkgs\manifests\mRemoteNG\mRemoteNG\1.76.20.yaml
> .\winget-pkgs\manifests\Mu\Mu\1.0.3.yaml
> .\winget-pkgs\manifests\NagleCode\PacketSender\6.2.3.yaml
> .\winget-pkgs\manifests\NimbusWeb\NimbusWeb\6.10.34.yaml
> .\winget-pkgs\manifests\ONLYOFFICE\DesktopEditors\5.5.1.yaml
> .\winget-pkgs\manifests\OSGeo\QGIS\3.12.3.yaml
> .\winget-pkgs\manifests\PicoTorrent\PicoTorrent\0.18.0.yaml
> .\winget-pkgs\manifests\Plex\Plexamp\3.0.3.yaml
> .\winget-pkgs\manifests\Renode\Renode\1.9.0.yaml
> .\winget-pkgs\manifests\RevoUninstaller\RevoUninstaller\2.1.5.yaml
> .\winget-pkgs\manifests\RevoUninstaller\RevoUninstallerPro\4.3.1.yaml
> .\winget-pkgs\manifests\RiotGames\LeagueOfLegends\1.0.0.0.yaml
> .\winget-pkgs\manifests\RStudio\RStudio\1.3.959.yaml
> .\winget-pkgs\manifests\Rustlang\rust-gnu\1.43.1.yaml
> .\winget-pkgs\manifests\Rustlang\rust-msvc\1.43.1.yaml
> .\winget-pkgs\manifests\SMPlayer\SMPlayer\20.4.2.yaml
> .\winget-pkgs\manifests\StefHeyenrath\GitHubReleaseNotes\1.0.5.3.yaml
> .\winget-pkgs\manifests\TechSmith\Camtasia\2020.0.2.yaml
> .\winget-pkgs\manifests\TechSmith\Snagit\6.10.34.yaml
> .\winget-pkgs\manifests\TeraTermProject\TeraTerm\4.105.yaml
> .\winget-pkgs\manifests\Texmaker\Texmaker\5.0.4.yaml
> .\winget-pkgs\manifests\TeXworks\TeXworks\0.6.5.yaml
> .\winget-pkgs\manifests\TGRMNSoftware\BulkRenameUtility\3.3.1.0.yaml
> .\winget-pkgs\manifests\TheHandBrakeTeam\HandBrake\1.3.2.yaml
> .\winget-pkgs\manifests\TonyPottier\ImageView\2.0.0.yaml
> .\winget-pkgs\manifests\TTYPlus\MTPutty\1.7.yaml
> .\winget-pkgs\manifests\TunnelBear\TunnelBear\4.2.10.yaml
> .\winget-pkgs\manifests\VivaldiTechnologies\Vivaldi\3.0.1874.38.yaml
> .\winget-pkgs\manifests\wandersick\AeroZoom\4.0.0.7.yaml
> .\winget-pkgs\manifests\Zap\Zap\2.9.0.yaml
> .\winget-pkgs\manifests\Zettlr\Zettlr\1.6.0.yaml
> .\winget-pkgs\manifests\Zoom\Zoom\5.0.5.yaml
> .\winget-pkgs\manifests\Zotero\Zotero\5.0.87.yaml

**Comment by MarNicGit** [comment]
https://github.com/microsoft/winget-pkgs/issues/1863

**Comment by qiancy98** [comment]
> #1863

Oh yes it's a dump of #1863. I hope the Tools/YamlCreate.ps1 can change to UTF-8 output...
