### ISSUE TITLE
[YamlCreate] Simple Update 

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#21219]
# Description of the new feature/enhancement

Some users might not want to go trough the whole prompt thing (or enter the wrong thing), would it be possible to only update the InstallerUrl, SHA256 and ProductCode?

Might be a lot simpler once we get #21204 to work

# Proposed technical implementation details (optional)
method 1
Prompt for every different InstallerUrl so it can replace multiple installers at once

method 2
If version number is in the InstallerUrl try to replace Version Numbers, if 404 prompt for url

another feature:
If installerUrl dosn't change delete the previous manifest version

**Comment by vedantmgoyal2009** [comment]
Why Azure Pipelines are not running by default? Is it experiencing any issue?

**Comment by vedantmgoyal2009** [comment]
Is anyone currently working on this or should I start?

**Comment by OfficialEsco** [comment]
Since #21204 is still in the PR phase, most likely not

**Comment by vedantmgoyal2009** [comment]
Ok, so I will be implementing and suggesting changes on that PR only...

**Comment by OfficialEsco** [comment]
You can submit PR to Trenly's PR and modify this branch https://github.com/Trenly/winget-pkgs/blob/YamlParsing/Tools/YamlCreate.ps1
