### ISSUE TITLE
Attempting to install Audacity results in a 410 - Gone Error

### ISSUE THREAD

**Issue by MinerMax555** [microsoft/winget-pkgs#2150]
when attempting to install Audacity, the file that winget tries to download results in a 410 - Gone Error.

The archive it downloads from deleted the version referenced by the newest manifest (2.4.1), and instead added a file for version 2.4.2. The archive itself seems like a weird choice for the location to download audacity, as it appears to only be a mirror for various software instead of the actual source.

**Comment by OfficialEsco** [comment]
I just sent a PR for v2.4.2 #2152 

There seems to be no perma link for Audacity, Fossies seems to delete old versions, Fosshub moves old versions to \Audacity-old.html, and the google code mirror aint updated

**Comment by denelon** [comment]
The PR was merged so I'm closing this issue.
