### ISSUE TITLE
Forgotten pr's

### ISSUE THREAD

**Issue by qiancy98** [microsoft/winget-pkgs#2177]
I check the history and find a lot of issues, the last active time of which is at least 6 days. (20 in total)
My filter is "is:pr is:open updated:<2020-06-24"

Here are pr's on YamlCreate.ps1:
#451 

Here are pr's on general yaml files:
#1938 #561

Here are pr's that might lack "blocking issue" tag:
#756 #545 #332 (#332 has moved to here.)

Here are confilcted pr's (and should be closed or add a fail tag):
#1193 #445

---
The following have been done (either merged or closed) before 20-07-01 00:00 (UTF-4)

Here are pr's on README:
#1432 #1287 #1286 #769

Here are pr's on YamlCreate.ps1:
#1159 #478 #462 (#462 is better than #451)

Here are pr's on Issue template:
#1135 #481

Here are pr's on general yaml files:
#2059 #1315 

Here are pr's that might lack "blocking issue" tag:

Here are confilcted pr's (and should be closed or add a fail tag):

Here are pr's on .editorconfig:
#334

**Comment by denelon** [comment]
@qiancy98 I'll take a look at those.

**Comment by denelon** [comment]
The README.md PRs are all merged now.

**Comment by denelon** [comment]
I've asked @KevinLaMS to look at the YamlCreate.ps1 PRs.

**Comment by denelon** [comment]
I've merged the Issue Template PRs, but I needed to move a link out of the comment, so that's waiting on a team approver.

**Comment by qiancy98** [comment]
It seems that you don't like the "block issue" tag, do you? If it is this case, I will delete related texts. Thanks.
