### ISSUE TITLE
Package Request: Chocolatey

### ISSUE THREAD

**Issue by vanillajonathan** [microsoft/winget-pkgs#21877]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Chocolatey Software, Inc.

**Publisher Url**: https://chocolatey.org/

**Package Name**: Chocolatey

**Package Url**: https://chocolatey.org/

**Description**: Chocolatey is a machine-level, command-line package manager and installer for Windows software. It uses the NuGet packaging infrastructure and Windows PowerShell to simplify the process of downloading and installing software.

**Package Version**:

**Installer URL**: https://community.chocolatey.org/install.ps1

## For new versions:

**Current Package Identifier**:

**Comment by ItzLevvie** [comment]
WinGet doesn't support `.ps1` files yet.

I believe it's being tracked by https://github.com/microsoft/winget-cli/issues/298.

**Comment by vanillajonathan** [comment]
Maybe Chocolatey have some packages that are not on WinGet.

**Comment by dertuxmalwieder** [comment]
> Also Chocolatey is not moderated

Chocolatey *is* moderated. One of my packages is currently waiting for moderation.

**Comment by anborg** [comment]
> I think there would be no point to this since we have winget. Also Chocolatey is not moderated and managed by anyone so it is not reliable and safe like winget.

A classic ms entltiled attitude.  That's one reason users must shy away from big corps on core tools like package managers.  They relesed this half-baked tool that can't install softwares that a typical developer would use ... I wasted my time .. now have to go back to choco...

**Comment by pauby** [comment]
As part of the Chocolatey Team, how do we go about getting Chocolatey published to Winget and ensure that only our team / automation can push updates?

We currently have two products we would push to Winget.

**Comment by pauby** [comment]
> Also Chocolatey is not moderated and managed by anyone so it is not reliable and safe like winget.

That shows a complete misunderstanding of Chocolatey is a wholly incorrect statement. I'll leave it at that.

**Comment by SpecterShell** [comment]
> As part of the Chocolatey Team, how do we go about getting Chocolatey published to Winget and ensure that only our team / automation can push updates?

Installation methods that WinGet currently supports:
- Download .exe/.msi installer and execute
- Download single .exe executable and create symbolic link (user scope)

Installation methods that WinGet would support:
- Download and extract .zip, execute .exe/.msi inside
- Download and extract .zip, extract files and link executable(s) (user scope?)

AFAIK none of the above methods is known to be able to run .ps1 script at present. And it is not feasible to install choco as a .zip package since choco is usually working in machine scope (administrator) but WinGet can only install it in user scope (No idea if WinGet would add this feature in the future). So it is recommended to build a .exe/.msi installer, just like ChocolateyGUI.😉

> ensure that only our team / automation can push updates

Yes. You can call moderaters when needed. Once verified, you can add agreements to the manifest, which cannot be added by others.

> We currently have two products we would push to Winget.

ChocolateyGUI already exists here. I'm curious that what another product is? 🤔

**Comment by pauby** [comment]
We're looking to add Chocolatey CLI and I understand the caveats about installation method above. We would also like to take over 'official maintenance' of ChocolateyGUI.

**Comment by ohkeenan** [comment]
> As part of the Chocolatey Team, how do we go about getting Chocolatey published to Winget and ensure that only our team / automation can push updates?
> 
> We currently have two products we would push to Winget.

As someone who just tried to install chocolatey via winget I greatly appreciate your efforts! I'm looking for the bitwarden-cli specifically which Chocolatey has but winget does not, unless I'm mistaken.

**Comment by Andrej730** [comment]
@pauby any updates on chocolatey cli on winget?

**Comment by pauby** [comment]
Yes and no. There is an MSI installer in testing. We should have everything wrapped up (which is not just testing) _soon_.

**Comment by denelon** [comment]
@pauby, we're working on a "verified developer" feature to restrict changes to packages to a GitHub user. The business process is the long-lead issue. We've got a PowerShell script in [PR](https://github.com/microsoft/winget-pkgs/pull/96846) to help until all of the wiring and business process are in place. 

The script is to help our moderators track PRs. It's certainly not foolproof, but it's a start.

**Comment by denelon** [comment]
@ohkeenan is `winget install Bitwarden.Bitwarden` not the same bitwarden-cli you are referring to?

**Comment by x545** [comment]
`choco upgrade chocolatey` worked for me

**Comment by pauby** [comment]
Chocolatey CLI 2.0.0 has just been approved. Just waiting on the updating of the community repository.

Note that this is being pushed manually currently until we are happy that our customers and community are happy with it.

I think this can be closed?

**Comment by ohkeenan** [comment]
@denelon I think it likely is but installing the entire package wasn't what I was looking to do.
@pauby having Chocolatey on winget is going to be lovely thank you.
