### ISSUE TITLE
[YamlCreate] Fill In PR Parameters

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#21940]
# Description of the new feature/enhancement
Slightly related to #21219 

When submitting a PR, it should prompt you for the appropriate parameters. Additionally, it should prompt for issues to resolve (Can enter multiple as a comma separated list)

# Proposed technical implementation details (optional)
- Prompt users if they have signed the CLA
- Prompt users if they have checked for open PR's
- Prompt users if they have validated their manifest
  - If the user tested using sandbox and validation passed, automatically mark this as complete
- Prompt users if they have tested their manifest
  - If the user tested using sandbox, automatically mark this as complete
- Prompt users for any issues this PR resolves
  - User enters issues as comma separated list
  - Text gets added to the PR to link issues
  - Example: User enters `21219, 21205` Text added to PR is `Resolves #21219  Resolves #21205`

**Comment by vedantmgoyal2009** [comment]
Have you already started working on it otherwise I would like to do?

**Comment by Trenly** [comment]
> Have you already started working on it otherwise I would like to do?

I haven’t started on it yet, but I think we should wait until #21204 is completed

**Comment by vedantmgoyal2009** [comment]
Okay, actually till you replied I already have implemented it on my local machine. Once #21204 is merged, I will open a PR resolving this issue.

**Comment by vedantmgoyal2009** [comment]
#21940

**Comment by vedantmgoyal2009** [comment]
>   * If the user tested using sandbox, automatically mark this as complete

I just saw this but as `winget validate` returns some codes, the same SandboxTest Script should do, otherwise, I didn't find any logic to implement this. If you have any suggestions, please tell.

**Comment by vedantmgoyal2009** [comment]
@Trenly
