### ISSUE TITLE
[SandboxTest] Validation treats warnings as fatal

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#21941]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Manifest validation warnings will cause the sandbox test to throw an exception
# Steps to reproduce
- Create a manifest which returns a validation warning when using `winget validate`
- Run sandbox test on that manifest

# Expected behavior
- The sandbox test will show the validation warning, and continue the installation test

# Actual behavior
- The sandbox test shows the validation warning, and then exits
```raw
PS D:\Git\winget-pkgs> .\Tools\SandboxTest.ps1 D:\Git\winget-pkgs\manifests\m\MichaelBromley\SKQW\1.0.0-beta.2

--> Validating Manifest
Manifest validation succeeded with warnings.
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.

Manifest validation failed.
At D:\Git\winget-pkgs\Tools\SandboxTest.ps1:32 char:5
+     throw 'Manifest validation failed.'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Manifest validation failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Manifest validation failed.
```

# Environment

```none
PS D:\Git\winget-pkgs> winget --info

Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by OfficialEsco** [comment]
cc @felipecrs 

Guessing this is sorta intended behaviour because we do want them to contain Silent/SilentWithProgress switches, but AFAIK if we only input the Silent switch it will still throw since SilentWithProgress is blank.

Also did probably not think there was so many executables without silent switches (There probably is, just not easy to find)

**Comment by felipecrs** [comment]
The SandboxTest simply relies on the status code of winget.exe.

But you can skip de validation with -SkipValidation

**Comment by Trenly** [comment]
> Guessing this is sorta intended behaviour because we do want them to contain Silent/SilentWithProgress switches, but AFAIK if we only input the Silent switch it will still throw since SilentWithProgress is blank.
> 
> Also did probably not think there was so many executables without silent switches (There probably is, just not easy to find)
> 
> For example the silent switch for that executable is --silent (Probably InstallShield)

That does make sense, but in either case there is a discrepancy between the cli and the script, as one treats it as an error and the other treats it as a warning. In the case of the CLI, it asks the user to validate that it installs, as some exe files do install without user input.

> The SandboxTest simply relies on the status code of winget.exe.
> 
> But you can skip de validation with -SkipValidation
Thank you for the switch

**Comment by felipecrs** [comment]
> That does make sense, but in either case there is a discrepancy between the cli and the script, as one treats it as an error and the other treats it as a warning. In the case of the CLI, it asks the user to validate that it installs, as some exe files do install without user input.

Consider opening an issue in `winget-cli` to add a flag such `--ignore-warnings`, or even to change the default behavior so warnings do not throw a non-zero status code (and then a new flag such as `--include-warnings` could be introduced).

After that we can also tweak the `SandboxTest.ps1` to use it.

**Comment by denelon** [comment]
@Trenly is this resolved or do we need an issue over at https://github.com/microsoft/winget-cli?

**Comment by Trenly** [comment]
> @Trenly is this resolved or do we need an issue over at https://github.com/microsoft/winget-cli?

It is still happening, but after more investigation; I think this might be fixable in the sandbox script itself. I see that two different return codes are given depending on if it is a warning or an error. I suppose the question then is if this is something that _should_ be changed in the CLI or something that doesn't really matter.

I'll leave creating a CLI issue up to your discretion @denelon. Should the CLI return a `0` status code when validation has warnings, or should it be kept as is?

I'll probably create a pull request to fix the sandbox script later tomorrow.

```raw
PS D:\Git\winget-pkgs> winget validate --manifest D:\Git\winget-pkgs\manifests\e\Egnyte\EgnyteDesktopApp\3.11.2.104; $LASTEXITCODE

Manifest validation succeeded.
0
PS D:\Git\winget-pkgs> winget validate --manifest D:\Git\winget-pkgs\manifests\e\Egnyte\EgnyteDesktopApp\3.11.2.104; $LASTEXITCODE

Manifest validation succeeded with warnings.
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
-1978335192
PS D:\Git\winget-pkgs> winget validate --manifest D:\Git\winget-pkgs\manifests\e\Egnyte\EgnyteDesktopApp\3.11.2.104; $LASTEXITCODE

Manifest validation failed.
Manifest Error: Schema validation failed.
Error context: <root>[Installers][0] Description: Missing required property 'InstallerUrl'.
Error context: <root>[Installers] Description: Failed to validate item #0 in array.
Error context: <root> Description: Failed to validate against schema associated with property name 'Installers'.
 File: Egnyte.EgnyteDesktopApp.installer.yaml
Manifest Error: Required field missing. Field: InstallerUrl

-1978335191
PS D:\Git\winget-pkgs> winget validate --manifest D:\Git\winget-pkgs\manifests\e\Egnyte\EgnyteDesktopApp\3.11.2.104; $LASTEXITCODE

Manifest validation succeeded with warnings.
Manifest Warning: Unknown field. Field: Blah

-1978335192
```

**Comment by felipecrs** [comment]
In my opinion, if it says succeeded it should return `0` as status code. Then, it may be also be desired by someone to catch the warnings (some CI job or whatever), and for so, a new option like `winget validate --fail-on-warning` could be introduced to achieve it (by restoring the previous behavior).

**Comment by Trenly** [comment]
> In my opinion, if it says succeeded it should return `0` as status code. Then, it may be also be desired by someone to catch the warnings (some CI job or whatever), and for so, a new option like `winget validate --fail-on-warning` could be introduced to achieve it (which would restore the previous behavior).

If this is the path that is decided, possibly also a setting tthe user can set to always fail on warnings
