### ISSUE TITLE
Request: Sizer by BrianApps

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/winget-pkgs#22057]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:

**Publisher Url**:

**Package Name**:

**Package Url**:

**Description**:

**Package Version**:

**Installer URL**:

## For new versions:

**Current Package Identifier**:

All I know is this: http://www.brianapps.net/sizer4/

brilliant lil app

**Comment by ImJoakim** [comment]
Hey @Poopooracoocoo, I made 2 pull requests. One for the official release which is version 3.3.4.0, and one for the version you mentioned 4.0.640. This version is currently in development.

You can install the following versions (once merged) via the following commands:

Release 3.3.4.0: `winget install sizer`
Dev 4.0.640: `winget install sizer-dev`

**Comment by Poopooracoocoo** [comment]
@ImJoakim thanks. the dev release hasn't gotten any updates in ages afaik. i wouldn't mark Sizer4 as a dev release. it's perfectly stable. 

i'd instead prefer to just have the one sizer 4 release.

**Comment by ImJoakim** [comment]
> @ImJoakim thanks. sizer 4 hasn't received any updates in ages afaik. i wouldn't mark Sizer4 as a dev release. it's perfectly stable too.
> 
> i'd instead prefer to just have the one sizer release being sizer 4.

I do understand that, but it's still technically still in development, so we have to follow that when we're adding it as a package.

**Comment by Poopooracoocoo** [comment]
understood. i just hope no one misunderstands. 

btw i don't think sizer is going to get an update

**Comment by ImJoakim** [comment]
> i'd instead prefer to just have the one sizer release being sizer 4, and sizer 3 being separate

Well, we could split them up and list them as Sizer 3 and Sizer 4, similarly to how Sublime text is currently listed:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/SublimeHQ/SublimeText

However, we would only be able to do that if Sizer 4 had an official release. If it ever does, I'd be happy to split them up.
