### ISSUE TITLE
Add attribution/component governance for powershell-yaml

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#22081]
# Description of the new feature/enhancement

The YamlCreate script is being refactored to use powershell-yaml.

# Proposed technical implementation details (optional)

We need to create the proper attributions and hook up component governance in our build pipelines.

**Comment by Trenly** [comment]
@denelon  Do we have an estimated release date for the governance components? I understand it isn't at the top of MSFT's priority list. I'm just trying to plan out which items I work on when, so having a rough estimate would be helpful

**Comment by denelon** [comment]
It might be done, let me check.

**Comment by denelon** [comment]
* https://github.com/microsoft/winget-pkgs/pull/30274
