### ISSUE TITLE
FutureRestore GUI 1.90: Validation-Installation-Error

### ISSUE THREAD

**Issue by CoocooFroggy** [microsoft/winget-pkgs#22240]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [x] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: CoocooFroggy

**Publisher Url**: https://github.com/CoocooFroggy/

**Package Name**: FutureRestore GUI

**Package Url**: https://github.com/CoocooFroggy/FutureRestore-GUI/

**Description**: A GUI implementation for FutureRestore written in Java.

**Package Version**: 1.90

**Installer URL**: https://github.com/CoocooFroggy/FutureRestore-GUI/releases/download/1.90/FutureRestore-GUI-Windows-1.90.msi

## For new versions:

**Current Package Identifier**: CoocooFroggy.FutureRestore-GUI

---

I have an open PR in #22178, and can validate the manifest and install it without any warnings or errors. However, the CI bot states:

> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

However, I cannot find specifically what the issue is, and cannot reproduce the issue. Any help would be appreciated.

**Comment by ItzLevvie** [comment]
By checking Revo Uninstaller, it seems like the application is 64-bit.

Since you put x86, Azure Pipelines booted up a 32-bit version of Windows and tried to install it but ran into issues.

**Comment by CoocooFroggy** [comment]
Thanks for all your help, also changing the publisher as you pointed out worked as well.
