### ISSUE TITLE
Spotify -> cant play this right now -> seems related 2 winget

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/winget-pkgs#22281]
# Brief description of your issue
installing Spotify trough winget gives me can’t pay this right now on all songs,
I’ve not had this issue before when I had internet.
# Steps to reproduce

run winget install spotify (i did use
```powershell
function wi ($target) {
    Winget install $target
}
```
 try and play song.
 
 Restart pc.
 
 Try and play song
 
# Expected behavior

song plays

# Actual behavior

I get the error 
`cant play this right now `

# Environment

```none

Windows: Windows.Desktop v10.0.19043.928
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

spotify ps5
```

**Comment by KaranKad** [comment]
I can't replicate this issue, I am able to play all available songs. Try reinstalling Spotify.

**Comment by NicTanghe** [comment]
The issue was with drivers of the soundcard.
