### ISSUE TITLE
Microsoft Office full package 

### ISSUE THREAD

**Issue by sohag0711** [microsoft/winget-pkgs#22404]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:

**Publisher Url**:

**Package Name**:

**Package Url**:

**Description**:

**Package Version**:

**Installer URL**:

## For new versions:

**Current Package Identifier**:

**Comment by ImJoakim** [comment]
I believe this is already added. You can install it via `winget install office`.

It's located here: [Microsoft/Office/16.0.14131.20278](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/Office/16.0.14131.20278)

**Comment by KevinLaMS** [comment]
@sohag0711  I agree we have this package.  Please make sure it works for you and close this out.  Cheers.
