### ISSUE TITLE
[YamlCreate.ps1] When `InstallerType:msi`, entering `ProductCode` should be mandatory

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#22427]
# Description of the new feature/enhancement
When the user selects `InstallerType` msi, entering ProductCode should be compulsory to enter and the script would not proceed further. For other installer types, it will be optional.

# Proposed technical implementation details (optional)
if (installertype equals 'msi')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entering ProductCode is mandatory
else
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the script will proceed further.

**Comment by OfficialEsco** [comment]
Not all MSI's have a ProductCode and not all Programs installed by MSI have a ProductCode.

If the MSI Installer have a ProductCode it will tell you the ProductCode this does however not have to be the Softwares ProductCode.

They want a different matching system than the ProductCode.

**Comment by vedantmgoyal2009** [comment]
On my system, it has never told me the product code of any software even once.
