### ISSUE TITLE
Problem with w\WikiPad manifest?

### ISSUE THREAD

**Issue by jsmorley** [microsoft/winget-pkgs#22505]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When I fork and clone the repository to my local PC, the entry for w\WikiPad in Manifests is always marked as "dirty" on my PC. My fork insists that it is up to date with Master, and I can't see how to resolve this. Is there some error in the repository for the Manifest w\WikiPad ?
# Steps to reproduce
Forked the repo to my account on GitHub and using TortoiseGit created a clone on my local PC

# Expected behavior
I would expect a full, clean copy of the repo on my PC

# Actual behavior
The Manifest w\WikiPad is always flagged as "dirty"

# Environment

```none
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.100
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Any other software?
TortoiseGit 2.12.0.0 (C:\Program Files\TortoiseGit\bin)
git version 2.31.1.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig)
```

**Comment by ImJoakim** [comment]
Hey @jsmorley, what's your issue exactly?

**Comment by jsmorley** [comment]
Sorry, looks like I didn't create the issue correctly.

What happens is that I fork the repository to my account on GitHub, and clone it to my local PC.

The Manifest \w\WikiPad is always flagged as dirty.

My fork insists it is up to date.

I suspect that maybe there is some problem with \w\WikiPad in the Master?

**Comment by ItzLevvie** [comment]
There's a capitalization issue, https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WikidPad

Both `WikiPad` and `Wikipad` exist and need to be merged into one.

**Comment by jsmorley** [comment]
Thank you. I will just wait for it to be fixed.
