### ISSUE TITLE
notepad++ doesn't upgrade, if notepad++ is opened, when ran

### ISSUE THREAD

**Issue by scadden365** [microsoft/winget-pkgs#22514]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

notepad++ doesn't upgrade, if notepad++.exe is opened when winget upgrade notepad++ is ran

# Steps to reproduce

open notepad++
run winget upgrade notepad++ from windows terminal
-----------------------------------------------------
Found Notepad++ [Notepad++.Notepad++]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.2/npp.8.1.2.Installer.x64.exe
Successfully verified installer hash
Starting package install...
Successfully installed
----------------------------------------------------
It appears to be installed, and running : winget list notepad++
Name      Id                  Version
-------------------------------------
Notepad++ Notepad++.Notepad++ 8.1.2

Winget thinks the latest version is installed. 
But when you check "?" "About Notepad++" , it still show the old version v8.1.1

# Expected behavior

That the newest version of notepad++ be installed

# Actual behavior

notepad++ doesn't upgrade, even though it lists the lastest version when "winget list" is ran

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

**Comment by OfficialEsco** [comment]
This is a issue with Notepad++, not WinGet.
* .\npp.8.1.1.Installer.x64.exe /S
* Open Notepad++
* .\npp.8.1.2.Installer.x64.exe /S
* Install succeeds
* Windows reports 8.1.2
* Notepad++ report 8.1.1
* Reclose and open Notepad++ and it still reports 8.1.1
* Uninstall Notepad++ reports 8.1.2

/RESTARTAPPLICATIONS does not work so there is nothing we can do to work around the developers mess.

**Comment by scadden365** [comment]
OfficialEsco, Thanks for taking the time to look at the problem, I have reported it to notepad++

**Comment by KevinLaMS** [comment]
Seems like a challenge for them to fix.  If they shut down the EXE you may lose what you are working on.  :(
@scadden365  Thanks for opening an issue on notepad++.  Feel free to close this issue.

**Comment by scadden365** [comment]
Thanks KevinLaMS, notepad++ is fairly good at remembering all the text in non saves files, even after an update, so it should be ok.
