### ISSUE TITLE
PowerShell preview entries are not consistent

### ISSUE THREAD

**Issue by rjmholt** [microsoft/winget-pkgs#22522]
# Brief description of your issue

Follow up from https://github.com/microsoft/winget-pkgs/pull/8623#issuecomment-797654830.

EDIT: Related to https://github.com/microsoft/winget-pkgs/issues/100.

The community have submitted several entries for PowerShell releases, which is awesome.

Unfortunately, the submissions are not consistent, either in the manifest contents/metadata or in the [version string of the directory](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/PowerShell/Preview).

# Steps to reproduce

# Expected behavior

winget entries for PowerShell should be consistent to ensure a good experience for users using winget as an installation vector.

# Actual behavior

winget entries for PowerShell vary.

# Environment

N/A

**Comment by OfficialEsco** [comment]
Just took a look, the inconsistent manifests versions are from before Manifest Schema 1.0.0 which is why it dosn't match ARP, after diving deeper it seems like you were the one automatically generating manifests based on the marketing version https://github.com/microsoft/winget-pkgs/pull/17879

**Comment by rjmholt** [comment]
> after diving deeper it seems like you were the one automatically generating manifests based on the marketing version #17879

Yeah that's [our automation](https://github.com/PowerShell/PowerShell/blob/master/tools/releaseToWinget.ps1). Can you explain the "marketing version" vs what's expected? The version we give there is PowerShell's self-reported semver v2 version:

![image](https://user-images.githubusercontent.com/7009879/127215374-3c5340e4-091c-49c7-979d-e5d3e62a3552.png)

I've been in contact with the winget team around our automation and they didn't seem to indicate any issue.

Ideally I'd like to establish a canonical format for our manifests so that they're all consistent with each other, so I'm happy to learn what the right approach is here.

**Comment by OfficialEsco** [comment]
`7.2.0-preview.7` or `Powershell 7.2 Preview 7` is the marketing version, whatever is displayed in Windows (**A**dd or **R**emove **P**rograms/Display Version in Registry) is what we call the real version which winget-cli requires for matching against new versions.
At the same DisplayName and Publisher also needs to match what Windows/ARP sees.
![image](https://user-images.githubusercontent.com/15158490/127217538-fd902bef-c956-4011-b65a-fb494e938222.png)

If its Microsoft Employees then we know they don't do quality check or are up to date with the changes.

The more correct Metadata you can provide the better (filling the working Schema fields), i can see that the `ShortDescription` field which certain websites uses are broken in the older manifests, however those websites will pull the metadata from the latest manifest.

**Comment by rjmholt** [comment]
> is what we call the real version which winget-cli requires for matching against new versions

I see, sounds like we'll need to [reuse some logic](https://github.com/PowerShell/PowerShell/blob/3733a0bb3749b448002b034d0d09055367adac27/tools/packaging/packaging.psm1#L3750-L3790) to map from PowerShell's versions to Windows file versions.

> At the same DisplayName and Publisher also needs to match what Windows/ARP sees.

Can you elaborate on what you're referring to by `ARP` here? Where does the requirement about matching fields come from?

> If its Microsoft Employees then we know they don't do quality check or are up to date with the changes.

Thanks for the feedback.

> i can see that the ShortDescription field which certain websites uses are broken in the older manifests (because of the Schema v1.0.0 update), however those websites will pull the metadata from the latest manifest.

I didn't follow you here. Looking through the manifests that are currently checked in, I don't see any URLs other than some references to the PowerShell GitHub repository, which I'm fairly sure are live links. Certainly the `ShortDescription` fields seem to be populated with just a short package name.

> Talk to @denelon

Yeah, I have an internal thread with the winget team to try and understand the situation here better.

**Comment by JohnMcPMS** [comment]
We have schemas and docs, but it is honestly easiest to look at the existing examples there.  Of course, there might be other fields that they don’t have, so you can check the [docs and schemas](../tree/master/doc/manifest/schema/1.0.0).

The `PackageName` and `Publisher` fields in the locale manifest are used to match with the `DisplayName` and `Publisher` values from the ARP (Add/Remove Programs) registry entries.  You can see from [OfficialEsco's comment](https://github.com/microsoft/winget-pkgs/issues/22522#issuecomment-887789049) where those are located in the registry.  These are the same values that will be displayed in the Add/Remove Programs UI on Windows.  We prefer these to match exactly if possible, if only for consistency.  However, it is not uncommon for the `DisplayName` to include details that we encode elsewhere, and thus it can be difficult to have an exact match.  For instance, PowerShell is putting the architecture in the `DisplayName`, likely because it is not exposed to the user anywhere else and both could be installed, leading to confusion in ARP if it is not present.

There is a normalization algorithm applied to both strings, so certain portions of the name can be omitted in the manifest.  It is a rather complicated set of regexes though, but removing things like versions and architectures is part of it.  We should probably expose a way for the client to spit that information out to make sure it matches and easier process...

There are other fields that we can correlate on as well, and more that we are planning to add in the future.  The most relevant one that you can use right now is the `ProductCode`; this GUID value comes from the MSI and lets us bypass the name and publisher match, but is version specific.

**Comment by rjmholt** [comment]
So I've had a user raise an issue in https://github.com/PowerShell/PowerShell/issues/14583#issuecomment-888118788 that they can't install `PowerShell-Preview` in the `de-DE` locale. That feels related to the current structure our manifests, but I'm not sure I understand the locale element here well enough to know what to change.

**Comment by OfficialEsco** [comment]
A locale provides additional Metadata/matching possibility if it appears differently in ARP when installed in another language.

The default locale (en-US) should contain the default Product Name and global tags such as `cross-platform` and `foss`, a non default locale can contain Unicode characters so its easier to discover the software in different languages.

**The issue:**
```
winget install --name PowerShell-Preview --exact
No package found matching input criteria.
```
```
winget show -?

The following options are available:
  -m,--manifest  The path to the manifest of the package
  --id           Filter results by id
  --name         Filter results by name
  --moniker      Filter results by moniker
  -v,--version   Use the specified version; default is the latest version
  -s,--source    Find package using the specified source
  -e,--exact     Find package using exact match
  --versions     Show available versions of the package
```
@mi-hol is attempting to install `PackageName: PowerShell-Preview` which is case sensitive and does not exsist
You can install Powershell Preview with
```
winget install PowerShell-Preview
winget install PowerShell-Preview --exact
winget install "PowerShell Preview"
winget install "PowerShell Preview" --exact
winget install Microsoft.PowerShell.Preview
winget install Microsoft.PowerShell.Preview --exact
winget install --name "PowerShell Preview"
winget install --name "PowerShell Preview" --exact
winget install --id Microsoft.PowerShell.Preview
winget install --id Microsoft.PowerShell.Preview --exact
winget install --moniker powershell-preview
winget install --moniker powershell-preview --exact
winget install pwsh
```

**Comment by rjmholt** [comment]
Ah that's very helpful, thanks @OfficialEsco!

> ```
> winget install pwsh (or not really since Powershell stable also uses this)
> ```

Hmmmm, preview should really be `pwsh-preview` I think. That's how it's intended to be exposed on the command line. But if winget is focused on the MSI, and the MSI installs a pwsh.exe (which we alias through a cmd script), then maybe we can't do that?

**Comment by OfficialEsco** [comment]
You can add `pwsh-preview` to either one of these and it will work

https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
> Commands: List of commands or aliases to run the package

https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
> Tags: List of additional package search terms

**Comment by KevinLaMS** [comment]
I am marking this external for powershell to resolve.  winget is not taking any action on this issue perse.  Yell if I got that wrong.
