### ISSUE TITLE
Package Request: Chatterino

### ISSUE THREAD

**Issue by killertofus** [microsoft/winget-pkgs#22593]
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:fourtf

**Publisher Url**: https://chatterino.com/

**Package Name**: chatterino

**Package Url**: https://chatterino.com/

**Description**: Chatterino 2 is a chat client for Twitch.tv.

**Package Version**: 2.3.2

**Installer URL**: https://github.com/Chatterino/chatterino2/releases/download/v2.3.2/Chatterino.Installer.exe or https://chatterino.fra1.digitaloceanspaces.com/bin/2.3.2/Chatterino%20Installer.exe

## For new versions:

**Current Package Identifier**:

**Comment by killertofus** [comment]
would also need the vc_redist.x64 to be insatlled along with it `ExecWait "$INSTDIR\vcredist_x86.exe /install /quiet"` should work

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/11099#issuecomment-823041143
https://github.com/microsoft/winget-pkgs/pull/16022#issuecomment-854040392

**Comment by Trenly** [comment]
[Policy] Unblocked
