### ISSUE TITLE
Winget packages cache is running behind the CI?

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#2274]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&template=Bug_Report.md&title=}

# Brief description of your issue

`winget search <recent package name i.e. openmpt>` is not showing any results despite the pr being merged 3 hours ago (https://github.com/microsoft/winget-pkgs/commit/b860fa1796ececa8ba74485868d1968ac00d7430), the CI passing, and commits being submitted after it (but are also being excluded).

# Steps to reproduce

`winget search openmpt`

# Expected behavior

openmpt's listing

# Actual behavior
```
 super@DESKTOP-123456  ~  winget show openmpt
No app found matching input criteria.
```

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.329
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by JohnMcPMS** [comment]
The CDN was stuck on an older version of the file and wasn't updating.  We have some ideas to investigate as to what is causing this, but for now I have purged the CDN and it appears to be up to date now:

```
PackageFullName   : Microsoft.Winget.Source_2020.707.556.192_neutral__8wekyb3d8bbwe
```

```
> winget search docker
Name                Id                       Version       Matched
--------------------------------------------------------------------------
Docker Desktop      Docker.DockerDesktop     2.3.0.3.45519 Moniker: docker
Docker Desktop Edge Docker.DockerDesktopEdge 2.3.2.1.46329
```

In addition, we obviously need to put in a watchdog to ensure that the CDN is actually taking updates.

**Comment by nbros** [comment]
Hello @JohnMcPMS,
The CDN is falling behind again: the PR on #3183 for updating to Calibre 4.23.0 was merged 3 days ago but winget is still returning 4.21.0.

**Comment by JohnMcPMS** [comment]
@nbros, this appears to be a different issue. Looking into it more now.

**Comment by JohnMcPMS** [comment]
We have resolved the issue and everything appears to be up to date.  There was one hiccup in the back end that shouldn't affect clients, but if you see anything else let us know.  Closing this issue in favor of new ones being opened.
