### ISSUE TITLE
astiga request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#22763]
PackageIdentifier: astiga
PackageVersion: 0.1.2
PackageLocale: en-US
Publisher: Koen
PackageName: astiga
License: proprietary
ShortDescription: listen music to the cloud
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://s3.eu-central-1.wasabisys.com/astiga-dist/astiga%20Web%20Setup%200.1.2.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by KevinLaMS** [comment]
i have submitted PR   ###https://github.com/microsoft/winget-pkgs/pull/22923

**Comment by KevinLaMS** [comment]
I have submitted PR #22923 22923
