### ISSUE TITLE
Kartik

### ISSUE THREAD

**Issue by Minteck** [microsoft/winget-pkgs#22774]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Me (@Minteck)

**Publisher Url**: https://github.com/Minteck

**Package Name**: Kartik

**Package Url**: https://kartik.hopto.org

**Description**: Kartik is a cross-platform simple 2D car racing game

**Package Version**: 21.07

**Installer URL**: https://kartik.hopto.org/cdn/release/stable/0/windows (the installer URL is version-independent and will always download the latest version on the selected branch, here `stable`)

## For new versions:

**Current Package Identifier**:

**Comment by vedantmgoyal2009** [comment]
Zip installers are currently not supported by winget.

**Comment by Minteck** [comment]
> Zip installers are currently not supported by winget.

Got it. It is possible perhaps that in the near future I make it build an MSI package instead of a ZIP file, which if I do I'll probably reopen the issue.
