### ISSUE TITLE
droidcamobs Request

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#22977]
PackageIdentifier: Droidcamobs
PackageVersion: 1.3
PackageLocale: en-US
Publisher: droidcamobs
PackageName: droidcamobs
License: open source
ShortDescription: webcam emulator between smartphone and pc
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://files.dev47apps.net/obs/DroidCamOBS.Setup.1.3.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by KaranKad** [comment]
`OBSProject.OBSStudio` is a dependency.
