### ISSUE TITLE
Package request: Pypy

### ISSUE THREAD

**Issue by victorbnl** [microsoft/winget-pkgs#23460]
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: The Pypy Team

**Publisher Url**: https://www.pypy.org/people.html (I guess)

**Package Name**: Pypy

**Package Url**: https://www.pypy.org/index.html

**Description**: A fast, compliant alternative implementation of Python

**Package Version**: v7.3.5

**Installer URL**: https://www.pypy.org/download.html

**Comment by victorbnl** [comment]
Oops I just saw there was no installer so you'll need to wait for winget to support installing .zip files. Feel free to label or close this issue in consequence if you want

**Comment by oxygen-dioxide** [comment]
Though there isn't an official installer for pypy, there is a third party pypy distribution called winpython. I have created a pull request
https://github.com/microsoft/winget-pkgs/pull/24253

**Comment by cmp0xff** [comment]
Hi, `pypy` has arrived at 3.11, but in `winget`, we only have PyPy.PyPy.3.9. Since `winget` now supports zip, can we reopen this issue?
