### ISSUE TITLE
devkitPro.devkitPro can't be installed silently

### ISSUE THREAD

**Issue by quhxl** [microsoft/winget-pkgs#23569]
# Brief description of your issue

This installer will not install any program unless this is explicitly selected in the interactive installer.

# Steps to reproduce

`winget install devkitPro.devkitPro` 

# Expected behavior

devkitPro gets installed

# Actual behavior

This installer will not install any program unless this is explicitly selected in the interactive installer.

# Environment

```none
Windows Package Manager v1.0.11591
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.21996.1
Package: Microsoft.DesktopAppInstaller v1.11.11591.0
```

**Comment by quhxl** [comment]
Should the package be removed?

**Comment by jedieaston** [comment]
Yes.
