### ISSUE TITLE
Lightshot package bad hash

### ISSUE THREAD

**Issue by JonLevin25** [microsoft/winget-pkgs#23757]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Installing lightshot (`Skillbrains.lightshot`) fails with the error `Installer hash does not match; to override this check use --force`
It could be malacious, but I assume  this is just a config issue.
it seems like the install link is `https://app.prntscr.com/build/setup-lightshot.exe` - I assume that's a permalink for the latest package? If so the hash will obv change.

Is there a solution for a case like this? It seems like a symptom of a larger problem with permalinks and versioning/hashing.

# Steps to reproduce
run `winget install Skillbrains.lightshot` on a system that does not have it

# Expected behavior
It will download and install the package without problems

# Actual behavior
Installer downloads the executable, but fails to run it stating the hash does not match.

# Environment

```none
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by denelon** [comment]
Lightshot was removed from the repository. We're not able to download and validate the package.
