### ISSUE TITLE
Request for IrfanView plugin

### ISSUE THREAD

**Issue by cheesecracker** [microsoft/winget-pkgs#23933]
# Package Requested
IrfanView plugin

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Irfan Skiljan

**Publisher Url**: https://www.irfanview.com/

**Package Name**:  Irfanview-plugin ??

**Package Url**:  N/A

**Description**:  Irfanview plugin is important in some situations.  It just adds a few tens of MB in the hard disk.  With today's standard in computer storage, the additional space can be considered as "nothing".

**Package Version**: N/A

**Installer URL**:  https://www.fosshub.com/IrfanView.html?dwl=iview458_plugins_x64_setup.exe

## For new versions:

**Current Package Identifier**:

**Comment by ItzLevvie** [comment]
According to FossHub's ToS - we are unable to add applications from this website.

IrfanView Plugin is currently not able to be added because it has a dependency on IrfanView and WinGet currently does not have dependency support for applications yet.

**Comment by chbwien** [comment]
> According to FossHub's ToS - we are unable to add any applications from this website:
> ![image](https://user-images.githubusercontent.com/11600822/128395825-77f1c085-859d-42e9-a79e-8efa4e215c1f.png)
> 
> IrfanView Plugin is currently not able to be added to the repository because it has an install-time dependency on IrfanView and WinGet currently does not have dependency support for applications yet.

At least the singleton 1.0 has entries for package dependencies...
https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
The question is: Are they working as expected?

**Comment by ItzLevvie** [comment]
>At least the singleton 1.0 has entries for package dependencies...
Multi-file manifests have it too: https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json#L213-L230.

> The question is: Are they working as expected?
No, WinGet will ignore it even if you added it to your manifest as the code in winget-cli to understand and install dependencies hasn't been implemented yet.

**Comment by denelon** [comment]
Fosshub TOS

**Comment by cheesecracker** [comment]
It's a pity that this has no solution.  I suppose unless the author IrfanView comes and solve the problem himself, there's no way out. 🤔

**Comment by garretwilson** [comment]
Was the issue here the lack of winget support for dependencies? Is this functionality available now? See microsoft/winget-cli#163 and https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23163%20-%20Dependencies.md . It's unclear whether this has been implemented.
