### ISSUE TITLE
Easy way to submit package yaml

### ISSUE THREAD

**Issue by StefanKoell** [microsoft/winget-pkgs#2399]
I'm the author of [Royal TS](https://github.com/microsoft/winget-pkgs/tree/master/manifests/RoyalApps/RoyalTS). I searched through the issues and couldn't find something similar, so here we go: 

# Description of the new feature/enhancement
As the subjects states: an easier way to submit packages is needed. I'm using a completely automated CI pipeline (Azure Devops) and I tried to automate the package submission using a PR by script. This is extremely hard (for me). I'm not a git guru but after spending days, I wasn't able to make it work reliably.

# Proposed technical implementation details (optional)

Like chocolatey, provide a simple command line tool where a new package yaml file can be submitted.

Alternatively, provide a solid working sample or an Azure Devops task which makes the submission easier.

Thanks for listening. I really would like to update the yaml with each of my release.

Stefan

**Comment by denelon** [comment]
@StefanKoell we are working on both a reference implementation on how to automate the submission, and tooling to make it easier to generate/submit manifests.

**Comment by denelon** [comment]
We are building a tool that will help create manifests and submit PRs.

**Comment by vedantmgoyal2009** [comment]
@StefanKoell WinGetCreate is now available to create manifests. By the way, you can also YamlCreate.ps1 script present in the Tools folder of this repository.

@denelon Can this issue be closed now?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-create support CI/CD scenarios.
