### ISSUE TITLE
API to push new packages/versions

### ISSUE THREAD

**Issue by secana** [microsoft/winget-pkgs#2401]
# Description: Add API to push new packages/versions

Add an easy to you API where a new setup and the corresponding manifest can be pushed to, which creates an PR to add or update the submitted setup.

## Why?

I tried to implement a CD pipeline with Azure DevOps that automatically builds and publishes a new setup to *winget-pkgs*. As the current workflow needs a PR I have to do the following non-trivial steps:

1. Create a Azure Pipeline (or any other CI/CD system)
2. In that pipeline build the setup 
3. Create a fork of the *winget-pkgs* repo from the Pipeline
4. Add the package to the fork
5. Create a PR from the fork to the upstream repo

This is very complicated and needs a lot of "git-in-git" magic.

# Proposed technical implementation details (optional)

I would like something like this:

1. Create a Azure Pipeline (or any other CI/CD system)
2. In that pipeline build the setup 
3. Push the setup with the manifest to some REST endpoint and be done with it.

This approach would be inline with most other package managers e.g. NuGet, NPM, Docker etc.

**Comment by denelon** [comment]
This is very similar to #2399

**Comment by secana** [comment]
@denelon you are right. I did not see the other issue when I searched for similar ones. 

Closed as duplicate of #2399
