### ISSUE TITLE
winget install JetBrains.dotUltimate installer keeps running after it is finished installing

### ISSUE THREAD

**Issue by denska** [microsoft/winget-pkgs#24025]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

winget install -exact JetBrains.dotUltimate --override /SpecificProductNames=ReSharper installer does not stop when it is finished installing. Not even with --interactive, when you manually click exit button after installing. The AppInstallerCLI.exe keeps running until what I assume is a timeout.

# Steps to reproduce

Run
winget install --exact JetBrains.dotUltimate --interactive --override /SpecificProductNames=ReSharper
or
winget install --exact JetBrains.dotUltimate --override /SpecificProductNames=ReSharper

# Expected behavior

JetBrains.dotUltimate gets installed in like max 10 min and moves on.

# Actual behavior

 JetBrains.dotUltimate gets installed, but the installer does not know it is finished, so it keeps going until it (propably) times out after at least 45min. 

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11451
Windows: Windows.Desktop version v10.0.18363.1679
Package: Microsoft.DesktopAppInstaller version v1.11.11451.0 

Any other software?
```

**Comment by ItzLevvie** [comment]
Could it be that you're missing some switches?

There's already a ReSharper package and you can do `winget install JetBrains.ReSharper` to install it.

Last time I installed it there was no installation hangs.
