### ISSUE TITLE
[YamlCreate.ps1] Prompt for FamilyName and SignatureSha265

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#24066]
## Description of the new feature/enhancement
Prompt user to enter SignatureSha256 and FamilyName for MSIX and APPX installers.

# Proposed technical implementation details (optional)
if (InstallerType -eq 'msix' -or InstalerType -eq 'appx') {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Prompt to enter FamilyName and SignatureSha256
}

Since I don't know anything about YAML Parsing, @Trenly please implement it in #21204

**Comment by Trenly** [comment]
@OfficialEsco I'm out of town for the next few days; Is this something you would be able to grab?

**Comment by vedantmgoyal2009** [comment]
Resolved in the above PR.
