### ISSUE TITLE
Gitkraken hash doesnt match

### ISSUE THREAD

**Issue by orion160** [microsoft/winget-pkgs#24209]
Winget install doent work, the hash doesnt match

- [ X] I would like someone else to build the manifest.

Version: 7.7.1
Publisher: Axosoft, LLC
Author: Axosoft, LLC
Moniker: gitkraken
Description: Legendary Git GUI client for Windows, Mac & Linux.
Homepage: https://www.gitkraken.com/git-client
License: Proprietary
License Url: https://www.gitkraken.com/eula
Installer:
  Type: Exe
  Locale: en-US
  Download Url: https://release.axocdn.com/win64/GitKrakenSetup.exe
  SHA256: e4d8f1772cf389e17e7921f8664a943e7ff6e67691aa9bf28e88da3f7616d8f6

**Comment by OfficialEsco** [comment]
But the hash already is  `e4d8f1772cf389e17e7921f8664a943e7ff6e67691aa9bf28e88da3f7616d8f6`?

**Comment by ImJoakim** [comment]
> But the hash already is `e4d8f1772cf389e17e7921f8664a943e7ff6e67691aa9bf28e88da3f7616d8f6`?
> 
> And the hash matches on my end
> 
> ```
> PS C:\Users\Esco> winget install gitkraken
> Found GitKraken [Axosoft.GitKraken]
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://release.axocdn.com/win64/GitKrakenSetup.exe
>   ██████████████████████████████   149 MB /  149 MB
> Successfully verified installer hash
> Starting package install...
> Successfully installed
> ```

Same here. Installation worked perfectly fine for x64 and x86. The current hash is correct for both installers.

**Comment by orion160** [comment]
I leave my prompt, i dont know if there is a problem with locales

PS C:\Users\idbl6> winget install gitkraken
Encontrado GitKraken [Axosoft.GitKraken]
La licencia de esta aplicación fue concedida por el propietario.
Microsoft no es responsable de los paquetes de terceros, ni les concede ninguna licencia.
Downloading https://release.axocdn.com/win64/GitKrakenSetup.exe
  ██████████████████████████████   149 MB /  149 MB
El hash del instalador no coincide; para anular este control use --force

---- translated ---

PS C: \ Users \ idbl6> winget install gitkraken
Found GitKraken [Axosoft.GitKraken]
The license for this application was granted by the owner.
Microsoft is not responsible for third-party packages, nor does it grant any licenses to them.
Downloading https://release.axocdn.com/win64/GitKrakenSetup.exe
   █████████████████████████████ 149 MB / 149 MB
The installer hash does not match; to override this control use --force

**Comment by OfficialEsco** [comment]
have you tried winget source update?

**Comment by orion160** [comment]
It worked
