### ISSUE TITLE
Error trying to install virtualbox

### ISSUE THREAD

**Issue by orion160** [microsoft/winget-pkgs#24216]
- [x ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

--- 
Install prompt

PS C:\Users\idbl6> winget install virtualbox
Encontrado Oracle VM VirtualBox [Oracle.VirtualBox]
La licencia de esta aplicación fue concedida por el propietario.
Microsoft no es responsable de los paquetes de terceros, ni les concede ninguna licencia.
Downloading https://download.virtualbox.org/virtualbox/6.1.26/VirtualBox-6.1.26-145957-Win.exe
  ██████████████████████████████   103 MB /  103 MB
Hash de instalador comprobado correctamente
Iniciando la instalación del paquete...
Installer failed with exit code: 1

translation

PS C: \ Users \ idbl6> winget install virtualbox
Found Oracle VM VirtualBox [Oracle.VirtualBox]
The license for this application was granted by the owner.
Microsoft is not responsible for third-party packages, nor does it grant any licenses to them.
Downloading https://download.virtualbox.org/virtualbox/6.1.26/VirtualBox-6.1.26-145957-Win.exe
   █████████████████████████████ 103 MB / 103 MB
Installer hash checked successfully
Starting the package installation ...
Installer failed with exit code: 1

---

Encontrado Oracle VM VirtualBox [Oracle.VirtualBox]
Version: 6.1.26
Publisher: Oracle Corporation
Author: Oracle Corporation
Moniker: virtualbox
Description: VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use. Not only is VirtualBox an extremely feature rich, high performance product for enterprise customers, it is also the only professional solution that is freely available as Open Source Software under the terms of the GNU General Public License (GPL) version 2.
Homepage: https://www.virtualbox.org
License: GNU General Public License, version 2
License Url: https://www.virtualbox.org/wiki/Licensing_FAQ
Installer:
  Type: Exe
  Locale: en-US
  Download Url: https://download.virtualbox.org/virtualbox/6.1.26/VirtualBox-6.1.26-145957-Win.exe
  SHA256: eed44e66d898c17cae46a14dff1fc86ac5c321372a7fc46efcef454c1e454307

**Comment by orion160** [comment]
UPDATE
---
![image](https://user-images.githubusercontent.com/61389980/128614975-c10bc018-6fbc-4a92-b660-e4347ee87d65.png)
when trying to install in interactive mode

**Comment by walderston** [comment]
@orion160 was able to use the winget version without issue in a sandbox.

Does using the option `--silent` work for you? Wonder if it is worth to change the current switches from `-s -l -msiparams` to `--silent`

**Comment by OfficialEsco** [comment]
Uhhhhhhhhhm, i just realized the error code, @orion160 have you tried updating when running PowerShell as Administrator?

@walderston feel free to submit the PR's to fix the switches, i think Virtualbox might have more issues tho, i tried to test it out but then it just kept throwing "Update not applicable" when the InstallerType was exe,

**Comment by orion160** [comment]
@OfficialEsco i wasnt updating virtualbox, i was installing for first time virtual box in a fresh and recently reset of my PC.

Also, i am using windows 11, i dont know if there is a problem with it.

**Comment by OfficialEsco** [comment]
There is no difference between Win10 and Win11, you need to run Powershell as Administrator to install Virtualbox

**Comment by orion160** [comment]
It worked as administrator

**Comment by orion160** [comment]
It worked as administrator

**Comment by walderston** [comment]
as its worked, I'll leave it alone :)

**Comment by ImJoakim** [comment]
I'll go ahead and fix the interactive install 👍

**Comment by orion160** [comment]
Okay, it is expected behavior to run correctly as administrator, or it should be fixed?

if i am not bad, the default(aka winget install ...) does it in silent mode.

**Comment by OfficialEsco** [comment]
This is a issue on VirtualBox's side.

Winget-cli will add support for a tag which will warn that the installer requires the CMD to be run as Administrator.
