### ISSUE TITLE
League of legends regions

### ISSUE THREAD

**Issue by orion160** [microsoft/winget-pkgs#24222]
- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

It can be useful via locales, or other mechanism to redirect to other regions, LAN, LAS, EUW, etc.

example:

winget install RiotGames.LeagueOfLegends --locale es-MX

---

Version: 11.13.382.1241
Publisher: Riot Games, Inc
Description: League of Legends installer
License: Limited License
Installer:
  Type: Exe
  Download Url: https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
  SHA256: 17b74e5962f1a6e3ade07f493b1627699715e7e0cca6732b9b7772269d65e984

**Comment by quhxl** [comment]
Is this related to #16349?

**Comment by orion160** [comment]
yes, it is.

**Comment by albertopasqualetto** [comment]
It would be useful if a locale could overwrite the download url in order to select the right server.
