### ISSUE TITLE
WinGet does not report version number for Sigil

### ISSUE THREAD

**Issue by aps9** [microsoft/winget-pkgs#24325]
# Brief description of your issue

After installing Sigil 1.7.0, the version is listed as Unknown.

# Steps to reproduce

(1) Open a command prompt as administrator.
(2) winget install sigil
(3) winget list sigil

(4) (Optional) winget upgrade sigil

# Expected behavior

It should show the current version as 1.7.0 (or newer).

It should not try to upgrade with the latest version already installed.

# Actual behavior

```
Name  Id                Version Available Source
------------------------------------------------
Sigil Sigil-Ebook.Sigil Unknown 1.7.0     winget
```

WinGet shows Unknown as the version.  The application itself can be opened from the Start menu and it correctly shows version 1.7.0.

Also, at step 4, WinGet tries to upgrade it, even though the newest version is installed.

# Environment

```
[winget --info]
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software? n/a
```

I don't know whether this is an issue with WinGet, or the Sigil installer, or the Sigil manifest, or something else altogether.

Thank you.

**Comment by ItzLevvie** [comment]
https://github.com/microsoft/winget-cli/issues/1356#issuecomment-895409232

**Comment by OfficialEsco** [comment]
This will be fixed in the next version of Sigil since the dev(s) over there are awesome :)

**Comment by denelon** [comment]
@OfficialEsco is there a link to an issue there, or has this been resolved?

**Comment by OfficialEsco** [comment]
check mentioned issue https://github.com/Sigil-Ebook/Sigil/issues/635 🙄

Still not solved here tho because there have been no updates yet

**Comment by Trenly** [comment]
Resolved by https://github.com/microsoft/winget-pkgs/pull/32317

cc @ItzLevvie
