### ISSUE TITLE
adding compiler for 💎 Crystal language 💎

### ISSUE THREAD

**Issue by alexanderadam** [microsoft/winget-pkgs#2462]
# Package Requested

Name: Crystal language
Version: `0.35.1` and up
License: [Apache License 2.0](https://github.com/crystal-lang/crystal/blob/master/LICENSE)

# Further information

* https://github.com/crystal-lang/distribution-scripts/issues/64
* https://github.com/crystal-lang/crystal/issues/5430#issuecomment-641872261
* https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows#running-crystal-compiler-on-windows-bootstrapping

Please keep in mind that publishing Crystal on Windows is currently still not finished. So I hope that I also speak for others when I say that you are very welcome to help to bring Crystal to the Windows ecosystem if you're interested.

**Comment by rishavs** [comment]
yes to this please. Any way of installing and updating crystal on windows will great speed up the adoption of this fantastic language.

**Comment by denelon** [comment]
Is there an installer for this package? Or is it a .zip or standalone .exe?

**Comment by alexanderadam** [comment]
No, there's no installer yet. Currently there's just [this build instruction](https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows#running-crystal-compiler-on-windows-bootstrapping) to get the compiler.

My feeling is also that many of the Crystal users aren't using Windows. That's probably also one of the reasons why there's no 'proper' installation or at least some alpha binaries and I guess you'll run into open arms in case you are thinking to help out in making Windows support better.

Apart from that, some folks are using the Crystal in the WSL in case that would be easier.
I don't know what's possible with winget or what'd be the best solution here.

**Comment by rishavs** [comment]
Related discussion on Crystal repo about giving direct link to crystal.exe https://github.com/crystal-lang/crystal/issues/9843

**Comment by alexanderadam** [comment]
What kind of feedback is needed?
Did I miss answering something?

**Comment by denelon** [comment]
Bad bot coder. <-

**Comment by denelon** [comment]
I was looking at the Crystal GitHub repository. It looks like we may be close to being able to have a package WinGet can handle. I don't know how to test this, but we're adding support for .zip
* microsoft/winget-cli/issues/140

After WinGet 1.4 is GA and >50% of users have updated, we'll start accepting ,zip "installers".

It's possible to test with a preview client and a local manifest.
