### ISSUE TITLE
Forgotten pr's

### ISSUE THREAD

**Issue by qiancy98** [microsoft/winget-pkgs#2497]
I searched all the pr's that older than one day. Seems that most pr's are solved about five days ago, and thanks for your effort!
My filters:
- is:pr is:open label:Azure-Pipeline-Passed -label:Blocking-Issue -label:"Needs: Attention" updated:<2020-07-17 
- is:pr is:open no:label -is:draft updated:<2020-07-17 

There are five pr's left.
* On Powershell scripts
  - #451 (maybe we can close it now since #2378) (I add a commit just now so will not meet the filter condition)
  - #2378 (last updated 3 days ago)
* On General YAML files
  - #805 #895 (These two are last updated by Kevin 5 days ago and need review)

**Comment by denelon** [comment]
@qiancy98 I merged #2378 and the other manifests are blocked on being stand-alone apps or dependencies.

**Comment by qiancy98** [comment]
@denelon Thank you.
