### ISSUE TITLE
Can't install Microsoft Visual Studio Build Tools

### ISSUE THREAD

**Issue by Jarmos-san** [microsoft/winget-pkgs#25062]
# Brief description of your issue

Although Visual Studio Build Tools [are listed on the registry](https://winget.run/pkg/Microsoft/VisualStudio.BuildTools), I wasn't able to download it with the `winget install -e --id Microsoft.VisualStudio.BuildTools` command. It can't find the package & throws this error message:

```console
No package found matching input criteria.
```

# Steps to reproduce

Run either of this two commands:

```console
winget install -e --id Microsoft.VisualStudio.BuildTools
```

or,

```console
winget search Microsoft.VisualStudio.BuildTools
```

# Expected behavior

Visual Studio Build Tools should install automatically without any issues.

# Actual behavior

`winget` can't find `Microsoft.VisualStudio.BuildTools`

# Environment

```console
Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by quhxl** [comment]
Do you mean: `winget install -e --id Microsoft.VisualStudio.2019.BuildTools`?

**Comment by ItzLevvie** [comment]
You can find the application you want by doing `winget search <applicationName> or <packageIdentifier>` and then install it using `winget install <applicationName> or <packageIdentifier>`.

https://winget.run is on an old version of the manifests way back in March 2021 which was using the 0.1.0 schema and hasn't been updated in ages.

**Comment by Jarmos-san** [comment]
@ItzLevvie @quhxl Got it! [winget.run](https://winget.run/) appears quite outdated. But running `winget install -e --id Microsoft.VisualStudio.2019.BuildTools` did work!

Closing the thread as a non-issue.
