### ISSUE TITLE
Can not upgrade LibreOffice

### ISSUE THREAD

**Issue by rhemberger** [microsoft/winget-pkgs#25347]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Can not upgrade LibreOffice
# Steps to reproduce
```
PS C:\WINDOWS\system32> winget upgrade
Name        ID                      Version Verfügbar Quelle
------------------------------------------------------------
LibreOffice LibreOffice.LibreOffice 7.1.4.2 7.1.5.2   winget
PS C:\WINDOWS\system32> winget upgrade LibreOffice
Es wurden keine anwendbaren Aktualisierungen gefunden.
```

# Expected behavior
LibreOffice should be upgraded to 7.1.5.2

# Actual behavior
Winget does nothing

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19043.1165
Paket: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software?
```

**Comment by rhemberger** [comment]
The issue persists:
```
PS C:\WINDOWS\system32> winget list libreoffice
Name        ID                      Version Verfügbar Quelle
------------------------------------------------------------
LibreOffice LibreOffice.LibreOffice 7.1.5.2 7.2.0.4   winget
PS C:\WINDOWS\system32> winget upgrade libreoffice
Es wurden keine anwendbaren Aktualisierungen gefunden.
PS C:\WINDOWS\system32> winget install libreoffice
Gefunden LibreOffice [LibreOffice.LibreOffice]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://download.documentfoundation.org/libreoffice/stable/7.2.0/win/x86_64/LibreOffice_7.2.0_Win_x64.msi
  ██████████████████████████████   323 MB /  323 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
```

**Comment by denelon** [comment]
@rhemberger was the earlier version installed using the Windows Package Manager, or was it from another source? In some cases this can happen when the installer type doesn't match. In other cases, this can be caused by product codes in an .msi.

**Comment by rhemberger** [comment]
I have been using LibreOffice since it split from OpenOffice. I don't remember there ever being anything other than an msi installer.
Direct download https://download.documentfoundation.org/libreoffice/stable/7.1.5/win/x86_64/LibreOffice_7.1.5_Win_x64.msi has a product code {1B2877FB-50CD-49C9-9433-CFBBFC89C5B7} in the file attributes. https://github.com/microsoft/winget-pkgs/blob/master/manifests/l/LibreOffice/LibreOffice/7.1.5.2/LibreOffice.LibreOffice.installer.yaml has ProductCode: '{4F0D0C39-A2CD-4908-AA4C-A1CC9BDCD71A}'.
Does this prevent both upgrade-to and upgrade-from?
Doing software packaging for my company  for a decade the product code was never useful for anything at best.

**Comment by ItzLevvie** [comment]
Product Code in that manifest looks good to me:
![image](https://user-images.githubusercontent.com/11600822/130229983-d46f9bc2-e622-481e-a04e-694e44511081.png)

`{1B2877FB-50CD-49C9-9433-CFBBFC89C5B7}` is the **Package** Code
`{4F0D0C39-A2CD-4908-AA4C-A1CC9BDCD71A}` is the **Product** Code

**Comment by denelon** [comment]
@rhemberger I was going to test this morning, and I see a newer version 7.2.0.4.

Sadly I got the MSI error code 1603, so I'll have to set up a different environment to test in.

The product code can help with matching in Apps & Features to make sure the upgrade is detecting the correct product. Since it's essentially always been an MSI, that shouldn't cause any trouble.

I attempted to install 7.1.5.2 the previous version to test upgrade to 7.2.0.4. I forgot how big it is :) 


```
PS C:\Users\denelon> winget install LibreOffice -v 7.1.5.2
Found LibreOffice [LibreOffice.LibreOffice]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.documentfoundation.org/libreoffice/stable/7.1.5/win/x86_64/LibreOffice_7.1.5_Win_x64.msi
  ██████████████████████████████   314 MB /  314 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\denelon\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-LibreOffice.LibreOffice.7.1.5.2-2021-08-20-08-21-53.503.log
```

**Comment by denelon** [comment]
OK, I used the same sandbox script that @ItzLevvie showed in her screenshot. I was able to install the previous version and perform an upgrade from 7.1.5.2 to 7.2.0.4. It appears to have worked. Next I'll try the 7.1.4.2 to 7.1.5.2 scenario.

```
--> Installing the Manifest 7.1.5.2                                                                                                                         
Found LibreOffice [LibreOffice.LibreOffice]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.documentfoundation.org/libreoffice/stable/7.1.5/win/x86_64/LibreOffice_7.1.5_Win_x64.msi
  ██████████████████████████████   314 MB /  314 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

PS C:\Users\WDAGUtilityAccount\Desktop\Tools> winget upgrade
Name           Id                      Version     Available   Source
---------------------------------------------------------------------
Microsoft Edge Microsoft.Edge          90.0.818.66 92.0.902.78 winget
LibreOffice    LibreOffice.LibreOffice 7.1.5.2     7.2.0.4     winget
PS C:\Users\WDAGUtilityAccount\Desktop\Tools> winget upgrade LibreOffice
Found LibreOffice [LibreOffice.LibreOffice]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.documentfoundation.org/libreoffice/stable/7.2.0/win/x86_64/LibreOffice_7.2.0_Win_x64.msi
  ██████████████████████████████   323 MB /  323 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\Tools>
```

**Comment by denelon** [comment]
@rhemberger it appears 7.1.4.2 has been removed. Can you upgrade to 7.2.0.4?

https://github.com/microsoft/winget-pkgs/pull/17117
https://github.com/microsoft/winget-pkgs/pull/24961

**Comment by rhemberger** [comment]
Please read #https://github.com/microsoft/winget-pkgs/issues/25347#issuecomment-902175992

**Comment by denelon** [comment]
@rhemberger thanks, I missed that one. I'm not sure why 7.1.4.2 was removed other than someone was getting a 404. 

Can you submit a [feedback report](https://aka.ms/winget-feedback) so we can see the logs? Once it's done, please share the URL back here.

I'm wondering if downloading the MSI and running it would fail or succeed, but I would like to get logs before you try that.

**Comment by rhemberger** [comment]
```
PS C:\WINDOWS\system32> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            Deutsch (Deutschland)

```

**Comment by rhemberger** [comment]
Sorry, I don't have this app. And as you kann see, winget upgrade choked, but winget install did it's job; downloading  the MSI and running it succeeded. 
Es wurden keine anwendbaren Aktualisierungen gefunden. =  No applicable updates were found.

**Comment by denelon** [comment]
Since you don't have the feedback app would you mind sharing logs from the previous few days? You can see the log path via `winget --info`.

**Comment by rhemberger** [comment]
https://1drv.ms/u/s!Apvy8p3RTS0WsxLNZcsQhzEUWnxt?e=dP8F17

**Comment by rhemberger** [comment]
For the records:
2021-08-19 21:07:15.055 [CLI ] Installer [X64,Msi,Unknown,en-US] not applicable: Installer locale is not compatible with currently installed locale: en-US not compatible with de-DE
2021-08-19 21:07:15.056 [CLI ] Installer [X86,Msi,Unknown,en-US] not applicable: Installer locale is not compatible with currently installed locale: en-US not compatible with de-DE

**Comment by denelon** [comment]
That might be a misunderstanding for the original manifest author (probably very hard to find in the history in manifest schema 0.2.0). The installer locale is generally used for installers compiled for a specific language. The manifest locale is more about localized metadata like description, package name, publisher, etc.

It's been a long time since I've used Libre Office (I did use Open Office in the past), but I believe the installer is compatible with multiple languages back then. If that's the case now, then the installer locale should likely be removed.

@ImJoakim I think you submitted the most recent manifest. Can you confirm if removing the installer locale would have a negative impact?

**Comment by rhemberger** [comment]
For our Swedish or Norwegian clients almost all programs are en-us. And some people might prefer another locale than the system locale for other reasons. 
Afaics `InstallerLocale: en-US` is in almost every *.installer.yaml. Presumably, none of these manifests can "upgrade" on non en-US systems.
Imo the code should be reconsidered. Imo the inconsistency between `winget install` and `winget upgrade` should be eliminated.

**Comment by denelon** [comment]
@rhemberger I agree the inconsistency needs to be resolved. The locale related to the installer is critical for packages like [Firefox](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/91.0/Mozilla.Firefox.installer.yaml) with 10s of installer nodes due to localization.

[InstallerLocale](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/installer.md#installerlocale) is optional and would only be blocking if a requirement was set in [settings](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#locale).

**Comment by MarkusKepert** [comment]
Another hint when installing LibreOffice 7.2 (after uninstall 7.1 with winget)

Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Installer failed with exit code: 3010

extract from log:
MSI (s) (BC:C0) [12:14:06:630]: Das Produkt wurde durch Windows Installer installiert. Produktname: LibreOffice 7.2.0.4. Produktversion: 7.2.0.4. Produktsprache: 1031. Hersteller: The Document Foundation. Erfolg- bzw. Fehlerstatus der Installation: 0.

MSI (s) (BC:C0) [12:14:06:630]: Für Windows Installer ist ein Neustart des Systems erforderlich. Produktname: LibreOffice 7.2.0.4. Produktversion: 7.2.0.4. Produktsprache: 1031. Hersteller: The Document Foundation. Typ des Systemneustarts: 2. Ursache des Neustarts: 1.

Means: Installer succeded, but request system reboot. But: Winget recognice this as failure. Should be better output.

**Comment by timdhoffmann** [comment]
I was able to upgrade LibreOffice `7.2.1.2   -->   7.2.2.2` by elevating the command with `gsudo`:
```
gsudo winget upgrade --all -h
```
It still claimed `Installer failed with exit code: 3010` but LibreOffice seems to be upgrade correctly regardless. See this post: https://github.com/microsoft/winget-cli/issues/248#issuecomment-904427172.

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your issue still persists. 

If the issue does continue to persist, please open a new issue, and be sure to include any applicable logs from the upgrade attempt. Thank you!

###### Close with reason: Stale;
