### ISSUE TITLE
Add codes to messages from bots

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#25594]
# Description of the new feature/enhancement

It would be nice if there were codes or unique strings in messages from the bots. I get a lot of e-mail and I'd like to have a trivial way to exclude messages from the bots. It would make building e-mail filtering rules much easier. 
>Note: This does mean replies with copied messages might still get filtered out.

# Proposed technical implementation details (optional)

@wingetbot & @msftbot should add some unique strings when they post responses on issues and PRs to make it easier to filter them out.

**Comment by denelon** [comment]
I'm thinking about adding something like the example below for each message from a bot.

wingetbot template: "description" message

-or-

msftbot template: "description" message

eg.
```
@<author>,
Thank you for your submission.
Various [GitHub labels](https://docs.microsoft.com/windows/package-manager/package/winget-validation) will be applied during validation.
[Validation Pipeline|<status>] [Publish Pipeline|<status>]

wingetbot template: initial PR message
```

>Note: some of the messages from wingetbot may not be directly modified as they are part of the built in responses. We will look into options for those messages.

**Comment by vedantmgoyal2009** [comment]
I think one comment would be better but it could be difficult to implement. The user would see his/her PR status in the form of badges. 
```
@<author>,
Thank you for your submission.
Pull Request Status : [Azure-Pipeline-Passed: <Running|Failed|Success>] [Validation-Completed: <Failed|Success>] 
Pipeline Status: [Validation Pipeline Badge] [Publish Pipeline Badge]
Error: <name and description of any error e.g. Validation-Executable-Error, Binary-Validation-Error, etc..>
```

**Comment by denelon** [comment]
I think attempting to update comments would be problematic. Every time validation is triggered again, the labels get reset. We might consider something like this in the future, but for now, the goal is to make it easier to add rules to e-mail clients to help filter the noise. 

I could for example filter out "msftbot template" and "wingetbot template" to ignore *all* of them, or I could filter on "initial PR message" to filter just those out.

**Comment by vedantmgoyal2009** [comment]
> I think attempting to update comments would be problematic. 

Like @msftbot updates the original PR comment by appending "Microsoft Reviewers: Open in Codeflow", can't it do for this comment? 

> Every time validation is triggered again, the labels get reset.

They are badges (I mean this [![Gitter](https://img.shields.io/gitter/room/Microsoft/winget-pkgs)](https://gitter.im/Microsoft/winget-pkgs)), not labels. Only the drawback is that there would be too many endpoints at your end.

> We might consider something like this in the future, but for now, the goal is to make it easier to add rules to e-mail clients to help filter the noise.

In future, we are looking forward to fully automated PRs. I know the logic will be too complex but nothing is impossible.

**Comment by denelon** [comment]
We are also looking forward to fully automated PRs 😊. We started it too soon. That's what led to moderation. We would love to get to a point where community moderation isn't necessary. That's a lofty goal, and as you said "nothing is impossible". It's going to take time and work.

**Comment by vedantmgoyal2009** [comment]
> We are also looking forward to fully automated PRs 😊. We started it too soon. That's what led to moderation. We would love to get to a point where community moderation isn't necessary. That's a lofty goal, and as you said "nothing is impossible". It's going to take time and work.

Well, I tried to automatically generate manifests and submit PRs for packages that are shipped through GitHub releases (e.g. Brave Browser, Joplin, Jackett) but my API limit was exhausted while making the script.

**Comment by denelon** [comment]
If any of those are open source, you might try creating issues for them to integrate the Windows Package Manager Manifest Creator into their CI/CD pipelines. We have seen a couple of examples for doing that with GitHub actions. It seems like a better approach for an Independent Software Vendor or publisher to be responsible for adding their own packages to the repository.

**Comment by Trenly** [comment]
@denelon - This should be trivial to do for MSFTbot now that config as code is out; Is this feature still something which we should consider?

**Comment by denelon** [comment]
I still think it would add value :)

**Comment by Trenly** [comment]
Partially resolved by https://github.com/microsoft/winget-pkgs/pull/66350

Wingetbot still has some learning to do

**Comment by denelon** [comment]
@Trenly, You've been driving the e-mail filter paths for msftbot. I've assigned this to @hackean-msft for the back end wingetbot messages. I'll have him work with you on the codes when he picks this Issue up to work on it.

**Comment by denelon** [comment]
@Trenly we're somewhat limited on a few of the messages that are being sent by Azure DevOps, but if you can share examples of messages from @wingetbot that should have a:
Template wingetbot/foo/bar/baz

We can look at those to see what can be done :)

**Comment by Trenly** [comment]
> @Trenly we're somewhat limited on a few of the messages that are being sent by Azure DevOps, but if you can share examples of messages from @wingetbot that should have a: Template wingetbot/foo/bar/baz
> 
> We can look at those to see what can be done :)

Some of them I think are coming from rules outside fabricbot too; Or at least I'm not able to find the source of them

<table>
<tr>
<td>Link
<td>Code
<tr>
<td><a href="https://github.com/microsoft/winget-pkgs/pull/93292#issuecomment-1376300536">https://github.com/microsoft/winget-pkgs/pull/93292#issuecomment-1376300536</a>
<td>Template: msftbot/validationCompleted (Note - please also remove the @ mention)
<tr>
<td><a href="https://github.com/microsoft/winget-pkgs/pull/93365#issuecomment-1376549317">https://github.com/microsoft/winget-pkgs/pull/93365#issuecomment-1376549317</a>
<td>Template: wingetbot/pipelineStatus (Note - can these also be linked to the actual pipelines like the readme file?)
<tr>
<td><a href="https://github.com/microsoft/winget-pkgs/pull/93339#issuecomment-1375674325">https://github.com/microsoft/winget-pkgs/pull/93339#issuecomment-1375674325</a>
<td>Template: wingetbot/validationError/urls
</table>

These were the only ones I was able to find at the moment

**Comment by hackean-msft** [comment]
@Trenly pinging this issue to ask if this is still valuable.

**Comment by Trenly** [comment]
@hackean-msft - I think that with the majority of messages now coming from the github-policy-service (and those already have the codes), there is not a need to add additional ones to wingetbot at this time.

I'm good considering this closed if @denelon is

**Comment by Trenly** [comment]
Close with reason: Complete;
