### ISSUE TITLE
WinGetSvc-Validation complains that EXE type does not support non-existent switches

### ISSUE THREAD

**Issue by jazzdelightsme** [microsoft/winget-pkgs#258]
**Repro steps:**
1. Write a manifest for an EXE installer type, with Custom and InstallLocation switches. (Example: #256)
2. Submit a PR for it.

**Expected result:**
Either it all works, or the validation error I get makes sense.

**Actual result:**
```
##[warning] Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
```

My manifest does not have "Silent" or "SilentWithProgress" switches, so I don't understand what the warning is about.

The switches that it *does* have (Custom and InstallLocation) seem to work fine, so...

**Comment by superusercode** [comment]
I am also confused as to how to even implement switches for exe files. Is there a good example for this?

**Comment by denelon** [comment]
@jazzdelightsme the warning currently appears unless you have both "Silent" and "SilentWithProgress" switches in the manifest. The PR shouldn't automatically "fail", however.

**Comment by denelon** [comment]
@jazzdelightsme It's been a while since this issue was created. I believe we've updated the validation code several times since this happened. I believe this issue may be resolved now.
