### ISSUE TITLE
Support HTTP redirects better

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#259]
We have encountered a few different kinds of issues with the various HTTP redirects used to identify installers.  We need better error messages for these validation scenarios, and a set of capabilities to correctly handle them when validating manifests and checking installers.

**Comment by Restia666Ashdoll** [comment]
winget is not able to pick Videohelp links like Scoop does
https://github.com/microsoft/winget-pkgs/pull/1770
https://github.com/microsoft/winget-pkgs/pull/1467
On Scoop 
https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/lav-filters-megamix-np.json
https://github.com/lukesampson/scoop-extras/blob/master/bucket/foobar2000.json

**Comment by denelon** [comment]
It seems foobar2000's author/publisher would prefer not to be included in the Windows Package Manager.

https://hydrogenaud.io/index.php?topic=119506.0

Redirect support has been implemented so manifests behind redirects and range requests (that the client can navigate through) are now supported.

**Comment by EndlessBernkastel** [comment]
@denelon You still do not support videohelp links like Scoop. Some apps like Lav Filters Megamix are uploaded to Videohelp by the authors themselves and winget cant accept those links(unlike Scoop).
https://github.com/microsoft/winget-pkgs/pull/1467

Regarding foobar2000, the author didnt gave any input on winget on this. It was just a suggestion from another dev. Scoop supports foobar2000 through Videohelp links. Unless Peter Pawlowski himself requests for it to be removed, we shouldnt remove it.
