### ISSUE TITLE
Package Requested SQL Server Express [2019]

### ISSUE THREAD

**Issue by herrxyz** [microsoft/winget-pkgs#25931]
# Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Microsoft

**Publisher Url**: https://www.microsoft.com

**Package Name**: Microsoft® SQL Server® 2019 Express 

**Package Url**: https://www.microsoft.com/en-us/Download/details.aspx?id=101064 (just installation helper, not program itself)

**Description**: Microsoft® SQL Server® 2019 Express, ideally add other versions (2017, ...) too

**Package Version**: tbd

**Installer URL**: tbd

**Comment by xtqqczze** [comment]
Fixed by #30090

**Comment by xtqqczze** [comment]
Package name: `Microsoft.SQLServer.2019.Express` was deleted by #59196, so this issue requires triage.

cc: @denelon

**Comment by xtqqczze** [comment]
Individual package requests:
* #69114
* #69115
* #85885 
* #85884

**Comment by kkbruce** [comment]
I saw that there was already 2019, but I listed 2022 yesterday. Do you still need 2017?

Ps. The MSSQL has no full `.exe` install type, only the initial install `.exe` type. 

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/6bad7f85-f4e4-4a70-a050-f8804f8596b5)

**Comment by kkbruce** [comment]
In that case, I will try to launch it online.

**Comment by kkbruce** [comment]
@xtqqczze confirm it.

![image](https://github.com/microsoft/winget-pkgs/assets/2024682/0c6a4ba8-cbc9-40e3-9cfb-561f3555f96c)

**Comment by Trenly** [comment]
As shown in the screenshot above, the package has been added

###### Close with reason: Package added;
