### ISSUE TITLE
The validation in sandbox command should not run as admin by default

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#26177]
# Description of the new feature/enhancement
The validation script should not use admin console to run in sandbox.

Take `tencent.tencentmeeting` as an example. This package can only really install the content files when the installer is run from a console with admin privilage. If you run it from a user mode console, the installer will actually install nothing, even `--scope machine` added. However, this installer returns nothing even under situation. So winget will believe it installed successfully. But in sandbox, all the console will start as admin, which cannot reflect what we use console normally (normally we start a console as normal user). So we need to start the validation script as usermode and check whether new programs was added.
# Proposed technical implementation details (optional)
Let the validation script start a console in user mode in sandbox and validation pipeline.

**Comment by OfficialEsco** [comment]
Well... AFAIK this is a issue with Windows Sandbox that we cannot workaround.

**Comment by lychichem** [comment]
> Well... AFAIK this is a issue with Windows Sandbox that we cannot workaround.

Emm... I'm requiring tencent team for a better installer, which may solve the issue. But I don't think they'll do anything...

**Comment by vedantmgoyal2009** [comment]
> Well... AFAIK this is a issue with Windows Sandbox that we cannot workaround.

There's a workaround. I am only stuck at implementing it in the Sandbox Test script.

**Comment by jedieaston** [comment]
Tagging @pbozzay since he works on Sandbox. Is it possible in the current sandbox configuration to enable UAC on the default account? In normal Windows I think you need to at least logoff and log on for the change to take effect (although last time I messed with it I'm 99% sure I had to reboot).

**Comment by vedantmgoyal2009** [comment]
> In normal Windows I think you need to at least logoff and log on for the change to take effect (although last time I messed with it I'm 99% sure I had to reboot).

No, there isn't any issue like this.

**Comment by jedieaston** [comment]
I just tested it in a Sandbox, enabling UAC prompts you to reboot.

**Comment by pbozzay** [comment]
@jedieaston right now we don't have a way of disabling UAC (unfortunately). In theory UAC configuration is something we can add customization for, but it would be a while until the change reached a public build...

We are hoping to add reboot support to Sandbox soon, so that would help - though it's obviously less desirable than being 'born' with the desired UAC settings. I'll take this into consideration for planning and see what we can do in the future.

**Comment by SpecterShell** [comment]
> > Well... AFAIK this is a issue with Windows Sandbox that we cannot workaround.
> 
> Emm... I'm asking tencent team for a better installer, which may solve the issue. But I don't think they'll do anything...

They have added new switches to the installer in recent versions so it can install with admin privilege now.

**Comment by Trenly** [comment]
[Policy] Area External
