### ISSUE TITLE
Request for Misfit Model 3D (Dev Build)

### ISSUE THREAD

**Issue by Lu9-ST** [microsoft/winget-pkgs#26186]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Misfit Code

**Publisher Url**: http://www.misfitcode.com/

**Package Name**: Misfit Model 3D (Development Build)

**Package Url**: http://www.misfitcode.com/misfitmodel3d/

**Description**: Misfit Model 3D is an OpenGL-based 3D model editor that works with triangle-based models. It supports multi-level undo, skeletal animations, simple texturing, command-line batch processing, and a plugin system for adding new model and image filters. Complete online help is included. The primary design goal is to be easy to use. Misfit Model 3D is no longer under active development.

**Package Version**: 1.3.8

**Installer URL**: http://downloads.sourceforge.net/misfitmodel3d/mm3d-1_3_8-win32-installer.exe

## For new versions:

**Current Package Identifier**: tbd

**Comment by kdpuvvadi** [comment]
#29462

**Comment by Trenly** [comment]
@ItzLevvie I think this can be closed when you submit your next PR?

**Comment by kdpuvvadi** [comment]
@Trenly 1.3.8 is already in the repo. As per the developer it's not stable. So, added that in the dev channel. 

```bash
$ winget search misfit
Name                  Id                           Version
----------------------------------------------------------
Misfit Model 3D       MisfitCode.MisfitModel3D     1.2.4
Misfit Model 3D (Dev) MisfitCode.MisfitModel3D.dev 1.3.8
```
