### ISSUE TITLE
Request for GameMaker: Studio 2

### ISSUE THREAD

**Issue by Lu9-ST** [microsoft/winget-pkgs#26187]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: YoYo Games Ltd.

**Publisher Url**: https://yoyogames.com

**Package Name**: GameMaker: Studio 2

**Package Url**: https://www.yoyogames.com/gamemaker

**Description**: GameMaker Studio 2 is a complete development environment for making games. It comes with a comprehensive set of tools and lets you create games for Windows, Mac, Linux, Android, iOS, HTML5, Xbox, PlayStation, and Nintendo Switch. GameMaker has helped developers create much-loved and multi-million seller games such as: Undertale, Forager, & Hyper Light Drifter.

**Package Version**: 2.3.3.574

**Installer URL**: https://www.yoyogames.com/download/studio/2

## For new versions:

**Current Package Identifier**: tbd

**Additional notes:** GameMaker: Studio 2 has been given a free tier recently which allows the user to use the IDE without any limitations other than export options. The installer for the IDE's most recent update can be found on the Installer URL.

**Comment by Trenly** [comment]
@ItzLevvie  I think this can be closed when you submit your next PR?

**Comment by Trenly** [comment]
@msftbot dependencies

**Comment by stephengillie** [comment]
It seems that this package has become added. 

```PowerShell
Name                       Id                           Version      Source
----                       --                           -------      ------
GameMaker                  YoYoGames.GameMaker.Studio.2 2024.2.0.132 winget
```
