### ISSUE TITLE
Help with Rufus.Rufus package

### ISSUE THREAD

**Issue by VlaDexa** [microsoft/winget-pkgs#26293]
The current rufus package comes as .appx, but the developer stopped releasing .appx builds of Rufus, so I think it needs to use .exe now

# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:
Rufus
**Publisher Url**:
https://rufus.ie
**Package Name**:
Rufus
**Package Url**:
https://rufus.ie

**Description**:
Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.
**Package Version**:
3.15
**Installer URL**:
https://github.com/pbatard/rufus/releases/download/v3.15/rufus-3.15.exe
## For new versions:

**Current Package Identifier**:
Rufus.Rufus

**Comment by quhxl** [comment]
The exe installers are portable apps. We are not able to support them. microsoft/winget-cli#182

**Comment by edgarchinchilla** [comment]
> The exe installers are portable apps. We are not able to support them. [microsoft/winget-cli#182](https://github.com/microsoft/winget-cli/issues/182)

No, Rufus has two versions:
- Installer
- https://github.com/pbatard/rufus/releases/download/v3.15/rufus-3.15.exe
- Portable
- https://github.com/pbatard/rufus/releases/download/v3.15/rufus-3.15p.exe

**Comment by ItzLevvie** [comment]
`rufus-3.15p.exe` is a rename of `rufus-3.15.exe`.

They're not two versions.
