### ISSUE TITLE
Unexpected restart when installing Calibre

### ISSUE THREAD

**Issue by P3t3rU5** [microsoft/winget-pkgs#26291]
# Brief description of your issue

After updating Calibre the computer restarted

# Steps to reproduce

```none
winget upgrade calibre
```

computer suddenly restarts without any warning

from event viewer:

```none
The process msiexec.exe has initiated the restart of computer  on behalf of user NT AUTHORITY\SYSTEM for the following reason: No title for this reason could be found
 Reason Code: 0x80030002
 Shutdown Type: restart
 Comment: The Windows Installer initiated a system restart to complete or continue the configuration of 'calibre 64bit'.
```

# Expected behavior

At least some kind of warning would be nice

# Actual behavior

Not to have a sudden restart out of the blue

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.168
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by Trenly** [comment]
@P3t3rU5 - Is the issue still there?

**Comment by P3t3rU5** [comment]
Hey @Trenly I don't even remember raising the issue to be honest, so I guess this can be closed

**Comment by Trenly** [comment]
Close with reason: See above;

**Comment by arielsalvo** [comment]
Can this be reopened?
The issue is still present and installing/upgrading without restart appears to be supported by the MSI installer being used.
Running the installer with `/?` shows it accepts these options to control restarts:
* /norestart:  Do not restart after the installation is complete
* /promptrestart: Prompts the user for restart if necessary
* /forcerestart: Always restart the computer after installation

**Comment by arielsalvo** [comment]
I can confirm overriding with `/norestart` will not restart the machine

```
❯ winget upgrade calibre.calibre --silent --override "/norestart"
Found calibre [calibre.calibre] Version 6.12.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/kovidgoyal/calibre/releases/download/v6.12.0/calibre-64bit-6.12.0.msi
  ██████████████████████████████   151 MB /  151 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 3010
Restart your PC to finish installation.
```

**Comment by mdanish-kh** [comment]
@arielsalvo Can you show which version of WinGet you're on through `winget --info` command? [This fix](https://github.com/microsoft/winget-cli/pull/2499) has made it's way into v1.4.10173.

**Comment by arielsalvo** [comment]
The versions match but I'll have to wait until the next upgrade from calibre to check if the machine reboots without the parameter (unless you can tell me how to downgrade and I'll be happy to test)
```
❯ winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2546
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
If you want, you can install a previous version through winget by uninstalling calibre first through `winget uninstall calibre` and then installing a previous version (let's say `6.11.0`) through `winget install --id calibre.calibre --silent --version 6.11.0`. You should have 6.12.0 listed as available upgrade after these steps.

Be sure to run the upgrade command with `--verbose-logs` (i.e., `winget upgrade calibre.calibre --silent --verbose-logs`). In case it still reboots for you, I would suggest creating a [new issue](https://github.com/microsoft/winget-pkgs/issues/new/choose) and include the logs from the Log location shown in winget --info output.

Note: I tried all these steps myself and could not reproduce your issue. I saw from logs that /norestart was being passed to the installer .

**Comment by arielsalvo** [comment]
Completely understandable.
The last time I tried without the override param may have been with the previous winget version.
I will try downgrading and upgrading again following those instructions and, if it still happens, I will open a new issue.
Thank you very much!
