### ISSUE TITLE
Split Ubuntu in different packages

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-pkgs#26805]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

The desire is to be able to:

```console
$ winget install ubuntu
$ winget install ubuntu-20.04
$ winget install ubuntu-18.04
$ winget install ubuntu-16.04
```

Instead of

```console
$ winget install ubuntu --version 18.04
$ winget install ubuntu --version 16.04
```

As all of them can coexist in the system as they have their own namespace and they receive their own minor updates.

This marks the introduction of the just "ubuntu", not versioned, the rolling release one, which is not yet available in winget.

**Comment by Trenly** [comment]
@jedieaston If the moniker were changed to be specific to each of the versions, would that result in us being able to do the `winget install ubuntu-18.04` like felipecrs suggested, or is only the latest moniker for the package used when winget calls the API?

**Comment by jedieaston** [comment]
I'm not 100% sure (haven't looked at the database schema in a bit) but I don't think that's how it works. If we just changed the monikers they'd all point to `Canonical.Ubuntu`'s latest version.

But @felipecrs is right, all of the packages have different update cadences and things that make it better to have them under separate identifiers.

**Comment by Trenly** [comment]
Moving to new PackageIdentifiers and updating Metadata -
* https://github.com/microsoft/winget-pkgs/pull/33640
* https://github.com/microsoft/winget-pkgs/pull/33641
* https://github.com/microsoft/winget-pkgs/pull/33642

Removing from old locations -
* https://github.com/microsoft/winget-pkgs/pull/33644
* https://github.com/microsoft/winget-pkgs/pull/33645
* https://github.com/microsoft/winget-pkgs/pull/33646

**Comment by felipecrs** [comment]
Amazing. We are just missing the Ubuntu (just Ubuntu) now, which can be found at https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6.

Refs https://github.com/microsoft/WSL/issues/7381

**Comment by Trenly** [comment]
With the addition of msstore as a source, the unversioned package should already be available

**Comment by felipecrs** [comment]
> With the addition of msstore as a source, the unversioned package should already be available

Not really, this only applies to systems where the IT does not block MS Store. Also, if that were rule, we would not need to have Ubuntu-16.04, Ubuntu-18.04 and Ubuntu-20.04 in the WinGet source too (as other hundreds of packages in the same situation).

**Comment by jedieaston** [comment]
Does `wsl --install -d Ubuntu` work for you with the Microsoft Store blocked? It does for me, although there's 100 different methods of blocking the MSStore so I don't know if it does in all cases.

**Comment by felipecrs** [comment]
It does not apply to me, as my company enforces the use of Windows 10 1909 which hasn't received the backport. This method only applies to Windows 10 2004 onwards.

**Comment by jedieaston** [comment]
Darn! Maybe you can send [this](https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing) to your neighborhood sysadmin and see if they can get an upgrade approved ;)

**Comment by felipecrs** [comment]
It's Enterprise edition, which means it's still supported:

https://docs.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education

**Comment by jedieaston** [comment]
Oof. This should help then, it installs the same package as `wsl --install -d Ubuntu`: https://github.com/microsoft/winget-pkgs/pull/34324

We'll just have to make sure it's up-to-date.

**Comment by felipecrs** [comment]
This is perfect! It's not up to date, the same way as most of the other Ubuntu variants in WinGet are not as well, but that's not a problem for me.

I would just suggest you to add the moniker "ubuntu" to it, so that `winget install ubuntu` would work.
