### ISSUE TITLE
Can I submit a package without a signed installer?

### ISSUE THREAD

**Issue by kimwalisch** [microsoft/winget-pkgs#2701]
Hi,

I would like to submit a package for my free open source application (single exe without any dependencies) to winget. However since this is a free application I have written in my sparse time I am not willing to buy a code signing certificate to sign my application's installer.

Does winget allow packages without a signed installer?
What type of installer do you suggest I should create for my application?

Thanks for your help.

**Comment by denelon** [comment]
@kimwalisch in order of preference: MSIX, MSI, EXE

Some formats do require a signature, but we don't require a signature in the repository here. If you have an unsigned EXE installer, that's OK. It may just take some extra time for our static analysis to complete, and for the installer to gain sufficient reputation to be approved. That is generally on the order of days.

**Comment by kimwalisch** [comment]
OK, thanks for your answer!
