### ISSUE TITLE
Approving a PR as a moderator does nothing.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#27041]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Approving a PR as a moderator doesn't do anything.

# Steps to reproduce

1. Approve a PR using a GitHub account on the magic list (#15674). 

# Expected behavior

@msftbot adds the Moderator-Approved label, and assuming all other policies pass, the PR is merged into master.
# Actual behavior

Nothing. No label, no friendly message from @msftbot, etc. No PRs have been merged for the last 50 hours or so :(. The Validation/Publishing Pipeline badges are still green, and the pipelines are still working. It's just the bot.

(I'm sorry @msftbot that I said those hurtful things about your ability to read and your favoritism of Apple Music over Spotify. If you come back it can be like old times :D).

**Comment by vedantmgoyal2009** [comment]
https://github.com/microsoft/winget-pkgs/pull/26961#issuecomment-913467796

**Comment by vedantmgoyal2009** [comment]
@denelon Please look into the issue with @msftbot.

**Comment by jedieaston** [comment]
![image](https://user-images.githubusercontent.com/21368066/132365700-16d9312f-daa9-4705-a1e3-fe9ced0d2c01.png)

*gulp*

**Comment by denelon** [comment]
Thanks for the heads-up! We're looking into it.

**Comment by denelon** [comment]
I just got a notification from the team about the "unscheduled down time" for the bot (@msftbot). The team is working on it. As soon as it's back up we'll work through the backlog.

**Comment by denelon** [comment]
It looks like the bot is back up and running again. Feel free to @mention me if there are some that need the 'Moderator Approved" label added.
