### ISSUE TITLE
OpenJS.NodeJSLTS returns a 403 error when trying to upgrade

### ISSUE THREAD

**Issue by DawMatt** [microsoft/winget-pkgs#27055]
# Brief description of your issue

The OpenJS.NodeJSLTS package does not upgrade when requested. Instead it makes two attempts to download the file, each failing, then returns a 403.

Please note this package has had problems with every single minor version upgrade I've tried via winget (at least 5 so far). Other packages install OK (e.g. Python 3). This may be an issue with the provider's hosting of the package.

# Steps to reproduce

1. Have an older version of Node.js LTS installed
2. Use `winget upgrade OpenJS.NodeJSLTS` to attempt to upgrade

Fails to install, returning a 403 error

# Expected behavior

The installer is downloaded and installed.

# Actual behavior

For a minor upgrade:

```
Name                                            Id                           Version          Available        Source
---------------------------------------------------------------------------------------------------------------------
Node.js LTS                                     OpenJS.NodeJSLTS             14.17.5          14.17.6          winget
```

I see attempts to download the installer, followed by a 403 error.

```
 winget upgrade OpenJS.NodeJSLTS
Found Node.js LTS [OpenJS.NodeJSLTS]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi
  ██████████████████████████████  0.00 B / 29.1 MB
  ██████████████████████████████  24.1 MB / 29.1 MB
An unexpected error occurred while executing the command:
0x80190193 : Forbidden (403).
```

If I take the same URL from above and try to access it via my browser I notice that it quickly downloads a portion of the file (e.g. 14 Mb), then makes no further progress for 10 or more seconds, then slowly downloads the remainder of the file. In total it takes around a minute before the browser informs me the download is complete. Once downloaded I can then manually install this package successfully.

# Environment

```none
[winget --info]
winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1165
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

**Comment by vedantmgoyal2009** [comment]
Please post the output of `winget settings`.

**Comment by jedieaston** [comment]
You aren't sitting behind a corporate proxy/VPN/firewall, are you? The weirdness with downloading it via your browser shows it's not a winget problem, but I'm curious what is going on.

**Comment by DawMatt** [comment]
> Please post the output of `winget settings`.

Included below. I'm assuming this is the default content for this file:

```json
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
}
```

**Comment by DawMatt** [comment]
> You aren't sitting behind a corporate proxy/VPN/firewall, are you? The weirdness with downloading it via your browser shows it's not a winget problem, but I'm curious what is going on.

I'm not behind a corporate proxy/VPN/firewall (on home network) but this is a work system. There is security software installed including Zscaler.

I was wondering if this was something to do with how node.js had setup their hosting of the files that caused the weird download stuttering effect. Wasn't sure whether there was something that could be done at the manifest level to work around it e.g. to tell winget to be patient and work with a longer download timeout than is the default, or to allow for more retries/errors when downloading chunks of the file?

**Comment by jedieaston** [comment]
There's a slight (very slight) possibility that part of the download instability is being caused by the default Delivery Optimization downloader. If you want to try the normal downloader, add 

```   

 "network": {
       "downloader": "wininet"
   }

```
after the comma in your settings file.

**Comment by vedantmgoyal2009** [comment]
@DawMatt Does the [above](<https://github.com/microsoft/winget-pkgs/issues/27055#issuecomment-913906118>) reply fix your issue?

**Comment by DawMatt** [comment]
@jedieaston , @vedantmgoyal2009 , I think that has actually resolved the issue.

To test this I tried to do an install rather than update as there had been no point releases since my last attempt:

```
winget install OpenJS.NodeJSLTS
```

I tried once before applying the new settings. This failed as expected.

After changing the downloader I ran the command again. This did use both of the retry attempts (the first attempt stalled for more than 30 seconds then failed) but did download the installer on the first run of the command. 

The installer returned the following during its run:

```
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
```

A quick search indicates this can be returned when the product being installed is already installed. So it looks like the workaround above downloaded the installer OK. Thanks for the help!

**Comment by DawMatt** [comment]
@jedieaston , @vedantmgoyal2009 , today was the first time I've seen an update to Node LTS in a while. Tried to upgrade it using the standard command (but with the revised settings from before):

```
winget upgrade OpenJS.NodeJSLTS
```

The download stalled for a considerable time, as before, but the download completed without requiring any retries and installed correctly.

Thanks for all the help!
