### ISSUE TITLE
Automation has determined Egnyte.EgnyteDesktopApp 3.12.0.107 reboots during installation

### ISSUE THREAD

**Issue by ChuckFerring** [microsoft/winget-pkgs#27161]
Automation has determined that Egnyte.EgnyteDesktopApp 3.12.0.107 is causing a forced reboot during installation. Installation flags should be added to avoid this or the package should be removed.

**Comment by vedantmgoyal2009** [comment]
I guess this requires a separate config file which is currently not supported by winget. Requires microsoft/winget-cli#158
