### ISSUE TITLE
Bulk Rename Utility has unknown version

### ISSUE THREAD

**Issue by BlueTooth4269** [microsoft/winget-pkgs#27208]
# Brief description of your issue

When installing Bulk Rename Utility using Winget, it does not seem to register the version correctly. After installation, it says version "unknown", still lists it in the upgrade list and reinstalls when using `winget upgrade --all`

# Steps to reproduce

Install Bulk Rename Utility using `winget install TGRMNSoftware.BulkRenameUtility -i`

# Expected behavior

The version should be registered correctly and not be "unknown".

# Actual behavior

The version is not registered correctly and is "unknown".

# Environment

```
winget --info
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1165
Paket: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by ImJoakim** [comment]
https://github.com/microsoft/winget-pkgs/issues/27206#issuecomment-915047667

**Comment by Trenly** [comment]
Close with reason: Resolved with above linked PR;
