### ISSUE TITLE
Validate for case sensitive duplication

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#27346]
# Description of the new feature/enhancement
Pipeline validation should be added for all pull requests that ensures any files added into an existing directory match existing casing

This will prevent issues such as #27329 

# Proposed technical implementation details
Test all portions of the modified directories to ensure they remain case sensitive.

Examples
```powershell
#Assume ../manifests/g/Google/Chrome/0.0.0.0 already exists
#Assume ../manifests/g/Google/Chrome/1.1.1.1 does not exist

#Changes to files in. . . 
../Manifests/* should fail validation because ../manifests/ already exists and incoming casing does not match
../manifests/G/* should fail validation because ../manifests/g/ already exists and incoming casing does not match
../manifests/g/google/* should fail validation because ../manifests/g/Google/ already exists and incoming casing does not match
../manifests/g/Google/Chrome/0.0.0.0 should pass validation because all directories exist and casing matches
../manifests/g/Google/Chrome/1.1.1.1 should pass validation because ../manifests/g/Google/Chrome/ exists and casing matches, and 1.1.1.1 is a new directory
```

**Comment by denelon** [comment]
We have been looking into these issues. They usually arise when a user is moving a package to a different directory and trying to be case sensitive with the "new" Publisher or PackageName.

**Comment by vedantmgoyal2009** [comment]
I'm not sure but doing these two things will help in detecting case-sensitivity duplication:
- in the directory where we clone winget-pkgs repository (not the winget-pkgs folder itself), we can run `fsutil.exe file SetCaseSensitiveInfo <directory> enable`
- run `git config core.ignoreCase false`

I have done the same on my computer and this helped me in detecting packages that were causing problems in https://github.com/microsoft/winget-pkgs/issues/27329. Again, not sure but if these can be implemented in the **Validation Pipeline**, we can prevent case-sensitive duplication.

**Comment by Trenly** [comment]
@denelon I thought I saw a few days ago that a PR was rejected since the path didn’t match existing casing. Do you know if this has been implemented, or if I am just misremembering?

**Comment by Trenly** [comment]
Duplicate of #7384
