### ISSUE TITLE
Genshin Impact

### ISSUE THREAD

**Issue by victorbnl** [microsoft/winget-pkgs#27389]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: miHoYo

**Publisher Url**: 

**Package Name**: Genshin Impact

**Package Url**: https://genshin.mihoyo.com/

**Description**: Floating World Under the Moonlight

**Package Version**: 2.11.2.0

**Installer URL**: https://autopatchhk.yuanshen.com/client_app/launcher/20210901_d1b7945b3e043187/GenshinImpact_install_mihoyo_20210817202902.exe

**Comment by vedantmgoyal2009** [comment]
Duplicate of #20435. This package has already been requested.

**Comment by victorbnl** [comment]
Weirdly it didn't appear in the results
