### ISSUE TITLE
packages from China can't pass azure piplines validation again

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#27435]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

#27141 #27255 #27256

On my computer, these packages install successfully. However, they can't pass validation, and get a different error each time, including "Error-Installer-Availability", "URL-Validation-Error", and "Validation-Installation-Error".

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version 1.0.11694
Windows: Windows.Desktop version 22449
Package: Microsoft.DesktopAppInstaller version 1.15.11694.0

Any other software?
```

**Comment by oxygen-dioxide** [comment]
related issue:#1937

**Comment by denelon** [comment]
@oxygen-dioxide these have all been merged.
