### ISSUE TITLE
PowerShell MSIX option

### ISSUE THREAD

**Issue by VincentJoshuaET** [microsoft/winget-pkgs#275]
I prefer to install the MSIX package. I hope it's added as well.

_Sent from my Redmi Note 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TravisEz13** [comment]
We have a MSIX that will be published to the windows store.

Unfortunately, a standalone MSIX will have limited functionality (according to Appx this is by design) and we don't plan on releasing an MSIX.
