### ISSUE TITLE
TUG.TeXLive - No package found matching input criteria

### ISSUE THREAD

**Issue by trivvz** [microsoft/winget-pkgs#27528]
# Brief description of your issue

Installation of `TUG.TeXLive` not possible although it was added as winget package.

# Steps to reproduce

Installation according to [this one](https://winget.run/pkg/TUG/TeXLive):

```
❯ winget install -e --id TUG.TeXLive
```

# Expected behavior

Package installed successfully as it was added in #8045 (and the manifest file is [here](https://github.com/yigitemres/winget-pkgs/blob/27dba79b6e073d01e03708ed642716228ba5a144/manifests/t/TUG/TeXLive/2019/TUG.TeXLive.yaml)).

# Actual behavior

```
❯ winget install -e --id TUG.TeXLive
No package found matching input criteria.
```

Searching also doesn't find it:

```
❯ winget search --id TeXLive
No package found matching input criteria.
```

# Environment

```none
❯ winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by quhxl** [comment]
It was removed due to https://github.com/microsoft/winget-pkgs/pull/19989#issue-684631000

**Comment by vedantmgoyal2009** [comment]
@quhxl my question is a bit off-topic, but is https://winstall.app also outdated?

**Comment by quhxl** [comment]
The way I observe it is up-to-date. At least a version from a recent PR is shown there as an example. (#27513 -> https://winstall.app/apps/e2eSoft.iVCam)

**Comment by quhxl** [comment]
Feel free to close this issue yourself. 😊
