### ISSUE TITLE
Wrong License Displayed

### ISSUE THREAD

**Issue by NPaudel** [microsoft/winget-pkgs#27533]
# Brief description of your issue

Microsoft's VSCode repository has MIT license. But it is only for the source code. The installer file is under a different license. But when installing Visual Studio Code using Winget, it shows MIT license, even though the installer has different license. 

# Steps to reproduce
Open Windows Terminal
Type `winget install vscode`
Press Enter key

# Expected behavior
Under license, it shows Microsoft's license for VIsual Studio Code installer.

# Actual behavior
It shows MIT license
![image](https://user-images.githubusercontent.com/54449465/133120784-021c8098-7328-424c-8aa8-6138049249f5.png)

# Environment
Windows Package Manager v1.0.11694
Windows:  Windows.Desktop v10.0.22000.184
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

**Comment by denelon** [comment]
@NPaudel, thank you for pointing this out. There is a subtle difference between the source code license and the product license. I reached out to the team, and they will be making modifications to their automated publishing process so this can be corrected.

According to [Visual Studio Code - Code Editing. Redefined](https://code.visualstudio.com/) it just has "Free. Built on open source. Runs everywhere." I think that's how the licensing is different. I did find on [License - Visual Studio Code](https://code.visualstudio.com/License/) under section 5 that the license applies to the product, but that the source code is under MIT. There is also a link to [Menu license links to non Open Source license · Issue #60 · microsoft/vscode (github.com)](https://github.com/microsoft/vscode/issues/60#issuecomment-161792005). 

Generally, I've seen "Commercial" as a generic license pointing to the license documentation. In this case, maybe "Free" is a better "license" value for the manifest, and then the link to the [License]((https://code.visualstudio.com/License/)) would be more appropriate.

**Comment by lszomoru** [comment]
Thanks @NPaudel for filing the issue, and thanks @denelon for the additional context. I have made the necessary changes to our automation so all new manifest created through the automation should have the correct license information. I will also submit pull requests to correct the old manifest so that the license information is consistent across all our manifests.

**Comment by vedantmgoyal2009** [comment]
#27804 by @NPaudel

**Comment by vedantmgoyal2009** [comment]
@lszomoru I can correct the license information in all the manifests of VSCode. Just to confirm that the following license information is correct one?
```
License: Free
LicenseUrl: https://code.visualstudio.com/License/
```

**Comment by OfficialEsco** [comment]
So, VSCode runs under this license? https://en.wikipedia.org/wiki/Free_license

> A free license or open license is a license agreement which contains provisions that allow other individuals to reuse another creator's work, giving them four major freedoms.

Which is how VSCodium works i guess?

**Comment by lszomoru** [comment]
After talking to @denelon, I have opted to match the terminology that is being used by Visual Studio:
- Stable - `Microsoft Software License`
- Insiders -  `Microsoft Pre-Release Software License`

**Comment by NPaudel** [comment]
I will make the same change to my pull request, thanks
