### ISSUE TITLE
Mobatek.MobaXterm

### ISSUE THREAD

**Issue by Mistrical** [microsoft/winget-pkgs#27576]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Mobatek

**Publisher Url**: https://www.mobatek.net/

**Package Name**: MobaXterm Home Edition

**Package Url**:  https://mobaxterm.mobatek.net/

**Description**: Enhanced terminal for Windows with X11 server, tabbed SSH client, network tools and much more

**Package Version**: 21.3

**Installer URL**: https://download.mobatek.net/2132021082033134/MobaXterm_Installer_v21.3.zip

## For new versions:

**Current Package Identifier**: 21.3

**Comment by vedantmgoyal2009** [comment]
Currently, zip installers are not supported by winget. microsoft/winget-cli#140

**Comment by Mistrical** [comment]
> Currently, zip installers are not supported by winget. [microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140)

@vedantmgoyal2009  There is an MSI installer inside the zip. Is this supported?

**Comment by vedantmgoyal2009** [comment]
> > Currently, zip installers are not supported by winget. [microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140)
> 
> @vedantmgoyal2009 There is an MSI installer inside the zip. Is this supported?

Sadly no, but I think it will be supported in the upcoming releases.

**Comment by jedieaston** [comment]
The issue for installer file inside of zip is https://github.com/microsoft/winget-cli/issues/859, fyi.

**Comment by Mistrical** [comment]
Bump
