### ISSUE TITLE
Azure Pipelines cannot post validate certain pull requests

### ISSUE THREAD

**Issue by DeusMaximus** [microsoft/winget-pkgs#27697]
Hey there,

I submitted a fairly straight forward pull request for the RSI Launcher [here](https://github.com/microsoft/winget-pkgs/pull/27695).

It's currently stuck in a loop, constantly trying to validate, failing, adding two MS devs, removing them, trying again to validate... ad infinitum.

The part where it's failing seems to be at the Post Validation step, and digging deeper, Azure Pipelines seems to be trying to apply a label to the pull request, but fails for some reason, causing the entire process (which runs successfully before this step) to fall apart, and the bot seems to not know what to do, hence causing the neverending loop of adding/removing the two devs, and spamming my poor mailbox all to hell.

I did submit an earlier version of this manifest, but the fork I had was a mess, so I closed the pull request, deleted and re-created the fork, and resubmitted the pull request in a much cleaner and less commit heavy fashion, thinking that may have something to do with it. Sadly, it didn't.

I also noticed that [this automated pull request](https://github.com/microsoft/winget-pkgs/pull/27657) seems to be suffering the same fate as mine.

By all means, if I'm doing something wrong, please let me know.

**Comment by jedieaston** [comment]
Another one: https://github.com/microsoft/winget-pkgs/pull/27580

(it’s failing, but since there’s no logs from the Installation Validation step I don’t know why. And wingetbot just keeps trying, poor thing…)

**Comment by denelon** [comment]
I think we've isolated the cause. We're working on a fix.

We also had another unrelated problem around 1:00 PM PST affecting about 60 PRs when the automatic manifest update job started.

**Comment by denelon** [comment]
I believe this has been resolved.
