### ISSUE TITLE
Have InstallerUrl point at the latest version instead of a specific version

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-pkgs#28238]
# Description of the new feature/enhancement

I browsed through the manifests, and it seems like it's mandatory to submit each package version separately. As a result, some are lagging behind. To avoid waiting for someone to submit a manifest for every update, why not permalink to the latest one instead? I think it's called a stable URL?

For example, instead of linking
https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/78.9.1/win64/en-US/Thunderbird%20Setup%2078.9.1.msi
then
https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/91.0.3/win64/en-US/Thunderbird%20Setup%2091.0.3.msi
etc, link https://download.mozilla.org/?product=thunderbird-latest&os=win&lang=en-US.

# Proposed technical implementation details (optional)

To keep the ability to select the installed version, it might make sense to just add a `latest` directory to the existing ones.

**Comment by Trenly** [comment]
Based on [this comment](https://github.com/microsoft/winget-pkgs/discussions/19171#discussioncomment-933278) I think this would be both a CLI feature and a pkgs feature, unless the 1.1 manifest schema resolves this issue

**Comment by lychichem** [comment]
It will cause some issue when updating packages, as only the latest version is kepped in the manifest list. So, unless you can't find a link directly point to the certain version, i don't suggest using latest link. However, i believe wingetbot can use a latest link to check if there is an update, and email the author who last changed the manifest. That is, an optional `latest link` key can be added to schema, it will not be used when users run `winget upgrade`, but a bot (I call it `checklatestbot`) can use it to check whether there is update.

**Comment by jedieaston** [comment]
It can only do it if it detects a SHA256 change, and it usually takes at least a day, maybe two for it to open the PR. (I do Chrome/Spotify manually a lot since they are very popular and almost always broken due to their evergreen installers). 

It seems like it used to be better at following up, but since the repo has grown so much it's slower on the uptake.

**Comment by jedieaston** [comment]
There isn't a standard, no. The automation isn't that smart, it downloads the file at the existing link in the existing manifest, if the SHA256 hash doesn't match then it opens a PR to fix it (and bump the PackageVersion if the file has a newer ProductVersion attribute). 

If you want to help us by automatically creating new manifests when you have new links, consider running `[wingetcreate update](https://github.com/microsoft/winget-create)` as part of your release process.
