### ISSUE TITLE
[Installer hash does not match] when trying to install Google chrome

### ISSUE THREAD

**Issue by BoomEarth** [microsoft/winget-pkgs#28291]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

When running winget install chrome, I receive Installer hash does not match. If I run as a standard user with the --force flag, it installs.

# Steps to reproduce

Open up powershell as admin, run winget install chrome. Then run powershell as a standard user and run winget install chrome --force

# Expected behavior

The expected behavior is for Google Chrome to install with a valid hash.

# Actual behavior

The hash doesn't match when installing.

# Environment

```none
[winget --info]
Windows: Windows.Desktop v10.0.19042.1237
Package: Microsoft.DesktopAppInstaller v1.12.11692.0


Any other software?
```

**Comment by ImJoakim** [comment]
This issue will be fixed in #28271

**Comment by ImJoakim** [comment]
@BoomEarth This should now be fixed 👍

**Comment by BoomEarth** [comment]
Very nice! Thank you!
