### ISSUE TITLE
[BitcoinCoreProject.BitcoinCore version 0.21.1] 0x80190194 : Not found (404)

### ISSUE THREAD

**Issue by ItzLevvie** [microsoft/winget-pkgs#28386]

**Comment by OfficialEsco** [comment]
![image](https://user-images.githubusercontent.com/15158490/134499184-fa8f4446-e215-42e7-a254-aee481c497af.png)

**Comment by vedantmgoyal2009** [comment]
I think I should check for installer hashes while checking response codes for download URLs.

**Comment by ItzLevvie** [comment]
> ![image](https://user-images.githubusercontent.com/15158490/134499184-fa8f4446-e215-42e7-a254-aee481c497af.png)
> https://bitcoincore.org/bin/bitcoin-core-0.21.1/

Looks like the URL changed - the manifest has the bad one: https://github.com/microsoft/winget-pkgs/blob/master/manifests/b/BitcoinCoreProject/BitcoinCore/0.21.1/BitcoinCoreProject.BitcoinCore.installer.yaml#L8

https://bitcoin.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe doesn't work
https://bitcoincore.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe works

**Comment by OfficialEsco** [comment]
> Looks like the URL changed - the manifest for 0.21.1 has the bad one: https://github.com/microsoft/winget-pkgs/blob/master/manifests/b/BitcoinCoreProject/BitcoinCore/0.21.1/BitcoinCoreProject.BitcoinCore.installer.yaml#L8
> 
>(old) https://bitcoin.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe doesn't work
> (new) https://bitcoincore.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe works

Weeeeell you see, both of the URLs work for me, in Edge and Firefox and in Sandbox 🤷‍♂️
Decided to replace the manifest because the installer is unsigned and a big leap in version anyways

**Comment by prayank23** [comment]
> (old) https://bitcoin.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe doesn't work:

>(new) https://bitcoincore.org/bin/bitcoin-core-0.21.1/bitcoin-0.21.1-win64-setup-unsigned.exe works:

The new URL is using the correct domain. 

https://bitcoin.org is maintained by @Cobra-Bitcoin
Neither it's an official website for Bitcoin nor associated with Bitcoin Core project.

https://bitcoincore.org is the website maintained by Bitcoin Core contributors and should be preferred for downloading Bitcoin Core.
