### ISSUE TITLE
Hacktoberfest 2021 topic?

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#28524]
# Description of the new feature/enhancement

[Hacktoberfest](https://hacktoberfest.digitalocean.com) is back this year. winget-pkgs participated last year and it went well (that's when my contributions started going way up anyway). I think we should participate this year too, especially as the client will now be included in Windows 11.

# Proposed technical implementation details (optional)

Same rules as last year, if the topic "hacktoberfest" is added to the repo, merged PRs count towards a user's total for the event.

**Comment by denelon** [comment]
Thanks for creating the issue! I just added the topic.
