### ISSUE TITLE
Dell Support Assist

### ISSUE THREAD

**Issue by CarlMaccabee** [microsoft/winget-pkgs#28566]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Dell

**Publisher Url**:

**Package Name**: Support Assist

**Package Url**:

**Description**: 

**Package Version**: 3.10.3.3

**Installer URL**: https://downloads.dell.com/serviceability/catalog/SupportAssistInstaller.exe

## For new versions:

**Current Package Identifier**:

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/12836

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco CarlMaccabee has requested **Dell** Support Assist, but you have given reference to the PR of **HP** Support Assist. Does it also cause the same error or is it a mistake while giving reference to PR?

**Comment by OfficialEsco** [comment]
> @OfficialEsco CarlMaccabee has requested **Dell** Support Assist, but you have given reference to the PR of **HP** Support Assist. Does it also cause the same error or is it a mistake while giving reference to PR?

O my lord you are correct, i was so sure i’ve submitted « X Support Assistant » that i forgot about the Dell part… 5AM mistake 🙄

**Comment by OfficialEsco** [comment]
Not possible anyways
![image](https://user-images.githubusercontent.com/15158490/134769589-af63243c-7bdd-485e-8bcb-38d9d2dbf724.png)

**Comment by vedantmgoyal2009** [comment]
@denelon Another package that requires custom hardware 😀

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
