### ISSUE TITLE
LibreOffice download link broken

### ISSUE THREAD

**Issue by leochras** [microsoft/winget-pkgs#28759]
# Brief description of your issue
[LibreOffices](https://github.com/microsoft/winget-pkgs/blob/master/manifests/l/LibreOffice/LibreOffice/7.2.0.4/LibreOffice.LibreOffice.installer.yaml) manifest or at least its download link seems to be broken. Other packages work fine.
# Steps to reproduce
`winget install libreoffice`
# Expected behavior
Sucessful Installation
# Actual behavior
![image](https://user-images.githubusercontent.com/16163571/134808084-ad25da18-2f2e-48e3-b02a-36b52de7ba17.png)
# Environment

```none
[winget --info]
Windows Package Manager v1.0.12581
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12581.0

```

**Comment by leochras** [comment]
Seems like it's a server side problem. I'll close this issue if they start working again..

**Comment by OfficialEsco** [comment]
You might actually be correct, i see that 7.2.1 got released, 7.2.0 might have had a critical bug so they removed it?

**Comment by ItzLevvie** [comment]
It's been moved to https://downloadarchive.documentfoundation.org/libreoffice/old/7.2.0.4/win

**Comment by OfficialEsco** [comment]
Ahaaa

7.1.5.2 also returns 404 on https://download.documentfoundation.org/libreoffice/stable/7.1.5/win/x86_64/LibreOffice_7.1.5_Win_x64.msi
However 7.0.6.2 does not on https://download.documentfoundation.org/libreoffice/stable/7.0.6/win/x86_64/LibreOffice_7.0.6_Win_x64.msi

The rest seems to use the https://downloadarchive.documentfoundation.org/libreoffice/old/ url, do only specific versions get moved?

**Comment by ItzLevvie** [comment]
> The rest seems to use the https://downloadarchive.documentfoundation.org/libreoffice/old/ url, do only specific versions get moved?

Only 7.0.6, 7.1.6, and 7.2.1 are available on https://download.documentfoundation.org; the rest seem to have been moved to https://downloadarchive.documentfoundation.org.

**Comment by leochras** [comment]
Would be nice to  have the most recent version (7.2.1) in the manifest, but it works now, thanks!

**Comment by OfficialEsco** [comment]
Here you go https://github.com/microsoft/winget-pkgs/pull/29113, i was going to do it, and add a few other locales, but its downloading at 600-800kb for some reason so i never bothered...
