### ISSUE TITLE
Still and Fresh channels for LibreOffice

### ISSUE THREAD

**Issue by 3rd3** [microsoft/winget-pkgs#28783]
LibreOffice has two release channels, one for stable versions (called "still") and one for less stable version ("fresh"). It would be nice if one could choose between the two as it is possible in Chocolatey ("libreoffice-still" and "libreoffice-fresh").

**Comment by OfficialEsco** [comment]
I assume they share the same name? We can do this with Manifest Schema 1.1.0 when we get channel support

**Comment by 3rd3** [comment]
Unfortunately, the LibreOffice download directory is not actually structured in "still" and "fresh" sections, but both can be found in the "stable" section; otherwise one could simply programmatically parse these directories.

https://download.documentfoundation.org/libreoffice/stable/

Their dowload page lists both version, though withou explicitly calling it "still" and "fresh":

https://www.libreoffice.org/download/download/

The two channels are mentioned in the release plan on their wiki:

https://wiki.documentfoundation.org/ReleasePlan

Perhaps it is always the last two stable versions?

**Comment by rdinse** [comment]
@licon4812 and @ItzLevvie added an LTS version 5 months ago. Is this supposed to be a `libreoffice-still` equivalent?

https://github.com/microsoft/winget-pkgs/pull/63980

https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TheDocumentFoundation/LibreOffice/LTS

**Comment by NJT145** [comment]
LTS needs an update. Are there any automated way to track last libreoffice-still and libreoffice-fresh versions?

**Comment by licon4812** [comment]
> LTS needs an update. Are there any automated way to track last libreoffice-still and libreoffice-fresh versions?

@NJT145  #94160

**Comment by 3rd3** [comment]
So the answer to this question appears to be 'no' since 7.3.7 is currently the "still" version, but LTS is now on "fresh" (7.4.4).
