### ISSUE TITLE
Warnings raised during pipeline runs don't create a label.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#28798]
# Brief description of your issue

If a warning is raised in a pipeline run (say, that something needs to go to manual review), there isn't an accompanying label applied to the PR to let a maintainer know they need to look at it. 

# Steps to reproduce

1. Open a PR with a manifest that will trigger a manual review warning during a pipeline step.
2. Watch as there isn't a label applied nor a maintainer assigned.

# Expected behavior

A label is applied that signifies that it isn't necessarily the PR author's fault, and a maintainer is assigned.

# Actual behavior

No label is added, and the PR author has to dig into the pipeline to see what happened (which isn't a bad first troubleshooting step, of course, but it seems like a super easy thing to expose in GitHub via a label so that it can be dealt with by a maintainer). 

https://github.com/microsoft/winget-pkgs/pull/28794 is the one I've noticed this on.

**Comment by mdanish-kh** [comment]
The bot now assigns the repo maintainers once labels such as `Needs-Attention`, `Internal-Error-<X>`, `Validation-<X>-Error` and more (see [.github/policies/labelManagement.assignIcmUsers.yml](https://github.com/microsoft/winget-pkgs/blob/master/.github/policies/labelManagement.assignIcmUsers.yml)) are added to a PR. Additionally the bot provides helpful error messages, suggesting actions for the user to fix the issue or wait for the repo maintainer.
