### ISSUE TITLE
Latest release of winget-cli broke /Tools/SandboxTest.ps1

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#28844]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
The new version of winget relies on a desktop framework that isn't yet available through the [Runtime Framwork Downloads Page](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge)

# Steps to reproduce
Use the sandbox test script for any manifest

# Expected behavior
The script executes without error

# Actual behavior

![image](https://user-images.githubusercontent.com/12611259/134994433-d5f27f3e-d333-421a-9e4e-50e7749a7409.png)

# Environment
Windows sandbox

cc @denelon

**Comment by jedieaston** [comment]
This is really weird. WinGet requires [14.0.25426.0](https://github.com/microsoft/winget-cli/blob/9bc2c1145d752307b06b3f3bcc7249da2c837585/src/AppInstallerCLIPackage/Package.appxmanifest#L19), but Add-AppxPackage seems to think differently.

**Comment by jedieaston** [comment]
Found the problem. The https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx link that is used in the Sandbox script downloads an older version of the VCLibs than winget (implictly) requires. I pulled the version that is in `%ProgramFiles(x86)%\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0` of my Visual Studio install and used it as the dependency and it worked fine.

@denelon, I don't know who owns those links, but would you mind giving them a ping and asking them to update?

**Comment by Trenly** [comment]
> Found the problem. The https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx link that is used in the Sandbox script downloads an older version of the VCLibs than winget (implictly) requires. I pulled the version that is in `%ProgramFiles(x86)%\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0` of my Visual Studio install and used it as the dependency and it worked fine.
> 
> @denelon, I don't know who owns those links, but would you mind giving them a ping and asking them to update?

I think it's interesting that the AppxManifest in the repo says the minium required version is `14.0.25426.0` but when I inspect the released msixbundle, and go to the path `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle\AppInstaller_x64.msix\AppxManifest.xml` It shows this:
```xml
<Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19041.0"/>
    <TargetDeviceFamily Name="Windows.Holographic" MinVersion="10.0.20346.0" MaxVersionTested="10.0.22000.0"/>
    <PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.30035.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
  </Dependencies>
```

**Comment by jedieaston** [comment]
They must be using a different AppxManifest for the signed bundles. Boo, hiss.

**Comment by JohnMcPMS** [comment]
> They must be using a different AppxManifest for the signed bundles. Boo, hiss.

We definitely are because it is the AppInstaller UWP + winget.  However, this is basically a VS thing where it updates that minimum version as part of the build process, based on what we are using.  I have a guess as to what caused it, but the right solution is for the owner of the aka.ms link to keep it up to date when they publish new packages.

**Comment by Trenly** [comment]
> > They must be using a different AppxManifest for the signed bundles. Boo, hiss.
> 
> We definitely are because it is the AppInstaller UWP + winget. However, this is basically a VS thing where it updates that minimum version as part of the build process, based on what we are using. I have a guess as to what caused it, but the right solution is for the owner of the aka.ms link to keep it up to date when they publish new packages.

Are there alternate URL's where these packages are published? If not, do we know if that the team responsible for those links is responsive and will have them updated quickly?

**Comment by denelon** [comment]
We're trying to track the right people down to get this resolved.

**Comment by KevinLaMS** [comment]
Greetings.  The VCLibs packages has been updated.  Thanks for reporting.  Please close if this works for you.

**Comment by denelon** [comment]
We just heard back that the download links should be updated with the latest version: 30035.

**Comment by Trenly** [comment]
> Greetings. The VCLibs packages has been updated. Thanks for reporting. Please close if this works for you.

> We just heard back that the download links should be updated with the latest version: 30035.

Yep! Looks like the latest version is there; The script requires a few changes to work, but I've already created the PR
