### ISSUE TITLE
Tuxpaint and Tuxpaint stamps always reinstall when running winget upgrade --all

### ISSUE THREAD

**Issue by mavhc** [microsoft/winget-pkgs#28950]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
With tuxpaint or tuxpaint stamps installed, every "winget upgrade --all" installs them both again, I assume because the version number is missing.

# Steps to reproduce
(I assume)
winget install tuxpaint
winget upgrade tuxpaint

In my case tuxpaint was already installed via other means.

# Expected behavior
It doesn't upgrade all the time

# Actual behavior
It does reinstall every time upgrade is run

# Environment

Windows Package Manager v1.0.12581
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22463.1000
Package: Microsoft.DesktopAppInstaller v1.16.12581.0

**Comment by Trenly** [comment]
I would recommend reaching out to the publisher and seeing if they will update their installer to add the version information
https://github.com/microsoft/winget-cli/issues/1356#issuecomment-895409232

**Comment by mavhc** [comment]
Have done https://sourceforge.net/p/tuxpaint/bugs/234/

**Comment by jedieaston** [comment]
TuxPaint is open source, and I found the problem in their innosetup configuration. If I can get a local build environment up, I'll send them a fix.

**Comment by kdpuvvadi** [comment]
> TuxPaint is open source, and I found the problem in their innosetup configuration. If I can get a local build environment up, I'll send them a fix.
> 
> Edit: [Fingers crossed...](https://sourceforge.net/p/tuxpaint/tuxpaint/merge-requests/9/)

Looks like your changes are merged.

**Comment by jedieaston** [comment]
Awesome! Once they cut a new release we should be good to go. 

@mavhc You can either close this issue now, or if you leave it open we can close it once the new version is released.
