### ISSUE TITLE
Python path and environment variables

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#29155]
# Description of the new feature/enhancement

I was recently informed a user did `winget install python3` and as this was a new install the path and environment variables weren't added. To do that the user would have to `winget install python3 -i` for interactive. Trying to do this after install required running the installer in interactive mode, and due to the way it was installed initially, the MSI wasn't available.

Does anyone know what switches could be passed to the installer (if this is possible)?

**Comment by jedieaston** [comment]
We need to add "PrependPath=1" to the silent install instructions.

https://docs.python.org/3/using/windows.html#installing-without-ui

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Because http://github.com/microsoft/winget-pkgs/pull/29175#issue-1013839422 has been merged, should this issue be closed?

**Comment by jedieaston** [comment]
I need to do the rest of them (if someone doesn’t get to them first), so I think we should leave it open.

**Comment by vedantmgoyal2009** [comment]
@jedieaston I'll do for Python 3

**Comment by denelon** [comment]
I reopened this issue so the other PRs can also be tracked. I did find the limit of 10 linked Issues for a PR, I'm going to assume the same holds in the other direction.

**Comment by jedieaston** [comment]
It looks like @vedantmgoyal2009 is correct, except for 3.9.6 and 3.9.7, all of the other Python manifests already had that option.

This should be resolved:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/21368066/135878097-45b8b7db-a9a1-40cb-8d8f-0dbd91b53542.png">

**Comment by denelon** [comment]
Thanks @vedantmgoyal2009, @jedieaston, and @BEEDELLROKEJULIANLOCKHART
