### ISSUE TITLE
Duplicate package entires for Meld(the difftool)

### ISSUE THREAD

**Issue by akxer** [microsoft/winget-pkgs#29198]
# Brief description of your issue
Unable to upgrade meld because of duplicate package entries
# Steps to reproduce
Run ```winget upgrade meld.meld``` in powershell

# Expected behavior
It should upgrade the package to it's latest version or give a relevant error

# Actual behavior
```powershell
winget upgrade meld.meld
Multiple installed packages found matching input criteria. Please refine the input.
Name Id
-------------------------------------------
Meld Meld.Meld
Meld {64FF0987-16EF-496B-A3DF-604954B3F75E}
```
As can be seen above, there seems to be multiple conflicting package entries for Meld

# Environment
Windows 11 Insider Preview 10.0.220000.65 (co_release)
```none
Windows Package Manager v1.1.12663
Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by KaranKad** [comment]
This should fix it https://github.com/microsoft/winget-pkgs/pull/29254.

**Comment by KaranKad** [comment]
Can you try it now to see if it works?
