### ISSUE TITLE
Unable to upgrade Powertoys

### ISSUE THREAD

**Issue by akxer** [microsoft/winget-pkgs#29199]
# Brief description of your issue
Unable to upgrade Microsoft Powertoys even though there are updates available
# Steps to reproduce
1. Run `winget upgrade`
2. Note the Packages available
``` winget upgrade
Name                Id                  Version     Available   Source
----------------------------------------------------------------------
PowerToys (Preview) Microsoft.PowerToys 0.45.0      0.47.0      winget
```
3. Run `winget upgrade Microsoft.PowerToys`

# Expected behavior
It should upgrade the package

# Actual behavior
We get this output ```No applicable update found.```

# Environment

```none
Windows 11 Insider Preview 10.0.220000.65 (co_release)

Windows Package Manager v1.1.12663
Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by jedieaston** [comment]
A solution for this has been proposed in https://github.com/microsoft/winget-cli/issues/752, and it's a client issue, so we can't do anything about it in this repo at the moment. Sorry!
