### ISSUE TITLE
Weird search output when installing Postman

### ISSUE THREAD

**Issue by andyliuhaowen** [microsoft/winget-pkgs#29493]
# Brief description of your issue

Weird search output when installing Postman

# Steps to reproduce

```
winget install postman
```

# Expected behavior

Postman installs.

# Actual behavior

```
PS > winget install postman
Multiple packages found matching input criteria. Please refine the input.
Name                    Id              Source
-----------------------------------------------
Nightingale REST Client 9N2T6F9F5ZDN    msstore
Postman                 Postman.Postman winget
```

This might not be a bug, but this output doesn't make sense to me.

# Environment

```none
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12701.0
```

**Comment by kdpuvvadi** [comment]
Nightingale  rest client might have used tag postman or both have common tags. 

try installing postman with ` winget install -e Postman.Postman`

**Comment by KaranKad** [comment]
This became an issue when msstore source was added in by default, now you really need to be exact with what you want to install.

**Comment by jedieaston** [comment]
Related: https://github.com/microsoft/winget-cli/issues/1523

**Comment by kdpuvvadi** [comment]
it's same with every other package with similar name on msstore

**Comment by denelon** [comment]
Duplicate of microsoft/winget-cli#1523
