### ISSUE TITLE
Local Repo like (Chocolatey for Business)

### ISSUE THREAD

**Issue by pateldm2008** [microsoft/winget-pkgs#29553]
# Description of the new feature/enhancement

Can we host Package Repository internally? We like to use winget to install Infrastructure Software/Tools on Images or newly built Windows Servers.

**Comment by denelon** [comment]
Yes, take a look at https://github.com/microsoft/winget-cli-restsource.

**Comment by Trenly** [comment]
You can have private sources as stated on the [blog](https://devblogs.microsoft.com/commandline/windows-package-manager-1-1/), but I’m not certain on how to configure them. I believe there is an issue over at the winget-cli repo, but I couldn’t find it from my phone

**Comment by denelon** [comment]
Windows Server 2019 isn't supported due to other dependencies for servicing and supporting Windows Package Manager on that SKU. It is possible to install on Windows Server 2022, but that should be considered experimental. The license for offline installation is available on the GitHub releases.
