### ISSUE TITLE
Need better documentation regarding supporting architectures

### ISSUE THREAD

**Issue by soapdog** [microsoft/winget-pkgs#296]
Checking out manifest in this repo I couldn't find manifests supporting other architectures that are not x64. An example is Visual Studio Code which is used in 32bit built-in emulation by many Surface Pro X owners. It's manifest lists only the x64 version, so I'm assuming trying to install it on a Surface Pro X would fail.

It would be great if there was more info about how to support x86 and arm64 manifests and that at least the Microsoft own manifests would list those options when applicable as well.

**Comment by MrRoundRobin** [comment]
Hey soapdog,

i created a multi arch YAML for PowerShell in PR #335. Sadly at the moment the validation failed with 
>  Manifest: We don't support more than one installer for now.

but localy it works already on my Pro X using
`winget install -m .\winget-pkgs\manifests\Microsoft\Powershell\7.0.1.yaml`

**Comment by denelon** [comment]
We're getting closer to support for multiple architectures with https://github.com/microsoft/winget-cli/issues/132

**Comment by denelon** [comment]
We are evaluating a draft of the 1.0 schema including support for multiple architectures in the same manifest structure. 
https://github.com/microsoft/winget-cli/discussions/646

**Comment by denelon** [comment]
I'm just cleaning up older Issues. We've made great progress in the architecture support. Many manifests now have ARM64 variants, and we detect when we can install an x86 or x64 version under emulation.

Visual Studio Code is a great example:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VisualStudioCode/1.64.2/Microsoft.VisualStudioCode.installer.yaml
