### ISSUE TITLE
Support for store apps

### ISSUE THREAD

**Issue by lostmsu** [microsoft/winget-pkgs#298]
I want to be able to do `winget install Netflix`, and it should install Netflix from https://www.microsoft.com/en-us/p/netflix/9wzdncrfj3tj

#### Options:
1. Automatically include all the Store apps
2. Add a manifest option for store apps

**Comment by sundhaug92** [comment]
microsoft/winget-cli#117

**Comment by lostmsu** [comment]
Closing as duplicate of https://github.com/microsoft/winget-cli/issues/117
