### ISSUE TITLE
.validation file for Tencent.TXEDULite may need to be removed

### ISSUE THREAD

**Issue by ItzLevvie** [microsoft/winget-pkgs#29891]
It seems like the folder doesn't contain a package and only the `.validation` file is there.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Tencent/TXEDULite

**Comment by lychichem** [comment]
@ItzLevvie Seems it is named as Tencent.EDULite now. See https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Tencent/EDULite/1.0
