### ISSUE TITLE
Calibre failing periodic validation

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#30058]
On Mon, Oct 04, 2021 at 10:15:29AM -0700, denelon wrote:
> @kovidgoyal it doesn't seem to be transient. It essentially fails every day from our daily periodic check.
> 
> https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+Automatic+update+of+calibre.calibre

I dont know how to read that. What is the error you are getting? What
HTTP code? A network timeout? A TLS error?

_Originally posted by @kovidgoyal in https://github.com/microsoft/winget-pkgs/issues/29164#issuecomment-933969083_

**Comment by kovidgoyal** [comment]
that looks like a network issue on the path between wherever you are
downloading and the server. If you are downloading the latest release
you can try one of the alternate download links, mentioned here:
https://calibre-ebook.com/download_windows 

If you are trying to download historical releases maybe try increasing
the timeout in whatever http library you are using.

**Comment by vedantmgoyal2009** [comment]
@denelon we haven't seen this in a while...
