### ISSUE TITLE
[Bug]: Daum.PotPlayer hash mismatch

### ISSUE THREAD

**Issue by nagi1999a** [microsoft/winget-pkgs#30085]
### Brief description of your issue

Daum.PotPlayer version 0929 manifest seems to have wrong hash.

### Steps to reproduce

winget install --id Daum.PotPlayer

### Expected behavior

Install without problem.

### Actual behavior

get "Installer hash does not match; to override this check use --force" message while installing.

### Environment

```shell
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by AarjavPatni** [comment]
I'm facing this issue as well.

**Comment by AarjavPatni** [comment]
I'm facing this issue for v221215.
