### ISSUE TITLE
[Package Request]: Helm

### ISSUE THREAD

**Issue by ssrahul96** [microsoft/winget-pkgs#30128]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Helm
Publisher Url: https://helm.sh
Package Name: Helm.Helm
Description: helm is a package manager for Kubernetes
Package Version: 3.7.0
Installer URL: https://get.helm.sh/helm-v3.7.0-windows-amd64.zip

Current Package Identifier (for new versions):

**Comment by jedieaston** [comment]
Not yet, that's being tracked in https://github.com/microsoft/winget-cli/issues/182

**Comment by ssrahul96** [comment]
> 
> 
> If you can get it merged into the helm repo so that it's automatically generated for every release (and signed?), we can add it. (Just want to make sure they're willing to support it so you don't have to maintain a fork for all eternity)

I think they are using circle ci build internally, so i could raise a PR for that.

**Comment by Trenly** [comment]
Package is now available as Helm.Helm

<--
Close with reason: Resolved;
-->
