### ISSUE TITLE
[Package Request]: schollz.croc

### ISSUE THREAD

**Issue by Dommel** [microsoft/winget-pkgs#30231]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: zack.scholl
Publisher Url: https://github.com/schollz/croc
Package Name: croc
Description: 
README.md

croc
Version Coverage Build Status

This project is supported by:

croc is a tool that allows any two computers to simply and securely transfer files and folders. AFAIK, croc is the only CLI file-transfer tool that does all of the following:

    allows any two computers to transfer data (using a relay)
    provides end-to-end encryption (using PAKE)
    enables easy cross-platform transfers (Windows, Linux, Mac)
    allows multiple file transfers
    allows resuming transfers that are interrupted
    local server or port-forwarding not needed
    ipv6-first with ipv4 fallback
    can use proxy, like tor

For more information about croc, see my blog post.
Package Version: 9.4.2
Installer URL: https://github.com/schollz/croc/releases/tag/v9.4.2

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
@denelon - Can you re-title this please `[Package Request]: schollz.croc`
