### ISSUE TITLE
Question about threat model

### ISSUE THREAD

**Issue by DustinKingen** [microsoft/winget-pkgs#303]
I see that a bot will be automatically reviewing the manifests. Is there anything built-in to do virus scanning?

**Comment by illgitthat** [comment]
From [the announcement](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/):
> One critical concern we had was how to build a repository of trusted applications. We are automatically checking each manifest. We leverage SmartScreen, static analysis, SHA256 hash validation and a few other processes to reduce the likelihood of malicious software making its way into the repository and onto your machine.

**Comment by vexx32** [comment]
Yeah, I'm pretty concerned that all the documentation and responses I've seen indicate that the WinGet team seem to think that validating a manifest ensures that a package can be trusted.

A manifest is metadata. Metadata isn't what causes security breaches in the vast, vast majority of cases.

A serious, concerted effort to validate that malicious code isn't somehow snuck into one of the packages with a valid manifest needs to be made. Virus scanning should be a must-have.

**Comment by DustinKingen** [comment]
@vexx32 I agree. Especially since third parties will be hosting the binaries and they can potentially be compromised for any version of the manifest.

**Comment by chausner** [comment]
As part of the validation, the installers are checked with SmartScreen.

**Comment by jamierocks** [comment]
> I agree. Especially since third parties will be hosting the binaries and they can potentially be compromised for any version of the manifest.

This would only be an issue if they are compromised **before** being added without being noticed though, as the sha256 checksum is recorded in the manifest.

Compromised files should be noticed by humans, but SmartScreen should be a good defense against those than fall through the cracks.

**Comment by denelon** [comment]
In addition to SmartScreen, we are performing static analysis of the binary for malware and additional validation. One of our next activities will be open sourcing the validation pipeline to help bring additional transparency and trust behind the community repository. Some of what we are doing is covered in the blog post.

https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

**Comment by vexx32** [comment]
Great! However, as this blog post candidly outlines, Smart Screen will effectively block any and all independent publishers from utilizing WinGet. Yes, even if they get their code signed, at personal expense.

https://getimageview.net/2020/06/02/microsoft-defender-smartscreen-is-hurting-independent-developers/

I don't think that's reasonable by any stretch that WinGet will effectively completely block a majority of smaller/independent developers from utilizing it as a platform to deploy their software.

Looking at other package managers, even on Linux, this is a pretty unusual stance to take and severely limits potential contributors both to the packages repository as well as (I would imagine, though yes, I am only speculating) the WinGet application itself.

**Comment by vexx32** [comment]
@DustinKingen should this be taken as a confirmation that tools written by independent developers are simply not at all supported/in scope for WinGet?

**Comment by DustinKingen** [comment]
@vexx32 I closed this issue since it’s two months old.

I’m not a WinGet maintainer so I won’t be able to address your question.
