### ISSUE TITLE
[New Feature]: Moderators should be able to request another run of the tests.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#30364]
### Description of the new feature/enhancement

I'd like to (and I'm sure the other mods would too) be able to request the pipelines to re-run if they fail, as sometimes PRs get stuck in an unhealthy state and we have to close and reopen the PR (or tell the contributor to do it), which clutters the history up as GitHub doesn't really expect for PRs to open and close very often. It's confusing when trying to figure out the current state of the PR to scroll through and see "@jedieaston closed this pull request. @jedieaston opened this pull request" eight times, with notifications being sent everywhere at the same time. And sometimes labels just disappear during the close/re-open even if they'd be useful to maintainers for debugging.

Sometimes it makes sense for a maintainer to take a look, but often some backend service timed out (*cough* defender *cough*) and if we run it again everything is fine. But @msftbot is extremely okay with just assigning it and leaving Chrome or Edge or other safe apps in limbo.

### Proposed technical implementation details (optional)

Two ways I can think of to implement this:

- the best for UX would probably be to have @wingetbot start listening for keywords/commands in our comments. That way we don't have to be delegated permissions in ADO to talk to the Azure DevOps app (which I understand you can't do), but since @wingetbot has the permissions, we could say "@wingetbot rerun" which would trigger it to do "/azp rerun". If @wingetbot can't listen for commands right now, that might be a problem.
- If that will be too hard to implement, we could just have a GitHub Action that looks for comments and triggers the pipelines. That might be easier to implement depending on maintainer preferences. You could just have a action that looks for [issue_comments](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment) that are in pull requests, if it finds one that says "rerun" written by someone on the mods list, then it triggers the pipeline to run again (either via `/azp run` or [the GitHub Actions -> pipelines integration](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops)).

**Comment by vedantmgoyal2009** [comment]
@denelon just a friendly reminder, this issue is also waiting to be discussed.

**Comment by vedantmgoyal2009** [comment]
@denelon I would like to add that moderators should be given write access to @wingetbot's PRs. It really hurts for someone to open a new, fresh PR with the "changes requested" on the @wingetbot's PR.

Example - https://github.com/microsoft/winget-pkgs/pull/35336 opened by @wingetbot, Levvie requested changes. Now, another person has to open another PR for the same package with suggestions applied (https://github.com/microsoft/winget-pkgs/pull/35351).

I think you can add the mods team as a collaborator on https://github.com/wingetbot/winget-pkgs

**Comment by denelon** [comment]
@ImJoakim, @ItzLevvie, @jedieaston, @KaranKad, @OfficialEsco, and @quhxl,

I've done some testing, and I think I can get @msftbot to just comment /azp run when a moderator comments /azp run. That would allow moderators to trigger a build. Integration with @wingetbot is an entirely different undertaking. I still think we would want to do that, but it will take a bit more time. The @msftbot also doesn't really have a concept of a GitHub team yet, so I've got a feature ask for the team working on it.

It would have the bot remove nearly every label on the PR, dismiss any approvals, and then the bot would add /azp run, and the build would get triggered. Are any of you available for the next half hour-hour to test with me?

**Comment by OfficialEsco** [comment]
I'm free for then next 30-60m 🤷‍♂️

**Comment by jedieaston** [comment]
I am also available.

**Comment by denelon** [comment]
Give it a shot.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/35279

**Comment by denelon** [comment]
I think I fixed the erroneous labels. We will still see the "Commenter does not have sufficient privileges for PR 35279 in repo microsoft/winget-pkgs", but it looks like it might work.

**Comment by denelon** [comment]
Is there another one so we can confirm?

**Comment by jedieaston** [comment]
https://github.com/microsoft/winget-pkgs/pull/35233#issuecomment-974202687

**Comment by denelon** [comment]
Ahh, need to fix the comment... it added the PR author

**Comment by jedieaston** [comment]
One other nit: maybe the command for moderators shouldn't be `/azp run`, since that also triggers the azure pipelines bot that then gets cranky because we don't have permissions to run the pipelines directly.

**Comment by denelon** [comment]
what do you want? I can change it.

**Comment by denelon** [comment]
I also removed mentioning the author. I'm not sure I can get the commenter alias to be mentioned. I'm digging in sparse documentation.

**Comment by jedieaston** [comment]
what about `/rerun-pipelines-please`? we use the word rerun too much for it to be the command alone.

**Comment by denelon** [comment]
OK, it looks for "/rerun-pipelines-please" as a substring. It also should add the "contextual author".

**Comment by denelon** [comment]
Got another one?

**Comment by jedieaston** [comment]
https://github.com/microsoft/winget-pkgs/pull/35177#issuecomment-974210004

**Comment by jedieaston** [comment]
I wonder if it's getting upset because of the newlines? Most of the time people run `/azp run` without anything else in the comment. Seems like a bug in the pipelines bot.

**Comment by denelon** [comment]
I split it into two comments, let's see if that does the trick. Could there possibly be another one? 😁

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/34576#issuecomment-974224007
expected jedieaston to find one 😁

**Comment by denelon** [comment]
I guess it might be tripping on regex since "run" is in a "/" command.

**Comment by denelon** [comment]
Do you want to try without the leading "/" or try changing the command to not include some reserved word (I have no idea what the list is)?

**Comment by jedieaston** [comment]
We can try it without the leading `/`, but it looks like that one worked right? 

![image](https://user-images.githubusercontent.com/21368066/142659345-777e4b78-0574-4e0a-b890-37bd8a0cf8a9.png)

**Comment by denelon** [comment]
I'm OK with it. We can look at cleaning the comment from aure-pipelines later. I couldn't find an example where the bot added the /azp run without the message from azure-pipelines.

**Comment by denelon** [comment]
Should I build a rule so when a "non" moderator tries they will be told "Request Denied"?

**Comment by denelon** [comment]
I almost want to create a reply from @msftbot to @azure-pipelines to say "Yes, I am. Do as you are told". 😁

**Comment by denelon** [comment]
OK, I've built the rule for non moderators when they try `/rerun-pipelines-please` they will be informed they are not a moderator and Request denied.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/34577#issuecomment-974238918

**Comment by denelon** [comment]
Looks like a valid test.

**Comment by Trenly** [comment]
Poor denelon, he don't have mod priveleges 😢  Sad day

**Comment by denelon** [comment]
The rules are based on "activity sender". I'm not allowed to be nice to the bot. I just have to tell it what to do I guess.

**Comment by vedantmgoyal2009** [comment]
He's the maintainer. He has direct access to everything. Why will he use `/rerun-pipelines-please` when he can `/azp run`? 😂

**Comment by Trenly** [comment]
> The rules are based on "activity sender". I'm not allowed to be nice to the bot. I just have to tell it what to do I guess.

Is this the first stages of the code-based rules that you mentioned in gitter?

**Comment by denelon** [comment]
Not yet. The bot currently has a web based UI. The team has added support to export the rules as JSON, and allows me to put them in the repository. This was just another rule in the web UI. Unfortunately, they are all in one file so it's super long and kind of risky for making PRs against. I've asked the team to allow support for one or more rules per file so they can individually be acted upon. That way we can make changes per rule.

I am testing the export to JSON in another private repository. It's a nightmare to clean up right now, but I'm hoping to get to it in the next couple of weeks with most of the engineering team out, that might be a bit challenging.

**Comment by denelon** [comment]
It's a good week with few meetings/interruptions, so I'm trying to give the community moderators some much needed attention. @jedieaston since you created the issue, you can validate with #34577, and if you are happy, you can close this Issue. 🙌

**Comment by vedantmgoyal2009** [comment]
/rerun-pipelines-please

Let me test once with an issue rather than a PR.

**Comment by denelon** [comment]
I'm thinking about setting up a community call. I need to figure out which hour works best to get the widest cross section of moderators. I'll also allow community members to join.

**Comment by vedantmgoyal2009** [comment]
![image](https://user-images.githubusercontent.com/83997633/142662342-21627384-365c-4881-8123-75d4329ba465.png)

**Comment by jedieaston** [comment]
It looks like ADO still isn't recognizing the bot.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#troubleshoot-pull-request-comment-triggers seems to say that it needs to be a collaborator in the GitHub repository, which unless I'm wrong, can't be applied to GItHub apps (it only works for users).

**Comment by Trenly** [comment]
I think its because the github app inherits its auth from the invoker. In the case of wingetbot, azp run works because it calls /azp run as wingetbot, even though it is the github app doing it

**Comment by denelon** [comment]
Yeah, I really want to get the work so I can just put moderators in a GitHub team, and drive the rules by that. It's much easier than explicitly having to use their alias over and over again in multiple rules. If we add or remove moderators, it becomes quite painful. 

We are in the top three teams at GitHub using @msftbot, so we do have some pull, and the team finally has their own PM and engineering manager. I truly hope they are also able to open source the project, but I think that is a long way out if it's even possible.

**Comment by denelon** [comment]
Failure on the negative. It shouldn't have said @jedieaston is not a moderator.

**Comment by denelon** [comment]
I needed to make it an "And" not an "Or" on the activity sender. It's updated. Let's get one more to be sure.

**Comment by jedieaston** [comment]
done (#34577)

**Comment by vedantmgoyal2009** [comment]
@msftbot (GitHub App) cannot be collaborators. I once had opened a support ticket for it to know if there's any workaround but there wasn't. While I was setting up https://github.com/apps/winget-pkgs-automation-bot, I came to know that GitHub Apps are just CONTRIBUTORS so you will have to make @wingetbot do it.

For GitHub Apps:
![image](https://user-images.githubusercontent.com/83997633/142663329-7b94a796-a225-49e8-87a6-2578483efd24.png)

**Comment by jedieaston** [comment]
> I think its because the github app inherita its auth from the invoker. In the case of wingetbot, azp run works because it calls /azp run as wingetbot, even though it is the github app doing it

@wingetbot __has__ collaborator access though:

![image](https://user-images.githubusercontent.com/21368066/142662952-7103dccf-3bcd-4698-80f2-0f0d0a0951b2.png)

@wingetbot is a real GitHub user, whereas @msftbot is an app (from github.com, the easiest way to tell is whether or not they have a profile [or the word "bot" next to their name]). @wingetbot says `/azp run`, which triggers the pipelines bot which has permission to talk to ADO over the API.

**Comment by denelon** [comment]
That looks better!

**Comment by denelon** [comment]
I wonder what else I can break today...

**Comment by denelon** [comment]
Since it wasn't the newline, do you want me to squash the message back to a single comment?

**Comment by jedieaston** [comment]
Yes please.

**Comment by jedieaston** [comment]
Do you want me to make the "ADO doesn't listen to @msftbot" stuff another issue?

**Comment by denelon** [comment]
OK, let's find another one and have either @vedantmgoyal2009 or @Trenly try the failure case, and then a moderator to test the success case.

And yes @jedieaston another issue would be goodness. I'm also trying to remember which `.md` file needs to be updated with this feature.

**Comment by denelon** [comment]
I also don't like cluttered conversation in GitHub threads.

**Comment by Trenly** [comment]
#35298

**Comment by vedantmgoyal2009** [comment]
https://github.com/microsoft/winget-pkgs/pull/35291#issuecomment-974258109

**Comment by denelon** [comment]
This feels a bit like blind pair programming.

**Comment by jedieaston** [comment]
https://github.com/microsoft/winget-pkgs/pull/35298 makes it look like @azure-pipelines doesn't see it unless it's literally the string "/azp run".

**Comment by denelon** [comment]
Maybe I can make it first.

**Comment by denelon** [comment]
moved `/azp run` to be first again.

**Comment by denelon** [comment]
Yuck. why does this have to be so hard?

**Comment by vedantmgoyal2009** [comment]
Perhaps, azure-pipelines[bot] needs to be improved. Or maybe try with `/AzurePipelines run` once.

**Comment by denelon** [comment]
I don't think I can modify azure-pipelines bot. It's either two comments with a short error or one with a long error ☹️

**Comment by jedieaston** [comment]
Maybe two comments for now + a bug report to ADO?

**Comment by denelon** [comment]
[![](https://api.gh-polls.com/poll/01FMWKVXMT3RBYSB1FYARCRKWD/One%20comment%20with%20a%20long%20error)](https://api.gh-polls.com/poll/01FMWKVXMT3RBYSB1FYARCRKWD/One%20comment%20with%20a%20long%20error/vote)
[![](https://api.gh-polls.com/poll/01FMWKVXMT3RBYSB1FYARCRKWD/Two%20comments%20with%20a%20short%20error)](https://api.gh-polls.com/poll/01FMWKVXMT3RBYSB1FYARCRKWD/Two%20comments%20with%20a%20short%20error/vote)

**Comment by Trenly** [comment]
Are you sure its actually re-running the pipelines? Looking at https://dev.azure.com/ms/winget-pkgs/_build?definitionId=337 I'm not seeing any of the recent tests which supposedly started new runs currently running in https://dev.azure.com/ms/winget-pkgs/_build?definitionId=337

**Comment by jedieaston** [comment]
> Are you sure its actually re-running the pipelines? 

it isn't, that's to be a separate issue: https://github.com/microsoft/winget-pkgs/issues/30364#issuecomment-974257309

(yes, GitHub issues are not the place for synchronous collaboration)

**Comment by Trenly** [comment]
> > Are you sure its actually re-running the pipelines?
> 
> it isn't, that's to be a separate issue: [#30364 (comment)](https://github.com/microsoft/winget-pkgs/issues/30364#issuecomment-974257309)
> 
> (yes, GitHub issues are not the place for synchronous collaboration)

Thanks, I missed that

**Comment by denelon** [comment]
Does Gitter support a smaller group chat?

**Comment by Trenly** [comment]
> Does Gitter support a smaller group chat?

I think you can create private rooms inside a community

**Comment by denelon** [comment]
Done, and added the four of us.

**Comment by vedantmgoyal2009** [comment]
@denelon You added yourself, jedieaston, trenly, and esco?

**Comment by vedantmgoyal2009** [comment]
Also, Ryan is a contributor but he can run pipelines. Does it defeat the point of having the bot, a collaborator?

![image](https://user-images.githubusercontent.com/83997633/142667923-9750f106-d213-4b5a-aff5-ef50c8dae606.png)

**Comment by Trenly** [comment]
> Also, Ryan is a contributor but he can run pipelines. Does it defeat the point of having the bot, a collaborator?
> 
> ![image](https://user-images.githubusercontent.com/83997633/142667923-9750f106-d213-4b5a-aff5-ef50c8dae606.png)

Thats probably because he is authorized on the pipeline itself as a MSFT developer

**Comment by denelon** [comment]
All moderators can run the new command to get the bot to add `/azp run`. All contributors can run `/azp run`.

**Comment by vedantmgoyal2009** [comment]
> All contributors can run `/azp run`.

I don't understand what are you trying to say. I'm a contributor but I can't run the pipelines.

**Comment by denelon** [comment]
Sorry, Ryan is an administrator I believe.

**Comment by denelon** [comment]
He has "Write" at the very least.

**Comment by vedantmgoyal2009** [comment]
Okay.

**Comment by jedieaston** [comment]
Since the GitHub/moderator side of the work is done, I'm closing this.

The adventure continues in https://github.com/microsoft/winget-pkgs/issues/35372
