### ISSUE TITLE
[Moderation]: Allow moderators to tag issues

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#30581]
### Description of the new feature/enhancement

Several package request issues are blocked, but not tagged with blocking issues. Some examples include, but are not limited to:
- #30362
- #30231 
- #30128 
- #30129 
- #28835

Moderators and community members often point out these blocking issues in the comments. I propose that Moderators be allowed to tag issues and PRs through Wingetbot/Msftbot or some other form of automation. 

### Proposed technical implementation details (optional)

```
@<bot> tags <list of tags>
// if a tag is prefixed with - then it should be removed from the issue/PR
```
This would allow moderators to perform actions such as:
```
@<bot> tags Blocking-Issue Dependencies
@<bot> tags Interactive-Only-Installer Blocking-Issue

// If and only if the issue has the "Package-Request" label, allow them to remove the triage label
@<bot> tags  .zip Blocking-Issue -Needs-Triage
```

**Comment by vedantmgoyal2009** [comment]
Reference: https://github.com/actions/github-script#apply-a-label-to-an-issue

**Comment by vedantmgoyal2009** [comment]
@denelon please add `Area-Bots` label to this issue, its related to bot.
