### ISSUE TITLE
[Package Request]: yuzu

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#30709]
### Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: yuzu-team
Publisher Url: https://github.com/yuzu-emu/yuzu
Package Name: yuzu
Description: yuzu is the world's most popular, open-source, Nintendo Switch emulator — started by the creators of Citra. It is written in C++ with portability in mind, and we actively maintain builds for Windows and Linux.
Package Version: 1.8
Installer URL: https://github.com/yuzu-emu/liftinstall/releases/download/1.8/yuzu_install.exe

Current Package Identifier (for new versions):

**Comment by mbledkowski** [comment]
Hi, I am also looking forward for this package to be added to the repository

**Comment by russellbanks** [comment]
We might be able to add the mainline builds, as they are zips.

**Comment by soredake** [comment]
@russellbanks thank you! I've request silent install option from yuzu team later, for now, this can be closed.

**Comment by soredake** [comment]
https://github.com/yuzu-emu/yuzu/issues/10190
