### ISSUE TITLE
Moving Packages

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#30732]
Looking at all the manifests, there is an established pattern of `Publisher.Package[.SubPackage][.Distro]` to ensure that packages which are substantially similar are placed under the same folder in the manifest structure. As I was looking, I found that there are several packages which could be moved to new identifiers to align with the pattern better.  One example of this is BraveBrowser -
```raw
PackageIdentifier -> Suggested Identifier
BraveSoftware.BraveBrowser
BraveSoftware.BraveBrowser-Beta -> BraveSoftware.BraveBrowser.Beta
BraveSoftware.BraveBrowser-Dev -> BraveSoftware.BraveBrowser.Dev
BraveSoftware.BraveBrowser-Nightly -> BraveSoftware.BraveBrowser.Nightly
```
Since the pipelines don't yet support multiple changes in a PR, I have a script that can generate the branches required to move each version individually. However, looking at the number of packages that I am proposing updates to, this would result in ~2,300 PR's. 

I do not want to flood the repository with PR's, since this would likely overwhelm the moderators and the pipelines even if done in small chunks. Additionally, there is likely to be domain validation issues with some of these packages (See #30688 from when I tested my script). 

This leaves me with two main questions -
1. Is it okay / feasible to move these packages? I do know that package moves are intended to be difficult since PackageIdentifiers are intended to be a static field, but I think that in some cases it is warranted. At the very least a process for moving packages should be identified since it is sometimes necessary.
2. If it is okay to move these packages, is there a way to get MSFT's support to approve these changes/prs knowing that these are existing, valid packages and the only information which is changing is metadata related

Thanks to @jedieaston for encouraging me to put my thoughts into an issue

[proposed_updates.csv](https://github.com/microsoft/winget-cli/files/7366932/proposed_updates.csv)

**Comment by Trenly** [comment]
> This will become more of an issue when 1.1 comes out. There are tons of packages where we changed the version numbers to match the ARP table when they aren't the "real" version numbers. Those will have to be rolled back (with ARP data added to the new keys).
> 
> JetBrains, Python, Jackett, AWS CLI, several of the KDE packages, .NET Core (all of them), and probably a bunch of other ones. We should probably start coming up with a strategy to figure that out, I've just been putting it off since there's no roadmap on [microsoft/winget-cli#1073](https://github.com/microsoft/winget-cli/issues/1073) being implemented for list/upgrade.

I can’t agree more. It seems like there will be a large number of versions that need to be moved / updated / changed once the 1.1 schema is released.

I think this truly highlights the need for #125 to become a priority not only for the validation pipeline but also the publish pipeline.

——-

Regardless, I think moving some of these packages will help identify packages that 1.1.0 schema changes will need to be made to, since it will be easier to fetch all the folders that contain sub-package or distro folders and then that list can be used to update the packages once 1.1.0 is released

**Comment by jedieaston** [comment]
Can we put a halt to this for a little while? We still haven't got any good ideas on how to make this more efficient, and flooding the queue with rename PRs is blocking us from seeing ones that people actually need approved.

**Comment by vedantmgoyal2009** [comment]
I am not doing any other packages now. There were few versions of OneDrive and Teams left inside the old package identifier because at that time, the limit of creation of PRs was exhausted. Once OneDrive ones would get merged, I would be creating PRs for Teams, because if I leave this in the middle, it would create unnecessary confusions for other users.

**Comment by jedieaston** [comment]
BTW: the next release of winget will have a way for the user to select what architecture they would like to install, regardless of what architecture they are running for their system (so if you're on a x64 system and want the x86 version of something, `--architecture` or `--a` during install will do that): https://github.com/microsoft/winget-cli/pull/1666

As a result, we should start figuring out which of the `*.x64` and `*.x86` manifests can be merged. Adobe Reader seems like a target, as do the .NET SDKs.

**Comment by vedantmgoyal2009** [comment]
These packages need to moved to `Microsoft.dotnetRuntime.5`:
- Microsoft.dotnetRuntime.5-x86
- Microsoft.dotnetRuntime.5-x64
- Microsoft.dotnetRuntime.5-arm64

These packages need to moved to `Microsoft.dotnetRuntime.3`: 
- Microsoft.dotnetRuntime.3-x86
- Microsoft.dotnetRuntime.3-x64

These packages need to moved to `Microsoft.dotnetRuntime.6`: 
- Microsoft.dotnetRuntime.6-x64

**Comment by vedantmgoyal2009** [comment]
I guess `--architecture` is now in public preview(?)

**Comment by jedieaston** [comment]
Yep. Once it's in stable, we can start merging those manifests (unless they are being used as dependencies elsewhere, in which case we'll still have to wait on the schema being extended).

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@jedieaston, [you previously mentioned KDE](http://github.com/microsoft/winget-pkgs/issues/30732#issuecomment-946117551:~:text=18%20Oct%202021-,This%20will%20become%20more,implemented%20for%20list%2Fupgrade.,-1). By ["we can start merging manifests"](http://github.com/microsoft/winget-pkgs/issues/30732#issuecomment-1016816701:~:text=once%20it's%20in%20stable%2C%20we%20can%20start%20merging%20those%20manifests%20(unless%20they%20are%20being%20used%20as%20dependencies%20elsewhere%2C%20in%20which%20case%20we'll%20still%20have%20to%20wait%20on%20the%20schema%20being%20extended).), do you mean that if [this](http://github.com/microsoft/winget-pkgs/issues/30732#issue-1029341563) is completed, "https://github.com/microsoft/winget-pkgs/issues/39190#issue-1090227311" shall be possible to remediate? (Unless it is not already possible?)

**Comment by jedieaston** [comment]
The KDE packages aren't separated by architecture, so #39190 doesn't change by it existing. Although I need to see if we can start merging some other manifests, or if we need more support in the client (Adobe Reader, maybe?)
