### ISSUE TITLE
[Bug]: Workrave.Workrave Version Unknown

### ISSUE THREAD

**Issue by anaurelian** [microsoft/winget-pkgs#31007]
### Brief description of your issue

Even after installing the latest version of Workrave.Workrave using winget,  Workrave still appears in the list of available updates, with a version of `Unknown`.

### Steps to reproduce

Install Workrave using winget: `winget install -e --id Workrave.Workrave`

Optional: upgrade Workrave using winget: `winget upgrade -e Workrave.Workrave`

Run ` winget upgrade` again.

### Expected behavior

 Workrave.Workrave should not appear in the list of available updates.

### Actual behavior

![image](https://user-images.githubusercontent.com/24680762/138428268-862ed3cc-5812-45ba-bd01-21a965842833.png)

### Environment

```shell
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1288
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by Trenly** [comment]
I believe https://github.com/rcaelers/workrave/issues/349 will resolve this issue

**Comment by anaurelian** [comment]
[Workrave Release v1.10.49](https://github.com/rcaelers/workrave/releases/tag/v1_10_49) [fixes](https://github.com/rcaelers/workrave/issues/349#issuecomment-1005868674) this issue. Thanks @rcaelers
