### ISSUE TITLE
[Package Request]: starship

### ISSUE THREAD

**Issue by DinkelThomas** [microsoft/winget-pkgs#31142]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Starship Contributors
Publisher Url: https://github.com/starship/starship
Package Name: starship
Description: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
Package Version: 0.58.0
Installer URL: https://github.com/starship/starship/releases/download/v0.58.0/starship-aarch64-pc-windows-msvc.zip

Current Package Identifier (for new versions): 
https://github.com/starship/starship/releases/tag/v0.58.0

**Comment by arihant2math** [comment]
Starship is on winget now:
`winget install --id Starship.Starship`

**Comment by Trenly** [comment]
Close with reason: Starship has started publishing MSI and is now in repository;
