### ISSUE TITLE
[Bug]: Dokan Library doesnt support live upgrade

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-pkgs#31432]
### Brief description of your issue

Dokan Library doesnt support live upgrading of the install, you have to uninstall the installed version, reboot, and then install the new version. Is it possible to remove or disable the upgrade system for this package?

### Steps to reproduce

Try to upgrade a existing Dokan installation

### Expected behavior

Upgrade has a notice stating that it will fail or upgrade is some other way warned against or disabled

### Actual behavior

Upgrade fails with error code 1603, if installer is manually run by downloading installer, Installer refuses stating that live upgrade is unsupported

### Environment

```shell
Package: 1.16.12702
Windows: 10.0.22000.258
```

**Comment by denelon** [comment]
This depends on:
* microsoft/winget-cli/issues/994

**Comment by Trenly** [comment]
@Masamune3210 / @OfficialEsco - In the latest release of the client we can set `UpgradeBehavior: deny` and `RequireExplicitUpgrade: true` in the manifest to effectively prevent users from upgrading the package using WinGet; The only thing that prevented me from doing this was the fact that I don't know the exact PackageIdentifier which needs updating

**Comment by Masamune3210** [comment]
Could have sworn the manifest had Dokan or FUSE in the name, but GitHub search is arse and I'm stuck on mobile until I get off work later today. Will try to remember to look when I get home.

**Comment by OfficialEsco** [comment]
`dokan-dev.Dokany`

**Comment by Trenly** [comment]
Thanks; I'll submit the updates

**Comment by Trenly** [comment]
Should be resolved by the above PR's for any new installs

###### Close with reason: PRs merged;

**Comment by 3xploiton3** [comment]
i dont install dokany, but winget detect for upgrade

![image](https://github.com/user-attachments/assets/f5389a05-160d-4fd5-847b-fc207f4d0134)

**Comment by 3xploiton3** [comment]
![Image](https://github.com/user-attachments/assets/b3b305d6-79ca-4740-978c-7dca0cb61131)
