### ISSUE TITLE
Apps with generic/latest installers are broken most of the time

### ISSUE THREAD

**Issue by auanasgheps** [microsoft/winget-pkgs#3250]
Hello, I hope I am using the right way of reporting this behavior.

Today I wanted to test winget to install all my programs in a fresh Windows installation.

# Brief description of your issue

I have noticed that most (if not all) programs that have generic/latest installers (no versioning) are broken, most likely because the program has been updated and the hash does not correspond.

Is winget team working to resolve this issue? We can't just keep manually updating hashes.

# Steps to reproduce

Install a program like: Google Chrome, WhatsApp, TeamViewer, Spotify, XnViewMP, Torguard, Origin

# Expected behavior

Apps should install.

# Actual behavior

Installation will fail. Observe they all have a generic installer, without a version.

# Environment

```none
[winget --info]
Windows Package Manager v0.1.42241
Windows: Windows.Desktop v10.0.19041.450
Package: Microsoft.DesktopAppInstaller v1.10.42241.0
```

**Comment by denelon** [comment]
We have been looking at several approaches to this issue. Our preference is to have a manifest point to a specific version of a package. That would enable users to chose an older version if they prefer. Unfortunately, some packages are published at a static URL. We have been discussing the concept of something like "latest" for the version and checking/updating the SHA256 automatically after validating a package. Unfortunately, this could happen at any time, and we can't guarantee that we will always have the correct value. Users wouldn't be able to trust which version of an application they are getting, but it might be better than what happens today.

**Comment by auanasgheps** [comment]
I really appreciate the versioning system and I actually used it today but unfortunately this is not applicable for static links, so maybe there could be an exception system for such apps.
 

> Users wouldn't be able to trust which version of an application they are getting

However, as long as:

- we are using the official repo of the App
- package is signed 
- the user has not specified a version in the command

Why winget should not just allow the install?
Winget could also warn the user in such cases and ask for confirmation.

**Comment by auanasgheps** [comment]
I have another suggestion: since many apps are hosted on GitHub, winget could have a link to the repo of the app. In an ideal world could periodically check for new releases and automagically create new manifests.

**Comment by denelon** [comment]
We have built automation to create a new manifest and submit the PR for packages that have changed at the same URL.

**Comment by auanasgheps** [comment]
That's wonderful, thanks!
