### ISSUE TITLE
README lacks instructions on how to add this repository to winget

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/winget-pkgs#3270]
Title. I've just installed winget and stumbled upon this neat community repository. Unfortunately I have no idea how to add it. I would assume the GitHub URL also serves as the winget repo URL, but apparently not:

```
> winget source add -n Community https://github.com/microsoft/winget-pkgs

Adding source:
  Community -> https://github.com/microsoft/winget-pkgs
An unexpected error occurred while executing the command:
No ranges for the specified operation were able to be processed.
```

I would submit a PR myself to fix this, but I don't know what the correct way to add the repo is.

**Comment by Jaiganeshkumaran** [comment]
@NSExceptional This repository is automatically added when you install WinGet by default so no need to add it manually.

**Comment by NSExceptional** [comment]
Oh, hm. The URL that shows up in `source list` looks like it would be a different repo judging by the domain. Sorry
