### ISSUE TITLE
[Package Request]: Snappy Driver Installer

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#32778]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Glenn Delahoy
Publisher Url: https://www.snappy-driver-installer.org
Package Name: SDIO
Description: Driver Installation and Update Tool
Package Version: 1.11.3
Installer URL: https://www.snappy-driver-installer.org/downloads/SDIO_1.11.3.738.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
@denelon - Can you update title? `[Package Request]: Snappy Driver Installer`
