### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by fabcard** [microsoft/winget-pkgs#32782]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: abbodi1406
Publisher Url: https://github.com/abbodi1406
Package Name: VisualCppRedist AIO
Description: 

    AIO Repack for latest Microsoft Visual C++ Redistributable Runtimes, without the original setup bloat payload.

    Built upon VBCRedist_AIO_x86_x64.exe by @ricktendo64

    The process is handled by a windows command script, which runs hidden in the background by default.

    Before installation, the script will check and remove existing non-compliant Visual C++ Runtimes, including the original EXE or MSI setups, or older MSI packages versions.

    The uninstallation option/script will remove any detected VC++ runtimes (except UCRT).

    Windows XP support is partial, the pack will install and detect latest runtimes versions, but it will not check and remove non-compliant versions.

    You can extract the installer file with 7-zip or WinRar to a short path, and run Installer.cmd as administrator

Package Version: 0.54.0
Installer URL: https://github.com/abbodi1406/vcredist/releases/download/v0.54.0/VisualCppRedist_AIO_x86_x64_54.zip or https://rebrand.ly/vcredist or https://kutt.it/vcppredist

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
* #141508 

###### Close with reason: Package added;
