### ISSUE TITLE
[Package Request]:  Avogadro

### ISSUE THREAD

**Issue by mveril** [microsoft/winget-pkgs#32813]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Avogadro Chemistry
Publisher Url: https://avogadro.cc
Package Name: Avogadro
Description: An intuitive molecular editor and visualization tool
Package Version: 1.2.0.20190217
Installer URL: https://jztkft.dl.sourceforge.net/project/avogadro/avogadro/1.2.0/Avogadro-1.2.0n-win32.exe

Current Package Identifier (for new versions):

**Comment by Amoenus** [comment]
Added #33945

**Comment by mveril** [comment]
Thanks @Amoenus

**Comment by Amoenus** [comment]
@mveril 
 #33945 is merged, please check that it installs fine for you via `winget`

**Comment by mveril** [comment]
It's work fine!
Thank you
