### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/winget-pkgs#329]
This should help a lot with format on save that sane developers have.

https://editorconfig.org/

I wasn't able to figure out if this repo uses 2, 4, [or even 0](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) (*Come on, Kevin!*) spaces for indentation. It's quite frustrating.

**Comment by maxmichels** [comment]
I would support this!! In the "original" project winget-cli they use 4 spaces indention.

**Comment by msftrubengu** [comment]
Given that manifest are yml files using 2 spaces indentation looks like the right approach.
