### ISSUE TITLE
[Request] Add a "privacy_policy" to all manifests

### ISSUE THREAD

**Issue by thecodingdude** [microsoft/winget-pkgs#330]
I'm sure I am not alone in thinking each package should have a link to the packages privacy policy. In a world where the GDPR exists, all applications that are included in this package manager should have some form of quality control.

It would be nice if there was a set standard enforced here, such as ensuring there is a contact for a companies DPO, and how they handle the various GDPR articles and user rights. Any package with an inadequate privacy policy would be nominated for removal.

**Comment by JohnMH** [comment]
I'm not sure what having a privacy policy has to do with "quality control", or what that has to do with GDPR.. GIMP has absolutely no privacy policy, for example, and there's no reason for it to.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/571

**Comment by denelon** [comment]
This has been added to the draft for the next version of the manifest schema.

https://github.com/microsoft/winget-cli/discussions/646

**Comment by JohnMH** [comment]
Is PrivacyURL an optional field? Otherwise, this is damaging to software that doesn't have a privacy policy.

**Comment by denelon** [comment]
Yes, it's optional.
