### ISSUE TITLE
[Package Request]: Languagetools

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#33090]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Languagetools
Publisher Url: https://languagetool.org/windows
Package Name: langaugetools
Description: spellcheck app
Package Version: 1.0.2
Installer URL: https://languagetool.org/download/windows-app/LanguageTool-1.0.2.exe

Current Package Identifier (for new versions): 1.0.2

**Comment by OfficialEsco** [comment]
Added in https://github.com/microsoft/winget-pkgs/pull/33050
