### ISSUE TITLE
Question about Windows Store apps

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/winget-pkgs#331]
Will Windows Store applications be supported with winget? I'd like to be able to submit a pull request for one of my Windows apps on the Store.

On a side note, props for all the hard work you all have done on this so far!

**Comment by atomic1fire** [comment]
I think it would be even better if every (purchased/free) windows store app was treated as part of the repository, personally. 

Although I don't know how purchases would work unless winget relies on the user's microsoft account.

But it does sound like this is something they're aware of.

https://github.com/microsoft/winget-cli/issues/117

**Comment by nitishvijai** [comment]
@atomic1fire Exactly! I think this in itself would help improve the winget repository immensely.

**Comment by jvintzel** [comment]
We are tracking this issue in the open source client repository.  https://github.com/microsoft/winget-cli/issues/117
