### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#33583]
### Brief description of your issue

Hello,
Fresh Windows 10 x64 install. Run my script and a error appears when trying to install EarTrumpet.
My script:
`winget install --id=rammichael.7+TaskbarTweaker  -e ;
winget install --id=Lexikos.AutoHotkey -e  ;
winget install --id=Piriform.CCleaner -e  ;
winget install --id=SingularLabs.CCEnhancer -e  ;
winget install --id=File-New-Project.EarTrumpet -e  ;
winget install --id=ESET.Security  -e ;
winget install --id=Mozilla.Firefox -e  ;
winget install --id=Tonec.InternetDownloadManager -e --force ;
winget install --id=KeePassXCTeam.KeePassXC -e  ;
winget install --id=Notepad++.Notepad++ -e  ;
winget install --id=qBittorrent.qBittorrent -e  ;
winget install --id=DavidMoore.IPFilterUpdater -e  ;
winget install --id=QL-Win.QuickLook -e ;
winget install --id=RevoUninstaller.RevoUninstallerPro -e ;
winget install --id=Rufus.Rufus -e  ;
winget install --id=Ookla.Speedtest -e  ;
winget install --id=VideoLAN.VLC -e ;
winget install --id=t1m0thyj.WinDynamicDesktop -e ;
winget install --id=RARLab.WinRAR -e`
Error:
![EarTrumpet](https://user-images.githubusercontent.com/88634350/139749874-7884c963-d02d-456f-9cb4-24b84514d73b.jpg)

### Steps to reproduce

Fresh Windows install and run the script.

### Expected behavior

Install EarTrumpet with no error.

### Actual behavior

EarTrumpet not installed with error. 

### Environment

```shell
Windows Package Manager v1.1.12701
Windows 10 Pro 21H1 19043.1288
```

**Comment by jedieaston** [comment]
EarTrumpet requires some dependencies, and I don't know what they are. App Installer says "ask the developer for {blank} package"

**Comment by denelon** [comment]
@riverar it looks like we may have a bug to fix.
