### ISSUE TITLE
[Bug]: PowerShell v7.2.0-preview10 is detected as update for PowerShell v7.2.0-rc1 in WinGet

### ISSUE THREAD

**Issue by IGR2014** [microsoft/winget-pkgs#33622]
### Brief description of your issue

PowerShell v7.2.0-rc1 should be an update for PowerShell v7.2.0-preview10 when updating over WinGet.
I believe the problem is because versions are defined as follow:
**7.2.0.10** for PowerShell v7.2.0-preview10
**7.2.0.1** for PowerShell v7.2.0-rc1

### Steps to reproduce

Just execute `winget upgrade ` inside PowerShell v7.2.0-rc1 and you will see suggested update to PowerShell v7.2.0-preview10 which seems to be a downgrade actually

### Expected behavior

Update order:
PowerShell v7.2.0-preview10 -> PowerShell v7.2.0-rc1

### Actual behavior

Update order
PowerShell v7.2.0-rc1 -> PowerShell v7.2.0-preview10

### Environment

```shell
Windows Package Manager v1.1.12663
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.22000.282
Пакет: Microsoft.DesktopAppInstaller v1.16.12663.0

Журналы: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by OfficialEsco** [comment]
I was so confused about this but got there in the end
`PowerShell v7.2.0-rc1` installs as `7.2.0.1`
while `PowerShell v7.2.0-preview10` installs as `7.2.0.10`

This cannot be solved in the current Manifest Version, this can be fixed in Manifest Version 1.1 if we get the channel support figured out.

**Comment by TravisEz13** [comment]
There is a PR out to fix this in future PowerShell RC releases:  https://github.com/PowerShell/PowerShell/pull/16354

**Comment by IGR2014** [comment]
Ouch, sorry, I didn`t found your issue in PowerShell repo. My bad, guess it's more related to PowerShell than WinGet

**Comment by IGR2014** [comment]
I can see it's now resolved by this commit: https://github.com/PowerShell/PowerShell/commit/00d39fa4d5f562f3ee03df7f0d0355501eb1af4a
So thanks to @TravisEz13

**Comment by IGR2014** [comment]
> Thanks. We do RC releases so seldomly. Bugs in specialized code, specific to the RC, like this are difficult to find. 😞

It's okay, this is why enthusiasts like me are here testing latest releases)
