### ISSUE TITLE
[Bug]: Installing F5 Access App I receive error of no Store Account but can install other Apps such as Teams and Zoom

### ISSUE THREAD

**Issue by 46dikumar** [microsoft/winget-pkgs#34313]
### Brief description of your issue

C:\WINDOWS\system32>winget install "F5 Access"
Found F5 Access [9WZDNCRDSFN0] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: F5 Networks
Publisher Url: http://www.f5.com
Publisher Support Url: mailto:SupportEdgeClientWP@f5.com
Description: F5 Access secures enterprise application and file access from your Windows 10 and Windows 10 Mobile device using SSL VPN technologies, as a part of an enterprise deployment of F5 BIG-IP Access Policy Manager (TM).

Requirements:
F5 Access is a free application, but requires a valid license on F5 BIG-IP Access Policy Manager.  BIG-IP Access Policy Manager must be running version 11.5 or later.  Please contact your IT administrator to check if your organization is ready to F5 Access for Windows 10.

Licence: https://cdn.f5.com/product/apm/apps/eula.html
Privacy Url: https://www.f5.com/company/policies/privacy-policy
Agreements:
Category: Utilities & tools
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: yes
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition failed: no store account found

### Steps to reproduce

Certain Apps install without any problem but installing F5 Access I get no store account found error. Please advise

### Expected behavior

![image](https://user-images.githubusercontent.com/93883483/140659968-25e3e878-886f-4c74-8f83-1b255a51f069.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/93883483/140659922-8c4d514f-8c73-42b0-b803-c954a8f7961f.png)

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1288
Package: Microsoft.DesktopAppInstaller v1.16.12653.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

C:\WINDOWS\system32>
```

**Comment by ItzLevvie** [comment]
Is this issue and https://github.com/microsoft/winget-cli/issues/1585 the same?

Both complains about the "no store account found"

A workaround is to sign into the Microsoft Store.

**Comment by 46dikumar** [comment]
Hi Levvie, I don't get the message of "No store account found" with other Apps like I mention Teams or Zoom. I am not able to understand why this "F5 Access" requires Sign-in. Also, I am signed in to Microsoft Store using Work Account. Signed out and back sign-in but it is strange that this particular app or maybe some others throw the error!

**Comment by OfficialEsco** [comment]
You require a Microsoft Account because this is a msstore package, not a winget-pkgs package.

**Comment by ItzLevvie** [comment]
> I don't get the message of "No store account found" with other Apps like I mention Teams or Zoom

I think I understand why.

Zoom is an unpackaged Win32 app in the Microsoft Store which doesn't require a MSA to download.

F5 Access seems to be a packaged MSIX/APPX application (`F5Networks.vpn.client_btcnfmkykcjs2) which requires a MSA to download.

Microsoft Teams (Electron) doesn't use the Microsoft Store, the application you're installing is from this repository, denoted as `winget` in `winget list`'s source column.
