### ISSUE TITLE
P.S.A. Holidays

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#34366]
Hello everyone. I wanted to let you all know as we enter into the holidays, there will be periods of less activity. Many of the Microsoft employees working on the project have substantial amounts of paid time off subject to loss if they are not taken this year. Many of the areas of focus during this time are in support of engineering improvements to help make the team more efficient when troubleshooting issues or spending time "on-call" to support various aspects of the services and integration between GitHub and Azure DevOps.

Edit:
The following dates are observed holidays:
* December 23, 2021 
* December 24, 2021
* December 31, 2021

**Comment by OfficialEsco** [comment]
Please prioritize cleaning up these PRs as much as possible before any holidays
https://github.com/microsoft/winget-pkgs/pulls?q=is%3Aopen+is%3Apr+label%3AModerator-Approved+-label%3AValidation-Completed

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/microsoft/winget-pkgs/issues/34366#issuecomment-965086003".

However, do not rush, because that is likely to be more problematic.
Hopefully, your period of recreation shall be pleasant.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Hopefully, your period of recreation shall be pleasant.

**Comment by OfficialEsco** [comment]
Those PRs are >5% of the PRs we Moderators validate in a week, these PRs are already validated by us and are blocked because Microsoft them self choose to, the amount of blocked PRs are caused by Microsoft applying the Validation-Completed ONCE a week instead of fixing the issue.
