### ISSUE TITLE
[Package Request]: VeraCrypt

### ISSUE THREAD

**Issue by EricMGVS** [microsoft/winget-pkgs#34519]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: IDRIX
Publisher Url: https://veracrypt.fr/
Package Name: VeraCrypt
Description: Free Open source disk encryption with strong security for the Paranoid
Package Version: 1.24-Update7
Installer URL: https://launchpad.net/veracrypt/trunk/1.24-update7/+download/VeraCrypt%20Setup%201.24-Update7.exe

**Comment by KaranKad** [comment]
https://github.com/veracrypt/VeraCrypt/issues/447

**Comment by Trenly** [comment]
Duplicate of #18101

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This issue should be closed because of the existence of "http://github.com/microsoft/winget-pkgs/issues/18101".
