### ISSUE TITLE
[Package Request]: easeus partition master

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#34766]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Easeus 
Publisher Url: https://www.easeus.com/partition-manager/epm-free.html
Package Name: easeus partition master
Description: harddisk manager
Package Version:  2021.1.3
Installer URL: https://download2.easeus.com/epm_setup.php?product=epm_free&tid=B&id=589&dateline=1636815322

Current Package Identifier (for new versions): 1.3

**Comment by OfficialEsco** [comment]
@Trenly
```
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /S
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /SILENT
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /q
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /quiet
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /exenoui
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe --silent
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe -s
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /S /v/q
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe --silent --system-level
PS M:\> C:\Users\User\Downloads\epm_free_Installer_20211230.589.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
```
https://community.chocolatey.org/packages/PartitionMasterFree#files
![VirtualBoxVM_dhacltELid](https://user-images.githubusercontent.com/15158490/147753908-5c67eae2-56b7-4285-84d1-cea90ae40015.png)

**Comment by Trenly** [comment]
@OfficialEsco  -
```
InstallerUrl: http://download.easeus.com/free/epm.exe
InstallerSwitches:
  Silent: /SP- /VERYSILENT
  SilentWithProgress: /SP- /VERYSILENT
  Custom: /NORESTART
```

**Comment by OfficialEsco** [comment]
Hmm, Chocolatey got the 16.0 version tho, this one installs 14.5
![VirtualBoxVM_VWhfFZWmyz](https://user-images.githubusercontent.com/15158490/147839901-4203eaf6-70fd-4973-b72d-4affec9e225a.png)

**Comment by Trenly** [comment]
> Hmm, Chocolatey got the 16.0 version tho, this one installs 14.5 ![VirtualBoxVM_VWhfFZWmyz](https://user-images.githubusercontent.com/15158490/147839901-4203eaf6-70fd-4973-b72d-4affec9e225a.png)
> 
> edit: found 15.0 http://download.easeus.com/free/epm_free.exe

I don't know why they seem to have so many different url's. I'll keep digging here too

**Comment by Trenly** [comment]
I found a link for 16.6, but still don't know how to do silent install https://down.easeus.com/product/epm_free

**Comment by SpecterShell** [comment]
https://download.easeus.com/free/epm_suite_freeB18.exe
Let me do some research first.🤔

**Comment by OfficialEsco** [comment]
What the url, well i can confirm it does work
![VirtualBoxVM_iDLW6J7sFS](https://user-images.githubusercontent.com/15158490/148796167-3608d15c-411d-4495-b296-5f24bb1e1475.png)

Via that file name i found https://download.easeus.com/free/epm_suite_free.exe which installs 16.0
![VirtualBoxVM_7q1ysqYtOJ](https://user-images.githubusercontent.com/15158490/148796562-6015ba94-f0a3-4d4a-9d35-acc616842c29.png)

However is it actually the same package?
![VirtualBoxVM_kzxx6mMZ8g](https://user-images.githubusercontent.com/15158490/148796972-251c5188-83c0-4f39-a891-9defb6fd239b.png)


Question, is it just my VM that is in the upside down world?
![VirtualBoxVM_E7zURq1Ia0](https://user-images.githubusercontent.com/15158490/148796737-28ab1bd3-4626-4572-92c3-3756f00bf533.png)

**Comment by SpecterShell** [comment]
https://download.easeus.com/free/epm_free_B16.exe
Install the Partition Master without installing the Suite.

**Comment by OfficialEsco** [comment]
That does indeed look more correct, sweet
