### ISSUE TITLE
[Package Request]: ntop

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#34765]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:  gsass1
Publisher Url: https://github.com/gsass1/NTop
Package Name: ntop
Description: system-monitor with Vi-emulation for Windows
Package Version: 0.3.4
Installer URL: https://github.com/gsass1/NTop/releases/download/v0.3.4/ntop.exe

Current Package Identifier (for new versions): 0.3.4

**Comment by KaranKad** [comment]
Blocked by https://github.com/microsoft/winget-cli/issues/182
