### ISSUE TITLE
[Package Request]: strawberrymusicplayer

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#34764]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Jones kvinge
Publisher Url: https://www.strawberrymusicplayer.org/
Package Name: strawberrymusic player
Description: strawberry music player without debug
Package Version: 1.0
Installer URL: https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.0/StrawberrySetup-1.0.0-Qt6-x64.exe

Current Package Identifier (for new versions): 1.0

I know there is an existing app with ID StrawberryMusicPlayer.Strawberry. But, that one created additional debug menu that cannot be disabled. So, this one is the clean installation.

**Comment by KaranKad** [comment]
Thanks for pointing that out, should be resolved with https://github.com/microsoft/winget-pkgs/pull/34767
