### ISSUE TITLE
[Bug]: MiniToolSoftwareLimited.MiniToolPartitionWizardFree Package installs program, which it isn't supposed to.

### ISSUE THREAD

**Issue by XXDoMi77** [microsoft/winget-pkgs#34762]
### Brief description of your issue

The package "MiniToolSoftwareLimited.MiniToolPartitionWizardFree" also installs "MiniTool ShadowMaker PW Edition"

Also on a side note, it also opens a website after the installation is finished, but that doesn't bother me as much as other software being installed...

### Steps to reproduce

Install the package as Administrator with following command:

```
winget install -e -h --accept-package-agreements --accept-source-agreements MiniToolSoftwareLimited.MiniToolPartitionWizardFree
```

### Expected behavior

The package should only install MiniTool Partition Wizard Free and not any other software from MiniTool.

### Actual behavior

The package installs MiniTool Partition Wizard Free and also installs "MiniTool ShadowMaker PW Edition"

### Environment

```shell
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by Trenly** [comment]
Please note this package has also been renamed to `MiniTool.PartitionWizard.Free`
