### ISSUE TITLE
[Package Request]: genymotiondesktopwithoutvirtualbox

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#34770]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Genymotion
Publisher Url: https://www.genymotion.com/download/
Package Name: Genymotiondesktopwithoutvirtualbox
Description: android virtualisation
Package Version: 3.2.1
Installer URL: https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment]
```
Selection: 1

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: Genymobile.Genymobile

[Required] Enter the version. for example: 1.33.7
Version: 3.2.1

[Required] Enter the download url to the installer.
Url: https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe
[Error] Invalid URL Response - The URL did not return a successful response from the server
```

```
❯ wingetcreate new https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe
Downloading and parsing: https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe...
Failed to download installer.
HTTP response was unsuccessful. Status code: Forbidden
```

**Comment by SpecterShell** [comment]
A User-Agent like `Microsoft-Delivery-Optimization/10.1` is needed to visit this URL, otherwise it will return a Cloudflare captcha page.
Both WinGetCreate and YamlCreate should put a User-Agent into the session.

**Comment by Trenly** [comment]
Unless I'm doing something wrong, the User-Agent didn't seem to work

![image](https://user-images.githubusercontent.com/12611259/151064846-668ff1f0-e7d7-45cd-9f30-517f45daa0a0.png)

**Comment by SpecterShell** [comment]
Should be done in this way:
```PowerShell
$_WebClient.Headers.Add("User-Agent", "Microsoft-Delivery-Optimization/10.1")
```

And do not forget `Test-Url`:
```PowerShell
$HTTP_Request.Headers.Add("User-Agent", "Microsoft-Delivery-Optimization/10.1")
```
