### ISSUE TITLE
The Package ATLauncher (ATLauncher.ATLauncher) does not leave a version number.

### ISSUE THREAD

**Issue by ETHREAL1** [microsoft/winget-pkgs#35125]
### Brief description of your issue

The Package ATLauncher (ATLauncher.ATLauncher) does not leave a version number. So whenever "winget upgrade --all" is run it reinstall an older version of ATLauncher. Also of note is the Package is not made by the makers of ATLauncher. The real makers are here: https://atlauncher.com/ and I have contacted them and they did not make the Winget package.

### Steps to reproduce

1. Install ATLauncher by running "winget install ATLauncher".
2. Do a full package update by running "winget upgrade --all".
You can do step 2 as many times as you would like and it will always redownload and install ATLauncher again. Not to mention it's an older version as well and if you open ATLauncher it updates its self each time after using winget.

### Expected behavior

To only update the package when there is actually an update.
Or have it only install a base version and let ATLauncher update its self.

### Actual behavior

Every time a full package upgrade is run it install an older version of ATLauncher.

### Environment

```shell
Windows Package Manager v1.1.12663
Windows: Windows.Desktop v10.0.22000.346
Package: Microsoft.DesktopAppInstaller v1.16.12663.0

ATLauncher (ATLauncher.ATLauncher)
```

**Comment by Trenly** [comment]
This isn't something that can be fixed by winget. Only the publisher of the application can truly fix this issue.
As a temporary workaround, you could enter a registry key. I'll try and find the exact key which needs to be updated

**Comment by ETHREAL1** [comment]
> This isn't something that can be fixed by winget. Only the publisher of the application can truly fix this issue.
> As a temporary workaround, you could enter a registry key. I'll try and find the exact key which needs to be updated

How would one contact the package makers then? The makers of the program did not make or provide permission to make the winger package.

**Comment by Trenly** [comment]
I already reached out to them -
> [8:55 PM] RyanTheAllmighty: Yup, looks like I missed that version property when I initially made it. I'll take a look and get that updated

**Comment by RyanTheAllmighty** [comment]
I've added in a version (`1.0.0.0`) and changed the name of the record in the registry to `ATLauncher Setup`.

The files been uploaded to `https://download.nodecdn.net/containers/atl/app/dist/windows/ATLauncher-setup-1.0.0.0.exe` with sha256 of `871ff4cf041367b02513228b0f00c5bb4df7028c795a4d6cd3577c1dcdc2e356`

The setup that's run always downloads the latest version of the application, so the winget shouldn't need to get updated going forward unless winget moves to a more publisher pushing out updates in non setup form, similar to AUR, then I'd definitely want to take a look at automating that.

Let me know if that solves the issue going forward.

**Comment by ETHREAL1** [comment]
> I've added in a version (`1.0.0.0`) and changed the name of the record in the registry to `ATLauncher Setup`.
> 
> The files been uploaded to `https://download.nodecdn.net/containers/atl/app/dist/windows/ATLauncher-setup-1.0.0.0.exe` with sha256 of `871ff4cf041367b02513228b0f00c5bb4df7028c795a4d6cd3577c1dcdc2e356`
> 
> The setup that's run always downloads the latest version of the application, so the winget shouldn't need to get updated going forward unless winget moves to a more publisher pushing out updates in non setup form, similar to AUR, then I'd definitely want to take a look at automating that.
> 
> Let me know if that solves the issue going forward.

Just tied it out. The problem still persists... It does say it's installing 1.0.0.0 but after the install, if you list installed packages ATLaunchers version is still unknown...

**Comment by RyanTheAllmighty** [comment]
Looking at https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/ATLauncher/ATLauncher/1.0.0.0/ATLauncher.ATLauncher.installer.yaml it has the wrong installer url which would be the issue. It's pointing to the download redirect from the site, but that's not updated yet.

I'll update it to fix it going to the wrong version, but the hash will not match then

**Comment by Trenly** [comment]
I’ll submit the fix for winget

**Comment by RyanTheAllmighty** [comment]
Looks like running `winget upgrade --all` after installing ATLauncher through winget now no longer shows an update. Thanks for the support @Trenly looks all resolved now 👍🏻
