### ISSUE TITLE
Sonos S1 Controller manifest needs to be updated with latest installer (v11.2.2)

### ISSUE THREAD

**Issue by BookWorm0** [microsoft/winget-pkgs#3529]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
Sonos has released a new version of the S1 Controller app (v11.2.2), and a manifest update is required.

# Steps to reproduce
Launch Sonos S1 Controller and connect to system.
Under “Select a Music Source,” observe “Update Now”.
Select “Update Now”. Only the Windows controller app is updated.

# Expected behavior
Expected: No “Update Now”

# Actual behavior
Under “Select a Music Source,” observe “Update Now”.

# Environment
Windows Package Manager v0.1.42241 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.1082
Package: Microsoft.DesktopAppInstaller v1.10.42241.0

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

**Comment by yigitemres** [comment]
This is fixed with #3530. Needs to be closed.
