### ISSUE TITLE
[Package Request]:  Remove Fizzi.SlippiLauncher off repository

### ISSUE THREAD

**Issue by ABOhiccups** [microsoft/winget-pkgs#35316]
The developer request to remove Slippi Launcher off repository.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/Fizzi

**Comment by OfficialEsco** [comment]
Since you added them, do you want US to remove them? Also would be nice if you shared the thread/chat logs.

Does this ping them @project-slippi? For a official confirmation

**Comment by ABOhiccups** [comment]
> Since you added them, do you want US to remove them? Also would be nice if you shared the thread/chat logs.
> 
> Does this ping them @project-slippi? For a official confirmation

Yes, go ahead and remove them.
