### ISSUE TITLE
Azure Pipelines doesn't listen to bots.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#35372]
### Brief description of your issue

Moderators can now request the tests to run. Awesome! But when @msftbot tries to run `/azp run`, azure-pipelines denies it since @msftbot is not [a collaborator in the repository](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#troubleshoot-pull-request-comment-triggers). @msftbot can't be a collaborator in the repository since it isn't a GitHub user, but a GitHub app (which has a whole different permissions setup).

![image](https://user-images.githubusercontent.com/21368066/142667878-4b80ce77-46c1-40b8-a786-e0ba8b38d7a0.png)

### Steps to reproduce

1. Be a moderator!
2. Type `/rerun-pipelines-please` into a comment on a failed pull request. 
3. Look at @msftbot try its best to run the pipelines again.
4. Watch as ADO denies it.

### Expected behavior

ADO to be nice to @msftbot, because even though we all have problems with them, they're trying their best!

### Actual behavior

The pipelines don't run because ADO can't verify that @msftbot has permissions to run the pipelines.

### Environment

```shell
Windows Package Manager v1.1.12986

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Any other software? I replaced explorer.exe with Microsoft Bob, that doesn't cause an issue, right?
```

**Comment by jedieaston** [comment]
@denelon Is there a way to have @msftbot do requests against the GitHub API? What we could do as a stopgap is use the [Run Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops) GitHub Action and have it set to manual run only, then have @msftbot when hearing the magic phrase trigger the action [via the API](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event). Since @msftbot has enough permissions to use that API (since it's a GitHub app) it should work.

I know this is a bit silly (use CI to run different CI), but since we don't have any roadmap on ADO implementing it the way we want this is a simple stopgap. I can write the action if you think it is a good idea.

**Comment by vedantmgoyal2009** [comment]
I also wrote the action. Pull Request: https://github.com/microsoft/winget-pkgs/pull/30387

**Comment by jedieaston** [comment]
That action unfortunately wouldn’t work for the same reason the current @msftbot setup doesn’t work, as ADO doesn’t see it as having equivalent permissions.

**Comment by vedantmgoyal2009** [comment]
My action uses PAT of @wingetbot for authorization and since @wingetbot is a collaborator, it should work. The main concern at that time was: https://github.com/microsoft/winget-pkgs/pull/30387#discussion_r729644701 (security concern).

**Comment by denelon** [comment]
I believe the team has a different approach in mind. I've just asked to get an idea of the level of effort remaining. Hopefully it's not too big, and we can get this unblocked.
