### ISSUE TITLE
[Package Request]: yt-dlp

### ISSUE THREAD

**Issue by 1hiking** [microsoft/winget-pkgs#35475]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: yt-dlp
Publisher Url: https://github.com/yt-dlp/yt-dlp/releases
Package Name: yt-dlp
Description: A youtube-dl fork with additional features and fixes
Package Version: 2021.11.10.1
Installer URL: https://github.com/yt-dlp/yt-dlp/releases/download/2021.11.10.1/yt-dlp.exe

Current Package Identifier (for new versions):

**Comment by KaranKad** [comment]
Blocked by https://github.com/microsoft/winget-cli/issues/140 and https://github.com/microsoft/winget-cli/issues/182
