### ISSUE TITLE
[Package Request]: ludusavi

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#35471]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: mtkennerly
Publisher Url: https://github.com/mtkennerly/ludusavi
Package Name: ludusavi
Description:  Backup tool for PC game saves 
Package Version: 0.10.0
Installer URL: https://github.com/mtkennerly/ludusavi/releases/download/v0.10.0/ludusavi-v0.10.0-win64.zip

Current Package Identifier (for new versions):

**Comment by vedantmgoyal2009** [comment]
For future visitors, the developer is waiting for .zip support for winget.

https://github.com/mtkennerly/ludusavi/issues/56#issuecomment-722612878
