### ISSUE TITLE
[Package Request]: retroarch

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#35545]
### Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: retroarch-team
Publisher Url: https://www.retroarch.com/index.php
Package Name: retroarch
Description: RetroArch is a frontend for emulators, game engines and media players. 
Package Version: 1.9.12
Installer URL: https://buildbot.libretro.com/stable/1.9.12/windows/x86_64/RetroArch-Win64-setup.exe

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/discussions/34891

**Comment by nopeinomicon** [comment]
Would argue that this is dependent pretty much only on https://github.com/microsoft/winget-cli/issues/182 . Retroarch *can* be run even without the old DX9 package (Retroarch features both DX11 and Vulkan rendering engines), but the installer pretty much forces you to have it assuming you want a silent install. There is however a portable zip file version of Retroarch that avoids this issue entirely assuming implementation of the aforementioned feature.

**Comment by ProustIdee** [comment]
I'm not sure if this is the best place to post this, but why does Retroarch show up in Winget when installed from Steam?

```
Name                                            Id                            Version        Available      Source
------------------------------------------------------------------------------------------------------------------
RetroArch                                       Libretro.RetroArch            Unknown        1.10.3.0       winget
```

I can't think of another package that does this. I'm not sure what would happen if I let Retroarch "upgrade". Two installations?

**Comment by OfficialEsco** [comment]
Because the Steam installer does not set the DisplayVersion registry string.
It would be 2 installations yeah because your current install is under the Steam folder.
Very soon these will be hidden under a --include-unknown switch. (or you can install a Release Candidate Pre-Release of [WinGet-CLI](https://github.com/microsoft/winget-cli/releases))
