### ISSUE TITLE
Installer failed with exit code: 1610

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#35740]
### Brief description of your issue

I try to install Google.Drive with the following command : 

winget install Google.Drive

I face the following issue. 

Installer failed with exit code: 1610

### Steps to reproduce

Open Terminal under Windows 11 and execute the following command : 

winget install Google.Drive

### Expected behavior

To install Google.Drive

### Actual behavior

Facing the issue with following text : 

Installer failed with exit code: 1610

### Environment

```shell
winget --info
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
This error message is coming from the installer for the package. I believe it is an MSI packaged inside of an EXE. The MSI error 1610 indicates:

The configuration data for this product is corrupt. Contact your support personnel.

I'd suggest searching for that specific error related to the package, or contacting the publisher.

**Comment by ivonenchev** [comment]
I was installled the Google.Drive

**Comment by oswinrodrigues** [comment]
> I have installled the Google.Drive

What was the solution here? Did you install it using `winget`? If so, how did you overcome the `1610` error?

**Comment by soredake** [comment]
Reboot solved this error for me with google drive.
