### ISSUE TITLE
Improved YAML support inside of VSCode

### ISSUE THREAD

**Issue by JPinkney** [microsoft/winget-pkgs#360]
# Description of the new feature/enhancement
Hi! This isn't really a feature request I just more or less wanted to people know that a JSON schema has been provided to the json schema store for the manifest YAML files: https://github.com/SchemaStore/schemastore/pull/1049.

What this means is that when that PR is merged if you open up this repository inside of VSCode you will get intellisense (Hover, Completion, Validation) for all of the manifest yaml files as long as you have https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml installed.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
There is also a YAML extension from Red Hat you can use. I would personally use that in addition to any IntelliSense from this schema.

**Comment by JPinkney** [comment]
When the schema is merged on the schema store the Red Hat YAML extension will automatically pick up the schema for the manifest/\*/\*/\*.yml files (I created the Red Hat YAML extension)

**Comment by WSLUser** [comment]
Cool! Thanks for the awesome extension then. I didn't realize you created it.

**Comment by felipecassiors** [comment]
Since it's merged, I think this can be closed.

![image](https://user-images.githubusercontent.com/29582865/83700777-2036b380-a5de-11ea-9622-15882f2d38cc.png)
