### ISSUE TITLE
install PowerBi fails with installer has does not match

### ISSUE THREAD

**Issue by ChristianBeier** [microsoft/winget-pkgs#36008]
### Brief description of your issue

When I try to update or do an winget install PowerBI 2.99.621.0 it fails with Installer hash does not match; to override this check use --force

### Steps to reproduce

winget install Microsoft.PowerBi

### Expected behavior

Version 2.99.621.0 gets installed / updated

### Actual behavior

failure

### Environment

```shell
Windows Package Manager (Preview) v1.2.3131-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.17.3131.0

PowerBI version 2.98.1025.0 installed
PowerBi version 2.99.621.0 available
```

**Comment by denelon** [comment]
Another related issue that may help in this scenario:
* microsoft/winget-cli/issues/870

**Comment by Trenly** [comment]
- Resolved by #36051

**Comment by IAmIlliest** [comment]
This issue appears to be back, at least for me. It's failing with the usual hash does not match error again.

**Comment by ItzLevvie** [comment]
Keep an eye on https://github.com/microsoft/winget-pkgs/pull/62922

**Comment by TroldeJens** [comment]
I have the same problem now, when trying to install PowerBI version 2.110.1161.0 using
`winget install Microsoft.PowerBI --source winget`

**Comment by mdanish-kh** [comment]
New version merged; Please try again now.
- https://github.com/microsoft/winget-pkgs/pull/89929

**Comment by pauldj54** [comment]
I think this issue went back again:

![image](https://user-images.githubusercontent.com/706754/220358733-c8fc4dee-a6a0-4e68-8d0a-f8e8995d7b57.png)

**Comment by kenrad24** [comment]
> I think this issue went back again:
> 
> ![image](https://user-images.githubusercontent.com/706754/220358733-c8fc4dee-a6a0-4e68-8d0a-f8e8995d7b57.png)

+1 for me as well. Looks like the hash is broken again.

**Comment by mdanish-kh** [comment]
The PRs for the package are having some issues passing the validation pipelines atm:
- https://github.com/microsoft/winget-pkgs/pull/96887
- https://github.com/microsoft/winget-pkgs/pull/97377

**Comment by nikmartin** [comment]
This issue once again exists: 
```powershell
(1/1) Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.131.1126.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  ██████████████████████████████   498 MB /  498 MB
Installer hash does not match.
```

**Comment by keeper-117** [comment]
This issue once again exists:


![Image](https://github.com/user-attachments/assets/bcec1824-cfeb-4831-8a11-5a8e8522528c)

**Comment by jason-nyc** [comment]
again a problem in v2.138.1004.0.  this isn't a reliable install method unfortunately. 

winget install --id Microsoft.PowerBI --exact --accept-package-agreements --scope Machine
https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe


**Installer hash does not match; this cannot be overridden when running as admin**

**Comment by j1mmyfever** [comment]
+1 Can't install today.

Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  ██████████████████████████████   544 MB /  544 MB
Installer hash does not match.

**Comment by DevOpsMage** [comment]
> This has been a repeating issue across multiple Microsoft products for years. I would think the processes that update these Winget versions would be highly managed, documented and verified/automated by now.
> 
> Can we possibly get some feedback on this issue so we know someone is looking at these and working on a permanent solution?

This is my thoughts exactly. We are almost 4 years on just "this" issue being reported. How has this not been fixed in the CI pipeline?

**Comment by j1mmyfever** [comment]
I actually thought this was potentially a policy issue in my environment
but magically was resolved yesterday with no other changes. Gotta be a
pipeline issue.
