### ISSUE TITLE
[Package Request]: Geek Uninstalller

### ISSUE THREAD

**Issue by nikkehtine** [microsoft/winget-pkgs#36097]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Thomas Koen
Publisher Url: https://geekuninstaller.com/
Package Name: Geek Uninstaller
Description: Fast, efficient, simple uninstaller program
Package Version: 1.4.8.145
Installer URL: https://geekuninstaller.com/geek.zip

Current Package Identifier (for new versions):

**Comment by startadv** [comment]
![image](https://user-images.githubusercontent.com/94285692/143773241-6cdac89d-2942-4274-a6d8-7599688e6d25.png)
The installer is in zip format. So it cannot be added.

**Comment by Trenly** [comment]
Blocked by #174
