### ISSUE TITLE
LibreOffice wrong package manifest location

### ISSUE THREAD

**Issue by NathanBnm** [microsoft/winget-pkgs#36182]
LibreOffice manifests should be located to `TheDocumentFoundation/LibreOffice` instead of `LibreOffice/LibreOffice`.

**Comment by vedantmgoyal2009** [comment]
Following the convention of `Publisher.AppName`, `LibreOffice.LibreOffice` is incorrect.

I have opened the PRs to move the whole package to `TheDocumentFoundation.LibreOffice`.

#36184, #36185, #36186, #36187, #36188, #36189, #36190, #36191, #36192, #36193, #36194, #36195, #36196, #36197, #36198, #36199, #36200, #36201, #36202, #36203
