### ISSUE TITLE
[Package Request]: origin missing

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#36362]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Electronic Arts Inc.
Publisher Url: https://www.origin.com/irl/en-us/store
Package Name: Origin
Description: Platform Packed with Great PC Games
Package Version: 10.5
Installer URL: https://origin-a.akamaihd.net/Origin-Client-Download/origin/live/OriginThinSetup.exe

Current Package Identifier (for new versions):

**Comment by ItzLevvie** [comment]
Last time I checked, it requires VC redist on a clean install of Windows, so it's currently not supported yet.

WinGet will have package dependency support in the future which will allow this package to be added.

**Comment by stephengillie** [comment]
The dependency here appears to be `Microsoft.VCRedist.2015+.x64` (or maybe `.x86`.)
