### ISSUE TITLE
[Bug]: Microsoft.dotnet Downloaded Older Version

### ISSUE THREAD

**Issue by SinaMobasheri** [microsoft/winget-pkgs#36574]
### Brief description of your issue

I try to update all packages but `Microsoft.dotnet` is getting updated every time, look at the version that Winget trying to update vs the version that actually downloaded

Found  [Microsoft.dotnet] ***Version 6.1.21.52711***
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100/dotnet-sdk-6.0.100-win-x64.exe <- ***6.0.100***

### Steps to reproduce

Fix Download Link

### Expected behavior

download version 6.1.21.52711

### Actual behavior

downloaded version 6.0.100

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
6.0.100 is 6.1.21.52711.

**Comment by SinaMobasheri** [comment]
ok i get it (actually not 😀), but it's keep prompt to update every time I run `winget upgrade --all`
@ItzLevvie

**Comment by ItzLevvie** [comment]
Are you getting an error code?

I think if you have multiple NET SDKs installed, it'll try to update all of them which is a known issue and is tracked at https://github.com/microsoft/winget-cli/issues/1105.

**Comment by SinaMobasheri** [comment]
no error code !
but yes i isntalled .Net via Visual Studio Build Tools, Thanks for mentioning That... 💡✋🏻🙏🏻
@ItzLevvie
