### ISSUE TITLE
[Bug]: Mozilla.Firefox.Nightly installs with afrikaans locale

### ISSUE THREAD

**Issue by jonaskuske** [microsoft/winget-pkgs#36588]
### Brief description of your issue

When installing Firefox Nightly, it installs the afrikaans version, `.af` instead of `.en` in download URLs: https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/Nightly/96.0a1/Mozilla.Firefox.Nightly.installer.yaml#L28-L44

### Steps to reproduce

- Run `winget install -e Mozilla.Firefox.Nightly`
- Open Nightly
- Notice the localization is neither English nor your local language (in my case German) but Afrikaans

### Expected behavior

Should install either the English or users' locale version

### Actual behavior

Install the afrikaans version via the [`https://ftp.mozilla.org/pub/firefox/nightly/2021/11/2021-11-16-21-26-01-mozilla-central-l10n/firefox-96.0a1`**_`.af`_**`.win64.installer.exe`](https://ftp.mozilla.org/pub/firefox/nightly/2021/11/2021-11-16-21-26-01-mozilla-central-l10n/firefox-96.0a1.af.win64.installer.exe) download

### Environment

```shell
Windows Package Manager (Preview) v1.2.3131-preview
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1387
Paket: Microsoft.DesktopAppInstaller v1.17.3131.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
@Trenly what did you do? 🤔
https://github.com/microsoft/winget-pkgs/blame/master/manifests/m/Mozilla/Firefox/Nightly/96.0a1/Mozilla.Firefox.Nightly.installer.yaml#L25-L45

**Comment by Trenly** [comment]
Uhhh. Thats a great question. I’m not sure what happened there

**Comment by Trenly** [comment]
> 😁 Ill fix it, gonna add the msix anyways

Thank you; I have a fix ready, but if you're going to add the MSIX I'll focus on some of the yamlcreate bugs
