### ISSUE TITLE
some electron apps fail manual validation.

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#3694]
#3663 WeiyunConcept and #3468 Mitalk install and work successfully on my computer, but they failed to run in manual validation. They are both electron apps.
# Environment

```none
[winget --info]
Windows Package Manager v0.2.2521
Windows: Windows.Desktop v10.0.20215.1000
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Any other software?
```

**Comment by denelon** [comment]
@oxygen-dioxide is this still an issue?
