### ISSUE TITLE
[Bug]: NanaZip unable to upgrade

### ISSUE THREAD

**Issue by Velgus** [microsoft/winget-pkgs#37168]
### Brief description of your issue

With NanaZip 1.0.46.0 installed, it does not upgrade to 1.0.88.0.

It is shown as upgrade-able, but does not change when `winget upgrade --all` is run.

```
PS C:\Users\Velgus> winget upgrade
Name    Id             Version  Available Source
------------------------------------------------
NanaZip M2Team.NanaZip 1.0.46.0 1.0.88.0  winget
```

### Steps to reproduce

1. Have NanaZip 1.0.46.0 installed.
2. Attempt `winget upgrade --all`

### Expected behavior

NanaZip is upgraded to 1.0.88.0.

### Actual behavior

NanaZip remains at 1.0.46.0.

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0
```

**Comment by OfficialEsco** [comment]
```
PS C:\Users\User> winget install M2Team.NanaZip --version 1.0.46.0
Found NanaZip [M2Team.NanaZip] Version 1.0.46.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed

PS C:\Users\User> winget upgrade --all
Found NanaZip [M2Team.NanaZip] Version 1.0.88.0
Found  [M2Team.NanaZip] Version 1.0.88.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed

PS C:\Users\User> winget list
Name                                      Id                                        Version            Available Source
-----------------------------------------------------------------------------------------------------------------------
NanaZip                                   M2Team.NanaZip                            1.0.88.0                     winget
NanaZip                                   M2Team.NanaZip                            1.0.46.0           1.0.88.0  winget
```

![image](https://user-images.githubusercontent.com/15158490/145235785-58460da1-5a3e-4f1d-8283-9a20494c7fea.png)

NanaZip Preview gets installed. This is a issue with NanaZip's weird GitHub Release/Naming Scheme

**Comment by Velgus** [comment]
Looks like the non-preview version for winget was removed, and the preview version is now the only version - works for me.

**Comment by OfficialEsco** [comment]
It appears they released their first stable yesterday which might explain the name change…
https://github.com/M2Team/NanaZip/releases
We’ll see how it plays out, worst case we’ll delete (or move) 1.0.88.0

**Comment by OfficialEsco** [comment]
Should be resolved once #37290 gets merged, we'll see if NanaZip release Previews in the future or just Stable versions before we start making a package named `M2Team.NanaZip.Preview`.
Unless you upgraded to 1.0.95.0 just delete NanaZip Preview and try `winget upgrade NanaZip` later :)

**Comment by OfficialEsco** [comment]
Hey just wanted to let you know, NanaZip is again releasing Previews, as of https://github.com/microsoft/winget-pkgs/pull/37725 there will be 2 packages since they go under different names :)

**Comment by Velgus** [comment]
Thanks for the info!
