### ISSUE TITLE
[Package Request]: qBittorrent

### ISSUE THREAD

**Issue by pwnorbitals** [microsoft/winget-pkgs#37214]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: qBittorrent
Publisher Url: https://www.qbittorrent.org
Package Name: qBittorrent
Description: 
Package Version: 4.3.9
Installer URL: https://www.qbittorrent.org/download.php

Current Package Identifier (for new versions): qBittorrent.qBittorrent

**Comment by OfficialEsco** [comment]
We cannot add qBittorrent because it is marked as PUA. 

* https://github.com/microsoft/winget-pkgs/pull/33459
* https://github.com/microsoft/winget-pkgs/pull/26231
* https://github.com/microsoft/winget-pkgs/pull/23687
* https://github.com/microsoft/winget-pkgs/pull/19135
