### ISSUE TITLE
[Bug]: Sublime Text 4 shows "unknown" version after installation

### ISSUE THREAD

**Issue by Icarusradio** [microsoft/winget-pkgs#37597]
### Brief description of your issue

When I try to install Sublime Text 4 via winget, `winget list` always shows "unknown" for the version of the installed program, which makes it unable to apply updates via `winget upgrade`.

### Steps to reproduce

1. Remove "Sublime Text 4" via the Control Panel
2. Search Sublime Text 4 via `winget search sublime`
3. Install with `winget install -e --id SublimeHQ.SublimeText.4`
4. Check the version with `winget list`

### Expected behavior

The version shows correctly and winget should be able to update Sublime Text 4 via `winget upgrade`.

### Actual behavior

`winget list` shows (the header is "Name ID Version Source" in Chinese)
```
名称                                          ID                                            版本                源
-----------------------------------------------------------------------------------------------------------------------
Sublime Text                                  Sublime Text_is1                              Unknown
```
`winget upgrade --all` does not apply upgrade to Sublime Text 4.

### Environment

```shell
winget --info
Windows Package Manager (Preview) v1.2.3411-preview
Windows: Windows.Desktop v10.0.19044.1387
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```
```

**Comment by denelon** [comment]
@Icarusradio this is likely caused by the entry reported in Apps & Features. Can you check to see if the program version is reported there?

**Comment by Icarusradio** [comment]
> Apps & Features

Yeah, I checked Apps & Features in settings, it does not show the version of Sublime Text.

**Comment by denelon** [comment]
That's what's causing the unknown. The Sublime Text installer isn't reporting the version. They will need to update their installer to report the version. We may be capturing the version based on the file version which isn't necessarily the correct version for the program.

**Comment by denelon** [comment]
I looked at their website. It looks like you can submit a "support" request to ask them to make the change.

**Comment by lutzroeder** [comment]
Duplicate of #126287
