### ISSUE TITLE
P.S.A Back End Service Migration

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#37629]
We will be performing some back-end service migration work. 

This should have minimal impact, but I wanted to inform the community in the event anything causes trouble. The goal is to have minimal downtime for validation and publishing pipelines. There may be some delays caused by DNS. We're targeting Tuesday for the bulk of this work. If we encounter problems, we will notify the community here.

**Comment by denelon** [comment]
We hit a couple of problems. We're going to try again for tomorrow.

**Comment by denelon** [comment]
We have published the changes. We do have some DNS propagation delays, but they should not impact any users.

We do have one issue with the pipeline status badges, we're working to fix that. ETA is tomorrow.

**Comment by OfficialEsco** [comment]
Hopefully this also resolves the stuck Merge/Publishing pipeline?

**Comment by denelon** [comment]
Everything should be back up and working again.
Is there a PR we need to look at for stuck pipeline?

**Comment by denelon** [comment]
We're looking through any pipeline runs that didn't get completed during the migration.

**Comment by OfficialEsco** [comment]
It appears someone have been doing the cleanup yes :)
Remaining PRs:
* https://github.com/microsoft/winget-pkgs/pull/37996
* https://github.com/microsoft/winget-pkgs/pull/37968
* https://github.com/microsoft/winget-pkgs/pull/37898
* https://github.com/microsoft/winget-pkgs/pull/37849
* https://github.com/microsoft/winget-pkgs/pull/37839
* https://github.com/microsoft/winget-pkgs/pull/37688
* https://github.com/microsoft/winget-pkgs/pull/37616

**Comment by zachcarp** [comment]
:rocket:
