### ISSUE TITLE
URL Validation failing because server blocks HEAD requests

### ISSUE THREAD

**Issue by tiernano** [microsoft/winget-pkgs#3798]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When the validation code runs, it checks if the URLs in the manifest are "Correct" by making a HEAD call. the manifest here (https://github.com/microsoft/winget-pkgs/pull/3797) is failing because the underlying server is throwing 405 METHOD NOT ALLOWED errors for HEAD Calls, but responds correctly to GETs.
# Steps to reproduce
manifest above fails due to urls being invalid. urls are valid in browser. checked status with CURL below.

curl -I https://tailscale.com
shows a 405 error

curl https://tailscale.com 
shows the HTML.
# Expected behavior
urls are passed as valid
# Actual behavior

urls are marked as not valid

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2521 Preview
Windows: Windows.Desktop v10.0.20215.1000
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Any other software?
used curl to verify the server was correct:

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by ashpatil-msft** [comment]
This issue should be resolved now.
