### ISSUE TITLE
Create a manifest Gallery website

### ISSUE THREAD

**Issue by ericsampson** [microsoft/winget-pkgs#3799]
# Description of the new feature/enhancement
Having a public Gallery website as a user-friendly way to browse/search the manifests would be excellent. The `search` command in the CLI is a good start, but a website can be a lot richer experience, and some people would find it easier to use.
Examples:
- [NPM](npmjs.com)
- [NuGet](nuget.org)
- [chocolatey](chocolatey.org)
- [brew](brew.sh)
- many others...

Thanks!

**Comment by denelon** [comment]
Take a look at http://winstall.app/, https://winget.run/, or https://github.com/goranalkovic/WinGetGui. All three of those are community built UI mechanisms.
