### ISSUE TITLE
[New Feature]: Move existing projects to projects beta.

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#37991]
### Description of the new feature/enhancement

Migrate to projects beta.

**Comment by jedieaston** [comment]
Is there an example of how this looks for a public project? It looks like the new projects system doesn't really do much unless you are working in a team where kanban isn't enough.

**Comment by vedantmgoyal2009** [comment]
_Sourced from: https://github.blog/changelog/2021-10-27-the-new-github-issues-public-beta_

![image](https://user-images.githubusercontent.com/83997633/146437182-16d5d04e-4da0-4b4b-a73c-1a9576e01845.png)

**Comment by Trenly** [comment]
I think this really depends on how MSFT wants to manage their workflow. If the standard projects framework is working for them, then I don't know that using the beta version would be any benefit

**Comment by denelon** [comment]
I've got a beta project that is already going cross repository. 

https://github.com/orgs/microsoft/projects/137

**Comment by jedieaston** [comment]
That project looks to be set to org only or something — can’t see it as a contributor.

**Comment by vedantmgoyal2009** [comment]
> I've got a beta project that is already going cross repository. 
> 
> https://github.com/orgs/microsoft/projects/137

For us, it is 404, maybe you have set it to private.

**Comment by denelon** [comment]
I'll see if I can figure out where the permissions are. We've got some limitations for beta projects with GitHub when they are organization wide.
