### ISSUE TITLE
Notice [New package version]: IrfanView version 4.59

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38172]
### Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: IrfanSkiljan
Package Name: IrfanView
Package Version: 4.59
Installer URL: https://www.irfanview.com/download_sites.htm

Current Package Identifier: [IrfanSkiljan.IrfanView](https://github.com/microsoft/winget-pkgs/tree/master/manifests/i/IrfanSkiljan/IrfanView)

We're currently waiting for a reliable mirror

| Mirror  | Comment | Example url |
| ------------- | ------------- | ------------- | 
| ❌ Irfanview  | requires headers to be set  | https://www.irfanview.info/files/iview459_x64_setup.exe |
| ❌ FossHub  | https://github.com/microsoft/winget-pkgs/pull/25178#issuecomment-900508433  | |
| ❌ Major Geeks | deletes old versions | |
| ✔️ Fileforum / BetaNews | not updated to 4.59 | https://download.betanews.com/download/967963863-1/iview459_x64_setup.exe |
| ❌ Programosy | deletes old versions | |
| ❌ CNET | Requires Cookie? | |
| ✔️ TechSpot | Static link, keeps old versions | http://files03.tchspt.com/temp/iview459_x64_setup.exe |

If anyone know of a Mirror that keep old versions and we're allowed to use them as a Host please let us know :)

**Comment by vedantmgoyal2009** [comment]
FileForum keeps the old versions. Don't know whether it's safe or not. We can ask the publisher to publish the releases on GitHub or Source Forge.

**Comment by vedantmgoyal2009** [comment]
Also, has anyone from Microsoft or any contributor asked Foss Hub if they can whitelist WinGet for automating the download process?

**Comment by Trenly** [comment]
See also https://github.com/microsoft/winget-pkgs/issues/23933

**Comment by OfficialEsco** [comment]
> See also #23933

Also see https://github.com/microsoft/winget-pkgs/pull/21591 then =) Not sure why they are not linked

I doooon't think we want to use a Vanity url for IrfanView, however that might be what we have to do, then we'll just update the manifest when wingetbot tries to delete the previous one

**Comment by OfficialEsco** [comment]
Still no betanews release.. what cnet url were you thinking of?
https://download.cnet.com/IrfanView-64-bit/3001-2192_4-76444710.html requires a cookie to download
which ONE TIME gave me a url like this but with a bunch trackers
https://prod.downloadnow.com/s/17/05/73/70/iview459_x64_setup.exe
which obv dosn't work without the trackers and i can't get a new url 🤦‍♂️

**Comment by OfficialEsco** [comment]
not active users but i'll try @techspot @techspotbr, can we use you guys as a source? 🤔

**Comment by Trenly** [comment]
> Still no betanews release.. what cnet url were you thinking of? https://download.cnet.com/IrfanView-64-bit/3001-2192_4-76444710.html requires a cookie to download which ONE TIME gave me a url like this but with a bunch trackers https://prod.downloadnow.com/s/17/05/73/70/iview459_x64_setup.exe which obv dosn't work without the trackers and i can't get a new url 🤦‍♂️

Looks like they changed how they distribute URLs ;

I found the files on their site, but it looks like it requires the request to have the headers set. As long as the header has the referrer, then it works. Probably nothing we can do about it for now though
```
wget -Headers @{'Referer'='https://www.irfanview.info/files/iview459_setup.exe'} https://www.irfanview.info/files/iview459_setup.exe -OutFile D:\Users\Trenly\Downloads\Temp\iview_wget_test.exe
```
https://www.irfanview.info/files/iview459_setup.exe
https://www.irfanview.info/files/iview459_x64_setup.exe

**Comment by OfficialEsco** [comment]
uhh, went looking for packages with dependency's, found this

> ```
>    InstallerUrl: https://download.betanews.com/download/1099412658-1/iview458_plugins_x64_setup.exe
>```
>cc @OfficialEsco: do we want to be using the betanews mirror here? I think I might have saw someone removing manifests with betanews URLs because they claimed that it was shipping "spyware" or "bloatware" or something.
>
>_Originally posted by @ItzLevvie in https://github.com/microsoft/winget-pkgs/pull/21591#r671882496_
>
>Actually never mind; the removed manifests were about TechSpot URLs. BetaNews seems fine to me.
>
>_Originally posted by @ItzLevvie in https://github.com/microsoft/winget-pkgs/pull/21591#r671887815_

https://github.com/microsoft/winget-pkgs/pull/42136/files#diff-ce9a042100e3cdc843fcd670fe4c1e3f351c07caae3e12533294d8e0929aba3cR116-R134

However the only thread i can find that mentions techspot in any sort of way was this one..

>Also, not every single package in this repository uses official links. IrfanView is one of them because it doesn't allow hotlinking downloads, so we have to use download links from BetaNews or somewhere else.
>
>A common comment I have seen a few months ago from someone here has said something along these lines: "Please don't use i.e. TechSpot because this website has adware and may have tampered the software." but we got no choice other than to use URLs from various mirrors due to hotlinking. We also check the hashes to make sure it matches the official sources.
>
>_Originally posted by @ItzLevvie in https://github.com/microsoft/winget-pkgs/discussions/31547#discussioncomment-1562995
