### ISSUE TITLE
[New package version]: Intel.IntelDriverAndSupportAssistant version 21.7.50.3

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38197]
### Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Intel
Package Url: https://www.intel.com/content/www/us/en/support/detect.html
Package Name: Intel Driver And Support Assistant
Package Version: 21.7.50.3
Installer URL: in theory this https://downloadmirror.intel.com/28425/a08/Intel-Driver-and-Support-Assistant-Installer.exe
However this one https://dsadata.intel.com/installer downloads 21.7.50.3
![image](https://user-images.githubusercontent.com/15158490/146656534-ada1de52-6e2a-4470-be6c-e7df8a8b0fb8.png)
![image](https://user-images.githubusercontent.com/15158490/146656538-1a42c782-113a-44bf-a43f-f2d444140069.png)

Current Package Identifier: Intel.IntelDriverAndSupportAssistant

**Comment by Trenly** [comment]
Looks like they dropped the `/a08`
