### ISSUE TITLE
[Package Request]: Maxthon.Maxthon.6

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38198]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: The Maxthon Authors
Publisher Url: https://www.maxthon.com/
Package Name: Maxthon
Description: 
Package Version: 6.1.2.3000
Installer URL x64: https://dl.maxthon.com/mx6/maxthon_6.1.2.3000_x64.exe
Installer URL x86: https://dl.maxthon.com/mx6/maxthon_6.1.2.3000_x86.exe

Package Identifier: Maxthon.Maxthon.6

Can't get past this screen
![image](https://user-images.githubusercontent.com/15158490/146656784-1871c855-99e8-4857-9c2a-e38dcaade2ea.png)

```
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /S
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /Silent
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe --silent
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /S /v/q
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /EXENOUI
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /quiet
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe /q
PS C:\Users\User\Downloads> .\maxthon_6.1.2.3000_x64.exe --quiet
```

**Comment by Trenly** [comment]
@OfficialEsco - `--slient --system-level`

**Comment by OfficialEsco** [comment]
Clever guy, thanks 😁
