### ISSUE TITLE
[New package version]: ShiningLight.OpenSSL

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38249]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Shining Light Productions
Package Name: OpenSSL
Package Version: 1.1.1m and 3.0.1
Installer URL: https://slproweb.com/products/Win32OpenSSL.html

Current Package Identifier (for new versions): ShiningLight.OpenSSL

okay so, this package is messy

> September 9, 2021 - OpenSSL 3.0 is available. Users should currently install a 1.1.1 series + a 3.0 series for maximum application compatibility. All application developers should begin migrating their applications to use OpenSSL 3.0 series.

However both report as OpenSSL and version 1.0.0... Is there a smart way we can do this?

**Comment by Trenly** [comment]
Using the Exe -
![image](https://user-images.githubusercontent.com/12611259/146723943-e7493550-a44a-486c-960f-a41c1abf9f0b.png)

**Comment by Trenly** [comment]
@OfficialEsco I spoke with one of the devs and v1.0.0 is the version of their MSI Packaging Script and not the version of the exe packaged inside the MSI and it doesn’t sound like they are willing to change it.

I think it would take someone from MSFT pushing on them to make the change, and even then I don’t know if they would. 

I would be of the opinion that we should possibly remove the program since the versioning information is completely incorrect, which is a different case entirely than the version information being missing. I would then suggest we wait until the 1.1.0 manifest is fully released and the client can handle Add/Remove Programs Entry metadata

![5D877145-A593-488B-830A-AE53E233110F](https://user-images.githubusercontent.com/12611259/147304970-d9d138b9-5db8-43de-8880-8243d769d7ea.png)

**Comment by OfficialEsco** [comment]
Weeeell, we could do what we do with AnyDesk, use the EXE as Primary Metadata and only the ProductCode for the MSI matching.
The MSI versions look exactly the same, so schema 1.1.0 can't help that one.
![VirtualBoxVM_uDTLBqwHRC](https://user-images.githubusercontent.com/15158490/147310673-cc06a8f0-bb0c-4464-bf38-2440418b1042.png)
Since the EXE does not report a version it will work just like before.
The next client should be out soon, so i don't think its worth removing the manifests, rather just prepare them

**Comment by dbaileyut** [comment]
The current upgrade loop is pretty annoying. (i.e. running `winget.exe upgrade --all` always updates it)

If the developers won't change the way they package this, what's the way forward for doing proper version detection? If it can't be done today, I'd say it is worth removing.

**Comment by OfficialEsco** [comment]
I believe winget cli will make a command to update software's without a version.
On our part there is MAYBE the ARP Entries field, however we do not know how effective that is yet.
On your side you can manually add the version for any software without a version.


This is way easier with RevoUninstaller, but i can give you the field for OpenSSL
1. open RegEdit and go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OpenSSL (64-bit)_is1`
2. Create a new `String` called `DisplayVersion`
3. Set the value to 1.0.0

**Comment by derjoshder** [comment]
Dear author of this software,
I really want to thank you for taking part in fighting the commercial part of the internet, with everybody sharing what they do for some gratitude. I hope it is OK for you, that I donated to Wikimedia foundation this year, and just drop you this message of thankfulness.
I'm trying to get cadquery running under windows, so I read the stackexchange recommendation hiere:
https://stackoverflow.com/questions/54773709/conda-error-ssl-certificate-httpsconnectionpoolhost-repo-anaconda-com-po
 to install your software to get rid of an error message with conda under win64. Hope it helps.

**Comment by treysis** [comment]
I agree. Not everything has to land via winget. If it's currently not compatible, it currently just can't be part of this system.

**Comment by treysis** [comment]
As you can see I just removed all manifests of ShiningLight.OpenSSL. Maybe it'll work one day, but until then good riddance.

**Comment by gunnarhaslinger** [comment]
I just checked the state of ShiningLight OpenSSL MSI Version Numbers
https://slproweb.com/products/Win32OpenSSL.html

It seems they have done their homework and fixed their MSI-Packages, at least the new releases. The old "Win64 OpenSSL v1.1.1w Light" ist still broken and show MSI Product Version 1.0.0 but all other newer Releases seem to be fine and have a correct MSI Product Version now.

I especially checked:

- [x] Win64 OpenSSL v3.2.1 Light
- [x] Win64 OpenSSL v3.1.5 Light
- [x] Win64 OpenSSL v3.0.13 Light

Here for example:
```
PS C:\> winget list openssl
Name                         ID                                     Version
---------------------------------------------------------------------------
OpenSSL Light 3.2.1 (64-bit) {7E1CA3A5-A7B9-4066-B194-8E2C160E67F6} 3.2.1
```

So I would highly appreciate if "ShiningLight/OpenSSL/Light" could be undeleted and updated to the current Win64 OpenSSL v3.2.1 Light.
