### ISSUE TITLE
[New package version]: TradingView.TradingViewDesktop version 1.0.0.2205

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38269]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: TradingView, Inc.
Publisher Url: https://www.tradingview.com/desktop/
Package Name: TradingView
Package Version: 1.0.0.2205
Installer URL: No idea

Current Package Identifier (for new versions): TradingView.TradingViewDesktop

I couldn't seem to find the MSIX so i attempted to use the appinstaller but that turned into this:
```
PS M:\> winget install -m .\t\TradingView\TradingViewDesktop\1.0.0.2205\
Found TradingView [TradingView.TradingViewDesktop] Version 1.0.0.2205
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://tvd-packages.tradingview.com/beta/latest/win32/TradingView.appinstaller
  ██████████████████████████████  4.00 KB / 4.00 KB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 0x8051100f : unknown error
```

@al-lac might know how this site works

**Comment by vedantmgoyal2009** [comment]
Few questions I have:
- Does WinGet support `-AppInstaller` parameter? 
- What is the InstallerType you are testing with?
- The URL problem is same as with MasterPackager?

![image](https://user-images.githubusercontent.com/83997633/146663462-2f45416c-8b6f-4e34-8b73-09dd3cee53bc.png)

**Comment by OfficialEsco** [comment]
I believe I've seen -AppInstaller used in a manifest before, tried Appx and MSIX and now exe with -AppInstaller, still no luck.
Do a quick 5 min test and you'll get the same outcome 🤷‍♂️

**Comment by Trenly** [comment]
@OfficialEsco - You can get the full directory listing at https://tvd-packages.tradingview.com/
According to the listing, the correct URL would be https://tvd-packages.tradingview.com/beta/1.0.0-beta.13/win32/x64/TradingView.msix

**Comment by vedantmgoyal2009** [comment]
Just to confirm, I am going the correct way.

![image](https://user-images.githubusercontent.com/83997633/146784678-ca86a73b-b379-4819-bcfe-a56ad47a516c.png)

**Comment by Trenly** [comment]
> Just to confirm, I am going the correct way.
> 
> ![image](https://user-images.githubusercontent.com/83997633/146784678-ca86a73b-b379-4819-bcfe-a56ad47a516c.png)

Looks right to me.
Only thing I think may need to be added is a check that it is a stable version, not beta

**Comment by vedantmgoyal2009** [comment]
https://github.com/Trenly/winget-pkgs/blob/master/manifests/t/TradingView/TradingViewDesktop/1.0.0.1906/TradingView.TradingViewDesktop.installer.yaml

This and the older manifests need to be deleted since it's a beta version.

**Comment by Chaython** [comment]
This package is severely out of date, I was so surprised when I installed tradingview in winget.... SO many winget projects are so out of date...
"winget install tradingview
Found TradingView [TradingView.TradingViewDesktop] Version 1.0.0.2205"
Current version is 2.7.4...
