### ISSUE TITLE
[Bug]: Latest "Huawei.AppGallery" installed but not detected & upgrade failed

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#38292]
### Brief description of your issue

My device (manufactured by Huawei itself, `Huawei Matebook X Pro`) is previously installed `Huawei.AppGallery` before Windows 10 is extracted before my first powerup. It's currently running the latest version of `AppGallery` but Winget doesn't detect it.

![image](https://user-images.githubusercontent.com/49941141/146669728-a691c2e0-e735-4f11-a62a-bbd90dda9c1e.png)

![image](https://user-images.githubusercontent.com/49941141/146669733-12719037-f6dd-4951-979a-024d57fb3398.png)

When I try to upgrade it, there's an "installation error" with exit code 2.

Is it a special bug only happens on Huawei's device?

### Steps to reproduce

1. You should prepare a device manufactured by **Huawei** (mostly `MateBook` series)
2. Upgrade to latest **Windows 10 Home China** to enable **Winget**
3. Invoke `winget upgrade "Huawei.AppGallery"`

### Expected behavior

1. **Winget** prompt up a UAC dialog
2. Choose **Yes** and wait a little while, **AppGallery** upgrade successful

### Actual behavior

After clicking **Yes** in the UAC dialog, an error has occured.

![image](https://user-images.githubusercontent.com/49941141/146670311-3073c73e-bdeb-426a-8ce9-4d446a6d1b33.png)

### Environment

```shell
~ λ winget --info
Windows Package Manager v1.1.13405
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.19042.1387
程序包: Microsoft.DesktopAppInstaller v1.16.13405.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
I sorta managed to replicate this
```
PS M:\> winget install Huawei.appgallery --version 2.1.2.301
Found AppGallery [Huawei.appgallery] Version 2.1.2.301
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://appdl-drcn.dbankcdn.com/dl/appdl/application/apk/d8/d88fef21d89e491b88c0ca8d5cfe9c29/PC45857bbbe1344af6b6f306457e5634b6.2109071020.exe?maple=0&trackId=0&distOpEntity=HWSW&cno=portal
  ██████████████████████████████   176 MB /  176 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget upgrade Huawei.appgallery
Found AppGallery [Huawei.appgallery] Version 2.1.2.304
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://appdl-1-drcn.dbankcdn.com/dl/appdl/application/apk/e1/e1de6209b0344315ae03e2d470445888/PC2411c6370f944df38275c0e01b5f91fd.2112071051.exe?maple=0&trackId=0&distOpEntity=HWSW&cno=H5
  ██████████████████████████████   221 MB /  221 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget install Huawei.appgallery
Found AppGallery [Huawei.appgallery] Version 2.1.2.304
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://appdl-1-drcn.dbankcdn.com/dl/appdl/application/apk/e1/e1de6209b0344315ae03e2d470445888/PC2411c6370f944df38275c0e01b5f91fd.2112071051.exe?maple=0&trackId=0&distOpEntity=HWSW&cno=H5
  ██████████████████████████████   221 MB /  221 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2
```
Exit code 2 means that version is already installed, however your version reports as Unknown, my version appears to be in English, so either the software is Dynamic depending on OS Language or they use a Chinese setup file that is not setup correctly.

**Comment by Dragon1573** [comment]
> `exit code: 2` means that version is already installed, however your version reports as `Unknown`

Oh, I see ...

Maybe the "OEM" version of AppGallery is pre-installed with the operating system in another way, totally different from that by Winget and could not be correctly detected.

I'll try to manage updates with AppGallery itself. Thank you for your insructions! ❤️
