### ISSUE TITLE
[New package version]: NordVPN.NordVPN version 6.41.11.0

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#38310]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: TEFINCOM S.A.
Package Url: https://nordvpn.com/download/
Package Name: NordVPN
Package Version: 6.41.11.0
Installer URL: https://downloads.nordcdn.com/apps/windows/NordVPN/latest/NordVPNSetup_x64.exe
Its supposed to be https://downloads.nordcdn.com/apps/windows/10/NordVPN/6.41.11/NordVPNSetup.exe
Not uploaded yet?

Current Package Identifier: NordVPN.NordVPN
![image](https://user-images.githubusercontent.com/15158490/146684813-e439220b-9fe4-4c79-8c46-93f9a2829d64.png)

We also need to add x86 and x64 Architecture, URLs for previous version
https://downloads.nordcdn.com/apps/windows/10/NordVPN/6.40.5/NordVPNSetup.exe
https://downloads.nordcdn.com/apps/windows/10/NordVPN/6.40.5/NordVPNSetup_x64.exe
![image](https://user-images.githubusercontent.com/15158490/146684828-fdc7896f-7db2-4f40-83a6-422548a5e16e.png)

**Comment by Trenly** [comment]
@OfficialEsco try -
https://downloads.nordcdn.com/apps/windows/NordVPN/6.41.11/NordVPNSetup_x64.exe
https://downloads.nordcdn.com/apps/windows/NordVPN/6.41.11/NordVPNSetup_x86.exe

**Comment by OfficialEsco** [comment]
what on earth, i tried something like that, but i without the x64/x86 in the filename so it returned 404... good find!
