### ISSUE TITLE
[Package Request]: ksnip.ksnip

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#38442]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: ksnip
Publisher Url: http://github.com/ksnip
Package Name: ksnip.ksnip
Description: Ksnip is a Qt-based cross-platform screenshot tool that provides many annotation features for your screenshots.
Package Version: 1.9.2
Installer URL: http://github.com/ksnip/ksnip/releases/download/v1.9.2/ksnip-1.9.2.msi

Current Package Identifier (for new versions): 1.9.2

**Comment by OfficialEsco** [comment]
What? This package already exist under ksnip.ksnip.

> [X] I have performed a search and couldn't find this package.
```

PS M:\> winget list
Name                                    Id                                       Version            Available    Source
-----------------------------------------------------------------------------------------------------------------------
ksnip                                   ksnip.ksnip                              1.9.2                           winget

PS M:\> winget search ksnip
Name  Id          Version Source
---------------------------------
ksnip ksnip.ksnip 1.9.2   winget
```
