### ISSUE TITLE
[Package Request]: WatchGuardTechnologies/WatchGuardSystemManager/12.7.2

### ISSUE THREAD

**Issue by Crazy-Clown** [microsoft/winget-pkgs#38498]
### Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: WatchGuard Technologies
Publisher Url: https://www.watchguard.com
Package Name: WatchGuardSystemManager
Description: WatchGuard System Management Software to Manage Firebox products from WatchGuard Technologies
Package Version: 12.7.2
Installer URL: https://cdn.watchguard.com/SoftwareCenter/Files/WSM/12_7_2/WSM12_7_2.exe

Current Package Identifier (for new versions):

**Comment by Crazy-Clown** [comment]
There's an issue with the existing listing on winget and it's frustrating to have to always cancel the installation during a winget upgrade --all because of the package being outdated/incomplete.  Can someone assist with publishing the new version?  I would like to know how to do this myself, but am not very technical when it comes to manifest or any GitHub publications.

Thanks.

**Comment by Trenly** [comment]
>  Can someone assist with publishing the new version?

I've submitted a PR for this

>  I would like to know how to do this myself, but am not very technical when it comes to manifest or any GitHub publications.

For a beginner, you can take a look over at the [Wingetcreate](/microsoft/winget-create#readme) application, but I'm not super experienced with it and I personally don't like the way it is structured. I use the [YamlCreate](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md) script. The documentation for YamlCreate walks through how to create a fork of this repository and how to clone it to your computer, as well as the additional tools like the github cli that will allow the script to automatically submit the PR's for you

**Comment by Crazy-Clown** [comment]
@Trenly I ended up using the wingetcreate app and it seemed to have worked, which is good.  I am not sure about all of the checks and things that happen in the back end though, is everything being processed correctly, or is there additional steps I must do to get this to publish?

**Comment by Trenly** [comment]
> @Trenly I ended up using the wingetcreate app and it seemed to have worked, which is good. I am not sure about all of the checks and things that happen in the back end though, is everything being processed correctly, or is there additional steps I must do to get this to publish?

It looks like its in processing
