### ISSUE TITLE
[Package Request]: Icedrive

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#38852]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Icedrive
Publisher Url: https://icedrive.net/plans
Package Name: Icedrive
Description: Cloud Storage for Windows
Package Version: 2.29
Installer URL: https://icedrive.net/downloads/win/Icedrive_Installer-2.29.9.exe

Current Package Identifier (for new versions): 2.29

**Comment by OfficialEsco** [comment]
Resolved in  #39191 
The merge crashed so the issue didn't get marked as Merged..

**Comment by arjun-msft** [comment]
Closing per @OfficialEsco.
