### ISSUE TITLE
[Package Request]: HostsMan

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#38871]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: abelhadigital
Publisher Url: https://www.abelhadigital.com/hostsman/
Package Name: HostsMan
Description: HostsMan is a freeware application that let's you manage your hosts file with ease.
Package Version: 4.7.105
Installer URL: https://drive.google.com/uc?export=download&id=0B0N7Pu7pijFBejcxNXlLZVVMSnM

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment]
> Installer URL: https://drive.google.com/uc?export=download&id=0B0N7Pu7pijFBejcxNXlLZVVMSnM

This url does not work, also the installer is Zipped

**Comment by Trenly** [comment]
Close with reason: Provided URL does not work; No additional information provided since Esco's post in 2021 - No-Recent-Activity
