### ISSUE TITLE
[Package Request]: KDE.Connect.Release

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#38931]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Connect.Release
Description: http://apps.kde.org/kdeconnect
Package Version: master-821
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-21.12.0-821-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-821

**Comment by jedieaston** [comment]
This already exists as KDE.KDEConnect.
