### ISSUE TITLE
[Package Request]: DoubleCommander

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#39258]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: http://github.com/doublecmd
Package Name: DoubleCommander
Description: 
Package Version: 1.0.2
Installer URL: http://github.com/doublecmd/doublecmd/releases/download/v1.0.2/doublecmd-1.0.2.x86_64-win64.msi

Current Package Identifier (for new versions): 1.0.2

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Within "https://github.com/doublecmd/doublecmd/releases", many different versions are present, so appendation of the type of file/installer and/or architecture may be necessary.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/alexx2000/DoubleCommander

```
❯ winget search doublecommander
Name             Id                        Version
--------------------------------------------------
Double Commander alexx2000.DoubleCommander 1.0.2

❯ winget search "Double Commander"
Name             Id                        Version
--------------------------------------------------
Double Commander alexx2000.DoubleCommander 1.0.2
```
Where and what are you searching?..

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/microsoft/winget-pkgs/issues/39258#issuecomment-1002656196".

I was searching within "http://github.com/microsoft/winget-pkgs/tree/master/manifests/d" rather than for the name of the publisher.
