### ISSUE TITLE
[Package Request]: SigmaFileManager

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-pkgs#39275]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Aleksey Hoffman
Publisher Url: http://github.com/aleksey-hoffman
Package Name: SigmaFileManager
Description: 
Package Version: 1.4.0
Installer URL: http://github.com/aleksey-hoffman/sigma-file-manager/releases/download/v1.4.0/Sigma-File-Manager-1.4.0-Windows-Setup.exe

Current Package Identifier (for new versions): 1.4.0

**Comment by ItzLevvie** [comment]
```shell
winget install AlekseyHoffman.Sigma-File-Manager
will allow you to install Sigma file manager version 1.4.0

**Comment by Trenly** [comment]
![image](https://user-images.githubusercontent.com/12611259/147686420-0bbcd8c6-0504-405c-bf6b-54cd3ed5150e.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/microsoft/winget-pkgs/issues/39275#issuecomment-1002691544".

Please have observed "http://github.com/microsoft/winget-pkgs/issues/39258#issuecomment-1002692187".
