### ISSUE TITLE
[New package version]: SonicWALL.GlobalVPN version 4.10.6

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#39540]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: SonicWALL
Publisher Url: https://www.sonicwall.com/products/remote-access/vpn-clients/
Package Name: GlobalVPN 
Package Version: 4.10.6
Installer URL: ?

These are the urls i can find
* https://software.sonicwall.com/GlobalVPNClient/184-010739-00_REV_A_GVCSetup64.exe
* https://software.sonicwall.com/GlobalVPNClient/184-010738-00_REV_A_GVCSetup32.exe

Current Package Identifier (for new versions): SonicWALL.GlobalVPN

I can't seem to find the correct URL..
@felipejunio05 would you mind helping? =)

**Comment by Trenly** [comment]
@OfficialEsco Lets use the vanity URL so wingetbot can auto-upgrade since it doesn't seem like old versions are retained
https://software.sonicwall.com/GlobalVPNClient/GVCSetup64.exe
https://software.sonicwall.com/GlobalVPNClient/GVCSetup32.exe

**Comment by OfficialEsco** [comment]
https://software.sonicwall.com/GlobalVPNClient/GVCSetup64.exe installs 4.10.4 on my VM >.>

**Comment by Trenly** [comment]
> https://software.sonicwall.com/GlobalVPNClient/GVCSetup64.exe installs 4.10.4 on my VM >.> Also i think they retain old versions?

Hmm. I'll keep looking

**Comment by OfficialEsco** [comment]
The urls do look like
https://software.sonicwall.com/GlobalVPNClient/GVCSetup64_4.9.0.1202_EN.exe
https://software.sonicwall.com/GlobalVPNClient/GVCSetup32_4.9.0.1202_EN.exe
tho, its just the last digit that is unknown..

We could probably use the vanity url since none is actively maintaining the Manifest, 4.10.4 + auto update is better than 4.9.0

**Comment by Trenly** [comment]
> The urls do look like https://software.sonicwall.com/GlobalVPNClient/GVCSetup64_4.9.0.1202_EN.exe https://software.sonicwall.com/GlobalVPNClient/GVCSetup32_4.9.0.1202_EN.exe tho, its just the last digit that is unknown..
> 
> We could probably use the vanity url since none is actively maintaining the Manifest, 4.10.4 + auto update is better than 4.9.0

I tested all the numbers from 1202 through 6750 for `4.10.6.<version>` and none of them work. I'm thinking maybe it was removed?
