### ISSUE TITLE
Azure Pipelines isn't running the tests for pending PRs

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#3971]
There are four pull requests currently in the queue: #3967, #3968, #3969 and #3970 for which Azure Pipelines says there are no tests to run, which mean they won't be marked ready to be merged. I didn't know where else to put this, so I opened an issue.

**Comment by msftrubengu** [comment]
Az pipelines are now up and running. Thanks!

**Comment by jedieaston** [comment]
Looks like it is happening again, see #3995, #3994, #3993, and #3992. It doesn't look like I have permissions to reopen the issue, but @msftrubengu can you look at it again?

**Comment by denelon** [comment]
Thank you for pointing these issues out! We're working on the "back-end" to get better / more sophisticated alerting in place.
