### ISSUE TITLE
[New Feature]: Update PackageName of Mozilla.Firefox.Nightly

### ISSUE THREAD

**Issue by RyanHir** [microsoft/winget-pkgs#39790]
### Description of the new feature/enhancement

Replace current name `Nightly` with a more descriptive name such as `Mozilla Firefox (Nightly)` (like the Beta beta) or `Mozilla Firefox Nightly` (like the ESR package).

Input for which name to use would be appreciated.

**Comment by OfficialEsco** [comment]
That is Mozilla's fault
![VirtualBoxVM_0XYv58MmRx](https://user-images.githubusercontent.com/15158490/148036298-6e0d8dac-c0ef-4db7-ae92-fc3b829ceac3.png)
Using ProductCode's would also be difficult as its `Nightly 96.0a1 (x64 en-US)`

**Comment by RyanHir** [comment]
Its safe to assume there is not any name aliasing functionality?

**Comment by OfficialEsco** [comment]
No, we can probably work around this by using AppsAndFeaturesEntries when™️ that gets supported with all the function

**Comment by ItzLevvie** [comment]
Close with reason: This was fixed;
