### ISSUE TITLE
[Bug]: Google.EarthPro Installed package type is not compatible with exe

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#40143]
### Brief description of your issue

Trying to update Google.EarthPro but it reports as wrong InstallerType.
WinGetCreate cannot detect the InstallerType

InstallerTypes:
Exe: Installed package type is not compatible with exe [WinGet-Google.EarthPro.7.3.4.8248-2022-01-07-12-55-02.800.log](https://github.com/microsoft/winget-pkgs/files/7828624/WinGet-Google.EarthPro.7.3.4.8248-2022-01-07-12-55-02.800.log)
Burn: Installed package type is not compatible with burn
Wix: `Installer failed with exit code: 1620`
MSI: `Installer failed with exit code: 1620`
Inno: Installed package type is not compatible with inno
Nullsoft: Installed package type is not compatible with nullsoft

### Steps to reproduce

```
❯ winget install Google.EarthPro --version 7.3.3.7786
Found Google Earth Pro [Google.EarthPro] Version 7.3.3.7786
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/dl/earth/client/advanced/current/googleearthprowin-7.3.3-x64.exe
  ██████████████████████████████  65.4 MB / 65.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

❯ winget upgrade Google.EarthPro
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
```

### Expected behavior

To update Google Earth

### Actual behavior

See Steps to reproduce

### Environment

```shell
❯ winget --info
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

and 

winget --info
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by Trenly** [comment]
I think it may be a case of an MSI installer packaged inside an EXE.

If you convert this to schema `1.1.0` then you can possibly use @jedieaston's solution from https://github.com/microsoft/winget-cli/pull/1796#issuecomment-993548211

**Comment by OfficialEsco** [comment]
One step ahead of you, however me and his script do not like eachother https://github.com/microsoft/winget-pkgs/discussions/38882#discussioncomment-1924220

**Comment by Trenly** [comment]
> Edit: however i do not know why i didn’t add it manually
Me on most days of the week

**Comment by OfficialEsco** [comment]
Oh i was one step ahead of myself too, i was going to use jedieaston's script to find the InstallerType, but i didn't add the AppsAndFeaturesEntries because they don't do anything in winget v1.2.3411-preview

**Comment by jedieaston** [comment]
I can't detect inner InstallerType with that script (yet), you'll have to add that manually :(
