### ISSUE TITLE
[Bug]: WinFsp.WinFsp: Installer failed with exit code: 1603

### ISSUE THREAD

**Issue by kevinoid** [microsoft/winget-pkgs#40169]
### Brief description of your issue

If I install WinFsp.WinFsp 1.9.21096 then upgrade to 1.10.22006, the "Installer failed with exit code: 1603"

### Steps to reproduce

    C:\Users\Username> winget install --exact --id WinFsp.WinFsp --version 1.9.21096
    Found WinFsp [WinFsp.WinFsp] Version 1.9.21096
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    Downloading https://github.com/billziss-gh/winfsp/releases/download/v1.9/winfsp-1.9.21096.msi
      ██████████████████████████████  2.22 MB / 2.22 MB
    Successfully verified installer hash
    Starting package install...
    Successfully installed

    C:\Users\Username> winget upgrade --exact --id WinFsp.WinFsp --version 1.10.22006
    Found WinFsp [WinFsp.WinFsp] Version 1.10.22006
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    Downloading https://github.com/billziss-gh/winfsp/releases/download/v1.10/winfsp-1.10.22006.msi
      ██████████████████████████████  2.04 MB / 2.04 MB
    Successfully verified installer hash
    Starting package install...
    Installer failed with exit code: 1603
    Installer log is available at: C:\Users\Username\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-WinFsp.WinFsp.1.10.22006-2022-01-07-09-20-55.131.log

[WinGet-WinFsp.WinFsp.1.10.22006-2022-01-07-09-20-55.131.log](https://github.com/microsoft/winget-pkgs/files/7830116/WinGet-WinFsp.WinFsp.1.10.22006-2022-01-07-09-20-55.131.log)

The Application Event Log shows EventID 10005 from MsiInstaller with data

> Product: WinFsp 2022 -- An older version of WinFsp is already installed. You must uninstall it before you can install this version.

### Expected behavior

Upgrade would succeed.

### Actual behavior

> Installer failed with exit code: 1603

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1415
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by kevinoid** [comment]
I assumed this would be fixable by adding `UpgradeBehavior: uninstallPrevious` to WinFsp.WinFsp.installer.yaml, as I did in https://github.com/kevinoid/winget-pkgs/commit/winfsp-upgrade-1603  Unfortunately, this did not fix the issue.  Installing with `winget install --manifest .\manifests\w\WinFsp\WinFsp\1.10.22006\` generated the same error.  Since the log does not indicate that uninstallation was attempted, I assume I've done something incorrectly.  Any suggestions would be appreciated.

[WinGet-2022-01-07-09-35-04.006.log](https://github.com/microsoft/winget-pkgs/files/7830187/WinGet-2022-01-07-09-35-04.006.log)

**Comment by Trenly** [comment]
> I assumed this would be fixable by adding `UpgradeBehavior: uninstallPrevious` to WinFsp.WinFsp.installer.yaml, as I did in [kevinoid@winfsp-](https://github.com/kevinoid/winget-pkgs/commit/winfsp-upgrade-1603) Unfortunately, this did not fix the issue. Installing with `winget install --manifest .\manifests\w\WinFsp\WinFsp\1.10.22006\` generated the same error. Since the log does not indicate that uninstallation was attempted, I assume I've done something incorrectly. Any suggestions would be appreciated.
> 
> [WinGet-2022-01-07-09-35-04.006.log](https://github.com/microsoft/winget-pkgs/files/7830187/WinGet-2022-01-07-09-35-04.006.log)

If I’m not mistaken, upgrade behavior only applies when `winget upgrade` is used. Setting it to uninstallPrevious should fix the issue, but you probably won’t be able to test an upgrade scenario using an install test

**Comment by kevinoid** [comment]
> If I’m not mistaken, upgrade behavior only applies when winget upgrade is used.

Right you are.  Thanks!  `winget upgrade --manifest` worked, although the WinFsp installer requires interaction due to files in use:

![WinFsp upgrade screenshot](https://user-images.githubusercontent.com/336433/148579697-df0e113c-d269-4b2f-9743-d4c161647458.png)

(Note that I'm not actually using it and have not done any configuration on the test system.)

Do you know how this is typically handled by winget packages?

**Comment by Trenly** [comment]
> Do you know how this is typically handled by winget packages?

I don't believe it is handled at all with the current version of the client; There is an option to add an installer switch for `Upgrade` if the publisher has provided a switch to proceed without closing the applications.
