### ISSUE TITLE
[Package Request]: Hourglass

### ISSUE THREAD

**Issue by JerryWinkler** [microsoft/winget-pkgs#40226]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Chris Dziemborowicz
Publisher Url: https://chris.dziemborowicz.com/apps/hourglass/
Package Name: Hourglass
Description: The simple countdown timer for Windows.
Package Version: v1.15.0
Installer URL: https://github.com/dziemborowicz/hourglass/releases/download/v1.15.0/HourglassInstaller.exe

**Comment by petervk** [comment]
I'm hoping we can add i2van's version of this application instead as it is actively maintained and has additional features.

Pull Request: https://github.com/microsoft/winget-pkgs/pull/224518

Issue: https://github.com/microsoft/winget-pkgs/issues/224523
