### ISSUE TITLE
Consider opting-in for Hacktoberfest

### ISSUE THREAD

**Issue by JanPokorny** [microsoft/winget-pkgs#4026]
This year, the event [Hacktoberfest](https://hacktoberfest.digitalocean.com/) by DigitalOcean changed rules to include only participating repositories. A repository participates by [including the `hacktoberfest` topic](https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean). Participants that manage to create 4 accepted PRs to participating projects will receive a T-shirt and a goodie bag.

In my opinion, a manifest repository is a good fit for Hacktoberfest, since it is relatively easy to make a small, self-contained, meaningful contribution. Enrolling may benefit WinGet by spreading awareness and attracting new contributors.

Downsides may include receiving some low-quality contributions. Thankfully this year's rules have been updated to count only accepted PRs, thus lowering the incentive for creating dumb PRs "just for the T-shirt".

**Comment by denelon** [comment]
Thanks for the suggestion! #hacktoberfest topic added 👍
