### ISSUE TITLE
OpenSSL link is broken. 

### ISSUE THREAD

**Issue by legionaryu** [microsoft/winget-pkgs#4048]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
I was trying to install OpenSSL, but winget fails to download it. The reason is that the link that winget uses is broken (https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.msi) the right one is this https://slproweb.com/download/Win64OpenSSL_Light-1_1_1h.msi

# Steps to reproduce
winget install openssl

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2521 Visualização
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.19041.508
Pacote: Microsoft.DesktopAppInstaller v1.11.2521.0

Links
------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
```

**Comment by jedieaston** [comment]
I've fixed it in #4049, so once that gets merged you should be good to go.
