### ISSUE TITLE
[Bug]: winget cannot find pokemon showdown version and always thinks there is an available upgrade

### ISSUE THREAD

**Issue by ix0rai** [microsoft/winget-pkgs#40529]
### Brief description of your issue

When installing pokemon showdown through winget, winget always acts as if there is an applicable update to `0.3.0` for it and claims that the current installed version is `Unknown`
![image](https://user-images.githubusercontent.com/66223394/149023297-3d5527ff-e049-4ecc-af5a-ddc7ed9b38a2.png)

Performing the upgrade does not fix the issue, the version is still `Unknown`

### Steps to reproduce

1. install winget
2. install Smogon.PokemonShowdown
3. run winget upgrade
4. see that the version is `unknown` and there's an available upgrade

### Expected behavior

the latest version of showdown should have been installed and recognised by winget

### Actual behavior

winget does not recognise that showdown is already on the latest version

### Environment

```shell
Windows Package Manager v1.1.13405
Windows: Windows.Desktop v10.0.19044.1415
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by lychichem** [comment]
It is because pokemon showdown doesn't write displayversion registery key, so winget cannot read it from ARP list. You should ask the developer of pokemon showdown to make their installer  write this key.

**Comment by jedieaston** [comment]
This issue was fixed (or at least mitigated) in https://github.com/microsoft/winget-cli/pull/1765, and that should be in the *next* preview release.

**Comment by Trenly** [comment]
Just for reference, here is their nsi script -
They probably want a dynamic version, but it doesn't seem like they push out new builds to the website that often so ¯\_(ツ)_/¯
https://github.com/smogon/pokemon-showdown-client/blob/master/desktop/pokemonshowdown.nsi

**Comment by ix0rai** [comment]
going to close this as it seems to be entirely on showdown's side
