### ISSUE TITLE
[New package version]: Microsoft.ServiceFabricRuntime version 8.2.1363.9590

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#40705]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Current Package Identifier: [Microsoft.ServiceFabricRuntime](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/ServiceFabricRuntime)
Publisher: Microsoft Corporation
Package Name: Microsoft Azure Service Fabric
Package Version: 8.2.1363.9590
Package Url: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started
Not the correct download URL: https://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK

Since the package is missing Metadata i'm not sure where to get find the download url
![firefox_ciVWbWHmhC](https://user-images.githubusercontent.com/15158490/149359706-cf2c656b-869e-4ca1-970d-de3f1c710f99.png)
Looking for something like https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.8.0.521.9590.exe

**Comment by ItzLevvie** [comment]
https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.8.2.1363.9590.exe

Changelogs as well as Download URLs are available at https://github.com/microsoft/service-fabric/tree/master/release_notes

**Comment by OfficialEsco** [comment]
Ahaaa, i think i found the github page, but didn't look at the release notes..
Ty, however the installer is failing with exit code 1 for me
