### ISSUE TITLE
[404 Package url]: GNURadio.GNURadio

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#40715]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Current Package Identifier: [GNURadio.GNURadio](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GNURadio/GNURadio)

Not sure if the url went 404 recently, but as of now it is

https://github.com/gnuradio/gnuradio
https://wiki.gnuradio.org/index.php/InstallingGR#Windows

**Comment by vedantmgoyal2009** [comment]
The link works for me:

![image](https://user-images.githubusercontent.com/83997633/149382403-5f782741-2f76-48c7-a301-be3d152e66ee.png)

**Comment by vedantmgoyal2009** [comment]
![image](https://user-images.githubusercontent.com/83997633/149382726-8c87e1e3-ed87-44a8-aa85-04b6f26610a1.png)

**Comment by OfficialEsco** [comment]
Just found the issue... Firefox insisted on doing HTTPS which the webpage does not support...
