### ISSUE TITLE
Atualizaçao do aplicativo Name: Insomnia | Version: 2020.4.1

### ISSUE THREAD

**Issue by alvaroico** [microsoft/winget-pkgs#4087]
Id: Insomnia.Insomnia
Version: 2020.4.1
Name: Insomnia
Publisher: Insomnia
Homepage: https://insomnia.rest
License: MIT
LicenseUrl: https://github.com/Kong/insomnia/blob/develop/LICENSE
AppMoniker: Insomnia
Tags: insomnia, insomnia core
Description: The Desktop API client for REST and GraphQL. Make requests, inspect responses.
Installers:
  - Arch: x64
    Url: https://github.com/Kong/insomnia/releases/download/core%402020.4.1/Insomnia.Core-2020.4.1.exe
    InstallerType: exe
    Sha256: 2B36F3756C7C08AC62DBE1834431C57607DCEFCB9652BBB85410CA924131DE0A

**Comment by jedieaston** [comment]
I made a PR for this, #4123.

**Comment by alvaroico** [comment]
> I made a PR for this, #4123. 

#4091

Hello mine has been done for some time.  Is there any additional adjustment?

**Comment by alvaroico** [comment]
Effected Merged
