### ISSUE TITLE
[New Feature]: It is possible to use Winget install the applications to WSA?

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [microsoft/winget-pkgs#40961]
### Description of the new feature/enhancement

As the best Package manager over the world
So, we need could control more
Winget-->MS store
Winget-->win32
Winget-->WSL system
Winget-->Edge PWA(save URL as desktop app）
Winget-->android app

### Proposed technical implementation details (optional)

Maybe use adb to sync the android app.

**Comment by jedieaston** [comment]
I agree this would be a nice feature. We already have an issue for it in the winget-cli repo, maybe add thoughts over there?

Duplicate of https://github.com/microsoft/winget-cli/issues/1625

**Comment by vedantmgoyal2009** [comment]
I guess you cannot close cross-repo issues.
