### ISSUE TITLE
[Package Request]: mpv.net

### ISSUE THREAD

**Issue by 1hiking** [microsoft/winget-pkgs#41007]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: mpv.net
Publisher Url: https://github.com/stax76/mpv.net/
Package Name: 
Description: mpv.net is a modern media player for Windows based on the popular mpv player.
Package Version: 5.4.9.0
Installer URL: https://github.com/stax76/mpv.net/releases

Current Package Identifier (for new versions):

**Comment by ItzLevvie** [comment]
cc @1hiking:

Response from the developer (@stax76): https://github.com/microsoft/winget-pkgs/pull/36550#issue-1067899064

**Comment by 1hiking** [comment]
Oh Interesting, I made this issue in the knowledge of https://github.com/microsoft/winget-cli/issues/1585. I will close this and wait for that issue to have a fix then.
