### ISSUE TITLE
[Bug]: winget upgrade does not find new pgAdmin version

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#41130]
### Brief description of your issue

`winget upgrade` does not report and install a new pgAdmin version. 

### Steps to reproduce

Run sandbox test on pgAdmin 6.3 (the second but last version):

```
.\Tools\SandboxTest.ps1 .\manifests\p\PostgreSQL\pgAdmin\6.3\
```

Within the sandbox, run `winget upgrade` or `winget upgrade pgAdmin`. 

### Expected behavior

winget upgrade finds and installs the newest (manifest) version.

### Actual behavior

winget upgrade does not find the newest version, i.e. v6.4 currently. 

```pwsh
--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 6.3

Found pgAdmin [PostgreSQL.pgAdmin] Version 6.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v6.3/windows/pgadmin4-6.3-x64.exe
  ██████████████████████████████   150 MB /  150 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                                                    DisplayVersion Publisher                    ProductCode
-----------                                                    -------------- ---------                    -----------
Microsoft Visual C++ 2017 X64 Additional Runtime - 14.16.27033 14.16.27033    Microsoft Corporation        {27744187-E45F-41F3-8BC2-0DC5F9238FDB}
Microsoft Visual C++ 2017 X64 Minimum Runtime - 14.16.27033    14.16.27033    Microsoft Corporation        {65835E57-3712-4382-990A-8D39008A8E0B}
Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27033  14.16.27033.0  Microsoft Corporation        {cc3a7c63-31fb-4129-9024-63ebefd86a95}
pgAdmin 4 version 6.3                                          6.3            The pgAdmin Development Team pgAdmin 4v6_is1



PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
[Agree to ToS]
Name           Id             Version     Available    Source
-------------------------------------------------------------
Microsoft Edge Microsoft.Edge 92.0.902.67 97.0.1072.62 winget
1 upgrades available.
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget list pgAdmin
Name                  Id              Version
---------------------------------------------
pgAdmin 4 version 6.3 pgAdmin 4v6_is1 6.3
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget search pgAdmin
Name    Id                 Version Source
------------------------------------------
pgAdmin PostgreSQL.pgAdmin 6.4     winget
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade pgAdmin
No installed package found matching input criteria.
```

### Environment

```shell
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1466
Package: Microsoft.DesktopAppInstaller v1.16.12653.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
Posting here, since there might be something wrong with the manifest? Please move to [winget-cli](https://github.com/microsoft/winget-cli/) if appropriate.

I updated the manifest for the latest versions 6.4 (https://github.com/microsoft/winget-pkgs/pull/40719) and 6.3 (https://github.com/microsoft/winget-pkgs/pull/38461) with `wingetcreate update <PackageIdentifier> --version <version> --interactive`.

**Comment by dpprdan** [comment]
I just checked the above for all available manifests (versions 4.30, 5.7, 6.0 - 6.3) and `winget upgrade pgAdmin` does not find newer versions for any of them.

**Comment by ItzLevvie** [comment]
cc @dpprdan: It should be back up and running now:
![image](https://user-images.githubusercontent.com/11600822/149764589-28ad5088-c921-4cec-b4aa-b8217ae82f3c.png)

**Comment by dpprdan** [comment]
@ItzLevvie Looking good on my end, thanks! 
Should we make the change for the other manifests, too?

**Comment by dpprdan** [comment]
I have a similar problem with RStudio (#41629).

```pwsh
PS C:\Users\Daniel> winget search RStudio
Name                                 ID                           Version       Quelle
---------------------------------------------------------------------------------------
RStudio Desktop Professional Edition RStudio.RStudio.Professional 1.4.1717-3    winget
RStudio Desktop Open Source Edition  RStudio.RStudio.OpenSource   2021.09.2+382 winget
PS C:\Users\Daniel> winget list Rstudio
Name    ID      Version
-----------------------------
RStudio RStudio 2021.09.0+351
```
Do I understand correctly that the`Name`s have to match for winget to find the update, @ItzLevvie? I.e. I need to change `PackageName:` here to `RStudio`? 
https://github.com/microsoft/winget-pkgs/blob/cb61d362a6ca7eb1cbbb2fd89d5529bd76e59ecd/manifests/r/RStudio/RStudio/OpenSource/2021.09.2%2B382/RStudio.RStudio.OpenSource.locale.en-US.yaml#L11

**Comment by ItzLevvie** [comment]
> Should we make the change for the other manifests, too?

It should be fine.

> I.e. I need to change PackageName: here to RStudio?

That PackageName was done by purpose since both packages, OS and Pro, have the same name in Control Panel so it becomes a unambiguous package if you ran `winget upgrade` which is why there's `Desktop Open Source Edition` and `Desktop Pro Edition`.

It does break `winget list`'s mapping but adding ProductCode there will fix it. You can take a look at https://github.com/microsoft/winget-pkgs/pull/41884.

I was waiting for future winget-cli versions to see how the new 1.1.0 schema fields will work for ARP entries.

**Comment by ItzLevvie** [comment]
RStudio should now be fixed in the latest commits:
![image](https://user-images.githubusercontent.com/11600822/151159325-de67ca5a-868c-4350-9d35-f973211de136.png)

**Comment by dpprdan** [comment]
Yes, it is, @ItzLevvie, thank you! 🎉
