### ISSUE TITLE
[New Feature]: Moving VC++ Redist manifests

### ISSUE THREAD

**Issue by SpecterShell** [microsoft/winget-pkgs#41216]
### Description of the new feature/enhancement

Is it necessary to move `Microsoft.VC++YYYYRedist-arch` to `Microsoft.VC++Redist/YYYY/Arch` before they become widely used as dependencies? (Although there have been 200+ manifest using this at this point)

**Comment by OfficialEsco** [comment]
I think this is a good plan, i can't recall if we will be able to have dependency architectures in the same manifest later, but if we can we would have to restructure anyways

**Comment by jedieaston** [comment]
We (hopefully) will, I made an issue for it: https://github.com/microsoft/winget-cli/issues/1665

No comments from the team on it yet, but it will probably not be present until a hypothetical schema 1.2 (and who knows when that will happen), so I think it's safe to move stuff how we want for now.

**Comment by OfficialEsco** [comment]
How much work would it take to bind the `--architecture` switch to the Dependency pipeline?
Since Schema version 1.1.0 isn't widely used yet i don't see why we can't add the Architecture field

**Comment by jedieaston** [comment]
>How much work would it take to bind the `--architecture` switch to the Dependency pipeline?

I haven't looked into it much but I don't think it would be that hard. I'm not sure how extensible those code paths are, next time I have the codebase open I'll take a peek.

>  Since Schema version 1.1.0 isn't widely used yet i don't see why we can't add the Architecture field

I figured the schemas were pretty much frozen unless there was a bug, but I don't know. @denelon, thoughts?

**Comment by vedantmgoyal2009** [comment]
I am moving the package identifiers. Will replace dependencies once PRs gets merged.

**Comment by OfficialEsco** [comment]
IMO as of right now there is no reason to accept the new package identifier as the cons are much much much greater than the one "cleaner" pro reason
cc @ItzLevvie

**Comment by jedieaston** [comment]
Can we hold on moving stuff until we’re sure we can’t make more changes to 1.1? There’s no point in moving them now unless we won’t have the schema change for a while (like months).

**Comment by SpecterShell** [comment]
Another question is:
`Microsoft.VC++2015-2019Redist-x64`
`Microsoft.VC++2015-2022Redist-x64`
Which one should be used as dependency?

**Comment by OfficialEsco** [comment]
> Another question is: `Microsoft.VC++2015-2019Redist-x64` `Microsoft.VC++2015-2022Redist-x64` Which one should be used as dependency?

AFAIK 2019 and 2022 is the same, or atleast 2022 uninstalls 2019 before installing, would it break and confuse people if it was Microsoft.VC++2015+Redist?

I think the install would break if a dependency called for 2015-2019 when 2015-2022 is installed

**Comment by Trenly** [comment]
Manifests have been separated into Microsoft.VCRedist.<Year>.<Arch>

Close with reason: Completed;
