### ISSUE TITLE
URLs don't pass validation if they contain an HTML id

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#4186]
#4179 and #4075 (before I removed the html id(s) from the URLs) are both examples of this happening. Since the pages exist and are accessible, they should pass validation, but the pipeline fails claiming a bad request.

I don't think these should be failing, given that a id in the URL usually helps to go to the part of the page that has the relevant material, for example, Plex's license. Without the id, the user would go to the URL and not see the license, therefore wondering why the wrong link was present.

Pipeline log: https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_apis/build/builds/115244/logs/16

**Comment by denelon** [comment]
I believe this has been resolved. Feel free to reopen if not.
