### ISSUE TITLE
[Package Request]: Hashicorp Terraform

### ISSUE THREAD

**Issue by LordMike** [microsoft/winget-pkgs#41934]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Hashicorp
Publisher Url: https://www.terraform.io/
Package Name: Hashicorp.Terraform
Description: Terraform is an open-source infrastructure as code software tool that provides a consistent CLI workflow to manage hundreds of cloud services. Terraform codifies cloud APIs into declarative configuration files.
Package Version: 1.1.4
Installer URL: https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_windows_amd64.zip

Current Package Identifier (for new versions): 

## Note:
There is currently no MSI installer, only a zip with a single-exe.

**Comment by andrew-flatters-bliss** [comment]
@denelon Is this still blocked as the .zip branches following the chains seem to be resolved and merged?

**Comment by Trenly** [comment]
> @denelon Is this still blocked as the .zip branches following the chains seem to be resolved and merged?

* https://github.com/microsoft/winget-pkgs/issues/87300
