### ISSUE TITLE
Repository update pipeline is stuck?

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#4226]
I went to install some software that had recently been updated in the repository, and the manifests weren't updated in` winget show`, even after a ` winget source update `. It turns out that the pipeline has been stuck trying to sign the updated repository package for 16-ish hours. 

Here's the run: https://github.com/microsoft/winget-pkgs/runs/1261687532

**Comment by denelon** [comment]
@jedieaston, thanks for letting us know. We're testing a fix now.

**Comment by denelon** [comment]
@jedieaston, we cancelled that build. The next one in the queue completed successfully. Your package should be updated shortly. We're looking to have the fix for this out with our first release next week.

**Comment by jedieaston** [comment]
Awesome, thanks!

**Comment by denelon** [comment]
We're discussing the push to production today. There are several bug fixes included.

**Comment by denelon** [comment]
The changes have been put into production. I'm going to go ahead and close this issue. Feel free to re-open or create a new issue if  this fails again. We've put some automatic monitoring in place. There is also a work item to put a badge on the readme to help check the status of the pipelines #519.
