### ISSUE TITLE
YamlCreate.ps1: Trim white-space after reading user inputs

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/winget-pkgs#427]
# Description of the new feature/enhancement

We should remove all leading and trailing white-space after reading the user inputs.

Otherwise there may be leading / trailing white-space in 1) manifest content or 2) the file name of the manifest.

# Proposed technical implementation details (optional)

In [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1), append `| foreach-object trim` to every `read-host` cmdlet lines.

**Comment by maxmichels** [comment]
why do you think this is needed? i guess a simple $varibale.trim() should do the work. have you tried it?

**Comment by KiruyaMomochi** [comment]
> why do you think this is needed? i guess a simple $varibale.trim() should do the work. have you tried it?

For example, if I typed `1.0.0 ` when the script asking for `Version`, the result file name will be `1.0.0 .yaml`. Also, there will be trailing space in the file content. It's really annoying.

I think `$varibale.trim()` is also fine. I'm new to PowerShell. What I want to say is that we should *trim* user's input.

**Comment by maxmichels** [comment]
I will create PR later today 👍🏼

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/609

**Comment by maxmichels** [comment]
This one is not fixed with #609. I will create another PR. I forgot about it..
