### ISSUE TITLE
[Package Request]: Nvidia SDK's

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#43367]
### Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [x] I think there is a new version available and I have provided the URL.

### Please provide the following information

Just putting this here so that I don't forget that the rest of these should (probably) be added -
https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-sdk/resources/

* #43340
* [Nvidia.VideoEffectsSDK.30xx-Ampere v0.6.5](https://international.download.nvidia.com/Windows/broadcast/sdk/v0.6.5/nvidia_video_effects_sdk_installer_ampere.exe)
* [Nvidia.AudioEffectsSDK.20xx-Turing v1.0.5](https://international.download.nvidia.com/Windows/broadcast/sdk/1.0.5/nvidia_audio_effects_sdk_v1.0.5_turing.exe)
* [Nvidia.AudioEffectsSDK.30xx-Ampere v1.0.5](https://international.download.nvidia.com/Windows/broadcast/sdk/v1.0.5/nvidia_audio_effects_sdk_v1.0.5_ampere.exe)
* [Nvidia.ARSDK.20xx-Turing v0.7.6](https://international.download.nvidia.com/Windows/broadcast/sdk/v0.7.6/nvidia_ar_sdk_installer_turing.exe)
* [Nvidia.ARSDK.30xx-Ampere v0.7.6](https://international.download.nvidia.com/Windows/broadcast/sdk/0.7.6/nvidia_ar_sdk_installer_ampere.exe)

**Comment by jedieaston** [comment]
![image](https://user-images.githubusercontent.com/21368066/151370104-ad7e404c-69c6-4880-91ef-9dc27b680184.png)

It looks like the Ampere and Turing ones add the same ARP entry, confusing winget. There might be a blocking issue here until the local package index (https://github.com/microsoft/winget-cli/pull/1614) is smart enough to differentiate.

**Comment by Trenly** [comment]
> ![image](https://user-images.githubusercontent.com/21368066/151370104-ad7e404c-69c6-4880-91ef-9dc27b680184.png)
> 
> It looks like the Ampere and Turing ones add the same ARP entry, confusing winget. There might be a blocking issue here until the local package index ([microsoft/winget-cli#1614](https://github.com/microsoft/winget-cli/pull/1614)) is smart enough to differentiate.

Do they have different product codes?

**Comment by Trenly** [comment]
> It looks like the Ampere and Turing ones add the same ARP entry, confusing winget. There might be a blocking issue here until the local package index ([microsoft/winget-cli#1614](https://github.com/microsoft/winget-cli/pull/1614)) is smart enough to differentiate.

Dang, that is a bit disappointing that they don't even differentiate the product codes
