### ISSUE TITLE
Node.js package versions with `Switches` field are all broken

### ISSUE THREAD

**Issue by saschanaz** [microsoft/winget-pkgs#4360]
# Brief description of your issue

For example, installing Node.js 14.14 throws:

```
> winget install Node.js -v 14.14.0
Found Node.js [OpenJS.NodeJS]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://nodejs.org/dist/v14.14.0/node-v14.14.0-x64.msi
  ██████████████████████████████  29.1 MB / 29.1 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Kagami\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\OpenJS.NodeJS.14.14.0.log
```

... while installing 14.12 is okay:

```
> winget install Node.js -v 14.12.0
Found Node.js [OpenJS.NodeJS]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://nodejs.org/dist/v14.12.0/node-v14.12.0-x64.msi
  ██████████████████████████████  29.1 MB / 29.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

# Steps to reproduce

* `winget install Node.js -v 14.14.0`

# Expected behavior

It should succeed

# Actual behavior

`Installer failed with exit code: 1603`

# Environment

```none
> winget --info
Windows Package Manager v0.2.2521 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.572
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

Pinging contributors who add `Switches`: @jedieaston @ItzLevvie

**Comment by jedieaston** [comment]
I'm happy to fix the manifests, but I'm unable to reproduce this...

```
> winget install Node.js -v 14.14.0                                             
Found Node.js [OpenJS.NodeJS]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://nodejs.org/dist/v14.14.0/node-v14.14.0-x64.msi
  ██████████████████████████████  29.1 MB / 29.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed

```

```
> winget --info
Windows Package Manager v0.2.2521 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.572
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

```

Can you post the log file that WinGet gave you the path for? That may help track down the discrepancy.

**Comment by saschanaz** [comment]
Did you run the terminal app with admin privilege? Because doing so makes it succeed. I guess `/q` suppresses UAC popup to make it fail by default.

**Comment by jedieaston** [comment]
Yes, I did. Now that I think about it, Node didn’t install on my host without running PowerShell as admin, so that must be what it is. 

Looks like the resolution to this is being tracked in Microsoft/winget-cli#152, since when that attribute is added this can be fixed in a more user friendly way.

**Comment by saschanaz** [comment]
Yes, that would be great! Can we remove `/q` until winget adds that feature? I don't think failing by default is a good user experience 🤔

**Comment by jedieaston** [comment]
Alright, I've fixed this for all of the affected LTS and normal (i.e. not nightly) builds. Once they are merged you should be good to go.

**Comment by KevinLaMS** [comment]
Just to be clear. The removal of the  /Q will not change the behavior.  By default we will do MSI silently.  So we are stuck with the 1603 when not run in a non-administrative prompt.

**Comment by saschanaz** [comment]
> Just to be clear. The removal of the /Q will not change the behavior. By default we will do MSI silently. So we are stuck with the 1603 when not run in a non-administrative prompt.

Could you explain why [14.12.0](https://github.com/jedieaston/winget-pkgs/blob/48ff33c6a64e033818ce883a3a5b69c099565ef5/manifests/OpenJS/NodeJS/14.12.0.yaml) is not getting the silent behavior then? Sounds like it should be silent but it's not. Making it non-silent is the sole reason why I didn't include `/q` there.

**Comment by saschanaz** [comment]
15.0.1 installs without any problem, thank you @jedieaston!
