### ISSUE TITLE
[Package Request]:  SophiApp

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#43942]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: https://github.com/Sophia-Community
Publisher Url: https://github.com/Sophia-Community/SophiApp
Package Name:  SophiApp
Description:  ⚡ The next chapter of the Sophia Script project. A GUI app for fine-tuning and tweaking Windows 10 & Windows 11 (in the future) 
Package Version: 1.0.0.0 beta 1
Installer URL: https://github.com/Sophia-Community/SophiApp/releases/download/1.0.0.0/SophiApp.zip

Current Package Identifier (for new versions):

**Comment by lychichem** [comment]
Have you ever carefully read all the instructions and selected the checkbox? It's a zip file, which is blocked now.

**Comment by farag2** [comment]
@soredake, I'm one of the main developer of SophiApp. Unfortunately, as you were told above, winget doesn't support archives yet. And I don't think that SophiApp is ready to be distributed via such channel. Better wait until March when we're going to release the stable build with the Windows 11 support. Also 1.0.0.0 version is already totally out-dated. Take a look at 1.0.0.11. :) It's much more stable with working search, a new Security category.

**Comment by Trenly** [comment]
Blocked by #174

**Comment by Trenly** [comment]
Resolved by #95135 and #95542
