### ISSUE TITLE
[Bug]: Pipelines fail to validate packages with WinUI dependency

### ISSUE THREAD

**Issue by yoshiask** [microsoft/winget-pkgs#44310]
### Brief description of your issue

The automatic validation of packages fails if the package contains a dependency on WinUI 2.5+. This is particularly problematic for UWP apps updated in the last year, as WinUI 2.4 (the most recent working version) released in May 2020, and the Sun Valley / Win11 styles were introduced in WinUI 2.6.

### Steps to reproduce

1) Submit a PR to add a package with a dependency on WinUI 2.6.
2) Wait for the CI to run.
3) Observe that validation fails.

See #43996 or #30081 for an example.

### Expected behavior

Validation does not fail because of dependencies on stable WinUI versions.

### Actual behavior

Validation fails even when the package is otherwise valid.

### Environment

```shell
N/A
```

**Comment by jedieaston** [comment]
We may need to start listing WinUI 2.5+ as a dependency (which won't help you *now* but would be a workaround for this that won't break packages on Windows 10 that doesn't have it installed by default).

Does anyone know if there's somewhere Microsoft makes the appx available for download outside of the store? The only link I can find with a quick search is to the SDK.

**Comment by veler** [comment]
> Does anyone know if there's somewhere Microsoft makes the appx available for download outside of the store? The only link I can find with a quick search is to the SDK.

It looks like Windows Terminal can be installed through WinGet: https://github.com/Microsoft/Terminal#via-windows-package-manager-cli-aka-winget

**Comment by jedieaston** [comment]
Found it: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by veler** [comment]
Does that mean that installing this VSIX on the CI's VM should give us this possibility?
In the documentation, I see WinUI 3 listed but not 2.5/2.6.

**Comment by jedieaston** [comment]
We would need to add it as a dependency to manifests that require WinUI, and I don't know if it works for 2.x. I'll test it later today and see.

**Comment by ItzLevvie** [comment]
> It looks like Windows Terminal can be installed through WinGet: https://github.com/Microsoft/Terminal#via-windows-package-manager-cli-aka-winget

cc @veler: This is because Windows Terminal includes a pre-built WinUI 2.7 in the MSIX package so it doesn't require people to install that dependency on their device if they don't have it.

> Installing the Windows App SDK Runtime gives you the WinUI frameworks too.

An alternative way would be to contact the WinUI team to see if they can create aka.ms links for WinUI 2.5, 2.6 & 2.7 which can then be added into the WinGet package repository so that the package can have its dependencies included.

For example:
```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.WinUI.x64
    MinimumVersion: 2.6
```

> I don't know if it works for 2.x

If the VSIS only includes WinUI 3.0 then it'll not work for WinUI 2.x.

WinUI is version-specific so if an app needs WinUI 2.6, you will not be able to use WinUI 2.5 or WinUI 2.7 or WinUI 3.0, it must be WinUI 2.6.

**Comment by jedieaston** [comment]
I didn't realize Microsoft.UI.Xaml was the same thing. In which case, https://github.com/microsoft/winget-cli/issues/1861 is an issue I made on the other repo for the same ask since DesktopAppInstaller now requires WinUI too.

**Comment by denelon** [comment]
We're doing some work to enable support Windows App SDK.

**Comment by yoshiask** [comment]
> We're doing some work to enable support Windows App SDK.

While this is greatly appreciated, I would like to note just in case that this will not fix issues with WinUI 2.x dependencies.

**Comment by yoshiask** [comment]
https://github.com/actions/virtual-environments/issues/4856 
It looks like `windows-2022` is being introduced. Does Windows Server 2022 including WinUI 2.6? Would updating the workflows to the latest version fix this issue?

**Comment by denelon** [comment]
I think the bigger question in my will it install correctly on machines requiring a newer version of WinUI.

It's possible to set a minimum OS version in the manifest to prevent the Windows Package Manager from installing on an older OS. That "should" cause a different error message internally when we perform dynamic analysis if we're on an older OS than what is specified.

**Comment by denelon** [comment]
This issue is quite old, but I believe now that we have support for dependencies this issue might be resolved. Can anyone confirm?
