### ISSUE TITLE
[Package Request]: Vale

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/winget-pkgs#44415]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: errata-ai
Publisher Url: https://errata.ai/
Package Name: vale
Description: A syntax-aware linter for prose built with speed and extensibility in mind.
Package Version: 2.14.0
Installer URL: https://github.com/errata-ai/vale/releases/download/v2.14.0/vale_2.14.0_Windows_64-bit.zip

Current Package Identifier (for new versions): 

GitHub: https://github.com/errata-ai/vale
Chocolatey: https://community.chocolatey.org/packages/vale

**Comment by vedantmgoyal2009** [comment]
> [x] I have checked that the installer for this package is not a standalone or portable executable or a .zip file

You ticked that but still reported a package with the installer that is a `.zip`.

**Comment by Stanzilla** [comment]
> > [x] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
> 
> You ticked that but still reported a package with the installer that is a `.zip`.

My bad, fixed!

**Comment by Trenly** [comment]
Blocked by #174
