### ISSUE TITLE
[Bug]: GOG.Galaxy waits for input if version is already installed or if running -> not really unattended

### ISSUE THREAD

**Issue by Yolgie** [microsoft/winget-pkgs#44864]
### Brief description of your issue

GOG.Galaxy installer is not unattended and blocks waiting for user action in 2 cases:

## Case: Same Version
Because GOG.Galaxy does not report it's installed version correctly (actually not at all, see https://github.com/microsoft/winget-pkgs/issues/30134, https://github.com/microsoft/winget-pkgs/issues/27206) it is always reinstalled also if the same version is already installed on the system. This causes an error in the installer that actually blocks and waits for user input.

![image](https://user-images.githubusercontent.com/200311/152656434-1d62eb2d-27fe-48fe-a707-18f0926192ac.png)

## Case: Program running
This also happens if GOG.Galaxy is running. Then the Installer blocks with the prompt to stop it.

![image](https://user-images.githubusercontent.com/200311/152656573-4b9dca6a-d1a6-4509-827f-292e4112de88.png)

## Case: Same Version
1. Install GOG.Galaxy with `winget install GOG.Galaxy`
2. Verify that GOG.Galaxy version is not set correctly by running `winget upgrade`
3. Make sure GOG.Galaxy is not running
4. "Upgrade" GOG.Galaxy with `winget upgrade --all` or `winget upgrade GOG.Galaxy`
5. Popup appears

## Case: Programm running
1. Install GOG.Galaxy with `winget install GOG.Galaxy`
2. Verify that GOG.Galaxy version is not set correctly by running `winget upgrade`
3. Start GOG.Galaxy
4. "Upgrade" GOG.Galaxy with `winget upgrade --all` or `winget upgrade GOG.Galaxy`
5. Popup appears

### Expected behavior

No popups, just silently installs or skips installation if already installed.

### Actual behavior

Popup waiting for user interaction

### Environment

```shell
Windows: Windows.Desktop v10.0.19044.1466
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
GOG.Galaxy: Version 2.0.45.61
```

**Comment by OfficialEsco** [comment]
> Case: Same Version

Well, this is on GOG not reporting the version, not our fault its reinstalling the same version OR accidentally downgrading

> Case: Program running

I don't remember if this is a Inno or a Nullsoft switch but they tend to have a switch to close the running program (not sure if every installer got it), however this is a good prompt if they have unsaved work

**Comment by Yolgie** [comment]
I'm absolutely aware that this is mostly an issue with the GOG Installer itself, but the underlying question is really how does winget want to proceed with installers that act this way? Is it required that the installer is really unattended no matter the state or is this fine from a winget perspective? Or mabye more precisely what kind of promt/interactivity is expected/allowed and what kind should be suppressed with flags added to the manifest?

**Comment by OfficialEsco** [comment]
Unknown version: Don't upgrade

Self updating: Warning

Installing: Unattended

Upgrading: Have not been focused, but if there is a switch it should be implemented

I've just been told Inno uses `/CLOSEAPPLICATIONS` and `/FORCECLOSEAPPLICATIONS` however those don't work, so its probably something the Publisher have to support.

**Comment by denelon** [comment]
The latest release of WinGet now excludes "Unknown" versions from the "default" `winget upgrade --all` flow. An option is available to "--include-unknown".
