### ISSUE TITLE
[Bug]: DownloadHelper.VdhCoApp 1.6.3 does not install correctly

### ISSUE THREAD

**Issue by chbwien** [microsoft/winget-pkgs#44897]
### Brief description of your issue

DoewnloadHelper.VdhCoApp 1.6.3 installs, but after the installation, the installed version keeps 'unknown', so with the next upgrade --all the program is reinstalled again. The keeps going...
Looks like the installer does not set the correct settings.

### Steps to reproduce

install it, and use winget upgrade and you will see this
```
Name     ID                      Version Verfügbar Quelle
---------------------------------------------------------
VdhCoApp DownloadHelper.VdhCoApp Unknown 1.6.3     winget
```

### Expected behavior

Correct setting of the version and therefore winget is recognizing the version

### Actual behavior

The version stays at unknown

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1466
Paket: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by OfficialEsco** [comment]
This is a issue with the Publishers Installer not setting the DisplayVersion string, not WinGet.
![VirtualBoxVM_0wrsbwXAXO](https://user-images.githubusercontent.com/15158490/152680699-9b52b68a-236a-48b6-beae-a335b540ce3a.png)
Since this is a GitHub package you can open a issue here https://github.com/mi-g/vdhcoapp/issues
@Trenly or @jedieaston can probably submit a PR to fix the installer, however the fix will not be out before the next version.

**Comment by chbwien** [comment]
Thank you for the info. I've created an issue: https://github.com/mi-g/vdhcoapp/issues/118

**Comment by alanlivio** [comment]
Hi. I think I found a related problem.  
When doing `winget upgrade` VdhCoApp is updated although having the last version.  


![image](https://user-images.githubusercontent.com/604808/183412667-b623ee15-dfa6-493b-8935-7a7a6259540e.png)

**Comment by OfficialEsco** [comment]
Well.. Its the same issue.
Upgrade to [WinGet Cli version 1.3.2091](https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091)

**Comment by alanlivio** [comment]
Thanks @OfficialEsco. `winget upgrade VdhCoApp` does not reinstall the same version.
However, a `winget upgrade --all` have the following  result
```
> winget upgrade --all
No installed package found matching input criteria.
1 package(s) have version numbers that cannot be determined. Use "--include-unknown" to see all results.
```
Bests

**Comment by alanlivio** [comment]
Just an update. The --include-unknown option upgrade the app but also without version
``` 
$ winget upgrade --all --include-unknown
Failed in attempting to update the source: winget
Name           Id                      Version Available Source
---------------------------------------------------------------
VdhCoApp 1.6.3 DownloadHelper.VdhCoApp Unknown 1.6.3     winget
1 upgrades available.
(1/1) Found VdhCoApp [DownloadHelper.VdhCoApp] Version 1.6.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/mi-g/vdhcoapp/releases/download/v1.6.3/VdhCoAppSetup-1.6.3.exe
...
```
```
$ winget list DownloadHelper.VdhCoApp
Name           Id                      Version Available Source
---------------------------------------------------------------
VdhCoApp 1.6.3 DownloadHelper.VdhCoApp Unknown 1.6.3     winget
```
