### ISSUE TITLE
Installations fail with message "IT policies may be restricting access to this folder"

### ISSUE THREAD

**Issue by aditya-giri** [microsoft/winget-pkgs#450]
A lot of packages (Atom, Kindle, Postman etc.) all failed to install via winget. One error I get often is:

![Capture](https://user-images.githubusercontent.com/30208735/82445650-d2d92300-9ac2-11ea-8ea7-a19af76ed8de.PNG)

There is not folder called adity under ProgramData, although that is my username. 
The installations succeed if I do them manually, no access errors of any sort.

**Comment by LukasNespor** [comment]
It is not probably issue of the winget itself. You can try to run the installation file from:
```
c:\Users\adity\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\
```
Note: If the app is not there (_but should be because it was already downloaded using winget_) just copy it there and try to start it manually. You will get the same error.

**Comment by aditya-giri** [comment]
@LukasNespor running the installation from that directory does not work. But if I copy the same file to the different location and try it goes through. It may not be an issue with winget itself, but it's definitely an issue with where the installers are being stored.

**Comment by LukasNespor** [comment]
This issue is already tracked in different repository https://github.com/microsoft/winget-cli/issues/189

**Comment by aditya-giri** [comment]
Ah apologies 🤦 I opened the issue in the wrong repo. Closing this.
