### ISSUE TITLE
winget upgrade installs demo version in the place of full version

### ISSUE THREAD

**Issue by jan-oratowski** [microsoft/winget-pkgs#45191]
### Brief description of your issue

Looks like:
`winget upgrade`

Will try to "upgrade" some packages to their demo versions:
![image](https://user-images.githubusercontent.com/54535207/152676981-b96c1b39-5d7c-4254-944b-6999a3ed8e54.png)

### Steps to reproduce

Install Video Hub App 3 or any other software that has a demo and full version available.

Try upgrading.

### Expected behavior

Full and demo versions should be treated as separate packages, or there should be a way to blacklist package keywords and prevent the package from upgrading.

### Actual behavior

The demo version will be installed over the full version.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1503
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment]
The demo version is the only manifest that has been submitted as far as I can tell. It's likely due to how the package is matched in Windows Apps & Features.

**Comment by whyboris** [comment]
@msftbot closed the issue incorrectly! I do not believe `winget` is doing a service to people by overwriting their purchased software with a demo 🤔 

https://github.com/whyboris/Video-Hub-App/issues/790

**Comment by whyboris** [comment]
@microsoft -- I'm the creator of [_Video Hub App_](https://github.com/whyboris/Video-Hub-App) and would love if `wget` didn't overwrite purchased software with a demo version.

Please advise what I can do to prevent this from happening.

**Comment by jan-oratowski** [comment]
Hi @whyboris,

I think the problem may be caused by the fact that the version of the demo app is set to 3.1.0-demo and it somehow confuses winget as it thinks 3.1.0-demo > 3.1.0.

Demo:
![image](https://user-images.githubusercontent.com/54535207/215823657-1dc4a012-4903-4d99-a69d-6c07dba3fe29.png)
Full:
![image](https://user-images.githubusercontent.com/54535207/215823336-6b4a1916-6f78-479d-b158-caab16df7241.png)

I think that removing "-demo" from the version and just renaming the demo app to something like "Video Hub App Demo 3" could solve the problem.

Probably also leaving "-demo" in the version, but adding "-full" to the full version can also solve the problem as "full" > "demo" when sorting strings.

**Comment by whyboris** [comment]
Hey @jan-oratowski - thank you for the suggestion! I'll look into this before my next release (hoping for end of February).

I like your idea of keeping the version the same but changing the app name. I would also want the full version of the app, when installed, to _replace_ the demo; I'll test and see if things work well 🤞 

More suggestions welcome 🙇

**Comment by denelon** [comment]
@whyboris, We do see a fairly common patterns of:
* "Publisher.Package" and "Publisher.Package.Insider"
* "Publisher.Package" and "Publisher.Package.Preview"

I believe "Publisher.Package" and "Publisher.Package.Demo" would also align nicely.

WinGet evaluates the "displayName" and "displayVersion" values out of the registry (It's the same keys used in Windows Apps and Features) to determine what packages are installed, and which versions they are. Modifying the "displayName" across the two variations of the package would sufficiently distinguish the two. Although for the sake of completeness, things in parenthesis may be excluded, so I would avoid using them.

I'm not aware of any cases where a "full" version replaces another ("insider", "preview", or "demo") version. That's not a mechanism supported by WinGet intrinsically. Performing that kind of an action would likely require some custom behavior in the installer for the "full" version.

**Comment by jan-oratowski** [comment]
I have just checked and when I have:

- DEMO installed and run the FULL installer, it will not ask me if I want to replace the version, or give me any warning, it will just do it.
- FULL installed and run the DEMO installer, also no warning and just overwrite it
