### ISSUE TITLE
[Bug]: Docker Desktop not installing silently

### ISSUE THREAD

**Issue by varXX404** [microsoft/winget-pkgs#45705]
### Brief description of your issue

Docker Desktop installation is very verbose even when using --silent

### Steps to reproduce

Run 
`winget install --silent --source winget --name "Docker Desktop" --accept-package-agreements --accept-source-agreements`

### Expected behavior

A silent installation with a message of 

Found Docker Desktop Version X.X.X
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading
Successfully verified Installer hash
Starting package install...
Sucessfully installed

### Actual behavior

Hundreds of lines, descirbing every file that is getting unpackaged.

https://i.imgur.com/7p7HyCt.png

### Environment

```shell
PS C: \Windows\system32> winget --info
Windows Package Manager VI. 1.13405
Copyright (c) Microsoft Corporation. All rights reserved.
Windows: Windows . Desktop v10.Ø.19044.1466
Package: Microsoft . DesktopAppInsta11er VI .16.13405.0

Logs: . DesktopAppInsta11er 8wekyb3d8bbwe\Loca1State\DiagOutputDir
```

**Comment by denelon** [comment]
Related to:

* microsoft/winget-cli/issues/1927
