### ISSUE TITLE
[Package Request]: VisiPics.VisiPics

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#45788]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

- Publisher: Guillaume FOUET (aka Ozone)
- Publisher Url: <http://www.visipics.info/index.php>
- Package Name: VisiPics
- Description: Quick & Easy Duplicate Images Cleaner
- Package Version: 1.31
- Installer URL: <https://www.fosshub.com/VisiPics.html?dwl=VisiPics-1-31.exe>
- Current Package Identifier (for new versions): **None**

**Comment by Dragon1573** [comment]
There's something wierd with the **Installer URL**. When I create the manifest of this package, I met the following errors:

```text
manifests  master ≡ λ wingetcreate.exe new

 InstallerUrls 值为:
  https://www.fosshub.com/VisiPics.html?dwl=VisiPics-1-31.exe

正在下载和分析: https://www.fosshub.com/VisiPics.html?dwl=VisiPics-1-31.exe...
无法从 [https://www.fosshub.com/VisiPics.html?dwl=VisiPics-1-31.exe] 中分析数据包
```

The "actual" download url of this package looks like this (Got from **Download** Panel in Microsoft Edge):

- <https://download.fosshub.com/Protected/expiretime=1644620952;badurl=aHR0cHM6Ly93d3cuZm9zc2h1Yi5jb20vVmlzaVBpY3MuaHRtbA==/9d1bd67c5d275c117d4777bf69372695190da83d7753c50c064646a73392a4f0/5b8d472959eee027c3d78953/5b8d474959eee027c3d7895c/VisiPics-1-31.exe>

I can't handle this situation myself, so I create this issue (package request). I'm willing to submit the manifests myself when I find the "stable" URL of this package.

**Comment by OfficialEsco** [comment]
We're not allowed to use Fosshub as its against their TOS.

**Comment by OfficialEsco** [comment]
> > We're not allowed to use Fosshub as its against their TOS.
> 
> Oops?! It's mentioned in `Abuse - Section B.` and `Exceptions` Part in TOS.
> 
> Is it possible to talk with FossHub and adding `winget.exe` to FossHub's "Exception" List?

I believe they don't want bots to constantly access and download from their server as they probably monitor usage and stuff

Feel free to ask them but you'll probably get denied

**Comment by Dragon1573** [comment]
> I believe they don't want bots to constantly access and download from their server as they probably monitor usage and stuff

Okay, I'll installed it manually 😂

Thanks for your help. This issue can be closed.
