### ISSUE TITLE
[Bug]: Screen To Gif doesn't run on ARM64 even after installing .NET 

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#45821]
### Brief description of your issue

Tracking external Issue:
* NickeManarin/ScreenToGif/issues/1075

### Steps to reproduce

`winget install screentogif -s winget`
-or-
`winget install screentogif -s msstore`

### Expected behavior

After install succeeds I can launch Screen To Gif.

### Actual behavior

![ScreenToGif Error](https://user-images.githubusercontent.com/61799811/153651582-07bb57e5-29b6-48f3-99ef-9b74fa578558.png)

### Environment

```shell
PS C:\Users\denelon> winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by jedieaston** [comment]
> `winget install screentogif -s msstore`

Off-topic, but does the Microsoft Store have a manual review step for win32 apps like the community repository does? It seems like apps that don't run shouldn't make it into the store, although they do here because I'm the only mod with a arm64 device and I rarely test on it :/

**Comment by vedantmgoyal2009** [comment]
Raspberry Pi 4?

**Comment by denelon** [comment]
Surface Pro X

**Comment by denelon** [comment]
Surface Pro X

**Comment by denelon** [comment]
I don't know what all gets tested for the Microsoft Store. I've mentioned this to them.
