### ISSUE TITLE
[Package Request]: New Version of Waterfox

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#46222]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: WaterfoxLimited
Publisher Url: https://www.waterfox.net
Package Name: Waterfox
Description: Waterfox is free and open source browser, based on Mozilla Firefox.
Package Version: 91.6.0
Installer URL: https://github.com/WaterfoxCo/Waterfox/releases/download/G4.0.7/Waterfox.G4.0.7.Setup.exe

Current Package Identifier (for new versions): Waterfox.Waterfox

**Comment by Trenly** [comment]
This already exists. `winget install Waterfox.Waterfox --version G4.0.7`

**Comment by thedoggybrad** [comment]
@Trenly It is available but the versions are not sorted correctly so winget is confused. Thank You  for the pull request to remove other versions.
