### ISSUE TITLE
[Package Request]: Chromium (Stable)

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#46251]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Woolsys and The Chromium Authors
Publisher Url: https://chromium.woolyss.com/
Package Name: Chromium
Description: The open source web browser maintained by the Chromium team and modified by Woolsys.
Package Version: 98.0.4758.82
Installer URL: https://github.com/Hibbiki/chromium-win64/releases/download/v98.0.4758.82-r950365/mini_installer.sync.exe
Architecture: 64-Bit
Status: Stable

Current Package Identifier (for new versions):

**Comment by thedoggybrad** [comment]
@Trenly Can you add this? Thank You in advance.

**Comment by thedoggybrad** [comment]
@OfficialEsco Can you add it? Thanks in Advance.

**Comment by OfficialEsco** [comment]
Hmm, sure, we already have eloston.ungoogled-chromium which is the macchrome fork, but i see the reason for wanting the Hibbiki version
