### ISSUE TITLE
[Bug]: Chrome update keeps failing on our devices running Win11-enterprise

### ISSUE THREAD

**Issue by DrDonkz** [microsoft/winget-pkgs#46559]
### Brief description of your issue

Chrome update keeps failing on our devices running Win11-enterprise. Chrome is installed before using the enterprise installer MSI. Does these fails only happen to us or is it normal a few apps won't be able to update right every once in a while?

### Steps to reproduce

install chrome using the enterprise msi installer, then update using winget and it will give an error saying it cannot be installed.

### Expected behavior

The update starts and finishes without problems

### Actual behavior

The update fails unexpectedly

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.526
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

Chrome version 98.0.4758.82
```

**Comment by jedieaston** [comment]
Can you get the log file from when you do `winget upgrade Google.Chrome`?

**Comment by DrDonkz** [comment]
Good afternoon,

Apparently the users with this problem had the wrong version installed. They didn't use the enterprise version made available to them, which caused the main problem. Thanks for the quick reply though!


Met vriendelijke groet,

Max Jonkers
Afdeling-ICT

E   ***@***.***

 [cid:a932596c-8dcc-4658-bca6-c1b0ded48db7]

 Olympiaweg 8b | 5143 NA Waalwijk | T 0416 67 39 30

OMO Scholengroep De Langstraat bestaat uit het Dr. Mollercollege,
het d'Oultremontcollege, het Van Haestrechtcollege en de Walewyc-mavo.

Disclaimer
Dit e-mailbericht is slechts bestemd voor de geadresseerde en kan informatie bevatten die persoonlijk of vertrouwelijk is en niet openbaar mag worden gemaakt. Indien een ander dan geadresseerde dit e-mailbericht ontvangt of anderszins in handen krijgt, is hij niet gerechtigd tot kennisneming, verspreiding of vermenigvuldiging daarvan.


________________________________
Van: Easton Pillay ***@***.***>
Verzonden: woensdag 16 februari 2022 15:03
Aan: microsoft/winget-pkgs ***@***.***>
CC: Max Jonkers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/winget-pkgs] [Bug]: (Issue #46559)


Can you get the log file from when you do winget upgrade Google.Chrome?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fwinget-pkgs%2Fissues%2F46559%23issuecomment-1041523609&data=04%7C01%7Cm.jonkers%40sgdelangstraat.nl%7C35409c09cb9743ba304308d9f15520a7%7Cf668b49c4ab448c2a69c461f683a504b%7C0%7C0%7C637806170801674935%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9hbBeTPsCumIVV1eeIi%2BeYAJ7t9iH1m0vwYXXfGN7ZM%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXVXTOVKZLZKSAIGY4CB4ILU3OVDFANCNFSM5ORD2QHQ&data=04%7C01%7Cm.jonkers%40sgdelangstraat.nl%7C35409c09cb9743ba304308d9f15520a7%7Cf668b49c4ab448c2a69c461f683a504b%7C0%7C0%7C637806170801674935%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l9vMcic3x1dVh%2FTeFWIApAx9ozCIDl9OxuiYcH431Sw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cm.jonkers%40sgdelangstraat.nl%7C35409c09cb9743ba304308d9f15520a7%7Cf668b49c4ab448c2a69c461f683a504b%7C0%7C0%7C637806170801674935%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0UfTj%2B%2Bp8mcBrEsVZhR1IOnQJQ%2FxPs7y67ovgW8Cc5Y%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cm.jonkers%40sgdelangstraat.nl%7C35409c09cb9743ba304308d9f15520a7%7Cf668b49c4ab448c2a69c461f683a504b%7C0%7C0%7C637806170801674935%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zh7ClXwaQcHM2J306pvETCFNNbsja8zT9Qck95iYncs%3D&reserved=0>.

**Comment by DrDonkz** [comment]
Apparently the users with this problem had the wrong version installed. They didn't use the enterprise version made available to them, which caused the main problem. Thanks for the quick reply though!

**Comment by ItzLevvie** [comment]
Close with reason: Author has their issue solved;
