### ISSUE TITLE
[Bug]: Sky.SkyGo

### ISSUE THREAD

**Issue by meyerdominik** [microsoft/winget-pkgs#47074]
### Brief description of your issue

I had the german version of Sky Go installed on my computer. When I decided to upgrade all via winget (winget upgrade -all). Then winget decided to replace my german version of sky go with the english one (can't log in with my german sky account in the english version)

### Steps to reproduce

1) Install the german version via https://desktopclient.ott.sky.com/skygodesktop/DE/SkyGoInstaller.exe (https://www.sky.de/produkte/sky-go-158150)
2) winget upgrade Sky.SkyGo
2.1) winget downloads from https://desktopclient.ott.sky.com/skygodesktop/GB/SkyGoInstaller.exe
3) the german version is replaced with the english verison

### Expected behavior

Either upgrade the german verison or do not upgrade at all

### Actual behavior

winget decided to replace my german version of sky go with the english one

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.493
Package: Microsoft.DesktopAppInstaller v1.16.13405.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by meyerdominik** [comment]
Seems not to work :(  

> winget source update
>Updating all sources...
>Updating source: msstore...
>Done
>Updating source: winget...
>  ██████████████████████████████  100%
>Done

> winget upgrade sky.skygo
>Found Sky Go [Sky.SkyGo] Version 22.1.3.0
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
> Downloading https://desktopclient.ott.sky.com/skygodesktop/GB/SkyGoInstaller.exe
> Package download canceled.

**Comment by Trenly** [comment]
> Seems not to work :(
> 
> > winget source update
> > Updating all sources...
> > Updating source: msstore...
> > Done
> > Updating source: winget...
> > ██████████████████████████████  100%
> > Done
> 
> > winget upgrade sky.skygo
> > Found Sky Go [Sky.SkyGo] Version 22.1.3.0
> > This application is licensed to you by its owner.
> > Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
> > Downloading https://desktopclient.ott.sky.com/skygodesktop/GB/SkyGoInstaller.exe
> > Package download canceled.

You may have to use `--Locale de-DE` or to update your [settings](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md)

**Comment by meyerdominik** [comment]
Settings do not seem to work either: 


    {
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },


	"installBehavior": {
          "preferences": {
              "locale": [ "de-DE" ]
          }
    }
    }

@Trenly Do you have an example for the usage of `--Locale de-DE` ?

**Comment by ItzLevvie** [comment]
> Do you have an example for the usage of --Locale de-DE ?

Sky Go installer is a bit complicated since every region has a different version number which creates upgrade loops.

**Comment by meyerdominik** [comment]
Sky Germany updated their sofware to the same verisonnumber as the GB-version. Seems to be fixed now. 👍
