### ISSUE TITLE
[Package Request]: Epson Device Admin

### ISSUE THREAD

**Issue by GoliathLabs** [microsoft/winget-pkgs#47180]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Seiko Epson Corporation
Publisher Url: https://www.epson.eu/verticals/device-admin
Package Name: Epson Device Admin
Description: Easily manage an entire fleet of printers and scanners remotely, with full control including the ability to install, configure, monitor, maintain and troubleshoot your devices for increased productivity and cost savings.
Package Version: v4.17
Installer URL: https://neon.epson-europe.com/files/repo/2016/EpsonDeviceAdmin/media/EDAv4.17.zip

Current Package Identifier (for new versions):

**Comment by GoliathLabs** [comment]
Epson unfortunately only publishes its installer embedded in a zip file. I don't know if we can work around this problem.

**Comment by Trenly** [comment]
* Blocked by microsoft/winget-cli#140
