### ISSUE TITLE
[Bug]: VMWare.WorkstationPro is not installing with --interactive

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/winget-pkgs#47196]
### Brief description of your issue

I'm trying to install the latest version with this command line:

```
winget install --id VMware.WorkstationPro --exact --interactive --rainbow -s winget
```

After it downloads the installer, I get this dialog box:

![image](https://user-images.githubusercontent.com/5177512/154814014-ec1205e9-4d9b-4338-bb5e-1a7d49796972.png)

After I press OK, winget says the pkg successfully installed but it didn't:

```
Found VMware Workstation [VMware.WorkstationPro] Version 16.2.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download3.vmware.com/software/wkst/file/VMware-workstation-full-16.2.2-19200509.exe
  ██████████████████████████████   615 MB /  615 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

Note that non-interactive (silent) install works just fine.

### Steps to reproduce

Execute:
```
winget install --id VMware.WorkstationPro --exact --interactive --rainbow -s winget
```

### Expected behavior

VMWare Workstation Pro is successfully installed via an interactive install and I don't get the Usage dialog.

### Actual behavior

I get this dialog:

![image](https://user-images.githubusercontent.com/5177512/154814116-46180884-250f-4842-a446-461eab2c7c09.png)

And the app is not installed

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
The issue is caused by the installer being a Installer in a Installer, the Custom switches (`EULAS_AGREED=1 DATACOLLECTION=0 AUTOSOFTWAREUPDATE=0`) we have set are still being applied to the installer while in Interactive mode
