### ISSUE TITLE
[Bug]: Unable to upgrade "Tencent.QQ"

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#47431]
### Brief description of your issue

I previously installed package `Tencent.QQ` with version `9.5.6.28129`. When I invoke `winget upgrade` and refresh the index, it successfully detected a newer version `9.5.8.28186`. But when I invoke `winget upgrade Tencent.QQ`. It responsed **"No applicable update found"**.

I think it's an unexpected behaviour. Shall we modify the value of "UpgradeBehavior"?

### Steps to reproduce

1. Create and launch a **brand new** Windows Sandbox with `Tools/SandboxTest.ps1`.
2. Launch "Administrator: Windows Powershell" in the Windows Sandbox, and then invoke `winget install Tencent.QQ --version 9.5.6.28129` for a previous version.
3. After the installation, invoke `winget upgrade` to refresh manifests index and check for available updates.

   ```text
   PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
   Name           Id             Version     Available    Source
   -------------------------------------------------------------
   Microsoft Edge Microsoft.Edge 92.0.902.67 98.0.1108.56 winget
   腾讯QQ         Tencent.QQ     9.5.6.28129 9.5.8.28186  winget
   2 upgrades available.
   ```

4. Invoke `winget upgrade Tencent.QQ` and unexpected behaviour occured (see below).

### Expected behavior

A newer version (`9.5.8.28186`) of `Tencent.QQ` is correctly found. The upgrade process is launched.

### Actual behavior

`winget.exe` could NOT find any newer version of `Tencent.QQ`.

```text
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade Tencent.QQ
No applicable update found.
```

But if I invoke the following command block, it's successfully updated ...

```text
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget uninstall Tencent.QQ; if ($?) {
>> winget install Tencent.QQ
>> }
Found 腾讯QQ [Tencent.QQ]
Starting package uninstall...
Successfully uninstalled
Found 腾讯QQ [Tencent.QQ] Version 9.5.8.28186
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dldir1.qq.com/qqfile/qq/PCQQ9.5.8/QQ9.5.8.28186.exe
  ██████████████████████████████   173 MB /  173 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

### Environment

```shell
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1526
Package: Microsoft.DesktopAppInstaller v1.16.12653.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
* #47450 
* #47446

**Comment by Dragon1573** [comment]
## Validation Steps

1. Invoke `.\Tools\SandboxTest.ps1` in Windows Terminal.
2. Automatically launced a brand-new Windows Sandbox with `winget.exe` configured.
3. Install a previous version of `Tencent.QQ`.
   ```text
   PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install Tencent.QQ -v 9.5.6.28129
   The `msstore` source requires that you view the following agreements before using.
   Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
   The source requires current machine's geographic region to be sent to function properly.

   Do you agree to all the source agreements terms?
   [Y] Yes  [N] No: Y
   Found 腾讯QQ [Tencent.QQ] Version 9.5.6.28129
   This application is licensed to you by its owner.
   Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
   Downloading https://dldir1.qq.com/qqfile/qq/PCQQ9.5.6/QQ9.5.6.28129.exe
     ██████████████████████████████   170 MB /  170 MB
   Successfully verified installer hash
   Starting package install...
   Successfully installed
   ```
4. Refresh the manifest index.
   ```PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
   Name           Id             Version     Available    Source
   -------------------------------------------------------------
   Microsoft Edge Microsoft.Edge 92.0.902.67 98.0.1108.56 winget
   腾讯QQ         Tencent.QQ     9.5.6.28129 9.5.8.28186  winget
   2 upgrades available.
   ```
5. Try to upgrade `Tencent.QQ` (but failed).
   ```text
   PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade Tencent.QQ
   No applicable update found.
   ```

## Related logs

[Winget_logs_Sandbox.zip](https://github.com/microsoft/winget-pkgs/files/8113023/Winget_logs_Sandbox.zip)

**Comment by ItzLevvie** [comment]
cc @Dragon1573: With the new changes from https://github.com/microsoft/winget-pkgs/pull/47450 and https://github.com/microsoft/winget-pkgs/pull/47446, it should be solved if you're running WinGet version 1.3.431-preview.

![image](https://user-images.githubusercontent.com/11600822/155144614-6c9e31ba-6311-4362-b8ac-ee9da7619a9c.png)

**Comment by Dragon1573** [comment]
@ItzLevvie Now I manually upgraded `winget.exe` to the latest pre-release (v1.3.431-preview).

```text
winget-pkgs  λ winget list 应用安装程序
名称         ID                                          版本
-------------------------------------------------------------------
应用安装程序 Microsoft.DesktopAppInstaller_8wekyb3d8bbwe 1.18.431.0

winget-pkgs  λ winget --info
Windows 程序包管理器(预览) v1.3.431-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.19044.1526
程序包: Microsoft.DesktopAppInstaller v1.18.431.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

winget-pkgs  λ winget features
以下实验性功能正在进行中。
它们可以通过设置文件“winget settings”进行配置。

功能                          状态   属性         链接
--------------------------------------------------------------------------------
Show Dependencies Information 已启用 dependencies https://aka.ms/winget-settings
Direct MSI Installation       已禁用 directMSI    https://aka.ms/winget-settings
```

## Validation Process

```text
winget-pkgs  λ gsudo winget install --scope machine --location E:\Applications\QQ --version 9.5.6.28129 Tencent.QQ
已找到 腾讯QQ [Tencent.QQ] 版本 9.5.6.28129
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
Downloading https://dldir1.qq.com/qqfile/qq/PCQQ9.5.6/QQ9.5.6.28129.exe
  ██████████████████████████████   170 MB /  170 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装

winget-pkgs  λ winget upgrade -s winget
名称   ID         版本        可用
-----------------------------------------
Vim    vim.vim    8.2.4428    8.2.4451
腾讯QQ Tencent.QQ 9.5.6.28129 9.5.8.28186
2 升级可用。
2 packages have version numbers that cannot be determined. Use "--include-unknown" to see all results.

winget-pkgs  λ gsudo winget upgrade Tencent.QQ
已找到 腾讯QQ [Tencent.QQ] 版本 9.5.8.28186
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
Downloading https://dldir1.qq.com/qqfile/qq/PCQQ9.5.8/QQ9.5.8.28186.exe
  ██████████████████████████████   173 MB /  173 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装
```

Above 2 pull requests DOES solve the problem. This issue can be closed, thank you @Trenly @ItzLevvie.

**Comment by Dragon1573** [comment]
However, when we launch a brand-new **Windows Sandbox** via `./Tools/SandboxTest.ps1`, the version of `winget.exe` is still v1.1.12653. I have tried upgrade **App Installer** package with `*.msixbundle` manually many times, but none of them succeeded.

@ItzLevvie Could you please explain more about your "VM"? Is it a **Windows Sandbox**, or just exactly what we usually refered to (a virtual machine running in Hyper-V, VMWare or Oracle)?

**Comment by Trenly** [comment]
> However, when we launch a brand-new **Windows Sandbox** via `./Tools/SandboxTest.ps1`, the version of `winget.exe` is still v1.1.12653. I have tried upgrade **App Installer** package with `*.msixbundle` manually many times, but none of them succeeded.
> 
> @ItzLevvie Could you please explain more about your "VM"? Is it a **Windows Sandbox**, or just exactly what we usually refered to (a virtual machine running in Hyper-V, VMWare or Oracle)?

SandboxTest uses the last release marked “Latest” from Github; Since the 1.3 client hasn’t been fully released, it isn’t marked as latest. 

The reason the upgrade to winget fails on sandbox is because of a dependency on Windows UI Xaml >= 2.6; I believe sandbox comes with 2.4 by default. @jedieaston has a fix for this which is just waiting for the full release of the 1.3 client
