### ISSUE TITLE
[Bug]: Unwanted software bundled with Estmob.SendAnywhere

### ISSUE THREAD

**Issue by u254254** [microsoft/winget-pkgs#47643]
### Brief description of your issue

When installing `Estmob.SendAnywhere`, unwanted software called 'Gicon' is bundled that is for showing an ad. It is optional and unchecked in install screen. but in quiet install by winget, it is installed without any prompt.

### Steps to reproduce

1. Install `Estmob.SendAnywhere` by winget.
2. Press Yes in UAC. (I don't know what happen in press No in UAC)

### Expected behavior

No unwanted software.

### Actual behavior

Installs unwanted software called 'Gicon'

### Environment

```shell
Windows Package Manager v1.1.13405
Windows: Windows.Desktop v10.0.19044.1526
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by OfficialEsco** [comment]
These are the only options i can see when running it manually?
![VirtualBoxVM_sBVzx0Lwna](https://user-images.githubusercontent.com/15158490/155163057-b5acdeae-18f8-4b6f-a46a-72b116ca5729.png)

And no Gicon software installed
![VirtualBoxVM_XSiravHGAE](https://user-images.githubusercontent.com/15158490/155163270-0ee02073-6f2e-4aa9-afcf-9566b04a4f19.png)

**Reset VM**
```
PS M:\> winget install Estmob.SendAnywhere
Found Send Anywhere [Estmob.SendAnywhere] Version 21.4.211415
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://update.send-anywhere.com/downloads/x64/SendAnywhereSetup.exe
  ██████████████████████████████  94.9 MB / 94.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

Still no Gicon software
![VirtualBoxVM_kMSX2fhsVI](https://user-images.githubusercontent.com/15158490/155163774-cc465e51-14a5-4d69-9fc8-68ecced59eee.png)

**Comment by denelon** [comment]
I have also not been able to reproduce this.

@u254254 can you replicate this and share logs? The log location is visible via `winget --info`.

**Comment by u254254** [comment]
I tested manual install in fresh VM (English and Korean). in English Windows, no 'Smart Search' component showing and no Gicon installed. in Korean Windows, Smart Search component shows and installs Gicon.

-----
### Test Images

| English | Korean |
| :-------: | :------: |
| ![No 'Smart Search' component](https://user-images.githubusercontent.com/72965213/155522243-56d03246-6658-4eca-9719-9a32fa8d81af.png) | ![install_ko](https://user-images.githubusercontent.com/72965213/155522431-327437dc-6d61-4b68-b12c-6741ccae1e73.png) |
| *No Gicon installed* | ![gicon_installed](https://user-images.githubusercontent.com/72965213/155522678-f5a915cf-f828-4264-aae0-6502070765f2.png) |
|| *Installed with WinGet:* ![gicon_installed_winget](https://user-images.githubusercontent.com/72965213/155522775-81574876-fe43-4514-8838-181460c837f9.png) |

WinGet logs (Korean Windows): [WinGet logs.zip](https://github.com/microsoft/winget-pkgs/files/8132392/WinGet.logs.zip)

Plus: It registers itself into Task Scheduler:
![Gicon Scheduler](https://user-images.githubusercontent.com/72965213/155524251-568d1d76-5f49-4550-922d-aa1ba9db306e.png)

**Comment by OfficialEsco** [comment]
And both times you used https://update.send-anywhere.com/downloads/x64/SendAnywhereSetup.exe ?
So the bad thing about Closed source Nullsoft and Inno installers is that we cannot know their custom switches, aka we cannot disable it when the evil Developer enabled it by default..

**Comment by OfficialEsco** [comment]
I do not, i've never seen a package act differently under a different locale, i believe this is a Korean/Chinese issue...
We can force it to be Interactive only? Or add a warning to the Korean InstallerLocale/Locale?

**Comment by denelon** [comment]
We need to test to see if Gicon flags as PUA. I've asked the team to confirm and run scans. If it is detected as PUA, we will remove it from the repository.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/23473

**Comment by SpecterShell** [comment]
There is no switch to uncheck NSIS section and I didn't see any custom switches available.
Anyway, there are two ways to bypass it manually:
1. Block `www.wizchat.co.kr` in Firewall
2. Put something to `%APPDATA\msafespt\msafespt.exe%

```NSIS
Function .onInit
  ; ...
  StrCmp $LANGUAGE 1042 label_1084 ; If is Korean, jump to label_1084
  Push $R0
  Push $R1
  StrCpy $R1 5
  SectionGetFlags $R1 $R0
  IntOp $R0 $R0 & 0xFFFFFFFE ; https://nsis-dev.github.io/NSIS-Forums/html/t-143655.html
  SectionSetFlags $R1 $R0 ; Force uncheck "Smart Search"
  SectionSetText $R1 "" ; Hide "Smart Search"
  Pop $R1
  Pop $R0
label_1084:
  IfFileExists $APPDATA\msafespt\msafespt.exe 0 label_1086 ; If file exists, hide "Smart Search"
  SectionSetText 5 ""
label_1086:
  ; ...
FunctionEnd
```

> I do not, i've never seen a package act differently under a different locale, i believe this is a Korean/Chinese issue... We can force it to be Interactive only? Or add a warning to the Korean InstallerLocale/Locale?
It only appears in Korean.

**Comment by denelon** [comment]
We have added a [task](https://github.com/microsoft/winget-pkgs/blob/418066a42af65a7ad7c7807390b77ae3acdcf9af/.github/fabricbot.json#L4731)  with @msftbot to add "Blocking-Issue" to PRs for this package.
