### ISSUE TITLE
RubyInstallerTeam.Ruby - Splitting versions

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#47664]
Ruby needs to be split into different folders at X.X since they can be installed side by side

```
| RubyInstallerTeam
|| Ruby
||| 2.7
|||| 2.7.1
|||| 2.7.2
|||| 2.7.5-1
||| 3.0
|||| 3.0.0
|||| 3.0.1.1
|||| 3.0.2-1
||| 3.1
|||| 3.1.0-1
```
We would probably have to use x64 and x86 folders too unless winget-cli supports updating 2 installs
![VirtualBoxVM_ciMefjfcYd](https://user-images.githubusercontent.com/15158490/155196216-053e4265-8c1b-446a-a56c-31b3a45d379d.png)
![VirtualBoxVM_QMJUe8diY7](https://user-images.githubusercontent.com/15158490/155196220-06ab45b5-c89f-4ae0-a46d-bcb658b31776.png)

--------------------------

>To help with debugging, another set of packages that fail to upgrade:
>
>```
>    PS ...Sda\Code> winget upgrade --all
>    Name                      Id                               Version      Available    Source
>    -------------------------------------------------------------------------------------------
>    Ruby                      RubyInstallerTeam.Ruby           2.4.3-2      3.1.0-1      winget
>    Ruby                      RubyInstallerTeam.Ruby           3.0.1-1      3.1.0-1      winget
>    9 upgrades available.
>    27 packages have version numbers that cannot be determined. Use "--include-unknown" to see all results.
>```
>
>That is, `winget upgrade --all` can be run twice and the same 9 packages will be listed, even after some of those packages were ostensibly upgraded.
>
>_Originally posted by **JohnLukeBentley** in https://github.com/microsoft/winget-cli/issues/752#issuecomment-1044387977_

**Comment by mthierman** [comment]
```
Name                               Id                               Version Available Source
--------------------------------------------------------------------------------------------
Ruby 2.7.6-1-x64-msvcrt with MSYS2 RubyInstallerTeam.RubyWithDevKit 2.7.6-1 3.1.2-1   winget
```

This is.. not ideal

**Comment by russellbanks** [comment]
> ```
> Name                               Id                               Version Available Source
> --------------------------------------------------------------------------------------------
> Ruby 2.7.6-1-x64-msvcrt with MSYS2 RubyInstallerTeam.RubyWithDevKit 2.7.6-1 3.1.2-1   winget
> ```
> 
> This is.. not ideal

I'll split the RubyWithDevKit package into `RubyWithDevKit.2.7`, `RubyWithDevKit.3.1`, etc, too so winget would allow you to stay updated on a specific Ruby version

**Comment by OfficialEsco** [comment]
> Is there a tool for AppsAndFeaturesEntries

Currently this is the only automated method [jedieaston/Add-ARPEntries](https://github.com/jedieaston/Add-ARPEntries) by @jedieaston

> I haven't seen anything like that in YamlCreate

I'm not sure if @Trenly got any ideas about how we could implement this, but since we do have Sandbox integration i think it should be possible once we add support for those fields (Trenly is currently™️ rewriting YamlCreate so if its going to be supported its in the new version) (I think this is the branch with the new version [Trenly/Recursion](https://github.com/Trenly/winget-pkgs/tree/Recursion))

Example of how it should look
```
  AppsAndFeaturesEntries:
  - Publisher: Microsoft Corporation
    DisplayName: Microsoft .NET Core Runtime - 3.1.25 (arm64)
    DisplayVersion: 3.1.25.31218
    ProductCode: '{d38317c6-4235-427b-a41c-0709f93f9181}'
```

**Comment by Trenly** [comment]
I do have a few ideas on how to do it. I've even been considering implementing it in YamlCreateV2 instead of waiting until V3 (Recursion) due to the complexity of recursion, and the need to support portables in v2 and eventually zip, at least until v3 is stable.

I think I should be able to get the entries from the Sandbox, but the issue with that is having to go back in and modify the manifests after the sandbox test runs. What I've been considering for now is to just add a prompt for the Primary ARP entry. If the file is an MSI file, much of the information can be pulled from the database; If a .exe has the VersionInfo set, I can recommend that, etc.

**Comment by OfficialEsco** [comment]
Could one of you geniuses run the Add-ARPEntries script over the new manifests? I don't use Hyper-V so i'm kinda left out :(

RubyWithDevKit just got moved too =)
Moves:
* https://github.com/microsoft/winget-pkgs/pull/66736
* https://github.com/microsoft/winget-pkgs/pull/66757
* https://github.com/microsoft/winget-pkgs/pull/66758
* https://github.com/microsoft/winget-pkgs/pull/66760
* https://github.com/microsoft/winget-pkgs/pull/66767
* https://github.com/microsoft/winget-pkgs/pull/66783
* https://github.com/microsoft/winget-pkgs/pull/66832
* https://github.com/microsoft/winget-pkgs/pull/66833
* https://github.com/microsoft/winget-pkgs/pull/66834
* https://github.com/microsoft/winget-pkgs/pull/66835
* https://github.com/microsoft/winget-pkgs/pull/66836
* https://github.com/microsoft/winget-pkgs/pull/66837
* https://github.com/microsoft/winget-pkgs/pull/66838
* https://github.com/microsoft/winget-pkgs/pull/66839
* https://github.com/microsoft/winget-pkgs/pull/66840
* https://github.com/microsoft/winget-pkgs/pull/66841

Removes:
* https://github.com/microsoft/winget-pkgs/pull/66754
* https://github.com/microsoft/winget-pkgs/pull/66755
* https://github.com/microsoft/winget-pkgs/pull/66756
* https://github.com/microsoft/winget-pkgs/pull/66761
* https://github.com/microsoft/winget-pkgs/pull/66762
* https://github.com/microsoft/winget-pkgs/pull/66763
* https://github.com/microsoft/winget-pkgs/pull/66776
* https://github.com/microsoft/winget-pkgs/pull/66777
* https://github.com/microsoft/winget-pkgs/pull/66778

**Comment by russellbanks** [comment]
> Could one of you geniuses run the Add-ARPEntries script over the new manifests? I don't use Hyper-V so i'm kinda left out :(

I've got the Add-ARPEntries script set up so I'll work through those manifests and add the ARP entries

**Comment by russellbanks** [comment]
All ARP entries for both RubyInstallerTeam.Ruby and RubyInstallerTeam.RubyWithDevKit have been added :)
