### ISSUE TITLE
the captcha widget position is always fixed to the webpage, please add an option "position: absolute" for the widget

### ISSUE THREAD

**Issue by jmayes41** [microsoft/winget-pkgs#47753]
the captcha widget position is always fixed to the webpage, please add an option "position: absolute" for the widget
thank you

__Originally posted by @shinebay in https://github.com/hCaptcha/hcaptcha-integrations-list/issues/17__

**Comment by vedantmgoyal2009** [comment]
Not related to Windows Package Manager and Microsoft can't do anything in this regard. Please find the correct repository and post your issue there.
