### ISSUE TITLE
[Package Request]: SQLite Studio

### ISSUE THREAD

**Issue by szyb** [microsoft/winget-pkgs#47856]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Paweł Salawa
Publisher Url: https://sqlitestudio.pl
Package Name: Sqlite Studio
Description: SQLiteStudio is desktop application for browsing and editing SQLite database files. It is aimed for people, who know what SQLite is, or what relational databases are in general.
Package Version:  3.3.3
Installer URL: https://github.com/pawelsalawa/sqlitestudio/releases/download/3.3.3/sqlitestudio-3.3.3.zip

Current Package Identifier (for new versions): -

**Comment by ItzLevvie** [comment]
> I have checked that the installer for this package is not a standalone or portable executable or a .zip file

**Comment by Trenly** [comment]
* Blocked by microsoft/winget-cli#140

**Comment by schlamar** [comment]
There is now an exe installer available: https://github.com/pawelsalawa/sqlitestudio/releases

**Comment by schlamar** [comment]
Created a PR https://github.com/microsoft/winget-pkgs/pull/93750

**Comment by szyb** [comment]
Closing, as package is now available. Thank you @schlamar for your work!
![image](https://user-images.githubusercontent.com/1598139/214071687-d8844c6f-afd5-40d4-8bdd-3e6afb9e99b6.png)
