### ISSUE TITLE
Question: how to handle installers without direct links?

### ISSUE THREAD

**Issue by JudahGabriel** [microsoft/winget-pkgs#48]
As I'm playing with this tool, I notice a great deal of Win32 apps have installers which are not available for direct link. This prevents them from being used with winget.

For example, [IrfanView](https://www.irfanview.com/), a popular image viewer and editor. Its installer is listed on the 3rd party site fosshub.com. Here is the link: https://www.fosshub.com/IrfanView.html?dwl=iview454_x64_setup.exe

**The URL is misleading, however: this isn't the actual installer link, it's a page (with ads) that programmatically triggers downloading the installer.** This way, there is no direct link to the installer, and thus, fosshub gets ad views to subsidize their bandwidth.

Looking at Irfanview's download page, all the installers are on 3rd party sites, and all of them prevent hotlinking like this.

**How can I submit a manifest when the installer doesn't have a direct URL?** Obviously, I could host the installer myself, but my servers couldn't handle e.g. a million downloads. Will Microsoft fetch these installers and mirror them on its own CDN? IMO, this is the best option.

**Comment by chausner** [comment]
> @JudahGabriel in this specific case IrfanView does provide their own hosting, they just hide it under alternate downloads:
> https://www.irfanview.info/files/iview454_x64.zip

Even that link is not a direct download:
```
iwr https://www.irfanview.info/files/iview454_x64.zip

StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
                    <html><head><meta
                     content="text/html; charset=ISO-8859-1"
                     http-equiv="content-type"><title>download: files/iview454_x64.zip</title>…
```
They deliberately got rid of all direct links.

**Comment by Jaiganeshkumaran** [comment]
You can download the file and then check for the actual download link in your browser.

**Comment by lavinir** [comment]
> You can download the file and then check for the actual download link in your browser.

Those are usually dynamically generated links that expire. I'm also looking for a good solution to this but have not found one outside of hosting it myself.

**Comment by JudahGabriel** [comment]
Yep, these are dynamic links that are generated with a special token. 

This is again why winget needs to have its own CDN mirror of installers.
