### ISSUE TITLE
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/winget-pkgs?pullRequest=48632) <br/>All CLA requirements met.

### ISSUE THREAD

**Issue by jmayes41** [microsoft/winget-pkgs#48747]
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/winget-pkgs?pullRequest=48632) <br/>All CLA requirements met.

_Originally posted by @microsoft-cla[bot] in https://github.com/microsoft/winget-pkgs/issues/48632#issuecomment-1049611895_

**Comment by vedantmgoyal2009** [comment]
Please stop spamming the repository.

@denelon please close the issue.
