### ISSUE TITLE
CI timeout but still running

### ISSUE THREAD

**Issue by YadominJinta** [microsoft/winget-pkgs#492]
#279 has running over 24h and the CI timeout
```
5/20/2020 5:00:58 PM
Status: Completed
##[error] Result: Failed
##vso[task.logissue type=error] Operation timed out.
```

But it's still running.

The pr is opened by me, but I don't know why it takes so long time to Installer scan

**Comment by dmex** [comment]
#373 also stuck with CI validation running for more than 17 hours

**Comment by AusNugz** [comment]
#458 is at 18.5 hours on the Manifest Content Validation stage.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/458

**Comment by denelon** [comment]
I've kicked these builds off again.
