### ISSUE TITLE
CI broken, so no new packages are showing up in the install list

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#494]
Started with the PR that added MS edge https://github.com/microsoft/winget-pkgs/commit/b347b1038d2f9784be33cbd8ed3b29476f432595, but any new commit after that also has the same exact error.

`One or more errors occurred. (MakeAppx.EXE is expected (Parameter 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64\MakeAppx.EXE')) MakeAppx.EXE is expected (Parameter 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64\MakeAppx.EXE')`

**Comment by denelon** [comment]
Hey, thanks for pointing this out. We are having an issue with the pipelines. The team is working on it. I'm going to pin this issue and put another one in to create a badge so the status can be updated and visible on the main README.

**Comment by denelon** [comment]
#519 Created to add a pipeline health badge

**Comment by msftrubengu** [comment]
Fixed. Publish pipeline is up and running and the packages got added to winget.
