### ISSUE TITLE
[Package Issue]: Notepad++.Notepad++ silent uninstall bug

### ISSUE THREAD

**Issue by fulopm** [microsoft/winget-pkgs#49601]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Uninstalling with the --silent flag isn't silent, the uninstaller opens, and winget reports a successful uninstall.

### Steps to reproduce

1. Install Notepad++
2. Issue command `winget uninstall Notepad++.Notepad++ --silent`

### Actual behavior

Notepad++ uninstaller opens in foreground, and waits for user input to go trough the casual next-next-finish flow.

### Expected behavior

Notepad++ should uninstall without any user input (except for UAC prompt maybe)

### Environment

```shell
PS > winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.527
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/12369436/156029811-43516aa9-5134-4691-b005-2421c1d8fbeb.png)

**Comment by KaranKad** [comment]
Currently winget is able to silently uninstall nullsoft and inno setup application that register `QuietUninstallString` in Registry and Notepad++ here does not do that, this can either be fixed by requesting developer to add it or once when the feature at https://github.com/microsoft/winget-cli/issues/1885 implemented.
