### ISSUE TITLE
whatsapp installation fails on "Installer hash does not match error"

### ISSUE THREAD

**Issue by uishon** [microsoft/winget-pkgs#4986]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When installing whatsapp, getting "Installer hash does not match error".
# Steps to reproduce

    winget install whatsapp

# Expected behavior
A successful install.

# Actual behavior

    PS C:\Users\uisho> winget install whatsapp
    Found WhatsApp [WhatsApp.WhatsApp]
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    Downloading https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
    ██████████████████████████████   159 MB /  159 MB
    Installer hash does not match; to override this check use --force
    PS C:\Users\uisho>

# Environment

```none
[winget --info]
Windows Package Manager version v0.2.2941 Preview
Windows: Windows.Desktop version v10.0.19042.630
Package: Microsoft.DesktopAppInstaller version version v1.11.2941.0

Any other software?
```

**Comment by KevinLaMS** [comment]
I believe this is now fixed.  https://github.com/microsoft/winget-pkgs/pull/5470

**Comment by ClashTheBunny** [comment]
Does this need to be kicked off more regularly?  I'm now getting errors for this version released around Dec 17:
`WhatsApp Messenger 2.2049.10`

**Comment by ThijsFTW** [comment]
This is again (still?) an issue. 

```
winget upgrade whatsapp
Found WhatsApp [WhatsApp.WhatsApp] Version 2.2245.9
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
  ██████████████████████████████   153 MB /  153 MB
Installer hash does not match; this cannot be overridden when running as admin
```

**Comment by mdanish-kh** [comment]
> This is again (still?) an issue.

Will be fixed once https://github.com/microsoft/winget-pkgs/pull/95141 gets merged
