### ISSUE TITLE
[Fork] Successfully installed with remove: Access is denied

### ISSUE THREAD

**Issue by mloskot** [microsoft/winget-pkgs#5022]
# Brief description of your issue

`winget` says the Fork has been successfully installed, but it throws an error anyway, despite the command runs as Administrator.

# Steps to reproduce

1. Command Prompt > Run as Administrator
2. `winget install Fork.Fork`

# Expected behavior

No error messages.

# Actual behavior

![image](https://user-images.githubusercontent.com/80741/100261067-81ff2700-2f4a-11eb-8cd0-c7de2c95a03e.png)

# Environment

```none
winget --info
Windows Package Manager v0.2.2941 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.630
Package: Microsoft.DesktopAppInstaller v1.11.2941.0

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by yigitemres** [comment]
Installed without any errors.
![WindowsTerminal_WF38R9rW2l](https://user-images.githubusercontent.com/3883354/100336501-50886900-2fe7-11eb-8976-797fe69c2e06.png)

**Comment by mloskot** [comment]
I have just tried to install it in the non-admin terminal and it worked!

![image](https://user-images.githubusercontent.com/80741/100341790-58431000-2fdd-11eb-9524-f6099d1aeadd.png)

I suspect it is related to the similar stories reported in https://github.com/microsoft/winget-cli/issues/189#issuecomment-665791295 and https://github.com/microsoft/winget-cli/issues/428#issuecomment-636406880 and in several more issues.

**Comment by denelon** [comment]
This appears to be resolved. If it's not, feel free to reopen the Issue.
