### ISSUE TITLE
[Package Issue]:  AnyDeskSoftwareGmbH.AnyDesk

### ISSUE THREAD

**Issue by shem-sargent** [microsoft/winget-pkgs#50953]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

AnyDesk 7.0.4 (MSI) Installer hash does not match

### Steps to reproduce

```Powershell
PS> winget install anydesk
```

### Actual behavior

```
Found AnyDesk [AnyDeskSoftwareGmbH.AnyDesk] Version ad 7.0.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.anydesk.com/AnyDesk.msi
  ██████████████████████████████  7.51 MB / 7.51 MB
Installer hash does not match; this cannot be overridden when running as admin
```

After manually downloading https://download.anydesk.com/AnyDesk.msi
```Powershell
PS> get-filehash .\AnyDesk.msi | fl *
Algorithm : SHA256
Hash      : 27BFA9167279579FE90765E70D792F652143D6AE8D76B8EC1EE4F7899CC95F6E
Path      : .\AnyDesk.msi
```

This does not match the hash at https://github.com/microsoft/winget-pkgs/blob/428b66fb37a79fd75ede665833020955e7f95c02/manifests/a/AnyDeskSoftwareGmbH/AnyDesk/ad%207.0.4/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml#L18

### Expected behavior

Matching hashes, normal install progress.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
Ofc they release TWO updates when i take a break/don't check..
Wingetbot also don't seem to know what to do with this Package so it dosn't get auto updated, hopefully we will make it work with auto update once `AppsAndFeaturesEntries` is in stable

**Comment by shem-sargent** [comment]
@OfficialEsco Thank you so much for the quick response.
