### ISSUE TITLE
Failed to install Julia: Access Denied

### ISSUE THREAD

**Issue by azurefx** [microsoft/winget-pkgs#510]
When I use winget to install Julia I get the following error:

```
PS C:\Users\Azure> winget install julia
Found Julia [Julialang.Julia]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://julialang-s3.julialang.org/bin/winnt/x64/1.4/julia-1.4.1-win64.exe
  ██████████████████████████████  64.9 MB / 64.9 MB
Successfully verified installer hash
Installing ...
```

[Error]
[Access Denied.]
[Ok]

```
Installer failed with exit code: 1
```

![AccessDenied](https://user-images.githubusercontent.com/16398460/82489509-5bcc7a80-9b14-11ea-8013-325d4119b4e6.png)

The installer command line is `"C:\Users\Azure\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\Julialang.Julia.1.4.1.exe" /SILENT /LOG="C:\Users\Azure\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\Julialang.Julia.1.4.1.log"`

But I can't find any logs under that directory. Process Monitor indicates that a `CreateFile` call which attempts to open the log file failed with `ACCESS DENIED` error. I tried to run the installer under `~\Download` manually with that command line and it succeeded (with a log created at that destination).

```
PS C:\Users\Azure> winget show julia
Found Julia [Julialang.Julia]
Version: 1.4.1
Publisher: Julialang
AppMoniker: julia
Description: Julia is a high-level, high-performance, dynamic programming language
Homepage: https://julialang.org/
License: MIT
License Url: https://github.com/JuliaLang/julia/blob/master/LICENSE.md
Installer:
  SHA256: 953090cf2a3690791df7550175a8969e8de15cbd84d815975b6495cc884deab6
  Download Url: https://julialang-s3.julialang.org/bin/winnt/x64/1.4/julia-1.4.1-win64.exe
  Type: Inno
PS C:\Users\Azure> winget -v
v0.1.41331 预览
PS C:\Users\Azure> systeminfo /fo csv | ConvertFrom-Csv | select OS*, 系统* | Format-List

OS 名称   : Microsoft Windows 10 专业版
OS 版本   : 10.0.18363 暂缺 Build 18363
OS 制造商  : Microsoft Corporation
OS 配置   : 独立工作站
OS 构建类型 : Multiprocessor Free
系统启动时间  : 2020/5/21, 1:30:26
系统制造商   : LENOVO
系统型号    : 20C5A08JCD
系统类型    : x64-based PC
系统目录    : C:\WINDOWS\system32
系统区域设置  : zh-cn;中文(中国)
```

@davidanthoff

**Comment by LukasNespor** [comment]
Already reported in different repository https://github.com/microsoft/winget-cli/issues/189
