### ISSUE TITLE
Cannot install LibreOffice 0x80190194 : Not found (404).

### ISSUE THREAD

**Issue by ivonenchev** [microsoft/winget-pkgs#51541]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I have tried to install TheDocumentFoundation.LibreOffice. I face issue with description :

An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Steps to reproduce

PS C:\Users\> winget install TheDocumentFoundation.LibreOffice
Found LibreOffice [TheDocumentFoundation.LibreOffice] Version 7.3.0.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.documentfoundation.org/libreoffice/stable/7.3.0/win/x86_64/LibreOffice_7.3.0_Win_x64.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Actual behavior

Downloading https://download.documentfoundation.org/libreoffice/stable/7.3.0/win/x86_64/LibreOffice_7.3.0_Win_x64.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Expected behavior

To install TheDocumentFoundation.LibreOffice success.

### Environment

```shell
PS C:\Users\> winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ivonenchev** [comment]
When I have tried to download the file : https://download.documentfoundation.org/libreoffice/stable/7.3.0/win/x86_64/LibreOffice_7.3.0_Win_x64.msi

I face, that the file is missing. 

The page you requested could not be found
For a list of all mirrors please go to this page: https://download.documentfoundation.org/mirmon/allmirrors.html

**Comment by ifurther** [comment]
I think the problem is libreoffice upgrading this stable version

**Comment by ivonenchev** [comment]
I have already installed the LibreOffice 7.3.1
