### ISSUE TITLE
Can Microsoft.VisualStudio.BuildTools refrain from willfully doing everything it wants to?

### ISSUE THREAD

**Issue by fghzxm** [microsoft/winget-pkgs#5181]
# Brief description of your issue
`Microsoft.VisualStudio.BuildTools` exhibits user-unfriendly behaviors when installing:
1. It instructs the Visual Studio Installer to automatically install all the workloads without an obvious way for the user to intervene, and
2. It automatically reboots the machine without confirmation once installation is finished.
This is unexpected.  I thought it would only install the Installer and then let me decide what to do next.

(I've not tried but I guess other Visual Studio packages also do the same thing?)

# Steps to reproduce
1. You decide to install MSVC and the Windows SDK on your computer, so you run `winget install Microsoft.VisualStudio.BuildTools`.
2. Continue to do your work in other programs, planning to launch the Visual Studio Installer when you've finished one more page in your lab report in Word.

# Expected behavior
You do some work in other programs and the Visual Studio Installer is ready to launch.  Alternatively, the Installer may be launched automatically, or even some popular components installed automatically, but you always reserve ultimate control.

# Actual behavior
A couple minutes pass and the Installer launches itself and starts installing UWP and .NET and every other workload for no explainable reason, you think OK, I'll just remove those workloads and leave only C++ when it's done, and return to Word.
Then a couple more minutes pass and the computer suddenly restarts itself, and you don't have autosave turned on.  Bam.

# Environment

```none
[winget --info]
Windows Package Manager v0.2.3162 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.662
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

Any other software?
Microsoft.VisualStudio.BuildTools 16.6.30128.74
```

**Comment by jedieaston** [comment]
This isn't how the other Visual Studio manifests do it (they only install the required components and pop up the installer to ask about the rest, as you explain). As such, I've updated this manifest to behave the same way in #5216.

**Comment by fghzxm** [comment]
@jedieaston Thank you.  Should I close this issue now, or will the maintainers of this repo do it later?

**Comment by jedieaston** [comment]
@fghzxm It has been merged, so you can close it!
