### ISSUE TITLE
[New Feature]: Provide a workflow to build zip( and so on ) into a exe( and so on).

### ISSUE THREAD

**Issue by CN-traveler** [microsoft/winget-pkgs#51836]
### Description of the new feature/enhancement

Winget is a tool to replace the traditional software installation method, but it can not completely replace the traditional method now. For some applications, there may be no silent installation method, not an executable file, or even no installation and uninstallation program.

So can we build a workflow to help those non-standards applications build a standard application?

> Note: the author is non-native English speaker, so I'm very sorry if you can't understand this issue.

**Comment by Trenly** [comment]
> ### Description of the new feature/enhancement
> Winget is a tool to replace the traditional software installation method, but it can not completely replace the traditional method now. For some applications, there may be no silent installation method, not an executable file, or even no installation and uninstallation program.
> 

These are all features that are planned for future releases - the first two are the ones for no installation/uninstallation, and the third is for when there is no silent installation method
* microsoft/winget-cli#182
* microsoft/winget-cli#2012
* microsoft/winget-cli#823
