### ISSUE TITLE
[Package Request]: JPEGView

### ISSUE THREAD

**Issue by sylikc** [microsoft/winget-pkgs#52201]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Kevin M (sylikc)
Publisher Url: https://github.com/sylikc/jpegview
Package Name: JPEGView
Description: fast and highly configurable viewer/editor for JPEG, BMP, PNG, WEBP, TGA, GIF and TIFF images with a minimal GUI. Basic on-the-fly image processing is provided 
Package Version: 1.0.39.1
Installer URL: https://github.com/sylikc/jpegview/releases/download/v1.0.39.1-wix/JPEGView64_en-us_1.0.39.1.msi https://github.com/sylikc/jpegview/releases/download/v1.0.39.1-wix/JPEGView32_en-us_1.0.39.1.msi

Current Package Identifier (for new versions): N/A

Hi, I am the current maintainer of this GPLv2 app.  I just built a very rudimentary MSI installer, but as I was stepping through the manifest, it's asking for signature 256 and all.... I sort of need help with the manifest and submission.  Thanks!

By the way, do I commit the manifest to the repository?

**Comment by ALazyMeme** [comment]
Personally I found the easiest way to create a package was through the wingetcreate tool. Most of the work is done for you, you just need to input information where it prompts: https://docs.microsoft.com/en-us/windows/package-manager/package/manifest

**Comment by sylikc** [comment]
I started stepping through it, and I installed `wingetcreate` but I was reviewing the example fields in the manifest, and I wouldn't happen to have anything like `SignatureSha256`

**Comment by ItzLevvie** [comment]
> I wouldn't happen to have anything like SignatureSha256

`SignatureSha256` is for MSIX/APPX.

**Comment by sylikc** [comment]
Thanks, btw, ok... I can submit it straight from the `wingetcreate`.  Question: Do I commit the manifest.yaml files to my repository?  Is it considered public?

Ok it auto-submitted https://github.com/microsoft/winget-pkgs/pull/52204

**Comment by sylikc** [comment]
thanks for the help and approval @ItzLevvie
