### ISSUE TITLE
Validation bot requires Content-Length and range GET requests for the installer download

### ISSUE THREAD

**Issue by chausner** [microsoft/winget-pkgs#523]
https://github.com/microsoft/winget-pkgs/pull/503 is currently blocked by the validation bot because it fails with the following error:
````
Error occurred during installer copy from https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.11.2-win64.msi.
 Range GET requests are not supported by the copy source.
````

It seems the webpage does not support range GET requests for the download but the bot requires it. I think the bots need to drop this requirement since not every webserver supports this.

A similar issue currently blocks https://github.com/microsoft/winget-pkgs/pull/47:
````
Error occurred during installer copy from https://www.irfanview.info/files/iview454_x64.zip.
 The Content-Length for the copy source is not specified.
````
In that case, the web server does not specify the file size in the Content-Length header. Again, not every webserver supports this so the bot should be made compatible to those sites.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/91

**Comment by denelon** [comment]
This issue should be resolved now.
