### ISSUE TITLE
Access Denied when installing Git

### ISSUE THREAD

**Issue by chrisvire** [microsoft/winget-pkgs#525]
I tried installing Git.Git (`winget install -h --id Git.git`). It downloaded https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Git-2.26.2-64-bit.exe and at the end I got an "Access Denied" error.

**Comment by KevinLaMS** [comment]
Thanks Chris.  I think this is a duplicate of https://github.com/microsoft/winget-cli/issues/247. Would you mind up voting?

**Comment by jefferai** [comment]
I see that you closed the winget-cli bug. I want to note that out of 3 packages I tried installing, this happened to me for 2 of them (winscp, cpu-z). Not sure if this is specific to these manifests/applications or if this is a deeper bug that belongs in the other repo.

**Comment by jefferai** [comment]
Also probably since you closed the other bug as a duplicate of this one you should remove the duplicate label from here?

**Comment by KevinLaMS** [comment]
Sorry Jefferai  i meant this one.  Duplicate of https://github.com/microsoft/winget-cli/issues/189

**Comment by jefferai** [comment]
To be clear I don't get "unable to write", I get "access denied". Not sure if it's the same or not.

**Comment by cderv** [comment]
I get the same Access Denied issue when the download installer tries to execute.

**Comment by crramirez** [comment]
Still happens in winget 1.0

**Comment by crramirez** [comment]
![image](https://user-images.githubusercontent.com/8397379/119797336-6addc980-beda-11eb-85af-8786275c7060.png)

**Comment by electronic-dk** [comment]
I've had the same issue, but at least I was able to install git from an elevated prompt, unlike discord which does not install from either a user nor an elevated prompt

**Comment by electronic-dk** [comment]
AFAIK, correct git installation requires https://github.com/microsoft/winget-cli/issues/254
(But I'd prefer if git would just install into a user directory if there's no elevation)

**Comment by CreepasCraft** [comment]
I get the same issue with android studio, discord, cpu-z and some others

**Comment by crramirez** [comment]
Trick. It worked for me after I went to Settings->Apps & features searched for App Installer -> Advanced options->Reset

After that I could install things

**Comment by alex-ong** [comment]
`Settings->Apps & features searched for App Installer -> Advanced options->Reset` did the trick for me.
