### ISSUE TITLE
Url validation error

### ISSUE THREAD

**Issue by CN-traveler** [microsoft/winget-pkgs#53509]
Url validation error
- manifests\c\cheat-engine\cheat-engine\7.4.0
  - https://github.com/cheat-engine/cheat-engine/releases/download/7.4/CheatEngine74.exe
    - This URL has previously been reported as Malware to [Microsoft Defender SmartScreen](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
    - If you believe this is in error, you may [file a report](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL2NoZWF0LWVuZ2luZS9jaGVhdC1lbmdpbmUvcmVsZWFzZXMvZG93bmxvYWQvNy40L0NoZWF0RW5naW5lNzQuZXhl)

_Originally posted by @wingetbot in https://github.com/microsoft/winget-pkgs/issues/52246#issuecomment-1065894875_

**Comment by CN-traveler** [comment]
How can I solve this problem?

**Comment by Trenly** [comment]
You can report the URL as not malware in the link provided. After that you just have to wait and see if the SmartScreen team unblocks it. Until they unblock it, there isn’t anything you can do

**Comment by CN-traveler** [comment]
> You can report the URL as not malware in the link provided. After that you just have to wait and see if the SmartScreen team unblocks it. Until they unblock it, there isn’t anything you can do

Thank you!
