### ISSUE TITLE
Comparison to conda

### ISSUE THREAD

**Issue by Hoeze** [microsoft/winget-pkgs#538]
Hi, I wonder how this compares to the package manager `conda`:
- Does it allow installing multiple versions of the same package?
=> conda: indirect, using different environments
- How does it resolve dependencies? Are there heuristics to solve the exponential complexity problem of dependency graphs?
=> conda: yes
- Will it be cross-platform?
=> conda: yes

Feel free to close this issue if it is not appropriate.

**Comment by WSLUser** [comment]
> Does it allow installing multiple versions of the same package?
> => conda: indirect, using different environments

yes but requires seperate manifests. There is only one environment: the OS itself. This isn't for a programming language but for an OS similar to chocolately.

> Will it be cross-platform?

 
Why? This is for Windows. Linux and BSD don't require another package manager. Mac has brew even though it's not supported by Apple.
