### ISSUE TITLE
Is the code for the wingetbot available anywhere?

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#5418]
I was wondering if the code for the wingetbot will ever be made available for building our own pipelines. Once self-hosted repositories are a thing, I'd like to automate the updating of line of business apps and I think it would be handy as a starting point. 

Should I starting rolling my own or is this a possibility?

**Comment by denelon** [comment]
There are a few different services supporting the system today. We're planning on open sourcing, but we have some additional changes that need to be made in order to do that. One of the components is an internal tool, and we haven't seen the timeline for that becoming open source. There is also a REST API under development that should make it much easier to host your own source for packages. How would you see submissions in your scenario? Would it be centrally maintained by an IT department, or would employees be able to submit any app they like?

**Comment by jedieaston** [comment]
I would prefer that IT managed it primarily, but through a Git repo just like this. We get a new app, commit a manifest for it to a repo and then it can be consumed over the REST API. For heavily updated software like Chrome, something like the bot that could automatically open a pull request for an update would be handy for this workflow. Of course if user wanted to commit to the repo that'd be fine as well, but I think that's more of an organizational policy thing and not as much a technical problem winget needs to solve.

**Comment by denelon** [comment]
We're building a tool that will help build manifests and submit PRs. It will be open source.

**Comment by jedieaston** [comment]
Hey @msftbot, it isn't marked as requiring author feedback! Please don't close it.

**Comment by jedieaston** [comment]
Hey @msftbot, it isn't marked as requiring author feedback! Please don't close it.

**Comment by KevinLaMS** [comment]
Thanks for raising the issue.  The bot will not close it.

**Comment by JanDeDobbeleer** [comment]
> We're building a tool that will help build manifests and submit PRs. It will be open source.

@denelon any view on a timeline? I want to have my tool in the community repo but I refuse to manually update the manifest due to continuous delivery everywhere else.

**Comment by denelon** [comment]
@JanDeDobbeleer we're doing some internal testing with the tools now. We have a big change coming with a new manifest schema and partitioning files on GitHub to avoid display issues. The team is hard at work to validate everything and update to the new draft schema. We're hoping to get this tool out in March 2021.

**Comment by JanDeDobbeleer** [comment]
@denelon I appreciate you sharing that information SO MUCH, thank you! Looking forward to it 🙏🏻

**Comment by JanDeDobbeleer** [comment]
@denelon hope is rising as we near the end of March 😬 Any update on the timings?

**Comment by denelon** [comment]
@JanDeDobbeleer we've done some internal testing with the manifest creation tool against the 0.1 manifest syntax. That has gone fairly well, but we decided to hold off until the new v1.0 manifest schema support is in place. We're doing an internal bug bash next week. All of the work for our internal requirements to ship a product is starting to wrap up. I was targeting May 1st, but I am not super confident we'll hit that date right now. I'm hoping we aren't delayed more than a couple of weeks. I know it's not what you wanted to see, but that's where we stand. I've got the Public Service Announcement pinned as an issue in both repositories, and there are links to the new schema and the draft pull request for the specification and JSON schemas.

**Comment by denelon** [comment]
My apologies for not updating this issue sooner. It's a bit tough to cross link threads. I'm going to mention a few Issues here to help cross link things better.

https://github.com/microsoft/winget-pkgs/issues/8900 - PSA: New Manifest Schema
https://github.com/microsoft/winget-cli/issues/803 - PSA: New Manifest Schema
https://github.com/microsoft/winget-cli/issues/157 - Create manifest wizard

**Comment by JanDeDobbeleer** [comment]
@denelon thanks. The update was exactly what I needed to know so thx. Not looking at putting more pressure on all of this, now I know what I can answer to people asking for winget support.

**Comment by denelon** [comment]
Everything takes longer than you plan [even when you plan for that](https://en.wikipedia.org/wiki/Hofstadter%27s_law). The 0.1 preview of the tool has been tested, and we're very close to the release (think days, not weeks). I've even used the tool to submit a couple of manifests here.
