### ISSUE TITLE
Reported installed version of OpenMedia.4KVideoDownloader is incorrect

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-pkgs#54507]
### Brief description of your issue

With the latest version of "4k Video Downloader" (`OpenMedia.4KVideoDownloader`) installed, i.e. version 4.20.0.4740, `winget` tells me I have version 4.19.4.4720 installed, and that there's an upgrade available.

### Steps to reproduce

(Probably?) Install version 4.19.4.4720 of "4k Video Downloader", and upgrade to 4.20.0.4740.

Then invoke `winget upgrade`.

### Expected behavior

"4k Video Downloader" should not be listed by `winget upgrade`, and `winget list` should list it as version 4.20.0.4740

### Actual behavior

`winget upgrade` reports:

````
PS❯  winget upgrade | sls -raw 'Name|---|4k'
Name                                            Id                           Version        Available      Source
-----------------------------------------------------------------------------------------------------------------
4K Video Downloader                             OpenMedia.4KVideoDownloader  4.19.4.4720    4.20.0.4740    winget
````

Note: this is probably not `winget`'s fault -- kind of. The app shows up twice under the `Uninstall` tree:
[HKEY_LOCAL_MACHINE__SOFTWARE__Microsoft__Windows__CurrentVersion__Uninstall_OpenMedia.4KVideoDownloader_202203101546.zip](https://github.com/microsoft/winget-cli-restsource/files/8224297/HKEY_LOCAL_MACHINE__SOFTWARE__Microsoft__Windows__CurrentVersion__Uninstall_OpenMedia.4KVideoDownloader_202203101546.zip)
 

### Environment

```shell
PS❯  winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.527
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows <REDACTED>re Terms https://www.microsoft.com/en-us/<REDACTED>redocs/terms-of-sale

PS❯  Get-WindowsVersionViaWinRT.ps1

Key           Value
---           -----
OSVersionFull 10.0.22000.527.amd64fre.co_release.210604-1628
FlightRing    Retail
App           pwsh.exe
AppVer        7.2.1.500
DeviceFamily  Windows.Desktop
```

**Comment by OfficialEsco** [comment]
No?
```
PS M:\> winget install OpenMedia.4KVideoDownloader -v 4.19.4.4720
Found 4K Video Downloader [OpenMedia.4KVideoDownloader] Version 4.19.4.4720
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.4kdownload.com/app/4kvideodownloader_4.19.4_x64.msi
  ██████████████████████████████  90.4 MB / 90.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget list
Name                                  Id                                     Version                      Available   Source
----------------------------------------------------------------------------------------------------------------------------
4K Video Downloader                   OpenMedia.4KVideoDownloader            4.19.4.4720                  4.20.0.4740 winget

PS M:\> winget upgrade OpenMedia.4KVideoDownloader
Found 4K Video Downloader [OpenMedia.4KVideoDownloader] Version 4.20.0.4740
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.4kdownload.com/app/4kvideodownloader_4.20.0_x64.msi
  ██████████████████████████████  90.6 MB / 90.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget list
Name                                   Id                                      Version                      Available Source
----------------------------------------------------------------------------------------------------------------------------
4K Video Downloader                    OpenMedia.4KVideoDownloader             4.20.0.4740                            winget
```

Note: you cannot install both versions (exe and msi)

Manually installed the 4.19.4 exe version

```
PS M:\> winget list
Name                                  Id                                     Version                      Available   Source
----------------------------------------------------------------------------------------------------------------------------
4K Video Downloader                   OpenMedia.4KVideoDownloader            4.19.4.4720                  4.20.0.4740 winget

PS M:\> winget upgrade OpenMedia.4KVideoDownloader
Found 4K Video Downloader [OpenMedia.4KVideoDownloader] Version 4.20.0.4740
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.4kdownload.com/app/4kvideodownloader_4.20.0_x64_online.exe
  ██████████████████████████████   863 KB /  863 KB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget list
Name                                   Id                                      Version                      Available Source
----------------------------------------------------------------------------------------------------------------------------
4K Video Downloader                    OpenMedia.4KVideoDownloader             4.20.0.4740                            winget
```

Both 4.19.4 and 4.20.0 is installed at the same point at one time, however the installer cleans up the previous version, this seems to be something on your side.

HOWEVER, my registry key is `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{59b7ab8a-bcd1-45ce-a82b-a50ee09d0b53}`

Something with your installer might have gone wrong at some point, i would advice you to reinstall `4K Video Downloader`

**Comment by sba923** [comment]
I've been digging and as I said in my original post the issue indeed lies in the installer having let quite some garbage in the registry. Even the Settings app thinks there are two apps installed:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/12860484/159160347-dc496f26-c775-4efb-84a5-ef42693ff743.png">

Once I've uninstalled both "copies" of the app and reinstalled it via `winget` (what else 😝) the situation's back to normal.

Note that such installer issues are not that uncommon, I also had a system where the registry contained entries for both VLC 3.0.12 and 3.0.16 (but in _that_ case neither `winget` nor was showing the app twice), so I was able to uninstall it *twice* with `winget uninstall`!

**Comment by OfficialEsco** [comment]
Do we know of installers which do not clean up the previous version which is why we can add this field to the manifest: `UpgradeBehavior: uninstallPrevious`

However as i said and tested, 4k Video Downloader does clean up the previous version, so i believe this is a issue between your PC and the Installer (since it also happened with VLC), my best guess is that it gets terminated too early or the cleanup part process errors out or gets permission denied.

btw, the uninstall registry strings and the Settings app/Add or Remove Programs are tied together (which WinGet uses for matching)

**Comment by sba923** [comment]
I've faced tons of issues with 4k Video Downloader's auto-update features over the years, ranging from failed upgrades ("you have to download the installer from the website and upgrade that way") to issues when multiple accounts have the app installed on the same machine.

The VLC issue was probably created quite some time in the past, when I upgraded from 3.0.12 to whatever that release had told me to upgrade too.

I'll keep monitoring the consistency of `winget`'s behavior with the Windows built-in mechanisms (Settings, Control Panel Add/Remove Programs).

FWIW I've been managing what apps are installed on which PCs in the household with a set of scripts built on top of   
[Get-InstalledApp.zip](https://github.com/microsoft/winget-pkgs/files/8311212/Get-InstalledApp.zip), that keep a history of that script's output in CSV files for each system. Among other use cases, I'm using this to determine if all PCs have the same version of common apps installed. So I should even be able to determine when VLC and 4k Video Downloader got "duplicated" on that particular system, and whether the situation ever existed, even temporarily, on other systems.

**Comment by sba923** [comment]
I've faced tons of issues with 4k Video Downloader's auto-update features over the years, ranging from failed upgrades ("you have to download the installer from the website and upgrade that way") to issues when multiple accounts have the app installed on the same machine.

The VLC issue was probably created quite some time in the past, when I upgraded from 3.0.12 to whatever that release had told me to upgrade too.

I'll keep monitoring the consistency of `winget`'s behavior with the Windows built-in mechanisms (Settings, Control Panel Add/Remove Programs).

FWIW I've been managing what apps are installed on which PCs in the household with a set of scripts built on top of   
[Get-InstalledApp.zip](https://github.com/microsoft/winget-pkgs/files/8311212/Get-InstalledApp.zip), that keep a history of that script's output in CSV files for each system. So I should even be able to determine when VLC got "duplicated" on that particular system.

**Comment by OfficialEsco** [comment]
Wops forgot to reply, would it be bad if we made winget always uninstall 4k Video Downloader before installing the new version? Since you've experienced the issues with recent versions its probably not fixed...

The way WinGet works is simply
1. Downloads the installer from the provided URL
2. Installs the Software with the silent switches

So its exactly like you downloading the exe/msi from their website.
So if their Installer is borked we cannot do anything else than remove the previous version and install on a clean slate.
I would probably recommend you to use the MSI because the EXE is a Online installer which downloads the exe which would work like the Auto Updater.

**Comment by sba923** [comment]
Just ran the self-upgrade process. Now the app's about box reports version `4.20.1.4780`, but `winget list` still reports version `4.20.0.4740`.

This is consistent with Settings / Apps & features:

![image](https://user-images.githubusercontent.com/12860484/159776850-181f342b-b646-4eb6-b1d5-1df7cf5bbd12.png)


The registry contains: 
[4kVideoDownloaderRegistryEntries202203232007.csv](https://github.com/microsoft/winget-pkgs/files/8335850/4kVideoDownloaderRegistryEntries202203232007.csv)

**Comment by sba923** [comment]
Note that the issue with running an uninstall followed by an install might be that the configuration of the app would be different after the whole operation (depending on what the uninstaller does or doesn't remove).

BTW upgrading apps with `winget` often results in desktop icons being added that were not present before the upgrade, but that's another story altogether 😉.

**Comment by OfficialEsco** [comment]
> Sometimes this fails, and one has to download the EXE from their website 'cos that's what they offer by default. And recently what you get (from https://www.4kdownload.com/thanks-for-downloading?source=videodownloader) is even an "online installer" that downloads the actual installer under the hood.

Yes, thats why i said you should try the MSI instead, these are our urls
https://github.com/microsoft/winget-pkgs/blob/9df157affefa0fe45b63db5c2b35a3e55b03452f/manifests/o/OpenMedia/4KVideoDownloader/4.20.0.4740/OpenMedia.4KVideoDownloader.installer.yaml#L13-L31
The MSI's are the full installer and i very much doubt it will have any of the issues you are experiencing 

> Note that the issue with running an uninstall followed by an install might be that the configuration of the app would be different after the whole operation (depending on what the uninstaller does or doesn't remove).

Yeah that is why this should be a last resort and the people who use the software should warn us if it does

> BTW upgrading apps with winget often results in desktop icons being added that were not present before the upgrade, but that's another story altogether 😉.

Yeah.. That is because it just runs the silent switches, we could add a custom switch (install only) or a upgrade switch (should be used if the Software got a switch for upgrade instead of using UninstallPrevious)

I guess we should request a field for StartMenuShortcut, DesktopShortcut and any other switch you can think off at [winget-cli](https://github.com/microsoft/winget-cli/issues)

**Comment by sba923** [comment]
Using the MSI will only solve the issue if the self-upgrade within the app installed via MSI doesn't exhibit the same registry problem / doesn't use the EXE to self-upgrade.

I need to experiment by uninstalling, installing an old version via MSI, and then perform a self-upgrade.

**Comment by OfficialEsco** [comment]
Glhf https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KVideoDownloader

@KaranKad are you a 4k Video Download user? Are you using the burn or msi version and have you encountered this issue before?

**Comment by KaranKad** [comment]
> @KaranKad are you a 4k Video Download user? Are you using the burn or msi version and have you encountered this issue before?

Cant say because I don't use it anymore, will try testing it tho.

**Comment by sba923** [comment]
I've performed the following test:

1. uninstalled 4k Video Downloader via `winget` (even more than once JIC 😝)
2. manually cleaned up everything in the registry related to it (_very_ tedious)
3. installed 4k Video Downloader version `4.20.0.4740` via `winget` (so, using the MSI)
4. launched the app (had to re-activate / enter license key due to #2)
5. let the app perform its self-upgrade process

Now the app reports it's version `4.20.1.4780`, and `winget` and the Settings app report the same thing.

I could in theory run another test where #3 would be replaced by "install the app via its EXE installer."

The key is probably #2.

To be safe, now I have to run those steps on all my PCs 😭.

**Comment by OfficialEsco** [comment]
> 2. manually cleaned up everything in the registry related to it (very tedious)

Hi there, RevoUninstaller would like a word with you.
Or `BCUninstaller`/`Bulk Crap Uninstaller` if you'd like something Open-Source (but unmaintained unfortunately..)

**Comment by sba923** [comment]
> > 2. manually cleaned up everything in the registry related to it (very tedious)
> 
> Hi there, RevoUninstaller would like a word with you. Or `BCUninstaller`/`Bulk Crap Uninstaller` if you'd like something Open-Source (but unmaintained unfortunately..)

Thanks for the hints. But I like to be in control, I don't know what these tools actually do. They must have some assumptions about what they can, cannot, should or should not remove, and in the context of the kind of mess I'm experiencing, how can I trust they will not remove anything they shouldn't remove, or leave behind something they should remove?

**Comment by OfficialEsco** [comment]
You can see/choose what it removes, in theory they watch what the uninstaller does then searches for any relevant information (+ the information its told to look for if its a tricky software), but since you already know what to look for this should be perfect for you.

Test it in Sandbox/VM ;)

**Comment by sba923** [comment]
The current situation is that the app's auto-updates itself, but most of the time `winget` doesn't update it. Must be that they don't keep their manifest up to date...
