### ISSUE TITLE
[Package Issue]: 7zip.7zip

### ISSUE THREAD

**Issue by ktos** [microsoft/winget-pkgs#54531]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget seems to prefer x64 version of 7-zip, instead of ARM64 on ARM64-based PC. The manifest declares ARM64 installer path in `Installers - Architecture: arm64`, but not in `Installers - InstallerLocale` key in YAML, so the problem may be in here.

Similarly, `winget show 7zip.7zip` shows info about x64 package, while ARM64 is available.

The installer works correctly when specifying architecture, e.g. `winget install 7zip.7zip -a arm64`.

### Steps to reproduce

Run basic (default) installation of 7-zip on ARM64-based PC, without specifying architecture, e.g. `winget install 7zip.7zip`.

### Actual behavior

x64 installer is being downloaded and executed.

### Expected behavior

ARM64 installer should be preferred on ARM64-based PC.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

```
E:\_t>winget show 7zip.7zip
Found 7-Zip [7zip.7zip]
Version: 21.07
Publisher: Igor Pavlov
Publisher Url: https://www.7-zip.org
Publisher Support Url: https://www.7-zip.org/support.html
Author: Igor Pavlov
Moniker: 7zip
Description: Free and open source file archiver with a high compression ratio.
Homepage: https://www.7-zip.org
License: GNU LGPL
License Url: https://www.7-zip.org/license.txt
Copyright: Copyright (C) 1999-2021 Igor Pavlov.
Copyright Url: https://www.7-zip.org/license.txt
Installer:
  Type: wix
  Locale: en-US
  Download Url: https://www.7-zip.org/a/7z2107-x64.msi
  SHA256: 5447c9ac39c48f1bc7c88359b0520396a8c9707b307c107236a93a68e6fd3eb6
  Release Date: 2021-12-26

E:\_t>systeminfo | grep -i arm
System Type:               ARM64-based PC
                           [01]: ARMv8 (64-bit) Family 8 Model 805 Revision D0E Qualcomm Technologies Inc ~2995 Mhz
```

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/blob/3475c20456e30c6c18c8d890b111ab6bf44da579/manifests/7/7zip/7zip/21.07/7zip.7zip.installer.yaml#L56-L88

@denelon the issue seems to be that it forcefully prefers MSI over EXE instead of ARM64 available installer > MSI > EXE

**Comment by JohnMcPMS** [comment]
You can actually see the decision process in the `--verbose-logs` (from my x64 machine so not exactly the same):
```
2022-03-16 11:03:28.462 [CLI ] Starting installer selection.
2022-03-16 11:03:28.462 [CLI ] Installer [X64,nullsoft,Machine,] is current best choice
2022-03-16 11:03:28.462 [CLI ] Installer [X64,nullsoft,Machine,] is better than [X86,nullsoft,Machine,] due to: Machine Architecture
2022-03-16 11:03:28.462 [CLI ] Installer [Arm64,nullsoft,Machine,] not applicable: Machine is not compatible with Arm64
2022-03-16 11:03:28.462 [CLI ] Installer [X86,wix,Machine,en-US] is better than [X64,nullsoft,Machine,] due to: Locale
2022-03-16 11:03:28.462 [CLI ] Installer [X86,wix,Machine,en-US] is current best choice
2022-03-16 11:03:28.462 [CLI ] Installer [X64,wix,Machine,en-US] is better than [X86,wix,Machine,en-US] due to: Machine Architecture
2022-03-16 11:03:28.462 [CLI ] Installer [X64,wix,Machine,en-US] is current best choice
2022-03-16 11:03:28.462 [CLI ] Completed installer selection.
```
I think that the issue is that because the `InstallerLocale` is actually set for the MSI, we prefer it over the neutral locale of the EXE options (when it matches).  You can see that on the line where `X86` is chosen over `X64` due to `Locale` (`X64` is then chosen as better later on):
```
2022-03-16 11:03:28.462 [CLI ] Installer [X86,wix,Machine,en-US] is better than [X64,nullsoft,Machine,] due to: Locale
```
I remember having a discussion with @yao-msft about this; the expectation was that being able to understand the language in the package was more important than matching the architecture, so long as the architecture was compatible with the system.

**Comment by denelon** [comment]
Would you mind commenting on the issue with something like that to add a bit more clarity?
________________________________
