### ISSUE TITLE
P.S.A. Pipelines Paused

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#54601]
We've encountered a couple of throughput limits. We hit the GitHub rate limits as well as some issues with Azure DevOps pipelines.

The pipelines are paused as we manually throttle them to get PRs validated. We're working on better mechanisms to handle the high-capacity periods.

**Comment by Jaifroid** [comment]
Any updates? [My PR](https://github.com/microsoft/winget-pkgs/pull/54541) is failing Installer Validation with what it says is a Binary Validation Error, even though the manifest installs fine locally and there is no virus scanner warning on my fully up-to-date PC using Windows Defender. I'm suspecting pipeline failure rather than a problem with the package...

**Comment by numeredev** [comment]
@Jaifroid I think, most of us experience this behavior right now. Let's give @denelon and his team some time to fix the pipeline issues.

**Comment by Jaifroid** [comment]
OK, thanks @numeredev. Will do.

**Comment by denelon** [comment]
Quick update: We implemented code to deal with the underlying infrastructure problems. We were validating our code and GitHub was having issues at the same time with their APIs. They seem to have subsided so we're moving ahead quickly to get this rolled out. We will manually trigger any builds that failed during this time once the services are back up and running at full capacity. We have been manually throttling the services to keep PRs flowing, and we will ensure none of the open PRs get missed.

**Comment by gnpaone** [comment]
> Quick update: We implemented code to deal with the underlying infrastructure problems. We were validating our code and GitHub was having issues at the same time with their APIs. They seem to have subsided so we're moving ahead quickly to get this rolled out. We will manually trigger any builds that failed during this time once the services are back up and running at full capacity. We have been manually throttling the services to keep PRs flowing, and we will ensure none of the open PRs get missed.

Hi @denelon, is the pipeline issue solved? There's lots of PR backlogs (including mine)

**Comment by denelon** [comment]
@gnpaone,
They are not completely solved yet. We will leave this issue open until they are. The team is still working on parallel efforts to manually trigger runs (and watch logs/alerts for failures) and to work on automating the fixes/optimizations.

**Comment by denelon** [comment]
We've turned normal validation on. Any remaining PRs will be picked up by our "PR cleaner".
