### ISSUE TITLE
Installer failed while installing AnyDesk and Microsoft Teams

### ISSUE THREAD

**Issue by sanamhub** [microsoft/winget-pkgs#54647]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer failed while installing AnyDesk and Microsoft Teams

AnyDesk: `AnyDeskSoftwareGmbH.AnyDesk`

Microsoft Teams: `Microsoft.Teams`

### Steps to reproduce

1. Open terminal
2. Type `winget upgrade --all`
3. Hit enter

### Actual behavior

Errors while installing some packages (screenshot below)

![image](https://user-images.githubusercontent.com/31341013/158744551-cb75a470-3fa7-4770-8f64-c22c5fa79cca.png)

![image](https://user-images.githubusercontent.com/31341013/158744592-5572cf1b-c7de-45f3-aea2-b54dd528e2db.png)

### Expected behavior

Install success

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```


### Screenshots and Logs

_No response_

**Comment by OfficialEsco** [comment]
AnyDesk requires Powershell to be run as Administrator, this is already implemented in the Manifest but winget-cli does not know what to do with it yet.
https://github.com/microsoft/winget-pkgs/blob/a133a9a63e1c16c3f50688679b8f44f24eb82636/manifests/a/AnyDeskSoftwareGmbH/AnyDesk/ad%207.0.6/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml#L38

Microsoft Teams cooould still have the issues with the Machine-Wide and Per user Installation (the logs as requested would be helpful.)

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your problem still persists. 

If additional problems persist, it would be extremely helpful if a new issue could be opened. Thanks!

###### Close with reason: Stale;
