### ISSUE TITLE
How should we write silent arguments for 7zip self extractors?

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#5485]
Some softwares are released as 7zip self extractors, such as utaformatix(#5335), flashpointInfinity(#4961). 
Take utaformatix as an example. I tried to use 
```
-y -o"C:\Program Files\utaformatix"
```
as silent arguments. However, this needs administrator privilege. So what is the best way to add a 7zip self extractor into the winget repo?

**Comment by denelon** [comment]
I'm not sure if we need to prompt for elevation on this one, or if we need another flag in the manifest to indicate that it requires administrative privileges for silent install. What are your thoughts @oxygen-dioxide?

**Comment by oxygen-dioxide** [comment]
I think we should find a path where administrator privilege isn't needed.
