### ISSUE TITLE
Moderators should have a way to close PRs.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#55005]
### Description of the new feature/enhancement

Continuing the theme of https://github.com/microsoft/winget-pkgs/issues/35372 (which I hear is very close!), Moderators should have a way to request wingetbot/msftbot close a PR given a reason. Many times we close PRs by marking them as being "resolved" by another PR, which just [causes confusion](https://github.com/microsoft/winget-pkgs/pull/54700#issuecomment-1072990783) unless everyone is aware of the workaround.

There may be a way to do this via a GitHub Team (delegating the power to close PRs), but I don't know if you can without consuming licenses (which is obviously a no-go for outside people). I know that was talked about at one stage, but I guess it was dropped. As such, I think the bot should just take care of it on our behalf.

### Proposed technical implementation details (optional)

"@wingetbot close" should close a PR. 

Preferably, it would refuse to do so if we hadn't made any other comments on the PR (or if there was no other text in the comment with the command), forcing us to explain why it was being closed. Although we're usually good about explaining, having a little enforcement wouldn't be a bad thing.

**Comment by vedantmgoyal2009** [comment]
* Just putting my issue here: https://github.com/microsoft/winget-pkgs/issues/35373

**Comment by Trenly** [comment]
Now that config as code has been released, it should be trivial to do this with MSFTbot using similar logic to the duplicate issues. 

Not only does closing PR's apply to some of the stale wingetbot PR's, but also some for known issues where new contributors submit PR's for versions which we know have issues or have been removed for certain reasons. If its okay with @denelon and the team, I'd be happy to take a look into writing up the config for this

**Comment by Trenly** [comment]
Moderators can now close PRs using:
```
Close with reason: <reason>;
```
Note the semicolon is necessary as a terminating character
