### ISSUE TITLE
[New package version]: Elastic.Elasticsearch version 8+

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#55431]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Elastic
Package Name: Elasticsearch
Package Url: https://www.elastic.co/elasticsearch/
Package Version: `7.17.0`, `7.17.1`, `8.0.0`, `8.0.1`, `8.1.0`, `8.1.1` + later versions
Latest versions: https://github.com/elastic/elasticsearch/tags

Current Package Identifier: [Elastic.Elasticsearch](https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/Elastic/Elasticsearch)

-----

I'm creating this issue for awareness.

I believe Elasticsearch have stopped releasing msi's, but if anyone knows of a direct link that would be great
The latest url we have is https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3.msi

**Comment by jedieaston** [comment]
> Deprecated in 7.16.2.
> After 7.16.2, we’ll no longer release Windows MSI installer packages for Elasticsearch. To install Elasticsearch on Windows, use the [.zip archive package](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/zip-windows.html) instead.


https://www.elastic.co/guide/en/elasticsearch/reference/7.16/windows.html

This has been getting a bit more common lately, I think a lot of places that build for multiple platforms have issues working building MSIs into their build infrastructure, and it's something to keep up with that many clients don't care enough about (they'll just run it on Linux or via Docker Desktop). I've seen rants about how hard it is to build Windows installers on hn and other places, and I don't think msix is making it any easier.

**Comment by OfficialEsco** [comment]
@denelon can you tag this with Zip?
I'm guessing we can support this later by extracting the folder to a specific location?
Not sure how it will work without a ARP table to work with tho

**Comment by jedieaston** [comment]
I don't think it will be possible to upgrade to the zip version from the msi version (or even something you'd want to do, jumping to a major version of Elasticsearch is usually something to plan around). I think winget will generate a new ARP value for the zip version, based on the spec.

**Comment by Trenly** [comment]
The zip file only contains a few non-executable files and some .bat files
[Policy] Scripted Application
