### ISSUE TITLE
WinGetBot closing and reopening PRs instead of checking for existing 

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#55436]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Currently we have a issue where the Bitwig webpage certificate is outdated which means wingetbot fails to download the installer, before it would make a PR and we could leave it open so it didn't create more PRs, however after the tweaks it does not.

Another issue with this is the waiver system which requires the Administrator to tell the bot to automatically create it.
For example https://github.com/microsoft/winget-pkgs/pull/54677 have been open for 6 days because we're waiting for waivers, in the past we would add resolves or closes in the PR body to close the PR.
However in the meantime wingetbot have closed and created these PRs
* #54813
* #54986
* #55077
* #55299
* #55415

Instead of checking if there already is a PR or using its own open PR

### Steps to reproduce

null

### Actual behavior

wingetbot creates multiple PRs

### Expected behavior

Check if there is a open PR, if not create a PR
Possibly check if the labels are OK on the open PR, if not rerun the CURRENT OPEN PR.

### Environment

```shell
null
```

**Comment by vedantmgoyal2009** [comment]
* https://github.com/vedantmgoyal2009/vedantmgoyal2009/pull/348

Wouldn't it be better if we have some commands like @dependabot to manage this behavior?

**Comment by Trenly** [comment]
@officialesco - I haven't seen this behavior in a while; Do you think it's safe to call this closed?
