### ISSUE TITLE
WinGetBot reruning PRs in good state

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#55485]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Since the wingetbot buff it have started to rerun PRs which is in a good state
Example PRs:
* #55473
* #55468
* #55469
* #55474

### Steps to reproduce

Have a PR open with only the `Validation-Completed` and `Azure-Pipeline-Passed` label
Wait for the bot cleaner to pass and rerun the PRs

### Actual behavior

Reruns the PRs.

### Expected behavior

Leave em alone.

### Environment

```shell
null
```

**Comment by vedantmgoyal2009** [comment]
@officialesco I can confirm this no longer happens now.

cc @denelon

**Comment by OfficialEsco** [comment]
You're right, we've not seen it in a while
