### ISSUE TITLE
KDE.KDEConnect need update

### ISSUE THREAD

**Issue by wateroader** [microsoft/winget-pkgs#5548]
KDE.KDEConnect cannot install and need update new version

**Comment by pbrandstetter** [comment]
Could you please provide the error shown by winget-cli?
We already merged #5760 with the most recent version of KDEConnect, does this fix your problem?

**Comment by Trenly** [comment]
@denelon I believe #19444 resolves this issue

**Comment by dtantono** [comment]
I think the url is changed again https://download.kde.org/unstable/kdeconnect/win64-pre-20.08/
