### ISSUE TITLE
[Package Request]: DU Meter

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#55573]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Hagel Technologies Ltd.
Publisher Url: https://www.hageltech.com/about/us
Package Name: DU Meter
Description: DU Meter is an Internet usage monitor for your computer. It shows real-time graphs and can create reports and alerts based on your downloads and uploads.
Package Version: 8.01
Installer URL: https://dl.hageltech.com/DUMeter-Install.exe

Current Package Identifier (for new versions):

**Comment by TechnicaVivunt** [comment]
#55736

**Comment by TechnicaVivunt** [comment]
Du Meter has been added/merged as of yesterday.

**Comment by Trenly** [comment]
Close with reason: Added and merged;
