### ISSUE TITLE
[Package Issue]: Fork.Fork upgrade behaves as a fresh install

### ISSUE THREAD

**Issue by Zageron** [microsoft/winget-pkgs#55611]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Upgrading package results in a clean install with all workspace and application settings destroyed.

### Steps to reproduce

Run winget upgrade fork.fork

### Actual behavior

"Fresh Install"

### Expected behavior

Upgrade version while keeping all settings.

### Environment

```shell
PS L:\> winget --info
Windows Package Manager (Preview) v1.3.431-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1586
Package: Microsoft.DesktopAppInstaller v1.18.431.0
```

**Comment by OfficialEsco** [comment]
That is a issue with the Fork installer and there is nothing we can do about it.
It does the same immediately after running the exe https://git-fork.com/update/win/ForkInstaller.exe

**Comment by Zageron** [comment]
Thank you, I will follow up with them and see what they say. (They're who sent me here in the first place haha.)

**Comment by OfficialEsco** [comment]
> Thank you, I will follow up with them and see what they say. (They're who sent me here in the first place haha.)

Of course, well, i took a peek at Chocolatey and they use the same setup as us, and as i said it just happens when you run the exe installer, so the least they can give us is a upgrade switch command

**Comment by cwatzl** [comment]
Has there been any response to this from the Fork devs? This has just happened to me again, it's really annoying.

**Comment by Zageron** [comment]
> Has there been any response to this from the Fork devs? This has just happened to me again, it's really annoying.

I emailed them immediately after this and their response was to "please use the update functionality within the app", with no other response.

**Comment by Zageron** [comment]
The alternate solution is pinning, which I believe has an open issue / feature request.

**Comment by cwatzl** [comment]
Well, that's not great. I sent them a mail too. Maybe if more customers complain about this we get a better shot at a real solution.

**Comment by cwatzl** [comment]
Fork seems to have its own upgrade utility, installed into %LOCALAPPDATA%\Fork\Update.exe.
Maybe the WinGet manifest can be adapted to delegate to that utility instead of downloading & executing a full installer? I skimmed the WinGet manifest format docs and found no obvious way, though.

**Comment by Zageron** [comment]
Well hopefully that's acceptable for being able to install this package via Winget and then not mangle it. Thanks for the suggestion, I hope it works.
