### ISSUE TITLE
[Package Request]: FotoSketcher

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#55923]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: APEXIA
Publisher Url: https://fotosketcher.com/
Package Name: 
Description: FotoSketcher is a 100% free program for Windows (there is also an experimental version for MacOS) which converts your digital photos into art automatically and in just a few mouse clicks. Over 20 different styles are available from pencil sketches to watercolor or oil paintings, pen & ink drawings, abstract art and cartoons. From photo to painting (landscapes, architecture, portraits, etc.) in seconds!
Package Version: 3.80
Installer URL: https://www.fotosketcher.com/FotoSketcher_3.80_setup_64bit.exe

Current Package Identifier (for new versions):

**Comment by thedoggybrad** [comment]
@Trenly

**Comment by thedoggybrad** [comment]
@OfficialEsco

**Comment by Trenly** [comment]
@thedoggybrad Esco and I (along with several other members of the repo) check for new issues daily. No need to tag us in every package request, we see them all anyways and get to them when we have time

**Comment by KaranKad** [comment]
I've created a PR for it at https://github.com/microsoft/winget-pkgs/pull/55943. But it will have problems upgrading because version is unknown in Add or remove programs.

**Comment by thedoggybrad** [comment]
@KaranKad I am experiencing the issue right now, it loops to upgrade and upgrade to the same version using (Winget upgrade --all). Any workarounds to temporarily stop reinstallation of FotoSketcher again and again. If the issue has no workarounds I would like FotoSketcher to be temporarily removed on WINGET. Hope that there is a workaround.

**Comment by KaranKad** [comment]
You should install latest preview version of winget from GitHub. It doesn't upgrade apps that have unknown version when you use `winget upgrade -all`

**Comment by hinakhan09** [comment]
Download Now https://pclife.info/fotosketcher-crack/
