### ISSUE TITLE
Pipelines should skip Installer Validation for metadata only PRs

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#55921]
### Description of the new feature/enhancement

Most of the time in the validation pipeline is spent on Installer Verification (according to ADO). This is a waste of time if the PR is a modification to metadata (like publisher information changes, or converting from singleton to multifile). I think that some of the strife with the pipeline-stormageddon of 2022(tm) could have been avoided if the pipelines didn't spend so much time on checking data that didn't change when the manifest was converted.

If there is no change to information winget uses to install a package or to information used for matching (which could be verified in the pipeline), the Installation Verification step should be skipped.

### Proposed technical implementation details (optional)

If the installers array or the global installer properties (InstallerType, Publisher, etc.) haven't changed, don't run the `InstallerValidation` job. Shouldn't be too hard once you parse the YAML, I don't think.

**Comment by Trenly** [comment]
* Related to https://github.com/microsoft/winget-pkgs/issues/18354

**Comment by jedieaston** [comment]
Shoot, should this be the same issue? I looked under that tag and my brain just must not have processed the title.

**Comment by Trenly** [comment]
I think this one is actually broader, since it makes note that there is metadata in the installer file like FileExtensions and Protocols. These metadata items are left out of the other issue

**Comment by OfficialEsco** [comment]
I think its fine, + it also includes the Installer ManifestType
AND its a reminder >:(
