### ISSUE TITLE
[Package Issue]: Scilab.Scilab

### ISSUE THREAD

**Issue by citron** [microsoft/winget-pkgs#56024]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Scilab version is stuck to "unknown".
"winget upgrade --all" reinstalls Scilab.Scilab again and again, even if the lastest version is already installed

### Steps to reproduce

```
winget install Scilab.Scilab
winget upgrade --all
winget list scilab
winget upgrade --all
winget list scilab
```

### Actual behavior

```
> winget list Scilab
Nom    ID            Version Disponible Source
----------------------------------------------
scilab Scilab.Scilab Unknown 6.1.1      winget
```

### Expected behavior

```
> winget list Scilab
Nom    ID            Version Disponible Source
----------------------------------------------
scilab Scilab.Scilab 6.1.1   6.1.1      winget
```

### Environment

```shell
Gestionnaire de package Windows v1.2.10271
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Journaux: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```
```


### Screenshots and Logs

_No response_

**Comment by Trenly** [comment]
This is because the publisher of Scilab does not provide the version information to Windows. The best thing to do here would be to contact the publisher and ask them to add the Version information

In the future, the 1.3 client will skip upgrading packages with unknown versions unless a specific option is used

**Comment by luzpaz** [comment]
Heads up, Scilab has changed their version scheme
Current version is 2023.1.0  
https://www.scilab.org/download/2023.1.0/scilab-2023.1.0.bin.x64.exe
