### ISSUE TITLE
PRs quality

### ISSUE THREAD

**Issue by aliheikal** [microsoft/winget-pkgs#5612]
It came to my attention that some users are submitting PRs that are resulting in inconsistent YAML files or spam, so I thought I should raise this as an issue. It is a quality matter from my point of view. How can we control this?

Example 1:

1. I submitted [this](https://github.com/microsoft/winget-pkgs/commit/05f33a4a00325d047a7ef119e2a4559afeaea659) PR for Bot Framework Composer 1.1.1
2. User with handle DW-42 submitted [this](https://github.com/microsoft/winget-pkgs/commit/286a73a93b4f0ec8eee3309e223bd4d167b97c2c) update PR claiming it is to make things consistent, while this PR actually removed the word Corporation from the publisher, making it inconsistent, and also changed the homepage url to Bot Framework homepage instead of Bot Framework Composer homepage.
3. I submitted [this](https://github.com/microsoft/winget-pkgs/commit/8669f6552eed32d0e8680e210e99cd946d3de1d9#diff-ee4708a295a71c29ca8b7438c70be74644786cd3ff519e2d60c316fa5b54f51a) fix PR to fix the homepage url.

Example 2:

1. User with handle DW-42 submitted [this](https://github.com/microsoft/winget-pkgs/commit/286a73a93b4f0ec8eee3309e223bd4d167b97c2c) update PR claiming it is to make things consistent, while this PR actually removed the word Corporation from the publisher, making it inconsistent, and also changed the homepage url to a wrong one.
2. I submitted [this](https://github.com/microsoft/winget-pkgs/commit/0be82a7d0bcfb670e5fce3fc7bb3ee865598cd35#diff-4052d4e14ad1eeb48bd8f37f46d4e8318e355f090c553edf4f6f123f1d5df227) PR for Bot Framework Composer 1.2.1
3. User with handle DW-42 submitted [this](https://github.com/microsoft/winget-pkgs/pull/5048/commits/a13c5a40bfc32061ce8d54fc799898bb637d9285) update PR claiming it is to make things consistent, while this PR actually added the word Corporation to the publisher, contradicting their own previous PR of actually removing the word Corporation from the publisher, and also changed the homepage url to the documentation page instead of the homepage.

**Comment by denelon** [comment]
I'm going to move this issue to Discussions. I think there are several different areas we can begin to tackle. My hope is that the discussion will uncover opportunities to improve how validation works. We also have a feature coming to allow verified publishers to manage their manifests.

We also have some current challenges with how list maps packages by their manifests against their entries in Add / Remove Programs in Windows 10. I've made several changes to publisher and package names in manifests to improve the matching. In some cases that meant adding or removing words like "Team", "Corporation", and other associated words for publishers and packages.
