### ISSUE TITLE
[Package Request]: Android-Messages-Desktop

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#56654]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: OrangDrangon
Publisher Url: https://github.com/OrangeDrangon/android-messages-desktop
Package Name: Android-Messages-Desktop
Description: send messages from web browser
Package Version: 5.3.1
Installer URL: https://github.com/OrangeDrangon/android-messages-desktop/releases/download/v5.3.1/AndroidMessages-v5.3.1-win-x64.exe

Current Package Identifier (for new versions):

**Comment by TechnicaVivunt** [comment]
Looks like this application has no installer flags for silent installation when trying all of the popular ones (/s, /silent, /qn). If you think you can get the dev to add silent install options (assuming this installation doesn't require any dependencies) I think it could be added.

**Comment by dtantono** [comment]
as you can see from the developer comment. you can use the command provided by developer. (https://github.com/OrangeDrangon/android-messages-desktop/issues/369)

**Comment by TechnicaVivunt** [comment]
Sweet! Looks like I just missed the capital S flag. I'll submit a manifest first thing in the morning.

**Comment by Trenly** [comment]
> Sweet! Looks like I just missed the capital S flag. I'll submit a manifest first thing in the morning.

Actually, the silent flag isn't needed. Because it is built with electron, it is a nullsoft installer type, and will install silently by default when the installer type is specified correctly
