### ISSUE TITLE
[Package Request]: Dell Display Manager

### ISSUE THREAD

**Issue by JerryWinkler** [microsoft/winget-pkgs#56792]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Dell

Publisher Url: https://www.dell.com/support/home/en-us/product-support/product/dell-s2719dgf-monitor/drivers

Package Name: Dell Display Manager

Description: Dell Display Manager enhances everyday productivity through comprehensive management tools giving you optimal front of screen experience, efficient display management and easy, effortless multitasking. IT Managers will now be able to manage and control monitors remotely improving overall productivity. This application requires Display Data Channel Command Interface (DDC/CI) to work.

Package Version: 1.55.0.2090

Installer URL: https://dl.dell.com/FOLDER08196078M/1/ddmsetup2090.exe

**Comment by Trenly** [comment]
I believe this will be blocked due to hardware requirements
>  For Windows operating systems, Dell Display Manager (DDM) works only with select Dell monitors developed from 2013 and beyond, except Dell D-series and Nvidia G-SYNC-based models

**Comment by JerryWinkler** [comment]
> I believe this will be blocked due to hardware requirements
> 
> > For Windows operating systems, Dell Display Manager (DDM) works only with select Dell monitors developed from 2013 and beyond, except Dell D-series and Nvidia G-SYNC-based models

I can't confirm since I am using supported Dell displays, hence the request.

I wonder if the install would actually fail without a supported monitor? Or if installation works and one could just not use the features to change monitor settings. If the latter, then I sure would find it nice to be able to install/update via winget.

**Comment by hueldoeu** [comment]
i have so many problems with DDM
