### ISSUE TITLE
EarTrumpet: Download request status is not success. 0x80190194 : Not found (404).

### ISSUE THREAD

**Issue by pbrandstetter** [microsoft/winget-pkgs#5757]
When trying to install EarTrumpet winget-cli shows, that the installation file can not be found.

# Brief description of your issue

The installation file https://install.eartrumpet.app/master/EarTrumpet.Package_2.1.7.3_x86.appxbundle was never available or has been removed. So winget-cli could not find the installer-file.

# Steps to reproduce

```winget install eartrumpet```

# Expected behavior

A successful install of eartrumpet.

# Actual behavior

winget-cli shows an error:

![image](https://user-images.githubusercontent.com/43231569/103224348-d6217080-4927-11eb-96fa-f058dae01e64.png)

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by sa-orlov** [comment]
No

**Comment by pbrandstetter** [comment]
Fixed with #5759

**Comment by denelon** [comment]
I believe Ear Trumpet is in the Microsoft Store. If you enable the experimental store feature, you should be able to install Ear Trumpet.

**Comment by pbrandstetter** [comment]
Thank you, I already submitted a PR and now we should be able to install eartrumpet via winget.
