### ISSUE TITLE
[Package Issue]: NewTek.NDI5Tools

### ISSUE THREAD

**Issue by maehne** [microsoft/winget-pkgs#57635]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

When NewTek.NDI5Tools are installed using `winget`, they always get reinstalled during a `winget upgrade --all`. When I just issue `winget upgrade`, the currently installed version is listed as Unknown:

```
PS> winget upgrade
Name                  ID                     Version       Verfügbar     Quelle
-------------------------------------------------------------------------------
[...]
NDI 5 Tools           NewTek.NDI5Tools       Unknown       5.1.2.0       winget
[...]
PS> winget show NewTek.NDI5Tools
Gefunden NDI 5 Tools [NewTek.NDI5Tools]
Version: 5.1.2.0
Herausgeber: NewTek, inc.
Beschreibung: Transmit live video and audio with NDI.
Lizenz: MIT
Installationsprogramm:
  Typ: inno
  Download-URL: https://downloads.ndi.tv/Tools/NDI%205%20Tools.exe
  SHA256: fc6d35f793ea13577600a65fa49fecd6b79a70bdddd3bad6b03c40ee5297222b
```

It may be relevant that I configured `winget` to install packages in machine scope.

### Steps to reproduce

1. Install NewTek.NDI5Tools: `winget install NewTek.NDI5Tools`. In my case, version 5.1.2.0 will get installed.
2. Upgrade all packages: `winget upgrade --all`. NewTek.NDI5Tools will get directly considered for upgrade (to version 5.1.2.0 in my case). 

### Actual behavior

NewTek.NDI5Tools always get reinstalled during a `winget upgrade --all`. The installed version gets listed as "Unknown".

### Expected behavior

NewTek.NDI5Tools should only get upgraded if there is a new version available. After upgrade, `winget upgrade` should list the version, to which the package got upgraded.

### Environment

```shell
Windows-Paket-Manager v1.2.10271
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22000.593
Paket: Microsoft.DesktopAppInstaller v1.17.10271.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/te…
```

### Screenshots and Logs

[WinGet-2022-04-13-10-41-50.592.log](https://github.com/microsoft/winget-pkgs/files/8479919/WinGet-2022-04-13-10-41-50.592.log)
[WinGet-2022-04-08-11-08-58.140.log](https://github.com/microsoft/winget-pkgs/files/8479920/WinGet-2022-04-08-11-08-58.140.log)
[WinGet-2022-04-08-11-27-42.764.log](https://github.com/microsoft/winget-pkgs/files/8479921/WinGet-2022-04-08-11-27-42.764.log)
[WinGet-2022-04-13-10-30-37.392.log](https://github.com/microsoft/winget-pkgs/files/8479922/WinGet-2022-04-13-10-30-37.392.log)
[WinGet-NewTek.NDI5Tools.5.1.2.0-2022-04-08-11-30-30.081.log](https://github.com/microsoft/winget-pkgs/files/8479904/WinGet-NewTek.NDI5Tools.5.1.2.0-2022-04-08-11-30-30.081.log)
[WinGet-NewTek.NDI5Tools.5.1.2.0-2022-04-08-11-09-04.699.log](https://github.com/microsoft/winget-pkgs/files/8479905/WinGet-NewTek.NDI5Tools.5.1.2.0-2022-04-08-11-09-04.699.log)

**Comment by OfficialEsco** [comment]
Hey! This issue is caused by the Developer not adding a DisplayVersion to the `A`dd or `R`emove `P`rograms registry table.
There is a workaround in the 1.3 version of winget client where you have to use --include-unknown to update programs which does not set the DisplayVersion.

The proper way to fix this would be to contact the Developer and tell them their Installer needs to add a DisplayVersion string to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{35D49334-910D-4519-B971-C7B604214855}_is1`
![VirtualBoxVM_DSPtXBJAl8](https://user-images.githubusercontent.com/15158490/163154198-7f17bb35-4333-42c2-906a-495841f92b40.png)

**Comment by Trenly** [comment]
Close with reason: As of version 5.5.2.0 NDI5Tools does write a DisplayVersion to the registry;
