### ISSUE TITLE
[Installer hash does not match]: microsoft.office

### ISSUE THREAD

**Issue by FSynchro** [microsoft/winget-pkgs#57646]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When installing microsoft office through the winget client we get the error:

"installer hash does not match; this cannot be overridden when running as admin".

This has happened before previously:

https://github.com/microsoft/winget-pkgs/issues/35459#

### Steps to reproduce

winget install microsoft.office -s winget

### Actual behavior

Gives error when trying to download: Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe

Error in question:

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Installs office silently.

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by FSynchro** [comment]
Workaround is to use --force for now.

**Comment by FSynchro** [comment]
```
2022-04-13 15:46:58.481 [CLI ] Package hash verification failed. SHA256 in manifest [e5355c841092d89acc1e2839039c25e6d842449a473bee6285213d83403a4d29] does not match download [482965fb962d591714de3665dccde5ae3f576d5b10bd0b9801ae76f66965a5e7]
2022-04-13 15:46:58.481 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:19d

```

**Comment by lloydjatkinson** [comment]
This is again an issue
