### ISSUE TITLE
Outdated package information

### ISSUE THREAD

**Issue by codmccabe** [microsoft/winget-pkgs#5770]
`PS C:\> winget install xming`
`Found Xming [colinharrison.xming]`
`This application is licensed to you by its owner.`
`Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.`
`Downloading https://ayera.dl.sourceforge.net/project/xming/Xming/6.9.0.31/Xming-6-9-0-31-setup.exe`
`An unexpected error occurred while executing the command:`
`InternetOpenUrl() failed.`
`0x80072efd : unknown error`

I don't know if this is a valid issue, please disregard if it is.

**Comment by lychichem** [comment]
This is because your network is broken and cannot connect to the download link. I don't know where you live in but you should try to use hosts our other what we call "scientific way to connect to Internet" in China to download and install this package.

**Comment by lychichem** [comment]
Anyway, I changed the download link in #5793 ,hope this change may help you.

**Comment by megamorf** [comment]
This issue is now a duplicate because the issue (#5787) that was originally reported on the winget-cli repo has been moved here.
