### ISSUE TITLE
[Package Issue]: Alibaba.Yuque

### ISSUE THREAD

**Issue by Shaloc** [microsoft/winget-pkgs#57728]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

There are two branches of Yuque in alibaba, one is AliYuque (阿里语雀), the other is Yuque (语雀). The former is for Alibaba Inc internal use, and can only be logged in with emploee account of Alibaba Inc.The latter is public version of Yuque, which can be registered and logged in by everyone.
The Alibaba. The package `Alibaba.Yuque` includes AliYuque other than Yuque, but it is likely that most users will want to install the latter.
The links of Yuque and AliYuque are 
```text
https://app.nlark.com/yuque-desktop/[version]/Yuque-[version].exe
https://app.nlark.com/yuque-desktop/[version]/AliYuque-[version].exe
```
I suggest
- AliYuque should be included in another package `Alibaba.AliYuque`
- The `Alibaba.Yuque` package should include Yuque other than AliYuque
- The upgrade of `Alibaba.Yuque` and `Alibaba.AliYuque` should be seperated

### Steps to reproduce

```powershell
winget install Alibaba.Yuque
```

### Actual behavior

The internal-used Yuque (AliYuque) is downloaded and installed.

### Expected behavior

Download and install public Yuque.

### Environment

```shell
Windows 程序包管理器(预览) v1.3.692-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22598.1
程序包: Microsoft.DesktopAppInstaller v1.18.692.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
@vedantmgoyal2009 - your automation will need to be updated as part of the Package Structure changes

**Comment by SpecterShell** [comment]
> @vedantmgoyal2009 - your automation will need to be updated as part of the Package Structure changes
It is not the automation's fault. The publisher push the wrong branch to the update source by accident when the new version released.
https://www.yuque.com/yuque/yuque-desktop/changelog-1-1-4#comment-22081307

**Comment by Trenly** [comment]
> > @vedantmgoyal2009 - your automation will need to be updated as part of the Package Structure changes
> 
> It is not the automation's fault. The publisher push the wrong branch to the update source by accident when the new version released. https://www.yuque.com/yuque/yuque-desktop/changelog-1-1-4#comment-22081307

Ahhhh, I see. Makes sense; I thought vedant was scraping both of them with the same logic

**Comment by Trenly** [comment]
Close with reason: Resolved by 57735;
