### ISSUE TITLE
EarTrumpet Installer URL invalid

### ISSUE THREAD

**Issue by rich-davies** [microsoft/winget-pkgs#5777]
https://github.com/microsoft/winget-pkgs/blob/master/manifests/File-New-Project/EarTrumpet/2.1.7.3.yaml has an invalid URL:
_Found EarTrumpet [File-New-Project.EarTrumpet]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://install.eartrumpet.app/master/EarTrumpet.Package_2.1.7.3_x86.appxbundle
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404)._

**Comment by pbrandstetter** [comment]
Duplicate of #5757 
Already fixed with PR #5759
