### ISSUE TITLE
[Package Issue]: JetBrains.IntelliJIDEA.Ultimate available update detected incorrectly

### ISSUE THREAD

**Issue by fulopm** [microsoft/winget-pkgs#57809]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

IntelliJ IDEA Ultimate is on latest version on my machine, but `winget upgrade` shows an older version, and my installed version as an available update.

### Steps to reproduce

- Update IntelliJ IDEA with its built-in updater
- Check `winget upgrade` output, still shows an update available

### Actual behavior

`winget upgrade` still shows an available upgrade, even after IntelliJ IDEA is upgraded to the latest version.

### Expected behavior

IntelliJ IDEA should not be shown after updating to latest in `winget upgrade` output.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/12369436/163470318-7e0443b1-2b22-44eb-9b78-25a404b101af.png)

**Comment by ItzLevvie** [comment]
What version does it show in Control Panel (Apps & features / Installed Apps) because that's what WinGet uses to determine what version you're on and if the application needs an upgrade or not.

It's usually the installers' fault for not updating the registry entries properly. All WinGet does is download the installer and run it under unattended mode via installer switches.

**Comment by fulopm** [comment]
@ItzLevvie 

Thanks, it seems that the installer didn't update the version. I'll file a bug report to JetBrains.

![image](https://user-images.githubusercontent.com/12369436/163471626-01af3b37-9bea-44c9-8486-8a85454a0616.png)

**Comment by fulopm** [comment]
reported [here](https://youtrack.jetbrains.com/issue/IDEA-292235)

**Comment by ItzLevvie** [comment]
It looks like this has been an issue since May 2020 for DisplayVersion and June 2013 (!) for DisplayName: https://youtrack.jetbrains.com/issue/IDEA-240373 (DisplayVersion) and https://youtrack.jetbrains.com/issue/IDEA-109831 (DisplayName).

All JetBrains apps seem to be affected.
