### ISSUE TITLE
xming 

### ISSUE THREAD

**Issue by codmccabe** [microsoft/winget-pkgs#5787]
`PS C:\> winget install xming`
`Found Xming [colinharrison.xming]`
`This application is licensed to you by its owner.`
`Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.`
`Downloading https://ayera.dl.sourceforge.net/project/xming/Xming/6.9.0.31/Xming-6-9-0-31-setup.exe`
`An unexpected error occurred while executing the command:`
`InternetOpenUrl() failed.`
`0x80072efd : unknown error`

I don't know if this is a valid issue, please disregard if it is.

**Comment by megamorf** [comment]
The xming package download link has been updated via #5793. This issue and its duplicate #5770 can be closed once the package installation has been verified to work with the new download URL (when the changes have been replicated to the winget package index).

**Comment by codmccabe** [comment]
You all rock
