### ISSUE TITLE
[Package Issue]: Microsoft.dotnetPreview

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [microsoft/winget-pkgs#57940]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

The `Microsoft.dotnetPreview` package attempts to install SDK [`6.0.100-rc.1.21463.6`](https://github.com/microsoft/winget-pkgs/blob/32a02cb68252e9a1e053df3af0aae4b3036ecc24/manifests/m/Microsoft/dotnetPreview/6.1.21.46306/Microsoft.dotnetPreview.installer.yaml#L18), that is, a *release candidate* of an already released and feature-upgraded sdk (up to date version is `6.0.202`). `winget show Microsoft.dotnetPreview` shows it is a package managed by Microsoft, yet it has been updated 7 months ago.

### Steps to reproduce

`winget install dotnet.Preview`

### Actual behavior

Downloading & installing `dotnet-sdk-6.0.100-rc.1.21463.6-win-x64.exe`.

### Expected behavior

Downloading & installing `dotnet-sdk-7.0.100-preview.3.22179.4-win-x64`, at least at the moment of writing this issue.
In an ideal world, this package should receive an update each time a new preview of a .NET SDK is released.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment]
You should be good to go now, due to @lychichem's PR.
