### ISSUE TITLE
how to use winget with installer less packages like scoop/choco 

### ISSUE THREAD

**Issue by maxandersen** [microsoft/winget-pkgs#580]
# Description of the new feature/enhancement
document how/if installer less packages works with winget.
i.e. for https://github.com/maxandersen/jbang I already support https://github.com/maxandersen/jbang/blob/master/src/main/scripts/choco/jbang.nuspec[choco] and [scoop](https://github.com/maxandersen/jbang/blob/master/src/main/scripts/scoop/jbang.json) as they
allow you to specify zip file to downlod and put it in a standard location and have it exposed in the path by default.

winget seem to not have this notion, making it still necessary to use choco/scoop - any plans on improving/enabling this ?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/182

**Comment by maxandersen** [comment]
Still an issue.

**Comment by maxandersen** [comment]
What feedback is it you are after ? There are no new questions and it is still an issue. 

Thank you.

**Comment by maxandersen** [comment]
I

**Comment by denelon** [comment]
I need to update the bot's comments. It will not close the issue if there is no label requesting author feedback.
