### ISSUE TITLE
Adding tools to "Automatic hash update" process?

### ISSUE THREAD

**Issue by M1kep** [microsoft/winget-pkgs#5833]
I'm interested in how an application can be added to to the Automatic Hash Updates that wingetbot performs?

**Comment by M1kep** [comment]
Adding some "Author Feedback" to keep this open.

**Comment by jedieaston** [comment]
It does it automatically if the hash doesn't match for the same URL. For example, Google doesn't post a new URL for each installer for Chrome, so if the bot detects that the hash for the installer has changed, it fixes the manifest. 

(as I understand it, since the code isn't available yet).

**Comment by M1kep** [comment]
@jedieaston id agree it was automatic, but the kubectl package was using the "latest" format as well and was overlooked. This leads me to believe there is some specific format or a registration, for lack of a better word, that needs to happen.

**Comment by M1kep** [comment]
"Author Feedback"

**Comment by M1kep** [comment]
@denelon is there someway to flag this issue so I don't have to provide "author feedback" every week?

**Comment by KevinLaMS** [comment]
@M1kep   it should be fixed.  Sorry about that.

**Comment by denelon** [comment]
This issue has been resolved for quite some time. I'm going to go ahead and close this.
