### ISSUE TITLE
MikTex Invalid Installer URL

### ISSUE THREAD

**Issue by nicolasAmat** [microsoft/winget-pkgs#5841]
# Brief description of your issue

MikTex invalid installer URL.

# Steps to reproduce

`winget install miktex`

# Actual behavior

```PowerShell
PS C:\Users\_> winget install miktex
Found MiKTeX [ChristianSchenk.MiKTeX]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://muug.ca/mirror/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7442-x64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

# Environment

```none
Windows Package Manager v0.2.3162 Preview
Windows: Windows.Desktop v10.0.19042.685
Package: Microsoft.DesktopAppInstaller v1.11.3162.0
```

**Comment by OfficialEsco** [comment]
This is a tricky one, MikTex does not have a static permanent link.
https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-20.12-x64.exe will redirect you to a bunch of different mirrors, BUT since they all have have the same SHA-256 it should be ok.

#5842 will fix this issue since the current yaml is 10 versions behind.
Later we will see how the mirrors handle old urls.

**Comment by nicolasAmat** [comment]
Thanks. It seems to be fixed.

**Comment by zeratax** [comment]
This seems to not work again?

```console
$ winget install -e --id ChristianSchenk.MiKTeX
Found MiKTeX [ChristianSchenk.MiKTeX] Version 22.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-22.7-x64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : unknown error
```

**Comment by mdanish-kh** [comment]
> This seems to not work again?
> 
> ```
> $ winget install -e --id ChristianSchenk.MiKTeX
> Found MiKTeX [ChristianSchenk.MiKTeX] Version 22.7
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-22.7-x64.exe
> An unexpected error occurred while executing the command:
> Download request status is not success.
> 0x80190194 : unknown error
> ```

- https://github.com/microsoft/winget-pkgs/pull/87445

The issues will be resolved once this PR gets merged.

**Comment by WrinkleRelease** [comment]
Having trouble upgrading my MiKTeX install.
```Powershell
PS C:\> winget upgrade
Name                      Id                          Version      Available    Source
--------------------------------------------------------------------------------------
MiKTeX                    MiKTeX.MiKTeX               22.8         22.10        winget 
```
Running `winget upgrade --id MiKTeX.MiKTeX` produces:

```PowerShell
PS C:\> winget upgrade --id MiKTeX.MiKTeX
No applicable update found.

**Comment by mdanish-kh** [comment]
@WrinkleRelease - The package id was recently modified to align with WinGet's naming convention; that might have been a breaking issue. Could you please try `winget install MiKTeX.MiKTeX` for now? Any subsequent versions *should* be cleanly upgrade-able.

**Comment by WrinkleRelease** [comment]
> @WrinkleRelease - The package id was recently modified to align with WinGet's naming convention; that might have been a breaking issue. Could you please try `winget install MiKTeX.MiKTeX` for now? Any subsequent versions _should_ be cleanly upgrade-able.

Not a problem. Would you suggest I uninstall the current package just to be clean?
