### ISSUE TITLE
[Package Issue]: CrystalDewWorld.CrystalDiskMark

### ISSUE THREAD

**Issue by stilett0** [microsoft/winget-pkgs#58540]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I have version 8.0.4a already installed by CrystalDiskMark 8.0.4a's installer from their website without using winget (https://osdn.net/projects/crystaldiskmark/downloads/75540/CrystalDiskMark8_0_4a.exe/ )

However, winget offers me version 8.0.4 as Available.

CrystalDiskMark 8.0.4a is newer than 8.0.4.

Packages for both CrystalDiskMark 8.0.4 and 8.0.4a exist within winget-pkgs.

I suspect that if I did not have CrystalDiskMark installed already, then "winget install CrystalDewWorld.CrystalDiskMark" would have offered me 8.0.4 as newest.

### Steps to reproduce

winget upgrade --include-unknown

(while 8.0.4a is already installed)

### Actual behavior

```
PS C:\Users\stilett0\Downloads> winget upgrade --include-unknown
Name                  Id                     Version       Available     Source
-------------------------------------------------------------------------------
CrystalDiskMark       CrystalDewWorld.Cryst… 8.0.4a        8.0.4         winget
1 upgrade available.
```

### Expected behavior

No upgrades available.

### Environment

```shell
Windows Package Manager (Preview) v1.3.431-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1645
Package: Microsoft.DesktopAppInstaller v1.18.431.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by stilett0** [comment]
To be fair, for other applications, "a" might mean alpha, or the final "a-less" version number might be final. But apparently CrystalDiskMark is using "a" to mean a point release -after- the initial 8.0.4 release.

**Comment by OfficialEsco** [comment]
I can actually recall some packages using X.X.Xa/b/c/d/e but i can't recall if they release X.X.X, but if they do this issue is affecting at least some other package

eitherway they should definitively check the winget-cli sorting, for example search is not sorted at all which makes it a mess..
```
❯ winget search
Name                                   Id                                    Version
-------------------------------------------------------------------------------------------
115电脑版                              115.115                               1.0.4.6
115浏览器                              115.115Chrome                         25.0.1.0
Knotes                                1MHz.Knotes                           2.11.2
BPMN-RPA Studio                       1ic.BPMN-RPAstudio                    21.8.11
Fishing Funds                         1zilc.FishingFunds                    5.7.2
SyncBackFree                          2BrightSparks.SyncBackFree            10.2.14.0
360极速浏览器                          360.360Chrome                         13.5.2001.0
```
or
```
❯ winget search mozilla
Name                      Id                               Version Match
-------------------------------------------------------------------------------
Mozilla VPN               Mozilla.VPN                      2.7.1.0 Tag: mozilla
Mozilla Firefox ESR       Mozilla.Firefox.ESR              91.8.0  Tag: mozilla
Firefox Developer Edition Mozilla.Firefox.DeveloperEdition 100.0b8 Tag: mozilla
Mozilla Firefox           Mozilla.Firefox                  99.0.1  Tag: mozilla
MozBackup                 JasnaPaka.MozBackup              1.5.1   Tag: mozilla
Mozilla Thunderbird Beta  Mozilla.Thunderbird.Beta         99.0b2
Mozilla Thunderbird       Mozilla.Thunderbird              91.8.1
SeaMonkey                 Mozilla.SeaMonkey                2.53.11
Nightly                   Mozilla.Firefox.Nightly          97.0a1
Mozilla Firefox (Beta)    Mozilla.Firefox.Beta             97.0
```

**Comment by Trenly** [comment]
> for example search is not sorted at all which makes it a mess.

Search is sorted, it’s just sorted by relevance as opposed to version. Moniker, PackageIdentifier (by how closely it matches), Name, and Tags all play into how a package gets sorted iirc

**Comment by JohnMcPMS** [comment]
The generic version sorting that is implemented tries to hew as close to [semver ](https://semver.org/)as possible, and this part applies to the "a" here (we just aren't strict about having a hyphen):

> 9. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

And specifically:

> Pre-release versions have a lower precedence than the associated normal version.

Or to be more succinct, as @stilett0 said:

> To be fair, for other applications, "a" might mean alpha, or the final "a-less" version number might be final.

The version that we have *should* match whatever is put into Add/Remove Programs.  The only way to solve this that I see is to create a manifest property to indicate "treat alpha chars on last version part as higher than no alpha chars" (really, a version quirking field for more than just that, but it will be the first one).

**Comment by Trenly** [comment]
> The generic version sorting that is implemented tries to hew as close to [semver ](https://semver.org/)as possible, and this part applies to the "a" here (we just aren't strict about having a hyphen):
> 
> > 9. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.
> 
> And specifically:
> 
> > Pre-release versions have a lower precedence than the associated normal version.
> 
> Or to be more succinct, as @stilett0 said:
> 
> > To be fair, for other applications, "a" might mean alpha, or the final "a-less" version number might be final.
> 
> The version that we have _should_ match whatever is put into Add/Remove Programs. The only way to solve this that I see is to create a manifest property to indicate "treat alpha chars on last version part as higher than no alpha chars" (really, a version quirking field for more than just that, but it will be the first one).

I think that makes sense, but whenever there is a prerelease version, in 99% of cases, we have split the package identifiers into normal and prerelease given the absence of channels.

**Comment by DenWin** [comment]
I suggested to update 8.0.4 instead of creating 8.0.4a and now 8.0.4c
See issue https://github.com/microsoft/winget-pkgs/issues/122931

**Comment by DenWin** [comment]
@trenly @stilett0

Hi, the issue seems to have been fixed by https://github.com/microsoft/winget-pkgs/pull/122942.
Well at least for 8.0.4c and future once

I recommend to close this issue

**Comment by Trenly** [comment]
Close with reason: Mitigated;
