### ISSUE TITLE
[Package Request]: Looking Glass Host

### ISSUE THREAD

**Issue by PAI5REECHO** [microsoft/winget-pkgs#58708]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: HostFission
Publisher URL: https://looking-glass.io/
Package Name: Looking Glass Host
Description: An extremely low latency KVMFR (KVM FrameRelay) implementation for guests with VGA PCI Passthrough
Package Version: B5.0.1
Installer URL: https://looking-glass.io/artifact/B5.0.1/host

Current Package Identifier (for new versions): `HostFission.LookingGlassHost`

**Comment by PAI5REECHO** [comment]
Just realized that, I'll look

**Comment by Trenly** [comment]
Close with reason: Added in above linked PR;
