### ISSUE TITLE
[Package Issue]: NickeManarin.ScreenToGif Does Not Upgrade Existing Installations

### ISSUE THREAD

**Issue by phuzion** [microsoft/winget-pkgs#58993]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When upgrading to a new version of ScreenToGif, if the original version was installed outside of winget, an additional copy will be installed, rather than upgrading the existing copy. Since the old version remains, `winget upgrade` always shows an outdated copy of ScreenToGif in the upgrade candidates list.

I'm not 100% sure if this qualifies as a side-by-side installation or not, so I'm classifying this under the more generic installation issue tag. Please re-tag as appropriate.

### Steps to reproduce

* Install any old version of ScreenToGif interactively using the MSI file provided in the manifest
* Run `winget upgrade` and see that ScreenToGif is listed as a possible upgrade
* Run `winget upgrade NickeManarin.ScreenToGif` and allow the upgrade to occur
* Note in appwiz.cpl that there are two versions of ScreenToGif installed

### Actual behavior

Two versions of the application appear in Programs and Features

### Expected behavior

The old copy of ScreenToGif should be upgraded rather than have a second copy installed.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1645
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by phuzion** [comment]
I originally installed ScreenToGif 2.33.1 from an MSI. When I say interactive, I mean that I downloaded and opened the MSI and clicked through the wizard steps.

If there's anything I can do on my end to assist (collecting logs, etc), please let me know.

**Comment by denelon** [comment]
It looks like we may need to leverage the [MSI Upgrade Code](https://docs.microsoft.com/windows/win32/msi/upgradecode).

Related Issues:
* https://github.com/microsoft/winget-cli/issues/1145
* https://github.com/microsoft/winget-cli/issues/1001

**Comment by phuzion** [comment]
Out of curiosity, I installed ScreenToGif 2.33.0 using the MSI and clicking through the wizard, and then upgraded to versions 2.35.0 and 2.36.0, and there was no duplication in Programs and Features.

After uninstalling 2.36.0 through Programs and Features, manually reinstalling 2.35.0, and then attempting an upgrade using `winget upgrade ScreenToGif`, I continue to see the duplicate entry in Programs and Features.

**Comment by NickeManarin** [comment]
This was an issue with older versions of the MSI package. It should not happen with newer version.
The app supports perUser/perMachine installations.

**Comment by NickeManarin** [comment]
@phuzion Sorry for the delay.

Let me clarify what I wrote before:

The installer lets you install in perUser/perMachine modes via user selection in the UI (this was not available before; I think that it was set as `perMachine`). 
Of course, when installing perMachine in version 2.35 and then later trying to install perUser in 2.36 you would get two entries in the program list.
Newer installers (after v2.36) will handle that (uninstalling the version regardless of the installation mode) when running manually.

But if the installer is triggered by a tool (via msiexec), you still need to uninstall the other version manually.

The installer lets you install in perUser/perMachine modes via user selection in the UI (this was not available before; I think that it was set as `perMachine`). 
Of course, when installing perMachine in version 2.35 and then later trying to install perUser in 2.36 you would get two entries in the program list.
Newer installers (after v2.36) will handle that (uninstalling the version regardless of the installation mode) when running manually.

But if the installer is triggered by a tool (via msiexec), you still need to uninstall the other version manually.

**Comment by bartoszek** [comment]
The issue persist with `NickeManarin.ScreenToGif:2.37.1`
After upgrading from `2.37` to `2.37.1` winget alongside `control_panel/add_remove_program` shows both version being installed.
```pwsh
winget list|Select-String ScreenToGif                                                                                                                                  in pwsh at 13:34:14

ScreenToGif                               NickeManarin.ScreenToGif                  2.37.1                       winget
ScreenToGif                               NickeManarin.ScreenToGif                  2.37           2.37.1        winget
```

**Comment by edler-san** [comment]
Same for `2.37.2` to `2.3.38`.

**Comment by denelon** [comment]
@NickeManarin any ideas? Did something change?

**Comment by denelon** [comment]
@NickeManarin sorry, the issue didn't refresh for me correctly. I saw your comments after I posted :(

**Comment by denelon** [comment]
If there aren't any settings that persist, we could add "uninstallPrevious" for newer manifests for a while to help.
