### ISSUE TITLE
P.S.A. CLA signing is failing

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#59167]
If you have already signed the CLA you may see PRs failing on this step. The team is aware and is working to mitigate this issue.

**Comment by vedantmgoyal2009** [comment]
It is still failing. See https://github.com/microsoft/winget-pkgs/pull/59671

**Comment by denelon** [comment]
@vedantmgoyal2009 I believe that was their first PR, and they did need to sign the CLA.
