### ISSUE TITLE
[Package Issue]: BraveSoftware.BraveBrowser

### ISSUE THREAD

**Issue by thetredev** [microsoft/winget-pkgs#59352]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Installation works fine. However, the ID for installation differs from the ID which is listed as installed. I expect both IDs to be the same.

### Steps to reproduce

1. Install Brave browser using `winget install -e --id BraveSoftware.BraveBrowser`
2. List installed packages using `winget list -s winget --id Brave`

### Actual behavior

`winget list -s winget --id Brave` yields
```
Name                                    ID                                             Version            Available
-----------------------------------------------------------------------------------------------------------------------
Brave                                   BraveSoftware Brave-Browser                    101.1.38.109
```

### Expected behavior

`winget list -s winget --id Brave` yields
```
Name                                    ID                                             Version            Available
-----------------------------------------------------------------------------------------------------------------------
Brave                                   BraveSoftware.BraveBrowser                    101.1.38.109
```

### Environment

```shell
Windows-Paket-Manager v1.2.10271
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1682
Paket: Microsoft.DesktopAppInstaller v1.17.10271.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
On an en-US PC I see the expected results:
```
PS C:\Users\WinGet> winget list Brave
Name  Id                         Version      Source
-----------------------------------------------------
Brave BraveSoftware.BraveBrowser 101.1.38.109 winget
```
![image](https://user-images.githubusercontent.com/11600822/166299088-f99e18b3-391e-483c-846f-ae57ffd5a4e4.png)

Does Brave have a different publisher if your system language isn't en-US?

**Comment by thetredev** [comment]
Wow, that was unexpected. I can't answer that question, but it seems like it. Can/should this even be fixed then?

**Comment by thetredev** [comment]
Another suggestion: can we force `winget` somehow to only print the en-US publisher? I'm guessing, however, that the publisher is written to disk somewhere (registry, install folder, or local winget cache/store).
