### ISSUE TITLE
[Package Request]: Hakuneko-Nightly

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#59658]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Ronny Wegener
Publisher Url: https://github.com/manga-download/hakuneko
Package Name: Hakuenko-Nightly
Description: HakuNeko is a cross-platform downloader for manga and anime from various websites. HakuNeko does not host anything by itself.
Package Version: 8.3.4
Installer URL: https://github.com/manga-download/hakuneko/releases/download/nightly-20200705.1/hakuneko-desktop_8.3.4_windows-setup_amd64.exe

Current Package Identifier (for new versions):

**Comment by russellbanks** [comment]
Hi, I've made a pull request for this - #62958

**Comment by russellbanks** [comment]
Merged in [d9bfc17](https://github.com/microsoft/winget-pkgs/commit/d9bfc170dd064dfc8832e875c3c026f880411500) :)

**Comment by dtantono** [comment]
cool, thanks
