### ISSUE TITLE
[Package Request]: BlueMail

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#59680]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: BlueMail
Publisher Url: https://bluemail.me/download/
Package Name: BlueMail
Description: an email client
Package Version: 4.10
Installer URL: https://download.bluemail.me/BlueMail-Desktop-Installer.exe

Current Package Identifier (for new versions): 4.10

**Comment by Trenly** [comment]
Package exists in msstore source `winget show 9PMHZVM588P4`
