### ISSUE TITLE
[Package Request]: Please stop packaging AccessibilityInsights releases

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/winget-pkgs#59885]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Hi! I work on Accessibility Insights, and we discovered today that you've been packaging our releases (see https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/AccessibilityInsights). In 2 words, Please stop. In slightly more words, Please stop and delete all releases you've published so far. We haven't yet committed to using WinGet as a publishing vehicle, and if/when we make that decision, we want it to be certain that we have a consistent story around required upgrades and supported versions. Thanks!

**Comment by vedantmgoyal2009** [comment]
@davetryon will it apply for android also?
