### ISSUE TITLE
Support FTP for installers download

### ISSUE THREAD

**Issue by NathanBnm** [microsoft/winget-pkgs#602]
It seems that FTP is not supported to download installers. For example with Adobe Reader DC there is no direct installer accessible through HTTP because they only provide an online installer which download itself the latest version.

Here is the log I get when trying to install:

```
>winget install -m 2020.009.20063.yaml
Found Acrobat Reader DC [Adobe.AcrobatReaderDC]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading ftp://ftp.adobe.com/pub/adobe/reader/win/AcrobatDC/2000920063/AcroRdrDC2000920063_en_US.exe
An unexpected error occurred while executing the command:
Query download request status failed.
0x80072ef2 : unknown error
```

**Comment by maxmichels** [comment]
You should create a feature request at [microsoft/winget-cli](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=Issue-Feature&template=Feature_Request.md&title=)

**Comment by maxmichels** [comment]
feature-request: microsoft/winget-cli#305

**Comment by denelon** [comment]
Closing this issue as it was created in the client repository.
