### ISSUE TITLE
[Package Issue]: TortoiseSVN upgrade rebooted PC without warning

### ISSUE THREAD

**Issue by loufidelity** [microsoft/winget-pkgs#60211]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Running `winget upgrade tortoisesvn` rebooted my PC without warning.

### Steps to reproduce

Run `winget upgrade tortoisesvn` while having an older version installed

### Actual behavior

Unexpected reboot

### Expected behavior

Some warning at least or postponed reboot.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1706
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by solomoncyj** [comment]
https://github.com/microsoft/winget-pkgs/pull/60856

**Comment by loufidelity** [comment]
Today I got another unexpected reboot when upgrading TortoiseSVN to version 1.14.29387.

Windows Package Manager v1.2.10941.
