### ISSUE TITLE
[Package Request]: rclone

### ISSUE THREAD

**Issue by mbledkowski** [microsoft/winget-pkgs#60427]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: rclone
Publisher Url: https://rclone.org/
Package Name: rclone
Description: Rclone syncs your files to cloud storage
Package Version: v1.58.1
Installer URL: https://downloads.rclone.org/v1.58.1/rclone-v1.58.1-windows-amd64.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
Blocked by microsoft/winget-cli#140

**Comment by Miladiir** [comment]
As the blocking issue is marked as fixed this raises the question: Is it possible now?

**Comment by mdanish-kh** [comment]
> As the blocking issue is marked as fixed this raises the question: Is it possible now?

You can track the progress for .zip installers in the pinned PSA issue: https://github.com/microsoft/winget-pkgs/issues/87300

**Comment by Cyberavater** [comment]
+1
