### ISSUE TITLE
[Package Request]: Browser Tamer

### ISSUE THREAD

**Issue by aloneguid** [microsoft/winget-pkgs#60479]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: aloneguid
Publisher Url: https://www.aloneguid.uk/projects/bt/
Package Name: Browser Tamer
Description: Browser Tamer acts as a browser proxy on your machine that catches links you click and redirects them to a browser or browser profile of your choice.
Package Version: 2.5.4
Installer URL: https://www.aloneguid.uk/projects/bt/bin/bt-installer-2.5.4.exe

Current Package Identifier (for new versions):

**Comment by SpecterShell** [comment]
Nice tool 😉, but there are some issues with the installer:

1. While the software is installed into `C:\Program Files (x86)\BT\`, which is in system scope, the **A**dd **R**emove **P**rogram information is written to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Browser Tamer`, which is in user scope. It is suggested to keep them aligned by
   - Change the directory of ARP to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Browser Tamer`, or
   - Change the directory of files to `C:\Users\<Username>\AppData\Local\Programs`

2. You can add `DisplayVersion` to ARP to help WinGet recognize installed version.
   ```nsis
   WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Browser Tamer" DisplayVersion "2.5.4"
   WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Browser Tamer" Publisher "aloneguid"
   ```

3. https://nsis.sourceforge.io/Reference/$PROGRAMFILES

**Comment by aloneguid** [comment]
Thanks @SpecterShell :) I was going to update the installer but looks like it's already merged in (thanks for spotting it by the way).  I guess the next version then needs to uninstall from system scope and install in user scope.
