### ISSUE TITLE
[New Version Available]: Rufus

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#60617]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Pete Batard
Publisher Url: https://rufus.ie/en/
Package Name: 
Description: Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.
Package Version: 3.1.1877
Installer URL: https://github.com/pbatard/rufus/releases/download/v3.18/rufus-3.18.exe

Current Package Identifier (for new versions):

**Comment by o-l-a-v** [comment]
Use the Microsoft Store version instead? It will auto update.

* https://apps.microsoft.com/store/detail/rufus/9PC3H3V7Q9CH?hl=en-us&gl=US

Rufus being in MS Store is the reason why the developer of Rufus doesn't provide the appx file anymore.

* https://github.com/pbatard/rufus/issues/1732#issuecomment-836371605

Install once with Microsoft Store or winget-cli:

* ```winget install --id 9PC3H3V7Q9CH --source msstore```
