### ISSUE TITLE
[Package Request]: directx

### ISSUE THREAD

**Issue by cjwddtc** [microsoft/winget-pkgs#60621]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: microsoft
Publisher Url: https://www.microsoft.com/en-us/download/details.aspx?id=35
Package Name: directx
Description: 
Package Version: 
Installer URL: https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe

Current Package Identifier (for new versions):

**Comment by licon4812** [comment]
I have created the manifest and attempting to merge now 
#63653

**Comment by licon4812** [comment]
This merge is complete. To see the package type winget search directx. To install winget install Microsoft.DirectX

**Comment by ItzLevvie** [comment]
cc @denelon: Would you be able to close this? It's merged: https://github.com/microsoft/winget-pkgs/blob/635709300afe2c49bd1c9985c832233fcb5c2beb/manifests/m/Microsoft/DirectX/9.29.1974.1/Microsoft.DirectX.installer.yaml
