### ISSUE TITLE
[Package Request]: steamlink 

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#60991]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: valve
Publisher Url: https://steamcommunity.com/app/353380/discussions/8/3105764348181505385
Package Name: steamlink 
Description: steam link for windows 
Package Version: 1.0
Installer URL: https://media.steampowered.com/steamlink/windows/latest/SteamLink.zip

Current Package Identifier (for new versions):

**Comment by jedieaston** [comment]
I think this is blocked by https://github.com/microsoft/winget-cli/issues/859
