### ISSUE TITLE
[Package Issue]: Microsoft.VisualStudio.2022.BuildTools

### ISSUE THREAD

**Issue by alanlivio** [microsoft/winget-pkgs#61729]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The package is installed well but with a bad identifier, which prevents the winget list with the same id.
OS Version: 10.0.22621 N/A Build 22621
Winget version:  v1.2.10941

![image](https://user-images.githubusercontent.com/604808/169817413-8cfe9636-54ec-4ae4-b446-20631a0ca0f8.png)

### Steps to reproduce

```bash
$ winget install Microsoft.VisualStudio.2022.BuildTools
Found Visual Studio Build Tools 2022 [Microsoft.VisualStudio.2022.BuildTools] Version 17.2.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
$ winget list 
```

### Actual behavior

id 18f55be3

### Expected behavior

id Microsoft.VisualStudio.2022.BuildTools 

### Environment

```shell
winget --info
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment]
We should be able to fix this once winget 1.3 is in stable, since then it'll be able to match against the ARP data in the manifest (there isn't any there yet, but I'll add it shortly so it'll be ready for 1.3).
