### ISSUE TITLE
[Package Request]: ElectronMail

### ISSUE THREAD

**Issue by CharlesZ54** [microsoft/winget-pkgs#61743]
### Package Requested

- [X] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [x] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: vladimiry
Publisher Url: https://github.com/vladimiry/ElectronMail
Package Name: ElectronMail
Description:  Unofficial ProtonMail Desktop App 
Package Version: 5.0.2
Installer URL: https://github.com/vladimiry/ElectronMail/releases/download/v5.0.2/electron-mail-5.0.2-windows-x64-nsis-installer.exe

Current Package Identifier (for new versions):

**Comment by OfficialEsco** [comment]
The last 3 times this have been submitted it have been blocked by VC++2015-2019 https://github.com/microsoft/winget-pkgs/pull/20471#issuecomment-880163897 install prompt, so it probably has to wait for Dependency support to roll out (leave the issue open =))

**Comment by CharlesZ54** [comment]
I think this should be enabled now after this commit: https://github.com/vladimiry/ElectronMail/issues/528
