### ISSUE TITLE
[Package Issue]: Mega.MEGASync desktop duplicates

### ISSUE THREAD

**Issue by cobalt2727** [microsoft/winget-pkgs#62121]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

every time I upgrade it another desktop icon appears. they are slowly taking over my wallpaper. send help.

![image](https://user-images.githubusercontent.com/60624944/170605165-8ff4e53b-257f-49c3-92ff-0e66e7702120.png)

### Steps to reproduce

`winget upgrade --all`

### Actual behavior

more icons

### Expected behavior

a lack of more icons

### Environment

```shell
latest everything, refer to my other issue if needed (I can edit this if requested, I'm typing this in a bit of a hurry)
```

**Comment by denelon** [comment]
This is often caused by side-by-side installation rather than a true upgrade. I'm not sure if there are any switches we can pass to the installer during upgrade to avoid additional icons.
