### ISSUE TITLE
Version of "Bulk Rename Utility" not determined

### ISSUE THREAD

**Issue by DarthSonic** [microsoft/winget-pkgs#62171]
### Brief description of your issue

When using "winget list" the tool "Bulk Rename Utility" is no proper recognised. The version of the tool cannot be determined.

`Bulk Rename Utility                        TGRMNSoftware.BulkRenameUtility             Unknown         3.4.3.0   winget`

### Steps to reproduce

install BRU and run winget list

### Expected behavior

BRU should show installed version number and be not updated through winget upgrade everytime.

### Actual behavior

BRU version is not determined and it gets installed with each winget upgrade run.

### Environment

```shell
Windows Package Manger latest version.
Windows 11 Pro Insider Preview Beta.
```

**Comment by Masamune3210** [comment]
App does not register a DisplayVersion
![image](https://user-images.githubusercontent.com/1053504/170810984-7e1395a2-62f2-4ac1-9c0e-4c67f494862d.png)

**Comment by DarthSonic** [comment]
Thank you. I contacted developer about the issue.
