### ISSUE TITLE
[Package Request]: Arduino

### ISSUE THREAD

**Issue by TheNavyBear** [microsoft/winget-pkgs#62457]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Arduino
Publisher Url: https://www.arduino.cc/
Package Name: Arduino IDE
Description: The open-source Arduino Software (IDE) makes it easy to write code and upload it to the board. This software can be used with any Arduino board.
Package Version: 
Installer URL: https://downloads.arduino.cc/arduino-1.8.19-windows.exe

Current Package Identifier (for new versions): 

I know Arduino is in the Microsoft Store, but that version can't be used by other apps to send code to the board (including VS Code). I would like to see the standalone version included in WinGet so I can easily manage it without having to use the MS Store version which doesn't work with other apps.

**Comment by Trenly** [comment]
Blocking Issue - Interactive Install Only; Driver Prompt blocks installation

* #16716
* #19659
* #29721
