### ISSUE TITLE
[Package Issue]: Microsoft.VisualStudio.2019.Enterprise

### ISSUE THREAD

**Issue by Jacob-Tate** [microsoft/winget-pkgs#62655]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installer which is downloaded via the command `winget install Microsoft.VisualStudio.2019.Enterprise --accept-package-agreements --accept-source-agreements --silent --scope Machine` is for visual studio 2022 and installs as such. Im not sure why this is occuring but I cant find a link for the 2019 installer on microsofts website that isnt the 2022 version without going through the azure version of the download IE. `https://my.visualstudio.com/Downloads?q=visual%20studio%202019&wt.mc_id=o~msft~vscom~older-downloads`. The issue with this method is that it is behind a login wall so we cant just use the link.

### Steps to reproduce

 `winget install Microsoft.VisualStudio.2019.Enterprise --accept-package-agreements --accept-source-agreements --silent --scope Machine`

### Actual behavior

Downloads visual studio 2022

### Expected behavior

Downloads visual studio 2019

### Environment

```shell
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1415
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
@jedieaston - Any ideas?

**Comment by jedieaston** [comment]
This is where I get it from: https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

I’m guessing I messed up the link for 2019, once I’m back to my PC I’ll open a fix PR.
