### ISSUE TITLE
[Package Request]: Bundesnetzagentur Breitbandmessung 3.2.1

### ISSUE THREAD

**Issue by caraoge** [microsoft/winget-pkgs#62685]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Bundesnetzagentur (zafaco GmbH)
Publisher Url: https://www.breitbandmessung.de/desktop-app
Package Name: Breitbandmessung 
Description: With the desktop app, the Bundesnetzagentur (Federal Network Agency) provides you with a verification procedure for checking contractually agreed speeds. As part of a measurement campaign, you can determine the actual speeds achieved by your Internet access in upload and download. You can compare these with the contractually agreed speeds. A total of 30 measurements must be taken on three different calendar days. There must be a minimum interval of one calendar day between each measurement, and the measurements must be spread out over the measurement day. The regulations for the measurements to prove underperformance are stored in the desktop app, so that you only have to perform the measurements according to the instructions. At the end of a measurement campaign, you will receive a measurement protocol stating whether there is a non-conforming performance. You can present this protocol with all measurement details to your provider as proof of underperformance.

Package Version: 3.2.1
Installer URL: https://download.breitbandmessung.de/bbm/Breitbandmessung-win.exe

Current Package Identifier (for new versions):

**Comment by denelon** [comment]
@caraoge 
Take a look at the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create). It is a command-line tool designed to help build manifests. It also supports CI/CD scenarios.
