### ISSUE TITLE
[Package Request]: Xanthus58.ValorantRandomizer 1.3.2

### ISSUE THREAD

**Issue by Xanthus58** [microsoft/winget-pkgs#62901]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Xanthus58
Publisher Url: https://github.com/Xanthus58/Valorant-Randomizer
Package Name: Xanthus58.ValorantRandomizer
Description: A randomized for Valorant; it has will automatically select an agent; weapons and shields.
Package Version: 1.3.2
Installer URL: https://github.com/Xanthus58/Valorant-Randomizer/releases/download/1.3.2/INSTALLER_ValorantRandomizer_1.3.2.exe

Current Package Identifier (for new versions): Xanthus58.ValorantRandomizer

**Comment by russellbanks** [comment]
Hi, I've done this for you - #62936

**Comment by Xanthus58** [comment]
> Hi, I've done this for you - #62936

Thanks a ton <3
