### ISSUE TITLE
[Package Issue]: JetBrains.CLion

### ISSUE THREAD

**Issue by timoschwarzer** [microsoft/winget-pkgs#62986]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

CLion (and all other JetBrains IDEs) have `UpgradeBehavior: install` in their manifests, resulting in multiple installed versions when doing upgrades. It should be set to `uninstallPrevious` instead.

### Steps to reproduce

1. Install an old version of CLion via winget
2. Upgrade CLion to a newer version via winget

### Actual behavior

You now have 2 versions of CLion installed.

### Expected behavior

Only the newer version should be installed and the old version should have been removed.

### Environment

```shell
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.708
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
@timoschwarzer - Has this been resolved with the above PR's?

**Comment by timoschwarzer** [comment]
@Trenly I'll try, thanks for the ping!

**Comment by timoschwarzer** [comment]
@Trenly sorry for the late reply, it seems to be fixed. Thanks!
