### ISSUE TITLE
[Package Issue]: Microsoft.EdgeWebView2Runtime

### ISSUE THREAD

**Issue by Hitmanforrent** [microsoft/winget-pkgs#63311]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget fails to upgrade Microsoft.EdgeWebView2Runtime to version 102.0.1245.39 from version 102.0.1245.33

### Steps to reproduce

Run: winget upgrade -e --id Microsoft.EdgeWebView2Runtime.

### Actual behavior

The installer reports that the package successfully upgraded, but the package remains at version 102.0.1245.33. No second version is detected using winget list.

### Expected behavior

The installer to update the package to version 102.0.1245.39, and uninstall version 102.0.1245.33.

### Environment

```shell
PS C:\Users\ryang> winget --info
Windows Package Manager (Preview) v1.3.1391-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.708
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.1391.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2022-06-10-20-46-56.951.log](https://github.com/microsoft/winget-pkgs/files/8882827/WinGet-2022-06-10-20-46-56.951.log)
[WinGet-2022-06-10-20-43-22.424.log](https://github.com/microsoft/winget-pkgs/files/8882828/WinGet-2022-06-10-20-43-22.424.log)

**Comment by albertosantini** [comment]
Same here, but I think the problem it is on package side.

I tried also two alternatives.

- I used the option `Change` from `Control Panel / Programs and Features` to repair the package installed
- I uninstalled and installed again the package with winget

Same result: installed 102.0.1245.33 and not 102.0.1245.39

```
 8:11:27 [C:\WINDOWS\system32]$ winget --info
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.708
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
Have you both tried updating with Terminal run as Administrator?

We're aware Microsoft.EdgeWebView2Runtime is a bit weird, but the common issue with the 1.2 client that its not run as Administrator, the 1.3 client will try to execute the installer as Administrator, however they found a issue with msi's.

The other issue with Microsoft.EdgeWebView2Runtime is that Microsoft Edge contains a installation of WebView + some programs installs WebView as a Dependency so its installed Twice.

**Comment by albertosantini** [comment]
Thanks for fixing the manifest. 
Anyway I confirm (with winget 1.2) I run a cmd as Runs as Administrator before excuting the upgrade.

**Comment by albertosantini** [comment]
Hey.

I am sorry but it seems the same problem: the installing process of 103 release completes correctly, but there is always 102 release.

```
winget upgrade
Name                            Id                            Version       Available     Source
------------------------------------------------------------------------------------------------
Microsoft Edge WebView2 Runtime Microsoft.EdgeWebView2Runtime 102.0.1245.44 103.0.1264.37 winget
1 upgrades available.
```

```
winget --info
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.739
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
I think https://github.com/microsoft/winget-pkgs/pull/64394 fixed the issue?
I just did WinGet Install and got version 103.0.1264.37

**Comment by albertosantini** [comment]
@OfficialEsco Thank you. Resolved.
