### ISSUE TITLE
[Package Request]: WSL Ubuntu 22.04

### ISSUE THREAD

**Issue by david-plugge** [microsoft/winget-pkgs#63383]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

https://apps.microsoft.com/store/detail/ubuntu-2204-lts/9PN20MSR04DW

Publisher: [Canonical Group Limited](https://apps.microsoft.com/store/search?publisher=Canonical%20Group%20Limited)
Publisher Url: 
Package Name: Ubuntu 22.05 LTS
Description: 
Package Version: 2204.0.10.0
Installer URL: 

Current Package Identifier (for new versions):

**Comment by licon4812** [comment]
ubuntu 22.04LTS already is a package in winget.

The id: 9PN20MSR04DW
