### ISSUE TITLE
[Package Issue]: AngusJohnson.ResourceHacker

### ISSUE THREAD

**Issue by Hitmanforrent** [microsoft/winget-pkgs#63607]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget search lists the latest version as 5.1.7, when version 5.1.8 is the latest version and is the version that winget installs. In addition, winget fails to recognize the version of the package, but as I understand it that's likely an issue for the developer.

### Steps to reproduce

Run winget install -e --id AngusJohnson.ResourceHacker

### Actual behavior

Winget lists 5.1.7 as the latest version, but correctly installs 5.1.8 which is the real latest version.

### Expected behavior

Winget to list 5.1.8 as the latest version, and ideally recognize the version number in winget list.

### Environment

```shell
PS C:\Users\ryang> winget --info
Windows Package Manager (Preview) v1.3.1611-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.739
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.1611.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\ryang>
```

### Screenshots and Logs

https://i.imgur.com/qj4C8FD.png

[WinGet-2022-06-14-20-38-07.095.log](https://github.com/microsoft/winget-pkgs/files/8904757/WinGet-2022-06-14-20-38-07.095.log)
[WinGet-AngusJohnson.ResourceHacker.5.1.7-2022-06-14-20-38-24.187.log](https://github.com/microsoft/winget-pkgs/files/8904758/WinGet-AngusJohnson.ResourceHacker.5.1.7-2022-06-14-20-38-24.187.log)

**Comment by ItzLevvie** [comment]
Version Number was based off from the DisplayName https://github.com/microsoft/winget-pkgs/pull/42354 but I'll update tomorrow so people don't get confused.

I think DisplayVersion fixes are implemented in the latest winget-cli preview so it's only the manifest that needs to be updated to add AppsAndFeaturesEntries.

**Comment by Trenly** [comment]
Close with reason: Resolved by 63650;
