### ISSUE TITLE
[Package Issue]: Package.Identifer WinSCP.WinSCP

### ISSUE THREAD

**Issue by hj-collab** [microsoft/winget-pkgs#63818]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Current version is 5.21 and winget have 6 month old package of 5.19.5. No last few packages

### Steps to reproduce

winget install --id WinSCP.WinSCP

### Actual behavior

5.19.5 gets installed

### Expected behavior

5.21 should install

### Environment

```shell
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.739
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by OfficialEsco** [comment]
Well, you made it sound worse than it is and used the wrong issue template...

5.21 was released 2 days ago..
5.19.6 was the latest version which was released 4 months ago.
