### ISSUE TITLE
Installer failed with exit code: 2147748098

### ISSUE THREAD

**Issue by Dmole** [microsoft/winget-pkgs#63886]
### Brief description of your issue

winget upgrade --all

Fails.

### Steps to reproduce

winget upgrade --all

### Expected behavior

Upgrade.

### Actual behavior

    winget upgrade --all > fail_to_detect_stdout.txt
    ^H-^H\^H|^H/^H-^H\^H ^M   ^H-^H ^MFound Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 102.0.1245.30
    (1/1) Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 102.0.1245.30
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    Successfully verified installer hash
    Starting package install...
    ^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H ^MInstaller failed with exit code: 2147748098

### Environment

```shell
winget --info
    Windows Package Manager v1.2.10941
    Copyright (c) Microsoft Corporation. All rights reserved.

    Windows: Windows.Desktop v10.0.22000.708
    Package: Microsoft.DesktopAppInstaller v1.17.10941.0

    Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

    Links               
    ---------------------------------------------------------------------------
    Privacy Statement   https://aka.ms/winget-privacy
    License Agreement   https://aka.ms/winget-license
    Third Party Notices https://aka.ms/winget-3rdPartyNotice
    Homepage            https://aka.ms/winget
    Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
This issue has been reported to EdgeWebView2:

* MicrosoftEdge/WebView2Feedback/issues/2515

**Comment by denelon** [comment]
I've submitted a modified manifest:
* microsoft/winget-pkgs/pull/64638

This should help with the upgrade scenario in terms of detecting if the existing install is either user or machine based.

The error is a result of attempting to upgrade a machine-based install with user context.

We have other work in progress to detect when a package is already installed in the event the user runs `winget upgrade <package>` to switch over logically to the upgrade flow.

**Comment by denelon** [comment]
@Dmole can you try again? The changes I submitted have been merged.

**Comment by Dmole** [comment]
Edge can be upgraded in 4 ways (windows,edge,winget,manual), so instead of testing on a fresh VM, I'll just close this issue for now.
