### ISSUE TITLE
[Package Request]: Rise Media Player

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#63959]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

**Publisher:** Rise-Software
**Publisher Url:** https://github.com/Rise-Software
**Package Name:** Rise.App.Rise-Media-Player
**Description:** One media player for everything you own or stream; whether it's music or videos, online or offline Rise Media Player does it all. And it's beautiful and native with the latest version of WinUI.
**Package Version:** v0.0.171.0
**Installer URL:** https://github.com/Rise-Software/Rise-Media-Player/releases/download/v0.0.171.0/Rise.App_0.0.171.0_x86_x64_arm.msixbundle

**Current Package Identifier (for new versions):** v0.0.171.0

**Comment by KaranKad** [comment]
This software requires you to install a certificate.
`Installer failed with exit code: 0x800b0109 : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.`

**Comment by KrisSchneider** [comment]
The app is still in beta, so that is probably why the installer does not come with a certificate.

**Comment by KrisSchneider** [comment]
Also, it has good scores on virus scanning these websites: 
https://virusscan.jotti.org/en-US/filescanjob/i2s5mflc77
https://www.virustotal.com/gui/file/1d2dabc1aa20b2da8548325f0c98af430e97e46d379c2dee0d771d53e6af2cad?nocache=1

**Comment by KrisSchneider** [comment]
Oh, that's why, ok.
