### ISSUE TITLE
[Package Issue]: Mega.MEGASync

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#64093]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Winget installs a version of MegaSync that does not match the hash online.

### Steps to reproduce

1. Go to powershell
2. Enter this into the terminal:
```powershell
PS C:\Users\krist> sudo winget install -e --id Mega.MEGASync
```
3. Then you should get this output
```powershell
Found MEGAsync [Mega.MEGASync] Version 4.6.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://mega.nz/MEGAsyncSetup64.exe
  ██████████████████████████████  49.1 MB / 49.1 MB
Installer hash does not match; this cannot be overridden when running as admin
```

### Actual behavior

Winget installs a version of MegaSync that does not match the hash online.

### Expected behavior

I expected Winget to properly install MegaSync as it has done before last week.

### Environment

```shell
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1706
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Any other software? 
ScoopInstaller, gsudo (installed with scoop).
```

### Screenshots and Logs

```powershell
PS C:\Users\krist> sudo winget install -e --id Mega.MEGASync
Found MEGAsync [Mega.MEGASync] Version 4.6.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://mega.nz/MEGAsyncSetup64.exe
  ██████████████████████████████  49.1 MB / 49.1 MB
Installer hash does not match; this cannot be overridden when running as admin
```

![(WindowsTerminal)o6Q5K3_06-21-2022](https://user-images.githubusercontent.com/101912712/174886846-c833d3c5-2d6f-465c-9aff-429914cd1c9c.jpg)

**Comment by jedieaston** [comment]
This was resolved by https://github.com/microsoft/winget-pkgs/pull/64117, I believe, can you give it another shot?

**Comment by KrisSchneider** [comment]
I tried doing it again in PowerShell, this is what happened:
```powershell
PS C:\Users\krist> sudo winget install -e --id Mega.MEGASync
Found MEGAsync [Mega.MEGASync] Version 4.6.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://mega.nz/MEGAsyncSetup64.exe
  ██████████████████████████████  49.1 MB / 49.1 MB
Installer hash does not match; this cannot be overridden when running as admin
PS C:\Users\krist> winget install -e --id Mega.MEGASync
Found MEGAsync [Mega.MEGASync] Version 4.6.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://mega.nz/MEGAsyncSetup64.exe
  ██████████████████████████████  49.1 MB / 49.1 MB
Installer hash does not match; to override this check use --force
PS C:\Users\krist>
```

**Comment by KrisSchneider** [comment]
After running `winget source update`, my issue is now fixed. Thank you to those that helped me, I can now successfully install Megasync without any issues.
![(WindowsTerminal)B4G386_06-22-2022](https://user-images.githubusercontent.com/101912712/175073662-c3c5aaaf-f67b-4864-9a6d-bffaade6e262.jpg)

**Comment by hueldoeu** [comment]
very strange problem. when i check for updates 
![image](https://github.com/microsoft/winget-pkgs/assets/11273667/00e35ff2-1dc2-48bc-a047-ba94bfca66c2)
mega says it's up 2 date.
but on winget (or unigetui) i always see sometimes updates available for Mega.MEGASync, which i skip.
