### ISSUE TITLE
Integrate winget in microsoft store, to achieve a wider variety of apps there

### ISSUE THREAD

**Issue by lorisobi** [microsoft/winget-pkgs#6417]
# Description of the new feature/enhancement

The Microsoft Store lacks of many popular apps (Discord for example), but winget has these. It would be a great help for User Experience and adaption of the store, to integrate winget in the "crawler" of the MS Store. This could be similar to some linux distros, where the store is just a GUI for a CLI-package-manager. This could lead to problems about the pricing of a normal ms developer account and the free publishing here, but I think this could be solved somehow.

**Comment by denelon** [comment]
The Microsoft Store [accepts traditional applications](https://developer.microsoft.com/microsoft-store/desktop-apps/). For example, Discord is now available. This feature request is more about the store than the Windows Package Manager, so I'm going to go ahead and close this issue.

Thanks for the request!
