### ISSUE TITLE
Winget upgrade mistakes Visual C++ 2013 with SSMS

### ISSUE THREAD

**Issue by FurtadoPires** [microsoft/winget-pkgs#64630]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Having `Microsoft Visual C++ 2013 Redistributable` installed makes `winget upgrade` suggests installing `Microsoft.SQLServerManagementStudio`, the problem is that the latter is a tool to manage sql server database, while the former it's just a dependency for some old softwares.

### Steps to reproduce

-Install [Visual C++ 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (both x86 and x64 have this problem)
-Run `winget upgrade`

### Actual behavior

It's suggesting a different software as a update

### Expected behavior

It should only suggest updates to the correct software

### Environment

```shell
Version: v1.3.1681
Windows.Desktop v10.0.22000.778 X64
Microsoft.DesktopAppInstaller v1.18.1681.0
```

### Screenshots and Logs

![winget](https://user-images.githubusercontent.com/7890832/176251477-4d55bd2b-7ba3-4cec-8ec3-8f60b698d5c2.png)

**Comment by Trenly** [comment]
Close with reason: Extra ARP entries have been removed;
