### ISSUE TITLE
[Package Request]: Java Version 8 Update 333 i586 (32bit)

### ISSUE THREAD

**Issue by rvtdadmin** [microsoft/winget-pkgs#64948]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Oracle
Publisher Url: www.java.com
Package Name: Java 8 32bit
Description: Java SE runtime
Package Version: 8 Update 333
Installer URL: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=246472_2dee051a5d0647d5be72a7c0abff270e

Comments: Java 8 "64bit" is in the repository as ID: Oracle.JavaRuntimeEnvironment 
The 32bit version does not appear to be in the repository.

Current Package Identifier (for new versions): 

Thank you

**Comment by licon4812** [comment]
The package contains the installer for the 32 bit version 
![image](https://user-images.githubusercontent.com/32421608/177113125-70df4996-f3c2-441d-8d02-4c29a153b3d0.png)

**Comment by rvtdadmin** [comment]
Thank you, I was not aware of multiple installers per manifest and being able to specify architecture. 
This can be closed.
