### ISSUE TITLE
[Package Request]: Hibit.StartUpManager

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#65007]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Hibit
Publisher Url: https://www.hibitsoft.ir/
Package Name: Hibit.StartUpManager
Description: HiBit Startup Manager is a powerful Startup utility that Manage autostart programs by adding or removing apps, editing their properties and also Manage process, services, task scheduler and conrext menu.
Package Version: 2.3.20
Installer URL: https://www.hibitsoft.ir/HibitStartup/HiBitStartupManager-setup-2.3.20.exe

Current Package Identifier (for new versions): 
https://www.hibitsoft.ir/HibitStartup/HiBitStartupManager-setup-2.3.20.exe

**Comment by licon4812** [comment]
Merging now #65447
