### ISSUE TITLE
[Package Request]: CopyTrans.ControlCenter

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#65039]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: CopyTrans
Publisher Url: https://www.copytrans.net/
Package Name: CopyTrans.ControlCenter
Description: CopyTrans Control Center is the iPhone apps and documents manager. Take control over your favorite iPhone apps and app data and keep them safe.
Package Version: 5.003
Installer URL: https://www.copytrans.net/bin/Install_CopyTransControlCenter.exe

Current Package Identifier (for new versions): 
https://www.copytrans.net/bin/Install_CopyTransControlCenter.exe

**Comment by Masamune3210** [comment]
Manifest submitted
