### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by Unicornninja80** [microsoft/winget-pkgs#65045]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Smile
Publisher Url: https://smilesoftware.com/
Package Name: Text Expander
Description: Create snippets of text for support responses, sales outreach, or even common emails and save them in TextExpander.
Package Version: 7.2 (720.16)
Installer URL: https://textexpander.com/download
Current Package Identifier (for new versions):

**Comment by licon4812** [comment]
Attempting to merge now #65116
