### ISSUE TITLE
Badges aren't working :(

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#65273]
It looks like whatever service backs up the badges isn't working properly.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/21368066/177611541-310f357b-75c0-4a88-9eaa-08d6c5bb54aa.png">

(https://github.com/microsoft/winget-pkgs/pull/65272#issuecomment-1176498022)

**Comment by vedantmgoyal2009** [comment]
The issue has been fixed now and can be closed.

**Comment by jedieaston** [comment]
It's broken again :(

<img width="768" alt="image" src="https://user-images.githubusercontent.com/21368066/177764690-15d2c7e2-fbf5-4baf-9974-cd27af583979.png">

**Comment by ItzLevvie** [comment]
![Validation Pipeline Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=ValidationPipeline "Validation Pipeline Badge") ![Publish Pipeline Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=PublishPipeline "Publish Pipeline Badge")

**Comment by jedieaston** [comment]
Maybe my browser was caching weird, it looks fine for me now. Closing again...
