### ISSUE TITLE
[Package Issue]: PeterPawlowski.foobar2000

### ISSUE THREAD

**Issue by YauhenPylAurea** [microsoft/winget-pkgs#65280]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Tried to install `PeterPawlowski.foobar2000`

### Steps to reproduce

```
winget install PeterPawlowski.foobar2000
```

### Actual behavior

It reports that the app is installed but the installer has not been run,
```
Found foobar2000 [PeterPawlowski.foobar2000] Version 1.6.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foobar2000.org/files/foobar2000_v1.6.11.exe
  ██████████████████████████████  4.55 MB / 4.55 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

### Expected behavior

Foobar installer must be run

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1766
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/42114592/177635157-828dd1fd-7d71-46a1-ad60-7592a09843be.png)

**Comment by Trenly** [comment]
Can you provide the log files that are generated when you run `winget install PeterPawlowski.foobar2000 --verbose-logs` ?

The application installs fine for me
![image](https://user-images.githubusercontent.com/12611259/177637105-94da0493-8ebb-4585-aede-239e77be5479.png)

**Comment by YauhenPylAurea** [comment]
sorry, where can I find log file at my system ? :)

**Comment by Trenly** [comment]
Location of the logs can be seen in `winget --info`

**Comment by YauhenPylAurea** [comment]
[WinGet-2022-07-06-23-15-47.601.log](https://github.com/microsoft/winget-pkgs/files/9058068/WinGet-2022-07-06-23-15-47.601.log)

**Comment by YauhenPylAurea** [comment]
Just run once again and there is another log file
[WinGet-2022-07-06-23-22-44.927.log](https://github.com/microsoft/winget-pkgs/files/9058081/WinGet-2022-07-06-23-22-44.927.log)
Hope it will help
