### ISSUE TITLE
[Package Issue]: geeksoftwareGmbH.PDF24Creator should be updated to the latest version

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#65308]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Why is geeksoftwareGmbH.PDF24Creator not updated to version 11.2.0? It's currently at version 10.8.0. 
Here is the link for the latest version: https://download1.pdf24.org/pdf24-creator-11.2.0.exe.

### Steps to reproduce

N/A

### Actual behavior

N/A

### Expected behavior

N/A

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1806
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![(WindowsTerminal)e9a3D1_07-06-2022](https://user-images.githubusercontent.com/101912712/177685817-d40253cc-0dce-47dd-9b1c-0472a656b5cb.jpg)

**Comment by treysis** [comment]
11.3.0 is out for weeks and also hasn't been made available.

**Comment by mdanish-kh** [comment]
> 11.3.0 is out for weeks and also hasn't been made available.

@treysis Package has been updated to `11.3.0`.
