### ISSUE TITLE
[Package Request]: SublimeHQ.SublimeMerge

### ISSUE THREAD

**Issue by TaliaFlor** [microsoft/winget-pkgs#65636]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Sublime HQ Pty Ltd
Publisher Url: https://www.sublimehq.com
Package Name: Sublime Merge
Description:  Git GUI client from the makers of Sublime Text
Package Version: 2074
Installer URL: https://download.sublimetext.com/sublime_merge_build_2074_x64_setup.exe

Current Package Identifier (for new versions): SublimeHQ.SublimeMerge

**Comment by Masamune3210** [comment]
Manifest Submitted

**Comment by Masamune3210** [comment]
Sorry, would have linked the PR if I could and knew how

**Comment by denelon** [comment]
Here is an example:
https://github.com/microsoft/winget-pkgs/pull/65943#issue-1302560366

**Comment by Masamune3210** [comment]
Sweet, thanks for the info, I'll do that from now on
