### ISSUE TITLE
Amazon.AWSCLI Install has verification failed

### ISSUE THREAD

**Issue by ronorato** [microsoft/winget-pkgs#659]
I was attempting to install Amazon.AWSCLI today using winget and received a warning that the installer has failed verification.  Due to this mismatch I canceled the installer to prevent a possible security issue on my system. 
The following are the commands that I executed when installing:

    winget install -h -e Amazon.AWSCLI
    
    Found AWS Command Line Interface v2 [Amazon.AWSCLI]
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    Downloading https://awscli.amazonaws.com/AWSCLIV2.msi

    Installer hash verification failed. Continue? (Y|N)
    Canceled; Installer hash mismatch

System information:
- Hardware: SurfaceBook 2 with latest SurfacBook 2 patches
- OS: Windows 10 Pro, 2004, Build: 19041.264
- Windows Insider Program enabled for slow
- Developer settings
  - Developer Mode is on
  - Device Portal off
  - Device discovery off
  - PowerShell policy has been set to run all scripts

**Comment by LukasNespor** [comment]
It seems that link https://awscli.amazonaws.com/AWSCLIV2.msi points to latest 2.x.x version so the hash does not match.

**Comment by ronorato** [comment]
I did end up just installing the CLI via the Amazon site.  My goal is to create a PowerShell script to help rebuild my laptop after I complete an engagement.

**Comment by jamierocks** [comment]
I've opened https://github.com/microsoft/winget-pkgs/pull/682 to remove the current awscli 2.0 manifest, as its clearly broken.

**Comment by jamierocks** [comment]
This has been resolved with https://github.com/microsoft/winget-pkgs/commit/dc0deabf47897aeb7ee1e36529a08d82cc621bf6.

**Comment by superusercode** [comment]
It is possible to get static links to the AWS CLI

i.e. https://awscli.amazonaws.com/AWSCLIV2-2.0.15.msi

**Comment by superusercode** [comment]
See https://chocolatey.org/packages/awscli#files for examples on how to get static versions of the AWS CLI binary links

**Comment by jamierocks** [comment]
Thanks @superusercode! I've opened another PR to re-add aws-cli v2 (https://github.com/microsoft/winget-pkgs/pull/820).

**Comment by denelon** [comment]
We now have automation that will generate a new manifest if the installer has changed at the URL. Does that resolve this issue?
