### ISSUE TITLE
[Package Request]: add WindscribeVPN

### ISSUE THREAD

**Issue by Zliced13** [microsoft/winget-pkgs#65944]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Windscribe
Publisher Url: https://windscribe.com/
Package Name: Windscribe.WindscribeVPN
Description: Windscribe encrypts your browsing activity, blocks ads, and unblocks entertainment content.
Package Version: v2.4.11
Installer URL: https://github.com/Windscribe/Desktop-App/releases/download/v2.4.11/Windscribe_2.4.11.exe

Current Package Identifier (for new versions): 
https://github.com/Windscribe/Desktop-App/releases/download/v2.4.11/Windscribe_2.4.11.exe

**Comment by KrisSchneider** [comment]
Should I close this issue?

**Comment by Zliced13** [comment]
@licon4182

**Comment by licon4812** [comment]
> @licon4812

Ok I will take a look
