### ISSUE TITLE
[Package Issue]: MarkText.MarkText

### ISSUE THREAD

**Issue by fxha** [microsoft/winget-pkgs#66517]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The `marktext.app` domain (`PackageUrl`) of the MarkText package is no longer owned by the MarkText organization and must be removed or replaced by `github.com/marktext/marktext` due to security concerns. See https://github.com/marktext/marktext/issues/3348.

### Steps to reproduce

.

### Actual behavior

Old domain is present.

### Expected behavior

Link to GitHub repository or remove outdated domain.

### Environment

```shell
.
```

**Comment by russellbanks** [comment]
Resolved
