### ISSUE TITLE
[Package Request]: Dewvpn

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#66541]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Dewvpn
Publisher Url: https://www.dewvpn.com/
Package Name: Dewvpn
Description: a free VPN
Package Version:  1.2
Installer URL: https://d87hw114pqw7b.cloudfront.net/dewvpn-setup.exe

Current Package Identifier (for new versions): 1.2

**Comment by Trenly** [comment]
Unfortunately the website for dewvpn no longer exists and the installer URL results in 404.
