### ISSUE TITLE
[Package Request]: topgrade

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#66558]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: https://github.com/topgrade-rs
Publisher Url: https://github.com/topgrade-rs/topgrade
Package Name: topgrade
Description: Keeping your system up to date usually involves invoking multiple package managers. This results in big, non-portable shell one-liners saved in your shell. To remedy this, topgrade detects which tools you use and runs the appropriate commands to update them.
Package Version: 11.0.2
Installer URL: https://github.com/topgrade-rs/topgrade/releases/download/v11.0.2/topgrade-v11.0.2-x86_64-pc-windows-msvc.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
Blocked by microsoft/winget-cli#140

@soredake - This isn’t the first time I’ve mwntioned that **.zip files are not yet supported**

https://github.com/microsoft/winget-pkgs/issues/61766#issuecomment-1134994407

I’m asking that you refrain from opening issues requesting packages distributed as .zip files until the client supports them, as creating these issues now is needlessly clogging up the issues queue
