### ISSUE TITLE
[Package Request]: Autoruns

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#66554]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Microsoft
Publisher Url: https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns
Package Name: autoruns
Description: This utility, which has the most comprehensive knowledge of auto-starting locations of any startup monitor, shows you what programs are configured to run during system bootup or login, and when you start various built-in Windows applications like Internet Explorer, Explorer and media players. These programs and drivers include ones in your startup folder, Run, RunOnce, and other Registry keys. Autoruns reports Explorer shell extensions, toolbars, browser helper objects, Winlogon notifications, auto-start services, and much more. Autoruns goes way beyond other autostart utilities.
Package Version: 14.09
Installer URL: https://download.sysinternals.com/files/Autoruns.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
Blocked by microsoft/winget-cli#140

**Comment by Ramoonus** [comment]
You can try the Microsoft sysinternals package

**Comment by ItzLevvie** [comment]
It'll be coming soon: https://github.com/microsoft/winget-pkgs/pull/68811

**Comment by Trenly** [comment]
Close with reason: Merged #68811;

**Comment by adripo** [comment]
Can you create also 64bit package, please?
