### ISSUE TITLE
[Package Request]: GlosSI

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#66555]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: https://github.com/Alia5
Publisher Url: https://github.com/Alia5/GlosSI
Package Name: GlosSI
Description:  Tool for using Steam-Input controller rebinding at a system level alongside a global overlay 
Package Version: 0.0.7.0
Installer URL: https://github.com/Alia5/GlosSI/releases/download/0.0.7.0/GlosSI-0.0.7.0.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
Blocked by microsoft/winget-cli#140

@soredake - This isn’t the first time I’ve mwntioned that **.zip files are not yet supported**

https://github.com/microsoft/winget-pkgs/issues/61766#issuecomment-1134994407

I’m asking that you refrain from opening issues requesting packages distributed as .zip files until the client supports them, as creating these issues now is needlessly clogging up the issues queue

**Comment by Trenly** [comment]
I took a look at this now that .zip is supported.

Unfortunately the newest releases use a token which is unique when the download link is clicked and the file will not download without it.  https://glossi.flatspot.pictures/api/download/GlosSI-0.1.2.0?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmODg3NGJmMC04ZDUxLTRjMjYtOGY4ZC01N2M3NmI3YWZkMDIiLCJpYXQiOjE3MDYyMzY1MjMsImV4cCI6MTcwNjIzNjY0M30.r5WNPJrz8iWa3FVYGR19OAYzJAdy1gjbjX4ZOhLgP7A&installer=1
