### ISSUE TITLE
[Package Request]: NSudo

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#66557]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: https://github.com/M2Team
Publisher Url: https://github.com/M2Team/NSudo
Package Name: NSudo
Description:  Series of System Administration Tools 
Package Version: 8.2
Installer URL: https://github.com/M2Team/NSudo/releases/download/8.2/NSudo_8.2_All_Components.zip

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
Blocked by microsoft/winget-cli#140

@soredake - This isn’t the first time I’ve mwntioned that **.zip files are not yet supported**

https://github.com/microsoft/winget-pkgs/issues/61766#issuecomment-1134994407

I’m asking that you refrain from opening issues requesting packages distributed as .zip files until the client supports them, as creating these issues now is needlessly clogging up the issues queue

**Comment by Trenly** [comment]
![image](https://github.com/microsoft/winget-pkgs/assets/12611259/1f6d71ea-3bc1-4db7-b6e1-9ac46af241f2)
https://www.virustotal.com/gui/file/346e38030cc9eeef48223804ba27631db96691d68bfc5d1728140d468f555204

Close with reason: Defender scan reports malware; NSudo Repository is archived
