### ISSUE TITLE
[Package Issue]: Git.Git 2.37.1

### ISSUE THREAD

**Issue by albertosantini** [microsoft/winget-pkgs#66568]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Git.Git 2.37.1 manifest has been approved, but Git 2.37.0 is not updated.

### Steps to reproduce

$  winget upgrade
No installed package found matching input criteria.

### Actual behavior

$ winget list Git.Git
Name Id      Version Source
----------------------------
Git  Git.Git 2.37.0  winget

$  winget upgrade
No installed package found matching input criteria.

### Expected behavior

Update from Git 2.37.0 to 2.37.1

### Environment

```shell
$ winget --info
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
This is because it has not been published yet - Note the [PR](https://github.com/microsoft/winget-pkgs/pull/66443) does not have the Publish-Pipeline-Succeeded label on it.

Currently the publishing pipelines are experiencing issues and I’ve notified @denelon on Gitter; I’ll also tag @JohnMcPMS @hackean-msft and @ryfu-msft here since I know Denelon is on PTO

**Comment by albertosantini** [comment]
@Trenly Thanks for the details and the effort to resolve the issues about the pipelines.
 
I was asking because I submitted for the first time an unpdate for that manifest, then another contributor pushed another update, and I was not sure if I did something wrong.

Closing the issue.
