### ISSUE TITLE
[Package Request]: add Hekasoft Backup and Restore

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#66865]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Hekasoft
Publisher Url: https://hekasoft.com/
Package Name: Hekasoft.Backup-Restore
Description: An all-in-one solution to manage your browser data and settings. Backup your favourite browser’s settings in a single file that you can store on an external drive or CD-ROM and use it to restore the profile.
Package Version: 0.95
Installer URL: https://download.fosshub.com/Protected/expiretime=1658315926;badurl=aHR0cHM6Ly93d3cuZm9zc2h1Yi5jb20vSGVrYXNvZnQtQmFja3VwLVJlc3RvcmUuaHRtbA==/7d6ced016128cb6137e3e4e6b7ec41359201533eeef37fc498062053a8a16539/5df684a55ad943080c4c98f4/5ff9f8a295b5643a1f06a8d5/backup-restore-0.95.exe

Current Package Identifier (for new versions): 
https://download.fosshub.com/Protected/expiretime=1658315926;badurl=aHR0cHM6Ly93d3cuZm9zc2h1Yi5jb20vSGVrYXNvZnQtQmFja3VwLVJlc3RvcmUuaHRtbA==/7d6ced016128cb6137e3e4e6b7ec41359201533eeef37fc498062053a8a16539/5df684a55ad943080c4c98f4/5ff9f8a295b5643a1f06a8d5/backup-restore-0.95.exe

**Comment by KrisSchneider** [comment]
If the installer URL does not work. 
Try MajorGeeks: 
https://files2.majorgeeks.com/c87b3b366e7d53480945584d110a7f035772a3a5/backup/backup-restore-0.95.exe
https://files1.majorgeeks.com/10afebdbffcd4742c81a3cb0f6ce4092156b4375/backup/backup-restore-0.95.exe

Or Author's website:
https://hekasoft.com/download/download-hekasoft-backup-restore/?wpdmdl=1261&masterkey=XdB0Cktf-b2svT1kEhkYkdrQPi9_ffCYWgrODRykQfWI9SCIA_hzuy1a0YY4AvrCrwHCZCFpmECAxihh1kbyQWQdrsQpgShbdCvJB5BZ4SY

**Comment by Trenly** [comment]
For whomever creates the manifest (If anyone does it before I get around to it) - I know that Fosshub’s ToS don’t allow us to use their URLs, and so we will need to use the hekasoft url
