### ISSUE TITLE
[Package Request]: jdownloader

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#66923]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: jdownloader
Publisher Url: https://jdownloader.org/
Package Name: jdownloader
Description: download manager written in Java
Package Version: 2.0
Installer URL: https://sdl.adaware.com/?bundleid=JD001&savename=JDownloaderSetup.exe

Current Package Identifier (for new versions): 2.0

**Comment by aman207** [comment]
jdownloader 2 is already has a manifest

https://github.com/microsoft/winget-pkgs/blob/f9c0c9e656521c1a66bb7b89cb0b32bc921ff251/manifests/a/AppWork/JDownloader/2.0/AppWork.JDownloader.locale.en-US.yaml

**Comment by ItzLevvie** [comment]
Close with reason: Package exists;

**Comment by denelon** [comment]
@Trenly it looks like we need a similar rule for Issues.

**Comment by Trenly** [comment]
> @Trenly it looks like we need a similar rule for Issues.

Will do!
