### ISSUE TITLE
[Package Issue]: Move Neotys.NeoLoad to Tricentis.NeoLoad

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-pkgs#66937]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

[Neotys has been acquired by Tricentis](https://www.tricentis.com/blog/announcing-tricentis-neotys-acquisition/) and new versions (`7.8.1` onwards) of [Neotys.NeoLoad](https://github.com/mdanish-kh/winget-pkgs/tree/master/manifests/n/Neotys/NeoLoad) have `Tricentis` in the publisher field instead of `Neotys`.

![image](https://user-images.githubusercontent.com/88161975/179945920-455da16e-4662-4234-ad4c-f82adbbe241c.png)

Should I move this [8.0.0 manifest](https://github.com/mdanish-kh/winget-pkgs/tree/master/manifests/n/Neotys/NeoLoad/8.0.0) from `Neotys.NeoLoad` to `Tricentis.NeoLoad` (and update its metadata) and add newer versions in the new directory? Or should I add the newer versions in the old directory?

Secondly (if moderators approve the move), what about the old versions (`7.3` to `7.8.1`) present in [Neotys.NeoLoad](https://github.com/mdanish-kh/winget-pkgs/tree/master/manifests/n/Neotys/NeoLoad) directory? Should we get rid of them or should they remain in the old directory? They might be a cause of confusion for the user as then two same packages would be under different publisher directories.

### Steps to reproduce

.

### Actual behavior

.

### Expected behavior

.

### Environment

```shell
.
```

**Comment by denelon** [comment]
@Trenly

I agree with your suggestion. This process would help considerably. Our longer-term solution is likely to be a combination of:
* https://github.com/microsoft/winget-cli/issues/1900
* https://github.com/microsoft/winget-cli/issues/1899

I've seen this come up a few times now. I'm not sure where the best place is to document this as a recommended practice. Maybe it's time for an F.A.Q. What are your thoughts on this?

**Comment by Trenly** [comment]
> @Trenly
> 
> I agree with your suggestion. This process would help considerably. Our longer-term solution is likely to be a combination of:
> 
> * [Package Tombstones winget-cli#1900](https://github.com/microsoft/winget-cli/issues/1900)
> * [Support redirecting manifests winget-cli#1899](https://github.com/microsoft/winget-cli/issues/1899)
> 
> I've seen this come up a few times now. I'm not sure where the best place is to document this as a recommended practice. Maybe it's time for an F.A.Q. What are your thoughts on this?

I think an FAQ would be good; I think special topics of interest would be Publisher changes / acquisitions as mentioned here, Zip support, Common causes of “No installed package found matching criteria” when trying to upgrade, What is an ARP Entry, Issues with Unknown package version, issues with Disambiguation of side-by-side installs (VC++ / Dotnet), etc.

If there were a central place like an FAQ that we could reference to all of the “common issues” that we see, it would be great. 

I propose we use our Blind Pair Programming group on Gitter to gather opinions, then I can create a draft markdown file and we can get it published

**Comment by mdanish-kh** [comment]
Resolved through #66947 and #66948. This may be closed if it needs no further discussion.

**Comment by denelon** [comment]
We now have an [F.A.Q](https://github.com/microsoft/winget-pkgs/blob/master/FAQ.md) thanks to @Trenly.

**Comment by Trenly** [comment]
Just leaving this here - Validated the transition is working as expected:
```raw
PS C:\Windows\system32> winget show Neotys.Neoload --versions
Found NeoLoad [Neotys.NeoLoad]
Version
-------
8.0.0
7.8.1
7.7.0
7.6.0
7.5.1
7.4.0
7.3
PS C:\Windows\system32> winget install Neotys.NeoLoad -v 7.8.1
Found NeoLoad [Neotys.NeoLoad] Version 7.8.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://d24mnm5myvorwj.cloudfront.net/documents/download/neoload/v7.8/neoload_7_8_1_windows_x64.exe
  ██████████████████████████████   360 MB /  360 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Windows\system32> winget list NeoLoad
Name    Id             Version Available
----------------------------------------
NeoLoad Neotys.NeoLoad 7.8.1   8.0.0
PS C:\Windows\system32> winget upgrade Neotys.NeoLoad
Found NeoLoad [Neotys.NeoLoad] Version 8.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://d24mnm5myvorwj.cloudfront.net/documents/download/neoload/v8.0/neoload_8_0_0_windows_x64.exe
  ██████████████████████████████   358 MB /  358 MB
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Successfully installed
PS C:\Windows\system32> winget list NeoLoad
Name    Id                Version
---------------------------------
NeoLoad Tricentis.NeoLoad 8.0.0
PS C:\Windows\system32> winget -v
v1.2.10271
```
