### ISSUE TITLE
[Package Issue]: TorProject.TorBrowser are installing to desktop and not creating a link on desktop

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#66932]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After installing a package a i see just a folder on desktop, and no link.

### Steps to reproduce

Install TorProject.TorBrowser.

### Actual behavior

Package is installed to desktop folder and no link is created.

### Expected behavior

Package should be installed to %LOCALAPPDATA% and desktop link should be created. 

### Environment

```shell
Диспетчер пакетов Windows v1.3.1741
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.22000.556
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.18.1741.0

Журналы: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by soredake** [comment]
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/tor-browser/tools/chocolateyInstall.ps1#L17

**Comment by Trenly** [comment]
This has always been how Tor installs by default. Winget does not posess the ability to modify this currently

**Comment by KaranKad** [comment]
Also Tor Browser installer installs itself as a portable application, hence winget is unable to update it. We need winget to treat this application as a portable one but installed using a installer.

**Comment by NJT145** [comment]
you can use `--location="$env:LOCALAPPDATA\Tor Browser"` or `--location="%LOCALAPPDATA%\Tor Browser"` to install it in LOCALAPPDATA.
I am using this code to install it (on powershell): 
```
winget install -e -i --id=TorProject.TorBrowser --location="$env:LOCALAPPDATA\Tor Browser" --source=winget --scope=user
```
I am using `-i` option in order to check any issues happens on auto install. You can safely ignore it.
The only missing automation is to select language of installer.
And, do you know how I can register Tor Browser as an app on Windows 10 ? Tor Browser is totally portable and winget cannot upgrade it.

**Comment by luzpaz** [comment]
Requesting updated of package to v12.5 (see https://github.com/microsoft/winget-pkgs/issues/111119)
