### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by stilett0** [microsoft/winget-pkgs#67041]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Spicebrains
Publisher Url: http://instant-eyedropper.com/
Package Name: Instant Eyedropper
Description: 
Package Version: 2.0.1
Installer URL: http://instant-eyedropper.com/download/instant-eyedropper-2.0.1.exe

Current Package Identifier (for new versions): Spicebrains.Instant-Eyedropper

They haven't updated their homepage yet, but they uploaded and linked the executable on June 7th, 2022.

**Comment by mdanish-kh** [comment]
Blocked by Microsoft Defender SmartScreen

![image](https://user-images.githubusercontent.com/88161975/180298288-d5ef6531-691b-4a22-be30-19e8cfb904de.png)

**Comment by denelon** [comment]
If this application becomes unblocked by Microsoft Defender SmartScreen, the request may be reopened.

**Comment by Trenly** [comment]
@mdanish-kh - Did this fail SmartScren on the Pipelines or in the Sandbox? If it failed in the sandbox it could be due to the unknown publisher value and would likely pass validation pipelines through the full SmartScreen scan

**Comment by mdanish-kh** [comment]
> @mdanish-kh - Did this fail SmartScren on the Pipelines or in the Sandbox? If it failed in the sandbox it could be due to the unknown publisher value and would likely pass validation pipelines through the full SmartScreen scan

I'm afraid I don't know the difference between the two (maybe Microsoft Defender SmartScreen behavior can be addressed in FAQ?). I also haven't checked in Sandbox as I don't own the Pro version of Windows (I always validate and install my manifests in a VM). What I'm understanding is that I'm being asked whether I checked this through Azure pipelines by creating a PR or did I run this locally? To that question, I just ran the installer locally and it showed me this prompt. I assumed that we don't include packages that are blocked through SmartScreen preventing a true silent install. Please correct me if I'm assuming wrong.

**Comment by OfficialEsco** [comment]
@mdanish-kh that message dosn't actually mean that its blocked by SmartScreen, its more like a "Unknown Hash Detected".
AFAIK the VM's also have this prompt disabled so it won't get stuck on "Unattended", if you make a PR with this installer it will run trough multiple AV's and most likely get accepted and this prompt will go away.
