### ISSUE TITLE
[Package Issue]: WiresharkFoundation.Wireshark out of date development release

### ISSUE THREAD

**Issue by mivsvit** [microsoft/winget-pkgs#67066]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

In [ New version: WiresharkFoundation.Wireshark version 3.7.0.0 #60496 ](https://github.com/microsoft/winget-pkgs/pull/60496) Wireshark was changed to the development release 3.7.0 not the stable release.  As per https://www.wireshark.org/#download the current stable release is 3.6.6  and the development release is 3.7.1 not 3.7.0:

_"[Stable Release (3.6.6) • June 15, 2022](https://www.wireshark.org/#group_873)
[Old Stable Release (3.4.14) • May 4, 2022](https://www.wireshark.org/#group_890)
[Development Release (3.7.1) • June 27, 2022](https://www.wireshark.org/#group_899)"_

### Steps to reproduce

```
C:\Users\UserName>winget search wireshark
Name      Id                            Version Source
-------------------------------------------------------
Wireshark WiresharkFoundation.Wireshark 3.7.0.0 winget
```
Check https://www.wireshark.org/#download for stable and development versions.

### Actual behavior

winget is offering an out of date development release of Wirehark (version 3.7.0). 

### Expected behavior

winget should offer the stable release (currently version 3.6.6). 

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by ItzLevvie** [comment]
Will upload a new stable release to WinGet.
