### ISSUE TITLE
P.S.A. Submitting Portable Packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#67263]
### Public Service Announcement

We will be holding submissions for portable packages until the Windows Package Manager1.3 client has rolled out to more than half of the installed user base.

You may still submit a PR for one of these packages, but it will be labeled with "Blocking-Issue" and ".exe"

**Note:** We've added [Microsoft.NuGet](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/NuGet) to test end-to-end scenarios with Windows Package Manager 1.3 release candidate builds. It will throw an error on earlier versions as the new "portable" package type isn't supported in earlier versions.

FYI, I'm aiming to open up 1.2 schema validation in the community repository ~tomorrow August 9th, 2022 (EOD Pacific Time). (edit: 8/9)~ by Tuesday August 16th. (edit 9/13).

**Comment by denelon** [comment]
We can't. 

We have to make some broad assumptions about the telemetry we receive from clients that do have it enabled and apply a multiplier. We have a "reasonable" idea about how many users install Windows Insider Builds, and we know about how long it takes for things to roll out there.

**Comment by vedantmgoyal2009** [comment]
That's mathematics again.

![image](https://user-images.githubusercontent.com/83997633/180823202-716a9038-dcd1-44d3-964f-ca9c120b317c.png)

**Comment by JakobDev** [comment]
When will winget 1.3 be released?

**Comment by russellbanks** [comment]
Is there a tool for creating 1.2 manifests yet (for portable packages)

**Comment by ItzLevvie** [comment]
@Trenly has been working on an update for YamlCreate.ps1 to support schema 1.2.0 which is available at https://github.com/Trenly/winget-pkgs/blob/Manifest1.2/Tools/YamlCreate.ps1

**Comment by denelon** [comment]
We will be updating wingetcreate as soon as well.

**Comment by denelon** [comment]
Updated to Tuesday August 16th.

**Comment by denelon** [comment]
I was out yesterday. I've confirmed the team is working on deploying the changes now.

**Comment by denelon** [comment]
Portable package validation is now available.
