### ISSUE TITLE
[Package Issue]: Rustlang.Rustup is outdated and can't detect version.

### ISSUE THREAD

**Issue by WinkelCode** [microsoft/winget-pkgs#67393]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Rustlang.Rustup is outdated and can't detect version.

### Steps to reproduce

Have Rustup installed, then run `winget upgrade` and check the output.

Note: I un- and re-installed Rustup from the website, behavior is still the same.

### Actual behavior

Rustup version isn't detected:
![image](https://user-images.githubusercontent.com/29005772/180715928-af3b69a4-f713-4fea-a3d4-7fd13298aeec.png)
Rustup is now on v1.25.1, WinGet is still on 1.24.4.
![image](https://user-images.githubusercontent.com/29005772/180715951-240a530a-c335-4572-b912-95a2b2aaedc1.png)

### Expected behavior

Version is detected and rustup is hopefully up-to-date.

### Environment

```shell
Windows Package Manager v1.2.11601
Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by Trenly** [comment]
The reason the version is “Unknown” is because the installer never sets the DisplayVersion key to tell Windows what version of the software is installed. The only way to fix the unknown version is to have the publisher make changes to their build script so that the installer sets the version when installing

**Comment by jedieaston** [comment]
I just opened a PR to fix the version, at least, although @Trenly is right about your other issue.

**Comment by jedieaston** [comment]
And I opened a PR to fix the issue on the Rustup side: https://github.com/rust-lang/rustup/pull/3047

**Comment by martinsstuff** [comment]
> The reason the version is “Unknown” is because the installer never sets the DisplayVersion key to tell Windows what version of the software is installed. The only way to fix the unknown version is to have the publisher make changes to their build script so that the installer sets the version when installing

Should software like this even be on WinGet then? Having one of these programs installed makes it redownload the installer every time `winget upgrade --all` is executed.

**Comment by jedieaston** [comment]
There's a mitigation for the infinite upgrade problem in winget 1.3, which should be released shortly into stable: https://github.com/microsoft/winget-cli/pull/1765

(You can also install a release candidate build to get it now: https://github.com/microsoft/winget-cli/releases/tag/v1.3.1872)

**Comment by dmad** [comment]
I've "solved" the issue for now by manually creating (and updating) the DisplayVersion key:

`
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Rustup]
"DisplayVersion"="1.64.0"
`

**Comment by Trenly** [comment]
> And I opened a PR to fix the issue on the Rustup side: [rust-lang/rustup#3047](https://github.com/rust-lang/rustup/pull/3047/files)

@msftbot Installer-Issue
@msftbot Area-External

**Comment by anarelion** [comment]
We should properly format the download URLs like in #95599 , any version upgrade will break the SHA256 and make this package impossible to install.

**Comment by fbstj** [comment]
rust-lang/rustup#3047 should have fixed this in version [1.25.2](https://github.com/rust-lang/rustup/releases/tag/1.25.2) released last week

**Comment by mcdonaldjc** [comment]
> [rust-lang/rustup#3047](https://github.com/rust-lang/rustup/pull/3047) should have fixed this in version [1.25.2](https://github.com/rust-lang/rustup/releases/tag/1.25.2) released last week

I still have the issue on 1.25.2

**Comment by gotounix** [comment]
@mcdonaldjc https://github.com/rust-lang/rustup/pull/3047/ is not in `1.25.2`, so it's not fixed in `1.25.2`.

**Comment by mcdonaldjc** [comment]
> @mcdonaldjc [rust-lang/rustup#3047](https://github.com/rust-lang/rustup/pull/3047) is not in `1.25.2`, so it's not fixed in `1.25.2`.

My bad. I must be confused because 1.25.2 was released on 2023-02-01. Yet, that pull request was merged into the master branch on 2022-08-27. What am I missing here? Not trying to be a nuisance.

**Comment by khaneliman** [comment]
> > @gotounix [rust-lang/rustup#3047](https://github.com/rust-lang/rustup/pull/3047) is not in `1.25.2`, so it's not fixed in `1.25.2`.
> 
> My bad. I must be confused because 1.25.2 was released on 2023-02-01. Yet, that pull request was merged into the master branch on 2022-08-27. What am I missing here? Not trying to be a nuisance.

Not sure what their git flow is, but i see it in the upcoming version changelog. https://github.com/rust-lang/rustup/pull/3273/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR49

**Comment by mcdonaldjc** [comment]
@khaneliman, that's nice, thanks. It looks like it can be merged into the master branch but not go out with their releases. Guess I can look forward to it soon!

**Comment by supleed2** [comment]
Ran `winget install Rustlang.Rustup --force` just now which installed v1.26.0 and now winget detects the rustup version correctly, this issue seems to be solved :)

**Comment by ItzLevvie** [comment]
Close with reason: See above;
