### ISSUE TITLE
[Package Issue]: ViGEm.ViGEmBus

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#67408]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

```
❯ winget install -h --accept-package-agreements --accept-source-agreements ViGEm.ViGEmBus
Found ViGEm Bus Driver [ViGEm.ViGEmBus] Version 1.18.367
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
```

### Steps to reproduce

do `winget install -h --accept-package-agreements --accept-source-agreements ViGEm.ViGEmBus`

### Actual behavior

Installer failed with exit code: 1603

### Expected behavior

Driver installed fine.

### Environment

```shell
❯ winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
I believe this is due to https://github.com/microsoft/winget-cli/issues/2365 as the installer is an MSI packaged inside of an exe. 

@soredake - Can you try installing using the latest version of the 1.3 build instead?

**Comment by soredake** [comment]
@Trenly still fails with the same error.

**Comment by cobalt2727** [comment]
Can confirm this happens to me as well.

**Comment by soredake** [comment]
As of now with recent version of windows/winget i can install vigembus package without 1603 error.
