### ISSUE TITLE
[Package Issue]: AppWork.JDownloader

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#67407]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

```
❯ winget install -h --accept-package-agreements --accept-source-agreements AppWork.JDownloader
Found JDownloader 2 [AppWork.JDownloader] Version 2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```

### Steps to reproduce

do `winget install -h --accept-package-agreements --accept-source-agreements AppWork.JDownloader`

### Actual behavior

Installer failed with exit code: 1

### Expected behavior

App installed fine.

### Environment

```shell
❯ winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
Can you please provide the logs that are generated when trying to install the package?

**Comment by soredake** [comment]
@Trenly how can i provide a logs?

**Comment by Trenly** [comment]
Run the command to install the application, then go to your logs directory (can be found with `winget --info`) and attach it to a comment here

**Comment by soredake** [comment]
[WinGet-2022-07-25-17-06-47.243.log](https://github.com/microsoft/winget-pkgs/files/9181865/WinGet-2022-07-25-17-06-47.243.log)

**Comment by soredake** [comment]
Package still fails to be installed from normal terminal windows, but installs fine from elevated. 

Maybe adding `ElevationRequirement: elevationRequired` will fix installation.
