### ISSUE TITLE
[Package Issue]: ViGEm.HidHide

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#67409]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

```
❯ winget install -h --accept-package-agreements --accept-source-agreements ViGEm.HidHide
Found HidHide [ViGEm.HidHide] Version 1.2.98
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
```

### Steps to reproduce

do `winget install -h --accept-package-agreements --accept-source-agreements ViGEm.HidHide`

### Actual behavior

Installer failed with exit code: 1603

### Expected behavior

Driver installed fine.

### Environment

```shell
❯ winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
I believe this is due to https://github.com/microsoft/winget-cli/issues/2365 as the installer is an MSI packaged inside of an exe. 

@soredake - Can you try installing using the latest version of the 1.3 build instead?

**Comment by soredake** [comment]
@Trenly still fails with the same error.

**Comment by soredake** [comment]
Now winget fails with all packages using msi....

**Comment by Trenly** [comment]
It installs fine for me; Given that it is error 1603, I'm almost certain that it is because of this, especially given @jedieaston's latest comment in https://github.com/microsoft/winget-cli/issues/2365
> The SYSTEM account does not have Full Control permissions on the folder that you are trying to install the Windows Installer package to. You notice the error message because the Windows Installer service uses the SYSTEM account to install software.

![image](https://user-images.githubusercontent.com/12611259/180795094-4da21780-d5de-4984-b90d-57ee19512602.png)
![image](https://user-images.githubusercontent.com/12611259/180795196-f75ef700-db1e-4a95-b021-0612bb35e94c.png)


> Now winget fails with all packages using msi....

Yes, see https://github.com/microsoft/winget-cli/issues/2365

**Comment by soredake** [comment]
> Yes, see [microsoft/winget-cli#2365](https://github.com/microsoft/winget-cli/issues/2365)

I'm using version version `v1.3.1872`  now.

**Comment by Trenly** [comment]
> > Yes, see [microsoft/winget-cli#2365](https://github.com/microsoft/winget-cli/issues/2365)
> 
> I'm using version version `v1.3.1872` now.

Using v1.4.2011-preview would have changed the ACLs - or Access Control Levels - on the folder. To fix the issue, you will need to do what @jedieaston did and add permissions for System to access the folder. I don't know which folder it is exactly that needs to be changed though

**Comment by jedieaston** [comment]
%TEMP%\WinGet should be the folder you have to change the ACLs on.

**Comment by soredake** [comment]
I removed this folder, now SYSTEM have full access to it, i still get 1603.

**Comment by soredake** [comment]
As of now with recent version of windows/winget i can install hidhide package without 1603 error.
