### ISSUE TITLE
[Package Issue]: cannot upgrade rstudio.quarto with `winget upgrade rstudio.quarto`

### ISSUE THREAD

**Issue by eitsupi** [microsoft/winget-pkgs#67560]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The `winget upgrade quarto` command does not install the latest version of quarto.

### Steps to reproduce

```powershell
winget install quarto -v 1.0.36
winget upgrade quarto
```

### Actual behavior

The `winget upgrade quarto` command does not install the latest version of quarto.

### Expected behavior

Installing the latest version, which was listed by `winget upgrade`.

### Environment

```shell
winget --info
Windows パッケージ マネージャー v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
パッケージ: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by cderv** [comment]
Thanks for the report, I'll have a look.

**Comment by cderv** [comment]
@eitsupi is this the type of issue you are getting https://github.com/microsoft/winget-cli/issues/1191 ?

**Comment by eitsupi** [comment]
Perhaps it has to do with the fact that quarto is installed in the user directory during manual installation and in the system directory when installed with winget?

**Comment by Trenly** [comment]
Can you attach the logs from running `winget upgrade rstudio.quarto --verbose-logs`?
Also, what is the output you get from running `winget list quarto` ?

**Comment by eitsupi** [comment]
> Can you attach the logs from running `winget upgrade rstudio.quarto --verbose-logs`?
> Also, what is the output you get from running `winget list quarto` ?

```powershell
❯ winget upgrade rstudio.quarto --verbose-logs
適用可能な更新は見つかりませんでした。
MARs ~  3.915s
❯ winget list quarto
名前   ID             バージョン 利用可能 ソース
------------------------------------------------
Quarto RStudio.quarto 1.0.36     1.0.37   winget
```

I used to manually install quarto in my user directory, so that could be a possible influence?

**Comment by cderv** [comment]
I get the same `No applicable update found.`

````powershell
> winget upgrade rstudio.quarto --verbose-logs
Aucune mise à jour applicable trouvée.
````
