### ISSUE TITLE
EclipseAdoptium.Temurin - Split into `.jdk` and `.jre`

### ISSUE THREAD

**Issue by russellbanks** [microsoft/winget-pkgs#67708]
The EclipseAdoptium.Temurin packages are currently split as two separate packages: `EclipseAdoptium.Temurin` and `EclipseAdoptium.TemurinJRE`. I feel like it would be beneficial if, for clarity, the packages matched more like the ojdkbuild packages on here. (Shown below)

![WindowsTerminal_kJHegjjDx6](https://user-images.githubusercontent.com/74878137/181280796-d5d6cd20-7b59-4ef7-9608-486d604b0ea2.png)

This would mean moving the packages (using Adoptium 17 as an example):

`EclipseAdoptium.Temurin.17` -> `EclipseAdoptium.Temurin.17.JDK`
`EclipseAdoptium.TemurinJRE.17` -> `EclipseAdoptium.Temurin.17.JRE`

This makes the more sense as both packages come from the same GitHub releases and it also means that they will all be listed in numerical order, making it easier for the user to find the version, and then choose the variation:

`EclipseAdoptium.Temurin.8.JDK`
`EclipseAdoptium.Temurin.8.JRE`
`EclipseAdoptium.Temurin.11.JDK`
`EclipseAdoptium.Temurin.11.JRE`

Rather than:

`EclipseAdoptium.Temurin.8`
`EclipseAdoptium.Temurin.11`
`EclipseAdoptium.TemurinJRE.8`
`EclipseAdoptium.TemurinJRE.11`

</br>

If this is an acceptable change (best for a moderator to say so), then I'm happy to do this myself.

**Comment by Trenly** [comment]
I'm Trenly and I approve this message

**Comment by vedantmgoyal2009** [comment]
Please assign this to me since the InstallerUrls are so messed up in some manifests. I'll do it along with fixing it in the automation, on or by this Friday.

Also, I think `EclipseAdoptium.Temurin.<jre/jdk>.<version>` is more preferable than `EclipseAdoptium.Temurin.<version>.<jre/jdk>`. Rest whatever mods decide.

**Comment by russellbanks** [comment]
> Also, I think `EclipseAdoptium.Temurin.<jre/jdk>.<version>` is more preferable than `EclipseAdoptium.Temurin.<version>.<jre/jdk>`. Rest whatever mods decide.
> 
> Edit: To keep the naming consistent across the repo, original post is correct.

Although this wouldn't match ojdkbuild, I agree that it is more preferable to have it like `EclipseAdoptium.Temurin.<jre/jdk>.<version>` because it makes the most sense to have the version number last.

**Comment by vedantmgoyal2009** [comment]
I've opened for JDK. Once they get merged, I'll do JRE.

**Comment by russellbanks** [comment]
Is it possible you could add Temurin 19 and Temurin 20, please. They're both JDK only and in beta so it may be worth putting `Eclipse Temurin JDK with Hotspot 19 (Beta)` and `Eclipse Temurin JDK with Hotspot 20 (Beta)`.

**Comment by vedantmgoyal2009** [comment]
I guess you've already added them to the repo. 
https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/EclipseAdoptium/Temurin/

**Comment by russellbanks** [comment]
Ohh okay, you're transferring them, rather than creating new manifests. Thanks.

**Comment by russellbanks** [comment]
@vedantmgoyal2009 is there any update on the JRE packages?

**Comment by vedantmgoyal2009** [comment]
I will open PRs for them today midnight IST.

**Comment by russellbanks** [comment]
Thanks again @vedantmgoyal2009 :)
