### ISSUE TITLE
[Package Issue]: AnyDeskSoftwareGmbH.AnyDesk

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-pkgs#67794]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget seems to be parsing the version information from the Windows Registry in an incorrect way.

### Steps to reproduce

1. Execute "winget upgrade".
2. Take note how winget seems to pull the version from the Registry with a carrot (I think it's a carrot) on the front. See screen shot below.

### Actual behavior

See steps to reproduce and screen shot.

### Expected behavior

Pull the version from the Registry without the carrot. (I think it's a carrot)

### Environment

```shell
PS C:\Users\trpar> winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/32105035/181575461-dbe4358e-895f-4f30-be1d-4d9b82ed0db7.png)

**Comment by JohnMcPMS** [comment]
This looks like a bad manifest to me.  Looking at the history, we would have to ask @OfficialEsco if they remember why they made the version start with "ad" in #14259.

I just installed the latest on a sandbox and the `DisplayVersion` is "7.0.13"

[The website](https://anydesk.com/en/downloads/windows) lists it under the download button as "v7.0.13 (3.8 MB)", no "ad" involved.  I don't see any reason why we should want to use a non-standard, non-sortable package version like this.  It should be changed to be `PackageVersion: 7.0.13`, which would resolve the issue you are seeing.

**Comment by OfficialEsco** [comment]
The EXE package which most people have installed contains `ad`
![VirtualBoxVM_JI7aSWx8TZ](https://user-images.githubusercontent.com/15158490/181613656-2c045dc9-e975-4c75-a520-4b599dddae2e.png)

IF we use `7.0.13` instead of `ad 7.0.13` all the exe users will be in a constant upgrade loop.

**Comment by denelon** [comment]
The "<" symbol means we evaluated the version, and it was less than one of the manifests we have in range.

**Comment by JohnMcPMS** [comment]
I was going to suggest that `DisplayVersion` solves this, but it doesn't really work as coded for joining two disparate versions like the exe/msi here.  The only thought that comes to mind is improving the version parsing logic here to better ignore the leading "ad".

`DisplayVersion` (as coded) is always going to create a range that overlaps one or the other of lower values, making it never upgrade.

As far as the version parsing goes, I'm thinking that if there are leading non-decimal characters followed by decimal characters in the first version part, we can ignore them?  So `ad 7.0.13` == `7.0.13` and `v1.2.3` == `1.2.3`.  `foo1` == `bar1` would also be true, but `1.foo2` != `1.bar2`.

AnyDesk, with only the one version at a time, isn't actually impacted by this much (until "ad 10.0.0" doesn't sort higher than "ad 9.9.9").  And this issue is more about the confusing `< VERSION` which was intended to indicate "less than VERSION".  But improving the baseline version parsing would remove the need for using the "ad" here (or allow it, depending on preference).  And it would certainly remove the need to use `DisplayVersion` mapping.

@OfficialEsco and @jedieaston , you have more experience with the plethora of version numbers out there.  Do you see any issue with my suggestion above?  Any improvement?  We obviously have to be careful not to disrupt the existing behavior, but I don't really see a problem affecting versions that don't start with numbers.

**Comment by OfficialEsco** [comment]
AnyDesk exe is the only package which have this stupid Version schema, there was actually a period where we had AnyDesk.AnyDesk.MSI and AnyDesk.AnyDesk.EXE to work around this issue..

I don't see any issues in doing that, that could maybe also resolve the `v<VersionNumber>` inconsistency too

**Comment by jedieaston** [comment]
This also sounds good to me.

**Comment by trparky** [comment]
Any update on this issue?

**Comment by R-Adrian** [comment]
(maybe this will increase the priority?)  AnyDesk 7.0.14 was released recently to fix another security vulnerability (the changelog doesn't mention any CVE for it, or any details yet) but winget still tries to "upgrade" from 7.0.14 to the old 7.0.13.

side note: Firefox Developer edition also seems affected by a similar wrong version detection

![image](https://user-images.githubusercontent.com/16319504/184499862-06ce03c3-7b6c-4ec8-93e0-85b8199d90c8.png)

**Comment by khewweifeng** [comment]
Hi, I also facing issue with anydesk installation 

Installer hash does not match; this cannot be overridden when running as admin

![Screenshot (21)](https://user-images.githubusercontent.com/54496743/198763182-8955d677-5dd0-42fb-b1d0-e95fee0946ac.png)

**Comment by OfficialEsco** [comment]
Currently blocked in validation for unknown pipeline issue reasons
* https://github.com/microsoft/winget-pkgs/pull/86858

**Comment by NJT145** [comment]
The hash must to be updated. But there is an other problem: There is a lack of separation of [AnyDesk.exe](https://download.anydesk.com/AnyDesk.exe) and [AnyDesk.msi](https://download.anydesk.com/AnyDesk.msi) versions. For example, while I use installation by "AnyDesk.exe", `winget list Anydesk` gives `Id=AnyDeskSoftwareGmbH.AnyDesk` and `Version=> 7.1.6`.
You can use exe or msi to install it. Take a look at [here](https://support.anydesk.com/knowledge/command-line-interface-for-windows).
Maybe it is better to separate those versions like AnyDeskSoftwareGmbH.AnyDesk.exe and AnyDeskSoftwareGmbH.AnyDesk.msi .

**Comment by NJT145** [comment]
A simple note:
To install by using [AnyDesk.exe](https://download.anydesk.com/AnyDesk.exe), you can use this powershell script:
```
$InstallDir = “C:\Program Files (x86)\AnyDesk”;
$TempInstall = "$env:temp\AnyDesk.exe";
$url = "https://download.anydesk.com/AnyDesk.exe";
Invoke-WebRequest -Uri $url -OutFile $TempInstall;
$TempInstall  --install $InstallDir --start-with-win --create-desktop-icon;
Remove-Item -Path $TempInstall
```
This will install AnyDesk with default settings. (For 32bit systems, use `$InstallDir = “C:\Program Files\AnyDesk”`)

**Comment by NJT145** [comment]
A simple note:
You can install [AnyDesk.exe](https://download.anydesk.com/AnyDesk.exe) version of this program by using this simple powershell script:
```
Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    $TempInstall = "$env:temp\AnyDesk.exe";
    $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    Invoke-Command -ScriptBlock { CMD /C "$TempInstall --install $InstallDir --start-with-win --create-shortcuts --create-desktop-icon --update-manually" };
    Remove-Item -Path $TempInstall }
```
Check the official [documentation](https://support.anydesk.com/knowledge/command-line-interface-for-windows) for available parameters.

**Comment by OfficialEsco** [comment]
Separating the package causes a bigger issue where both the MSI and EXE matches, the only difference is the stupid version name of the EXE which is `ad <version>`

**Comment by NJT145** [comment]
The only difference is NOT the version name. For example, msi version installs at "C:\Program Files (x86)\AnyDeskMSI" while exe version installs at "C:\Program Files (x86)\AnyDesk". In installation folder, the msiversion adds "MSI" at the end of name ("AnyDeskMSI.exe"). As a result, it would be better to separate "AnyDesk.exe" version from regular msi version.
You can create a new package for exe version with `id=AnyDeskSoftwareGmbH.AnyDesk.exe` to solve any conflict issues for that.
I also created a powershell script for exe version's installation. You can use this script:
```
Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    $TempInstall = "$env:temp\AnyDesk.exe";
    $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    [string[]] $argList = @("--install $InstallDir", "--start-with-win", "--create-shortcuts", "--create-desktop-icon", "--remove-first", "--update-manually");
    Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait;
    Remove-Item -Path $TempInstall }
```

**Comment by NJT145** [comment]
For a support to 32 bit systems, you can add  `if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Program Files\AnyDesk”}`
Result:
```
Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Program Files\AnyDesk”};
    $TempInstall = "$env:temp\AnyDesk.exe";
    $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    [string[]] $argList = @("--install $InstallDir", "--start-with-win", "--create-shortcuts", "--create-desktop-icon", "--remove-first", "--update-manually");
    Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait;
    Remove-Item -Path $TempInstall }
```

**Comment by NJT145** [comment]
just a quick fix: "--remove-first" at $argList cause bug on "--create-shortcuts". So, use this code instead:
```
Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Program Files\AnyDesk”};
    $TempInstall = "$env:temp\AnyDesk.exe"; $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    [string[]] $argList = @("--install $InstallDir", "--start-with-win", "--create-shortcuts", "--create-desktop-icon", "--update-manually");
    Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait;
    Remove-Item -Path $TempInstall }
```

**Comment by NJT145** [comment]
just a quick fix: "--remove-first" at $argList cause bug on "--create-shortcuts". So, use this code instead:
`Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Program Files\AnyDesk”};
    $TempInstall = "$env:temp\AnyDesk.exe";
    $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    [string[]] $argList = @("--install $InstallDir", "--start-with-win", "--create-shortcuts", "--create-desktop-icon", "--update-manually");
    Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait;
    Remove-Item -Path $TempInstall }`

**Comment by NJT145** [comment]
just a quick fix: "--remove-first" at $argList cause bug on "--create-shortcuts". So, use this code instead:
```
Invoke-Command -ScriptBlock {
    $InstallDir = “C:\Program Files (x86)\AnyDesk”;
    if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Program Files\AnyDesk”};
    $TempInstall = "$env:temp\AnyDesk.exe";
    $url = "https://download.anydesk.com/AnyDesk.exe";
    Invoke-WebRequest -Uri $url -OutFile $TempInstall;
    [string[]] $argList = @("--install $InstallDir", "--start-with-win", "--create-shortcuts", "--create-desktop-icon", "--update-manually");
    Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait;
    Remove-Item -Path $TempInstall }
```

**Comment by NJT145** [comment]
I checked the manifest and see that exe version is already in it.
As a result, we need to check if `winget upgrade` have any conflict with that.
And, it can be better to use exe version as default, because of version number issue on msi version. (exe version shows version 7.1.7)

**Comment by OfficialEsco** [comment]
Just retested the exe, and its still broken

![Screenshot_20230116_162119](https://user-images.githubusercontent.com/15158490/212712785-368e00fe-d469-4288-a6e9-254e99bea0f9.png)

**Comment by NJT145** [comment]
when I use same command at powershell, version number is correct. So, what can cause this issue?
My powershell code is this:
`Invoke-Command -ScriptBlock { $InstallDir = "C:\Progra~2\AnyDesk"; if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Progra~1\AnyDesk”}; $TempInstall = "$env:temp\AnyDesk.exe"; $url = "https://download.anydesk.com/AnyDesk.exe"; Invoke-WebRequest -Uri $url -OutFile $TempInstall; [string[]] $argList = @("--install $InstallDir", "--update-auto", "--create-desktop-icon", "--create-shortcuts"); Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait; Remove-Item -Path $TempInstall }`
What is the difference between this and the winget's install of exe?
Any ideas?

**Comment by NJT145** [comment]
when I use same command at powershell, version number is correct. So, what can cause this issue?
My powershell code is this:
`Invoke-Command -ScriptBlock { $InstallDir = "C:\Progra~2\AnyDesk"; if (-not (Test-Path -Path $InstallDir)) {$InstallDir = “C:\Progra~1\AnyDesk”}; $TempInstall = "$env:temp\AnyDesk.exe"; $url = "https://download.anydesk.com/AnyDesk.exe"; Invoke-WebRequest -Uri $url -OutFile $TempInstall; [string[]] $argList = @("--install $InstallDir", "--update-auto", "--create-desktop-icon", "--create-shortcuts"); Start-Process -FilePath $TempInstall -ArgumentList $argList -Wait; Remove-Item -Path $TempInstall }`
What is the difference between this and the winget's install of exe?
Any ideas?

**Comment by OfficialEsco** [comment]
Tested your script, same version number.

**Comment by NJT145** [comment]
I see it now. It is not reflected to `winget list` results, so I didn't see it before...
So, we need to wait untill this issue solved in order to switch to exe, than okay.

**Comment by NJT145** [comment]
I figured out a small difference between exe version and msi version:
In order to backup your workspace, you need to backup .trace and .conf files on C:\ProgramData\AnyDesk . Be careful about these:

exe                                                                      msi
C:\ProgramData\AnyDesk\ad_svc.trace              C:\ProgramData\AnyDesk\ad_msi\ad_msi_svc.trace
C:\ProgramData\AnyDesk\service.conf              C:\ProgramData\AnyDesk\ad_msi\service.conf
C:\ProgramData\AnyDesk\system.conf              C:\ProgramData\AnyDesk\ad_msi\system.conf

You can use same config files on both, just don't forget to change .trace filename accordingly.

**Comment by NJT145** [comment]
I figured out a small difference between exe version and msi version:
In order to backup your workspace, you need to backup .trace and .conf files on C:\ProgramData\AnyDesk . Be careful about these:

exe <-> msi
C:\ProgramData\AnyDesk\ad_svc.trace <-> C:\ProgramData\AnyDesk\ad_msi\ad_msi_svc.trace
C:\ProgramData\AnyDesk\service.conf <-> C:\ProgramData\AnyDesk\ad_msi\service.conf
C:\ProgramData\AnyDesk\system.conf <-> C:\ProgramData\AnyDesk\ad_msi\system.conf

You can use same config files on both, just don't forget to change .trace filename accordingly.

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your problem still persists. 

If additional problems persist, it would be extremely helpful if a new issue could be opened. Thanks!

###### Close with reason: Stale;

**Comment by hueldoeu** [comment]
Since version 9.0.1 this works very good . cmd => winget upgrade AnyDeskSoftwareGmbH.AnyDesk
