### ISSUE TITLE
[New Feature]: Move versions from ExpressVPN.ExpressVPN to ExpressVPN.ExpressVPN.Preview

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-pkgs#67863]
### Description of the new feature/enhancement

ExpressVPN has two versions of its package on their website https://www.expressvpn.com/latest#windows , an Early Preview version (uses ExpressVPN lightway protocol), and normal release (not optimized for ExpressVPN lightway protocol). Both can be useful versions to the users so it may be a good idea to include both. 

Currently both types of versions are included in the [ExpressVPN.ExpressVPN](https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/ExpressVPN/ExpressVPN) directory, ExpressVPN `version 10`'s are all standard releases and `version 12`'s are all early preview releases.

The question is, should we move `version 12`'s to new directory `ExpressVPN.ExpressVPN.Preview`? Or just get rid of preview releases? Or let them stay in the current directory? As winget currently does not have support for release channels, what could be the implications in upgrade scenario as a consequence of this move?

### Some Considerations
- Both cannot be installed side-by-side (they install to same directory) 
- Both have same DisplayName
- Both make two ARP entries to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall` (one is unique so maybe that can be used as **primary ARP entry**??)
![image](https://user-images.githubusercontent.com/88161975/181700642-9225c179-87b5-4bbd-aaf0-1befd9104ee9.png)
![image](https://user-images.githubusercontent.com/88161975/181701165-521cd6aa-4699-4ae0-954c-47c7ba428c65.png)

If moderators approve of this move, then I can start making the manifests.

**Comment by russellbanks** [comment]
+1 for splitting the packages into `ExpressVPN.ExpressVPN` and `ExpressVPN.ExpressVPN.Preview`. I would suggest only keeping the latest version in `ExpressVPN.ExpressVPN.Preview` because those versions will probably end up in the stable release channel eventually anyway.

**Comment by Trenly** [comment]
@mdanish-kh - Do these still need to be split out?

**Comment by mdanish-kh** [comment]
I just checked again, and I believe Version 12s are all stable releases now, so there's no need now for moving these packages
