### ISSUE TITLE
[New Feature]: Hints for controlled folder access

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/winget-pkgs#68133]
### Description of the new feature/enhancement

I had an installer crash because Windows [Controlled Folder Access ](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide) blocked the installer from creating a folder in `%userprofile%\Documents` (even while I was running it from an Administrator terminal).

There was no useful information on the console - I just got `Installer failed with exit code: 2`.

Is there a way to let winget know through the manifest that the installer needs access to specific folders, so that the crash can be prevented or so?

**Comment by vedantmgoyal2009** [comment]
@denelon I think this should be transferred to cli repo.

**Comment by hansmbakker** [comment]
Done, moved to https://github.com/microsoft/winget-cli/issues/2400
