### ISSUE TITLE
Wrong license for Kindle For PC

### ISSUE THREAD

**Issue by jamierocks** [microsoft/winget-pkgs#684]
I don't believe that Kindle For PC is licensed MIT, and the link to its license shouldn't be to a Microsoft repository.

https://github.com/microsoft/winget-pkgs/blame/master/manifests/Amazon/Kindle/1.25.52064.yaml

**Comment by superusercode** [comment]
According to https://chocolatey.org/packages/Kindle#files the correct license is https://www.amazon.com/gp/help/customer/display.html?nodeId=200699130
