### ISSUE TITLE
[Package Issue]: KDE.kmymoney can't install 5.1 beta with broken link; please install 5.0.6 (the latest stable) instead

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/winget-pkgs#68491]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When you type 
`winget install kmymoney`
it doesn't work, because the URL is wrong. 

**The URL is wrong because the URL is for a nightly/beta build (and no longer exists).** 

[The KMyMoney website itself](https://download.kde.org/stable/kmymoney/5.0.6/win64/) encourages users to install the prior stable version (5.0.6)

### Steps to reproduce

```C:\WINDOWS\system32>winget install KDE.kmymoney```

### Actual behavior

```C:\WINDOWS\system32>winget install KDE.kmymoney
Found KMyMoney [KDE.kmymoney] Version 5.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://build-artifacts.kde.org/binary-factory/KMyMoney_Release_win64/1382/kmymoney-5.1-1382-windows-msvc2019_64-cl.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).```

### Expected behavior

Here's what happens when I tell winget to install the 5.0.6 version specifically:

```
C:\WINDOWS\system32>winget install --version 5.0.6 kmymoney
Found KMyMoney [KDE.kmymoney] Version 5.0.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.kde.org/stable/kmymoney/5.0.6/win64/kmymoney5-mingw64-5.0.6-8.1-setup.exe
  ██████████████████████████████   108 MB /  108 MB
Successfully verified installer hash
Starting package install...
Successfully installed```

This is a workaround, but it would be great if the normal 'winget install kmymoney' would do this instead of trying to install the 5.1 nightly build version

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
I have made a PR to solve the 403 Forbidden error: 

`build-artifacts.kde.org` is the expected URL for this application here as `download.kde.org` has been discontinued for many KDE applications built for Windows & macOS. Notice the difference between `KMyMoney_Release_win64` (which is a stable) version v.s. `KMyMoney_Nightly_win64` in the URLs.

KDE developers have recommended moving over to `build-artifacts.kde.org` as you'll be downloading newer versions because the versions on `download.kde.org` are a few years old and very outdated. This is also probably why Chocolately hasn't had their KDE packages updated.

You will need to contact KDE developers to see if they can upload builds to static URLs so that it can be included in winget-pkgs manifests without going 404 Not Found or 403 Forbidden in case someone forgets to

**Comment by MikeTheGreat** [comment]
Ok.  I think what I'm hearing is "KDE is switching to `build-artifacts.kde.org` and they need to provide stable URLs for downloading their stuff, or else they risk links breaking like this"

I'll see if I can log a bug in the KMyMoney system and then hope for the best.  It would be cool if WinGet works smoothly but this is my first time using it so I'm not _that_ invested in it yet.

Thank you!

**Comment by MikeTheGreat** [comment]
Ok, I logged this in the KDE bug tracker at https://bugs.kde.org/show_bug.cgi?id=457460.

Good luck y'all :)
