### ISSUE TITLE
microsoft store is broken

### ISSUE THREAD

**Issue by Chaython** [microsoft/winget-pkgs#6851]
I've had to clean install windows many times because microsoft store just stops working...
I did another clean install laltely to get it working(for the christmas $1/3 month xbox ultimate).
Now lately I had been playing dead by daylight, but after MS store updated xbox, gaming services was not operating, so I forced game services reinstallation through ps, tried launching the game over and over kept opening the gaming services page in ms store, so I reinstalled the gaming services again... game started working. Few days later game stopped working again same issue though it kept going through multiple gaming service reinstalls etc... so I reset/repaired the app, it worked. Again a few days later stopped working, I did the app repair/wsreset/gaming services reinstallation and nothing was wotking so I uninstalled the game. 
After uninstalling the game remained in the start menu, and if I go into winapps the games folder is still there... the game is still fully installed except it doesn't show up as installed in the microsoft store, nor in the uninstall apps listed, right clicking and going to apps settings launches and then ctd the settings app.
Ik this is not exactly related to winget, but winget does require the fairly broke ms store, and the ms team here, seems much more enthusiastic than any other ms staffer, so I'm looking for advice on how to remove and reinstall the app without clean installing windows again. Also want MS to fix the store...

**Comment by Donna3344** [comment]
So complicated

**Comment by pbrandstetter** [comment]
Hello @Chaython 
if you report any issues on GitHub please stick to the templates provided so we can help better.
Regarding you problem, just search on google for reset ms store, this may help out.
Next time you should report your problem to Feedback Hub and not on any unrelated repo 😉

**Comment by Chaython** [comment]
As I said I did, reset microsoft store.
I've been reporting the issue for 6 years, it's so common, I'm surprised they hadn't abandoned MS store yet.
I didn't follow the template, as it is unrelated, I've just been begging for someone competent to bring it up with their colleagues.
MS staff are truly in a cult, sniffing their own farts.
I very much prefer linux, it's sad so many developers still use DirectX.
________________________________

**Comment by Chaython** [comment]
Often when MS store, stops working the only working solution was clean installing Windows. A terrible experience, as MS store apps cannot be "found" they have to be completely reinstalled. The only store with such issues and lack of basic functionality.
In this case, I booted into Linux, to delete the game's folder. [As if you take permission to do it within Windows, SYS loses access, and no apps will install]... I then deleted all related registry keys, just [ctrl]+[F]ing through regedit. Then installing the app worked again.
________________________________

**Comment by MattBDev** [comment]
I think this issue can either be closed and the author can report it on the Feedback Hub or it can be moved to microsoft/winget-cli

**Comment by denelon** [comment]
We're doing some work with the store team on the future store source for the Windows Package Manager. I shared this report with them. They also suggested [Windows]+[f] in Windows to report the issue to Feedback Hub so they can review logs. We also have the https://support.xbox.com/en-US/help/account-profile/manage-account/xbox-insider-hub-report-a-problem site to report feedback as an Xbox Insider.

Our current experimental source for the Windows Package Manager is a curated list of about 300 free store Apps rated E for everyone. We are hoping to have a more robust source that will also allow Apps that a customer has already purchased to also be available.
