### ISSUE TITLE
[Package Request]: Add Apache.netbeans

### ISSUE THREAD

**Issue by neoribs** [microsoft/winget-pkgs#68735]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Apache
Publisher Url: https://netbeans.apache.org/
Package Name: Apache.netbeans
Description: Development Environment, Tooling Platform and Application Framework.
Package Version: 14
Installer URL: https://dlcdn.apache.org/netbeans/netbeans-installers/14/Apache-NetBeans-14-bin-windows-x64.exe

Current Package Identifier (for new versions): https://www.apache.org/dyn/closer.cgi/netbeans/netbeans-installers/14/Apache-NetBeans-14-bin-windows-x64.exe

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/issues/13844

**Comment by Yousha** [comment]
Resolved by #102998 ?
