### ISSUE TITLE
[Package Request]: Lightshot

### ISSUE THREAD

**Issue by Andret2344** [microsoft/winget-pkgs#68755]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

**Publisher**: Skillbrains 
**Publisher URL**: https://www.dobreprogramy.pl/skillbrains,wydawca,6627154906330753
**Package Name**: Lightshot
**Description**: The fastest way to take a customizable screenshot _(more can be found on the [official website](https://app.prntscr.com/en/index.html))_
**Package Version**: 5.5.0.7
**Installer URL**: https://app.prntscr.com/build/setup-lightshot.exe

**Comment by Trenly** [comment]
Last I checked, this package had validation blocked because the publisher doesn't allow requests from the Azure pipelines

https://github.com/microsoft/winget-pkgs/pull/23768#issuecomment-918945591
