### ISSUE TITLE
P.S.A Manifest schema 1.2 validation disabled

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#68845]
### Description of the new feature/enhancement

YamlCreate was updated to generate 1.2 schema manifests.
wingetcreate was also updated to generate 1.2 schema manifests. (edit: 8/8)

These are currently blocked by validation and will be re-enabled after portable packages start being accepted.

The REST schema needs to be updated with the 1.2 schema (we're dual publishing) which is why this was disabled (in addition to portable packages).

### Proposed technical implementation details (optional)

Please just switch the Manifest Version back to 1.1.0 in the PR after creating the manifest. (edit: 8/8)

FYI, I'm aiming to open up 1.2 schema validation in the community repository ~tomorrow August 9th, 2022 (EOD Pacific Time). (edit: 8/9)~ by Tuesday August 16th. (edit 9/13).

**Comment by Alphrag** [comment]
Hi, it seems that this not only affects `YamlCreate` but also `wingetcreate` for those that use the [last release (version 1.1.2.0)](https://github.com/microsoft/winget-create/releases/tag/v1.1.2.0) as updating with this will lead to the use of 1.2 schema manifests (see for example the files generated by the automated [update of Ferdium.Nightly](https://github.com/microsoft/winget-pkgs/pull/68941/commits/87e98c4909b4f61926a4a402f6f050f8f99dced1) when using `wingetcreate update`).

**Comment by denelon** [comment]
@Alphrag thanks for the update. I edited the description above.

**Comment by denelon** [comment]
We hit a snag. It's looking more like the end of the week. We will get it out ASAP.

**Comment by denelon** [comment]
Updated to Tuesday August 16th.

**Comment by iqfareez** [comment]
Hi. So, is the validation pipeline is ready for a new schema yet?

**Comment by OfficialEsco** [comment]
> Updated to Tuesday August 16th.

> Hi. So, is the validation pipeline is ready for a new schema yet?

They will most likely start prepping in 2-3 hours, so hopefully everything will go as planed and be live tonight :)

**Comment by denelon** [comment]
Testing went well yesterday. I haven't heard any reason not to ship it today. As @OfficialEsco guessed, we will start the work in a couple of hours. Most of the engineers are in Pacific Time.

**Comment by vedantmgoyal2009** [comment]
@denelon any updates?

**Comment by denelon** [comment]
I was out yesterday. I've just confirmed the team is working on deploying the changes now.

**Comment by denelon** [comment]
Manifest validation for the 1.2 schema is now enabled. We will run through open PRs to trigger builds. Our moderators can also trigger builds for these PRs.
