### ISSUE TITLE
[Package Request]: Microsoft SQL Server 2017 Developer

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/winget-pkgs#69115]
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://support.microsoft.com/
Package Name: Microsoft.SQLServer.2017.Developer
Description: SQL Server 2017 Developer is a full-featured free edition, licensed for use as a development and test database in a non-production environment.
Homepage: https://www.microsoft.com/sql-server/sql-server-2017
Package Version: 14.2204.5490.2
Release Notes Url: https://docs.microsoft.com/sql/sql-server/sql-server-2017-release-notes
Installer URL: https://download.microsoft.com/download/5/A/7/5A7065A2-C81C-4A31-9972-8A31AC9388C1/SQLServer2017-SSEI-Dev.exe

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/issues/25931#issuecomment-906285627

**Comment by TheBossMagnus** [comment]
So, the app fails to install without user input. Help is needed for silent switches...

**Comment by xtqqczze** [comment]
See #25931 for the discussion on proposed technical implementation.

**Comment by xtqqczze** [comment]
Mainstream support for SQL Server 2017 ended on 2022-10-11, but extended support is until [2027-10-12](https://learn.microsoft.com/en-us/lifecycle/products/sql-server-2017).

**Comment by Trenly** [comment]
Close with reason: Exists as Microsoft.SQLServer.2017.Developer;
