### ISSUE TITLE
[Package Request]: Microsoft SQL Server 2017 Express

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/winget-pkgs#69114]
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://support.microsoft.com/
Package Name: Microsoft.SQLServer.2017.Express
Description: Microsoft SQL Server 2017 Express is a powerful and reliable free data management system that delivers a rich and reliable data store for lightweight Web Sites and desktop applications.
Homepage: https://www.microsoft.com/sql-server/sql-server-2017
Package Version: 14.2204.5490.2
Release Notes Url: https://docs.microsoft.com/sql/sql-server/sql-server-2017-release-notes
Installer URL: https://download.microsoft.com/download/5/E/9/5E9B18CC-8FD5-467E-B5BF-BADE39C51F73/SQLServer2017-SSEI-Expr.exe

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/issues/25931#issuecomment-906285627

**Comment by TheBossMagnus** [comment]
So, the app fails to install without user input. Help is needed for silent switches...

**Comment by xtqqczze** [comment]
See #25931 for the discussion on proposed technical implementation.

**Comment by xtqqczze** [comment]
Mainstream support for SQL Server 2017 ended on 2022-10-11, but extended support is until [2027-10-12](https://learn.microsoft.com/en-us/lifecycle/products/sql-server-2017).

**Comment by Trenly** [comment]
Close with reason: Exists as Microsoft.SQLServer.2017.Express;
