### ISSUE TITLE
[Package Issue]: Github.CLI install/upgrade failed

### ISSUE THREAD

**Issue by hantsy** [microsoft/winget-pkgs#69299]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget upgrade Github.CLi
Found GitHub CLI [GitHub.cli] Version 2.14.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/cli/cli/releases/download/v2.14.4/gh_2.14.4_windows_amd64.msi
  ██████████████████████████████  8.03 MB / 8.03 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1619
Installer log is available at: C:\Users\hantsy\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-GitHub.cli.2.14.4-2022-08-11-09-48-36.151.log

### Steps to reproduce

winget upgrade Github.CLI

### Actual behavior

failed.

### Expected behavior

it should upgrade it without any interactions.

### Environment

```shell
winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1865
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0
```

**Comment by denelon** [comment]
Which version of GitHub CLI is currently installed on the system?

Can you share the log?

**Comment by hantsy** [comment]
I encountered this issue when upgrading to 2.14.3, see: https://github.com/cli/cli/issues/6040. 

And I manually installed 2.14.3 and tried to upgrade to 2.14.4 this time the same issue occured.

>Can you share the log?

The log file is empty.

**Comment by hantsy** [comment]
Both new install(winget uninstall and install) and upgrade failed.

**Comment by denelon** [comment]
Can you manually remove GitHub.CLI and then run through installing 2.14.3 with winget and then trying upgrade with winget?

1. Manually uninstall GitHub.CLI
2. Run `winget install GitHub.CLI --version 2.14.3`
3. Run `winget upgrade GitHub.CLI`

I'm trying to determine if it's the package installer, the manifest, or the client that is causing the problem.

I'm guessing it might be related to trying to upgrade the package when it wasn't installed via winget. I didn't see the "AppsAndFeatures" entry in the manifests.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/GitHub/cli/2.14.3/GitHub.cli.installer.yaml
https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/GitHub/cli/2.14.4/GitHub.cli.installer.yaml

**Comment by OfficialEsco** [comment]
Winget upgrade from 2.14.4 to 2.14.5 worked for me, i see you're getting exit code 1619 which have a few reasons, but its either you don't have access to the file, the file is in use or the file does not exist. 

https://www.itninja.com/question/help-with-msi-1619

https://social.technet.microsoft.com/Forums/windows/en-US/9aee99aa-427e-42ce-8b73-b2b9ae7f28a1/package-install-keeps-failing-with-exit-code-1619
