### ISSUE TITLE
Split `Microsoft.PowerShell` into `Microsoft.PowerShell.7.0` and `Microsoft.Powershell.7.2`

### ISSUE THREAD

**Issue by russellbanks** [microsoft/winget-pkgs#69585]
If you look at the [release/tag history](https://github.com/PowerShell/PowerShell/tags) of PowerShell, PowerShell 7.0, 7.2 and 7.3 (The preview) are all getting updates. Therefore, it would make sense to split `Microsoft.PowerShell` into `Microsoft.PowerShell.7.0` and `Microsoft.Powershell.7.2`. The downside is that until the feature to point to the latest version in a set of package channels is implemented, you wouldn't be able to do `winget install powershell` unless the latest version was updated every time to have that as its moniker. See https://github.com/microsoft/winget-pkgs/pull/67898#issuecomment-1199940707

**Comment by denelon** [comment]
@russellbanks the PowerShell team is publishing their own manifests. I'm not sure if their recommendation would be to split their package into minor versions, or to keep the package the way it is with respect to updates. It may be better to focus the activity on getting more 👍on pinning.

It's still possible to `winget show Microsoft.PowerShell --versions` and then `winget install Microsoft.PowerShell --version <x.y.z>`.

>Note: I'm hoping to get pinning out in the next release or two. The current priority is support for .zip packages with a single installer or portable packages in 1.4.

**Comment by russellbanks** [comment]
Thank you for your reply :)

For anyone else that reads this, go give https://github.com/microsoft/winget-cli/issues/476 a 👍
