### ISSUE TITLE
[Package Request]: GPU-Z by TechPowerUp

### ISSUE THREAD

**Issue by suratovvlad** [microsoft/winget-pkgs#70469]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: TechPowerUp 
Publisher Url: https://www.techpowerup.com/
Package Name: TechPowerUp.GPU-Z
Description: GPU-Z is a lightweight utility designed to give you all information about your video card and GPU.
Package Version: 2.47.0
Installer URL: https://nl2-dl.techpowerup.com/files/CX_GLRax-0knE2pKIgakyA/1660813451/GPU-Z.2.47.0.exe

Current Package Identifier (for new versions):

**Comment by suratovvlad** [comment]
I see, there was this package https://github.com/microsoft/winget-pkgs/issues/22086, but now it is not available for some reason
![image](https://user-images.githubusercontent.com/3812290/185243369-93d761c7-dfc3-47c4-a2b9-b1075c79e648.png)

**Comment by russellbanks** [comment]
The packages were removed because the installer URLs returned 404. #70481 will revert the latest version. However, it is still 404 so it will need updating once that PR has been accepted.

**Comment by ItzLevvie** [comment]
> However, it is still 404 so it will need updating once that PR has been accepted.

This part is intentional because the developer only allows package managers to download TechPowerUp applications without any sort of expiration dates by taking advantage of WinGet's user agent.

**Comment by ItzLevvie** [comment]
Close with reason: Resolved by the two pull requests above;
