### ISSUE TITLE
Azul Zulu FX variations

### ISSUE THREAD

**Issue by russellbanks** [microsoft/winget-pkgs#70722]
Azul Zulu has 4 Java environment variatons: `JDK`, `JRE`, `JDK FX`, and `JRE FX`. The JDK and JRE variatons have been submitted for the most part, but ideally the FX variations of each could be submitted too. Following the naming schema (`Azul.Zulu.<Major Version>.<JDK|JRE>`), it would make sense to have it as `Azul.Zulu.<Major Version>.<JDK|JRE>.FX>`. However, I'm not sure how to go about this because that doesn't follow the correct naming pattern:

![WindowsTerminal_AY6MfpwcFB](https://user-images.githubusercontent.com/74878137/185379180-bd24a392-a8ac-4df4-a590-89b57f7b4591.png)

Edit: `Azul.Zulu.<MajorVersion>.<JDK|JRE>-FX` could work, but I don't know whether this is ideal

**Comment by Trenly** [comment]
I believe they actually refer to it as ZuluFX, so perhaps Azul.ZuluFX.Major.JDK/JRE

**Comment by russellbanks** [comment]
> I believe they actually refer to it as ZuluFX, so perhaps Azul.ZuluFX.Major.JDK/JRE

I did not know this, thank you. I'll gradually submit them under `Azul.ZuluFX` :)
