### ISSUE TITLE
[Package Issue]: Microsoft.office 16.0.15427.20220 hash and version mismatch

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#70730]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

![image](https://user-images.githubusercontent.com/9316590/185397006-32e86d6d-7861-46de-b944-c1ed59b22c72.png)
And, the version number of the downloaded installer is 16.0.15330.20218.

### Steps to reproduce

run commands shown in screen capture above

### Actual behavior

hash mismatch

### Expected behavior

successfully upgraded.

### Environment

```shell
Windows 程序包管理器(预览) v1.4.2161-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22622.575
系统体系结构: X64
程序包: Microsoft.DesktopAppInstaller v1.19.2161.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
I'm getting `16.0.15427.20220` with `InstallerSha256: 5FC094307539330877391E337AC945F9598783F51C57ECC5FCFCC7A375836189` when downloading from https://officecdn.microsoft.com/pr/wsus/setup.exe:
![image](https://user-images.githubusercontent.com/11600822/185398952-3c9ae8a3-8ebc-4dc5-beaf-99931ebb0dac.png)
![image](https://user-images.githubusercontent.com/11600822/185399562-f9c46fe3-1666-4880-9afe-001b8d35e656.png)

**Comment by denelon** [comment]
This could be delayed due to:
* https://github.com/microsoft/winget-pkgs/issues/70728

**Comment by lychichem** [comment]
office autoupdated to 16.0.15601.20044, closing.
