### ISSUE TITLE
[Package Request]: Lakes Environmental Screen View

### ISSUE THREAD

**Issue by TechnicaVivunt** [microsoft/winget-pkgs#71054]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [x] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Lakes Enviromental
Publisher Url: https://www.weblakes.com/
Package Name: ScreenView
Description: SCREEN View is a user friendly interface for the U.S. EPA screening model, SCREEN3.
Package Version: 4.0.1
Installer URL: https://www.weblakes.com/products/screen/update/Lakes_Environmental_SCREEN_View_V.4.0.1_Install.exe

Current Package Identifier (for new versions):

**Comment by TechnicaVivunt** [comment]
This install would be considered a complex install since it requires the exe to self extract before it gets to the actual installer. Currently reading up on manifest v1.2 to see what's needed to get this one off the ground. If someone can point me to the direction of how to utilize NestedInstallTypes I'd be grateful.

**Comment by Trenly** [comment]
> This install would be considered a complex install since it requires the exe to self extract before it gets to the actual installer. Currently reading up on manifest v1.2 to see what's needed to get this one off the ground. If someone can point me to the direction of how to utilize NestedInstallTypes I'd be grateful.

Support for this is not in the 1.2 schema or the 1.3 client. Additionally, NestedInstallerType is only valid for `zip` installers
