### ISSUE TITLE
[New Feature]: Ensure consistent line endings in package files

### ISSUE THREAD

**Issue by Okeanos** [microsoft/winget-pkgs#71796]
### Description of the new feature/enhancement

The winget-pkgs repository uses `.gitattributes` and `.editorconfig` to attempt sane and consistent formatting of package files. Specifically, both files contain rules concerning `yaml` handling:

`.editorconfig`:

```
[*.{yml,yaml}]
end_of_line = crlf
insert_final_newline = true
# editorconfig/editorconfig#329
indent_style = space
indent_size = 2
```

`.gitattributes`:

```
*.yaml text=auto
```

Now, this _looks_ like it's all good and the end of line (EOL) terminator is consistently enforced as `CRLF`, right? Well, on *nix systems the Git setting `text=auto` and its relatives, the core settings `core.autocrlf=auto` and `core.eol` may result in the following warning:

```
warning: in the working copy of '<path>.yaml', CRLF will be replaced by LF the next time Git touches it
```

That definitely isn't the intended behaviour based on the `.editorconfig`. As to why Git behaves this way, see [gitattributes#text](https://git-scm.com/docs/gitattributes#_text), [git-config#core.autocrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf), and [git-config#core.eol](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol).

In effect: I would like the provided `.gitattributes` file to be updated to reflect the intended EOL terminator style.

### Proposed technical implementation details (optional)

Some related discussion about this was already done in #1863 - specifically, the following additional fix was proposed for the `.gitattributes` file to solve file encoding issues incidentally also fixing the EOL ambiguity:

```
*.yaml text=auto working-tree-encoding=UTF-16 eol=CRLF
```

Note the specific `eol=CRLF` setting. I assume a pipeline check on newly added files should also be included (if not already present) that lints YAML files according to the expected format including EOL terminators.

**Comment by denelon** [comment]
We're using UTF-8, but I think that makes sense to standardize the "eol=CRLF".

**Comment by denelon** [comment]
@msftrubengu does this also fix:

* https://github.com/microsoft/winget-pkgs/issues/1863

**Comment by Okeanos** [comment]
> @msftrubengu does this also fix:
> 
> * [Ensure consistent manifest encoding #1863](https://github.com/microsoft/winget-pkgs/issues/1863)

It does not - I specifically did not include character encoding information in the changes to the gitattributes file because I was unsure what the consensus of the maintainers is.
