### ISSUE TITLE
[Package Request]: Virtualhere-GUI

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#71926]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Virtualhere
Publisher Url: https://www.virtualhere.com/
Package Name: Virtualhere
Description: VirtualHere allows USB devices to be used remotely over a network just as if they were locally connected!
Package Version: 4.6.3
Installer URL: https://www.virtualhere.com/sites/default/files/usbclient/vhui64.exe

Current Package Identifier (for new versions): 4.6.3

**Comment by infinitepower18** [comment]
#78644
