### ISSUE TITLE
[Package Request]:  lossless-cut

### ISSUE THREAD

**Issue by Cyberavater** [microsoft/winget-pkgs#72074]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: mifi
Publisher Url: https://github.com/mifi/lossless-cut
Package Name: lossless-cut
Description: The swiss army knife of lossless video/audio editing
Package Version: 3.46.2
Installer URL: https://github.com/mifi/lossless-cut/releases/tag/v3.46.2

Current Package Identifier (for new versions): ??

**Comment by Trenly** [comment]
This package cannot be added currently as their appx file is not signed
> Installer failed with exit code: 0x800b0100 : No signature was present in the subject.

**Comment by mifi** [comment]
See https://github.com/mifi/lossless-cut/issues/337

**Comment by Trenly** [comment]
[Policy] Blocking-Issue
[Policy] Area-External

**Comment by JustMyGithub** [comment]
If winget requires signing, would someone kindly tell the creator how to do this? He is willing to sign, he just doesnt know how to do this https://github.com/mifi/lossless-cut/issues/337#issuecomment-622977295
