### ISSUE TITLE
 winget install MTPutty - fails hash matchfails

### ISSUE THREAD

**Issue by freddyrios** [microsoft/winget-pkgs#7228]
# Brief description of your issue
Running winget install MTPutty fails. Root cause of the issue seems to be that the URL used to download is not version specific: "Downloading https://ttyplus.com/download/mtputty_setup.exe" (quick fix is to upgrade the manifest to the latest, but to really solve it the MTPutty author probably needs to be contacted). 

Winget is expecting to see version 1.7 while going to the site  and it got replaced with https://ttyplus.com/download/mtputty_setup.exe, while going to site shows a link to the same address stating its 1.8 beta: https://ttyplus.com/downloads/.

# Steps to reproduce
Run "winget install MTPutty"

# Expected behavior
Downloads the version in the manifest using a version specific URL. The validates the hash succesfully and succeeds.

# Actual behavior

Fails with error "Installer hash does not match; to override this check use --force"

# Environment

Windows Package Manager v0.2.3162 Preview
Windows: Windows.Desktop v10.0.19042.746
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

Any other software?
PuTTY   PuTTY.PuTTY     0.74

**Comment by denelon** [comment]
@freddyrios we have some automation running that performs a daily check of the hash. If the hash is invalid, we attempt to generate a valid PR and submit it through the pipelines to "fix" these kinds of issues.

The longer term solution will depend either on some fairly sophisticated automation here with the validation pipelines in the Windows Package Manager, or more likely, the publisher as you stated.

I noticed the manifest was submitted as a binary file, so we're looking into that as well.

**Comment by freddyrios** [comment]
@denelon thanks, that makes sense. 

I just sent them a message about the version specific URL and linked back to this.

**Comment by vedantmgoyal2009** [comment]
@freddyrios You can now run `winget install TTYPlus.MTPutty` and I hope that will solve your issue.

@denelon You can close this now(?)

**Comment by freddyrios** [comment]
@vedantmgoyal2009, @denelon confirmed that's working with the latest.

As the publisher never replied I agree there is not much to do.

FYI the ticket in their system they never replied to is #331.
