### ISSUE TITLE
Package Request: cURL

### ISSUE THREAD

**Issue by hifocus** [microsoft/winget-pkgs#726]
# Description of the new feature/enhancement

cURL is a commonly used command line based download tool. By allowing `winget install curl` can make ease for its installation on Windows.

# Proposed technical implementation details (optional)

As cURL does not provide official installers for Windows, currently the only way to install it is download its [binary builds for windows](https://curl.haxx.se/windows/), extract, then manually copy `curl.exe` to `C:\Users\xxx` for it to be effective, or add a path via environment variable.

I wonder if there's a way to allow `winget install curl` to come true, and have everything done via one simple command?

**Comment by chausner** [comment]
curl is actually included already in recent versions of Windows: https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

**Comment by masx200** [comment]
I support it!

**Comment by floh96** [comment]
Blocked by https://github.com/curl/curl/issues/5424

**Comment by bb010g** [comment]
Blocked by: https://github.com/microsoft/winget-cli/issues/182

**Comment by denelon** [comment]
We're getting closer to support for .zip based installers with portable packages inside. I've added the .zip label and removed .exe now that portable packages are supported.

* microsoft/winget-cli/issues/140

**Comment by hifocus** [comment]
> We're getting closer to support for .zip based installers with portable packages inside. I've added the .zip label and removed .exe now that portable packages are supported.
> 
> * [Support installing .zip files winget-cli#140](https://github.com/microsoft/winget-cli/issues/140)

Thanks for ever making this software more excellent

**Comment by denelon** [comment]
@Trenly do you already have a cURL manifest in the works somewhere?

**Comment by Trenly** [comment]
> @Trenly do you already have a cURL manifest in the works somewhere?

Linked above
