### ISSUE TITLE
[Package Request]: Microsoft Report Builder

### ISSUE THREAD

**Issue by randomgit87** [microsoft/winget-pkgs#75355]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Microsoft
Publisher Url: https://www.microsoft.com/en-us/download/details.aspx?id=53613
Package Name: Microsoft Report Builder
Description: Report Builder provides a productive report-authoring environment for IT professionals and power users. The download provides a stand-alone installer for Report Builder.

Report Builder provides data visualizations that include charts, maps, sparklines, and data bars that can help produce new insights well beyond what can be achieved with standard tables and charts. Use Report Builder to create reports and shared datasets. Publish report parts, and then browse the Report Part Gallery to reuse existing report parts as building blocks for creating new reports quickly with a “grab and go” experience.

Package Version: 15.0.19914.0
Installer URL: https://download.microsoft.com/download/5/E/B/5EB40744-DC0A-47C0-8B0A-1830E74D3C23/ReportBuilder.msi

Current Package Identifier (for new versions):

**Comment by randomgit87** [comment]
I believe i submitted correctly with wingetcreate.

**Comment by khilangoel** [comment]
```insights
select top(10) * from Repository
where RepositoryName = 'winget-pkgs'
```

**Comment by denelon** [comment]
@randomgit87 which PR is it?

**Comment by denelon** [comment]
I found it:
* https://github.com/microsoft/winget-pkgs/pull/75356

@randomgit87 one of the moderators made several suggestions for you to merge/consider.
