### ISSUE TITLE
[Package Issue]: TorProject.TorBrowser  Download request status is not success.

### ISSUE THREAD

**Issue by alanlivio** [microsoft/winget-pkgs#75640]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Download request status is not success.

### Steps to reproduce

$ winget install TorProject.TorBrowser

### Actual behavior

$ winget install TorProject.TorBrowser
Found Tor Browser [TorProject.TorBrowser] Version 11.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dist.torproject.org/torbrowser/11.5/torbrowser-install-win64-11.5_en-US.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Expected behavior

successful install TorProject.TorBrowser

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22622.586
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/604808/187416990-4b284a51-7557-4152-9451-4cfc457b6aee.png)

**Comment by alanlivio** [comment]
Thanks @NSO73

**Comment by Kripta-Studios** [comment]
Still the issue, because each time Tor makes an update the url with the package changes. 

```
$ winget install TorProject.TorBrowser
Encontrado Tor Browser [TorProject.TorBrowser] Versión 11.5.8
El propietario de esta aplicación le concede una licencia.
Microsoft no es responsable, ni tampoco concede ninguna licencia de paquetes de terceros.
Downloading https://dist.torproject.org/torbrowser/11.5.8/torbrowser-install-win64-11.5.8_en-US.exe
Se ha producido un error inesperado al ejecutar el comando:
Download request status is not success.
0x80190194 : No encontrado (404).
```

The solution would be as easy as changing the url to: https://dist.torproject.org/torbrowser/12.0.1/torbrowser-install-12.0.1_ALL.exe
