### ISSUE TITLE
[Package Issue]: IrfanSkiljan.IrfanView `scope=user` not working

### ISSUE THREAD

**Issue by treysis** [microsoft/winget-pkgs#76572]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Trying to install IrfanSkiljan.IrfanView with `--scope=user` fails on a machine without admin privileges.

### Steps to reproduce

- User account without admin privileges
- `winget install -e --id=IrfanSkiljan.IrfanView --scope=user`

### Actual behavior

App installation fails due to missing admin privileges.

### Expected behavior

App should be installed to user's local AppData folder if `--scope=user` is set.

### Environment

```shell
[winget --info]
Windows-Paket-Manager v1.3.2091
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1889
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2091.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

IrfanView_Install.log
```
01.09.2022 - 13:40:38: Can't create destination directory!

Please check your write permissions and system policies!

Try to create the destination folder manually and restart.: C:\Program Files\IrfanView\
```

**Comment by denelon** [comment]
<img width="867" alt="Irfan" src="https://user-images.githubusercontent.com/61799811/187946527-7980743b-15f1-472b-8bde-2bc7504e28a8.png">

I was prompted with a UAC and the install succeeded. I was running Windows Terminal in User mode.

**Comment by treysis** [comment]
You typed `--scope user` but it should be `--scope=user` with `=`. Could you please try again? With `--scope=user` there shouldn't be a UAC prompt and it should just install without the need for admin privileges (which some users don't have).

**Comment by denelon** [comment]
@treysis either syntax is valid. I was still prompted for a UAC (the installer is requesting this and not winget). The installer would need to be modified in order to not require UAC. If you go directly to the [URL for the installer](https://download.betanews.com/download/967963863-1/iview460_x64_setup.exe) and run it, you will still get the UAC prompt.

The following node from the manifest would apply to my machine.
https://github.com/microsoft/winget-pkgs/blob/5dd24a81eaf9b958047673a91cb2cd1852c180bd/manifests/i/IrfanSkiljan/IrfanView/4.60/IrfanSkiljan.IrfanView.installer.yaml#L120-L125

<img width="867" alt="Irfan2" src="https://user-images.githubusercontent.com/61799811/187963376-3a10b41c-4dba-4a06-b95d-60298607c1cb.png">

**Comment by denelon** [comment]
It's possible the package supports user scope, but the installer isn't enlightened for that scenario. It's also possible that the package doesn't support the scope correctly. 🤷‍♂️

**Comment by treysis** [comment]
> It's also possible that the package doesn't support the scope correctly. 🤷‍♂️

That's why I reported the issue. The package doesn't support the scope. Instead it reports successful installation, which it is not.

**Comment by denelon** [comment]
@ImJoakim it looks like you were the last to modify the manifest for this package. Were you able to confirm if the "user" scope actually worked correctly?

**Comment by OfficialEsco** [comment]
This is still a IrfanView issue as the user scope does not default to AppData, it defaults to C:\Program Files\IrafanView
![image](https://user-images.githubusercontent.com/15158490/188196803-aabbf0f0-be9c-4148-b19d-66f9c6f6dd0c.png)

But yeah we could probably only deliver a Machine scope as the registry key always points to 
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\IrfanView64
```

**Comment by treysis** [comment]
Has been fixed in https://github.com/microsoft/winget-pkgs/pull/78488
