### ISSUE TITLE
[Package Request]: PostgreSQL 9.6.24

### ISSUE THREAD

**Issue by FabioWielewski** [microsoft/winget-pkgs#77122]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Enterprisedb
Publisher Url: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
Package Name: PostgreSql
Description: Gerenciador de Banco de Dados
Package Version: 9.6.24
Installer URL: https://www.enterprisedb.com/postgresql-tutorial-resources-training?uuid=91f8264f-8a2d-434a-9559-4dfa9b3b80b1&campaignId=701380000017oAXAAY

Current Package Identifier (for new versions):

**Comment by FabioWielewski** [comment]
Gerenciador antigo porém utilizado mundialmente.

**Comment by mdanish-kh** [comment]
![image](https://user-images.githubusercontent.com/88161975/188124364-558495e3-8b63-4a11-91bf-fb84ee79a3f3.png)
You can use this URL: https://get.enterprisedb.com/postgresql/postgresql-9.6.24-1-windows-x64.exe
and create a manifest using either [winget-create](https://github.com/microsoft/winget-create) or [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1). More details about creating a manifest can be found [here](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#creating-your-first-manifest).

**Comment by ptanmay143** [comment]
#79396 resolves this issue. This issue can be closed.

**Comment by Trenly** [comment]
Close with reason: Resolved by 79396;
