### ISSUE TITLE
[Package Request]: mobaxterm

### ISSUE THREAD

**Issue by cjwddtc** [microsoft/winget-pkgs#77910]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: https://mobaxterm.mobatek.net/
Package Name: mobaxterm
Description: A ssh client
Package Version: 22.1
Installer URL: https://download.mobatek.net/2212022060563542/MobaXterm_Installer_v22.1.zip

Current Package Identifier (for new versions):

**Comment by mdanish-kh** [comment]
- Blocked by https://github.com/microsoft/winget-cli/issues/140

winget currently does not support installers inside of zip archive.

**Comment by yujincheng08** [comment]
@mdanish-kh installers in zip are supported.

**Comment by mdanish-kh** [comment]
> @mdanish-kh installers in zip are supported.

https://github.com/microsoft/winget-pkgs/issues/80892#issuecomment-1260057099 It's still an experimental feature.
