### ISSUE TITLE
[Package Issue]: Discord.Discord not starting after fresh install

### ISSUE THREAD

**Issue by G0rocks** [microsoft/winget-pkgs#77925]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When starting discord after installing from winget I get this error message:
![discord start fail](https://user-images.githubusercontent.com/44577486/188267321-5fd725f3-c8f6-42bf-ad61-a848eaf77acf.jpg)
And then the app closes after pressing ok.

### Steps to reproduce

1. install Discord.Discord from winget on windows 10 version:
20H2
19042.1889

2. Attempt to run the app

### Actual behavior

Some error shows up

### Expected behavior

I expected discord to check for updates and if there were any I expected it to install them before opening the app

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1889
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

### Screenshots and Logs

![discord start fail](https://user-images.githubusercontent.com/44577486/188267400-0b1c6416-e3cd-4985-ba2c-c18dffc8f4c6.jpg)

**Comment by ETHREAL1** [comment]
Also having this issue. something of note is that it's only a winget issue. if you download it directly from discord it works normally with the same version number. So as a temporary workaround is to remove discord and install it from discord manually.

**Comment by ItzLevvie** [comment]
Close with reason: This should now be resolved;

Uninstall Discord by running `winget uninstall --id Discord.Discord` and then reinstall Discord by running `winget install --id Discord.Discord`
