### ISSUE TITLE
[Package Request]: virtual desktop

### ISSUE THREAD

**Issue by cjwddtc** [microsoft/winget-pkgs#77942]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: https://www.vrdesktop.net/
Package Name: virtualdesktop
Description: Watch movies, browse the web or play games on a giant virtual screen.
Package Version: 1.21.1
Installer URL: https://download.vrdesktop.net/files/VirtualDesktop.Streamer.Setup.exe

Current Package Identifier (for new versions):

**Comment by infinitepower18** [comment]
#78620
