### ISSUE TITLE
Add third party X servers such as VcxSrv

### ISSUE THREAD

**Issue by WSLUser** [microsoft/winget-pkgs#781]
# Description of the new feature/enhancement

I want to install a third party X server such as VcxSrv and Xming from winget.
# Proposed technical implementation details (optional)
https://sourceforge.net/projects/vcxsrv/files/vcxsrv/1.20.6.0/vcxsrv-64.1.20.6.0.installer.exe/download is what Pengwin currently uses to install it in pengwin-setup. Double check it's the most up to date version. Be sure a tag "X-Server" exists.

# A clear and concise description of what you want to happen.

winget install vcxsrv
winget install xming, etc.

**Comment by CaptainBrooksie** [comment]
My pull request for this has been approved for merger

https://github.com/microsoft/winget-pkgs/pull/732

**Comment by CaptainBrooksie** [comment]
`winget install vcxsrv` will install VcxSrv Windows X Server

**Comment by WSLUser** [comment]
Great, now we need Xming added. Not sure what other ones should be added. X410 is a paid app on the Store so I don't think we could/should add that one.

**Comment by WSLUser** [comment]
Great, that just leaves Xming then. If there are others, somebody can chime in. X410 should not be considered as it's a paid Store app and will require some substantial updates to winget before we can start offering paid Store apps, not mention a conversation on how winget should handle paid apps vs FOSS apps.

**Comment by WSLUser** [comment]
Still needs Xming afaik

**Comment by denelon** [comment]
```
winget search xming
Name  Id                  Version  Source
------------------------------------------
Xming colinharrison.xming 6.9.0.31 winget
```

It looks like Xming is in the repository now. Feel free to re-open this issue if that's not the correct package.
