### ISSUE TITLE
[Package Request]: add Noxplayer

### ISSUE THREAD

**Issue by FlawlessCasual17** [microsoft/winget-pkgs#78464]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Bignox
Publisher Url: https://www.bignox.com/
Package Name: Bignox.Noxplayer
Description: An Android emulator to play mobile games on PC.
Package Version: 7.0.35
Installer URL: https://res06.bignox.com/full/20220902/7d37168d3750455da2a7fda06f7026fd.exe?filename=nox_setup_v7.0.3.5_full_intl.exe

Current Package Identifier (for new versions): 
https://res06.bignox.com/full/20220902/7d37168d3750455da2a7fda06f7026fd.exe?filename=nox_setup_v7.0.3.5_full_intl.exe

**Comment by infinitepower18** [comment]
Seems to be a custom made installer that doesn't have any silent installer switches

**Comment by SpecterShell** [comment]
It cannot be added to the repo bacause the validation pipeline failed to pass the graphics card test from its installer.
```
2022-09-08 13:37:01.395 [CLI ] Starting: 'C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Contoso.Contoso.Contoso\8490e0989cd34113bc1bf29513f8b05a.exe' with arguments '-silent'
2022-09-08 13:37:13.299 [CLI ] ShellExecute installer failed: 104
2022-09-08 13:37:13.301 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:193
```
![image](https://user-images.githubusercontent.com/56779163/189265430-15e3fb55-8c71-4d5c-aa20-1b9662f019ff.png)

**Comment by KrisSchneider** [comment]
Should I close this issue?

**Comment by SpecterShell** [comment]
Since this is a hardware-related blocking issue, I think you could keep it open until there are some solutions. 🤔

**Comment by denelon** [comment]
Related to:

* https://github.com/microsoft/winget-cli/issues/1417

**Comment by Trenly** [comment]
@msftbot Blocking-Issue

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504
