### ISSUE TITLE
`winget install Microsoft.NuGet` does not work

### ISSUE THREAD

**Issue by ctaggart** [microsoft/winget-pkgs#7855]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

```
winget install Microsoft.NuGet
```
Does not install nuget. The exe is a binary, not an installer. It also points to `latest` which will break as soon as there is a new latest. See https://www.nuget.org/downloads.

from #6884 by @cilerler
```
Url: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
```

# Steps to reproduce

```
winget install Microsoft.NuGet
```

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by cilerler** [comment]
You are right. 

Unfortunately, NuGet does not have an installer.

And I copied it from the original commit accepted and reversed after that, and use it as a placeholder with the correct location until (a) winget supports EXE installations (b) NuGet provides an installer.

We have same kind of needs for apps like CURL, etc.

Also, if it was copying it to a specified path, and add it into the PATH, having the `latest` would not be a real problem, you would only need to use `-force`.

**Comment by ctaggart** [comment]
The issue with `latest` is the checksum will not match.
`Sha256: 3ce2f08716277ce3a7556893b0a39e5c2bf1dd6765afd54843700d4a35d7c058`

**Comment by cilerler** [comment]
As I stated above `winget install Microsoft.NuGet --force` will pass the checksum issue.  
But it won't place it into the `C:\Program Files (x86)\NuGet` folder and add that folder into the `PATH` environment variable, and that is the main issue, and that is the reason I said, I added that as a placeholder.
The original entry is here https://github.com/microsoft/winget-pkgs/pull/227/files

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/194 is the blocking issue. This isn't an installer it's a standalone .exe.

**Comment by russellbanks** [comment]
WinGet 1.3 now supports portable exe files so Microsoft NuGet has been added. You can install it with `winget install Microsoft.NuGet`.

**Comment by denelon** [comment]
[Windows Package Manager 1.3](https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091) has been released 🎉
