### ISSUE TITLE
[Package Issue]: TimKosse.FileZilla.Client

### ISSUE THREAD

**Issue by JamieSabbatella** [microsoft/winget-pkgs#78578]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

It appears the application link has some sort of validation for User Agents, and does not allow Winget to download the application from the source URL.

The link will work in a browser

Powershell confirms the same issue when no UA is specified:

Fails:
Invoke-WebRequest -Uri https://download.filezilla-project.org/client/FileZilla_3.60.1_win64-setup.exe

Successful: Invoke-WebRequest -Uri https://download.filezilla-project.org/client/FileZilla_3.60.1_win64-setup.exe -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27"

### Steps to reproduce

winget install -e --id TimKosse.FileZilla.Client

### Actual behavior

![image](https://user-images.githubusercontent.com/66468791/188488421-e6e807a2-032a-4eac-a864-9eab072e5c3e.png)

PS C:\Users\User> winget install -e --id TimKosse.FileZilla.Client
Found FileZilla Client [TimKosse.FileZilla.Client] Version 3.60.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.filezilla-project.org/client/FileZilla_3.60.1_win64-setup.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).

### Expected behavior

A successful installation would be expected.

The link does work in a browser, but not in WinGet

### Environment

```shell
PS C:\Users\User> winget --info
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.856
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\User>
```

### Screenshots and Logs

[WinGet-2022-09-05-15-48-18.760.log](https://github.com/microsoft/winget-pkgs/files/9491220/WinGet-2022-09-05-15-48-18.760.log)

**Comment by JamieSabbatella** [comment]
I have created a ticket with FileZilla to try and resolve the issue with them.

https://trac.filezilla-project.org/ticket/12768

**Comment by codesquid** [comment]
The infrastructure on filezilla-project.org and its subdomains is meant to be used only by humans and FileZilla itself, not third-party installers.

If you want to re-distribute FileZilla using your third-party installer, you absolutely must host the binaries on your own infrastructure.
For redistribution, please take note of https://filezilla-project.org/license.php and https://filezilla-project.org/trademark_policy.php

**Comment by ItzLevvie** [comment]
Close with reason: See https://github.com/ScoopInstaller/Extras/issues/9179;

**Comment by rollingmoai** [comment]
@codesquid Alternatively, if you don't want third-party installers using the https://filezilla-project.org/ infrastructure, can you at least provide mirrors for the binaries? Sourceforge (which the binaries were previously hosted) or somewhere else would be good.

**Comment by Romanitho** [comment]
The thing is, it might be the case for some other apps no ? 😕

**Comment by UncleDan** [comment]
Does the fact that an installer can work is enough to publish? https://github.com/microsoft/winget-pkgs/pull/162919
