### ISSUE TITLE
[Package Request]: Argus Monitor

### ISSUE THREAD

**Issue by oy1** [microsoft/winget-pkgs#78639]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Argotronic GmbH
Publisher Url: https://www.argusmonitor.com/
Package Name: Argus Monitor
Description: Fan Control and System Monitoring with Argus Monitor
Package Version: 6.0.08
Installer URL: https://www.argusmonitor.com/downloads/ArgusMonitor_Setup.exe

Current Package Identifier (for new versions): ?

**Comment by mdanish-kh** [comment]
Available now with `winget install Argotronic.ArgusMonitor` or `winget install argus-monitor`.
