### ISSUE TITLE
[Package Issue]: Adobe.Acrobat.Reader.64-bit (upgrade not working)

### ISSUE THREAD

**Issue by giggio** [microsoft/winget-pkgs#78654]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Acrobat shows as available for upgrade, but it fails to upgrade.

Versions are:

```
Name                         Id                          Version      Available    Source
-----------------------------------------------------------------------------------------
Adobe Acrobat DC (64-bit)    Adobe.Acrobat.Reader.64-bit 22.001.20169 22.002.20191 winget
```

### Steps to reproduce

Run:

```pwsh
winget upgrade Adobe.Acrobat.Reader.64-bit
```

### Actual behavior

Fails with:

```
winget upgrade Adobe.Acrobat.Reader.64-bit
Found Adobe Acrobat Reader DC (64-bit) [Adobe.Acrobat.Reader.64-bit] Version 22.002.20191
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 150201
```

I can briefly see a window for the installer and it disappears very fast.

### Expected behavior

It upgrades.

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.918
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```


### Screenshots and Logs

_No response_

**Comment by SamaelAmbrona** [comment]
Hello. I also have this issue with both update and new installations. I have tried the manual installation using same command line as in winget logs. The installation started and finished immediately with the following error

![image](https://user-images.githubusercontent.com/103502291/197761283-503de28a-46aa-40a7-bc17-7b9eedf7e214.png)

I attach logs of the installation, in case they help.


[WinGet-2022-10-25-11-07-54.686.log](https://github.com/microsoft/winget-pkgs/files/9859798/WinGet-2022-10-25-11-07-54.686.log)

**Comment by giggio** [comment]
I don't know when, but now I have version `22.003.20263`. It must have upgraded recently when I used `--all`. Maybe the installer itself had a problem with the previous version. I'm closing the issue.

**Comment by SamaelAmbrona** [comment]
I still have the issue with new installation. Please don't close it

**Comment by TheAlienDrew** [comment]
Also experiencing issues trying to update my **Acrobat Pro 64-bit** (originally installed via [Acrobat_DC_Web_x64_WWMUI.zip](https://trials.adobe.com/AdobeProducts/APRO/Acrobat_HelpX/win32/Acrobat_DC_Web_x64_WWMUI.zip)) install with winget, but throws error:
- `Installer failed with exit code: 1603`

I hope you guys know this, but when it comes to Acrobat... there are technically several different installation types, based on the initial install, please overview https://www.adobe.com/devnet-docs/acrobatetk/tools/AdminGuide/identify.html#identifying-dc-installs

I'm sure this is the reason we're having issues upgrading.
