### ISSUE TITLE
Two NSIS packages

### ISSUE THREAD

**Issue by sredna** [microsoft/winget-pkgs#7872]
There seems to be two different NSIS packages.

NSIS/NSIS is out of date.

Nullsoft/NSIS is up to date but Nullsoft technically does not own NSIS, it is an independent open source project these days. 

I don't know how a canonical name is decided but there should only be one package. There are some other 3rd-party NSIS related tools and IDE add-ons (not on winget currently) so keeping all of that under NSIS/* is the best solution?

**Comment by jedieaston** [comment]
This has always confused me too. I'll remove Nullsoft/NSIS and move everything to NSIS/NSIS unless there's an objection?

**Comment by jedieaston** [comment]
The Nullsoft.NSIS package has been removed, so this can be closed.
