### ISSUE TITLE
Installing spotify doesn't work as expected

### ISSUE THREAD

**Issue by anirugu** [microsoft/winget-pkgs#79083]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/35772421/189114690-28150134-c841-4d1b-b6e6-006a29fdbd0f.png)

 I am not sure what is going wrong but look like hash doesn't match. What I believe is spotify team come up with new version and since winget-cli match with the old hash, it's failed. I am just guessing. It might be a different reason, it's work fine in the past. 

### Steps to reproduce

install it by given command, I am on windows 10.

### Expected behavior

it should work and install the software

### Actual behavior

it's failed due to hash mismatch.

### Environment

```shell
Windows 10,
latest winget package ( not preview)
```

**Comment by Trenly** [comment]
This should be resolved by -
* https://github.com/microsoft/winget-pkgs/pull/150294

###### Close with reason: Newer version of Spotify added to repo;
