### ISSUE TITLE
[Package Request]: add EarTrumpet Dev 

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-pkgs#79166]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: File New Project
Publisher Url: https://github.com/File-New-Project
Package Name: File-New-Project.EarTrumpet.Dev
Description: EarTrumpet is a powerful volume control app for Windows. (Dev Version)
Package Version: 2.20.6
Installer URL: https://install.eartrumpet.app/dev/EarTrumpet.Package_2.2.0.6_x86.appxbundle

Current Package Identifier (for new versions): 
https://install.eartrumpet.app/dev/

**Comment by denelon** [comment]
@riverar do you have an opinion here?

I'm not sure if it's a different package family name or if it would cause conflict with the upgrade scenario (assuming you're OK with having it added to the community repository).

**Comment by riverar** [comment]
Thanks for pinging me.

Both dev and non-dev have the same identity (40459File-New-Project.EarTrumpet) and cannot be installed simultaneously, so I don't think this will work well in winget community repository at this time. I'll take an action to give dev builds identity, then can revisit.
