### ISSUE TITLE
[Package Request]: Media Player Classic - Black Edition (MPC-BE)

### ISSUE THREAD

**Issue by th3v4n** [microsoft/winget-pkgs#79281]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: [Aleksoid1978](https://github.com/Aleksoid1978)
Publisher Url: https://github.com/Aleksoid1978/MPC-BE
Package Name: MPC-BE
Description: MPC-BE is a free and open source audio and video player for Windows.
MPC-BE is based on the original Guliverkli project and "Media Player Classic Home Cinema" project, contains additional features and bug fixes.
Package Version: 1.6.4
Installer URL: https://github.com/Aleksoid1978/MPC-BE/releases/download/1.6.4/MPC-BE.1.6.4.x64-installer.zip

Current Package Identifier (for new versions): MPC-BE.1.6.4

**Comment by Trenly** [comment]
This installer is contained in a .zip file and is blocked by microsoft/winget-cli#140
