### ISSUE TITLE
[Package Issue]: Mozilla.Firefox.DeveloperEdition

### ISSUE THREAD

**Issue by arihant2math** [microsoft/winget-pkgs#79299]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I have the latest version of the Developer Edition installed, but winget only detects it as "105.0" when it actually is "105.0b9". This makes winget list it as outdated, but it is up to date.

### Steps to reproduce

- Install Firefox Developer Edition
- Run `winget upgrade`

### Actual behavior

winget detects the installed version of firefox as 105.

### Expected behavior

winget should detect it as 105b9.

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22616.100
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

### Screenshots and Logs

Firefox Developer Edition            Mozilla.Firefox.DeveloperEdition 105.0        105.0b9   winget

**Comment by ppvnf** [comment]
I think it was fixed https://github.com/microsoft/winget-pkgs/pull/79215 and https://github.com/microsoft/winget-pkgs/pull/80578

**Comment by ppvnf** [comment]
Same problem persists with the new version. I've installed 106.0b3, but Winget detects it as 106.0 and says it is out of date

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the manifests which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your problem still persists with the newest versions of Firefox. 

If additional problems persist, it would be extremely helpful if a new issue could be opened. Thanks!

###### Close with reason: Stale;
