### ISSUE TITLE
[Package Request]: Please ad VSCodium Insider

### ISSUE THREAD

**Issue by GitMensch** [microsoft/winget-pkgs#79360]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: VSCodium
Publisher Url: https://github.com/VSCodium/vscodium-insiders
Package Name: VSCodium Insiders
Description: VSCodium... Insider Version
Package Version: [1.72.0.22252-insider](https://github.com/VSCodium/vscodium-insiders/releases/tag/1.72.0.22252-insider)
Installer URL: https://github.com/VSCodium/vscodium-insiders/releases

Current Package Identifier (for new versions): VSCodium.VSCodium - I'd suggest to use VSCodium.Insider or similar.

Note, especially @vedantmgoyal2009: VSCodium.VSCodium currently uses the VSCodium publisher URL, but has "Microsoft Corporation" as publisher, it seems reasonable to change that to "VSCodium".

**Comment by Trenly** [comment]
> Current Package Identifier (for new versions): VSCodium.VSCodium - I'd suggest to use VSCodium.Insider or similar.

By current repo standards, this should be VSCodium.VSCodium.Insiders

> Note, especially @vedantmgoyal2009: VSCodium.VSCodium currently uses the VSCodium publisher URL, but has "Microsoft Corporation" as publisher, it seems reasonable to change that to "VSCodium

"Microsoft Corportation" is actually correct because that is the value VSCodium writes to the Publisher value in the registry

**Comment by GitMensch** [comment]
> "Microsoft Corportation" is actually correct because that is the value VSCodium writes to the Publisher value in the registry

Warning: this changed with the last release (while integrating insiders) https://github.com/VSCodium/vscodium/issues/1227

> `VSCodium.VSCodium` instead of `Microsoft.VSCodium`

**Comment by vedantmgoyal2009** [comment]
VSCodium will be added by the maintainers themselves once they fix the Publisher in the next version.

**Comment by GitMensch** [comment]
So @daiyam will actually handle that, nice.

**Comment by daiyam** [comment]
@GitMensch, yep. Here my steps for winget:
- fix the publisher in the regular (stable) version
- reenable the step in the workflow done by @vedantmgoyal2009  to automate the update on new release
- add the insider version

**Comment by vedantmgoyal2009** [comment]
* https://github.com/microsoft/winget-pkgs/pull/79534

**Comment by vedantmgoyal2009** [comment]
@daiyam can the workflow be re-enabled so that this can be resolved?

**Comment by vedantmgoyal2009** [comment]
* https://github.com/VSCodium/vscodium/pull/1260
