### ISSUE TITLE
[Fix]: Don't require ReleaseNotes for ReleaseNotesUrl in YamlCreate.ps1

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/winget-pkgs#79486]
### Description of the new feature/enhancement

Currently the behavior is that is ReleaseNotes is blank then it will also null out the ReleaseNotesUrl field

https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1#L1992

It should allow a URL without actually copying the release notes themselves - especially as those can often be very large so wouldn't show up nicely when doing `winget show`.

Note this is just for the tool creation script - you can always modify the value afterwards and it doesn't have a problem with that (even more reason to have the tool support this IMO)

**Comment by Trenly** [comment]
Looks like a typo on my end; I'll open a PR with the fix soon

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/winget-pkgs/pull/79487 😄 

Tested locally and it works as expected now
