### ISSUE TITLE
Failed hash verification for Postman pkg

### ISSUE THREAD

**Issue by mcaslop** [microsoft/winget-pkgs#795]
# Description of the new feature/enhancement

I'm getting an error when trying to install postman's package.

![image](https://user-images.githubusercontent.com/25783807/82692565-8f4afa00-9c25-11ea-81c0-f2f02ef84092.png)

I don't know if this happens due the application's build, the manifest integrity, the hash validation method or something else.

The bug was introduced by @wilsonvargas on this [PR-353](https://github.com/microsoft/winget-pkgs/pull/353).

# Proposed technical implementation details (optional)

**Comment by wilsonvargas** [comment]
The real problem is that the download link, even though it contains a version number, actually points to the latest version, and there has been an update published during the last couple of days. 

This PR #816 fixes it

**Comment by jamierocks** [comment]
Fixed with https://github.com/microsoft/winget-pkgs/commit/9d98e7fb16b49af19bf3b5edc4b7209123d7e250.
