### ISSUE TITLE
Winget\upgrade --all

### ISSUE THREAD

**Issue by s4sutler100** [microsoft/winget-pkgs#79589]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/16606451/190039235-0011a6e6-7517-4936-a1ad-3b17a9c35d04.png)

### Steps to reproduce

winget ugrade --all

### Expected behavior

update these programs  silently

Microsoft Visual C++ 2008 Redistributable - x86 9.0… Microsoft.VC++2008Redist-x86  9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2008 Redistributable - x64 9.0… Microsoft.VC++2008Redist-x64  9.0.30729.4148 9.0.30729.6161 winget
Eclipse Temurin JRE with Hotspot 8u332-b09 (x86)     EclipseAdoptium.Temurin.8.JRE 8.0.332.9      8.0.345.1      winget
Eclipse Temurin JDK with Hotspot 8u332-b09 (x86)     EclipseAdoptium.Temurin.8.JDK 8.0.332.9      8.0.345.1      winget

### Actual behavior

Microsoft Visual C++ 2008 Redistributable - x86 9.0… Microsoft.VC++2008Redist-x86  9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2008 Redistributable - x64 9.0… Microsoft.VC++2008Redist-x64  9.0.30729.4148 9.0.30729.6161 winget
Eclipse Temurin JRE with Hotspot 8u332-b09 (x86)     EclipseAdoptium.Temurin.8.JRE 8.0.332.9      8.0.345.1      winget
Eclipse Temurin JDK with Hotspot 8u332-b09 (x86)     EclipseAdoptium.Temurin.8.JDK 8.0.332.9      8.0.345.1      winget  

Java gets updated but acts like nothing happened.
Microsoft.VC++2008Redist-x86 
 Microsoft.VC++2008Redist-x64 
don't get updated.

### Environment

```shell
v1.4.2161-preview
Windows 10 pro v 21H2
```

**Comment by denelon** [comment]
@s4sutler100 what are the results of `winget list`? Do these packages get "upgraded" or do new versions get installed "side-by-side"?

**Comment by xaocon** [comment]
Your screenshot shows you had a typo. `ubknown`

**Comment by s4sutler100** [comment]
when updating MV c++ x86 and x64
says there are newer versions availible.
Won't update to the newer versions.
9.0.30729.6161

Tells me there are two packages to update to 1 is unknown so I type "winget upgrade ---include-unknown"  
and relists the 2 programs im trying to upgrade tto.
Also listing winamp 5.8, wich that version has been installed , but the latest version is actually 5.9. 

http://forums.winamp.com/showthread.php?t=458120&utm_source=socialmedia&utm_medium=twitter&utm_campaign=winamp5.9&utm_term=july2022

**Comment by s4sutler100** [comment]
> Your screenshot shows you had a typo. `ubknown`

yes, am aware of that but fixed it and nothing happens just relists the repository I'm looking for.

**Comment by s4sutler100** [comment]
> @s4sutler100 what are the results of `winget list`? Do these packages get "upgraded" or do new versions get installed "side-by-side"?

Define  "side-by-side"

"what are the results of `winget list`?"
![image](https://user-images.githubusercontent.com/16606451/190718688-c9b64c20-cd8c-42a3-a2f6-8e7d6c83053c.png)   
![image](https://user-images.githubusercontent.com/16606451/190718793-f4b0d49e-d356-4a36-8c4b-7dcd0c94babf.png)
"Do these packages get "upgraded"" NO
"Do new versions get installed?" NO

**Comment by s4sutler100** [comment]
the repository lists Winamp still needing to be updated to 5.8 when in fact 5.9 is the latest version.

**Comment by s4sutler100** [comment]
When I "winget upgrade --all" Winamp acts clueless and reinstalls 5.8.

**Comment by mdanish-kh** [comment]
> the repository lists Winamp still needing to be updated to 5.8 when in fact 5.9 is the latest version.

`5.9` has not been added to winget. A dependency issue is blocking `5.9` from being merged.
- #79220

**Comment by s4sutler100** [comment]
> > the repository lists Winamp still needing to be updated to 5.8 when in fact 5.9 is the latest version.
> 
> `5.9` has not been added to winget. A dependency issue is blocking `5.9` from being merged.
> 
> * [Radionomy.Winamp version 5.9 #79220](https://github.com/microsoft/winget-pkgs/pull/79220)
Ok thank you, good to know.
At least needs to stop reinstalling once already upgraded.

**Comment by s4sutler100** [comment]
hello?
