### ISSUE TITLE
[Package Request]: Add Neovim Nightly

### ISSUE THREAD

**Issue by trbrink** [microsoft/winget-pkgs#79698]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:  neovim.io
Publisher Url:  https://neovim.io
Package Name:  Neovim Nightly
Description:  Vim-fork focused on extensibility and usability
Package Version:  0.8.0-dev-1092-g89b9eab63
Installer URL:  https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi

Current Package Identifier (for new versions):

**Comment by vedantmgoyal2009** [comment]
Thanks for the initial PR. The later updates will be automated.

**Comment by p00f** [comment]
how do i upgrade this? `winget upgrade --id Neovim.Neovim.Nightly` doesn't work because the "version" is always `0.11.0` (i.e. the one after the current release) so winget says `No newer package versions are available from the configured sources`
