### ISSUE TITLE
YamlCreate doesn't trim trailing whitespace

### ISSUE THREAD

**Issue by russellbanks** [microsoft/winget-pkgs#79955]
The [editorconfig](https://github.com/microsoft/winget-pkgs/blob/73c31e56ac29f897bdf24c8c1e40321cc5f0f4ec/.editorconfig#L9) specifies that trailing whitespaces should be trimmed, whereas yamlcreate doesn't do this. Opening a manifest that was created with yamlcreate in VSCode with the editorconfig plugin removes those whitespaces.

- https://github.com/microsoft/winget-pkgs/pull/79954

cc: @Trenly

**Comment by Trenly** [comment]
I did notice this but haven’t been able to figure out exactly whats causing it. I have a few ideas, but will investigate more tonight

**Comment by Trenly** [comment]
Found the issue; Will have a PR out tonight

**Comment by Trenly** [comment]
Detailed information on the cause is in the [commit message](https://github.com/Trenly/winget-pkgs/commit/474defdd6bc9584a0b900c29ad5f642b20b31d6f)
