### ISSUE TITLE
[Package Issue]: [Plex.Plexamp]

### ISSUE THREAD

**Issue by Xarishark** [microsoft/winget-pkgs#79999]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer tries to install Microsoft.VC++2015-2019Redist-x64 dependency while I have Microsoft.VC++2015-2022Redist-x64 installed and the installation fails.

### Steps to reproduce

1. Have Microsoft.VC++2015-2022Redist-x64 installed
2. winget install plex.plexamp

### Actual behavior

The installation fails and throws a Another version of this application is already installed. error for the dependency.
![image](https://user-images.githubusercontent.com/21146743/190899998-44e9d0e4-f7f1-4049-aecb-5911318f5230.png)

### Expected behavior

Both 2019 and 2022 packages are acceptable so the manifest should include them both and if one is installed it should mark as all dependencies are installed.

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22622.598
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

**Comment by denelon** [comment]
Related to:

* microsoft/winget-cli/issues/1789
* microsoft/winget-cli/issues/2103

**Comment by OfficialEsco** [comment]
Could you check now? We merged VC++2015 to VC++2015-2022 since they apparently use the same upgrade path.

**Comment by Trenly** [comment]
[Policy] Needs-Author-Feedback
