### ISSUE TITLE
[Package Issue]: calibre.calibre

### ISSUE THREAD

**Issue by CaptainGlac1er** [microsoft/winget-pkgs#80008]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Looks like there is a download for 6.5.0 but it is trying to download a 6.4.0 which returns a 404 

### Steps to reproduce

winget upgrade calibre.calibre

### Actual behavior

> winget upgrade calibre.calibre
Found calibre [calibre.calibre] Version 6.4.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/kovidgoyal/calibre/releases/download/v6.4.0/calibre-64bit-6.4.0.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Expected behavior

Application updates

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.978
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

### Screenshots and Logs

> winget upgrade calibre.calibre
Found calibre [calibre.calibre] Version 6.4.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/kovidgoyal/calibre/releases/download/v6.4.0/calibre-64bit-6.4.0.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

**Comment by mdanish-kh** [comment]
Looks like the publisher only retains the installer URLs of the latest release. This issue will be resolved once #79703 gets merged.
