### ISSUE TITLE
WinGetSvc-Validation (Manifest Content Validation) fails

### ISSUE THREAD

**Issue by javiergualix** [microsoft/winget-pkgs#806]
Hi,

I'm getting a failed WinGetSvc-Validation (Manifest Content Validation) when trying to submit the MEGASync installer #804. The job sais GET requests are not supported by the copy source, but in the previous line I can see the installer URL with a dot (.) at the end of line, making the URL inaccessible https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=82031&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=40

`5/22/2020 6:28:17 PM
Status: Completed
Result: Failed
Error occurred during installer copy from https://mega.nz/MEGAsyncSetup.exe.
Range GET requests are not supported by the copy source.`

This character doesn't appear in the YAML file. I validated and tried the Winget YAML file on my machine and everything worked well.

**Comment by chausner** [comment]
See https://github.com/microsoft/winget-pkgs/issues/523.

**Comment by denelon** [comment]
@javiergualix I'm scanning over old issues. It looks like the range request issue is closed. I did a quick search and found "Mega.MEGASync 4.4.0.0". I'm going to close this issue. Feel free to reopen if it's not the same package you were looking for.
