### ISSUE TITLE
[New Feature]: Custom symbolic link for portable installers

### ISSUE THREAD

**Issue by cnshenj** [microsoft/winget-pkgs#80607]
### Description of the new feature/enhancement

1.3 now supports `portable` installer type. A symbolic link to the portable executable will be automatically created. However, the symbolic link may be too long, for example:
```
<SYMLINK>      mkcert-v1.4.4-windows-amd64.exe [C:\Users\username\AppData\Local\Microsoft\WinGet\Packages\FiloSottile.mkcert__DefaultSource\mkcert-v1.4.4-windows-amd64.exe]
```
To use the package, we have to type `mkcert-v1.4.4-windows-amd64` every time. If we can add an additional symbolic link like `mkcert`, then it would be much more convenient.

### Proposed technical implementation details (optional)

Please consider adding a property `CustomSymLink` to `installer.yml`.
```yaml
InstallerType: portable
CustomSymLink: mkcert
```

**Comment by Trenly** [comment]
Setting the value of `Commands` changes the symlink. For example:
```yaml
Commands: 
- mkcert
```

**Comment by cnshenj** [comment]
Thanks! Closed.
