### ISSUE TITLE
[Package Issue]: BraveSoftware.BraveBrowser

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#80719]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

This is Brave's latest version: https://github.com/brave/brave-browser/releases/tag/v1.43.93
Latest Brave version number in Winget is incorrect and outdated: https://github.com/microsoft/winget-pkgs/pull/76696

Related:
https://github.com/microsoft/winget-pkgs/issues/77220

### Steps to reproduce

1. Download and Install Brave through Winget
2. Go to about page and check for update. 
3. Brave will update to the version I mentioned above

### Actual behavior

Latest Brave version number in Winget is incorrect and outdated: https://github.com/microsoft/winget-pkgs/pull/76696

### Expected behavior

This is Brave's latest version: https://github.com/brave/brave-browser/releases/tag/v1.43.93

### Environment

```shell
v1.3.2091
Windows.Desktop v10.0.19044.2006
X64
Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by ppvnf** [comment]
@mdanish-kh Thanks, but shouldn't the version be 105.0.5195.127 or 1.43.93 instead of combining both?

**Comment by mdanish-kh** [comment]
The package version should be the one matching Control Panel / Apps & Features. 
![image](https://user-images.githubusercontent.com/88161975/192124891-f3ed96d8-50e2-4298-9553-610c17ffb977.png)
