### ISSUE TITLE
[Package Request]:  IrfanView PlugIns

### ISSUE THREAD

**Issue by borque** [microsoft/winget-pkgs#80745]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

**Publisher:**
Irfan Skiljan
**Publisher Url:**
https://www.irfanview.com
**Package Name:**
IrfanView PlugIns
**Description:**
An official collection of many additional image and file formats to be displayed by the popular image viewer IrfanView after installation.
The main programme IrfanView is available using winget as a seperate download.
The plugins need to be installed in the corresponding version of the main programme and are provided by the original author.
**Package Version:**
4.60
**Installer URL:**
https://www.fosshub.com/IrfanView.html/iview460_plugins_setup.exe (32bit)
https://www.fosshub.com/IrfanView.html/iview460_plugins_x64_setup.exe (64bit)

**Comment by borque** [comment]
I just received a mail telling me that IrfanView is already available. I am aware of that. But my request is not concerning the main programme, but the additional plugin package which is released as a separate installer.

And this seems to be not included in the winget installer script for the main programme.

**Comment by OfficialEsco** [comment]
Ref: https://github.com/microsoft/winget-pkgs/pull/21591 and https://github.com/microsoft/winget-pkgs/pull/59777

We do not have IrfanView Plugins because it needs IrfanView to be installed, this can be resolved by adding IrfanView as the dependency, however that requires https://github.com/microsoft/winget-cli/issues/163 to be completed and be in the Stable version.

**Comment by borque** [comment]
Ah, allright! I had not noticed that the dependencies are not yet part of the stable winget. Thus I have proposed a manifest a few moments before your reply...

**Comment by Trenly** [comment]
@msftbot Dependencies

**Comment by Trenly** [comment]
@MSFTbot Dependencies

**Comment by Trenly** [comment]
@MSFTbot Blocking-Issue

**Comment by Trenly** [comment]
@MSFTbot Dependencies

**Comment by Sn1cket** [comment]
> Ah, allright! I had not noticed that the dependencies are not yet part of the stable winget. Thus I have proposed a manifest a few moments before your reply...

I think this should work now with the release version 1.6 of winget.

**Comment by stephengillie** [comment]
Is the `4.60` version of this package still available? 

I'll close this now, as newer versions of this package appear to be in the repo:

```PowerShell
PS C:\ManVal> (Find-WinGetPackage IrfanSkiljan.IrfanView.PlugIns).AvailableVersions
4.66
4.62
```

Please let me know if this is in error, and I'll reopen.
