### ISSUE TITLE
[Package Issue]: VentisMedia.MediaMonkey

### ISSUE THREAD

**Issue by DonEstefan** [microsoft/winget-pkgs#80835]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Side-By-Side installation.

### Brief description of your issue

The package VentisMedia.MediaMonkey claims to upgrade MediaMonkey from version 4 to version 5. However, the updater installs version 5 side-by-side with version 4 instead of doing an in-place upgrade. This behavior is intended and also documented here: https://www.mediamonkey.com/support/knowledge-base/purchasing-licensing-mediamonkey-for-windows/upgrade-mediamonkey-for-windows/ -> "Upgrading MediaMonkey 4 —> 5".
This basically means, that there is no direct upgrade path from version 4 to 5. To reflect this in winget, it would make sense to 
split MediaMonkey  in 2 separate packages `VentisMedia.MediaMonkey4` and `VentisMedia.MediaMonkey5` with a fixed version detection and separate update paths.

```
C:\>winget list --name mediamonkey
Name            ID                      Version Verfügbar Quelle
----------------------------------------------------------------
MediaMonkey 4.1 VentisMedia.MediaMonkey 4.1     5         winget
MediaMonkey 5   MediaMonkey 5_is1       5

```

### Steps to reproduce

* install Mediamonkey4 from the homepage (https://www.mediamonkey.com/MediaMonkey-4_Setup.exe)
* do a `winget upgrade VentisMedia.MediaMonkey` to start the update
* another `winget upgrade` will still show Mediamonkey5 as an available update for Mediamonkey4, even if it has successfully been applied in the previous step

### Actual behavior

`winget upgrade VentisMedia.MediaMonkey` does a side-by-side installation of Mediamonkey5 when Mediamonkey4 is installed (instead of an in-place upgrade). 

### Expected behavior

winget upgrade should not detect Mediamonkey 5 as an update for Mediamonkey 4.

### Environment

```shell
Windows: Windows.Desktop v10.0.19044.2006
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by Trenly** [comment]
Close with reason: Resolved by above PRs;
