### ISSUE TITLE
[Package Request]: zoxide

### ISSUE THREAD

**Issue by ajeetdsouza** [microsoft/winget-pkgs#80892]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Ajeet D'Souza
Publisher Url: https://github.com/ajeetdsouza/zoxide
Package Name: zoxide
Description: A smarter cd command. Supports all major shells.
Package Version: v0.8.3
Installer URL: https://github.com/ajeetdsouza/zoxide/releases/tag/v0.8.3

---

> I have checked that the installer for this package is not contained in a .zip file

Support for .zip files seems to have been merged, so I think this should be possible now.

**Comment by denelon** [comment]
We will wait until 1.4 is GA with >50% rollout before we start accepting .zip packages.

We will add a few for early adoption and validation, but we haven't decided which packages that will be yet.

I added the blocking-issue and .zip labels so we can find them when support is enabled.

**Comment by ajeetdsouza** [comment]
That works, thanks!
