### ISSUE TITLE
[Package Issue]: JetBrains.PHPStorm doesn't detect installed version correctly

### ISSUE THREAD

**Issue by Sirs0ri** [microsoft/winget-pkgs#81122]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I noticed thatwinget seems to compare the build number of the local PHPStorm instance (eg. 222.4167.33) against the version number of the latest available version (eg. 2022.2.2), causing winget to think there's an update available, even though both numbers refer to the same version of PHPStorm.

PHPStorm also reports its build number in Window's "Programs and features" dialog.

### Steps to reproduce

Install PHPstorm:
```PS> winget install JetBrains.PHPStorm```

Check for a new version:
```PS> winget search phpstorm```

It'll show that you've installed version 222.4167.33 (the current build number), while 2022.2.2 (the current version number) is available.

Running `winget upgrade --all` will trigger a reinstall of the current version.

### Actual behavior

Winget compares the installed version's build number against the available version's human-readable version, detecting a mismatch and causing a reinstall.

### Expected behavior

Winget should compare the installed version's build number (which the program seems to report as its "version" to other windows dialogs as well" against a repository of build numbers, not human readable numbers to detect that build number 222.4167.33 is in fact the latest version.

### Environment

```shell
**Winget**
Windows-Paket-Manager v1.2.11601
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22622.601
Paket: Microsoft.DesktopAppInstaller v1.17.11601.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

**PhpStorm**
PhpStorm 2022.2.2
Build #PS-222.4167.33, built on September 15, 2022
<licensing info removed>
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=15
```

### Screenshots and Logs

```
PS> winget search phpstorm
Name           ID                             Version     Quelle
-----------------------------------------------------------------
PhpStorm       JetBrains.PHPStorm             2022.2.2    winget
```
[WinGet-2022-09-30-01-01-22.844.log](https://github.com/microsoft/winget-pkgs/files/9679587/WinGet-2022-09-30-01-01-22.844.log)

```
PS> winget list phpstorm
Name     ID                 Version     Verfügbar Quelle
--------------------------------------------------------
PhpStorm JetBrains.PHPStorm 222.4167.33 2022.2.2  winget
```
[WinGet-2022-09-30-01-11-51.719.log](https://github.com/microsoft/winget-pkgs/files/9679588/WinGet-2022-09-30-01-11-51.719.log)

**Comment by jedieaston** [comment]
Improvements have been made to the matching system in winget 1.3 (once you upgrade, this issue should go away). You can download it here: https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091

**Comment by Sirs0ri** [comment]
Yap, with 1.3 winget correctly recognises my installed version as 2022.2.2, and shows it as the latest version available

Awesome!
