### ISSUE TITLE
[Package Issue]: Package.Identifer

### ISSUE THREAD

**Issue by thorrrr** [microsoft/winget-pkgs#82264]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Hi 
Been trying for weeks and WInget will not install any of the Microsoft.VCRedist.2013.x86

![image](https://user-images.githubusercontent.com/8170673/193583848-04959b92-3883-404f-9727-64c442d9b8aa.png)

Have these installed

![image](https://user-images.githubusercontent.com/8170673/193584858-e6884e0b-da89-4d96-a276-96e38b4d4db7.png)

### Steps to reproduce

Winget Upgrade with ID does not work

### Actual behavior

Nothing

### Expected behavior

To install

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1042
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

Listed above

**Comment by Trenly** [comment]
Your screenshot shows you have two different versions of 2013-x86 installed
![image](https://user-images.githubusercontent.com/12611259/193592450-2352da6e-0328-410a-8e6f-e443c84545db.png)

Removing the older version should fix the issue

**Comment by thorrrr** [comment]
cheers
