### ISSUE TITLE
Upgrading PostgreSQL 14.5 is not reflected.

### ISSUE THREAD

**Issue by dmdragon** [microsoft/winget-pkgs#82335]
### Brief description of your issue

Run the PostgreSQL 14 upgrade, the 14.5 installer will be run and the version will be 14.5, but then run the winget upgrade,  get PostgreSQL 14.5 again.

### Steps to reproduce

1. Run `winget upgrade`
1. Postgres 14 (ID: PostgreSQL.PostgreSQL) Version 14.5 is found.
1. Run `winget upgrade --id PostgreSQL.PostgreSQL`
1. PostgreSQL 14.5 will be installed.
1. Check the PostgreSQL version, it is 14.5.
    ```
    postgres=# SELECT Version();
                              version
    ------------------------------------------------------------
     PostgreSQL 14.5, compiled by Visual C++ build 1914, 64-bit
    ```
1.  Re-run `winget upgrade`, also find Postgres 14 version 14.5.

### Expected behavior

After the installation of PostgreSQL 14.5 is complete, when run `winget upgrade`, PostgreSQL does not come up.

### Actual behavior

After the installation of PostgreSQL 14.5 is complete, when run `winget upgrade`, PostgreSQL come up.

### Environment

```shell
Windows Package Manager v1.3.2091
Windows: Windows.Desktop v10.0.22621.521
System Arthitecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by denelon** [comment]
If running `winget upgrade PostgreSQL` installs another version and doesn't update the previous version, we may need to look at adding the "uninstallPrevious" key to the manifest. If you run `winget list` and you see two entries that is likely the case. We've got some work coming to look at the upgrade command to detect if the latest version is already installed and not end up in a loop because the earlier version is still present.

**Comment by dmdragon** [comment]
Thanks.

When I run `winget upgrade PostgreSQL`, the latest version of the installer is downloaded, run, and upgraded it, but then run `winget upgrade` command again, the old version remains on the display and is a candidate for upgrade. When `winget list` is run, there is one entry.

**Comment by jantari** [comment]
I looked into this and it is because the Postgres Installer that [EnterpriseDB](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) packages doesn't set the Version information in the registry / control panel correctly:

```
Administrator in ~
❯ Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" |
∙   Where { $_.GetValue('DisplayName') -like "*post*" }

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

Name                           Property
----                           --------
PostgreSQL 14                  DisplayVersion  : 14
                               Publisher       : PostgreSQL Global Development Group
                               DisplayName     : PostgreSQL 14
                               UrlInfoAbout    : http://www.postgresql.org/
                               HelpLink        : http://www.postgresql.org/docs
                               Comments        : The PostgreSQL RDBMS, version 14, packaged by EnterpriseDB
                               Contact         :
                               VersionMajor    : 14
                               MajorVersion    : 14
                               VersionMinor    : 0
                               MinorVersion    : 0
                               UninstallString : "C:\Program Files\PostgreSQL\14\uninstall-postgresql.exe"
                               InstallLocation : C:\Program Files\PostgreSQL\14
                               NoModify        : 1
                               NoRepair        : 1
                               EstimatedSize   : 950654
                               InstallDate     : 20221010


Administrator in ~
❯ echo "SELECT Version();" | & "C:\Program Files\PostgreSQL\14\bin\psql.exe" postgresql://postgres:postgres@localhost:5432
                          version
------------------------------------------------------------
 PostgreSQL 14.5, compiled by Visual C++ build 1914, 64-bit
(1 Zeile)
```

It reported 14.0 even for the 14.1 I had previously installed. They just don't set the minor versions. I fear it's an issue that would have to be communicated to them as they publish the Windows installer.

**Comment by jantari** [comment]
@denelon allowing to specify a file path and matching against the ProductVersion in that files' metadata could be an option.

```
~\Documents
❯ Get-Item "${env:ProgramFiles}\PostgreSQL\14\bin\psql.exe" | fl *

PSPath              : Microsoft.PowerShell.Core\FileSystem::C:\Program Files\PostgreSQL\14\bin\psql.exe
PSParentPath        : Microsoft.PowerShell.Core\FileSystem::C:\Program Files\PostgreSQL\14\bin
PSChildName         : psql.exe
PSDrive             : C
PSProvider          : Microsoft.PowerShell.Core\FileSystem
PSIsContainer       : False
Mode                : -a---
ModeWithoutHardLink : -a---
VersionInfo         : File:             C:\Program Files\PostgreSQL\14\bin\psql.exe
                      InternalName:
                      OriginalFilename:
                      FileVersion:      14.5
                      FileDescription:  psql - the PostgreSQL interactive terminal
                      Product:          PostgreSQL
                      ProductVersion:   14.5
                      Debug:            False
                      Patched:          False

[ ... truncated ...]
```

ansibles `win_package` module supports that as a fallback option too: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_package_module.html#parameter-creates_version

**Comment by dmdragon** [comment]
Recently, PostgreSQL 15 was released, so I upgraded and uninstalled PostgreSQL 14.5.
As a result, PostgreSQL (15) no longer shows up in `winget upgrade`.
However, PostgreSQL 15 does not yet have a minor version, so it may recur during a minor upgrade.

```powershell
PS C:\>  Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" | Where { $_.GetValue('DisplayName') -like "*post*" }

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

Name                           Property
----                           --------
PostgreSQL 15                  DisplayVersion  : 15
                               Publisher       : PostgreSQL Global Development Group
                               DisplayName     : PostgreSQL 15
                               UrlInfoAbout    : http://www.postgresql.org/
                               HelpLink        : http://www.postgresql.org/docs
                               Comments        : The PostgreSQL RDBMS, version 15, packaged by EnterpriseDB
                               Contact         :
                               VersionMajor    : 15
                               MajorVersion    : 15
                               VersionMinor    : 0
                               MinorVersion    : 0
                               UninstallString : "C:\Program Files\PostgreSQL\15\uninstall-postgresql.exe"
                               InstallLocation : C:\Program Files\PostgreSQL\15
                               NoModify        : 1
                               NoRepair        : 1
                               EstimatedSize   : 953141
                               InstallDate     : 20221016

PS C:\>
```

**Comment by kdpuvvadi** [comment]
i think for postgresql, different major version should have their own `PackageIdentifier` for e.g for v13 `PostgreSQL.PostgreSQL.13` , for v12 `PostgreSQL.PostgreSQL.12` and so on.  

```
 $ winget update
Name                        Id                    Version  Available
--------------------------------------------------------------------
PostgreSQL 13               PostgreSQL.PostgreSQL 13       14.5
PostgreSQL 14               PostgreSQL.PostgreSQL 14       14.5
```

it would then be

```
 winget update
Name                        Id                         Version  Available
-------------------------------------------------------------------------
PostgreSQL 13               PostgreSQL.PostgreSQL.13   13       13.8
PostgreSQL 14               PostgreSQL.PostgreSQL.14   14       14.5
```

**Comment by jantari** [comment]
@kdpuvvadi no, if you want to install a specific older version then use `winget install --version`

**Comment by kdpuvvadi** [comment]
What i'm saying here is a suggestion mate to the maintainers like @denelon

**Comment by MarcelStranak** [comment]
Got the same issue with the following packages:

```
Name                        Id                    Version Available Source
--------------------------------------------------------------------------
PostgreSQL 14               PostgreSQL.PostgreSQL 14      14.5      winget
OpenSSL (64-bit)            ShiningLight.OpenSSL  1.0.0   3.0.8     winget
MySQL Installer - Community Oracle.MySQL          1.6.4.0 8.0.31    winget
```

**Comment by denelon** [comment]
This looks like a case where the installer doesn't report the version to the registry that was upgraded.

**Comment by denelon** [comment]
WinGet looks at the "displayVersion" key used to drive the Windows Apps & Features version. 

*Note, it's the value below the "displayName".*

**Comment by MarcelStranak** [comment]
Thanks. The manual workaround worked. Changing the values in "displayVersion" to corresponding versions, stopped the problem for now.

**Comment by Danik1601** [comment]
> I looked into this and it is because the Postgres Installer that [EnterpriseDB](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) packages doesn't set the Version information in the registry / control panel correctly:
> 
> It reported 14.0 even for the 14.1 I had previously installed. They just don't set the minor versions. I fear it's an issue that would have to be communicated to them as they publish the Windows installer.

I reported it here, got an answer:
https://www.postgresql.org/message-id/18040-bd2f19c82c5110c5@postgresql.org
