### ISSUE TITLE
[Package Request]: voidtools.Everything

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#82462]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: voidtools
Publisher Url: https://www.voidtools.com/
Package Name: voidtools.Everything
Description: Locate files and folders by name instantly.
Package Version: 1.4.1.1021
Installer URL: https://www.majorgeeks.com/files/details/everything.html

Current Package Identifier (for new versions): 1.4.1.1020
I believe https://www.voidtools.com/downloads/ isn't working for tracking new releases, how about Major Geeks? 

Previous issue:
https://github.com/microsoft/winget-pkgs/issues/80627

**Comment by mdanish-kh** [comment]
I do see the new version on their official website 
![image](https://user-images.githubusercontent.com/88161975/193908330-87d7d9af-a74e-4787-8685-94a9b787ca3b.png)

**Comment by ppvnf** [comment]
> I do see the new version on their official website ![image](https://user-images.githubusercontent.com/88161975/193908330-87d7d9af-a74e-4787-8685-94a9b787ca3b.png)

Shouldn't new versions be automatically added to Winget? I thought there was something wrong with the official website

**Comment by mdanish-kh** [comment]
As of yet, winget does not have the ability do perform such automation.

- https://github.com/microsoft/winget-pkgs/issues/500#issuecomment-922064882

**Comment by vedantmgoyal2009** [comment]
You can create an issue to add the package to the automation at https://github.com/vedantmgoyal2009/vedantmgoyal2009.

**Comment by ppvnf** [comment]
> You can create an issue to add the package to the automation at https://github.com/vedantmgoyal2009/vedantmgoyal2009.

I am gonna do it, thanks!

**Comment by ppvnf** [comment]
thanks
