### ISSUE TITLE
[Package Issue]: Ditto.Ditto needs updating

### ISSUE THREAD

**Issue by RadAd** [microsoft/winget-pkgs#82555]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

New package available, manifest needs updating.

### Steps to reproduce

```
Found Ditto [Ditto.Ditto]
Version: 3.24.214.0
Publisher: Scott Brogden
Publisher Url: https://sourceforge.net/projects/ditto-cp/
Publisher Support Url: https://github.com/sabrogden/Ditto/issues
Author: Scott Brogden
Moniker: ditto
Description: Ditto is an extension to the standard windows clipboard. It saves each item placed on the clipboard allowing you access to any of those items at a later time.
Homepage: https://ditto-cp.sourceforge.io
License: GPL-3.0-only
License Url: https://raw.githubusercontent.com/sabrogden/Ditto/master/DittoSetup/Chocolatey/tools/LICENSE.txt
Copyright Url: https://raw.githubusercontent.com/sabrogden/Ditto/master/DittoSetup/Chocolatey/tools/LICENSE.txt
Installer:
  Type: inno
  Locale: en-US
  Download Url: https://github.com/sabrogden/Ditto/releases/download/3.24.214.0/DittoSetup_64bit_3_24_214_0.exe
  SHA256: 07d72975d8c16bca021da2e0378a0ffb0f63e327909bf9197df7081732fb1ddb
```

### Actual behavior

Version 3.24.214.0 is outdated.

### Expected behavior

Website show Version 3.24.238.0 is available.
See https://ditto-cp.sourceforge.io/

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2006
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
Getting this for the x86 installer:
![image](https://user-images.githubusercontent.com/88161975/194225894-1985ae84-745d-4573-b0c5-1ac43c64466b.png)

**Comment by RadAd** [comment]
Which anti-virus do you use?
VirusTotal say its ok https://www.virustotal.com/gui/url/f87abee4e1b8e5e2ab08195c96c0a13e6b7d1b6776095891376d4d973caf6bb5?nocache=1

**Comment by mdanish-kh** [comment]
> Which anti-virus do you use? VirusTotal say its ok https://www.virustotal.com/gui/url/f87abee4e1b8e5e2ab08195c96c0a13e6b7d1b6776095891376d4d973caf6bb5?nocache=1

![image](https://user-images.githubusercontent.com/88161975/194226943-9c0996f9-06fa-4095-9d73-485e61329a55.png)

Maybe a false positive, but it's getting flagged by Windows Defender.

**Comment by RadAd** [comment]
I scanned it with Windows Defender, seems ok for me.

**Comment by mdanish-kh** [comment]
> I scanned it with Windows Defender, seems ok for me.

I'll create a draft PR and let it run through the pipelines, maybe it's an issue at my end.
