### ISSUE TITLE
New version of Wireshark drops 32-bit support - how to handle depreciated architectures?

### ISSUE THREAD

**Issue by gknutson1** [microsoft/winget-pkgs#82562]
Recently, [version 4.0.0 of Wireshark](https://www.wireshark.org/news/20221004.html) was released. This version [drops support for 32-bit operating systems](https://gitlab.com/wireshark/wireshark/-/issues/17779). I am unsure as to how this upgrade should be handled, and can think of two different possibilities:

- I submit the new version as normal, updating `WiresharkFoundation.Wireshark` and removing the 32-bit executables
-  or I rename `WiresharkFoundation.Wireshark` to `WiresharkFoundation.Wireshark.3` and create the new version as `WiresharkFoundation.Wireshark.4`

Option two is not unprecedented - see `SublimeHQ.SublimeText.3` and `SublimeHQ.SublimeText.4` - and it would allow people who want 32-bit versions of Wireshark to still use winget. However, I am unsure how auto-updates from `WiresharkFoundation.Wireshark` would be handled.

I looked around a bit and was unable to find anything about this situation in the documentation.

**Comment by Trenly** [comment]
Winget detects architecture support, so dropping the x86 installers and just using WiresharkFoundation.Wireshark will be good enough. If a user is on x86 they will see a "No applicable installer" message when trying to specifically update the package, and it will be skipped when using --all

**Comment by gknutson1** [comment]
Ok, thank you for your help.
