### ISSUE TITLE
[Package Issue]: Microsoft.OpenJDK.17 duplicate manifest v17.0.4.1(01)

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#82576]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

There seems to be duplicate manifests for Microsoft.OpenJDK.17, version 17.0.4.1(01).

There may also be a `PackageVersion` versus `AppsAndFeaturesEntry.DisplayVersion` issue for all 17.0.4 versions.

This may be related to [my issue](https://github.com/microsoft/winget-pkgs/issues/67792#issuecomment-1233398585) regarding updating Microsoft.OpenJDK.17.

### Steps to reproduce

These two installer.yaml files are identical (except for the `PackageVersion` obviously):

`.\manifests\m\Microsoft\OpenJDK\17\17.0.4.1\Microsoft.OpenJDK.17.installer.yaml`
`.\manifests\m\Microsoft\OpenJDK\17\17.0.4.101\Microsoft.OpenJDK.17.installer.yaml`

They were added by #71801 and #71917 and a "Possible duplicate package entry." [flagged by wingetbot](https://github.com/microsoft/winget-pkgs/pull/71917#issuecomment-1226299456) in the latter PR.

Looking at the [OpenJDK 17 download](https://learn.microsoft.com/en-US/java/openjdk/download) page, I think there may also be a `PackageVersion` versus `AppsAndFeaturesEntry.DisplayVersion` issue (or similar). The current version is "branded" as 17.0.4.1 LTS, but installs as 17.0.4.101 (ARP display version, ARP name: "Microsoft Build of OpenJDK with Hotspot 17.0.4.1+1 (x64)"). 

The [previous version](https://learn.microsoft.com/en-US/java/openjdk/older-releases#openjdk-17) is "branded" as 17.0.4, but installs as 17.0.4.8 (ARP name: "Microsoft Build of OpenJDK with Hotspot 17.0.4+8 (x64)". The related manifest is `.\manifests\m\Microsoft\OpenJDK\17\17.0.4.8\`

Maybe the latter is also relevant for the Microsoft.OpenJDK.11 issue in #67792? I didn't investigate this further.

### Actual behavior

see above

### Expected behavior

see above

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.2006
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by denelon** [comment]
@schandra13 Is the intent to have a marketing version that can differ from the version reported to Windows Apps & Features? If that's the case, are you just waiting to remove the duplicate entry?

**Comment by dpprdan** [comment]
@denelon is @schandra13 a member of the Microsoft OpenJDK team? Otherwise I am a bit puzzled that it is necessary to rely on community contributions to get Microsofts' OpenJDK's manifests added (or rather that this does not happen automatically on release but has to be done manually).

**Comment by dpprdan** [comment]
> There may also be a `PackageVersion` versus `AppsAndFeaturesEntry.DisplayVersion` issue [...]
> Maybe the latter is also relevant for the Microsoft.OpenJDK.11 issue in #67792? I didn't investigate this further.

I looked into this a bit more and am _pretty_ sure that this is the case. The latest version is [branded as 11.0.16.1](https://learn.microsoft.com/en-US/java/openjdk/download#openjdk-110161-lts--see-previous-releases) and the ARP and manifest version is [11.0.16.101](https://github.com/microsoft/winget-pkgs/blob/1dbc124420ab9cf3992a06c43977cf4300ad2c81/manifests/m/Microsoft/OpenJDK/11/11.0.16.101/Microsoft.OpenJDK.11.installer.yaml#L5)

**Comment by schandra13** [comment]
> @schandra13 Is the intent to have a marketing version that can differ from the version reported to Windows Apps & Features? If that's the case, are you just waiting to remove the duplicate entry?

The reason you are seeing the different versions was because of the respin of release we had. So we added a new version of the jdk then. They look similar but they are different - the shas, package versions etc

**Comment by dpprdan** [comment]
> They look similar but they are different - the shas,

That's the thing, they are not:

https://github.com/microsoft/winget-pkgs/blob/f25a73708bb4cecfa3ca5b672f45a8fdb3be0165/manifests/m/Microsoft/OpenJDK/17/17.0.4.1/Microsoft.OpenJDK.17.installer.yaml#L20
https://github.com/microsoft/winget-pkgs/blob/f25a73708bb4cecfa3ca5b672f45a8fdb3be0165/manifests/m/Microsoft/OpenJDK/17/17.0.4.101/Microsoft.OpenJDK.17.installer.yaml#L20

> package versions etc

Well, that's just `PackageVersion` versus `AppsAndFeaturesEntry.DisplayVersion`, isn't it?

**Comment by d3r3kk** [comment]
After I sort out the fix for this issue, I'll have a look into the other #67792 issue to see what might be happening there and look for improvements we could make for Oct-PSU regarding that problem, too.

**Comment by ItzLevvie** [comment]
Close with reason: This is solved now;
