### ISSUE TITLE
[Package Issue]: CondaForge.Mambaforge

### ISSUE THREAD

**Issue by ptanmay143** [microsoft/winget-pkgs#82610]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

Similar to #36706 multiple entries for Mambaforge are being created after using `winget` to upgrade them.

- Trying to uninstall old version from `Add or remove programs` seems to open uninstall window for latest version.
- Install path/location only has the latest version.
- So the only extra thing is the remnant of the old version in the `Add or remove programs` list.

### Steps to reproduce

1. Upgrade installed mambaforge package using `winget upgrade`.
2. Redundant entry for old version still exists in the `winget list`` output.

### Actual behavior

Duplicate entries are being created.

### Expected behavior

Old version entry should be removed on successful upgrade to new version.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22622.601
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

<img width="960" alt="image" src="https://user-images.githubusercontent.com/39222830/194345401-5fe7e6dd-9181-4972-b5fb-3b34be0e8ffc.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/39222830/194345656-8f67cb73-3831-428d-9129-08360e815d46.png">

**Comment by ptanmay143** [comment]
@Trenly Hey, thanks for fixing the issue. What next steps should I perform to remove the extra entry or should a simple upgrade next time when a new version releases will fix it?

**Comment by Trenly** [comment]
> @Trenly Hey, thanks for fixing the issue. What next steps should I perform to remove the extra entry or should a simple upgrade next time when a new version releases will fix it?

Manually uninstall through appwiz.cpl

**Comment by ptanmay143** [comment]
> Manually uninstall through appwiz.cpl
The issue is that the appwiz.cpl entry for the recent and the previous version both try to uninstall the recent version.

**Comment by Trenly** [comment]
> > Manually uninstall through appwiz.cpl
> 
> The issue is that the appwiz.cpl entry for the recent and the previous version both try to uninstall the recent version.

Unfortunately that can only be fixed by finding and removing the registry entry using regedit, or by uninstalling "both" versions through appwiz (uninstall one, try to uninstall the other and say yes when it says it may have already been removed) and re-installing
