### ISSUE TITLE
[Package Request]: Grid9 2022-015

### ISSUE THREAD

**Issue by MrEnder0** [microsoft/winget-pkgs#82704]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: MrEnder0
Publisher Url: https://github.com/MrEnder0
Package Name: Grid9
Description: A esoteric interpreted language made in Nim based on a 3x3 grid of zeros and ones.
Package Version: 2022-015
Installer URL: https://github.com/MrEnder0/Grid9/releases/download/2022-015/Grid9.Setup.2022-015.exe

Current Package Identifier (for new versions):

**Comment by TheBossMagnus** [comment]
![image](https://user-images.githubusercontent.com/92474350/194756335-d6ee5d2c-4f48-4960-a8fb-3a4b1dfc8e62.png)
Not sure, but this smart screen warning doesn't allow the app to pass the pipeline...

**Comment by MrEnder0** [comment]
What is the best way to fix this?

**Comment by MrEnder0** [comment]
Could I submitted is somewhere for it to get reviewed.

**Comment by TheBossMagnus** [comment]
Clicking on show more you can report it as safe. Idk when and if they will unblock it.....

**Comment by MrEnder0** [comment]
Thanks
