### ISSUE TITLE
[Package Request]: NextDNS new version available.

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#82792]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Romain Cointepas & Olivier Poitrey
Publisher Url: https://nextdns.io
Package Name:
Description: NextDNS protects you from all kinds of security threats, blocks ads and trackers on websites and in apps and provides a safe and supervised Internet for kids — on all devices and on all networks.
Package Version: v3.0.4
Installer URL: https://github.com/nextdns/windows/releases/download/v3.0.4/NextDNSSetup-3.0.4.exe

Current Package Identifier (for new versions):

**Comment by mdanish-kh** [comment]
@Trenly - Should this be added under `NextDNS.NextDNS.Prerelease`? I believe the current manifest is also a pre-release version that could be moved under this new PackageIdentifier. The stable version is `2.2.1` available here on their official website. https://storage.googleapis.com/nextdns_windows/NextDNSSetup-2.2.1.exe

**Comment by Trenly** [comment]
> @Trenly - Should this be added under `NextDNS.NextDNS.Prerelease`? I believe the current manifest is also a pre-release version that could be moved under this new PackageIdentifier. The stable version is `2.2.1` available here on their official website. https://storage.googleapis.com/nextdns_windows/NextDNSSetup-2.2.1.exe

Yes
