### ISSUE TITLE
[Package Issue]: HermannSchinagl.LinkShellExtension

### ISSUE THREAD

**Issue by Cyberavater** [microsoft/winget-pkgs#82864]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Trying to install "HermannSchinagl.LinkShellExtension" throws

"vcruntime140.dll was not found"

### Steps to reproduce

Not required.

### Actual behavior

Not required.

### Expected behavior

Try to install the required dependency if it's not already fulfilled.

### Environment

```shell
Not required.
```

**Comment by ItzLevvie** [comment]
When dependency is not installed:
![image](https://user-images.githubusercontent.com/11600822/194728675-f09a8190-fba8-4db4-81ef-1d79477fd866.png)

When dependency is installed:
![image](https://user-images.githubusercontent.com/11600822/194728685-4f63ab99-971f-482f-8781-9d2c99400647.png)

`settings.json` file:
![image](https://user-images.githubusercontent.com/11600822/194728699-db706744-9138-4ed3-a60c-f8fe3deea7a9.png)

**Comment by Trenly** [comment]
See https://github.com/microsoft/winget-pkgs/pull/49982#issuecomment-1235709698
