### ISSUE TITLE
[YamlCreate.ps1] NestedInstallerType does not accept any value

### ISSUE THREAD

**Issue by mirror-kt** [microsoft/winget-pkgs#82898]
I was trying to create a package for [nektos/act](https://github.com/nektos/act), but NestedInstallerType does not accept any value.

Is Options empty the expected behavior?

<img width="497" alt="image" src="https://user-images.githubusercontent.com/43880251/194746969-d4584430-966e-4940-aefe-b746484e932f.png">

I'm using the HEAD b177986e1f0dbd0f0ce0dd1fd0455b6c6a18ded4 .

**Comment by Trenly** [comment]
I see the issue;

Zip is not a supported installer type in the 1.2 Schema. This is caused by microsoft/winget-cli#2532
