### ISSUE TITLE
[Package Request]: ShowWhatProcessLocksFile

### ISSUE THREAD

**Issue by Cyberavater** [microsoft/winget-pkgs#82926]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: PolarGoose
Publisher Url: https://github.com/PolarGoose/ShowWhatProcessLocksFile
Package Name: ShowWhatProcessLocksFile
Description: An utility to discover what processes lock a specific file or folder.
Package Version: 3.0
Installer URL: https://github.com/PolarGoose/ShowWhatProcessLocksFile/releases/tag/v3.0

Current Package Identifier (for new versions): 3.0

**Comment by vedantmgoyal2009** [comment]
> ### Package Requested
> * [ ]  I would like someone else to build the manifest.
> * [ ]  I would like help so I can submit the manifest.
> * [ ]  I have performed a search and couldn't find this package.
> * [x]  I have checked that the installer for this package is not contained in a .zip file
> * [ ]  I think there is a new version available and I have provided the URL.

The package is contained in a .zip file, and you've specifically tick merked the opposite of that.

BTW, zip support will be out in next few months, so you'll have to wait to get the package added to the repo.

**Comment by Cyberavater** [comment]
> > ### Package Requested
> > 
> > * [ ]   I would like someone else to build the manifest.
> > * [ ]   I would like help so I can submit the manifest.
> > * [ ]   I have performed a search and couldn't find this package.
> > * [x]   I have checked that the installer for this package is not contained in a .zip file
> > * [ ]   I think there is a new version available and I have provided the URL.
> 
> The package is contained in a .zip file, and you've specifically tick merked the opposite of that.
> 
> BTW, zip support will be out in next few months, so you'll have to wait to get the package added to the repo.

Unzip. you'll get msi.

**Comment by vedantmgoyal2009** [comment]
Currently, winget can't do that.
