### ISSUE TITLE
[Package Request]: TranslucentTB

### ISSUE THREAD

**Issue by Hellements** [microsoft/winget-pkgs#83037]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:
Publisher Url: https://github.com/TranslucentTB/TranslucentTB
Package Name:
Description: A lightweight utility that makes the Windows taskbar translucent/transparent. 
Package Version: 2021.5
Installer URL: https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.5/bundle.msixbundle or https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.5/TranslucentTB.appinstaller

Current Package Identifier (for new versions):

**Comment by KaranKad** [comment]
See https://github.com/microsoft/winget-pkgs/pull/29790#issuecomment-1029508996

**Comment by KaranKad** [comment]
You can install TranslucentTB using winget via Microsoft Store by running `winget install translucenttb` or `winget install 9PF4KZ2VN4W9` to be more precise.

**Comment by ItzLevvie** [comment]
Close with reason: See above;
