### ISSUE TITLE
[Package Request]: FrostWireLLC.FrostWire

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#83137]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: FrostWire LLC
Publisher Url: https://www.frostwire.com/
Package Name: FrostWire
Description: An easy to use Cloud Downloader, BitTorrent Client and Media Player. Search, Download, Play, Share 
Package Version: 6.9.9
Installer URL: https://github.com/frostwire/frostwire/releases and https://sourceforge.net/projects/frostwire/postdownload

@ptanmay143 tried to add an earlier version, but it failed because of virus detection: https://github.com/microsoft/winget-pkgs/pull/14072#issuecomment-850690367

I believe it won't fail like last time, because VirusTotal result is almost clean for the latest version: https://www.virustotal.com/gui/file/cf828748c541b254dee1812932197272fa8cec9a0742e9d92d2a9eed0998db10?nocache=1

**Comment by ptanmay143** [comment]
@denelon This issue can now be closed as resolved.

**Comment by ppvnf** [comment]
Thanks!
