### ISSUE TITLE
[Package Request]: DelugeTeam.Deluge (outdated)

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#83138]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: DelugeTeam
Publisher Url: https://deluge-torrent.org/
Package Name: Deluge
Description: Deluge is a lightweight, Free Software, cross-platform BitTorrent client.
Package Version: 2.1.1 
Installer URL: https://ftp.osuosl.org/pub/deluge/windows/?C=M;O=D

Current Package Identifier (for new versions): 1.3.15

DelugeBeta also seems outdated, but I don't know where to find the download link for it

**EDIT:** VirustTotal result is totally clear: https://www.virustotal.com/gui/file/183f401f088cbb973633dbeeb16ded1326b7aa567acfc9de32855d5be14653ae/detection/f-183f401f088cbb973633dbeeb16ded1326b7aa567acfc9de32855d5be14653ae-1665438716

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-pkgs/pull/69016#issuecomment-1225628521 URL blocked by Microsoft Defender SmartScreen. I'll create a draft PR to check whether it has been unblocked now.

**Comment by ppvnf** [comment]
@mdanish-kh, do you think using https://www.majorgeeks.com/files/details/deluge.html would work?

**Comment by ppvnf** [comment]
@mdanish-kh Would it be possible to use a mirror?

For example:
- https://www.softpedia.com/get/Internet/File-Sharing/Deluge.shtml#download
- https://www.filecroco.com/download-deluge/download/

**Comment by mdanish-kh** [comment]
The download URLs need to be directly from ISV's server https://github.com/microsoft/winget-pkgs/pull/16368#issuecomment-857281310. As the official link is available here, I don't think we can go for an external mirror.

**Comment by SpecterShell** [comment]
The validation pipeline scans files by using Windows Defender, which likes to mark BitTorrent softwares such as qBittorrent and BitComet as PUA (Potentially unwanted application). One way to avoid this issue is to submit new version as early as possible before Defender get realized.

**Comment by ppvnf** [comment]
> The validation pipeline scans files by using Windows Defender, which likes to mark BitTorrent softwares such as qBittorrent and BitComet as PUA (Potentially unwanted application). One way to avoid this issue is to submit new version as early as possible before Defender get realized.

In this case I believe the problem isn't the file ([VirusTotal](https://www.virustotal.com/gui/file/183f401f088cbb973633dbeeb16ded1326b7aa567acfc9de32855d5be14653ae/detection) is totally clear), but the fact that the URL is from a FTP server: https://github.com/microsoft/winget-pkgs/pull/69016#issuecomment-1225628521

**Comment by SpecterShell** [comment]
Yeah Defender marks their URLs as PUA as well.

**Comment by Trenly** [comment]
@MSFTbot Blocking-Issue

**Comment by ppvnf** [comment]
this was fixed. beta version appears out of date tho
