### ISSUE TITLE
[Package Request]: Box Drive

### ISSUE THREAD

**Issue by entreprenr** [microsoft/winget-pkgs#83175]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Box.com
Publisher Url: https://www.box.com/resources/downloads
Package Name: Box Drive
Description: Local sync with Box Drive (similar to Dropbox or Google Drive)
Package Version: 14.8
Installer URL: https://e3.boxcdn.net/box-installers/desktop/releases/win/Box-x64.msi

Current Package Identifier (for new versions): Doesn't yet exist

**Comment by mdanish-kh** [comment]
Already available in WinGet 
- https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/Box/Box/2.27.242

You can install it through `winget install Box.Box`
