### ISSUE TITLE
[Package Request]: Service Bus Explorer

### ISSUE THREAD

**Issue by SeanFeldman** [microsoft/winget-pkgs#83229]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: https://github.com/paolosalvatori/ServiceBusExplorer
Package Name: Service Bus Explorer
Description: Service Bus Explorer
Package Version: 5.0.14
Installer URL: n/a (https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest)

Current Package Identifier (for new versions):

**Comment by SeanFeldman** [comment]
Based on https://github.com/microsoft/winget-cli/issues/140, it should be possible to use portable zip-packaged deployment.
I'm looking for information on how to build and submit a zip-based manifest.

**Comment by mdanish-kh** [comment]
> Based on [microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140), it should be possible to use portable zip-packaged deployment. I'm looking for information on how to build and submit a zip-based manifest.

Zip installers are still an experimental feature in WinGet. https://github.com/microsoft/winget-pkgs/issues/80892#issuecomment-1260057099.

**Comment by Trenly** [comment]
@msftbot .zip

**Comment by Trenly** [comment]
@MSFTbot .zip
