### ISSUE TITLE
[Package Issue]: BlueStack.BlueStacks

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#83317]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer failed with exit code: 4294967254

### Steps to reproduce

winget upgrade

### Actual behavior

failed with exit code 

### Expected behavior

upgrade bluestacks with winget 

### Environment

```shell
winget --info
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.521
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/54496743/195346576-48912333-823b-48e3-8b78-3cbc4f73a4d6.png)

**Comment by khewweifeng** [comment]
Name         Id                   Version    Available    Source
----------------------------------------------------------------
BlueStacks 5 BlueStack.BlueStacks 5.9.0.1062 5.9.300.1014 winget
1 upgrades available.

(1/1) Found BlueStacks [BlueStack.BlueStacks] Version 5.9.300.1014
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 4294967254

**Comment by TheDude53** [comment]
It installed just fine in my tests. Would you mind uploading the BlueStacks installer log? It should be located in `C:\ProgramData\BlueStacks_nxt\Logs` and have the file name `Installer_5.9.300.1014.log`.

**Comment by TheDude53** [comment]
Glad to hear you got it working! Upon an initial review of the log, I didn't see any reason for it to fail. Regardless, I think it would be safe to close this issue now as the issue has been resolved. Cheers!

**Comment by twerner** [comment]
I had this same issue. Running the official .exe gave me the error FAILED_TO_CREATE_VMCONFIG. I followed the instructions [from this Reddit post](https://www.reddit.com/r/BlueStacks/comments/wre955/problem_bluestacks_failed_to_create_vmconfig/), deleted the Nouget 32-bit instance, and the winget upgrade ran perfectly after.
