### ISSUE TITLE
[Package Request]: cloc

### ISSUE THREAD

**Issue by jnm2** [microsoft/winget-pkgs#83318]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: AlDanial (Albert Danial)
Publisher Url: https://github.com/AlDanial
Package Name: cloc (Count Lines of Code)
Description: cloc counts blank lines, comment lines, and physical lines of source code in many programming languages.
Package Version: 1.94
Installer URL: https://github.com/AlDanial/cloc/releases/download/v1.94/cloc-1.94.exe (only a portable app is built)

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/pull/77921
