### ISSUE TITLE
[Package Request]: MediaArea.MediaInfo (CLI)

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#83391]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Current packages is 21.09 for CLI. Version 22.09 is available (zip only).
Download page: https://mediaarea.net/en/MediaInfo/Download/Windows

**Comment by mdanish-kh** [comment]
GUI added here https://github.com/microsoft/winget-pkgs/pull/83395

CLI is contained in a .zip package.

**Comment by ppvnf** [comment]
@denelon Could you please add the ZIP label?

**Comment by ppvnf** [comment]
MediaArea.MediaInfo is up to date
