### ISSUE TITLE
[Package Issue]: PolyMC.PolyMC

### ISSUE THREAD

**Issue by FayneAldan** [microsoft/winget-pkgs#84685]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Hello. The lead developer of `PolyMC.PolyMC` has gone rogue and the application is no longer considered safe, including the current version, as it downloads executable JAR files from a now compromised server. I am requesting that the package be removed from WinGet. Thanks.

### Steps to reproduce

N/a

### Actual behavior

N/a

### Expected behavior

N/a

### Environment

```shell
N/a
```

**Comment by RokeJulianLockhart** [comment]
https://github.com/microsoft/winget-pkgs/issues/118715#issuecomment-1825980305
