### ISSUE TITLE
[Package Request]: IBM Semeru Runtime 18

### ISSUE THREAD

**Issue by anyuzu99** [microsoft/winget-pkgs#84766]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: IBM
Publisher Url: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/
Package Name: IBM Semeru Runtime 18
Description:
Package Version: 18.0.2_9
Installer URL: https://github.com/ibmruntimes/semeru18-binaries/releases/download/jdk-18.0.2%2B9_openj9-0.33.1/ibm-semeru-open-jdk_x64_windows_18.0.2_9_openj9-0.33.1.msi

Current Package Identifier (for new versions):

**Comment by TheBossMagnus** [comment]
I think 2 packages are needed(JRE/JDK).
And maybe also uploading other Java 17-16-X as older versions could be useful for someone...?

**Comment by TheBossMagnus** [comment]
#85176 #85174

**Comment by Trenly** [comment]
Close with reason: Package added to repo;
