### ISSUE TITLE
[Package Request] Hugo

### ISSUE THREAD

**Issue by wikicrafter** [microsoft/winget-pkgs#8504]
I proposed for windows  would be great if it could to install hugo through winget

**Comment by yigitemres** [comment]
If you talking about this [HUGO](https://github.com/gohugoio/hugo) currently it's not possible due to lack of zip support. microsoft/winget-cli/issues/140

**Comment by Robin-Wils** [comment]
I think zip support was added in 2022 September. Can this package be checked again?
https://github.com/microsoft/winget-cli/issues/140

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/issues/87300
