### ISSUE TITLE
Specify hash calculations process in contributing section

### ISSUE THREAD

**Issue by G0rocks** [microsoft/winget-pkgs#8546]
# Description of the new feature/enhancement
Specify how a person, that wants to contribute by adding a manifest, can find the SHA256 hash needed for the manifest. Add this specification to the front page of this repository (here: https://github.com/microsoft/winget-pkgs)

This means less obstacles for newcomers to overcome and less obstacles means more manifests faster which leads to a better package manager. I know I had to google for like 10 minutes to figure this thing out, would have been way nicer if the instructions would have been on the front page under "Contribute"
# Proposed technical implementation details (optional)
Add how to calculate the SHA256 hash from the installer declared in the YAML manifest file to the front page of this repo somewhere under "Contributing"

Add how to calculate the SHA256 hash from the installer declared in the YAML manifest file to the front page of this repo somewhere under "Contributing"

**Comment by denelon** [comment]
Just in case someone else looks at this issue, it's the `winget hash` command.
`winget hash -?` provides some details.

**Comment by G0rocks** [comment]
Thanks, I didn't know :)

**Comment by G0rocks** [comment]
Using the wingetcreate tool you don't need this, though it should still be documented. Close issue???

**Comment by denelon** [comment]
I'm going to keep this open. We still have the scenario with multiple installers (not currently supported by wingetcreate). Lots of documentation work over the next couple of weeks...

**Comment by vedantmgoyal2009** [comment]
Well, the YamlCreate script is now much intelligent than before. You can try that also.

**Comment by denelon** [comment]
Both of these solutions have been working for quite some time. I'm going to go ahead and close this issue.
