### ISSUE TITLE
Create step by step guide on how to contribute/how to add manifest

### ISSUE THREAD

**Issue by G0rocks** [microsoft/winget-pkgs#8554]
The idea is to put a step by step guide on the frontpage of the repo for new contributors (like me) that really want to add some package to this repo but don't know how. Creating this issue since #8543 is irrelevant but a guide like this is a better idea than the one that issue suggests.
# Description of the new feature/enhancement

For me creating my first pull request (https://github.com/microsoft/winget-pkgs/pull/8521) it has taken a while for me to figure out how to do this stuff (and I honestly still haven't, PR hasn't merged yet).
# Proposed technical implementation details (optional)
If there was a clear and concise step by step guide to follow, that would speed up things for new contributors, make things easier for them and ultimately speed up the input of new packages to this repo.

A written step-by-step guide is posted on the frontpage of this repository  containing clear and concise steps on how to add a manifest file with all the information (how to know the architecture, how to calculate the hash etc.).

**Comment by denelon** [comment]
@G0rocks we're also about to make some major changes to the manifest structure and syntax. https://github.com/microsoft/winget-cli/discussions/646

I agree we need to enhance the instructions quite a bit. We're also building a new CLI utility that will help author manifests. It will try to parse installers to get as much of the correct meta-data as possible. An author can also point to an existing package to leverage the current meta-data when submitting a new version. If the user provides authentication, the tool will even create the PR with the manifest that was generated/modified. The tool will also be open-source.

**Comment by G0rocks** [comment]
Ok that's cool, so if there is a new method of doing things arriving soon, it's probably not worth it to make a poper step-by-step guide just yet but if it is arriving later (like in more than a month I suppose) I still think it would be totally appropriate to make the guide. Later an issue to update the guide for the new method of doing things can be added.

And that tool sounds like a great step in the right direction for maintaining the package collection. Later I hope it will be able to update itself mostly autonomously. Somebody was talking about that last year in some issue here and it seemed really cool.

**Comment by denelon** [comment]
We've got a couple of automated processes to help keep packages up to date. If the binary changes at the URL we can calculate a new hash and submit the PR to update the manifest. If the URL is not working, we can delete the invalid manifest, and if it's the last one for a given package, we create a "Help-Wanted" issue for the community to help us fix it. We've been looking at automating packages in GitHub based on new releases, and packages with RSS feeds or other notification methods so we can start looking at automatically building new manifests.

**Comment by G0rocks** [comment]
Okay, that's awesome so currently keeping packages up do date is completely automated so long as the URL works? That's neat.

However I've no idea how long it's going to be until this new way of adding manifests arrives, do you know how for how much longer approximately contributors need to keep using the current method?

**Comment by denelon** [comment]
We're aiming for the end of the month. This is likely to coincide with the new manifest schema and structure as well.

**Comment by denelon** [comment]
Absolutely! We're going to do a "Bug Bash" to try and break it before we release the initial preview. I'll make sure we take copious notes to be prepared for documentation in GitHub as well as https://docs.microsoft.com/

**Comment by denelon** [comment]
We've decided to make a few changes to the tool based on feedback from the current beta testers. The tool will generate a multi-file manifest. One of the challenges we're seeing currently is when a user is trying to do a rename which involves the PR touching files in 2 directories (1 for the add or move and 1 for the delete). We currently only support operations on a single directory. Our new ETA for the tool is May (as early as possible). I added a .md file to help with the new [v1.0  schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md).

**Comment by denelon** [comment]
Here is the link to the new [wingetcreate](https://github.com/microsoft/winget-create) tool designed to help build manifests. The PR is in progress so soon you will be able to `winget install wingetcreate`.

**Comment by G0rocks** [comment]
Awesome, that is very cool. I haven't tried it yet but if that works nicely, I suggest adding a line about that tool in the [readme](https://github.com/microsoft/winget-pkgs/blob/master/README.md).

Trying the wingetcreate tool with [this PR](https://github.com/microsoft/winget-pkgs/pull/14077)

**Comment by denelon** [comment]
I'm still working to update docs :) I'll do that next.

**Comment by denelon** [comment]
Added to Authoring a Manifest on the main readme.

**Comment by G0rocks** [comment]
Tried the wingetcreate tool, worked great, waaayyy simpler.
