### ISSUE TITLE
[Package Request]: Microsoft SQL Server 2019 Developer

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/winget-pkgs#85884]
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://support.microsoft.com/
Package Name: Microsoft.SQLServer.2019.Developer
Description: SQL Server 2019 Developer is a full-featured free edition, licensed for use as a development and test database in a non-production environment.
Homepage: https://www.microsoft.com/sql-server/sql-server-2019
Package Version: 15.0.2000.5
Release Notes Url: https://docs.microsoft.com/sql/sql-server/sql-server-2019-release-notes
Installer URL: https://download.microsoft.com/download/d/a/2/da259851-b941-459d-989c-54a18a5d44dd/SQL2019-SSEI-Dev.exe

**Comment by xtqqczze** [comment]
See #25931 for the discussion on proposed technical implementation.

**Comment by Yousha** [comment]
Resolved by #73906 ?

**Comment by Trenly** [comment]
Close with reason: Package has been added;
