### ISSUE TITLE
[Package Request]: Microsoft SQL Server 2019 Express

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/winget-pkgs#85885]
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://support.microsoft.com/
Package Name: Microsoft.SQLServer.2019.Express
Description: Microsoft SQL Server 2019 Express is a powerful and reliable free data management system that delivers a rich and reliable data store for lightweight Web Sites and desktop applications.
Homepage: https://www.microsoft.com/sql-server/sql-server-2019
Package Version: 15.0.2000.5
Release Notes Url: https://docs.microsoft.com/sql/sql-server/sql-server-2019-release-notes
Installer URL: https://download.microsoft.com/download/7/f/8/7f8a9c43-8c8a-4f7c-9f92-83c18d96b681/SQL2019-SSEI-Expr.exe

**Comment by kkbruce** [comment]
Closes #85885

**Comment by Yousha** [comment]
Resolved by  #58956 ?

**Comment by Trenly** [comment]
Close with reason: Package has been added;
