### ISSUE TITLE
Package Request: ffmpeg

### ISSUE THREAD

**Issue by reyqn** [microsoft/winget-pkgs#859]
# Description of the new feature/enhancement

ffmpeg is a very useful tool, it would be nice to be able to install it via winget.

# Proposed technical implementation details (optional)

ffmpeg does not however release official builds. The builds available [here](https://ffmpeg.zeranoe.com/builds/) seem to be endorsed on the ffmpeg website, but maybe that's a security issue?

**Comment by LightDestory** [comment]
Windows build of ffmpeg are provided as a .zip format but right now, using as reference [Manifest Spec](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md), winget don't support it. 
We must wait for further development :)

**Comment by masx200** [comment]
I support it!

**Comment by Restia666Ashdoll** [comment]
Hope they add all 4 versions (stable/git - static/shared).

**Comment by pcgeek86** [comment]
Here's the manifest from the Scoop package manager, which I currently use: https://github.com/rivy/scoop.bucket.scoop-main/blob/master/ffmpeg-shared.json

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by Wikistore** [comment]
but there is also alternative package managers like: chocolatey

choco install ffmpeg

**Comment by Wikistore** [comment]
> Windows build of ffmpeg are provided as a .zip format but right now, using as reference [Manifest Spec](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md), winget don't support it.
> We must wait for further development :)

but there is also alternative package managers like: chocolatey

choco install ffmpeg

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
https://forum.cockos.com/showpost.php?s=e8350c0f7481e5bed58a88f36e7c6abd&p=2338654&postcount=1#:~:text=ffmpeg.zeranoe.com%20will%20close%20on%20sep%2018%2C%202020%2C%20and%20all%20builds%20will%20be%20removed states that the quoted compilation of `ffmpeg` has been discontinued.

Consequently, I suggest that somebody assist remediation of "https://github.com/BtbN/FFmpeg-Builds/issues/135" to hopefully allow this proposition to succeed without relying upon "https://github.com/microsoft/winget-cli/issues/140" to ultimately generate an inferior installer.

**Comment by rlaphoenix** [comment]
For Windows, an alternative build source I've been using for a long time has been Gyan's builds, https://www.gyan.dev/ffmpeg/builds/

**Comment by sitiom** [comment]
> For Windows, an alternative build source I've been using for a long time has been Gyan's builds, [gyan.dev/ffmpeg/builds](https://www.gyan.dev/ffmpeg/builds/)

- https://github.com/microsoft/winget-pkgs/pull/87327
