### ISSUE TITLE
[Package Issue]: Microsoft.XNARedist update is not "recorded" by winget

### ISSUE THREAD

**Issue by lackovic** [microsoft/winget-pkgs#85901]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

When running `winget upgrade -h --all` winget reports the update is successfully installed.

When running `winget upgrade -h --all` again winget incorrectly detects the old version as installed and install the new version again.

### Steps to reproduce

```
> winget install -e --id Microsoft.XNARedist
> winget upgrade -h --all
> winget upgrade -h --all
```

### Actual behavior

The application is upgraded twice.

### Expected behavior

The application is upgraded only once and second attempt should not find any udpate.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

```
> winget upgrade -h --all
Name                                                      Id                        Version          Available    Source
------------------------------------------------------------------------------------------------------------------------
Microsoft XNA Framework Redistributable 3.1               Microsoft.XNARedist       3.1.10527.0      4.0.30901.0  winget

(1/1) Found Microsoft XNA Framework Redistributable Refresh [Microsoft.XNARedist] Version 4.0.30901.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/5/3/A/53A804C8-EC78-43CD-A0F0-2FB4D45603D3/xnafx40_redist.msi
  ██████████████████████████████  6.73 MB / 6.73 MB
Successfully verified installer hash
Starting package install...
Successfully installed

> winget list Microsoft.XNARedist
Name                                                Id                  Version     Source
-------------------------------------------------------------------------------------------
Microsoft XNA Framework Redistributable 4.0 Refresh Microsoft.XNARedist 4.0.30901.0 winget
```

**Comment by denelon** [comment]
If you run `winget list` are there two different versions installed "side-by-side"?

**Comment by lackovic** [comment]
> If you run `winget list` are there two different versions installed "side-by-side"?

Yes:
```
> winget list | findstr WindowsSDK
Windows Software Development Kit - Win??? Microsoft.WindowsSDK                     < 10.0.22000.832      10.0.226??? winget
Windows Software Development Kit - Win??? Microsoft.WindowsSDK                     10.0.22621.1                    winget
```

**Comment by denelon** [comment]
OK, that makes sense. We have work in progress to "detect" if the current version is already installed so we don't show a "false" need to upgrade. The current logic is to iterate over everything that's installed to show available upgrades. When things get installed "side-by-side", the client doesn't yet know how to reason about that situation correctly.

That will help in this situation. the Windows SDK, ADK, DDK, etc. have some interesting caveats that we're working on separately

**Comment by lackovic** [comment]
@denelon thanks for the explanation! Is there anything I can do to solve my situation? Can/should I uninstall one of the two versions? Which one and how?
