### ISSUE TITLE
[Package Request]: Apache Tomcat 10

### ISSUE THREAD

**Issue by entreprenr** [microsoft/winget-pkgs#85904]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Apache Tomcat
Publisher Url: https://tomcat.apache.org
Package Name: Apache Tomcat 10
Description: Java Servlet Engine
Package Version: 10.0.27
Installer URL: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.exe

Note:
"winget search tomcat" has no results.
Tomcat versions 9 and 10 would have to exist side by side. I should be able to install Tomcat 9 with "winget install tomcat9" and Tomcat 10 with "winget install tomcat10" or similar.

**Comment by SpecterShell** [comment]
The installer requires JRE during installation, but dependencies features (and "or" feature for JREs) has not yet been implemented in WinGet.
![image](https://user-images.githubusercontent.com/56779163/197222407-41373b3e-aaac-4a18-a1b1-97fc5dbb1dd6.png)
