### ISSUE TITLE
Error installing `yt-dlp.yt-dlp`

### ISSUE THREAD

**Issue by congqiao** [microsoft/winget-pkgs#85997]
### Brief description of your issue

I can't install `yt-dlp.yt-dlp`.

### Steps to reproduce

`winget install -e --id "yt-dlp.yt-dlp"`

### Expected behavior

`yt-dlp.yt-dlp` is installed.

### Actual behavior

> An unexpected error occurred while executing the command:
0x80070057 : The parameter is incorrect.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by SpecterShell** [comment]
It should be fixed now. Can you try again?

**Comment by congqiao** [comment]
> It should be fixed now. Can you try again?

I just tried and got the same error message. No other details.

**Comment by Trenly** [comment]
I just tried this in my sandbox session and it seemed to install just fine using the latest version of winget.
@congqiao - Are you still experiencing this issue?
