### ISSUE TITLE
[Package Issue]: Microsoft.DotNet.SDK.6

### ISSUE THREAD

**Issue by bgoewert** [microsoft/winget-pkgs#86165]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

Upgrading Microsoft.DotNet.SDK.6 does not remove old version. Also tried removing both versions and reinstalling, but I had the same and other interesting results.

### Steps to reproduce

1. winget install Microsoft.DotNet.SDK.6 -v 6.0.305
2. winget upgrade --id Microsoft.DotNet.SDK.6
3. winget list Microsoft.DotNet.SDK.6

### Actual behavior

Before reinstalling.
```
PS C:\Users\bgoewert> winget upgrade
Name                                             Id                             Version   Available   Source
------------------------------------------------------------------------------------------------------------
Microsoft .NET SDK 6.0.305 (x64)                 Microsoft.DotNet.SDK.6         6.0.305   6.0.402     winget
Eclipse Temurin JRE with Hotspot 11.0.16+8 (x64) EclipseAdoptium.Temurin.11.JRE 11.0.16.8 11.0.16.101 winget
2 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.

PS C:\Users\bgoewert> winget upgrade --id Microsoft.DotNet.SDK.6
No applicable update found.
```

Reinstall
```
PS C:\Users\bgoewert> winget install Microsoft.DotNet.SDK.6 -v 6.0.305
Found Microsoft .NET SDK 6.0 [Microsoft.DotNet.SDK.6] Version 6.0.305
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.305/dotnet-sdk-6.0.305-win-x64.exe
  ██████████████████████████████   195 MB /  195 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\bgoewert> winget list Microsoft.DotNet.SDK
Name                                  Id                       Version Available Source
---------------------------------------------------------------------------------------
Microsoft .NET SDK 6.0.305 (x64)      Microsoft.DotNet.SDK.6   6.0.305 6.0.402   winget
Microsoft .NET Core SDK 3.1.424 (x64) Microsoft.DotNet.SDK.3_1 3.1.424           winget

PS C:\Users\bgoewert> winget install Microsoft.DotNet.SDK.6 -v 6.0.402
Found Microsoft .NET SDK 6.0 [Microsoft.DotNet.SDK.6] Version 6.0.402
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.402/dotnet-sdk-6.0.402-win-x64.exe
  ██████████████████████████████   197 MB /  197 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\bgoewert> winget list Microsoft.DotNet.SDK
Name                                  Id                       Version Source
------------------------------------------------------------------------------
Microsoft .NET Core SDK 3.1.424 (x64) Microsoft.DotNet.SDK.3_1 3.1.424 winget

PS C:\Users\bgoewert> winget list Microsoft.DotNet.SDK.6
No installed package found matching input criteria.

PS C:\Users\bgoewert> winget list Microsoft.DotNet
Name                                                   Id                              Version Source
------------------------------------------------------------------------------------------------------
Microsoft .NET Core Runtime - 3.1.30 (x64)             Microsoft.DotNet.Runtime.3_1    3.1.30  winget
Microsoft .NET Core SDK 3.1.424 (x64)                  Microsoft.DotNet.SDK.3_1        3.1.424 winget
Microsoft ASP.NET Core 6.0.10 - Shared Framework (x86) Microsoft.DotNet.AspNetCore.6   6.0.10  winget
Microsoft ASP.NET Core 3.1.30 - Shared Framework (x86) Microsoft.DotNet.AspNetCore.3_1 3.1.30  winget

PS C:\Users\bgoewert> winget list Microsoft
Name                                      Id                                        Version            Available Source
-----------------------------------------------------------------------------------------------------------------------
_(Removed everything except for DotNet.SDK.6 because this list is too long)_
Microsoft .NET SDK 6.0.305 (x64)          Microsoft.DotNet.SDK.6                    6.0.305            6.0.402   winget
Microsoft .NET SDK 6.0.402 (x64)          Microsoft.DotNet.SDK.6                    6.0.402                      winget

PS C:\Users\bgoewert> winget upgrade --id Microsoft.DotNet.SDK.6
No installed package found matching input criteria.

PS C:\Users\bgoewert> winget upgrade
Name                                             Id                             Version   Available   Source
------------------------------------------------------------------------------------------------------------
Microsoft .NET SDK 6.0.305 (x64)                 Microsoft.DotNet.SDK.6         6.0.305   6.0.402     winget
Eclipse Temurin JRE with Hotspot 11.0.16+8 (x64) EclipseAdoptium.Temurin.11.JRE 11.0.16.8 11.0.16.101 winget
2 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.

PS C:\Users\bgoewert> winget uninstall Microsoft.DotNet.SDK.6
No installed package found matching input criteria.

PS C:\Users\bgoewert> winget uninstall Microsoft.DotNet.SDK.6 -v 6.0.305
No installed package found matching input criteria.

PS C:\Users\bgoewert> winget uninstall Microsoft.DotNet.SDK.6 -v 6.0.402
No installed package found matching input criteria.
```

### Expected behavior

1. winget upgrade --id Microsoft.DotNet.SDK.6
2. winget removes the old version
3. winget installs the new version

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
```

### Screenshots and Logs

Screenshot of programs showing multiple versions
![ApplicationFrameHost_qETJXiFrO2](https://user-images.githubusercontent.com/15313658/197563981-cb01ba3f-3a22-4441-91bc-215aecaccc4d.png)

**Comment by chrsmrtn-** [comment]
I too am experiencing this issue. This issue is also impacting these packages as well:

![image](https://user-images.githubusercontent.com/5657979/210652324-4a57809a-7f87-4e94-af9b-b7771eb11c60.png)

**Comment by gonzalmic** [comment]
Replying here so i don't create a new issue:

I'm seeing the same issue here

Microsoft ASP.NET Core 3.1.32 - Shared Framework (x86)
Microsoft ASP.NET Core 5.0.17 - Shared Framework (x86)
Microsoft ASP.NET Core 6.0.16  - Shared Framework (x86) 

are all seen as the same ID

Microsoft.DotNet.AspNetCore.6

Is the fix to uninstall Versions 3.1.32, 5.0.17
I attempted updating by name
Microsoft ASP.NET Core 6.0.16  - Shared Framework (x86)
But i see that it attempted to update the x64 installer


`05/24/2023 14:13:15 - Received following arguments for winget; update --accept-source-agreements --name="Microsoft ASP.NET Core 5.0.17 - Shared Framework (x86)" --silent --disable-interactivity
   -\ 
   -\ 
Found Microsoft ASP.NET Core Runtime 6.0 [Microsoft.DotNet.AspNetCore.6] Version 6.0.16
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.16/aspnetcore-runtime-6.0.16-win-x64.exe
   -\|/-\|/-\ 

  â–ˆâ–ˆâ–ˆâ–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’â–’  1024 KB / 8.55 MB
  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  8.55 MB / 8.55 MB
Successfully verified installer hash
Starting package install...
   -\|/-\ 
Successfully installed
   -\ 
   -\ 
Found Microsoft ASP.NET Core Runtime 6.0 [Microsoft.DotNet.AspNetCore.6] Version 6.0.16
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.16/aspnetcore-runtime-6.0.16-win-x64.exe
   -\|/ 

  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  8.55 MB / 8.55 MB
Successfully verified installer hash
Starting package install...
   -\|/ 
Successfully installed`

**Comment by oturpe** [comment]
Also affects `Microsoft.DotNet.SDK.7`.
I have both 7.0.302 and 7.0.203 installed.
`winget upgrade --all` wants to download and run the 7.0.302 installed everytime.
Curiously, `winget upgrade Microsoft.DotNet.SDK.7` does not find anything to upgrade.

Both are installed:
```
> winget list | rg DotNet.SDK.7
Microsoft .NET SDK 7.0.302 (x64)         Microsoft.DotNet.SDK.7                    7.0.302                       winget
Microsoft .NET SDK 7.0.203 (x64)         Microsoft.DotNet.SDK.7                    7.0.203             7.0.302   winget
```

Winget still wants to run the upgrade:
```
> winget upgrade
Name                             Id                     Version Available Source
--------------------------------------------------------------------------------
Microsoft .NET SDK 7.0.203 (x64) Microsoft.DotNet.SDK.7 7.0.203 7.0.302   winget
1 upgrades available.
```

Targeted upgrade does not find anything to do:
```
> winget upgrade Microsoft.DotNet.SDK.7
No applicable upgrade found.
```

Upgrading everything downloads and runs the installer again:
```
> winget upgrade --all
Name                             Id                     Version Available Source
--------------------------------------------------------------------------------
Microsoft .NET SDK 7.0.203 (x64) Microsoft.DotNet.SDK.7 7.0.203 7.0.302   winget
1 upgrades available.

(1/1) Found Microsoft .NET SDK 7.0 [Microsoft.DotNet.SDK.7] Version 7.0.302
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.302/dotnet-sdk-7.0.302-win-x64.exe
  ██████████████████████████████   207 MB /  207 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by alsaghir** [comment]
Same here, any update on this one ?

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest pre-release](https://github.com/microsoft/winget-cli/releases) of the CLI and see if your problem still persists. 

There is a new [experimental feature](https://github.com/microsoft/winget-cli/discussions/4281) for `Side-By-Side` installs which may help with this case. As there are many similar issues for side by side open on the CLI repo, I'll be closing this one to keep things clean.

###### Close with reason: Tracked at winget-cli; Experimental feature available

**Comment by peteraritchie** [comment]
Still happening for me with winget cli version v1.8.1911

**Comment by brmcmill** [comment]
+1 There are issues with trying to install Microsoft.DotNet.SDK.6 with winget.

![image](https://github.com/user-attachments/assets/ccc98d69-9a14-4c51-9d21-8c150fc0d164)
