### ISSUE TITLE
Multiple manifests for Git LFS

### ISSUE THREAD

**Issue by centreboard** [microsoft/winget-pkgs#862]
Git LFS appears under both Git and GitHub.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/GitHub/GitLFS/2.11.0.yaml
https://github.com/microsoft/winget-pkgs/blob/master/manifests/Git/GitLFS/2.11.0.yaml

Both point at the same download link, just with slightly different metadata.

Is it intended that a package should just be listed once in this repository?

**Comment by jamierocks** [comment]
Git LFS isn't part of the Git project, I'll open a pr removing `Git.GitLFS` shortly.

As for `GitHub.GitLFS`, I'm unsure whether it should be moved to `GitLFS.GitLFS` or stay.

> Copyright (c) 2014-2020 GitHub, Inc. and Git LFS contributors

**Comment by jamierocks** [comment]
This was resolved.
