### ISSUE TITLE
It is still pulling the old version when what do I need to do to fix that

### ISSUE THREAD

**Issue by Rotmaster** [microsoft/winget-pkgs#86316]
It is still pulling the old version when what do I need to do to fix that

_Originally posted by @Rotmaster in https://github.com/microsoft/winget-pkgs/issues/86170#issuecomment-1292134955_

**Comment by Trenly** [comment]
Caused by #86160

**Comment by Trenly** [comment]
Close with reason: See above for more detail;

**Comment by Rotmaster** [comment]
do i need to do anything?
