### ISSUE TITLE
[Package Request]: Xtreme Download Manager Beta

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#86557]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: subhra Das Gupta
Publisher Url: https://github.com/subhra74/xdm
Package Name: subhra74.XtremeDownloadManager.Beta
Description: Xtreme Download Manager (XDM) is a powerful tool to increase download speeds up to 500%, save streaming videos from YouTube, DailyMotion, Facebook, Vimeo, Google Video and 1000+ other websites, resume broken/dead downloads, schedule and convert downloads.
Package Version: [8.0.12-beta](https://github.com/subhra74/xdm-experimental-binaries/releases/tag/8.0.12-beta)
Installer URL:  [xdmsetup-8.0.12-x86.msi](https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.12-beta/xdmsetup-8.0.12-x86.msi)

**Comment by TheBossMagnus** [comment]
#86773
