### ISSUE TITLE
[Package Issue]: ryanSn.winMoji

### ISSUE THREAD

**Issue by DeusMaximus** [microsoft/winget-pkgs#86621]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Despite the pull request #86205 having been approved yesterday, the package ryanSn.winMoji cannot be found by the winget client. Attempted on two different machines, one running 1.4 preview on Windows 11, and another running 1.3.0 release on Windows 10.

### Steps to reproduce

winget install --id ryanSn.winMoji

or

winget search --id ryanSn.winMoji

### Actual behavior

No package found matching input criteria.

### Expected behavior

Finds and installs package.

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.755
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

-- 

Windows Package Manager v1.3.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2130
System Architecture: X64

Logs: %TEMP%\WinGet\defaultState

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![winMoji-missing](https://user-images.githubusercontent.com/10080364/198420619-10d0e9b2-5f07-4776-b2fd-d3ffd91f58b7.png)

**Comment by DeusMaximus** [comment]
wingetcreate was used to create the manifest, and the PR passed okay. It _looks_ right to me, but I'd appreciate someone pointing out where I screwed up.

**Comment by KaranKad** [comment]
It works for me
![image](https://user-images.githubusercontent.com/71691514/198557862-24af86f5-2b45-4276-a93b-a60b023ec444.png)

Try these commands
`winget source update`
or 
`winget source reset`

**Comment by Trenly** [comment]
* Caused by #86160

**Comment by Trenly** [comment]
Close with reason: CDN should now have the latest source;
