### ISSUE TITLE
Multiple versions of AdaptOpenJDK/OpenJDK should not have the same id.

### ISSUE THREAD

**Issue by zdevcs** [microsoft/winget-pkgs#8670]
Multiple versions of [`AdaptOpenJDK/OpenJDK`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/AdoptOpenJDK) should not have the same id.
When searching, you cannot directly get id values with version numbers like [`BellSoft/LibericaJDK`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/BellSoft).
```
PS C:\Users\zhait> winget search openjdk
名称                        ID                         版本      匹配                源
-------------------------------------------------------------------------------------------
Liberica JDK 8 Full         BellSoft.LibericaJDK8Full  8.0.282.8 Tag: OpenJDK        winget
Liberica JDK 8              BellSoft.LibericaJDK8      8.0.282.8 Tag: OpenJDK        winget
Liberica JDK 15 Full        BellSoft.LibericaJDK15Full 15.0.2.10 Tag: OpenJDK        winget
Liberica JDK 15             BellSoft.LibericaJDK15     15.0.2.10 Tag: OpenJDK        winget
Liberica JDK 14 Full        BellSoft.LibericaJDK14Full 14.0.2.13 Tag: OpenJDK        winget
Liberica JDK 14             BellSoft.LibericaJDK14     14.0.2.13 Tag: OpenJDK        winget
Liberica JDK 11 Full        BellSoft.LibericaJDK11Full 11.0.10.9 Tag: OpenJDK        winget
Liberica JDK 11             BellSoft.LibericaJDK11     11.0.10.9 Tag: OpenJDK        winget
AdoptOpenJDK 15.0.2+7 (x64) AdoptOpenJDK.OpenJDK       15.0.2.7  Tag: openjdk        winget
ojdkbuild 14.0.1-1 (x64)    ojdkbuild.ojdkbuild        14.0.1-1  Tag: openjdk source winget
```
This obviously does not make sense and additional commands need to be executed for this purpose.
```
PS C:\Users\zhait> winget show AdoptOpenJDK.OpenJDK --versions
已找到 AdoptOpenJDK 15.0.2+7 (x64) [AdoptOpenJDK.OpenJDK]
版本
---------
15.0.2.7
15.0.1.9
15.0.0.36
14.0.2
14.0.1
11.0.10
11.0.8
11.0.7
8.0.282.8
8.0.265
8.0.252
```

**Comment by zdevcs** [comment]
See https://github.com/microsoft/winget-pkgs/pull/8937
This PR cannot pass validation at this time; the issue is temporarily suspended.

**Comment by denelon** [comment]
@zdevcs, you can enable [PowerShell tab auto-complete](https://github.com/microsoft/winget-cli/blob/master/doc/Completion.md). That will save some keystrokes and make it easier to cycle through available versions.

If it still makes sense to "rename" the packages, you will need one PR per manifest, and you will need to make sure the directory structure conforms "/manifests/publisher/package/".
![AutoComplete](https://user-images.githubusercontent.com/61799811/111816008-8e144900-8899-11eb-91c7-ca17e48e528d.gif)

**Comment by yigitemres** [comment]
@denelon Can we get option/feature to print last x amount of versions of the app when searching?

```powershell
~
❯ winget search emacs
Name      Id        Match           Versions
----------------------------------------------------------
GNU Emacs GNU.Emacs Moniker: emacs  28.0.50, 27.1.91, 27.1

```

**Comment by denelon** [comment]
@yigitemres try `winget show GNU.Emacs --versions`

```
PS C:\Users\denelon> winget show GNU.Emacs --versions
Found GNU Emacs [GNU.Emacs]
Version
-------
28.0.50
27.1.91
27.1
PS C:\Users\denelon>
```

**Comment by yigitemres** [comment]
@denelon Thanks for the fast response. I know that we have `show` command. What I suggest is (if possible):

1) Ability modify result page according to user needs.
2) Ability to track specific installed app versions from cli. (instead of `winget list | Select-String $appname`)

I'm using Gentoo inside WSL for a good time. I'm probably heavily inspired from portage.😄

**Comment by denelon** [comment]
@yigitemres I'll have to think about what makes sense for the (x amount of versions). We're working on a REST API implementation, and we'd need to make sure the models we're proposing would support that behavior. I believe it will, I just need to check. Please create an issue for "Add an argument to show to display x number of versions". We'll have to think about UX concerns, but It's a fair ask 😊

As a part of the normal flow for the Windows Package Manager we will track what has been installed by the package manager. There are still plenty of nasty edge cases where packages update themselves, and users might install other versions via the web or some other method (sneaker net). I'm sure there will be plenty of power user scenarios that enables.

**Comment by jedieaston** [comment]
I fixed this in those PRs, and it falls in line with how I started doing builds of Coretto and Microsoft's OpenJDK preview.
