### ISSUE TITLE
[Package Issue]: VMware.HorizonClient Version 8.6.0.29364

### ISSUE THREAD

**Issue by ri-we** [microsoft/winget-pkgs#86716]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

VMware.HorizonClient Version 8.6.0.29364 fails to install with error: Installer failed with exit code: 2147942487

### Steps to reproduce

winget install -e --id VMware.HorizonClient

### Actual behavior

Installation is failing

### Expected behavior

Installer failed with exit code: 2147942487

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.755
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

### Screenshots and Logs

Found VMware Horizon Client [VMware.HorizonClient] Version 8.6.0.29364
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2147942487

Found VMware Horizon Client [VMware.HorizonClient] Version 8.4.1.26410
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download3.vmware.com/software/CART23FQ1_WIN_2111_1/VMware-Horizon-Client-2111.1-8.4.1-19480429.exe
  ██████████████████████████████   317 MB /  317 MB
Successfully verified installer hash
Starting package install...
Successfully installed

**Comment by auanasgheps** [comment]
I think is related to my pull request, where I'm trying to push the new version. #87334 

I get the same error.

The install commands have not changed and in fact the installation ends successfully if done manually with these commands.

**Comment by virtualex-itv** [comment]
Fix submitted under [PR#88817](https://github.com/microsoft/winget-pkgs/pull/88817#issuecomment-1317981724)...

**Comment by mdanish-kh** [comment]
@ri-we Can you please check again now?

**Comment by ri-we** [comment]
> @ri-we Can you please check again now?

It now successfully updates, thanks for fixing it.

**Comment by mdanish-kh** [comment]
> It now successfully updates, thanks for fixing it.

@virtualex-itv gets all the credit

**Comment by mdanish-kh** [comment]
Close with reason: Fixed in PR 88817;

**Comment by ri-we** [comment]
who is maintaining the VMware.HorizonClient package? Haven't seen an update for a while.

**Comment by virtualex-itv** [comment]
> who is maintaining the VMware.HorizonClient package? Haven't seen an update for a while.

@ri-we - I have been actively maintaining it and there has been a version (8.7.0) released since this one.  I'll package the latest version (8.8.0) shortly.

**Comment by ri-we** [comment]
@virtualex-itv is this packagage community maintained? Or are you working for the vendor? Community maintained packages are nice, but also something to worry about.

**Comment by auanasgheps** [comment]
I work at VMware. I would love to help get this package maintained by us, but I have no idea how to do so. Let me know and we'll discuss.

**Comment by virtualex-itv** [comment]
> I work at VMware. I would love to help get this package maintained by us, but I have no idea how to do so. Let me know and we'll discuss.

@auanasgheps -  I'm also a VMware employee...not sure how we'd go about this either...

**Comment by mdanish-kh** [comment]
@virtualex-itv @auanasgheps https://github.com/microsoft/winget-pkgs/issues/100 is being worked on; You would be able to take control of the package once the business process for it is finalized. In the meantime, you might want to integrate winget-create into your release workflow to automate submissions for the package. You can look at examples of [Oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml) and [Powertoys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml) on how to set that up.

**Comment by denelon** [comment]
@auanasgheps and @virtualex-itv we would love to have VMware publish manifests for their packages. 😊

If you can get the process automated, it's likely the other submissions would slow down or stop. As soon as we have the "Verified Developer" business processes resolved, we will make an announcement and update documentation across the board.

**Comment by auanasgheps** [comment]
@denelon I'll get in touch with the Release Manager / Product Manager for Horizon, hoping to get his/her interest in the matter!
