### ISSUE TITLE
[Package Issue]: Google.AndroidStudio 2021.3.1.17 endless reinstalls

### ISSUE THREAD

**Issue by justinkb** [microsoft/winget-pkgs#86933]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

After updating to AndroidStudio version 2021.3.1.17 from 2021.3.1.16, winget still insists that 2021.3.1.16 is still installed.

My theory is that this is because the DisplayVersion in registry is simply "2021.3".

https://github.com/justinkb/winget-pkgs/commit/172ee58f923917aa01167402407c7648e9e70a6d is my candidate fix, but I have no way of validating whether this works as intended without setting up a winget repository (the issue can't be tested with a simple winget validate --manifest . and winget install --manifest . combo), and that is too much of a hassle

### Steps to reproduce

Install/update Google.AndroidStudio to 2021.3.1.17

Try a "winget upgrade --all"

### Actual behavior

Keeps installing 2021.3.1.17 endlessly

### Expected behavior

I expect winget to be aware it has already been updated

### Environment

```shell
[winget --info]
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.675
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by russellbanks** [comment]
By the looks of it, https://github.com/microsoft/winget-cli/issues/2366 is the cause here

**Comment by russellbanks** [comment]
>https://github.com/justinkb/winget-pkgs/commit/172ee58f923917aa01167402407c7648e9e70a6d is my candidate fix

Duplicate DisplayVersion entries cause the pipeline to fail - https://github.com/jedieaston/Add-ARPEntries/issues/9

**Comment by russellbanks** [comment]
I think as a temporary measure, we could make it so only the latest version has a direct DisplayVersion correlation. This would consist of:
1. Removing 2021.3.1.17
2. Replacing 2021.3.1.16 with 2021.3, but containing the installer for 2021.3.1.17

**Comment by justinkb** [comment]
it's not a critical issue for me, I'll leave it up to you to decide what you think is best for now. seems like a high priority bug, so hopefully it's fixed soon tho

**Comment by birbilis** [comment]
When a download is big, it's obviously an issue

**Comment by treysis** [comment]
Can I temporarily fix that in the registry for the currently installed version? I'll do it manually after every update until this is resolved.

**Comment by russellbanks** [comment]
> Can I temporarily fix that in the registry for the currently installed version? I'll do it manually after every update until this is resolved.

Are you still experiencing an issue @treysis? This should already be resolved

**Comment by justinkb** [comment]
This is now occurring again with 2022.2.1.18 and 2022.2.1.20. I am also
seeing this again. Presumably the 2022.2.1.20 manifest doesn't do the
version trick

**Comment by justinkb** [comment]
Had a quick look, the .19 and .20 installer manifests both fail the include
"2022.2" DisplayVersion specifiers. Both will need to be amended

**Comment by russellbanks** [comment]
> "2022.2" DisplayVersion specifiers

If multiple consecutive versions have the same DisplayVersion, only the earliest one needs that entry. Otherwise, the pipelines fail and have broken before because of this.

**Comment by justinkb** [comment]
then winget must have some bug, because this issue has definitely come back with 2022.2.1.18 onward to .19 and .20

**Comment by treysis** [comment]
Maybe it's because the last version with the `DisplayVersion` field was major version 2022.**1**, while 2022.2.1.18, .19, and .20 are all major version 2022.**2**?

**Comment by justinkb** [comment]
that's not it: https://github.com/microsoft/winget-pkgs/blob/0bf4a822b70e611025ad7b5a61530f53dbc13b6e/manifests/g/Google/AndroidStudio/2022.2.1.18/Google.AndroidStudio.installer.yaml#L17

**Comment by treysis** [comment]
Then maybe the latest version needs this entry (as this was the case for 2021.3.1.17)? Or, the fix never worked in the first place.

**Comment by treysis** [comment]
Any chance adding "DisplayVersion" to 1.20 and remove it from 1.18?

**Comment by justinkb** [comment]
@russellbanks what compelling reason is there even to keep old minor version manifests in the repository? Is there any real point?
