### ISSUE TITLE
[Package Request]: VirtualBox 7.0

### ISSUE THREAD

**Issue by timeneverdie** [microsoft/winget-pkgs#86967]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Oracle
Publisher Url: https://www.virtualbox.org
Package Name: VirtualBox
Description: 
Package Version: 7.0.2
Installer URL: https://download.virtualbox.org/virtualbox/7.0.2/VirtualBox-7.0.2-154219-Win.exe

Current Package Identifier (for new versions): 6.38 (in fact, 6.40 comes out too)

**Comment by vedantmgoyal2009** [comment]
* https://github.com/microsoft/winget-pkgs/pull/83118

**Comment by timeneverdie** [comment]
> * [New version: Oracle.VirtualBox version 7.0.2 [FP-O] #83118](https://github.com/microsoft/winget-pkgs/pull/83118)

Why did it fail? Why didn't Microsoft merge?

**Comment by vedantmgoyal2009** [comment]
It did not pass automatic validation, which is why manual validation from MS team is needed.

**Comment by timeneverdie** [comment]
> It did not pass automatic validation, which is why manual validation from MS team is needed.

It has been 21 days. It's kidding. I don't think Microsoft takes Winget Project seriously.

**Comment by vedantmgoyal2009** [comment]
They do take. I guess it got missed because it moved down in the list.

**Comment by vedantmgoyal2009** [comment]
I've mentioned it in the chat. You can hope to get it resolved in the next few days.

**Comment by i2** [comment]
Any updates on this resolution?

**Comment by linghengqian** [comment]
- I think this issue should be closed.

**Comment by mdanish-kh** [comment]
Close with reason: Package merged into the repository.

**Comment by mdanish-kh** [comment]
Close with reason: Package merged into the repository;
