### ISSUE TITLE
[Package Issue]: appmakes.Typora

### ISSUE THREAD

**Issue by Troubadix** [microsoft/winget-pkgs#86970]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installed Typora using "winget install appmakes.Typora", installs current version 1.4.8 but "winget upgrade" still shows 1.4.7
Trying to updated older version of Typora using "winget upgrade" works but still shows 1.4.7.

### Steps to reproduce

"winget install appmakes.Typora"
"winget upgrade"

### Actual behavior

Version information is wrong

### Expected behavior

Version information is shown correctly

### Environment

```shell
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.2130
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by SpecterShell** [comment]
This is due to a bug from the installer of the latest version 1.4.8 that writes incorrect version 1.4.7 to the registry. I have opened an issue to them. https://github.com/typora/typora-issues/issues/5493

**Comment by abnerlee** [comment]
updated new installer in https://github.com/microsoft/winget-pkgs/pull/87071

**Comment by Trenly** [comment]
Close with reason: Resolved by 87071;
