### ISSUE TITLE
[Package Issue]: Remove Mozilla.Firefox.Nightly yamls

### ISSUE THREAD

**Issue by t-matsuu** [microsoft/winget-pkgs#87309]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Firefox Nightly is a package that is updated twice a day.
It is not appropriate to add Mozilla.Firefox.Nightly to winget because we cannot handle such an update frequency, and in fact has not been updated for a long time.

### Steps to reproduce

winget show Mozilla.Firefox.Nightly

### Actual behavior

Show 97.0a1. on a particular release date.

### Expected behavior

Show the latest version on the latest date released.

### Environment

```shell
[winget --info]
Windows パッケージ マネージャー v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.755
システム アーキテクチャ: X64
パッケージ: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by russellbanks** [comment]
We could potentially automate the publishing of `Mozilla.Firefox.Nightly` - pinging @vedantmgoyal2009 for this. For the time being, I'll remove the outdated versions and at least get the latest nightly version on there so we have something to work with.

**Comment by russellbanks** [comment]
I've submitted a [pull request](https://github.com/microsoft/winget-pkgs/pull/87337) for the latest nightly release, `108.0a1`. This is basic in the sense that it only adds en-US installers, and there are lots of languages that the nightly releases are available in, but adding them all by hand would be a monumental task. Most of the URLs seem to be in the format of:
```
https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-[version].[locale].[architecture].installer.[exe|msi|msix)
```
So it could theoretically be automated for the future.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/87309#issuecomment-1497410404

@gamer191, it appears to have been removed, since `Find-WinGetPackage 'Firefox' | Select-String 'Nightly'` returns nothing.
