### ISSUE TITLE
Should demo/trial versions of software be allowed?

### ISSUE THREAD

**Issue by MarNicGit** [microsoft/winget-pkgs#874]
Should demo/trial versions of software be allowed? Allowing them would open up the repo to thousands of entries from games and software alike. Personally I wouldn't be against it as it'd make trying out software easier.

The issue I have is that there isn't really a precedent; Linux repositories rarely list proprietary programs at all (with the exception of drivers) so there isn't really a concept of a "demo" or "trial" there.

If people agree that these should be submitted then I propose their versions are prefixed with `demo-`/`trial-`, as well as mentioning any limitations in the description.

The biggest difference between a demo and a trial would be that the demo version is just function-limited whereas the trial version is time-limited.

**Comment by chausner** [comment]
A lot of software uses the same installers for bought and trial licenses. I.e. even if you have bought the product, you would still first download the trial version and then activate it using a serial key. I think it would be confusing if this software was prefixed with demo/trial.

**Comment by MarNicGit** [comment]
That's a good point you make, and I agree that those installers should not be prefixed. What I'm mostly aiming at is installers that specifically install a demo/trial version of an application and are not unlockable by means of a serial key or account.
