### ISSUE TITLE
[Package Request]: Microsoft PC Manager (Beta)

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#87459]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Microsoft
Publisher Url: https://pcmanager.microsoft.com/en
Package Name: Microsoft.PCManager
Description: Clean up system fragments, free up occupied resources, and make your Windows as fast as new.
Package Version: 1.2.4.5
Installer URL: https://aka.ms/PCManager10000

By the way, please add servers outside China (download speed is so slow).

**Comment by Trenly** [comment]
> By the way, please add servers outside China (download speed is so slow).

The URL goes directly to a China server. Unless someone at Microsoft has a link to a different CDN, we can only add the China server
![image](https://user-images.githubusercontent.com/12611259/199870833-fe76904f-b23c-4041-86e6-e888378da09a.png)

**Comment by SpecterShell** [comment]
https://aka.ms/PCManagerOFLV2.3
Not the latest version

**Comment by SpecterShell** [comment]
https://aka.ms/PCManagerUpgrade10000
Redirect to latest version. Currently there is only one URL in their API response.

**Comment by ppvnf** [comment]
Apparently clicking "Download" in https://pcmanager.microsoft.com/en uses a US server now

**Comment by jo-chemla** [comment]
Hi there. I could not find Microsoft PC Manager on winget.run. Could you check if it has indeed been added to the packages? Thanks!

**Comment by rollingmoai** [comment]
> Hi there. I could not find Microsoft PC Manager on winget.run. Could you check if it has indeed been added to the packages? Thanks!

I suggest you use winstall.app: https://winstall.app/apps/Microsoft.PCManager

**Comment by jo-chemla** [comment]
Woops sorry about that. Indeed, the package gets listed on winstall but not on the winget website - this mislead me in thinking the package was not available, but searching it with `winget` cli did indeed find it.

**Comment by jo-chemla** [comment]
By the way, if I'd like this package - or any windows package automatically built - to be published as a chocolatey package, should I ask a maintainer from here or directly ask one of the [chocolatey-community](https://github.com/chocolatey-community/chocolatey-packages) core maintainers? Note that if a Github Action is already setup to publish these winget packages, it could easily be used to push the same packages to chocolatey using the flow described in [this article](https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/). 
Should I open a new issue for that request? Thanks again for your help!
