### ISSUE TITLE
[Package Issue]: Microsoft.Sysinternals.ProcessExplorer

### ISSUE THREAD

**Issue by RadAd** [microsoft/winget-pkgs#87458]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

```
-> winget upgrade -e --id Microsoft.Sysinternals.ProcessExplorer
Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 17.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://live.sysinternals.com/procexp.exe
  ██████████████████████████████  4.35 MB / 4.35 MB
Installer hash does not match; to override this check use --force
```

### Steps to reproduce

`winget upgrade -e --id Microsoft.Sysinternals.ProcessExplorer`

### Actual behavior

`Installer hash does not match; to override this check use --force`

### Expected behavior

Successful installation

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by lobneroO** [comment]
I get the same problem with version 17.04 when installing.

> $ winget install Microsoft.Sysinternals.ProcessExplorer
> Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 17.04
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://live.sysinternals.com/procexp64.exe
>   ██████████████████████████████  2.28 MB / 2.28 MB
> Installer hash does not match.

**Comment by thekovic** [comment]
Hello, I would like to reopen this issue as it's happening for me now and failing to install Version 17.06:
```
> winget install --id Microsoft.Sysinternals.ProcessExplorer
Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 17.06
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.sysinternals.com/files/ProcessExplorer.zip
  ██████████████████████████████  3.34 MB / 3.34 MB
Installer hash does not match.
```

**Comment by lukaskaeppeli** [comment]
> Hello, I would like to reopen this issue as it's happening for me now and failing to install Version 17.06:
> 
> ```
> > winget install --id Microsoft.Sysinternals.ProcessExplorer
> Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 17.06
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://download.sysinternals.com/files/ProcessExplorer.zip
>   ██████████████████████████████  3.34 MB / 3.34 MB
> Installer hash does not match.
> ```

Same here with Version 17.08.
