### ISSUE TITLE
[Package Issue]: VirusTotal.VirusTotalUploader

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#87702]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

VirusTotal.VirusTotalUploader
version not detected after installing latest one

### Steps to reproduce

install VirusTotal.VirusTotalUploader
list VirusTotal.VirusTotalUploader

### Actual behavior

version not detected

### Expected behavior

version detected

### Environment

```shell
Gerenciador de Pacotes do Windows v1.3.2691
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.19044.2130
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.18.2691.0

Registros: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-------------------------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
Termos da Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![Captura de tela 2022-11-07 132206](https://user-images.githubusercontent.com/73800734/200361551-3d212b49-dc3a-4b44-baad-75424e7dda05.png)

**Comment by Trenly** [comment]
This is because the publisher does not set the DisplayVersion property in their installer. Because winget uses this property to determine the version of the application, it displays it as unknown because there is no version information available.

@msftbot area-external

**Comment by ppvnf** [comment]
Thanks for fixing it in https://github.com/microsoft/winget-pkgs/pull/87703

**Comment by ppvnf** [comment]
I did further testing and it's not fixed yet
![Captura de tela 2022-11-09 103736](https://user-images.githubusercontent.com/73800734/200844697-eb67ed9a-828e-462e-97d4-f892f3f2b44e.png)

**Comment by Trenly** [comment]
@msftbot Installer issue
