### ISSUE TITLE
Issue with Figma package install

### ISSUE THREAD

**Issue by jahvari** [microsoft/winget-pkgs#87705]
### Brief description of your issue

When attempting to either upgrade or install Figma package, this is the error that is returned. 

C:\WINDOWS\system32>winget install --id Figma.Figma
Found Figma [Figma.Figma] Version 116.4.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://desktop.figma.com/win/FigmaSetup.exe
  ██████████████████████████████  92.9 MB / 92.9 MB
Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

winget install --id Figma.Figma

winget upgrade --id Figma.Figma

### Expected behavior

The package to install or upgrade

### Actual behavior

Returns this error: 

Installer hash does not match; this cannot be overridden when running as admin

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2006
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by Trenly** [comment]
Close with reason: New version merged;

**Comment by mauromotion** [comment]
I'm still having this issue. Am I missing something? Figma won't update and I get: `Installer hash does not match; to override this check use --force` 

Do I need to force it? Also from the actual Figma app it looks like there's no update needed.
