### ISSUE TITLE
Pipelines appear to be down.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-pkgs#8772]
On several open pull requests the automated tests are failing with an authentication error, see #8769, #8768. 

```
Script failed with error: ERROR: (AuthenticationFailed) Authentication failed.
```

Edit: sorry, looks like it's working now.

**Comment by denelon** [comment]
It might have to do with the AAD issues we're currently experiencing.

**Comment by jedieaston** [comment]
https://i.imgur.com/Awr4wXr.jpeg
