### ISSUE TITLE
[Package Request]: Help with building manifests for Affinity Photo, Designer and Publisher (URLs needed)

### ISSUE THREAD

**Issue by borque** [microsoft/winget-pkgs#88226]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Serif
Publisher Url: https://affinity.serif.com/
Package Name: Affinity Photo / Affinity Designer / Affinity Publisher
Description: The Affinity-programs from Serif offer similar functions as the corresponding Adobe Apps Photoshop, Illustrator and InDesign without requiring a subscription.

I would like to create manifests for them, unfortunately I am unable to find static download URLs. I have download URLs in my personal Serif-Account, but I am unsure whether they are personalized for me or generic.
If someone could provide proper generic URLs I would be happy to build the manifests.

Edit: I have found these URLs in the download area of a popular german computer magazine, but I am unsure whether they are working everywhere and are without adware...
https://securedl.cdn.chip.de/downloads/54314858/affinity-photo-2.0.0.msix
https://securedl.cdn.chip.de/downloads/46845141/affinity-designer-2.0.0.msix
https://securedl.cdn.chip.de/downloads/102258215/affinity-publisher-2.0.0.msix

Thanks for help!

**Comment by TheBossMagnus** [comment]
So, getting the free trial download requires registration, idk if this is ok with Winget rules.
Using third-party links isn't a great solution, but from Italy they work fine. 
Is 2.0.0 the latest release?

**Comment by borque** [comment]
Can be closed once PRs #89224 , #89223 and #89210 are merged.

**Comment by AsciiWolf** [comment]
They sadly were not merged. Please, consider reopening this issue.
