### ISSUE TITLE
[Package Request]: AxGlyph

### ISSUE THREAD

**Issue by jiaojiaodubai** [microsoft/winget-pkgs#88305]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:Amyxun
Publisher Url:https://www.amyxun.com/
Package Name:AxGlyph
Description:A WYSIWYG scientific illustration editor for Microsoft Office users
Package Version:1.78
Installer URL:https://download.s21i.faiusr.com/4232652/0/0/ABUIABBPGAAgg8_mmQYo5JmmZw.zip?f=%E7%9F%A2%E9%87%8F%E7%BB%98%E5%9B%BE_AxGlyph_Setup_Win_20220920.zip&v=1663674244

Current Package Identifier (for new versions):

**Comment by TheBossMagnus** [comment]
.zip download

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Yousha** [comment]
Resolved by #122522 ?

**Comment by jiaojiaodubai** [comment]
yes, I think this issue should be closed now.
