### ISSUE TITLE
[Package Request]: AxMath

### ISSUE THREAD

**Issue by jiaojiaodubai** [microsoft/winget-pkgs#88303]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:Amyxun
Publisher Url:https://www.amyxun.com/
Package Name:AxMath
Description:A professional formula editor for users of Microsoft Office programs
Package Version:2.7058
Installer URL:https://download.s21i.faiusr.com/4232652/0/0/ABUIABBPGAAg886mmQYolufQ4AU.zip?f=%E5%85%AC%E5%BC%8F%E7%BC%96%E8%BE%91%E5%99%A8_AxMath_Setup_Win_20220920.zip&v=1663674227

Current Package Identifier (for new versions):

**Comment by TheBossMagnus** [comment]
.zip download

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Heviwulansari** [comment]
> 
(RAHASIA) Jangan Berikan kepada pihak lain /yg mengaku BRI. Kode OTP Pembukaan rekening Anda adalah 687659 (berlaku 10 menit). Info Contact BRI 14017 / 1500017

**Comment by jiaojiaodubai** [comment]
Installer URL updated: https://download.s21i.faiusr.com/4232652/0/0/ABUIABBPGAAg_cmbpgYo8ZqKiwY.zip?f=%E5%85%AC%E5%BC%8F%E7%BC%96%E8%BE%91%E5%99%A8_AxMath_Setup_Win_20230731.zip&v=1690756346
