### ISSUE TITLE
Package parity with ninite

### ISSUE THREAD

**Issue by superusercode** [microsoft/winget-pkgs#890]
This is primarily a tracking issue for myself with the intent to add packages not yet included from ninite, make sure they use static installer links, ensure the right installer types are being used, and include as much information possible in the manifests (such as descriptions, tags, cli names ,etc.). I will avoid unsupported or EOL releases.

| Name                         | Description                                       | /select Name                   |
|------------------------------|---------------------------------------------------|--------------------------------|
| .NET                         | Microsoft .NET 3.5 SP1                            | ".NET"                         |
| .NET 4                       | Microsoft .NET 4.0.30319                          | ".NET 4"                       |
| .NET 3.5                     | Microsoft .NET 3.5 SP1                            | ".NET 3.5"                     |
| .NET 4.5                     | Microsoft .NET 4.5.50709                          | ".NET 4.5"                     |
| .NET 4.5.1                   | Microsoft .NET 4.5.51641                          | ".NET 4.5.1"                   |
| .NET 4.5.2                   | Microsoft .NET 4.5.51650                          | ".NET 4.5.2"                   |
| .NET 4.6                     | Microsoft .NET 4.6.00081                          | ".NET 4.6"                     |
| .NET 4.6.1                   | Microsoft .NET 4.6.01055                          | ".NET 4.6.1"                   |
| .NET 4.6.2                   | Microsoft .NET 4.6.01590                          | ".NET 4.6.2"                   |
| .NET 4.7                     | Microsoft .NET 4.7.02053                          | ".NET 4.7"                     |
| .NET 4.7.1                   | Microsoft .NET 4.7.02558                          | ".NET 4.7.1"                   |
| .NET 4.7.2                   | Microsoft .NET 4.7.03062                          | ".NET 4.7.2"                   |
| .NET 4.8                     | Microsoft .NET 4.8.03761                          | ".NET 4.8"                     |
| 7-Zip                        | Great Compression App 19.00                       | "7-Zip"                        |
| Acrobat                      | Acrobat Std/Pro Updates 9.x-2020                  | Acrobat                        |
| Ad-Aware                     | Antivirus Free Trial 11.15.1046.10613             | "Ad-Aware"                     |
| AIM                          | AOL Instant Messenger 7.5.21.5                    | AIM                            |
| AIMP                         | Music Player 4.60.2180                            | AIMP                           |
| Air                          | Adobe Air 32.0.0.125                              | Air                            |
| Audacity                     | Audio Editor 2.3.3                                | Audacity                       |
| Auslogics                    | Great Disk Defrag 7.1.0.0                         | Auslogics                      |
| Avast                        | Avast Free Antivirus 20.3.2405                    | Avast                          |
| AVG                          | AVG Free Antivirus 20.3.3120                      | AVG                            |
| Avira                        | Avira Free Antivirus 15.0.2005.1882               | Avira                          |
| BitTorrent Sync              | File Synchronization 1.4.111                      | "BitTorrent Sync"              |
| Blender                      | 3D Creation Suite 2.82.0                          | Blender                        |
| CCCP                         | Video decoders plus MPC 2015.10.19                | CCCP                           |
| CDBurnerXP                   | Disc Burner 4.5.8.7128 (requires .NET)            | CDBurnerXP                     |
| Chrome                       | Fast Browser by Google 83.0.4103.61               | Chrome                         |
| Citrix Receiver              | Citrix Receiver 4.12.0.18016                      | "Citrix Receiver"              |
| Citrix Workspace             | Citrix Workspace 20.2.0.25                        | "Citrix Workspace"             |
| Classic Start                | Classic Shell Win8 Start Menu 4.3.1               | "Classic Start"                |
| CutePDF                      | Print Documents as PDF Files 4.0                  | CutePDF                        |
| Digsby                       | Multi-IM Client Build 30295                       | Digsby                         |
| Discord                      | Voice and Text Chat 0.0.305                       | Discord                        |
| Dropbox                      | Great Online Backup/File Sync 97.4.467            | Dropbox                        |
| Eclipse                      | IDE for Java 4.15.0 (requires Java)               | Eclipse                        |
| eMule                        | File Sharing Client 0.50a                         | eMule                          |
| Essentials                   | Great Antivirus by Microsoft 4.10.209             | Essentials                     |
| Evernote                     | Online Notes 6.24.2.8919                          | Evernote                       |
| Everything                   | Local File Search Engine 1.4.1.969                | Everything                     |
| FastStone                    | FastStone Image Viewer 7.5                        | FastStone                      |
| FileZilla                    | FTP Client 3.48.1                                 | FileZilla                      |
| Firefox                      | Extensible Browser 76.0.1                         | Firefox                        |
| Firefox ESR                  | Extended Support Release 68.8.0                   | "Firefox ESR"                  |
| Firefox ESR 10               | Extended Support Release 10.0.12                  | "Firefox ESR 10"               |
| Firefox ESR 17               | Extended Support Release 17.0.11                  | "Firefox ESR 17"               |
| Firefox ESR 24               | Extended Support Release 24.8.1                   | "Firefox ESR 24"               |
| Firefox ESR 31               | Extended Support Release 31.8.0                   | "Firefox ESR 31"               |
| Firefox ESR 38               | Extended Support Release 38.8.0                   | "Firefox ESR 38"               |
| Firefox ESR 45               | Extended Support Release 45.9.0                   | "Firefox ESR 45"               |
| Firefox ESR 52               | Extended Support Release 52.9.0                   | "Firefox ESR 52"               |
| Firefox ESR 60               | Extended Support Release 60.9.0                   | "Firefox ESR 60"               |
| Firefox ESR 68               | Extended Support Release 68.8.0                   | "Firefox ESR 68"               |
| Flash                        | Flash Player for other browsers 32.0.0.371        | Flash                          |
| Flash (IE)                   | Flash Player for Internet Explorer 32.0.0.371     | "Flash (IE)"                   |
| Flash (PPAPI)                | Flash Player for Opera and Chromium               | "Flash (PPAPI)"                |
| foobar2000                   | Music Player 1.5.4                                | foobar2000                     |
| Foxit Reader                 | Alternative PDF Reader 10.0.0.35798               | "Foxit Reader"                 |
| GIMP                         | Open Source Image Editor 2.10.18.2                | GIMP                           |
| Glary                        | System Utilities 5.142.0.168                      | Glary                          |
| GOM                          | Video Player 2.3.14.5270                          | GOM                            |
| Google Backup and Sync       | Online Backup/File Sync 3.49.9800.0000            | "Google Backup and Sync"       |
| Google Drive                 | Online Backup/File Sync 2.34.5075.1619            | "Google Drive"                 |
| Google Drive File Stream     | (requires G Suite) 38.0.16.0                      | "Google Drive File Stream"     |
| Google Earth                 | Online Atlas by Google 7.3.3.7699                 | "Google Earth"                 |
| Google Talk                  | Google Talk IM Client 1.0.0.104                   | "Google Talk"                  |
| GoToMeeting                  | Online Meeting 10.9.0.17359                       | GoToMeeting                    |
| Greenshot                    | Screenshot Tool 1.2.10.6                          | Greenshot                      |
| HandBrake                    | Convert Videos 1.3.2 (requires .NET 4.7.1)        | HandBrake                      |
| Hulu                         | Internet TV                                       | Hulu                           |
| ImgBurn                      | Disc Burner 2.5.8.0                               | ImgBurn                        |
| InfraRecorder                | Disc Burner 0.53.0                                | InfraRecorder                  |
| Inkscape                     | Vector Graphics Editor 1.0                        | Inkscape                       |
| IrfanView                    | Image Viewer 4.54                                 | IrfanView                      |
| iTunes                       | Music/Media Manager 12.10.7.3                     | iTunes                         |
| Java                         | Java Runtime Environment (JRE) 8u251-b08          | Java                           |
| Java 6                       | Java Runtime Environment (JRE) 6u45-b06           | "Java 6"                       |
| Java 7                       | Java Runtime Environment (JRE) 7u79-b15           | "Java 7"                       |
| Java 8                       | Java Runtime Environment (JRE) 8u251-b08          | "Java 8"                       |
| Java (AdoptOpenJDK)          | 32-bit Java Runtime (JRE) 8u252-b09               | "Java (AdoptOpenJDK)"          |
| Java (AdoptOpenJDK) 8        | 32-bit Java Runtime (JRE) 8u252-b09               | "Java (AdoptOpenJDK) 8"        |
| Java (AdoptOpenJDK) x64      | 64-bit Java Runtime (JRE) 8u252-b09               | "Java (AdoptOpenJDK) x64"      |
| Java (AdoptOpenJDK) x64 8    | 64-bit Java Runtime (JRE) 8u252-b09               | "Java (AdoptOpenJDK) x64 8"    |
| Java (AdoptOpenJDK) x64 11   | 64-bit Java Runtime (JRE) 11.0.7                  | "Java (AdoptOpenJDK) x64 11"   |
| Java (Oracle) 8              | New Oracle license 8u251-b08                      | "Java (Oracle) 8"              |
| Java (Oracle) x64 8          | New Oracle license 8u251-b08                      | "Java (Oracle) x64 8"          |
| Java x64                     | 64-bit Java Runtime (JRE) 8u251-b08               | "Java x64"                     |
| Java x64 7                   | 64-bit Java Runtime (JRE) 7u79-b15                | "Java x64 7"                   |
| Java x64 6                   | 64-bit Java Runtime (JRE) 6u45-b06                | "Java x64 6"                   |
| Java x64 8                   | 64-bit Java Runtime (JRE) 8u251-b08               | "Java x64 8"                   |
| Java x64 9                   | 64-bit Java Runtime (JRE) 9.0.4                   | "Java x64 9"                   |
| Java x64 10                  | 64-bit Java Runtime (JRE) 10.0.2                  | "Java x64 10"                  |
| JDK                          | Java Development Kit 8u251-b08                    | JDK                            |
| JDK 6                        | Java Development Kit 6u45-b06                     | "JDK 6"                        |
| JDK 7                        | Java Development Kit 7u79-b15                     | "JDK 7"                        |
| JDK 8                        | Java Development Kit 8u251-b08                    | "JDK 8"                        |
| JDK (AdoptOpenJDK)           | Java Development Kit 8u252-b09                    | "JDK (AdoptOpenJDK)"           |
| JDK (AdoptOpenJDK) 8         | Java Development Kit 8u252-b09                    | "JDK (AdoptOpenJDK) 8"         |
| JDK (AdoptOpenJDK) x64       | 64-bit Java Development Kit 8u252-b09             | "JDK (AdoptOpenJDK) x64"       |
| JDK (AdoptOpenJDK) x64 8     | 64-bit Java Development Kit 8u252-b09             | "JDK (AdoptOpenJDK) x64 8"     |
| JDK (AdoptOpenJDK) x64 11    | 64-bit Java Development Kit 11.0.7                | "JDK (AdoptOpenJDK) x64 11"    |
| JDK (Amazon Corretto)        | Java Development Kit 8u252-b09                    | "JDK (Amazon Corretto)"        |
| JDK (Amazon Corretto) 8      | Java Development Kit 8u252-b09                    | "JDK (Amazon Corretto) 8"      |
| JDK (Amazon Corretto) x64    | 64-bit Java Development Kit 8u252-b09             | "JDK (Amazon Corretto) x64"    |
| JDK (Amazon Corretto) x64 8  | 64-bit Java Development Kit 8u252-b09             | "JDK (Amazon Corretto) x64 8"  |
| JDK (Amazon Corretto) x64 11 | 64-bit Java Development Kit 11.0.7                | "JDK (Amazon Corretto) x64 11" |
| JDK x64                      | Java Development Kit 8u251-b08                    | "JDK x64"                      |
| JDK x64 7                    | Java Development Kit 7u79-b15                     | "JDK x64 7"                    |
| JDK x64 8                    | Java Development Kit 8u251-b08                    | "JDK x64 8"                    |
| JDK x64 11                   | Java Development Kit 11.0.7                       | "JDK x64 11"                   |
| K-Lite Codecs                | Video decoders plus Media Player Classic 15.4.8   | "K-Lite Codecs"                |
| K-Lite Codecs x64            | Supplemental 64-bit video decoders 10.0.0         | "K-Lite Codecs x64"            |
| KeePass                      | Password Manager Classic 1.38                     | KeePass                        |
| KeePass 2                    | Password Manager 2.45                             | "KeePass 2"                    |
| KeePass 1                    | Password Manager Classic 1.38                     | "KeePass 1"                    |
| KMPlayer                     | Video Player 4.1.2.2                              | KMPlayer                       |
| Krita                        | Painting Program 4.2.9                            | Krita                          |
| Launchy                      | Hotkey Launcher 2.5                               | Launchy                        |
| LibreOffice                  | Free Office Suite 6.4.4 (JRE recommended)         | LibreOffice                    |
| LogMeIn                      | Remote Access Free/Pro 4.1.13774                  | LogMeIn                        |
| Malwarebytes                 | Malware Remover 4.1.0.56                          | Malwarebytes                   |
| MediaMonkey                  | Music Organizer 4.1.28.1905                       | MediaMonkey                    |
| Messenger                    | Windows Live IM Client 2012 (2009 on XP)          | Messenger                      |
| Mozy                         | MozyHome Online Backup 2.28.2.432                 | Mozy                           |
| MusicBee                     | Music Manager & Player 3.3.7367.38620             | MusicBee                       |
| Notepad++                    | Programmer's Editor 7.8.6                         | "Notepad++"                    |
| NVDA                         | Screen Reader 2020.1                              | NVDA                           |
| OneDrive                     | Online File Sync by Microsoft 20.052.0311.0011    | OneDrive                       |
| OpenOffice                   | Free Office Suite 4.1.7 (JRE recommended)         | OpenOffice                     |
| Opera                        | Alternative Browser 12.17                         | Opera                          |
| Opera Chromium               | Alternative Browser 68.0.3618.125                 | "Opera Chromium"               |
| Opera 12                     | Alternative Browser 12.17                         | "Opera 12"                     |
| Paint.NET                    | Image Editor 4.211.7445.38453 (requires .NET 4.5) | "Paint.NET"                    |
| PDFCreator                   | Print Documents as PDF Files 3.5.1.7201           | PDFCreator                     |
| PeaZip                       | File Compression Tool 7.3.0                       | PeaZip                         |
| Picasa                       | Photo Manager by Google 3.9.141.259               | Picasa                         |
| Pidgin                       | Multi-IM Client 2.13.0                            | Pidgin                         |
| PuTTY                        | SSH client 0.73                                   | PuTTY                          |
| Python                       | Great Programming Language 2.7.18                 | Python                         |
| qBittorrent                  | Free Bittorrent Client 4.2.5                      | qBittorrent                    |
| QuickTime                    | Video Player 7.7.9                                | QuickTime                      |
| Reader                       | Adobe PDF Reader 20.9.20065                       | Reader                         |
| Reader 9                     | Adobe PDF Reader 9.5.5                            | "Reader 9"                     |
| Reader 10                    | Adobe PDF Reader 10.1.16                          | "Reader 10"                    |
| Reader 11                    | Adobe PDF Reader 11.0.23                          | "Reader 11"                    |
| Reader DC                    | Adobe PDF Reader 20.9.20065                       | "Reader DC"                    |
| Reader Classic               | Adobe PDF Reader 17.11.30171                      | "Reader Classic"               |
| Reader Classic 2015          | Adobe PDF Reader 15.6.30523                       | "Reader Classic 2015"          |
| Reader Classic 2017          | Adobe PDF Reader 17.11.30171                      | "Reader Classic 2017"          |
| RealVNC                      | RealVNC Remote Access 6.1.1.28093                 | RealVNC                        |
| Revo                         | App Uninstaller/Reverse Ninite 2.1.5              | Revo                           |
| Safari                       | Alternative Browser by Apple 5.1.7                | Safari                         |
| ShareX                       | Screenshot Uploader                               | ShareX                         |
| Shockwave                    | Shockwave Player 12.3.5.205                       | Shockwave                      |
| Silverlight                  | Microsoft Silverlight 5.1.50918.0                 | Silverlight                    |
| SkyDrive                     | Online File Sync by Microsoft 17.0.2015.0811      | SkyDrive                       |
| Skype                        | Internet Telephone 8.60.0.76                      | Skype                          |
| Songbird                     | Music Manager 2.2.0.2453                          | Songbird                       |
| Spotify                      | Online Music Service 1.1.33.569                   | Spotify                        |
| Spybot                       | Spyware Remover 1.6.2                             | Spybot                         |
| Spybot 2                     | Spyware Remover 2.7.64                            | "Spybot 2"                     |
| Spybot 1                     | Spyware Remover 1.6.2                             | "Spybot 1"                     |
| Steam                        | App Store for Games                               | Steam                          |
| SugarSync                    | Online Backup/File Sync 3.11.2.3                  | SugarSync                      |
| SumatraPDF                   | Lightweight PDF Reader 3.2                        | SumatraPDF                     |
| Super                        | SUPERAntiSpyware Free 8.0.1052                    | Super                          |
| TeamViewer                   | Remote Access Tool 15.5.6                         | TeamViewer                     |
| TeamViewer 7                 | Remote Access Tool 7.0.43148.0                    | "TeamViewer 7"                 |
| TeamViewer 8                 | Remote Access Tool 8.0.251453.0                   | "TeamViewer 8"                 |
| TeamViewer 9                 | Remote Access Tool 9.0.252029.0                   | "TeamViewer 9"                 |
| TeamViewer 10                | Remote Access Tool 10.0.252068.0                  | "TeamViewer 10"                |
| TeamViewer 11                | Remote Access Tool 11.3.55457.0                   | "TeamViewer 11"                |
| TeamViewer 12                | Remote Access Tool 12.0.251385                    | "TeamViewer 12"                |
| TeamViewer 13                | Remote Access Tool 13.2.36218                     | "TeamViewer 13"                |
| TeamViewer 14                | Remote Access Tool 14.7.39531                     | "TeamViewer 14"                |
| TeamViewer 15                | Remote Access Tool 15.5.6                         | "TeamViewer 15"                |
| TeraCopy                     | Better File Copy 3.2.6                            | TeraCopy                       |
| Thunderbird                  | Email Reader by Mozilla 68.8.1                    | Thunderbird                    |
| Thunderbird ESR              | Email Reader by Mozilla 17.0.9                    | "Thunderbird ESR"              |
| Thunderbird ESR 17           | Email Reader by Mozilla 17.0.9                    | "Thunderbird ESR 17"           |
| Trillian                     | Trillian IM 6.3.0.5                               | Trillian                       |
| TrueCrypt                    | Disk Encryption Tool 7.1a                         | TrueCrypt                      |
| TweetDeck                    | Twitter Client 3.3.7                              | TweetDeck                      |
| uTorrent                     | BitTorrent Client 3.5.0.43916                     | uTorrent                       |
| Visual Studio Code           | Programmer's Editor 1.45.1                        | "Visual Studio Code"           |
| VLC                          | Great Video Player 3.0.10                         | VLC                            |
| WebEx                        | WebEx Connect 731.2014.11.13                      | WebEx                          |
| Winamp                       | Music Player 5.8.0.3660                           | Winamp                         |
| WinDirStat                   | Directory Statistics 1.1.2.80                     | WinDirStat                     |
| WinMerge                     | Compare and Merge Files 2.16.6                    | WinMerge                       |
| WinRAR                       | Another Compression Tool 5.90 (Trial)             | WinRAR                         |
| WinSCP                       | SCP Client 5.17.5                                 | WinSCP                         |
| XnView                       | Image Viewer 2.49.3                               | XnView                         |
| Yahoo!                       | Yahoo! IM Client 11.5.0.0228                      | "Yahoo!"                       |
| Zoom                         | Video Conference 5.0.24951.515                    | Zoom                           |

**Comment by Dragon1573** [comment]
Excuse me @superusercode, I would like to submit manifests for `KMPlayer.KMPlayer` package. Before creating manifests with `wingetcreate.exe`, I search the package name and find this closed issue.

`KMPlayer` is listed in your table above. Could you please explain what the table above stands for? Am I able to create and submit this package to `winget-pkgs`?

Thank you!

**Comment by Dragon1573** [comment]
@superusercode Thank you!

I try my best to create a group of manifests of `PandoraTV.KMPlayer64X`, which is the `x64` version of *KMPlayer*. But I can't make the installation process "silent" ...

<details>
<summary>Installation Process</summary>

1. *KMPlayer* first launch a panel configuring the language of the installer. 
2. *KMPlayer* launch an installer of "Microsoft Visual C++ 2010 x86 Redistributable Setup". You should manually accept the license terms and click "Install".
3. Wait a moment, *KMPlayer* will be successfully installed. An [Install Complete](https://www.kmplayer.com/installcomplete) page will automatically launched with your default browser.

</details>

I think these manifests will definitely fail on Azure Pipeline (because it have to install interactively). Could you please help me with improving these manifests?
