### ISSUE TITLE
[Package Request]: guiscrcpy

### ISSUE THREAD

**Issue by Cyberavater** [microsoft/winget-pkgs#89594]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: srevinsaju
Publisher Url: https://github.com/srevinsaju/guiscrcpy
Package Name: guiscrcpy
Description: A simple, pluggable, graphical user interface for the fastest Android screen mirroring software, scrcpy
Package Version: 2022.7.1
Installer URL: https://github.com/srevinsaju/guiscrcpy/releases/tag/v2022.7.1

Current Package Identifier (for new versions):

**Comment by FernandoNunes** [comment]
Hi @Cyberavater the specified package is a stand-alone exe / util. As far as I know, that is now yet supported by winget.
