### ISSUE TITLE
[Package Request]: FileZilla Client

### ISSUE THREAD

**Issue by FernandoNunes** [microsoft/winget-pkgs#89756]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: FileZilla
Publisher Url: https://filezilla-project.org/index.php
Package Name: FileZilla Client x64
Description: The FileZilla Client not only supports FTP, but also FTP over TLS (FTPS) and SFTP. It is open source software distributed free of charge under the terms of the GNU General Public License.
Package Version: 3.63.2
Installer URL: https://dl4.cdn.filezilla-project.org/client/FileZilla_3.62.2_win64-setup.exe?h=gekcB9Ryan28SzhCYVix4Q&x=1669465035

**Comment by mdanish-kh** [comment]
Please see https://github.com/microsoft/winget-pkgs/pull/79352#issuecomment-1242989645 to understand why this package cannot be added to WinGet.

**Comment by mdanish-kh** [comment]
@msftbot Area-External

**Comment by Trenly** [comment]
@msftbot blocking-issue

**Comment by borque** [comment]
I understand that some publishers don't want their bandwith to be used by external installers. Perhaps they need some ads on their download pages to finance the infrastructure.
In many cases like these (especially for free software (and to my knowledge FileZilla is published under GPL) there are other mirrors.
In this special case for example the CDN of Chip, a large german computer magazine mirrors the file.
While noone is particularly happy with this situation it might be appropriate to use download urls from external sources here if the original author / publisher does not disagree.

**Comment by jonahdami** [comment]
I just found your request and checked my installed packages as I remembered I installed filezilla via winget.

Check out `winget install --id=TimKosse.FileZilla.Client`

**Comment by kairin** [comment]
> Please see [#78578 (comment)](https://github.com/microsoft/winget-pkgs/issues/78578#issuecomment-1238126217); The publisher does not want third-party installers to use its infrastructure and since WinGet does not maintain a mirror for hosting binaries, this package cannot be added.

i see... but does posting the binary in github itself is a violation of that?

**Comment by kairin** [comment]
> ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97212)

my earlier post using the original link to publishers website link i realised there was issues with the download.

however when checking in choco, they hosted it elsewhere.

i came to the conclusion if the executable binary is hosted elsewhere, it would be fine too.

**Comment by mdanish-kh** [comment]
We only accept packages from the official source.

> The Windows Package Manager policies requires that the InstallerUrl comes directly from the ISV's release location.

*Reference: https://learn.microsoft.com/en-us/windows/package-manager/package/repository#error-labels*

**Comment by borque** [comment]
I think accepting only "official" InstallerUrls is the best way to keep this repository clean and secure in most cases. But -as here- there might be special cases where this is not be the best solution. I have opened a discussion here ( https://github.com/microsoft/winget-pkgs/discussions/97158 ) .
