### ISSUE TITLE
[Package Issue]: TeamViewer.TeamViewer

### ISSUE THREAD

**Issue by simkoG** [microsoft/winget-pkgs#90083]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Cannot upgrade `TeamViewer.TeamViewer`.

### Steps to reproduce

`winget upgrade TeamViewer.TeamViewer --silent` 

### Actual behavior

```
Found TeamViewer [TeamViewer.TeamViewer] Version 15.36.9
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2
```

### Expected behavior

Upgrade the package without any errors. 

### Environment

```shell
> winget --info

Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2251
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2022-11-30-09-19-58.624.log](https://github.com/microsoft/winget-pkgs/files/10121004/WinGet-2022-11-30-09-19-58.624.log)

**Comment by denelon** [comment]
This appears to be related to the installer itself. I'm not sure what "exit code 2" is in relation to.

If the determination can be made, it might be possible to add that as an "expected return code" to the manifest.

There may be a log in the logs directory for Team Viewer with more detail. The log path for WinGet is available via `winget --info`.

**Comment by simkoG** [comment]
@denelon The previously attached log file is the only log file generated when I tried to upgrade Team Viewer.

**Comment by denelon** [comment]
If the installer isn't logging anything, there isn't much more that I can do to help troubleshoot. Maybe they offer some kind of support or there is a flag or an argument that could be passed to generate a log file. The "--override" argument supports passing arguments to installers if one is supported.

**Comment by brotich** [comment]
@simkoG If possible, may you try and install Team Viewer directly from the set up files, and document if there is any error visible in the install process. 

x64: https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
x86:  https://download.teamviewer.com/download/TeamViewer_Setup.exe

**Comment by schlamar** [comment]
> Winget is trying to install the 64bit version. If the 32bit version is installed, the 64bit installer is running in the same kind of error. A point to check.

That was exactly the issue in my case. I could verify this with `winget upgrade teamviewer -i`.
