### ISSUE TITLE
[Package Request]: osquery 

### ISSUE THREAD

**Issue by dNyaanOpasak** [microsoft/winget-pkgs#90246]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: osquery.io
Publisher Url: https://osquery.io/downloads/official/5.5.1
Package Name: osquery
Description: osquery 5.5.1 installer
Package Version: 5.5.1
Installer URL: https://pkg.osquery.io/windows/osquery-5.5.1.msi

Current Package Identifier (for new versions): MSI Upgrade Code: {EA6C7327-461E-4033-847C-ACDF2B85DEDE}

**Comment by dNyaanOpasak** [comment]
Even I can create a manifest and add it but I am not sure if I as an individual developer should be adding such an extremely important package to the winget. It should be done by either someone from osquery team or from Microsoft. If there is no problem with me submitting a manifest for something not developed / owned by me then I  can happily do it.

**Comment by mdanish-kh** [comment]
> Even I can create a manifest and add it but I am not sure if I as an individual developer should be adding such an extremely important package to the winget. It should be done by either someone from osquery team or from Microsoft. If there is no problem with me submitting a manifest for something not developed / owned by me then I can happily do it.

You can submit the manifest; WinGet is heavily driven by community support and new submissions are always welcome.
