### ISSUE TITLE
[Package Issue]: o2sh.onefetch

### ISSUE THREAD

**Issue by russellbanks** [microsoft/winget-pkgs#90267]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Onefetch 2.13.0, 2,13,1 & 2,13,2 wrote "v" in its DisplayVersion. It removed this in 2.14.0+. The ARP Entries are correctly set in each manifest (2.13.x has the DisplayVersion ARP of `vx.x.x` while 2.14.x does not). WinGet sees this as below:

```pwsh
> winget upgrade
Name                                                       Id                          Version      Available    Source
-----------------------------------------------------------------------------------------------------------------------
onefetch version 2.14.2                                    o2sh.onefetch               > 2.13.2     2.14.2       winget
```

I know this is a known issue, but I want to know the best way to fix this case. I opened #90263, #90264, #90265 to remove the manifests that refer to the versions that have the "v" in their DisplayVersion as I imagine this would fix it. Other mods might have better suggestions though.

### Steps to reproduce

`winget install onefetch`

cc: @mdanish-kh

**Comment by stephengillie** [comment]
#2394

**Comment by russellbanks** [comment]
> [#2394](https://github.com/microsoft/winget-cli/issues/2394)

Would my PRs fix this temporarily?

**Comment by Trenly** [comment]
> > [#2394](https://github.com/microsoft/winget-cli/issues/2394)
> 
> Would my PRs fix this temporarily?

Yes, removing the versions would work temporarily

**Comment by russellbanks** [comment]
Closing as resolved until https://github.com/microsoft/winget-cli/issues/1298 and https://github.com/microsoft/winget-cli/issues/2394 are addressed.
