### ISSUE TITLE
[Package Request]: Visual Studio Build Tools 2017

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-pkgs#90321]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Microsoft
Publisher Url:
Package Name: Visual Studio Build Tools 2017
Description: VS2017 build tools for VS2022
Package Version:
Installer URL:

Current Package Identifier (for new versions):

**Comment by jedieaston** [comment]
We don’t currently have the 2017 stuff, I can look into adding it. 

> VS2017 build tools for VS2022

is there a specific workload you’re looking for? If it can be installed through the VS22 installer, I can give you a command to install it with winget now.

**Comment by sba923** [comment]
I don't have a specific workload in mind. The package is present in several of my machines, where the VS22 installer reports an update's available... but `winget` can't apply it.... yet.

**Comment by sba923** [comment]
#90827 adds 15.8.9, but the latest version reported by the VS22 installer is 15.9.51.

Bottom line: `winget upgrade --all` still doesn't keep that package up-to-date.

@denelon what's the process so that the owners of "VS2017 build tools" push **all** their updates to the `winget` package store?

**Comment by jedieaston** [comment]
Oh darn, they don't post versioned links for the latest build of 2017 like they do for 2019 and 2022. They post a latest redirect link, I can use that I suppose...

**Comment by sba923** [comment]
@jedieaston shouldn't that issue be reopened?
