### ISSUE TITLE
[Package Issue]: Microsoft.Terminal

### ISSUE THREAD

**Issue by bckelley** [microsoft/winget-pkgs#90362]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

upon doing a ``` winget search Microsoft.Terminal``` I get No package found matching input criteria. According to ```DHowett:autogenerated/Microsoft.WindowsTerminal/0834e42f-73ce-4a99-bbee-7084cbf7b526``` which is PR#85492

### Steps to reproduce

using ```winget --version``` v1.3.2691 do ```winget search Microsoft.Terminal```

### Actual behavior

..

### Expected behavior

obvious. 

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2251
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```


### Screenshots and Logs

_No response_

**Comment by warshanks** [comment]
The package name is Microsoft.WindowsTerminal 
```
> winget search microsoft.windowsterminal
Name                     Id                                Version     Source
------------------------------------------------------------------------------
Windows Terminal         Microsoft.WindowsTerminal         1.15.2874.0 winget
Windows Terminal Preview Microsoft.WindowsTerminal.Preview 1.16.2641.0 winget
```

**Comment by bckelley** [comment]
> 

well who named it that, not sure of others but not what i look for.

**Comment by russellbanks** [comment]
For the future you could try more generic search terms like `winget search terminal`

**Comment by bckelley** [comment]
> For the future you could try more generic search terms like `winget search terminal`

what do you lead me to be in this predicament
