### ISSUE TITLE
[Package Request]: Bluebeam.Revu

### ISSUE THREAD

**Issue by Baker32** [microsoft/winget-pkgs#90644]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Bluebeam
Publisher Url: bluebeam.com
Package Name: Bluebeam Revu 21
Description: Setup Suite Launcher Unicode
Package Version: 21.0.20.0
Installer URL: https://bluebeam.com/FullRevuTRIAL

Current Package Identifier (for new versions): 21.0.20.0

**Comment by mluepkes** [comment]
Please see https://github.com/microsoft/winget-pkgs/pull/64731

**Comment by Baker32** [comment]
I believe in this latest package version (beginning with 21 vs 20), they have changed their license model and no longer require a serial number that seems to have stopped the previous attempt to add it to the repository.
