### ISSUE TITLE
[Package Issue]: Discord.Discord  - Autostart with OS forcefully enabled on upgrade even if user does not want this.

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#90642]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

i keep my Discord app settings to have the Startup settings to always be OFF by default, but yesterday when i upgraded Discord via winget, it forcefully set the app to start with the OS, even if the in-app setting is to not start with OS.

### Steps to reproduce

1) install an older version of Discord  (e.g. 1.0.9006)
2) configure it to always start manually, not at OS/user logon
3) run "winget upgrade Discord.Discord"  (currently this will upgrade it to 1.0.9007)

### Actual behavior

either winget or the Discord installer has set the app startup mode to always start at OS/User logon and completely bypassed the user setting to NOT do that (from the Discord settings).

### Expected behavior

Respect the user setting/preference and do not automatically start Discord at logon.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2311
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale



winget show discord.discord
Found Discord [Discord.Discord]
Version: 1.0.9007
Publisher: Discord Inc.
Publisher Url: https://discord.com
Publisher Support Url: https://support.discord.com
Author: Discord Inc.
Moniker: discord
Description: Whether you’re part of a school club, gaming group, worldwide art community, or just a handful of friends that want to spend time together, Discord makes it easy to talk every day and hang out more often.
Homepage: https://discord.com
License: Proprietary
License Url: https://discord.com/licenses
Privacy Url: https://discord.com/privacy
Copyright: (c) 2021 Discord Inc.
Copyright Url: https://discord.com/licenses
Installer:
  Type: exe
  Locale: en-US
  Download Url: https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9007/DiscordSetup.exe
  SHA256: 0ad34ac29ecc6dd01f40b46ab0cb1a971b5242aa28ee1a9b72fdb9847c6d6ee1
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/16319504/205692100-1c272ff3-5f52-4c94-a6ad-cc1ee15fe615.png)

**Comment by R-Adrian** [comment]
update: also filed a bug report with the Discord team ( #30674027 ) ... not sure if/when they get around to look at it.

**Comment by R-Adrian** [comment]
another update: someone from Discord responded to the bug report ... and if i ever saw a * facepalm * moment, then this is it.
It is obvious from the reply that they have not bothered to even look at the screenshot (same one i already posted above).


The basic summary of their message that comes out of this is basically that it's intended to behave like such a spyware, they do not care about in-app user preference or even that the user has already disabled its automatic start before (in exactly the same way as already indicated by their linked support article), so they will just push it through unsolicited anyway and we can go find some other ways to stop this app from starting automatically after each update.

![image](https://user-images.githubusercontent.com/16319504/206245614-8ca38160-09fa-4034-a344-453fda244ea2.png)

**Comment by R-Adrian** [comment]
today my Discord app updated by itself at startup (as it usually does) to v1.0.9008... but the automatic self-update left behind the old version number in the registry and winget still thinks it is version 1.0.9007 because of this:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Discord]
"DisplayName"="Discord"
"DisplayVersion"="1.0.9007"
```
(I tested that Winget is only looking at this when determining the version number by modifying it manually and checking what version will winget report.)

The automatic self-update of Discord did not create the Startup entries that the winget upgrade creates, and even if already updated winget still tries to get me to apply the update again... which it fails to apply properly ( see issue https://github.com/microsoft/winget-pkgs/issues/91016 )


since from the SqurrelSetup.log i see that the v1.0.9008 installer/updater stumbles at deleting the old Discord folder, i helped it along and deleted that folder manually for it, then ran winget upgrade discord.discord.

My conclusion is that the addition of Startup entries is caused by something in the parameters that winget passes to the Discord installer/updater. The updater built-in in the Discord App itself does not do this.


Screenshots below:
- just after the automatic self-update: Discord itself is reporting that it is version 1.0.9008 but winget still thinks it is 1.0.9007
- Startup entries appear after the winget upgrade  (the weird versions reported before the upgrade are because of me modifying that registry entry above)

![image](https://user-images.githubusercontent.com/16319504/206896106-632616ac-df6b-490b-8a65-e3b01b6f9d58.png)


![image](https://user-images.githubusercontent.com/16319504/206896250-79c1ff8a-2620-4820-85e4-e88786c86f84.png)

**Comment by Marc2p** [comment]
Same issue here
