### ISSUE TITLE
[Package Issue]: maurizuki.O2

### ISSUE THREAD

**Issue by maurizuki** [microsoft/winget-pkgs#90768]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The PR #90037 fails due to an installation error during the validation. The log of the validation pipeline is empty.
The result of the validation with the WinGet client is:

```
PS C:\repos> winget install -m C:\repos\winget-pkgs\manifests\m\maurizuki\O2\2.2.7
Found O2 [maurizuki.O2] Version 2.2.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/maurizuki/O2/releases/download/v2.2.7/O2-2.2.7-setup.exe
  ██████████████████████████████  3.63 MB / 3.63 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

The installer is not signed, I had to confirm UAC prompt manually.
At the end of the setup process, the installed app runs and the installer closes.

### Steps to reproduce

Run checks in PR #90037

### Actual behavior

Installation validation failed.

### Expected behavior

Installation validation succeeded.

### Environment

```shell
Windows Package Manager v1.3.2691
Windows: Windows.Desktop v10.0.22621.819
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by Trenly** [comment]
This is because it is failing the security check -
```
2022-11-29 13:38:32.930 [FAIL] Installer failed security check. Url: https://github.com/maurizuki/O2/releases/download/v2.2.7/O2-2.2.7-setup.exe Result: 0x80004005
```

**Comment by maurizuki** [comment]
I see that a second run resolved the problem. Thanks!
