### ISSUE TITLE
[Package Issue]: Plex.Plex

### ISSUE THREAD

**Issue by SiJiL82** [microsoft/winget-pkgs#90969]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Application launches after update finishes

### Steps to reproduce

Update Plex

### Actual behavior

Plex desktop app launches

### Expected behavior

It shouldn't launch - no application should launch itself after just updating it!

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Windows: Windows.Desktop v10.0.19045.2251
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0
```

**Comment by Trenly** [comment]
This would be an issue with the Plex installer. If there isn't a command line switch to prevent the application from launching, a feature request will need to be raised with the plex devs

@msftbot installer-issue
