### ISSUE TITLE
[Package Issue]: Discord.Discord fail to upgrade.

### ISSUE THREAD

**Issue by bartoszek** [microsoft/winget-pkgs#91016]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Upgrading Discord from `1.0.9007` to `1.0.9008` fails.

### Steps to reproduce

1. Have installed Discord Client `v1.0.9007`
2. Call `winget upgrade Discord`

### Actual behavior

3. You get `Error: 4294967295` access denied.
4. Excerpt from log Discord Installer log:
```
...
8248> 2022-11-24 13:29:16> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\bartus\AppData\Local\Discord\app-1.0.9007\Discord.exe]
8248> 2022-11-24 13:29:33> Utility: Process Started: C:\Users\bartus\AppData\Local\Discord\app-1.0.9007\Discord.exe --squirrel-install 1.0.9007, pid 17684
8248> 2022-11-24 13:29:39> Utility: Received exitcode 0 from process C:\Users\bartus\AppData\Local\Discord\app-1.0.9007\Discord.exe
8248> 2022-11-24 13:29:40> ApplyReleasesImpl: ran C:\Users\bartus\AppData\Local\Discord\app-1.0.9007\Discord.exe, pid 5036
8248> 2022-11-24 13:29:40> ApplyReleasesImpl: Starting fixPinnedExecutables
8248> 2022-11-24 13:29:40> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9007
8248> 2022-11-24 13:29:40> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\bartus\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: Access to the path 'C:\Users\bartus\AppData\Roaming\Microsoft\Windows\Start Menu\Programy' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```

### Expected behavior

It should upgrade Discord 1.0.9007 to 1.0.9008

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2251
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[SquirrelSetup.log](https://github.com/microsoft/winget-pkgs/files/10200533/SquirrelSetup.log)

**Comment by jedieaston** [comment]
Two things:
- was Discord running when you tried to upgrade it? That always makes it fail for me.
- `Start Menu\Programy` doesn't seem right, Discord's installer might have a bug?

**Comment by KK-Designs** [comment]
Close discord and then try to update it.

**Comment by rakleed** [comment]
> Close discord and then try to update it.

@stephengillie changing `UpgradeBehavior` to `uninstallPrevious` will not help if the application was running in the background?

**Comment by Trenly** [comment]
The behavior for discord has been updated so that a more clear message is shown

###### Close with reason: UpgradeBehavior changed;
