### ISSUE TITLE
[Package Issue]: Malwarebytes.Malwarebytes

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-pkgs#91703]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Version number for new version is wrong. The package says that the version should be 4.5.19.299 but really it should be 4.5.19.229. Even the name of the program indicates the right version but the available version number is wrong.

### Steps to reproduce

Run "winget upgrade".

### Actual behavior

Wrong version is being reported as the new version.

### Expected behavior

To tell me that I'm up to date.

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
git blame me for overlooking PackageVersion as File Version was set to `4.5.19.299` 🤦‍♂️
