### ISSUE TITLE
[Package Issue]: Rufus.Rufus 

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#91757]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

https://winget.run/pkg/Rufus/Rufus does not have version 3.21

and OTA pushed non-portable version (version 3.21) 

https://github.com/microsoft/winget-pkgs/pull/91131

https://github.com/microsoft/winget-pkgs/pull/91126

### Steps to reproduce

winget upgrade --all

### Actual behavior

https://winget.run/pkg/Rufus/Rufus does not have version 3.21

and OTA pushed non-portable version (version 3.21) 

### Expected behavior

able to upgrade version 3.21

### Environment

```shell
winget --info
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/54496743/208304585-9ac11fe8-840f-4ff9-9472-87b709913e29.png)

OTA pushed non-portable version (version 3.21)

**Comment by vedantmgoyal2009** [comment]
Use https://winstall.app/ instead of https://winget.run/pkg/Rufus/Rufus.

**Comment by Trenly** [comment]
Rufus.Rufus 3.21 does exist. https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rufus/Rufus

**Comment by khewweifeng** [comment]
> Rufus.Rufus 3.21 does exist. https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rufus/Rufus

but it does not upgrade with same portable edition (3.21) ...

**Comment by Trenly** [comment]
> > Rufus.Rufus 3.21 does exist. https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rufus/Rufus
> 
> but it does not upgrade with same portable edition (3.21) ...

I dont understand. Please explain in more detail

**Comment by jedieaston** [comment]
Instead of rufus_3.21p.exe, it's using rufus_3.21.exe which isn't portable and spews some stuff into appdata. Easy fix, I can open a PR....
