### ISSUE TITLE
[Package Request]: Files

### ISSUE THREAD

**Issue by JovialMockingbird** [microsoft/winget-pkgs#91790]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Files Community
Publisher Url: https://github.com/files-community/Files
Package Name: Files
Description: Explore a beautiful Windows-first design. Manage all your files with increased productivity. Work across multiple folders with tabs. And so much more.
Package Version: v2.4.3
Installer URL: https://github.com/files-community/Files/releases/download/v2.4.3/Files.Package_2.4.3.0_x64_ARM64_Sideload.msixbundle

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
The MSIX bundle for `Files` doesn't come bunded with `Microsoft.WindowsAppRuntime.1.2` which is a dependency for `Files` to be installed.

@msftbot dependencies

**Comment by vedantmgoyal2009** [comment]
The package had previously existed in the repo, but has been removed due to MS store support - https://github.com/microsoft/winget-pkgs/pull/24067#issuecomment-939493509
