### ISSUE TITLE
[Package Issue]: KDE.Krita

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-pkgs#91888]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget keeps telling me that that I have to upgrade KDE Krita even though I already have the latest version 5.1.4.

### Steps to reproduce

1. Let winget upgrade KDE Krita.
2. Run winget upgrade again.
3. Note how it tells you that you need to upgrade it, again.

### Actual behavior

...

### Expected behavior

To tell me that I don't have to upgrade the software, again.

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by stephengillie** [comment]
How long have you seen this issue? The most recent KDE.Krita manifest update adds a 4th set to the version number, so I'm wondering if it's causing an issue with the sort order.
* https://github.com/microsoft/winget-pkgs/pull/91769

**Comment by trparky** [comment]
I just started having this issue.

**Comment by mdanish-kh** [comment]
@msftbot reset feedback

**Comment by trparky** [comment]
`Krita (x64) 5.1.4     KDE.Krita      > 5.1.1 5.1.4.100 winget`
This is what winget says,

**Comment by GsakuL** [comment]
I'm having the same problem. 
Krita is `5.1.4.100` but winget still complains

```
> winget upgrade
Name                                    ID                                     Version          Verfügbar        Quelle
-----------------------------------------------------------------------------------------------------------------------
Krita (x64) 5.1.4                       KDE.Krita                              > 5.1.1          5.1.4.100        winget
```

neither `upgrade` nor `uninstall`+`install`resolve this issue

**Comment by GsakuL** [comment]
that's not a good idea. if KDE would update only that part, you could not differentiate between the two.
The better way should be to update ALL of the older Versions, and add the extra explicit `.0`. Some older Versions actually have this:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/KDE/Krita

Or even better: winget should recognize this and implicitly add zeros to make the comparable. 
Because, what happens if some makes a PR, with a new 3-Part Version, and then yet a new 4-Part PR gets created.
Then this issue would happen all over again i presume.

But like, how is it sorting in the first place? By Name alone? That's bad design in general. The folders already are SemVers, or the YML-Manifets contaim them too. It shouldn't be an issue sorting by a Version (which is just a "tuple of integers")

**Comment by stephengillie** [comment]
Semantic versioning officially appears to be a 3-tuple set, but this has become a 4-tuple set, which might be why it's sorting in this way. Supporting additional tuples would be one way to solve this issue. Related: 
* https://github.com/microsoft/winget-cli/issues/981

**Comment by denelon** [comment]
WinGet uses the version from Windows Apps & Features to detect the installed version. It looks like this package might not be updating the registry entry for "displayVersion".

The "appsAndFeatures" entry in the manifest should have the matching value if a "packageVersion" with a marketing version should be displayed. The ">" symbol is what I'm using to identify the presence of a marketing version in the manifest.

It also looks like the "displayVersion" key in the registry is rendering "Krita (x64) 5.1.4" in Windows Apps & Features.

Any of the versions are split at the periods and then the sections are evaluated against each other sequentially.

**Comment by rokejulianlockhart** [comment]
@denelon, is that worth reporting to Krita, then? I'd be happy to if it's their fault.

**Comment by denelon** [comment]
I spoke with one of the engineers, and there may still be a way to get the right behavior here. It will require looking at the other manifests for the other versions of Krita. We should ensure if "one" of them has the "packageVersion" and "displayVersion" fields that all manifests have them. There are strange behaviors when both aren't present in one of the manifests.

If someone can review the installer file for each version and they all have the "appsAndFeatures" key with the "displayVersion" present, then it may behave correctly.

As long as the Krita versioning scheme is consistent, we will be able to get the right behavior.

**Comment by stephengillie** [comment]
> If someone can review the installer file for each version and they all have the "appsAndFeatures" key with the "displayVersion" present, then it may behave correctly.

Reviewing [KDE.Krita](https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/KDE/Krita)'s 11 versions, the bug becomes apparent. [5.1.1 version](https://github.com/microsoft/winget-pkgs/blob/master/manifests/k/KDE/Krita/5.1.1/KDE.Krita.installer.yaml)'s `AppsAndFeaturesEntries` are filled out: 
```
  AppsAndFeaturesEntries:
  - DisplayName: Krita (x64) 5.1.1
    DisplayVersion: 5.1.1.101
    ProductCode: Krita_x64
```

But the [5.1.4 version](https://github.com/microsoft/winget-pkgs/blob/master/manifests/k/KDE/Krita/5.1.4.100/KDE.Krita.installer.yaml)'s `AppsAndFeaturesEntries` have only `DisplayName`:  
```
AppsAndFeaturesEntries:
- DisplayName: Krita (x64) 5.1.4
```
Also this version is scoped to all installers, while it was scoped to the individual installer in the previous version. Since there is only one installer, it doesn't impact programmatic operation, but standardization streamlines comprehension.  

> As long as the Krita versioning scheme is consistent, we will be able to get the right behavior.

Adding `DisplayVersion` and updating `PackageVersion` should resolve this issue.
```
PackageVersion: 5.1.4

  ...

AppsAndFeaturesEntries:
- DisplayName: Krita (x64) 5.1.4
    DisplayVersion: 5.1.4.100
    ProductCode: Krita_x64
```

**Comment by denelon** [comment]
@borque
It looks like you made the most recent changes to Kitra.  Would you mind adding the appropriate "appsAndFeatures" entries for the earlier versions?

**Comment by mdanish-kh** [comment]
Fixed now after updating all versions to use marketing version and use AppsAndFeaturesEntries for DisplayVersion. @trparky Can you please confirm?
```pwsh
~ winget install KDE.Krita --version 5.1.1
Found Krita [KDE.Krita] Version 5.1.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.kde.org/stable/krita/5.1.1/krita-x64-5.1.1-setup.exe
  ██████████████████████████████   126 MB /  126 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
```pwsh
~ winget list krita
Name              Id        Version Available Source
----------------------------------------------------
Krita (x64) 5.1.1 KDE.Krita 5.1.1   5.1.4     winget
```
```pwsh
~ winget upgrade krita
Found Krita [KDE.Krita] Version 5.1.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.kde.org/stable/krita/5.1.4/krita-x64-5.1.4-setup.exe
  ██████████████████████████████   122 MB /  122 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
```pwsh
~ winget list krita
Name              Id        Version Source
-------------------------------------------
Krita (x64) 5.1.4 KDE.Krita 5.1.4   winget
```

**Comment by borque** [comment]
Hello @denelon !
Sorry for the delay, I am currently busy with other things. But as it stands now the suggested fixes were already applied by @mdanish-kh !?
If I can be of any further help here, let me know!

**Comment by mdanish-kh** [comment]
Close with reason: Resolved by adding DisplayVersion to every manifest;
