### ISSUE TITLE
[Package Issue]: Upgrading Microsoft.VCRedist.2013 will install new package instead of replacing old version

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#92396]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Side-By-Side installation.

### Brief description of your issue

Affects both Microsoft.VCRedist.2013.x64 and Microsoft.VCRedist.2013.x86

When trying to update Microsoft.VCRedist.2013 from 12.0.30501 to version 12.0.40664.0 using Winget 1.3 on Windows 10/11, the new one will be installed while the old one will remain installed as well

### Steps to reproduce

1- install Microsoft.VCRedist.2013 from 12.0.30501 (x64 for example)
2 - update Microsoft.VCRedist.2013

### Actual behavior

When upgrading, Microsoft.VCRedist.2013 version 12.0.40664.0 is installed and Microsoft.VCRedist.2013 version 12.0.30501.0 remains installed as well

### Expected behavior

Microsoft.VCRedist.2013 version 12.0.40664.0 should replace the package in version 12.0.30501.0

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1335
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

Related to
https://github.com/microsoft/winget-pkgs/issues/92211
https://github.com/microsoft/winget-pkgs/issues/27935

**Comment by stephengillie** [comment]
Could you run `winget list --name "Visual C++"`?

**Comment by ppvnf** [comment]
![Captura de tela 2022-12-28 200117](https://user-images.githubusercontent.com/73800734/209883021-ff50682e-1230-4979-90e9-fdc1ebddc386.png)

**Comment by lychichem** [comment]
Maybe you installed vcredist in different languages?

**Comment by ppvnf** [comment]
> Maybe you installed vcredist in different languages?

Maybe, I've tried uninstalling both versions, installing the old version and upgrading and I didn't face the problem again...

Thanks!

**Comment by ppvnf** [comment]
I figured out what happened. In step 2 instead of `winget update Microsoft.VCRedist.2013` I ran `winget install Microsoft.VCRedist.2013`. I guess there is some reason for MS to allow having two versions of Microsoft.VCRedist.2013
