### ISSUE TITLE
[Package Request]: Picocrypt

### ISSUE THREAD

**Issue by atilluF** [microsoft/winget-pkgs#92436]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: HACKERALERT
Publisher Url: https://github.com/HACKERALERT/Picocrypt
Package Name: Picocrypt
Description: A very small, very simple, yet very secure encryption tool.
Package Version: 1.31
Installer URL: https://github.com/HACKERALERT/Picocrypt/releases/download/1.31/Picocrypt.exe

Current Package Identifier (for new versions):

**Comment by rodrigoborgesdeoliveira** [comment]
Hi @atilluF, I can help you out on submitting Picocrypt as a new package. Do you know if it runs on x86 (32-bit) platforms?

**Comment by rodrigoborgesdeoliveira** [comment]
After submitting the new package, Picocrypt's executable unfortunately fails the _Installers scan test_ with a [Binary validation error](https://learn.microsoft.com/en-us/windows/package-manager/package/repository#binary-validation-error), meaning Picocrypt is probably being identified as a [Potentially Unwanted Application (PUA)](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/criteria?view=o365-worldwide#potentially-unwanted-application-pua), and thus it might not be allowed to be pushed to winget (maybe someone from Microsoft can assist on this).

**Comment by HACKERALERT** [comment]
Can we try again on the latest v1.32? I'm not familiar with winget so I wouldn't be of much use but perhaps the latest version will work. One question, if this version goes through successfully, does that mean that when I run `winget install picocrypt`, Picocrypt will be "installed" and appear in my start menu? I'm the developer of Picocrypt so feel free to let me know if there's anything I can do on my end :)

**Comment by mdanish-kh** [comment]
@HACKERALERT I've opened a PR for adding the package https://github.com/microsoft/winget-pkgs/pull/109575

> One question, if this version goes through successfully, does that mean that when I run `winget install picocrypt`, Picocrypt will be "installed" and appear in my start menu?

WinGet doesn't have the ability yet to add start menu entries. This feature request is being tracked at:
- https://github.com/microsoft/winget-cli/issues/2299

Upon installation, WinGet will register add the app to the PATH variable so it can be invoked through `picocrypt` in the terminal. It'll also add registry entries for the portable application so that the application is visible in Apps&Features / `appwiz.cpl`.

**Comment by HACKERALERT** [comment]
Thank you! I'm glad we can give it another go. It seems the PR got a "Validation-Executable-Error" which I don't know means what but hopefully it's not a big issue like the one in the first PR.

> WinGet doesn't have the ability yet to add start menu entries.

I see, thanks for the information. If this becomes possible in the future, we can always add it then.

**Comment by HACKERALERT** [comment]
Ah, this seems a bit too complicated to setup and I think I'll pass for now. Maybe when winget becomes more developed and easy to use for portable packages, I will consider it again. For now though, a standard installer will probably suffice.

Thank you guys for all of your help!

@mdanish-kh, you can close the pull request now. @atilluF, you can close this issue now if you like. Of course, you can leave it open if other people want to give it a go.
