### ISSUE TITLE
[Package Issue]: Bitwarden.Bitwarden

### ISSUE THREAD

**Issue by FaserF** [microsoft/winget-pkgs#92828]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I am unable to install Bitwarden (other Programs work, but this specific one brings issues for me). Winget says it is already installed, but it definitly is not. If I run the installer in a user context with no admin permissions it works and brings me a admin pop up. But I got this issue now on multiple clients while running in the system context.

The Bitwarden installations worked fine for me with the 2022.10.X versions. I think afterwards the issues started.

I had written about the issue here too:
https://github.com/Romanitho/Winget-Install/issues/71

I have also tried it with --scope machine with no success.

### Steps to reproduce

Deploy Bitwarden via winget with a user with administrator permissions or with a system account (Intune for example). Winget will say it is installed, but it definitly is not.

### Actual behavior

Winget detects the app to be installed even through it is not. The installation directorys are not there and in the user context with 
`winget list Bitwarden`
it does not find anything. Reinstalling does not work as winget says it is already installed. When I run the command
`winget uninstall Bitwarden.Bitwarden`
it tries to uninstall it, but as it is not really installed it gets an error
```
An unexpected error occurred while executing the command: 
0x800401f5 : Application not found.
```
and afterwards still says it is installed.

### Expected behavior

Bitwarden installer should throw an error if it does not work, but winget definitly should not say it is installed when it is not. 

### Environment

```shell
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.963
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
>  But I got this issue now on multiple clients while running in the system context.

Winget does not support installing applications under the system context. Please try using a standard user or admin context

**Comment by FaserF** [comment]
I had also tried it with a admin user where it didnt work. Also it works just fine for every other application, just for Bitwarden it does not.

**Comment by krystofkrticka** [comment]
Some applications don't support systemwide installation. So that might be your issue with Bitwarden

**Comment by krystofkrticka** [comment]
> Some applications don't support systemwide installation. So that might be your issue with Bitwarden.

OK I just looked on bitwarden installer and it supports systemwide install but parameter might be required to start it.

**Comment by krystofkrticka** [comment]
OK that's weird I just tried to install Bitwarden in clean VM using machine scope in winget and it installed system wide after checking it's manifest.

**Comment by denelon** [comment]
Some installers prohibit installing in administrator mode. That may be the case here. Try installing as a "user" with machine scope. If it works under that context and fails under admin, then the "prohibitsElevation" should be added to the manifest to give the warning.

Note: we will have to do a manual review to approve it in that case while we work through some validation logic to support these scenarios. It's the most common reason Spotify.Spotify fails.

**Comment by FaserF** [comment]
Okay thanks for your information. For now we are deploying it in the user context and it works. So we have a workaround for now.

**Comment by KnifMelti** [comment]
In **SYSTEM** context you must **--override** this install with `/allusers /S`, we deploy it like that with [Winget-Install](https://github.com/Romanitho/Winget-Install#use-winget-native-parameters)

**Comment by MaanuelMM** [comment]
I was wondering if this has anything to do with #133334, a fix I made to solve a problem I was having installing Bitwarden with `--scope machine` as it always ended up being a user-level install instead of a system-level install.
