### ISSUE TITLE
[Package Issue]: Sigrok.Pulseview MSVCR100.dll missing error

### ISSUE THREAD

**Issue by brainstorm** [microsoft/winget-pkgs#92844]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

After installing and running PulseView, I'm greeted with this DLL error:

![pulseview_dll_error](https://user-images.githubusercontent.com/175587/210443184-00e88bdb-9602-44e3-8714-d5b5fa52deb7.png)

I have both reinstalled the app and it does not fix the problem and [followed the standard microsoft troubleshooting guide for this issue](https://answers.microsoft.com/en-us/windows/forum/all/missing-msvcr100dll/a9fb2f07-417f-4a54-a1c8-1af38586f951) with no success so far.

Spawning Pulseview from WSL works flawlessly though (apt-get install pulseview && pulseview) 🤷🏻‍♂️ 

### Steps to reproduce

1. `winget install pulseview`
2. Run pulseview

### Actual behavior

MSVCR100.dll missing error shows up and pulseview does not show up.

### Expected behavior

The package should work right after winget installing it on Windows 11.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```


### Screenshots and Logs

_No response_

**Comment by denelon** [comment]
My best guess is the package has a dependency on one of the Visual C runtimes.

Do you have any of the "Microsoft Visual C++" redistributables installed?
`winget list visual` should have one or more entries if you have it installed.

I have:
```text
winget list visual
Name                                                               Id                                     Version        Available     Source
---------------------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.34.31823 Microsoft.VCRedist.2015+.x86           14.34.31823.3  14.34.31931.0 winget
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.34.31823 Microsoft.VCRedist.2015+.x64           14.34.31823.3  14.34.31931.0 winget
```

**Comment by brainstorm** [comment]
Seems like I have a broad selection:

```
Name                                              Id                           Version        Available     Source
------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2019 Redistributable (… Microsoft.VCRedist.2015+.x64 14.29.30133.0  14.34.31931.0 winget
Microsoft Visual C++ 2015-2022 Redistributable (… Microsoft.VCRedist.2015+.x86 14.32.31326.0  14.34.31931.0 winget
Microsoft Visual C++ 2012 Redistributable (x64) … Microsoft.VCRedist.2012.x64  11.0.61030.0                 winget
Microsoft Visual C++ 2010  x86 Redistributable -… Microsoft.VCRedist.2010.x86  10.0.40219                   winget
Microsoft Visual C++ 2008 Redistributable - x64 … Microsoft.VCRedist.2008.x64  9.0.30729.6161               winget
Microsoft Visual C++ 2008 Redistributable - x86 … Microsoft.VCRedist.2008.x86  9.0.30729.6161               winget
```

... as other programs require different versions of them, I guess.

**Comment by stoune** [comment]
Installation of VC++ 2010 x64 Runtime fixed issues. It should be included into installer.
`winget install --id=Microsoft.VCRedist.2010.x64  -e`

**Comment by brainstorm** [comment]
Fantastic! Thanks @stoune, that worked for me.

Shall I close this issue or wait until this VCRedist is included into the installer (upstream or over here)?

**Comment by EDsteve** [comment]
> Installation of VC++ 2010 x64 Runtime fixed issues. It should be included into installer. `winget install --id=Microsoft.VCRedist.2010.x64 -e`

I am getting this message when i try that command:
"Found an existing package already installed. Trying to upgrade the installed package...
No applicable upgrade found."

What else can i try to dp?

This is my winget list visual:
```
`C:\Users\edsteve>winget list visual
Name                                          Id                                     Version        Available    Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x64            12.0.40664.0                winget
Microsoft Visual C++ 2015-2022 Redistributab… Microsoft.VCRedist.2015+.x86           14.34.31931.0               winget
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x86            12.0.40664.0                winget
Microsoft Visual C++ 2015-2022 Redistributab… Microsoft.VCRedist.2015+.x64           14.34.31931.0               winget
Microsoft Visual C++ 2010  x86 Redistributab… Microsoft.VCRedist.2010.x86            10.0.40219                  winget
Visual Studio Build Tools 2019                Microsoft.VisualStudio.2019.BuildTools 16.11.23       16.11.25     winget
Microsoft Visual Studio Code (User)           Microsoft.VisualStudioCode             1.77.1                      winget
Microsoft Visual Studio Installer             {6F320B93-EE3C-4826-85E0-ADF79F8D4C61} 2.11.69.53063
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x64            12.0.30501.0   12.0.40664.0 winget
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x86            12.0.30501.0   12.0.40664.0 winget
Winamp                                        Winamp.Winamp                          > 5.91.0.10029              winget
`
```

**Comment by elfmimi** [comment]
@EDsteve That seems to be yet another bug in winget. See https://github.com/microsoft/winget-pkgs/issues/85478

**Comment by haywardt** [comment]
still happening

**Comment by Gatodillo** [comment]
Some enterprise users are receiving the notice that this 2010 package is obsolete and is going to be automatically unistalled from their PCs. Also, after an automatic update, PulseView stopped  working on my personal PC.

Is a good idea to install this old/unsecure package?

https://community.sap.com/t5/technology-q-a/obsolete-software-microsoft-visual-c-2010-redistributable-package-detected/qaq-p/12686371
