### ISSUE TITLE
[Package Issue]: PurpleI2P.i2pd

### ISSUE THREAD

**Issue by et9235** [microsoft/winget-pkgs#93176]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Attempted this specific package several times, each time returning the same hash mismatch error.

### Steps to reproduce

1. open powershell as admin
2. run `winget upgrade PurpleI2P.i2pd`

### Actual behavior

winget returns `Installer hash does not match; this cannot be overridden when running as admin`

### Expected behavior

I expect the hash to be correct and the installation to proceed...
I don't think it's my network as the file has been re-downloaded several times.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/66205695/210940788-9824d179-827c-43ab-ad12-b344109ba5a2.png)

**Comment by stephengillie** [comment]
This is related to
* https://github.com/microsoft/winget-cli/issues/2666
