### ISSUE TITLE
[Package Request]: One Tagger

### ISSUE THREAD

**Issue by jnm2** [microsoft/winget-pkgs#93208]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:
Publisher Url: https://onetagger.github.io
Package Name: OneTagger
Description: Music tagger for Windows, MacOS and Linux with Beatport, Discogs, Musicbrainz, Spotify, Traxsource and many other platforms support.
Package Version: 1.5.1
Installer URL: https://github.com/Marekkon5/onetagger/releases/download/1.5.1/OneTagger-windows-setup.exe

Current Package Identifier (for new versions):

**Comment by FernandoNunes** [comment]
Hi @jnm2,

I've submitted a Pull Request that adds OneTagger.OneTagger Package to winget-pkgs.
All automated checks passed, now requiring moderator approval.

The PR is: https://github.com/microsoft/winget-pkgs/pull/93796

**Comment by FernandoNunes** [comment]
This PR can be closed, OneTagger package has been added.

**Comment by mdanish-kh** [comment]
Close with reason: Package added in #93796;
