### ISSUE TITLE
[Package Issue]: Logitech.GHUB

### ISSUE THREAD

**Issue by int3l** [microsoft/winget-pkgs#93299]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Upon installation or upgrade of the `Logitech.GHUB` package, the install process fails with an error message, because of incorrect exit code of the installer or some kind of timeout limit.

### Steps to reproduce

```terminal
winget install -e --id Logitech.GHUB
```

### Actual behavior

Installation process is completed successfully, because the Logitech.GHUB software automatically pops up, but for some reason the `winget` cli reports an error:

```terminal
Found Logitech G HUB [Logitech.GHUB] Version 2022.12.348746
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 15
```

### Expected behavior

Successful installation, upgrade or uninstall process without errors.

### Environment

```shell
winget --info
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

### Screenshots and Logs

I am not sure if the fault is on the `winget` side, but It seems more appropriate to report it here, because I don't know the official Logitech channel, where I can report the same problem. Please let me know, where I can forward the issue, if there is nothing wrong on the `winget` side.

Thanks in advance for your time!

**Comment by denelon** [comment]
I'm not sure what exit code 15 means from Logitech.GHUB. Maybe there is a way to report an issue on their site? You can run `winget show Logitech.GHUB` to get some URLs to try:

```
winget show Logitech.GHUB
Found Logitech G HUB [Logitech.GHUB]
Version: 2022.12.348746
Publisher: Logitech
Publisher Url: https://www.logitechg.com/en-us/innovation/g-hub.html.html
Author: Logitech
Moniker: lghub
Description: Logitech G HUB Software lets you customize Logitech G gaming devices.
Homepage: https://support.logi.com/hc/en-us/articles/360025298133
License: Proprietary
Privacy Url: https://www.logitechg.com/en-us/legal/web-privacy-policy.html
Copyright: Copyright (c) 2022 Logitech. All rights reserved
Tags:
  driver
  gaming
  ghub
  headset
  hub
  keyboard
  lghub
  logitech
  mouse
  utility
Installer:
  Installer Type: exe
  Installer Url: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  Installer SHA256: 234be8544a1cacdaadccd0718d14be477c861e38a1a8cf06ea5669ea5a472fb7
```

**Comment by int3l** [comment]
Thank you very much for your time, I tried to report the issue to the publisher via the official support channel in their website.
