### ISSUE TITLE
[Package Issue]: VinaySajip.PythonLauncher

### ISSUE THREAD

**Issue by NJT145** [microsoft/winget-pkgs#93309]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

This is a dead and deprecated package and should warn users at its description.
Look at that: [https://bitbucket.org/vinay.sajip/pylauncher/issues/14/installer-forgot-to-add-pyexe-dir-to-path](https://bitbucket.org/vinay.sajip/pylauncher/issues/14/installer-forgot-to-add-pyexe-dir-to-path)

### Steps to reproduce

look at description...

### Actual behavior

There is no info at package description. The creator of Python Launcher says that it is deprecated because CPython installer contains it in itself.

### Expected behavior

It should say "[DEPRECATED]" at the beginning of description or give an information for that deprecation issue.

### Environment

```shell
[winget --info]
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
I guess we can use `InstallationNotes` manifest field to warn user of the deprecation post-install. Can you suggest a suitable message for this scenario?

**Comment by Trenly** [comment]
@mdanish-kh - I think any deprecation message would be fine, if you still wanted to take care of this

**Comment by mdanish-kh** [comment]
- #151997

Couldn't find an official deprecation announcement in the repo. Went with more or less the same words the developer of the package used in [bitbucket.org/vinay.sajip/pylauncher/issues/14/installer-forgot-to-add-pyexe-dir-to-path](https://bitbucket.org/vinay.sajip/pylauncher/issues/14/installer-forgot-to-add-pyexe-dir-to-path)
