### ISSUE TITLE
[Package Issue]: Microsoft.WindowsTerminal

### ISSUE THREAD

**Issue by NJT145** [microsoft/winget-pkgs#93308]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

The package Microsoft.WindowsTerminal have no update on winget, but MSStore says there is an update for it.
Are there any thing that blocks to get its latest version on winget?

### Steps to reproduce

Code for upgrade: `winget upgrade --id=Microsoft.WindowsTerminal`
Result: `No applicable update found.`
Checked for available versions on winget, and that is the latest.
But MSStore says there is an update for it.
(After I installed Microsoft.WindowsTerminal, it is visible at MSStore as installed app...)

### Actual behavior

winget version cannot get the latest one, but MSStore does? Or there is a problem about its version number?

### Expected behavior

winget upgrade should upgrade Microsoft.WindowsTerminal to its latest release, so that MSStore wont notify for an available upgrade.

### Environment

```shell
[winget --info]
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
Are you running on Windows 10 or Windows 11?

We have an issue with the latest version only supporting Windows 11 and a related bug:
* https://github.com/microsoft/winget-cli/issues/2134
