### ISSUE TITLE
[Package Issue]: Canonical.Ubuntu

### ISSUE THREAD

**Issue by EduardGomezEscandell** [microsoft/winget-pkgs#93385]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

This package is deprecated.

Ubuntu on Windows (Canonical.Ubuntu) was removed from the store a while ago and is no longer maintained. Canonical's flagship on WSL is now "Ubuntu" (id: 9PDXGNCFSCZV). This makes this package effectively deprecated.

The main inconvenience is that `winget install --name Ubuntu` now shows the two packages, and it is not immediately apparent to users which one to choose. And using `-e` installs the deprecated one.

I propose removing the package from winget altogether.

### Steps to reproduce

`winget install --name Ubuntu -e`

### Actual behavior

The deprecated app is installed

### Expected behavior

The up-to-date app should be installed

### Environment

```shell
> winget --info
Administrador de paquetes de Windows v1.3.2691
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22623.1095
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.18.2691.0

Registros: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by rodrigoborgesdeoliveira** [comment]
@ItzLevvie2 @Trenly, when running `winget search Ubuntu`, it shows two IDs for version `2004.2021.825.0`. [One](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004.2021.825.0) in Ubuntu's root folder and [another](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004/2004.2021.825.0) under the 2004 folder (similar to the other versions).
![image](https://user-images.githubusercontent.com/12696894/212444159-ea6dd58d-2210-484f-b10b-d82637d0de3c.png)

What would make more sense: 1. replace the [one](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004.2021.825.0) in the root folder with version 2204 or 2. remove it in favor of keeping only the [one](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004/2004.2021.825.0) inside the 2004 version?

**Comment by Trenly** [comment]
> @ItzLevvie2 @Trenly, when running `winget search Ubuntu`, it shows two IDs for version `2004.2021.825.0`. [One](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004.2021.825.0) in Ubuntu's root folder and [another](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004/2004.2021.825.0) under the 2004 folder (similar to the other versions). ![image](https://user-images.githubusercontent.com/12696894/212444159-ea6dd58d-2210-484f-b10b-d82637d0de3c.png)
> 
> What would make more sense: 1. replace the [one](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004.2021.825.0) in the root folder with version 2204 or 2. remove it in favor of keeping only the [one](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Canonical/Ubuntu/2004/2004.2021.825.0) inside the 2004 version?

I would keep only the one in 2004. Since that is representative of Ubuntu 20.04
