### ISSUE TITLE
Installing Docker.DockerDesktop fails with exit code: 4294967291

### ISSUE THREAD

**Issue by stmax82** [microsoft/winget-pkgs#93495]
I'm getting the following error when trying to install (or upgrade) Docker.DockerDesktop.
Manual installation works.

Account is a normal user.
When installing programs the "Do you want to allow this app to make changes..." dialog pops up where I enter the credentials of an admin account.

Appending --log foo.log does not create a log file. Any way to diagnose what the problem might be?

![image](https://user-images.githubusercontent.com/6381927/211797335-9fd761a4-3e63-4910-b008-f0171cc43a15.png)

```
PS C:\Users\...> winget install Docker.DockerDesktop
Found Docker Desktop [Docker.DockerDesktop] Version 4.15.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 4294967291
```

**Comment by stephengillie** [comment]
Unfortunately, I couldn't duplicate the error in a VM and it installed normally. Could you install again with `--verbose-logs` added, and paste the log here? The log location can be found under `winget --info`.

**Comment by stmax82** [comment]
The end of the verbose log file says:
![image](https://user-images.githubusercontent.com/6381927/212295298-73905f2e-1bca-4c34-9464-a41f05cfbbc0.png)

I tried to manually start the DockerDesktopInstaller.exe with the "install" parameter, which results in the same error:
![image](https://user-images.githubusercontent.com/6381927/212294424-8fb980ca-eec3-48a1-8868-4eac0cea0c27.png)

I noticed that moving the DockerDesktopInstaller.exe file to another directory fixes the problem:
![image](https://user-images.githubusercontent.com/6381927/212296184-51cd5392-d89b-4629-ab41-a3f20ed7290f.png)

Not sure what's causing this but I guess it's a Docker problem and not a winget problem?

**Comment by trynn** [comment]
+1 from me.
Clean W11 setup. `PS $ winget install Docker.DockerDesktop`

**Comment by AlexDe74** [comment]
same issue with https://github.com/microsoft/winget-cli/issues/2740

Give the temporary folder with Docker Installation the admin permissions and start winget again - it will install

**Comment by MatLudke** [comment]
any solution. I got the same error after reinstalling docker.

**Comment by JarlamSierra** [comment]
Run Powershell with Administrator permission... Every time when you need to install any app, please use Admin mode.

**Comment by AlexDe74** [comment]
> any solution? I got the same error after trying to reinstalling docker.

Yes. Give v1.5.441-preview version of winget a try. It works there (commit https://github.com/microsoft/winget-cli/commit/6247fce7facd3945a5569e667333463a2738f1b8)

**Comment by bigteejay** [comment]
> No packages were found among the working sources.

I initially received the same error, however, installing by id starts...

```
PS C:\Users\User> winget search docker
Name                      Id                             Version     Match           Source
--------------------------------------------------------------------------------------------
Dockerun                  9NVBZPBTK78W                   Unknown                     msstore
Docker Desktop            Docker.DockerDesktop           4.19.0      Moniker: docker winget
Podman                    RedHat.Podman                  4.5.0       Tag: docker     winget
```

```
PS C:\Users\User> winget install Docker.DockerDesktop
Found Docker Desktop [Docker.DockerDesktop] Version 4.19.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
```

...we'll see how it goes/finishes ;-)

**Comment by jo-chemla** [comment]
Easy fix shared on [reddit](https://www.reddit.com/r/docker/comments/1ss9ef4/docker_desktop_installation_error_problem/) for anyone stumbling on this thread: 
1. Delete `C:\ProgramData\DockerDesktop` if present
2. Run Docker installer as administrator (right click on exe, “Run as administrator”), `winget install Docker.DockerDesktop`
3. Installer should work fine
