### ISSUE TITLE
P.S.A Publishing and Validation are having issues

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#93536]
We're aware publishing and validation are having a high failure rate.

We're looking into the Issue and will update as we make progress.

**Comment by stephengillie** [comment]
We've identified and disabled the failing regions, so validation and publishing can continue. As soon as the issue is resolved, we will bring the other regions back online.

**Comment by stephengillie** [comment]
All regions have been restored and are online in our normal operating configuration.
