### ISSUE TITLE
[Package Issue]: MarekJasinski.FreeCommanderXE

### ISSUE THREAD

**Issue by p-rogalski** [microsoft/winget-pkgs#93603]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Latest winget version: 20.0.810

Latest website version: 20.0.880

The winget version is two years old.

### Steps to reproduce

-

### Actual behavior

-

### Expected behavior

-

### Environment

```shell
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.963
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by stephengillie** [comment]
Winget has `version 20.0.810` while the [publisher's website](https://freecommander.com/en/downloads/) has `build 880` available. 
```
PS C:\> winget search MarekJasinski.FreeCommanderXE
Name             Id                            Version  Source
---------------------------------------------------------------
FreeCommander XE MarekJasinski.FreeCommanderXE 20.0.810 winget
```
- Would `build 880` be `version 20.0.880`?
- The current installer is MSI, but their website only has ZIP downloads. Is the newer version available as MSI?

**Comment by p-rogalski** [comment]
- `build 880` has version `2023.0.0.880`
- The ZIP archive contains only a single file (an EXE installer)

I could not find other download options.

**Comment by borque** [comment]
Adresses by PR #95311 (once ZIP-manifests are merged)

**Comment by borque** [comment]
Close with reason: requested update is PR PR https://github.com/microsoft/winget-pkgs/pull/95311
@stephengillie , @mdanish-kh can someone with mod-rights close this issue if you agree with me?

**Comment by mdanish-kh** [comment]
Close with reason: Package added in #95311. Thanks borque;
