### ISSUE TITLE
[Package Request]: VisualCost

### ISSUE THREAD

**Issue by infolocalret** [microsoft/winget-pkgs#93650]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Fundación Instituto de Tecnología de la Construcción de Cataluña – ITeC
Publisher Url: https://itec.es/soporte/descargas/visualcost/
Package Name: VisualCost
Description: VisualCost es una herramienta gratuita que ofrece el ITeC al sector de la construcción para facilitar a todos los profesionales y empresas el acceso a la lectura de mediciones y presupuestos elaborados en BIM.
Package Version: 5.8.754
Installer URL:

Current Package Identifier (for new versions):

**Comment by FernandoNunes** [comment]
Hi @infolocalret,

The package you requested is behind a login page. Can you provide a direct link for the download package ?

**Comment by infolocalret** [comment]
No, no está disponible, solo subscripción.

Gracias

De: Fernando Nunes ***@***.***>
Enviado el: domingo, 15 de enero de 2023 15:28
Para: microsoft/winget-pkgs ***@***.***>
CC: Informatica Localret ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoft/winget-pkgs] [Package Request]: VisualCost (Issue #93650)


[Correu Extern]



Hi @infolocalret<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finfolocalret&data=05%7C01%7Cjalache%40localret.cat%7Cc9fe0c656d5b4d0d867e08daf704a9cd%7Cf00ecc385c674fec9c786f7047a88693%7C0%7C0%7C638093896661812429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lyBjVJ34%2F15yE9eXQwNiPbkCb5YWpy7Ui%2B3tmkz3DxI%3D&reserved=0>,

The package you requested is behind a login page. Can you provide a direct link for the download package ?

-

**Comment by FernandoNunes** [comment]
@stephengillie  This package is available only on paid subscription page as confirmed by submitter. This can probably be close.

**Comment by infolocalret** [comment]
No, este producto es gratuito. Pero el fabricante pide el registro para descargarlo.

Descarga VisualCost - ITeC - Instituto de Tecnología de la Construcción<https://itec.es/soporte/descargas/visualcost/>

***@***.***




De: Fernando Nunes ***@***.***>
Enviado el: sábado, 21 de enero de 2023 16:16
Para: microsoft/winget-pkgs ***@***.***>
CC: Informatica Localret ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoft/winget-pkgs] [Package Request]: VisualCost (Issue #93650)


[Correu Extern]



@stephengillie<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstephengillie&data=05%7C01%7Cjalache%40localret.cat%7C6677b07fb09541f281e108dafbc25a9a%7Cf00ecc385c674fec9c786f7047a88693%7C0%7C0%7C638099109410554061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8AaAeY%2FsrA%2Ff76SOFSSa1kf4I3NZyAsB0eYFLwN2rE4%3D&reserved=0> This package is available only on paid subscription page as confirmed by submitter. This can probably be close.

-

**Comment by stephengillie** [comment]
> No, este producto es gratuito. Pero el fabricante pide el registro para descargarlo.

The publisher's website supports this - the package is free, if the user is registered & signed in:
> Para obtener gratuitamente el programa y los ejemplos de aplicación es necesario estar registrado en la web del ITeC.

Winget works best with unauthenticated downloads. Packages which aren't freely available for download without authentication probably won't install well through Winget.
