### ISSUE TITLE
Not able to found roblox with cli

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#94013]
### Brief description of your issue

Not able to found roblox with cli

### Steps to reproduce

winget search roblox 

winget search 9NBLGGGZM6WM

### Expected behavior

able to install roblox with winget cli

### Actual behavior

No package found matching input criteria 

### Environment

```shell
winget --info
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by khewweifeng** [comment]
> @stephengille - Roblox cannot be supported.
> 
> See [#47480 (review)](https://github.com/microsoft/winget-pkgs/pull/47480#pullrequestreview-888653322) and the littany of failed PRs - https://github.com/microsoft/winget-pkgs/issues?q=Roblox
> 
> > https://www.xbox.com/en-us/games/store/roblox/9nblgggzm6wm
> 
> Seems like this is a request for adding an Xbox store source, not just msstore

Another link but the id is the same - https://apps.microsoft.com/store/detail/roblox/9NBLGGGZM6WM

**Comment by rollingmoai** [comment]
If you are eager to use Winget, try using https://github.com/pizzaboxer/bloxstrap instead, which is available here:
```	
winget install bloxstrap
```
