### ISSUE TITLE
[Package Issue]: Microsoft.PCManager

### ISSUE THREAD

**Issue by xIUPITERx** [microsoft/winget-pkgs#94127]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I came across the following package (Microsoft.PCManager), but the download URL (``https://pcmanager.officeplus.cn/mvp/10000/26026/MSPCManagerSetup.exe ... ``) seems to be anything but official.

### Steps to reproduce

search for the PC Manager package 

### Actual behavior

should show legit URL (https://pcmanager-en.microsoft.com/)

### Expected behavior

shows an untrustworthy URL (https://pcmanager.officeplus.cn/mvp/10000/26026/MSPCManagerSetup.exe?sv=2021-06-08&se=2023-06-26T02%3A10%3A43Z&sr=c&sp=rwdl&sig=pDOh8oxm8ifT6anw8tZJNZhQ0WAXW279Le%2BA3rMFM6w%3D)

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

### Screenshots and Logs

> PS C:\Users\USER> winget show Microsoft.PCManager
Found Microsoft PC Manager(Beta) [Microsoft.PCManager]
Version: 1.2.6.4
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Publisher Support Url: https://support.microsoft.com/
Author: Microsoft Corporation
Description: Microsoft PC manager, a good way to protect your personal computer and optimize performance, provides PC cleanup, antivirus and Windows update, making your computer safe and secure!
Homepage: https://pcmanager-en.microsoft.com
License: Freeware
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks
Installer:
  Type: nullsoft
  Download Url: https://pcmanager.officeplus.cn/mvp/10000/26026/MSPCManagerSetup.exe?sv=2021-06-08&se=2023-06-26T02%3A10%3A43Z&sr=c&sp=rwdl&sig=pDOh8oxm8ifT6anw8tZJNZhQ0WAXW279Le%2BA3rMFM6w%3D
  SHA256: 12b4cb9589255f51daa31be099e9a70cd7de59e0e8931bf2510374fc49bada69
  Release Date: 2022-12-28

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/87480#issuecomment-1303087253

This was identified as an acceptable URL based on the "aka.ms" URL provided in the PR:
* https://github.com/microsoft/winget-pkgs/pull/87480 

A waiver was granted for that URL.

**Comment by xIUPITERx** [comment]
What exactly does that mean?
The URL is not one from microsoft itself, is it?

**Comment by denelon** [comment]
@SpecterShell, 

Can you share how you got to the URL for this package?

**Comment by xIUPITERx** [comment]
https://aka.ms/PCManager500000
Just wondering, why this link wasn't used, but I don't really know how Winget packages work

**Comment by denelon** [comment]
Generally, we prefer using URLs coming from the "official" site. In some cases, they are redirects, but we understand in many cases the underlying URL may change due to CDN modifications or other changes intentionally performed by ISVs.

**Comment by SpecterShell** [comment]
The URLs prior to 1.2.6.4 came from <https://aka.ms/PCManagerUpgrade10000>, which is obtained from their API (<https://pcmanager.microsoft.com/config/api/AppConfig>).
The URLs after that should came from <https://aka.ms/PCManager10000>, which can be found in <https://pcmanager.microsoft.com/en>.

**Comment by xIUPITERx** [comment]
So ``officeplus.cn`` is an official microsoft webside?

**Comment by SpecterShell** [comment]
Both OfficePLUS and PC Manager come from Microsoft China.

**Comment by LiCaoZ** [comment]
> So `officeplus.cn` is an official microsoft website?

Yes, it is owned by Microsoft China, and you can get the latest download link by `curl aka.ms/PCManager10000 -i` like `pcmanager.officeplus.cn/mvp/xxx`.

Due to legal reasons, PC Manager's official English website provides the `aka.ms/PCManager500000`, the 1.2.4 version. For more information, you can also contact the PC Manager's Operational team through the Discord invite link at the bottom of the PC Manager's English website.

Thank you for experiencing PC Manager. If you face any issue, you can submit it at the in-box feedback function or the Discord server above.
