### ISSUE TITLE
winget upgrade fails to list correct version and reinstalls even if latest version is installed

### ISSUE THREAD

**Issue by AbhishekAlate** [microsoft/winget-pkgs#94165]
### Brief description of your issue

Incorrect version of the product is reported on winget upgrade CLI and winget upgrade --id Amazon.WorkspacesClient reinstalls the latest version.

I see the right version in Apps:
![Installed version](https://user-images.githubusercontent.com/16275775/213267158-10d348ae-4684-40cd-8328-82a12137b3e9.png)

Example:
Amazon WorkSpaces                                                  Amazon.WorkspacesClient                  > 3.1.10         5.6.2.3417       winget

### Steps to reproduce

1. Install older version from https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
2. Run `winget upgrade` to lilst the packages, it'll show the incorrect version
3. Run `winget upgrade --id Amazon.WorkspacesClient`

### Expected behavior

It should not reinstall version 5.6.2.

### Actual behavior

It reinstalls the latest version.

### Environment

```shell
winget --info
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1455
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by AbhishekAlate** [comment]
Users are not facing this issue anymore, thank you for the quick response, I really appreciate it.

**Comment by AlejoMendoza87** [comment]
Still happening to me
![image](https://user-images.githubusercontent.com/40187063/218484793-63257084-521a-49ab-bea8-c5408c5a47f3.png)
![image](https://user-images.githubusercontent.com/40187063/218484941-2ff1e027-07b1-45cc-b598-211377779637.png)

**Comment by denelon** [comment]
What is displayed in Windows Apps & Features?

**Comment by mdanish-kh** [comment]
This is again the same case where the newer version is missing ARP Entries. I've opened a PR to resolve this issue.

**Comment by AlejoMendoza87** [comment]
It's working now, let's hope it doesn't break in the next update.
