### ISSUE TITLE
[Package Issue]: Oracle.VirtualBox - winget is trying to upgrade VirtualBox v6 to v7

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#94420]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

the v6 and v7 branches of the VirtualBox are supposed to be maintained separately, but winget is trying to upgrade VirtualBox v6 to v7

https://download.virtualbox.org/virtualbox/

**The UserManual.pdf file even says this (for both v6 and v7 cases, but seems v7 really dropped them):**

> Platforms With Limited Support. These legacy guest OS platforms can be used with
> Oracle VM VirtualBox, but only qualify for best effort support. Therefore, resolution of
> customer issues is not guaranteed. See chapter 4.1, Supported Guest Operating Systems,
> page 68.

https://www.reddit.com/r/virtualbox/comments/10hj4b4/is_there_a_port_of_xp_3d_acceleration_on_70/
v7.0 [...] doesn't support 3D acceleration on Windows XP

https://forums.virtualbox.org/viewtopic.php?t=106674
Windows XP 3D acceleration support is dropped in newer VirtualBox versions

### Steps to reproduce

- install latest VirtualBox v6, install a Windows XP VM 
- run winget upgrade
- find out that winget is trying to do a major version upgrade of VirtualBox, v6 -> v7
- after the upgrade the VM doesn't work properly (or at all)

### Actual behavior

winget tries to nuke VirtualBox v6 and install v7 in its place.

### Expected behavior

keep VirtualBox upgrades constrained to the same major version upgrade paths as the already installed version.
- v6 to v6.* upgrades
- v7 to v7.* upgrades

### Environment
env not relevant - this is a WinGet / manifest issue

**Comment by stephengillie** [comment]
Should these be separated into e.g. `Oracle.VirtualBox.6` and `Oracle.VirtualBox.7`?

**Comment by R-Adrian** [comment]
The OS on which winget and VirtualBox is running is Windows 10 Pro so a `MinimumOSVersion` filter would not work because that is already at 10.0.19045.2546 currently.
(Win 10 Pro 22H2, with 2023-01 preview KB patches from last week installed - January 19, 2023 — KB5019275)

The Windows XP OS inside the virtual machine does not even know what winget is, or cares about it, but we need it to drive some serial interfaces for troubleshooting industrial machinery.

What would be needed is something like a "minimum major version already installed" filter... if such a thing exists for winget.

**Comment by R-Adrian** [comment]
i think it might be simpler to just split the current Oracle.VirtualBox package into two packages with separate manifests ...
let's call them (probably)  `Oracle.VirtualBox-v6` and `Oracle.VirtualBox-v7`

**Comment by stephengillie** [comment]
Can v6 and v7 be installed side-by-side? I was originally going to suggest this, with `Oracle.VirtualBox.6` and `Oracle.VirtualBox.7` to match naming conventions. But this will make Winget assume the packages can be installed side-by-side, and might cause unintended behavior if they can't. For instance, installing the v7 after the v6 might cause the v7 installer to upgrade the v6 install, possibly orphaning registry data and causing an "Upgrade always available" situation for the v6 install.

**Comment by Trenly** [comment]
> What would be needed for winget is something like a "minimum major version of the target package that is already installed" filter... if such a thing exists.

This sounds like Package Pinning, which should be part of the 1.5 client release. See microsoft/winget-cli#476

**Comment by R-Adrian** [comment]
> > What would be needed for winget is something like a "minimum major version of the target package that is already installed" filter... if such a thing exists.
> 
> This sounds like Package Pinning, which should be part of the 1.5 client release. See [microsoft/winget-cli#476](https://github.com/microsoft/winget-cli/issues/476)

yay, it most certainly looks like it is.

**Comment by R-Adrian** [comment]
> Can v6 and v7 be installed side-by-side? 

VirtualBox was not designed to be a multi-version install.
https://forums.virtualbox.org/viewtopic.php?f=8&t=97283

**Comment by R-Adrian** [comment]
update:  seems that https://download.virtualbox.org/virtualbox/LATEST-STABLE.TXT has been modified, now it has a timestamp of `26-Jan-2023 16:06`  and this time it points to version 7.0.6 as "stable", even if it is not working properly with old operating systems like Windows XP.

**Comment by IlgazC** [comment]
Now a similar issue exist with VirtualBox 7.1.x which is manifests/o/Oracle/VirtualBox/7.1.0 , 7.1.0 isn't suggested to existing 7.0.x users and winget tried to upgrade my 7.0.x release to 7.1.x . 7.1 is a major upgrade with some yet unstable/untested enough changes. IMHO, the maintainer(s) should have waited for VirtualBox maintainers/Oracle to officially announce/add it to their update system.

**Comment by R-Adrian** [comment]
> Now a similar issue exist with VirtualBox 7.1.x which is manifests/o/Oracle/VirtualBox/7.1.0 , 7.1.0 isn't suggested to existing 7.0.x users and winget tried to upgrade my 7.0.x release to 7.1.x . 7.1 is a major upgrade with some yet unstable/untested enough changes. IMHO, the maintainer(s) should have waited for VirtualBox maintainers/Oracle to officially announce/add it to their update system.

according to 
https://download.virtualbox.org/virtualbox/LATEST-STABLE.TXT

**the stable version is currently 7.0.20 so that means we have another case of WinGet upgrading a stable software to a version still being tested. Even if it is pushed on the front page of the VirtualBox site that does not mean it should be used for upgrades yet.**


That being said... i will massively edit my first post in the issue description - VirtualBox 7.0 works acceptably with my XP VMs - though i cannot quite consider it fully there yet... quite a few times i had to troubleshoot some weird issues with it running XP and i still cannot figure it out why it broke. I had to dig into the registy of XP, manually clean the VBox drivers (registry+filesystem), reinstall... then it worked.

**Comment by R-Adrian** [comment]
another update: i think this is now an obsolete issue... and we probably have to close it as "not planned"

sometime after August 2024 and now (September 2024) VirtualBox v6 has been marked as "no longer supported" by Oracle... thus no more releases are planned in the v6 series

https://www.virtualbox.org/wiki/Changelog-6.1
says  **VirtualBox 6.1.x is no longer supported!** 

but in August it was not saying this:
https://web.archive.org/web/20240827231659/https://www.virtualbox.org/wiki/Changelog-6.1

**Comment by R-Adrian** [comment]
VirtualBox 6 is no longer supported.
