### ISSUE TITLE
Piriform.CCleaner - Too verbose of version in manifest

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-pkgs#94475]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The version stated in the manifest is too verbose for what the installer puts in the registry after install. Currently, even on latest version of the app, winget still states that there is a update waiting for it due to it comparing 6.08, what the installer puts in the registry as the version, to 6.08.10255, which is what the manifest states as the version expected. 

### Steps to reproduce

Upgrade CCleaner to the latest version and then check for updates using winget

### Actual behavior

Winget always states that there is a update ready even though there isn't 

### Expected behavior

The manifest and the registry key information align, winget doesn't show a false update listing

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/1053504/214193492-8124e5d5-279e-4746-b005-8fd9cf738222.png)

**Comment by rasa** [comment]
@Trenly Sorry that was my bad. Won't happen again.

**Comment by R-Adrian** [comment]
side note:  Piriform / Avast has a history of releasing the same version multiple times while changing stuff and only modifying the build number.
 They did this with Recuva, i would not be surprised if they do the same with CCleaner and this issue will have to be re-visited.  (The package manifest for Recuva is currently showing only the "shortened" version number.)

e.g. Recuva has had these 1.53 version numbers in the past:
 v1.53.1087 (main exe digital signature from June 2016) 
 v1.53.2065 (07 Mar 2022) 
 v1.53.2074 (28 Mar 2022) 
 v1.53.2078 (11 Apr 2022)
 v1.53.2083 (15 Jun 2022)

**Comment by rasa** [comment]
Note that Piriform.CCleaner.ProTrial all of have [x.y.z](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aclosed+piriform.ccleaner.protrial) versions.
And Piriform.CCleaner always had [x.y.z](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aclosed+piriform.ccleaner+) until version 5.79.8704. There are two PRs that say:
[Automatic update of Piriform.CCleaner from 5.89 to 5.89.0.9401](https://github.com/microsoft/winget-pkgs/pull/43405) 
And then there's [Update: Piriform.CCleaner.ProTrial version 5.89](https://github.com/microsoft/winget-pkgs/pull/42970).
