### ISSUE TITLE
[Package Issue]: mcmilk.7zip-zstd

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-pkgs#94590]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

`7-Zip ZS 22.01 ZS v1.5.2 R1 (x64)      mcmilk.7zip-zstd                       22.01 ZS v1.5.2 R1 22.01-v1.5.2-R1`

`22.01 ZS v1.5.2 R1` and `22.01-v1.5.2-R1` are the same but slightly different.

Since the version string is different, winget does not know the installation is uptodate, hence it gets installed every time.

### Steps to reproduce

Run update

### Actual behavior

Installs every time update is run

### Expected behavior

Since there is not update not need to update

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by stephengillie** [comment]
This appears to be "Upgrade always available" due to "Alphanumeric version 'numbers" impacting sort order." 

> `22.01 ZS v1.5.2 R1` and `22.01-v1.5.2-R1` are the same but slightly different.

It's subtle, but beyond swapping spaces for dashes, the first one also has a `ZS` in the middle. Otherwise they are the same. Which one is the higher version and which one is the lower version?
