### ISSUE TITLE
Fail to install TI Connect CE

### ISSUE THREAD

**Issue by NathanBnm** [microsoft/winget-pkgs#947]
When installing TI Connect CE (added in #614) I get the following exit code: "1624". Don't know what is making it fail.

**Comment by denelon** [comment]
I'm not familiar with TI Connect CE. Is this failure based on permissions (run as administrator) or the installer? We do have a feature on the backlog to support non-zero exit codes https://github.com/microsoft/winget-cli/issues/137.

**Comment by NathanBnm** [comment]
@denelon I finally solved this issue and opened #6013 and #6014.
