### ISSUE TITLE
How to test and validate Multi manifest?

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#9479]
# Description of the new feature/enhancement

Hey! 
The manifest v1.0.0 looks cool, but how on earth do we test and validate the manifest?
I've been looking at @jedieaston's manifests and the manifest JSON's, i currently have a NZXT.CAM.yaml, NZXT.CAM.locale.en-US.yaml and NZXT.CAM.installer.yaml which looks correct...

This is what i get when i try to validate NZXT.CAM.yaml
![image](https://user-images.githubusercontent.com/15158490/113171394-b744ba00-9247-11eb-8254-4310c660b1ef.png)

and this is what i get when i try to install NZXT.CAM.yaml
![image](https://user-images.githubusercontent.com/15158490/113171487-cf1c3e00-9247-11eb-9f54-0b9ad7b96f93.png)

**Comment by OfficialEsco** [comment]
Aha...
So you need to have $shcema in the manifests...
I also had Platform which is not supported, and i thought Channel was Stable, Beta, Dev etc

Apparently you validate the manifests with winget validate \winget-pkgs\manifests\n\NZXT\CAM\4.22.0 instead of the yaml file like before..

**Comment by denelon** [comment]
@OfficialEsco, I'm glad you were able to figure it out. We're working through documentation and bot messages. We don't have support for different platforms or channels yet.
