### ISSUE TITLE
[Package Issue]: Libretro.RetroArch version detection broken

### ISSUE THREAD

**Issue by cobalt2727** [microsoft/winget-pkgs#95222]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Pretty much as described in the title. I have 1.14.0.0 installed right now but winget thinks I've still got 1.13.0.0 for some reason. This is made a bit more annoying when compounded with https://github.com/microsoft/winget-cli/issues/1002 - meaning I can't just smoothly run a `winget upgrade --all` anymore without having to worry about deleting a duplicate RetroArch install

### Steps to reproduce

`winget upgrade`

### Actual behavior

version mismatch

### Expected behavior

correction version detection

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2546
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/60624944/215943058-7111448e-6a44-409c-97f2-bba63dd8249c.png)

![image](https://user-images.githubusercontent.com/60624944/215943120-a6fc1aa5-5658-4c88-90fa-0cb77ba34fd4.png)

**Comment by Trenly** [comment]
what is the output of `winget list Retroarch`

**Comment by cobalt2727** [comment]
Actually, it looks like this is an issue with RetroArch itself - not the winget package. Sorry to take up your time!
![image](https://user-images.githubusercontent.com/60624944/216218973-ed95fdf0-c5b6-4fa5-b00e-181e7231c2f9.png)
