### ISSUE TITLE
[Package Issue]: [Facebook.Messenger] Version 175.0.440556528

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#95301]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

winget install --id=Facebook.Messenger -e 

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Install Facebook.Messenger with winget

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/54496743/216087313-f7cf524a-1118-410d-bf3f-23036aea2ac4.png)

**Comment by mdanish-kh** [comment]
Will be resolved once this PR gets merged:
- #95127

**Comment by Trenly** [comment]
Close with reason: PR95127 is merged and published;

**Comment by mdanish-kh** [comment]
Close with reason: New version is added into repo;
