### ISSUE TITLE
Wrong version of Visual Studio Build Tools 2017 detected

### ISSUE THREAD

**Issue by mcdonaldjc** [microsoft/winget-pkgs#95343]
### Brief description of your issue

**Visual Studio Installer** shows that I have **Visual Studio Build Tools 2017** version **15.9.51** installed. Running `winget upgrade` shows the installed version as `15.8.9`, therefore, needing an update. Running `winget upgrade --all` attempts to install an update, but `winget upgrade` continues to report this app as outdated.

### Steps to reproduce

1. Install Visual Studio Installer.
2. Install Visual Studio Build Tools 20017.
3. Confirm the version is 15.9.51.
4. Open the Terminal.
5. Run `winget upgrade`

### Expected behavior

Winget should know the app's actual version and that no update is required.

### Actual behavior

I'm stuck in an update loop that has persisted for a couple of months, perhaps.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22623.1245
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

------------------------------------------------------------

Edition	        Windows 11 Pro
Version	        22H2
Installed on    ‎8/‎24/‎2022
OS build	22623.1245
Experience	Windows Feature Experience Pack 1000.22638.1000.0

------------------------------------------------------------

PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by denelon** [comment]
This is also in progress:
* https://github.com/microsoft/winget-pkgs/issues/94161

**Comment by mdanish-kh** [comment]
Ooops, this shouldn't be closed as I've checked the issue still persists.
```pwsh
~ winget list Microsoft.VisualStudio.2017.BuildTools
Name                           Id                                     Version  Available Source
-----------------------------------------------------------------------------------------------
Visual Studio Build Tools 2017 Microsoft.VisualStudio.2017.BuildTools < 15.8.9 15.9.51   winget
```
Turns out the fix was the other way round. The DisplayVersion should be removed from 15.8.9's manifest as DisplayVersion is actually equal to PackageVersion.
![image](https://user-images.githubusercontent.com/88161975/216708834-fbe2bcc7-627c-4e3c-8226-d53264e52bf2.png)

**Comment by mcdonaldjc** [comment]
> @mcdonaldjc Can you confirm if the issue is resolved for you?

Hello! I can confirm that the issue is no longer present on my system. I had updates for Postman, AWS CLI, and Node.js. Nothing in here about Visual Studio Build Tools.

Thanks to everyone for your swift attention!
