### ISSUE TITLE
[Package Issue]: Rustlang.Rustup tries to install x86_64 version on ARM64 

### ISSUE THREAD

**Issue by ssg** [microsoft/winget-pkgs#95352]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Trying to `winget upgrade` for `Rustlang.Rustup` incorrectly tries to download x86_64 version of the rustup-init.exe and fails with "hash does not match" error (not sure if the error is related to the issue though).

### Steps to reproduce

`winget upgrade --include-unknown --all`

### Actual behavior

```console
(1/1) Found Rustup: the Rust toolchain installer [Rustlang.Rustup] Version 1.25.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
  ██████████████████████████████  9.53 MB / 9.53 MB
Installer hash does not match; this cannot be overridden when running as admin
```

### Expected behavior

Winget should be trying to retrieve ARM64 version of the package.

### Environment

```shell
Windows: Windows.Desktop v10.0.22623.1245
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.20.101.0
```
```


### Screenshots and Logs

_No response_

**Comment by anarelion** [comment]
I have PR #95599 to fix the download URL, because it uses the generic download.

**Comment by ssg** [comment]
Closing since the fix has been merged.
