### ISSUE TITLE
[Package Issue]: Psiphon.PsiphonInc

### ISSUE THREAD

**Issue by NJT145** [microsoft/winget-pkgs#95448]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

It says "Installer hash does not match". Hash needs to be updated.

### Steps to reproduce

I tried these:
winget install -e -i --id=Psiphon.PsiphonInc --source=winget --scope=machine
winget install -e -i --id=Psiphon.PsiphonInc --source=winget --scope=user
winget install -e -i --id=Psiphon.PsiphonInc --source=winget

Errors:
Installer hash does not match; this cannot be overridden when running as admin
Installer hash does not match; this cannot be overridden when running as admin
Installer hash does not match; this cannot be overridden when running as admin

### Actual behavior

Winget gives error that says "Installer hash does not match".

### Expected behavior

Hash for this app needs an update. I know that I can bypass it at local shell, but I want to make a machine install.

### Environment

```shell
[winget --info]
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by NJT145** [comment]
I tried to override that hash issue, but it gives same "Installer hash does not match" error. Need help.

**Comment by stephengillie** [comment]
I've confirmed this behavior in a VM. This is the expected behavior when the downloaded package hash does not match the hash in the package's manifest. One common cause for this is that the developer released a new version of their software, updating in place their downloadable installer. A solution here is to have the manifest updated with the new version and hash data.

**Comment by mdanish-kh** [comment]
PR #95518 will fix this issue. Please note that the id will be changed to `PsiphonInc.Psiphon` instead of Psiphon.PsiphonInc to match the WinGet's standard convention of `Publisher.PackageName` for the PackageId field.
