### ISSUE TITLE
[Package Request]: Microsoft.powershell  version 7.3.2.0

### ISSUE THREAD

**Issue by j-dc** [microsoft/winget-pkgs#95491]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a script file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Microsoft
Publisher Url:
Package Name: Microsoft.Powershell
Description:
Package Version:7.3.2.0
Installer URL:

Powershel 7.3.2.0 is not available.  Yet the powershell documentation claims it is:
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

**Comment by ItzLevvie** [comment]
PR https://github.com/microsoft/winget-pkgs/pull/95159

**Comment by mdanish-kh** [comment]
Close with reason: Package merged into the repo now;
