### ISSUE TITLE
[NOT A BUG] Removed ioquake manifest?

### ISSUE THREAD

**Issue by Luca1991** [microsoft/winget-pkgs#9554]
Hello dear collegues,
some months ago (on November) I created a PR adding the ioquake (opensource quake 3 engine) manifest. The PR was eventually merged. (for reference  PR #5023)
Today I was trying to install ioquake on one of my machines, and I noticed that is was missing from winget.
I see that there were a manifest schema upgrade recently, is this the cause? If so, can I resubmit the manifest?

Thanks a lot,
Luca

**Comment by denelon** [comment]
@Luca1991 I don't believe that is the cause, but I don't see the package either. Be sure to use the new schema when you submit the manifest.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/6167 removed the manifest because https://ioquake3.org/files/1.36/installer/ioquake3-1.36-3.1.x86.exe does not work anymore..

**Comment by OfficialEsco** [comment]
Just checked their download links and clicked around on the page, stuff seems to be broken and unmaintained for almost 4 months?..

**Comment by Luca1991** [comment]
Oh :( yeah, every download link is broken as far as I can see...

Well I'll wait for a fix, and then resubmit the manifest.

Thank you very much!
