### ISSUE TITLE
[Package Request]: Lunar Client

### ISSUE THREAD

**Issue by icejuice-enjoyer** [microsoft/winget-pkgs#95607]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Moonsworth
Publisher Url: https://www.moonsworth.com/
Package Name: Lunar Client
Description: A modpack for all modern versions of Minecraft!
Package Version: 2.15.1
Installer URL: https://launcherupdates.lunarclientcdn.com/Lunar%20Client%20v2.15.1.exe

Current Package Identifier (for new versions): N/A

**Comment by mdanish-kh** [comment]
Close with reason: Package already available in WinGet;

You can use the command `winget install --id Moonsworth.LunarClient` to install the application.

**Comment by mdanish-kh** [comment]
Close with reason: Package already available in WinGet;
