### ISSUE TITLE
[Package Request]: AAAAXY

### ISSUE THREAD

**Issue by icejuice-enjoyer** [microsoft/winget-pkgs#95617]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: divVerent
Publisher Url: https://divverent.github.io/
Package Name: AAAAXY
Description: A nonlinear 2D puzzle platformer taking place in impossible spaces.
Package Version: 1.3.219
Installer URL: https://github.com/divVerent/aaaaxy/releases

Current Package Identifier (for new versions): N/A

**Comment by divVerent** [comment]
Author of the game here. Right now it's packaged as a zip with a portable executable inside - i.e. an exe file that could just be copied to `%ProgramFiles%\AAAAXY\AAAAXY.exe` and stores data in `%LocalAppData%\AAAAXY` and `%SavedGames%\AAAAXY`. There is currently no MSI installer.

If it is required for packaging, I can look into creating one; I cross-compile everything from Linux, but could probably use https://www.npmjs.com/package/msi-packager to create a MSI package and provide that on GitHub Releases.

If however the current form of packaging is OK for winget, I may as well leave things as is.

**Comment by mdanish-kh** [comment]
@divVerent WinGet supports installation of portable executables inside a zip archive. I've opened a PR for this package:

- #97315
