### ISSUE TITLE
[Package Request]: OpenRGB

### ISSUE THREAD

**Issue by icejuice-enjoyer** [microsoft/winget-pkgs#95616]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: OpenRGB
Publisher Url: https://openrgb.org/
Package Name: OpenRGB
Description: Open source RGB lighting control that doesn't depend on manufacturer software
Package Version: 0.8
Installer URL: https://gitlab.com/CalcProgrammer1/OpenRGB/-/releases (binaries are further down the page)

Current Package Identifier (for new versions): N/A

**Comment by mdanish-kh** [comment]
[Policy] Dependencies

Referencing the created PR
- https://github.com/microsoft/winget-pkgs/pull/95650

**Comment by RokeJulianLockhart** [comment]
Now that https://github.com/microsoft/winget-pkgs/pull/95650#event-10302515026 is merged, can this continue?

**Comment by Trenly** [comment]
Close with reason: Resolved in 95650;

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-pkgs/issues/95616#issuecomment-1854869693

@Trenly, do you mean #95650?
