### ISSUE TITLE
Package Issue - Kdenlive

### ISSUE THREAD

**Issue by heathguy** [microsoft/winget-pkgs#95801]
winget upgrade kdenlive
Found Kdenlive [KDE.Kdenlive] Version 22.12.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/view/Windows%20MingW/job/Kdenlive_Stable_mingw64/990/artifact/kdenlive-22.12.1-990-windows-gcc-x86_64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).

**Comment by mdanish-kh** [comment]
Should be fixed as this PR is merged now
- https://github.com/microsoft/winget-pkgs/pull/95580

Please note the issue may appear again as KDE does not provide static Urls for its packages and the Url needs to be constantly updated with the new build runs after a few days.

**Comment by mdanish-kh** [comment]
Close with reason: See above;
