### ISSUE TITLE
[Package Request]: opencascade

### ISSUE THREAD

**Issue by Andrej730** [microsoft/winget-pkgs#95908]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Open Cascade
Publisher Url: https://www.opencascade.com
Package Name: Open CASCADE Technology
Description: object-oriented C++ class library designed for rapid production of sophisticated domain-specific CAD/CAM/CAE applications.
Package Version: 7.7.0
Installer URL: https://dev.opencascade.org/system/files/occt/OCC_7.7.0_release/opencascade-7.7.0-vc14-64.exe

Current Package Identifier (for new versions): -

**Comment by mdanish-kh** [comment]
This package is blocked because InstallerUrl requires the user to create an account and login first.

**Comment by mdanish-kh** [comment]
[Policy] Area-External
