### ISSUE TITLE
Fabricbot automerge is disabled on changes pushed to a PR

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#96183]
When users push a new commit to a PR, automerge is disabled with the reason `Head branch was pushed to by a user without write access`. Given that the validation pipeline runs on changes pushed and removes all labels, the PR should still auto-merge once validation has completed and the changes have been re-approved

* Ref https://github.com/microsoft/winget-pkgs/pull/96172

* Related to https://github.com/microsoft/winget-pkgs/issues/95543

**Comment by Trenly** [comment]
From the FabricBot team - It's technically a feature is automerge being disabled when the base branch changes. Continued discussion is ongoing

**Comment by denelon** [comment]
Related to:
* https://github.com/microsoft/winget-pkgs/issues/95543

This is more likely a GitHub thing, but maybe fabric bot could do something here.

**Comment by Trenly** [comment]
Additional note - Sometimes it seems that there is a misdetection of the Base branch being modified; See https://github.com/microsoft/winget-pkgs/pull/96304 where no changes were pushed to the branch but automerge was still disabled

**Comment by Trenly** [comment]
This should be resolved with the new triggers
