### ISSUE TITLE
Fabricbot is merging PRs with `Possible-Duplicate` label

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-pkgs#96258]
The following PRs were labeled with `Possible-Duplicate` and should not have been auto-merged by fabricbot even if they have a `Moderator-Approved` label.

- https://github.com/microsoft/winget-pkgs/pull/96205
- https://github.com/microsoft/winget-pkgs/pull/96206
- https://github.com/microsoft/winget-pkgs/pull/96207
- https://github.com/microsoft/winget-pkgs/pull/96208

**Comment by vedantmgoyal2009** [comment]
That's the intended behavior, I guess.

**Comment by mdanish-kh** [comment]
Looks like I wrongly assumed the duplicate needed to be removed from repo first or the PR needed manual merge. My bad!

**Comment by denelon** [comment]
@mdanish-kh Possible-Duplicate is more of a Warning than an Error. If moderators approve it, it can be merged :)

**Comment by mdanish-kh** [comment]
I got deceived by the red color of the label as the red ones are usually blocking 😅

**Comment by denelon** [comment]
@mdanish-kh what color would you like? I'm happy to change it.

**Comment by mdanish-kh** [comment]
Yellow/Orange would be nice that generally indicate "warning". Thank you!

**Comment by denelon** [comment]
Orange it is :)
