### ISSUE TITLE
[Package Issue]: KDE.Kdenlive reports error 0x80190193 when downloading upgrade

### ISSUE THREAD

**Issue by tranquilcarbon** [microsoft/winget-pkgs#96254]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

when attempting to download the upgrade for kdenlive from version 22.12.1 to 22.12.2, the download URL will appear however, shortly after the update will fail with the following error:
 "An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : unknown error"

### Steps to reproduce

attempt to download KDE.Kdenlive or upgrade existing install

### Actual behavior

upgrade fails with a 0x80190193 : unknown error

### Expected behavior

upgrade/install should complete.

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2546
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-02-11-13-03-55.355.log](https://github.com/microsoft/winget-pkgs/files/10713715/WinGet-2023-02-11-13-03-55.355.log)

**Comment by tajnymag** [comment]
Can confirm having the same issue

```
(3/3) Found Kdenlive [KDE.Kdenlive] Version 22.12.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/view/Windows%20MingW/job/Kdenlive_Stable_mingw64/995/artifact/kdenlive-22.12.2-995-windows-gcc-x86_64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Zak�z�no (403)
```

**Comment by hueldoeu** [comment]
i have the same but with expressvpn

**Comment by hueldoeu** [comment]
> i have the same but with expressvpn

new link is https://www.expressvpn.works/clients/windows/expressvpn_windows_12.78.0.38_release.exe
in winget it's https://www.expressvpn.works/clients/windows/expressvpn_windows_12.78.0.28_release.exe
