### ISSUE TITLE
[Package Issue]: mozilla.thunderbird upgrade technology error

### ISSUE THREAD

**Issue by tranquilcarbon** [microsoft/winget-pkgs#96253]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Different install technology.

### Brief description of your issue

when installing thunderbird, the package will report the following error: "A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version."

### Steps to reproduce

attempt to upgrade mozilla thunderbird from version 102.7.1 to 102.7.2 from winget.

### Actual behavior

the installer errors reporting "A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version."

### Expected behavior

the upgrade to be installed.

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2546
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-02-11-12-59-50.656.log](https://github.com/microsoft/winget-pkgs/files/10713705/WinGet-2023-02-11-12-59-50.656.log)

**Comment by borque** [comment]
Is it possible, that you initially installed Thunderbird using one of the exe-installers Mozilla provides?
The current manifests only contain the MSI-installers due to the amount of different languages, installer-types and system-architectures.

**Comment by borque** [comment]
@denelon , according to the last post of the reporter, the issue was solved by using an msi-installer. So I suppose the issue can be closed?!

**Comment by otto-liljalaakso-nt** [comment]
I have run into this same issue, twice.
First time I solved it by the suggested solution here:

```
winget remove Mozilla.Thunderbird && winget install Mozilla.Thunderbird
```

But the issue returned after a while, probably when a new version became available.
I suspect that Thunderbird automatically updates itself using a different technology than MSI.

I wonder if Thunderbird has automatic updates enabled if it is first installed with Winget?
My installation was done by different means before I started using Winget,
so perhaps it is just this installation that has the bad auto-update setting enabled,
and fresh installations work correctly.

I will monitor what happens when the next version is out (I am now at 102.8.0).
I am not sure if this issue should be reopened, any opinions that are welcome.

**Comment by otto-liljalaakso-nt** [comment]
> I will monitor what happens when the next version is out (I am now at 102.8.0).
> I am not sure if this issue should be reopened, any opinions that are welcome.

Two further updates to 102.9.0 and 102.9.1 went without issues, so it seems that everything is working now.
