### ISSUE TITLE
Unfortunately uninstalled Windows Package Manager Source (winget) and how to reinstall it? [Package Issue]: Package.Identifer

### ISSUE THREAD

**Issue by Seanwanq** [microsoft/winget-pkgs#96353]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I mistakenly uninstalled the Windows Package Manager Source (Winget) app in Settings. And I found that my Winget cannot update the package from the Winget source. So how can I reinstall Windows Package Manager Source (Winget) again?

### Steps to reproduce

Uninstall Windows Package Manager Source (winget) app in setting.

### Actual behavior

```
winget update
Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.
```

### Expected behavior

The Windows Package Manager Source (winget) app can be reinstalled and Winget can update source correctly.

### Environment

```shell
winget --info
Windows Package Manager (Preview) v1.5.101-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.101.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

<img width="964" alt="image" src="https://user-images.githubusercontent.com/61580138/218290791-dcb18b87-5bdd-4b8f-aa6f-29dd953c47b7.png">

**Comment by Trenly** [comment]
This should resolve itself when the source updates, or you can manually update the source using `winget source update`. However, there are currently issues ongoing with the winget source - https://github.com/microsoft/winget-cli/issues/2956

**Comment by Seanwanq** [comment]
> This should resolve itself when the source updates, or you can manually update the source using `winget source update`. However, there are currently issues ongoing with the winget source - [microsoft/winget-cli#2956](https://github.com/microsoft/winget-cli/issues/2956)
> 
> Alternatively, you may be able to download the source package from https://winget.azureedge.net/cache/source.msix

Thank you! It works!
