### ISSUE TITLE
[Package Issue]: Google.Chrome

### ISSUE THREAD

**Issue by absmith82** [microsoft/winget-pkgs#96740]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Downloading https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

run winget install google.chrome

### Actual behavior

Installer hash does not match.

### Expected behavior

installer hash matches and google chrome installs

### Environment

```shell
Windows Package Manager v1.4.10173
Windows: Windows.Desktop v10.0.22621.1105
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Shoehorner** [comment]
There has got to be a way to automate the hash update for Chrome right? This has to be one of the more popular packages.

**Comment by denelon** [comment]
@Shoehorner we do automatically check for hash mismatches daily, and we attempt to update the manifest via automation. In some cases, these hash mismatches are detected and repaired more quickly with community involvement. We've been looking at something like: 
* https://github.com/microsoft/winget-cli/issues/870

The intent is to make this a bit easier to deal with, and to help us automatically fix them more quickly.

**Comment by maumeerally** [comment]
Chrome is a flagship app I deploy using Autopilot. Can't afford for it to really fail on hash mismatch, I've dumped winget altogether because of this.
