### ISSUE TITLE
microsoft-github-policy-service Bot Issues

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#96802]
All,

As the Validation pipeline issue has been resolved, I'm creating this issue to track things related to the [microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) bot. 

*Note: This is not to be confused with @wingetbot maintained by the WinGet team.*

I'll update the following list as we continue to monitor issues and work with the bot engineering team:
* https://github.com/microsoft/winget-pkgs/issues/96175
* https://github.com/microsoft/winget-pkgs/issues/96181
* https://github.com/microsoft/winget-pkgs/issues/96182
* https://github.com/microsoft/winget-pkgs/issues/96183
* https://github.com/microsoft/winget-pkgs/issues/96801

**Comment by zadjii-msft** [comment]
Something else we're noticing over on the Terminal: we've got a rule for when we add the `needs-second` label to a PR, the bot should add everyone else on the team to the PR as a reviewer. You can find our copy of the rule here: https://github.com/microsoft/terminal/blob/281015504629739995ddb63dd542615570919970/.github/fabricbot.json#L2580-L2646

As an example: https://github.com/microsoft/terminal/pull/14486
![image](https://user-images.githubusercontent.com/18356694/226000083-a16d5477-05b9-4b69-8e4f-aade65bdb7da.png)


However, we've just noticed that this regressed, and seems to be re-requesting a review from people who have already approved:
![image](https://user-images.githubusercontent.com/18356694/226000160-06a24184-63f5-44d0-8cbe-12464da0f272.png)


(I'm filing this here cause this has kinda become the "issues with fabric bot" thread. If there's a better place, lemme know.)

**Comment by astatide** [comment]
Hi @zadjii-msft,

Unfortunately, my position was eliminated as part of the layoffs on March 6th and I was the sole engineer on the project.  I was left to believe that means Fabric Bot will no longer be used/supported/maintained.  You'll have to contact Dragos Boia internally for any news on that front, especially as I no longer have access to any systems.

Best of luck, and I'm glad FabricBot was useful!

**Comment by zadjii-msft** [comment]
I think I heard as much through the grapevine - sorry to hear it 😢 FabricBot has been absolutely critical to us being able to stay on top of the Terminal repo. You can bet I'll be following up internally. 

Best of luck in the future!

**Comment by mdanish-kh** [comment]
cc @denelon All linked issues appear to have been closed as resolved.
