### ISSUE TITLE
[Package Issue]: BiglySoftware.BiglyBT

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/winget-pkgs#97482]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I have installed BiglyBT 3.2.0.0 and updated it to 3.3.0.1_B06 beta using internal updater.
Winget still thinks it is 3.2.0.0

### Steps to reproduce

Install biglybt 3.2 and enable beta updates in it.

### Actual behavior

Winget doesn't report correct version

### Expected behavior

Winget doesn't offer to downgrade biglybt.

### Environment

```shell
winget.exe --info
Диспетчер пакетов Windows версии 1.4.10173
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.22621.1105
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.19.10173.0

Журналы: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Параметры пользователя: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Ссылки
--------------------------------------------------------------------------------------
Заявление о конфиденциальности https://aka.ms/winget-privacy
Лицензионное соглашение        https://aka.ms/winget-license
Уведомления третьих сторон     https://aka.ms/winget-3rdPartyNotice
Домашняя страница              https://aka.ms/winget
Условия Windows Store          https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
What results do you get for `winget list biglybt`?

**Comment by kotenok2000** [comment]
BiglyBT BiglySoftware.BiglyBT 3.2.0.0 3.3.0.0  winget

**Comment by denelon** [comment]
It looks like the installer didn't upgrade the version in Windows Apps & Features.
WinGet looks at the "displayVersion" key from the registry to perform comparisons.
