### ISSUE TITLE
[Package Issue]: Microsoft.Office hash mismatch

### ISSUE THREAD

**Issue by dropbobbytables** [microsoft/winget-pkgs#97620]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match.

winget hash .\setup.exe
InstallerSha256: 8cd8255aa6aeb0b02bc5d9cd6c417368de39f57f191bf41f480c5eb68749b917

### Steps to reproduce

winget upgrade Microsoft.Office

### Actual behavior

Does not update. Installer hash does not match.

### Expected behavior

To update Office

### Environment

```shell
Windows: Windows.Desktop v10.0.19044.2251
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by leonkappes** [comment]
Can confirm this issue:
The Office CDN (https://officecdn.microsoft.com/pr/wsus/setup.exe) serves Version `16.0.16026.20162` 
while winget wants to install `16.0.16026.20200` therefore we have a hash mismatch.

**Comment by craiglandis** [comment]
Same here - 

```
PS C:\> winget install --id Microsoft.Office --exact --silent --accept-package-agreements --accept-source-agreements --force
Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.16026.20200
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe
  ██████████████████████████████  7.08 MB / 7.08 MB
Installer hash does not match; this cannot be overridden when running as admin
```

**Comment by mp-strachan** [comment]
I am also experiencing the issue across our fleet.

```powershell
PS C:\>  winget install --id Microsoft.Office --accept-package-agreements --accept-source-agreements --scope machine --silent
Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.16026.20200
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe
  ██████████████████████████████  7.08 MB / 7.08 MB
Installer hash does not match; this cannot be overridden when running as admin
```

Managed to manually workaround with the following

PS (as admin)
```powershell
winget settings --enable InstallerHashOverride
```

PS (non-admin. Couldn't execute as admin)
```powershell
winget install --id Microsoft.Office --accept-package-agreements --accept-source-agreements --scope machine --silent --force --ignore-security-hash
```

Really hope we get a fix for this ASAP...

**Comment by amineoe** [comment]
Try this : 
**winget upgrade --all --ignore-security-hash**

------------------------------------------------------------------------------------------------

(1/1) Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.16529.20164
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe
  ██████████████████████████████  7.25 MB / 7.25 MB
Installer hash does not match; proceeding due to --ignore-security-hash
Starting package install...
Successfully installed
