### ISSUE TITLE
[Package Issue]: Microsoft.VCRedist.2005.x86

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/winget-pkgs#97646]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I can't update Microsoft.VCRedist.2005.x86 from 8.0.56336  to  8.0.61001
I get "No installed package found matching input criteria." error.
Winget update displays this
winget update
Name                                                       Id                          Version      Available    Source
-----------------------------------------------------------------------------------------------------------------------
BiglyBT                                                    BiglySoftware.BiglyBT       3.2.0.0      3.3.0.0      winget
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30… Microsoft.VCRedist.2013.x64 12.0.30501.0 12.0.40664.0 winget
Microsoft Visual C++ 2005 Redistributable                  Microsoft.VCRedist.2005.x86 8.0.56336    8.0.61001    winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30… Microsoft.VCRedist.2013.x86 12.0.30501.0 12.0.40664.0 winget
4 upgrades available.

Same happens to other  Microsoft.VCRedist.

### Steps to reproduce

install visual с++ 2005 8.0.56336 by running installer.
Try to update.

### Actual behavior

Winget fails to update  Microsoft.VCRedist.2005.x86 8.0.56336

### Expected behavior

Winget works normally.

### Environment

```shell
winget --info
Диспетчер пакетов Windows версии 1.4.10173
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.22621.1105
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.19.10173.0

Журналы: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Параметры пользователя: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Ссылки
--------------------------------------------------------------------------------------
Заявление о конфиденциальности https://aka.ms/winget-privacy
Лицензионное соглашение        https://aka.ms/winget-license
Уведомления третьих сторон     https://aka.ms/winget-3rdPartyNotice
Домашняя страница              https://aka.ms/winget
Условия Windows Store          https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

[WinGet-2023-02-23-23-51-25.081.log](https://github.com/microsoft/winget-pkgs/files/10818380/WinGet-2023-02-23-23-51-25.081.log)

**Comment by Trenly** [comment]
@denelon - CLI, Area-Matching

```
2023-02-23 23:51:28.038 [REPO] Found multiple matches for available package [Microsoft.VCRedist.2005.x86] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{710f4c1c-cc18-4c49-8cbf-51240c89a1a2}'[Exact] Include:ProductCode='{ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}'[Exact] Include:UpgradeCode='{86c9d5aa-f00c-4921-b3f2-c60af92e2844}'[Exact] Include:NormalizedNameAndPublisher='microsoftvisualc2005redistributable'+'microsoft'[Exact]]
2023-02-23 23:51:28.038 [REPO]   Checking match with package id: {710f4c1c-cc18-4c49-8cbf-51240c89a1a2}
2023-02-23 23:51:28.039 [REPO]   Checking match with package id: {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}
2023-02-23 23:51:28.039 [REPO]   Found multiple packages with strong match fields
2023-02-23 23:51:28.039 [REPO]   Appropriate installed package could not be determined
```

**Comment by Trenly** [comment]
Several other issues are tracking issues related to VC Runtimes and side-by-side. I'm closing this issue in favor of the work over at the CLI.

###### Close with reason: Tracked at CLI;
