### ISSUE TITLE
[Package Request]: Grocy - ERP beyond your fridge

### ISSUE THREAD

**Issue by Elijahh177** [microsoft/winget-pkgs#97777]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Bernd Bestel
Publisher Url: https://grocy.info/
Package Name: Grocy
Description: ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home.
Package Version: 2.3.1
Installer URL: https://github.com/grocy/grocy-desktop/releases

Current Package Identifier (for new versions):

**Comment by upintheairsheep** [comment]
released. close
