### ISSUE TITLE
[Package Issue]: TeamViewer.TeamViewer.Host

### ISSUE THREAD

**Issue by nikomakela48** [microsoft/winget-pkgs#97818]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

It seems that TeamViewer has updated TeamViewer Host from version 15.39.3 to 15.39.5, and obviously the installer hash does not match. 

### Steps to reproduce

Try to install TeamViewer.TeamViewer.Host using winget. 

### Actual behavior

Installer hash doesn't match so installer fails. Tried using --force, didn't work.

### Expected behavior

Expected winget to install TeamViewer.TeamViewer.Host

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1265
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

[WinGet-2023-02-26-09-17-53.837.log](https://github.com/microsoft/winget-pkgs/files/10833202/WinGet-2023-02-26-09-17-53.837.log)
![winget](https://user-images.githubusercontent.com/93643753/221397673-f02c16ef-57ed-4c9e-97e6-f0938c225b2e.png)

**Comment by mdanish-kh** [comment]
Close with reason: New version with the updated hash merged in #97790;
