### ISSUE TITLE
[Package Request]: Code.Org Maker App

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-pkgs#98032]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: code.org
Publisher Url: code.org
Package Name: Code.org Maker App
Description: Browser specifically designed for Code.Org that allows you to connect physical stuff
Package Version: 1.1.9
Installer URL: https://downloads.code.org/maker/Code.org%20Maker%20App-1.1.9-win.msi (silent installer)

Current Package Identifier (for new versions):
N/A

**Comment by Trenly** [comment]
I'm not sure this would be a good fit for winget - since the package is going to be deprecated in a few months anyways

https://support.code.org/hc/en-us/articles/11304760762125-Deprecating-the-Maker-App-and-Chrome-Serial-Extension

**Comment by upintheairsheep** [comment]
did it!
