### ISSUE TITLE
[Package Issue]: MinGit faulty Path environment variable

### ISSUE THREAD

**Issue by abtesk** [microsoft/winget-pkgs#98100]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installation of MinGit does not seem to add a correct path to the Path environment variable.
I my case, following path is added:
```
~\AppData\Local\Microsoft\WinGet\Packages\Git.MinGit_Microsoft.Winget.Source_8wekyb3d8bbwe
```
However, the part `\cmd` is missing at the end to be correct.

### Steps to reproduce

Open terminal, type:
```
winget install MinGit
```
Close and open new terminal, type:
```
git
```

### Actual behavior

Error message, `git` can't be found.

### Expected behavior

Git manpage.

### Environment

```shell
Windows-Paket-Manager v1.4.10173
Windows: Windows.Desktop v10.0.22621.1265
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by denelon** [comment]
@abtesk I believe this is related to:
* microsoft/winget-cli/issues/2909

**Comment by abtesk** [comment]
Thanks for pointing out that issue!
I guess starting Terminal as administrator is *a* workaround until the fix is merged. It's quick and (rather) dirty when activating developer mode is not always an option.

**Comment by okineadev** [comment]
Execute `hash -r`
