### ISSUE TITLE
Manifest-Validation-Error

### ISSUE THREAD

**Issue by SoftCreatR** [microsoft/winget-pkgs#984]
I've tried to add a manifest file, however the automatic check returns a "Manifest-Validation-Error" because of

- SystemAppId
- Channel

According to the to the [manifest specification](https://github.com/microsoft/winget-cli/blob/0109b3937ac99deaefb1d4a68a1b477153dc596e/doc/ManifestSpecv0.1.md), these properties should be supported, but that's obviously not the case:

>  Manifest Warning: Unknown field. Field: SystemAppId Line: 15, Column: 5
> Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
> Manifest Error: Field is not supported. Field: Channel Value: stable

See https://github.com/microsoft/winget-pkgs/pull/917

EDIT:

Even the property `ManifestVersion` doesn't seem to be supported yet.

**Comment by superusercode** [comment]
I would recommend sticking to the generator script in the tools folder of this repository. There are a lot of fields in the spec not supported proper yet.

**Comment by SoftCreatR** [comment]
> I would recommend sticking to the generator script in the tools folder of this repository. There are a lot of fields in the spec not supported proper yet.

Already did that and created a new PR: https://github.com/microsoft/winget-pkgs/pull/988

That's fine for me and i'll keep an eye on further supported properties for new releases.
