### ISSUE TITLE
Package Issue: Resplendence.WhoCrashed v7.06

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#98476]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

The setup URL location is correct.  It looks like the publisher overwriting the setup causing the hash to mismatch. 
You are using a direct link to check for the newer version. The newer version can be found in the release notes.
ReleaseNotes: https://www.resplendence.com/whocrashed_whatsnew
The URL is unaffected by the newer version. The newer version is supposed to be v7.06 
The setup file hash is 8F9F79ABDB3195BD22B58CDE459E45139D320677579966C202CA371D87A0A4AD
Two things will be affected by the newer version affected the setup file hashes and the WhoCrashed Edition. 

### Steps to reproduce

When I run winget install WhoCrashed, it looks like the version and the setup file mismatch also. The correct hashes and version.
WhoCrashed Version Mismatch on winget. The setup file mismatch also.
Actual WhoCrashed v7.01 in winget. The actual setup file hash in winget 302b9a24938561acf81d090e92e6fb75cfec034a9b91e153d2d63385a5044823
Actual WhoCrashed in the web is v7.06  The actual setup file hash in the web is  8F9F79ABDB3195BD22B58CDE459E45139D320677579966C202CA371D87A0A4AD

### Actual behavior

[WhoCrashed.log](https://github.com/microsoft/winget-pkgs/files/10888311/WhoCrashed.log)
[WhoCrashedInstall.log](https://github.com/microsoft/winget-pkgs/files/10888312/WhoCrashedInstall.log)

### Expected behavior

![Screenshot (19)](https://user-images.githubusercontent.com/118059864/222901064-76a68fd1-c5e6-4878-9515-d65b6fb6cdd6.png)
The Screenshot 19 refer to my  WhoCrashed app is in v7.06
Expected Version is in v7.06  Expected setup file hashes is 8F9F79ABDB3195BD22B58CDE459E45139D320677579966C202CA371D87A0A4AD
When there is a newer versions, it will affected expected setup file hashes.

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2673
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by stephengillie** [comment]
Often, a hash mismatch is caused by the developer releasing a new version, and the fix is to update the application's WinGet manifest with the new hash (and any other new data).
