### ISSUE TITLE
[Package Request]: Add "Battery Mode" to winget

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/winget-pkgs#98483]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Tarasov Artyom
Publisher Url: https://github.com/tarcode-apps/BatteryMode/releases
Package Name:  TarasovArtyom.BatteryMode (not sure who defines this package name?)
Description: 

> Replaces Windows default battery indicator to a more powerful and useful one.
> 
> It provides backlight control, easy power scheme selection, detailed battery information and a lot of handy features for customization.
> 
> ![image](https://user-images.githubusercontent.com/8274816/222906625-d76ab557-0ec2-4651-ab11-e03f0e6df2be.png)

Package Version: [4.3.2.204](https://github.com/tarcode-apps/BatteryMode/releases/tag/v4.3.2.204)
Installer URL:

x86: https://github.com/tarcode-apps/BatteryMode/releases/download/v4.3.2.204/BatteryModeInstaller32.exe
x64: https://github.com/tarcode-apps/BatteryMode/releases/download/v4.3.2.204/BatteryModeInstaller64.exe

Current Package Identifier (for new versions):

**Comment by optsing** [comment]
#98617

**Comment by MagicAndre1981** [comment]
> #98617

works, thanks 👍
