### ISSUE TITLE
[Package Issue]: Gyan.FFmpeg

### ISSUE THREAD

**Issue by khewweifeng** [microsoft/winget-pkgs#98553]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

winget install Gyan.FFmpeg

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

-

### Environment

```shell
winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1265
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/54496743/222969517-620cf55c-f6e2-49ef-b893-16a643690fca.png)

**Comment by GyanD** [comment]
Seems that Shared hasn't been updated to 6.0.
