### ISSUE TITLE
[Package Issue]: unzip

### ISSUE THREAD

**Issue by JeffMill** [microsoft/winget-pkgs#98652]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I ran "winget install unzip"

The proposed unzip app is:

Zip & RAR Extractor [9PNBL3L7JPFT] Version Unknown
Version: Unknown
Publisher: UNO UNO UNO Go

Maybe this is a completely trusted app by a completely trusted publisher, but I can't find anything about this app or publisher.  This app doesn't even have a version number!

Should winget really default to installing this app when I specify "unzip" when there's 7-zip, just to mention one?

Smells name name squatting to me.

### Steps to reproduce

winget install unzip

### Actual behavior

asks to install unexpected / unknown app.

### Expected behavior

does nothing (shows that name is ambiguous) or uses a more well-known default.

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2604
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by stephengillie** [comment]
This does appear to be the top application when searching for "unzip":
```
PS C:\ManVal> winget search unzip
Name                       Id                 Version    Match      Source
---------------------------------------------------------------------------
Unzip: Zip & RAR Extractor 9PNBL3L7JPFT       Unknown               msstore
Zip-Unzip,compression      9MT44RNLPXXT       Unknown               msstore
IZArc                      IZArc.IZArc        4.5        Tag: unzip winget
GnuWin32: UnZip            GnuWin32.UnZip     5.51-1     Tag: unzip winget
PeaZip                     Giorgiotani.Peazip 9.1.0      Tag: unzip winget
360 Zip                    360.360Zip         1.0.0.1041 Tag: unzip winget
```

7zip doesn't have "unzip" in any of its names nor monikers:
```
PS C:\ManVal> winget search 7zip
Name                              Id                     Version            Match         Source
-------------------------------------------------------------------------------------------------
7zip 22                           XPFM275LQF9R3S         Unknown                          msstore
9 ZIP - open rar, zip, 7zip, gzip 9NBLGGH3TDHG           Unknown                          msstore
7-Zip                             7zip.7zip              22.01              Moniker: 7zip winget
7-Zip ZS                          mcmilk.7zip-zstd       22.01 ZS v1.5.4 R4 Tag: 7zip     winget
NanaZip Preview                   M2Team.NanaZip.Preview 2.1.451.0          Tag: 7zip     winget
NanaZip                           M2Team.NanaZip         2.0.450.0          Tag: 7zip     winget
7-Zip Alpha (msi)                 7zip.7zip.Alpha.msi    21.03.00.0                       winget
7-Zip Alpha (exe)                 7zip.7zip.Alpha.exe    21.04 beta                       winget
```

Adding "unzip" to 7zip manifests may help mitigate this issue for this search term.

**Comment by denelon** [comment]
The "winget" source doesn't have a package with that unique name, moniker, or tag. The "msstore" source returns the package with the Identifier: "9PNBL3L7JPFT". The "msstore" source also doesn't currently provide version numbers for packages.

Since there is only one "best match" returned, the command `winget install unzip` is installing that package.

The URL below is the Microsoft Store entry:
https://apps.microsoft.com/store/detail/unzip-zip-rar-extractor/9PNBL3L7JPFT

**Comment by denelon** [comment]
This is a case where WinGet is behaving as it should, but the search term "unzip" isn't matching to any other "better known" package.
