### ISSUE TITLE
[Package Issue]: Foxit.FoxitReader

### ISSUE THREAD

**Issue by elreymon** [microsoft/winget-pkgs#98780]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I have a Foxit reader installed (configured to show in spanish).
Afert winget update the program shows in english difficulting the work and re-configuration to no inglish speakers.

### Steps to reproduce

1. Install an old version of Foxit reader
2. Configure to use spanish (restart of the program is required)
3. Upgrade with winget as usual.

### Actual behavior

Afert winget update the program shows in english difficulting the work and re-configuration to no inglish speakers.

### Expected behavior

The installer should mantain the languaged configured. Actually only the en-US language version is linked to donwload by winget.
The miltilingual version should be linked instead. Here you can see the difference:

- Only en-US version (actual) https://cdn01.foxitsoftware.com/product/reader/desktop/win/12.1.1/FoxitPDFReader1211_enu_Setup_Prom.exe
- Multilingual version (desired or more appropiate) https://cdn01.foxitsoftware.com/product/reader/desktop/win/12.1.1/FoxitPDFReader1211_L10N_Setup_Prom.exe

### Environment

```shell
winget --info
Administrador de paquetes de Windows v1.4.10173
Windows: Windows.Desktop v10.0.19045.2604
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by mdanish-kh** [comment]
@elreymon The InstallerUrl has been updated. Can you please check again to see if the issue has been resolved for you?

**Comment by elreymon** [comment]
Works fine. Thanks a lot.
