### ISSUE TITLE
All in this category K-LiteCodecPack is outdated 

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#99153]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

There is a newer version of CodecGuide.K-LiteCodecPack The Iobit Uninstaller will tell you the version.
![Screenshot (80)](https://user-images.githubusercontent.com/118059864/224370543-e6dca1a2-a4a5-4c23-8391-7cd0a54c7aa6.png)
This app is to check everything up to date. The clues to the new URL is: If there is not up to date, it must be in winget use that address replace to where support the older number and change it to a newer number which is the new URL. 
Currently, 1.7.4.6 is unavailable because it could be waiting for future releases.  Also, the release note will be updated by the time.

### Steps to reproduce

When winget searches mkv use it to support the MKV Video Player. A bunch of K-Lite Codec is all outdated.

### Actual behavior

When I use winget to search MKV, suddenly a bunch of K-Lite Codec is outdated. Because the Iobit Uninstaller tries to check the website on the server. It suddenly found another URL that can be the file name changed. If you are up to date, you might see 404 Unavailable. That means the 1.7.4.6 version is not yet released. The release note should be https://codecguide.com/changelogs_full.htm for the clues to the new URL.

### Expected behavior

Install and Upgrade should work as expected

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2673
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/118059864/224375146-67835dfd-5567-42c1-9090-319715385af7.png)

**Comment by stephengillie** [comment]
If I'm understanding correctly, K-LiteCodecPack version 1.7.4.5 has been released but our manifest's highest version is 1.7.4.0. The solution would be to add an updated manifest with the new package version.

**Comment by BrandonWanHuanSheng** [comment]
Yes. Right now, there is greater than 1.7.4.5 It is 1.7.5.0

**Comment by mdanish-kh** [comment]
Close with reason: 17.5.0 and 17.5.2 versions have been added to the repo;
