### ISSUE TITLE
[Package Request]: Yandex.Disk

### ISSUE THREAD

**Issue by Andrej730** [microsoft/winget-pkgs#99184]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: YANDEX
Publisher Url: https://yandex.com/
Package Name: Yandex Disk
Description: Yandex Disk is a convenient and reliable cloud for storing all of your photos, videos, and documents. Your files are safe with Yandex Disk thanks to the built-in virus scanning and encryption, which can be used at any time on any device. All new Yandex Disk users get 5 GB of free space.
Package Version: 
Installer URL: https://disk.yandex.com/download/YandexDisk30Setup.exe/?instant=1

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in #99255;
