### ISSUE TITLE
[Package Request]: SDCC.SDCC

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/winget-pkgs#99198]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: SDCC
Publisher Url: https://sdcc.sourceforge.net/
Package Name: `SDCC.SDCC`
Description: The Small Device C Compiler (SDCC) is a free-software, partially retargetable C compiler for 8-bit microcontrollers.
Package Version: `3.3.0~4.2.0`
Installer URL:

* **win64** architecture:

  * [sdcc-3.3.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.3.0/sdcc-3.3.0-x64-setup.exe)
  * [sdcc-3.4.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.4.0/sdcc-3.4.0-x64-setup.exe)
  * [sdcc-3.5.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.5.0/sdcc-3.5.0-x64-setup.exe)
  * [sdcc-3.6.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.6.0/sdcc-3.6.0-x64-setup.exe)
  * [sdcc-3.8.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.8.0/sdcc-3.8.0-x64-setup.exe)
  * [sdcc-3.9.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/3.9.0/sdcc-3.9.0-x64-setup.exe)
  * [sdcc-4.0.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/4.0.0/sdcc-4.0.0-x64-setup.exe)
  * [sdcc-4.1.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/4.1.0/sdcc-4.1.0-x64-setup.exe)
  * [sdcc-4.2.0-x64-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win64/4.2.0/sdcc-4.2.0-x64-setup.exe)

* **win32** architecture:

  * [sdcc-3.3.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.3.0/sdcc-3.3.0-setup.exe)
  * [sdcc-3.4.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.4.0/sdcc-3.4.0-setup.exe)
  * [sdcc-3.5.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.5.0/sdcc-3.5.0-setup.exe)
  * [sdcc-3.6.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.6.0/sdcc-3.6.0-setup.exe)
  * [sdcc-3.8.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.8.0/sdcc-3.8.0-setup.exe)
  * [sdcc-3.9.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/3.9.0/sdcc-3.9.0-setup.exe)
  * [sdcc-4.0.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/4.0.0/sdcc-4.0.0-setup.exe)
  * [sdcc-4.1.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/4.1.0/sdcc-4.1.0-setup.exe)
  * [sdcc-4.2.0-setup.exe](https://sourceforge.net/projects/sdcc/files/sdcc-win32/4.2.0/sdcc-4.2.0-setup.exe)

Current Package Identifier (for new versions):

**Comment by BiosPlus** [comment]
Waiting for this initial commit to succeed before adding updated versions: https://github.com/microsoft/winget-pkgs/pull/131637
