### ISSUE TITLE
[Package Request]: Syncthing

### ISSUE THREAD

**Issue by dnet890** [microsoft/winget-pkgs#99239]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:Syncthing
Publisher Url:https://syncthing.net/downloads/
Package Name: Syncthing
Description: Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers. 
Package Version: 1.23
Installer URL: https://github.com/syncthing/syncthing/releases/download/v1.23.2/syncthing-windows-amd64-v1.23.2.zip

Current Package Identifier (for new versions):1.23

**Comment by Trenly** [comment]
Close with reason: Package is now available as Syncthing.Syncthing;
