### ISSUE TITLE
[Package Request]: Fujitsu Client DeskUpdate

### ISSUE THREAD

**Issue by ctih** [microsoft/winget-pkgs#99418]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a script file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Fujitsu Client Computing Limited
Publisher Url: fujitsu.com
Package Name: DeskUpdate
Description: Fujitsu driver manager
Package Version: 5.02.56.0
Installer URL: https://webdownloads4.ts.fujitsu.com/download/FileDownload/fileDownload.aspx?SoftwareGUID=FE7260C7-0B8E-46D5-8EEF-613E9DBB09CC&FileFolder=Downloadfiles&FileTypeExtension=EXE&FileNameClient=FTS_DeskUpdateSetup_5020056_1279825.EXE

Current Package Identifier (for new versions): FujitsuClientComputingLimited.DeskUpdate

**Comment by Dragon1573** [comment]
This package is already presented in the repository. Issue should be closed as "completed".

```text
D:\Workloads> winget search FujitsuClientComputingLimited.DeskUpdate --versions
已找到 DeskUpdate [FujitsuClientComputingLimited.DeskUpdate]
版本
--------
5.2.56.0
5.2.40.0

D:\Workloads> winget search FujitsuClientComputingLimited.DeskUpdate --versions
已找到 DeskUpdate [FujitsuClientComputingLimited.DeskUpdate]
版本
--------
5.2.56.0
5.2.40.0
D:\Workloads> winget show -e FujitsuClientComputingLimited.DeskUpdate --version 5.2.56.0
已找到 DeskUpdate [FujitsuClientComputingLimited.DeskUpdate]
版本: 5.2.56.0
发布者: Fujitsu Client Computing Limited
描述: Fujitsu driver manager
许可证: Proprietary
版权所有: Copyright © Fujitsu Client Computing Limited 2022
安装：
  安装程序类型： inno
  安装程序 URL： https://webdownloads2.ts.fujitsu.com/download/FileDownload/fileDownload.aspx?SoftwareGuid=FE7260C7-0B8E-46D5-8EEF-613E9DBB09CC&FileFolder=Downloadfiles&FileTypeExtension=EXE&FileNameClient=FTS_DeskUpdateSetup_5020056_1279825.EXE
  安装程序 SHA256： ad38663e34b616f81eb6a78750c9051c8967dbfd987e717bc76dc821c87a5155
```

**Comment by stephengillie** [comment]
> This package is already presented in the repository. Issue should be closed as "completed".
