### ISSUE TITLE
[Package Issue]: TheDocumentFoundation.LibreOffice - abuse of downloadarchive NON-CDN URLs

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#99420]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Microsoft Winget is abusing the bandwidth provided by The Document Foundation via the 'downloadarchive' url.

https://downloadarchive.documentfoundation.org/libreoffice/
I'm barely getting a few hundred kbps dowload speed from this when installing/updating Libreoffice via winget. 

see: https://redmine.documentfoundation.org/issues/3236
quote (from year 2020, before the load on the server skyrocketed):
Yes… **downloadarchive is not backed by a CDN**, and shares the same upstream link, so you wouldn't get faster speed there. Commercial CDNs are expensive and definitely not worth it for just not even 10 hits per days on average. We could deploy some of these on our volunteer-driven mirror network, however that'd need to be opt in (the release downloads are mostly fixed in size, but bibisect stuff much larger and ever increasing; that's also why downloadarchive is not backed by a CDN). Most likely few mirrors would be interested in this, not just because of the extra space needs, but also because universities and ISPs prefer to mirror stuff that their users/customers use (and they're vastly more likely to have LibreOffice users than QA team members among them).
/quote

### Steps to reproduce

- install /update Libreoffice via winget
- observe download speeds while doing so

### Actual behavior

slow download speed.

Reason: this repository is NOT backed up by a CDN.

### Expected behavior

solution: please use URLs on 
https://download.documentfoundation.org/libreoffice/stable/
- this one is served via the CDN network.

Note: downloadarchive can probably remain in use for URLs of old versions, but please do not use it as the main installation/update repository - it was obviously not designed to handle this much load. 

### Environment

```shell
winget --info
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2604
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
It looks like the latest [version](https://github.com/microsoft/winget-pkgs/blob/master/manifests/t/TheDocumentFoundation/LibreOffice/7.5.1.2/TheDocumentFoundation.LibreOffice.installer.yaml) is from @krystofkrticka.

If I'm understanding the issue correctly, the best practice here would be to use the CDN backed URL for the latest version, and then update the URL in the n-3 or n-4 version to the one that is not CDN backed after it falls off of the CDN backed URL.

**Comment by krystofkrticka** [comment]
@denelon what I found out is that downloadarchive is hit or miss when it comes to speed, but when I get to my computer at home I'll look into changing the download links to download.documentfoundation.org

**Comment by krystofkrticka** [comment]
> @denelon what I found out is that downloadarchive is hit or miss when it comes to speed, but when I get to my computer at home I'll look into changing the download links to download.documentfoundation.org

Also it looks like the winget is unable to automatically use local mirror because when I create package upgradr it asks me if I want to use my local mirror.

**Comment by krystofkrticka** [comment]
Also I didn't now that download archive is not backed by CDN.

**Comment by krystofkrticka** [comment]
BTW I used urls which were used by previous manifest versions so yes, somebody who created LibreOffice package in repo used download archive so I just kept using it as previous manifests.

**Comment by R-Adrian** [comment]
>  it would be nice if it was possible to use local mirror automatically 
just specify the URLs as found when browsing on the download server
e.g. in the folder https://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/
there is the URL
https://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi

simply trying to download that will get redirected automatically by the CDN to a (hopefully local) mirror.

example with wget:

```
---request begin---
GET /libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi HTTP/1.1
Host: download.documentfoundation.org
User-Agent: Wget/1.21.2
Accept: */*
Accept-Encoding: identity
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 302 Found
Date: Tue, 14 Mar 2023 18:04:05 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 414
Connection: keep-alive
Server: Apache
X-MirrorBrain-Mirror: mirrors.up.pt
X-MirrorBrain-Realm: region
Link: <http://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi.meta4>; rel=describedby; type="application/metalin                                                                        k4+xml"
Link: <http://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi.asc>; rel=describedby; type="application/pgp-signa                                                                        ture"
Link: <http://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi.torrent>; rel=describedby; type="application/x-bit                                                                        torrent"
Link: <https://mirrors.up.pt/tdf/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi>; rel=duplicate; pri=1; geo=pt
Link: <https://ftp.bme.hu/pub/mirrors/tdf/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi>; rel=duplicate; pri=2; geo=hu
Link: <https://tdf.mirror.liteserver.nl/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi>; rel=duplicate; pri=3; geo=nl
Link: <https://ftp.snt.utwente.nl/pub/software/tdf/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi>; rel=duplicate; pri=4; geo=nl
Link: <https://tdf.jensgutermuth.de/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi>; rel=duplicate; pri=5; geo=de
Digest: MD5=ESykXIqRmH5nx4/wut0yLw==
Digest: SHA=qyFoYiU8aOpnJU0rQhfyqIaRc6o=
Digest: SHA-256=bpALkOq2jrn5wLgV5WmE3tx7Jv/UwijS8snzLyOoLgk=
Location: https://mirrors.up.pt/tdf/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi

---response end---

```

**Comment by krystofkrticka** [comment]
well downloadarchive also redirects to correct mirror but only some times so yes it'll be best if I change links to cdn version

**Comment by krystofkrticka** [comment]
@denelon @R-Adrian #99477

**Comment by R-Adrian** [comment]
> well downloadarchive also redirects to correct mirror but only some times so yes it'll be best if I change links to cdn version

TheDocumentFoundation has mirror support for files on the downloadarchive too, but due the size of the files to be mirrored only servers involved in the testing of builds are mirroring - it's basically a testing bed for the 'live' CDN.

example: if you look at the upcoming 'testing' build of LibreOffice  7.5.2 you'll see some mirrors for testing
https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.2.1/win/x86_64/LibreOffice_7.5.2.1_Win_x86-64.msi.mirrorlist

but if you look at the list of mirrors for the current 'stable' version ... there are no other mirrors for downloadarchive so it has to serve that itself.
https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.1.2/win/x86_64/LibreOffice_7.5.1.2_Win_x86-64.msi.mirrorlist

**Comment by krystofkrticka** [comment]
Now I'm thinking what should we do after this is version 7.5.1 surpassed by version 7.5.2 on CDN. Should we change links back to downloadarchive because right now it's imposible to prevent 404s without support for alternate (fallback) URL

**Comment by krystofkrticka** [comment]
@R-Adrian BTW I already created PR to fix this issue.

**Comment by krystofkrticka** [comment]
> > well downloadarchive also redirects to correct mirror but only some times so yes it'll be best if I change links to cdn version
> 
> TheDocumentFoundation has mirror support for files on the downloadarchive too, but due the size of the files to be mirrored only servers involved in the testing of builds are mirroring - it's basically a testing bed for the 'live' CDN.
> 
> example: if you look at the upcoming 'testing' build of LibreOffice 7.5.2 you'll see some mirrors for testing https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.2.1/win/x86_64/LibreOffice_7.5.2.1_Win_x86-64.msi.mirrorlist
> 
> but if you look at the list of mirrors for the current 'stable' version ... there are no other mirrors for downloadarchive so it has to serve that itself. https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.1.2/win/x86_64/LibreOffice_7.5.1.2_Win_x86-64.msi.mirrorlist

Oh thanks I didn't know this. Because when I created this manifest the mirror list still had mirrors in it.
