### ISSUE TITLE
[Package Issue]: Microsoft.Office hash mismatch

### ISSUE THREAD

**Issue by dropbobbytables** [microsoft/winget-pkgs#99507]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match.
wget https://officecdn.microsoft.com/pr/wsus/setup.exe
winget hash .\setup.exe
InstallerSha256: 64b853226c83d5c971b18099aa89fb8e4c944317337b0e88b5e7561111e4bf85

Old hash: 8cd8255aa6aeb0b02bc5d9cd6c417368de39f57f191bf41f480c5eb68749b917

### Steps to reproduce

winget upgrade Microsoft.Office
or
winget install Microsoft.Office

### Actual behavior

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

To update/install Office

### Environment

```shell
Windows: Windows.Desktop v10.0.19044.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by mdanish-kh** [comment]
Close with reason: Fixed in #99864;
