### ISSUE TITLE
[Package Issue]: ShiningLight.OpenSSL

### ISSUE THREAD

**Issue by jmigual** [microsoft/winget-pkgs#99634]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The installer shows an update for the openssl package and it only reports the version 1.0.0 installed but I already have the latest one

### Steps to reproduce

1. `winget install openssl`
2. `winget upgrade` shows the issue

### Actual behavior

OpenSSL is shown as not updated

### Expected behavior

OpenSSL should not be shown as not updated

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1344
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/6493651/225565655-a40a648f-2658-4c4f-b79c-1ceaf721f059.png)

**Comment by Trenly** [comment]
What happens if you run `winget list OpenSSL` ?

**Comment by cnEUL** [comment]
yes, i have the same issue.

**Comment by Jackaed** [comment]
I have the same issue.

**Comment by NicolaIsotta** [comment]
OpenSSL Light is affected too
![image](https://github.com/microsoft/winget-pkgs/assets/18428155/62bb7097-4b41-423a-b413-a374168c59ea)

**Comment by cnEUL** [comment]
yes also on my update.

**Comment by Marcuse7** [comment]
This is related to #38249 . It seems like a mix-up of the installer package version and the product version to be installed.

**Comment by luzpaz** [comment]
Can the title of the ticket be less generic ?

**Comment by treysis** [comment]
Can we just remove the whole ShiningLight.OpenSSL manifests until Shining Light devs change their mind about their MSI packaging script with the awful 1.0.0?

**Comment by treysis** [comment]
I removed `ShiningLight.OpenSSL` entirely so this can be closed.
