### ISSUE TITLE
[Package Issue]: Microsoft.PowerShell.Preview 7.4.1.0 - wrong version

### ISSUE THREAD

**Issue by Andrej730** [microsoft/winget-pkgs#99631]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Brief description of your issue

Powershell Preview 7.4.0.1 added to winget packages as 7.4.1.0 which is a bit confusing - shouldn't it be 7.4.0.1?
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PowerShell/Preview/7.4.1.0/Microsoft.PowerShell.Preview.installer.yaml

Similar thing with upcoming PR #99498

It could be an issue if 7.4.1 will actually come out

**Comment by denelon** [comment]
@anamnavi is this intentional?

**Comment by mdanish-kh** [comment]
The reason is that MSIX installers report a different version to registry than the MSI ones. The two versions are separated as:

- PackageVersion is set to `7.4.1.0` as that is what MSIX installers write to registry
- DisplayVersion field `7.4.0.1` is used for the MSI ones

Since the MSIX installers are a temporary solution for the ARM systems (the pwsh team is working on MSI installers for arm architecture), I would say we use PackageVersion field according to the MSI installers and the marketing version i.e., `7.4.0.1` and use DisplayVersion field for the MSIX ones.

**Comment by mdanish-kh** [comment]
> Similar thing with upcoming PR https://github.com/microsoft/winget-pkgs/pull/99498

This was resolved in commit https://github.com/microsoft/winget-pkgs/pull/99498/commits/cd3ce1f949f36fe16f7b2f0c9eb7635e2e4e8367 by @anamnavi in the latest PR.

I've created PRs to fix the version in previous manifets. 
cc @anamnavi to please review these PRs:
- #99811
- #99812
- #99813
- #99814

**Comment by anamnavi** [comment]
@mdanish-kh yes that captures our scenario accurately since we are temporarily specifying MSIX installers until we have msi installer for arm.

So we would use `7.4.0.1` as the PackageVersion field. Where/how would we specify `7.4.1.0` for the msix installer?

**Comment by mdanish-kh** [comment]
I realized we can't set PackageVersion according to the MSI installers (if we also have the MSIX in the manifest) as the validation pipelines were updated to compare the version retrieved from the MSIX against the PackageVersion set in the manifest. If the versions don't match, we get https://github.com/microsoft/winget-pkgs/labels/Manifest-Installer-Validation-Error ![](https://user-images.githubusercontent.com/88161975/226061416-56bc3f42-9e30-4d3c-80b3-619fb59c56c8.png)

As MSIX installers don't support `AppsAndFeaturesEntries`, I think we are forced to use MSIX version as the PackageVersion and use DisplayVersion for MSI until we have MSI installers for the arm architecture as well.

cc @denelon / @Trenly if they have a better solution in mind

**Comment by mdanish-kh** [comment]
Close with reason: PowerShell Preview manifests all have consistent PackageVersions now;
