### ISSUE TITLE
[Package Request]: Carapace

### ISSUE THREAD

**Issue by Araxeus** [microsoft/winget-pkgs#99770]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/rsteube/carapace-bin/releases/latest
Publisher: @rsteube
Package Name: Carapace
Description: multi-shell multi-command argument completer 
Package Version: v0.22.0
Installer URL: https://github.com/rsteube/carapace-bin/releases/download/v0.23.0/carapace-bin_windows_amd64.zip

**Comment by Trenly** [comment]
![image](https://user-images.githubusercontent.com/12611259/225942947-77d2ca8f-eb05-4bfd-a142-ec12021388c5.png)

Blocked by https://github.com/microsoft/winget-cli/issues/2899

**Comment by rsteube** [comment]
@Trenly changed it to `zip`

**Comment by Araxeus** [comment]
@Trenly can you remove the `blocked` tag?

**Comment by ItzLevvie** [comment]
[Policy] reset feedback
