### ISSUE TITLE
Upgrade keep appearing Resplendence.WhySoSlow

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-pkgs#99784]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

It look like winget is having some critical bug. I check all the setup file is correct in the place. I already have the latest version but why it still offering the same update
winget upgrade -u

Name                   Id                                             Version     Available Source
--------------------------------------------------------------------------------------
WhySoSlow 1.61 Resplendence.WhySoSlow Unknown  1.61      winget
1 upgrades available.

### Steps to reproduce

winget upgrade -u 

### Actual behavior

It does not do anything with the installer and it just reinstalling the program. I also have the latest version of Resplendence.WhySoSlow 

### Expected behavior

Stop offering the updates. Offering update when there is newer version release.

### Environment

```raw
winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2728
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
This is due to Resplendence not writing the version of the application to the `DisplayVersion` key in the registry. Since you are on winget 1.4, this package should only be upgraded when using the `--include-unknown-versions` flag.

The only way to fix this is for the publisher to update their installer to set the Display Version

**Comment by BrandonWanHuanSheng** [comment]
Yes, It look like the installer did not write the key value "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WhySoSlowHome_is1|Value|DisplayVersion"
