### ISSUE TITLE
[Update Request]: How to change the Identifier of a package

### ISSUE THREAD

**Issue by GeoffreyChen777** [microsoft/winget-pkgs#99791]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

GeoffreyChen.Paperlib

### Package Version

2.2.0

### Please describe the changes you would like to see

Wish to change to FutureScholars.Paperlib

**Comment by Trenly** [comment]
I don't see version 2.2.0 existing in the repository yet. Therefore, to change the identifier there are 2 options -
1) Move all versions of `GeoffreyChen.Paperlib` to `FutureScholars.Paperlib`
2) Create a version 2.2.0 for `GeoffreyChen.Paperlib` and include `AppsAndFeaturesEntries` which are inaccurate, and then add a version 2.2.0 for `FutureScholars.Paperlib` and include `AppsAndFeaturesEntries` which are accurate. This will cause people on `GeoffreyChen.Paperlib 2.1.5` to be upgraded to `GeoffreyChen.Paperlib 2.2.0`, and then the matching logic will detect it as `FutureScholars.Paperlib 2.2.0` after the upgrade

**Comment by GeoffreyChen777** [comment]
option 1 would be fine .

**Comment by mdanish-kh** [comment]
@SpecterShell has moved all of the versions from `GeoffreyChen.Paperlib` to `FutureScholars.Paperlib`
